### ISSUE TITLE
REPL hangs at startup on windows

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#9242] opened 2014-12-03 18:28 UTC
I have noticed that Julia 0.3.3 REPL sometimes hangs at startup on windows se: 
![image](https://cloud.githubusercontent.com/assets/7973946/5286150/3294c7ca-7b22-11e4-8fa0-f6d7ae6886a2.png)
I have seen this on my own computer and some of my colleagues.

**Comment by axsk** [comment] 2015-01-20 15:10
I am experiencing the same problem for months now. 
It seems to happen randomly, around 1 out of 8 times here. 
The CPU stays around 25% and memory usage is constant 86MB (whereas a fresh working instance has around 97MB).

I am running Version 0.4.0-dev+2249 (x86_64-w64-mingw32) on Windows 8. It occurs when starting from cygwin as well as from the native cmd shell.

**Comment by tkelman** [comment] 2015-01-21 05:59
@axsk is this while you're running some calculation, or immediately on startup?

**Comment by axsk** [comment] 2015-01-21 14:50
immediately on startup, as in the screenshot above

**Comment by tkelman** [comment] 2015-01-21 14:52
Hmm, thanks. @dhoegh has this happened to you recently? Are you also on Windows 8 by any chance?

**Comment by dhoegh** [comment] 2015-01-21 14:55
It has happened recently, but I would probably say 1/20 startups. I am on Windows 7.

**Comment by tkelman** [comment] 2015-01-21 14:59
If it's always on x86_64, then this could potentially be an alternate manifestation of #7942, not sure.

**Comment by dhoegh** [comment] 2015-01-21 15:15
I and my colleagues have only  x86_64 so it is possible.

**Comment by tkelman** [comment] 2015-01-21 15:20
32-bit Julia runs just fine in 64 bit Windows. If you have the disk space and the time and wouldn't mind trying out 32-bit Julia for a little while, it would be interesting to see whether or not you ever encounter the same issue there.

**Comment by axsk** [comment] 2015-01-22 12:26
I am now trying the 32-bit version, and had no freeze so far (around 20 starts so far).
Interestingely the REPL starts up around 7 times so fast:
0.8s (32bit) compared to 5.8s (64bit)
Should I open a new issue for this?

**Comment by tkelman** [comment] 2015-01-22 15:56
Thanks for collecting that info. Are you using the nightlies or release? Is there a sys.dll file under lib/julia?

> so maybe it is connected to IO or something like that?

I think @ihnorton had a theory that there might be some race condition somewhere between libuv and codegen, so possibly.

**Comment by axsk** [comment] 2015-01-22 16:33
I am now using the nightlies from today.

**Comment by tkelman** [comment] 2015-01-22 16:43
Oh right, I never reverted Jameson's commit that put sys.dll back into the 32-bit nightlies, only on release-0.3. So you'll get faster startup with sys.dll, but backtraces will probably be missing line numbers and file names. If you want line numbers and file names in your backtraces, you can delete or rename sys.dll. Hopefully we'll fix all this before 0.4.0 gets released, so you don't have to choose one or the other.

**Comment by dhoegh** [comment] 2015-05-31 16:43
I have now observed this on master to:(
![image](https://cloud.githubusercontent.com/assets/7973946/7902769/ec05789c-07c4-11e5-9739-c326f3379593.png)

**Comment by Mike43110** [comment] 2015-06-01 15:06
I have experienced this on 0.3 and master too.

Very rarely and only on Haswell in my experience. I have not experienced it on my Ivy-Bridge box at all.

**Comment by tkelman** [comment] 2015-06-02 16:38
I feel like this might be the same underlying issue as #7942 and probably not REPL-related at all.

**Comment by tkelman** [comment] 2015-07-02 21:46
closing as dupe of #7942

**Closed by tkelman** 2015-07-02 21:46 UTC
Labels: REPL, windows
