### ISSUE TITLE
v0.6.2 stable fails to build due to pcre location change

### ISSUE THREAD

**Issue by mdcfrancis** [JuliaLang/julia#27058] opened 2018-05-10 17:07 UTC
Requires back port from master 

diff --git a/deps/pcre.mk b/deps/pcre.mk
index bdc784d..cb4a45d 100644
--- a/deps/pcre.mk
+++ b/deps/pcre.mk
@@ -5,7 +5,7 @@ PCRE_CFLAGS := -O3
 PCRE_LDFLAGS := $(RPATH_ESCAPED_ORIGIN)
 
 $(SRCDIR)/srccache/pcre2-$(PCRE_VER).tar.bz2: | $(SRCDIR)/srccache
-       $(JLDOWNLOAD) $@ https://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-$(PCRE_VER).tar.bz2
+       $(JLDOWNLOAD) $@ https://ftp.pcre.org/pub/pcre/pcre2-$(PCRE_VER).tar.bz2
 
 $(SRCDIR)/srccache/pcre2-$(PCRE_VER)/source-extracted: $(SRCDIR)/srccache/pcre2-$(PCRE_VER).tar.bz2

**Comment by mbauman** [comment] 2018-05-10 17:14
Duplicate of #26936. Just requires a new release, which is in progress.

**Closed by mbauman** 2018-05-10 17:14 UTC
