### ISSUE TITLE
fix USE_GPL_LIBS

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#13060] opened 2015-09-11 00:51 UTC
#12766 was reverted.

**Comment by tkelman** [comment] 2015-09-15 07:48
Reading libgit2's gpl exception, we either need to disable its build and test for non-gpl builds or link an executable to it.

**Comment by vtjnash** [comment] 2015-09-18 00:18
wow, that libgit2 license clause is a bit nuts (https://github.com/libgit2/libgit2/blob/master/COPYING):
```
			LINKING EXCEPTION

 In addition to the permissions in the GNU General Public License,
 the authors give you unlimited permission to link the compiled
 version of this library into combinations with other programs,
 and to distribute those combinations without any restriction
 coming from the use of this file.  (The General Public License
 restrictions do apply in other respects; for example, they cover
 modification of the file, and distribution when not linked into
 a combined executable.)
```

**Comment by StefanKarpinski** [comment] 2015-09-18 00:21
It's a bit odd, but I don't think it poses a problem for us, does it?

**Comment by tkelman** [comment] 2015-09-18 00:22
We're not linking libgit2 into a combined executable right now. So it would make a difference for a non-GPL build of Julia. An optional build flag does not exactly qualify as legal advice however.

**Comment by StefanKarpinski** [comment] 2015-09-18 00:25
What are we doing with it then?

**Comment by tkelman** [comment] 2015-09-18 00:39
Right now, just putting it in the binaries (and doing a trivial version test) because we can and because #11196 is imminent. We could take it out but it's not very big and we have other GPL deps.

Once Pkg is using it though, we'll be ccall'ing into it.

**Comment by StefanKarpinski** [comment] 2015-09-18 00:47
So the problem is that we're doing *less* than linking it? I don't think that doing less than linking even counts as creating a derived work.

**Comment by tkelman** [comment] 2015-09-18 00:53
shared address space? complex internal data structures?
https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#MereAggregation

**Comment by vtjnash** [comment] 2015-09-18 00:57
currently, we are just bundling it with the binaries, so "mere aggregation"? apparently that was not a situation the license author had anticipated, because the license otherwise sounds exceptionally generous ("unlimited permission").

**Comment by wildart** [comment] 2015-09-18 01:00
It is clear that any linking to `libgit2` which we do in #11196 fall under the licence exception.

**Comment by tkelman** [comment] 2015-09-18 01:02
Yeah I think we're okay right now on this but once we're using it we may need to come up with a workaround to satisfy the conditions of the exception more explicitly, or ask upstream for a clarification, for non-GPL Julia builds.

**Comment by JeffBezanson** [comment] 2015-09-18 01:06
Since we are currently not using it *at all*, the license is not relevant.
Should we worry about the license of every library we don't use? Is this a
build system, or some absurdist theater piece?

**Comment by StefanKarpinski** [comment] 2015-09-18 01:42
Oo, oo! I vote for absurdist theater piece. I love those.

**Comment by ScottPJones** [comment] 2015-09-18 01:49
Doesn't seem like any problem to me - we aren't *modifying* libgit2, and we are just going to link to it (and I don't think it matters if it is static or dynamic linking), so the linking exception holds.
At least in my former life, we used these sorts of libraries all the time, dynamically linked, as long as they had the linking exception or LGPL, and we didn't modify them.

**Comment by StefanKarpinski** [comment] 2015-09-18 02:01
Yeah, I don't see what the issue with this is. Even if we modify libgit2, we'll be publishing those changes, so we'd still be complying.

**Comment by tkelman** [comment] 2015-09-18 18:12
So should we close this with #13118? (backported in #13182)

**Comment by stevengj** [comment] 2015-09-25 16:09
That looks like a typical [GPL linking exception](https://en.wikipedia.org/wiki/GPL_linking_exception).   It basically makes the license more permissive than the LGPL, so I don't see why it would be a problem even for the non-GPL build, because it means that no restrictions are imposed on the licensing of other components.

The FSF's legal counsel has consistently (and persuasively — every violator has backed down from testing this in court) maintained that there is no legal difference between linking statically or dynamically, all other things being equal.  (See e.g. [here](http://www.gnu.org/licenses/gpl-faq.en.html#NFUseGPLPlugins).)   So, once we are actually using libgit2 in 0.5, we are effectively "linking it into a combined executable" and the exception applies.

**Closed** 2015-09-29 06:22 UTC
Labels: regression
