### ISSUE TITLE
Feature request: QR factorization updates

### ISSUE THREAD

**Issue by bdeonovic** [JuliaLang/julia#20791] opened 2017-02-24 20:46 UTC
QR update, QR insert, and QR delete 

It would be nice to be able to update a QR factorization. The library that octave uses is here: 

https://sourceforge.net/projects/qrupdate/

for reference. This will allow stuff like quickly updating a LM or GLM model when adding more observations.

**Comment by andreasnoack** [comment] 2017-02-24 20:53
Notice that this is already possible for Cholesky (with `LinAlg.lowrankupdate`) and that might be sufficient for LMs. For GLMs, I don't think an updated QR will help you much since all the observations are typically reweighted in each iteration.

**Comment by stevengj** [comment] 2017-02-24 21:02
This is also useful for Anderson acceleration of fixed-point solvers.

**Comment by bdeonovic** [comment] 2017-02-24 21:04
@andreasnoack  Sorry, I'm not actually interested in using QR updates for LM or GLM, I just thought others might be interested in those applications.

**Comment by Sacha0** [comment] 2017-07-17 04:26
Ref. #2929. Best!

**Comment by nrontsis** [comment] 2019-02-22 10:59
Isn't this a duplicate of #2929 (task 3/3)?

**Comment by ViralBShah** [comment] 2019-02-22 13:08
Yes, dup and best to implement in a package given the binary dependency. Could also be a gsoc project.

**Closed by ViralBShah** 2019-02-22 13:08 UTC
Labels: help wanted, linear algebra

**Comment by ChrisRackauckas** [comment] 2019-02-22 13:10
and this has been done in packages, I think https://github.com/pkofod/Anderson.jl is the right repo to look at (qrtools.jl, at least that's part of it @pkofod ?)

**Comment by nrontsis** [comment] 2019-02-22 14:00
Thanks @ChrisRackauckas. I think that the link you mention only implements a specific case (*delete* the *leftmost* column of the matrix under factorization).

I have implemented arbitrary deletion as well as the functionality to also add columns in [`GeneralQP.jl`](https://github.com/oxfordcontrol/GeneralQP.jl#updatable-factorizations) (see the `UpdatableQR` struct in [src/linear_algebra.jl](https://github.com/oxfordcontrol/GeneralQP.jl/blob/master/src/linear_algebra.jl)).

The caveat is that `UpdatableQR` is not an ''economical'' factorisation, in the sense that all the columns of Q are stored explicitly. In contrast [`qrupdate`](http://qrupdate.sourceforge.net) has methods for updating the factorisation in both economical and full form.

Nevertheless the `UpdatableQR` struct of `GeneralQP.jl` and the Q-less approach of [`QRupdate.jl`](https://github.com/mpf/QRupdate.jl) might cover quite a few use cases.

**Comment by ChrisRackauckas** [comment] 2019-02-22 14:02
Thanks! We'll definitely use this in our Anderson acceleration methods. @devmotion @kanav99

**Comment by devmotion** [comment] 2019-02-22 16:03
For Anderson acceleration we only need those special cases (deleting the left-most column and adding one on the right), so it seems we could use a simpler implementation than the one in https://github.com/oxfordcontrol/GeneralQP.jl/blob/master/src/linear_algebra.jl that is tuned and optimized better towards our needs. I tried to achieve this in https://github.com/JuliaNLSolvers/NLsolve.jl/pull/210.

The Q-less approach was discussed in https://github.com/JuliaNLSolvers/NLsolve.jl/issues/128 but seems to square the conditioning.

**Comment by pkofod** [comment] 2019-02-22 17:02
Yes, my stuff is  specifically for our needs, Good to see something more general
