### ISSUE TITLE
AnnotatedString: wrong join() result with other string types

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#55198] opened 2024-07-21 20:21 UTC
In both 1.11rc and nightly:
```julia
julia> using InlineStrings

julia> a = Base.AnnotatedString("annotated", [(1:9, :label => 1)])

julia> b = InlineString("abc")

# correct:
julia> a * b
"annotatedabc"

# wrong:
julia> join([a,b])
"annotated\x03cba"

# correct:
julia> join([String(a), b])
"annotatedabc"
```

**Comment by KristofferC** [comment] 2024-07-25 10:24
I think this is a bug in InlineStrings:

```
using InlineStrings
str = InlineString("abc")
iob = IOBuffer()
write(iob, str)
String(take!(iob))
# "\x03cba"
```

This https://github.com/JuliaStrings/InlineStrings.jl/blob/bf772fb62ac3b75e3422baaa8d9f8bc5e79254e1/src/InlineStrings.jl#L317 should use `sizeof(x)` not `sizeof(T)`.

**Comment by KristofferC** [comment] 2024-07-25 10:30
https://github.com/JuliaStrings/InlineStrings.jl/pull/83 should fix this.

**Comment by KristofferC** [comment] 2024-07-25 10:39
```julia
julia> using InlineStrings

julia> str = Base.AnnotatedString(InlineString("abc"))
"abc"

julia> sprint(print, str)
"\x03cba"
```

The problem is that AnnotatedStrings thinks that `print` and `write` are the same thing:

https://github.com/JuliaLang/StyledStrings.jl/blob/43fb018ed528d3b1b84c4bdb4ad682f20f0f7e7c/src/io.jl#L255-L256C6

**Comment by tecosaur** [comment] 2024-07-25 11:27
This is fixed in https://github.com/JuliaLang/StyledStrings.jl/pull/66, I'll let tests run then merge + bump + backport.

**Comment by tecosaur** [comment] 2024-08-11 13:51
#55461 updates the version of StyledStrings to include the fix.

**Closed** 2024-09-08 10:42 UTC
