### ISSUE TITLE
Something wrong with Debugger.jl

### ISSUE THREAD

**Issue by karen-sy** [JuliaLang/julia#37981] opened 2020-10-10 21:18 UTC
Debugger.jl is throwing strange issues on a very simple example. When I attempt debugging on the command-line, the debugger doesn't stop on the breakpoint. When I attempt using the debugger pane (on atom), I get the below error, and Julia is automatically terminated.
(edit: is Debugger.jl connected to Juno's debugger? I find it strange that both are failing .)

I've tried uninstall/reinstalling the Debugger package, but the error is persistent. 

Thanks.

Here's the code:
```
using Debugger

function main() # MAIN function
    print("entered MAIN function \n")
    x = 3
    @bp
    print("hello!")
end

#@enter main()
@run main()

```

Here is the issue:
```Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2193822 -- getindex at .\array.jl:809 [inlined]
isslotempty at .\dict.jl:170 [inlined]
ht_keyindex at .\dict.jl:286
in expression starting at none:1
getindex at .\array.jl:809 [inlined]
isslotempty at .\dict.jl:170 [inlined]
ht_keyindex at .\dict.jl:286
get at .\dict.jl:490 [inlined]
#prepare_framecode#35 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\construct.jl:163
prepare_framecode##kw at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\construct.jl:152
unknown function (ip: 00000000021943E8)
#prepare_call#38 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\construct.jl:261
prepare_call##kw at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\construct.jl:249 [inlined]
#get_call_framecode#59 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\localmethtable.jl:63
get_call_framecode##kw at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\localmethtable.jl:11 [inlined]
#evaluate_call_recurse!#64 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:225
evaluate_call_recurse! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:202 [inlined]
eval_rhs at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:389
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:529
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:579
finish! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:14
finish_and_return! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:29 [inlined]
#evaluate_call_recurse!#64 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:240
evaluate_call_recurse! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:202 [inlined]
eval_rhs at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:389
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:529
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:579
finish! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:14
finish_and_return! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:29 [inlined]
#evaluate_call_recurse!#64 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:240
evaluate_call_recurse! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:202 [inlined]
eval_rhs at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:389
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:529
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:579
finish! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:14
finish_and_return! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:29 [inlined]
#evaluate_call_recurse!#64 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:240
evaluate_call_recurse! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:202 [inlined]
eval_rhs at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:389
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:529
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:579
finish! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:14
finish_and_return! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:29 [inlined]
#evaluate_call_recurse!#64 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:240
evaluate_call_recurse! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:202 [inlined]
eval_rhs at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:389
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:445
step_expr! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\interpret.jl:579
finish! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:14
finish_and_return! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:29
unknown function (ip: 00000000021C9C45)
finish_stack! at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:59
unknown function (ip: 00000000021C9B95)
#debug_command#85 at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:473
debug_command at C:\Users\karen\.julia\packages\JuliaInterpreter\CPmYX\src\commands.jl:415
unknown function (ip: 00000000021C7850)
#54 at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:153
evalscope at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:386
#startdebugging#53 at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:151
startdebugging##kw at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:137 [inlined]
inner at .\essentials.jl:713
unknown function (ip: 0000000001F1C4F3)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
jl_f__apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:669 [inlined]
jl_f__apply_latest at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:705
#invokelatest#1 at .\essentials.jl:714
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
invokelatest##kw at .\essentials.jl:709
#48 at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:113
hideprompt at C:\Users\karen\.julia\packages\Atom\ipSjf\src\repl.jl:127
#47 at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:84 [inlined]
task_local_storage at .\task.jl:226
debug_file at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:83
debug_file at C:\Users\karen\.julia\packages\Atom\ipSjf\src\debugger\stepper.jl:81
unknown function (ip: 0000000001F156B9)
handlemsg at C:\Users\karen\.julia\packages\Atom\ipSjf\src\comm.jl:169
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
do_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\builtins.c:655
#31 at .\task.jl:356
unknown function (ip: 000000001DFFDE9A)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src\task.c:707
Allocations: 85248335 (Pool: 85219814; Big: 28521); GC: 86```

**Comment by vchuravy** [comment] 2020-10-10 23:35
@karen-sy thank you for opening this issue. Looking at the stacktrace it seems to be an issue with [JuliaInterpreter.jl](https://github.com/JuliaDebug/JuliaInterpreter.jl). Can you reopen the issue there? When you open the issue there make sure that you include the output of `versioninfo()` and `Pkg.status()`.

I will close this issue since it is not directly related to Julia, but is in a library package.

**Closed by vchuravy** 2020-10-10 23:35 UTC

**Comment by timholy** [comment] 2020-10-11 07:34
Thought to be fair, this is a Julia crash, so it may come back here with a MWE. @karen-sy, when you report it there, can you please include details about your Julia version and the version of JuliaInterpreter & Debugger? I can't reproduce this on Julia 1.0, 1.5, or 1.6 and JuliaInterpreter 0.8.1.

**Comment by karen-sy** [comment] 2020-10-11 07:51
Julia 1.5.0, latest updates of Debugger and JuliaInterpreter.
I actually made the switch to VSCode from Atom/Juno just earlier and the issue resolved itself. The VSCode debugger works without error, although of course that doesn't say much about what was wrong with Debugger.jl. Julia in Atom has been buggy in compiling various packages for some reason, so the problem could've been Juno-specific. 
If you need more information, let me know and I'll do my best to be helpful.
