### ISSUE TITLE
cholesky test fails due to rank deficiency with make testall1

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#12907] opened 2015-09-01 21:44 UTC
```
tkelman@ygdesk:~/Julia/julia$ ./julia -e 'versioninfo()' && make testall1
Julia Version 0.4.0-pre+7131
Commit d4a338e* (2015-09-01 21:13 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
    JULIA test/all
     * linalg/triangular     in  89.37 seconds
     * linalg/qr             in  19.01 seconds
     * linalg/dense          in  20.91 seconds
     * linalg/matmul         in   5.62 seconds
     * linalg/schur          in   4.51 seconds
     * linalg/special        in   2.47 seconds
     * linalg/eigen          in   1.29 seconds
     * linalg/bunchkaufman   in   0.70 seconds
     * linalg/svd            in   4.46 seconds
     * linalg/lapack         in   9.94 seconds
     * linalg/tridiag        in   5.16 seconds
     * linalg/bidiag         in   7.03 seconds
     * linalg/diagonal       in   8.41 seconds
     * linalg/pinv           in   5.28 seconds
     * linalg/givens         in   1.39 seconds
     * linalg/cholesky      ERROR: LoadError: LoadError("/home/tkelman/Julia/julia/test/linalg/cholesky.jl",24,ErrorException("test failed: 2 == 10\n in expression: rank(cpapd) == n"))
 in error at ./error.jl:21
 in default_handler at test.jl:30
 in do_test at test.jl:53
 in anonymous at no file:74
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in runtests at /home/tkelman/Julia/julia/test/testdefs.jl:179
 in anonymous at multi.jl:684
 in run_work_thunk at multi.jl:645
 in remotecall_fetch at multi.jl:718
 in remotecall_fetch at multi.jl:734
 in anonymous at task.jl:1430
while loading /home/tkelman/Julia/julia/test/runtests.jl, in expression starting on line 13
```

bad luck of the random seeds when tests run in serial here?

**Comment by kshyatt** [comment] 2015-09-01 23:09
I can't reproduce on OSX. I'll try on `julia.mit.edu`.

**Comment by andreasnoack** [comment] 2015-09-03 12:30
I can't reporduce either. @tkelman do you get this consistently?

**Comment by tkelman** [comment] 2015-09-03 12:36
Every time. I've been pulling and re-making consistently since it started happening, has not gone away. On Ubuntu 14.04, nothing in `Make.user`, no local changes (versioninfo only says it's dirty due to a bunch of untracked files lying around).

**Comment by KristofferC** [comment] 2015-09-03 12:41
I can not reproduce:

```
Julia Version 0.4.0-pre+7143
Commit d950841* (2015-09-02 11:27 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment] 2015-09-03 12:55
Probably related to the old processor architecture. Forcing openblas and/or LLVM to use an older instruction set might make this possible to reproduce on newer systems?

**Comment by tkelman** [comment] 2015-09-04 06:44
I can reproduce this on my sandy bridge win64 laptop via `OPENBLAS_CORETYPE=Penryn make testall1`. Can other people try the same?

**Comment by IainNZ** [comment] 2015-09-07 05:15
Reproduced on
```
julia> versioninfo()
Julia Version 0.4.0-pre+7304
Commit b3a1be5 (2015-09-05 13:59 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by kshyatt** [comment] 2015-09-07 05:36
According to @tkelman this is fixed with latest OpenBLAS dev version.

**Comment by tkelman** [comment] 2015-09-07 05:37
cc @xianyi

**Comment by tkelman** [comment] 2015-09-07 08:35
There's some really strange interplay between `cholfact` and the Julia RNG here, so now I'm not so sure what's going on. Is something reading from uninitialized memory maybe? Try running the following script with `OPENBLAS_CORETYPE=Penryn`:
```
using Base.Test
n = 10
srand(1234321)
areal = randn(n,n)/2
aimg  = randn(n,n)/2
a2real = randn(n,n)/2
a2img  = randn(n,n)/2
breal = randn(n,2)/2

for eltya in (Float32, Float64)
    a = convert(Matrix{eltya}, areal)
    apd  = a'*a                  # symmetric positive-definite
    εa = eps(abs(float(one(eltya))))
    κ     = cond(apd, 1) #condition number
    b = rand(1:5, n, 2)
    εb = eps(abs(float(one(Int))))
    ε = max(εa,εb)
    lpapd = cholfact(apd, :L, Val{true})
    @test norm(apd * (lpapd\b[1:n]) - b[1:n])/norm(b[1:n]) <= ε*κ*n

    @test 10 == rank(cholfact(Complex{Float32}[5.8525753f0 + 0.0f0im -0.79540455f0 + 0.7066077f0im 0.98274714f0 + 1.3824869f0im 2.619998f0 + 1.8532984f0im -1.8306153f0 - 1.2336911f0im 0.32275113f0 + 0.015575029f0im 2.1968813f0 + 1.0640624f0im 0.27894387f0 + 0.97911835f0im 3.0476584f0 + 0.18548489f0im 0.3842994f0 + 0.7050991f0im
                 -0.79540455f0 - 0.7066077f0im 8.313246f0 + 0.0f0im -1.8076122f0 - 0.8882447f0im 0.47806996f0 + 0.48494184f0im 0.5096429f0 - 0.5395974f0im -0.7285097f0 - 0.10360408f0im -1.1760061f0 - 2.7146957f0im -0.4271084f0 + 0.042899966f0im -1.7228563f0 + 2.8335886f0im 1.8942566f0 + 0.6389735f0im
                 0.98274714f0 - 1.3824869f0im -1.8076122f0 + 0.8882447f0im 9.367975f0 + 0.0f0im -0.1838578f0 + 0.6468568f0im -1.8338387f0 + 0.7064959f0im 0.041852742f0 - 0.6556877f0im 2.5673025f0 + 1.9732997f0im -1.1148382f0 - 0.15693812f0im 2.4704504f0 - 1.0389464f0im 1.0858271f0 - 1.298006f0im
                 2.619998f0 - 1.8532984f0im 0.47806996f0 - 0.48494184f0im -0.1838578f0 - 0.6468568f0im 3.1117508f0 + 0.0f0im -1.956626f0 + 0.22825956f0im 0.07081801f0 - 0.31801307f0im 0.3698375f0 - 0.5400855f0im 0.80686307f0 + 1.5315914f0im 1.5649154f0 - 1.6229297f0im -0.112077385f0 + 1.2014246f0im
                 -1.8306153f0 + 1.2336911f0im 0.5096429f0 + 0.5395974f0im -1.8338387f0 - 0.7064959f0im -1.956626f0 - 0.22825956f0im 3.6439795f0 + 0.0f0im -0.2594722f0 + 0.48786148f0im -0.47636223f0 - 0.27821827f0im -0.61608654f0 - 2.01858f0im -2.7767487f0 + 1.7693765f0im 0.048102796f0 - 0.9741874f0im
                 0.32275113f0 - 0.015575029f0im -0.7285097f0 + 0.10360408f0im 0.041852742f0 + 0.6556877f0im 0.07081801f0 + 0.31801307f0im -0.2594722f0 - 0.48786148f0im 3.624376f0 + 0.0f0im -1.6697118f0 + 0.4017511f0im -1.4397877f0 - 0.7550918f0im -0.31456697f0 - 1.0403451f0im -0.31978557f0 + 0.13701046f0im
                 2.1968813f0 - 1.0640624f0im -1.1760061f0 + 2.7146957f0im 2.5673025f0 - 1.9732997f0im 0.3698375f0 + 0.5400855f0im -0.47636223f0 + 0.27821827f0im -1.6697118f0 - 0.4017511f0im 6.8273163f0 + 0.0f0im -0.10051322f0 + 0.24303961f0im 1.4415971f0 + 0.29750675f0im 1.221786f0 - 0.85654986f0im
                 0.27894387f0 - 0.97911835f0im -0.4271084f0 - 0.042899966f0im -1.1148382f0 + 0.15693812f0im 0.80686307f0 - 1.5315914f0im -0.61608654f0 + 2.01858f0im -1.4397877f0 + 0.7550918f0im -0.10051322f0 - 0.24303961f0im 3.4057708f0 + 0.0f0im -0.5856801f0 - 1.0203559f0im 0.7103452f0 + 0.8422135f0im
                 3.0476584f0 - 0.18548489f0im -1.7228563f0 - 2.8335886f0im 2.4704504f0 + 1.0389464f0im 1.5649154f0 + 1.6229297f0im -2.7767487f0 - 1.7693765f0im -0.31456697f0 + 1.0403451f0im 1.4415971f0 - 0.29750675f0im -0.5856801f0 + 1.0203559f0im 7.005772f0 + 0.0f0im -0.9617417f0 - 1.2486815f0im
                 0.3842994f0 - 0.7050991f0im 1.8942566f0 - 0.6389735f0im 1.0858271f0 + 1.298006f0im -0.112077385f0 - 1.2014246f0im 0.048102796f0 + 0.9741874f0im -0.31978557f0 - 0.13701046f0im 1.221786f0 + 0.85654986f0im 0.7103452f0 - 0.8422135f0im -0.9617417f0 + 1.2486815f0im 3.4629636f0 + 0.0f0im],
        :U, Val{true}))
end
```

I'm seeing the failure occur the second time through the for loop, but not the first, for the same input data.

**Comment by andreasnoack** [comment] 2015-09-07 14:09
I can confirm this now with `OPENBLAS_CORETYPE=Penryn`. I can reduce your script to
```jl
using Base.Test
n = 10
areal = randn(n,n)/2
tmp = 0
for eltya in (Float32, Float64)
    a = convert(Matrix{eltya}, areal)
    apd  = a'*a                  # symmetric positive-definite
    b = ones(n, 2)
    lpapd = cholfact(apd, :L, Val{true})
    apd * (lpapd\b[1:n])

    tmp = Complex{Float32}[5.8525753f0 + 0.0f0im -0.79540455f0 + 0.7066077f0im 0.98274714f0 + 1.3824869f0im 2.619998f0 + 1.8532984f0im -1.8306153f0 - 1.2336911f0im 0.32275113f0 + 0.015575029f0im 2.1968813f0 + 1.0640624f0im 0.27894387f0 + 0.97911835f0im 3.0476584f0 + 0.18548489f0im 0.3842994f0 + 0.7050991f0im
                 -0.79540455f0 - 0.7066077f0im 8.313246f0 + 0.0f0im -1.8076122f0 - 0.8882447f0im 0.47806996f0 + 0.48494184f0im 0.5096429f0 - 0.5395974f0im -0.7285097f0 - 0.10360408f0im -1.1760061f0 - 2.7146957f0im -0.4271084f0 + 0.042899966f0im -1.7228563f0 + 2.8335886f0im 1.8942566f0 + 0.6389735f0im
                 0.98274714f0 - 1.3824869f0im -1.8076122f0 + 0.8882447f0im 9.367975f0 + 0.0f0im -0.1838578f0 + 0.6468568f0im -1.8338387f0 + 0.7064959f0im 0.041852742f0 - 0.6556877f0im 2.5673025f0 + 1.9732997f0im -1.1148382f0 - 0.15693812f0im 2.4704504f0 - 1.0389464f0im 1.0858271f0 - 1.298006f0im
                 2.619998f0 - 1.8532984f0im 0.47806996f0 - 0.48494184f0im -0.1838578f0 - 0.6468568f0im 3.1117508f0 + 0.0f0im -1.956626f0 + 0.22825956f0im 0.07081801f0 - 0.31801307f0im 0.3698375f0 - 0.5400855f0im 0.80686307f0 + 1.5315914f0im 1.5649154f0 - 1.6229297f0im -0.112077385f0 + 1.2014246f0im
                 -1.8306153f0 + 1.2336911f0im 0.5096429f0 + 0.5395974f0im -1.8338387f0 - 0.7064959f0im -1.956626f0 - 0.22825956f0im 3.6439795f0 + 0.0f0im -0.2594722f0 + 0.48786148f0im -0.47636223f0 - 0.27821827f0im -0.61608654f0 - 2.01858f0im -2.7767487f0 + 1.7693765f0im 0.048102796f0 - 0.9741874f0im
                 0.32275113f0 - 0.015575029f0im -0.7285097f0 + 0.10360408f0im 0.041852742f0 + 0.6556877f0im 0.07081801f0 + 0.31801307f0im -0.2594722f0 - 0.48786148f0im 3.624376f0 + 0.0f0im -1.6697118f0 + 0.4017511f0im -1.4397877f0 - 0.7550918f0im -0.31456697f0 - 1.0403451f0im -0.31978557f0 + 0.13701046f0im
                 2.1968813f0 - 1.0640624f0im -1.1760061f0 + 2.7146957f0im 2.5673025f0 - 1.9732997f0im 0.3698375f0 + 0.5400855f0im -0.47636223f0 + 0.27821827f0im -1.6697118f0 - 0.4017511f0im 6.8273163f0 + 0.0f0im -0.10051322f0 + 0.24303961f0im 1.4415971f0 + 0.29750675f0im 1.221786f0 - 0.85654986f0im
                 0.27894387f0 - 0.97911835f0im -0.4271084f0 - 0.042899966f0im -1.1148382f0 + 0.15693812f0im 0.80686307f0 - 1.5315914f0im -0.61608654f0 + 2.01858f0im -1.4397877f0 + 0.7550918f0im -0.10051322f0 - 0.24303961f0im 3.4057708f0 + 0.0f0im -0.5856801f0 - 1.0203559f0im 0.7103452f0 + 0.8422135f0im
                 3.0476584f0 - 0.18548489f0im -1.7228563f0 - 2.8335886f0im 2.4704504f0 + 1.0389464f0im 1.5649154f0 + 1.6229297f0im -2.7767487f0 - 1.7693765f0im -0.31456697f0 + 1.0403451f0im 1.4415971f0 - 0.29750675f0im -0.5856801f0 + 1.0203559f0im 7.005772f0 + 0.0f0im -0.9617417f0 - 1.2486815f0im
                 0.3842994f0 - 0.7050991f0im 1.8942566f0 - 0.6389735f0im 1.0858271f0 + 1.298006f0im -0.112077385f0 - 1.2014246f0im 0.048102796f0 + 0.9741874f0im -0.31978557f0 - 0.13701046f0im 1.221786f0 + 0.85654986f0im 0.7103452f0 - 0.8422135f0im -0.9617417f0 + 1.2486815f0im 3.4629636f0 + 0.0f0im]

    @test 10 == rank(cholfact(tmp,
        :U, Val{true}))
end
```
but not further. `tmp` is just stored for convenience. If I call the factorization on `tmp` with `U` afterwards I continue to get the error, but a single call with `L` and the `U` version works, i.e.
```jl
julia> include("../Desktop/testchol.jl")
ERROR: LoadError: test failed: 10 == 4
 in expression: 10 == rank(cholfact(tmp,:U,Val{true}))
 in error at ./error.jl:21
 in default_handler at test.jl:28
 in do_test at test.jl:53
 in anonymous at no file:23
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
while loading /Users/andreasnoack/Desktop/testchol.jl, in expression starting on line 5

julia> LAPACK.pstrf!('U', triu(tmp), eps())[3]
4

julia> LAPACK.pstrf!('L', triu(tmp), eps())[3]
10

julia> LAPACK.pstrf!('U', triu(tmp), eps())[3]
10
```
I would expect this to be a problem with OpenBLAS accessing out of bounds memory on Penryn.

**Comment by tkelman** [comment] 2015-09-07 14:35
Yeah, by taking away a few extra lines the result changed from rank 2 to rank 4. Since this doesn't happen on the latest develop branch of openblas, that is consistent with an uninitialized memory bug upstream. Since we don't have a newer release than 0.2.14 to use, we might need to do a bisect on openblas to pinpoint what the fix was, try to carry a local patch.

**Comment by tkelman** [comment] 2015-09-08 11:25
I bisected this to https://github.com/xianyi/OpenBLAS/commit/fd9fd42936736a3fd111e958a2d495cdcac89a42 - that commit fixes the issue. That commit by itself doesn't apply cleanly to 0.2.14, but it does if the immediate parent commit (https://github.com/xianyi/OpenBLAS/commit/97984819797bb7385ecf90f1b0b553cf3a476bdb) is cherry-picked too. That should probably be less risky than asking if upstream could tag 0.2.15 soon and upgrading to it - would want to get more testing in when we do that.

**Comment by tkelman** [comment] 2015-09-08 20:29
@kshyatt you had recently hit what looked like a related issue with nan's showing up in the factorization even on more recent processors when the cholesky tests were run in a different order, right? Can you post a diff that reproduces that error?

**Comment by kshyatt** [comment] 2015-09-08 20:43
https://github.com/JuliaLang/julia/pull/12870 it was the `chol` tests here. Keeping the test inside the inner loop triggered the failure.

**Comment by tkelman** [comment] 2015-09-08 21:10
Looks like the rebased-out commit that failed was b512505cacc69fd1ba2cf04ecca79cee587a4cfd ? But on Travis it only failed on OSX? Did you do anything special to get it to reproduce on julia.mit, or was it intermittent?

**Comment by kshyatt** [comment] 2015-09-08 21:10
It only failed with the specific `srand` seed.

**Closed** 2015-10-29 07:19 UTC
Labels: linear algebra, test, upstream
