### ISSUE TITLE
Better documentation standards for optional arguments 

### ISSUE THREAD

**Issue by mbeltagy** [JuliaLang/julia#18318] opened 2016-09-01 08:47 UTC
I believe we need better standards for documenting optional arguments. In the manual I sometimes see it as

```
foo(arg [,optional_arg])
```

So maybe we need to have that for all optional arguments in the help docs, instead of the often ambiguous

```
foo(arg, [optional_arg])
```

That latter maybe confused for an array.

**Comment by nalimilan** [comment] 2016-09-01 08:55
Currently, the only reference is the manual: http://docs.julialang.org/en/latest/manual/documentation/ It advises the `f(x[, y])` form, but that's quite recent so the existing docstrings don't really follow this rule.

An issue is that it's quite heavy when there are several optional arguments: `f(x[, y[, z]])`. Not sure what to do about it.

**Comment by tkelman** [comment] 2016-09-01 09:31
I think we should stop using square brackets for this and favor using the actual Julia syntax for optional inputs most places. If there are multiple signatures not implemented via trailing defaults, we can just list the signatures on separate lines.

**Comment by nalimilan** [comment] 2016-09-01 10:05
Might work. One would need to go over Base and see how it looks in practice.

**Comment by stevengj** [comment] 2016-09-05 20:11
Duplicate of #4902.

**Comment by fredrikekre** [comment] 2017-05-26 20:17
Close as dup?

**Closed** 2017-05-26 20:19 UTC
Labels: doc, docsystem
