### ISSUE TITLE
Support first and last of CartesianIndex

### ISSUE THREAD

**Issue by cossio** [JuliaLang/julia#35804] opened 2020-05-08 13:16 UTC
```
julia> last(CartesianIndex(1, 1, 2))
ERROR: MethodError: no method matching lastindex(::CartesianIndex{3})
Closest candidates are:
  lastindex(::Markdown.MD) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Markdown/src/parse/parse.jl:26
  lastindex(::Base64.Buffer) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Base64/src/buffer.jl:19
  lastindex(::Cmd) at process.jl:639
  ...
Stacktrace:
 [1] last(::CartesianIndex{3}) at ./abstractarray.jl:362
 [2] top-level scope at REPL[30]:1

julia> first(CartesianIndex(1, 1, 2))
ERROR: iteration is deliberately unsupported for CartesianIndex. Use `I` rather than `I...`, or use `Tuple(I)...`
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] iterate(::CartesianIndex{3}) at ./multidimensional.jl:164
 [3] first(::CartesianIndex{3}) at ./abstractarray.jl:341
 [4] top-level scope at REPL[35]:1
```

Is there some reason why

```julia
lastindex(::CartesianIndex{N}) where {N} = N
first(i::CartesianIndex) = i[1]
```

are not defined?

**Comment by mbauman** [comment] 2020-05-08 13:49
Duplicate of #31815

**Closed by mbauman** 2020-05-08 13:49 UTC
