### ISSUE TITLE
Git working directory is immediately dirty on a fresh clone

### ISSUE THREAD

**Issue by noisebrain** [JuliaLang/julia#28241] opened 2018-07-23 19:51 UTC
Hello,

a fresh checkout of 0.6.4 (also 0.6.3) does not seem to work

```
git clone https://github.com/JuliaLang/julia.git && \
>     cd julia && \
>     git checkout v0.6.4
Cloning into 'julia'...
remote: Counting objects: 776410, done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 776410 (delta 89), reused 166 (delta 55), pack-reused 776197
Receiving objects: 100% (776410/776410), 417.71 MiB | 2.31 MiB/s, done.
Resolving deltas: 100% (563696/563696), done.
Checking connectivity... done.
error: Your local changes to the following files would be overwritten by checkout:
	contrib/vagrant/Vagrantfile
	doc/images/jltypes.ai
	doc/src/assets/logo.png
Please, commit your changes or stash them before you can switch branches.
Aborting

```

**Comment by ararslan** [comment] 2018-07-23 22:54
So this is kind of bizarre:
```
[15:49:34] alex:test $ git clone https://github.com/JuliaLang/julia.git
Cloning into 'julia'...
remote: Counting objects: 776665, done.
remote: Compressing objects: 100% (141/141), done.
remote: Total 776665 (delta 220), reused 381 (delta 160), pack-reused 776184
Receiving objects: 100% (776665/776665), 418.10 MiB | 9.82 MiB/s, done.
Resolving deltas: 100% (563818/563818), done.
Checking connectivity... done.
[15:50:50] alex:test $ cd julia 
[15:51:03] alex:julia git:(master*) $ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   contrib/mac/app/julia.icns
	modified:   contrib/vagrant/.gitignore
	modified:   contrib/vagrant/README.md
	modified:   contrib/vagrant/Vagrantfile
	modified:   contrib/windows/7zS.sfx
	modified:   contrib/windows/julia.ico
	modified:   deps/libdSFMT.def
	modified:   doc/images/github_metadata_develbranch.png
	modified:   doc/images/github_metadata_fork.png
	modified:   doc/images/github_metadata_pullrequest.png
	modified:   doc/images/jltypes.ai
	modified:   doc/images/jltypes.svg
	modified:   doc/images/travis-icon.png
	modified:   doc/src/assets/logo.png

no changes added to commit (use "git add" and/or "git commit -a")
```
The working directory is already dirty immediately after cloning. The reported issue is merely a symptom of this.

**Comment by StefanKarpinski** [comment] 2018-07-24 04:50
Could it have something to do with LF settings? cc @keno

**Comment by vtjnash** [comment] 2018-07-24 17:00
Yes, that sounds quite strongly plausible.

**Comment by davidanthoff** [comment] 2018-07-24 18:46
I wonder whether this is related to https://github.com/JuliaLang/julia/pull/27291... What git versions are you running? I found [this](https://github.com/git/git/blob/master/Documentation/RelNotes/2.10.0.txt#L248), not sure whether it applies.

I actually can't reproduce this issue on either Windows or Ubuntu, but I have pretty recent git versions on both.

**Comment by noisebrain** [comment] 2018-07-24 18:58
The problem appears with git 2.7.4 on linux (ubuntu16) and git 2.15.2 on Mac

**Comment by noisebrain** [comment] 2018-07-24 19:00
Though, was able to successfully check out julia0.6.3 on the linux machine about 2 weeks ago, no changes to git version or other things during that time afaik

**Comment by davidanthoff** [comment] 2018-07-24 20:14
Could you try to update your git on linux to something newer and see whether it still appears?

There was apparently a bug fixed in git 2.10 that might explain this.

Of course it is still a mystery then why things don't work for you on Mac...

**Comment by noisebrain** [comment] 2018-07-24 21:36
On linux, updating via the package manager (sudo apt-get install --only-upgrade git) reports
"git is already the newest version (1:2.7.4-0ubuntu1.4)"

I briefly tried building git 2.18 from source, but it did not compile.

I am not sure if the bug in 2.10 is related, because I was able to use 2.7.4 successfully
about two weeks ago (cloned and built julia0.6.3 on the same linux machine, no
changes on the machine since then that I am aware of)

Anyway I will also try building 2.11 or so

**Comment by noisebrain** [comment] 2018-07-24 22:37
I tried checking out an older versions of two of the "modified" files, to see what the differences actually are, did not see any (same checksum).  The .png files that git notes as modifed can also be opened in a viewer.

Maybe this is related:

```
git diff doc/src/assets/logo.png
warning: CRLF will be replaced by LF in doc/src/assets/logo.png.
The file will have its original line endings in your working directory.
diff --git a/doc/src/assets/logo.png b/doc/src/assets/logo.png
index b18f64c..413e97a 100644
Binary files a/doc/src/assets/logo.png and b/doc/src/assets/logo.png differ
```

**Closed** 2018-07-26 16:48 UTC
