### ISSUE TITLE
LoadError with --inline=no

### ISSUE THREAD

**Issue by jhasse** [JuliaLang/julia#10238] opened 2015-02-18 16:55 UTC
When using [GLFW.jl](https://github.com/JuliaGL/GLFW.jl) (`Pkg.add("GLFW")`) and callbacks, it only works with `--inline=yes`. Example code:

```julia
import GLFW

GLFW.Init()
window = GLFW.CreateWindow(1, 1, "")
GLFW.SetWindowSizeCallback(window, (_, width, height) -> println(""))
```
Which works fine except when `--inline=no` is set:

```
~ julia --inline=no test.jl 
INFO: loaded GLFW 3.0.4 X11 GLX glXGetProcAddress clock_gettime /dev/js shared from /home/jhasse/.julia/v0.4/GLFW/deps/usr64/lib/libglfw
ERROR: LoadError: type Void has no field callbacks
 in SetWindowSizeCallback at /home/jhasse/.julia/v0.4/GLFW/src/util.jl:34
 in SetWindowSizeCallback at /home/jhasse/.julia/v0.4/GLFW/src/util.jl:44
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403
while loading /home/jhasse/test.jl, in expression starting on line 5
```

I'm sorry I can't figure out where exactly it goes wrong as I don't quite understand what is happening inside `util.jl`. Maybe @jayschwa knows more.

**Comment by pao** [comment] 2015-02-18 17:19
Which Julia version?

**Comment by jhasse** [comment] 2015-02-19 01:13
julia version 0.4.0-dev+3399

**Comment by pao** [comment] 2015-02-19 01:34
Might this be related to Void/Nullable/null/Undef/something else that changed recently in the nothingness department, @JeffBezanson?

**Comment by jayschwa** [comment] 2015-02-19 02:02
Sorry for the complexity of that macro in util.jl. If I have some time in the next few days, I'll try to reproduce and boil it down to a kernel.

**Comment by timholy** [comment] 2015-02-19 02:28
There are many closed issues about `--inline=no`, but it seems that they have been fixed (https://github.com/JuliaLang/julia/issues/9536). I'm not sure when +3399 is from, but it's possible you may want to upgrade. If not fixed, then you have a new one...

**Comment by jhasse** [comment] 2015-02-19 23:50
Just tried master (154076eedae2b17ff22df76e2954a5e43997ed3b): Not fixed :(

**Comment by jayschwa** [comment] 2015-02-21 06:28
I boiled down the problem and devised a simple test:
``` julia
using Base.Test

obj = "some object"
ptr_void = pointer_from_objref(obj)
ptr_type = convert(Ptr{typeof(obj)}, ptr_void)

x = unsafe_pointer_to_objref(ptr_void)
@test typeof(x) == typeof(obj)
@test x == obj

x = unsafe_pointer_to_objref(ptr_type)
@test typeof(x) == typeof(obj)
@test x == obj
```
`unsafe_pointer_to_objref` normally returns `obj` regardless if the given pointer is `Void` or typed. However, when given a typed pointer when `--inline=no`, `unsafe_pointer_to_objref` returns `nothing`. This causes a failure in GLFW.jl at https://github.com/JuliaGL/GLFW.jl/blob/master/src/glfw3.jl#L294 since the `ccall` is defined as returning a typed pointer.

**Comment by vtjnash** [comment] 2015-02-22 03:01
this seems likely to be fixed by https://github.com/JuliaLang/julia/pull/9986, when the codepath taken by that function is changed from an intrinsic to a ccall

**Comment by jakebolewski** [comment] 2015-04-01 22:48
This works for me now, please respond if this is still an issue.

**Closed by jakebolewski** 2015-04-01 22:48 UTC
Labels: bug
