### ISSUE TITLE
Default values for macros

### ISSUE THREAD

**Issue by hayd** [JuliaLang/julia#9627] opened 2015-01-05 20:46 UTC
The following syntax doesn't work for macros (but does for functions):

```jl
julia> macro foo(a, b::Bool=true)
          a, b
       end
ERROR: syntax: "(kw (:: b Bool) #t)" is not a valid function argument name

julia> function foo(a, b::Bool=true)  #works for functions
          a, b
       end
foo (generic function with 2 methods)

julia> foo(1)
(1,true)
```

**Comment by ihnorton** [comment] 2015-01-06 05:41
Seems unnecessary IMHO  (varargs work fine), but I guess it is arguably more consistent. The error message could at least be improved.

**Comment by JeffBezanson** [comment] 2015-01-06 06:50
This is basically a duplicate of #8846.

**Closed** 2016-01-05 15:51 UTC
Labels: decision, parser
