### ISSUE TITLE
[release-0.6] TypedPolynomial print causes SIGILL

### ISSUE THREAD

**Issue by fgerick** [JuliaLang/julia#39335] opened 2021-01-20 17:36 UTC
Playing around with 1.6.0-beta on MacOS I ran into this:

```julia
using TypedPolynomials
@polyvar x y
[x,y,0]
```

when the REPL tries to print the Vector:

```
3-element Vector{Term{Int64, Monomial{(x, y), 2}}}:

signal (4): Illegal instruction: 4
in expression starting at none:0
_zip_iterate_all at ./iterators.jl:361 [inlined]
iterate at ./iterators.jl:351 [inlined]
_show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:64
_show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:98 [inlined]
show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:13 [inlined]
show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:20
unknown function (ip: 0x16474189f)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#sprint#384 at ./strings/io.jl:103
unknown function (ip: 0x16473e6aa)
sprint##kw at ./strings/io.jl:101 [inlined]
alignment at ./show.jl:2528 [inlined]
alignment at ./arrayshow.jl:68
unknown function (ip: 0x16473e3a2)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
_print_matrix at ./arrayshow.jl:201
jfptr__print_matrix_19876.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
do_apply at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
jl_f__apply_latest at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:707 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
print_matrix at ./arrayshow.jl:170 [inlined]
print_matrix at ./arrayshow.jl:170 [inlined]
print_array at ./arrayshow.jl:327 [inlined]
show at ./arrayshow.jl:368
unknown function (ip: 0x16473b078)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#38 at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:220
jfptr_YY.38_54434.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
with_repl_linfo at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:462
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
display at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:213
display at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:225
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
display at ./multimedia.jl:328
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
do_apply at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
jl_f__apply_latest at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:707 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
print_response at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:247
#40 at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:231
jfptr_YY.40_54549.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
with_repl_linfo at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:462
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
print_response at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:229
do_respond at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:798
unknown function (ip: 0x164736c14)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
do_apply at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
jl_f__apply_latest at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:707 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
run_interface at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2441
jfptr_run_interface_53490.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
run_frontend at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1126
#44 at ./task.jl:406
jfptr_YY.44_53690.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
start_task at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
Allocations: 4752381 (Pool: 4751109; Big: 1272); GC: 5
Illegal instruction: 4
```

```
versioninfo()
Julia Version 1.6.0-beta1
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

```
(@v1.6) pkg> status TypedPolynomials MultivariatePolynomials
Status `~/.julia/environments/v1.6/Project.toml`
  [102ac46a] MultivariatePolynomials v0.3.12
  [afbbf031] TypedPolynomials v0.2.8
```

**Comment by fgerick** [comment] 2021-01-20 17:38
also works with `x+y`:

```
julia> x+y
x
signal (4): Illegal instruction: 4
in expression starting at none:0
_zip_iterate_all at ./iterators.jl:361 [inlined]
iterate at ./iterators.jl:351 [inlined]
_show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:64
_show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:98
_show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:122
show at /Users/felixger/.julia/packages/MultivariatePolynomials/bsuXE/src/show.jl:13
unknown function (ip: 0x15cbc76af)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#38 at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:220
jfptr_YY.38_54434.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
with_repl_linfo at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:462
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
display at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:213
display at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:225
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
display at ./multimedia.jl:328
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
do_apply at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
jl_f__apply_latest at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:707 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
print_response at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:247
#40 at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:231
jfptr_YY.40_54549.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
with_repl_linfo at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:462
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
print_response at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:229
do_respond at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:798
unknown function (ip: 0x15cbbc2b4)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
do_apply at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
jl_f__apply_latest at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:707 [inlined]
invokelatest at ./essentials.jl:706 [inlined]
run_interface at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2441
jfptr_run_interface_53490.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
run_frontend at /Users/julia/src/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1126
#44 at ./task.jl:406
jfptr_YY.44_53690.clone_1 at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
start_task at /Applications/Julia-1.6.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.6.dylib (unknown line)
Allocations: 6953308 (Pool: 6951174; Big: 2134); GC: 8
Illegal instruction: 4
```

**Comment by JeffBezanson** [comment] 2021-01-20 21:51
Looks like a duplicate of #39219

**Closed** 2021-01-21 05:20 UTC
