### ISSUE TITLE
A way to list accessible names

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#53483] opened 2024-02-26 20:51 UTC
In this [Discourse thread](https://discourse.julialang.org/t/get-all-names-accessible-from-a-module/98492) it is argued that there's no public way to get all the names accessible from a module including the names that became accessible via `using`.

For example `names(Main; all=true, imported=true)` doesn't return `@chain`.

```jl
julia> using Chain

julia> names(Chain)
2-element Vector{Symbol}:
 Symbol("@chain")
 :Chain

julia> names((@__MODULE__); all=true, imported=true)
8-element Vector{Symbol}:
 Symbol("##meta#58")
 :Base
 :Chain
 :Core
 :InteractiveUtils
 :Main
 :eval
 :include
```

I would like a way to get this list.

**Comment by ericphanson** [comment] 2024-02-27 01:21
Xref https://github.com/JuliaLang/julia/pull/42092

**Comment by lgoettgens** [comment] 2024-02-27 11:58
Duplicate of https://github.com/JuliaLang/julia/issues/36529

**Closed** 2024-02-27 12:07 UTC
