### ISSUE TITLE
large broadcasting overhead on small subarray

### ISSUE THREAD

**Issue by johnnychen94** [JuliaLang/julia#45510] opened 2022-05-30 06:21 UTC
```julia
function mapf!(f, out, A, B)
    @inbounds @simd for i in eachindex(out, A, B)
        out[i] = f(A[i], B[i])
    end
    return out
end

function mapf_broadcast!(f, out, A, B)
    @. out = f(A, B)
end

A, B = rand(64, 64), rand(64, 64)
out = similar(A)

@btime mapf!(max, view($out, :, 1), view($A, :, 1), view($B, :, 1)); # 16.011 ns (0 allocations: 0 bytes)

@btime mapf_broadcast!(max, view($out, :, 1), view($A, :, 1), view($B, :, 1));
# 1.6.5: 202.272 ns (9 allocations: 528 bytes)
# 1.7.3: 187.501 ns (9 allocations: 528 bytes)
# 1.8.0-beta3: 204.926 ns (5 allocations: 336 bytes)
# 1.9.0-DEV.647: 78.541 ns (3 allocations: 240 bytes)
```

For larger columns, the overhead still exists but is much smaller.

```julia
A, B = rand(4096, 4), rand(4096, 4)
out = similar(A)

@btime mapf!(max, view($out, :, 1), view($A, :, 1), view($B, :, 1)); # 1.037 μs (0 allocations: 0 bytes)
@btime mapf_broadcast!(max, view($out, :, 1), view($A, :, 1), view($B, :, 1));
# 1.8.0-beta3: 1.279 μs (5 allocations: 336 bytes)
# 1.9.0-DEV.647: 1.158 μs (3 allocations: 240 bytes)
```

**Comment by giordano** [comment] 2022-05-30 07:48
Duplicate of #28126?

**Closed** 2022-05-30 08:26 UTC
Labels: performance, arrays, broadcast
