### ISSUE TITLE
Type inference of constructors with known marginals

### ISSUE THREAD

**Issue by mschauer** [JuliaLang/julia#10207] opened 2015-02-15 12:34 UTC
In the following example, the constructor gets inferred as returning `T{A, B}`, and not `T{Int, B}` and the known type of the `a`-coordinate gets lost .

```
type T{A, B}
    a::A
    b::B
end
println(code_typed(T, (Int, Any)))
```

**Comment by vtjnash** [comment] 2015-02-16 01:55
can you explain why this is a problem? actual dispatch on the type signature `(Int,Any)` is impossible since `Any` is not a concrete leaf type

**Comment by mschauer** [comment] 2015-02-16 08:38
In a hopefully not to contrieved example, ``f`` should be typestable
```
immutable BaseKVector{K, T}
    x::Vector{T}
end
BaseKVector{T}(v::Vector{T}, K) = BaseKVector{K, T}(v)
BaseKVector{K1,T}(v::BaseKVector{K1,T}, K2) = BaseKVector{K2, T}(v.x)
indexrange{K}(v::BaseKVector{K}) = K : length(v.x) + K

f(x) = indexrange(BaseKVector(x, 1))

println(code_typed(BaseKVector, (BaseKVector, Int)))
println(code_typed(f, (Vector{Int},)))
```

**Comment by JeffBezanson** [comment] 2015-03-07 05:04
Similar to #5560, but more expensive since I think it would depend on re-running type inference after inlining. The problem is that, for obvious reasons, we have to generally avoid specializing functions for different *values* of arguments.

**Comment by JeffBezanson** [comment] 2017-04-07 23:42
The example in the OP is fixed now. We should add a test.

**Closed** 2017-04-10 21:18 UTC
Labels: inference, types and dispatch
