### ISSUE TITLE
Julia multithreading @threads macro

### ISSUE THREAD

**Issue by Kon19893** [JuliaLang/julia#33671] opened 2019-10-25 10:24 UTC
Dear Julia Team,

I am trying to multi-thread my code and i noticed that the @threads macro requires to set the environmental variable JULIA_NUM_THREADS. As it is stated, this cannot be done within the julia script itself, which is greatly inconvenient (as i have to either create an other script that 1st changes the environmental variable and then calls julia script, change the .exe file of julia or manually change the environmental variable each time i use the script).
Is there any solution to this problem so we can automate the multi-threaded scripts?

Kind Regards,
Konstantinos.

**Comment by fredrikekre** [comment] 2019-10-25 10:41
Duplicate of #16134

**Closed by fredrikekre** 2019-10-25 10:41 UTC
