### ISSUE TITLE
'make test' fails for julia-1.10.7

### ISSUE THREAD

**Issue by sergstesh** [JuliaLang/julia#56810] opened 2024-12-12 10:18 UTC
I downloaded the source tarball from https://github.com/JuliaLang/julia/releases/download/v1.10.7/julia-1.10.7-full.tar.gz
 , unpacked the tarball the usual way, did 'cd julia-1.10.7' and then invoked 'nice -n 19 make test 1>make_test.log 2>&1' command.

Output of 'versioninfo()':

```
julia> versioninfo()
Julia Version 1.10.7
Commit 4976d05258 (2024-11-26 15:57 UTC)
Build Info:

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) N100
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)

julia> 

```
.

See the uploaded 'make_test.log' file for actual failuers: [make_test.log](https://github.com/user-attachments/files/18109574/make_test.log) .

Pay special attention to the fact that julia-1.10.7 is an LTS release, and the linear algebra bug reported by me a long time ago is still there.

**Comment by vchuravy** [comment] 2024-12-12 10:30
Please make it easier to help you. These kinds of generic issues are not really useful for us.
An issue should be focused on let's say "Blas issue on Goldmont" and then instead of opening a new issue every few weeks,
you can check in and say "this still fails for me on 1.10.7", but a new issue for every version makes it challenging to keep track of the discussion and a "mega issue" like this causes the discussion to be not focused on one single issue, but rather leads to confusing discussion, and it is unclear whether the issue has been solved or not. It also makes it impossible for anyone else to find the issue since the "log" files are not indexed by search.

Duplicate of #54234

**Closed by vchuravy** 2024-12-12 10:30 UTC

**Comment by sergstesh** [comment] 2024-12-12 10:38
> Please make it easier to help you

First have a look into the log file - there other than linear algebra test failure issues. When looking into the log file, search case-insensitive the 'fail' substring.
