### ISSUE TITLE
better error message for readdlm on directories

### ISSUE THREAD

**Issue by gasagna** [JuliaLang/julia#11484] opened 2015-05-29 09:39 UTC
Hi, 

It took me a few minutes of headache to understand why 

``` julia
readdlm("I-typed-a-directory-instead-of-a-file-path")
```

gives 

``` julia
memory mapping failed: No such device
while loading In[37], in expression starting on line 1

 in mmap at mmap.jl:35
 in mmap_array at mmap.jl:110
 in mmap_array at mmap.jl:4
 in anonymous at datafmt.jl:64
 in open at /usr/bin/../lib/julia/sys.so
 in as_mmap at datafmt.jl:63
 in readdlm_auto at datafmt.jl:55
 in readdlm at datafmt.jl:49
 in readdlm at datafmt.jl:46
```

Probably a better error handling in these cases would help.

Davide

**Comment by KristofferC** [comment] 2017-05-26 21:03
```
julia> readdlm("I-typed-a-directory-instead-of-a-file-path")
ERROR: SystemError: opening file I-typed-a-directory-instead-of-a-file-path: No such file or directory
```

**Comment by tkelman** [comment] 2017-05-26 21:18
closed by what?

**Comment by KristofferC** [comment] 2017-05-26 21:20
Yeah, this was an accident. The issue is still as originally described.

**Closed** 2017-08-07 19:05 UTC
Labels: error handling, Hacktoberfest, intro issue, up for grabs
