### ISSUE TITLE
Pkg.update says: "Cannot perform fast-forward merge"

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#18113] opened 2016-08-18 14:32 UTC
This is with Julia 0.6

I tagged one or two packages, and then tried to published them. This failed, likely because PkgDev couldn't properly authorize with Github. I then tagged and published the same package from Julia 0.4, where everything went fine. Now I see this in Julia 0.6:

```
julia> Pkg.update()
INFO: Updating METADATA...
WARNING: Cannot perform fast-forward merge.
```

This warning has been there for a few days. How do I avoid it? Is there a way to do this automatically, or do I need to low-level git repo management? Would a hard git reset to the upstream master branch be appropriate, or can this lose data? (I would reset only the metadata repo, leaving my packages alone.)

I am making this an issue instead of a question on the mailing list because I think that tagging and publishing should be mainstream (not expert) actions, and Pkg and PkgDev should handle common error conditions automatically, or if not, should at least detect them and point to respective documentation.

**Comment by tkelman** [comment] 2016-08-19 03:50
you need to look at the git status to see what's wrong. impossible to guess.

**Comment by eschnett** [comment] 2016-08-19 13:59
`git pull` said everything was fine. `git status` said a rebase was in progress, and suggested a command to continue that rebase. That command failed because some hashes looked different than what git expected.

I "solved" this by renaming `REQUIRES`, deleting `METADATA` and `METADATA_BRANCH`, and checking out everything anew.

**Comment by tkelman** [comment] 2016-08-19 14:10
> because some hashes looked different than what git expected.

Do you mean you had a conflict in a file? We aren't going to be able to solve those automatically, but it would be good to find out how you managed to cause it.

**Comment by eschnett** [comment] 2016-08-19 15:45
No, there were no conflicts.

I noticed that if I tag, then publish, then tag another package, then publish again, the second pull request will include the first. I assume that makes it difficult to handle things on your side, in particular if you comment on the first pull request and it needs to be modifier. This seems like a surefire way to introduce conflicts. Is there a way to keep all publish-requests strictly separate?

If publish requests are not accepted, or are modified, then there needs to be a way for me to undo a publish request locally. One option would be to locally "forget" a publish request when a pull request has been opened. The packages remain tagged, but I won't be able to make use of this information in `Pkg.update()` until the publish request has been granted (merged). This way, my local state of things remains consistent with upstream.

Is that what you mean?

Alternatively, I'll have to learn what is going on behind the scenes (with my package repos and with `METADATA`), and manage things manually. Is there a write-up with sufficient detail for this?

**Comment by tkelman** [comment] 2016-08-19 15:59
> I noticed that if I tag, then publish, then tag another package, then publish again, the second pull request will include the first. I assume that makes it difficult to handle things on your side, in particular if you comment on the first pull request and it needs to be modifier. This seems like a surefire way to introduce conflicts. Is there a way to keep all publish-requests strictly separate?

Right, this is a long-standing issue in the way Pkg.tag (now PkgDev.tag, so this isn't really a base issue and is getting to be a duplicate of https://github.com/JuliaLang/PkgDev.jl/issues/57) works. Luckily not too many people are registering multiple packages at a time. It would be fixed by creating a new branch (`git checkout -b tagfoo`) before doing the PkgDev.tag operations, and returning to the default branch after a successful PkgDev.publish (or manual push, or I think Pkg.update will normally move you back to the default branch).

> Is there a write-up with sufficient detail for this?

If the functioning of METADATA isn't described in enough detail in the package development documentation then we should expand it. Some of this may change in Pkg3 but that's not a good reason to leave it undocumented, we'd just have to update whatever changes.

**Comment by juliohm** [comment] 2016-10-17 16:38
Every time I tag my packages and try to Pkg.update(), I get the same warning. This issue started with Julia v0.5.

**Comment by tkelman** [comment] 2016-10-17 16:45
> you need to look at the git status to see what's wrong. impossible to guess.

run `git status` inside your .julia/v0.5/METADATA

**Comment by juliohm** [comment] 2016-10-17 16:50
I did a git pull from there and it solved the issue. What I tried to say is
that the workflow of tagging and updating is always causing the warning.
The local and remote branch of METADATA diverge after the tag. My workflow
is as follows:

In Julia:
Pkg.tag("foo")

In Bash:
cd .julia/v0.5/METADATA
git push myfork_METADATA
Manually create PR

-Júlio

**Comment by tkelman** [comment] 2016-10-17 17:04
Create a new branch in metadata before you do Pkg.tag, should fix it. We should change PkgDev to do that.

**Comment by tlnagy** [comment] 2016-10-17 18:13
I ran into the same issue. I ended up making a backup of REQUIRES, deleted METADATA and ran a Pkg.update to redownload everything.

**Comment by ahwillia** [comment] 2016-10-19 17:28
I also get this issue. When I check now `git status` says that my local metadata has diverged... I think this is because I did `git pull` manually before to circumvent the problem and now I have a local merge commit?

Would it be possible to give us a nuclear option `Pkg.update("force")` that deletes any local changes/inconsistencies?

**Comment by tkelman** [comment] 2016-10-19 18:18
Yeah we need to rearrange the order in which PkgDev does things, it should make a new branch before making or committing any local modifications, instead of touching your local copy of metadata-v2. https://github.com/JuliaLang/PkgDev.jl/issues/57. I don't think there are convenient PkgDev wrappers for a reset operation here, but could be added. Or the issue can usually be fixed from the command line with appropriate reset and/or rebase invocations.

**Comment by tlnagy** [comment] 2017-01-19 22:39
I run into this problem on a regular basis with Julia 0.5. I had to delete METADATA again to unbork it.

**Comment by Balinus** [comment] 2017-01-31 14:06
I have the same problem. Before doing anything stupid, I just wanted to know what was my options? If i delete METADATA folder, it will solve the problem?

**Comment by timholy** [comment] 2017-01-31 14:27
Does `git rebase origin/metadata-v2` help?

**Comment by Balinus** [comment] 2017-01-31 14:56
I had a strange error when trying to do `Pkg.update()`:

`unsatisfiable package requirements detected: no feasible version could be found for package: FileIO`

So, I did:
`julia> Pkg.rm("FileIO")
INFO: Removing FileIO (unregistered)` 
then:
 ```julia
Pkg.clone("FileIO")
INFO: Cloning FileIO from git://github.com/JuliaIO/FileIO.jl.git
INFO: Computing changes...
------ PkgError ------------------------ Stacktrace (most recent call last)

 [1] — clone(::String) at pkg.jl:151

 [2] — #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at dir.jl:31

 [3] — cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{String}}, ::String) at file.jl:59

 [4] — (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{String}})() at dir.jl:31

 [5] — clone(::String) at entry.jl:221

 [6] — clone(::String, ::String) at entry.jl:203

 [7] — edit(::Function, ::String) at entry.jl:30

 [8] — resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at entry.jl:476

 [9] — resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at entry.jl:495

 [10] — resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at resolve.jl:37

unsatisfiable package requirements detected: no feasible version could be found for package: ImageMagick
  (you may try increasing the value of the
   JULIA_PKGRESOLVE_ACCURACY environment variable)
```
Then, I did `Pkg.clone("ImageMagick")`, which lead to something "strange" (it removed my package I develop `ClimateTools`, rebuilt some, etc...):

```julia
julia> Pkg.clone("ImageMagick")
INFO: Cloning ImageMagick from git://github.com/JuliaIO/ImageMagick.jl.git
INFO: Computing changes...
INFO: Cloning cache of AxisArrays from https://github.com/JuliaArrays/AxisArrays.jl.git
INFO: Cloning cache of CatIndices from https://github.com/JuliaArrays/CatIndices.jl.git
INFO: Cloning cache of ComputationalResources from https://github.com/timholy/ComputationalResources.jl.git
INFO: Cloning cache of CustomUnitRanges from https://github.com/JuliaArrays/CustomUnitRanges.jl.git
INFO: Cloning cache of FFTViews from https://github.com/JuliaArrays/FFTViews.jl.git
INFO: Cloning cache of ImageAxes from https://github.com/JuliaImages/ImageAxes.jl.git
INFO: Cloning cache of ImageCore from https://github.com/JuliaImages/ImageCore.jl.git
INFO: Cloning cache of ImageFiltering from https://github.com/JuliaImages/ImageFiltering.jl.git
INFO: Cloning cache of ImageMetadata from https://github.com/JuliaImages/ImageMetadata.jl.git
INFO: Cloning cache of IndirectArrays from https://github.com/JuliaArrays/IndirectArrays.jl.git
INFO: Cloning cache of IntervalSets from https://github.com/JuliaMath/IntervalSets.jl.git
INFO: Cloning cache of MappedArrays from https://github.com/JuliaArrays/MappedArrays.jl.git
INFO: Cloning cache of OffsetArrays from https://github.com/alsam/OffsetArrays.jl.git
INFO: Cloning cache of QuadGK from https://github.com/JuliaMath/QuadGK.jl.git
INFO: Cloning cache of RangeArrays from https://github.com/JuliaArrays/RangeArrays.jl.git
INFO: Cloning cache of ShowItLikeYouBuildIt from https://github.com/JuliaArrays/ShowItLikeYouBuildIt.jl.git
INFO: Cloning cache of SimpleTraits from https://github.com/mauro3/SimpleTraits.jl.git
INFO: Cloning cache of TiledIteration from https://github.com/JuliaArrays/TiledIteration.jl.git
INFO: Installing AxisArrays v0.0.3
INFO: Upgrading Blink: v0.5.0 => v0.5.1
INFO: Upgrading BufferedStreams: v0.2.1 => v0.2.3
INFO: Upgrading Calculus: v0.1.15 => v0.2.0
INFO: Installing CatIndices v0.0.1
INFO: Upgrading ColorTypes: v0.2.12 => v0.3.0
INFO: Upgrading ColorVectorSpace: v0.1.12 => v0.2.0
INFO: Upgrading Colors: v0.6.9 => v0.7.0
INFO: Upgrading Compat: v0.11.0 => v0.14.0
INFO: Upgrading Compose: v0.4.4 => v0.4.5
INFO: Installing ComputationalResources v0.0.1
INFO: Installing CustomUnitRanges v0.0.3
INFO: Upgrading DataStructures: v0.5.1 => v0.5.2
INFO: Upgrading DiffBase: v0.0.2 => v0.0.3
INFO: Upgrading Distributions: v0.11.1 => v0.12.0
INFO: Installing FFTViews v0.0.1
INFO: Upgrading FixedPointNumbers: v0.2.1 => v0.3.0
INFO: Upgrading ForwardDiff: v0.3.3 => v0.3.4
INFO: Upgrading GR: v0.18.0 => v0.19.0
INFO: Upgrading Gadfly: v0.5.2 => v0.5.3
INFO: Upgrading HDF5: v0.7.2 => v0.7.3
INFO: Installing ImageAxes v0.1.0
INFO: Installing ImageCore v0.1.1
INFO: Installing ImageFiltering v0.1.1
INFO: Installing ImageMetadata v0.1.1
INFO: Upgrading ImageView: v0.2.0 => v0.3.0
INFO: Upgrading Images: v0.5.14 => v0.6.0
INFO: Installing IndirectArrays v0.1.0
INFO: Installing IntervalSets v0.0.2
INFO: Upgrading JLD: v0.6.8 => v0.6.9
INFO: Upgrading JSON: v0.8.0 => v0.8.2
INFO: Upgrading LineSearches: v0.1.3 => v0.1.5
INFO: Installing MappedArrays v0.0.5
INFO: Upgrading MbedTLS: v0.4.2 => v0.4.3
INFO: Upgrading Media: v0.2.4 => v0.2.5
INFO: Upgrading Mux: v0.2.2 => v0.2.3
INFO: Installing OffsetArrays v0.2.12
INFO: Upgrading PDMats: v0.5.2 => v0.5.4
INFO: Upgrading PlotUtils: v0.2.0 => v0.3.0
INFO: Upgrading PositiveFactorizations: v0.0.3 => v0.0.4
INFO: Upgrading PyCall: v1.8.0 => v1.9.0
INFO: Installing QuadGK v0.1.1
INFO: Installing RangeArrays v0.1.1
INFO: Installing ShowItLikeYouBuildIt v0.0.1
INFO: Installing SimpleTraits v0.2.0
INFO: Upgrading StaticArrays: v0.1.3 => v0.1.4
INFO: Upgrading StatsBase: v0.12.0 => v0.13.0
INFO: Upgrading StatsFuns: v0.3.1 => v0.4.0
INFO: Installing TiledIteration v0.0.1
INFO: Removing ClimateTools v0.0.4
INFO: Building HttpParser
INFO: Building MbedTLS
Using system libraries...
INFO: Building Rmath
INFO: Building GR
INFO: Downloading pre-compiled GR 0.23.0 Redhat binary
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 37.4M  100 37.4M    0     0  8389k      0  0:00:04  0:00:04 --:--:-- 9584k
INFO: Building Blosc
INFO: Building HDF5
INFO: Building Cairo
INFO: Building Tk
INFO: Building Conda
INFO: Building PyCall
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/proy/.julia/v0.5/Conda/deps/usr:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-2017.0.1               |                0       128.2 MB
    numpy-1.11.3               |           py27_0         6.3 MB
    conda-4.3.8                |           py27_0         468 KB
    ------------------------------------------------------------
                                           Total:       135.0 MB

The following packages will be UPDATED:

    conda: 4.2.14-py27_0 --> 4.3.8-py27_0 
    mkl:   11.3.3-0      --> 2017.0.1-0   
    numpy: 1.11.2-py27_0 --> 1.11.3-py27_0

Fetching packages ...
mkl-2017.0.1-0 100% |####################################################################################| Time: 0:00:15   8.65 MB/s
numpy-1.11.3-p 100% |####################################################################################| Time: 0:00:00   9.07 MB/s
conda-4.3.8-py 100% |####################################################################################| Time: 0:00:00  10.30 MB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
INFO: PyCall is using /home/proy/.julia/v0.5/Conda/deps/usr/bin/python (Python 2.7.12) at /home/proy/.julia/v0.5/Conda/deps/usr/bin/python, libpython = /home/proy/.julia/v0.5/Conda/deps/usr/lib/libpython2.7
INFO: /home/proy/.julia/v0.5/PyCall/deps/deps.jl has not changed
INFO: /home/proy/.julia/v0.5/PyCall/deps/PYTHON has not changed
INFO: Package database updated
```

After these steps, everything seems to work... I guess until I begin to do some work on my package `ClimateTools` and publish the changes.

Honestly, I don't know what happened and I never had the chance to try your command @timholy

**Comment by KristofferC** [comment] 2017-05-25 23:23
Please comment if there is still a problem here.

**Closed by KristofferC** 2017-05-25 23:23 UTC
Labels: needs more info, packages
