### ISSUE TITLE
stdlib documentation "Edit on GitHub" link broken

### ISSUE THREAD

**Issue by cmichelenstrofer** [JuliaLang/julia#47553] opened 2022-11-13 19:00 UTC
The "Edit on GitHub" button in several (all?) of the documentation for the standard library points to the wrong URL. E.g. for [Test.jl](https://docs.julialang.org/en/v1/stdlib/Test/#Working-with-Test-Sets) it points to 

> `https://github.com/JuliaLang/julia/blob/master/**usr/share/julia/stdlib/v1.8/Test/docs/src/index.md`

which doesn't exist, instead of 

> `https://github.com/JuliaLang/julia/blob/master/stdlib/Test/docs/src/index.md`

I could not find where this documentation is being built or I would have tried to submit a PR for a fix.

**Comment by fredrikekre** [comment] 2022-11-13 22:28
Duplicate of #43307, https://github.com/JuliaDocs/Documenter.jl/issues/1975.

**Closed by fredrikekre** 2022-11-13 22:28 UTC
