### ISSUE TITLE
syntax error with for loop inside macro call inside function call

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#37339] opened 2020-09-01 23:35 UTC
The following gives a syntax error on master as well as 1.5:

```julia
julia> f(@m for i in 1:3
           println(i)
       end)
ERROR: syntax: missing comma or ) in argument list
Stacktrace:
 [1] top-level scope at none:1
```

Interestingly enough, it works just fine if I replace the `for` loop with a `begin`/`let`/`function`/... block. It even parses if I just wrap the `for` loop in `begin ... end` or braces.

**Comment by simeonschaub** [comment] 2020-09-02 00:19
I think I have a fix for this.

**Comment by simeonschaub** [comment] 2020-09-02 00:57
Hmm... It's a bit more difficult than I thought, since we currently allow generators inside macros inside functions, like `f(@m i for i in 1:3)`. I think to fix this, we would have to require brackets around the generator expression, which would be breaking and is currently used in https://github.com/JuliaLang/julia/blob/c3a63fc591a178837445c3243fd91dcef1f8ec0e/base/bitset.jl#L426 for example.

**Comment by JeffBezanson** [comment] 2020-09-02 17:20
Duplicate of #32182

**Closed by JeffBezanson** 2020-09-02 17:20 UTC
