### ISSUE TITLE
Type alias defs can contain parameters but they are just ignored

### ISSUE THREAD

**Issue by mauro3** [JuliaLang/julia#29533] opened 2018-10-05 10:08 UTC
Consider:
```julia
julia> Type3{X,Y,Z} = Tuple{A,B} where {A,B}                                                                                                                            
Tuple{A,B} where B where A                                                                                                                                              

julia> Type3{2,3,4}                                                                                                                                                     
ERROR: too many parameters for type                                                                                                                                     
Stacktrace:                                                                                                                                                             
 [1] top-level scope at none:0

julia> Type3{2,3}                                                                                                                                                       
Tuple{2,3}                                                                                                                                                              
```
As far as I can tell, the `{X,Y,Z}` in the type-alias definition are just ignored.  This is confusing, instead an error should be thrown.

x-ref: https://discourse.julialang.org/t/behaviour-of-nested-alias-type-parameters/15893

**Comment by JeffBezanson** [comment] 2018-10-05 15:01
Largely duplicate of #28794. However we could probably give a syntax error for `X where T` when `T` does not occur in `X`.

**Comment by StefanKarpinski** [comment] 2018-10-05 15:57
> However we could probably give a syntax error for `X where T` when `T` does not occur in `X`.

Wouldn't there still be the danger of constructing such a type non-syntactically? I guess that's a smaller surface and we could say that doing so will result in undefined behavior.

**Comment by JeffBezanson** [comment] 2018-10-05 17:15
Constructing that type non-syntactically is fine, and doesn't need to be undefined behavior.

**Closed** 2024-02-03 04:34 UTC
Labels: breaking, error handling, lowering

**Comment by vtjnash** [comment] 2024-02-03 04:35
This would be breaking to make it an error now, I and sometimes like using this to build various menageries of types. There also would still be plenty of syntactic cases such as `Union{Any, T} where T` even if it was made into a lowering error
