### ISSUE TITLE
`stack(vec_of_vecs)` for `vcat(vec_of_vecs...)`

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#21672] opened 2017-05-02 17:10 UTC
This [comes up periodically](http://stackoverflow.com/questions/43712385/converting-arrayarrayfloat64-1-1-to-arrayfloat64-2-in-julia) and it's a bit embarrassing that our official answer right now involves a inefficient splatting. We should have a function – maybe call it `stack`? – that efficiently does what `vcat(vec_of_vecs...)` does without the splatting. It should also stack in slices in different dimensions so that you can either stack slices as rows or columns, etc.

**Comment by mbauman** [comment] 2017-05-02 17:35
And return an `Array` or a custom array? Either way, there's a simple implementation here: http://stackoverflow.com/a/37488453/176071.  In this context I'd swap the index ordering so it's column-major contiguous.

**Comment by StefanKarpinski** [comment] 2017-05-02 18:03
For the base implementation, this would just convert a vector of vectors to matrices, as a specific case. I think whether it stacks in column major or row major order should probably be controlled by a dimension argument. There are generalizations one can imagine doing here.

**Comment by TotalVerb** [comment] 2017-05-03 07:01
There's a general issue with the names of reduction operations on collections of things (e.g. one-argument `join`) are sometimes different from the names of operations on things given as varargs (e.g. `string`, which is effectively a splatted-out one-argument `join`), even if they are conceptually the same operation.

Examples are:

- `maximum` (collection) vs. `max` (splat)
- `minimum` vs. `min`
- `sum` vs. `+`
- `prod` vs. `*`
- `join` vs. `string`

These are not so bad because the names are similar and standard, but `vcat` and `stack` would exacerbate the problem, because `stack` is certainly not a standard name for this operation.

In my opinion, a better name for `stack` is simply `reduce(vcat, ...)`. This is inefficient because of substantial copying, but it would not change the semantics to define a new overload of `reduce` specialized on `typeof(vcat)` so as to avoid the excessive copying, as `vcat` does presently.

**Comment by nalimilan** [comment] 2017-05-03 09:35
FWIW `stack` is already a standard term in the data frames/data table world (and not only in Julia). See [the DataTables docs](https://juliadata.github.io/DataTables.jl/stable/man/reshaping_and_pivoting.html#Reshaping-and-Pivoting-Data-1). So I'd rather use a different name -- or go with @TotalVerb's suggestion.

**Comment by dpsanders** [comment] 2017-05-03 13:31
I agree with @StefanKarpinski that we need a single-word function for this.

**Comment by Godisemo** [comment] 2017-05-03 13:37
What about `flatten`?

**Comment by kmsquire** [comment] 2017-05-03 13:38
FWIW, numpy uses `stack` for this operation.

**Comment by StefanKarpinski** [comment] 2017-05-03 21:37
`flatten` is a quite distinct operation that already exists.

**Comment by StefanKarpinski** [comment] 2017-05-03 21:43
The function `stack` could be used to mean one thing with arrays and another with data frames/tables – I don't think the operations are really at odds with each other, although IIUC the data table operation might be better called `vcat`.

**Comment by andyferris** [comment] 2017-05-03 23:40
I've been wondering if it's better to first support a "view" which you can copy, rather than the reverse process (where we have a function in `Base` which makes a contiguous copy, and later on we decide it would be nice to have a view for such an operation).

Thus, we could potentially have
```julia
m = NestedArray([[1, 2], [3, 4]]) # A 2x2 AbstractMatrix{Int} which is a "view", perhaps called `StackedArray`
copy(m) # contiguous in memory, `Matrix{Int}`. Perhaps `Array(m)` would be clearer/allow possibility for `similar` to return a nested structure.
```
and no `stack` function.

**Comment by TotalVerb** [comment] 2017-05-03 23:52
See also CatViews.jl by @ahwillia.

**Comment by nalimilan** [comment] 2017-05-04 08:05
> The function stack could be used to mean one thing with arrays and another with data frames/tables – I don't think the operations are really at odds with each other, although IIUC the data table operation might be better called vcat.

Yes, that's certainly possible. I just wanted to mention this because if other terms are available it would be better not to mix these two different operations (I wasn't aware of the Numpy precedent).

FWIW, data frames/tables already implement `vcat`, but `stack` is a a very different operation (which operates on a single data frame/table).

**Comment by StefanKarpinski** [comment] 2017-05-04 19:37
Another idea that occurred to me yesterday is to just have specialized methods for `reduce(vcat, Vector{<:Vector})` and `reduce(hcat, Vector{<:Vector})`. It doesn't generalize, but it may be sufficient. There's no reason not to have optimized methods for those specific cases anyway.

**Comment by StefanKarpinski** [comment] 2017-05-04 19:38
What does `stack` do on data frames? From the name, I would expect it to stack on data frame on top of another with the same columns.

**Comment by Godisemo** [comment] 2017-05-04 19:43
I think `stack` on dataframes is the same operation that in R is called `gather`. Correct me if i'm wrong. See [this cheat sheet](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf) from RStudio.

**Comment by nalimilan** [comment] 2017-05-04 20:11
> Another idea that occurred to me yesterday is to just have specialized methods for reduce(vcat, Vector{<:Vector}) and reduce(hcat, Vector{<:Vector}). It doesn't generalize, but it may be sufficient. There's no reason not to have optimized methods for those specific cases anyway.

Yes, that's what @TotalVerb proposed above, right?

> What does stack do on data frames? From the name, I would expect it to stack on data frame on top of another with the same columns.

This is `vcat`. `stack` rearranges rows and column in a data frame/table by creating one column for each level of a variable. It's a bit hard to describe in a few words, but see [this example](http://www.statmethods.net/management/reshape.html). That's indeed called `gather` or `melt` in the recent iterations of Hadley Wickham (from RStudio)'s R packages, but the term in base R and in Pandas is `stack`. Now that several variants of the name are commonly used, it's not very clear which terminology is the most standard though...

**Comment by andyferris** [comment] 2017-05-04 21:20
Correct me ifI'm wrong, but I thought the "stacked" form of a data frame was a bit like a sparse representation of the table, storing `(row, column, value)` tuples. (Or maybe that was called something else?)

**Comment by nalimilan** [comment] 2017-05-05 09:08
Yes, that's more or less the result of `stack`, i.e. only three columns giving variable name, level and value, and which can be converted to one column for each variable (plus the value column) using `unstack`.

**Comment by StefanKarpinski** [comment] 2017-05-05 14:06
It's rather unfortunate that we can't use `stack`, which is the most natural name for this operation because `stack` is used for an operation on data frames which is neither standard nor intuitive. I'm somewhat inclined to "take" the term and let data frames use something more natural like `gather` or `melt` for that operation. I always liked the "melt" / "cast" terminology from R's reshape2.

**Comment by nalimilan** [comment] 2017-05-05 14:30
Sure, the existence of the data frames/tables function shouldn't be a blocker if `stack` is natural in the present context. I'd need to do more research to check which of `stack`, `gather` and `melt` is the most common terminology  (and most likely to remain so in the future) for data frames. BTW, we already have `melt`, which is equivalent to `stack` but with a slightly different interface (for those interested, the original discussion is [here](https://github.com/JuliaStats/DataFrames.jl/issues/29)).

Sorry, I didn't expect my original comment to generate such a long sub-thread.

**Comment by mbauman** [comment] 2017-05-05 14:53
I'm not sure `stack` is really such an ideal name here; it's fine, but I don't think it's all that obvious or meaningful.  I was hoping to find some inspiration from the myriad of SO posts asking about this, but they almost all use verbiage like convert or transform.  I don't particularly like pigeon-holing this to just `reduce(hcat` given that it's so easy to generalize with Cartesian iteration such that the resulting size is `(size(A[1])..., size(A)...)`.

One possible alternative: `unnest`.  This makes it clear that it's operating on arrays of arrays and evokes the imagery of transforming `A[i][j]` to `A[j, i]`.

I think I'd also lean towards doing the `Array` copy in base, with a package like CatViews or GrowableArrays supporting the custom array type.

**Comment by StefanKarpinski** [comment] 2017-05-05 15:40
The term stack makes sense because you're taking a bunch of separate vectors/slices of some shape and stacking them along an axis to create a structure with the same shape but an additional "stacked" dimension. I agree that it makes less sense when you're thinking of it in terms of indices – which could arguably be a better way to think about it.

**Comment by StefanKarpinski** [comment] 2017-05-05 15:46
One way to express this could be how you'd like indices to be nested. I.e. you could write `nested(A, (2,(1,3)))` to transform `A` so that the output value is indexed as `B[j][i,k]` where, if the original input was a vector of vectors of vectors, it would be indexed as `A[i][j][k]`. Indices would implicitly be numbered and any shape of input would be allowed, so the input could be `A[i,j,k]` or `A[i][j,k]` or `A[i,j][k]` or `A[i][j][k]`.

**Comment by andyferris** [comment] 2017-05-05 21:18
The `B = nested(A, (2,(1,3)))` thing seems pretty cool. Would it return a view or a contiguous copy?

Assuming it's a view - one gotcha is that (these days) indices for different array types and dimensions could be of different types, so the `(2, (1, 3))` part may need to be recognized as a compile time constant so that `indices(B)` (and even the internals of `getindex`, if different indices use different types of `Integer`) is type stable. E.g. Perhaps in the end you want to create a `NestedArray{T, 3, (2, (1, 3))} <: AbstractArray{T, 3}`) or something, a bit like how `PermutedDimsArray` stores the permutation as a type parameter (I'm now looking at it's outer constructor [here](https://github.com/JuliaLang/julia/blob/master/base/permuteddimsarray.jl#L42) and wondering if it is type stable?).

> I think I'd also lean towards doing the `Array` copy in base, with a package like CatViews or GrowableArrays supporting the custom array type.

Right, this functionality seems perfect for being developed upon outside of `Base` and merged when we all like the API. To support custom indices, perhaps `dense` (or `full`) would be a good generic way to go from the (nested) view to the (stacked) copy? (unless we are happy to have `similar` always drop the nesting, in which case `copy` is natural).

**Comment by StefanKarpinski** [comment] 2017-05-08 14:03
I think the most straightforward approach here would be to optimize these two operations in Base:

```jl
julia> vov = [[1,2,3],[4,5,6],[7,8,9]]
3-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5, 6]
 [7, 8, 9]

julia> reduce(hcat, vov)
3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

julia> mapreduce(transpose, vcat, vov)
3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9
```

Since these operations already produce the desired result, having optimized implementations for these and then telling people to use these as the idiom for doing this would work nicely without any risk of breaking anyone's code. There's also no reason *not* to optimize this. Any more sophisticated functionality can be developed out of Base in a package.

**Summary:** the action item here, rather than introduce any new verbs into the standard library, is to write optimized methods of `reduce` and `mapreduce` for arrays of arrays with `vcat` and `hcat` as reducers.

**Comment by oxinabox** [comment] 2017-05-09 12:19
While at it, can we have `push_column!` and `push_row!` ?
Perhaps that should be a separate issue, but it is closely linked

**Comment by andyferris** [comment] 2017-05-09 12:23
There aren't any resizeable multidimensional arrays in Base, is there?

(It would be a good feature for a nested array view/wrapper type, though!)

**Comment by oxinabox** [comment] 2017-05-09 12:25
>There aren't any resizeable multidimensional arrays in Base, is there?

Yes, but there are resizeable 1D Arrays.
 `push!`  adds an element to a Vector.
and by mixing `reshape` and `push!`, you can do this in 2D


> (It would be a good feature for a nested array view/wrapper type, though!)

Sure, would. 
Make a PR to CatViews.jl

**Comment by andyferris** [comment] 2017-05-09 13:09
> and by mixing `reshape` and `push!`, you can do this in 2D

Correct me if I'm wrong, but I thought there's something in the implementation that prevents resizing if there exists a multidimensional view (being an `Array`, from `reshape`, not a something like a `SubArray`) of the same memory. (or perhaps doesn't prevent resizing, but does perform some unexpected memory copying that would make this less efficient, I can't remember exactly).

> Make a PR to CatViews.jl, that would kick-arse

:+1:

**Comment by oxinabox** [comment] 2017-05-17 02:31
[TensorFlow](https://www.tensorflow.org/api_docs/python/tf/stack) calls this operation `stack`
so there some prior to it.

Further before shortly 1.0 release they renames it to stack, from its old name `pack`

**Comment by m-j-w** [comment] 2017-05-17 16:43
In particular for larger than two-dimensional arrays such an explicit function would really help entering data.

From the already existing function names my personal favourite would be `merge`: It translates fairly easy to other (spoken) languages; `unnest` or `stack` are not exactly common verbs, and `flatten` and `reshape` somewhat imply a modifying indices. It also matches how I would probably explain it: `merge(a)` merges an array of arrays into a single array while keeping the total number of dimensions, e.g. a vector of vectors becomes a matrix.

I can also imagine an optional output container type as first argument, say `merge(Array, a)` since in (most?) cases data must be copied anyway. This would also give the possibility to say e.g. `merge(ArrayView, a)` to generate some view.

**Comment by StefanKarpinski** [comment] 2017-05-17 19:42
Merge is a really overloaded term and it's pretty unclear to me how this is a merge operation.

**Comment by ChrisRackauckas** [comment] 2017-05-18 23:32
>For the base implementation, this would just convert a vector of vectors to matrices, as a specific case. I think whether it stacks in column major or row major order should probably be controlled by a dimension argument. There are generalizations one can imagine doing here.

Indeed this is the way to go, mostly because there are a ton of design decision for how to actually use a Vector of Arrays. A good example of this is the `VectorOfArray` type in RecursiveArrayTools.jl (courtesy of @gabrielgellner).

https://github.com/JuliaDiffEq/RecursiveArrayTools.jl
https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/blob/master/src/vector_of_array.jl

This is the backbone of all JuliaDiffEq solutions, the replacement of GrowableArrays, and there are definitely some decisions to make there, like how to iterate and count length (preserving the vector idea? Or rejecting that and now iterating as a matrix?). And there are still things to work out, like what is the appropriate norm to use?

So the rules one would like to impose on a view for an object like this is very application-specific, which is why I think it's probably best to leave it to packages like this (and CatViews) to implement.

**Comment by bramtayl** [comment] 2017-06-26 12:11
tidyr has unnest for something similar to this

**Comment by StefanKarpinski** [comment] 2017-07-06 17:32
This is an optimization / feature issue so it can be punted to a 1.x release.

**Comment by jlapeyre** [comment] 2018-02-04 08:33
There are other functions that have the same problem. For instance `merge` for merging `Dicts`. Doing `merge(array_of_dicts...)` is prohibitively inefficient for a large arrays.  In this case, a  new method for `merge` should suffice.

Of course, this can wait til after 1.0 is released. OTOH, I could make a PR, since the change should be easy and won't break stuff.

**Comment by nalimilan** [comment] 2018-02-04 14:29
`reduce(merge, array_of_dicts)` would work here too, right?

Please make a PR if you feel like it, it would be great to have an efficient solution in 1.0 given how often this pattern appears.

**Comment by jlapeyre** [comment] 2018-02-04 21:31
`reduce(merge, array_of_dicts) would work here too, right?`

No, unless I am missing something. `reduce` is not a varargs function, but `merge` is.  The problem is splatting a huge number of dicts as varargs.  I searched _Collections and Data Structures_ for `...`. But, not all varargs functions have this problem. Eg for `map(f,iters...)` splatting a huge array of iterators is probably not a good idea. The only candidates I found are:

`union(s1,s2,...)` yes. Taking the union of a `10^6` small arrays with many duplicate elements sounds reasonable. Likewise `intersect`,  and maybe `symdiff`.

 `push!` yes, but that's exactly what `append!` is for, so no. 

`unshift!`, yes, and I don't see a counterpart to `append!` so yes. (I did not do a thorough search). 

I can start with a PR for `merge`.

**Comment by nalimilan** [comment] 2018-02-04 21:37
`reduce` is not a varargs function, but that's the point: you pass it a collection of arrays/dicts rather than splatting them, which eliminates the cost of splatting too many arguments.

**Comment by nalimilan** [comment] 2018-02-05 09:40
To be clear: the solution which appears to make consensus [above](https://github.com/JuliaLang/julia/issues/21672#issuecomment-299875637) is to use `reduce(vcat, vec_of_vecs)` instead of `vcat(vec_of_vecs...)`. The same approach could probably be adopted for `merge`.

**Comment by jlapeyre** [comment] 2018-03-12 21:52
@nalimilan  I re-read and understand that the consensus is to make `reduce(merge, array_of_dicts)`  efficient.  But, it turns out the the inefficiency was in helper function for `merge`.  I fixed this, so that
`merge(ten_thousand_dicts...)` is now efficient.

I can make a pull request. But, PRs are supposed to include one or more tests. I wonder what kind of test to include. The most unpleasant aspect of the previous behavior is that `10^4` dicts will use all 16GB on my machine.  Any ideas ?

**Comment by andyferris** [comment] 2018-03-13 05:37
@jlapeyre It's indeed a little tricky to test performance in our unit tests - mostly we test for correctness. The existing unit tests provide a harness for you to change the implementation (to be faster) with the confidence of knowing you didn't break anything in the meantime. Generally posting benchmarks you did along with the PR and/or adding stuff for nanosoldier to run (BaseBenchmarks.jl) is sufficient proof that you made something better.

**Comment by jlapeyre** [comment] 2018-03-13 10:22
@andyferris  Yes, that's the question. Unit tests are for what Stefan calls "observable" behavior. (But, I am able to detect the desktop crashing because all memory is allocated, even though its non-observable.)  Nanosoldier looks a bit ...complicated, but worthwhile. Its been a couple of years since I did a PR to julia. I am concentrating on finding a way to run all tests without allocating all memory. It looks like `make testall` has no way to limit cpus.  Setting `JULIA_NUM_THREADS` to 1 and running `Base.runtests(ncores=1)` may work. Is there something obvious I am overlooking ? I guess asking a question on discourse so there is record in the proper place is the way to go.

For this PR to fix `merge`, I ran the most obvious tests, and will rely of travis for the rest. I'll include a benchmark in the PR comment.  But, I have another PR to make that has the possibility to affect many more tests, so I need to find a way to run them all.

**Comment by nalimilan** [comment] 2018-03-13 10:55
You don't need to deal with Nanosolider yourself, just make a PR against BaseBenchmarks to add a benchmark. In general better avoid using a lot of memory, a smaller test should be enough to measure the performance difference. You probably shouldn't add a standard test  in Julia itself as these only check behavior, not performance. 

Anyway open a PR first so that we can discuss the fix.

**Comment by jlapeyre** [comment] 2018-03-13 11:33
@nalimilan.  I didn't add any tests to the standard Julia test suite. I just wanted to run them to be certain (better: less uncertain) that the change does not break anything. For the PR at hand, I just ran the test files that call `merge` explicitly.  But, in the future, I may want to run all tests. I this case, I find that I run out of memory with the standard Julia test suite. Maybe because I am doing this on a desktop and not a dedicated server; I don't know.

Anyway, to move forward, I made the PR. #26440

Hmm. I see that I accidentally left "(#21672)", which may be confusing.

**Comment by bramtayl** [comment] 2018-03-15 14:52
Doesn't this already work?

```julia
collect(Iterators.flatten([[1, 2, 3], [4, 5, 6]]))
```

**Comment by nalimilan** [comment] 2018-05-21 10:44
A question which popped up when working on https://github.com/JuliaLang/julia/pull/26440 is whether we should define optimized methods only for `reduce(merge, items::AbstractVector{<:Dict})`, or for  `reduce(merge, items::AbstractVector)` and use `mapreduce(typeof, typejoin, items)` to also take the optimized code path even for `Vector{Any}` objects which happen to contain only `Dict` entries. The former is definitely simpler to implement, but it can miss cases which would benefit from the optimization. Opinions?

**Comment by nalimilan** [comment] 2018-05-21 14:39
Turns out the minimal fix to support `reduce([hvcat], A)` was simple. See https://github.com/JuliaLang/julia/pull/27188.

**Comment by jlapeyre** [comment] 2018-05-21 15:14
Here is a [proposed solution](https://github.com/JuliaLang/julia/pull/26440#issuecomment-390671301). The other option is to define  method for `reduce(merge, items::AbstractVector{<:Dict})` that uses `mapreduce` to get the key types and also the value types.

**Comment by cstjean** [comment] 2018-06-27 15:57
It might be late to comment on this, but one advantage of a dedicated function is that it can handle empty vectors easily (eg. `stack(Vector{Int}[])`). `reduce(vcat, Vector{Int}[], vectors)` works fine, but requires consciously thinking of the special-case.

**Comment by nalimilan** [comment] 2018-06-27 16:57
We can probably improve the `reduce` specialization to handle the case of empty but concretely typed arrays, similar to how `reduce(+, Int[])` works. Might be as simple as calling `eltype(eltype(vectors))` first when choosing the element type, and only falling back to `mapreduce(eltype, promote_type, vectors)` if that's not concrete.

**Comment by epatters** [comment] 2019-03-06 22:04
To echo a previous comment, it would be nice to handle the empty case appropriately: just as `reduce(+, Int[])` returns `0`, so should `reduce(vcat, Vector{Int}[])` return `Int[]`. An operation as basic as concatenating a vector of vectors shouldn't be so finicky!

**Comment by nalimilan** [comment] 2019-03-07 07:58
Shouldn't be too hard to fix. We should just avoid calling `mapreduce(eltype, promote_type, A)` when `isconcretetype(eltype(A))`, and use the eltype directly instead. Would you make a PR?

**Comment by antoine-levitt** [comment] 2021-07-12 12:55
A discussion about this just came up on Slack. There's a bunch of closed issues about this, but nothing current that I can find. Can this issue be reopened? It seems it was fixed in a previous version of julia where `cat` without the dims kwarg was a thing.

Looks like the conclusion of https://github.com/JuliaLang/julia/pull/37196 was that `cat` shouldn't guess the user's mind, but a new "higher-level" `stack` function that takes a list of arrays of the same dimensionality and stack them along a new axis could be introduced?

**Comment by ChrisRackauckas** [comment] 2021-07-12 12:59
Indeed from the work with RecursiveArrayTools.jl we have found that this is a missing verb in the ecosystem. It's an essential missing verb because all of the fallback mechanisms that make RAT work without it relies on multidimensional indexing. This "works" until you hit GPUs, where CUDA.jl, AMDGPU, etc. all need to specialize the behavior. This needs to be a Base verb because in the end, every array type of that form needs to be the one that specifies the behavior. You cannot have a working system where some package in the ecosystem has to Requires.jl compatibility to every new thing that comes along, instead it needs to be a part of the Array interface that every new array type obeys.

For that reason, having a `stack` in the ecosystem is pretty necessary. A lot of the inconveniences of Flux.jl and how it's tied to CUDA.jl instead of being GPU-generic can be traced back to this missing primitive, which is why I would say it's a necessary feature which we have attempted but failed to work without in the package ecosystem.

**Comment by mcabbott** [comment] 2021-07-12 13:21
Yes would be great to have. While #37196 phrased this as a kind of `cat`, that seems more closely associated with some non-`stack` operations like `cat(ones(2,2), ones(2,2), dims=(1,2))` for some people. 

One alternative would be to phrase this as the inverse of `eachslice`, which #32310 is going to make N-dimensional. That's lazy, but lazy slices are for example still strided arrays, while lazy concatenation are not. We might choose differently, or we might make both say `stack` & `Stack` with the same arguments.

**Comment by johnnychen94** [comment] 2021-07-12 13:29
> a new "higher-level" stack function that takes a list of arrays of the same dimensionality and stack them along a new axis could be introduced?

FWIW, I've made a [StackViews](https://github.com/JuliaArrays/StackViews.jl) for this very specific purpose.

**Comment by ChrisRackauckas** [comment] 2021-07-12 13:34
Again, StackViews is relying on indexing: https://github.com/JuliaArrays/StackViews.jl/blob/master/src/StackViews.jl#L128-L133 . So `Array(SV)` will work, but it will fail on GPUs, or at least be extremely slow. That's not a solution. We need something that works on all array types in a way that is optimized for each new array type, which is not something that is indexing-based will be able to provide.

**Comment by antoine-levitt** [comment] 2021-07-12 13:35
There's two things here: an eager and a lazy version. It seems simpler to have Base implement the eager version, ie `stack([randn(2), randn(2)])` would be a plain 2x2 array. Lazy versions could be implemented by packages.

**Comment by mcabbott** [comment] 2021-07-12 13:38
My round-up of the half-dozen packages for this is at https://github.com/mcabbott/LazyStack.jl#other-packages . When last I checked the behaviour `LazyStack.stack` on CuArrays was to fall back to an eager method, and make a lazy container (which relies on indexing) only for things which are backed by Arrays.

**Comment by JeffBezanson** [comment] 2021-07-15 19:06
From triage:
- Yes
- We should implement the eager version in Base
- We're ok with requiring all the input arrays to have the same # of dimensions, and returning something with one added dimension. Is that sufficient for most uses in the ecosystem currently?

**Comment by antoine-levitt** [comment] 2021-07-15 19:17
Cool, thanks for discussing it! @mcabbott do you have code for this at the ready? If not I can try to make a PR.

**Comment by mcabbott** [comment] 2021-07-15 19:43
There's code in my PR for the case that the dimensions are ordered `func(As)[I, J] == As[J][I]` for any ndims. It's a trivial adaptation of what's there for `reduce(hcat, ...)`. (In fact IIRC it allows `func(As)[I,1,1,J] == As[J][I]` with some trivial dims.) It requires all slices the same size.

If this new function doesn't take a `dims` keyword, and puts the slices together in a fixed way, then restricting either `ndims` to 1 seems unnecessary & prevents stacking e.g. a matrix of matrices. The above ordering is very natural to column-major storage, but if I'm thinking correctly no multi-dim operations in Julia currently privilege this. 

If it does have some way to control in which dimensions the slices lie, then that requires more thought. The present `eachslice` allows one `dims` which indicates the array dim which becomes the iterator; the upgrade in #32310 allows multiple `dims` and their order matters. Should this function try to be the inverse? Shouldn't be hard to code this efficiently, but I guess needs cases like both `reduce(vcat, ...)` and `reduce(hcat, ...)`. (The convention of `mapslices` is the opposite to `eachslice`.)

**Comment by antoine-levitt** [comment] 2021-07-15 20:06
I didn't consider stacking eg matrices of matrices, but you're right there's nothing preventing stack from supporting this. `stack(As)[I,J] == As[J][I]` seems eminently reasonable. There's indeed no existing function that does this to my knowledge, but this is consistent both with column-major (and therefore with reshape), with the ordinary usage in linear algebra (in which matrices are usually more naturally seen as being collections of their columns rather than collections of their rows) and with precedent in packages (eg RecursiveArrays).

Regarding a specific way of control the dimensions, what would be the use case? It seems to me this would be too confusing for people to actually use and they'd be better off writing their own routines.

`stack(::Generator)` would be super nice also. Ideally it should behave the same way as `stack(collect())`, meaning it should support things like `stack(randn(2,2) for i=1:2, j=1:2))` returning a 4D array.

**Comment by mcabbott** [comment] 2021-07-15 20:15
> way of control the dimensions, what would be the use case?

Sometimes people wish to assemble a matrix from rows, you can do `reduce(vcat, transpose([fill(row^2,3) for row in 1:5]))` but maybe this would be neater?

My package went for the no-options, everything N-dimensional, version. Since it's lazy, allowing options just means you end up re-writing `PermutedDimsArray(stack(...), perm)`. But for an eager function, maybe it's more important to avoid `permutedims`. Not all permutations are captured by my `dims` keyword above (nor by `eachslice`).

**Comment by dorn-gerhard** [comment] 2021-07-16 10:46
Following the whole discussion I see two needed applications for arbitrary **arrays of arrays**:

1. Turning an array of arrays into a single md-array with more dimensions (is the subarrays have all the same size):
`A[i, j, k][a, b] -> A[a, b, i, j, k]`
The option of where to locate the indices` i, j, k` (as proposed three posts earlier) and in which order could be solved by permutedims or defined by a keyword `stack(A, dims = [1,7,5])` ending with `A[i, a, b, 1, k, 1, j]`
But I guess shuffling dimensions is a performance issue.

2. Stacking an array of arrays by appending in one or more dimensions, which for vectors of arrays works with 
vcat and hcat to stack into the first or second dimension.
`reduce(vcat, [rand(2,3) for _ = 1:4]): A[i][a,b] -> B[(a,i),b] = A[(i-1)*len_a + a, b]`
`reduce(hcat, [rand(2,3) for _ = 1:4]): A[i][a,b] -> B[(b,i),a] = A[a, (i-1)*len_b + b]`
Arrays of arrays are treated as vector of arrays `A[i,j,k][a,b] -> A[:][a,b]`

This task can be generalized to arbitrary multidimensional arrays and condensing two (or more) indices (columnwise `(a,b) = (b-1)*len_a + a`):
e.g. `A[i, j, k][a, b] -> A[a, b, i, j, k] -> B[i, (j, b), a, k] = A[i, (b-1)*len_j+j, a, k]`
which can be done by `B = reshape(permutedims(A,(3,2,4,1,5)), len_i, len_b*len_j, len_a, len_k)`
but which is rather slow.

So an efficient function for nr 1. (turning (md)arrays of (md)arrays into md arrays) which is the latest suggestion for `stack`
would be great and maybe you have efficient suggestions for collapsing indices of md arrays (e.g. something with `:`)

**Comment by mcabbott** [comment] 2021-07-16 12:36
I think your 1. is all that's planned; whether to take `dims` at all, and whether to allow `dims=(1,7,5)` not just `dims::Integer`, are the questions. And what to call it, e.g. is colliding with [DataFrames.stack](https://dataframes.juliadata.org/latest/lib/functions/#DataFrames.stack) OK?

For your 2. there are quite a lot of possible ways to do that in N dims. The notation you use here is almost exactly that of TensorCast.jl, for example:
```
julia> using TensorCast; A = [rand(2,3) for _ = 1:4];

julia> @cast B[(a,i),b] := A[i][a,b]; B == reduce(vcat, A)
true
```

**Comment by aiqc** [comment] 2021-07-23 16:36
When I think of "stack" I think about making a df taller via concatenation, which isn't really what this is about. This is more of a dimensional nesting?

![image](https://user-images.githubusercontent.com/74990642/126813361-1912694b-78af-4742-a157-e68d5b24ab92.png)

**Comment by antoine-levitt** [comment] 2021-07-23 17:24
Yeah I was thinking this also actually... I'm not a native english speaker but it seems to me stack can have two meanings : stack a and b next to other, and stack a and b on top of each other. Reasonably, stack(rand(2), rand(2)) could be a Vector of size 4, or a 2x2 matrix, so it's maybe bad to pick one?

**Comment by goretkin** [comment] 2021-07-28 13:42
When comparing a method definition 
`stack(...)`

to

`reduce(::typeof(vcat), ...)

is the main benefit of the first that it is easier to avoid method ambiguity errors?

I think it can be a good idea to have abbreviated names for more generic operations, the same way people tend to prefer `zeros(T, dims)` over `fill(zero(T), dims)`. But `zeros` is written in terms of `fill` (well, really [fill!](https://github.com/JuliaLang/julia/blob/1c951f7fe8e5e923cc5f5b18c91e461b61641b14/base/array.jl#L578-L595)), and I would assume we should write `stack` in terms of `reduce(vcat, ...`

**Comment by mcabbott** [comment] 2021-12-04 03:54
@goretkin 
> is the main benefit of the first that it is easier to avoid method ambiguity errors?

This doesn't seem to be clearly stated above, but one complaint about `reduce(hcat, xs)` is that it's not very discoverable. If you don't know that it has special methods, you might assume it concatenated one by one.

The other complaint is that it doesn't generalise very easily. You can write `cat([fill(1,2,3) for _ in 1:4]...; dims=3)` as `reduce((x...) -> cat(x...; dims=3), xs)` (pairwise) or `reshape(reduce(hcat, xs), ...)` (for this dimension). If you have a matrix of vectors instead, then things are awkward.

So more likely the `reduce(hcat, ...)` special case could have its implementation replaced by the general one, rather than the reverse.

@stillyslalom 
> Another approach: ... `reduce(cat(dims=3), [[1, 2], [3, 4]])`

This was one of the ideas explored in  #37196, and one objection there is that `cat(; dims=3)` already does something.

**Comment by MasonProtter** [comment] 2023-06-01 01:42
I believe this issue can be closed now.

**Closed** 2023-06-01 14:09 UTC
Labels: help wanted, arrays
