### ISSUE TITLE
PSA: don't use ifelse unless you are careful that you have a leaf bitstype

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#15494] opened 2016-03-14 06:31 UTC
PSA: try to avoid ifelse. Otherwise, you cause bugs.

action required: revert #14493

symptom: coverage buildbots are broken (https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/89/steps/Run%20non-inlined%20tests/logs/stdio)

```julia
$ ./julia -q --inline=no
srand(123);
A1 = Base.LinAlg.UnitUpperTriangular(convert(Matrix{BigFloat}, randn(9,9) |> (t -> chol(t't))));
using Base.Test

julia> similar(A1)
9x9 Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}:
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef  #undef

julia> copy!(B, A1);

julia> @test B == A1

Error During Test
  Test threw an exception of type UndefRefError
  Expression: B == A1
  UndefRefError: access to undefined reference
   in getindex(::Array{BigFloat,2}, ::Int64, ::Int64) at array.jl:241
   in getindex(::Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}, ::Int64, ::Int64) at linalg/triangular.jl:114
   in _getindex(::Base.LinearSlow, ::Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}, ::CartesianIndex{2}) at multidimensional.jl:359
   in getindex(::Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}, ::CartesianIndex{2}) at abstractarray.jl:476
   in next(::Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}, ::Tuple{CartesianRange{CartesianIndex{2}},CartesianIndex{2}}) at abstractarray.jl:400
   in next(::Base.Zip2{Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}},Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}}, ::Tuple{Tuple{CartesianRange{CartesianIndex{2}},CartesianIndex{2}},Tuple{CartesianRange{CartesianIndex{2}},CartesianIndex{2}}}) at iterator.jl:48
   in ==(::Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}, ::Base.LinAlg.UnitUpperTriangular{BigFloat,Array{BigFloat,2}}) at abstractarray.jl:990
   in eval(::Module, ::Any) at ./boot.jl:243
   in eval(::Module, ::Expr) at REPL.jl:3
ERROR: There was an error during testing
 in error(::ASCIIString) at error.jl:21
 in record(::Base.Test.FallbackTestSet, ::Base.Test.Error) at test.jl:317
 in do_test(::Base.Test.Threw, ::Expr) at test.jl:215
 in eval(::Module, ::Any) at ./boot.jl:243
 in eval(::Module, ::Expr) at REPL.jl:3
```

**Comment by yuyichao** [comment] 2016-03-14 06:36
More like especially avoid `ifelse` with side-effect? Is llvm (and possibly our inliner) smart enough to turn the branch into a select when it's beneficial?

**Comment by JeffBezanson** [comment] 2016-03-14 06:54
There aren't supposed to be any restrictions on when you can use `ifelse`. It simply uses function call semantics; arguments are evaluated eagerly. That seems to be the issue here, not bits types. Am I missing something?

**Comment by tkelman** [comment] 2016-03-14 09:57
duplicate of https://github.com/JuliaLang/julia/pull/15466

**Comment by JeffBezanson** [comment] 2016-03-15 06:30
Closing as dup.

**Closed by JeffBezanson** 2016-03-15 06:30 UTC
