### ISSUE TITLE
pid of child Process

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10420] opened 2015-03-06 14:38 UTC
We don't currently expose any way of getting the PID of a child process. Arguably, this is a system-level detail that we may not want people to program to, but it should be possible to get. Currently, on a 64-bit system you can do this:

``` jl
function pid(proc::Base.Process)
    proc.handle != C_NULL || error("process not running")
    int(unsafe_load(convert(Ptr{Uint32}, proc.handle + 72)))
end
```

Obviously not ideal. This also errors if the process has already finished when you call it, which can be unpredictable. What's a good API to this? Should we fold `getpid` into it as a zero-argument version?

**Comment by vtjnash** [comment] 2015-03-06 22:12
why do you need the pid?

regardless, since nodejs exposes it, we can too:
https://nodejs.org/api/process.html#process_process_pid

**Comment by StefanKarpinski** [comment] 2015-03-06 22:25
I don't personally, someone asked me for this. Since we allow getting this process's PID, it seems natural to allow getting the child's PID too. Should we just record the PID as soon as the process is spawned, when it's guaranteed that `proc.handle` is non-NULL?

**Comment by JeffBezanson** [comment] 2015-03-06 22:44
That sounds worthwhile. I can spare 4 bytes of memory.

**Comment by vtjnash** [comment] 2015-03-06 23:43
throwing an error sounds fine too

**Comment by colbec** [comment] 2015-12-08 16:21
@vtjnash asked why we need the pid. From a beginner perspective, there appears to be a need to launch and control long lasting processes such as a socket server in the background and then access it from the current Julia instance. We need to verify that it is properly running and (if necessary) later kill it via the pid if it does not want to go away when instructed. This is perhaps not a sophisticated approach to the issue - there may be a better Julia way of achieving this. I searched the docs but did not find anything obvious. run(...) does not expose any later access to the process it launches, and the @sync and @spawn family of routines don't seem to apply. In other applications I have parsed the output of ps to get the pid if necessary. This may be one case of how beginners think in terms of pids, perhaps erroneously.

**Comment by vtjnash** [comment] 2015-12-08 17:39
the `Process` object returned by the `spawn` and `open` class of functions support `kill` and status

the error version is actually better since the `pid` value is invalid (might point to a difference process entirely) once `proc.handle == C_NULL`

**Comment by colbec** [comment] 2015-12-08 17:50
Aha! Thankyou. Exposure to other programmes where open() is used in a more restricted context is something of a hindrance in reading Julia docs. A new avenue to explore.

**Comment by eschnett** [comment] 2015-12-08 17:57
I also would like to access the pid of a child (see <https://mail.google.com/mail/u/0/#label/julia-dev/15121c0b2b4b2038>). I want to start a Julia child that may run longer than the parent, and I thus need to know its pid to be able to control it later. (It will be controlled by a new Julia process that reads the pid from a file.)

If there's a better way for a newly created Julia process to control an already running background process, I'd be happy to use it.

**Comment by sarvjeetsinghghotra** [comment] 2015-12-19 18:54
Some idea how its API should be?

**Comment by Keno** [comment] 2016-07-22 22:34
I think this should just be `getpid(::Process)`.

**Comment by abalkin** [comment] 2017-10-09 16:19
This looks like a duplicate of #4752.

**Closed** 2017-10-09 16:23 UTC
Labels: Hacktoberfest, intro issue
