### ISSUE TITLE
Issue with help mode

### ISSUE THREAD

**Issue by TFC-343** [JuliaLang/julia#45039] opened 2022-04-20 12:58 UTC
# versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)

# method to reproduce
in REPL:
`
help?> ;;
`
# result
```
ERROR: LoadError: BoundsError: attempt to access 0-element Vector{Any} at index [1]
Stacktrace:
 [1] getindex
   @ .\array.jl:861 [inlined]
 [2] astname(x::Expr, ismacro::Bool)
   @ Base.Docs .\docs\Docs.jl:305
 [3] namify
   @ .\docs\Docs.jl:294 [inlined]
 [4] lookup_doc(ex::Expr)
   @ REPL C:\Users\james\AppData\Local\Programs\Julia-1.7.1\share\julia\stdlib\v1.7\REPL\src\docview.jl:232
 [5] docm(source::LineNumberNode, mod::Module, ex::Any)
   @ Base.Docs .\docs\Docs.jl:521
 [6] var"@doc"(__source__::LineNumberNode, __module__::Module, x::Vararg{Any})
   @ Core .\boot.jl:517
in expression starting at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\REPL\src\docview.jl:535
```

# excepted result
the help mode should not be able to return an error

**Comment by giordano** [comment] 2022-04-20 13:33
Duplicate of #43558

**Closed by giordano** 2022-04-20 13:33 UTC
