### ISSUE TITLE
Unusual backtrace line numbers with macros

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#1334] opened 2012-10-04 18:33 UTC
I've noticed that Julia's backtrace line numbers don't alway make sense.  For instance, in the following short program (named `lapack_perf.jl`) and ignoring the actual errors in the code:

```
reps  = 10
n     = 100
srand(1234321)
a     = rand(n,n)
apd   = a'*a

function test_chold{T<:Number}(apd::Matrix{T})
    times = zeros(10)
    cholds = T[]
    times = [@elapsed push(cholds, chold(apd)) for k = reps]
    
    # return so it doesn't get optimized away
    cholds
end


print( test_chold(apd) )
```

I get the following backtrace:
```
$ julia lapack_perf.jl 
no method convert(Type{Float64},CholeskyDense{Float64})
 in method_missing at base.jl:70
 in push at array.jl:708
 in test_chold at /Users/sabae/Desktop/lapack_perf.jl:49
 in load_now at util.jl:231
 in load_now at util.jl:245
 in require at util.jl:174
 in process_options at client.jl:178
 in _start at client.jl:232
at /Users/sabae/Desktop/lapack_perf.jl:17
 in load_now at util.jl:231
 in load_now at util.jl:245
 in require at util.jl:174
 in process_options at client.jl:178
 in _start at client.jl:232
 in load_now at util.jl:256
 in require at util.jl:174
 in process_options at client.jl:178
 in _start at client.jl:232
```

This all looks fine and good until we see the `in test_chold at /Users/sabae/Desktop/lapack_perf.jl:49` line; Clearly this file doesn't have a line 49.

EDIT: This is due to macros, as @dmbates states.  Is there a better way to effect line-printing with macros (which are very helpful and therefore likely to be used extensively)?

**Comment by SimonDanisch** [comment] 2015-01-14 10:56
I didn't want to open a new issue, but I have the feeling, that line numbers got worse lately.
Most recent example:
I was debugging OpenCL code, and I didn't get any decent line numbers at all, even though that there where (from what I can see) no funky constructs.
The error:
```
ERROR: InexactError()
 in convert at pointer.jl:7 (repeats 2 times)
while loading C:\Users\Sim\Desktop\Julia\InteropContext.jl, in expression starting on line 21
```
There is a lot missing here!
It took me quite some time to figure out the correct stack trace which was something like this:
```Julia
 in convert at pointer.jl:7 #didn't show up the time I got decent stack traces, though
OpenCL\src\types.jl on line 143
OpenCL\src\context.jl on line 176
OpenCL\src\context.jl on line 90
InteropContext.jl, in expression starting on line 17
C:\Users\Sim\Desktop\Julia\InteropContext.jl, in expression starting on line 21
```

"minimal" example:
https://gist.github.com/c5bc1f0422ba64fd46c5.git

I don't know what's going on here... I had a version, where it gave me the correct line numbers, but I can't reproduce it right now.

```Julia
Julia Version 0.4.0-dev+2523
Commit e26eb53* (2015-01-06 05:57 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Best,
Simon

**Comment by tkelman** [comment] 2015-01-14 11:36
If you can come up with an example that doesn't use code from a package, it'll be much easier to try bisecting this.

**Comment by SimonDanisch** [comment] 2015-01-14 12:30
Yes I know, but this requirement hold me back from posting any bug report
for the last months.
It has been nearly impossible for me to reproduce this with a better
minimal example, and at some point I gave up trying, as it was too time
consuming.

2015-01-14 12:36 GMT+01:00 Tony Kelman <notifications@github.com>:

**Comment by SimonDanisch** [comment] 2015-01-14 12:34
So I thought this is better than nothing. I must admit I haven't tried it
this time, as the last time was very frustrating. I tried every combination
of nested function calls, includes, separate modules, nested separated
modules, macros in the surrounding code, etc... I simply don't know how to
go about this, other than spear fishing in the dark ;)

2015-01-14 13:29 GMT+01:00 Simon Danisch <sdanisch@gmail.com>:

**Comment by tkelman** [comment] 2015-01-14 12:50
Okay, okay, I'll fiddle with things and try to see if I can find any commits since the 0.4-dev branch that give better backtraces there. You could try with older nightlies from http://s3.amazonaws.com/julianightlies, but it looks like the oldest ones still there are about a month old.

I do think your specific problem should probably be a separate issue though, since it's likely platform-dependent.

**Comment by timholy** [comment] 2015-01-14 13:17
@SimonDanisch, start julia with `julia --inline=no` and then try your tests.

But your report is likely to be very different from the one that started this thread; better to file a separate issue in such cases.

**Comment by SimonDanisch** [comment] 2015-01-14 16:56
`julia --inline=no` actually does the trick. I'll open a new issue together with this piece of information!

**Comment by ihnorton** [comment] 2015-03-07 00:38
One way to help with this would be to optionally emit line numbers corresponding to the lines of `code_typed` instead of the original source. I think such an option would be generally useful for advanced debugging.

**Comment by mlubin** [comment] 2015-04-23 19:39
Any chance we can get this in for 0.4? This is one of JuMP's biggest usability/debuggability issues.

**Comment by timholy** [comment] 2015-06-08 02:22
@Keno, any chance you could take a look at this? I poked around briefly but don't understand enough about LLVM to make progress on this in a reasonable amount of time. Here's my current favorite test script:
```jl
function foo()
    @show error("oops")
end
```
I saved this to a file `/tmp/showerror.jl`. Load this, then
```jl
julia> foo()
ERROR: oops
 in foo at /tmp/showerror.jl:100

julia> @code_typed foo()
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[symbol("#1#value")],Any[Any[symbol("#1#value"),Union(),18]],Any[],Any[Union(),Union()]], :(begin  # /tmp/showerror.jl, line 2: # show.jl, line 100:
    blah blah
```
You can see it gets the file right but the line number comes from `@show`'s definition in `show.jl`. Note the line information from the excerpt of `@code_typed`: it's using the "outer" node for the filename but the "inner" node for the line number.

With LLVM 3.3, it would seem that the problem is that [`(*it).second.lines.end()`](https://github.com/JuliaLang/julia/blob/22b5c9d7018711c1791d631c04bb69aed3a29602/src/debuginfo.cpp#L783) points somewhere inside the code from the macro. The correct file is being provided from `debugscope`, and I note that `debugscope.getLineNumber()` is a valid function call but it returns 0. Is this just a question of forgetting to set this parameter during code generation?

How fixable would this be on current julia? Or is your thinking that the ponies only come out with MCJIT?

**Comment by ihnorton** [comment] 2015-07-28 15:03
One way to fix this is to emit a scope wrapping the last top level line number. So in codegen when we see `# /tmp/showerror.jl, line 2: # show.jl, line 100:` we create a LexicalBlock wrapping the `showerror.jl:2` context, and then emit a LexicalBlockFile for `show.jl` as usual, but with the parent scope set to the LexicalBlock.

I've tried this and it works on 3.3, at least for JIT'd functions (I believe it should also work with DWARF but haven't tested yet).

Doing the latter would be ideal because we could then have both the macro definition and the macro invocation contexts (and it may help with some inlining-related line number problems too?). However, I have a couple questions:

- any suggestions for how to change the `jl_getFunctionInfo` API to return multiple lines? if we change the codegen to emit nested scopes then we would resolve each scope back up to the subprogram level, and ideally return all of them.

- @JeffBezanson @jakebolewski is it safe to assume that a nested `line_sym` node with file attached is unitary? that is, can I assume that the next `LineNode` pops back up to the original context?

**Comment by ihnorton** [comment] 2015-07-28 15:03
(if the latter assumption is true, than an easier partial fix would be to simply ignore nested `line_sym` nodes in codegen)

**Comment by ihnorton** [comment] 2015-07-28 17:44
On my (messy) [working branch](https://github.com/JuliaLang/julia/tree/b1334):

Tim's example:
```
julia> foo()
### jl_getFunctionInfo resolve line
file: show.jl lno: 100
LexicalBlock file: /cmn/jlbugs/1334_macro_lnos/showerror.jl lno: 2
LexicalBlock file: /cmn/jlbugs/1334_macro_lnos/showerror.jl lno: 2
### jl_getFunctionInfo resolve line
file: REPL.jl lno: 49
LexicalBlock file: REPL.jl lno: 49
ERROR: oops
 in foo at /cmn/jlbugs/1334_macro_lnos/showerror.jl:2
```

[a contrived example](https://gist.github.com/ihnorton/498064798a67bcd1261f)
```
julia> include("/cmn/jlbugs/1334_macro_lnos/foo.jl")
foo3 (generic function with 1 method)

julia> foo2()
### jl_getFunctionInfo resolve line
file: show.jl lno: 100
LexicalBlock file: /cmn/jlbugs/1334_macro_lnos/foo.jl lno: 11
### jl_getFunctionInfo resolve line
file: REPL.jl lno: 49
LexicalBlock file: REPL.jl lno: 49
ERROR: oops
 in foo2 at /cmn/jlbugs/1334_macro_lnos/foo.jl:11
```

**Comment by mlubin** [comment] 2015-07-28 17:46
:+1:

**Comment by timholy** [comment] 2015-07-28 17:49
Really impressive @ihnorton! If this is something that could be merged into 0.4, it would be quite an unexpected bonus!

**Comment by JeffBezanson** [comment] 2015-07-28 18:09
> can I assume that the next LineNode pops back up to the original context?

I don't believe so. We are completely missing any kind of "pop" for expanded macros or inlined functions. We'll need to add pop_location `meta` nodes.

**Comment by ScottPJones** [comment] 2015-07-28 18:17
Big win for debugging :+1: Your messy branch seems to be 500+ commits behind master, how hard would it be to bring it up to date?  (I'd start using it right away)

**Comment by ihnorton** [comment] 2015-07-28 22:21
@JeffBezanson I guess I'll go find my threadbare Scheme hat.

@ScottPJones the patch probably applies cleanly, but I wouldn't use it yet. As per above, it relies on a faulty assumption. (also makes the REPL noisy, hard-codes an important test, probably leaks, etc.).

**Comment by ihnorton** [comment] 2015-07-28 22:46
One complication: right now not all macros get line information.

**Comment by ihnorton** [comment] 2015-08-02 02:33
Another example from julia-users: https://groups.google.com/d/msg/julia-users/GXHm6sqR3YI/oF990MaNAQAJ

**Comment by ihnorton** [comment] 2015-08-03 19:32
I could use some help with lowering these `poploc` nodes. Some attempts and thoughts so far:

- I tried adding a `(meta poploc)` node at the end of every block that introduces a `line-number-filename-node`, and fiddled with `block` handling in `to-lff` to make it consider the next-to-last node as tail if the true tail is a meta node. This is really janky because (among other things) `return` is not the last statement in a given block, thus it breaks tail handling in other places.

- insert the meta node at macro invocation: haven't tried this yet, but I think it would have the same problem of introducing non-return tail nodes. Also not quite sure how to handle multiple line-number-filename nodes in the same expanded form (just count them?)

- *The cop-out solution*: just attach the file to every single line node. Would this be too expensive?

**Comment by ihnorton** [comment] 2015-08-04 15:25
@JeffBezanson, if you have any time to share thoughts on the `pop_location` `meta` nodes idea, that would be very helpful. @jakebolewski and @carnaval made a strong argument that this can't be addressed in general (to handle the corner cases of code splicing) without a significant reworking of the parsing and lowering code to trace source origin within each expression. Some interesting tidbits along these lines: [Debugging Layers (in Converge)](http://tratt.net/laurie/blog/entries/debugging_layers); [Racket's syntax object / srcloc](http://docs.racket-lang.org/reference/exns.html#%28def._%28%28quote._~23~25kernel%29._prop~3aexn~3asrclocs%29%29) design.

However, I am hopeful that there is some room for improvement in the current scheme:

- as above, attach the file to every single line node. This costs one additional symbol per line node, and probably a few lookups... That seems fairly insignificant overall, but I'll try to implement it and benchmark.

- another idea: strip all line nodes when splicing macros and inlining code. This would lose any chance of getting definition site, but should fix function-level line numbers. Seems like a good trade to me. An advantage of this idea is that it would have zero overhead and may not require any codegen or debuginfo changes.

**Comment by ihnorton** [comment] 2015-08-04 15:51
Related to the second idea: strip all non-filename line nodes when splicing code. Then we could make the original assumption that unattached line nodes are only at top-level scope, and still trace to the definition location.

(downside: consecutive non-toplevel filename line nodes could be ambiguous -- nested vs. spliced -- but that would not be terrible because the toplevel line would always be correct)

**Comment by timholy** [comment] 2015-09-04 06:16
@ihnorton, you should do the honors here.

**Comment by timholy** [comment] 2015-09-14 18:27
OK to close this?

**Comment by ihnorton** [comment] 2015-09-14 18:29
Ok :smile:

**Closed by ihnorton** 2015-09-14 18:29 UTC
Labels: bug

**Comment by KristofferC** [comment] 2015-09-14 18:44
New backtraces are really awesome btw!
