### ISSUE TITLE
Regression in constant propagation on nightly compared to v1.10.0

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#53038] opened 2024-01-24 17:50 UTC
On v1.10
```julia
julia> using StaticArrays, LinearAlgebra

julia> m_sing2 = @SMatrix [1 1; 1 0; 0 1]
3×2 SMatrix{3, 2, Int64, 6} with indices SOneTo(3)×SOneTo(2):
 1  1
 1  0
 0  1

julia> svd_full_false(A) = svd(A, full=false) # the full needs to be constant-propagated for concrete type inference 
svd_full_false (generic function with 1 method)

julia> @code_warntype svd_full_false(m_sing2)
MethodInstance for svd_full_false(::SMatrix{3, 2, Int64, 6})
  from svd_full_false(A) @ Main REPL[6]:1
Arguments
  #self#::Core.Const(svd_full_false)
  A::SMatrix{3, 2, Int64, 6}
Body::StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}
1 ─ %1 = (:full,)::Core.Const((:full,))
│   %2 = Core.apply_type(Core.NamedTuple, %1)::Core.Const(NamedTuple{(:full,)})
│   %3 = Core.tuple(false)::Core.Const((false,))
│   %4 = (%2)(%3)::Core.Const((full = false,))
│   %5 = Core.kwcall(%4, Main.svd, A)::StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}
└──      return %5
```
On nightly
```julia
julia> @code_warntype svd_full_false(m_sing2)
MethodInstance for svd_full_false(::SMatrix{3, 2, Int64, 6})
  from svd_full_false(A) @ Main REPL[2]:1
Arguments
  #self#::Core.Const(svd_full_false)
  A::SMatrix{3, 2, Int64, 6}
Body::Union{StaticArrays.SVD{Float64, SMatrix{3, 3, Float64, 9}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}, StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}}
1 ─ %1 = (:full,)::Core.Const((:full,))
│   %2 = Core.apply_type(Core.NamedTuple, %1)::Core.Const(NamedTuple{(:full,)})
│   %3 = Core.tuple(false)::Core.Const((false,))
│   %4 = (%2)(%3)::Core.Const((full = false,))
│   %5 = Main.svd::Core.Const(LinearAlgebra.svd)
│   %6 = Core.kwcall(%4, %5, A)::Union{StaticArrays.SVD{Float64, SMatrix{3, 3, Float64, 9}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}, StaticArrays.SVD{Float64, SMatrix{3, 2, Float64, 6}, SVector{2, Float64}, SMatrix{2, 2, Float64, 4}}}
└──      return %6
```

**Comment by maleadt** [comment] 2024-01-25 09:04
Bisected to #51968; cc @gbaraldi

**Comment by gbaraldi** [comment] 2024-01-25 17:18
I'll take a look, but the only thing that could maybe affect this is that I allowed for array allocation to be inlined?

**Comment by gbaraldi** [comment] 2024-01-26 14:42
So reverting the inlining does fix this, but I have no clue why 😕

**Comment by aviatesk** [comment] 2024-01-29 04:26
This issue appears to be something that should be addressed with modifications in StaticArrays.jl. Explaining the regression, due to #51968, there is now increased chances of inlining of those memory-ops, which consequently expanded the post-inlining IR of methods such as `StaticArrays._svd`, and this method body expansion is obstructing const-prop' for `_svd`. The issue can be resolved by making the following differential changes:
```diff
diff --git a/src/svd.jl b/src/svd.jl
index 69707e3..d2af6e9 100644
--- a/src/svd.jl
+++ b/src/svd.jl
@@ -32,9 +32,8 @@ function svdvals(A::StaticMatrix)
     similar_type(A, T2, Size(diagsize(A)))(sv)
 end
 
-function svd(A::StaticMatrix; full=Val(false))
-    _svd(A, full)
-end
+# `@inline` annotation is required to propagate `full` as constant to `_svd`
+@inline svd(A::StaticMatrix; full=Val(false)) = _svd(A, full)
 
 # Allow plain Bool in addition to Val
 # Required inline as of version 1.5 to ensure Bool usage like svd(A,
```

**Comment by jishnub** [comment] 2024-01-31 03:19
Closing this, as a fix has been added to `StaticArrays`

**Closed** 2024-01-31 03:19 UTC
Labels: regression
