### ISSUE TITLE
Documentation for Artifacts?

### ISSUE THREAD

**Issue by fingolfin** [JuliaLang/julia#39054] opened 2020-12-30 23:25 UTC
With Julia 1.6, Artifacts.jl isre now a stdlib. However, it is not listed in the manual, https://docs.julialang.org/en/v1.7-dev/stdlib/Artifacts/ gives a 404. IMHO there really should be something here, even if it's just a few lines that point elsewhere (e.g. to the Pkg.jl manual). Right now, searching the Julia manual for "artifacts" gives zero hits.

So the de-facto canonical place for documentation on artifacts is still Pkg.jl, specifically https://julialang.github.io/Pkg.jl/dev/artifacts/. But that does not (yet?) reflect the fact that Artifacts are now a stdlib (perhaps deliberately, but I think at least a callout pointing out this change in Julia 1.6 would be nice.

And then there is `LazyArtifacts.jl` about which I learned by pure chance a few days ago when I chanced upon a random conversation about it on Slack. The entire documentation for this seems to be an entry in `HISTORY.md`. While admittedly error messages kinda guide you to it when you need it, I think the documentation for artifacts should also mention this stdlib package.

**Comment by vtjnash** [comment] 2020-12-30 23:57
Duplicate of #39039

**Closed** 2020-12-30 23:58 UTC
