### ISSUE TITLE
Parametric Subtyping?

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#51025] opened 2023-08-23 18:05 UTC
I'm not sure if parametric subtyping would be the right term, but the pattern I'm interested in is this:
```julia

# minimum example
struct Thing{T} <: supertype(T)
	field::T
end

# actual use case
struct UnitfulNumber{T <: Number} <: supertype(T)
	field::T
end
```
The motivation being that many Unitful objects can't deal with functions that have `Real` restrictions, because units have to subtype `Number` instead of `Real`. How difficult would it be to support this?

**Comment by vchuravy** [comment] 2023-08-24 01:22
I think `type predicates` might be the right term, but I suspect for your use-case a limited set of predicates might be acceptable.

We have wanted something similar in the GPU ecosystem for wrapper arrays as well.

```
SubArray{T<:AbstractArray} <: storagetype(T)
```

**Comment by Seelengrab** [comment] 2023-08-24 07:34
This is basically a duplicate of #5 and/or traits.

**Comment by vchuravy** [comment] 2023-08-24 12:41
No it is not equivalent to #5 or interfaces/traits. 

This is not about `UnitfulNumber` implementing the interface of the class number, but that the interface it implements is dependent on a parameter of the class is self. 

Multiple Inheritance/Interface are an orthogonal concern.

**Comment by mbauman** [comment] 2023-08-24 13:07
Yeah, this is https://github.com/JuliaLang/julia/issues/8322.

**Closed** 2023-08-24 13:07 UTC
Labels: types and dispatch, feature
