### ISSUE TITLE
Healpix.jl tests hang on Julia v1.9

### ISSUE THREAD

**Issue by ziotom78** [JuliaLang/julia#46736] opened 2022-09-13 10:02 UTC
In the last weeks, I have experienced several timeouts when I run CI tests using GitHub Actions on Julia nightly. These always happen on Windows, Linux, and Mac OS X when `Pkg.test()` is invoked. Here are two examples of jobs taken from different repositories ([Healpix.jl](https://github.com/ziotom78/Healpix.jl) and [Stripeline.jl](https://github.com/lspestrip/Stripeline.jl).

- https://github.com/ziotom78/Healpix.jl/actions/runs/3043392306/jobs/4902605307
- https://github.com/lspestrip/Stripeline.jl/actions/runs/3030659143/jobs/4876980885

Unfortunately, I cannot reproduce the failure locally: I downloaded Julia nightly on my laptop and re-ran these tests, but they completed fine (just like Julia 1.6 and 1.8).

**Comment by giordano** [comment] 2022-10-07 15:33
We're seeing similar hangs in MPI.jl, for example all jobs on nightly in https://github.com/JuliaParallel/MPI.jl/actions/runs/3201031150 are timing out.  But hard to say whether it's related, not clear what the problem is exactly.  CC: @simonbyrne

**Comment by KristofferC** [comment] 2022-12-21 20:21
I'm not sure what can be done here. Does anyone have something that can be reproduced?

**Comment by giordano** [comment] 2022-12-21 20:27
Healpix tests used to reproducibly time out on GitHub Actions, but now CI isn't running anymore on nightly because it was useless, so I don't know what's going on now.

**Comment by gbaraldi** [comment] 2022-12-21 20:31
At least MPI seems to pass tests on nightly, so maybe this got fixed?

**Comment by giordano** [comment] 2022-12-21 20:39
Yeah, MPI had a different problem, #47472, addressed by https://github.com/JuliaParallel/MPI.jl/pull/680.

**Comment by giordano** [comment] 2022-12-21 20:41
I just ran Healpix tests locally on
```
Julia Version 1.10.0-DEV.170
Commit 077314063b* (2022-12-21 18:55 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.6.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```
and they hang at the `Map I/O` test set.  `Ctrl+C`-ing it shows and endless stacktrace
```
[...]
intersect_unionall_ at /Users/mose/repo/julia/src/subtype.c:2645
intersect_unionall at /Users/mose/repo/julia/src/subtype.c:2690
intersect at /Users/mose/repo/julia/src/subtype.c:0
intersect_all at /Users/mose/repo/julia/src/subtype.c:3298
intersect_aside at /Users/mose/repo/julia/src/subtype.c:2147
intersect_var at /Users/mose/repo/julia/src/subtype.c:0
intersect at /Users/mose/repo/julia/src/subtype.c:0
intersect at /Users/mose/repo/julia/src/subtype.c:0
intersect_all at /Users/mose/repo/julia/src/subtype.c:3298
intersect_aside at /Users/mose/repo/julia/src/subtype.c:2147
intersect_var at /Users/mose/repo/julia/src/subtype.c:0
[...]
```
(it exceeds the scrollbar in iTerm2).  Looks fairly reproducible to me.

**Comment by gbaraldi** [comment] 2022-12-21 20:52
Oh, I thought this was a memory related hang, not something different.

**Comment by giordano** [comment] 2022-12-21 20:56
They're also hanging in pkgeval: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2022-12/20/Healpix.primary.log

**Comment by gbaraldi** [comment] 2022-12-21 21:11
playing a bit in lldb, it seems we are stuck in a call to `jl_type_intersection(t2, t1);` where `t1 = Tuple{typeof(Base.convert), Type{AbstractArray{Union{Nothing, T}, 1}}, AbstractArray{var"#s95", 1} where var"#s95"} where T` and `t2 = Tuple{typeof(Base.convert), Type{T}, T} where T<:(AbstractArray{Union{Nothing, T}, 1} where T)`

**Comment by giordano** [comment] 2022-12-21 21:13
Reproducer is
```
using Healpix
Healpix.readPolarizedMapFromFITS(pkgdir(Healpix, "test", "pol_float_map.fits"), 1, Float32)
```

**Comment by DilumAluthge** [comment] 2022-12-21 21:14
Does an assert build of Julia give anything helpful?

**Comment by gbaraldi** [comment] 2022-12-21 21:16
I believe my build already has them on :)

**Comment by IanButterworth** [comment] 2022-12-22 02:26
Just a note to suggest that the peek profiler might be helpful to diagnose the issue here

**Comment by maleadt** [comment] 2022-12-22 08:35
MWE:

```julia
julia> x = Tuple{typeof(Base.convert), Type{T}, T} where T<:(AbstractArray{Union{Nothing, T}, 1} where T)
Tuple{typeof(convert), Type{T}, T} where T<:(AbstractArray{Union{Nothing, T}, 1} where T)

julia> y = Tuple{typeof(Base.convert), Type{AbstractArray{Union{Nothing, T}, 1}}, AbstractArray{var"#s95", 1} where var"#s95"} where T
Tuple{typeof(convert), Type{AbstractArray{Union{Nothing, T}, 1}}, AbstractVector} where T

julia> typeintersect(x, y)
```

Started hanging on 1.7, so this specifically doesn't seem like a regression.

**Comment by maleadt** [comment] 2022-12-22 08:50
Slightly shorter:

```julia
x = Tuple{typeof(convert), Type{T}, T} where T<:(AbstractArray{Union{Nothing, T}} where T)
y = Tuple{typeof(convert), Type{AbstractArray{Union{Nothing, T}}}, AbstractArray} where T
typeintersect(x, y)
```

**Comment by giordano** [comment] 2022-12-22 09:20
> Started hanging on 1.7, so this specifically doesn't seem like a regression.

The `Healpix.jl` reproducer
```julia
using Healpix
Healpix.readPolarizedMapFromFITS(pkgdir(Healpix, "test", "pol_float_map.fits"), 1, Float32)
```
works fine in v1.8.3 though.

**Comment by maleadt** [comment] 2022-12-22 13:12
```
7ad0e3deae79934e75c7d2d886ea744f7ee1bef6 is the first bad commit
commit 7ad0e3deae79934e75c7d2d886ea744f7ee1bef6
Author: Jeff Bezanson <jeff.bezanson@gmail.com>
Date:   Tue Apr 26 18:25:40 2022 -0400

    lower `new()` to reference the called object instead of re-creating it with apply_type (#44664)

    addresses #36384

 src/julia-syntax.scm | 90 +++++++++++++++++++++++++++++++---------------------
 test/syntax.jl       |  8 +++++
 2 files changed, 62 insertions(+), 36 deletions(-)
```

cc @JeffBezanson; although fixing the typeintersect hang is probably a better solution.

**Comment by gbaraldi** [comment] 2022-12-22 13:56
inside lldb it seems the hang comes from calling intersect with the following types, which seem to be kind of broken
`x = Union{Nothing, T} where T<:Union{Nothing, T}` and `y = Union{Nothing, T<:Union{Nothing, T}}`

**Comment by gbaraldi** [comment] 2022-12-22 14:05
A suspicious call to me seems to be 
```c
frame #1759: 0x00000001015a64b4 libjulia-internal.1.10.dylib`intersect(x=0x000000010b96d770, y=0x000000010b96d710, e=0x000000016eef5ab0, param=0) at subtype.c:0:13 [opt]
   2989	// (as opposed to being outside any type constructor, or comparing variable bounds).
   2990	// this is used to record the positions where type variables occur for the
   2991	// diagonal rule (record_var_occurrence).
-> 2992	static jl_value_t *intersect(jl_value_t *x, jl_value_t *y, jl_stenv_t *e, int param)
   2993	{
   2994	    if (x == y) return y;
   2995	    if (jl_is_typevar(x)) {
```
Where doing `jl_(x)` gives `Union{Nothing, T<:Union{Nothing, T}}` and jl_(y) gives `Union{Nothing, T<:Union{Nothing, T}}` But they are't the same value it seems

**Comment by vtjnash** [comment] 2022-12-22 18:25
`T<:Union{Nothing, T}}` is probably malformed in that a type should not be a subtype of itself. Sounds like a similar issue to one we have encountered elsewhere (e.g. https://github.com/JuliaLang/julia/pull/47877#issuecomment-1360275047 and https://github.com/JuliaLang/julia/pull/47868)

**Closed** 2023-01-04 08:09 UTC
Labels: types and dispatch
