### ISSUE TITLE
Crash after LibGit2 initialization error with faulty SSL_CERT_DIR

### ISSUE THREAD

**Issue by m-j-w** [JuliaLang/julia#21296] opened 2017-04-06 18:37 UTC
While trying to find a solution to a behind a proxy situation, I stumbled over this `fatal: error thrown and no exception handler available.` followed by a crash, happening on Julia 0.6 with a three weeks old master and todays master.

Reproducible by setting the environment variables `SSL_CERT_DIR` or `SSL_CERT_FILE` to a wrong destination and launching Julia:
```
$ SSL_CERT_DIR=/tmp julia-dev
fatal: error thrown and no exception handler available.
Base.InitError(mod=:LibGit2, error=ErrorException("error initializing LibGit2 module"))
rec_backtrace at /home/mjw/src/julia-master/src/stackwalk.c:84
record_backtrace at /home/mjw/src/julia-master/src/task.c:239
jl_throw at /home/mjw/src/julia-master/src/task.c:565
__init__ at ./libgit2/libgit2.jl:800
unknown function (ip: 0x7f822f986268)
jl_call_fptr_internal at /home/mjw/src/julia-master/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/mjw/src/julia-master/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/mjw/src/julia-master/src/gf.c:1913
jl_apply at /home/mjw/src/julia-master/src/julia.h:1416 [inlined]
jl_module_run_initializer at /home/mjw/src/julia-master/src/toplevel.c:85
_julia_init at /home/mjw/src/julia-master/src/init.c:704
julia_init at /home/mjw/src/julia-master/src/task.c:292
main at /home/mjw/src/julia-master/ui/repl.c:259
__libc_start_main at /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:291
unknown function (ip: 0x4016b8)
```
Also, same issue:
```
$ SSL_CERT_FILE=/tmp julia-dev
fatal: error thrown and no exception handler available.
Base.InitError(mod=:LibGit2, error=ErrorException("error initializing LibGit2 module"))
rec_backtrace at /home/mjw/src/julia-master/src/stackwalk.c:84
record_backtrace at /home/mjw/src/julia-master/src/task.c:239
jl_throw at /home/mjw/src/julia-master/src/task.c:565
__init__ at ./libgit2/libgit2.jl:800
unknown function (ip: 0x7f81d8082268)
jl_call_fptr_internal at /home/mjw/src/julia-master/src/julia_internal.h:326 [inlined]
jl_call_method_internal at /home/mjw/src/julia-master/src/julia_internal.h:345 [inlined]
jl_apply_generic at /home/mjw/src/julia-master/src/gf.c:1913
jl_apply at /home/mjw/src/julia-master/src/julia.h:1416 [inlined]
jl_module_run_initializer at /home/mjw/src/julia-master/src/toplevel.c:85
_julia_init at /home/mjw/src/julia-master/src/init.c:704
julia_init at /home/mjw/src/julia-master/src/task.c:292
main at /home/mjw/src/julia-master/ui/repl.c:259
__libc_start_main at /build/glibc-9tT8Do/glibc-2.23/csu/../csu/libc-start.c:291
unknown function (ip: 0x4016b8)
```

**Comment by simonbyrne** [comment] 2017-04-07 08:06
duplicate of #20439 and #18693

**Closed** 2017-04-07 08:12 UTC
Labels: libgit2
