### ISSUE TITLE
New segfault on 32-bit Julia 1.8.2

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#46999] opened 2022-10-01 12:49 UTC
I see this segfault reliably when trying to build the Fedora RPM on 32-bit. Unfortunately I cannot debug this on the build machine, I would have to set up a 32-bit VM.

Seems somewhat similar to https://github.com/JuliaLang/julia/issues/46986.

Julia 1.8.0 builds fine on 32-bit, but I haven't tried 1.8.1.

```
 /builddir/build/BUILD/julia-1.8.2/build/usr/bin/julia --check-bounds=yes --startup-file=no --depwarn=error ./runtests.jl default
┌ Warning: Networking unavailable: Skipping tests [Artifacts, Downloads, LazyArtifacts, LibCURL, LibGit2, Sockets, download]
└ @ Main ~/build/BUILD/julia-1.8.2/test/choosetests.jl:187
Running parallel tests with:
  nworkers() = 6
  nthreads() = 1
  Sys.CPU_THREADS = 6
  Sys.total_memory() = 23.465 GiB
  Sys.free_memory() = 21.685 GiB
Test                                (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
LinearAlgebra/triangular                 (2) |        started at 2022-10-01T10:17:20.657
LinearAlgebra/dense                      (4) |        started at 2022-10-01T10:17:20.816
LinearAlgebra/matmul                     (5) |        started at 2022-10-01T10:17:20.917
LinearAlgebra/qr                         (3) |        started at 2022-10-01T10:17:20.918
LinearAlgebra/schur                      (6) |        started at 2022-10-01T10:17:20.918
LinearAlgebra/special                    (7) |        started at 2022-10-01T10:17:20.918
LinearAlgebra/schur                      (6) |    54.73 |   3.19 |  5.8 |    2424.56 |   317.59
LinearAlgebra/eigen                      (6) |        started at 2022-10-01T10:18:16.110
      From worker 7:	
      From worker 7:	signal (11): Segmentation fault
      From worker 7:	in expression starting at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/LinearAlgebra/test/special.jl:228
      From worker 7:	gc_try_setmark at /builddir/build/BUILD/julia-1.8.2/src/gc.c:1764 [inlined]
      From worker 7:	gc_mark_scan_obj8 at /builddir/build/BUILD/julia-1.8.2/src/gc.c:2006 [inlined]
      From worker 7:	gc_mark_loop at /builddir/build/BUILD/julia-1.8.2/src/gc.c:2302
      From worker 7:	_jl_gc_collect at /builddir/build/BUILD/julia-1.8.2/src/gc.c:3098
      From worker 7:	ijl_gc_collect at /builddir/build/BUILD/julia-1.8.2/src/gc.c:3327
      From worker 7:	maybe_collect at /builddir/build/BUILD/julia-1.8.2/src/gc.c:903 [inlined]
      From worker 7:	jl_gc_pool_alloc_inner at /builddir/build/BUILD/julia-1.8.2/src/gc.c:1247 [inlined]
      From worker 7:	jl_gc_pool_alloc_noinline at /builddir/build/BUILD/julia-1.8.2/src/gc.c:1306 [inlined]
      From worker 7:	jl_gc_alloc_ at /builddir/build/BUILD/julia-1.8.2/src/julia_internal.h:369 [inlined]
      From worker 7:	jl_gc_alloc at /builddir/build/BUILD/julia-1.8.2/src/gc.c:3372
      From worker 7:	_new_array_ at /builddir/build/BUILD/julia-1.8.2/src/array.c:134 [inlined]
      From worker 7:	_new_array at /builddir/build/BUILD/julia-1.8.2/src/array.c:198 [inlined]
      From worker 7:	ijl_alloc_array_2d at /builddir/build/BUILD/julia-1.8.2/src/array.c:443
      From worker 7:	Array at ./boot.jl:461 [inlined]
      From worker 7:	Array at ./boot.jl:469 [inlined]
      From worker 7:	similar at ./abstractarray.jl:806 [inlined]
      From worker 7:	similar at ./abstractarray.jl:794 [inlined]
      From worker 7:	* at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/qr.jl:682 [inlined]
      From worker 7:	* at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/LinearAlgebra/src/uniformscaling.jl:260 [inlined]
      From worker 7:	macro expansion at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Test/src/Test.jl:464 [inlined]
      From worker 7:	macro expansion at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/LinearAlgebra/test/special.jl:235 [inlined]
      From worker 7:	macro expansion at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Test/src/Test.jl:1357 [inlined]
      From worker 7:	top-level scope at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/LinearAlgebra/test/special.jl:229
      From worker 7:	jl_toplevel_eval_flex at /builddir/build/BUILD/julia-1.8.2/src/toplevel.c:897
      From worker 7:	jl_eval_module_expr at /builddir/build/BUILD/julia-1.8.2/src/toplevel.c:203 [inlined]
      From worker 7:	jl_toplevel_eval_flex at /builddir/build/BUILD/julia-1.8.2/src/toplevel.c:709
      From worker 7:	jl_toplevel_eval_flex at /builddir/build/BUILD/julia-1.8.2/src/toplevel.c:850
      From worker 7:	ijl_toplevel_eval at /builddir/build/BUILD/julia-1.8.2/src/toplevel.c:915
      From worker 7:	ijl_toplevel_eval_in at /builddir/build/BUILD/julia-1.8.2/src/toplevel.c:965
      From worker 7:	eval at ./boot.jl:368 [inlined]
      From worker 7:	include_string at ./loading.jl:1428
      From worker 7:	_jl_invoke at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2348 [inlined]
      From worker 7:	ijl_apply_generic at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2549
      From worker 7:	_include at ./loading.jl:1488
      From worker 7:	include at ./Base.jl:419 [inlined]
      From worker 7:	macro expansion at /builddir/build/BUILD/julia-1.8.2/test/testdefs.jl:24 [inlined]
      From worker 7:	macro expansion at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Test/src/Test.jl:1357 [inlined]
      From worker 7:	macro expansion at /builddir/build/BUILD/julia-1.8.2/test/testdefs.jl:23 [inlined]
      From worker 7:	macro expansion at ./timing.jl:463 [inlined]
      From worker 7:	#runtests#1 at /builddir/build/BUILD/julia-1.8.2/test/testdefs.jl:21
      From worker 7:	runtests##kw at /builddir/build/BUILD/julia-1.8.2/test/testdefs.jl:5 [inlined]
      From worker 7:	runtests##kw at /builddir/build/BUILD/julia-1.8.2/test/testdefs.jl:5
      From worker 7:	unknown function (ip: 0xc42457c4)
      From worker 7:	_jl_invoke at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2367 [inlined]
      From worker 7:	ijl_apply_generic at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2549
      From worker 7:	jl_apply at /builddir/build/BUILD/julia-1.8.2/src/julia.h:1839 [inlined]
      From worker 7:	jl_f__call_latest at /builddir/build/BUILD/julia-1.8.2/src/builtins.c:774
      From worker 7:	_jl_invoke at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2348 [inlined]
      From worker 7:	ijl_apply_generic at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2549
      From worker 7:	jl_apply at /builddir/build/BUILD/julia-1.8.2/src/julia.h:1839 [inlined]
      From worker 7:	do_apply at /builddir/build/BUILD/julia-1.8.2/src/builtins.c:730
      From worker 7:	#invokelatest#2 at ./essentials.jl:731
      From worker 7:	_jl_invoke at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2367 [inlined]
      From worker 7:	ijl_apply_generic at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2549
      From worker 7:	jl_apply at /builddir/build/BUILD/julia-1.8.2/src/julia.h:1839 [inlined]
      From worker 7:	do_apply at /builddir/build/BUILD/julia-1.8.2/src/builtins.c:730
      From worker 7:	invokelatest##kw at ./essentials.jl:726
      From worker 7:	_jl_invoke at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2367 [inlined]
      From worker 7:	ijl_apply_generic at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2549
      From worker 7:	jl_apply at /builddir/build/BUILD/julia-1.8.2/src/julia.h:1839 [inlined]
      From worker 7:	do_apply at /builddir/build/BUILD/julia-1.8.2/src/builtins.c:730
      From worker 7:	#110 at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:285
      From worker 7:	run_work_thunk at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:70
      From worker 7:	macro expansion at /builddir/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:285 [inlined]
      From worker 7:	#109 at ./task.jl:484
      From worker 7:	unknown function (ip: 0xc4241b82)
      From worker 7:	_jl_invoke at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2367 [inlined]
      From worker 7:	ijl_apply_generic at /builddir/build/BUILD/julia-1.8.2/src/gf.c:2549
      From worker 7:	jl_apply at /builddir/build/BUILD/julia-1.8.2/src/julia.h:1839 [inlined]
      From worker 7:	start_task at /builddir/build/BUILD/julia-1.8.2/src/task.c:931
      From worker 7:	Allocations: 170783355 (Pool: 170740162; Big: 43193); GC: 310
LinearAlgebra/special                    (7) |         failed at 2022-10-01T10:19:05.017
ProcessExitedException(7)
Stacktrace:
  [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
    @ Base ./task.jl:871
  [2] wait()
    @ Base ./task.jl:931
  [3] wait(c::Base.GenericCondition{ReentrantLock})
    @ Base ./condition.jl:124
  [4] take_buffered(c::Channel{Any})
    @ Base ./channels.jl:416
  [5] take!(c::Channel{Any})
    @ Base ./channels.jl:410
  [6] take!(::Distributed.RemoteValue)
    @ Distributed ~/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:726
  [7] remotecall_fetch(::Function, ::Distributed.Worker, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, UInt128, Tuple{Symbol}, NamedTuple{(:seed,), Tuple{UInt128}}})
    @ Distributed ~/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:461
  [8] remotecall_fetch(::Function, ::Int32, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, UInt128, Tuple{Symbol}, NamedTuple{(:seed,), Tuple{UInt128}}})
    @ Distributed ~/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:492
  [9] macro expansion
    @ ~/build/BUILD/julia-1.8.2/test/runtests.jl:260 [inlined]
 [10] (::var"#43#55"{Vector{Task}, var"#print_testworker_errored#51"{ReentrantLock, Int32, Int32}, var"#print_testworker_stats#49"{ReentrantLock, Int32, Int32, Int32, Int32, Int32, Int32}, Vector{Any}, Dict{String, DateTime}})()
    @ Main ./task.jl:484
Worker 7 terminated.
UNHANDLED TASK ERROR: EOFError: read end of file
Stacktrace:
 [1] (::Base.var"#wait_locked#680")(s::TCPSocket, buf::IOBuffer, nb::Int32)
   @ Base ./stream.jl:945
 [2] unsafe_read(s::TCPSocket, p::Ptr{UInt8}, nb::UInt32)
   @ Base ./stream.jl:953
 [3] unsafe_read
   @ ./io.jl:759 [inlined]
 [4] unsafe_read(s::TCPSocket, p::Base.RefValue{NTuple{4, Int32}}, n::Int32)
   @ Base ./io.jl:758
 [5] read!
   @ ./io.jl:760 [inlined]
 [6] deserialize_hdr_raw
   @ ~/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/messages.jl:167 [inlined]
 [7] message_handler_loop(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
   @ Distributed ~/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:172
 [8] process_tcp_streams(r_stream::TCPSocket, w_stream::TCPSocket, incoming::Bool)
   @ Distributed ~/build/BUILD/julia-1.8.2/build/usr/share/julia/stdlib/v1.8/Distributed/src/process_messages.jl:133
 [9] (::Distributed.var"#103#104"{TCPSocket, TCPSocket, Bool})()
   @ Distributed ./task.jl:484
```

**Comment by vtjnash** [comment] 2023-02-06 15:31
Duplicate of https://github.com/JuliaLang/julia/issues/47686

**Closed by vtjnash** 2023-02-06 15:31 UTC
Labels: regression, 32-bit
