### ISSUE TITLE
Inconsistent @distributed vcat/hcat

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#45492] opened 2022-05-28 08:09 UTC
Typically, `vcat(...)` and `@distributed vcat` give the same result:
```julia
julia> using Distributed

julia> vcat(1, 2, 3)
3-element Vector{Int64}:
 1
 2
 3

julia> @distributed vcat for i in 1:3; i; end
3-element Vector{Int64}:
 1
 2
 3
```
But the return type of the latter suddenly changes when there is only one element:
```julia
julia> vcat(1)
1-element Vector{Int64}:
 1

julia> @distributed vcat for i in 1:1; i; end
1
```
Here, `@distributed` returns a plain number instead of an array. This doesn't make sense to make and seems inconsistent: why not always return an array?

This inconsistency originally noticed in the wild at https://github.com/ahwillia/NonNegLeastSquares.jl/issues/34.

<details>
<summary>versioninfo()</summary>

```
julia> versioninfo()
Julia Version 1.8.0-beta3
Commit 3e092a2521 (2022-03-29 15:42 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_PKG_USE_CLI_GIT = true
```

</details>

**Comment by jishnub** [comment] 2022-05-28 08:13
Related: https://github.com/JuliaLang/julia/issues/34380

**Comment by JoelTrent** [comment] 2023-05-10 06:26
A workaround that will always work is for the `i` to be concatenated in a distributed for loop to be a vector containing `i` rather than just `i`. I suspect this extra allocation may impact performance if every iteration is very fast, but it's unlikely to be a big deal otherwise. 

For 1 element:
```julia
julia> @distributed vcat for i in 1:1; [i]; end
1-element Vector{Int64}:
1
```

For multiple elements:
```julia
julia> @distributed vcat for i in 1:3; [i]; end
3-element Vector{Int64}:
1
2
3
```

**Comment by vtjnash** [comment] 2024-02-11 01:06
Seems to be actually just a duplicate of https://github.com/JuliaLang/julia/issues/34380

**Closed by vtjnash** 2024-02-11 01:06 UTC
Labels: parallel, arrays
