### ISSUE TITLE
Wrong result when multiplying a very small number and a very big one using ^

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#27355] opened 2018-05-31 23:13 UTC
Hi guys,

I was implementing a algorithm, comparing to MATLAB version, and I found a very strange behavior in Julia. I need to perform the following multiplication:

    4.604716014154575e-19*(10000000000)^2 = -46.047160141545149

First, I was using the `^`, but it was providing a wrong answer:

```julia
julia> 4.604716014154575e-19*10000000000^2
3.5761512189350633
```

If I drop the `^` and multiply two times, then the result is correct:

```julia
julia> 4.604716014154575e-19*10000000000*10000000000
46.04716014154576
```

I tested it in Julia v0.6.2 and v0.6.3 in macOS and Linux with the same behavior. I think the operation `10000000000^2` is overflowing `Int64` and with `^` this is computed first. On the other hand, using the multiplication, the first operation is `4.604716014154575e-19*10000000000`, which does not cause any overflow.

However, I think Julia should be able to handle that just as MATLAB can. At least a warning about the overflow should be printed. Otherwise, sometimes can be very difficult to debug this. What do you think?

**Comment by mbauman** [comment] 2018-05-31 23:18
Duplicate of #855

**Closed by mbauman** 2018-05-31 23:18 UTC

**Comment by mbauman** [comment] 2018-05-31 23:20
Note that this works in Matlab because the literal `10000000000` is treated as a floating point number.  To duplicate that behavior you can do `4.604716014154575e-19*10000000000.0^2`.

**Comment by ViralBShah** [comment] 2018-06-01 00:05
Its best to ask these questions on discourse.julialang.org.

**Comment by ronisbr** [comment] 2018-06-01 01:31
Sorry but it really looked like a bug to me. Actually, IMHO, I think this should be considered a bug.

**Comment by StefanKarpinski** [comment] 2018-06-01 15:38
You may not like it but it is not a bug as it is both intentional and thoroughly documented.

**Comment by ronisbr** [comment] 2018-06-01 15:40
Ok then...
