### ISSUE TITLE
fail to build on ubuntu

### ISSUE THREAD

**Issue by xiaoyuanzh** [JuliaLang/julia#32200] opened 2019-05-31 04:11 UTC
gemm.c: In function ‘sgemm’:
../common_param.h:849:23: error: ‘GEMM_DEFAULT_OFFSET_A’ undeclared (first use in this function)
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
gemm.c:375:37: note: in expansion of macro ‘GEMM_OFFSET_A’
   sa = (XFLOAT *)((BLASLONG)buffer +GEMM_OFFSET_A);
                                     ^
../common_param.h:849:23: note: each undeclared identifier is reported only once for each function it appears in
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
gemm.c:375:37: note: in expansion of macro ‘GEMM_OFFSET_A’
   sa = (XFLOAT *)((BLASLONG)buffer +GEMM_OFFSET_A);
                                     ^
../common_param.h:859:18: error: ‘SGEMM_DEFAULT_P’ undeclared (first use in this function)
 #define SGEMM_P  SGEMM_DEFAULT_P
                  ^
../common_param.h:930:18: note: in expansion of macro ‘SGEMM_P’
 #define GEMM_P   SGEMM_P
                  ^
gemm.c:376:37: note: in expansion of macro ‘GEMM_P’
   sb = (XFLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                     ^
../common_param.h:860:18: error: ‘SGEMM_DEFAULT_Q’ undeclared (first use in this function)
 #define SGEMM_Q  SGEMM_DEFAULT_Q

And my CPU  is 
Version: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
                Reference Code - CPU

**Comment by Keno** [comment] 2019-06-03 17:53
What version of julia are you trying to build and what flags are you passing? We don't build OpenBLAS by default anymore in favor of downloading binaries. Also, that particular error looks like something that was fixed quite some time ago in favor of a more intelligible error message.

**Comment by Keno** [comment] 2019-06-07 20:26
Closing without a way to reproduce, but feel free to comment here with more info and we can re-open.

**Closed by Keno** 2019-06-07 20:26 UTC
