### ISSUE TITLE
`could not load library "libsuitesparseconfig"` in `Base.runtests()`

### ISSUE THREAD

**Issue by kbrohart** [JuliaLang/julia#13703] opened 2015-10-21 15:45 UTC
```
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 5:	     * linalg/matmul         in  10.97 seconds, maxrss  216.77 MB
	From worker 5:	     * linalg/schur          in   9.59 seconds, maxrss  239.47 MB
	From worker 5:	     * linalg/special        in   3.51 seconds, maxrss  252.12 MB
	From worker 5:	     * linalg/eigen          in   7.75 seconds, maxrss  286.09 MB
	From worker 5:	     * linalg/bunchkaufman   in   4.48 seconds, maxrss  306.19 MB
	From worker 5:	     * linalg/svd            in   5.28 seconds, maxrss  314.95 MB
	From worker 4:	     * linalg/dense          in  53.87 seconds, maxrss  379.51 MB
	From worker 3:	     * linalg/qr             in  55.18 seconds, maxrss  439.10 MB
	From worker 5:	     * linalg/lapack         in  17.54 seconds, maxrss  374.41 MB
	From worker 4:	     * linalg/tridiag        in   8.56 seconds, maxrss  395.71 MB
	From worker 4:	     * linalg/pinv           in   5.19 seconds, maxrss  455.60 MB
	From worker 4:	     * linalg/givens         in   1.17 seconds, maxrss  455.60 MB
	From worker 3:	     * linalg/bidiag         in  13.73 seconds, maxrss  479.81 MB
	From worker 5:	     * linalg/diagonal       in  18.36 seconds, maxrss  442.35 MB
	From worker 3:	     * linalg/lu             in  15.97 seconds, maxrss  565.83 MB
	From worker 5:	     * linalg/symmetric      in   7.66 seconds, maxrss  461.52 MB
	From worker 5:	     * linalg/uniformscaling in   1.27 seconds, maxrss  462.55 MB
	From worker 3:	     * linalg/generic        in   2.99 seconds, maxrss  567.00 MB
	From worker 4:	     * linalg/cholesky       in  19.59 seconds, maxrss  477.09 MB
	From worker 4:	     * keywordargs           in   0.98 seconds, maxrss  478.36 MB
	From worker 5:	     * linalg/arnoldi        in   7.05 seconds, maxrss  491.54 MB
	From worker 5:	     * printf                in   2.76 seconds, maxrss  496.41 MB
	From worker 5:	     * char                  in   0.51 seconds, maxrss  496.88 MB
	From worker 3:	     * core                  in  11.56 seconds, maxrss  599.76 MB
	From worker 3:	     * triplequote           in   0.15 seconds, maxrss  599.88 MB
	From worker 2:	     * linalg/triangular     in 100.86 seconds, maxrss  538.02 MB
	From worker 3:	     * unicode               in  11.15 seconds, maxrss  600.04 MB
	From worker 5:	     * string                in  14.00 seconds, maxrss  607.13 MB
	From worker 5:	     * hashing               in   4.93 seconds, maxrss  616.96 MB
	From worker 5:	     * remote                in   0.33 seconds, maxrss  616.96 MB
	From worker 5:	     * iobuffer              in   0.93 seconds, maxrss  616.96 MB
	From worker 5:	     * staged                in   0.84 seconds, maxrss  616.96 MB
	From worker 3:	     * dict                  in   7.99 seconds, maxrss  600.04 MB
	From worker 3:	     * tuple                 in   0.88 seconds, maxrss  600.18 MB
	From worker 5:	     * arrayops              in  25.10 seconds, maxrss  718.11 MB
	From worker 2:	     * dates                 in  42.93 seconds, maxrss  589.87 MB
	From worker 4:	     * numbers               in  55.56 seconds, maxrss  698.83 MB
	From worker 5:	     * reduce                in   2.96 seconds, maxrss  736.35 MB
	From worker 4:	     * random                in  10.21 seconds, maxrss  699.25 MB
	From worker 2:	     * reducedim             in  11.69 seconds, maxrss  626.84 MB
	From worker 4:	     * intfuncs              in   0.51 seconds, maxrss  701.12 MB
	From worker 2:	     * simdloop              in   1.23 seconds, maxrss  626.84 MB
	From worker 4:	     * blas                  in   4.84 seconds, maxrss  720.41 MB
	From worker 5:	     * abstractarray         in  19.37 seconds, maxrss  739.54 MB
	From worker 5:	     * copy                  in   1.04 seconds, maxrss  739.54 MB
	From worker 5:	     * math                  in  10.51 seconds, maxrss  739.54 MB
	From worker 5:	     * fastmath              in   3.15 seconds, maxrss  739.54 MB
	From worker 5:	     * functional            in   0.84 seconds, maxrss  739.54 MB
	From worker 5:	     * operators             in   0.39 seconds, maxrss  739.54 MB
	From worker 5:	     * path                  in   1.87 seconds, maxrss  739.54 MB
	From worker 5:	     * ccall                 in   1.70 seconds, maxrss  750.29 MB
	From worker 5:	     * parse                 in   1.12 seconds, maxrss  750.45 MB
	From worker 5:	     * loading               in   0.12 seconds, maxrss  750.45 MB
	From worker 5:	     * bigint                in   2.22 seconds, maxrss  750.45 MB
	From worker 5:	     * sorting               in  21.29 seconds, maxrss  833.49 MB
	From worker 4:	     * bitarray              in  50.19 seconds, maxrss  804.73 MB
	From worker 4:	     * spawn                       [stdio passthrough ok]
	From worker 4:	Test Failed
	From worker 4:	  Expression: readall(pipeline(@cmd("\$exename -f -e 'println(STDERR,\"Hello World\")'"),stderr=@cmd("cat"))) == "Hello World\n"
	From worker 4:	   Evaluated: "WARNING: Error during initialization of module CHOLMOD:\nErrorException(\"could not load library \"libsuitesparseconfig\"\ndlopen(libsuitesparseconfig.dylib, 1): image not found\")\nHello World\n" == "Hello World\n"
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 5:	     * statistics            in   7.20 seconds, maxrss  849.67 MB
	From worker 5:	     * backtrace             in   0.25 seconds, maxrss  849.67 MB
	From worker 2:	     * sparse                in  60.49 seconds, maxrss  760.35 MB
	From worker 5:	     * priorityqueue         in   0.97 seconds, maxrss  849.67 MB
	From worker 6:	     * version               in   1.53 seconds, maxrss  152.68 MB
	From worker 6:	     * resolve               in   3.33 seconds, maxrss  174.52 MB
	From worker 5:	     * mmap                  in   5.10 seconds, maxrss  849.67 MB
	From worker 5:	     * mpfr                  in   3.20 seconds, maxrss  849.67 MB
	From worker 6:	     * pollfd                in   3.36 seconds, maxrss  176.60 MB
	From worker 6:	     * complex               in   5.85 seconds, maxrss  193.43 MB
	From worker 5:	     * broadcast             in   7.89 seconds, maxrss  852.38 MB
	From worker 5:	     * floatapprox           in   0.29 seconds, maxrss  852.77 MB
	From worker 6:	     * socket                in   2.45 seconds, maxrss  199.35 MB
The following 'Returned code...' warnings indicate normal behavior:
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
WARNING: Returned code may not match what actually runs.
	From worker 6:	     * reflection            in   1.47 seconds, maxrss  209.38 MB
	From worker 6:	     * regex                 in   0.70 seconds, maxrss  212.46 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 6:	     * float16               in   1.35 seconds, maxrss  215.75 MB
	From worker 6:	     * combinatorics         in   2.16 seconds, maxrss  224.67 MB
	From worker 6:	     * sysinfo               in   1.01 seconds, maxrss  235.33 MB
	From worker 6:	     * rounding              in   0.58 seconds, maxrss  237.00 MB
	From worker 5:	     * readdlm               in  12.34 seconds, maxrss  894.95 MB
	From worker 5:	     * mod2pi                in   0.10 seconds, maxrss  895.03 MB
	From worker 5:	     * euler                 in   1.08 seconds, maxrss  906.21 MB
	From worker 2:	     * file                  in  33.82 seconds, maxrss  760.35 MB
	From worker 5:	     * show                  in   3.70 seconds, maxrss  910.13 MB
	From worker 2:	     * lineedit              in   2.46 seconds, maxrss  760.35 MB
	From worker 5:	     * replcompletions       in   2.37 seconds, maxrss  914.68 MB
	From worker 5:	     * replutil              in   1.14 seconds, maxrss  916.66 MB
	From worker 2:	     * repl                 Test Failed
	From worker 5:	     * sets                  in   1.92 seconds, maxrss  920.60 MB
	From worker 2:	  Expression: output == "julia> "
	From worker 2:	   Evaluated: "WARNING: Error during initialization of module CHOLMOD:\r\nErrorException(\"could not load library \"libsuitesparseconfig\"\r\ndlopen(libsuitesparseconfig.dylib, 1): image not found\")\r\njulia> " == "julia> "
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 7:	     * goto                  in   0.30 seconds, maxrss  144.70 MB
	From worker 7:	     * llvmcall              in   0.08 seconds, maxrss  145.88 MB
	From worker 5:	     * test                  in   6.13 seconds, maxrss  930.45 MB
	From worker 7:	     * grisu                 in   4.00 seconds, maxrss  161.35 MB
	From worker 7:	     * meta                  in   0.25 seconds, maxrss  163.56 MB
	From worker 5:	     * nullable              in   1.69 seconds, maxrss  946.51 MB
	From worker 7:	     * profile               in   3.00 seconds, maxrss  175.52 MB
	From worker 7:	     * docs                  in   2.63 seconds, maxrss  188.43 MB
	From worker 5:	     * libgit2              Test Summary: | Pass  Total
	From worker 5:	libgit2       |   79     79
	From worker 5:	 in   7.07 seconds, maxrss  983.16 MB
	From worker 6:	     * ranges                in  30.06 seconds, maxrss  271.84 MB
	From worker 5:	     * base64                in   0.30 seconds, maxrss  983.16 MB
	From worker 5:	     * functors              in   0.40 seconds, maxrss  983.16 MB
	From worker 7:	     * markdown              in   2.51 seconds, maxrss  197.46 MB
	From worker 7:	     * enums                 in   1.00 seconds, maxrss  199.78 MB
	From worker 6:	     * serialize             in   2.80 seconds, maxrss  272.86 MB
	From worker 6:	     * i18n                  in   0.02 seconds, maxrss  272.89 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 6:	     * workspace             in   0.44 seconds, maxrss  273.04 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 6:	     * libdl                 in   1.45 seconds, maxrss  274.21 MB
	From worker 6:	     * int                   in   1.02 seconds, maxrss  278.09 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 6:	     * intset                in   0.64 seconds, maxrss  278.43 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 6:	     * floatfuncs            in   1.40 seconds, maxrss  279.06 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 5:	     * misc                  in  15.80 seconds, maxrss 1027.14 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 7:	     * cmdlineargs          Test Failed
	From worker 7:	  Expression: readchomp(out) == "WARNING: Foo.Deprecated is deprecated.\n  likely near no file:5"
	From worker 7:	   Evaluated: "WARNING: Error during initialization of module CHOLMOD:\nErrorException(\"could not load library \"libsuitesparseconfig\"\ndlopen(libsuitesparseconfig.dylib, 1): image not found\")\nWARNING: Foo.Deprecated is deprecated.\n  likely near no file:5" == "WARNING: Foo.Deprecated is deprecated.\n  likely near no file:5"
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 5:	     * fft                   in  14.45 seconds, maxrss 1062.80 MB
	From worker 6:	     * parallel              in  26.60 seconds, maxrss  279.52 MB
	From worker 8:	     * dsp                   in  13.16 seconds, maxrss  192.13 MB
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libsuitesparseconfig"
dlopen(libsuitesparseconfig.dylib, 1): image not found")
	From worker 5:	     * examples              in  25.54 seconds, maxrss 1072.42 MB
	From worker 3:	     * subarray              in 210.98 seconds, maxrss  922.48 MB
Exception running test spawn :
On worker 4:
LoadError: There was an error during testing
 [inlined code] from error.jl:21
 in record at test.jl:295
 [inlined code] from essentials.jl:61
 in do_test at test.jl:197
 [inlined code] from essentials.jl:116
 in include_string at loading.jl:346
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 [inlined code] from util.jl:179
 in runtests at /usr/local/Cellar/julia/HEAD/share/julia/test/testdefs.jl:7
 in anonymous at /usr/local/Cellar/julia/HEAD/share/julia/test/runtests.jl:36
 in anonymous at multi.jl:898
 in run_work_thunk at multi.jl:651
 [inlined code] from multi.jl:898
 in anonymous at task.jl:59
while loading /usr/local/Cellar/julia/HEAD/share/julia/test/spawn.jl, in expression starting on line 176
Exception running test repl :
On worker 2:
LoadError: There was an error during testing
 [inlined code] from error.jl:21
 in record at test.jl:295
 [inlined code] from essentials.jl:61
 in do_test at test.jl:197
 [inlined code] from /usr/local/Cellar/julia/HEAD/share/julia/test/repl.jl:347
 in anonymous at no file:0
 [inlined code] from essentials.jl:116
 in include_string at loading.jl:346
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 [inlined code] from util.jl:179
 in runtests at /usr/local/Cellar/julia/HEAD/share/julia/test/testdefs.jl:7
 in anonymous at /usr/local/Cellar/julia/HEAD/share/julia/test/runtests.jl:36
 in anonymous at multi.jl:898
 in run_work_thunk at multi.jl:651
 [inlined code] from multi.jl:898
 in anonymous at task.jl:59
while loading /usr/local/Cellar/julia/HEAD/share/julia/test/repl.jl, in expression starting on line 319
Exception running test cmdlineargs :
On worker 7:
LoadError: There was an error during testing
 [inlined code] from error.jl:21
 in record at test.jl:295
 [inlined code] from essentials.jl:61
 in do_test at test.jl:197
 [inlined code] from /usr/local/Cellar/julia/HEAD/share/julia/test/cmdlineargs.jl:176
 in anonymous at no file:0
 [inlined code] from essentials.jl:116
 in include_string at loading.jl:346
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 [inlined code] from util.jl:179
 in runtests at /usr/local/Cellar/julia/HEAD/share/julia/test/testdefs.jl:7
 in anonymous at /usr/local/Cellar/julia/HEAD/share/julia/test/runtests.jl:36
 in anonymous at multi.jl:898
 in run_work_thunk at multi.jl:651
 [inlined code] from multi.jl:898
 in anonymous at task.jl:59
while loading /usr/local/Cellar/julia/HEAD/share/julia/test/cmdlineargs.jl, in expression starting on line 3
ERROR: LoadError: Some tests exited with errors.
 [inlined code] from error.jl:21
 in anonymous at /usr/local/Cellar/julia/HEAD/share/julia/test/runtests.jl:64
 in cd at file.jl:22
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
while loading /usr/local/Cellar/julia/HEAD/share/julia/test/runtests.jl, in expression starting on line 13
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.5.0-dev+885
Commit 976ff98* (2015-10-21 15:06 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY SANDYBRIDGE)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

 in error at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in runtests at interactiveutil.jl:411
 [inlined code] from float.jl:185
 in runtests at interactiveutil.jl:400
 in process_options at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
```

**Comment by tkelman** [comment] 2015-10-21 20:25
duplicate of https://github.com/staticfloat/homebrew-julia/issues/180

**Closed by tkelman** 2015-10-21 20:25 UTC
Labels: mac
