### ISSUE TITLE
julia version mix 0.5 nightly 0.6

### ISSUE THREAD

**Issue by oheil** [JuliaLang/julia#17923] opened 2016-08-09 19:42 UTC
Currently the nightly build versions are 0.6

Nightly build checks at appveyor and travis are done against 0.6, but at http://pkg.julialang.org/ all packages are shown to pass/fail 0.5 although they are not checked against 0.5 anymore.
Or does http://pkg.julialang.org/ just need some time to proceed to 0.6?

Download of version 0.5 (rc1) seems also not possible anymore from http://julialang.org/downloads/ as no link is provided (at least I can't find it).

This is not a major problem for me but maybe its confusing for some people.

**Comment by KristofferC** [comment] 2016-08-09 19:46
There is a PR up to put up the download link for the RC on the website repo.

For travis you can use 0.5 to test against the RC. PkgEval will likely be updated not too soon.

**Comment by tkelman** [comment] 2016-08-09 21:39
Duplicate of #17881. I'm not going to have PkgEval move to testing against 0.6 for a while.

**Closed by tkelman** 2016-08-09 21:39 UTC
