### ISSUE TITLE
Frivolous argument to sum should error out

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10630] opened 2015-03-25 14:21 UTC
I passed a random type to the second argument of `sum` and was demonstrating that it should be an error - but it wasn't.

````
julia> sum(rand(5,5), "hello")
5x5 Array{Float64,2}:
 0.24839    0.126172  0.152222   0.239802  0.40931 
 0.824976   0.13897   0.260075   0.600798  0.742999
 0.754645   0.458384  0.0487075  0.60348   0.476881
 0.959021   0.528383  0.312642   0.722538  0.242399
 0.0129307  0.624825  0.326454   0.519783  0.965539
````

Julia knows what you want to compute. You don't need to tell it. :-)

**Comment by jiahao** [comment] 2015-03-25 14:25
Dupe of #10461? Should be fixed on master.

**Comment by ViralBShah** [comment] 2015-03-25 14:26
The negative dimension was caught, but not this. It is on the current master.

**Comment by simonster** [comment] 2015-03-25 14:44
We could restrict the dimension argument to `Union(Vector{T}, (T...), T)` where `T<:Integer`, although that prevent passing an arbitrary iterator, or we could add throw an error if the iterator yields something that's not an integer, which would presumably be elided at compile time for the common cases.

**Closed** 2015-03-30 21:34 UTC
Labels: types and dispatch
