### ISSUE TITLE
download timeouts in Windows 10

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/julia#35660] opened 2020-04-30 09:20 UTC
I saw when upgrading TimeZones.jl, it was trying to download timezone data, and a timeout occurred. Testing various things in https://github.com/JuliaTime/TimeZones.jl/issues/257 and since TimeZones.jl is using Julia `Base.download`, this could be a problem on the Julia side.

On Windows 10, the download sometimes succeeds, and sometimes times out.  Here it succeeded twice, and failed once
```
julia> url="https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz"; download(url, basename(url))
"tzdata2015a.tar.gz"

julia> url="https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz"; download(url, basename(url))
"tzdata2015a.tar.gz"

julia> url="https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz"; download(url, basename(url))
┌ Error: Download failed: curl: (7) Failed to connect to data.iana.org port 443: Timed out
└ @ Base download.jl:43
ERROR: failed process: Process(`'C:\WINDOWS\System32\curl.exe' -s -S -g -L -f -o tzdata2015a.tar.gz https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz`, ProcessExited(7)) [7]

Stacktrace:
 [1] pipeline_error at .\process.jl:525 [inlined]
 [2] download_curl(::String, ::String, ::String) at .\download.jl:44
 [3] download(::String, ::String) at .\download.jl:62
 [4] top-level scope at REPL[6]:1
 [5] eval(::Module, ::Any) at .\boot.jl:331
 [6] eval_user_input(::Any, ::REPL.REPLBackend) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:86
 [7] run_backend(::REPL.REPLBackend) at C:\Users\jr\.julia\packages\Revise\WkyNB\src\Revise.jl:1023
 [8] top-level scope at none:0
```
I tried on two other machines, one Windows, and Linux, on a different network and there I could not reproduce the issue.

Trying the same in cmd.exe (with the option flags in the long format) gives
```
C:\Users\jr>curl --silent --show-error --globoff --location --fail "https://data.iana.org/time-zones/releases/tzdata2019c.tar.gz" --output tzdata2019c.tar.gz
curl: (7) Failed to connect to data.iana.org port 443: Timed out
```
but this sometimes works fine.  Some details of `curl`
```
C:\Users\jr>where curl
C:\Windows\System32\curl.exe

C:\Users\jr>curl --version
curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL
Release-Date: [unreleased]
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL
```

However, in PowerShell `curl` translates to
```
PS C:\Users\jr> Invoke-WebRequest -Uri https://data.iana.org/time-zones/releases/tzdata2019c.tar.gz -OutFile tzdata2019c.tar.gz
```
which works reliably.

`Base.download_powershell`  is not reliable either
```
julia> url="https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz"; Base.download_powershell(url, basename(url))
"tzdata2015a.tar.gz"

julia> url="https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz"; Base.download_powershell(url, basename(url))
ERROR: failed process: Process(`'C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe' -Version 3 -NoProfile -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; (New-Object System.Net.Webclient).DownloadFile('https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz', 'tzdata2015a.tar.gz')"`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error at .\process.jl:525 [inlined]
 [2] download_powershell(::String, ::String) at .\download.jl:20
 [3] top-level scope at REPL[7]:1
 [4] eval(::Module, ::Any) at .\boot.jl:331
 [5] eval_user_input(::Any, ::REPL.REPLBackend) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\REPL\src\REPL.jl:86
 [6] run_backend(::REPL.REPLBackend) at C:\Users\jr\.julia\packages\Revise\WkyNB\src\Revise.jl:1023
 [7] top-level scope at none:0
```

Note that I can download Julia without problems
```
url="https://julialang-s3.julialang.org/bin/winnt/x64/1.4/julia-1.4.1-win64.exe"; download(url, basename(url))
```

Summary: `Base.download` flakiness depends both on the ISP used and the URL what is to be downloaded.  On Windows, PowerShell `Invoke-WebRequest` seem to be more reliable than `C:\Windows\System32\curl.exe`.

Similar issue in the past has been https://github.com/JuliaLang/julia/issues/32720, but on MacOS.

**Comment by BrandonConder** [comment] 2021-01-02 19:53
In windows cmd.exe shell this invocation appears to be invalid.

```shell
C:\>'C:\WINDOWS\System32\curl.exe' -s -S -g -L -f -o tzdata2015a.tar.gz https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz`
The filename, directory name, or volume label syntax is incorrect.
```
The single-quotes around the command are not valid. Under windows you can use double-quotes:

```shell
C:\>"C:\WINDOWS\System32\curl.exe" -s -S -g -L -f -o "%TMP%/tzdata2015a.tar.gz" https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz

C:\>IF EXIST "%TMP%/tzdata2015a.tar.gz" ( echo Exists )
Exists
```

I don't currently have all the necessary tools to test out fixes... I'd suggest the easiest thing would be to prioritize PowerShell downloads over curl downloads on Windows, unless and until the double-quote vs. single-quote issue can be addressed.

**Comment by musm** [comment] 2021-01-02 22:11
On 1.6 we have fully transitioned away from using executables to handle file downloading. Please test on master, where the issue should be fixed. We can't backport the `Base.download` changes because they are too breaking.

**Comment by musm** [comment] 2021-01-02 22:11
@BrandonConder  But yea we probably have an escaping issue in calling the `curl.exe` executable

**Comment by musm** [comment] 2021-01-02 22:13
Do we have a reproducible test case here?

**Comment by BrandonConder** [comment] 2021-01-03 04:14
> Do we have a reproducible test case here?

As far as I can tell, no.

I came here because of [an issue a user was having with another project](https://github.com/mitmath/18S191/issues/57).
I tested from the command line, and got a a strange error about "https not supported of unavailable" which cleared up when I changed out the single-quotes. Later I got set up with Julia on Windows and was not able to reproduce either failure.


My setup:

- Windows 10 Pro x64, updates current as of 1/2/2021
- Julia 1.5.3 x64 portable downloaded 1/2/2021
- Cable internet, roughly 60ms ping to data.iana.org

Some small findings:

- Windows 10 Pro seems to include PowerShell and curl.exe in the default path
- All the flags listed above for curl.exe appear to be consistent with curl on my Ubuntu 20.04 computer


In light of the fact that I wasn't able to reproduce the failure, it seems I may have mistakenly connected these two issues based on what I saw in the other thread; escaping shouldn't be an intermittent failure as described here.

**Comment by jaakkor2** [comment] 2021-01-03 09:33
I cannot reproduce the original problem anymore
```
url="https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz"; download(url, basename(url))
```
with Julia v1.5.3 nor v1.6.0-DEV. Maybe https://data.iana.org improved their servers.

**Comment by musm** [comment] 2021-01-03 18:13
Sounds good, thanks for double checking. Closing since it looks fixed for now. Please open a new issue if this shows up again.

**Closed by musm** 2021-01-03 18:13 UTC
