### ISSUE TITLE
`methods` seems to get 100x slower than in v1.5

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#38059] opened 2020-10-16 14:48 UTC
MRE:
> julia@1.5.2
```julia
julia> methods(show);

julia> length(methods(show))
304

julia> @time methods(show);
  0.000278 seconds (966 allocations: 46.531 KiB)
```

> julia@master
```julia
julia> methods(show);

julia> length(methods(show))
314

julia> @time methods(show);
  0.022454 seconds (14.80 k allocations: 812.578 KiB)
```

The profiling shows most of the time is spent in [`_methods_by_ftype`](https://github.com/JuliaLang/julia/blob/9d6da9c4d664b832379bd2d0fa97cefecabb0e7e/base/reflection.jl#L808-L817), and I guess https://github.com/JuliaLang/julia/pull/35983 might be the source of this.

---

Well, I'm not sure the performance for `methods` is critical; I found this problem just because Juno's completions are much slower than before when using Julia built from master, and profiling shows that this line calling `methods` is the source of the performance regression:
https://github.com/JunoLab/Atom.jl/blob/c751731bd488db815110ed7771b7f313d8b92116/src/utils.jl#L268
```julia
ismacro(f::Function) = startswith(string(methods(f).mt.name), "@")
```

Now I found changing this line into
```julia
function ismacro(@nospecialize(f::FT)) where {FT<:Function}
  isdefined(FT, :name) || return false
  tn = FT.name::Core.TypeName
  return occursin('@', string(tn.name))
end
```
gets rid of the performance regression anyway, so I'm okay with it if the slowness of `methods` can't be helped in order to circumvent the latency issues.

**Comment by KristofferC** [comment] 2020-10-16 15:39
Ref https://github.com/JuliaLang/julia/issues/36860, https://github.com/JuliaLang/julia/issues/38037

**Comment by JeffBezanson** [comment] 2020-10-16 16:10
Yes this is a duplicate of #36860.

**Closed by JeffBezanson** 2020-10-16 16:10 UTC
