### ISSUE TITLE
addprocs(["user@host"]) can not execute command on remote Windows

### ISSUE THREAD

**Issue by 229668880** [JuliaLang/julia#29702] opened 2018-10-18 01:56 UTC
Hi, I am trying to use addprocs  to connect to remote workers on Windows. SSH connection is successful, but Julia cannot excecute commands.

I think it is not the problem of Julia on remote machines, because I got the same error even remote Julia is uninstalled.  SSH is good, because it can work on cmd.exe.

Here are the errors:
```
root@192.168.1.106's password: [Here I input password]
        From failed worker startup:     Unable to execute command or shell on remote system: Failed to Execute process.
ERROR: Unable to read host:port string from worker. Launch command exited with error?
error(::String) at .\error.jl:33
read_worker_host_port(::Pipe) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:273
connect(::Distributed.SSHManager, ::Int64, ::WorkerConfig) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\managers.jl:397
create_worker(::Distributed.SSHManager, ::WorkerConfig) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:505
setup_launched_worker(::Distributed.SSHManager, ::WorkerConfig, ::Array{Int64,1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:451
(::getfield(Distributed, Symbol("##47#50")){Distributed.SSHManager,WorkerConfig})() at .\task.jl:259
Stacktrace:
 [1] sync_end(::Array{Any,1}) at .\task.jl:226
 [2] #addprocs_locked#44(::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:tunnel, :sshflags, :max_parallel),Tuple{Bool,Cmd,Int64}}}, ::Function, ::Distributed.SSHManager) at .\task.jl:266
 [3] #addprocs_locked at .\none:0 [inlined]
 [4] #addprocs#43(::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:tunnel, :sshflags, :max_parallel),Tuple{Bool,Cmd,Int64}}}, ::Function, ::Distributed.SSHManager) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:369
 [5] #addprocs at .\none:0 [inlined]
 [6] #addprocs#251(::Bool, ::Cmd, ::Int64, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Array{String,1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\managers.jl:118
 [7] addprocs(::Array{String,1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\managers.jl:117
 [8] top-level scope at none:0
```

**Comment by 229668880** [comment] 2018-10-18 18:16
1. I  use cmd.exe on local machine, and can ssh to remote windows which returns a interactive cmd.exe shell. Just typing "julia" in the shell can start Julia.exe.
2. Remote machine SSH allow to run commands

Just now, I try to use addprocs([("root@192.168.1.114",1)],sshflags="-vv") for detailed errors:

OpenSSH_7.5p1, OpenSSL 1.0.2k  26 Jan 2017
debug2: resolving "192.168.1.114" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.1.114 [192.168.1.114] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/seanm/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.5
debug1: Remote protocol version 2.0, remote software version WeOnlyDo 2.4.3
debug1: no match: WeOnlyDo 2.4.3
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.1.114:22 as 'yang'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,ssh-dss
debug2: ciphers ctos: aes128-cbc,aes128-ctr,3des-cbc,blowfish-cbc,aes192-cbc,aes192-ctr,aes256-cbc,aes256-ctr,rijndael128-cbc,rijndael192-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,cast128-cbc
debug2: ciphers stoc: aes128-cbc,aes128-ctr,3des-cbc,blowfish-cbc,aes192-cbc,aes192-ctr,aes256-cbc,aes256-ctr,rijndael128-cbc,rijndael192-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,cast128-cbc
debug2: MACs ctos: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,none
debug2: MACs stoc: hmac-sha2-256,hmac-sha2-512,hmac-sha1,hmac-sha1-96,hmac-md5,none
debug2: compression ctos: none,none
debug2: compression stoc: none,none
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: ecdh-sha2-nistp256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:kcEhArZc3EcqGd9JiZcw7I5kM+IVAJD2ryA0YnboJGE
debug1: Host '192.168.1.114' is known and matches the RSA host key.
debug1: Found key in /home/seanm/.ssh/known_hosts:15
debug2: set_newkeys: mode 1
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 4294967296 blocks
debug2: key: /home/seanm/.ssh/id_rsa (0x0)
debug2: key: /home/seanm/.ssh/id_dsa (0x0)
debug2: key: /home/seanm/.ssh/id_ecdsa (0x0)
debug2: key: /home/seanm/.ssh/id_ed25519 (0x0)
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: password,gssapi-with-mic,publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /home/seanm/.ssh/id_rsa
debug1: Trying private key: /home/seanm/.ssh/id_dsa
debug1: Trying private key: /home/seanm/.ssh/id_ecdsa
debug1: Trying private key: /home/seanm/.ssh/id_ed25519
debug2: we did not send a packet, disable method
debug1: Next authentication method: password
yang@192.168.1.114's password:
debug2: we sent a password packet, wait for reply
debug1: Authentication succeeded (password).
Authenticated to 192.168.1.114 ([192.168.1.114]:22).
debug2: fd 4 setting O_NONBLOCK
debug2: fd 5 setting O_NONBLOCK
debug1: channel 0: new [client-session]
debug2: channel 0: send open
debug1: Entering interactive session.
debug1: pledge: network
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug1: Sending command: sh -l -c 'cd -- '\\''C:\\Users\\seanm\\Desktop'\\''

'\\''E:\\Programming\\Julia\\bin\\julia.exe'\\'' --worker'
debug2: channel 0: request exec confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 131072 rmax 98304
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug2: channel 0: rcvd adjust 0
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug2: channel 0: rcvd close
debug2: channel 0: output open -> drain
debug2: channel 0: close_read
debug2: channel 0: input open -> closed
debug2: channel 0: obuf empty
debug2: channel 0: close_write
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2024, received 1496 bytes, in 0.9 seconds
Bytes per second: sent 2181.4, received 1612.3
debug1: Exit status 1
        From failed worker startup:     sh: -c: line 2: unexpected EOF while looking for matching `''
        From failed worker startup:     sh: -c: line 3: syntax error: unexpected end of file
ERROR: Unable to read host:port string from worker. Launch command exited with error?
error(::String) at .\error.jl:33
read_worker_host_port(::Pipe) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:273
connect(::Distributed.SSHManager, ::Int64, ::WorkerConfig) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\managers.jl:397
create_worker(::Distributed.SSHManager, ::WorkerConfig) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:505
setup_launched_worker(::Distributed.SSHManager, ::WorkerConfig, ::Array{Int64,1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:451
(::getfield(Distributed, Symbol("##47#50")){Distributed.SSHManager,WorkerConfig})() at .\task.jl:259
Stacktrace:
 [1] sync_end(::Array{Any,1}) at .\task.jl:226
 [2] #addprocs_locked#44(::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:tunnel, :sshflags, :max_parallel),Tuple{Bool,String,Int64}}}, ::Function, ::Distributed.SSHManager) at .\task.jl:266
 [3] #addprocs_locked at .\none:0 [inlined]
 [4] #addprocs#43(::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol,Symbol},NamedTuple{(:tunnel, :sshflags, :max_parallel),Tuple{Bool,String,Int64}}}, ::Function, ::Distributed.SSHManager) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\cluster.jl:369
 [5] #addprocs at .\none:0 [inlined]
 [6] #addprocs#251(::Bool, ::String, ::Int64, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Array{Tuple{String,Int64},1}) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Distributed\src\managers.jl:118
 [7] (::getfield(Distributed, Symbol("#kw##addprocs")))(::NamedTuple{(:sshflags,),Tuple{String}}, ::typeof(addprocs), ::Array{Tuple{String,Int64},1}) at .\none:0
 [8] top-level scope at none:0

**Comment by StefanKarpinski** [comment] 2018-10-18 19:46
Does running these commands on the remote machine work:
```
cd -- /cygdrive/c/Users/seanm/Desktop
export JULIA_WORKER_TIMEOUT=60
/cygdrive/e/Programming/Julia/bin/julia --worker
```

**Comment by 229668880** [comment] 2018-10-18 19:55
Yes, it is running, and just stop there without doing anything.

Windows Task Manager also shows that a Julia process is running.

**Comment by 229668880** [comment] 2018-10-18 19:58
If I use Ctrl+C to force it stop. A message is return:

Internal error: encountered unexpected error in runtime:
InterruptException()

By the way, I use Julia 1.0

**Comment by 229668880** [comment] 2018-10-18 20:02
Sorry. If I press Enter more times, it returns:  julia_worker:9724#192.168.1.114

**Comment by StefanKarpinski** [comment] 2018-10-18 20:07
Can you confirm that this was on the remote machine, not the local machine?

**Comment by 229668880** [comment] 2018-10-18 20:09
Yes, I confirm

**Comment by 229668880** [comment] 2018-10-18 20:11
On local machine, I try: 
addprocs(["yang@192.168.1.114:9724"],exename="/cygdrive/e/Programming/Julia/bin/julia",dir="/cygdrive/c/Users/seanm/Desktop")

Remote Julia returns an error:
ErrorException("Process(1) - Invalid connection credentials sent by remote.")CapturedException(ErrorException("Process(1) - Invalid connection credentials sent by remote."), Any[(error(::String) at error.jl:33, 1), (process_hdr(::TCPSocket, ::Bool) at process_messages.jl:248, 1), (message_handler_loop(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:142, 1), (process_tcp_streams(::TCPSocket, ::TCPSocket, ::Bool) at process_messages.jl:117, 1), ((::##105#106{TCPSocket,TCPSocket,Bool})() at task.jl:259, 1)])
Process(1) - Unknown remote, closing connection.

**Comment by vchuravy** [comment] 2018-10-18 20:53
Duplicate of #29243, https://github.com/JuliaLang/julia/blob/1f1b1b8c4e27668efddcaceb59db9422bb274cfd/stdlib/Distributed/src/managers.jl#L148 assumes that it will run on a posix system.

**Comment by StefanKarpinski** [comment] 2018-10-18 21:33
Right, Windows is non-POSIX, unfortunately and therefore not supported.

**Closed** 2018-10-19 03:28 UTC

**Comment by mgkuhn** [comment] 2021-07-10 09:52
For the record: a `shell=:wincmd` option of [Distributed.addprocs()](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.addprocs) was added in Julia 1.6 for Windows workers where you ssh into `cmd.exe`. The documentation now also makes clear that the default is for POSIX shells.
