### ISSUE TITLE
REPL exception with 4 keystrokes (tab completion with macros)

### ISSUE THREAD

**Issue by abraunst** [JuliaLang/julia#30517] opened 2018-12-26 12:35 UTC
open julia, write `@a.<TAB>`  -> boom. Don't ask what I was trying to achieve, just fat fingers.

```
julia> @a.┌ Error: Error in the keymap
│   exception =
│    LoadError: UndefVarError: @a not defined
│    Stacktrace:
│     [1] top-level scope
│     [2] lower at ./meta.jl:68 [inlined]
│     [3] get_type(::Expr, ::Module) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/REPLCompletions.jl:422
│     [4] complete_symbol(::String, ::getfield(REPL.REPLCompletions, Symbol("##21#25")), ::Module) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/REPLCompletions.jl:123
│     [5] completions(::String, ::Int64, ::Module) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/REPLCompletions.jl:699
│     [6] completions(::String, ::Int64) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/REPLCompletions.jl:569
│     [7] complete_line(::REPL.REPLCompletionProvider, ::Any) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:349
│     [8] complete_line(::REPL.LineEdit.PromptState, ::Any) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:322
│     [9] complete_line(::REPL.LineEdit.MIState) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:313
│     [10] edit_tab(::REPL.LineEdit.MIState, ::Any, ::Any) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:1954 (repeats 2 times)
│     [11] (::getfield(REPL.LineEdit, Symbol("##108#160")))(::Any, ::Any, ::Vararg{Any,N} where N) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:1995
│     [12] #invokelatest#1 at ./essentials.jl:742 [inlined]
│     [13] invokelatest at ./essentials.jl:741 [inlined]
│     [14] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(REPL.LineEdit, Symbol("##108#160")),String})(::Any, ::Any) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:1324
│     [15] prompt!(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2365
│     [16] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2268
│     [17] run_frontend(::LineEditREPL, ::REPL.REPLBackendRef) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:1035
│     [18] run_repl(::AbstractREPL, ::Any) at /home/ab/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:192
│     [19] (::getfield(Base, Symbol("##735#737")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:362
│     [20] #invokelatest#1 at ./essentials.jl:742 [inlined]
│     [21] invokelatest at ./essentials.jl:741 [inlined]
│     [22] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:346
│     [23] exec_options(::Base.JLOptions) at ./client.jl:284
│     [24] _start() at ./client.jl:436
│    in expression starting at none:1
└ @ REPL.LineEdit ~/src/julia/build1.x/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2367
```

**Comment by KristofferC** [comment] 2019-01-01 17:36
Let's tag an eventual PR that fixes this instead.

**Comment by cafaxo** [comment] 2019-01-01 17:56
Is this a duplicate of https://github.com/JuliaLang/julia/issues/27184?

**Comment by KristofferC** [comment] 2019-01-01 18:01
Yes.

**Closed by KristofferC** 2019-01-01 18:01 UTC
Labels: REPL, bug
