### ISSUE TITLE
spawn & repl tests fail because of spurious output of image file path

### ISSUE THREAD

**Issue by rekado** [JuliaLang/julia#10541] opened 2015-03-17 11:16 UTC
The tests in `test/spawn.jl` and `test/repl.jl` that call the julia executable and compare the output against an expected string fail because `ui/repl.c` prints the path to the image file.

The image file path is not printed when it is an absolute path, yet `JL_SYSTEM_IMAGE_PATH` is unconditionally defined as a relative path in `Make.inc` on line 338:

    JCPPFLAGS += "-DJL_SYSTEM_IMAGE_PATH=\"$(build_private_libdir_rel)/sys.ji\""

**Comment by tkelman** [comment] 2015-03-17 14:41
> `ui/repl.c` prints the path to the image file.

Where, exactly? I don't see it...

**Comment by rekado** [comment] 2015-03-17 14:47
I probably should have mentioned that I'm using version 0.3.6:
https://github.com/JuliaLang/julia/blob/v0.3.6/ui/repl.c#L208

Apparently this is no longer the case in master, but as it is these tests don't pass for the latest release 0.3.6.

**Comment by tkelman** [comment] 2015-03-17 14:53
Oh, right. That is some old code, dates back to e92066d91e369bafb551e4a297e9a7b7774e6333 apparently. I'm not sure what we needed the print for, if anything. The unconditionally setting `JL_SYSTEM_IMAGE_PATH` to a relative path might be due to a somewhat more recent backport, I'm not sure.

What's the least exotic build environment setup that can reproduce this causing a test failure, for release-0.3?

**Comment by tkelman** [comment] 2015-03-17 14:56
Wait, line 208 is an `snprintf` which should just be to a string buffer, not a visible output...

**Comment by rekado** [comment] 2015-03-17 15:07
Hmm, that's odd because I get this output whenever I run `julia`:

~~~
[rekado@workstation:~/code/guix] (610) $ /gnu/store/f7ndy3ai87mmz75fpc43ypvqi90n8ds6-julia-0.3.6/bin/julia
/gnu/store/f7ndy3ai87mmz75fpc43ypvqi90n8ds6-julia-0.3.6/bin/../lib/julia/sys.ji
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-02-17 22:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-unknown-linux-gnu

julia> exename=joinpath(JULIA_HOME,(ccall(:jl_is_debugbuild,Cint,())==0?"julia":"julia-debug"))
"/gnu/store/f7ndy3ai87mmz75fpc43ypvqi90n8ds6-julia-0.3.6/bin/julia"

julia> readall(`$exename -f -e 'println(STDERR,"Hello World")'` .> `cat`)
"Hello World\n/gnu/store/f7ndy3ai87mmz75fpc43ypvqi90n8ds6-julia-0.3.6/bin/../lib/julia/sys.ji\n"

julia> 
~~~

**Comment by JeffBezanson** [comment] 2015-03-17 15:14
That's very odd. I just tried this in 0.3.6 and I don't get the extra output.

**Comment by rekado** [comment] 2015-03-17 15:17
> What's the least exotic build environment setup that can reproduce this causing a test failure, for release-0.3?

I shall try to reproduce this in a more traditional build environment and report back.

**Comment by tkelman** [comment] 2015-03-18 11:24
Maybe simpler, can you get `snprintf` to output to stdout from a simpler test program? Might be something funky that's specific to Guix.

**Comment by rekado** [comment] 2015-03-18 17:04
I'm beginning to think that the line I referenced isn't responsible after all.  I'll investigate further.

**Comment by rekado** [comment] 2015-03-19 14:36
The responsible print statement appears to be on line 753 in `src/init.c` in the procedure `julia_init`:

    // If we are able to load the sysimg and get a cpu_target, use that unless user has overridden
    if (jl_compileropts.cpu_target == NULL) {
        printf("%s\n", imageFile);
        const char * sysimg_cpu_target = jl_get_system_image_cpu_target(imageFile);

        // If we can't load anything from the sysimg, default to native
        jl_compileropts.cpu_target = sysimg_cpu_target ? sysimg_cpu_target : "native";
    }

Curiously, I do not see this line in the 0.3.6 tagged version of the file, but I do see it in the version of the file that's included in the release tarball `julia-0.3.6_0c24dca65c.tar.gz`.

**Comment by tkelman** [comment] 2015-03-19 14:39
Oh, that's @staticfloat's snafu, I remember him saying something about letting some debug code sneak in and sneakily redoing the tag. Must've forgotten to reupload the source-dist tarball.

**Comment by staticfloat** [comment] 2015-03-19 18:33
Very weird.  I had clearly uploaded a new tarball (since it had the correct hash in the name, that is, `julia-0.3.6_0c24dca65c.tar.gz`) but the contents were old.  In any case, thanks for reporting, and it should be fixed now.

**Closed by staticfloat** 2015-03-19 18:33 UTC
