### ISSUE TITLE
Pushing on array of tuple crashes Julia

### ISSUE THREAD

**Issue by theogf** [JuliaLang/julia#33727] opened 2019-10-31 13:04 UTC
On Julia 1.1 1.2 1.3
```
function mean_foo(m) where {T}
    f = NTuple[]
    n = [1,1]
    for i in 1:2
        x = ntuple(_->zeros(10),n[i])
        for j in 1:n[i]
            x[j] .= sum(rand(length(m)).*m)
        end
        push!(f,x)
    end
    return f
end
mean_foo([rand(10) for _ in 1:4])
```
make Julia crashes with the error 
```
Unreachable reached at 0x7f0de61f9aa2
signal (4): Illegal instruction
```
With the error happening on `push!(f,x)`

**Comment by StefanKarpinski** [comment] 2019-10-31 13:11
Also on master.

**Comment by Liozou** [comment] 2019-10-31 14:40
Here are two reductions of the problem. I have no idea what's going on in there but I thought it might be useful for anyone familiar with the code.

This one I derived manually from the original problem:
```julia
function a()
    f = NTuple[]
    x = ntuple(zeros, Ref(1)[])
    push!(f,x)
end
a()
```

The second one, using @maleadt's [creduce_julia](https://github.com/maleadt/creduce_julia) tool (and further minimised):
```julia
function b()
    f = NTuple[]
    x = ntuple(zeros, 11)
    push!(f,x)
end
b()
```
In this last one, the 11 constant is actually the minimum value for which this happens.

**Comment by fredrikekre** [comment] 2019-10-31 14:44
> In this last one, the 11 constant is actually the minimum value for which this happens.

https://github.com/JuliaLang/julia/blob/93ebf3ee92915761acf367d359d36df93be4b302/base/ntuple.jl#L17-L31

**Comment by JeffBezanson** [comment] 2019-10-31 16:12
Probably a duplicate of #31824. For now please use `Tuple` instead of `NTuple`.

**Comment by Liozou** [comment] 2019-10-31 17:30
I just tested and I confirm that #31833 solves this issue.

**Comment by JeffBezanson** [comment] 2019-11-06 22:49
Closing as duplicate.

**Closed by JeffBezanson** 2019-11-06 22:49 UTC
Labels: arrays, backport 1.0, backport 1.3, bug
