### ISSUE TITLE
`StackOverflowError` in `errorshow.jl` tests caused by a failed process

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#56136] opened 2024-10-13 04:56 UTC
In https://buildkite.com/julialang/julia-master/builds/40789#0192768d-90df-4f4a-b608-57bf23e81d02, the error is
```julia
The global RNG seed was 0x97ae56821e92e3eccafbafda2814ff12.
Error in testset errorshow:
Test Failed at /usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-0/julialang/julia-master/julia-9ad92bd675/share/julia/test/errorshow.jl:225
  Expression: typeof(err) === $(Expr(:escape, :MethodError))
   Evaluated: StackOverflowError === MethodError
ERROR: LoadError: Test run finished with errors
in expression starting at /usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-0/julialang/julia-master/julia-9ad92bd675/share/julia/test/runtests.jl:100
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 1.12.0-DEV.1341
Commit 9ad92bd675 (2024-10-10 13:09 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: FreeBSD (x86_64-unknown-freebsd13.2)
  CPU: 8 × AMD EPYC Processor (with IBPB)
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver1)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_INSTALL_DIR = julia-9ad92bd675
  JULIA_SHELL = /usr/local/bin/bash
  JULIA_CPU_TARGET = generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1);x86-64-v4,-rdrnd,base(1)
  JULIA_TEST_MAXRSS_MB = 3800
  JULIA_CMD_FOR_TESTS = julia-9ad92bd675/bin/julia .buildkite/utilities/timeout.jl julia-9ad92bd675/bin/julia
  JULIA_TEST_VERBOSE_LOGS_DIR = /tmp/jl_2N2Juh
  JULIA_IMAGE_THREADS = 8
  JULIA_BINARYDIST_FILENAME = julia-9ad92bd675-freebsd64
  JULIA_CPU_THREADS = 8
  JULIA_NUM_THREADS = 1
  JULIA_VERSION = 1.12.0-DEV
  JULIA_TEST_IS_BASE_CI = true
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:44
 [2] runtests(tests::String; ncores::Int64, exit_on_error::Bool, revise::Bool, seed::Nothing)
   @ Base ./util.jl:719
 [3] top-level scope
   @ none:1
 [4] eval
   @ ./boot.jl:439 [inlined]
 [5] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:295
 [6] _start()
   @ Base ./client.jl:558
caused by: failed process: Process(setenv(`/usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-0/julialang/julia-master/julia-9ad92bd675/bin/julia -C native -J/usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-0/julialang/julia-master/julia-9ad92bd675/lib/julia/sys.so -g1 /usr/home/julia/.buildkite-agent/builds/freebsd13-amdci6-0/julialang/julia-master/julia-9ad92bd675/bin/../share/julia/test/runtests.jl all --ci`,["PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin", "BUILDKITE_BUILD_CREATOR_TEAMS=", "BUILDKITE_LAST_HOOK_EXIT_STATUS=0", "UPLOAD_FILENAME=julia-9ad92bd675-freebsd-x86_64", "BUILDKITE_PROJECT_PROVIDER=github", "ARCH=x86_64", "LONG_COMMIT=9ad92bd6756fd56bbfc2dbfbe567f70c8af92efb", "GKS_ENCODING=utf8", "JULIA_TEST_MAXRSS_MB=3800", "BUILDKITE_GROUP_LABEL=Test"  …  "JULIA_LOAD_PATH=@:@stdlib", "BUILDKITE_PULL_REQUEST=56089", "BUILDKITE_ORGANIZATION_ID=d409823c-5fa7-41c8-9033-7269c5fde4f3", "BUILDKITE_GROUP_KEY=", "NCORES_FOR_TESTS=8", "JULIA_CPU_TARGET=generic;sandybridge,-xsaveopt,clone_all;haswell,-rdrnd,base(1);x86-64-v4,-rdrnd,base(1)", "TAR_VERSION=9ad92bd675", "BUILDKITE_AGENT_PID=820", "OPENBLAS_MAIN_FREE=1", "BUILDKITE_AGENT_META_DATA_CPUSET_LIMITED=true"]), ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error
   @ ./process.jl:598 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:513
 [3] run
   @ ./process.jl:510 [inlined]
 [4] runtests(tests::String; ncores::Int64, exit_on_error::Bool, revise::Bool, seed::Nothing)
   @ Base ./util.jl:711
 [5] top-level scope
   @ none:1
 [6] eval
   @ ./boot.jl:439 [inlined]
 [7] exec_options(opts::Base.JLOptions)
   @ Base ./client.jl:295
 [8] _start()
   @ Base ./client.jl:558
```
This seems to be caused by a failed process, and we should have better error handling in such cases.

**Comment by d-netto** [comment] 2024-10-16 13:31
Duplicate of https://github.com/JuliaLang/julia/issues/56190.

**Closed by d-netto** 2024-10-16 13:31 UTC
Labels: ci

**Comment by d-netto** [comment] 2024-10-16 14:27
Yes, unfortunately only noticed that this issue was opened after I opened mine. Thanks for the heads-up.
