### ISSUE TITLE
1.3.1 documentation pdf missing

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#34261] opened 2020-01-05 03:29 UTC
The link to the 1.3.1 pdf documentation on docs.julialang.org is broken.

https://raw.githubusercontent.com/JuliaLang/docs.julialang.org/assets/julia-1.3.1.pdf

**Comment by fredrikekre** [comment] 2020-01-10 09:32
Essentially a duplicate of #33968.

**Closed by fredrikekre** 2020-01-10 09:32 UTC
Labels: docsystem
