### ISSUE TITLE
ERROR: ArgumentError: can't repeat a string -1 times

### ISSUE THREAD

**Issue by bcavileer** [JuliaLang/julia#10931] opened 2015-04-21 18:07 UTC
Trying out some exercises in the REPL I saw this error.  I cannot reproduce it.  Even restarting the REPL and re-running this code will not reproduce the ERROR.  

```
julia> Float64[x * y for x in 1:2, y in 1:3]
```
```
2x3 Array{Float64,2}:
 1.0  02.0  03.0
 Error showing value of type Array{Float64,2}:
ERROR: ArgumentError: can't repeat a string -1 times
 in print_matrix_row at show.jl:962
 in print_matrix at show.jl:1006
 in showarray at show.jl:1185
 in anonymous at replutil.jl:27
 in with_output_limit at ./show.jl:1202
 in writemime at replutil.jl:26
 in display at REPL.jl:111
 in display at REPL.jl:114
 in display at multimedia.jl:149
 in print_response at REPL.jl:133
 in print_response at REPL.jl:118
 in anonymous at REPL.jl:595
 in run_interface at ./LineEdit.jl:1552
 in run_frontend at ./REPL.jl:835
 in run_repl at ./REPL.jl:164
 in _start at ./client.jl:430
```

```
Version 0.4.0-dev+4234 (2015-04-13 21:27 UTC)
Commit fe4cb53* (7 days old master)
x86_64-linux-gnu
```

**Comment by pao** [comment] 2015-04-21 18:32
Canonical link to the location of the error: https://github.com/JuliaLang/julia/blob/fe4cb5395bd3fe08417d83c8dae2e086c23d12d5/base/show.jl#L962

**Comment by bcavileer** [comment] 2015-04-21 18:36
From help on Commit fe4cb53*
```
Base.repeat(A, inner = Int[], outer = Int[])

   Construct an array by repeating the entries of "A". The i-th
   element of "inner" specifies the number of times that the
   individual entries of the i-th dimension of "A" should be
   repeated. The i-th element of "outer" specifies the number of
   times that a slice along the i-th dimension of "A" should be
   repeated.
```

**Comment by mbauman** [comment] 2015-04-21 18:37
I'd bet the root cause here is https://github.com/JuliaLang/julia/issues/10908 (which was also not reproducible).  Note the leading zeros — I imagine that's screwing up the alignment calculations, leading to your -1.

**Comment by jakebolewski** [comment] 2015-05-29 13:51
Closing as a dup #10908.

**Closed by jakebolewski** 2015-05-29 13:51 UTC
