### ISSUE TITLE
'make test' fails for julia-1.11.0-beta2

### ISSUE THREAD

**Issue by sergstesh** [JuliaLang/julia#54777] opened 2024-06-12 12:57 UTC
Output of versioninfo():

```
julia> versioninfo()
Julia Version 1.11.0-beta2
Commit edb3c92d6a (2024-05-29 09:37 UTC)
Build Info:

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) N100
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)

julia>

```
.

I downloaded Julia tarball from https://github.com/JuliaLang/julia/releases/download/v1.11.0-beta2/julia-1.11.0-beta2-full.tar.gz , unpacked it the usual way, did 'cd julia-1.11.0-beta2' and built Julia using the following command line:

`nice -n 19 make test 1>make_test.log 2>&`

.

See the attached 'make_test.log' file for details on failures.
[make_test.log](https://github.com/user-attachments/files/15805392/make_test.log)

**Comment by giordano** [comment] 2024-06-12 17:28
Duplicate of #54280

**Closed by giordano** 2024-06-12 17:28 UTC
