### ISSUE TITLE
Array type inference takes exponential time

### ISSUE THREAD

**Issue by cberzan** [JuliaLang/julia#17903] opened 2016-08-08 19:00 UTC
When concatenating a `Float64[]` and an `Any[]` that contains some `nothing` values, inferring the type of the resulting array takes time exponential in the length of the arrays. Example:

```
julia> for n in [100, 150, 200, 250, 300, 350, 400]
           x = zeros(Float64, n)
           y = [0.0, nothing]
           print("n=$n: ")
           @time result = [x..., y...]
       end
n=100:   0.711594 seconds (208.66 k allocations: 12.082 MB, 3.53% gc time)
n=150:   1.409423 seconds (88.71 k allocations: 4.886 MB)
n=200:   2.961411 seconds (100.57 k allocations: 5.549 MB)
n=250:   7.311390 seconds (126.25 k allocations: 6.930 MB, 0.07% gc time)
n=300:  16.698541 seconds (153.91 k allocations: 8.400 MB)
n=350:  25.183418 seconds (183.35 k allocations: 9.966 MB, 0.02% gc time)
n=400:  39.814280 seconds (214.75 k allocations: 11.587 MB)

julia> versioninfo()
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Workarounds: Changing `[x..., y...]` to `Any[x..., y...]` or `vcat(x, y)` does not exhibit this issue.

Background: In my case, the presence of `nothing` in `y` was a bug. It was a difficult bug to find though, because x had tens of thousands of items, so my program just hung with 100% CPU usage. When x and y are small, there is no noticeable problem, so it took me a while to figure out what was going on. It would be great if there was a way to set time limits on type inference, or at least get warnings if it's taking too long.

**Comment by JeffBezanson** [comment] 2016-08-09 14:50
Yes, it is generally not a good idea to splat a large number of things, since we have to look at the types of all the arguments to do dispatch. This can be slow, even when not exponential time.
This particular case seems to be fixed in 0.5. I get the same result as you in 0.4, and this in 0.5:

```
julia> for n in [100, 150, 200, 250, 300, 350, 400]
                  x = zeros(Float64, n)
                  y = [0.0, nothing]
                  print("n=$n: ")
                  @time result = [x..., y...]
              end
n=100:   0.047764 seconds (12.60 k allocations: 679.501 KB)
n=150:   0.020727 seconds (4.55 k allocations: 371.636 KB)
n=200:   0.022821 seconds (4.77 k allocations: 515.714 KB)
n=250:   0.023493 seconds (4.95 k allocations: 696.651 KB)
n=300:   0.024536 seconds (5.16 k allocations: 938.167 KB)
n=350:   0.025108 seconds (5.35 k allocations: 1.169 MB)
n=400:   0.026563 seconds (5.55 k allocations: 1.483 MB)
```

**Comment by DemiMarie** [comment] 2016-08-10 19:54
Could there be a mode that allows issuing runtime warnings when certain operations are detected?  Perl has `use warnings;`.

**Comment by StefanKarpinski** [comment] 2016-08-10 20:54
There could be, but I think it would make more sense to simply disallow those operations. The problem is that splatting is sometimes fine and sometimes not and there's no static difference.

**Comment by KristofferC** [comment] 2017-05-25 23:20
This is fixed.

**Closed by KristofferC** 2017-05-25 23:20 UTC
Labels: benchmark, inference
