### ISSUE TITLE
Pkg.update() does not continue to all packages when one package fails.

### ISSUE THREAD

**Issue by RatanRSur** [JuliaLang/julia#13584] opened 2015-10-13 16:06 UTC
I'm not sure if this is actually intended behavior but here's what happened.

Added an NCurses library

`Pkg.clone(https://github.com/Keno/NCurses.jl.git)`

It fails with

```
ERROR: Terminals can't be installed because it has no versions that support 0.4.0 of julia. You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in resolve at /opt/homebrew-cask/Caskroom/julia/0.4.0/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in update at /opt/homebrew-cask/Caskroom/julia/0.4.0/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at /opt/homebrew-cask/Caskroom/julia/0.4.0/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
```

I left the package in for the time being and called Pkg.update(). Same error so I removed NCurses and tried again.

```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating NCurses...
INFO: Computing changes...
ERROR: Terminals can't be installed because it has no versions that support 0.4.0 of julia. You may need to update METADATA by running `Pkg.update()`
 in error at error.jl:22
 in resolve at /opt/homebrew-cask/Caskroom/julia/0.4.0/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in update at /opt/homebrew-cask/Caskroom/julia/0.4.0/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at /opt/homebrew-cask/Caskroom/julia/0.4.0/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib

julia> Pkg.rm("NCurses")
INFO: Removing NCurses (unregistered)

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Upgrading Compat: v0.7.5 => v0.7.6
INFO: Upgrading StatsBase: v0.7.3 => v0.7.4
```

The packages `Compat` and `StatsBase` were not updated until I removed the offending package. Is there something I don't know about that requires the update of all packages fail for one's error?

**Comment by milktrader** [comment] 2015-10-13 17:07
The `requires` file for Terminals in METADATA has this line:
````
julia 0.2 0.3
````
So you'll need to be on Julia 0.2 or Julia 0.3 pre-release. 

I'm not sure if this package is still maintained or if it has been merged into base and needs to be deprecated? @IainNZ @Keno

**Comment by IainNZ** [comment] 2015-10-13 17:12
It isn't maintained, and Pkg is doing the right thing (if you wanted to override it, you can still explicitly clone it). But I'm not sure thats the point of this issue, I think the issue is that Pkg.update gives up. Given how it works, I understand why it does.

**Comment by IainNZ** [comment] 2015-10-13 17:13
@RatanRSur btw, if you want NCurses functionality, its partially wrapped in this package: https://github.com/tonyhffong/TermWin.jl, but you might want to make your own package.

**Comment by RatanRSur** [comment] 2015-10-13 17:36
@milktrader I understand why it failed, I was just surprised that it's failure stopped the whole update process such that `Compat` and `StatsBase` wouldn't be updated.

@IainNZ Thanks for the suggestion! One thing I need clarification on: giving up on all packages even if one fails is intended behavior?

**Comment by IainNZ** [comment] 2015-10-13 18:29
How I understand it is that the installed packages defines a set of requirements and Pkg.update simply finds a set of packages that satisfies it. As it can't do so, it gives up. Partially satisfaction is possible but not well-defined and harder. So I'd say it is expected.

**Comment by stevengj** [comment] 2015-10-13 20:27
It is expected, but not particularly desirable.

**Comment by stevengj** [comment] 2015-10-13 20:29
I'm hoping to put together a solution for #13487 that will also fix this problem: you should be able to update package Foo as long as updating all of its dependencies succeeds.

**Comment by wildart** [comment] 2015-10-16 00:21
I don't think that a function which updates one package can resolve this issue. Such function will throw the same error.  It is a more question of how exceptions should handled during operations on multiple packages.

**Comment by tkelman** [comment] 2015-10-16 01:33
This is a dependency resolution failure, so if a function that updates a single package performs dependency resolution in a more local fashion and is able to ignore disconnected portions of the dependency graph, it would likely be able to succeed in cases like this.

**Comment by wildart** [comment] 2015-10-16 01:44
Dependency resolution faults are not an issue here. Such faults are expected and the outcome will be the same - exception on a package with unresolvable dependencies. Any kind of `update` will not be able resolve problem for `NCurses.jl`, so exception will be thrown every time when `resolve` hits `NCurses`.

**Comment by tkelman** [comment] 2015-10-16 01:45
If dependency resolution fails, there's no way for update to do anything meaningful.

**Comment by jhlq** [comment] 2015-10-17 17:12
A function that updates individual packages atleast provides a workaround for updating other packages without removing the failing one, it is also useful when one is on a mobile network and only require a specific update. Pinning packages is an option, although at increased time consumption. Is there a deep reason such a function is not available?

**Comment by IainNZ** [comment] 2015-10-17 17:48
@jhlq updating a single package (and its dependencies) is a somewhat separate issue, https://github.com/JuliaLang/julia/issues/13487

**Comment by simonbyrne** [comment] 2018-08-10 16:45
This has changed considerably with the new Pkg. If still an issue, please open at https://github.com/JuliaLang/Pkg.jl

**Closed by simonbyrne** 2018-08-10 16:45 UTC
Labels: error handling, packages
