### ISSUE TITLE
Sparse Matrix-Vector Broadcast (`.*`) Runs Out of Memory

### ISSUE THREAD

**Issue by r-barnes** [JuliaLang/julia#29436] opened 2018-09-30 02:59 UTC
**Description**

When performing an outer product (`M .* v`) of a sparse matrix by a vector (either dense or sparse), I run out of memory.

The matrix in question is `3,955,848×3,955,848 SparseMatrixCSC{Float64,Int64} with 31,646,765` stored entries. The vector is of length 3,955,848.

The result should be another 3,955,848x3,955,848 matrix of 3,955,848 entries, which should fit comfortably in memory. Unfortunately, it seems as though there must be a fair amount of unnecessary allocation happening somewhere.

**Version**

Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, westmere)

**Error Message**

```
ERROR: OutOfMemoryError()
Stacktrace:
 [1] _allocres at ./boot.jl:394 [inlined]
 [2] _diffshape_broadcast(::typeof(*), ::SparseMatrixCSC{Float64,Int64}, ::SparseVector{Float64,Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:189
 [3] _copy at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:970 [inlined]
 [4] copy at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:965 [inlined]
 [5] materialize at ./broadcast.jl:724 [inlined]
 [6] broadcast at ./broadcast.jl:702 [inlined]
 [7] copy at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/SparseArrays/src/higherorderfns.jl:1082 [inlined]
 [8] materialize(::Base.Broadcast.Broadcasted{SparseArrays.HigherOrderFns.PromoteToSparse,Nothing,typeof(*),Tuple{SparseMatrixCSC{Float64,Int64},Array{Float64,1}}}) at ./broadcast.jl:724
 [9] top-level scope at none:0
```

**Example Code**

```
using SparseArrays

width  = 1636
height = 2418
I      = vec(rand(1:width*height,8*width*height))
J      = vec(rand(1:width*height,8*width*height))
V      = vec(rand(1,8*width*height))
M      = sparse(I,J,V) 
v      = vec(rand(1,width*height))
M.*v #Everything blows up
```

Note that this works fine for (`width=height=100`) and returns the expected sparse matrix with the expected number of entries.

**Comment by Sacha0** [comment] 2018-09-30 17:40
Thanks @r-barnes! This issue is a duplicate of a few existing issues; the most relevant issues/comments that I can provide off the top of my head are: https://github.com/JuliaLang/julia/issues/26561#issuecomment-375401917 and https://github.com/JuliaLang/julia/issues/27653#issuecomment-398514781. Best!

**Closed by Sacha0** 2018-09-30 17:40 UTC
Labels: sparse
