### ISSUE TITLE
problems running commands on windows

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#20477] opened 2017-02-06 21:58 UTC
I tried asking first on discourse, see here: https://discourse.julialang.org/t/unable-to-automate-travis-from-command-line/1926/6.

```julia
julia> run(`travis login`)
ERROR: could not spawn `travis login`: no such file or directory (ENOENT)
 in _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::RawFD, ::RawFD, ::RawFD) at .\process.jl:321
 in #414 at .\process.jl:478 [inlined]
 in setup_stdio(::Base.##414#415{Cmd,Ptr{Void},Base.Process}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:466
 in #spawn#413(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}, ::Bool, ::Bool) at .\process.jl:477
 in run(::Cmd) at .\process.jl:591
```

`travis login` works just find from the command prompt
the folder travis in is in my julia ENV["path"]
running regular commands like `run(dir)` works just fine
running ruby commands like `run(ruby --version)` works just fine

**Comment by vtjnash** [comment] 2017-02-06 22:39
`which` isn't a Windows command. It sounds like you are trying to unix-isms (like being able to make arbitrary files executable) that aren't valid on Windows (only files ending in `.exe` and `.com` are executable).

**Comment by bramtayl** [comment] 2017-02-06 22:43
I know. Git comes packaged with a bunch of unix command line tools and I added them to my path.

**Comment by bramtayl** [comment] 2017-02-06 22:45
Also, 'travis login' works just fine in my windows command prompt, as stated above. It's travis's official command line interface and I installed it with Ruby

**Comment by tkelman** [comment] 2017-02-07 03:17
what kind of file is it? libuv can't spawn batch files

**Comment by bramtayl** [comment] 2017-02-07 03:32
In the folder there's a file called travis.bat (Windows Batch File!)

```
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\Ruby22-x64\bin\ruby.exe" "C:/Ruby22-x64/bin/travis" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\Ruby22-x64\bin\ruby.exe" "%~dpn0" %*
```

There's also a travis file with no extention. Its contents are

```
#!C:/Ruby22-x64/bin/ruby.exe
#
# This file was generated by RubyGems.
#
# The application 'travis' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

gem 'travis', version
load Gem.bin_path('travis', 'travis', version)
```

**Comment by tkelman** [comment] 2017-02-07 04:15
shebang scripts only work inside a posix emulation environment like cygwin or msys.

**Comment by bramtayl** [comment] 2017-02-07 07:02
Hmm, ok. Well, here is a work-around:

```julia
path = readstring(`which travis`) |> chomp
# replace /c/ with c:/ for windows paths
path_edit = replace(path, r"/([a-z])/", s"\g<1>:/")
# work around for windows: call ruby directly
run(`ruby $path_edit login`)
```

Still confused as to how I can run travis from the command prompt if shebang scripts don't work?

**Comment by tkelman** [comment] 2017-02-07 09:14
it's probably running the bat file from the command prompt

**Comment by bramtayl** [comment] 2017-02-10 00:40
Ok, I think this might be a bigger issue than i thought. Once I got git's unix tools off my path, things like `run(`dir`)` stopped working with the same error. I guess git's version doesn't have the same issue?

**Comment by vtjnash** [comment] 2017-02-10 01:54
It's quite possible that git bundles executable versions of `cmd` builtin functions to improve their posix emulation layer. You can run a batch script by spawning the batch interpreter (`cmd.exe`, or you can use `env(ENV, "COMSPEC", "cmd.exe")`)

closing since this is a user usage question, not a bug report / feature request, and better suited to discourse.

**Closed** 2017-02-28 05:16 UTC
Labels: upstream, windows
