### ISSUE TITLE
Unstable vararg inlining

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#20668] opened 2017-02-18 21:17 UTC
The following is reduced from an old (1 week) version of `ImageCore.jl` test. It fails as is but passes if the for loop earlier in the `try` block is removed (or other minor tweaks of the code).

```julia
immutable MappedArray{T,N,A<:AbstractArray} <: AbstractArray{T,N}
    data::A
end
of_eltype{S,N}(data::AbstractArray{S,N}) = MappedArray{Float64,N,typeof(data)}(data)
of_eltype(data::AbstractArray{Float64}) = data
Base.size(A::MappedArray) = size(A.data)

struct StackedView{T<:Number,N,A<:Tuple{Vararg{AbstractArray{T}}}} <: AbstractArray{T,N}
    function (::Type{StackedView{T,N,A}}){T,N,A}(parents::A)
        for p in parents
            size(p) == (2, 2)
        end
        new{T,N,A}()
    end
end

@inline function StackedView(arrays::AbstractArray...)
    stackedview(arrays...)
end

@inline function stackedview(arrays::AbstractArray...)
    arrays_T = map(of_eltype, arrays)
    StackedView{Float64,2,typeof(arrays_T)}(arrays_T)
end

using Base.Test

try
    for (A, B) = (([1 3;2 4], [-1 -5; -2 -3]),
                  ([1 3;2 4], [-1.0 -5.0; -2.0 -3.0]),
                  )
        stackedview([1 3;2 4], B)
    end

    a, b = Float32[0.1 0.2; 0.3 0.4], [0.5 0.6; 0.7 0.8]
    V = @inferred(StackedView(a, a, b))
finally
end
```

Working version of `code_warntype`:
```julia
Variables:
  #self#::Any
  arrays::Tuple{Array{Float32,2},Array{Float32,2},Array{Float64,2}}
  arrays_T::Tuple{MappedArray{Float64,2,Array{Float32,2}},MappedArray{Float64,2,Array{Float32,2}},Array{Float64,2}}

Body:
  begin
      SSAValue(1) = (Core.getfield)(arrays::Tuple{Array{Float32,2},Array{Float32,2},Array{Float64,2}}, 1)::Array{Float32,2}
      SSAValue(2) = (Core.getfield)(arrays::Tuple{Array{Float32,2},Array{Float32,2},Array{Float64,2}}, 2)::Array{Float32,2}
      SSAValue(3) = (Core.getfield)(arrays::Tuple{Array{Float32,2},Array{Float32,2},Array{Float64,2}}, 3)::Array{Float64,2}
      $(Expr(:inbounds, false))
      # meta: location /home/yuyichao/projects/contrib/ImageCore.jl/test/views.jl stackedview 22
      arrays_T::Tuple{MappedArray{Float64,2,Array{Float32,2}},MappedArray{Float64,2,Array{Float32,2}},Array{Float64,2}} = (Core.tuple)($(Expr(:new, :($(QuoteNode(MappedArray{Float64,2,Array{Float32,2}}))), SSAValue(1))), $(Expr(:new, :($(QuoteNode(MappedArray{Float64,2,Array{Float32,2}}))), SSAValue(2))), SSAValue(3))::Tuple{MappedArray{Float64,2,Array{Float32,2}},MappedArray{Float64,2,Array{Float32,2}},Array{Float64,2}}
      # meta: pop location
      $(Expr(:inbounds, :pop))
      return $(Expr(:invoke, MethodInstance for StackedView{Float64,2,Tuple{MappedArray{Float64,2,Array{Float32,2}},MappedArray{Float64,2,Array{Float32,2}},Array{Float64,2}}}(::Tuple{MappedArray{Float64,2,Array{Float32,2}},MappedArray{Float64,2,Array{Float32,2}},Array{Float64,2}}), :($(QuoteNode(StackedView{Float64,2,Tuple{MappedArray{Float64,2,Array{Float32,2}},MappedArray{Float64,2,Array{Float32,2}},Array{Float64,2}}}))), :(arrays_T)))
  end::StackedView{Float64,2,Tuple{MappedArray{Float64,2,Array{Float32,2}},MappedArray{Float64,2,Array{Float32,2}},Array{Float64,2}}}
```

Broken version of `code_warntype`:
```julia
Variables:
  #self#::Any
  arrays::Tuple{Array{Float32,2},Array{Float32,2},Array{Float64,2}}

Body:
  begin 
      return $(Expr(:invoke, MethodInstance for stackedview(::Array{Float32,2}, ::Vararg{AbstractArray,N} where N), :(Main.stackedview), :((Core.getfield)(arrays, 1)::Array{Float32,2}), :((Core.getfield)(arrays, 2)::Array{Float32,2}), :((Core.getfield)(arrays, 3)::Array{Float64,2})))
  end::StackedView{Float64,2,_} where _
```

**Comment by vtjnash** [comment] 2017-06-09 21:08
I believe this was fixed by #21677

**Closed by vtjnash** 2017-06-09 21:08 UTC
Labels: inference

**Comment by tkelman** [comment] 2017-06-10 00:21
but not tested

**Comment by vtjnash** [comment] 2017-06-10 04:25
It should be tested there too. If I'm understanding the root cause correctly, the fix for this was inherent to the redesign, and (one of) the main purposes of it.

**Comment by tkelman** [comment] 2017-06-10 04:28
that pr did not add any tests at all
