### ISSUE TITLE
Many segfaults in x86_64-apple-darwin CI

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#44891] opened 2022-04-07 07:33 UTC
Not sure if this is an issue that is OK to ignore, but https://buildkite.com/julialang/julia-master/builds/10799#a370ae8f-3465-4ae1-b227-85b3b42e3b96 (in #44792 but the PR is likely irrelevant) has a couple of

```
      From worker 4:
      From worker 4:	signal (6): Abort trap: 6
      From worker 4:	in expression starting at none:0
```

and many

```
      From worker 5:	signal (11): Segmentation fault: 11
      From worker 5:	in expression starting at none:0
```

from a few workers (including a few of this from worker 4). Not sure if it's related but this test also has

```
      From worker 17:	julia(34134,0x70000c014000) malloc: *** error for object 0x7fc9ddc8aac0: pointer being realloc'd was not allocated
      From worker 17:	julia(34134,0x70000c014000) malloc: *** set a breakpoint in malloc_error_break to debug
      From worker 17:
      From worker 17:	signal (6): Abort trap: 6
      From worker 17:	in expression starting at none:0
      From worker 17:	__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
      From worker 17:	Allocations: 11064404 (Pool: 11058487; Big: 5917); GC: 18
```

aarch64-apple-darwin in the same build also has many similar segfauilt messages.

**Comment by giordano** [comment] 2022-04-07 07:56
Likely duplicate of #44562

**Comment by maleadt** [comment] 2022-04-07 08:15
I don't know, it starts with an SIGABRT here. The fact that it then cascades into segfaults is fixed by https://github.com/JuliaLang/julia/issues/44562#issuecomment-1065320081=.

**Comment by ViralBShah** [comment] 2022-09-05 22:34
Closing since we have been better on darwin CI recently.

**Closed by ViralBShah** 2022-09-05 22:34 UTC
Labels: bug, mac, ci
