### ISSUE TITLE
Failed guessing eltype when mapping an user-defined function on a sparse arrays

### ISSUE THREAD

**Issue by abraunst** [JuliaLang/julia#34931] opened 2020-02-29 12:11 UTC
EDIT: Summary:  `B = A; (t->B()).(spzeros(10))` constructs a sparse vector of type `Any`, while `(t->A()).(spzeros(10))` constructs correctly a sparse array of type `A`

I hope this is not a duplicate.
```julia
julia> struct A end
julia> function test(x)
           B = A
           (t->B()).(x)
       end
julia> test(zeros(1))
1-element Array{A,1}:
 A()
```
all seems ok. However,

```julia
julia> using SparseArrays
julia> test(spzeros(1))
1-element SparseVector{Any,Int64} with 1 stored entry:
  [1]  =  A()
```
So the eltype could not be infered. Note that 
```julia
julia> (t->A()).(spzeros(1))
1-element SparseVector{A,Int64} with 1 stored entry:
  [1]  =  A()
```
has no problem whatsoever

**Comment by abraunst** [comment] 2020-03-02 12:03
Even simpler example, showing that it's about `map`, `SparseArrays` and user defined functions, I adjusted the title
```julia
julia> f(x)=1.0; map(f, spzeros(2))
2-element SparseVector{Any,Int64} with 2 stored entries:
  [1]  =  1.0
  [2]  =  1.0
```

**Comment by mbauman** [comment] 2020-03-02 20:40
Duplicate of #19595

**Closed by mbauman** 2020-03-02 20:40 UTC

**Comment by mbauman** [comment] 2020-03-02 20:42
In short: Sparse broadcast is one of the last places that depends upon inference to get its eltype and it's a very major refactor to fix that as it requires a design that permits incremental widening by value.  Sparse's map is just broadcast + an extra shape check.

**Comment by abraunst** [comment] 2020-03-02 21:39
> In short: Sparse broadcast is one of the last places that depends upon inference to get its eltype and it's a very major refactor to fix that as it requires a design that permits incremental widening by value. Sparse's map is just broadcast + an extra shape check. 

Thanks a lot for the explanation! I'm sorry I could not find #19595. :-/ 

> A type-instability like referring to a non-constant global is one of the things that can reveal this.

In the first example everything is wrapped in the function `ŧest()`, so there shouldn't be any non-cost global right?

**Comment by mbauman** [comment] 2020-03-02 23:07
Ah, interesting, I missed how that first example is slightly different.  The root cause here is the same — there's apparently a type instability still — but I'm not entirely sure why.
