### ISSUE TITLE
uppercase/lowercase functions are not portable?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#11471] opened 2015-05-28 14:21 UTC
Since @ScottPJones was mentioning upper/lowercase functions recently, I took a quick look at them and I noticed that we are calling `towupper` and `towlower`, which are C99 functions that accept `wchar_t` arguments.

Unfortunately, this means that they are broken on Windows (where `wchar_t` is 16 bits) for any character outside the BMP.   Even on other platforms with a 32-bit `wchar_t`, they are going to return different results on different systems, and many systems will have out-of-date Unicode tables.  They are also locale-dependent; I'm not sure if this is desirable for us.

utf8proc has up-to-date upper/lower/titlecase mapping data already in its "database" (generated from http://www.unicode.org/Public/UNIDATA/UnicodeData.txt), so maybe we should just add a `utf8proc_toupper` function (etc.) to utf8proc to make this accessible.  Then we could call that (probably plus a check for the common case of ASCII codepoints).

**Comment by ScottPJones** [comment] 2015-05-28 14:49
Yep... although I wouldn't solve this with utf8proc... I'd intended to tackle this shortly (it's something else we need for our project, and I'd prefer to use Julia as much as possible).

**Comment by JeffBezanson** [comment] 2015-05-28 14:56
> although I wouldn't solve this with utf8proc

Why not? If utf8proc does this wrong, we should just fix it instead of re-implementing.

**Comment by ScottPJones** [comment] 2015-05-28 14:58
Because, I believe it can better be implemented in pure Julia (sorry, now I'm a convert!)

**Comment by jiahao** [comment] 2015-05-28 14:59
Essentially a duplicate of #7848

The Unicode standard defines upper-lower case mappings on a per character basis, but a correct transformation must necessarily take into account the locale. (See the infamous Turkish i - İ, ı - I pairings as the most egregious examples.)

**Comment by ScottPJones** [comment] 2015-05-28 15:09
I don't think this really is a duplicate of #7848, and should be reopened.
If you look at ICU (probably the most widely used library for this sort of stuff), you can do either locale dependent or locale independent case mappings...
I think that in Base, Julia should give consistent results on all platforms, using locale independent mappings.
I think fancy locale dependent mappings, as discussed in #7848, belong in a package (I'll have to look, they may already be handled by the ICU.jl package).

**Comment by jiahao** [comment] 2015-05-28 15:12
Did you read the discussion in #7848? The conclusion was exactly what you said, that we should have a locale independent choice in Base and have the locale specific choices not in base.

**Comment by ScottPJones** [comment] 2015-05-28 15:14
I missed the last couple of comments (I'm in a meeting right now!)  Sorry, my fault totally... The only difference is that I think any locale dependent mappings should be done as extending the Base methods via a Package...

**Comment by ScottPJones** [comment] 2015-05-28 15:17
Also, I think @stevengj's point was something else, and this may need to still be open... it was about characters outside the BMP not being handled (even in a local independent fashion), on Windows,
simply due to the way the functions are implemented...

**Comment by jiahao** [comment] 2015-05-28 15:20
If it really makes you happier, I'll close #7848 in favor of this issue.

**Comment by ScottPJones** [comment] 2015-05-28 15:31
Actually, I don't think #7848 needs to be closed either :grinning:
IMO, this one is about non-BMP case mapping being broken on Windows (good catch, @stevengj),
and #7848 is about the need for having both locale independent (in Base) and locale dependent (hopefully in a package outside of Base).

**Comment by stevengj** [comment] 2015-05-28 21:22
Pure Julia code for this has its pluses and minuses.  On the minus side, it is more work: this information is already in utf8proc, and adding a couple of functions to expose it to Julia is literally something like 6 lines of C code.  Also on the minus side, having it in utf8proc makes it available to non-Julia users.  On the plus side, writing code in Julia is more fun, and potentially allows for more optimizations (e.g. inlining).

For my own part, I tend to default to the path of least work.

**Comment by ScottPJones** [comment] 2015-05-28 21:56
About the minuses... more work, well, maybe, but it's something that I'd like to do when I want to take a break from other stuff :grinning:  (i.e. the Julia is fun part), plus doing it in Julia helps improve my Julia skills, and finally, I'm not talking at all about removing anything from `utf8proc`, so `utf8proc` is still available to non-Julia users (how many are there?)
About the pluses... I've been thinking about ways to make the size of the data structures much smaller,
and to write the code to generate the data structures (probably into a C source code file) in Julia also...
[I posted on julia-users, https://groups.google.com/forum/#!topic/julia-users/CyrLc_E0dac, to try to get some help to learn the best "julian" way of doing that, but nobody responded... :sad:]

**Comment by stevengj** [comment] 2015-05-29 17:28
Actually, it looks like the `towupper` functions etcetera take a `wint_t`, [even on Windows](https://msdn.microsoft.com/en-us/library/45119yx3.aspx), which in my understanding is at least 32 bits wide.  In which case the Julia `ccall` is wrong on Windows.

But I'm confused, because we have test coverage of `lowercase` etc... if we are passing the wrong type on Windows, how could we not have noticed?

**Comment by stevengj** [comment] 2015-05-30 03:34
Sorry, I didn't realize that `(for #....)` would close an issue on github; I thought it had to be `fixed` or `closes` or similar.

**Comment by stevengj** [comment] 2015-05-30 04:14
By the way, should `ucfirst` be using titlecase rather than uppercase for the first letter?

**Comment by ScottPJones** [comment] 2015-05-30 06:59
Yes about using titlecase

**Comment by ScottPJones** [comment] 2015-05-30 07:31
BTW, could you reopen #7848, which really is separate, and isn't addressed by your nice fix to this issue?

**Comment by jiahao** [comment] 2015-05-30 10:52
I don't see the need. We already decided that locale-specific transformations should not belong in base, which is the remaining part of that issue.

**Closed** 2015-06-01 13:13 UTC
Labels: unicode

**Comment by nalimilan** [comment] 2015-06-03 06:22
@stevengj I'd have preferred we wait for a true utf8proc release before relying on it. Now I need to package this development version to build the nightlies...

**Comment by tkelman** [comment] 2015-06-03 07:09
There is a tag https://github.com/JuliaLang/utf8proc/releases/tag/1.3-dev1 but it's got a -dev1 marker on it, should we promote that to 1.3.0?

**Comment by nalimilan** [comment] 2015-06-03 10:05
Well, not before we sort out https://github.com/JuliaLang/utf8proc/issues/42. :-)

**Comment by tkelman** [comment] 2015-06-03 10:10
It would also be friendlier to distro packagers to put this change in under a conditional utf8proc version number check.
