### ISSUE TITLE
break in catch block skips finally

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#12925] opened 2015-09-03 07:06 UTC
```julia
function f()
    for i in [1,2,3,4]

        println("i = $i")
        try
            [1,2][i]
        catch e
            println("catch!")
            if (rand() > 0.5)
                break
            else
                return
            end
        finally
            println("finally!")
        end

        println("")
    end
end
```

`return` from the catch block results in the `finally` block being executed.
However, `break` from the catch block causes the `finally` block to be skipped.

**Comment by tkelman** [comment] 2015-09-03 08:21
duplicate of #12806

**Closed by tkelman** 2015-09-03 08:21 UTC
