### ISSUE TITLE
mbedTLS complains about failing entropy sources on CI

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#38601] opened 2020-11-29 00:16 UTC
e.g. in https://build.julialang.org/#/builders/79/builds/6315/steps/5/logs/stdio

```
nested task error: Failed - mbedTLS: ctr_drbg_init returned (-0x0034) CTR_DRBG - The entropy source failed while requesting
```

**Comment by vtjnash** [comment] 2020-11-29 02:01
Duplicate of https://github.com/JuliaLang/Downloads.jl/issues/58 (closed wont-fix upstream)

May be fixed soon though by changing to the native TLS engines?

**Comment by Keno** [comment] 2020-11-29 02:03
> This looks like a problem on VMs that don't have a real entropy source. Seems rare and like there's not much we can do about it here. What can you do? VMs suck man_shrugging

The buildbot is not a VM.

**Closed** 2022-03-13 05:19 UTC
Labels: mac, ci
