### ISSUE TITLE
julia-1.7.1 with curl >=7.81.0: Build failure

### ISSUE THREAD

**Issue by ChristianS99** [JuliaLang/julia#44657] opened 2022-03-17 16:22 UTC
```
Generating REPL precompile statements... 26/36ERROR: LoadError: IOError: stream is closed or unusable
Stacktrace:
 [1] check_open
   @ ./stream.jl:386 [inlined]
 [2] uv_write_async(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
   @ Base ./stream.jl:1018
 [3] uv_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
   @ Base ./stream.jl:981
 [4] unsafe_write(s::Base.TTY, p::Ptr{UInt8}, n::UInt64)
   @ Base ./stream.jl:1064
 [5] mktemp(fn::Main.anonymous.var"#2#6"{Set{String}, String, Base.DevNull}, parent::String)
   @ Base.Filesystem ./file.jl:722
in expression starting at /var/tmp/portage/dev-lang/julia-1.7.1-r3/work/julia-1.7.1/contrib/generate_precompile.jl:3
```
with curl-7.80.0 build is fine

**Comment by giordano** [comment] 2022-03-18 00:18
Sounds much like a duplicate of  #43249

**Comment by ChristianS99** [comment] 2022-03-18 07:51
Looks similar, but I tried with proposed patches or older versions of libgit2, but only installing an old version of curl helped.
Therefore I made a new issue.

**Comment by ngam** [comment] 2022-03-19 13:20
at conda-forge, we had a similar problem and it was resolved with updating the downloads module.

https://github.com/conda-forge/julia-feedstock/pull/178/files

Basically, get the latest Downloads from master or something, which should already fix things. However, we also had patches for libgit2, etc. so you may need those as well.

**Comment by ngam** [comment] 2022-03-19 13:23
(disclaimer: if I remember correctly, I thought we were getting segfaults at the time, though I am not too sure)

**Comment by mtasaka** [comment] 2022-03-19 13:36
This is actually julia is segfaulting with curl 7.81.0
https://bugzilla.redhat.com/show_bug.cgi?id=2056842
https://bugzilla-attachments.redhat.com/attachment.cgi?id=1862510

So my guess is that in fact #43249 fixed nothing.

**Comment by mtasaka** [comment] 2022-03-19 13:41
This should be fixed with https://github.com/JuliaLang/Downloads.jl/pull/164

**Comment by giordano** [comment] 2022-03-19 14:25
Nothing to do here then, right?

**Comment by ngam** [comment] 2022-03-19 17:07
> Nothing to do here then, right?

The only thing would be be backport a higher downloads version to 1.7.1 and prior, and that's it...

https://github.com/JuliaLang/julia/blob/ac5cc99908d463582e66db3368b9b48fae1e2525/stdlib/Downloads.version#L1

but I don't know if that's actually logical --- I get there is an LTS support thing going on, but that won't be 1.7.1, right? It would be 1.7.2/1.6.5 and whatever comes after them. So, yes, I would agree nothing to do here besides pointing out the fix if someone really really really wants to use 1.7.1 at this point in time...

**Comment by ngam** [comment] 2022-03-19 17:08
i.e. it would make more sense to upgrade julia if one wants to use the upgraded curl imo

**Comment by giordano** [comment] 2022-03-19 17:10
> The only thing would be be backport a higher downloads version to 1.7.1 and prior, and that's it...

It's quite hard to backport changes to an already released version.  However the fix in `Downloads.jl` is already in the `master` branch of Julia and it has been also backported to the 1.7 branch with https://github.com/JuliaLang/julia/pull/44433.

I don't see anything else we can possibly do here, so I'm going to close this issue.

**Closed by giordano** 2022-03-19 17:10 UTC
Labels: build

**Comment by ChristianS99** [comment] 2022-03-20 10:36
OK, thx. When it works in 1.7.2, that's fine for me. Thx for clarification
