### ISSUE TITLE
'make test' fails for julia-1.11.0-rc1

### ISSUE THREAD

**Issue by sergstesh** [JuliaLang/julia#54966] opened 2024-06-27 23:13 UTC
I downloaded source tarball ( wget -t0 -c https://github.com/JuliaLang/julia/releases/download/v1.11.0-rc1/julia-1.11.0-rc1-full.tar.gz ) and unpacked it the usual way.

Then, after doing 'cd julia-1.11.0-rc1' I ran the following command line:

`nice -n 19 make test 1>make_test.log 2>&1`
.

Output of 'versioninfo()':

```
julia> versioninfo()
Julia Version 1.11.0-rc1
Commit 3a35aec36d (2024-06-25 10:23 UTC)
Build Info:

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) N100
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)

julia>
```
.

Test failures can be seen in the uploaded 'make_test.log' file.
[make_test.log](https://github.com/user-attachments/files/16022152/make_test.log)

**Comment by giordano** [comment] 2024-06-28 00:18
I can't open the log file now, but is there anything new compared to  #54280,  #54777, #54234, or #54771?

**Comment by giordano** [comment] 2024-08-13 20:00
Duplicate of #54777

**Closed by giordano** 2024-08-13 20:00 UTC
