### ISSUE TITLE
Inplace `map!` accepts only `AbstractArray`s, but not generators

### ISSUE THREAD

**Issue by bvdmitri** [JuliaLang/julia#51767] opened 2023-10-19 07:38 UTC
Is there a particular reason why this cannot work?

```julia
julia> map!(+, zeros(5), (i for i in 1:5), (i for i in 1:5))
ERROR: MethodError: no method matching map!(::typeof(+), ::Vector{Float64}, ::Base.Generator{UnitRange{Int64}, typeof(identity)}, ::Base.Generator{UnitRange{Int64}, typeof(identity)})

Closest candidates are:
  map!(::F, ::AbstractArray, ::AbstractArray) where F
```
Or is it just a missing method?

For example, there is an easy workaround
```julia
for (i, a, b) in zip(eachindex(output), input_a, input_b)
    output[i] = f(a, b)
end
```

Other non-standard iterators are supported, but only if they are subtyped as an `AbstractArray`
```julia
julia> map!(+, zeros(5), 1:5, 1:5)
5-element Vector{Float64}:
  2.0
  4.0
  6.0
  8.0
 10.0
```

**Comment by simeonschaub** [comment] 2023-10-19 13:29
duplicate of #38344

**Closed by simeonschaub** 2023-10-19 13:29 UTC
Labels: iteration
