### ISSUE TITLE
`core` tests do not reliably throw expected errors

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#43376] opened 2021-12-09 03:20 UTC
I have noticed that running `Base.runtests(["core"])` fails, but running `make test-core` does not.  This is reproducible on linux x86_64 and macOS aarch64 on both latest `master` (63f5b8a1654a77a91eccd619a665da5080ea6058 as of this writing) and `v1.7.0`, but not on anything earlier, like `1.6.4`.

These three tests fail: https://github.com/JuliaLang/julia/blob/63f5b8a1654a77a91eccd619a665da5080ea6058/test/core.jl#L3521-L3523

Intriguingly, when input directly into the REPL of a new session, these statements do not cause a problem on 1.6.4 or 1.7, although they do give different answers:
```
$ julia-1.7.0 -E 'Vararg{Int, N} where N<:T where T'
Vararg{Int64}
$ julia-1.6.4 -E 'Vararg{Int, N} where N<:T where T'
Vararg{Int64, N} where {T, N<:T}
```

I'm not sure what changes occur to the running Julia session when running `make test-core`.  Is it expected that, at all times, these tests should cause errors?

**Comment by KristofferC** [comment] 2021-12-09 03:47
Duplicate of https://github.com/JuliaLang/julia/issues/43004

**Closed** 2021-12-10 00:44 UTC
