### ISSUE TITLE
Documentation should somehow expose/list common scientific algorithms/packages

### ISSUE THREAD

**Issue by Datseris** [JuliaLang/julia#30812] opened 2019-01-23 14:06 UTC
This comes from this : https://docs.julialang.org/en/v1.0/search/?q=Fourier+transform 

which searches for Fourier transforms in the Julia docs but finds nothing. Google is not that great either, showing FFTW (which has a specialized real-to-real only version) but not AbstractFFTs which has the standard general version.

I think there should be a page in the manual titled "scientific algorithms" or similar, which has sections with titles like "Fourier Transforms", etc., and in text each section links the various packages. I feel like the Fourier transform is just too important for a technical computing language to not be mentioned anywhere. True, it is not part of the core language, but shouldn't the official language manual at least mention it?

I am tagging @andreasnoack who resolved my question on Slack.

**Comment by JeffBezanson** [comment] 2019-01-23 17:13
A package search tool like juliaobserver is the right thing for this I think.

**Comment by Datseris** [comment] 2019-01-23 17:37
Yes, this is a valid response. As a side note I want to add:

https://docs.julialang.org/en/v1.0/search/?q=juliaobserver

https://docs.julialang.org/en/v1.0/search/?q=juliaobserver (this has spaces between names)

I can see that Julia observer is mentioned in the homepage. Why are you against it being in the docs? 

--- 

Continuing to the main issue: it becomes even worse when using the suggestion: https://juliaobserver.com/searches?utf8=%E2%9C%93&term=Fourier+Transform

You can see that `AbstractFFTs` is number 22 (not even visible until you scroll down) even though it has the old core Julia code on FFTs (correct me if I am wrong).

You may disagree with my suggestion here, but I think you will agree with the fact that Julia packages have a visibility/discovery difficulty. I believe this issue can't be solved with an "automated package searcher generator" but with humans serving as curators. This is just my opinion of course but it is also clear that the designers of the Julia website (whoever they may be) agree with this opinion, due the very large portion of the website covered by the "Ecosystem" (which is curated and not automatically generated).

I have renamed my issue title to reflect the true concern, which was never specifically about Fourier Transforms. To solve it, why not link/expose the ecosystem part of the official website _again in the documentation?_ I will open a PR there to link Fourier Transforms in the Scientific domains.

**Comment by ViralBShah** [comment] 2019-01-23 19:53
There is a very nascent JuliaDocs effort to make the Julia package ecosystem a lot more visible and discoverable.

@SimonDanisch

**Comment by andreasnoack** [comment] 2019-01-23 20:22
I'm not sure what the right solution is but I do agree that there is a general issue with visibility of important scientific tools and I think developers tend to underestimate this issue. I think the issue is particularly severe for ffts where it is quite unintuitive that the package to look for is `AbstractFFTs`. Several people have been confused about where to find ffts.

cc @stevengj

**Comment by JeffBezanson** [comment] 2019-01-23 21:19
There is a "Resources" section under "Getting Started" in the docs. We should add a couple more links there. That section needs some work: we should remove the command line help (#28845), and instead briefly mention packages (`]add` and `using`).

**Comment by Datseris** [comment] 2019-01-23 21:44
> Did you forget to do this.

Yes, sorry @KristofferC . Apparently I forgot to press the "save" button... 

I am very glad that there are efforts to improve this situation. I will try to contribute in my own way! :)

**Comment by antoine-levitt** [comment] 2019-01-25 08:21
Let's be honest, people who are looking for FFTs are not going on the julia website, they are going to type "fft" in julia, see it doesn't work, then search "julia FFT" in their favorite search engine. Currently, the first directly usable link for me on google is number 4, pointing at https://discourse.julialang.org/t/where-is-the-fft/16512. I'm not sure how to manipulate search engines into pointing to the correct thing, but maybe at least https://github.com/JuliaMath/FFTW.jl could be made friendlier. I'll make a PR.

**Comment by ViralBShah** [comment] 2022-03-13 05:53
Closing since things are generally better to find nowadays - and also not sure what specifically to do here. Perhaps an issue for the website repo?

**Closed by ViralBShah** 2022-03-13 05:53 UTC
