### ISSUE TITLE
Julia crash after destructuring into a pair

### ISSUE THREAD

**Issue by sairus7** [JuliaLang/julia#48332] opened 2023-01-18 10:48 UTC
I've been playing around with destructuring syntax to find out if it works only for tuples or as well for pairs. 
So maybe I entered wrong syntax string that was interpreted with error.
Julia 1.8.5 on Windows.

```julia
julia> p = (:a => [1], :b => [2])
(:a => [1], :b => [2])

julia> (a, xa), (b, xb) = p 
(:a => [1], :b => [2])

julia> a # this works fine
:a

julia> (a => xa), (b => xb) = p 
(:a => [1], :b => [2])

julia> a # this makes Julia crash
```
<details>
  <summary>Error output</summary>
  
  ```
┌ Error: Error in the keymap
│   exception =
│    MethodError: no method matching isless(::Vector{Int64}, ::Symbol)
│    Closest candidates are:
│      isless(::AbstractVector, ::AbstractVector) at abstractarray.jl:2612
│      isless(::Any, ::Missing) at missing.jl:88
│      isless(::Missing, ::Any) at missing.jl:87
│      ...
│    Stacktrace:
│      [1] min(x::Symbol, y::Vector{Int64})
│        @ Base .\operators.jl:494
│      [2] _extrema_rf
│        @ .\reduce.jl:851 [inlined]
│      [3] BottomRF
│        @ .\reduce.jl:81 [inlined]
│      [4] MappingRF
│        @ .\reduce.jl:95 [inlined]
│      [5] _foldl_impl(op::Base.MappingRF{Base.ExtremaMap{typeof(identity)}, Base.BottomRF{typeof(Base._extrema_rf)}}, init::Base._InitialValue, itr::Pair{Symbol, Vector{Int64}})
│        @ Base .\reduce.jl:62
│      [6] foldl_impl(op::Base.MappingRF{Base.ExtremaMap{typeof(identity)}, Base.BottomRF{typeof(Base._extrema_rf)}}, nt::Base._InitialValue, itr::Pair{Symbol, Vector{Int64}})
│        @ Base .\reduce.jl:48
│      [7] mapfoldl_impl(f::Base.ExtremaMap{typeof(identity)}, op::typeof(Base._extrema_rf), nt::Base._InitialValue, itr::Pair{Symbol, Vector{Int64}})
│        @ Base .\reduce.jl:44
│      [8] mapfoldl(f::Function, op::Function, itr::Pair{Symbol, Vector{Int64}}; init::Base._InitialValue)
│        @ Base .\reduce.jl:162
│      [9] mapfoldl
│        @ .\reduce.jl:162 [inlined]
│     [10] #mapreduce#262
│        @ .\reduce.jl:294 [inlined]
│     [11] mapreduce
│        @ .\reduce.jl:294 [inlined]
│     [12] extrema(f::Function, itr::Pair{Symbol, Vector{Int64}}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Base .\reduce.jl:840
│     [13] extrema(f::Function, itr::Pair{Symbol, Vector{Int64}})
│        @ Base .\reduce.jl:840
│     [14] extrema(itr::Pair{Symbol, Vector{Int64}}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Base .\reduce.jl:810
│     [15] extrema(itr::Pair{Symbol, Vector{Int64}})
│        @ Base .\reduce.jl:810
│     [16] region(s::Union{REPL.LineEdit.MIState, REPL.LineEdit.ModeState, IOBuffer})
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:137
│     [17] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, terminal::REPL.Terminals.UnixTerminal, buf::IOBuffer, state::REPL.LineEdit.InputAreaState, prompt::Any; indent::Int64, region_active::Bool)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:435
│     [18] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, terminal::REPL.Terminals.UnixTerminal, s::Union{REPL.LineEdit.PrefixSearchState, REPL.LineEdit.PromptState}; beeping::Bool)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:1846
│     [19] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, terminal::REPL.Terminals.UnixTerminal, s::Union{REPL.LineEdit.PrefixSearchState, REPL.LineEdit.PromptState})
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:1843
│     [20] refresh_multi_line(terminal::REPL.Terminals.UnixTerminal, args::Any; kwargs::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:538
│     [21] refresh_multi_line(terminal::REPL.Terminals.UnixTerminal, args::Any)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:535
│     [22] refresh_multi_line(s::REPL.LineEdit.PromptState; kw::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:417
│     [23] refresh_multi_line
│        @ C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:412 [inlined]
│     [24] refresh_multi_line(::REPL.LineEdit.MIState)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:232
│     [25] refresh_line
│        @ C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:1333 [inlined]
│     [26] commit_line(s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2141
│     [27] (::REPL.LineEdit.var"#114#168")(::REPL.LineEdit.MIState, ::Any, ::Vararg{Any})
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2232
│     [28] #invokelatest#2
│        @ .\essentials.jl:729 [inlined]
│     [29] invokelatest
│        @ .\essentials.jl:726 [inlined]
│     [30] (::REPL.LineEdit.var"#25#26"{REPL.LineEdit.var"#114#168", String})(s::Any, p::Any)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:1472
│     [31] prompt!(term::REPL.Terminals.TextTerminal, prompt::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2603
│     [32] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
│        @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2505
│     [33] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
│        @ REPL C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\REPL.jl:1248
│     [34] (::REPL.var"#49#54"{REPL.LineEditREPL, REPL.REPLBackendRef})()
│        @ REPL .\task.jl:484
└ @ REPL.LineEdit C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2605
julia>

Unhandled Task ERROR: MethodError: no method matching isless(::Vector{Int64}, ::Symbol)
Closest candidates are:
  isless(::AbstractVector, ::AbstractVector) at abstractarray.jl:2612
  isless(::Any, ::Missing) at missing.jl:88
  isless(::Missing, ::Any) at missing.jl:87
  ...
Stacktrace:
  [1] min(x::Symbol, y::Vector{Int64})
    @ Base .\operators.jl:494
  [2] _extrema_rf
    @ .\reduce.jl:851 [inlined]
  [3] BottomRF
    @ .\reduce.jl:81 [inlined]
  [4] MappingRF
    @ .\reduce.jl:95 [inlined]
  [5] _foldl_impl(op::Base.MappingRF{Base.ExtremaMap{typeof(identity)}, Base.BottomRF{typeof(Base._extrema_rf)}}, init::Base._InitialValue, itr::Pair{Symbol, Vector{Int64}})
    @ Base .\reduce.jl:62
  [6] foldl_impl(op::Base.MappingRF{Base.ExtremaMap{typeof(identity)}, Base.BottomRF{typeof(Base._extrema_rf)}}, nt::Base._InitialValue, itr::Pair{Symbol, Vector{Int64}})
    @ Base .\reduce.jl:48
  [7] mapfoldl_impl(f::Base.ExtremaMap{typeof(identity)}, op::typeof(Base._extrema_rf), nt::Base._InitialValue, itr::Pair{Symbol, Vector{Int64}})
    @ Base .\reduce.jl:44
  [8] mapfoldl(f::Function, op::Function, itr::Pair{Symbol, Vector{Int64}}; init::Base._InitialValue)
    @ Base .\reduce.jl:162
  [9] mapfoldl
    @ .\reduce.jl:162 [inlined]
 [10] #mapreduce#262
    @ .\reduce.jl:294 [inlined]
 [11] mapreduce
    @ .\reduce.jl:294 [inlined]
 [12] extrema(f::Function, itr::Pair{Symbol, Vector{Int64}}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base .\reduce.jl:840
 [13] extrema(f::Function, itr::Pair{Symbol, Vector{Int64}})
    @ Base .\reduce.jl:840
 [14] extrema(itr::Pair{Symbol, Vector{Int64}}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Base .\reduce.jl:810
 [15] extrema(itr::Pair{Symbol, Vector{Int64}})
    @ Base .\reduce.jl:810
 [16] region(s::Union{REPL.LineEdit.MIState, REPL.LineEdit.ModeState, IOBuffer})
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:137
 [17] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, terminal::REPL.Terminals.UnixTerminal, buf::IOBuffer, state::REPL.LineEdit.InputAreaState, prompt::Any; indent::Int64, region_active::Bool)
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:435
 [18] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, terminal::REPL.Terminals.UnixTerminal, s::Union{REPL.LineEdit.PrefixSearchState, REPL.LineEdit.PromptState}; beeping::Bool)
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:1846
 [19] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, terminal::REPL.Terminals.UnixTerminal, s::Union{REPL.LineEdit.PrefixSearchState, REPL.LineEdit.PromptState})
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:1843
 [20] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, s::REPL.LineEdit.ModeState; kw::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:420
 [21] refresh_multi_line(termbuf::REPL.Terminals.TerminalBuffer, s::REPL.LineEdit.ModeState)
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:420
 [22] refresh_line(s::Union{REPL.LineEdit.MIState, REPL.LineEdit.ModeState, IOBuffer}, termbuf::REPL.Terminals.AbstractTerminal)
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:1334
 [23] activate(p::REPL.LineEdit.TextInterface, s::REPL.LineEdit.ModeState, termbuf::REPL.Terminals.AbstractTerminal, term::REPL.Terminals.TextTerminal)
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2414
 [24] transition(f::Function, s::REPL.LineEdit.MIState, newmode::Union{Symbol, REPL.LineEdit.TextInterface})
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2446
 [25] transition
    @ C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2450 [inlined]
 [26] (::REPL.var"#do_respond#66"{Bool, Bool, REPL.var"#77#87"{REPL.LineEditREPL, REPL.REPLHistoryProvider}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\REPL.jl:861
 [27] #invokelatest#2
    @ .\essentials.jl:729 [inlined]
 [28] invokelatest
    @ .\essentials.jl:726 [inlined]
 [29] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\LineEdit.jl:2510
 [30] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL C:\Julia\1.8.0\share\julia\stdlib\v1.8\REPL\src\REPL.jl:1248
 [31] (::REPL.var"#49#54"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL .\task.jl:484
ERROR: TaskFailedException
Stacktrace:
fatal: error thrown and no exception handler available.
MethodError(f=Base.findnext, args=(:a, ".\task.jl", 1), world=0x0000000000007e9f)
jl_method_error_bare at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1879
jl_method_error at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1897
jl_lookup_generic_ at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2530
ijl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2545
#445 at .\strings\util.jl:685
map at .\tuple.jl:221 [inlined]
#replace#443 at .\strings\util.jl:684
replace at .\strings\util.jl:676
unknown function (ip: 000000005ae18ea0)
fixup_stdlib_path at .\methodshow.jl:139
print_stackframe at .\errorshow.jl:704
print_stackframe at .\errorshow.jl:697
#show_full_backtrace#881 at .\errorshow.jl:586
show_full_backtrace##kw at .\errorshow.jl:576 [inlined]
show_backtrace at .\errorshow.jl:781
#showerror#605 at .\task.jl:83
showerror##kw at .\task.jl:80
unknown function (ip: 000000005ae18b33)
show_exception_stack at .\errorshow.jl:878
display_error at .\client.jl:103
unknown function (ip: 000000005ae0df44)
display_error at .\client.jl:106
unknown function (ip: 000000005ae0dd70)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1838 [inlined]
jl_f__call_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:774
#invokelatest#2 at .\essentials.jl:729 [inlined]
invokelatest at .\essentials.jl:726 [inlined]
_start at .\client.jl:524
jfptr__start_57488.clone_1 at C:\Julia\1.8.0\lib\julia\sys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1838 [inlined]
true_main at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:575
jl_repl_entrypoint at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:719
mainCRTStartup at /cygdrive/c/buildbot/worker/package_win64/build/cli\loader_exe.c:59
BaseThreadInitThunk at C:\Windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
  ```
  
</details>

**Comment by KristofferC** [comment] 2023-01-18 10:59
The issue is

```julia
julia> 1 => 2
1 => 2

julia> (a => b) = 1 # Actually extends the Pair constructor
Error showing value of type UnionAll:
ERROR: 
SYSTEM (REPL): showing an error caused an error
ERROR: 
SYSTEM (REPL): caught exception of type MethodError while trying to handle a nested exception; giving up
```

where the problem is a combination of https://github.com/JuliaLang/julia/issues/25744 and https://github.com/JuliaLang/julia/issues/15483.

I'll close this since there are already issues opened for this but I agree it is non-ideal.

**Closed by KristofferC** 2023-01-18 10:59 UTC

**Comment by KristofferC** [comment] 2023-01-18 11:03
Actually, the same issue has been reported in https://github.com/JuliaLang/julia/issues/37783, https://github.com/JuliaLang/julia/issues/42552, https://github.com/JuliaLang/julia/issues/39929
