### ISSUE TITLE
Variable type is not inferred correctly if an `if` statement is added

### ISSUE THREAD

**Issue by ronisbr** [JuliaLang/julia#26752] opened 2018-04-09 14:16 UTC
First of all, sorry about the title! I can't really summarize the problem in a good way (if anyone can change it to a better one, then, please, be my guest!).

I was trying to optimize a toolbox I was coding and I had a very strange type warnings using `@code_warntype`. I posted the problem on discourse to verify if I was doing something wrong [1] with global declaration of constants.

It turns out that @tkoolen and @StefanKarpinski identified a bigger problem (that I cannot really describe in technical detail) and asked to open an issue.

Consider the following code:

```julia
VERSION >= v"0.4.0-dev+6521" && __precompile__()

module TestConst

export test

function test(n::Number, e::Number)
    # Auxiliary constant to compute the functions.
    K1 = 3.0

    # Declare the functions that must solved for 0.
    f1(a, i) = K1
end

end
```

If I analyze the type using `@code_warntype test(1,1)`, then I get:

```
Variables:
  #self# <optimized out>
  n <optimized out>
  e <optimized out>
  K1 <optimized out>
  f1::TestConst.#f1#1{Float64}

Body:
  begin  # line 12:
      f1::TestConst.#f1#1{Float64} = $(Expr(:new, TestConst.#f1#1{Float64}, 3.0))
      return f1::TestConst.#f1#1{Float64}
  end::TestConst.#f1#1{Float64}
```

However, consider the following code in which a check of the variable `n` is added:

```julia
VERSION >= v"0.4.0-dev+6521" && __precompile__()

module TestConst

export test

function test(n::Number, e::Number)
    if (n <= 0)
        throw(ArgumentError("The angular velocity must be greater than 0."))
    end

    # Auxiliary constant to compute the functions.
    K1 = 3.0

    # Declare the functions that must solved for 0.
    f1(a, i) = K1
end

end
```

In this case, I see problems about the type:

```
Variables:
  #self# <optimized out>
  n::Int64
  e <optimized out>
  K1::Core.Box
  f1::TestConst.#f1#1

Body:
  begin 
      K1::Core.Box = $(Expr(:new, :(Core.Box)))
      NewvarNode(:(f1::TestConst.#f1#1))
      unless (Base.sle_int)(n::Int64, 0)::Bool goto 6 # line 9:
      (TestConst.throw)($(Expr(:new, :(Base.ArgumentError), "The angular velocity must be greater than 0.")))::Union{}
      6:  # line 13:
      (Core.setfield!)(K1::Core.Box, :contents, 3.0)::Float64 # line 16:
      f1::TestConst.#f1#1 = $(Expr(:new, :(TestConst.#f1#1), :(K1)))
      return f1::TestConst.#f1#1
  end::TestConst.#f1#1
```

I performed a simple benchmark on both version using:

```julia
@time for k=1:1000000000
    test(1,1)
end
```

The result was `0.93s` for the first algorithm and `18s` for the second one.

---
# References

[1] https://discourse.julialang.org/t/correct-way-to-declare-global-constant-in-modules/10234/6

**Comment by ronisbr** [comment] 2018-04-09 14:25
Just an update, as adviced by @StefanKarpinski, I saw that if I move `K1` to a place before the `if`, then everything works well:

```julia
VERSION >= v"0.4.0-dev+6521" && __precompile__()

module TestConst

export test

function test(n::Number, e::Number)
    # Auxiliary constant to compute the functions.
    K1 = 3.0

    if (n <= 0)
        throw(ArgumentError("The angular velocity must be greater than 0."))
    end

    # Declare the functions that must solved for 0.
    f1(a, i) = K1
end

end
```

```
Variables:
  #self# <optimized out>
  n::Int64
  e <optimized out>
  K1 <optimized out>
  f1::TestConst.#f1#1{Float64}

Body:
  begin 
      NewvarNode(:(f1::TestConst.#f1#1{Float64})) # line 11:
      unless (Base.sle_int)(n::Int64, 0)::Bool goto 6 # line 12:
      (TestConst.throw)($(Expr(:new, :(Base.ArgumentError), "The angular velocity must be greater than 0.")))::Union{}
      6:  # line 16:
      f1::TestConst.#f1#1{Float64} = $(Expr(:new, TestConst.#f1#1{Float64}, 3.0))
      return f1::TestConst.#f1#1{Float64}
  end::TestConst.#f1#1{Float64}
```

**Comment by JeffBezanson** [comment] 2018-04-09 14:37
Duplicate of #15276

**Closed** 2018-04-09 14:44 UTC

**Comment by StefanKarpinski** [comment] 2018-04-09 14:53
Is it really though? This seems to require a more sophisticated optimization, but perhaps I'm wrong.

**Comment by JeffBezanson** [comment] 2018-04-09 15:02
It's exactly the same issue: lowering introduces a `Box` because it can't figure out that it's unnecessary.
