### ISSUE TITLE
map(a -> zip(a...), itr) inference imprecision

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#33634] opened 2019-10-22 14:51 UTC
```julia
julia> versioninfo()
Julia Version 1.3.0-rc4.1
Commit 8c4656b97a (2019-10-15 14:08 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_CMDSTAN_HOME = /home/tamas/src/cmdstan/
```

MWE condensed from [discussion](https://discourse.julialang.org/t/type-stable-zip-of-tuple/30105):
```julia
using Test

# wrapper is pretty much irrelevant for the problem, just to make an MWE
@inline wrapper(itrs) = sum(prod(first.(i)) for i in Iterators.product(itrs...))

zipped1(pairs) = wrapper(map(pair -> zip(pair...), pairs))

zipped2(pairs) = wrapper(map(pair -> zip(pair[1], pair[2]), pairs))

pairs = (1:5 => 1:5, 2:3 => 2:3)

@inferred zipped1(pairs) # ERROR: return type Int64 does not match inferred return type Any
@inferred zipped2(pairs) # inferred correctly
```
I found some similar-looking issues, but this did not look like a duplicate of any of them.

**Comment by vtjnash** [comment] 2020-03-15 21:51
Duplicate of #29114

**Closed by vtjnash** 2020-03-15 21:51 UTC
Labels: inference

**Comment by Keno** [comment] 2020-07-17 22:05
This wasn't quite a duplicate of #29114 (which was mostly about inlining not inference). But in any case, it got fixed by the recent inference precision enhancements.

**Comment by tpapp** [comment] 2020-07-18 11:48
Indeed, it is fixed now. Thanks for the clarification.
