### ISSUE TITLE
time macro occasionally throws a DomainError

### ISSUE THREAD

**Issue by kpamnany** [JuliaLang/julia#18868] opened 2016-10-10 21:44 UTC
It appears that ``GC_Diff.allocd`` can sometimes be negative after ``GC_Diff()`` is called. This causes a ``DomainError`` when ``prettyprint_getunits()`` (called from ``time_print()``) tries to take the log of this negative value.

**Comment by yuyichao** [comment] 2016-10-10 21:48
I assume you are running threading code?

**Comment by kpamnany** [comment] 2016-10-10 21:49
Yep!

**Comment by KristofferC** [comment] 2016-10-10 21:52
Duplicate of https://github.com/JuliaLang/julia/issues/17255?

**Comment by yuyichao** [comment] 2016-10-10 21:53
Ah, yeah. (Somehow I thought it was threading.)

**Comment by kpamnany** [comment] 2016-10-10 21:54
Indeed it is. Closing.

**Closed by yuyichao** 2016-10-10 21:53 UTC
