### ISSUE TITLE
eachslice is type unstable

### ISSUE THREAD

**Issue by ariroffe** [JuliaLang/julia#39639] opened 2021-02-12 18:22 UTC
```
julia> a = [1 2; 3 4]

julia> function f1(arr)
           for x in eachcol(arr) end
       end

julia> function f2(arr)
           for x in eachslice(arr; dims=2) end
       end
```

Now, if I do:
```
julia> @code_warntype f1(a)
Variables
  #self#::Core.Compiler.Const(f1, false)
  arr::Array{Int64,2}
  @_3::Union{Nothing, Tuple{SubArray{Int64,1,Array{Int64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},Int64}}
  x::SubArray{Int64,1,Array{Int64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true}
(...)
```

However:
```
julia> @code_warntype f2(a)
Variables
  #self#::Core.Compiler.Const(f2, false)
  arr::Array{Int64,2}
  @_3::Union{Nothing, Tuple{Any,Int64}}
  x::Any
(...)
```

Shouldn't these two functions be equivalent in terms of type stability, and the compiler know that `x` is a `SubArray` in the second case? 
It isn't just this case though, `eachslice` seems to have the same behavior for other array eltypes and dimensions.
Sorry if this isn't an issue, I'm somewhat new to Julia.

**Comment by antoine-levitt** [comment] 2021-02-13 08:11
Confirmed, that's because of 
```
    inds_before = ntuple(d->(:), dim-1)
```
in eachslice (in share/julia/base/abstractarraymath.jl) which is not type stable because dim is not known at runtime. But shouldn't constant propagation take care of this?

**Comment by Luapulu** [comment] 2022-03-16 16:21
I ran into what I think is a related problem:

```
julia> m = rand(10, 10);

julia> eltype(eachcol(m))
Any
```

but eltype should give me some subtype of AbstractVector.

**Comment by LilithHafner** [comment] 2022-07-13 13:21
This is fixed on master.

```julia
julia> a = [1 2; 3 4]
2×2 Matrix{Int64}:
 1  2
 3  4

julia> function f1(arr)
           for x in eachcol(arr) end
       end
f1 (generic function with 1 method)

julia> function f2(arr)
           for x in eachslice(arr; dims=2) end
       end
f2 (generic function with 1 method)

julia> @code_warntype f1(a)
MethodInstance for f1(::Matrix{Int64})
  from f1(arr)
     @ Main REPL[39]:1
Arguments
  #self#::Core.Const(f1)
  arr::Matrix{Int64}
Locals
  @_3::Union{Nothing, Tuple{SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}, Tuple{Base.OneTo{Int64}, Int64}}}
  x::SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}
(...)

julia> @code_warntype f2(a)
MethodInstance for f2(::Matrix{Int64})
  from f2(arr)
     @ Main REPL[40]:1
Arguments
  #self#::Core.Const(f2)
  arr::Matrix{Int64}
Locals
  @_3::Union{Nothing, Tuple{SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}, Tuple{Base.OneTo{Int64}, Int64}}}
  x::SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}
(...)

julia> m = rand(10, 10);

julia> eltype(eachcol(m))
SubArray{Float64, 1, Matrix{Float64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}

julia> versioninfo()
Julia Version 1.9.0-DEV.968
Commit 201d4f6715 (2022-07-13 09:02 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.3.0)
  CPU: 4 × Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, skylake)
  Threads: 1 on 2 virtual cores
Environment:
  LD_LIBRARY_PATH = /usr/local/lib
```

**Closed by LilithHafner** 2022-07-13 13:21 UTC
