### ISSUE TITLE
Function as data breaks in threading block

### ISSUE THREAD

**Issue by jnkh** [JuliaLang/julia#14343] opened 2015-12-10 00:24 UTC
When functions are used as data inside a threading block, it (occasionally) results in a segmentation fault. When the same function is called as a locally defined function, the program runs smoothly.

Here is a minimal example illustrating this. We are calling the function fn(x) in two different ways. Once as is, and once as a data component of a type. It breaks only in the second case.

```julia
using Base.Threads

type CarryFunction
	fn::Function
end

alpha = 0.1
fn(x) = alpha*x

function use_anonymous(N::Int, c::CarryFunction)
	a = zeros(N)
	@threads all for i in 1:length(a)
		# a[i] = fn(i) #NO SEGFAULT
		a[i] = c.fn(i) #SEGFAULT (sometimes... but not always!)
	end
	println(a[1],a[end])
end

length = 10000
repetitions = 100
for j = 1:repetitions
	use_anonymous(length,CarryFunction(fn))
end
```

**Comment by yuyichao** [comment] 2015-12-10 00:44
I can't reproduce on #14190 . There where some similar segfaults that I pushed separately so your particular problem might already be fixed on master. Note that you also need to remove the `all` parameter to the `@thread` macro now.

**Comment by JeffBezanson** [comment] 2015-12-10 04:31
Possibly dup of #11857

**Comment by yuyichao** [comment] 2015-12-10 04:38
Likely but hard to tell since none of these have backtraces.......

At least this one is probably reproducible on a more recent master?

**Closed** 2016-01-05 17:52 UTC
Labels: multi-threading
