### ISSUE TITLE
kwargs bug in Test.@test

### ISSUE THREAD

**Issue by kcajf** [JuliaLang/julia#38215] opened 2020-10-28 18:03 UTC
```
julia> using Test

julia> @test isapprox(2, 3)
Test Failed at REPL[8]:1
  Expression: isapprox(2, 3)
   Evaluated: isapprox(2, 3)
ERROR: There was an error during testing

julia> @test isapprox(2, 3; atol=3)
Test Passed

julia> atol = 3
3

julia> @test isapprox(2, 3; atol)
Test Failed at REPL[11]:1
  Expression: isapprox(2, 3; atol)
   Evaluated: isapprox(2, 3)
ERROR: There was an error during testing

julia> versioninfo()
Julia Version 1.6.0-DEV.1354
Commit 29a6e66e49 (2020-10-28 07:27 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake-avx512)
```

This is a nasty one! Seems like `@test` parses and re-assembles the call for certain functions, in order to display pretty output. It doesn't handle the new anyonymous kwargs syntax, however. It seems like `atol` is just getting dropped in the second case.

**Comment by DebadityaPal** [comment] 2020-11-01 12:43
Hi,
I did some debugging on the test macro:
`macro test(ex, kws...)
    test_expr!("@test", ex, kws...)
    orig_ex = Expr(:inert, ex)
    result = get_test_result(ex, __source__)
    :(do_test($result, $orig_ex))
end`
at /stdlib/Test/src/Test.jl
I could narrow down the problem to the function get_test_result(ex, __source__). When no value is assigned to atol in the function call, this function removes the argument from the Expr.

When we pass `@test isapprox(2,3; atol=3)`, the value of result is:
`begin
    try
        eval_test(Expr(:call, $(Expr(:escape, :isapprox)), Expr(:parameters, :atol => $(Expr(:escape, 3))), $(Expr(:escape, 2)), $(Expr(:escape, 3))), Expr(:call, :isapprox), $(QuoteNode(:(#= REPL[42]:1 =#))), $(QuoteNode(false)))
    catch _e
        _e isa InterruptException && rethrow()
        Threw(_e, Base.catch_stack(), $(QuoteNode(:(#= REPL[42]:1 =#))))
    end
end`

and when we pass `@test isapprox(2,3; atol)`, the value of result is :
`begin
    try
        eval_test(Expr(:call, $(Expr(:escape, :isapprox)), Expr(:parameters), $(Expr(:escape, 2)), $(Expr(:escape, 3))), Expr(:call, :isapprox), $(QuoteNode(:(#= REPL[41]:1 =#))), $(QuoteNode(false)))
    catch _e
        _e isa InterruptException && rethrow()
        Threw(_e, Base.catch_stack(), $(QuoteNode(:(#= REPL[41]:1 =#))))
    end
end`
The second result shows the ommision of the atol keyword

**Comment by DebadityaPal** [comment] 2020-11-01 12:45
I would like to work on this issue further and help solve it.

**Comment by kcajf** [comment] 2020-11-01 14:40
I think this is the place to look:

https://github.com/JuliaLang/julia/blob/238874c0b6a8647ecfdf825bb41e585706ed4667/stdlib/Test/src/Test.jl#L466:L509

**Comment by DebadityaPal** [comment] 2020-11-02 07:36
So what I could understand was that the @test takes in an Expr input. When we pass kwargs without assigning them values, the Expr treats them as normal parameters, and that is why atol was getting ignored.
```
@test isapprox(1,2; atol=2)
Expr
  head: Symbol call
  args: Array{Any}((4,))
    1: Symbol isapprox
    2: Expr
      head: Symbol parameters
      args: Array{Any}((1,))
        1: Expr
          head: Symbol kw
          args: Array{Any}((2,))
            1: Symbol atol
            2: Int64 2
    3: Int64 1
    4: Int64 2
nothing

```
and
```
@test isapprox(1,2; atol)
Expr
  head: Symbol call
  args: Array{Any}((4,))
    1: Symbol isapprox
    2: Expr
      head: Symbol parameters
      args: Array{Any}((1,))
        1: Symbol atol
    3: Int64 1
    4: Int64 2
nothing
```
The problem is present with the way Expr handles unassigned keywords, you could try writing `@test isapprox(1,2; atol=atol)`
The slack community says this anonymous kwargs syntax will be properly available in Julia v1.6 onwards.

>

**Closed** 2021-01-07 20:27 UTC
Labels: bug, testsystem
