### ISSUE TITLE
Segmentation fault when calling C function with special signature.

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/julia#16719] opened 2016-06-02 16:25 UTC
* OS: Ubuntu 16.04
* Julia: 
```bash
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+4445 (2016-06-02 07:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 1cd0dee (0 days old master)
|__/                   |  x86_64-unknown-linux-gnu
```

when calling a C function with a special shape in Julia, it crashes.
```bash
signal (11): Segmentation fault
while loading /home/lizz/dev/dump/test.jl, in expression starting on line 10
unknown function (ip: 0x7f641f91fd02)
unknown function (ip: 0x7f641f920ec9)
unknown function (ip: 0x7f641f9247f1)
unknown function (ip: 0x7f641f921aac)
unknown function (ip: 0x7f641f9265c0)
unknown function (ip: 0x7f641f9b4fdb)
unknown function (ip: 0x7f641f9b6890)
unknown function (ip: 0x7f641f80c203)
unknown function (ip: 0x7f642017a89e)
unknown function (ip: 0x7f642017ac1a)
unknown function (ip: 0x7f642017a458)
operator() at /home/centos/buildbot/slave/package_tarball64/build/src/jitlayers.cpp:330
operator() at /home/centos/local/include/c++/5.1.0/functional:2271
addModule at /home/centos/buildbot/slave/package_tarball64/build/src/jitlayers.cpp:433
jl_finalize_function at /home/centos/buildbot/slave/package_tarball64/build/src/jitlayers.cpp:665
jl_generate_fptr at /home/centos/buildbot/slave/package_tarball64/build/src/codegen.cpp:1028
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:84
jl_parse_eval_all at /home/centos/buildbot/slave/package_tarball64/build/src/ast.c:780
jl_load at /home/centos/buildbot/slave/package_tarball64/build/src/toplevel.c:585
include_from_node1 at ./loading.jl:426
unknown function (ip: 0x7f641b29f2cc)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:88
process_options at ./client.jl:266
_start at ./client.jl:322
unknown function (ip: 0x7f641b2da754)
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:88
unknown function (ip: 0x401db5)
unknown function (ip: 0x4017fa)
unknown function (ip: 0x7f641eb4b82f)
unknown function (ip: 0x401840)
Allocations: 958286 (Pool: 957204; Big: 1082); GC: 1
Segmentation fault (core dumped)
```

The C function is
```c
typedef struct {
    void *p;
} Handle;

int fun(Handle hModel,
        const char *id,
        const char *typeName,
        Handle inputIds,
        Handle outputIds,
        Handle attrNames,
        Handle attrVals,
        Handle* pLayerEntry);
```

A minimal reproduce code is [here](https://github.com/innerlee/JuliaIssue).

Thanks!

cc. @zhangxc11, @lindahua

**Comment by yuyichao** [comment] 2016-06-02 16:28
This is most likely a user error. The pointer shouldn't be converted before passing to the C function.

**Comment by yuyichao** [comment] 2016-06-02 16:31
Actually, in addition to the user error about passing the pointer, there's also an llvm assertion, which is what causing the segfault.

```
Wrong types for attribute: byval inalloca nest noalias nocapture nonnull readnone readonly sret dereferenceable(1) dereferenceable_or_null(1)
  %179 = call i32 %178(i64 %143, i64 %146, i64 %149, i64 %153, i64 %157, i64 %161, i64 byval %165, %Handle* %175), !dbg !23
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by innerlee** [comment] 2016-06-02 16:34
Is it easy to fix it?

**Comment by yuyichao** [comment] 2016-06-02 17:28
> Is it easy to fix it?
> (edit: by modifying user code?)

Probably not. Except that it's probably cpu-arch dependent.... Probably not particularly hard to fix the right way. Have to check though...

**Comment by vtjnash** [comment] 2016-06-02 20:15
@yuyichao do you have a repro on why that argument got marked as byval? My PR @ line 
https://github.com/JuliaLang/julia/pull/16677/files#diff-be60d844ffde1319a02946d17c472e46L954 might help with making the llvm verifier happy, but there should have been an assertion at that point anyways, nor should it have been byval in the first place.

**Comment by yuyichao** [comment] 2016-06-02 22:10
The issue is that `needPassByRef` [takes into account spilling](https://github.com/JuliaLang/julia/blob/c95b61b1ec4a16953ca496f50ee6f0e0a2797529/src/abi_x86_64.cpp#L188) but `preferred_llvm_type` doesn't. (It also seems that the assertion is not enabled even for the debug build in codegen for me since my llvm doesn't have assertion enabled. otherwise it should trigger the assertion here).

the clang output is

```llvm
define i32 @fun(i8* %hModel.coerce, i8* %id, i8* %typeName, i8* %inputIds.coerce, i8* %outputIds.coerce, i8* %attrNames.coerce, i64 %attrVals.coerce, %struct.Handle* %pLayerEntry)
```

So it seems that the change in your PR should be the right fix?

**Comment by yuyichao** [comment] 2016-06-02 22:30
Actually,

```c
int fun(Handle hModel,
        const char *id,
        const char *typeName,
        Handle inputIds,
        Handle outputIds,
        Handle attrNames,
        Handle attrVals,
        Handle* pLayerEntry)
{
    return (int)(long)attrVals.p + (int)(long)attrNames.p;
}
```

Gives
```llvm
define i32 @fun(i8* nocapture readnone %hModel.coerce, i8* nocapture readnone %id, i8* nocapture readnone %typeName, i8* nocapture readnone %inputIds.coerce, i8* nocapture readnone %outputIds.coerce, i8* %attrNames.coerce, i64 %attrVals.coerce, %struct.Handle* nocapture readnone %pLayerEntry) #0 {
  %1 = trunc i64 %attrVals.coerce to i32
  %2 = ptrtoint i8* %attrNames.coerce to i64
  %3 = trunc i64 %2 to i32
  %4 = add nsw i32 %1, %3
  ret i32 %4
}
```

So it seems that both are passed by value as a pointer/pointer-size integer and llvm can handle the spill automatically. (clang is doing something when passing the spill threshold though.....)

**Comment by vtjnash** [comment] 2016-06-03 01:08
Oh, that's wrong. byval is orthogonal to spilling

**Comment by yuyichao** [comment] 2016-06-03 01:12
> Oh, that's wrong. byval is orthogonal to spilling

That's what confuses me a lot when I'm implementing the aarch64 one, I though for a long time that I need to handle spilling too and then I thought there's something special about llvm on x86 that requires the frontend to handle spilling....

**Comment by vtjnash** [comment] 2016-06-13 05:18
add to https://github.com/JuliaLang/julia/issues/14912

**Closed by vtjnash** 2016-06-13 05:18 UTC
Labels: codegen
