### ISSUE TITLE
Pkg.update() makes julia 0.4 crash on Windows

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#10490] opened 2015-03-12 17:52 UTC
It happened twice. After running Pkg.update() when I launch julia it crashes immediately. 
On the second time I removed .julia/v0.4, rebuilt julia with make cleanall and reinstalled Pkg with Pkg.add("ImageView") and again the same thing. Launching a  new julia session crashes right away.

**Comment by ivarne** [comment] 2015-03-12 19:07
Is any message printed with the crash?

**Comment by pao** [comment] 2015-03-12 19:19
If this is Win64, very likely #10249.

**Comment by joa-quim** [comment] 2015-03-12 19:29
Yes, it's Win64. But I can't reproduce #10249
Meanwhile I had rebuild to a working version by doing again 'make cleanall, make'
The crashing is absolutely silent. The only thing I could find is that it came from julia.exe

**Comment by pao** [comment] 2015-03-12 19:50
Can you run under a debugger?

**Comment by joa-quim** [comment] 2015-03-12 19:54
How can I do that?
I know how to debug with VS but for that I would need to have a julia built with it. Since I build with mingw I have no idea how to debug (please, no gdb).

**Comment by pao** [comment] 2015-03-12 20:01
I don't think you can get around using `gdb`. https://github.com/JuliaLang/julia/blob/master/README.windows.md#windows-build-debugging

But to just capture a backtrace you only need `r` and `bt` commands.

**Comment by joa-quim** [comment] 2015-03-12 20:16
Sorry but again, how I do that?

**Comment by pao** [comment] 2015-03-12 20:56
Side question: can you reproduce this in a build off the buildbots? If so you should be able to use WinDbg, though I'm not sure how much detail you can get there.

I'm doing these instructions from memory; I usually start programs from GDB instead of attaching to them since they aren't interactive. I apologize for any errors.

1. Start Julia
2. Attach gdb (`gdb -p PIDNO`, you can get the PID from Task Manager)
3. `(gdb) c` to continue execution
4. Crash Julia
5. `(gdb) bt` to print a backtrace

**Comment by tkelman** [comment] 2015-03-12 23:15
Which Julia executable are you running? The one at `usr/bin/julia.exe`, or are you doing some combination of `make win-extras`, `make install`, and/or `make dist`?

If you want Julia to be usable with the package manager at this point, you need to either use the buildbot binaries or cross-compile from Cygwin. The formerly recommended MSYS2 compilers are not compatible with anything from WinRPM.

**Comment by joa-quim** [comment] 2015-03-13 14:33
Hmm, I'm running a usr\bin\julia.exe build by me with MSYS2. So that is it. Will try with the buildbots.

**Comment by joa-quim** [comment] 2015-03-14 00:35
... ai, I've done that before but forgot how to and now I don't find any doc on how to generate the installers with the buildbots. Sorry, where's that info?

**Comment by tkelman** [comment] 2015-03-14 00:42
What do you mean generate? Do you just want to download the latest nightly binary installer? That's at https://status.julialang.org/download/win64

Creating an installer from a local source build is done via `make dist`, though you can also use `make binary-dist` and at some point the former will change meaning, so you may as well start using the latter now.

**Comment by joa-quim** [comment] 2015-03-14 00:57
Thanks (2nd case ofc)
I had tried the `make dist` in the train but it failed (probably because the train was running too fast)

**Comment by joa-quim** [comment] 2015-03-14 13:05
OK, if I build with `make dist` and install it. It still crashes. I can't even try to use gdb because when executed `julia.exe` or `julia-debug.exe` from the mintty shell simply nothing happens (????).

Installing the nightly version works ok but I still can't use imageView because of that know issue

`ERROR: LoadError: LoadError: LoadError: Tk.TclError("error initializing Tcl: Can't find a usable init.tcl in the following directories: \n    {C:\\programs\\WinPython2.7.6.3_64\\python-2.7.6.amd64\\share\\tcl} C:/programs/WinPython2.7.6.3_64/python-2.7.6.amd64/share/tcl8.5 C:/programs/WinPython2.7.6.3_64/python-2.7.6.amd64/lib/tcl8.5 V:/Julia-0.4.0-dev/lib/tcl8.5 V:/lib/tcl8.5 V:/Julia-0.4.0-dev/library V:/library V:/tcl8.5.2/library V:/tcl8.5.2/library\n\n\n\nThis probably means that Tcl wasn't installed properly.\n")`

**Comment by joa-quim** [comment] 2015-03-14 19:53
Continuing with weirdness.
If, from the version installed from the nightly, I try to is install Gtk.jl, it fails because:
`WARNING: Unknown download failure, error code: 2148270086
WARNING: Retry 1/5 downloading: http://download.opensuse.org/repositories/window
s:/mingw:/win64/openSUSE_13.1//noarch/mingw64-libjpeg8-8.0.2-1.1.noarch.rpm
(repeat 5 times)`

However, I was apparently able to do the same install when run from my own julia build. But the price is that, again, my local build now again crashes immediately upon launch.

**Comment by tkelman** [comment] 2015-03-15 03:31
`WARNING: Unknown download failure, error code: 2148270086`

I think that's intermittent flakiness from opensuse's downloads. We can probably modify WinRPM to use the S3 caching server now. Tk should also be installing from WinRPM, not picking anything up from local Python installations.

The compiler version we formerly recommended for use with MSYS2 is not compatible with package downloads from WinRPM, unfortunately. For source builds we'll either need to find a different MinGW-w64 distribution to recommend with MSYS2 (the one from opensuse would probably be a good choice), or only endorse the Cygwin cross-compilation. Sorry for the trouble. Unless you're working on patches to base Julia, the binaries should really be good enough. If they're not working, I think we can try to fix what's wrong there.

**Comment by joa-quim** [comment] 2015-03-15 16:13
It hardly could have been a intermittent opensuse's download hick-up. I had repeatedly tried from the nightly version install and it always failed but once I tried with my local build it worked right away.

One issue that one time or other (later) want to address are those WinRPM binaries is that what I see in my `WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin` are mostly files that I already have (as Win native builds with VS) in my system. So at a certain point in future I would rather use my binaries, in particular when one will be able to build Julia from VS, than those ones. I guess that will be possible no?

**Comment by tkelman** [comment] 2015-03-16 03:22
That's really strange then. Something would appear to be messed up with WinRPM's downloading on the nightlies then. Can you try tracing through the code path that WinRPM executes there and reproduce the single failing call?

> So at a certain point in future I would rather use my binaries, in particular when one will be able to build Julia from VS, than those ones. I guess that will be possible no?

Probably, if you have binaries built from elsewhere on your path and Julia can load them, then BinDeps should see them and use them rather than going to WinRPM. At this stage the reproducibility and ease of use is much more important to us than saving disk space. Many of Python's issues on Windows are due to C extensions requiring very specific Visual Studio versions to compile everything, when most users just want the package to work rather than having to fiddle with compilers. I'd very much like to avoid getting into that mess.

**Comment by tkelman** [comment] 2015-05-19 01:18
@wildart this isn't really a package issue, it's a gcc version incompatibility problem that happens to be triggered by some workarounds we have in WinRPM

**Comment by tkelman** [comment] 2015-06-13 22:06
I've turned off the behavior in WinRPM that would cause this problem, so I'm going to close this. ZMQ and hence IJulia might be broken in fresh installs until I can figure out how to use the opensuse toolchain. My working branch for that is https://github.com/JuliaLang/julia/tree/tk/winbuild - if you try in an msys2 build, run the script `contrib/windows/get_toolchain.sh` and try that version of mingw-w64.

**Closed by tkelman** 2015-06-13 22:06 UTC
Labels: windows
