### ISSUE TITLE
`@nospecialize` on tuple destructuring prints misleading error

### ISSUE THREAD

**Issue by MilesCranmer** [JuliaLang/julia#56356] opened 2024-10-27 17:49 UTC
Using `@nospecialize` on tuple destructuring of arguments prints a misleading error:

```julia
julia> f(@nospecialize((x, y))) = x
ERROR: syntax: "(x, y)" is not a valid function argument name around REPL[1]:1
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1

julia> versioninfo()
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 6 default, 0 interactive, 3 GC (on 6 virtual cores)
```

**Comment by nsajko** [comment] 2024-10-27 18:56
Duplicate of #52060

**Closed by nsajko** 2024-10-27 18:56 UTC
Labels: duplicate
