### ISSUE TITLE
Move everything unsafe into Unsafe module

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#51913] opened 2023-10-28 14:17 UTC
People have complained about aliasing of e.g. sum! and I believe all functions that end with ! may be problematic (I haven't decided on a sublist, if that's not true, to move) except maybe `push!`. People may not have, but I find it problematic too, and array mutability.

1a. I'm thinking as a first step move every such (except push!), at least those with potential aliasing problem (recently documented, I think those are all), to module Unsafe (alternative name Aliasing).

I looked up to see if sum! is used by Julia itself, and as I thought it isn't, though I found `cumsum!(counts, counts)` regarding sorting, and something for testing `OffsetArray`s

1b. Which brings me to a next, maybe controversial proposal, Not export @inbounds. It would be hugely breaking too, but I think we could still export it as a no-op macro; and if you do `using Unsafe` that macro would change to its current definition.

It's not even clear the macro is always faster, like the global option, I read it can actually make slower.

2. If people need to do `using Unsafe` then this is of course a breaking change, so what's the point? I'm thinking people will do `using Julia1` to recover full compatibility and even, for now, it will be done implicitly for your, unless you run julia with juliax. Julia1 would depend on Unsafe, but for Julia 2.0 those will be excised.

Then in Julia 2.0, nobody can claim Julia is unsafe or its standard libraries, and all Julia 2.0 code will work also in 1.x.

[I have further plans for 2.0, remove everything Julia itself doesn't need, e.g. Array (we now have Memory type), and push! for arrays, at least no longer export (promote full immutability); I think Julia only needs 1d arrays, and stuff based on it e.g. Dict.]

**Comment by PallHaraldsson** [comment] 2023-10-29 18:39
I could look into this, but I will not start if people would be totally against this.

One more candidate for Unsafe, would be `similar` there and not exported.

**Comment by KristofferC** [comment] 2023-10-29 19:24
I don't think it makes sense for a single workspace for things that are "unsafe" since you want code within the same area to be live together even if some of them are unsafe or not. If (and this is a pretty big if) something like this should be considered it should imo be an annotation on the function / method, similar to how it is done in rust.

> I have further plans for 2.0

There isn't really a thing that is Julia 2.0 so I would not make too big plans for it.

------------

This issue is talking a little bit about everything: aliasing, unsafeness, breaking changes, Julia 2.0 so it is a bit confusing what it is actually about.

**Comment by PallHaraldsson** [comment] 2023-10-29 19:31
I'm here only proposing fencing off Unsafe code in the julia stdlib (excision could come later). And it's non-breaking if Julia does implicit `using Unsafe`, but then it has no actual benefit for users since invisible to them, so for users who want to develop and know all their code is safe, this needs to be breaking, i.e. no implicit `using Unsafe` done in 2.0. Such code would however be compatible with all 1.x, could be run there.

**Comment by gvdr** [comment] 2023-10-30 21:53
I would find this extremely cumbersome to work with, and would invite a radical rethinking of Julia. As well, the definition of "unsafe" here is unpractically wide (all self modifying functions???). For me is a "no, please".

**Comment by Tokazama** [comment] 2023-10-31 03:28
I'm not sure what the benefit is of putting it all in a module. I often have methods involving multiple steps with the innermost being unsafe/unchecked. What's the practical benefit of putting these in a separate module?

**Comment by jakobnissen** [comment] 2023-10-31 06:13
Duplicate of https://github.com/JuliaLang/julia/issues/40360 .
I agree this 
1) is not too useful until the semantics of Julia has been nailed more down. It's strange to pack away some functions in a module when it's so easy for users to import private names, modify fields of structs, commit type piracy, and violate the thousand implicit and obscure contracts that Julia relies on, and
2) might be annoying to use because it's practical that unsafe implementations live next to the code that uses it

**Comment by PallHaraldsson** [comment] 2023-10-31 08:42
>when it's so easy for users to import private names, modify fields of structs, commit type piracy

It's not strictly speaking bad to import or use private, only if they go away in a breaking change, but it's not something I can easily change, so I'm leaving that to somebody else to worry about. Reading fields of structs seems ok, maybe even modify, also type piracy. The semantics of all of this is nailed down I believe, they are just surprising, to some, after an update?

>might be annoying to use because it's practical that unsafe implementations live next to the code that uses it

That's basically the point, to make using annoying, not too convenient. Nobody strictly needs any of those functions, not even `similar` or `@inbounds`. But if using need to be extra careful, why justified to jump through hoops.

**Comment by andrewjradcliffe** [comment] 2023-11-03 01:06
One should not forget that [`@fastmath`](https://llvm.org/docs/LangRef.html#fast-math-flags)'s poison values can become undefined behavior when used carelessly. Strictly speaking, unless one guarantees that all inputs to a `@fastmath`'d block are neither `NaN` nor +/- `Inf`, then one is asking for trouble.

As for Rust -- read its stdlib source and you'll notice that it's full of unsafe code. The distinction between unsafe and unsound programs, made in the first chapter of the [Rustonomicon](https://doc.rust-lang.org/nomicon/working-with-unsafe.html), is a useful conceptual framework for separating truly egregious practices from the unsafe-but-sound practices.

**Comment by oscardssmith** [comment] 2023-11-03 01:47
>[@fastmath](https://llvm.org/docs/LangRef.html#fast-math-flags)'s poison values can become undefined behavior when used carelessly.
I believe this isn't quite correct. Julia almost always freezes undefs so it's probably unspecified rather than undefined behavior.

**Comment by KristofferC** [comment] 2023-11-03 11:00
> Duplicate of https://github.com/JuliaLang/julia/issues/40360 .

I think there is enough overlap that this can be closed.

**Closed by KristofferC** 2023-11-03 11:00 UTC

**Comment by andrewjradcliffe** [comment] 2023-11-04 00:18
> Julia almost always freezes undefs so it's probably unspecified rather than undefined behavior.

I stand corrected -- I've never been close enough to Julia compiler to know this.
