### ISSUE TITLE
Unused type parameters incur allocations

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaLang/julia#45846] opened 2022-06-28 22:22 UTC
It seems that "unused" type parameters incur allocations. For example:

```julia
using BenchmarkTools

foo(a) = 1;
function foo!(a)
    @. a += foo(a)
    return nothing
end;
a = rand(100);
@benchmark foo!($a)

bar(a) where {A} = 1;          # added unused type parameter {A}
function bar!(a) where {B}     # added unused type parameter {B}
    @. a += bar(a)
    return nothing
end;
a = rand(100);
@benchmark bar!($a)
```
Resulting output for no unused type parameter:

```julia
BenchmarkTools.Trial: 10000 samples with 998 evaluations.
 Range (min … max):  13.638 ns … 160.222 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     14.812 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   15.515 ns ±   4.163 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▆█▇█▂                                                       ▂
  ▆█████▆▅▆▆▅▅▄▃▄▄▃▃▃▁▄▄▄▁▄▄▄▁▃▃▁▃▁▄▅▇██▇▆▇▇▇▆▆▃▄▅▃▄▄▁▃▁▃▃▃▃▃▃ █
  13.6 ns       Histogram: log(frequency) by time      36.7 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

Resulting output with unused type parameter:

```julia
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.571 μs … 80.060 μs  ┊ GC (min … max): 0.00% … 90.39%
 Time  (median):     1.633 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.743 μs ±  1.271 μs  ┊ GC (mean ± σ):  1.15% ±  1.65%

  ▃█▅▆▃                                                      ▁
  █████▇▆▅▅▆▅▅▃▄▄▅▁▃▁▁▄▁▃▃▁▁▁▁▁▁▁▆▇█▇▇▆▆█▆▆▅▃▄▃▃▄▃▃▁▄▄▄▄▁▄▅▆ █
  1.57 μs      Histogram: log(frequency) by time     3.94 μs <

 Memory estimate: 1.56 KiB, allocs estimate: 100.

```

It seems like maybe this should error?

Config info:
```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.4.0)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = subl
  JULIA_PKG_DEVDIR = /dev/julia
```

**Comment by gbaraldi** [comment] 2022-06-29 00:42
We generate some really bad code for this.
```julia
julia> @code_llvm bar(a)
;  @ REPL[114]:1 within `bar`
define nonnull {}* @japi3_bar_1376({}* %0, {}** %1, i32 %2, {}** %3) #0 {
top:
  %4 = alloca {}**, align 8
  store volatile {}** %1, {}*** %4, align 8
  ret {}* inttoptr (i64 4314267744 to {}*)
}

julia> @code_llvm foo(a)
;  @ REPL[3]:1 within `foo`
define i64 @julia_foo_1377({}* nonnull align 16 dereferenceable(40) %0) #0 {
top:
  ret i64 1
}
```

**Comment by vchuravy** [comment] 2022-06-29 00:50
Yeah we end up in one of the slow ABI's.

**Comment by jishnub** [comment] 2022-06-29 01:50
Same as https://github.com/JuliaLang/julia/issues/29393?

**Comment by gbaraldi** [comment] 2022-06-29 01:55
That's it. Closing as it's a duplicate of #29393

**Closed by gbaraldi** 2022-06-29 01:55 UTC
Labels: codegen, inference

**Comment by charleskawczynski** [comment] 2022-06-29 02:02
Ah, sorry, I tried searching for an existing issue but couldn't find one. Sorry for the noise!
