### ISSUE TITLE
Weird behavior of function `take` in 0.4-rc2

### ISSUE THREAD

**Issue by boathit** [JuliaLang/julia#13248] opened 2015-09-21 07:17 UTC
I cannot understand why the result of `take` can be visited by a for loop while throwing an error when put in a list comprehension, such as the code 
```
for x in take(repeated(2), 10)
    println(x)
end
```
works well but the following code
```
[x for x in take(repeated(2), 10)]
``` 
throws an error,

LoadError: MethodError: `length` has no method matching length(::Base.Take{Base.Repeated{Int64}})
while loading In[153], in expression starting on line 1

 in anonymous at no file

**Comment by swt30** [comment] 2015-09-21 10:38
When you put an iterator like `take` or `repeated` in an array comprehension, it needs to have the `length` method defined so the comprehension knows how long the resulting array is going to be. Looks like the Take iterator doesn't have that defined. You can define it yourself by doing
```
Base.length(t::Base.Take) = t.n
```
after which that code will work. This would make a nice simple pull request. 

I feel like I've also seen discussions somewhere about making a fallback comprehension strategy of just appending to the array instead of pre-allocating the space when the length of the iterator is unknown, but this would be slower and you'd run out of memory if you did something like `[x for x in repeated(2)]`.

**Comment by ivarne** [comment] 2015-09-21 11:53
```julia
Base.length(t::Base.Take) = t.n
```
Will be problematic if you try to `take` more elements than the wrapped iterator contains.
eg. `[x for x in take([1,2,3], 10)]`. Not sure what kind of nastiness a lying `Base.length` will create, but before adding one by default, we check to see how that condition is treated in various places.

**Comment by boathit** [comment] 2015-09-21 12:09
@swt30 I agree `collect` does that perfectly, but personally I think, fixing this issue can make the language itself more harmonic.

**Comment by swt30** [comment] 2015-09-21 12:09
Yeah, I was thinking that would be an issue. In this case it just gives a BoundsError when it tries to read past the end of the array, but I can envision more complicated iterators causing problems if they don't expect to be evaluated beyond when they trigger `done`. What about
```jl
length(t::Take) = min(t.n, length(t.xs))
```
This requires the wrapped iterator to have a `length` defined though, so the original question still won't work unless you define 
```jl
length(r::Repeated) = Inf
```
at which point you've returned a Float64 from what should really be an Integer valued function. Do we have any concept of an "integer infinity"?

**Comment by nalimilan** [comment] 2015-09-21 12:14
Duplicate of https://github.com/JuliaLang/julia/pull/11977.

**Closed by nalimilan** 2015-09-21 12:14 UTC

**Comment by swt30** [comment] 2015-09-21 12:16
As usual, the community is on this one already :+1:
