### ISSUE TITLE
issubset() is slow with vectors of strings

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#24624] opened 2017-11-16 14:04 UTC
`issubset(x, y)` is incredibly slow with vectors of strings compared with the equivalent `isempty(setdiff(x, y))`. This is because it uses `elt in y` rather than building a dictionary/set. Of course, `issubset` can be made even faster than `setdiff` when the result is `false` due to the possibility to short-circuit when encountering an element which does not appear in `y`.

```julia
julia> x = [@sprintf("id%010d", k) for k in 1:9999];

julia> y = [@sprintf("id%010d", k) for k in 1:10000];

julia> @time issubset(x, y)
  0.388715 seconds (10.00 k allocations: 156.391 KiB)
true

julia> @time isempty(setdiff(x, y))
  0.004538 seconds (17 allocations: 145.383 KiB)
true
```

**Comment by stevengj** [comment] 2017-11-16 15:42
This is essentially a duplicate of #13675.   I will repeat my comment from there:

> Arguably, the only case (if any) in which performance of [set operations] on arrays matters is for very small arrays (e.g. < 10 elements). (If you are doing it with huge arrays and care about performance, you should be using a different data structure.) For very small arrays, the overhead of copying into a Set datastructure probably outweighs the small performance advantage of the lookups.

**Comment by StefanKarpinski** [comment] 2017-11-16 18:14
So the todo here is that someone needs to benchmark on a few different systems where the cutoff size is for various element types and try to come up with a good rule of thumb for when to use an O(n^2) element search approach and when to use the O(~n) set-based approach.

**Comment by stevengj** [comment] 2017-11-16 20:18
I dunno, if your size is big enough that you want the set-based approach, maybe we should just tell people to use sets or some other appropriate data structure.

**Comment by nalimilan** [comment] 2017-11-16 20:47
It sounds better to automatically use the most efficient approach. Also it's kind of weird to use completely different algorithms for `issubset` and `setdiff`.

**Closed** 2018-03-07 18:14 UTC
Labels: good first issue, help wanted, performance
