### ISSUE TITLE
map() preserves shape, but not pmap()

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#19172] opened 2016-10-31 22:44 UTC
I'm not sure if this is desired behavior or not, but the two functions currently have inconsistent output. It would be nice for `pmap()` to preserve shape too.

```julia
julia> map(prod, Base.product(1:5, 1:5))
5×5 Array{Int64,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

julia> pmap(prod, Base.product(1:5, 1:5))
25-element Array{Any,1}:
  1
  2
  3
  4
  5
  2
  4
  6
  8
 10
  3
  6
  9
 12
 15
  4
  8
 12
 16
 20
  5
 10
 15
 20
 25
```

**Comment by jiahao** [comment] 2016-11-01 01:00
Essentially a duplicate of #4606

**Closed** 2016-11-01 01:01 UTC
Labels: parallel
