### ISSUE TITLE
factorize() fails on symmetric sparse matrices

### ISSUE THREAD

**Issue by mfherbst** [JuliaLang/julia#34069] opened 2019-12-10 13:18 UTC
When running on Julia 1.3.0
```julia
S = sprandn(50, 50, 0.3)
@show isposdef(Symmetric(S + S'))
factorize(Symmetric(S + S'))
```
I get
```julia
isposdef(Symmetric(S + S')) = false
ERROR: PosDefException: matrix is not positive definite; Cholesky factorization failed.
Stacktrace:
 [1] #ldlt!#10(::Float64, ::Bool, ::typeof(ldlt!), ::SuiteSparse.CHOLMOD.Factor{Float64}, ::SuiteSparse.CHOLMOD.Sparse{Float64}) at usr/share/julia/stdlib/v1.2/SuiteSparse/src/cholmod.jl:1448
 [2] #ldlt!#11 at ./none:0 [inlined]
 [3] ldlt! at usr/share/julia/stdlib/v1.2/SuiteSparse/src/cholmod.jl:1473 [inlined]
 [4] factorize(::Symmetric{Float64,SparseMatrixCSC{Float64,Int64}}) at usr/share/julia/stdlib/v1.2/SparseArrays/src/linalg.jl:1441
 [5] top-level scope at REPL[20]:1
```
So it seems calling `factorize` on `Symmetric` sparse matrices attempts to do a cholesky even if the matrix is not positive-definite.

**Comment by andreasnoack** [comment] 2019-12-10 14:02
It seems like there are two issues here. The failure is because there is a zero pivot and CHOLMOD doesn't do pivoting in the numerical stage. You can see that e.g. by subtracting the identity from the diagonal of `S + S'`. You can `factorize` that matrix even though it's not positive definite.

In the sparse `factorize` we should set `check=false` and use the `lu` from UMFPACK when the factorization doesn't succeed.

Regarding the error message then it's a regression. This is from Julia 0.6.
```julia
julia> ldltfact(S + S')
ERROR: ArgumentError: matrix has one or more zero pivots
Stacktrace:
 [1] #ldltfact!#12(::Float64, ::Function, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1452
 [2] (::Base.LinAlg.#kw##ldltfact!)(::Array{Any,1}, ::Base.LinAlg.#ldltfact!, ::Base.SparseArrays.CHOLMOD.Factor{Float64}, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./<missing>:0
 [3] #ldltfact#14(::Float64, ::Array{Int64,1}, ::Function, ::Base.SparseArrays.CHOLMOD.Sparse{Float64}) at ./sparse/cholmod.jl:1495
 [4] #ldltfact#15(::Array{Any,1}, ::Function, ::Hermitian{Float64,SparseMatrixCSC{Float64,Int64}}) at ./sparse/cholmod.jl:1542
```

I thought we fixed this recently in a slightly different invocation of CHOLMOD so we might have broken it here. CHOLMOD can be a bit difficult to work with.

**Comment by mfherbst** [comment] 2019-12-10 14:48
Thanks for your quick feedback. I can confirm that the `ldlt` succeeds if I explicitly ensure the diagonal to be non-zero.

**Comment by dkarrasch** [comment] 2019-12-11 17:35
Why do we attempt `cholesky` in the sparse case, when we don't in the dense case?
https://github.com/JuliaLang/julia/pull/33652#issuecomment-545793922

Is it different here because the `ldlt!` call benefits from something that has been done by the `cholesky` call even though it may not have succeeded? For quick reference, this is what we currently have
```julia
function factorize(A::LinearAlgebra.RealHermSymComplexHerm{Float64,<:SparseMatrixCSC})
    F = cholesky(A; check = false)
    if LinearAlgebra.issuccess(F)
        return F
    else
        ldlt!(F, A)
        return F
    end
end
```

**Comment by vtjnash** [comment] 2020-10-22 16:47
This is fixed now:
```
julia> factorize(Symmetric(S + S'))
ERROR: ZeroPivotException: factorization encountered one or more zero pivots. Consider switching to a pivoted LU factorization.
Stacktrace:
 [1] ldlt!(F::SuiteSparse.CHOLMOD.Factor{Float64}, A::SuiteSparse.CHOLMOD.Sparse{Float64}; shift::Float64, check::Bool)
   @ SuiteSparse.CHOLMOD ~/julia/usr/share/julia/stdlib/v1.6/SuiteSparse/src/cholmod.jl:1472
 [2] #ldlt!#11
   @ ~/julia/usr/share/julia/stdlib/v1.6/SuiteSparse/src/cholmod.jl:1497 [inlined]
 [3] ldlt!
   @ ~/julia/usr/share/julia/stdlib/v1.6/SuiteSparse/src/cholmod.jl:1497 [inlined]
 [4] factorize(A::Symmetric{Float64, SparseMatrixCSC{Float64, Int64}})
   @ SparseArrays ~/julia/usr/share/julia/stdlib/v1.6/SparseArrays/src/linalg.jl:1623
 [5] top-level scope
   @ REPL[12]:1
```

**Closed by vtjnash** 2020-10-22 16:47 UTC
Labels: bug, linear algebra, regression, sparse
