### ISSUE TITLE
Sporadic "invalid age range update" failure

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#21653] opened 2017-04-30 15:53 UTC
https://travis-ci.org/JuliaImages/Images.jl/jobs/227340490

Sporadic. https://travis-ci.org/JuliaImages/Images.jl/jobs/227340600 was run at the same time (one for the push, one the PR).

**Comment by mpastell** [comment] 2017-05-11 12:44
I also get this sometimes with Weave.jl using 0.6-rc1. Seems to be fixed using `Base.invokelatest`

**Comment by vtjnash** [comment] 2017-05-19 02:31
I discovered this reliable trigger (on 5dea367321 branched from 25f241ccf8), but seems to be fixed now (presumably by 26177)
```
julia> code_typed(Base.to_indices, Tuple{Array{Float32,2}, Tuple{}, Tuple{Vararg{Int64}}}, optimize=false)
WARNING: An error occurred during inference. Type inference is now partially disabled.
Base.AssertionError(msg="invalid age range update")
```

**Comment by lbenet** [comment] 2017-08-23 17:01
We are getting this error in travis with Julia nightly; see [this comment](https://github.com/PerezHz/TaylorIntegration.jl/pull/33#issuecomment-324231263) for some weird behavior related to commenting some tests. Everything runs nicely in Julia 0.6.

**Comment by mauro3** [comment] 2017-11-03 20:53
I get this with:
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-pc-linux-gnu

julia> module Mod
       using Images, ImageView, ImageSegmentation
       import PyPlot
       import JLD2
       end                                                                                                                                                               
exit()                                                                                                                                                                   
Mod                                                                                                                                                                      
                                                                                                                                                                         
julia> exit()                                                                                                                                                            
MethodError(Core.Inference.convert, (AssertionError, "invalid age range update"), 0x0000000000000ac6)                                                                    
```
I can post a list of installed packages and versions if that is required.

**Comment by mauro3** [comment] 2017-11-03 21:01
Also when adding Parameters.jl:
```
julia> module Mod                                                                                          
                                                                                                    
       using Images, ImageView, ImageSegmentation                                                                            
       import PyPlot                                                                                                               
       import JLD2                                                                                                                
       using Parameters                                                                                 
                                                                                                  
       end                                                                
ERROR: MethodError: no method matching convert(::Type{AssertionError}, ::String)
Closest candidates are:                                                                                    
  convert(::Type{Any}, ::ANY) at essentials.jl:28                                                   
  convert(::Type{T}, ::T) where T at essentials.jl:29                                                                        
Stacktrace:                                                                                                                        
 [1] AssertionError(::String) at ./coreimg.jl:14                                                                                  
 [2] update_valid_age!(::UInt64, ::UInt64, ::Core.Inference.InferenceState) at ./inference.jl:2353      
 [3] add_backedge!(::Core.MethodInstance, ::Core.Inference.InferenceState) at ./inference.jl:2366 
 [4] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1421
 [5] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [6] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927    
 [7] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950   
 [8] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2084                            
 [9] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2669                               
 [10] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787                             
 [11] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [12] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [13] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [14] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [15] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950                                
 [16] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2722                              
 [17] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787                             
 [18] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [19] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [20] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [21] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927   
 [22] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950  
 [23] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2084                           
 [24] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2669                              
 [25] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787                             
 [26] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [27] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [28] abstract_call(::Any, ::Tuple{}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [29] abstract_apply(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1561
 [30] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1689
 [31] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [32] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [33] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2722
 [34] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787
 [35] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [36] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [37] abstract_call(::Any, ::Tuple{}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [38] abstract_apply(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1561
 [39] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1689
 [40] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [41] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [42] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2722
 [43] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787           
 [44] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [45] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [46] abstract_call(::Any, ::Tuple{}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [47] abstract_apply(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1561
 [48] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1689
 [49] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [50] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [51] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2722                         
 [52] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787                                                            
 [53] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [54] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [55] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [56] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [57] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [58] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2722                                 
 [59] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787                               
 [60] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535                       
 [61] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420    
 [62] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [63] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [64] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [65] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2076    
 [66] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2669                          
 [67] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787                                                             
 [68] typeinf_edge(::Method, ::Any, ::SimpleVector, ::Core.Inference.InferenceState) at ./inference.jl:2535
 [69] abstract_call_gf_by_type(::Any, ::Any, ::Core.Inference.InferenceState) at ./inference.jl:1420
 [70] abstract_call(::Any, ::Array{Any,1}, ::Array{Any,1}, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1897
 [71] abstract_eval_call(::Expr, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1927
 [72] abstract_eval(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:1950
 [73] abstract_interpret(::Any, ::Array{Any,1}, ::Core.Inference.InferenceState) at ./inference.jl:2084    
 [74] typeinf_work(::Core.Inference.InferenceState) at ./inference.jl:2669                          
 [75] typeinf(::Core.Inference.InferenceState) at ./inference.jl:2787                                                        
 [76] typeinf_frame(::Core.MethodInstance, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2504                
 [77] typeinf_code(::Core.MethodInstance, ::Bool, ::Bool, ::Core.Inference.InferenceParams) at ./inference.jl:2583                
 [78] typeinf_ext(::Core.MethodInstance, ::UInt64) at ./inference.jl:2622                               
```

**Comment by staticfloat** [comment] 2017-12-06 00:31
I'm running into this as well now, it seems to be very sensitive to a smattering of lots of different modules included together.

**Comment by colintbowers** [comment] 2017-12-13 23:14
I've just encountered this on v0.6, when working with the `CSV` module (`Pkg.update()` run today). I've been unable to produce an MWE, but have found a *really* strange fix that works for my particular case.

I've got my own (fairly big) module `IOX`. At the top of the IOX.jl file, I've got the line:

`using SomeModule1, ..., SomeModuleK, CSV` 

If I start a new instance of julia at the REPL and execute 

`using IOX`

I get `WARNING: An error occurred during inference. Type inference is now partially disabled.` and then the `Base.MethodError(f=typeof(Core.Inference.convert)(), args=(Base.AssertionError, "invalid age range update"), world=0x0000000000000ac2)` followed by a couple of hundred of reference lines, after which Julia crashes and dumps me in the terminal.

If instead, I do:

`using CSV
using IOX`

I get no error. Even stranger, if I edit the line in IOX.jl to:

`using CSV
using SomeModule1, ..., SomeModuleK`

and then try:

`using IOX`

I also get no error.

So it is definitely something to do with the order in which packages are loading that is triggering it.

**Comment by tkoolen** [comment] 2018-03-02 02:40
This is an issue with 0.6.2 and RigidBodySim.jl as well now. I'm wondering: could the common denominator here be Reexport.jl? All of the (public) examples given in this issue involve Reexport either directly or through dependencies.

**Comment by tkoolen** [comment] 2018-03-02 17:40
Not using `Reexport` anymore in `RigidBodySim` itself didn't fix the error (although some dependencies still use `Reexport`). Note also that this is just a shot in the dark.

**Comment by rdeits** [comment] 2018-03-02 18:24
Just got the same error in the tests of TypedPolynomials.jl, which does not have Reexport anywhere in its dependency tree: https://travis-ci.org/JuliaAlgebra/TypedPolynomials.jl/jobs/348352188#L535

**Comment by tkoolen** [comment] 2018-03-03 14:10
I was able to reduce the RigidBodySim case to the following scenario, which is reproducible on my Linux machine (but not on my Mac).

```julia
twan@tk-loco:~/code/RigidBodyDynamics/v0.6/RigidBodyDynamics$ julia --startup-file=no
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using OhMyREPL # yes, required

julia> module M
       import DiffEqCallbacks
       import RigidBodyTreeInspector
       RigidBodyTreeInspector.animate(x) = x
       end
M

julia> # press ctrl+D
MethodError(Core.Inference.convert, (AssertionError, "invalid age range update"), 0x0000000000000ac6)
```

Installation details: https://gist.github.com/tkoolen/8eb392231917df49f730a017c8fd1531

**Comment by KristofferC** [comment] 2018-03-03 14:15
> `julia> using OhMyREPL # yes, required`

😱

**Comment by tkoolen** [comment] 2018-03-03 14:24
I don't think it's specifically tied to OhMyREPL. I was seeing age range update failures on the METADATA.jl JuliaCIBot as well, which of course didn't have OhMyREPL installed. It's probably just an additional bit of complexity that triggers something or other.

**Comment by tkoolen** [comment] 2018-03-03 14:28
One interesting thing about OhMyREPL is that it has an `__init__` function though; maybe a lead?

**Comment by tkoolen** [comment] 2018-03-03 15:49
FWIW, commenting out the `__init__` function in OhMyREPL made the invalid age range update error upon exit go away.

**Comment by tkoolen** [comment] 2018-03-12 19:35
Alright, another shot in the dark: could this be some kind of race condition that happens in the presence of `__init__` functions that take a nontrivial amount of time?

**Comment by dehann** [comment] 2018-03-12 20:36
For the sake of broader testing:  I just tried the example and got the error first time.  My system config is:
```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```
Additional note, my IJulia is not set up correctly, but the error still occurred.

**Comment by hakanergun** [comment] 2018-04-03 15:00
Is there any work around for julia 0.6.2? I suddenly started to have this problem under windows 10.

**Comment by philippwitte** [comment] 2018-05-30 19:59
Deleting everything in  `~/.julia/.cache`, `~/.julia/lib` and `~/.julia/v0.6/METADATA` solved the issue for me.

**Comment by KristofferC** [comment] 2019-10-15 09:54
Seems fixed (haven't heard about this in a long time). Someone can comment/reopen an issue if this happens again.

**Closed by KristofferC** 2019-10-15 09:54 UTC
Labels: inference
