### ISSUE TITLE
Undefined variable in module could print the module

### ISSUE THREAD

**Issue by matbesancon** [JuliaLang/julia#40482] opened 2021-04-14 16:46 UTC
```julia
julia> using LinearAlgebra

julia> LinearAlgebra.hello()
ERROR: UndefVarError: hello not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:26
 [2] top-level scope
   @ REPL[2]:1
```

The error could be more helpful with `ERROR: UndefVarError: no binding hello defined in module LinearAlgebra`

**Comment by vtjnash** [comment] 2021-04-14 18:14
Duplicate of https://github.com/JuliaLang/julia/issues/25263

**Closed by vtjnash** 2021-04-14 18:14 UTC
