### ISSUE TITLE
Should fieldnames return a tuple rather than an array?

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#25327] opened 2017-12-29 22:29 UTC
It would sound natural to me for `fieldnames` to return a tuple. The current implementation returning an array implies an allocation even in cases where it could be avoided.

~~This could have more visible consequences now that we have `NamedTuple`, for which it is more common to extract the field names since they cannot be known in advance.~~ EDIT: this comment doesn't seem accurate (see below)

**Comment by vtjnash** [comment] 2017-12-29 22:43
Reflection on `fieldnames` is discouraged. (for `NamedTuple`, the keys should be extracted with the `keys` function).

**Comment by yurivish** [comment] 2017-12-29 23:09
> Reflection on fieldnames is discouraged. 

Could you clarify what you mean here? I'm not sure if you meant something specific to `NamedTuple`s or if it's discouraged to use `fieldnames` for metaprogramming in general.

**Comment by nalimilan** [comment] 2017-12-29 23:10
Conversely, what are typical use cases for `fieldnames`?

**Comment by smldis** [comment] 2017-12-29 23:12
The small story about this is that the issue is coming from slack, a user posted it as a note and there where some thumbs up and no thumbs down. I would rather let some core developer discuss the consecuences (and tradeoffs) of a deprecation for 0.7 and a switch for 1.0 or for the next major api break.
Please don't be noisy on the topic since it is difficult to take care of such a breaking change at this precise time.

**Comment by andyferris** [comment] 2017-12-30 03:24
> Reflection on `fieldnames` is discouraged.

If that's true in general (not specifically for named tuples) then we shouldn't be exporting it from `Base`, should we?

**Comment by vtjnash** [comment] 2017-12-30 03:40
We export lots of reflection toys from Base. I suppose we could hide them under some sort of `Reflection` module, but many of them (`isbits`, `names`, `fieldoffset`, etc.) are pretty useful, and all are pretty varied.

(For NamedTuples, this is also just an artifact of their current implementation, not part of their stable API)

**Comment by yurivish** [comment] 2017-12-30 05:09
The reflection stuff is highly useful for building good tooling for understanding and writing Julia code; it would be unfortunate if their use would be discouraged in general. If there are some rough edges that would need to be fixed with breaking changes in a 1.X, though, then maybe marking them "unstable" would suffice?

**Comment by nalimilan** [comment] 2017-12-30 16:24
These considerations don't seem to directly address the issue at hand, do they? What do we expect people to use `fieldnames` for exactly?

**Comment by smldis** [comment] 2017-12-31 13:43
Looking at master they are mostly used for testing and documentation.
As for other usecases: 

julia master (cholmod.jl):  
```
let offset = fieldoffset(C_Sparse{Float64}, findfirst(name -> name === :stype, fieldnames(C_Sparse{Float64})))
```

gadfly (chain method)
```
for name in fieldnames(Data)
    #more code
    getfield(data, name)
    #more code
```

So @vtjnash a `Reflection` module would be a nice occasion to put some engineering love in the julia reflection toolbox.
Is this feasible given the release and man power constraints, before or after 1.0?

The toolbox for now is composed by more than just: `isbits`, `names`, `fieldoffset`, `fieldname`,`fieldnames`, `getfield`, `methods`, `methodswith`, `subtypes`

The currently exported methods list is not structured ordered by usecase/functionality (the work could start from here right?)
```
# types
    convert,
    # getproperty,
    # setproperty!,
    fieldoffset,
    fieldname,
    fieldnames,
    fieldcount,
    isconcrete,
    oftype,
    promote,
    promote_rule,
    promote_type,
    subtypes,
    instances,
    supertype,
    typeintersect,
    typejoin,
    widen,

#= ... =#

# help and reflection
    apropos,
    edit,
    code_typed,
    code_warntype,
    code_lowered,
    code_llvm,
    code_native,
    fullname,
    functionloc,
    isconst,
    isinteractive,
    less,
    method_exists,
    methods,
    methodswith,
    module_name,
    module_parent,
    names,
    varinfo,
    versioninfo,
    which,
@isdefined,```

If this is the case, I'd link the discussion to #20555.
If it is not this issue is still addressable by finding an answer to the issue title.

**Comment by JeffBezanson** [comment] 2017-12-31 23:45
I do think it would make sense for `fieldnames` to return a constant, immutable container. It tends to be small, and it would be weird to mutate it, so we might as well avoid the allocation.

**Comment by nalimilan** [comment] 2018-01-24 11:11
Opened https://github.com/JuliaLang/julia/pull/25725.

**Closed** 2018-02-09 19:05 UTC
