### ISSUE TITLE
JL_LLVM_VERSION not defined in codegen_shared.h (in llvmcalltest.cpp)

### ISSUE THREAD

**Issue by iamed2** [JuliaLang/julia#30379] opened 2018-12-13 19:42 UTC
This seems...not right?

```
In file included from /Users/ericdavies/repos/julia1p0/src/llvmcalltest.cpp:9:
./codegen_shared.h:21:5: warning: 'JL_LLVM_VERSION' is not defined, evaluates to 0 [-Wundef]
#if JL_LLVM_VERSION >= 50000
    ^
./codegen_shared.h:31:5: warning: 'JL_LLVM_VERSION' is not defined, evaluates to 0 [-Wundef]
#if JL_LLVM_VERSION >= 50000
    ^
./codegen_shared.h:41:5: warning: 'JL_LLVM_VERSION' is not defined, evaluates to 0 [-Wundef]
#if JL_LLVM_VERSION >= 50000
    ^
./codegen_shared.h:50:5: warning: 'JL_LLVM_VERSION' is not defined, evaluates to 0 [-Wundef]
#if JL_LLVM_VERSION >= 50000
    ^
./codegen_shared.h:59:5: warning: 'JL_LLVM_VERSION' is not defined, evaluates to 0 [-Wundef]
#if JL_LLVM_VERSION >= 50000
    ^
./codegen_shared.h:69:5: warning: 'JL_LLVM_VERSION' is not defined, evaluates to 0 [-Wundef]
#if JL_LLVM_VERSION >= 50000
    ^
```

Happens when building `release-1.0` branch using BinaryBuilder LLVM on macOS with clang.

**Comment by iamed2** [comment] 2018-12-14 20:19
Was the issue for sure not present when that commit was introduced to master?

Current master can't have this issue because of https://github.com/JuliaLang/julia/commit/82941f33e532085cbe8a9bc5b905a2d709687997, but I can't say for the previous state (running on battery so can't rebuild Julia right now).

**Comment by KristofferC** [comment] 2019-02-18 15:12
What is there to triage here?

**Comment by StefanKarpinski** [comment] 2019-02-18 15:36
If the issue is fixed, the issue should probably be closed.

**Comment by KristofferC** [comment] 2019-02-18 15:37
Not sure why it wasnt auto closed by the comment in https://github.com/JuliaLang/julia/pull/30422#issue-239275731. Perhaps that is only when merging to master.

**Closed by KristofferC** 2019-02-18 15:37 UTC
Labels: bug, codegen, triage
