### ISSUE TITLE
Pkg.update() Stalls After Installation of RCall

### ISSUE THREAD

**Issue by odysseus9672** [JuliaLang/julia#11652] opened 2015-06-10 07:03 UTC
Adding RCall stalls with the last output being:
INFO: Cloning cache of DataFrames from git://github.com/JuliaStats/DataFrames.jl.git

This can be circumvented using:
Pkg.clone("git://github.com/JuliaStats/DataFrames.jl.git")

and Pkg.add("RCall") proceeds to completion. The problem is that after the Pkg.clone step completes, Pkg.update() now stalls permanently. I observe this behavior on both Linux and Mac OS X 10.10 systems. The version of julia this happens on is:

Version 0.4.0-dev+5287 (2015-06-09 22:19 UTC)
Commit c7e2b33* (0 days old master)

I've been observing this behavior in the master branch for a couple of weeks, now.

**Comment by kshyatt** [comment] 2015-06-10 07:07
I don't have RCall installed but I'm seeing what appears to be something similar - `Updating METADATA` has been hanging for over an hour when it normally takes < 1 minute, when I run `Pkg.update`, on `Version 0.4.0-dev+5282`.

**Comment by tkelman** [comment] 2015-06-10 08:37
Duplicate of #11623

**Closed by tkelman** 2015-06-10 08:37 UTC

**Comment by kshyatt** [comment] 2015-06-10 08:39
Oops, sorry!
