### ISSUE TITLE
repmat accepting Int only

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaLang/julia#20112] opened 2017-01-18 20:46 UTC
```julia
julia> repmat(rand(2,2), Int32(1))
ERROR: MethodError: no method matching repmat(::Array{Float64,2}, ::Int32)
Closest candidates are:
  repmat(::Union{AbstractArray{T,1},AbstractArray{T,2}}, ::Int64) at abstractarraymath.jl:271
  repmat(::Union{AbstractArray{T,1},AbstractArray{T,2}}, ::Int64, ::Int64) at abstractarraymath.jl:271
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
```
Could the signature be relaxed to accept generic `Integer`s? (I guess yes :)

**Comment by tkelman** [comment] 2017-01-18 21:11
near-duplicate of https://github.com/JuliaLang/julia/issues/17372

**Comment by CarloLucibello** [comment] 2017-01-18 21:27
>near-duplicate of #17372
In that case the signature of reshape was tightened to avoid some weird consequenced (obtaining ReshapedArray instead of Array). I guess that it is safe to relax repmat instead, right?

**Comment by fredrikekre** [comment] 2017-02-20 21:26
Any reason this was reopened? Fixed by https://github.com/JuliaLang/julia/pull/20113

**Closed** 2017-02-20 21:26 UTC
