### ISSUE TITLE
student has permissions problem for `libcairo-2.dll`

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaLang/julia#53139] opened 2024-01-31 20:22 UTC
my student is getting an access denied error.
student installed Julia from installer online.
```
julia> versioninfo() Julia Version 1.10.0 Commit 3120989f39 (2023-12-25 18:01 UTC)
Platform Info: OS: Windows (x86_64-w64-mingw32) 
CPU: 8 × 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz 
WORD_SIZE: 64 
LIBM: libopenlibm 
LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake) 
Threads: 1 on 8 virtual cores
```
![image](https://github.com/JuliaLang/julia/assets/30643894/26daa7fd-68fb-405e-acff-0d08e1794240)

**Comment by vtjnash** [comment] 2024-01-31 20:59
It maybe failed to set the executable bits on that dll, but I am not sure why that could have happened only for this one computer

**Comment by ViralBShah** [comment] 2024-01-31 23:56
Is it reproducible on other Windows machines? Perhaps it is an issue with the Cairo Yggdrasil recipe.

**Comment by SimonEnsemble** [comment] 2024-01-31 23:59
other students with Windows are able to run `CairoMakie.jl` just fine!

https://github.com/MakieOrg/Makie.jl/issues/3568

**Comment by ViralBShah** [comment] 2024-01-31 23:59
Maybe the student has some heavy security settings in windows?

**Comment by giordano** [comment] 2024-02-01 00:55
Sounds like a duplicate of #52272 which I have no idea why it was closed without any action.

**Comment by giordano** [comment] 2024-02-01 00:58
I wonder if this is related to https://github.com/JuliaLang/Pkg.jl/pull/3349, because according to #52272 this issue doesn't occur if installing the same artifact through Julia v1.9.

**Comment by giordano** [comment] 2024-02-22 14:35
Closing as duplicate of #52272, there's no point in keeping multiple tickets about the same issue open.

**Closed by giordano** 2024-02-22 14:35 UTC
Labels: windows
