### ISSUE TITLE
uniformize variable declaration syntaxes

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#18197] opened 2016-08-23 12:46 UTC
```jl
julia> const x = 2, y = 3, z = 4
ERROR: syntax: invalid assignment location "3"
```

```jl
julia> global x = 2, y = 3, z = 4
4
```

```jl
julia> global const x = 2, y = 3, z = 4
4
```

Reported at https://groups.google.com/forum/#!topic/julia-users/YSbN6EPOzKk.

**Comment by yuyichao** [comment] 2016-08-23 12:52
FWIW

```jl
julia> (a, (b, c)) = (1, (2, 3))
(1,(2,3))

julia> const (a, (b, c)) = (1, (2, 3))
ERROR: syntax: expected identifier after "const"

julia> global (a, (b, c)) = (1, (2, 3))
ERROR: syntax: invalid syntax in "global" declaration
```

**Comment by JeffBezanson** [comment] 2016-08-23 14:36
Duplicate of #7314

**Comment by StefanKarpinski** [comment] 2016-08-23 18:40
I guess that would explain why it seemed familiar and I thought it had already been fixed :)

**Closed** 2016-10-17 16:32 UTC
Labels: parser
