### ISSUE TITLE
@parallel (+) segmentation fault on arm 

### ISSUE THREAD

**Issue by dasGringuen** [JuliaLang/julia#13508] opened 2015-10-09 12:13 UTC
Hello

we are running Julia on the Red Pitaya platform using Debian Jessie armhf. 
Were are getting a segmentation fault while running the next code. 
You can find the code and the error log while running it with gdb.

Any hints?

Many thanks,
Adrian

Julia version:
-------------
<pre>
root@red-pitaya:~/julia# ./julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc4 (2015-10-04 03:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  arm-linux-gnueabihf

julia> 
</pre>

Code:
-----
<pre>
root@red-pitaya:~/julia# cat multicore_forloop.jl
#A microbenchmark to demonstrate the effect of parallel for loops
#
#$author: Manfred Mücke
#$created: 20.9.2015
#$lastchange: 29.9.2015
#

println ("==== multicore_forloop.jl ====")
println ("Julia version: $VERSION")

#remove all workers which might be around
rmprocs(workers())
println("Sequential run - available processes: $(nprocs()) ")

@everywhere n=5000000 # to scale test size

#------------------sequential
s_s=0
for i = 1:n #first run
  s_s += i^2
end
s_s=0
t_seq = @elapsed for i = 1:n #measure
  s_s += i^2
end

#add four worker processes on local machine
addprocs(4)
println("Parallel run - available workers: ",nworkers())

#------------------parallel
@everywhere s_p=0
s_p = @parallel (+) for i = 1:n # first run
  i^2
end
@sync @everywhere sleep(1) # global barrier

t_par = @elapsed @parallel (+) for i = 1:n # measure
  i^2
end

if (myid() == 1)
  println ("Results match: $(s_p == s_s) ($s_p, $s_s)")
  println (" Sequential: \t$t_seq\n Parallel: \t$t_par\n Speed-Up: \t$(t_seq/t_par)\n")
  println ("===============================================")
end

#remove all workers which might be around
#rmprocs(workers())
</pre>

Gdb log
-------
<pre>
root@red-pitaya:~/julia# gdb --args ./julia ./multicore_forloop.jl 
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./julia...done.
(gdb) r
Starting program: /root/julia/julia ./multicore_forloop.jl
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x12d20450 (LWP 10644)]

WARNING: deprecated syntax "println (" at /root/julia/multicore_forloop.jl:15.
Use "println(" instead.
==== multicore_forloop.jl ====

WARNING: deprecated syntax "println (" at /root/julia/multicore_forloop.jl:17.
Use "println(" instead.
Julia version: 0.4.0-rc4
WARNING: rmprocs: process 1 not removed
Sequential run - available processes: 1 

signal (11): Segmentation fault

signal (11): Segmentation fault

signal (11): Segmentation fault

signal (11): Segmentation fault
[New Thread 0x10d4a450 (LWP 10653)]
[New Thread 0x1054a450 (LWP 10654)]
[New Thread 0xfd4a450 (LWP 10655)]
[New Thread 0xf54a450 (LWP 10656)]
ERROR: LoadError: connect: connection refused (ECONNREFUSED)

...and 3 other exceptions.

while loading /root/julia/multicore_forloop.jl, in expression starting on line 55
UndefRefError()
[Thread 0xf54a450 (LWP 10656) exited]
[Thread 0x1054a450 (LWP 10654) exited]
[Thread 0xfd4a450 (LWP 10655) exited]
[Thread 0x10d4a450 (LWP 10653) exited]
[Thread 0x36ff1000 (LWP 10641) exited]
[Inferior 1 (process 10641) exited with code 01]
</pre>

**Comment by dasGringuen** [comment] 2015-10-15 17:03
Hello,

I have tried also with a Raspberry pi and I'm getting the same segmentation fault errors.
I followed the ARM compilation guide, enabled the debugging information and run it with GDB.
Next you can find a more detailed output.

Could you please suggest how to proceed. We are looking forward on tracking this issue and fixing it.

Regards,
Adrian

Versioninfo()
-------------
<pre>
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b (2015-10-08 06:20 UTC)
DEBUG build
Platform Info:
  System: Linux (arm-linux-gnueabihf)
  CPU: ARMv7 Processor rev 5 (v7l)
  WORD_SIZE: 32
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.6.1
</pre>

Make.user
---------

<pre>
pi@raspberrypi ~/julia $ cat Make.user 
FORCE_ARMV7=1
LLVM_ASSERTIONS=1

override USE_SYSTEM_BLAS=1
override USE_SYSTEM_LAPACK=1
override USE_SYSTEM_LIBM=1
override USE_SYSTEM_FFTW=1
override USE_SYSTEM_GMP=1
override USE_SYSTEM_MPFR=1
override USE_SYSTEM_ARPACK=1
</pre>


gdb output
---------

<pre>
pi@raspberrypi ~/julia $ gdb --args usr/bin/julia-debug multi_core.jl 
GNU gdb (Raspbian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from usr/bin/julia-debug...done.
(gdb) r
Starting program: /home/pi/julia/usr/bin/julia-debug multi_core.jl
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
WARNING: unable to determine host cpu name.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.

WARNING: deprecated syntax "println (" at /home/pi/julia/multi_core.jl:15.
Use "println(" instead.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
==== multicore_forloop.jl ====warning: JITed object file architecture armv4 is not compatible with target architecture arm.


WARNING: deprecated syntax "println (" at /home/pi/julia/multi_core.jl:17.
Use "println(" instead.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
Julia version: 0.4.0
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
WARNING: rmprocs: process 1 not removed
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
Sequential run - available processes: 1 
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
WARNING: unable to determine host cpu name.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
WARNING: unable to determine host cpu name.
WARNING: unable to determine host cpu name.
WARNING: unable to determine host cpu name.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.

signal (11): Segmentation fault

signal (11): Segmentation fault

signal (11): Segmentation fault

signal (11): Segmentation fault
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
[New Thread 0x522e7450 (LWP 25229)]
[New Thread 0x51ae7450 (LWP 25230)]
[New Thread 0x512e7450 (LWP 25231)]
[New Thread 0x50ae7450 (LWP 25232)]
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
ERROR: LoadError: connect: connection refused (ECONNREFUSED)

...and 3 other exceptions.

while loading /home/pi/julia/multi_core.jl, in expression starting on line 57
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
UndefRefError(warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
)
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
warning: JITed object file architecture armv4 is not compatible with target architecture arm.
[Thread 0x522e7450 (LWP 25229) exited]
[Thread 0x512e7450 (LWP 25231) exited]
[Thread 0x51ae7450 (LWP 25230) exited]
[Thread 0x50ae7450 (LWP 25232) exited]
[Inferior 1 (process 25222) exited with code 01]
(gdb) 

</pre>





Compilation log
------------------

<pre>
pi@raspberrypi ~/julia $ make debug -j4
    CC src/jltypes.dbg.obj
    CC src/gf.dbg.obj
    CC src/support/hashing.dbg.obj
    CC src/support/timefuncs.dbg.obj
    CC src/support/ptrhash.dbg.obj
    CC src/support/operators.dbg.obj
    CC src/support/utf8.dbg.obj
    CC src/support/ios.dbg.obj
    CC src/support/htable.dbg.obj
    CC src/support/bitvector.dbg.obj
    CC src/support/int2str.dbg.obj
    CC src/support/libsupportinit.dbg.obj
    CC src/builtins.dbg.obj
    CC src/support/arraylist.dbg.obj
    CC src/support/strtod.dbg.obj
    CC src/module.dbg.obj
    CC src/codegen.dbg.obj
    CC src/disasm.dbg.obj
    LINK src/support/libsupport-debug.a
    CC src/debuginfo.dbg.obj
    CC src/interpreter.dbg.obj
In file included from intrinsics.cpp:52:0,
                 from codegen.cpp:1264:
ccall.cpp:245:4: warning: #warning "ccall is defaulting to llvm ABI, since no platform ABI has been defined for this CPU/OS combination" [-Wcpp]
 #  warning "ccall is defaulting to llvm ABI, since no platform ABI has been defined for this CPU/OS combination"
    ^
    CC src/alloc.dbg.obj
    CC src/dlload.dbg.obj
    CC src/sys.dbg.obj
    CC src/init.dbg.obj
    CC src/task.dbg.obj
In file included from /home/pi/julia/usr/include/libunwind.h:7:0,
                 from julia_internal.h:164,
                 from task.c:16:
task.c: In function ‘rec_backtrace’:
/home/pi/julia/usr/include/libunwind-arm.h:272:5: warning: right-hand operand of comma expression has no effect [-Wunused-value]
   }), 0)
     ^
/home/pi/julia/usr/include/libunwind-common.h:108:29: note: in expansion of macro ‘unw_tdep_getcontext’
 #define unw_getcontext(uc)  unw_tdep_getcontext(uc)
                             ^
task.c:644:5: note: in expansion of macro ‘unw_getcontext’
     unw_getcontext(&uc);
     ^
    CC src/array.dbg.obj
debuginfo.cpp: In member function ‘virtual void JuliaJITEventListener::NotifyObjectEmitted(const llvm::object::ObjectFile&, const llvm::RuntimeDyld::LoadedObjectInfo&)’:
debuginfo.cpp:406:13: warning: narrowing conversion of ‘SectionSize’ from ‘uint64_t {aka long long unsigned int}’ to ‘size_t {aka unsigned int}’ inside { } [-Wnarrowing]
             };
             ^
debuginfo.cpp:209:18: warning: unused variable ‘Size’ [-Wunused-variable]
         uint64_t Size;
                  ^
debuginfo.cpp:229:18: warning: unused variable ‘SectionAddrCheck’ [-Wunused-variable]
         uint64_t SectionAddrCheck = 0; // assert that all of the Sections are at the same location
                  ^
    CC src/dump.dbg.obj
    CC src/toplevel.dbg.obj
    CC src/jl_uv.dbg.obj
    CC src/jlapi.dbg.obj
    CC src/signal-handling.dbg.obj
    CC src/llvm-simdloop.dbg.obj
In file included from signal-handling.c:62:0:
signals-unix.c: In function ‘sigdie_handler’:
signals-unix.c:42:55: warning: passing argument 3 of ‘rec_backtrace_ctx’ from incompatible pointer type
     bt_size = rec_backtrace_ctx(bt_data, MAX_BT_SIZE, (ucontext_t*)context);
                                                       ^
In file included from signal-handling.c:7:0:
julia_internal.h:171:18: note: expected ‘bt_context_t’ but argument is of type ‘struct ucontext_t *’
 DLLEXPORT size_t rec_backtrace_ctx(ptrint_t *data, size_t maxsize, bt_context_t ctx);
                  ^
    CC src/simplevector.dbg.obj
    CC src/gc.dbg.obj
    CC src/flisp/flisp.dbg.obj
    CC src/flisp/builtins.dbg.obj
    CC src/flisp/string.dbg.obj
    CC src/flisp/equalhash.dbg.obj
    CC src/flisp/table.dbg.obj
    CC src/flisp/iostream.dbg.obj
    CC src/flisp/julia_extensions.dbg.obj
    CC src/flisp/flmain.dbg.obj
    LINK src/flisp/libflisp-debug.a
    LINK src/flisp/flisp-debug
    FLISP src/julia_flisp.boot
    FLISP src/julia_flisp.boot.inc
    CC src/ast.dbg.obj
    LINK usr/lib/libjulia-debug.so
    CC ui/repl.dbg.obj
    LINK usr/bin/julia-debug
    JULIA usr/lib/julia/sys-debug.o
WARNING: unable to determine host cpu name.
exports.jl
essentials.jl
docs/bootstrap.jl
base.jl
reflection.jl
build_h.jl
version_git.jl
c.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
refpointer.jl
functors.jl
abstractarray.jl
subarray.jl
array.jl

hashing.jl
rounding.jl
float.jl
complex.jl
rational.jl
abstractarraymath.jl
arraymath.jl
simdloop.jl
reduce.jl
bitarray.jl
intset.jl
dict.jl
set.jl
iterator.jl
osutils.jl
char.jl
ascii.jl
iobuffer.jl
string.jl
strings/types.jl
strings/basic.jl
strings/search.jl
strings/util.jl
strings/io.jl
unicode.jl
unicode/UnicodeError.jl
unicode/types.jl
unicode/checkstring.jl
unicode/utf8.jl
unicode/utf16.jl
unicode/utf32.jl
unicode/utf8proc.jl
parse.jl
shell.jl
regex.jl
pcre.jl
base64.jl
io.jl
iostream.jl
libc.jl
libdl.jl
env.jl
path.jl
intfuncs.jl
nullable.jl
task.jl
lock.jl
show.jl
stream.jl
uv_constants.jl
socket.jl
stat.jl
fs.jl
process.jl
multimedia.jl
grisu.jl
file.jl
methodshow.jl
floatfuncs.jl
math.jl
float16.jl
cartesian.jl
multidimensional.jl
primes.jl
reducedim.jl
ordering.jl
collections.jl
sort.jl
version.jl
gmp.jl
mpfr.jl
combinatorics.jl
hashing2.jl
dSFMT.jl
random.jl
printf.jl
meta.jl
Enums.jl
serialize.jl
channels.jl
multi.jl
managers.jl
loading.jl
poll.jl
mmap.jl
sharedarray.jl
datafmt.jl
deepcopy.jl
interactiveutil.jl
replutil.jl
test.jl
i18n.jl
Terminals.jl
LineEdit.jl
REPLCompletions.jl
REPL.jl
client.jl
util.jl
linalg.jl
broadcast.jl
statistics.jl
sparse.jl
irrationals.jl
dft.jl
dsp.jl
sysinfo.jl
quadgk.jl
fastmath.jl
pkg.jl
profile.jl
Dates.jl
markdown/Markdown.jl
docs/Docs.jl
deprecated.jl
require.jl
docs/helpdb.jl
docs/basedocs.jl
/home/pi/julia/base/precompile.jl
    LINK usr/lib/julia/sys-debug.so
</pre>

**Comment by tkelman** [comment] 2015-10-15 20:49
Best to use something separate gist.github.com to post long logs, whith just links here so this page isn't as bad to scroll through. Someone with access to an arm build will have to look into this.

**Comment by ViralBShah** [comment] 2015-11-25 12:14
I trimmed the output above. Also, this is easily reproduced just with:

````
viral@julia-arm:~/julia$ ./julia -p 2
WARNING: unable to determine host cpu name.
WARNING: unable to determine host cpu name.
WARNING: unable to determine host cpu name.

signal (11): Segmentation fault
while loading no file, in expression starting on line 0

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
````

**Comment by yuyichao** [comment] 2016-01-06 01:46
Close as a direct dup of https://github.com/JuliaLang/julia/issues/12344 (and almost all of these issues on ARM) are just due to incompatible C ABI. Please feel free to report additional issues with `@parallel` on ARM after #14194 is merged.

**Closed by yuyichao** 2016-01-06 01:46 UTC
Labels: arm, parallel
