### ISSUE TITLE
sum, maximum, .. very slow for tuples > 32

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#47648] opened 2022-11-21 09:50 UTC
`sum`, `prod`, `maximum`, `minimum`, `extrema` benchmark comparably over small vectors and small tuples (n <= 32).  They continue to benchmark well for n in 33..64 for vectors but become very slow for tuples with more than 32 elements. 
(run using Julia 1.9.0-alpha1, windows 64)
```
julia> r16 = rand(16) ; r32 = rand(32); r33 = rand(33); r64 = rand(64);
julia> t16 = Tuple(r16); t32 = Tuple(r32); t33 = Tuple(r33); t64 = Tuple(r64);

julia> (@btime maximum($r16)), (@btime maximum($t16));
  21.242 ns (0 allocations: 0 bytes)
  12.412 ns (0 allocations: 0 bytes)

julia> (@btime maximum($r32)), (@btime maximum($t32));
  29.447 ns (0 allocations: 0 bytes)
  20.762 ns (0 allocations: 0 bytes)

julia> (@btime maximum($r33)), (@btime maximum($t33));
  30.291 ns (0 allocations: 0 bytes)
  755.238 ns (35 allocations: 816 bytes)

julia> (@btime maximum($r64)), (@btime maximum($t64));
  54.813 ns (0 allocations: 0 bytes)
  1.330 μs (66 allocations: 1.55 KiB)


julia> (@btime sum($r16)), (@btime sum($t16));
  13.600 ns (0 allocations: 0 bytes)
  5.900 ns (0 allocations: 0 bytes)

julia> (@btime sum($r32)), (@btime sum($t32));
  13.714 ns (0 allocations: 0 bytes)
  7.000 ns (0 allocations: 0 bytes)

julia> (@btime sum($r33)), (@btime sum($t33));
  14.314 ns (0 allocations: 0 bytes)
  738.583 ns (35 allocations: 816 bytes)

julia> (@btime sum($r64)), (@btime sum($t64));
  14.214 ns (0 allocations: 0 bytes)
  1.360 μs (66 allocations: 1.55 KiB)
```

**Comment by KristofferC** [comment] 2022-11-21 10:23
Digging down a bit:

```julia
julia> op = Base.BottomRF{typeof(max)}(max)
Base.BottomRF{typeof(max)}(max)

julia> @btime Base._foldl_impl($op, Base._InitialValue(), $t33)
  759.228 ns (35 allocations: 816 bytes)
0.9957947023576502

julia> @btime Base._foldl_impl($op,  Base._InitialValue(), $r33)
  59.112 ns (0 allocations: 0 bytes)
0.9957947023576502

julia> @which Base._foldl_impl(op,Base._InitialValue(), t33)
_foldl_impl(op, init, itr::Tuple) in Base at tuple.jl:277

julia> @which Base._foldl_impl(op,Base._InitialValue(), r33)
_foldl_impl(op::OP, init, itr) where OP in Base at reduce.jl:53
```

So it seems the splatting defined in https://github.com/JuliaLang/julia/blob/c9eccfc1e863bcbf7ef3be55403c5bcd60a1494e/base/tuple.jl#L329 is bad for performance when the tuple gets large (which makes sense).

**Comment by N5N3** [comment] 2022-11-21 11:05
Should be fixed if we merge #47109.
Mind to take a quick look there @KristofferC?

**Comment by KristofferC** [comment] 2022-11-21 11:07
Heh, I also did an attempt: https://github.com/JuliaLang/julia/commit/ad9e2cf778bcfb32c38336013425c26bcb0ec741. Any thoughts?

**Comment by N5N3** [comment] 2022-11-21 11:16
https://github.com/JuliaLang/julia/pull/47109 would let one more element when trying unroll at julia level. (Since `ntuple(identity, 32) isa Base.Any32`)
I think this might help to avoid possible regression.

**Comment by KristofferC** [comment] 2022-11-21 11:20
Ok, let's go with that one then :)

**Closed** 2022-11-21 19:39 UTC
Labels: performance
