### ISSUE TITLE
"make testall" produces new error in 'repl' : InterruptException

### ISSUE THREAD

**Issue by colbec** [JuliaLang/julia#14277] opened 2015-12-05 06:24 UTC
Using openSUSE Leap 42.1:

make testall appears to complete with SUCCESS, but produces new errors not expressed about 24 hours ago. These do not contain a note about normal behaviour, hence the report. Output follows:

julia> make testall
...
	From worker 5:	     * lineedit              in   1.77 seconds, maxrss  733.94 MB
	From worker 4:	     * file                  in  30.41 seconds, maxrss  728.28 MB
WARNING: Caught an exception in the keymap:
ERROR: InterruptException:
WARNING: Caught an exception in the keymap:
ERROR: InterruptException:
	From worker 5:	     * replcompletions       in   2.20 seconds, maxrss  734.07 MB
WARNING: Caught an exception in the keymap:
ERROR: InterruptException:
	From worker 5:	     * replutil              in   0.88 seconds, maxrss  739.62 MB
...
SUCCESS

**Comment by tkelman** [comment] 2015-12-05 06:30
I'm pretty sure this is actually in happening in the repl test, and was caused by the change in https://github.com/JuliaLang/julia/commit/fb48014b23273bc3f021d31aab3246d717d2bb5d from `raise` to `kill` in `jl_raise_debugger` which the repl code uses in a few places.

**Comment by tkelman** [comment] 2015-12-06 21:08
closed by https://github.com/JuliaLang/julia/pull/14296 ?

**Closed** 2015-12-06 21:09 UTC
Labels: test
