### ISSUE TITLE
detailed error output no longer printed when a worker exits

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#13814] opened 2015-10-29 02:30 UTC
Looking at #13810, on 0.4:

```
julia> @fetchfrom 2 v
fatal error on 2: ERROR: MethodError: `convert` has no method matching convert(::Type{Array{ASCIIString,1}}, ::Function)
This may have arisen from a call to the constructor Array{ASCIIString,1}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{Array{T,1}}, !Matched::Range{T})
  convert{T,S,N}(::Type{Array{T,N}}, !Matched::SubArray{S,N,P<:AbstractArray{T,N},I<:Tuple{Vararg{Union{AbstractArray{T,1},Colon,Int64}}},LD})
  ...
 in setindex! at array.jl:313
 in deserialize_array at serialize.jl:612
 in handle_deserialize at serialize.jl:461
 in deserialize at serialize.jl:480
 in handle_deserialize at serialize.jl:461
 in deserialize at serialize.jl:536
 in handle_deserialize at serialize.jl:461
 in deserialize at serialize.jl:694
 in deserialize_datatype at serialize.jl:647
 in handle_deserialize at serialize.jl:461
 in message_handler_loop at multi.jl:847
 in process_tcp_streams at multi.jl:836
 in anonymous at task.jl:63
Worker 2 terminated.
ERROR: ProcessExitedException()
 in yieldto at ./task.jl:71
 in wait at ./task.jl:371
 in wait at ./task.jl:286
 in wait at ./channels.jl:93
 in take! at ./channels.jl:82
 in take! at ./multi.jl:792
 in remotecall_fetch at multi.jl:729
 in remotecall_fetch at multi.jl:734
ERROR (unhandled task failure): EOFError: read end of file
```

and on master:

```
julia> @fetchfrom 2 v
Worker 2 terminated.
ERROR: ProcessExitedException()
 in yieldto at ./task.jl:67
 in wait at ./task.jl:367
 in wait at ./task.jl:282
 in wait at ./channels.jl:97
 in take! at ./channels.jl:84
 in take! at ./multi.jl:809
 in remotecall_fetch at multi.jl:735
 in remotecall_fetch at multi.jl:740
 in eval at ./boot.jl:264
ERROR (unhandled task failure): EOFError: read end of file
```

**Comment by tkelman** [comment] 2015-10-29 02:34
Worth bisecting to make sure I don't accidentally backport the cause.

**Comment by vtjnash** [comment] 2015-10-29 02:58
I had just fixed this on jn/worker_stderr (was waiting for travis to push it to master)

**Comment by vtjnash** [comment] 2015-10-29 03:02
closed by 2b36acd6015f10a59c44d93b1250f81b35c5bb26

**Closed by vtjnash** 2015-10-29 03:02 UTC
Labels: error handling, parallel, regression

**Comment by tkelman** [comment] 2015-10-29 04:11
what was the cause? add a test?

**Comment by JeffBezanson** [comment] 2015-10-29 14:19
Definitely caused by my cf5f23adafb4f9d1eca2ff0cdea80398ee34f799. Should not be backported, since it's a behavior change.
