### ISSUE TITLE
vector * matrix does not work

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#10350] opened 2015-02-27 11:10 UTC
```julia
julia> x = [1,2]
2-element Array{Int64,1}:
 1
 2

julia> A = [1 2; 3 4]
2x2 Array{Int64,2}:
 1  2
 3  4

julia> x * A
ERROR: DimensionMismatch("*")
 in generic_matmatmul! at linalg/matmul.jl:369
 in * at linalg/matmul.jl:76

julia> A * x
2-element Array{Int64,1}:
  5
 11
```
The fix is trivial: at `linalg/matmul.jl:76`, put the 1 first:
```
julia> (*)(A::AbstractVector, B::AbstractMatrix) = reshape(A,1,length(A))*B
Warning: Method definition *(AbstractArray{T,1},AbstractArray{T,2}) in module LinAlg at linalg/matmul.jl:76 overwritten in module Main at none:1.
* (generic function with 143 methods)

julia> x * A
1x2 Array{Int64,2}:
 7  10
```

**Comment by ivarne** [comment] 2015-02-27 11:53
Are you sure, or are you looking for `a' * x` instead?

**Comment by tpapp** [comment] 2015-02-27 12:26
Yes, I am aware that matrix multiplication is not commutative :-)

I can see two possibilities:
1. in Julia, all vectors are column vectors, so `vector * matrix` makes no sense, but then it should not be defined,
2. `vector * matrix` is interpreted as `vector' * matrix` as a DWIM extension (like, for example, R), but then the function has a bug.

If neither 1 nor 2, what's the purpose of the abovementioned definition in `matmul.jl`? Can you please give an example of a use case that would call this method?

**Comment by andreasnoack** [comment] 2015-02-27 12:33
```julia
julia> randn(3)*randn(1,3)
3x3 Array{Float64,2}:
 -0.383066   0.0384389  -0.614607
 -0.549317   0.0551214  -0.881347
  0.777643  -0.0780328   1.24768 
```
but this issue is a dup of #4774.

**Comment by ivarne** [comment] 2015-02-27 12:36
```julia
julia> x' * A
1x2 Array{Int64,2}:
 7  10

julia> x = [1,2]
2-element Array{Int64,1}:
 1
 2

julia> x * A
2x2 Array{Int64,2}:
 2  3
 4  6
```
This is a problem with linear algebra in Julia, because we parameterize arrays by number of dimensions instead of size of the dimensions. Julia's dispatch system sees `[1,2]` and `[1 2]'` as different types, but for LinAlg purposes they are equivalent, so you can use them interchangeably.

**Comment by jiahao** [comment] 2015-02-27 16:19
Closing as duplicate of #4774.

**Closed by jiahao** 2015-02-27 16:19 UTC
