### ISSUE TITLE
typing a tuple array slows down sorting

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#9741] opened 2015-01-12 16:13 UTC
As [discussed on the mailing list](https://groups.google.com/d/msg/julia-users/V-wS9a6OHlM/J1ZwR_P4BKEJ), adding type information to an array of tuples actually slows down Julia.  This doesn't seem right:
```julia
f = rand(Float64,10^6)
i = rand(Int,10^6)
v1 = collect(zip(f,i)) # Vector{(Float64,Int64)}
v2 = convert(Vector{Any}, v1)
@time sort(v1);
@time sort(v2);
```
gives 23sec for the typed array and 9sec for the untyped array (with Julia 0.4).

cc: @StefanKarpinski

**Comment by stevengj** [comment] 2015-01-12 16:33
I also notice that it is allocting 10x as many bytes when sorting the typed array and is spending more time in the gc (70% vs. 20%).

**Comment by sbromberger** [comment] 2015-01-12 16:49
I don't know whether this is significant, but there's a huge difference between successive iterations of `sort(v1)`:

```
julia> @time sort(v1);
elapsed time: 15.606325672 seconds (4426195872 bytes allocated, 68.13% gc time)

julia> @time sort(v1);
elapsed time: 29.92448937 seconds (4421730016 bytes allocated, 84.72% gc time)

julia> @time sort(v1);
elapsed time: 24.988851029 seconds (4421730016 bytes allocated, 77.51% gc time)
```

This is on an otherwise-lightly-loaded machine.

**Comment by nalimilan** [comment] 2015-01-12 16:57
@sbromberger The first run is likely faster because a part of the garbage collection is only performed when reaching a threshold during the second run. Then timings get more stable, because the third run takes an equivalent amount of work from the second run, and so on.

**Comment by simonster** [comment] 2015-01-12 17:51
I would guess that, when the array is typed as `Vector{(Float64, Int)}`, we unbox the tuple when we load it from the array and rebox the tuple when we store it, whereas when it is typed as `Vector{Any}`, we reuse the same boxed tuple. This should improve when we store arrays of tuples unboxed.

**Comment by afniedermayer** [comment] 2015-01-12 18:16
I'm not sure whether it's the unboxing of tuples. Sorting `Vector{(Any,Any)}` is faster than sorting `Vector{Any}`. The following code

```julia
f = rand(Float64,10^6)
i = rand(Int,10^6)
v1 = collect(zip(f,i)) # Vector{(Float64,Int64)}
v2 = convert(Vector{Any}, v1)
v3 = convert(Vector{(Any,Any)},v1)
@time sort(v1);
@time sort(v2);
@time sort(v3);
```

gives this output
```julia
elapsed time: 23.996273562 seconds (4430512508 bytes allocated, 73.37% gc time)
elapsed time: 9.286033268 seconds (415194564 bytes allocated, 25.13% gc time)
elapsed time: 7.006919146 seconds (930410196 bytes allocated, 59.25% gc time)
```

**Comment by simonster** [comment] 2015-01-12 18:55
Try this:

```julia
function shift!(x)
	for i = 2:length(x)
		@inbounds x[i] = x[i-1]
	end
end

f = rand(Float64,10^6)
i = rand(Int,10^6)
v1 = collect(zip(f,i)) # Vector{(Float64,Int64)}
v2 = convert(Vector{Any}, v1)
v3 = convert(Vector{(Any,Any)},v1)
shift!(v1)
shift!(v2)
shift!(v3)
gc()
@time shift!(v1)
gc()
@time shift!(v2)
gc()
@time shift!(v3)
```

which yields:

```
elapsed time: 0.082906809 seconds (64000016 bytes allocated, 71.74% gc time)
elapsed time: 0.100797334 seconds (15991904 bytes allocated)
elapsed time: 0.009030296 seconds (32000048 bytes allocated)
```

The `(Float64, Int)` variant boxes the tuple (32 bytes per array element: 8 bytes for the type, 8 bytes for the length, and 8 bytes per tuple element) and each element of the array (2*16 bytes per array element). The `(Any, Any)` variant boxes the tuple (32 bytes per array element), but reuses the boxed elements. The `Any` variant reuses the boxed tuples, but falls back to dynamic dispatch for `setindex!` and so boxes the index there (16 bytes per array element). Note that the `(Any, Any)` variant is fastest despite more memory allocation than the `Any` variant because it calls `arrayset` directly instead of looking up the `setindex!` method dynamically.

I believe the dynamic lookup for `Vector{Any}` is necessary because of [these methods](https://github.com/JuliaLang/julia/blob/master/base/darray.jl#L294-L297). Without them, `shift!` with a `Vector{Any}` does not allocate and sorting a `Vector{Any}` is much faster as well.

**Comment by afniedermayer** [comment] 2015-01-12 19:17
@simonster That's very interesting. Unfortunately, it's beyond my knowledge of the details of boxing/unboxing in Julia, so I'll have to leave this to other.

Just one more comment. `isless` seems to have a major effect here: by simply adding an additional method to the `isless` function in the code above, I get this:

```julia
Base.isless{T<:Number,S<:Number}(a::(T,S),b::(T,S)) =
          (a[1]<b[1]) || (a[1]==b[1] && a[2]<b[2])

f = rand(Float64,10^6)
i = rand(Int,10^6)
v1 = collect(zip(f,i)) # Vector{(Float64,Int64)}
v2 = convert(Vector{Any}, v1)
v3 = convert(Vector{(Any,Any)},v1)
@time sort(v1);
@time sort(v2);
@time sort(v3);
```

Output:
```
elapsed time: 6.335423732 seconds (1841633256 bytes allocated, 71.63% gc time)
elapsed time: 8.522724198 seconds (415161284 bytes allocated, 21.04% gc time)
elapsed time: 7.218812753 seconds (930269888 bytes allocated, 56.64% gc time)
```

**Comment by vtjnash** [comment] 2015-01-13 03:22
duplicate of https://github.com/JuliaLang/julia/issues/9194

**Closed** 2015-01-13 04:44 UTC
Labels: performance

**Comment by Jutho** [comment] 2015-01-14 22:32
> I believe the dynamic lookup for Vector{Any} is necessary because of these methods. Without them, shift! with a Vector{Any} does not allocate and sorting a Vector{Any} is much faster as well.

The correct link should now be [this](https://github.com/JuliaLang/julia/blob/de2fefff01fc74e3602f138279aec56cf907383e/base/darray.jl#L302) . Is this method really necessary, or can it not be written in a different way, such that `Vector{Any}` could at least be indexed efficiently?
