### ISSUE TITLE
`broadcast()` fails to infer type

### ISSUE THREAD

**Issue by maxlarsen** [JuliaLang/julia#15426] opened 2016-03-09 20:10 UTC
Not sure if this is fixed on master, but on 0.4.3:
~~~
function ff()
	gg(x,y)=1.0*(x==y)
	xx=[(i,i) for i=1:2]
	yy=xx'
	broadcast(gg,xx,yy)
end

ff()

> ERROR: LoadError: MethodError: `convert` has no method matching
> convert(::Type{Tuple{Int64,Int64}}, ::Float64)

~~~

**Comment by stevengj** [comment] 2016-05-05 14:13
Duplicate of #16164 (or vice versa)

**Closed by stevengj** 2016-05-05 14:13 UTC

**Comment by stevengj** [comment] 2016-05-05 14:20
Or rather, of #4883.
