### ISSUE TITLE
Type-inference regression in string(::Int)

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#15911] opened 2016-04-17 15:01 UTC
On 0.4, `string(::Int)` was type-stable. This is no longer the case on master:
```julia
julia> f(x) = string(x)
gf (generic function with 1 method)

julia> g(x) = dec(x)
g (generic function with 1 method)

julia> @code_warntype f(2)
Variables:
  #self#::#f
  x::Int64

Body:
  begin  # REPL[1], line 1:
      return (Base.dec)(x::Int64)::Any
  end::Any

julia> @code_warntype g(2)
Variables:
  #self#::#g
  x::Int64

Body:
  begin  # REPL[2], line 1:
      return (Base.dec)((Base.box)(UInt64,(Base.box)(Int64,(Base.flipsign_int)(x::Int64,x::Int64))),1,(Base.slt_int)(x::Int64,0)::Bool)::ASCIIString
  end::ASCIIString
```

And yet, we have:
```julia
string(x::Union{Int8,Int16,Int32,Int64,Int128}) = dec(x)
```

**Comment by vtjnash** [comment] 2016-04-17 20:09
duplicate of #265

**Comment by nalimilan** [comment] 2016-04-17 21:50
Hmm, are you sure you meant https://github.com/JuliaLang/julia/issues/265? That one is very old, so clearly not a regression.

**Comment by vtjnash** [comment] 2016-04-18 04:07
yes. it's a hard issue to forget :P

actually, this one may have an easy workaround, but it needs confirmation:
```
diff --git a/base/intfuncs.jl b/base/intfuncs.jl
index 2a206c6..8d220da 100644
--- a/base/intfuncs.jl
+++ b/base/intfuncs.jl
@@ -228,6 +228,8 @@ ndigits(x::Integer) = ndigits(unsigned(abs(x)))
 
 ## integer to string functions ##
 
+string(x::Union{Int8,Int16,Int32,Int64,Int128}) = dec(x)
+
 function bin(x::Unsigned, pad::Int, neg::Bool)
     i = neg + max(pad,sizeof(x)<<3-leading_zeros(x))
     a = Array(UInt8,i)
diff --git a/base/parse.jl b/base/parse.jl
index 123b4af..90497a3 100644
--- a/base/parse.jl
+++ b/base/parse.jl
@@ -145,10 +145,6 @@ function parse{T<:Integer}(::Type{T}, s::AbstractString, base::Integer)
 end
 parse{T<:Integer}(::Type{T}, s::AbstractString) = get(tryparse_internal(T, s, 0, true))
 
-## stringifying integers more efficiently ##
-
-string(x::Union{Int8,Int16,Int32,Int64,Int128}) = dec(x)
-
 ## string to float functions ##
 
 tryparse(::Type{Float64}, s::ByteString) = ccall(:jl_try_substrtod, Nullable{Float64}, (Ptr{UInt8},Csize_t,Csize_t), s, 0, sizeof(s))
```

**Comment by ivarne** [comment] 2016-04-18 09:27
Reopening, as this seems to be solvable without addressing the issue we all know. I tested the patch on my system, and it seems to solve @nalimilan's demonstration of the issue.

@vtjnash Github displays diffs much nicer, if you specify language `diff` just as you normally specify `julia`

````
```diff
````

**Comment by nalimilan** [comment] 2016-04-18 10:44
Thanks, see https://github.com/JuliaLang/julia/pull/15919.

BTW, `string(0x1)` is type unstable (`Union{ASCIIString, UTF8String}`), but that will be fixed by merging these two types.

**Closed** 2016-04-18 14:46 UTC
Labels: regression
