### ISSUE TITLE
Error on parametric nothing union could be clearer

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#51136] opened 2023-08-31 20:35 UTC
```
julia> mutable struct Bar{T<:Real}
       foo::Union{Nothing,T}
       end

julia> Bar(1)
Bar{Int64}(1)

julia> Bar(nothing)
ERROR: UndefVarError: `T` not defined
Stacktrace:
 [1] Bar(foo::Nothing)
   @ Main ./REPL[1]:2
 [2] top-level scope
   @ REPL[2]:1
```

Perhaps something like
```
Cannot construct Bar without knowing what type T should be
```

**Comment by vtjnash** [comment] 2023-08-31 20:56
Duplicate of https://github.com/JuliaLang/julia/issues/48731

**Closed** 2023-08-31 21:03 UTC
