### ISSUE TITLE
[macOS] Julia-1.5 Release Issues

### ISSUE THREAD

**Issue by conradwt** [JuliaLang/julia#36890] opened 2020-08-03 10:04 UTC
First, when downloading the DMG located [here](https://julialang-s3.julialang.org/bin/mac/x64/1.5/julia-1.5.0-mac64.dmg), the application name should be **Julia-1.5** but it's **Julia-1.0**.  

Second, it doesn't appear that the bundle has been properly notarized because I'm getting the following dialog:

![Screen Shot 2020-08-03 at 2 58 32 AM](https://user-images.githubusercontent.com/20219/89171098-83d55280-d535-11ea-9f5d-2b1f0529e75c.png)

**Comment by KristofferC** [comment] 2020-08-03 17:46
I can't repro. Application name is correct and I don't get the notarization warning.

**Comment by staticfloat** [comment] 2020-08-03 18:07
Works for me as well; I see neither of the issues described.

@conradwt; can you run a checksum on the downloaded `.dmg` to ensure you're getting the same thing as us?  It should give a SHA256 checksum of `6312ab1a8301225855d13e9cc4c9ee5c8368a16cbf4f30006407b2ee53dff447`. (Those are published in the [checksums file](https://julialang-s3.julialang.org/bin/checksums/julia-1.5.0.sha256) linked from the [downloads page](https://julialang.org/downloads/))

I'm going to close this as two of us cannot reproduce this issue, but if you are getting the right checksummed file and still experiencing these issues, please comment and we'll reopen.

**Closed by staticfloat** 2020-08-03 18:07 UTC
