### ISSUE TITLE
SharedArray not being garbage collected

### ISSUE THREAD

**Issue by gcamilo** [JuliaLang/julia#9348] opened 2014-12-13 22:53 UTC
I posted about this in Julia-users, I thought it might be worth making an issue about this, let me know if not.

I can't find a way to deallocate a SharedArray, if the code below runs once, it means the computer has enough memory to run this. If I can properly deallocate the memory I should be able to do it again, however, I run out of memory and the program crashes:

	@everywhere nQ = 60
	@everywhere function inF(x::SharedArray,nQ::Int64)

		number = myid()-1;
		targetLength = nQ*nQ*3

		startN = floor((number-1)*targetLength/nworkers()) + 1
		endN = floor(number*targetLength/nworkers())

		myIndexes = int64(startN:endN)
		for j in myIndexes
			inds = ind2sub((nQ,nQ,nQ),j)
			x[inds[1],inds[2],inds[3],:,:,:] = rand(nQ,nQ,nQ)
		end

	end

	while true
		zeroMatrix = SharedArray(Float64,(nQ,nQ,3,nQ,nQ,nQ),pids=workers(), init = x->inF(x,nQ))
		println("ran!")
		@everywhere zeroMatrix = 1
		@everywhere gc()
	end

**Comment by simonster** [comment] 2015-06-01 16:02
#3934 and #6597 are fixed. However, this issue persists with the updated test case:

```julia
@everywhere nQ = 60
@everywhere function inF(x::SharedArray,nQ::Int64)
    number = myid()-1;
    targetLength = nQ*nQ*3

    startN = floor(Int, (number-1)*targetLength/nworkers()) + 1
    endN = floor(Int, number*targetLength/nworkers())

    myIndexes = startN:endN
    for j in myIndexes
        inds = ind2sub((nQ,nQ,nQ),j)
        x[inds[1],inds[2],inds[3],:,:,:] = rand(nQ,nQ,nQ)
    end
end

while true
    zeroMatrix = SharedArray(Float64,(nQ,nQ,3,nQ,nQ,nQ),pids=workers(), init = x->inF(x,nQ))
    println("ran!")
    @everywhere zeroMatrix = 1
    @everywhere gc()
end
```

**Comment by amitmurthy** [comment] 2015-06-02 02:41
https://github.com/JuliaLang/julia/issues/10960 could be a root cause of these issues. The finalizer installed in RemoteRef  objects is responsible for deleting its references in other processes. It is a little difficult to debug this with https://github.com/JuliaLang/julia/issues/10960 still open.

**Comment by amitmurthy** [comment] 2015-06-06 11:25
This runs without any leaks now.

```
addprocs(2)
@everywhere nQ = 10
@everywhere function inF(x::SharedArray)
    x.loc_subarr_1d[:] = rand(length(x.loc_subarr_1d))
end

while true
    zeroMatrix = SharedArray(Float64,(nQ,nQ,3,nQ,nQ,nQ),pids=workers(), init = x->inF(x))
    println("ran!")
    zeroMatrix = 1
    @everywhere gc()
end
```

closed by https://github.com/JuliaLang/julia/commit/6b94780328ad81326de28024ad45c26a69197ffe

Do reopen if you see a leak again.

**Closed by amitmurthy** 2015-06-06 11:25 UTC
Labels: parallel
