### ISSUE TITLE
Wrong output when composing length() with values() for Dictionaries

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/julia#26421] opened 2018-03-12 01:44 UTC
Consider the following code:
``` julia
julia> num_dict = Dict(1 => IntSet(1:2), 2 => IntSet(1:3))
Dict{Int64,IntSet} with 2 entries:
  2 => IntSet([1, 2, 3])
  1 => IntSet([1, 2])

julia> length(values(num_dict))
2

julia> length.(values(num_dict))
2

julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
```
It seems erroneous to me that in this case `length.(values(num_dict))` returns `2` instead of a vector with 3 and 2 as it's elements.

**Comment by JeffBezanson** [comment] 2018-03-12 04:02
Duplicate of #18618

**Closed by JeffBezanson** 2018-03-12 04:02 UTC
