### ISSUE TITLE
Confusing error message in Base.test

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#9941] opened 2015-01-27 18:46 UTC
I had the following (incorrect) code:

```
function foo()
    throw(BoundsError)   # should be throw(BoundsError())
end
```

with a test
```
@test_throws BoundsError foo()
```

which produced the following (very confusing) error:

```
ERROR: test failed: BoundsError was thrown instead of BoundsError
 in expression: foo()
 in error at error.jl:21
 in default_handler at test.jl:27
 in do_test_throws at test.jl:69
```

Is there any way to make this error message a little more helpful?

**Comment by ivarne** [comment] 2015-01-27 19:34
How should this be fixed?

Is restricting the value to be thrown to be `isa(value, Exception)` reasonable, or is there good reasons to allow anything to be thrown?

**Comment by JeffBezanson** [comment] 2015-01-27 19:34
We should just clarify the error message.

**Comment by IainNZ** [comment] 2015-01-27 19:36
Dupe of https://github.com/JuliaLang/julia/issues/9686

**Closed by IainNZ** 2015-01-27 19:36 UTC
Labels: error handling, test, up for grabs
