### ISSUE TITLE
lufact should allow more pivoting options? 

### ISSUE THREAD

**Issue by gwhowell** [JuliaLang/julia#10971] opened 2015-04-23 21:23 UTC
I don't see the option of column pivoting in lufact 

available in UMFPACK and in the matlab and octave sparse lu 

Using column pivoting often gives a sparser and better conditioned L 
than just using row pivoting.

**Comment by tkelman** [comment] 2015-04-24 02:33
I agree this would be quite useful. Another entry to my list in https://github.com/JuliaLang/julia/pull/10402#issuecomment-77775800 - pivoting is a more complicated subject than a boolean true/false. cc @andreasnoack

**Comment by andreasnoack** [comment] 2015-04-24 12:03
I've spent most the my time in SuiteSparse land inside CHOLMOD and SPQR so I'm not familiar with all the options in UMFPACK. I've just browsed through the sources and also looked at the MATLAB documentation and from that it is not clear to my what is requested here. @gwhowell Could you please point to a place where this is described. Preferely in the UMFPACK source or manual, but just explaining how you'd do this in MATLAB would be helpful.

**Comment by gwhowell** [comment] 2015-04-24 16:46
Hi,

My current interest is in rectangular A, then instead of the normal

equations

A^t A x = A^t b

I can work with an equivalent equation

L^t L y = z

Since L is usually quite a bit better conditioned than A, convergence
of conjugate gradient on L^t L tends to be quite a bit faster. I think
that's an easy change to make in the code (as easy as just taking out
the check for square matrices ? )

For sparse matrices the column (as well as row) pivoting L is often
better conditioned.

Here's the octave "help lu",  this syntax may be a bit cleaner than the
matlab ..
will look for that next, and perhaps code snippets that use them both.

It's great you're looking at this so quickly, wow !!


'lu' is a function from the file
/usr/lib64/octave/3.6.4/oct/x86_64-redhat-linux-gnu/lu.oct

 -- Loadable Function: [L, U] = lu (A)
 -- Loadable Function: [L, U, P] = lu (A)
 -- Loadable Function: [L, U, P, Q] = lu (S)
 -- Loadable Function: [L, U, P, Q, R] = lu (S)
 -- Loadable Function: [...] = lu (S, THRES)
 -- Loadable Function: Y = lu (...)
 -- Loadable Function: [...] = lu (..., 'vector')
     Compute the LU decomposition of A.  If A is full subroutines from
     LAPACK are used and if A is sparse then UMFPACK is used.  The
     result is returned in a permuted form, according to the optional
     return value P.  For example, given the matrix 'a = [1, 2; 3, 4]',

          [l, u, p] = lu (A)

     returns

          l =

           1.00000  0.00000
           0.33333  1.00000

          u =

           3.00000  4.00000
           0.00000  0.66667

          p =

           0  1
           1  0

     The matrix is not required to be square.
  When called with two or three output arguments and a spare input
     matrix, 'lu' does not attempt to perform sparsity preserving column
     permutations.  Called with a fourth output argument, the sparsity
     preserving column transformation Q is returned, such that 'P * A *
     Q = L * U'.

     Called with a fifth output argument and a sparse input matrix, 'lu'
     attempts to use a scaling factor R on the input matrix such that 'P
     * (R \ A) * Q = L * U'.  This typically leads to a sparser and more
     stable factorization.

     An additional input argument THRES, that defines the pivoting
     threshold can be given.  THRES can be a scalar, in which case it
     defines the UMFPACK pivoting tolerance for both symmetric and
     unsymmetric cases.  If THRES is a 2-element vector, then the first
     element defines the pivoting tolerance for the unsymmetric UMFPACK
     pivoting strategy and the second for the symmetric strategy.  By
     default, the values defined by 'spparms' are used ([0.1, 0.001]).

     Given the string argument 'vector', 'lu' returns the values of P
     and Q as vector values, such that for full matrix, 'A (P,:) = L *
     U', and 'R(P,:) * A (:, Q) = L * U'.

     With two output arguments, returns the permuted forms of the upper
     and lower triangular matrices, such that 'A = L * U'.  With one
     output argument Y, then the matrix returned by the LAPACK routines
     is returned.  If the input matrix is sparse then the matrix L is
     embedded into U to give a return value similar to the full case.
     For both full and sparse matrices, 'lu' loses the permutation
     information.

**Comment by gwhowell** [comment] 2015-04-24 17:01
Hi Andreas,

Here's the matlab help lu,  Actually the syntax looks identical to the
octave .. In addtion to a column pivot vector q, they can also have
a scaling matrix R -- specified by how many arguments you put on the
left hand side of the call (an additional argument on the right hand side
is whether to have threshold pivoting, i.e., only pivot if the threshold
is violated).  Will look next at the documentation for SuiteSparse.



 LU     LU factorization.
    [L,U] = LU(A) stores an upper triangular matrix in U and a
    "psychologically lower triangular matrix" (i.e. a product of lower
    triangular and permutation matrices) in L, so that A = L*U. A can be
    rectangular.

    [L,U,P] = LU(A) returns unit lower triangular matrix L, upper
    triangular matrix U, and permutation matrix P so that P*A = L*U.

    [L,U,p] = LU(A,'vector') returns the permutation information as a
    vector instead of a matrix.  That is, p is a row vector such that
    A(p,:) = L*U.  Similarly, [L,U,P] = LU(A,'matrix') returns a
    permutation matrix P.  This is the default behavior.

    Y = LU(A) returns the output from LAPACK'S DGETRF or ZGETRF routine if
    A is full. If A is sparse, Y contains the strict lower triangle of L
    embedded in the same matrix as the upper triangle of U. In both full
    and sparse cases, the permutation information is lost.

    [L,U,P,Q] = LU(A) returns unit lower triangular matrix L, upper
    triangular matrix U, a permutation matrix P and a column reordering
    matrix Q so that P*A*Q = L*U for sparse non-empty A. This uses UMFPACK
    and is significantly more time and memory efficient than the other
    syntaxes, even when used with COLAMD.

    [L,U,p,q] = LU(A,'vector') returns two row vectors p and q so that
    A(p,q) = L*U.  Using 'matrix' in place of 'vector' returns permutation
    matrices.

    [L,U,P,Q,R] = LU(A) returns unit lower triangular matrix L, upper
    triangular matrix U, permutation matrices P and Q, and a diagonal
    scaling matrix R so that P*(R\A)*Q = L*U for sparse non-empty A.
    This uses UMFPACK as well.  Typically, but not always, the row-scaling
    leads to a sparser and more stable factorization.  Note that this
    factorization is the same as that used by sparse MLDIVIDE when
    UMFPACK is used.

    [L,U,p,q,R] = LU(A,'vector') returns the permutation information in two
    row vectors p and q such that R(:,p)\A(:,q) = L*U.  Using 'matrix'
    in place of 'vector' returns permutation matrices.

    [L,U,P] = LU(A,THRESH) controls pivoting in sparse matrices, where
    THRESH is a pivot threshold in [0,1].  Pivoting occurs when the
    diagonal entry in a column has magnitude less than THRESH times the
    magnitude of any sub-diagonal entry in that column.  THRESH = 0 forces
    diagonal pivoting.  THRESH = 1 is the default.

    [L,U,P,Q,R] = LU(A,THRESH) controls pivoting in UMFPACK.  THRESH is a
    one or two element vector which defaults to [0.1 0.001].  If UMFPACK
    selects its unsymmetric pivoting strategy, THRESH(2) is not used. It
    uses its symmetric pivoting strategy if A is square with a mostly
    symmetric nonzero structure and a mostly nonzero diagonal.  For its
    unsymmetric strategy, the sparsest row i which satisfies the criterion
    A(i,j) >= THRESH(1) * max(abs(A(j:m,j))) is selected.  A value of 1.0
    results in conventional partial pivoting. Entries in L have absolute
    value of 1/THRESH(1) or less.  For its symmetric strategy, the diagonal
    is selected using the same test but with THRESH(2) instead.  If the
    diagonal entry fails this test, a pivot entry below the diagonal is
    selected, using THRESH(1). In this case, L has entries with absolute
    value 1/min(THRESH) or less. Smaller values of THRESH(1) and THRESH(2)
    tend to lead to sparser LU factors, but the solution can become
    inaccurate.  Larger values can lead to a more accurate solution (but
    not always), and usually an increase in the total work and memory
    usage.

    [L,U,p] = LU(A,THRESH,'vector') and [L,U,p,q,R] = LU(A,THRESH,'vector')
    are also valid for sparse matrices and return permutation vectors.
    Using 'matrix' in place of 'vector' returns permutation matrices.

    See also CHOL, ILU, QR.

    Overloaded methods:
       codistributed/lu
       gpuArray/lu
       gf/lu
       sym/lu

**Comment by andreasnoack** [comment] 2015-04-24 17:46
It is my impression (from the UMFPACK manual and MATLAB manual) that UMFPACK is defaulting to a combination of "symmetric" pivoting where both rows and columns are interchanged and traditional partial pivoting where the rows are interchanged.

To be specific, which input argument in MATLAB or Octave is activating the row pivoting that you are asking for?

**Comment by jiahao** [comment] 2015-04-24 18:33
@gwhowell please try to respect The MathWorks's copyright to the Matlab documentation. It is unclear what exactly you are referring to in the enormous block of text you have just copied.

**Comment by gwhowell** [comment] 2015-04-24 19:30
Hi,
You already have row pivoting,  what I need most is the rectangular matrices
(should be an easy fix, just don't throw out the rectangular matrices with
an if statement)

matlab and octave specify the row and column pivoting options by asking for
them in the output list

[l,u,p] = lu(a)

returns l, u, p -- p row pivot matrix so that l*u = p * a

[l,u,p] - = lu(a,"vector")

gives a permutation vector

[l,u,p,q] returns matrices p and q such that

l * u = p * a * q

Have a meeting, will look at the UMFPACK interface, hopefully Monday.


Regards,
Gary Howell

**Comment by andreasnoack** [comment] 2015-04-28 12:53
I've changed the title of this issue. It would probably be good to support more pivoting options at some point, but it is not a top priority right now.

**Comment by tkelman** [comment] 2015-05-24 02:38
I think this is still a good long-term feature request to keep open, any specific reason to close it already?

**Comment by stevengj** [comment] 2020-11-12 00:02
Closing as a duplicate of a more modern issue: #36720

**Closed by stevengj** 2020-11-12 00:02 UTC
Labels: linear algebra, sparse
