### ISSUE TITLE
Sorting broken on an edge case

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#43034] opened 2021-11-11 04:10 UTC
```jl
julia> sort(unsigned.([1,0,1,0,1,1]), rev=true)
6-element Vector{UInt64}:
 0x0000000000000001
 0x0000000000000000
 0x0000000000000001
 0x0000000000000000
 0x0000000000000001
 0x0000000000000001
```
see #42718 for why this bug exists

**Comment by vtjnash** [comment] 2021-11-11 16:29
Duplicate of https://github.com/JuliaLang/julia/pull/29576

**Comment by KristofferC** [comment] 2022-01-26 15:27
And now fixed.

**Closed by KristofferC** 2022-01-26 15:27 UTC
