### ISSUE TITLE
Julia installer says "Restart installer as Administrator to install Julia system wide" even when it is run as admin

### ISSUE THREAD

**Issue by blacklightpy** [JuliaLang/julia#37077] opened 2020-08-17 17:23 UTC
I have download the Windows Installer of Julia 1.5.0. When I run it as administrator, it shows `Restart installer as Administrator to install Julia system wide.` The default path was in %LocalAppData%/Programs

I also tried installing Julia with winget before, but wasn't able to access Julia directly from terminal as it wasn't added to PATH. I tried running winget as admin too but still no luck. The program was installed in %LocalAppData%/Programs in both cases too.

Please fix the installer to allow installing as admin.

**Comment by musm** [comment] 2020-08-17 18:58
Strange, works on my machine. Can you post more details ? Which Windows version?

**Comment by musm** [comment] 2020-08-17 18:59
Does it work when you try installing julia in non-admin mode? Also obvious thing like restarting you computer and checking again.

**Comment by blacklightpy** [comment] 2020-08-18 10:17
I'm using Windows 10, build 20185. Yeah I can install Julia without admin. I can install it as admin too, but then this message pops up and the default install path is set to the user folder. I restarted my PC but still no luck.

I read [here](https://discourse.julialang.org/t/run-as-administrator-to-install-system-wide/44465/2) yesterday that this is a message that can be ignored and the path can then be changed to install it system-wide. But it would be nice if the message is fixed because it can be misleading to newbies.

I had this issue while installing Julia 1.4.2 (the version that comes with winget) and also the current 1.5.0 release.

**Comment by musm** [comment] 2020-08-18 16:16
So the issue is that the path is not system wide when launching it as admin ? 

The title of this PR suggests you are not able to install Julia as admin? It seems that's not an issue for you.

**Comment by blacklightpy** [comment] 2020-08-19 16:50
I thought it was not possible to install Julia system wide because it kept saying restart installer as administrator to do so.

Yes, now this isn't an issue for me because I know that message can be ignored. But it's a bit misleading and can confuse new users. Could do a fix in the installer.

**Comment by musm** [comment] 2020-08-19 17:31
Can't do much about that AFAIK, otherthan distributing an Admin and non-Admin installer at the same time.

**Comment by blacklightpy** [comment] 2020-08-20 14:53
Alright, it's manageable. The Python installer does a good job at that tho, could take some reference from there.

**Comment by musm** [comment] 2020-08-20 15:31
I have a fix for this incoming

**Closed** 2020-08-24 00:49 UTC
Labels: windows

**Comment by odalet** [comment] 2021-02-16 12:49
Well, as of v1.5.3, the installer is still showing a message asking to start the installer as an Admin although I ran it as an Admin. Maybe [this line](https://github.com/JuliaLang/julia/pull/37161/files#diff-2cf0219998348287fc5f4f844547202b61d50f8c08a377855b2bbf9a1c63ff06R126) in the installer does not do a correct job of detecting administrators...
