### ISSUE TITLE
Presence of Default Argument confuses parser

### ISSUE THREAD

**Issue by dalejordan** [JuliaLang/julia#46235] opened 2022-07-31 23:31 UTC
The following function definition causes a syntax error, apparently because the default argument of `g` causes the parser to think it's an rvalue. Removing the "= 1" or adding an alpha character to after the `_` compiles ok.
```
(@v1.7) julia> foo(x) =
                   let f(y) = x + y,
                       g(_, y, z = 1) = x - y
                       (f, g)
                   end
ERROR: syntax: all-underscore identifier used as rvalue around REPL[10]:3
Stacktrace:
 [1] top-level scope
   @ REPL[10]:1
```

(@v1.7) julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_WARN_COLOR = light_red
  JULIA_INFO_COLOR = light_blue

**Comment by stevengj** [comment] 2022-08-02 14:42
The reason for the error is that
```jl
g(_, y, z = 1) = x - y
```
is lowered to
```jl
g(_, y, z) = x - y
g(_, y) = g(_, y, 1)
```
in which the second definition uses `_` as an rvalue.

**Comment by raminammour** [comment] 2022-08-02 19:18
Isn't this a duplicate of this [issue](https://github.com/JuliaLang/julia/issues/32727)?

**Comment by JeffBezanson** [comment] 2022-08-03 17:50
Yes, it's a duplicate. Thanks for finding that.
Duplicate of #32727

**Closed by JeffBezanson** 2022-08-03 17:50 UTC
Labels: bug, lowering
