### ISSUE TITLE
JuMP crashes Julia 1.8.0 Beta-3 on M1

### ISSUE THREAD

**Issue by ixzh** [JuliaLang/julia#44824] opened 2022-04-01 11:39 UTC
When running:
```julia
     using JuMP, Cbc 
     m=Model(Cbc.Optimizer)
```
I got this error:
```
julia(17828,0x100220580) malloc: *** error for object 0xe00000000000000: pointer being freed was not allocated
julia(17828,0x100220580) malloc: *** set a breakpoint in malloc_error_break to debug
```

It works on Julia 1.7.2 though. 

1.8.0 beta3 info:
```
Julia Version 1.8.0-beta3
Commit 3e092a2521 (2022-03-29 15:42 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
```

My 1.7.2 info:
```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, westmere)
```

How can I resolve this?

**Comment by staticfloat** [comment] 2022-04-04 16:41
Please post a minimal reproducer script and `Manifest.toml` that can be used to instantiate and showcase the issue.

**Comment by ixzh** [comment] 2022-04-04 18:42
> Please post a minimal reproducer script and `Manifest.toml` that can be used to instantiate and showcase the issue.

Hi I have updated the issue description above. Hope it is clear this time!

**Comment by gbaraldi** [comment] 2022-04-04 20:18
I can repro and get a backtrace to `libClp.1.14.6.dylib ClpModel::~ClpModel()`. This might be an upstream bug on the solver, but I'm not very familiar with them to go further. This issue should probably go on the [Clp.jl repo](https://github.com/jump-dev/Clp.jl)

**Comment by KristofferC** [comment] 2022-04-22 12:29
M1 is tier 3 and therefore is not release blocking.

**Comment by ViralBShah** [comment] 2022-10-15 15:55
Please reopen if still an issue.

**Comment by ianfiske** [comment] 2022-10-25 11:35
I confirmed that the exact MWE above triggers the same crash on a new M1 on Julia 1.8.2.  Also with using Clp instead of Cbc.  I cannot reopen since I am not the OP.  Should I create a new issue.

**Comment by ViralBShah** [comment] 2022-10-25 12:06
Is this using Rosetta?

**Comment by ViralBShah** [comment] 2022-10-25 12:52
It's most likely a bug in how those libraries are built, or they need rebuilding. @odow Could you suggest if this is a Julia issue or a library issue, and if so what is the right place to file this? Maybe these libraries just need to be rebuilt with a newer toolchain? Seems like a lot has improved on the M1 front since Dec 2021 when these were last built:

https://github.com/JuliaBinaryWrappers/Clp_jll.jl/releases/tag/Clp-v100.1700.601%2B0

**Comment by gbaraldi** [comment] 2022-10-25 13:04
I'm not sure this has ever worked on aarch64-macos

**Comment by ViralBShah** [comment] 2022-10-25 13:05
Ah the 1.7.2 is actually on Intel.

**Comment by ViralBShah** [comment] 2022-10-25 13:31
Yeah, it makes sense to make a new build.

**Comment by ianfiske** [comment] 2022-10-25 13:55
There is also this https://github.com/jump-dev/Clp.jl/issues/131 and that's probably this should be kept if this is not a Julia issue.  Thank you for looking at this though @ViralBShah .

**Comment by ViralBShah** [comment] 2022-10-25 13:56
Great. Let's close this in favour of that one. I'll chime in there.

**Closed by ViralBShah** 2022-10-25 13:56 UTC
Labels: apple silicon

**Comment by odow** [comment] 2022-10-25 19:53
Cbc and Clp are known to fail on M1: https://github.com/jump-dev/Clp.jl/issues/131. 

@ixzh: use HiGHS.jl instead.
