### ISSUE TITLE
Possible licensing issue with openssl?

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10763] opened 2015-04-07 17:51 UTC
Inspired by https://github.com/JuliaWeb/Roadmap/issues/5#issuecomment-84493845, I wanted to check here. Since Julia uses libgit2, which is in turn built using OpenSSL, are we OK with using OpenSSL derivatives elsewhere within Julia or are there licensing issues with the dual-licensed OpenSSL stuff?

If there _are_ licensing issues associated with the use of OpenSSL in Julia, does Julia's reliance on libgit2 (and libgit2's reliance on OpenSSL) pose any problem?

(Bottom line: I'd love to be able to use OpenSSL within Julia without having to worry about license restrictions / violations. IANAL. Please tell me how to do this.)

**Comment by jiahao** [comment] 2015-04-07 17:54
Julia does _not_ currently use libgit2.

**Comment by tkelman** [comment] 2015-04-07 18:07
But we bundle it in the nightly binaries at the moment. Along with its dependencies. And we have a trivial "did it build correctly" test for it.

**Comment by sbromberger** [comment] 2015-04-07 18:16
I did a quick grep through the source:

```
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:../include/git2/sys/openssl.h
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:hash/hash_openssl.h
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:../src/hash/hash_openssl.h
deps/libgit2-0.22.0/build/CMakeFiles/git2.dir/C.includecache:../src/hash/hash_openssl.h
```

and in the travis build that just finished for a PR I submitted:

```
cd libgit2-0.22.0/build/ && \
	cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/home/travis/build/JuliaLang/julia/usr -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_COMPILER="gcc" -DCMAKE_CXX_COMPILER="g++" -DTHREADSAFE=ON
...
-- checking for module 'openssl'
--   package 'openssl' not found
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1..1")
...
/usr/bin/gcc  -Dgit2_EXPORTS -DOPENSSL_SHA1 -DGIT_SSL -DGIT_THREADS -D_FILE_OFFSET_BITS=64 -DGIT_ARCH_32 -DCLAR_FIXTURE_PATH=\"/home/travis/build/JuliaLang/julia/deps/libgit2-0.22.0/tests/resources/\" -DCLAR_RESOURCES=\"\" -DCLAR_TMPDIR=\"libgit2_tests\" -D_GNU_SOURCE -Wall -Wextra  -fvisibility=hidden -fPIC -Wno-missing-field-initializers -Wstrict-aliasing=2 -Wstrict-prototypes -Wdeclaration-after-statement -Wno-unused-function -O3 -DNDEBUG -fPIC -I/home/travis/build/JuliaLang/julia/deps/libgit2-0.22.0/src -I/home/travis/build/JuliaLang/julia/deps/libgit2-0.22.0/include -I/home/travis/build/JuliaLang/julia/deps/libgit2-0.22.0/deps/http-parser -I/home/travis/build/JuliaLang/julia/deps/libgit2-0.22.0/tests    -o CMakeFiles/git2.dir/src/zstream.c.o   -c /home/travis/build/JuliaLang/julia/deps/libgit2-0.22.0/src/zstream.c
```

**Comment by tkelman** [comment] 2015-04-07 18:20
Also see https://github.com/JuliaLang/julia/blob/c8c967c761f0463fad6b84ca36d18832cefa5092/Makefile#L289-L293 - @staticfloat added those lines, I think because libgit2 was linking to them and otherwise the generic linux binaries would fail at dlopening libgit2 IIRC.

**Comment by tkelman** [comment] 2015-04-07 18:23
Command-line git also uses openssl, and we bundle that in the Windows binaries.
![image](https://cloud.githubusercontent.com/assets/5934628/7030289/630c2a08-dd18-11e4-8a7f-bb60da83c668.png)

Someone should check the OSX binaries which also bundle command-line git.

**Comment by jiahao** [comment] 2015-04-07 18:24
Note that libgit2 has a [special linking exception clause](https://github.com/libgit2/libgit2/blob/master/COPYING#L10-L19). Also, since we already link to other GPLed dependencies by default (like FFTW), the default distribution is already GPLed. I really don't see the cause for alarm here, other than the possible upstream licensing conflict of OpenSSL.

**Comment by sbromberger** [comment] 2015-04-07 18:29
It's precisely the licensing issue with OpenSSL that I'm struggling with. We're examining alternatives to GnuTLS for the JuliaWeb framework, and one of the reasons @keno didn't use OpenSSL initially was due to licensing concerns. I am truly hoping that there are no issues here so we can go ahead and try to implement OpenSSL in JuliaWeb without worrying about whether or not we can create bundles that are not in conflict with whatever license Julia is distributed under.

If someone authoritative can say, "OpenSSL is good to go; use it without apprehension" (and perhaps, "...but be sure to include this license text in the files...") then problem solved.

**Comment by tkelman** [comment] 2015-04-07 18:31
I would look at the precedent of what Git does. I don't believe they have such a linking exception in their license since it's not really a library the way libgit2 is, and unlike libgit2 they're the ones distributing binaries in the Windows case. We're just taking their binaries and repackaging them. Though for libgit2 and the OS X binaries, we are compiling everything from source on our buildbots and distributing the results.

**Comment by sbromberger** [comment] 2015-04-07 18:45
It actually looks like this could be Julia's decision: from http://openssl.org/support/faq.html#LEGAL2 -

> Can I use OpenSSL with GPL software?

> On many systems including the major Linux and BSD distributions, yes (the GPL does not place restrictions on using libraries that are part of the normal operating system distribution).
> On other systems, the situation is less clear. Some GPL software copyright holders claim that you infringe on their rights if you use OpenSSL with their software on operating systems that don't normally include OpenSSL.
> If you develop open source software that uses OpenSSL, you may find it useful to choose an other license than the GPL, or state explicitly that "This program is released under the GPL with the additional exemption that compiling, linking, and/or using OpenSSL is allowed." If you are using GPL software developed by others, you may want to ask the copyright holder for permission to use their  software with OpenSSL.

Again, IANAL so would appreciate guidance here.

**Comment by tkelman** [comment] 2015-04-07 18:51
Yikes. Well this is also another great motivation to move faster on the libgit2 transition. The next release should have support for using the OS' native crypto libraries on OS X and Windows (this has worked with MSVC for a while but I cleaned up and got the patch merged to make it work with MinGW as well a few weeks ago).

**Comment by JeffBezanson** [comment] 2015-04-07 18:51
The "normal operating system distribution" clause is important --- for example, one can run GPL programs on Windows where they must link against libraries that are obviously proprietary. So if you use the system-provided libopenssl on linux or BSD I'd say there is no problem.

However we have so few GPL dependencies that it would be worthwhile to try asking the copyright holders for permission to use with openssl, for other platforms.

**Comment by tkelman** [comment] 2015-04-07 18:53
> if you use the system-provided libopenssl on linux

I believe this is the case with source builds, but not our generic binaries which copy over libssl and libcrypto from the build system and bundle them. Maybe we should stop doing that?

**Comment by sbromberger** [comment] 2015-04-07 19:33
@tkelman 
> Yikes.

Why yikes? It sounds as if this frees Julia up to decide whether or not to include "This program is released under the GPL with the additional exemption that compiling, linking, and/or using OpenSSL is allowed." in its license, in which case it appears we should be all good. I guess I'm missing something.

**Comment by JeffBezanson** [comment] 2015-04-07 19:40
What we need is for our GPL dependencies to include that in their licenses. Julia itself is already fine since it's MIT licensed.

**Comment by sbromberger** [comment] 2015-04-07 19:41
Ah, I think I get it. Thanks. That seems like an awful lot of work.

**Comment by staticfloat** [comment] 2015-04-08 00:58
The reason we copy the SSL libs on the generic linux binaries is because since we build on a very old Linux system for maximum glibc compatibility, the SSL library versions are highly patched versions of old releases (So they're secure, but use an old ABI).  This means that we can't just hotswap in the system SSL libraries, since they use newer ABIs.

**Comment by ViralBShah** [comment] 2015-04-08 03:17
Cc @aviks

**Comment by StefanKarpinski** [comment] 2015-04-08 04:20
I have no idea if it's even remotely plausible, but axTLS is a BSD-licensed TLS library:

http://axtls.sourceforge.net/

**Comment by sbromberger** [comment] 2015-04-08 04:31
@stefankarpinski We're debating the merits of various packages in the JuliaWeb Roadmap repo - but I think the preference is to use one that enjoys widespread, popular support. This provides numerous security advantages essential for a package that will (hopefully) underpin secure communications within Julia.

As you can see, [there are dozens](http://en.wikipedia.org/wiki/Comparison_of_TLS_implementations) of TLS implementations, each with varying licenses. I think it would be a shame if we were forced to limit our choices because of an open source licensing issue.

**Comment by sbromberger** [comment] 2015-04-08 04:31
@stefankarpinski We're debating the merits of various packages in the JuliaWeb Roadmap repo - but I think the preference is to use one that enjoys widespread, popular support. This provides numerous security advantages essential for a package that will (hopefully) underpin secure communications within Julia.

As you can see, [there are dozens](http://en.wikipedia.org/wiki/Comparison_of_TLS_implementations) of TLS implementations, each with varying licenses. I think it would be a shame if we were forced to limit our choices because of an open source licensing issue.

**Comment by tkelman** [comment] 2015-04-08 04:31
Would have to look at it in detail, but I'm guessing it's not API-compatible the way LibreSSL is? May need some patches to libgit2 to add it as an option, but they might well be receptive.

**Comment by nalimilan** [comment] 2015-04-08 14:39
If JuliaWeb is distributed independently from Julia (users call `Pkg.add` themselves), and under a MIT license, I don't think there's a problem with it linking to OpenSSL. It would only arise for people who would like to distribute a Julia+JuliaWeb bundle including GPL components of Julia (and on platforms where OpenSSL cannot be considered as a system library). Right?

**Comment by sbromberger** [comment] 2015-04-08 14:42
@nalimilan ideally we'd standardize on one TLS library for the entire language so that the build process doesn't use one thing and the web framework another.

**Comment by ihnorton** [comment] 2015-04-15 03:56
If our license list is fully up-to-date, as far as I can tell the remaining GPL-only libraries we link are FFTW and ([maybe](https://github.com/JuliaLang/julia/issues/6131)) Rmath.

**Comment by nalimilan** [comment] 2015-04-15 09:56
Yes, but it still means that anybody willing to ship a Julia program linking to a GPL library and using SSL will be in legal trouble...

**Comment by ihnorton** [comment] 2015-04-15 13:12
I know, but if Rmath goes away and we really need OpenSSL, then getting an exception for FFTW might not be completely out of the question.

**Comment by hayd** [comment] 2015-09-23 20:36
Note that OpenSSL is an *optional* dependency to libgit2 https://github.com/libgit2/libgit2#optional-dependencies, it's unclear what that really means here/for Julia.

> OpenSSL (non-Windows) to talk over HTTPS and provide the SHA-1 functions

**Comment by tkelman** [comment] 2015-09-23 20:52
https is pretty much mandatory, building without it isnt an option

mbedtls has a more explicit license but i think it would require work with libgit2 upstream to try using it

**Comment by drbo** [comment] 2015-10-08 01:48
I know that Debian for one considers any package that has both GPL'd and OpenSSL dependencies non-redistributable.  Since current default Julia packages link to both OpenSSL (via libgit2) and to FFTW, this needs to be fixed.

**Comment by tkelman** [comment] 2015-10-08 04:26
The debian libgit2 package links against openssl. A few ways to fix this:

1. Go back to using slow command-line git on Linux.
2. Don't support https in the package manager on Linux.
3. Work with libgit2 upstream to add support for using a GPL-compatibly-licensed TLS implementation such as mbedtls or nss.
4. Do nothing - if git (which distributed openssl in their windows binaries and possibly elsewhere) hasn't gotten in trouble for this, then maybe it's not worth worrying about. IANAL.

1 and 2 are not really viable. If anyone would like to help with 3, the contribution would be welcome.

**Comment by wildart** [comment] 2015-10-08 04:40
What about linking against `libcurl`?

**Comment by tkelman** [comment] 2015-10-08 04:46
I tried that on an ubuntu system. Removed `libssl-dev`, commented out the pkg_config line from `Make.inc` (ref #12590) and my force-openssl patch from `deps/Makefile`, and installed `libcurl4-nss-dev` or `libcurl4-gnutls-dev`, neither could pass the pkg or libgit2-online tests with a rebuild of libgit2.

**Comment by wildart** [comment] 2015-10-08 05:29
We can rely on installed`libgit2`and do not build our on.

**Comment by tkelman** [comment] 2015-10-08 05:33
That would rule out any distribution that doesn't have a new enough version, unless we add in version checks and wrappers around old API's. Both libgit2 and openssl have a bunch of different API versions floating around in common use, though openssl is much more likely to already be installed - we just can't easily use multiple different versions of it from libgit2 unless we try to write some kind of compatibility shim. I suspect since crypto is involved that would not be a good idea.

**Comment by wildart** [comment] 2015-10-08 05:45
Major Linux distributions include some version of `libgit2` which would suffice for Pkg functionality (install, remove & update).

**Comment by tkelman** [comment] 2015-10-08 09:03
on centos 6, the version is 0.20.0 http://pkgs.org/centos-6/epel-x86_64/libgit2-0.20.0-2.el6.x86_64.rpm.html

Are our bindings really going to support 4 different release series simultaneously?

**Comment by nalimilan** [comment] 2015-10-08 09:20
But does it make any difference where libgit2 comes from (system vs. bundled)? I don't think Debian will accept any package that simultaneously links to libgit2 and to a GPL library (or includes GPL code), even if it uses the system libgit2.

**Comment by wildart** [comment] 2015-10-08 20:15
>  I don't think Debian will accept any package that simultaneously links to libgit2 and to a GPL library

Why not? libgit2 has GPL licence.

**Comment by simonster** [comment] 2015-10-08 20:34
I think there's some subtlety here and I'm not entirely sure if this is actually a violation. Is the Julia FFTW module part of Julia, or is Julia a "system library" for the purpose of the GPL (i.e. "a compiler used to produce the work, or an object code interpreter used to run it")? In the latter case it seems like our use of OpenSSL is probably allowed by the GPL because LibGit2 does not directly or indirectly use FFTW.

Also if Pkg is sufficiently extricated from FFTW and other GPL libs we're fine, although it's not clear whether it is already sufficiently extricated or whether additional work would be required. Certainly Pkg isn't calling FFTW, but since Pkg and FFTW could be run in the same process space the situation is still kind of unclear. A solution that would obviously be okay is to have a --no-gpl-libs command-line flag for Julia that avoids loading GPL libraries, and make Pkg operations execute in a worker process that is run with this flag.

**Comment by nalimilan** [comment] 2015-10-09 21:41
FWIW, I've just discovered Fedora considered libgit2 as a system library, which allows GPL packages to link to it: https://fedoraproject.org/wiki/Licensing:FAQ?rd=Licensing/FAQ#What.27s_the_deal_with_the_OpenSSL_license.3F

**Comment by yuyichao** [comment] 2015-10-09 21:43
I suppose you mean `considered libssl as a system library` ..... ;-p

**Comment by nalimilan** [comment] 2015-10-09 22:19
Oh, right, I've fixed it.

**Comment by hayd** [comment] 2015-10-09 23:05
Note: @wildart put together [a PR for mbedtls support in libgit2](https://github.com/libgit2/libgit2/pull/3462) (3.), which I guess will solve this issue (leaving FFTW/sparse/rmath).

**Comment by wildart** [comment] 2015-10-11 13:25
I've just finished mbedtls support PR to `libgit2`. Thus, we should be GPL compliant.

**Comment by PallHaraldsson** [comment] 2015-10-17 00:02
IINAL.

@drbo "I know that Debian for one considers any package that has both GPL'd and OpenSSL dependencies non-redistributable."

That is kind of strange (do you mean only for static linking of *both*?). The GPL allows using OpenSSL under the "system library exception" [I assume it applies, since OpenSSL is included in all variants of Debian. If some variant of Debian doesn't have OpenSSL, that would be the only reason I can see where you would have a problem OR they are thinking of that, want packages to be be cross-platform outside of the Debian/OpenSSL-using systems (we could have a way around that..).] In Windows you would have a problem.

@simonster "Is the Julia FFTW module part of Julia, or is Julia a "system library" for the purpose of the GPL (i.e. "a compiler used to produce the work, or an object code interpreter used to run it")?"

Does it matter. I guess this has something relevant to say [while details are not strictly the same with "interpreter has a license that is incompatible with the GPL"]:
http://www.gnu.org/licenses/gpl-faq.html#InterpreterIncompat

See also:
[Not sure they would view GPL-incompatible as harshly as "non-free"..]

Can I release a non-free program that's designed to load a GPL-covered plug-in?
http://www.gnu.org/licenses/gpl-faq.html#NFUseGPLPlugins


If you have Julia installed as a runtime (with GPL code say the FFTW), then a user using Julia can use it with *his* GPL-incompatible code (it's not about what you do privately); and then distribute (outside his organization) his program - *without* the Julia runtime+FFTW, under the system library exception (it would seem) to someone with same setup at least and *I guess* also when not, as Julia could have been preinstalled.. But do we want to rely on that, since we want to make static binaries possible including the Julia runtime?

If licences are incompatible you can still distribute as "mere aggregation" (that I'm just not sure will fly for Julia's case). See links above (and the FAQ in full), about all restrictions. I'm sure Debian is not more restrictive than that.

**Comment by wildart** [comment] 2015-10-18 01:29
My mbedTLS backend PR is not going to be accepted. So if there is any solution, it would need mbedTLS to be bundled into a binary distro.

**Comment by tkelman** [comment] 2015-10-18 01:31
We can do that. I can handle the build system parts. Would it be simpler using the stream API that was proposed in the other libgit2 PR?

**Comment by wildart** [comment] 2015-10-18 01:34
It would look similar to what `mbedTLS.jl` is doing for `HttpServer.jl`.

**Closed** 2016-09-26 21:18 UTC
