### ISSUE TITLE
Incorrect behavior of length(“\0\uff”)

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#10957] opened 2015-04-23 14:38 UTC
This returns 0, and is not consistent with:
length(“\0q”) -> 2
length(utf16(“\0q”) -> 2
length(utf32(“\0q”) -> 2
length(utf16(“\0\uff) -> 2

**Comment by jiahao** [comment] 2015-04-23 15:23
I suspect this is the root cause of #10958. Closing as duplicate.

@ScottPJones your editor tries to convert input into smart quotes, which makes it hard to copy-paste code into the REPL for testing.

Also, please look at GitHub's triple-backtick syntax for encasing code snippets.

**Closed by jiahao** 2015-04-23 15:23 UTC

**Comment by pao** [comment] 2015-04-23 15:27
> Also, please look at GitHub's triple-backtick syntax for encasing code snippets.

https://guides.github.com/features/mastering-markdown/ (Examples section, click "Code")
