### ISSUE TITLE
Pkg.update() extremely slow on windows.

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#9791] opened 2015-01-15 17:31 UTC
On my windows machine:
```
julia> @time Pkg.update()
INFO: Updating METADATA...
INFO: Updating Autoreload...
INFO: Updating Images...
INFO: Computing changes...
INFO: No packages to install, update or remove
elapsed time: 340.298214242 seconds (886894024 bytes allocated, 0.21% gc time)
```
Nearly six minutes. Ouch!

This is with a fresh build from master within the last hour, but it's been an issue for a while now.

**Comment by simonster** [comment] 2015-01-15 17:41
This will be fixed when we switch to libgit2 (#7584). Otherwise I'm not sure if there's anything we can do. In my experience launching processes on Windows is much slower than on *nix platforms, and that's presumably the bottleneck here, as it was on Linux before JuliaLang/libuv#24.

**Closed** 2015-01-15 18:12 UTC

**Comment by tkelman** [comment] 2015-01-15 23:17
Part of the problem is if you have many packages installed, the `@async` blocks are launching dozens of git processes simultaneously, completely locking (and often overheating) my machine. If we could mitigate that to cap to `CPU_CORES` processes at a time, I think it would be worth doing. The libgit2 transition has so far been the slowest-moving of any of the 0.4 targets.

**Comment by sbohora** [comment] 2017-03-15 16:32
This is still the same problem that `Pkg.add()` is too slow. Has this issue been fixed in JuliaPro 0.5.1.1? Thanks.

**Comment by KristofferC** [comment] 2017-03-15 16:47
A non official way is to try out https://github.com/KristofferC/Pkg25.jl and see if it helps.

**Comment by twadleigh** [comment] 2017-03-15 17:16
Moving to libgit2 didn't bring much improvement that I could tell. AV also appears to hugely exacerbate the problem (based on my own anecdotal experience between the two windows machines that I use: one with AV, one without).
