### ISSUE TITLE
Performance regression when recursively traversing nested types.

### ISSUE THREAD

**Issue by racinmat** [JuliaLang/julia#40302] opened 2021-04-01 21:31 UTC
When digging into #40282  I discovered one dependency, https://github.com/CTUAvastLab/HierarchicalUtils.jl suffers from performance regression in some cases. From that I extracted following code
```julia
using Pkg
pkg"activate ."
pkg"precompile"
using OrderedCollections: OrderedDict
using BenchmarkTools
abstract type NodeType end
struct LeafNode <: NodeType end
struct InnerNode <: NodeType end
NodeType(::Type{T}) where T = @error "Define NodeType(::Type{$T}) to be either LeafNode() or InnerNode()"
NodeType(x::T) where T = NodeType(T)
find_traversal(n, x) = pred_traversal(n, t -> x === t)
pred_traversal(n::T, p::Function, s::String="") where T = _pred_traversal(NodeType(T), n, p, s)
_pred_traversal(::LeafNode, n, p, s="") = p(n) ? [stringify(s)] : String[]
function _pred_traversal(::InnerNode, n, p, s="")
    d = _childsort(children(n))
    l = length(d)
    res = vcat([pred_traversal(_ith_child(d, i), p, s * encode(i, l)) for i in 1:l]...)
    p(n) ? vcat(stringify(s), res) : res
end
_childsort(x::Union{Tuple, Vector, OrderedDict}) = x
function _childsort(x::NamedTuple{T}) where T
    ks = tuple(sort(collect(T))...)
    NamedTuple{ks}(x[k] for k in ks)
end
children(n) = children(NodeType(n), n)
children(::LeafNode, _) = ()
children(_, ::T) where T = @error "Define children(n::$T) to return a collection of children (one of allowed types)"
const ALPHABET = [Char(x) for x in vcat(collect.([42:43, 48:57, 65:90, 97:122])...)]
function stringify(c::AbstractString)
    if length(c) % 6 != 0
        c = c * '0' ^ mod(6-length(c), 6)
    end
    join(ALPHABET[parse(Int, x, base=2) + 1] for x in [c[i:i+5] for i in 1:6:(length(c)-1)])
end
function _ith_child(m::Union{Tuple, Vector, NamedTuple}, i::Integer)
    return m[i]
end
_ith_child(m::OrderedDict, i::Integer) = _ith_child(collect(m), i)
_segment_width(l::Integer) = ceil(Int, log2(l+1))
encode(i::Integer, l::Integer) = string(i, base=2, pad=_segment_width(l))
abstract type AbstractVertex end
mutable struct Leaf <: AbstractVertex
    n::Int64
end
NodeType(::Type{<:Vector}) = InnerNode()
children(v::Vector) = v
noderepr(v::Vector) = isempty(v) ? "[]" : "Vector of"
NodeType(::Type{Leaf}) = LeafNode()
const LINEAR_TREE_3 = [[[[[[[Leaf(1)]]]]]]]
t = LINEAR_TREE_3
@time find_traversal(t, [t, t])
@btime find_traversal(t, [t, t])
```
which runs much slower on Julia 1.6.0.
This is output of Julia 1.5.4
```
C:\Projects\something\julia_1_6_benchmarks>"C:\Users\racinsky\AppData\Local\Programs\Julia 1.5.4\bin\julia.exe" main.jl
 Activating environment at `C:\Projects\something\julia_1_6_benchmarks\Project.toml`
Precompiling project...
  0.561740 seconds (1.76 M allocations: 91.772 MiB, 2.31% gc time)
  2.311 μs (55 allocations: 3.19 KiB)
```
and this is output of Julia 1.6.0
```
C:\Projects\something\julia_1_6_benchmarks>C:\Users\racinsky\AppData\Local\Programs\Julia-1.6.0\bin\julia.exe main.jl
┌ Warning: The Pkg REPL interface is intended for interactive use, use with caution from scripts.
└ @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\REPLMode\REPLMode.jl:378
  Activating environment at `C:\Projects\something\julia_1_6_benchmarks\Project.toml`
 16.823255 seconds (28.98 M allocations: 1.649 GiB, 1.00% gc time, 99.99% compilation time)
  8.267 μs (111 allocations: 6.61 KiB)
```

We can see it's 30x slower during the first run, and 3.5x slower on consecutive lines.

Manifest.toml and Project.toml is exactly the same for both versions.

**Comment by KristofferC** [comment] 2021-04-02 09:00
The compile-time seems to be slightly better at nightly. 11s -> 2.23 seconds for me. The runtime is still slower. I'll see if I can figure out what caused the runtime regression.

**Comment by KristofferC** [comment] 2021-04-02 12:58
I spend some time looking at this. It is kinda messy but here is some stuff:

The first big compile time increase (0.5s -> 5s) was from 258d04e8bfdb8189fd61199bccd7
The secon one (5s -> 10s) was from 51592abc99d6f
The biggest perf reduction ~factor of 2x was from fd8f97e98c93

**Comment by KristofferC** [comment] 2021-04-02 13:18
@racinmat, One possible workaround is if you can specify the return type of the 

```jl
[pred_traversal(_ith_child(d, i), p, s * encode(i, l)) for i in 1:l]
```

expression. For example, changing to:

```jl
z = Vector{Vector{String}}[pred_traversal(_ith_child(d, i), p, s * encode(i, l)) for i in 1:l]
res = vcat(z...)
```

I get (on 1.6.0):

```
  0.170358 seconds (809.41 k allocations: 41.404 MiB, 2.64% gc time)
  935.000 ns (38 allocations: 2.33 KiB)
```

which is better than you had on 1.5.0.

**Comment by racinmat** [comment] 2021-04-02 20:03
Thanks, I'll try the workaround, hopefully, it will be fixed in some future releases.

**Comment by racinmat** [comment] 2021-08-16 09:55
It seems julia 1.7 beta 3 has some improvements there:
```julia
C:\Projects\something\julia_1_6_benchmarks_mwe>C:\Users\racinsky\AppData\Local\Programs\Julia-1.7.0-beta3\bin\julia.exe main.jl
┌ Warning: The Pkg REPL mode is intended for interactive use only, and should not be used from scripts. It is recommended to use the functional API instead.
└ @ Pkg.REPLMode C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.7\Pkg\src\REPLMode\REPLMode.jl:377
  Activating project at `C:\Projects\something\julia_1_6_benchmarks_mwe`
┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ C:\Projects\something\julia_1_6_benchmarks_mwe\Manifest.toml:0
  7.704055 seconds (14.52 M allocations: 818.623 MiB, 6.49% gc time, 0.46% compilation time)
  13.800 μs (110 allocations: 5.67 KiB)
```

**Comment by racinmat** [comment] 2021-12-01 11:52
It's even better with stable 1.7.0 released yesterday
```
(base) C:\Projects\something\julia_1_6_benchmarks_mwe>"C:\Users\racinsky\AppData\Local\Programs\Julia 1.5.3\bin\julia.exe" main.jl
 Activating environment at `C:\Projects\something\julia_1_6_benchmarks_mwe\Project.toml`
Precompiling project...
  0.881549 seconds (1.78 M allocations: 92.467 MiB, 2.13% gc time)
  3.475 μs (55 allocations: 3.19 KiB)

(base) C:\Projects\something\julia_1_6_benchmarks_mwe>"C:\Users\racinsky\AppData\Local\Programs\Julia 1.5.4\bin\julia.exe" main.jl
 Activating environment at `C:\Projects\something\julia_1_6_benchmarks_mwe\Project.toml`
Precompiling project...
  0.961464 seconds (1.76 M allocations: 91.772 MiB, 1.70% gc time)
  3.062 μs (55 allocations: 3.19 KiB)

(base) C:\Projects\something\julia_1_6_benchmarks_mwe>C:\Users\racinsky\AppData\Local\Programs\Julia-1.6.0\bin\julia.exe main.jl
  Activating environment at `C:\Projects\something\julia_1_6_benchmarks_mwe\Project.toml`
 23.312357 seconds (28.98 M allocations: 1.649 GiB, 0.78% gc time, 99.99% compilation time)
  12.600 μs (111 allocations: 6.61 KiB)

(base) C:\Projects\something\julia_1_6_benchmarks_mwe>C:\Users\racinsky\AppData\Local\Programs\Julia-1.6.1\bin\julia.exe main.jl
  Activating environment at `C:\Projects\something\julia_1_6_benchmarks_mwe\Project.toml`
 29.379206 seconds (29.06 M allocations: 1.653 GiB, 0.66% gc time, 99.99% compilation time)
  13.700 μs (111 allocations: 6.61 KiB)

(base) C:\Projects\something\julia_1_6_benchmarks_mwe>C:\Users\racinsky\AppData\Local\Programs\Julia-1.6.2\bin\julia.exe main.jl
  Activating environment at `C:\Projects\something\julia_1_6_benchmarks_mwe\Project.toml`
 29.143421 seconds (29.06 M allocations: 1.653 GiB, 0.77% gc time, 99.99% compilation time)
  11.600 μs (111 allocations: 6.61 KiB)

(base) C:\Projects\something\julia_1_6_benchmarks_mwe>C:\Users\racinsky\AppData\Local\Programs\Julia-1.6.4\bin\julia.exe main.jl
  Activating environment at `C:\Projects\something\julia_1_6_benchmarks_mwe\Project.toml`
Precompiling project...
  ✓ OrderedCollections
  4 dependencies successfully precompiled in 7 seconds
  1 dependency precompiled but a different version is currently loaded. Restart julia to access the new version
 30.391447 seconds (28.93 M allocations: 1.645 GiB, 1.22% gc time, 99.98% compilation time)
  14.400 μs (115 allocations: 6.62 KiB)

(base) C:\Projects\something\julia_1_6_benchmarks_mwe>C:\Users\racinsky\AppData\Local\Programs\Julia-1.7.0-beta3\bin\julia.exe main.jl
  Activating project at `C:\Projects\something\julia_1_6_benchmarks_mwe`
  8.627650 seconds (14.52 M allocations: 818.617 MiB, 4.05% gc time, 0.40% compilation time)
  14.600 μs (110 allocations: 5.67 KiB)

(base) C:\Projects\something\julia_1_6_benchmarks_mwe>C:\Users\racinsky\AppData\Local\Programs\Julia-1.7.0\bin\julia.exe main.jl
  Activating project at `C:\Projects\something\julia_1_6_benchmarks_mwe`
Precompiling project...
  ✓ OrderedCollections
  4 dependencies successfully precompiled in 7 seconds
  1 dependency precompiled but a different version is currently loaded. Restart julia to access the new version
  4.884765 seconds (15.84 M allocations: 880.657 MiB, 5.98% gc time, 99.98% compilation time)
  19.300 μs (126 allocations: 5.91 KiB)
```

**Comment by racinmat** [comment] 2022-04-05 11:26
I used the
```julia
z = Vector{String}[pred_traversal(_ith_child(d, i), p, s * encode(i, l)) for i in 1:l]
res = isempty(z) ? String[] : reduce(vcat, z)
```
it got the same time, the time difference between the 1.5 and 1.6 and newer is negligible now, thanks.

In https://github.com/CTUAvastLab/HierarchicalUtils.jl/pull/11 this fix lead to time of running tests in CI from 21 minutes to 15 minutes.

**Comment by vtjnash** [comment] 2023-08-24 19:56
Looks fixed on master
```
julia> @time find_traversal(t, [t, t])
  0.445210 seconds (909.63 k allocations: 62.740 MiB, 99.91% compilation time)
String[]

julia> @btime find_traversal(t, [t, t])
  2.500 μs (47 allocations: 2.03 KiB)
```
where v1.10 was
```
julia> @time find_traversal(t, [t, t])
  0.789709 seconds (2.00 M allocations: 127.607 MiB, 11.01% gc time, 99.95% compilation time)
String[]

julia> @btime find_traversal(t, [t, t])
  11.450 μs (134 allocations: 8.05 KiB)
String[]
```

**Closed** 2023-08-24 19:55 UTC
Labels: performance, regression, latency
