### ISSUE TITLE
REPL cursors is misaligned when pasting code with tabs

### ISSUE THREAD

**Issue by fbruetting** [JuliaLang/julia#18543] opened 2016-09-16 14:43 UTC
When I paste tab containing code to the REPL, the cursor isn't at the right position. So when the cursor blinks at e.g. the 5th character, text editing is actually done at the 7th character of the REPL.

**Comment by Keno** [comment] 2016-09-16 16:47
We should replace tabs by spaces in bracketed paste mode.

**Comment by KristofferC** [comment] 2016-09-16 20:39
What terminal?

**Comment by fb87** [comment] 2016-09-16 21:11
Gnome Terminal with bash, but does that matter?

**Comment by rfourquet** [comment] 2017-10-08 13:53
It seems fixed now, in `bracketed_paste` in "Base/repl/LineEdit.jl", and I cannot reproduce the bug. Closing for now, @fbruetting can you confirm this is fixed for you?

**Closed by rfourquet** 2017-10-08 13:53 UTC
Labels: REPL

**Comment by fbruetting** [comment] 2017-10-08 16:52
Yes, I recognized it. But by how many spaces are tabs getting replaced? Is this configurable?

**Comment by rfourquet** [comment] 2017-10-08 17:34
> But by how many spaces are tabs getting replaced? Is this configurable?

It's defined in `Base.LineEdit.tabwidth = 8`, it's a global so not configurable, but would be easy (if you like I can do it).

**Comment by fbruetting** [comment] 2017-10-08 17:39
Would be really cool if we could also set 4 spaces, which is also pretty commen and leads to a better screen utilization on laptops! ;)

**Comment by fbruetting** [comment] 2017-11-02 01:53
Ping… :)

**Comment by rfourquet** [comment] 2017-12-06 11:01
@fbruetting see #24940, once it's meged, you can put this in your .juliarc.jl:
```julia
atreplinit() do repl
    repl.options = Base.REPL.Options(tabwidth=4)
end
```
Or at the REPL:
```
julia> Base.active_repl.options.tabwidth=4
```
