### ISSUE TITLE
Method definition warning that only shows up on Windows

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#18769] opened 2016-10-02 22:36 UTC
On windows

``` julia
> julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> *{T}(x::Int, ::Type{T}) = T(x)
ERROR: error in method definition: function Base.* must be explicitly imported to be extended
```

However on Linux I don't see this warning

**Comment by yuyichao** [comment] 2016-10-02 23:02
Somehow the REPL uses `*` only on windows?

**Comment by vtjnash** [comment] 2016-10-02 23:02
This is caused by our default `contrib/windows/juliarc.jl` file (adding `JULIA_HOME` to `ENV["PATH"]`)

**Comment by yuyichao** [comment] 2016-10-02 23:05
So is there anything to fix here?

**Comment by StefanKarpinski** [comment] 2016-10-03 16:55
Don't make that sketchy method overload for `*`?

**Comment by yuyichao** [comment] 2016-10-03 17:00
I.e. close as user error? (Julia doesn't override anything.)

**Comment by musm** [comment] 2017-04-24 23:29
@vtjnash why exactly does windows need https://github.com/JuliaLang/julia/blob/master/contrib/windows/juliarc.jl
also if we do something like ` "$(JULIA_HOME);$(ENV["PATH"])"` will that not fix the issue?

**Comment by TotalVerb** [comment] 2017-04-24 23:32
That'll just move the issue to `string` instead of `*`.

**Comment by musm** [comment] 2017-04-24 23:36
...sigh....I thought I found a loophole

**Comment by vtjnash** [comment] 2017-04-24 23:50
I guess because we've always done it that way (https://github.com/JuliaLang/julia/commit/79dd2186e3393efe416518a9d18a6e5c4fcd17c6), and nobody has questioned or tested it since?

**Comment by musm** [comment] 2017-04-24 23:59
I just deleted the juliarc.jl that shipped with the binaries in /etc/julia  and ran julia ... no problems there 
@tkelman  do you see any problems with deleting the file?

**Comment by vtjnash** [comment] 2017-04-25 00:02
Does WinRPM still work?

**Comment by musm** [comment] 2017-04-25 00:08
doesn't look like it will work
```julia
ERROR: could not spawn `7z x -y 'C:\Users\Mus\.julia\v0.6\WinRPM\cache\4\noarch%2Fmingw64-liblzma5-5.0.4-9.22.noarch.rpm' '-oC:\Users\Mus\.julia\v0.6\WinRPM\cache\4'`: no such file or directory (ENOENT)
Stacktrace:
 [1] _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::Base.DevNullStream, ::Base.PipeEndpoint, ::Base.TTY) at .\process.jl:365
 [2] #373 at .\process.jl:517 [inlined]
 [3] setup_stdio(::Base.##373#374{Cmd}, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}) at .\process.jl:503
 [4] #spawn#372(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}) at .\process.jl:516
 [5] spawn(::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.TTY}) at .\process.jl:511
 [6] open(::Cmd, ::String, ::Base.DevNullStream) at .\process.jl:583
 [7] do_install(::WinRPM.Package) at C:\Users\Mus\.julia\v0.6\WinRPM\src\WinRPM.jl:465
 [8] do_install(::WinRPM.Packages{Array{LibExpat.ETree,1}}) at C:\Users\Mus\.julia\v0.6\WinRPM\src\WinRPM.jl:443
 [9] #install#21(::Bool, ::Function, ::WinRPM.Package) at C:\Users\Mus\.julia\v0.6\WinRPM\src\WinRPM.jl:387
 [10] (::WinRPM.#kw##install)(::Array{Any,1}, ::WinRPM.#install, ::WinRPM.Package) at .\<missing>:0
 [11] install(::String) at C:\Users\Mus\.julia\v0.6\WinRPM\src\WinRPM.jl:359
```

**Comment by vtjnash** [comment] 2017-04-25 00:11
OK – it looks like that'll need a PR first then

**Comment by musm** [comment] 2017-04-25 00:17
So it's only because WinRPM needs `7z`, @tkelman  would you  have any objects to changing WinRPM to instead look for 7z using the `JULIA_HOME` variable instead ?

**Comment by tkelman** [comment] 2017-04-25 00:35
We shouldn't be messing with this kind of thing until after branching

**Comment by musm** [comment] 2017-04-28 14:19
how about we remove  the `won't fix` bit since #21540 will fix this  ;)

**Comment by StefanKarpinski** [comment] 2017-04-28 19:10
Sure, although there's not harm in fixing a "won't fix" issue either :)

**Comment by musm** [comment] 2017-06-17 17:12
could we reopen until  https://github.com/JuliaLang/julia/pull/21540 is merged so we don't lose track (note the  pr has been ready for sometime now)?

**Comment by musm** [comment] 2017-07-07 22:48
Anyone mind taking a look at  #21540   ?  it's been ready since May, thanks!

**Closed** 2017-08-03 18:50 UTC
Labels: windows
