### ISSUE TITLE
Weird result of expression substitution in REPL

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#9705] opened 2015-01-10 04:23 UTC
The result is different if the expression is the only thing

```julia
julia> a = :a
:a

julia> :($a)
:($(Expr(:$, :a)))

julia> ans
:($(Expr(:$, :a)))

julia> ex = :($a)
:a

julia> ans
:a

julia> let
       :($a)
       end
:a

julia> begin
       :($a)
       end
:a
```

Is this a (confusing) feature or a bug?

**Comment by jakebolewski** [comment] 2015-01-10 05:09
Dupe of #9600

**Closed by jakebolewski** 2015-01-10 05:09 UTC
