### ISSUE TITLE
Inference failure when splatting a number

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#19957] opened 2017-01-10 00:05 UTC
Minimal reproducible example:
```julia
julia> immutable MyFunc{F}
               func::F
          end

julia> (f::MyFunc{F}){F}(x) = f.func(x...)

julia> f = MyFunc(x -> 1 + x)
MyFunc{##15#16}(#15)

julia> f((1,))
2

julia> g(f, x) = f(x...)
g (generic function with 1 method)


julia> @code_warntype g(f, (1,))
Variables:
  #self#::#g
  f::MyFunc{##15#16}
  x::Tuple{Int64}

Body:
  begin
      return (Core._apply)((Core.getfield)(f::MyFunc{##15#16},:func)::##15#16,(Core.getfield)(x::Tuple{Int64},1)::Int64)::Any
  end::Any
```

cc @jrevels

**Comment by yuyichao** [comment] 2017-01-10 00:31
It's due to splatting of a number and not a tuple.

```jl
julia> f(x) = (x...)
@f (generic function with 1 method)

julia> @code_warntype f(1)
Variables:
  #self#::#f
  x::Int64

Body:
  begin 
      return (Core._apply)(Core.tuple,x::Int64)::Tuple
  end::Tuple

julia> f(1)
(1,)
```

**Comment by yuyichao** [comment] 2017-01-10 00:38
And this seems to be caused by the special handling of `Core._apply` not being able to handle scalar input (or generic iterables). Handling of generic iterables with compile time known size might be useful although it seems non-trivial....

**Comment by vtjnash** [comment] 2017-01-10 01:13
would be fixed by https://github.com/JuliaLang/julia/pull/12579 then?

**Comment by yuyichao** [comment] 2017-01-10 01:17
Sort of. Although it doesn't infer the length?

**Comment by indexfrom0** [comment] 2017-01-10 03:40
splat splat splitty splat #inferencefailure

**Comment by JeffBezanson** [comment] 2017-01-10 17:23
As long as numbers are iterable (which, most likely, they will continue to be) it's worth adding handling for this to `_apply` inference.

**Comment by dpsanders** [comment] 2017-05-27 00:46
This has now been fixed:
```
julia> @code_warntype g(f, (1,))
Variables:
  #self#::#g
  f::#f
  x::Tuple{Int64}

Body:
  begin
      return (Core.tuple)((Core.getfield)(x::Tuple{Int64}, 1)::Int64, 1)::Tuple{Int64,Int64}
  end::Tuple{Int64,Int64}
```

**Comment by tkelman** [comment] 2017-05-27 01:05
could use a test

**Comment by dpsanders** [comment] 2017-05-27 01:06
Good point.

**Comment by tkelman** [comment] 2017-05-27 01:10
a partial related test was added in #20343, but it looks a bit different?

**Comment by mbauman** [comment] 2018-12-10 22:54
Does this really just need a test in order to close it?

**Comment by StefanKarpinski** [comment] 2018-12-10 23:11
![@kshyatt](https://user-images.githubusercontent.com/153596/49767589-0a755600-fca7-11e8-95e5-60811aa1e5a1.jpg)

**Closed** 2019-01-04 16:56 UTC
Labels: good first issue, inference
