### ISSUE TITLE
Error compiling master on OS X Yosemite

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#8937] opened 2014-11-08 03:03 UTC
With a fresh clone of commit 8cbf07940a0b, having installed `cmake` with `brew install cmake`, I get the following error (tried yesterday and today with fresh clones):
```
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _git_path_iconv in path.c.o
  "_libiconv_close", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_clear in path.c.o
      _git_path_dirload in path.c.o
  "_libiconv_open", referenced from:
      _git_path_direach in path.c.o
      _git_path_iconv_init_precompose in path.c.o
      _git_path_dirload in path.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [libgit2.0.21.2.dylib] Error 1
make[4]: *** [CMakeFiles/git2.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [libgit2-0.21.2/build/libgit2.dylib] Error 2
make[1]: *** [julia-release] Error 2
make: *** [release] Error 2
```

**Comment by ViralBShah** [comment] 2015-01-02 06:11
I think people usually keep these things updated, especially if you are trying to build julia. Is it necessary to say so? I am neutral on the matter.

In this case, @dpsanders had installed fink for something and forgotten about it, and it is unlikely that such a thing in the documentation may have alerted him to it being the cause of the build failure.

I think we can close this one.

**Closed** 2015-04-16 19:00 UTC
Labels: doc
