### ISSUE TITLE
Warning when "nothing" is included in a log message

### ISSUE THREAD

**Issue by samtkaplan** [JuliaLang/julia#28914] opened 2018-08-27 11:58 UTC
In Julia 0.7.0, the following code produces a deprecation warning.

```julia
x = nothing
@info "x=$x"
```

The output is:
```
┌ Warning: Calling `print` on `nothing` is deprecated; use `show`, `repr`, or custom output instead.
│   caller = #print_to_string#330(::Nothing, ::Function, ::Nothing) at io.jl:124
└ @ Base .\strings\io.jl:124
[ Info: x=nothing
```

I am filing this issue because I am assuming that the log message `x=$x` should be valid syntax for Julia 0.7 and 1.0.  If not, please feel free to close this.  Thanks!

**Comment by ararslan** [comment] 2018-08-28 02:17
This is indeed intended behavior, introduced in #27829, so I'll go ahead and close this.

**Closed by ararslan** 2018-08-28 02:17 UTC
