### ISSUE TITLE
Format 2-digit Year in Date Missing Centuries

### ISSUE THREAD

**Issue by versipellis** [JuliaLang/julia#30590] opened 2019-01-04 15:58 UTC
Using the `Dates` modules, when formatting an existing date, if the "year" field is only two digits long, it parses out missing the centuries. For example:

```
> Date("01/01/19","mm/dd/yy")
0019-01-01
```

**Comment by yuyichao** [comment] 2019-01-04 16:00
So do you want 2019 or 1919?

**Comment by versipellis** [comment] 2019-01-04 16:09
2019. Alternatively, I imagine there could be a secondary argument which
specified the base century "2000" or "1900" for either "2019" or "1919".

**Comment by iamed2** [comment] 2019-01-04 19:00
I think if anything it should default to the current century. Or the nearest year to the current year.

Python's `strptime` has some weird behaviour:

| digits | year |
|-------|-----|
| 19 | 2019 |
| 00 | 2000 |
| 68 | 2068 |
| 69 | 1969 |

**Comment by davidanthoff** [comment] 2019-01-04 20:00
I think this is a duplicate of https://github.com/JuliaLang/julia/issues/30002.

**Closed** 2019-01-04 20:19 UTC
Labels: dates
