### ISSUE TITLE
Ghost package

### ISSUE THREAD

**Issue by samuela** [JuliaLang/julia#12206] opened 2015-07-18 19:57 UTC
I have somehow managed to install the Distributions package without having any trace of it on my system. I'm on v0.3.8. For example, 

```julia
julia> using Distributions # works

julia> Pkg.status()
2 required packages:
 - CPUTime                       0.0.4
 - MAT                           0.2.12
7 additional packages:
 - BinDeps                       0.3.14
 - Blosc                         0.1.2
 - Compat                        0.4.9
 - HDF5                          0.4.18
 - SHA                           0.0.4
 - URIParser                     0.0.5
 - Zlib                          0.1.8

julia> Pkg.installed()
Dict{ASCIIString,VersionNumber} with 9 entries:
  "Blosc"     => v"0.1.2"
  "Zlib"      => v"0.1.8"
  "CPUTime"   => v"0.0.4"
  "BinDeps"   => v"0.3.14"
  "Compat"    => v"0.4.9"
  "HDF5"      => v"0.4.18"
  "MAT"       => v"0.2.12"
  "SHA"       => v"0.0.4"
  "URIParser" => v"0.0.5"

julia> Pkg.dir("Distributions")
"/home/skainswo/.julia/v0.3/Distributions"

shell> ls /home/skainswo/.julia/v0.3/
BinDeps/   .cache/     CPUTime/    MAT/        REQUIRE     URIParser/
Blosc/     Compat/     HDF5/       METADATA/   SHA/        Zlib/
```

What's the deal?

**Comment by yuyichao** [comment] 2015-07-18 20:03
Everything you've shown seems to be coherent. `Pkg.dir` doesn't check the existance of the directory IIRC. (and the existance of the result directory is used by some packages to test whether certain packages are installed)

**Comment by samuela** [comment] 2015-07-18 20:06
@yuyichao So where is Distributions installed then?

**Comment by yuyichao** [comment] 2015-07-18 20:08
Ahh. Sorry. I missed the first line.

What's `LOAD_PATH` and is it in there?

**Comment by samuela** [comment] 2015-07-18 20:12
@yuyichao Ah, here we go!

```julia
julia> LOAD_PATH
4-element Array{Union(UTF8String,ASCIIString),1}:
 ""                                                                                    
 "/contrib/projects/julia/packages/v0.3"                                               
 "/gpfs/main/sys/shared/psfu/contrib/projects/julia/v0.3.8/local/share/julia/site/v0.3"
 "/gpfs/main/sys/shared/psfu/contrib/projects/julia/v0.3.8/share/julia/site/v0.3"      

shell> ls /contrib/projects/julia/packages/v0.3/Distributions/
doc/  LICENSE.md  NEWS.md  perf/  README.md  REQUIRE  src/  test/
```

So, really the issue here is that `Pkg.{installed, status, dir}` are wrong.

**Comment by yuyichao** [comment] 2015-07-18 20:13
Yeah. That's a known issue. Having all of my package installed system-wise, I'm seeing similar issues from time to time.

Close as duplicate of https://github.com/JuliaLang/julia/issues/8679

**Comment by samuela** [comment] 2015-07-18 20:14
Great, thanks for your help!

**Closed by yuyichao** 2015-07-18 20:13 UTC
