### ISSUE TITLE
Error message for variable with same name as function could be more explicit

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaLang/julia#35126] opened 2020-03-16 12:02 UTC
```
julia> f(x) = 2
f (generic function with 1 method)

julia> let
       f = f(2)
       end
ERROR: UndefVarError: f not defined
Stacktrace:
 [1] top-level scope at REPL[7]:2
```

**Comment by StefanKarpinski** [comment] 2020-03-16 13:21
The outer function definition is a red herring here though. The issue is that inside of the let block it's an undefined local variable and you're accessing it before it's defined.

**Comment by antoine-levitt** [comment] 2020-03-16 13:44
Sure, the problem is that the variable shadows the function name. If I write `g = f(2)` I'm fine, and if I write `f = g(2)` it's OK too, it's just this particular conflicting case that's a bit tricky to find out. This is pretty frequent in numerical code, when you use `quantity(x)` as a function that computes `quantity`, and so you want to do `quantity = quantity(x); quantity + quantity^2` or something.

**Comment by antoine-levitt** [comment] 2020-03-16 13:44
To clarify: I know this is invalid code and I understand why julia is giving this message, I just wish it could be more helpful

**Comment by vtjnash** [comment] 2020-03-16 13:54
Duplicate of #17062

**Closed** 2023-11-08 17:24 UTC
Labels: error messages
