### ISSUE TITLE
Deprecation warning printed every time

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#21648] opened 2017-04-30 02:31 UTC
```jl
WARNING: Array{T, N}(::Type{T}, d::NTuple{N, Int}) is deprecated, use Array{T}(d) instead.
```
is printed every time.

**Comment by yuyichao** [comment] 2017-04-30 02:43
What's the code to reproduce?

**Comment by dpsanders** [comment] 2017-04-30 02:48
Here's the backtrace. This is from using master of `Plots.jl` with a user-defined type. I'll try to find a MWE.
```jl
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:64
 [2] Array(::Type{ColorTypes.RGBA{Float64}}, ::Tuple{Int64}) at ./deprecated.jl:51
 [3] plot_color(::Array{ColorTypes.RGB{FixedPointNumbers.Normed{UInt8,8}},1}) at /Users/dpsanders/.julia/v0.6/PlotUtils/src/colors.jl:24
 [4] generate_colorgradient(::ColorTypes.RGBA{Float64}) at /Users/dpsanders/.julia/v0.6/PlotUtils/src/color_utils.jl:51
 [5] get_color_palette(::Symbol, ::ColorTypes.RGBA{Float64}, ::Int64) at /Users/dpsanders/.julia/v0.6/PlotUtils/src/color_utils.jl:65
 [6] _update_subplot_colors(::Plots.Subplot{Plots.GRBackend}) at /Users/dpsanders/.julia/v0.6/Plots/src/args.jl:1073
 [7] _update_subplot_args(::Plots.Plot{Plots.GRBackend}, ::Plots.Subplot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Int64, ::Bool) at /Users/dpsanders/.julia/v0.6/Plots/src/args.jl:1159
 [8] _subplot_setup(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Array{Dict{Symbol,Any},1}) at /Users/dpsanders/.julia/v0.6/Plots/src/pipeline.jl:291
 [9] _plot!(::Plots.Plot{Plots.GRBackend}, ::Dict{Symbol,Any}, ::Tuple{Array{IntervalArithmetic.IntervalBox{2,Float64},1}}) at /Users/dpsanders/.julia/v0.6/Plots/src/plot.jl:199
 [10] (::Plots.#kw##plot)(::Array{Any,1}, ::Plots.#plot, ::Array{IntervalArithmetic.IntervalBox{2,Float64},1}) at ./<missing>:0
 [11] include_string(::String, ::String) at ./loading.jl:485
 [12] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /Users/dpsanders/.julia/v0.6/IJulia/src/execute_request.jl:156
 [13] eventloop(::ZMQ.Socket) at /Users/dpsanders/.julia/v0.6/IJulia/src/eventloop.jl:8
 [14] (::IJulia.##9#12)() at ./task.jl:335
while loading In[17], in expression starting on line 1
```:

**Comment by ararslan** [comment] 2017-04-30 05:11
Related to/duplicate of #20220?

**Comment by KristofferC** [comment] 2017-04-30 07:55
Dup of https://github.com/JuliaLang/julia/issues/20220#issuecomment-295627485

**Closed** 2017-07-11 22:01 UTC
Labels: deprecation, needs more info, won't fix
