### ISSUE TITLE
Type inference case

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#16050] opened 2016-04-26 00:01 UTC
This is on julia 0.4.5 on Windows:

````julia
function get_f()
	f1(x) = 2x

	function f2()
		b = f1(2)

		return b
	end

	return f2
end

f = get_f()

@code_warntype f()
````

I get
````
Variables:
  b::Any

Body:
  begin  # C:\Users\anthoff\source\4sD.jl\test2.jl, line 5:
      b = f1(2)::Any # C:\Users\anthoff\source\4sD.jl\test2.jl, line 7:
      return b
  end::Any
````

Could type inference work better here, i.e. type b properly?

I'm not sure how to title this issue, please adjust if this issue makes sense.

**Comment by yuyichao** [comment] 2016-04-26 00:08
Not sure what's causing this on 0.4 but on 0.5 this is caused by https://github.com/JuliaLang/julia/issues/15276 on 0.5. I'm going to close this as a dup of #15276 since it's unlikely we'll change anything about this on 0.4.

```jl
julia> function get_f()
           f1 = (x) -> 2x

           f2 = function()
               b = f1(2)

               return b
           end

           return f2
       end
get_f (generic function with 1 method)

julia> @code_warntype get_f()
Variables:
  #self#::#get_f
  f1::Core.Box
  #1::##1#3
  f2::##2#4
  #2::##2#4

Body:
  begin  # REPL[0], line 2:
      f1::Core.Box = $(Expr(:new, :((top(getfield))(Core,:Box)::Type{Core.Box})))
      #1::##1#3 = $(Expr(:new, :(Main.##1#3)))
      GenSym(0) = #1::##1#3
      (top(setfield!))(f1::Core.Box,:contents,GenSym(0))::##1#3 # REPL[0], line 4:
      #2::##2#4 = $(Expr(:new, :(Main.##2#4), :(f1::Core.Box)))
      f2::##2#4 = #2::##2#4 # REPL[0], line 10:
      return f2::##2#4
  end::##2#4
```

**Closed by yuyichao** 2016-04-26 00:08 UTC
