### ISSUE TITLE
jl_lam_gensyms assertion failure

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#10850] opened 2015-04-16 14:33 UTC
Happens somewhat often on 32-bit Travis: https://travis-ci.org/JuliaLang/julia/jobs/58725585 for example

```
julia-debug: ast.c:712: jl_lam_gensyms: Assertion `(((jl_value_t*)(((jl_taggedvalue_t *) ((char *)((l)) - __builtin_offsetof (jl_taggedvalue_t, value)))->type_bits&~(size_t)3))==(jl_value_t*)(jl_expr_type))' failed.
signal (6): Aborted
__kernel_vsyscall at  (unknown line)
gsignal at /lib/i386-linux-gnu/libc.so.6 (unknown line)
abort at /lib/i386-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: -1233785675)
unknown function (ip: -1233785497)
jl_lam_gensyms at /home/travis/build/JuliaLang/julia/src/ast.c:713
emit_function at /home/travis/build/JuliaLang/julia/src/codegen.cpp:3934
to_function at /home/travis/build/JuliaLang/julia/src/codegen.cpp:619
jl_compile at /home/travis/build/JuliaLang/julia/src/codegen.cpp:780
jl_trampoline_compile_function at /home/travis/build/JuliaLang/julia/src/builtins.c:998
jl_trampoline at /home/travis/build/JuliaLang/julia/src/builtins.c:1010
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_apply_generic at /home/travis/build/JuliaLang/julia/src/gf.c:1686
anonymous at multidimensional.jl:811
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_trampoline at /home/travis/build/JuliaLang/julia/src/builtins.c:1011
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_apply_generic at /home/travis/build/JuliaLang/julia/src/gf.c:1706
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_f_apply at /home/travis/build/JuliaLang/julia/src/builtins.c:413
check_bitop at bitarray.jl:7
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_apply_generic at /home/travis/build/JuliaLang/julia/src/gf.c:1686
anonymous at no file:219
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_trampoline at /home/travis/build/JuliaLang/julia/src/builtins.c:1011
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_toplevel_eval_flex at /home/travis/build/JuliaLang/julia/src/toplevel.c:514
jl_parse_eval_all at /home/travis/build/JuliaLang/julia/src/toplevel.c:550
jl_load at /home/travis/build/JuliaLang/julia/src/toplevel.c:589
jl_load_ at /home/travis/build/JuliaLang/julia/src/toplevel.c:598
runtests at /tmp/julia/share/julia/test/testdefs.jl:77
jlcall_runtests_44191 at  (unknown line)
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_apply_generic at /home/travis/build/JuliaLang/julia/src/gf.c:1686
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_f_apply at /home/travis/build/JuliaLang/julia/src/builtins.c:413
anonymous at multi.jl:836
run_work_thunk at multi.jl:587
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
jl_apply_generic at /home/travis/build/JuliaLang/julia/src/gf.c:1686
anonymous at task.jl:836
jl_apply at /home/travis/build/JuliaLang/julia/src/julia.h:1262
start_task at /home/travis/build/JuliaLang/julia/src/task.c:232
	From worker 3:	     * bitarray            Worker 3 terminated.
ERROR (unhandled task failure): EOFError: read end of file
 in wait at ./task.jl:305
 in wait at ./task.jl:221
 in wait_full at ./multi.jl:570
 in remotecall_fetch at multi.jl:670
 in remotecall_fetch at multi.jl:675
 in anonymous at task.jl:1386
```

(from commit bd748b973904fd23d43c7adf485cc2926f130dad)

**Comment by tkelman** [comment] 2015-04-19 07:13
previously seen here https://github.com/JuliaLang/julia/pull/10331#issuecomment-77602060

and here https://github.com/JuliaLang/julia/pull/10189#issuecomment-74334534 https://travis-ci.org/JuliaLang/julia/jobs/50687052#L3371, which was 64 bit

**Comment by JeffBezanson** [comment] 2015-04-25 02:59
It looks like this has stopped after b993658e1699db110ac85446a8fb3c251e65476a.

However now there seem to be all sorts of crazy failures on appveyor (since f2e3d33273430190d4fbe8a0688871e48445755b). I don't know what's going on.

**Comment by tkelman** [comment] 2015-04-25 05:15
This one predated #10380 by some margin, but hadn't opened a separate issue for it initially.

**Comment by tkelman** [comment] 2015-07-25 00:55
Reopen if anyone sees this again.

**Comment by tkelman** [comment] 2015-08-01 18:30
reopening due to https://github.com/JuliaLang/julia/pull/12302#issuecomment-126935918

**Comment by stevengj** [comment] 2015-08-03 03:00
Closing this again since #12302 was apparently caused by a missing GC root, which has now been fixed.

**Closed by stevengj** 2015-08-03 03:00 UTC
Labels: bug, test
