### ISSUE TITLE
Error while compiling package when the JULIA_PKGDIR contains underscore character like _SomeFolder_

### ISSUE THREAD

**Issue by yoann-darche** [JuliaLang/julia#15846] opened 2016-04-12 17:06 UTC
Environment : Windows 7 x64 SP1
Julia Version 0.4.5 (2016-03-18 00:58 UTC) //  x86_64-w64-mingw32

When I've set the environment variable `JULIA_PKGDIR = d:\_APP_\Julia\Home`, I've not been able to compile "Blink" pakage. But the `Pkg.init()` has run perfectly :
```
C:\>set JULIA_PKGDIR=D:\_APP_\Julia\Home
C:\>D:\_APP_\Julia\Julia-0.4.5\julia.lnk
                _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32
 
julia> Pkg.init()
INFO: Initializing package repository D:\_APP_\Julia\Home\v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl

julia> Pkg.add("Blink")
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Blink from git://github.com/JunoLab/Blink.jl.git
INFO: Cloning cache of Codecs from git://github.com/dcjones/Codecs.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
[...]
INFO: Installing BinDeps v0.3.21
INFO: Installing Blink v0.3.4
[...]
INFO: Directory D:\_APP_\Julia\Home\v0.4\HttpParser already created

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: D:\_APP_\Julia\Home\v0.4\HttpParser\deps\downloads\libhttp_parser.zip

Extracting  usr\lib
Extracting  usr\lib\libhttp_parser32.dll
Extracting  usr\lib\libhttp_parser64.dll

Everything is Ok
[...]
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
WARNING: Could not check MbedTLS version
INFO: Package database updated
 
julia> using Blink
INFO: Precompiling module Blink...
**ERROR: LoadError: LoadError: UndefVarError: APP not defined**
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
while loading D:\_APP_\Julia\Home\v0.4\Lazy\src\liblazy.jl, in expression starting on line 105
while loading D:\_APP_\Julia\Home\v0.4\Lazy\src\Lazy.jl, in expression starting on line 91
ERROR: LoadError: LoadError: LoadError: Failed to precompile Lazy to D:\_APP_\Julia\Home\lib\v0.4\Lazy.ji
in error at error.jl:21
while loading D:\_APP_\Julia\Home\v0.4\Blink\src\rpc\jsexprs.jl, in expression starting on line 1
while loading D:\_APP_\Julia\Home\v0.4\Blink\src\rpc/rpc.jl, in expression starting on line 11
while loading D:\_APP_\Julia\Home\v0.4\Blink\src\Blink.jl, in expression starting on line 7
ERROR: Failed to precompile Blink to D:\_APP_\Julia\Home\lib\v0.4\Blink.ji
in error at error.jl:21

```
When I've change the `JULIA_PKGDIR` to `d:\Julia\Home` no more issue while compiling !

**Comment by vtjnash** [comment] 2016-04-12 17:51
duplicate of https://github.com/MikeInnes/Lazy.jl/issues/35

**Closed by vtjnash** 2016-04-12 17:51 UTC
