### ISSUE TITLE
Multithreading stalls if using more threads than cores

### ISSUE THREAD

**Issue by saschatimme** [JuliaLang/julia#32258] opened 2019-06-06 17:28 UTC
I noticed the following problem with the first release candiate of 1.2.
```julia
julia> versioninfo()
Julia Version 1.2.0-rc1.0
Commit 7097799 (2019-05-30 02:22 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz <---- Quad-Core CPU
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

Assume I have the following snippet:
```julia
using HomotopyContinuation, PolynomialTestSystems
f = equations(cyclic(7))
for _ in 1:100
    solve(f)
end
```

Now assume I start **two** Julia REPLs where each has `Threads.nthreads() ==4`.
If I paste the snippet into the first session, everything runs fine, but as soon as I paste the snippet into the *second* session **both** sessions freeze, but my CPU load is still 200% in each session.

Note that `solve` automatically multithreads using the [this code](https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl/blob/b466002ee30c84e84eb9252e6290eb83b637f734/src/solve.jl#L218) (this is basically an disassembled version of the `@threads` macro). Therefore I think the problem only occurs if there are more threads than cores running.

I think the same problem happens if I execute the test suite of `HomotopyContinuation` using
```julia
pkg> test HomotopyContinuation
```
At some point the tests just don't continue. If I reduce the test suite to only include the `solve(equations(cyclic(7)))` tests this problem doesn't happen :(
I know that this is not really an "MWE" but unfortunately I was not able to find a smaller version to trigger this.

**Comment by JeffBezanson** [comment] 2019-06-13 15:20
I suspect this might be fixed by #32238.

**Comment by JeffBezanson** [comment] 2019-06-18 05:15
I tried this on master but couldn't get it to work due to package version restrictions. Not urgent, but when that is sorted out it will be useful to try this on master. In the meantime I think we can fix it for 1.2.

**Comment by saschatimme** [comment] 2019-06-27 08:47
@JeffBezanson  The current master of HomotopyContinuation.jl now works again with the Julia master, but I still see the same behaviour on nightly: https://travis-ci.org/JuliaHomotopyContinuation/HomotopyContinuation.jl/jobs/551168625

**Comment by JeffBezanson** [comment] 2019-06-27 15:09
Can you reproduce that locally? It works for me.

**Closed** 2019-06-27 18:35 UTC

**Comment by saschatimme** [comment] 2019-06-29 11:55
@JeffBezanson Yes, if I run 
```julia
pkg> add HomotopyContinuation#master
pkg> test HomotopyContinuation
```
on my local machine the test just get stuck at some point.

```
julia> versioninfo()
Julia Version 1.3.0-DEV.458
Commit 92f8c50556 (2019-06-27 18:39 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.5.0)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```
