### ISSUE TITLE
[LLVM8] Illegal intoptr llbm assertion during `Plots.contour`

### ISSUE THREAD

**Issue by wforbes-pde** [JuliaLang/julia#40222] opened 2021-03-26 20:20 UTC
I'm trying to use Plots.contour. I'm not entirely sure that my objects have the appropriate size/shape for contour.

x is Vector{Float64} with 513 elements
t is Vector{Float64} with 10001 elements
time_steps is 10001x513 Array{Float64,2}

```
using Plots
Plots.contour(x, t, time_steps)


Illegal inttoptr
​     %37 = ptrtoint double addrspace(13)* %36 to i64
Illegal inttoptr
      %56 = inttoptr i64 %55 to i8 addrspace(13)*

signal (6): Aborted
in expression starting at none:0
gsignal at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f9f0a769d04)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-8.so.1 (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-8.so.1 (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-8.so.1 (unknown line)
unknown function (ip: 0x7f9f0a853ac1)
unknown function (ip: 0x7f9f0a8562d8)
unknown function (ip: 0x7f9f0a8568cd)
unknown function (ip: 0x7f9f0a791b4a)
unknown function (ip: 0x7f9f0a7c2ed3)
unknown function (ip: 0x7f9f0a7e884b)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#346 at ./array.jl:0
iterate at ./generator.jl:47 [inlined]
indexed_iterate at ./tuple.jl:89 [inlined]
gr_add_series at /home/wesley/.julia/packages/Plots/uCh2y/src/backends/gr.jl:1491
gr_display at /home/wesley/.julia/packages/Plots/uCh2y/src/backends/gr.jl:891
unknown function (ip: 0x7f9eb12c1048)
gr_display at /home/wesley/.julia/packages/Plots/uCh2y/src/backends/gr.jl:596
_show at /home/wesley/.julia/packages/Plots/uCh2y/src/backends/gr.jl:1776
_showjuno at /home/wesley/.julia/packages/Plots/uCh2y/src/output.jl:273 [inlined]
showjuno at /home/wesley/.julia/packages/Plots/uCh2y/src/output.jl:257
show at /home/wesley/.julia/packages/Plots/uCh2y/src/output.jl:212
unknown function (ip: 0x7f9f0a7f3df8)
#base64encode#3 at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Base64/src/encode.jl:208
base64encode##kw at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Base64/src/encode.jl:203 [inlined]
_binstringmime at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Base64/src/Base64.jl:46 [inlined]
#stringmime#6 at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Base64/src/Base64.jl:43
stringmime##kw at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Base64/src/Base64.jl:43
#stringmime#7 at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Base64/src/Base64.jl:44
stringmime##kw at /build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Base64/src/Base64.jl:44 [inlined]
displayinplotpane at /home/wesley/.julia/packages/Atom/BPtI0/src/display/showdisplay.jl:84
displayandrender at /home/wesley/.julia/packages/Atom/BPtI0/src/display/showdisplay.jl:131
#218 at /home/wesley/.julia/packages/Atom/BPtI0/src/eval.jl:191
unknown function (ip: 0x7f9f0a7f3df8)
jl_f__apply_latest at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#invokelatest#1 at ./essentials.jl:712 [inlined]
invokelatest at ./essentials.jl:711 [inlined]
#216 at /home/wesley/.julia/packages/Atom/BPtI0/src/eval.jl:190
withpath at /home/wesley/.julia/packages/CodeTools/VsjEq/src/utils.jl:30
withpath at /home/wesley/.julia/packages/Atom/BPtI0/src/eval.jl:9
#215 at /home/wesley/.julia/packages/Atom/BPtI0/src/eval.jl:173 [inlined]
with_logstate at ./logging.jl:398
with_logger at ./logging.jl:505 [inlined]
#214 at /home/wesley/.julia/packages/Atom/BPtI0/src/eval.jl:172 [inlined]
hideprompt at /home/wesley/.julia/packages/Atom/BPtI0/src/repl.jl:127
macro expansion at /home/wesley/.julia/packages/Media/ItEPc/src/dynamic.jl:24 [inlined]
evalall at /home/wesley/.julia/packages/Atom/BPtI0/src/eval.jl:162
unknown function (ip: 0x7f9f0a7f3df8)
jl_f__apply_latest at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
#invokelatest#1 at ./essentials.jl:712
unknown function (ip: 0x7f9f0a7f3df8)
invokelatest at ./essentials.jl:711
unknown function (ip: 0x7f9f0a7f3df8)
macro expansion at /home/wesley/.julia/packages/Atom/BPtI0/src/eval.jl:41 [inlined]
#184 at ./task.jl:358
unknown function (ip: 0x7f9eec0479ac)
unknown function (ip: 0x7f9f0a800cbb)
unknown function (ip: (nil))
Allocations: 118696019 (Pool: 118600401; Big: 95618); GC: 104
```

**Comment by vchuravy** [comment] 2021-03-26 20:21
@wforbes-pde What is your `versioninfo()`? From the output it seem like you might be running Julia 1.4?

**Comment by wforbes-pde** [comment] 2021-03-26 20:26
It appears that I am. I vaguely recall some preferred method of installing Julia where it would be easier to update.

julia> versioninfo()
Julia Version 1.4.1
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 8

**Comment by Keno** [comment] 2021-03-26 20:29
Where did you get this copy of Julia? These kinds of issues tens to happen if somebody decided to ignore our LLVM patchset. Can you try an official release?

**Comment by vchuravy** [comment] 2021-03-26 20:30
From the stacktrace I suspect it is: https://launchpad.net/ubuntu/+source/julia/1.4.1+dfsg-1

**Comment by vchuravy** [comment] 2021-03-26 20:32
Duplicate of #37003 and https://bugs.launchpad.net/ubuntu/+source/julia/+bug/1891205

@wforbes-pde we recommend the official release at https://julialang.org/downloads/ to avoid these issues

**Closed by vchuravy** 2021-03-26 20:32 UTC

**Comment by vchuravy** [comment] 2021-03-26 20:35
Yeah I checked their build recipe... `USE_SYSTEM_LLVM=1`

**Comment by wforbes-pde** [comment] 2021-03-26 20:36
I ran

sudo apt-get install julia

**Comment by vchuravy** [comment] 2021-03-26 20:43
Please comment on  https://bugs.launchpad.net/ubuntu/+source/julia/+bug/1891205 to let them know that you run into issues.

**Comment by wforbes-pde** [comment] 2021-03-26 20:46
Sure. Thanks for the quick response.
