### ISSUE TITLE
Nightly builds not updated

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#23846] opened 2017-09-23 16:22 UTC
OSX nightly appears to be stuck at 1af1f5275c (6 days old master).
Linux (x64 at least) appears to be stuck at 55ec9fe (9 days old master).

**Comment by DrKrar** [comment] 2017-09-23 18:39
Also, the windows build is stuck at 1af1f5275c  (6 days old master).

**Comment by DrKrar** [comment] 2017-09-23 18:40
julia> versioninfo()
Julia Version 0.7.0-DEV.1816
Commit 1af1f5275c* (2017-09-17 15:48 UTC)
Platform Info:
  OS: Windows (i686-w64-mingw32)
  CPU: Intel(R) Pentium(R) CPU G620 @ 2.60GHz
  WORD_SIZE: 32
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, sandybridge)
Environment:

**Comment by tkoolen** [comment] 2017-10-03 12:19
OSX and Windows are now at 6159bcb, Linux still at 55ec9fe.

**Comment by timholy** [comment] 2017-10-20 08:58
I'm not exactly sure I'm reading this correctly, but [this page](https://build.julialang.org/console) seems to suggest that every platform other than OSX is "offline" and that OSX is failing. However, this may not represent the whole truth, because in repositories I'm seeing that Linux is now at 10-16-2017 (eae7104bf) and OSX and Windows are both at 10-10-2017 (both 546a801260). That represents a significant improvement from ~1 week ago, esp. on Linux. But obviously it would be great to get rid of the lag.

**Comment by musm** [comment] 2017-10-30 16:56
I usually check https://status.julialang.org/  windows and osx are ~20 days

**Comment by bramtayl** [comment] 2017-11-09 00:51
Has it been almost a month since the last nightly? I'm looking to play around with the new named tuples

**Comment by ViralBShah** [comment] 2017-11-10 05:06
While the nightlies should of course be fixed, it is not too bad to build from source to try out the goodies!

**Comment by timholy** [comment] 2017-11-16 10:35
Is there anything we can do to help here? I have some branches for Revise (https://github.com/timholy/Revise.jl/pull/49 and more speculatively https://github.com/timholy/Revise.jl/pull/57) that are getting quite stale because I don't feel comfortable merging them until CI tests run. The problem is that they use facilities added to Base after Oct 10th, which is where the OSX binaries are stuck.

**Comment by timholy** [comment] 2017-11-21 14:55
Whoever caught the OSX and Linux builds up, thanks!

I'd close this, except I noticed that Windows *nightlies* are actually downloading 0.6.1, as you'll see if you click on the links [here](https://ci.appveyor.com/project/timholy/revise-jl/build/1.0.129).

**Comment by staticfloat** [comment] 2017-11-21 19:34
Yes, add https://github.com/JuliaLang/julia/issues/24611 to that list as another thing that's killing the Windows builds.  :)

**Comment by staticfloat** [comment] 2017-11-27 09:19
We had some windows nightlies go through a day or two ago; can you all confirm that it's working as expected?

**Comment by timholy** [comment] 2017-11-27 11:56
Yes, looks like it: https://ci.appveyor.com/project/SimonDanisch/fileio-jl-t5dw5/build/1.0.298 (The failures are a good demonstration that the latest is being used.)

Thanks a million, @staticfloat!

**Closed by timholy** 2017-11-27 11:56 UTC
Labels: build, ci
