### ISSUE TITLE
Performance Regression in multithreading

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#15871] opened 2016-04-14 10:27 UTC
I ran my [Logistic Regression benchmark](https://github.com/ranjanan/MT-Workloads/blob/master/Logistic%20Regression/logreg.jl) for threads. Not sure if this is related to earlier issues or not, but I thought I'd post an issue anyway.
Usually the output would be (on a version of master sometime in January)
```
Warm up run : 25 iterations!
Time taken by serial implementation = 1.508228316
Time taken by parallel implementation = 0.429550363
Speedup over 4 threads : 3.5111792374390336
```
Now, with the current threaded build of master, it's this:
```
Warm up run : 25 iterations!
Time taken by serial implementation = 1.831504341
Time taken by parallel implementation = 42.974081761
Speedup over 4 threads : 0.04261881268774738
```

**Comment by andreasnoack** [comment] 2016-04-14 14:22
I think this is mainly because of https://github.com/JuliaLang/julia/issues/15276 but it might be useful to keep a separate issue to track the consequences for threading.

**Comment by JeffBezanson** [comment] 2016-07-06 16:28
This particular case is fixed on master. If it comes up again, the workaround is to declare types on variables used both inside and outside the `@threads` loop.

**Closed by JeffBezanson** 2016-07-06 16:28 UTC
Labels: multi-threading, performance, regression

**Comment by ViralBShah** [comment] 2016-07-07 05:36
@ranjanan Can you verify?

**Comment by ranjanan** [comment] 2016-07-08 08:07
Yes, this seems like it's fixed.

**Comment by elanmart** [comment] 2016-09-17 11:50
Hi, running the `logreg` benchmark from above on 8 threads I'm getting a speedup of only 1.5 on the current master. Could this be a new issue or just a duplicate of #17395?
