### ISSUE TITLE
Trying to create sys-all.so causes segmentation fault

### ISSUE THREAD

**Issue by cielavenir** [JuliaLang/julia#30299] opened 2018-12-07 09:58 UTC
Running `/opt/julia-1.0.2/bin/julia --output-o sys-all.o --sysimage /opt/julia-1.0.2/lib/julia/sys.so --startup-file=no --compile=all --eval nothing
found 39977 uncompiled methods for compile-all` causes segemtation fault:

```
found 39977 uncompiled methods for compile-all
 11659 / 39977
signal (11): Segmentation fault
in expression starting at no file:0
jl_is_type_type at /buildworker/worker/package_linux64/build/src/julia.h:1058 [inlined]
emit_llvmcall at /buildworker/worker/package_linux64/build/src/ccall.cpp:977
emit_intrinsic at /buildworker/worker/package_linux64/build/src/intrinsics.cpp:921
emit_call at /buildworker/worker/package_linux64/build/src/codegen.cpp:3134
emit_expr at /buildworker/worker/package_linux64/build/src/codegen.cpp:3902
emit_ssaval_assign at /buildworker/worker/package_linux64/build/src/codegen.cpp:3615
emit_stmtpos at /buildworker/worker/package_linux64/build/src/codegen.cpp:3801 [inlined]
emit_function at /buildworker/worker/package_linux64/build/src/codegen.cpp:6254
jl_compile_linfo at /buildworker/worker/package_linux64/build/src/codegen.cpp:1159
_compile_all_deq at /buildworker/worker/package_linux64/build/src/precompile.c:262 [inlined]
jl_compile_all_defs at /buildworker/worker/package_linux64/build/src/precompile.c:303
jl_precompile at /buildworker/worker/package_linux64/build/src/precompile.c:365 [inlined]
jl_write_compiler_output at /buildworker/worker/package_linux64/build/src/precompile.c:34
jl_atexit_hook at /buildworker/worker/package_linux64/build/src/init.c:233
main at /buildworker/worker/package_linux64/build/ui/repl.c:234
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /opt/julia-1.0.2/bin/julia (unknown line)
Allocations: 1254722 (Pool: 1254268; Big: 454); GC: 2
Segmentation fault
```

I expect to get sys-all.so which then can be used for `cc -shared -o sys-all.so sys-all.o -ljulia`.

**Comment by cielavenir** [comment] 2018-12-07 09:59
Well, the enviornment is `Linux *** 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`

**Comment by SimonDanisch** [comment] 2018-12-08 13:36
duplicate of : https://github.com/JuliaLang/julia/issues/29601

**Closed** 2018-12-08 14:17 UTC
