### ISSUE TITLE
Function has no methods when argument type name is same as function name

### ISSUE THREAD

**Issue by rakeshvar** [JuliaLang/julia#41344] opened 2021-06-24 12:35 UTC
```julia
julia> function f(::f) where f
       f
       end
f (generic function with 0 methods)

julia> function g(::f) where f
       f
       end
g (generic function with 1 method)
```

The first definition fails to work while the second does. The first one has no methods.
`Version 1.5.1 (2020-08-25)`

**Comment by vtjnash** [comment] 2021-06-24 12:39
Duplicate of https://github.com/JuliaLang/julia/issues/33537

**Closed by vtjnash** 2021-06-24 12:39 UTC
