### ISSUE TITLE
Out of left field new ideas: parameterize the type function by the input and output types, add the map symbol to type parameters of functions for input and output parameters, and pattern match literals

### ISSUE THREAD

**Issue by aaronsheldon** [JuliaLang/julia#17905] opened 2016-08-08 22:36 UTC
I think my ideas [here](https://github.com/JuliaLang/julia/pull/13412#issuecomment-238327962) are so far out of the mainstream that they deserve to be beaten up in their own thread.

1. Parameterize the type "Function" by its input and output parameters. The following type hierarchy would apply:

        Function{In} <: Function == true
        Function{In, Out} <: Function{In} == true
In particular we could have this:

        foo(x::Int, y::Int) = convert(Float, x + y)
        z = foo
        isa(z, Function{Tuple{Int, Int}, Float}) == true
The set theoretic idea being that the type "Function" from T to S is a (abstract, lazy, or computed) list of Tuple{T, Tuple{T, S}} such that (x, (x, y)) is true for every element in the list:

        Function{T, S} <: AbstractList{Tuple{T, Tuple{T, S}}} == true
For functions with multiple methods the in types would be some form of union, hopefully parameterized to represent any inferences and code supplied restrictions:

        typeof(sin) = Function{T<:Union{Number, AbstractArray}, T}

So that a function that has been heavily overloaded in a manner that makes type inference difficult ends up as

      typeof(difficultfunction) = Function{Union{Tuple{...}, Tuple{...}, ...}, Any}
2. Add the "maps to" symbol "->" in the type parameter list of functions to differentiate between type parameters applying to the input and type parameters applying to the output:

        bar{T -> S}(x::T)::S = 2 * x
        baz{T -> S}(x::T) = (2 * x)::S
Also this should allow for tying the parameters:

        bac{T -> T}(x::T)::Vector{T} = x .* ones(T, x)
3. The result for for closures is that the following syntax covers parameterization:

        g{T -> S, R}(y::T)::Function{S, R} = (x::S -> (x + y)::R)
        g{T -> S, R}(y::T) = {S -> R}(x::S -> (x + y)::R)
And for truly anonymous Lambdas

        h = {T -> S}(x::T -> (x + 1)::S)
4. Finally I would like to see the syntax "x::{...}" used for exact pattern matching instead of the "::Val{...}" and "Val{...}()" constructs:

        fal(x::{0}) = 1
        fal(x::Int) = x * fal(x - sign(x))
Because types in some ways identify sets, in the mathematical sense, it might be interesting to allow:

        fun(x::{0, 1, 2, 3}) = 4
Reflecting the interpretation that the "::" operator represents the idea of "membership in".

**Comment by tkelman** [comment] 2016-08-08 22:51
see https://github.com/JuliaLang/julia/issues/17168

**Comment by JeffBezanson** [comment] 2016-08-08 22:53
See #210, #16191, #17168. This has been discussed a decent amount and is not really out of left field.

Given

```
bar{T -> S}(x::T)::S = 2 * x
```

the whole problem is how to determine `S`, but I won't repeat the whole discussion here.

Pattern matching syntax and singleton types (e.g. the set of the value `0`) are totally separate issues I believe.

**Comment by aaronsheldon** [comment] 2016-08-08 23:15
I agree the last point being a separate issue, this was more of a laundry list.

As far as the last point, I have found that to use the Val{}() construct I almost always have to put some form of branch in my code anyway to generate the Val{}(), which I find negates the whole point of the singleton construct. So that currently:

        fal(::Type{Val{0}}) = 1
        fal(x::Int) = x == 0 ? fal(Val{0}()) : fal(x - sign(x))

**Comment by StefanKarpinski** [comment] 2016-08-09 03:52
Note that return types are contravariant, which contradicts the subtype relation proposed in #13412, namely that `Function{In,Out} <: Function{In}` – the relation should be the other way around since a function that returns an `Out` is a subtype of a function with unconstrained return type. Also note that having type annotations on methods doesn't really help much in the presence of multiple dispatch since you need to dispatch on functions, and then select a method.

**Comment by vtjnash** [comment] 2016-08-09 20:48
closing as a duplicate of previous issues.

I believe the current plan for `{}` is to mean the same as `Tuple{}`, although that's not finalized yet.

> However, the Val{}() construct is effective when dynamically generating a set of overload methods for a function, which then act like a static lookup table, such as translating column names to scalar indexes.

"dynamically generating a static list" – something about this statement seems contradictory

The `Val` construct is typically also very inefficient, a `Dict` would be much lower overhead than using dispatch to compute this branch.

@carnaval has been discussing the possibility of converting a method definition on a constant into a truly efficient static lookup table. I think this was covered mostly by the getfield overloading issue.

**Closed by vtjnash** 2016-08-09 20:48 UTC
