### ISSUE TITLE
Performance issue on Windows 8

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#16570] opened 2016-05-25 05:20 UTC
Is there any known major performance issue with Julia on Windows 8?

Before I take the time to organize a test case, the  performance difference I am talking about here is huge. I have a code that takes 6min to run on Linux and Windows 10. This same code takes 97min on Windows 8.

I investigated other possible causes by running the code with different Julia releases on different computers. There are only two possible causes left: Windows 8 weirdness or HD vs. SSD. The latest cause is unlikely given that my package is not doing any explicit access to the disk.

**Comment by quinnj** [comment] 2016-05-25 05:22
It would at least be helpful to know the version of julia you're running and what kind of code you're touching. Most helpful, as you probably know, is full steps to reproduce what you're seeing.

**Comment by tkelman** [comment] 2016-05-25 05:30
You may have a really paranoid antivirus or similar.

**Comment by juliohm** [comment] 2016-05-25 05:30
@quinnj I've tried Julia v0.4.1 and v0.4.5. I will try to find the time during the week to organize the test case I mentioned. The package I am testing is [ImageQuilting.jl](https://github.com/juliohm/ImageQuilting.jl). Meanwhile, if someone wants to try something simple that should also reflect the same performance difference (although I didn't test this specific example), please run the following:

```julia
using ImageQuilting
using GeoStatsImages

TI = training_image("Flumy")
@time iqsim(TI, 30, 30, 30, size(TI)...)
```

**Comment by juliohm** [comment] 2016-05-25 05:31
@tkelman Windows 8 is the virus! :blush:

**Comment by juliohm** [comment] 2016-05-25 17:16
@quinnj @tkelman can you reproduce the issue? Do you have a machine with Windows 8 somewhere?

**Comment by quinnj** [comment] 2016-05-25 17:33
I do have a machine, but unfortunately I'm traveling until Friday, but could try it out then.

**Comment by tkelman** [comment] 2016-05-25 17:50
That line above took about 5-6 minutes for me on Windows 10. I do not have Windows 8, I have a laptop with Windows 7 but not that I'm regularly using.

**Comment by juliohm** [comment] 2016-05-25 18:02
@tkelman, thanks, that is the expected time on Windows 10. I am waiting for someone with Windows 8 + SSD to confirm the issue.

**Comment by juliohm** [comment] 2016-05-25 18:02
@quinnj no rush, I am also quite busy.

**Comment by jebej** [comment] 2016-05-26 03:39
The lines above take 5min with an i7 3770K on Windows 7 and 6.5min with an i5 2500 on Windows 8.1

**Comment by juliohm** [comment] 2016-05-26 06:23
Windows 8.1 on HD or SSD?

-Júlio

**Comment by juliohm** [comment] 2016-05-26 07:32
I tried the example above on the same problematic machine with Windows 8.1 and it is ok. @jebej can you please try the following one instead?

```julia
using ImageQuilting

TI = reshape(readdlm("models34.gslib", skipstart=3), 169, 134, 40)
TI[TI.==-999] = NaN

function thickness(basin)
    AUX = repeat(sum(!isnan(basin),3), inner=[1,1,size(basin,3)])
    AUX = AUX / maximum(AUX)
    AUX[isnan(basin)] = NaN

    AUX
end

auxvar=SoftData(thickness(TI),thickness)

shape = HardData()
for idx in find(isnan(TI))
    i,j,k = ind2sub(size(TI), idx)
    push!(shape, (i,j,k)=>NaN)
end
 
reals = @time iqsim(TI, 20, 20, 15, size(TI)..., cutoff=.01, soft=auxvar, hard=shape, nreal=1)
```

Please download the file models34.gslib by [clicking here](https://www.dropbox.com/s/s6ik763cy6mlwaz/models34.gslib?dl=0).

**Comment by jebej** [comment] 2016-05-26 13:12
SSDs on both computers, although like you said the benchmark doesn't seem to hit the disk too much. That last test you sent took ~6min (351sec) on Win8.1.

**Comment by juliohm** [comment] 2016-05-26 16:16
@jebej that is interesting, what Julia version have you used? I don't think it is the HD either, but I cannot think of any other possible cause.

@tkelman can an antivirus software compromise Julia performance or it was just a joke? All these computers presenting the issue are in the same network. The university installs a bunch of software to guarantee that the data is secured and so on.

I will try to profile the code later on Windows 8...

**Comment by jebej** [comment] 2016-05-26 16:28
I used 4.3 on Windows 8.1. You should definitely profile, and if nothing obvious sticks out we can compare profiler outputs.

**Comment by KristofferC** [comment] 2016-05-26 16:38
@juliohm AntiViruses can definitely mess with performance since they hook into a bunch of calls. Especially if you are opening and closing many files. I'm not sure if your application is doing that but if the only common factor is the software the IT people fill the computer with then it  is worth looking into.

**Comment by tkelman** [comment] 2016-05-26 17:38
It wasn't a joke. Watch task manager / resource monitor while this is running, see if anything other than Julia is consuming an unexpected amount of CPU, memory, disk, or other resources. In terms of the way Julia interacts with the Windows OS, there isn't all that much that's different in API's between Vista, 7, 8, and 10. More likely it's the difference between the computers and what other software they have installed that is interfering with your computation.

**Comment by juliohm** [comment] 2016-05-27 05:36
Yes, the profile plot (Tim's ProfileView) is not showing anything strange, most of the time is spent in the FFT calculation as it should be:

![screenshot from 2016-05-26 22-33-31](https://cloud.githubusercontent.com/assets/3345261/15598760/1d41d74a-2392-11e6-9cb8-3ae3df27054f.png)

How can I inspect the processes that are interfering with the Julia execution? The last time I checked the task manager on Windows, I don't remember seeing anything strange.

**Comment by tkelman** [comment] 2016-05-27 12:12
Is FFTW trying to use multiple threads? There are more detailed views than task manager you can try, the Resource Monitor, or Process Explorer, etc. Try enabling the C flag when you show the profile (it's a keyword argument for `Profile.print`, not sure how it works in ProfileView).

**Comment by juliohm** [comment] 2016-05-27 14:09
@tkelman I am asking for all CPU cores as you can see here: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L27

I will check the other resource monitors, this performance difference is really mysterious.

**Comment by tkelman** [comment] 2016-05-27 16:55
Maybe reduce this to ccalls and report to fftw then.

**Comment by juliohm** [comment] 2016-05-27 16:57
What do you mean exactly Tony?

-Júlio

**Comment by tkelman** [comment] 2016-05-27 17:34
Include C in your profiles for one thing, with the keyword argument or equivalent in ProfileView.

If it's spending all its time in fft calls, then there should be a handful of ccalls that capture the important part of the work. I doubt this is a problem with Julia, it may be something strange with threading in the underlying fftw C library.

**Comment by juliohm** [comment] 2016-05-27 17:36
Got it, I'll check this option in the profiler.

-Júlio

**Comment by juliohm** [comment] 2016-06-03 18:46
I don't know if that is the cause, but I see a Microsoft anti-malware software consuming memory, right after the Julia process:

![capture](https://cloud.githubusercontent.com/assets/3345261/15789362/8e8f3bba-2980-11e6-9e68-a731b9a168d9.PNG)

@jebej do you also have that?

**Comment by tkelman** [comment] 2016-06-03 18:56
It's taking 0% cpu in that screenshot, unless you're close to swapping the memory use of an idle process shouldn't make much difference. I suspect it's something in FFTW causing the difference.

**Comment by juliohm** [comment] 2016-06-15 15:44
These are the last lines of the sorted profile output:

![profile](https://cloud.githubusercontent.com/assets/3345261/16086616/ca49bc16-32e5-11e6-803d-501309df8299.png)

There is definitely something going on with the FFTW library and with `apply_generic` in `libjulia.dll`. What is the purpose of the latter and why it consumes so much time?

**Comment by juliohm** [comment] 2016-06-18 02:22
@tkelman @quinnj what is `jl_apply_generic`? Why is it so time consuming?

**Comment by vtjnash** [comment] 2016-06-18 13:32
It's the toplevel entry point, or in other words, the total run time. This should be more visible from the profile tree view.

**Comment by juliohm** [comment] 2016-06-25 02:51
How can I find the FFTW version called by Julia on Windows 8? The issue is affecting one of my colleagues and I still have no clue what is causing it.

**Comment by tkelman** [comment] 2016-06-25 05:27
It's version 3.3.4 and has been for some time (`deps/Versions.make`), see `deps/Makefile` on 0.4 or `deps/fftw.mk` on master for the exact compile settings.

**Comment by juliohm** [comment] 2016-06-25 13:12
@tkelman I am starting to think that the issue is not related to FFTW if the version is the same everywhere in all Julia versions I have tried. Do you see anything strange with the profile output above?

**Comment by tkelman** [comment] 2016-06-25 13:42
The semaphore and mutex calls look suspicious. Some of those threading API's do differ in subtle ways between Windows versions. I would think any issues in Windows 8 would also be visible in Windows 10, but maybe there are just bugs that later got fixed. What does the hierarchical tree or graphical view of the profile look like? Really I think you'll need to find the specific calls into fftw that your code is doing, and repeat them in a simple C function to see if it reproduces the performance difference. Or upgrading to Windows 10 might be simpler and could potentially also fix the issue?

**Comment by juliohm** [comment] 2016-06-25 14:02
Windows 8 has many different patches correct? My guess is that the Windows
8 installed in the university doesn't have all the patches as the Windows 8
tested above? If the FFTW library distributed with Julia is the same across
most Julia versions and Julia is guaranteed to use it without possibly
linking other FFTW libraries already installed in the machine, then the
problem is the OS.

Unfortunately we cannot update to Windows 10, this is an entire network of
computers in the department with a bunch of technical software installed.

I'll try print the profile hierarchical output, thank you.

-Júlio

**Comment by tkelman** [comment] 2016-06-25 14:17
Maybe there could be some other fftw library elsewhere on the path, that's a possibility. Worth checking, or setting your path temporarily to something minimal to see if it makes a difference.

**Comment by juliohm** [comment] 2016-06-25 19:58
@tkelman I generated the full output without flatting it, could you please take a look? [profile_output.txt](https://github.com/JuliaLang/julia/files/333258/profile_output.txt)

Thanks.

**Comment by tkelman** [comment] 2016-06-25 20:36
Looks like a lot of the time is in `fftw_printer_destroy` and various NT kernel semaphore/mutex functions getting called therein. Thanks for filing this upstream at FFTW's tracker - ref https://github.com/FFTW/fftw3/issues/63. We'll see what they say there.

**Comment by juliohm** [comment] 2016-07-25 04:06
I have updated Julia today and this performance issue is now affecting my Linux machine too. I will clone a clean Julia and rebuild release-0.4 from scratch to make sure the issue is not my fault nor FFTW library's fault.

**Comment by ihnorton** [comment] 2016-10-31 01:38
@juliohm is this still an issue on 0.5?

**Comment by juliohm** [comment] 2016-10-31 03:06
@ihnorton yes, I have just tried it again.

**Comment by ihnorton** [comment] 2016-11-02 15:32
@juliohm I get a significant slowdown on Windows 10 vs OS X.
Different systems, but reasonably comparable CPUs. Also both SSD (shouldn't matter, not i/o bound at all).

OS X 10.11:
```
julia> reals = @time iqsim(TI, 20, 20, 15, size(TI)..., soft=auxvar, hard=shape, nreal=1)
499.536336 seconds (82.02 M allocations: 226.698 GB, 39.84% gc time)
```

Windows 10 (copying manually from other screen):

`19350s (nearly identical allocations but only 1.78% gc time)`

Windows 10 with `set_num_threads(1)` in ImageQuilting/iqsim.jl:

`701.897s (nearly identical allocations, 27.13% gc time)`

So @tkelman's analysis that this is a thread sync issue is correct, but the problem does not appear to be related to the Windows version. Per the [FFTW manual](http://www.fftw.org/doc/Multi_002dthreaded-FFTW.html)

> However, this does not necessarily translate into performance gains—when multiple threads/CPUs are employed, there is an overhead required for synchronization that may outweigh the computatational parallelism. Therefore, you can only benefit from threads if your problem is sufficiently large.

The thread sync cost is much higher on Windows, at least with the Windows primitives FFTW is currently using (mutexes, see: http://stackoverflow.com/questions/1666653/are-mutexes-really-slower). Closing this as "upstream". I would suggest using 1 thread for your problem on Windows (or experiment with lower number) to get closer performance to other platforms.

**Closed by ihnorton** 2016-11-02 15:32 UTC
Labels: upstream, windows

**Comment by juliohm** [comment] 2016-11-02 15:38
@ihnorton I have tried running in another Windows 10 machine, and the performance was comparable to Linux. I will try it again and reopen the issue if it is the case. It may be something specific about the Windows installation or a patch version that is compromising the performance.

**Comment by ihnorton** [comment] 2016-11-02 21:22
Hmm, tried one other quick test (because I realized the CPUs weren't as similar as I thought). With `set_num_threads(4)` (4 physical cores on the Windows box):

`374s (blah, blah, 45.19% gc time)`

Unscientific, but did run twice, and it seems there is a parallel speedup on Windows (1 thread / 701s -> 4 thread / 374s), but Windows thread sync (mutexes?) may be extraordinarily expensive when used with HT (example ran again for >30 minutes, with 8 == Sys.CPU_CORES, until I killed it)

So, on Windows set number of threads to # physical cores at most. (I think you need Hwloc.jl for cross-platform checking of # physical cores)

**Comment by juliohm** [comment] 2016-11-02 22:24
@ihnorton , that is a very good point, I thought CPU_CORES in Julia would return the number of physical cores, is that incorrect?
