### ISSUE TITLE
UndefVarError with lower type bound even when all type parameters are specified for a constructor

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#42353] opened 2021-09-23 01:43 UTC
If I fully specify the type parameters for a constructor and the arguments are compatible, I expected it to work. However, I'm seeing errors from the default constructor:

```julia
julia> struct Struct1{T,S>:T}
           x::S
       end

julia> Struct1{Int,Real}(0)
ERROR: UndefVarError: S not defined
...

julia> struct Struct2{T,S>:T}
           x::S
           Struct2{T,S}(x) where {T,S} = new{T,S}(x)  # no bound for S
       end

julia> Struct2{Int,Real}(0)
Struct2{Int64, Real}(0)
```

I can also get the same error with a manual constructor with the same bound:

```julia
julia> struct Struct3{T,S>:T}
           x::S
           Struct3{T,S}(x) where {T,S>:T} = new{T,S}(x)
       end

julia> Struct3{Int,Real}(0)
ERROR: UndefVarError: S not defined
...
```

But, interestingly, it doesn't happen with the upper bound `T<:S`

```julia
julia> struct Struct4{S,T<:S}
           x::S
       end

julia> Struct4{Real,Int}(0)
Struct4{Real, Int64}(0)

julia> struct Struct5{S,T<:S}
           x::S
           Struct5{S,T}(x) where {S,T<:S} = new{S,T}(x)
       end

julia> Struct5{Real,Int}(0)
Struct5{Real, Int64}(0)
```

I wonder if this is a symptom of what @JeffBezanson described in https://github.com/JuliaLang/julia/issues/39280#issuecomment-763077129

> It helps here to understand that two different processes are happening: (1) picking a method to call, and (2) once inside the method, determining the value of `T` (#39277 has a similar concern).

But, since `Struct1{Int,Real}(0)` specifies the type, would it be possible to use the specified types as-is in the method body?

**Comment by vtjnash** [comment] 2021-09-23 03:53
Duplicate of https://github.com/JuliaLang/julia/issues/41728

**Closed by vtjnash** 2021-09-23 03:53 UTC
Labels: types and dispatch
