### ISSUE TITLE
Unintuitive error messages in REPL shell

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#10110] opened 2015-02-07 00:56 UTC
```
shell> !
bash: syntax error near unexpected token `)'

shell> (
bash: syntax error near unexpected token `)'
```

I understand that these might not be valid shell commands but the syntax error is puzzling.

**Comment by jiahao** [comment] 2015-02-07 06:31
These errors are emitted by the shell, not Julia. However, it looks like the shell is receiving an extra level of parentheses: at the ordinary bash prompt the errors are

```sh
bash-3.2$ !
bash: syntax error near unexpected token `newline'
bash-3.2$ (
> 
```

The second simply continues waiting for the closing right parenthesis.

c.f.

```sh
bash-3.2$ ! )
bash: syntax error near unexpected token `)'
bash-3.2$ ( )
bash: syntax error near unexpected token `)'
```

**Comment by vtjnash** [comment] 2016-03-25 20:07
duplicate of https://github.com/JuliaLang/julia/issues/10120

**Closed by vtjnash** 2016-03-25 20:07 UTC
Labels: REPL

**Comment by sbromberger** [comment] 2016-03-25 20:09
Technically, #10120 is a duplicate of this one.

**Comment by vtjnash** [comment] 2016-03-25 20:15
i usually keep whichever issue has more discussion (or analysis). usually that's the older issue, but sometimes it's the newer issue.
