### ISSUE TITLE
Detect if a name has a docstring

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#51169] opened 2023-09-03 21:32 UTC
I want to check all my functions have docstrings but there is no function to check for a docstring.

@stevengj [proposes](https://discourse.julialang.org/t/check-if-a-function-has-a-docstring/103489/4)

```jl
hasdoc(mod::Module, sym::Symbol) = 
    haskey(Base.Docs.meta(mod), Base.Docs.Binding(mod, sym))
```

which could go in `Test` or `Docs`.

**Comment by stevengj** [comment] 2023-09-04 15:05
Close as duplicate of https://github.com/JuliaLang/julia/issues/51174

**Closed by stevengj** 2023-09-04 15:05 UTC
