### ISSUE TITLE
ARM binaries missing for Julia 1.1.0

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#30870] opened 2019-01-28 15:12 UTC
I notice that the downloads page does not have binaries for ARM. Could you add a brief statement there describing the status, as in e g.:
- please wait a few days for the binaries to show up
- don't have the infrastructure for binaries, please use 1.0 instead
- ...

**Comment by ViralBShah** [comment] 2019-01-28 18:15
Maybe we should discuss the tiers on the downloads page (or point to the relevant section in the README.md), so that it sets these expectations.

**Comment by arnavs** [comment] 2019-02-19 06:37
Just wanted to check if these binaries have been built yet.

**Comment by ViralBShah** [comment] 2019-02-19 06:49
IIRC, there is a build regression on ARM  for 1.1.

**Comment by arnavs** [comment] 2019-02-19 07:20
Roger, thanks for the update.

**Comment by ararslan** [comment] 2019-02-19 17:05
Co-assigning Elliot as he has a better idea of the state of the build on any given platform.

**Comment by staticfloat** [comment] 2019-02-21 22:44
I have new ARM buildbots, but I haven't switched the new buildog configuration over to build yet, so they're languishing in a testing zone.  Alex, when you next have some free time, let's plan to upgrade the buildbot infrastructure to my new testing setup, and make sure that we can build these ARM binaries.  I think things should mostly work.  :)

**Comment by robsmith11** [comment] 2019-03-16 08:31
For anyone curious, the current nightly seems to be building without any issues.  I just downloaded a snapshot and ran `make` on my Android tablet with an Arch Arm chroot (Snapdragon 820 / 3GB RAM).
```
julia> versioninfo(verbose=true)
Julia Version 1.2.0-DEV.0
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  uname: Linux 3.18.71-gbf3ecfa #1 SMP PREEMPT Thu Jul 19 15:46:30 +03 2018 aarch64 unknown
  CPU: unknown:
              speed         user         nice          sys         idle          irq
       #1   307 MHz    5236143 s      38420 s    5145766 s   94852781 s    2587504 s
       #2   307 MHz    5943345 s      46989 s    4961981 s   97681823 s     429277 s
       #3  2150 MHz    5576008 s     125489 s    4161811 s   99490676 s     264564 s
       #4  2150 MHz    4953546 s     119577 s    3781152 s  100657166 s     232575 s

  Memory: 3.3130035400390625 GB (529.21484375 MB free)
  Uptime: 1.11535e6 sec
  Load Avg:  6.208984375  6.18701171875  6.13330078125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, kryo)
Environment:
  MOZ_PLUGIN_PATH = /usr/lib/mozilla/plugins
  HOME = /home/me
  TERM = screen-256color
  PATH = /home/me/.cargo/bin:/home/me/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by ViralBShah** [comment] 2019-03-28 15:18
Do we have arm binaries? If so, we should link on downloads.

**Comment by ViralBShah** [comment] 2019-04-29 22:54
https://github.com/JuliaLang/www.julialang.org/commit/fff941cfaec831823c6e3ca07608649695a09a8c

**Comment by terasakisatoshi** [comment] 2019-05-01 03:02
Hi, For those who see this issue, I wrote a belief instruction how to build Julia binary for Raspberry Pi series (including even Zero) by cross-compiling via Docker. 

- [armv7-a](https://gist.github.com/terasakisatoshi/00fa7d7b81b7c6748f2298f6ff65bf6e)
- [zero series](https://gist.github.com/terasakisatoshi/3f8a55391b1fc22a5db4a43da8d92c98)

Hope it helps. AFIK many packages e.g. PyCall, UnicodePlots, PackageCompiler, QuadGK, Plots works fine.

I'm so sorry to hear that arm32bit [Move to Tier3](https://github.com/JuliaLang/julia/pull/31880).

**Comment by ViralBShah** [comment] 2019-05-01 13:41
Had this been reliably working on 1.1? I wonder why it buildbots are unable to produce binaries then.

**Comment by ViralBShah** [comment] 2019-05-01 13:42
Should link those instructions in the arm section of the build docs.

**Comment by staticfloat** [comment] 2019-05-01 17:33
The buildbots do create binaries, but the binaries do not pass the full test suite.

**Comment by ViralBShah** [comment] 2019-05-01 18:43
Ok, but they never did, I thought. We should upload them for download and move arm to tier 2.

**Comment by ViralBShah** [comment] 2019-05-01 18:45
Cc @ararslan

**Comment by ararslan** [comment] 2019-05-01 19:52
> The buildbots do create binaries

Oh, I didn't realize the buildbots were even getting through the build these days. I'm cool with moving ARM back to tier 2, but I think we should perhaps reformat the download table on the website to better reflect support tiers.

**Comment by ViralBShah** [comment] 2019-05-01 22:27
Yes, we should also note the support tiers onthe downloads page. My suggestion - let's get the binaries up right away, and revert the PR for the Tier downgrade.

Separately, let's work on better communication of the Tiers.

**Comment by ViralBShah** [comment] 2019-05-02 04:38
Would be good to know if `arm` is likely to work on 1.2.

**Comment by terasakisatoshi** [comment] 2019-05-02 07:22
I updated my [gist above](https://github.com/JuliaLang/julia/issues/30870#issuecomment-488189564) to add google drive link to try Julia (v1.1.0) binaries for Raspberry Pi Series. These are generated using cross-compiling. (If there is a problem, Please let me know and I will delete the link).

**Comment by ViralBShah** [comment] 2019-05-02 12:47
Thanks @terasakisatoshi. First, I would like to check if our buildbots have these binaries, because if we do have arm binaries, then there is a streamlined process to get them uploaded to the julialang downloads page.

**Comment by staticfloat** [comment] 2019-05-02 20:52
@terasakisatoshi can you test out http://julialangnightlies.s3.amazonaws.com/pretesting/linux/armv7l/1.1/julia-80516ca202-linuxarmv7l.tar.gz please?  It doesn't pass the full test suite, but for your purposes it may be sufficient.

**Comment by terasakisatoshi** [comment] 2019-05-03 01:17
Hi, @staticfloat Thank you very much.

I tested your Julia 1.1.0 on my Raspberry Pi 3 model B+ with CUI environment i.e. Raspbian Lite.
There is no issue for my purpose (e.g. add some packages and use them). That is nice to me.

You can check out [my gist what I did](https://gist.github.com/terasakisatoshi/ae59137ef4995fa90ed8b4b62fa67bd8).
I also run [buffon.jl](https://gist.github.com/terasakisatoshi/11e76d62b642516ab2788e7bf569688d). It works fine.

**Comment by staticfloat** [comment] 2019-05-03 17:43
Here's a Julia v1.2: https://julialangnightlies.s3.amazonaws.com/pretesting/linux/armv7l/1.2/julia-8a84ba5018-linuxarmv7l.tar.gz

If that works for you on the same workload, I say let's add these to the official downloads.

**Comment by ViralBShah** [comment] 2019-05-03 17:49
My experience even when tests were not 100% passing was that you could still work with a lot of packages.

**Comment by robsmith11** [comment] 2019-05-03 21:24
I've been using a Linux AArch64 1.2 nightly on a daily basis for over a month without any problems.  I just built a 1.3 nightly yesterday, and it's passed my own package's tests as well.

**Comment by terasakisatoshi** [comment] 2019-05-04 02:28
@staticfloat
 
Your Julia 1.2.0 works O.K. (updated [what I did](https://gist.github.com/terasakisatoshi/ae59137ef4995fa90ed8b4b62fa67bd8)) except buffon.jl that checks parallel computation got worse performance (output result is O.K.).
However, it is worth adding download link for Arm 32-bit.

**Comment by ViralBShah** [comment] 2019-05-04 03:29
Just curious, if you are you able to produce a plot and use jupyter? I should fire up my Pi 3 as well this weekend.

**Comment by terasakisatoshi** [comment] 2019-05-04 06:01
@ViralBShah 

> if you are you able to produce a plot and use jupyter?

Technically, Yes. Plots.jl package depnds on GR.jl. Note that GR.jl does not prepare shared library for 32 bit system, so you should install GR runtime (, or you will fail `pkg> build Plots`) by reading/following [the document here](http://gr-framework.org/building.html#source-install-from-git).

You can refer my [Dockerfile](https://gist.github.com/terasakisatoshi/b61bb1228a7b0c7260fc8458cde8e68b) to reproduce environment that runs Plots.jl on your Raspberry Pi3. I've already created Docker image based on this Dockerfile [see my docker hub](https://cloud.docker.com/u/terasakisatoshi/repository/docker/terasakisatoshi/myjulia).

I believe ,it is not tested, replacing julia [1.0.3 which lives in Docker container](https://hub.docker.com/r/arm32v7/julia/) environment with julia-1.1.0 or julia-1.2.0-pre0 will work.

Enjoy your weekend with pi :D

**Comment by ViralBShah** [comment] 2019-05-04 13:26
Perhaps we can file an issue in Plots.jl. @jhinen will certainly help if possible.

**Comment by ViralBShah** [comment] 2019-05-04 13:56
For now, it seems we should put the 1.1 arm binaries on the downloads page from the buildbots and we can close this issue.

**Comment by jheinen** [comment] 2019-05-04 14:01
I could provide probably provide GR binaries if I had the 1.1 arm binaries for Julia. I'm currently on 0.6.2 on my pi ...

**Comment by eschnett** [comment] 2019-05-04 16:13
@jheinen That would be cool!

**Comment by terasakisatoshi** [comment] 2019-05-05 00:18
@jheinen 

I confirmed Plots.jl worked for the above 1.2.0-pre0 binary on my Raspberry Pi3.
 
Here is what I did:
 
1. [install dependency](http://gr-framework.org/building.html#source-install-from-git) and [build GR from source](https://github.com/sciapp/gr) on Raspberry Pi3
1. `julia -e 'using Pkg; Pkg.add("Plots")'`
1. `julia> using Plots; plot([1,2,3]); savefig("sample.png")`

**Closed** 2019-05-05 02:20 UTC
Labels: arm, build

**Comment by ViralBShah** [comment] 2019-05-05 02:22
Thanks everyone for the quick work here.

**Comment by ViralBShah** [comment] 2019-05-05 23:54
May I request some of the folks who chimed in here to test the status of the various open `arm` issues. Many are old, and may be fixed.
