### ISSUE TITLE
testset with for loop stops at first failed test

### ISSUE THREAD

**Issue by afniedermayer** [JuliaLang/julia#23375] opened 2017-08-21 12:34 UTC
The following shows only 1 failed test:
```julia
julia> @testset "foo $i" for i=1:3
         @test 2==3+i
       end
foo 1: Test Failed
  Expression: 2 == 3 + i
   Evaluated: 2 == 4
Stacktrace:
 [1] macro expansion at .\REPL[44]:2 [inlined]
 [2] macro expansion at .\test.jl:921 [inlined]
 [3] anonymous at .\<missing>:?
Test Summary: | Fail  Total
foo 1         |    1      1
Test Summary: | Fail  Total
foo 1         |    1      1
ERROR: Some tests did not pass: 0 passed, 1 failed, 0 errored, 0 broken.
```
However, if you manually write out the loop, all three tests are run:
```julia
julia> @testset "foo" begin
         @test 2==3+1
         @test 2==3+2
         @test 2==3+3
       end
foo: Test Failed
  Expression: 2 == 3 + 1
   Evaluated: 2 == 4
Stacktrace:
 [1] macro expansion at .\REPL[46]:2 [inlined]
 [2] macro expansion at .\test.jl:860 [inlined]
 [3] anonymous at .\<missing>:?
foo: Test Failed
  Expression: 2 == 3 + 2
   Evaluated: 2 == 5
Stacktrace:
 [1] macro expansion at .\REPL[46]:3 [inlined]
 [2] macro expansion at .\test.jl:860 [inlined]
 [3] anonymous at .\<missing>:?
foo: Test Failed
  Expression: 2 == 3 + 3
   Evaluated: 2 == 6
Stacktrace:
 [1] macro expansion at .\REPL[46]:4 [inlined]
 [2] macro expansion at .\test.jl:860 [inlined]
 [3] anonymous at .\<missing>:?
Test Summary: | Fail  Total
foo           |    3      3
ERROR: Some tests did not pass: 0 passed, 3 failed, 0 errored, 0 broken.
```
I don't think this is intended (see the discussion in #21594). If this is intended behavior, it should probably be better documented.

**Comment by fredrikekre** [comment] 2017-08-21 12:43
Soo... duplicate of #21594 ?

**Comment by afniedermayer** [comment] 2017-08-21 13:32
In my above example, there were nested testsets, yet it worked as intended:
```julia
@testset "foo" begin
  @testset "foo 1" begin
    @test 2==3+1
  end
  @testset "foo 2" begin
    @test 2==3+2
  end
end
```
Am I missing something?

**Comment by fredrikekre** [comment] 2017-08-21 13:35
That is *one* top level testset, when you use a for-loop you make 3 testsets, all of which are top level. So when the first one fails, the rest are not run.

**Comment by fredrikekre** [comment] 2017-08-21 13:38
From the OP; the "written out loop" becomes:
```julia
@testset "foo 1" begin
    @test 2==3+1
end
@testset "foo 2" begin
    @test 2==3+2
end
@testset "foo 3" begin
    @test 2==3+3
end
```
So when the first fail, the second is not run, same behavior as in #21594 :) I hope it makes it clear that it is the same issue?

**Closed** 2017-08-21 13:39 UTC

**Comment by StefanKarpinski** [comment] 2017-08-21 15:11
I think this is intentional behavior but it's unclear to me whether it should work like this.
