### ISSUE TITLE
nullable arrays regression regression due to #19760

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19827] opened 2017-01-02 23:41 UTC
https://github.com/JuliaLang/julia/pull/19760 caused a regression in nullable arrays performance; see this report:

https://github.com/JuliaCI/BaseBenchmarkReports/blob/88d896b0db239199f97014dad2444ed5a1ba6011/6d6ed95_vs_19f81ac/report.md

**Comment by Shade5** [comment] 2017-01-03 02:57
Any hint on how to start?

**Comment by StefanKarpinski** [comment] 2017-01-03 04:22
This is the benchmark that had a regression:

https://github.com/JuliaCI/BaseBenchmarks.jl/blob/4f6b7d5e66eec616a0cb08dbdee5dc9dbfbd52b4/src/nullable/NullableBenchmarks.jl#L135

The steps are:

0. Reproduce the regression and make sure it's real
1. Figure out how that change affected the performance of that benchmark
2. Figure out how to avoid that performance regression

Feel free to ask questions here while working on it.

**Comment by nalimilan** [comment] 2017-01-03 08:51
That's funny, since #19760 only touches `BitArray` code, but the `NullableArray` test type uses `Array{Bool}`...

**Comment by Shade5** [comment] 2017-01-04 03:03
These are the commands I executed. I got no error

```
julia> using BaseBenchmarks
julia> BaseBenchmarks.SUITE
julia> BaseBenchmarks.load!("nullable")
julia> run(BaseBenchmarks.SUITE["nullable"]["nullablearray"]);
```

**Comment by nalimilan** [comment] 2017-01-04 09:01
You're not supposed to get any error, the timings should just be different. See https://github.com/JuliaCI/BaseBenchmarks.jl

**Comment by Shade5** [comment] 2017-01-04 09:20
I don't get any output, what's the command to print output? Or is my series of commands incorrect?

**Comment by KristofferC** [comment] 2017-01-04 12:01
You don't need it. Please read through https://github.com/JuliaCI/BenchmarkTools.jl to be more familiar with the benchmarking system. In order for more people to learn from the answers I kindly suggest that further usage questions are directed to https://discourse.julialang.org.

**Comment by Shade5** [comment] 2017-01-05 15:02
Should I use `Nanosoldier` to benchmark?

**Comment by KristofferC** [comment] 2017-01-05 15:26
Let's continue the discussion at https://discourse.julialang.org/t/basebenchmark-comparing-pr-with-previous-commit/1303

**Comment by Shade5** [comment] 2017-01-05 17:09
Sure

**Comment by Shade5** [comment] 2017-01-06 08:34
This is the output I'm getting. I've compared master to just before #19760

```
52-element BenchmarkTools.BenchmarkGroup:
  tags: []
  ("perf_countequals","Array","Int64") => TrialJudgement(+0.08% => invariant)
  ("perf_countnulls","Array","Float32") => TrialJudgement(+0.00% => invariant)
  ("perf_countequals","NullableArray","Float64") => TrialJudgement(+0.00% => invariant)
  ("perf_sum","NullableArray","Float64") => TrialJudgement(-0.46% => invariant)
  ("perf_countnulls","Array","BigFloat") => TrialJudgement(-1.12% => invariant)
  ("perf_countnulls","Array","Complex{Float64}") => TrialJudgement(+0.34% => invariant)
  ("perf_sum","Array","BigFloat") => TrialJudgement(+6.62% => invariant)
  ("perf_countnulls","NullableArray","BigFloat") => TrialJudgement(-0.02% => invariant)
  ("perf_countnulls","NullableArray","Float64") => TrialJudgement(+0.00% => invariant)
  ("perf_countnulls","NullableArray","Int64") => TrialJudgement(+0.00% => invariant)
  ("
```perf_countequals","Array","Float32") => TrialJudgement(-0.59% => invariant)

**Comment by nalimilan** [comment] 2017-01-06 10:04
Thanks for checking. We should probably run Nanosoldier again to see whether the regression is reproducible there.

**Comment by Shade5** [comment] 2017-01-06 14:39
@nanosoldier `runbenchmarks("nullablearray", vs = "@c38a5a3044ffd62c585225a201422f95fd18f6dc")`

**Comment by vchuravy** [comment] 2017-01-06 15:46
You need to have commit access to run run nanosoldier, and I don't think you can do it from an issue. I just started a run from https://github.com/JuliaLang/julia/commit/5d90ab6f1407ff934825cfa234f8db378ec1161e#commitcomment-20387934

**Comment by Shade5** [comment] 2017-01-06 17:00
Cool, thanks

**Comment by Shade5** [comment] 2017-01-07 03:26
Nanosoldier gave no no performance regressions too

**Comment by Shade5** [comment] 2017-01-08 03:31
What do we do now?

**Comment by nalimilan** [comment] 2017-01-08 15:53
Looks like the regression actually appeared on master before https://github.com/JuliaLang/julia/pull/19760 was merged:
https://github.com/JuliaCI/BaseBenchmarkReports/blob/master/daily_2017_1_2/report.md

The relevant commit range is https://github.com/JuliaLang/julia/compare/1539061e7a9e51c2260e90aec6d1a29001624026...c38a5a3044ffd62c585225a201422f95fd18f6dc. I can see no obvious culprit the, but then the `broadcast` changes touch some fundamental code like `promote_op`. I guess we're going to have to check these commits individually...

**Comment by Shade5** [comment] 2017-01-11 13:35
Could it be noise like here: https://github.com/JuliaLang/julia/pull/19928#issuecomment-271702833

**Comment by tkelman** [comment] 2017-02-09 17:58
I'm going to propose closing this in favor of a targeted comparison of all regressions between 0.5 and 0.6 during feature freeze.

**Closed** 2017-02-09 17:59 UTC
Labels: nullable, performance, regression, up for grabs
