### ISSUE TITLE
docstrings for inner constructors are ignored

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#16730] opened 2016-06-03 01:26 UTC
```
julia> type Foo
       """some docs"""
       Foo() = new()
       end

help?> Foo
search: Foo floor pointer_from_objref OverflowError RoundFromZero FileMonitor

  No documentation found.

  Summary:

  type Foo <: Any
```

cc @MichaelHatherly

**Comment by MichaelHatherly** [comment] 2016-06-03 06:52
Dup of #14962 since the docstring isn't toplevel and so needs to use `@doc` directly:

```
julia> type Foo
           @doc """some docs""" ->
           Foo() = new()
       end

help?> Foo
search: Foo floor pointer_from_objref OverflowError RoundFromZero FileMonitor

  some docs
```

Perhaps we should consider extending where `@doc` is added automatically since this does come up quite often.

**Comment by IagobaApellaniz** [comment] 2016-06-03 13:55
Would be nice to have it automatically on the inner constructors. They are indeed methods on the global scope.

**Comment by tkoolen** [comment] 2018-10-30 00:19
It seems the `->` is still necessary in order to attach the docstring to an inner constructor. However, that syntax is now deprecated:

```julia
┌ Warning: Deprecated syntax `@doc call with ->`.
│ Use `a line break` instead.
└ @ none:24
```

Could this issue be fixed before removing the deprecated method?

**Comment by tpapp** [comment] 2018-11-09 09:09
At the moment, in `v1.0`
```julia
struct Foo
    @doc "best inner constructor ever"
    Foo() = new()
end
```
works fine.

**Comment by cossio** [comment] 2022-01-31 02:17
This is still an issue in Julia v1.7

**Comment by LilithHafner** [comment] 2023-05-14 16:30
I believe this is still an issue as of 1.9 and should be fixed. Closing as duplicate of #14962.

**Closed by LilithHafner** 2023-05-14 16:30 UTC
Labels: docsystem
