### ISSUE TITLE
Selective use of `using` defeats TAB completion in REPL

### ISSUE THREAD

**Issue by david-macmahon** [JuliaLang/julia#49595] opened 2023-05-02 06:52 UTC
This TAB completion works:
```Julia
julia> using Statistics

julia> mea<TAB> # completes "mean"

julia> mean(<TAB> # shows methods
```
But this TAB completion does not:
```Julia
julia> using Statistics: mean

julia> mea<TAB> # does not complete "mean" <-- WHY?

julia> mean(<TAB> # shows methods
```
It seems like all of these cases should work, including the one that doesn't (marked "WHY?").

**Comment by jakobnissen** [comment] 2023-05-02 06:57
Duplicate of #49109

**Closed by jakobnissen** 2023-05-02 06:57 UTC
