### ISSUE TITLE
ERROR: syntax: ssavalue with no def

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#32032] opened 2019-05-15 07:03 UTC
I get the error quoted in the title for this short line of code:
```
f((a -> a,); b=1)
```
in a fresh REPL. `versioninfo()`:
```
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_VERSION = 1.1.0
  JULIA_NUM_THREADS = 12
```
As @vchuravy says on [discourse](https://discourse.julialang.org/t/error-syntax-ssavalue-with-no-def/24220/6), this reproduces on 1.1 version, but not on master.

**Comment by c42f** [comment] 2019-05-15 07:25
This doesn't reproduce on 1.0.2

```
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by KristofferC** [comment] 2019-05-15 10:15
Removing labels beause I missed:

> As @vchuravy says on discourse, this reproduces on 1.1 version, but not on master.

**Comment by JeffBezanson** [comment] 2019-05-15 15:40
Fixed by 4eb63085f136868a2296ca28654e3f40cdd068e6 and 553082495c46e851db1d287c917963b408e0db6e.

**Comment by ararslan** [comment] 2019-05-15 19:21
Should we hold 1.1.1 for this? I haven't moved forward with it yet.

**Comment by KristofferC** [comment] 2019-05-15 19:38
I don't think so, no.

**Comment by ruizhi92** [comment] 2019-06-03 17:57
Any updates on what's the cause of this error message? It doesn't even direct me to the line of code that cause this problem

**Comment by JeffBezanson** [comment] 2019-06-03 19:59
This was a bug that has been fixed. Awaiting backporting to 1.1.x.

**Closed by JeffBezanson** 2019-06-03 19:59 UTC
