### ISSUE TITLE
We need more `unique` and related methods

### ISSUE THREAD

**Issue by gajomi** [JuliaLang/julia#14649] opened 2016-01-11 23:06 UTC
There is quite a bit of room to add optimized `unique` methods. The only extant single argument `unique` method `unique(C) at set.jl:107` explicitly loops through all the elements of `C` to build up the unique result, and so has cost proportional to the length `C`. However, in the case of ranges, something like

``` julia
unique{T}(x::Range{T}) = x
```

reduces the cost to `O(1)`, which could improve performance in a number of places (for example see #14004 and the fix at 75336c670e87e991de530531b9ebf2aebdfc18b2). 

Some of the optimizations that apply to `unique` also benefit `Set` construction (or methods involved therein), and will be noted.

I am planning to make a PR to implement these kinds of optimizations, and would like to use this issue to list out types where this optimization would be helpful. The checked off features in the list below refer to working implementations in this [branch](https://github.com/gajomi/julia/tree/moreuniquemethods) (I didn't think I should make a feature request until the branch was feature complete).

Targets:
- [x] `Range` types (maximally trivial assuming zero step sizes disallowed) a872404cfd0bab0d363a974b23fc3efe072e2c3f
- [x] `Dict`, `Set` and `IntSet` types (trivial cases) 990a4438c7e34b6b423ca6e132720e1229ce8ea2
- [x] `AbstractArray{Bool}`, `AbstractArray{Int8}` and other `AbstractArray{T}` with "small" bounds on total unique elements. Build up of unique list terminates when all possible elements are seen. Also applies to `union!(s::Set{T},AbstractArray{T})` methods, which are used in `Set` construction, among other things. c8b02c4871d3c15d3e8bc0f04e784e6e60351f95
- [x] `Diagonal`,`Tridiagonal` and other matrices with many repeated structural zeros 5d0e097986b85e36a0f8840e521e4a0f700c0fd1

...and possibly more? If you have a target in mind please leave a comment.

**Comment by tkelman** [comment] 2016-01-11 23:49
Can't ranges possibly have step 0?

**Comment by gajomi** [comment] 2016-01-12 00:33
They can indeed. But as far as I can tell this doesn't impact the correctness of the `unique` implementation above.
Example
```julia
julia> x = 1.:0.1:1.
1-element FloatRange{Float64}:
 1.0

julia> unique(x) == unique(collect(x))
true
```

**Comment by gajomi** [comment] 2016-01-12 00:39
Well I guess you can have
```julia
julia> x = 0:0
1-element UnitRange{Int64}:
 0
```
in which case the `unique` optimization above gives the correct behavior
```julia
julia> unique(x)
1-element Array{Int64,1}:
 0
julia> unique(x) == unique(collect(x))
true
```

I tried constructing float range with zero step sizes but got error that told me I could not. Curious though, in the above example `x = 0:0` I find
```julia
julia> step(x)
1
```
which is possibly a bug?

**Comment by gajomi** [comment] 2016-01-12 00:45
OK, I guess I wasn't trying hard enough. If you make a call to the `range` function you can get
```julia
julia> range(1,0.,3)
3-element FloatRange{Float64}:
 1.0,1.0,1.0
```
such that Ranges wont; be identically unique. Adding some logic to check for `zero` valued step sizes would be an easy fix.

**Comment by vtjnash** [comment] 2016-01-12 04:23
i think that is a lack of error checking on the part of the float range constructor -- a step of zero isn't logical so it is probably a user bug. the same arguments as Integers throw an argument error:
```
julia> range(1, 0, 3)
ERROR: ArgumentError: step cannot be zero
```

**Comment by gajomi** [comment] 2016-01-12 05:29
@vtjnash - so are you are saying that `range(1,0.,3)` should also be an error? I agree that this would seem to be the logical thing to do.

I am interested to know what other actually think should be done though, and have gone on a hunt for relevant discussions. Issues about ranges are `myriad`. I see a bunch of commits here #3121 referring to zero sized steps. There is an umbrella issue some time later #5585. Perhaps someone knows of an issue specific to step sizes equal to zero?

**Comment by nalimilan** [comment] 2016-01-12 09:27
I agree that `range(1,0.,3)` should throw an error.

**Comment by hayd** [comment] 2016-01-13 04:49
I think zero step should be allowed. Specifically that'd fix #10391... That issue also mentions:

    (1:5) * 0

**Comment by hayd** [comment] 2016-01-13 05:18
That also allows `zero` and `one` to be special cased... and 0(1).

**Comment by hayd** [comment] 2016-01-13 19:22
I think the issue is that SteppedRange doesn't allow a len, whereas FloatRange does. The options IMO:

1. disallow 0 step ranges consistently
2. add a length field to SteppedRange
3. introduce a ConstantRange type (this means that some methods will be type unstable)

Not sure what is the best, although this should probably be it's own issue.

**Comment by gajomi** [comment] 2016-01-19 01:45
Well it seems like there is some interest, so I started working on the feature(s). In the process of working on this it seemed reasonable to slightly expand the scope of the issue to other methods that are doing stuff closely related to `unique`. I have edited the original comment to highlight this fact and provided links to the branch where this work is taking place.

**Comment by gajomi** [comment] 2016-02-10 01:13
Pull request with features described above at #15009.

**Comment by kshyatt** [comment] 2016-05-10 00:14
@gajomi I see all the boxes are checked. Is it just that open PR that you need to finish before this issue can be closed?

**Comment by kshyatt** [comment] 2017-01-26 00:20
I'm closing this since it's been nearly a year. Reopen if there's more to add here.

**Closed by kshyatt** 2017-01-26 00:20 UTC
Labels: performance

**Comment by hayd** [comment] 2017-01-26 02:00
But #15009 is still open... I don't think this has been resolved yet.
