### ISSUE TITLE
Disallow partial matching in CLI options

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#56010] opened 2024-10-05 23:42 UTC
Currently prefixes of existing options are permitted on the CLI, so `--startup` works for `--startup-file`. 

Partial matching constrains the ways the CLI can be modified in the future. For example any prefix of a current option cannot safely be made a new option in case it takes over the behavior of a script that's using that partial match.

We have tab-completion and short options like `-p` so this kind of shortcut shouldn't be necessary. 

I suggest deprecating and removing partial matching.

**Comment by IanButterworth** [comment] 2024-10-05 23:57
IMO it's a highly convenient feature for interactive use, and I very much doubt people are using it in non-interactive julia invokes.

Perhaps there should be a docs note about it warning against using short forms outside of interactive use.

> We have tab-completion and short options like -p

My terminal doesn't tab complete julia args. Is that a thing in some terminals?

**Comment by jariji** [comment] 2024-10-06 00:15
I use https://github.com/zsh-users/zsh-autosuggestions which gets suggestions from my shell history. However it would be nice for `julia` to natively provide shell completion like other executables do, so I've opened https://github.com/JuliaLang/julia/issues/56012.

**Comment by fredrikekre** [comment] 2024-10-06 05:04
Duplicate of [#29669](https://github.com/JuliaLang/julia/issues/29669)

**Closed by fredrikekre** 2024-10-06 05:04 UTC
Labels: duplicate
