### ISSUE TITLE
Outline all asserts (and throws?)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#35221] opened 2020-03-22 15:48 UTC
A.
All `@assert`s should be exceptional, and since it's a macro already, it should outline (`@noinline`) automatically, as was manually done here (to avoid 3x speed regression):

https://github.com/JuliaLang/julia/pull/34237/files

B.
I was looking into optimizing factorial myself, and think in general throws should be outlined too, i.e. all preconditions. For now A. is a low hanging-fruit I think. I'm not sure, possibly after A. is done, throws can be implemented with asserts, getting B for free?

C.
Maybe there are complications when there are two or more asserts and/or throws, still I doubt solving A. and/or B. would be slower then. However possibly in that case something even better could be done?

**Comment by JeffBezanson** [comment] 2020-03-22 20:17
Duplicate of #29688. For assert though, I think it could be implemented entirely inside the macro, since the macro knows all the code that needs to run leading up to the `throw` (constructing the exception object).

**Closed by JeffBezanson** 2020-03-22 20:17 UTC

**Comment by NHDaly** [comment] 2025-01-21 23:51
A PR to do this just for assert, as you point out here: https://github.com/JuliaLang/julia/pull/57122
