### ISSUE TITLE
Stacktraces do not show recursive call

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#36787] opened 2020-07-24 01:18 UTC
In Julia 1.5-rc1, recursive calls were easy to find in the stacktrace:

```julia
julia> @noinline countdown(x = 10) = x == 0 ? error("hi") : countdown(x - 1)
countdown (generic function with 2 methods)

julia> countdown()
ERROR: hi
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] countdown(::Int64) at ./REPL[1]:1 (repeats 12 times)
 [3] top-level scope at REPL[2]:1
```

See `(repeats 12 times)` in the above stacktrace.

On the other hand, in Julia 1.6.0-DEV.503, there is no indication of recursive calls:

```julia
julia> countdown()
ERROR: hi
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] countdown(x::Int64)
   @ Main ./REPL[69]:1
 [3] top-level scope
   @ REPL[70]:1
```

It'd be great if we can bring back something like `(repeats 12 times)` in the old stacktrace printing.

cc @jkrumbiegel

**Comment by simeonschaub** [comment] 2021-02-12 17:58
Duplicate of #37587

**Closed by simeonschaub** 2021-02-12 17:58 UTC
