### ISSUE TITLE
T<:Union{Integer, Missing} loses Missing

### ISSUE THREAD

**Issue by nalimilan** [JuliaLang/julia#26405] opened 2018-03-10 15:50 UTC
This used to work on Julia 0.6.2, but on master `Missing` is lost:
```julia
julia> f(::Type{T}) where {T<:Union{Integer, Missing}} = T
f (generic function with 1 method)

julia> f(Union{Missing, Int})
Int64
```

**Comment by affans** [comment] 2018-03-11 20:01
This dosnt work on my 0.6.2, Windows. What am i doing wrong?

```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

julia>  f(::Type{T}) where {T<:Union{Integer, Missing}} = T
ERROR: UndefVarError: Missing not defined
```

**Comment by JeffBezanson** [comment] 2018-04-03 20:33
Duplicate of #25240

**Closed by JeffBezanson** 2018-04-03 20:33 UTC
Labels: bug, regression, types and dispatch
