### ISSUE TITLE
setindex! no longer inlined for rank N>6

### ISSUE THREAD

**Issue by Jutho** [JuliaLang/julia#9622] opened 2015-01-05 15:25 UTC
I just noticed this today on latest master (Version 0.4.0-dev+2498), I guess this must be regression?

``` julia
f6(A)=(A[1,1,1,1,1,1]=1.)
f7(A)=(A[1,1,1,1,1,1,1]=1.)
code_typed(f6,(Array{Float64,6},))
code_typed(f7,(Array{Float64,7},))
```

returns

```
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:A], Any[Any[],Any[Any[:A,Array{Float64,6},0]],Any[]], :(begin  # none, line 1:
        (top(arrayset))(A::Array{Float64,6},1.0,1,1,1,1,1,1)::Array{Float64,6}
        return 1.0
    end::Float64))))
```

versus

```
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[:A], Any[Any[],Any[Any[:A,Array{Float64,7},0]],Any[]], :(begin  # none, line 1:
        setindex!(A::Array{Float64,7},1.0,1,1,1,1,1,1,1)::Any
        return 1.0
    end::Float64))))
```

Consequently, indexing into an array of rank>6 becomes slow.  Indexing with a `CartesianIndex` could be fixed by letting the `stagedfunction` generate the `arrayset` call automatically, but I guess this also needs to be fixed for normal indexing?

**Comment by Jutho** [comment] 2015-01-05 15:26
For `getindex`, inlining stops for `N>7`.

**Comment by timholy** [comment] 2015-01-05 15:51
Dupe of #5393. Jeff closed that, but I'm not sure it's redundant with anything else, so perhaps we should leave this open.

As @simonster said there,
> I think performance drops because MAX_TUPLETYPE_LEN in inference.jl is 8, which appears to prevent getindex from getting inlined when it is passed >8 arguments.

**Comment by Jutho** [comment] 2015-01-05 15:55
I thought I had seen something like this before, but couldn't find it. Thanks. Ok then, I hope you agree that we should at least change indexing with `CartesianIndex` to immediately return the `arrayref` and `arrayset` instruction, so as to have at least one way of fast indexing?

**Comment by Jutho** [comment] 2015-01-05 15:59
Although with the `@inline` macro and/or `stagedfunctions` it should also be possible to make `getindex` and `setindex!` fast, no?

**Comment by timholy** [comment] 2015-01-05 16:59
I certainly support doing something (whatever seems best) to make this fast.

**Comment by mbauman** [comment] 2015-06-12 17:35
Hm, this got worse after #10525.  Inlining now stops for rank N>4.  I'll try to look into this one a bit more.

**Comment by mbauman** [comment] 2015-06-20 03:04
Ah, found it.  We're still one-worse than we were since I dispatch to an internal function that has one more argument (to specify the `LinearIndexing` trait), and so we hit `MAX_TUPLETYPE_LEN` one dimension sooner.

**Comment by matthieugomez** [comment] 2015-07-14 01:30
I encountered this issue. If it's hard to solve now, a warning would be nice - it was hard to pinpoint the source of the problem in my code.

**Comment by KristofferC** [comment] 2017-01-22 12:17
This seems fixed now,

```jl
julia> code_typed(f10,(Array{Float64,10},))
1-element Array{Any,1}:
 CodeInfo(:(begin 
        (Base.arrayset)(A,(Core.typeassert)(1.0,Float64)::Float64,1,1,1,1,1,1,1,1,1,1)::Array{Float64,10}
        return 1.0
    end))=>Float64
```

Please repoen if this is still a problem.

**Closed by KristofferC** 2017-01-22 12:17 UTC
Labels: performance
