### ISSUE TITLE
`mean(skipmissing(x))` is imprecise

### ISSUE THREAD

**Issue by tiemvanderdeure** [JuliaLang/julia#56456] opened 2024-11-05 10:03 UTC
The generic fallback for `mean` can give wrong results in some cases. Maybe it would be a good idea to add a specialized implementation when it is called on a `SkipMissing`, as there is for `sum`. The easiest way to do this would be to pass a function that computes both `sum` and `count` to `mapreduce`.

```julia
A = rand(Float32, 1_000_000) .+ 1f6
mean(skipmissing(A)) ≈ mean(A) # false
mean(A) ≈ (sum(skipmissing(A)) / length(A)) # true
```

Related: https://github.com/JuliaLang/julia/issues/30421

**Comment by mikmoore** [comment] 2024-11-05 15:08
Basically a duplicate of #52365. #52397 would fix this.

**Comment by mbauman** [comment] 2024-11-05 15:11
Duplicate of #52365

**Closed by mbauman** 2024-11-05 15:11 UTC
