### ISSUE TITLE
`mapreduce` doesn't support the conbination of general `op`, `_InitialValue` and `dim`

### ISSUE THREAD

**Issue by putianyi889** [JuliaLang/julia#52188] opened 2023-11-16 16:01 UTC
```julia
julia> y = fill(1.0, 3, 4);

julia> op(x,y) = x^2 + 3y;

julia> [mapreduce(identity, op2, y[:,k]) for k in 1:4]' # works without dim argument
1×4 adjoint(::Vector{Float64}) with eltype Float64:
 19.0  19.0  19.0  19.0

julia> mapreduce(identity, op2, y; init=0.0, dims=(1,)) # works with initial value
1×4 Matrix{Float64}:
 147.0  147.0  147.0  147.0

julia> mapreduce(identity, op2, y; dims=(1,))
ERROR: MethodError: no method matching reducedim_init(::typeof(identity), ::typeof(op2), ::Matrix{Float64}, ::Tuple{Int64})

Closest candidates are:
  reducedim_init(::Any, ::typeof(min), ::AbstractArray, ::Any)
   @ Base reducedim.jl:128
  reducedim_init(::Any, ::typeof(max), ::AbstractArray, ::Any)
   @ Base reducedim.jl:128
  reducedim_init(::Any, ::typeof(&), ::Union{Base.AbstractBroadcasted, AbstractArray}, ::Any)
   @ Base reducedim.jl:206
  ...

Stacktrace:
 [1] _mapreduce_dim(f::Function, op::Function, #unused#::Base._InitialValue, A::Matrix{Float64}, dims::Tuple{Int64})
   @ Base .\reducedim.jl:371
 [2] #mapreduce#800
   @ .\reducedim.jl:357 [inlined]
 [3] top-level scope
   @ REPL[70]:1
```

**Comment by jishnub** [comment] 2023-11-16 16:32
Duplicate of https://github.com/JuliaLang/julia/issues/45566 I think

**Closed** 2023-11-16 16:45 UTC
