### ISSUE TITLE
AbstractArray(::Array) constructor no longer works

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#26867] opened 2018-04-20 15:36 UTC
Not sure if this is intentional, but it's different behaviour from v0.6.2:
```julia
julia> AbstractArray(randn(10,10))
ERROR: MethodError: no method matching AbstractArray(::Array{Float64,2})
Closest candidates are:
  AbstractArray(::Any) where T<:AbstractArray at abstractarray.jl:22
  AbstractArray(::Union{QR, LinearAlgebra.QRCompactWY}) at /Users/solver/Projects/julia7/usr/share/julia/site/v0.7/LinearAlgebra/src/qr.jl:427
  AbstractArray(::QRPivoted) at /Users/solver/Projects/julia7/usr/share/julia/site/v0.7/LinearAlgebra/src/qr.jl:434
  ...
Stacktrace:
 [1] AbstractArray(::Array{Float64,2}) at ./abstractarray.jl:22
 [2] top-level scope
```

`AbstractArray{Float64}(randn(10,10))` works as expected, without error.

**Comment by fredrikekre** [comment] 2018-04-20 15:40
duplicate of your own issue #26177

**Closed by fredrikekre** 2018-04-20 15:40 UTC
