### ISSUE TITLE
[Feature Request] Multiple values from NamedTuple

### ISSUE THREAD

**Issue by kescobo** [JuliaLang/julia#38834] opened 2020-12-11 15:27 UTC
I think it would be useful to have some syntax for returning a subset of a `NamedTuple` as another `NamedTuple`, analogous to the same ability with regular `Tuple`s.

```
julia> tup = (1, 2, 3)
(1, 2, 3)

julia> tup[1]
1

julia> tup[[1,2]]
(1, 2)

julia> tup[[1]]
(1,)

julia> nt = (a=1, b=2, c=3)
(a = 1, b = 2, c = 3)

julia> nt[:a]
1

julia> nt[[:a, :b]]
ERROR: MethodError: no method matching getindex(::NamedTuple{(:a, :b, :c), Tuple{Int64, Int64, Int64}}, ::Vector{Symbol})
```

The following works, though I don't know if it's the most efficient:

```
julia> get(n::NamedTuple, ntkeys) = (; (s=>n[s] for s in ntkeys)...)
get (generic function with 2 methods)

julia> get(nt, [:a,:b])
(a = 1, b = 2)

julia> get(nt, [:a])
(a = 1,)
```

I'm not advocating it actually be called `get` - I think something that worked with `getindex` would be ideal. NamedTupleTools.jl [has a method called `select`](https://github.com/JeffreySarnoff/NamedTupleTools.jl/blob/master/src/NamedTupleTools.jl#L260-L270) that does this, but it seems like this functionality would be great to have in Base.

One counter argument is that this doesn't work with `Dict`s

```
julia> dict = Dict(pairs(nt)...)
Dict{Symbol, Int64} with 3 entries:
  :a => 1
  :b => 2
  :c => 3

julia> dict[[:a, :b]]
ERROR: KeyError: key [:a, :b] not found
```

But it is technically possible to have an array as a key in a `Dict`, but not for a `NamedTuple`.

I'm happy to make a PR if this idea is acceptable, and if there aren't any implications that are escaping me.

**Comment by kescobo** [comment] 2020-12-11 15:38
Another suggestions from slack helpdesk:

```
julia> NamedTuple{sel}((nt[k] for k in sel))
(a = 1, b = 2)
```

**Comment by JeffBezanson** [comment] 2020-12-11 16:14
The correct way to do it currently is
```
julia> nt = (a=1, b=2, c=3)

julia> NamedTuple{(:a, :b)}(nt)
(a = 1, b = 2)
```
i.e. the generator there is just redundant.

We could maybe define
```
@inline getindex(nt::NamedTuple, s::Tuple{Vararg{Symbol}}) = NamedTuple{s}(nt)
```
though this also conflicts with Dicts unfortunately.

**Comment by kescobo** [comment] 2020-12-11 16:53
> though this also conflicts with Dicts unfortunately.

Do you mean conceptually or literally? `Dict`s aren't a subtype of `NamedTuple`, right?

`NamedTuple{(:a, :b)}(nt)` is a little clunky, but if adding the `getindex` method is problematic, perhaps just making it clearer in the docs so it's easier to find. I had looked [here](https://docs.julialang.org/en/v1/manual/functions/#Named-Tuples), [here](https://docs.julialang.org/en/v1/manual/types/#Named-Tuple-Types), and the docstring for `NamedTuple`. It turns out that it **is**
in the docstring

```
NamedTuple{names}(nt::NamedTuple)

  Construct a named tuple by selecting fields in names (a tuple of Symbols) from another named tuple.
```

but I guess because this signature is so dissimilar from the types of selection syntax I'm used to, I skimmed past it.

**Comment by JeffBezanson** [comment] 2020-12-11 19:22
I guess we could add the `getindex` method.

**Comment by JeffreySarnoff** [comment] 2021-01-10 05:46
> though this also conflicts with Dicts unfortunately.
afaik The conflict is limited to Dicts with key[s] that are typed  `NTuple{N,Symbol}`.
`NamedTuples` cannot have fieldnames that are typed `NTuple{N,Symbol}`.

I do not find the conflict all that concerning. If the desire is for conflict-free `getindexing`, there are two approaches that occur to me.  Introduce `getindicies` that would require key[s] to be given as a Tuple, which would disambiguate the case of a key that is a tuple. Or use the dotted form of `getindex` which also presents the key[s] contained in a tuple.

**Comment by JeffBezanson** [comment] 2021-03-22 16:46
duplicate of #27021

**Closed by JeffBezanson** 2021-03-22 16:46 UTC
