### ISSUE TITLE
package interactions

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#2025] opened 2013-01-12 22:52 UTC
Especially in the presence of multiple dispatch, there are situations where there exists glue code that you want to load only when using both of two packages. For example, the k-nearest neighbors algorithm makes perfect sense to apply just to plain old matrices – but of course one _also_ wants it to work for data frames, data matrices and various other containers of data. Currently the only way to make this work is to have the [kNN package](https://github.com/johnmyleswhite/kNN.jl) depend on DataFrames and add the appropriate DataFrame-specific methods. This is going to get out of hand very quickly.

I can think of two solutions. One way is to write the kNN code in a more generic fashion so that it isn't coupled with the DataFrames package but uses an interface for containers of data which DataFrames happens to provide. This is generally a good idea, but I kind of suspect that it may be rather hard to make work in all cases. The other way is to provide a mechanism for loading glue code only when both kNN and DataFrames are loaded.

**Comment by StefanKarpinski** [comment] 2017-10-19 19:01
The plan for glue modules:

1. A module that glues `A` and `B` together is some module, say, `AB` which depends on `A` and `B`; it is not inside of module `A` or module `B`, it is an external module that depends on them.

2. We need some mechanism for registering (with Julia) that whenever `A` and `B` are both loaded, the code for the glue module `AB` will also be loaded.

3. Some way of making it possible for the code for `AB` to live inside of the repo of `A` or the repo of `B`, this will be addresses as part of Pkg3.

4. The ability to express in package registries, that if an environment includes `A` and `B` for certain versions of these package, then it also depends on `AB` with compatibility constraints between all the versions of the three packages. Normal package resolution will then guarantee that when `A` and `B` are both present in an environment, `AB` will as well.

I'm putting this issue on the 1.0 milestone instead of https://github.com/JuliaLang/julia/issues/6195, which is a particular implementation we're not doing, and https://github.com/JuliaLang/julia/pull/21743 which is another implementation we're not doing.

**Comment by MikeInnes** [comment] 2017-10-20 10:07
Just to point out – this will be a great replacement for Requires.jl, which is good at connecting two interfaces together. It won't help us with "backend-like" conditional dependencies of the kind that Plots has or Flux used to have, or that are coming up in GPU work, where package `B` provides an implementation but not an interface.

Of course, that might only be a trivial extension of this system, e.g. change the rule to "if `A` is loaded and `B` is installed / available".

**Comment by StefanKarpinski** [comment] 2017-10-20 17:37
It kind of does help even with that, e.g.:

```jl
using MLFramework, CuArrays
# when both are present `MLFramework_CuArrays` glue package is loaded
```

The glue package can do things like set the backend for `MLFramework`. However, it's a little weird that `CuArrays` might never be used but it's mere loading affects the behavior of `MLFramework`. Wouldn't it be better for them both being loaded to introduce code that allows `CuArrays` to be selected as a backedn for `MLFramework`, but still require `MLFramework.backend(CuArrays)` or something like that to actually activate the backend?

**Comment by StefanKarpinski** [comment] 2017-10-20 17:40
> "if `A` is loaded and `B` is installed / available"

This is a bit vague. As I remarked on the triage call, "having a package decide what to do based on some nebulous, ill-defined condition of your hard drive seems like a very bad idea". @Keno suggested that "installed / available" could be taken to mean "in your project / manifest", which would be a somewhat reasonable possibility, but I think I'd prefer some kind of global configuration mechanism (which could be included in the project file).

**Comment by MikeInnes** [comment] 2017-10-21 09:03
Sure, that case isn't an issue because `B` is providing an interface (the `CuArray` type itself). I'm thinking more of cases that currently look like:

```julia
Flux.convert_to_mxnet(model)
Plots.use_gadfly_backend()
```

In these cases it's less obvious how to frame this as tying a function to a type. You could just dispatch on a reasonable type from the backend (e.g. `backend(Gadfly.Plot)`, like your suggestion above), but this requires some coordination with backends to make it consistent. In Flux's case I could have done:

```julia
Flux.convert_model(TensorFlow.Tensor, model)
Flux.convert_mode(MXNet.SymbolicNode, model) # Or MXNet.NDArray?
```

But aside from being unpredictable, this unnecessarily exposes an implementation detail of the backend that users wouldn't see otherwise. Again you have to coordinate and define an interface, which is what this was supposed to avoid in the first place.

This is nowhere near as common or important as the Requires.jl use case, I'm just raising the flag for reference.

**Comment by Nosferican** [comment] 2017-11-05 09:34
I kind of favor a mixed approach. For example, in R `dtplyr` is the glue package for `dplyr` and `data.table`. It makes sense for the glue package to operate at this level since one provides most of the data manipulation / wrangling for dataframes and `data.table` provides the dataframe struct. However, I much rather have a `StatsBase` like solution. One package provides a unified API / framework and each package can implement the necessary methods for their structs. For example, if I provide a child of `StatsBase.RegressionModel` with all applicable methods in the API another package should be able to interact with any of my structs without any issues operating at the abstract level. I fear that providing a glue solution would incentivize writing at structs level when it would optimal to encourage methods at the abstract level.

**Comment by lobingera** [comment] 2017-12-12 15:04
Is there some visible development on this?

**Comment by JeffBezanson** [comment] 2017-12-31 00:22
I believe at this point this can and needs to be added as a feature in 1.x.

**Comment by bjarthur** [comment] 2017-12-31 00:32
so the 30-sec wait until display of first plot in Gadfly waits until then?

**Comment by JeffBezanson** [comment] 2017-12-31 01:06
I don't believe that delay is related to conditional dependencies? Am I missing something?

**Comment by ChrisRackauckas** [comment] 2017-12-31 01:32
Yes, Gadfly doesn't even have conditional dependencies. It doesn't use Requires.jl and it doesn't `@eval using` statements (which is Plots.jl's issue). Gadfly's first time to plot is completely orthogonal to this and just due to precompilation not capturing most of what users "think it would/should".

**Comment by lobingera** [comment] 2017-12-31 08:13
@ChrisRackauckas Just for the record, Gadfly renders via Compose and Compose has some infrastructure like https://github.com/GiovineItalia/Compose.jl/blob/master/src/Compose.jl#L30-L47, so you're technically right that Gadfly doesn't have conditional dependencies, but it depends on it ...

**Comment by ChrisRackauckas** [comment] 2017-12-31 08:19
Interesting. I didn't know Compose did that. Then it is the same problem as Plots.jl. Why does it have to be lazy though? It's the lazy loading part that makes it difficult.

**Comment by lobingera** [comment] 2017-12-31 09:41
Maybe we see (compared to Plots.jl) some covergence here: similar problems bounded by the same constraints lead to similar solutions. Compose actually manages two backends, a homegrown SVG and a link to Cairo for other formats. 

That's why i'm interested in these glue packages, because with them you could do optional dependencies at the time when precompilation happens. And not at some abstract runtime

**Comment by ChrisRackauckas** [comment] 2017-12-31 12:39
The ideas for fixing Plots.jl backends is much simpler than having some kind of Base hook for conditional deps. Instead its to pull in the backends with `using` and work off of that syntax, i.e. `using PlotsGR` instead of `gr()` doing that kind of stuff, and then having it add new dispatches to core functions using some abstract type. I think that's a sane thing to do and it fixes the precompilation problem. It just requires a re-write of the backend code to do it.

**Comment by lobingera** [comment] 2017-12-31 12:52
> It just requires a re-write of the backend code to do it.

What do you mean by **just**? Isn't that just giving up on modularizaion (which is (imho) re-using code without changing it)?

**Comment by ChrisRackauckas** [comment] 2017-12-31 12:57
No. It's putting the backend code into a separate package like `PlotsGR` and having that implement a documented function interface by implementing dispatch on a concrete subtype of some abstract backend dispatching type. It's more modular and allows more code re-use, at the cost of having to have the backend code in a separate repo. But if Pkg3 can handle separate submodules in the same package well (with precompilation), then it can be one repo.

**Comment by lobingera** [comment] 2017-12-31 13:02
Sorry, i'm lost. I thought, that the backend code is already in a separate package (i.e. GR.jl). And in your example, isn't the PlotsGR the abovementioned glue package? And when is the decision taken to execute/precompile PlotsGR?

**Comment by ChrisRackauckas** [comment] 2017-12-31 13:05
When the user calls `using PlotsGR`. That would be how a backend is chosen, then the package's init call could set a global in Plots to make the backend choice reflected in the latest using. Then each `plot` call can  have an optional argument passing through this global that says what the current backend is in terms of a type, and then core functions can be overloaded for specific backends by new dispatches in PlotsGR. So the decision to execute PlotsGR code is done when the user calls `using PlotsGR`, and the code to precompile are the new dispatches.

**Comment by timholy** [comment] 2018-07-08 19:43
Now that we have `Base.package_callbacks` as a "blessed" interface, in my opinion https://github.com/MikeInnes/Requires.jl/pull/46 seems like a non-objectionable solution to the other half of this problem. If that gets merged then perhaps we can close this.

**Comment by nalimilan** [comment] 2018-07-10 08:44
@timholy That sounds great. Could you explain a bit what that PR does? Does it fix all issues with the approach currently adopted by Requires?

**Comment by timholy** [comment] 2018-07-10 12:45
At one time Requires did a lot of "sneaky stuff" (i.e., overwrite methods in Core and Base), but over time it has worked more harmoniously with base julia; in particular, the addition of `Base.package_callbacks` in 0.6 gave us an official interface for calling a function whenever a new package has been loaded. The [interface for a package callback](https://github.com/JuliaLang/julia/blob/092b6c906c77187d391b3f8d5f6000d0ba08716e/base/loading.jl#L704-L706) is `f(id::Base.PkgId)`, thus passing information to the callback about which package just got loaded. The entire list of callbacks [gets called every time you load a new package](https://github.com/JuliaLang/julia/blob/092b6c906c77187d391b3f8d5f6000d0ba08716e/base/loading.jl#L840-L842). You'll note a comment that the interface was marked as experimental, but it hasn't changed during the entire 0.7 cycle (lots of stuff about loading *has* changed, but not the `package_callbacks` interface) and since we're about to release I think we can consider it safe. At least Revise.jl uses the same interface, so Requires is not the only consumer.

All this is provided by Base; now, on to Requires. First, let me describe the state of Requires master, which is largely the work of @MikeInnes. Requires defines a single [callback function](https://github.com/MikeInnes/Requires.jl/blob/b550be7e05c79aebf1ca21e739a8138162029eaf/src/require.jl#L20-L24) and [pushes it to `Base.package_callbacks`](https://github.com/MikeInnes/Requires.jl/blob/b550be7e05c79aebf1ca21e739a8138162029eaf/src/require.jl#L9). Requires also maintains a [Dict of thunks](https://github.com/MikeInnes/Requires.jl/blob/b550be7e05c79aebf1ca21e739a8138162029eaf/src/require.jl#L14) for use by its callback function; the Dict is indexed by PkgId, which does not require that the module itself exists (yet); the values stored in the Dict are just lists of functions (thunks) to call conditional on the loading of that package.

This Dict gets populated through `@require` calls. `@require` is a bit complicated in master, so now let me turn to my PR. In my PR, `@require` just does this (I've edited this heavily so it looks more like regular code):
```julia
julia> macroexpand(Main, quote
           @require JSON="682c06a0-de6a-54ab-a142-c8b1cf79cde6" include("morecode.jl")
       end)

        if !Requires.isprecompiling()
            Requires.listenpkg(Base.PkgId(Base.UUID("682c06a0-de6a-54ab-a142-c8b1cf79cde6"), "JSON")) do 
                Requires.withpath(@__DIR__) do 
                    Requires.err(@__MODULE__, "JSON") do 
                        const JSON = Base.require(JSON [682c06a0-de6a-54ab-a142-c8b1cf79cde6])
                        include("morecode.jl")
                    end
                end
            end
        end
```
All that basically does is execute
```julia
const JSON = Base.require(JSON [682c06a0-de6a-54ab-a142-c8b1cf79cde6])
include("morecode.jl")
```
inside whichever module you used `@require` in (that's what the `@__MODULE__` is about), setting the path (via `@__DIR__`) for finding `"morecode.jl"`. In my PR, this `@require` statement must occur inside the module's `__init__` function, which means that we register this JSON-dependency at the time of module initialization.

In the master branch of Requires, `@require` does a little bit more stuff because it supports having a `@require` statement outside `__init__`; it basically [stores all the `@require` calls in a module-global array `__inits__` and then creates an `__init__` function that iterates through the list and registers them](https://github.com/MikeInnes/Requires.jl/blob/b550be7e05c79aebf1ca21e739a8138162029eaf/src/init.jl#L5-L11). IMO this is a bad idea because it is exclusive with having a user-written `__init__` function. (You can iterate over `__inits__` yourself, but this appears to be undocumented, and the lack of error output about *why* it failed is problematic.) So I would describe this as the one dicey remaining feature in Requires, which is why I stripped it out. So on that branch Requires plays well with precompilation, custom initialization, and all the other fancy things we now know we need.

If that gets merged, I think it's fair to say that Requires is a clean and straightforward solution(*) to the problem of executing code that is dependent upon other modules having been loaded. That may not be the full list of ways we want to support interaction among packages, but it's the big one, and the one for which there aren't as good alternatives. Again, most of this progress has been from the work of @MikeInnes and those who designed the `Base.package_callbacks` interface; all I did was give this a nudge to fix a couple of bugs and strip out the last bit of problematic behavior.

Unfortunately, I don't think it's a deprecatable change, so it's pretty heavily breaking.

-----------------------------
(*) some might object to [monkeying with `task_local_storage`](https://github.com/MikeInnes/Requires.jl/blob/dc9c472f0494ee2a858a13ebffeb0afc03e461a0/src/require.jl#L22-L34) to set the path, but by my reading (I could be wrong) it's safe.

**Comment by StefanKarpinski** [comment] 2018-07-10 15:54
That sounds great, @timholy! In the future it might be good to make this entire business a little nicer to use and more official, but for now it sounds like we have everything we need. I support making the breaking change now so that Requires becomes a "clean and straightforward solution".

**Comment by lobingera** [comment] 2018-07-10 17:14
@timholy You mention above this a solution of one half of the problem, what would be the other?

**Comment by timholy** [comment] 2018-07-10 18:06
@lobingera, meaning `Base.package_callbacks` makes it possible to do this correctly (it's "the backend") and `Requires` is what implements the specific logic ("the frontend").

**Comment by MikeInnes** [comment] 2018-07-11 15:59
Tim's PR is merged and tagged; I concur that it's a strong and stable solution for package negotiations.

**Closed** 2018-08-10 16:38 UTC
Labels: packages
