### ISSUE TITLE
Spike in resource usage when scheduling looping tasks on non-primary threads

### ISSUE THREAD

**Issue by wsphillips** [JuliaLang/julia#36952] opened 2020-08-06 21:17 UTC
I've noticed that there can be a dramatic increase in CPU cycles for continuously running tasks spawned to non-primary threads. The following MWE costs virtually nothing to run asynchronously on the main Julia thread but eats up >30% CPU of the thread it spawns on if scheduled to a non-primary thread:
```julia
function spin_task()
    @async while true
        sin(rand()) # e.g. some work; alternatively the same high CPU cycling occurs doing nothing else but periodic wait/sleep
        sleep(0.01)
    end
end

spin_task() # hardly any resource usage when run on main Julia thread (<1% CPU utilization across all Julia threads)

Threads.@spawn spin_task() # huge resource usage (>30% CPU on htop) on whatever thread it gets spawned on
```
~~In my hands, this can lead to lockups (on that thread) and eventual segfaulting if the frequency of the task or workload is increased even marginally.~~ Is this kind of overhead to be expected/how might it be avoided? 

```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: AMD Ryzen Threadripper 1900X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

**Comment by JeffBezanson** [comment] 2020-08-11 00:53
I can reproduce this. Did you intend to close it?

Seems to be taking time in multiq_deletemin.

**Comment by wsphillips** [comment] 2020-08-11 10:58
> I can reproduce this. Did you intend to close it?

Well, not entirely. I thought I might be asking a dumb question. I was planning to bug @vtjnash at the multithreading-BoF about whether this is simply a design limitation or rough edges of the task system that need polish. 

> Seems to be taking time in multiq_deletemin.

If you agree that it's an unusual amount of cycles to spend I don't mind pecking at it, but then I also don't (currently) know my way around Julia's internals so well.

**Comment by StefanKarpinski** [comment] 2020-08-12 14:28
Fortunately, you're not required to fix issues that you file 😀. But if you want to poke around, please do! We can always use more people who know about the threading implementation!

**Comment by wsphillips** [comment] 2020-08-12 15:23
After discussing with @vtjnash it looks like this may be an artifact of [thread sleep threshold](https://github.com/JuliaLang/julia/blob/93f8a45cf50aea577e07a4f5e8bacc602712af17/src/options.h#L123). In cases where the current threshold default (4ms) is a large fraction of the sleep/wait interval, then the originally described behavior may result. (i.e. from the kernel's perspective the thread utilization is high) 

In my real use case, I'm kicking jobs to threads that are either iterating over a `Channel` or waiting on an edge-triggered `Threads.Condition()` every ~16ms (60Hz) so that would fall under that category. The good news is the cycles being spent ought to be "slack" and this _shouldn't_ equate to a reduction in throughput or latency, but I'll follow-up once I do some more testing/profiling to confirm.

**Closed** 2020-08-14 20:15 UTC
Labels: multithreading
