### ISSUE TITLE
@show 

### ISSUE THREAD

**Issue by HauntedCheppu** [JuliaLang/julia#49352] opened 2023-04-14 03:10 UTC
--------code------------
for i in range(1,4)
       @show x[i]
       end

-------output---------
x[i] = 0.2536116220400854
x[i] = 0.8434181963788412
x[i] = 0.920192039422826
x[i] = -0.801844574089227

--------problem---------------
instead of 
x[i] , do ==> x[1], x[2], x[3], x[4]

**Comment by oscardssmith** [comment] 2023-04-14 03:38
I don't understand what the problem is here. can you clarify?

**Comment by HauntedCheppu** [comment] 2023-04-14 03:47
run the code and you see what i mean

**Comment by HauntedCheppu** [comment] 2023-04-14 03:51
> I don't understand what the problem is here. can you clarify?

i in loop is integer value but @show x[i] print x[i]
while i is increasing in the loop

**Comment by jakobnissen** [comment] 2023-04-14 03:52
I think he is asking: Why does the left side of the show output say x[i] instead of e.g. x[2].

The answer is that this is how show is designed to work. Consider that if I was to be evaluated on the left side, why not also x?
More generally, the purpose of show is to display code on the left side and the value on the right.

**Comment by HauntedCheppu** [comment] 2023-04-14 03:55
> The answer is that this is how show is designed to work. Consider that if I was to be evaluated on the left side, why not also x?

x[i] in left side also be evaluated as x[1], x[2] .......
instead of printing x[i] only

**Comment by jakobnissen** [comment] 2023-04-14 04:12
Alright - well the answer here is "it's working as intended". Show is not supposed to evaluate the left side, but to display the piece of code that produced the value to the right.

There is, as far as I can see, no good way of only partially evaluating the code. So closing as "wontfix"

**Closed by jakobnissen** 2023-04-14 04:12 UTC
