### ISSUE TITLE
Add support for other updating operators

### ISSUE THREAD

**Issue by GregPlowman** [JuliaLang/julia#33432] opened 2019-10-01 02:03 UTC
As discussed on discourse https://discourse.julialang.org/t/custom-updating-binary-operator/29301

Would there be interest in adding support for other updating binary operators?

For example, it would be nice to be able to write `a ∪= b`

Aside from set union and intersection, are there any other candidates?

**Comment by JeffBezanson** [comment] 2019-10-01 22:07
Duplicate of #15964

**Closed** 2019-10-01 22:07 UTC
Labels: parser
