### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by GHTaarn** [JuliaLang/julia#53348] opened 2024-02-15 15:40 UTC
On https://docs.julialang.org/en/v1/stdlib/Test/

the link to https://pkgdocs.julialang.org/dev/creating-packages/#Adding-tests-to-the-package does not work. The link has the text "adding tests to your Julia Package"

**Comment by sjkelly** [comment] 2024-02-15 17:07
It points to `dev` whereas the link should probably be the `v1` link that works here: <https://pkgdocs.julialang.org/v1/creating-packages/#Adding-tests-to-the-package>

**Comment by GHTaarn** [comment] 2024-02-15 17:42
Thank you, that looks correct

**Comment by ViralBShah** [comment] 2024-02-16 14:14
Submit a PR?

**Comment by areebfazli** [comment] 2024-02-29 12:42
Hello, 
Is this issue closed? 
Or can I work on it?

**Comment by sjkelly** [comment] 2024-02-29 13:03
Welcome, it still needs a PR. Please link to this issue when you file the
PR so we can close it.

**Comment by areebfazli** [comment] 2024-03-01 14:13
The problem is not as simple as it seems because in the file index.md the link is using @ref as a reference. I can hardcode the working link https://pkgdocs.julialang.org/v1/creating-packages/#Adding-tests-to-the-package but I don't think that's the optimal solution as the other link on the page with the text "read about more here" has the same issue. 
The proper way to fix this is to change the definition of @ref but I cannot the location of that
Can someone guide me about this?

![Capture](https://github.com/JuliaLang/julia/assets/22425008/a7a8356f-2870-4046-8087-c313f8c17290)

**Comment by xlxs4** [comment] 2024-07-13 11:07
I think this can be closed; cref. https://github.com/JuliaLang/julia/pull/53509/files

**Closed** 2024-07-16 22:54 UTC
Labels: domain:docs, good first issue
