### ISSUE TITLE
Should `zero(::AbstractArray)` call `fill!`?

### ISSUE THREAD

**Issue by tkoolen** [JuliaLang/julia#27483] opened 2018-06-07 23:23 UTC
I thought this was just an issue in StaticArrays (https://github.com/JuliaArrays/StaticArrays.jl/issues/428), but the same thing is happening in Base.

Currently:

```julia
julia> mutable struct MyNumber
           val::Float64
       end

julia> Base.zero(::Type{MyNumber}) = MyNumber(0.0)

julia> v = zero([MyNumber(1.0), MyNumber(2.0)])
2-element Array{MyNumber,1}:
 MyNumber(0.0)
 MyNumber(0.0)

julia> v[1].val = 1
1

julia> v
2-element Array{MyNumber,1}:
 MyNumber(1.0)
 MyNumber(1.0)
```

I think this is not desirable for non-isbits types.

**Comment by vtjnash** [comment] 2021-05-29 04:17
Duplicate of https://github.com/JuliaLang/julia/issues/29168

**Closed by vtjnash** 2021-05-29 04:17 UTC
Labels: arrays
