### ISSUE TITLE
Compiling error on Fedora 34

### ISSUE THREAD

**Issue by xijiang** [JuliaLang/julia#40821] opened 2021-05-14 09:10 UTC
I have been using v1.6.1 for a while. Recently I tried to compile the nightly built and got errors as attached. This is obviously a Fedora problem, as the nightly built can be compiled on el7 and centos 7. But I post them here, hoping it can be solved on Julia side.

Many thanks.

```
/usr/bin/ld: ./codegen.o: in function `__gnu_cxx::new_allocator<llvm::Type*>::allocate(unsigned long, void const*)':
/usr/include/c++/11/ext/new_allocator.h:110: undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: ./llvm-late-gc-lowering.o: in function `__gnu_cxx::new_allocator<int>::allocate(unsigned long, void const*)':
/usr/include/c++/11/ext/new_allocator.h:110: undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: ./llvm-late-gc-lowering.o: in function `__gnu_cxx::new_allocator<unsigned int>::allocate(unsigned long, void const*)':
/usr/include/c++/11/ext/new_allocator.h:110: undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: ./llvm-late-gc-lowering.o: in function `__gnu_cxx::new_allocator<int>::allocate(unsigned long, void const*)':
/usr/include/c++/11/ext/new_allocator.h:110: undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: /usr/include/c++/11/ext/new_allocator.h:110: undefined reference to `std::__throw_bad_array_new_length()'
/usr/bin/ld: ./llvm-late-gc-lowering.o:/usr/include/c++/11/ext/new_allocator.h:110: more undefined references to `std::__throw_bad_array_new_length()' follow
```

**Comment by simeonschaub** [comment] 2021-05-14 09:25
Duplicate of #40703.

**Closed** 2021-05-14 09:25 UTC
