### ISSUE TITLE
Overwriting inner functions eliminates previous invocations

### ISSUE THREAD

**Issue by staticfloat** [JuliaLang/julia#36037] opened 2020-05-26 19:01 UTC
It appears that overwriting a function defined within another function can cause strange ordering issues.  MWE:

```julia
function do_test()
    function innerfunc()
        println(stderr, "innerfunc")
    end
    println(stderr, "pre-innerfunc")
    innerfunc()
    println(stderr, "post-innerfunc")

    # Overwrite innerfunc
    innerfunc() = nothing
    println("innerfunc is now overwritten")
end

do_test()
```

Expected output:
```
pre-innerfunc
innerfunc
post-innerfunc
innerfunc is now overwritten
```

Actual output:
```
pre-innerfunc
post-innerfunc
innerfunc is now overwritten
```

It appears that the optimizer records the final value of `innerfunc()` and completely disregards the original value:
```
julia> @code_lowered do_test()
CodeInfo(
1 ─      innerfunc = %new(Main.:(var"#innerfunc#3"))
│        Main.println(Main.stderr, "pre-innerfunc")
│        (innerfunc)()
│        Main.println(Main.stderr, "post-innerfunc")
│   %5 = Main.println("innerfunc is now overwritten")
└──      return %5
)
```

This is reproducible on every release of from 1.0 to `master`, I didn't bother looking farther back than 1.0.

**Comment by vtjnash** [comment] 2020-05-26 19:43
Well that is very minimal 😜

**Comment by staticfloat** [comment] 2020-05-26 19:46
Something went wrong, hah.  Updated.

**Comment by staticfloat** [comment] 2020-05-26 19:54
I will note that if this is run at top-level, it works as expected.  It's only when you're redefining an inner function.  I ran into this when I was debugging a test suite and accidentally had `@test inner_func() = "foo"` instead of `@test inner_func() == "foo"`, and couldn't understand why this was seemingly skipping all sorts of side-effects that the original definition of `inner_func()` should have been causing earlier on in that test set.

**Comment by KristofferC** [comment] 2020-05-26 19:57
Looks like https://github.com/JuliaLang/julia/issues/15602?

**Comment by KristofferC** [comment] 2020-05-26 19:57
Looks like https://github.com/JuliaLang/julia/issues/15602?

**Comment by staticfloat** [comment] 2020-05-27 22:24
I don't really see how these are related?  That issue is about a duplicate method warning, but in this case there is no warning, and in that thread I don't really see people writing methods like mine, it's all about having methods in separate branches that conflict with eachother.

**Comment by vtjnash** [comment] 2020-05-28 01:12
Duplicate of #15602

**Comment by vtjnash** [comment] 2020-05-28 01:13
We should perhaps turn back on the method overwrite warning

**Closed by vtjnash** 2020-05-28 01:12 UTC
