### ISSUE TITLE
Segfault on Mac Silicon during initial Registry download on a clean install

### ISSUE THREAD

**Issue by habemus-papadum** [JuliaLang/julia#51839] opened 2023-10-24 10:58 UTC
Hi,   
I am able to trigger a segfault on my Mac Silicon as follows:

```
❯ rm -rf ~/.julia
❯ tar xf ~/Downloads/julia-1.9.3-macaarch64.tar.gz
❯ julia-1.9.3/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.3 (2023-08-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.9) pkg> add JSON
  Installing known registries into `~/.julia`

[3592] signal (11.2): Segmentation fault: 11
in expression starting at none:0
Curl_connect_ongoing at /Users/nehal/tmp/julia-1.9.3/lib/julia/libcurl.4.dylib (unknown line)
multi_runsingle at /Users/nehal/tmp/julia-1.9.3/lib/julia/libcurl.4.dylib (unknown line)
Allocations: 2997 (Pool: 2986; Big: 11); GC: 0
zsh: segmentation fault  julia-1.9.3/bin/julia
```

I presume this is something specific to my machine otherwise there would be many other reports.  Any guidance on how I might troubleshoot this would be appreciated.  Thanks!

```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 10 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 10
  ```

**Comment by giordano** [comment] 2023-10-24 11:02
Duplicate of #48170

**Closed by giordano** 2023-10-24 11:02 UTC
