### ISSUE TITLE
Julia allows rewriting imported bindings

### ISSUE THREAD

**Issue by fcard** [JuliaLang/julia#21989] opened 2017-05-20 18:28 UTC
265 2: son of 265 (featuring world-famous star: the global variable)
```julia
f() = string
g() = global string = "abc"
```

```julia
julia> f()
string (generic function with 14 methods)

julia> g()
WARNING: imported binding for string overwritten in module Main
"abc"

julia> f()
string (generic function with 14 methods)
```

And this:
```julia
f(x::typeof(string)) = 1
f(x::String) = 2
g() = (global string = "abc"; f(string))
```

```julia
julia> g()
WARNING: imported binding for string overwritten in module Main
1
```
Already reported in #11723 but the [given explanation](https://github.com/JuliaLang/julia/issues/11723#issuecomment-221271888) didn't convince me, so I am bringing it up again as my own bug report. This still looks like a language breaking bug to me.

**Comment by yuyichao** [comment] 2017-05-20 20:09
You didn't break the language, you introduce undefined behavior in your own module. Givent an error is easy but it'll make interactive development harder. If you do care about this, you just shouldn't ignore the warning to begin with.

**Comment by fcard** [comment] 2017-05-20 20:47
\*Shrug\* I don't like the language allowing undefined behavior in the first place, and it sounds like this behavior _could_ be defined, but if there really is no interest whatsoever in looking into this as the "won't fix" label implies, then feel free to close the issue. This just has been bothering me for a while since the last discussion about it felt incomplete, but I will take your closure as my own.

**Comment by Keno** [comment] 2017-05-20 21:28
idk about "won't fix", seems like we can fix it eventually (e.g. once we start making speculative assumptions about globals when generating code). Given the warning though, it's not necessarily a priority though.

**Comment by yuyichao** [comment] 2017-05-20 21:36
We've already forbidden any overwirte that changes the type and that's likely the speculative assumption we're going to make about globals. Also, some constant globals are being used in inner loops and it'll be a huge regression unless we always make non-speculative assumptions about their values so speculative assuptions about globals won't help this.

This is the kind of thing that shouldn't be allowed in runtime bug is useful for debugging/testing/interactive development (not limited to `Main`) so I think the current behavior is the best option. The user just shouldn't be ignoring warnings, they really mean that something the user don't want to happen could happen.

**Comment by fcard** [comment] 2017-05-20 21:59
This one is really making my brain itch. Hopefully I will one day understand the compiler well enough to see this with the same clarity as you do, @yuyichao, but right now I just can't see the theoretical or practical barrier making this a impossibility. I really felt like this could be fixed, even if in five years from now.

Well, thanks for your time. Felicidades, till next time.

**Comment by StefanKarpinski** [comment] 2017-05-20 22:31
I'm reopening this because what a global binding refers to – imported or not – should be fully determined by parsing the module, without executing any code. We've had this "bug" for quite a long time and I've discussed it with @JeffBezanson, @vtjnash and others occasionally. The fact that `g`'s definition assigns to global `string` should dictate that `string` is the global that `g` defines, not `Base.string`. Which means that calling `f()` before `g()` should be an undef ref error instead of the current behavior.

**Comment by yuyichao** [comment] 2017-05-20 22:33
> should be fully determined by parsing the module, without executing any code.

Not for the REPL.

> Which means that calling f() before g() should be an undef ref error instead of the current behavior.

Changing to that behavior is certainly better, but it won't fix this issue since there's `eval` (which is also why `REPL` is special), unless we put a very tight restriction on when `eval` can be called and what it can do of course.

**Comment by yuyichao** [comment] 2017-05-20 22:35
> I'm reopening this because what a global binding refers to – imported or not – should be fully determined by parsing the module, without executing any code.

Actually this is not even true in a normal model when no metaprogramming is used. `include` is basically a special form of `eval` and it is impossible to statically evaluate it without executing any user code.

**Comment by vtjnash** [comment] 2017-05-20 22:36
Ah, yep. Stefan is right. The issue title might need to be edited, but I nominate that for 1.0. Should be an easy fix to lowering.

**Comment by StefanKarpinski** [comment] 2017-05-20 22:37
Just to be clear the fix to this problem is that it should not be possible to change what a global binding refers to:

- If `g()` is defined before `f()` is called, then `string` is a new global in the current module and calling `f()` should be an undefined variable error.
-  If `f()` is called before `g()` is defined, then `string` refers to `Base.string` and the definition of `g()` should be an immediate error.

@yuyichao, I understand how dynamic languages work, thanks.

**Comment by yuyichao** [comment] 2017-05-20 22:41
Actually the case I'm talking about is

```
julia> const a = 1
1

julia> f() = a
f (generic function with 1 method)

julia> f()
1

julia> a = 2
WARNING: redefining constant a
2

julia> f()
1
```

which I've been assuming to be included in this issue due to the mentioning of #265. If the issue is only about not changing global binding, which is indeed the only case the first post is about then I certainly agree it should be fixed.

**Comment by fcard** [comment] 2017-05-20 23:56
Yes, this issue was only about imported bindings getting confused with global variables, sorry if my wording caused confusion. (my mention of 265 was just because of how it looked, really) Thanks for chiming in and clarifying that this can be fixed in some way everybody, my brain can stop twisting now. Hopefully one day I will be able to participate in these conversations, but for now I will just be happy I helped make them happen.

I picked the title I did because I thought that the solution would be something like the compiler keeping track of what bindings a function uses and "readjusting" when it notices a change in them*, but just plain not allowing ambiguity between the bindings sounds good too, as long as it's not possible to create a "invalid" function like this I am a happy clam:
```julia
julia> const x = 1
1

julia> module M
       import Main.x

       f(a::String) = repeat(a, 2)
       f(a::Int) = a + a

       g() = (global x = "abc"; f(x))
       end
M

julia> @code_typed M.g()
CodeInfo(:(begin 
        M.x = "abc"
        return $(Expr(:invoke, MethodInstance for f(::Int64), :(M.f), :(M.x)))
    end))=>Int64
```
(which is what I meant by "breaking" the language, where the lowered code has an invocation to the wrong method, sorry if that was bad wording too)

Happy coding!

---

*e.g. the compiler sees `string` first and assumes it to be the imported `Base.string`, but then a function refers to a global `string`, and the compiler "goes back" and fixes the previous usage, or in the second case, as soon as an assignment to a global happens in a function all instances of that global's name in the function must refer to the global, rather than to the imported binding, and the compiler must "readjust" the function to fit that, but I don't really have enough understanding of the compiler's internals to know how compatible that type of bookkeeping and backtracking is with how it currently works.

**Comment by JeffBezanson** [comment] 2017-05-31 04:16
So IIUC, you want an error instead of a warning? That might be fine, but I don't see why it's such a big deal. Warnings in julia are serious; they're basically errors that let you keep going for convenience.

I think we probably should make the change @StefanKarpinski describes, but it's orthogonal --- one issue is what causes the binding to be resolved (executing the statement `global x = ...` vs. just defining a function that contains such a statement), and the other issue is what to do when some code tries to change where the binding points (error or warning).

**Comment by fcard** [comment] 2017-05-31 11:05
I suppose a warning is fine, it confuses me a bit why changing a constant's type is an error while this is just a warning, when they can cause the same types of problems (i.e. confuse type inference and create invalid code), but what I really wanted was to try to avoid needing a warning in the first place. I guess you can still use some `eval` trickery to change the type of a binding, but if you're being that explicit about doing it, erm.

A middle ground would be to allow imported globals to be overwritten by other globals and constants, and constants to be overwritten by constants of the same type (both with a warning), and anything else being an error, which is more closely to what happens with bindings in the same module, and wouldn't interfere with type inference... 

But honestly I don't really feel *too* strongly about this part of it, my main motivation with this issue was that I felt that this was a solvable problem that was brushed off as an unavoidable quirk the last time it was brought up, and I wanted to make sure it was given the attention I thought it deserved. So I would be mostly satisfied even if the warning part of it remained unchanged.

**Comment by StefanKarpinski** [comment] 2018-12-05 14:31
I'm pretty sure this no longer needs to be open.

**Closed by StefanKarpinski** 2018-12-05 14:31 UTC
