### ISSUE TITLE
mysterious error while solving simple system in two different programs

### ISSUE THREAD

**Issue by sintemalen** [JuliaLang/julia#17913] opened 2016-08-09 10:47 UTC
trying to solve simple system
```jl
A = [ 4. 1.; 2.718282 0.75 ]
b = [ -2.25, -0.843282 ]
```
in two different program environments, when trying so solve via: `x = A\b`
1) in simple program : get the expected result `x = [-2.9966775285924205,9.736710114369682]`
2) while generating `A` in a different manner in another, more complicated program (i.e. by first setting up `A = eye(2)`, then computing each element of A separately, but arriving at exactly same numbers for A & b, as in simple program 1), and then trying to solve, again via `x = A\b`, I now get the error message
"ctranspose not implemented for `Base.LinAlg.LU{Float64,Array{Float64,2}}`" !
NB: in BOTH program versions, just before trying to solve, I have for 'A'
```jl
       det(A) = 0.281718
       typeof(A):  Array{Float64,2}
```
 What may be so different for matrices `A` in both programs, if their content & type is the same, to generate this strange error in the second version, only, and, how should I correct program version 2), to avoid this ?

Updated by @andreasnoack (`/` -> `\`)

**Comment by KristofferC** [comment] 2016-08-09 10:54
Do you get a backtrace for the error?

**Comment by sintemalen** [comment] 2016-08-09 11:50
>Do you get a backtrace for the error?

My output:

...
----- fvec/fjac --------------
  1    -2.250000:        4.000000      1.000000
  2    -0.843282:        2.718282      0.750000

   type(fjac) Array{Float64,2}
   det(fjac) 0.28171780916919387
.
ERROR: LoadError: ctranspose not implemented for Base.LinAlg.LU{Float64,Array{Float64,2}}
 in \ at linalg/dense.jl:448
 in newt at /home/frank/Software/Coutsias/newt/julia/newt.jl:233


source code in 'newt.jl' [re-write of 'newt.c', from Numerical Recipes (vers. 2)]

...
    221     println("\n ----- fvec/fjac --------------")
    222     for i = 1:n
    223       @printf "  %d %12.6f:  " i p[i]
    224       for j = 1:n
    225         @printf "  %12.6f" fjac[i,j]
    226       end
    227       @printf "\n"
    228     end
    229 
    230     println("   type(fjac) $(typeof(fjac))\n")
    231     println("   det(fjac) $(det(fjac))\n")
    232 
    233     x = fjac\p
    234
...


---- On Tue, 09 Aug 2016 12:54:48 +0200 Kristoffer Carlsson  wrote ----

**Comment by andreasnoack** [comment] 2016-08-09 12:15
I can confirm this on 0.4. The problem appears when the `eltype(b)=Any`. E.g.
```jl
julia> A = [ 4. 1.; 2.718282 0.75 ];

julia> b = Any[ -2.25, -0.843282 ];

julia> A\b
ERROR: ctranspose not implemented for Base.LinAlg.LU{Float64,Array{Float64,2}}
 in error at ./error.jl:21
 in \ at linalg/dense.jl:448
``` 
This causes a different error on 0.5.
```jl
julia> A = [ 4. 1.; 2.718282 0.75 ];

julia> b = Any[ -2.25, -0.843282 ];

julia> A\b
ERROR: MethodError: no method matching one(::Type{Any})
Closest candidates are:
  one(::BitArray{2}) at bitarray.jl:413
  one(::Number) at number.jl:63
  one{T<:Number}(::Type{T<:Number}) at number.jl:64
  ...
 in \ at ./linalg/factorization.jl:37 [inlined]
 in \(::Array{Float64,2}, ::Array{Any,1}) at ./linalg/generic.jl:361
```
and I believe that is covered by https://github.com/JuliaLang/julia/issues/14237.

@sintemalen can you try to check the type of you `b` when the method fails. If the problem is the same as my small example here, I think we can close the issue.

**Comment by sintemalen** [comment] 2016-08-09 13:27
This should have been a reply to A. Noack's mail (reply to this does not work, don't know why): 
 
The reason for my problem with "x=A/b" was, that 'A' and 'b' where of DIFFERENT type: 
 
 typeof(A) : Array{Float64,2} 
 typeof(b) : Array{Any,1} 

Thanks, 
 
Frank 
 
---- On Tue, 09 Aug 2016 12:54:48 +0200 Kristoffer Carlsson wrote ----

**Comment by JeffBezanson** [comment] 2016-08-09 15:27
@sintemalen Thanks for the report. Some tips:

- Please quote code with three backtick (\`) characters.
- If possible, exclude line numbers to make it easier for us to copy and paste examples.
- It is also preferred to include enough code to fully reproduce the problem; i.e. we should be able to copy exactly what you post into a file, run it, and see the same error you do.

**Comment by andreasnoack** [comment] 2016-08-09 15:48
@sintemalen Thanks for confirming. The best thing you can do is to make sure that your `b` is better inferred. The solution depends on your code and you might be able to get some help for that on julia-users or StackExchange. As mentioned, on 0.5 the problem is covered by #14237 so I'll close here.

**Closed by andreasnoack** 2016-08-09 15:48 UTC
Labels: linear algebra
