### ISSUE TITLE
Threads.@threads should use iterators for the sub-loops

### ISSUE THREAD

**Issue by JKrehl** [JuliaLang/julia#18603] opened 2016-09-20 16:41 UTC
Since it is possible to select subranges of iterators using UnitRange objects it is my opinion that Threads.@threads should use that instead of the iteration through the subrange and item-wise evaluation of the given range at a specific index. See [threadingconstructs.jl#L52](https://github.com/JuliaLang/julia/blob/7cdb7793e007229b139c4b0d575c20d75d792765/base/threadingconstructs.jl#L52).

Solution: #18604

This becomes relevant when you want to use CartesianRange for parallelised ndimensional loops. CartesianRange flat representation is well defined so selecting subranges ([inspiration](https://groups.google.com/forum/#!topic/julia-users/uFAqu31gHq4)) using indices of the flat representation is well defined, therefore: they can be split into subranges without any problems. Using that ndimensional loops can be generically parallelised.

**Comment by JeffBezanson** [comment] 2019-06-26 18:25
Duplicate of #18263.

**Closed by JeffBezanson** 2019-06-26 18:25 UTC
Labels: multithreading
