### ISSUE TITLE
Julia fails to build on on aarch64 because libquadmath.so is not available

### ISSUE THREAD

**Issue by ggardet** [JuliaLang/julia#41613] opened 2021-07-16 08:15 UTC
Julia fails to build on aarch64 because `libquadmath.so` is not available on this arch.
Log:
```
[ 4706s] ln -sf /lib64/libgfortran.so.5 /home/abuild/rpmbuild/BUILD/julia-1.6.1/usr/lib/julia/libgfortran.so.5
[ 4706s] System library symlink failure: Unable to locate libquadmath.so.0 on your system!
[ 4706s] make[1]: *** [Makefile:206: /home/abuild/rpmbuild/BUILD/julia-1.6.1/usr/lib/julia/libquadmath.so.0] Error 1
[ 4706s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/julia-1.6.1/base'
[ 4706s] make: *** [Makefile:63: julia-base] Error 2
```

**Comment by Seelengrab** [comment] 2021-07-16 09:36
Are you sure you have all [required dependencies](https://github.com/JuliaLang/julia/blob/master/doc/build/build.md#required-build-tools-and-external-libraries) installed? There's also #36617. What system are you trying to build on?

**Comment by ggardet** [comment] 2021-07-16 09:51
I am trying to build on openSUSE Tumbleweed aarch64, with GCC11. `libquadmath` is available on other archs, but not on aarch64.

**Comment by Seelengrab** [comment] 2021-07-16 13:06
I just noticed you're trying to build 1.6.1 - I don't think 1.6.1 had even build support on aarch64. The issue I linked is about getting it to work in the future (motivated by Apple's recent move to that architecture) and has only recently begun to work. Do the official 1.7 beta binaries work? If so, you can try building 1.7 from source, which will probably work better than 1.6.1.

**Comment by Seelengrab** [comment] 2021-07-16 13:12
Fiddling around with the download links on julialang.org/downloads, there were binaries available for aarch64 and 1.6.1, so I suspect there's something going on with your setup. Perhaps the libraries are in a non-standard place, making julia unable to find them?

**Comment by giordano** [comment] 2021-07-16 20:55
> with GCC11

Any chance to try with GCC 9 or 10?  Also, why don't you simply use the [official binaries](https://julialang.org/downloads/) (aarch64 is Tier 1, since it's also tested in CI)?

**Comment by ggardet** [comment] 2021-07-20 07:44
> > with GCC11
> 
> Any chance to try with GCC 9 or 10? Also, why don't you simply use the [official binaries](https://julialang.org/downloads/) (aarch64 is Tier 1, since it's also tested in CI)?

The policy of the Linux distribution is to rebuild from sources, not using pre-built binaries.
I may try an older GCC.

**Comment by ggardet** [comment] 2021-11-23 12:49
It also fails with GCC7

**Comment by giordano** [comment] 2021-11-23 13:29
What if you remove line https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L213
?  But I'm confused, because this platform is Tier 1 and tested regularly :confused:

**Comment by imciner2** [comment] 2021-11-23 13:51
From some digging, I don't think libquadmath is supposed to exist on aarch64 platforms. At first glance, checking the Fedora GCC builds shows that libquadmath is only enabled on x86_64/ppc64le/ia64:
<pre class="syntaxhighlightblock"><code class="lang-rpm-specfile hljs">
%ifarch %{ix86} x86_64 ia64 ppc64le
%global build_libquadmath 1
%else
%global build_libquadmath 0
%endif
</code></pre>

Second, there was this somewhat recent bug in upstream GCC (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016) that says libquadmath fails to configure on aarch64 because it tries to detect if `__float128` is a supported type on the architecture - and it isn't for aarch64.

This begs the question, what is different about the CI builds for aarch64 and the original reporter's build? @ggardet can you please post your entire configure line so we can see the options you are building with?

**Comment by ggardet** [comment] 2021-11-23 13:56
```
%ifarch aarch64
  %define julia_march armv8-a
%endif

# We need these compilation flags to avoid error when building MBEDTLS with
# GCC-11.
# Ref.: https://build.opensuse.org/package/show/security:tls/mbedtls
export CFLAGS="%{optflags} -Wno-stringop-overflow -Wno-maybe-uninitialized"
export CXXLAGS="%{optflags} -Wno-stringop-overflow -Wno-maybe-uninitialized"

%define julia_builddir %{_builddir}/%{name}/
make %{?_smp_mflags} \
                     MARCH=%{julia_march} \
%ifarch aarch64
                     JULIA_CPU_TARGET="generic" \
%endif
                     prefix=%{_prefix} \
                     bindir=%{_bindir} \
                     libdir=%{_libdir} \
                     libexecdir=%{_libexecdir} \
                     datarootdir=%{_datarootdir} \
                     includedir=%{_includedir} \
                     sysconfdir=%{_sysconfdir} \
                     %{juliabuildopts} \
                     release debug
```
With `juliabuildopts` being:
```
BUNDLE_DEBUG_LIBS=1 \
NO_GIT=1 \
USE_SYSTEM_LLVM=0 \
USE_SYSTEM_LIBUNWIND=1 \
USE_SYSTEM_READLINE=1 \
USE_SYSTEM_PCRE=1 \
USE_SYSTEM_LIBM=0 \
USE_SYSTEM_OPENLIBM=0 \
USE_SYSTEM_OPENSPECFUN=1 \
USE_SYSTEM_DSFMT=0 \
USE_SYSTEM_BLAS=1 \
LIBBLAS=-lopenblas \
LIBBLASNAME=libopenblas \
USE_SYSTEM_LAPACK=1 \
LIBLAPACK=-libopenblas \
LIBLAPACKNAME=libopenblas \
USE_SYSTEM_FFTW=1 \
LIBFFTWNAME=libfftw3_threads.so.3 \
LIBFFTWFNAME=libfftw3f_threads.so.3 \
USE_SYSTEM_GMP=1 \
USE_SYSTEM_MPFR=1 \
USE_SYSTEM_ARPACK=1 \
USE_SYSTEM_SUITESPARSE=1 \
USE_SYSTEM_ZLIB=1 \
USE_SYSTEM_GRISU=1 \
USE_SYSTEM_LIBUV=0 \
USE_SYSTEM_UTF8PROC=0 \
USE_SYSTEM_PATCHELF=1 \
USE_SYSTEM_P7ZIP=1 \
USE_SYSTEM_MBEDTLS=0 \
USE_SYSTEM_LIBSSH2=1 \
USE_SYSTEM_LIBGIT2=0 \
USE_SYSTEM_CURL=1 \
USE_SYSTEM_NGHTTP2=1 \
USE_SYSTEM_CSL=1 \
USE_MKL=0 \
USE_BLAS64=0 \
USE_LLVM_SHLIB=1 \
VERBOSE=1 \
USECLANG=0 \
USE_BINARYBUILDER=0
```

**Comment by ggardet** [comment] 2021-11-23 16:24
> What if you remove line
> 
> https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L213
> 
> 
> ? But I'm confused, because this platform is Tier 1 and tested regularly 😕

If I drop this line, the build of julia 1.6.3 succeeds on aarch64 as well as on x86_64.

**Comment by giordano** [comment] 2021-11-23 16:33
And what if you replace that line with
```
$(eval $(call symlink_system_library,CSL,libquadmath,0,ALLOW_FAILURE))
```
?  Allowing the library not to be there is used in
https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L216-L218
which are other libraries which are not available on all platforms.  Again, no idea how the build bot currently works at all.

**Comment by imciner2** [comment] 2021-11-23 19:01
It is probably succeeding on the buildbot because the official packaging is using the BinaryBuilder-provided CSL, which is automatically extracted into the local lib directory. The build showing the issue is using the system CSL (it defines `USE_SYSTEM_CSL=1` on the build options), so the makefile then tries to make a symlink in the local library directory to the system's version of libquadmath. So the buildbot build step isn't actually doing this linking.

The way to fix this would be to guard this line inside an exclusion for aarch64 (I don't think we want to unconditionally make it allowed to fail, since in all other cases it being missing is probably a problem).
https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L213
And now that I think about it some more, shouldn't that line be inside this check as well?
https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L210
Since I think libquadmath is only available if gfortran is available (or at least it is packaged in the gfortran CSL tar).

And as a note, this line should probably get a different comment (since it currently reads that the libquadmath is available on all platforms).
https://github.com/JuliaLang/julia/blob/27c0291f7fbecd811a3f9eb62b1159cff6b61e2a/deps/csl.mk#L64-L65

**Comment by giordano** [comment] 2021-11-23 19:05
> It is probably succeeding on the buildbot because the official packaging is using the BinaryBuilder-provided CSL

But [CSL](https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.1%2B0/CompilerSupportLibraries.v0.5.1.aarch64-linux-gnu-libgfortran5.tar.gz) doesn't provide libquadmath for aarch64

**Comment by imciner2** [comment] 2021-11-23 19:13
> > It is probably succeeding on the buildbot because the official packaging is using the BinaryBuilder-provided CSL
> 
> But [CSL](https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.1%2B0/CompilerSupportLibraries.v0.5.1.aarch64-linux-gnu-libgfortran5.tar.gz) doesn't provide libquadmath for aarch64

Yes, but because the build isn't being told to use the system version (via `USE_SYSTEM_CSL=1`), the symlink step of the build is never getting run. If you trace through the makefile, you find that the line
https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L213
will only be run when this condition is satisfied, with where `$1` will be `CSL` for libquadmath - making this line only run when the variable `USE_SYSTEM_CSL` is not equal to 0.
https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L183-L185
Because that line actually adds the symlink target to the list of targets to run in the full symlink target here
https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L268
So because `USE_SYSTEM_CSL=1` is given in the build options, the `symlink_system_libraries` step of the build will try to symlink libquadmath.so into the local directory. On the buildbot version though, `USE_SYSTEM_CSL=0` is used, so `symlink_system_libraries` will not try to make a symlink.

**Comment by ggardet** [comment] 2021-11-24 08:14
> And what if you replace that line with
> 
> ```
> $(eval $(call symlink_system_library,CSL,libquadmath,0,ALLOW_FAILURE))
> ```
> 
> ? Allowing the library not to be there is used in
> 
> https://github.com/JuliaLang/julia/blob/8c9799530383d571d5beab4e530d86e40a289929/base/Makefile#L215-L218
> 
> 
> which are other libraries which are not available on all platforms. Again, no idea how the build bot currently works at all.

Build also succeeds with `ALLOW_FAILURE`.

**Comment by imciner2** [comment] 2021-11-25 15:47
I should have some time to pull out my aarch64 board and make the needed changes to the makefile this weekend and will submit a PR after that.

**Comment by giordano** [comment] 2021-11-25 15:50
Might also be good to look into #43071 :slightly_smiling_face:

**Comment by imciner2** [comment] 2021-11-25 16:05
> Might also be good to look into #43071 slightly_smiling_face

That one seems to have been fixed by a clean checkout of the branch, so it probably was just a weird state issue. Were you thinking of a different issue?

**Comment by giordano** [comment] 2021-11-25 16:11
> That one seems to have been fixed by a clean checkout of the branch

...and manually setting `override HAVE_SSP := 0`.  It appears libssp is also required on that platform, which is another library which isn't actually there:
https://github.com/JuliaLang/julia/blob/f458b07613357fbdf7b8deae79b78924659fe830/Make.inc#L888-L894

**Comment by ViralBShah** [comment] 2023-06-09 21:14
@ggardet Are you able to try with 1.9.1 or master?

**Comment by ViralBShah** [comment] 2023-07-19 03:29
We have been reliably building on aarch64 for a while now. Please reopen if still an issue with the latest release or master.

**Comment by uncomfyhalomacro** [comment] 2024-05-12 14:30
@ggardet this might be too late but i found out that the gcc specfile in opensuse disabled quadmath... i am currently forcing julia to use the patched libraries so i can update it to 1.10.3. Unfortunately, like i mentioned, aarch64 will be disabled :)

**Comment by ggardet** [comment] 2024-05-27 07:25
This is still broken with 1.10.3:
```
[15962s] '/home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/bin/7z' -> '/usr/bin/7z'
[15962s] ln -sf /usr/lib64/libopenlibm.so.4 /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libopenlibm.so
[15962s] ln -sf /usr/lib64/libgcc_s.so.1 /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libgcc_s.so.1
[15962s] ln -sf /usr/lib64/libgfortran.so.5 /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libgfortran.so.5
[15962s] System library symlink failure: Unable to locate libquadmath.so.0 on your system!
[15962s] make[1]: *** [Makefile:246: /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libquadmath.so.0] Error 1
[15962s] make: *** [Makefile:82: julia-base] Error 2
[15962s] make: *** Waiting for unfinished jobs....
```
But I cannot re-open.

**Comment by uncomfyhalomacro** [comment] 2024-05-27 23:54
> This is still broken with 1.10.3:
> 
> ```
> [15962s] '/home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/bin/7z' -> '/usr/bin/7z'
> [15962s] ln -sf /usr/lib64/libopenlibm.so.4 /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libopenlibm.so
> [15962s] ln -sf /usr/lib64/libgcc_s.so.1 /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libgcc_s.so.1
> [15962s] ln -sf /usr/lib64/libgfortran.so.5 /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libgfortran.so.5
> [15962s] System library symlink failure: Unable to locate libquadmath.so.0 on your system!
> [15962s] make[1]: *** [Makefile:246: /home/abuild/rpmbuild/BUILD/julia-1.10.3/build/usr/lib64/julia/libquadmath.so.0] Error 1
> [15962s] make: *** [Makefile:82: julia-base] Error 2
> [15962s] make: *** Waiting for unfinished jobs....
> ```
> 
> But I cannot re-open.

I think you should open a ticket to the openSUSE bugzilla. like i said, libquadmath is disabled in opensuse. check out the specfile.

**Comment by imciner2** [comment] 2024-05-28 00:24
> I think you should open a ticket to the openSUSE bugzilla. like i said, libquadmath is disabled in opensuse aarch64 of gcc. check out the specfile

As I said above, I don't think libquadmath is supported for aarch64, so our linking to it is the error here, not the fact it is missing in the distros.

(I can't find anything that seems to say for certain that aarch64 isn't supported with libquadmath, so maybe @fxcoudert can comment on that?)

**Comment by uncomfyhalomacro** [comment] 2024-05-28 00:51
i am not saying that libquadmath isn't supported. it's that it's disabled in opensuse so i suggested to open a ticket to opensuse bugzilla. you can see the line 50 from the link I posted, aarch64 was not added as the libquadmath_arch. since it's disabled, it also means Julia can't build it because it can't locate a non-existing libquadmath.so.

**Comment by ViralBShah** [comment] 2024-05-28 03:29
How do we build Julia on aarch64 linux in our build infrastructure (presumably which is ubuntu)?

**Comment by DilumAluthge** [comment] 2024-05-28 03:39
> USE_BINARYBUILDER=0

In the Base Julia Buildkite CI, we do not have this flag set. Thus, our CI uses BinaryBuilder to provide various binary dependencies.

**Comment by ggardet** [comment] 2024-05-28 08:32
According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016 libquadmath is not supported on aarch64. libquadmath is not enabled on aarch64 within Fedora and Debian either.

**Comment by uncomfyhalomacro** [comment] 2024-05-28 09:19
> According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016 libquadmath is not supported on aarch64. libquadmath is not enabled on aarch64 within Fedora and Debian either.

I guess it won't be a surprise that openSUSE have the same idea and also disabled libquadmath on aarch64. I guess this means we really cannot fix this issue then by ourselves and hope that one day libquadmath is properly supported (?). 

BUT, this comment from the discussion is interesting https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016#c1
> If long double is 128bit fp already, then glibc has full support of it.  So you dont need libquadmath at all.  It is only there if long double is not 128bit long double and glibc does not have support for the __float128 type.

Does this mean that we don't really need libquadmath???

**Comment by imciner2** [comment] 2024-05-28 09:27
> I guess this means we really cannot fix this issue then by ourselves and hope that one day libquadmath is properly supported (?).

No, as I said earlier in the thread during the analysis of the issue, the problem lies inside the Julia Makefiles/build system. The error is occurring when trying to make symlinks to the libraries, not when doing any actual building.

**Comment by fxcoudert** [comment] 2024-05-28 09:28
On aarch64-linux, the 128-bit floating-point type is `long double`. Therefore, libquadmath is not built because it is not necessary, the libc (usually glibc) is in charge of providing runtime support for math and I/O on this type, because it is a standard type.

On aarch64-darwin, `long double` is the same as `double` (64-bit fp type), and the compiler does supports `__float128` as a 128-bit floating-point type. It then provides runtime support through libquadmath.

On other aarch64 targets, I do not know.

**Comment by giordano** [comment] 2024-05-28 16:00
That [has been answered](https://github.com/JuliaLang/julia/issues/41613#issuecomment-977023868) three years ago already: we don't touch that code path in our builds.

**Comment by fxcoudert** [comment] 2024-05-28 16:09
A logical fix would be this:

```
diff --git a/base/Makefile b/base/Makefile
index 9a6c0d0d03..febee53a9d 100644
--- a/base/Makefile
+++ b/base/Makefile
@@ -249,12 +249,12 @@ endif
 ifneq (,$(LIBGFORTRAN_VERSION))
 $(eval $(call symlink_system_library,CSL,libgfortran,$(LIBGFORTRAN_VERSION)))
 endif
-$(eval $(call symlink_system_library,CSL,libquadmath,0))
 $(eval $(call symlink_system_library,CSL,libstdc++,6))
-# We allow libssp, libatomic and libgomp to fail as they are not available on all systems
+# We allow libssp, libatomic, libgomp and libquadmath to fail as they are not available on all systems
 $(eval $(call symlink_system_library,CSL,libssp,0,ALLOW_FAILURE))
 $(eval $(call symlink_system_library,CSL,libatomic,1,ALLOW_FAILURE))
 $(eval $(call symlink_system_library,CSL,libgomp,1,ALLOW_FAILURE))
+$(eval $(call symlink_system_library,CSL,libquadmath,0,ALLOW_FAILURE))
 $(eval $(call symlink_system_library,PCRE,libpcre2-8))
 $(eval $(call symlink_system_library,DSFMT,libdSFMT))
 $(eval $(call symlink_system_library,LIBBLASTRAMPOLINE,libblastrampoline))
```

**Comment by uncomfyhalomacro** [comment] 2024-05-29 09:02
@ggardet Can you please test one of the binaries built in https://build.opensuse.org/projects/home:uncomfyhalomacro:branches:science/packages/julia/repositories/openSUSE_Tumbleweed/binaries ? I would really appreciate if you can test it. I don't own an aarch64 machine sadly.

**Comment by ggardet** [comment] 2024-05-29 13:24
> @ggardet Can you please test one of the binaries built in https://build.opensuse.org/projects/home:uncomfyhalomacro:branches:science/packages/julia/repositories/openSUSE_Tumbleweed/binaries ? I would really appreciate if you can test it. I don't own an aarch64 machine sadly.

Build works, but I get the following error on run:
```
ERROR: Unable to find compatible target in cached code image.
Target 0 (neoverse-n1): Rejecting this target due to use of runtime-disabled features
```
I guess the build machine is a `neoverse-n1` while mine is not.

**Comment by giordano** [comment] 2024-05-29 13:30
That's because the build system should set `JULIA_CPU_TARGETS` during the build, for example something like https://github.com/JuliaCI/julia-buildkite/blob/933c6d5fa18fe8168a1ec134d7cef82f8cfa5be0/utilities/build_envs.sh#L56-L70
```sh
JULIA_CPU_TARGETS="generic;cortex-a57;thunderx2t99;carmel,clone_all;apple-m1,base(3);neoverse-512tvb,base(3)"
```

**Comment by ggardet** [comment] 2024-05-29 13:40
> That's because the build system should set `JULIA_CPU_TARGETS` during the build, for example something like https://github.com/JuliaCI/julia-buildkite/blob/933c6d5fa18fe8168a1ec134d7cef82f8cfa5be0/utilities/build_envs.sh#L56-L70
> 
> ```shell
> JULIA_CPU_TARGETS="generic;cortex-a57;thunderx2t99;carmel,clone_all;apple-m1,base(3);neoverse-512tvb,base(3)"
> ```
> 
> See e.g. https://discourse.julialang.org/t/unexpected-precompilation-in-binder-based-on-docker-image/114473

I used `JULIA_CPU_TARGET="generic;neoverse-n1"` which was missing a `S`. Retrying.
And it worked on an AWS M6g machine as it is compatible with `neoverse-n1`.

**Comment by uncomfyhalomacro** [comment] 2024-05-29 13:41
> That's because the build system should set `JULIA_CPU_TARGETS` during the build, for example something like https://github.com/JuliaCI/julia-buildkite/blob/933c6d5fa18fe8168a1ec134d7cef82f8cfa5be0/utilities/build_envs.sh#L56-L70
> 
> ```shell
> JULIA_CPU_TARGETS="generic;cortex-a57;thunderx2t99;carmel,clone_all;apple-m1,base(3);neoverse-512tvb,base(3)"
> ```
> 
> See e.g. https://discourse.julialang.org/t/unexpected-precompilation-in-binder-based-on-docker-image/114473

Thanks for the heads up! I will update it.

**Comment by uncomfyhalomacro** [comment] 2024-05-29 23:31
@ggardet we can finally close this right? see #54605

**Closed** 2024-05-30 00:23 UTC
Labels: domain:building, system:linux, system:arm
