### ISSUE TITLE
== not symmetric on types

### ISSUE THREAD

**Issue by wbhart** [JuliaLang/julia#15599] opened 2016-03-23 13:23 UTC
The code below demonstrates that if I change the order of operands to == then I get a different result. This appears to affect the "in" operator. This is with Julia 0.5.0-dev+3171.

```
   module Mymod
      type mytype
      end
   end

   sig_table = [x.sig for x in methods(Base.promote_rule)]

   V = Tuple{typeof(Base.promote_rule),Type{Mymod.mytype},Type{Int64}}

   V in sig_table # returns true!!

   for s in sig_table # prints yes
      if V == s
         println("yes")
      end
   end

  for s in sig_table # prints nothing
      if s == V
         println("yes")
      end
   end
```

A workaround for now is that we can use === instead of ==, but this behaviour is doubtlessly affecting other things in Julia.

**Comment by lostanlen** [comment] 2016-04-05 08:09
I have run the code on v0.4.6 and the behavior is the same.
Note that the `yes`'s appear if and only if `s` is a tuple of abstract parametric type.
Am I mistaken to think that the `yes`'s should never appear ?

**Comment by vtjnash** [comment] 2016-04-12 19:34
fixed by e529058

**Closed by vtjnash** 2016-04-12 19:34 UTC

**Comment by nalimilan** [comment] 2016-04-12 19:52
Can this be backported?

**Comment by vtjnash** [comment] 2016-04-12 20:44
yes, although it'll makes some perf tests somewhat slower and others much faster since this depends on the `@pure` macro to fix the slow case, which i don't think existed in v0.4

**Comment by nalimilan** [comment] 2016-04-12 21:22
Though call. I've added the label anyway so that we don't forget it.

**Comment by tkelman** [comment] 2016-06-19 08:58
not backporting this as it causes some major performance regressions on release-0.4, ref #16980
