### ISSUE TITLE
Display of Vector{SparseMatrixCSC} produces unwanted blank spaces/lines

### ISSUE THREAD

**Issue by pablosanjose** [JuliaLang/julia#33401] opened 2019-09-27 13:56 UTC
There are sometimes lots of extra spaces that are printed when showing a vector of SparseArrays, which leads to unwanted blank lines. As an example:
`using SparseArrays, StaticArrays; r = rand(1:100,17); v = rand(SMatrix{2,2,ComplexF64},17); [sparse(r,r,v), sparse(r[1:3],r[1:3],v[1:3])]`

If I paste the result here the issue is not appreciated, as Github does not wrap the extra space (which is the cause of the unwanted blank lines). Here is a screenshot: 
<img width="1070" alt="Screenshot 2019-09-27 at 15 48 50" src="https://user-images.githubusercontent.com/4310809/65774984-99246800-e13f-11e9-8e14-a63ee953ff60.png">

Observed on macos, both in v1.1 and master

**Comment by StefanKarpinski** [comment] 2019-10-01 15:21
I can reproduce this.

**Comment by abraunst** [comment] 2019-10-02 07:06
Cannot reproduce with master on Linux.

**Comment by StefanKarpinski** [comment] 2019-10-09 14:44
Still able to reproduce on master.

**Comment by pablosanjose** [comment] 2019-10-09 14:49
@abraunst : maybe the difference is the way the Linux terminal wraps (or not) extra space. Can you please check whether there are actual spaces printed after the second sparse matrix? (see gray selection in screenshot)
<img width="1154" alt="Screenshot 2019-10-09 at 16 48 12" src="https://user-images.githubusercontent.com/4310809/66492403-a3862080-eab4-11e9-9ccc-c27c40c0bd98.png">

**Comment by KristofferC** [comment] 2019-10-09 14:56
1.3:

![bild](https://user-images.githubusercontent.com/1282691/66493040-ab929000-eab5-11e9-8e0a-5096459620fd.png)

master:

![bild](https://user-images.githubusercontent.com/1282691/66493059-afbead80-eab5-11e9-816c-527b9f9cca46.png)

**Comment by pablosanjose** [comment] 2019-10-09 15:01
Is that macos? Current master (from nightly) still has the issue for me. Didn't try compiling myself

**Comment by rfourquet** [comment] 2019-10-09 15:12
I confirm @KristofferC 's observation, I'm on Linux. I believe this was fixed in ##33298.

**Comment by abraunst** [comment] 2019-10-09 15:45
@pablosanjose: It does wrap (checked with `println(" "^1000")`). The issue is just not reproduceable here.

**Comment by KristofferC** [comment] 2019-10-09 15:53
Can someone that it reproduces for run

```
julia> using SparseArrays, StaticArrays; r = rand(1:100,17); v = rand(SMatrix{2,2,ComplexF64},17); A = [sparse(r,r,v), sparse(r[1:3],r[1:3],v[1:3])];

julia> sprint(show, MIME("text/plain"), A)
"2-element Array{SparseMatrixCSC{SArray{Tuple{2, ...
```

and see if there actually are newlines in the end.

**Comment by pablosanjose** [comment] 2019-10-09 16:51
Uh! I just tried again on master (compiled from source) and the problem is gone. I'm not sure why it failed before (perhaps I was not running master by mistake somehow). @StefanKarpinski, can you confirm? Shall I close this?

Thanks for the fix by the way!

**Closed** 2019-10-09 17:42 UTC
Labels: display and printing

**Comment by StefanKarpinski** [comment] 2019-10-09 19:36
I was confused about which spaces you were referring to. Looks fixed to me as well.
