### ISSUE TITLE
Change in behavior of extension loading in v1.11

### ISSUE THREAD

**Issue by sethaxen** [JuliaLang/julia#56426] opened 2024-11-03 15:29 UTC
Suppose I have a package A with an extension that depends on packages B and C. Package B also depends on C. On Julia v1.10, if I loaded packages A and B, the extension would be loaded. But on Julia v1.11, it seems that I must also explicitly load package C for the extension to be loaded.

I created a repo demonstrating this change in behavior: https://github.com/sethaxen/ExtensionsTestDemo.jl, where A=ExtensionTestDemo, B=StatsBase, C=Random. The [tests](https://github.com/sethaxen/ExtensionsTestDemo.jl/blob/main/test/runtests.jl) check whether the extension is loaded depending on which dependencies are loaded, and the CI (e.g. https://github.com/sethaxen/ExtensionsTestDemo.jl/actions/runs/11652519441) demonstrates the change in behavior between v1.10 and v1.11.

**Comment by IanButterworth** [comment] 2024-11-03 16:12
Duplicate of https://github.com/JuliaLang/julia/issues/56204 ?

**Comment by sethaxen** [comment] 2024-11-03 19:05
> Duplicate of [#56204](https://github.com/JuliaLang/julia/issues/56204) ?

I'm not convinced it is. There the issue seems to be one extension trying to load another. That's not happening here.

**Comment by topolarity** [comment] 2024-11-06 01:41
I can reproduce this on 1.11 but it appears to be resolved on nightly

I have a hunch this was probably fixed by https://github.com/JuliaLang/julia/pull/56234 (which is marked for 1.11 backport but hasn't been done yet)

**Comment by topolarity** [comment] 2024-11-22 19:41
I can confirm this is fixed by https://github.com/JuliaLang/julia/pull/56658 (backport of the above)

**Comment by topolarity** [comment] 2024-12-03 01:42
This should now be fixed in the recently released 1.11.2

Please reopen if you see any lingering issues

**Closed by topolarity** 2024-12-03 01:42 UTC
