### ISSUE TITLE
mac binaries not codesigned for 1.2

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#33141] opened 2019-09-03 08:53 UTC
The mac binaries are not code signed for 1.2. I believe the 1.3 binaries for mac are also not code signed.

@ararslan suggests that in the builder, we should probably error out if the code signing step fails (or have some other solution to make mac signing more robust).

**Comment by dgleich** [comment] 2019-09-05 13:15
Note that this throws an "unidentified developer" error on macOS, which is what I was googling and searching for to see if anyone had reported this already. (https://discourse.julialang.org/t/julia-1-2-not-signed-correctly-on-macos/28396)

More specifically, the full error is (for future Google-ability)

```
“Julia-1.2” can’t be opened because it is from an unidentified developer.

Your security preferences allow installation of only apps from the App Store and identified developers.
```

Also, note that you can still launch Julia by using Finder to browse to the Applications directory. Then right click on Julia, and click Open. This will allow you to override the unidentified developer prompt. 

---

For what it's worth, I agree with erroring in the build if this fails. There have been enough man-in-the-middle attacks on open source projects on various platforms (e.g. look at the Handbrake scenario a few years ago -- https://blog.malwarebytes.com/threat-analysis/mac-threat-analysis/2017/05/handbrake-hacked-to-drop-new-variant-of-proton-malware/), that this really did make me worry I had a tampered download.

**Comment by ararslan** [comment] 2019-09-05 16:52
Apparently the issue is that our code signing certificate expired.

**Comment by ViralBShah** [comment] 2019-09-05 17:06
Cc @mdpradeep

**Comment by ViralBShah** [comment] 2019-09-14 12:56
@staticfloat @ararslan Please close this if matter resolved.

**Comment by ViralBShah** [comment] 2019-09-14 15:42
The `1.0.5` binaries also say "can't be opened because it is from an unidentified developer".

**Comment by ararslan** [comment] 2019-09-14 16:04
That's bizarre, because I checked the signing for 1.0.5 before uploading. 😕

**Comment by staticfloat** [comment] 2019-09-14 17:53
Did you clear the fastly cache? The curl -X PURGE thing?

**Comment by ararslan** [comment] 2019-09-14 18:05
I did for all 1.0-latest URLs, yeah

**Comment by staticfloat** [comment] 2019-09-15 05:09
Okay, I think I uploaded the unsigned 1.0.5 after signing it. I've re-uploaded a properly signed `.dmg`; try again.

**Comment by mbauman** [comment] 2019-10-08 15:00
This is now fixed — both the 1.0 and 1.2 binaries are properly signed (but folks on 10.15 Catalina will start seeing issue #33331).

**Closed by mbauman** 2019-10-08 15:00 UTC
Labels: build, mac

**Comment by conradwt** [comment] 2019-11-26 23:13
I just tried it with Julia 1.3.0 and it does not work at this time.  Does the Julia Core Team have a long term strategy to properly sign these application bundles for macOS 10.15 and newer because I really don't like clicking Open Anyway?  Also, I didn't see a note about this on the download page.

**Comment by ararslan** [comment] 2019-11-26 23:46
@conradwt, that's https://github.com/JuliaLang/julia/issues/33331. See discussion there for details.
