### ISSUE TITLE
Add doc string for broadcast operators

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaLang/julia#34150] opened 2019-12-19 17:15 UTC
I am looking at broadcast.jl and wondering what magic is occurring for me to use ".+" in an expression and have it work but when I type it by itself it gives an error.  

Why is it not like an addition where it's just a generic function? 

The goal of my exploration is to try and document the ".+" and ".*" broadcasting ability.

**Comment by mbauman** [comment] 2019-12-19 19:24
For the magic, see `Meta.@lower a .+ b`.  It's a syntax (more precisely, a lowering) thing that requires it appearing as an infix operator.

When used alone, though, it's parsed as a regular identifier, which is less-than-optimal.  That's why the help system is looking for it as a binding.

I could have sworn that we had an issue about generally improving the actual usability of standalone `.+` and friends, but I cannot find it now.  We've talking about it making it lower directly to `(args...) -> (+).(args...)`.  Was that just on slack or discourse?  Or maybe somewhere hidden in the huge [currying thread?](https://github.com/JuliaLang/julia/pull/24990)?

**Comment by mbauman** [comment] 2019-12-19 19:31
Duplicate of #33301

**Closed by mbauman** 2019-12-19 19:31 UTC
Labels: broadcast, doc
