### ISSUE TITLE
Source build of 1.9.0 on macOS ARM: make testall failures in testset backtrace

### ISSUE THREAD

**Issue by George9000** [JuliaLang/julia#45830] opened 2022-06-27 01:55 UTC
Built committ f849517c9f. The failure is new since 2f90355d22 which passed make testall.

Test was run with an isolated JULIA_DEPOT_PATH

Details of versioninfo and test results below. 

<details>
<summary>versioninfo</summary>

```
Julia Version 1.9.0-DEV.850
Commit f849517c9f (2022-06-26 16:19 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  uname: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 arm
  CPU: Apple M1 Max:
                 speed         user         nice          sys         idle          irq
       #1-10    24 MHz     343426 s          0 s     231484 s    9159534 s          0 s
  Memory: 64.0 GB (39037.234375 MB free)
  Uptime: 118733.0 sec
  Load Avg:  1.50634765625  2.779296875  3.93017578125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_DEPOT_PATH = /Users/foo/Desktop
  XPC_FLAGS = 0x0
  PATH = /Users/foo/.pyenv/bin:/opt/homebrew/opt/grep/libexec/gnubin:/Users/foo/bin:/Users/foo/.local/bin:/opt/homebrew/bin:/Users/foo/Library/Python/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/MacPorts/EmacsMac.app/Contents/MacOS:/opt/local/bin:/opt/local/sbin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/foo/perl5/perlbrew/bin:/Users/foo/perl5/perlbrew/perls/perl-5.35.5/bin:/Users/foo/.local/bin:/opt/homebrew/opt/fzf/bin:/Users/foo/.emacs.d/bin
  TERM = xterm-256color
  HOME = /Users/foo
  PERLBREW_HOME = /Users/foo/.perlbrew
  PERLBREW_MANPATH = /Users/foo/perl5/perlbrew/perls/perl-5.35.5/man
  PERLBREW_PATH = /Users/foo/perl5/perlbrew/bin:/Users/foo/perl5/perlbrew/perls/perl-5.35.5/bin
  MANPATH = /opt/local/share/man:/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/opt/X11/share/man:/Users/foo/perl5/perlbrew/perls/perl-5.35.5/man:/Library/Apple/usr/share/man:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man:
  HOMEBREW_PREFIX = /opt/homebrew
  HOMEBREW_CELLAR = /opt/homebrew/Cellar
  HOMEBREW_REPOSITORY = /opt/homebrew
  INFOPATH = /opt/homebrew/share/info:
```

</details>

<details>
<summary>test summary</summary>

```
Test Summary:                             |     Pass  Fail  Broken     Total      Time
  Overall                                 | 40598302     2  352667  40950971  16m39.7s
    LinearAlgebra/schur                   |      496                     496     20.2s
    LinearAlgebra/bunchkaufman            |     5688                    5688     31.7s
    LinearAlgebra/eigen                   |      512                     512     39.8s
    LinearAlgebra/lapack                  |      802                     802     19.6s
    LinearAlgebra/svd                     |      566                     566     31.3s
    LinearAlgebra/qr                      |     4705                    4705     57.0s
    LinearAlgebra/tridiag                 |     1541                    1541     28.1s
    LinearAlgebra/cholesky                |     2509                    2509     42.3s
    LinearAlgebra/special                 |     2942                    2942   1m44.4s
    LinearAlgebra/lu                      |     1368                    1368     54.1s
    LinearAlgebra/generic                 |      630                     630     22.9s
    LinearAlgebra/dense                   |     8475                    8475   2m27.3s
    LinearAlgebra/bidiag                  |     4736                    4736   1m37.5s
    LinearAlgebra/uniformscaling          |      446                     446     33.6s
    LinearAlgebra/lq                      |     2938                    2938     34.4s
    LinearAlgebra/pinv                    |      500                     500      6.8s
    LinearAlgebra/adjtrans                |      347                     347     13.9s
    LinearAlgebra/givens                  |     1847                    1847      2.9s
    LinearAlgebra/matmul                  |     1486                    1486   2m51.8s
    LinearAlgebra/ldlt                    |        8                       8      0.7s
    LinearAlgebra/blas                    |     1600                    1600     25.5s
    LinearAlgebra/factorization           |       80            16        96      2.7s
    LinearAlgebra/hessenberg              |      631                     631     29.8s
    compiler/validation                   |       28                      28      0.3s
    compiler/ssair                        |       69                      69      1.8s
    compiler/irpasses                     |      139             4       143      1.9s
    compiler/inference                    |     1225             2      1227      8.5s
    ambiguous                             |      104             2       106     10.3s
    compiler/inline                       |      185             1       186      2.2s
    compiler/contextual                   |       12                      12      1.3s
    compiler/codegen                      |      172                     172      7.4s
    compiler/AbstractInterpreter          |       12                      12      3.5s
    compiler/EscapeAnalysis/interprocedural |       32             4        36      3.6s
    compiler/EscapeAnalysis/local         |      347            21       368      7.3s
    strings/search                        |      876                     876      3.3s
    strings/basic                         |    87693                   87693      5.7s
    LinearAlgebra/structuredbroadcast     |      670                     670     28.6s
    strings/io                            |    12764                   12764      1.9s
    unicode/utf8                          |       19                      19      0.1s
    strings/types                         |  2302691                 2302691      2.1s
    LinearAlgebra/diagonal                |     2877                    2877   2m29.3s
    worlds                                |       88                      88      1.3s
    strings/util                          |     1147                    1147      5.7s
    keywordargs                           |      151                     151      1.0s
    atomics                               |     3448                    3448      8.3s
    subtype                               |   337679            19    337698      7.2s
    triplequote                           |       29                      29      0.0s
    char                                  |     1639                    1639      1.4s
    intrinsics                            |      304                     304      1.4s
    hashing                               |    12519                   12519      8.9s
    iobuffer                              |      209                     209      0.7s
    staged                                |       65                      65      1.3s
    dict                                  |   144426                  144426     13.6s
    numbers                               |  1578845             3   1578848     33.2s
    tuple                                 |      666                     666      4.0s
    offsetarray                           |      484             3       487     19.5s
    LinearAlgebra/symmetric               |     2823                    2823   2m25.5s
    core                                  |  8445938             3   8445941     46.9s
    reduce                                |     8586                    8586     10.4s
    simdloop                              |      240                     240      0.9s
    vecelement                            |      678                     678      3.6s
    rational                              |    98695             2     98697     11.6s
    intfuncs                              |   228009                  228009     19.6s
    copy                                  |      544                     544      1.6s
    subarray                              |   318323                  318323   1m29.4s
    reducedim                             |     1225             6      1231     38.8s
    fastmath                              |      946                     946      4.1s
    functional                            |       98                      98      3.0s
    LinearAlgebra/triangular              |    37908                   37908   4m44.6s
    arrayops                              |     2087             6      2093   1m00.6s
    path                                  |      373            12       385      0.7s
    ordering                              |       37                      37      1.3s
    operators                             |    13046                   13046      3.8s
    parse                                 |    16098                   16098      2.6s
    math                                  |  1909833                 1909833     23.0s
    gmp                                   |     2444                    2444      3.9s
    ccall                                 |   165125             1    165126     12.8s
    backtrace                             |       37     2       1        40      1.5s
    exceptions                            |       70                      70      1.1s
    loading                               |   161451                  161451     16.6s
    spawn                                 |      252             4       256     14.6s
    version                               |     2453                    2453      0.6s
    abstractarray                         |    55369         24795     80164   1m03.5s
    file                                  |     1074                    1074      5.2s
    namedtuple                            |      216                     216      1.4s
    complex                               |     8479             2      8481      6.6s
    floatapprox                           |       49                      49      0.7s
    reflection                            |      425                     425      3.3s
    regex                                 |      134                     134      1.3s
    mpfr                                  |     1137             1      1138     12.8s
    read                                  |     3812                    3812     19.2s
    sysinfo                               |        4                       4      0.1s
    env                                   |       96                      96      0.3s
    float16                               |   762093                  762093      4.0s
    combinatorics                         |      170                     170      4.2s
    mod2pi                                |       80                      80      0.3s
    euler                                 |       12                      12      0.8s
    rounding                              |   150016                  150016      3.4s
    client                                |        5                       5      0.8s
    errorshow                             |      245                     245      3.5s
    iterators                             |    86613                   86613     53.9s
    goto                                  |       19                      19      0.1s
    llvmcall                              |       19                      19      0.3s
    llvmcall2                             |       20                      20      0.1s
    ryu                                   |    31215                   31215      1.2s
    some                                  |       72                      72      0.7s
    meta                                  |       69                      69      0.8s
    stacktraces                           |       48                      48      1.1s
    docs                                  |      238                     238      2.4s
    show                                  |   128889             8    128897     19.0s
    sets                                  |     3643             1      3644     14.9s
    broadcast                             |      523                     523     39.8s
    binaryplatforms                       |      341                     341      4.1s
    atexit                                |       40                      40      5.3s
    enums                                 |      100                     100      2.8s
    interpreter                           |        3                       3      0.9s
    ranges                                | 12110692        327682  12438374     30.4s
    bitset                                |      195                     195      1.3s
    checked                               |     1239                    1239      5.6s
    int                                   |   736188                  736188      7.3s
    error                                 |       33                      33      1.0s
    boundscheck                           |                             None      4.6s
    osutils                               |       43                      43      0.0s
    cartesian                             |      349             3       352      6.1s
    iostream                              |       50                      50      0.7s
    secretbuffer                          |       30                      30      1.0s
    specificity                           |      175                     175      0.1s
    sorting                               |    24191             9     24200   1m18.8s
    misc                                  |  1282184                 1282184     30.1s
    syntax                                |     1659             1      1660      6.3s
    corelogging                           |      235                     235      4.5s
    channels                              |      256                     256     16.3s
    reinterpretarray                      |      420                     420     11.4s
    smallarrayshrink                      |       36                      36      0.2s
    filesystem                            |        6                       6      0.2s
    opaque_closure                        |       66             1        67      0.4s
    bitarray                              |   912211                  912211   1m58.3s
    asyncmap                              |      307                     307      8.4s
    missing                               |      574             1       575     12.9s
    SparseArrays/basetests                |       28                      28      4.5s
    LibGit2/online                        |       10                      10      2.8s
    download                              |                             None     31.1s
    Dates/accessors                       |  7723858                 7723858      3.0s
    Dates/adjusters                       |     3149                    3149      2.7s
    Dates/query                           |     1004                    1004      0.6s
    Dates/periods                         |      953                     953      8.4s
    Dates/ranges                          |   350637                  350637      9.9s
    Dates/rounding                        |      315                     315      1.2s
    Dates/types                           |      232                     232      0.9s
    Dates/io                              |      332                     332      6.8s
    Dates/arithmetic                      |      385                     385      3.7s
    Dates/conversions                     |      161                     161      0.5s
    SparseArrays/higherorderfns           |     7145             1      7146   1m11.3s
    ArgTools                              |      180                     180      4.2s
    Base64                                |     2031                    2031      2.2s
    Artifacts                             |     1452                    1452      3.7s
    CompilerSupportLibraries_jll          |        4                       4      0.0s
    CRC32c                                |      664                     664      0.4s
    DelimitedFiles                        |       89                      89      4.5s
    LibGit2/libgit2                       |      755                     755   1m03.3s
    Future                                |                             None      0.0s
    GMP_jll                               |        1                       1      0.4s
    InteractiveUtils                      |      281                     281     11.1s
    LLVMLibUnwind_jll                     |        7                       7      0.2s
    LazyArtifacts                         |        4                       4      2.3s
    LibCURL                               |        6                       6      1.0s
    LibCURL_jll                           |        1                       1      0.0s
    LibGit2_jll                           |        2                       2      0.8s
    LibSSH2_jll                           |                             None      0.0s
    LibUV_jll                             |        1                       1      0.2s
    LibUnwind_jll                         |                             None      0.1s
    Libdl                                 |       80             1        81      0.4s
    Logging                               |       40                      40      0.7s
    MPFR_jll                              |        1                       1      0.2s
    Markdown                              |      257                     257      2.9s
    MbedTLS_jll                           |        1                       1      0.0s
    cmdlineargs                           |      283             5       288   2m24.9s
    MozillaCACerts_jll                    |        1                       1      0.0s
    NetworkOptions                        |     3518                    3518      0.9s
    OpenBLAS_jll                          |        1                       1      0.0s
    Mmap                                  |      140                     140     15.5s
    OpenLibm_jll                          |        1                       1      0.3s
    PCRE2_jll                             |        2                       2      0.3s
    Printf                                |     1014                    1014      6.8s
    SparseArrays/sparsevector             |    10365             4     10369   2m00.4s
    floatfuncs                            |      232                     232   2m46.5s
    REPL                                  |     1460             3      1463     16.5s
    Downloads                             |      238                     238   1m09.4s
    Serialization                         |      129             1       130      3.7s
    Sockets                               |      172                     172      5.3s
    Profile                               |      113                     113     50.2s
    SuiteSparse                           |                             None      0.0s
    SuiteSparse_jll                       |        1                       1      0.7s
    Random                                |   204835                  204835     33.5s
    TOML                                  |      415             8       423      5.9s
    SHA                                   |      107                     107     44.5s
    UUIDs                                 |     1029                    1029      0.2s
    FileWatching                          |      634                     634   1m49.5s
    Zlib_jll                              |        1                       1      0.2s
    dSFMT_jll                             |        1                       1      0.4s
    libLLVM_jll                           |        1                       1      0.2s
    libblastrampoline_jll                 |        1                       1      0.0s
    nghttp2_jll                           |        1                       1      0.0s
    p7zip_jll                             |        1                       1      0.0s
    Unicode                               |      795                     795      3.2s
    Statistics                            |      804                     804     40.3s
    Tar                                   |     3161            11      3172     18.1s
    Test                                  |      458            17       475     21.9s
    SparseArrays/sparse                   |     4355                    4355   3m43.0s
    LinearAlgebra/addmul                  |     6876                    6876   9m07.9s
    Pkg                                   |     2456             2      2458   8m18.1s
    precompile                            |      155                     155     18.5s
    SharedArrays                          |      114                     114     11.9s
    threads                               |       40                      40   1m24.4s
    Distributed                           |       15                      15   1m58.4s
    stress                                |      118                     118      7.5s
    FAILURE

The global RNG seed was 0xe07dee24d07c22b1bc1effbaeb4405ff.

Error in testset backtrace:
Test Failed at /Users/foo/applications/julia/test/backtrace.jl:182
  Expression: found
Error in testset backtrace:
Test Failed at /Users/foo/applications/julia/test/backtrace.jl:194
  Expression: found
ERROR: LoadError: Test run finished with errors
in expression starting at /Users/foo/applications/julia/test/runtests.jl:93
gmake[1]: *** [Makefile:25: all] Error 1
gmake: *** [Makefile:558: testall] Error 2
```

</details>

Culprit section in `backtrace.jl`, lines 182 and 194

```
172 # issue #27959
173 let bt, found = false
174     @testset begin
175         bt = backtrace()
176     end
177     for frame in map(lookup, bt)
178         if frame[1].line == @__LINE__() - 3 && frame[1].file == Symbol(@__FILE__)
179             found = true; break
180         end
181     end
182     @test found
183 end
184
185 # issue 28618
186 let bt, found = false
187     @debug ""
188     bt = backtrace()
189     for frame in map(lookup, bt)
190         if frame[1].line == @__LINE__() - 2 && frame[1].file == Symbol(@__FILE__)
191             found = true; break
192         end
193     end
194     @test found
```

A git bisect goes back to:

```
a12c2f0a0dcf39fd8c8a0130b1df4a0a059828ca is the first bad commit
commit a12c2f0a0dcf39fd8c8a0130b1df4a0a059828ca
Author: Valentin Churavy <v.churavy@gmail.com>
Date:   Mon May 2 13:20:01 2022 -0400

    Upgrade to LLVM 14.0.2

 Makefile                              |   2 +-
 base/binaryplatforms.jl               |   2 +-
 contrib/refresh_checksums.mk          |   6 +-
 deps/Versions.make                    |  14 +-
 deps/checksums/clang                  | 174 ++++++++----
 deps/checksums/lld                    | 116 ++++++++
 deps/checksums/llvm                   | 502 ++++++++++++++++++----------------
 deps/llvm.mk                          |  23 +-
 deps/llvm.version                     |   4 +-
 deps/tools/bb-install.mk              |   7 +-
 src/Makefile                          |   2 +-
 src/codegen.cpp                       |   4 +-
 src/intrinsics.cpp                    |   2 +-
 src/llvm-muladd.cpp                   |   5 +-
 src/llvm-multiversioning.cpp          |   6 +-
 src/llvm-ptls.cpp                     |   7 +-
 src/llvm-simdloop.cpp                 |   4 +-
 stdlib/libLLVM_jll/Project.toml       |   2 +-
 stdlib/libLLVM_jll/src/libLLVM_jll.jl |   4 +-
 19 files changed, 560 insertions(+), 326 deletions(-)
 create mode 100644 deps/checksums/lld
```

**Comment by DilumAluthge** [comment] 2022-06-27 02:05
Thanks for reporting this! I think that this is a duplicate of #45784.

**Comment by DilumAluthge** [comment] 2022-06-27 21:25
Duplicate of #45784

**Closed by DilumAluthge** 2022-06-27 21:25 UTC
