### ISSUE TITLE
Julia 1.11 EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by gyk** [JuliaLang/julia#56209] opened 2024-10-17 09:15 UTC
Julia 1.11.x crashes on Windows 11.

## Steps To Reproduce

1. Generate an empty package using Pkg.jl.
2. Edit the source file:
    ```js
    module Bug

    export crash

    crash() = print("Hello World!")

    end
    ```
3. Run it in REPL:

    ```julia
    (@v1.11) pkg> activate .
      Activating project at `C:\Users\USER\Documents\Code\JuliaPrj\Bug`
    
    julia> using Bug
    [ Info: Precompiling Bug [be2db2ca-1662-471a-a884-a34a37ba56f1]
    
    Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
    Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffecfc00690 -- fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2353
    in expression starting at REPL[2]:1
    ```

- Version info:
    
    ```
    julia> versioninfo()
    Julia Version 1.11.1
    Commit 8f5b7ca12a (2024-10-16 10:53 UTC)
    Build Info:
      Official https://julialang.org/ release
    Platform Info:
      OS: Windows (x86_64-w64-mingw32)
      CPU: 16 × Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
      WORD_SIZE: 64
      LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
    Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
    ```

<details>
<summary>Complete output</summary>

```
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffecfc00690 -- fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2353
in expression starting at REPL[2]:1
fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2353
uv__fs_work at /workspace/srcdir/libuv\src/win\fs.c:3205
uv_fs_chmod at /workspace/srcdir/libuv\src/win\fs.c:3761
jl_fs_chmod at C:/workdir/src\jl_uv.c:614
#chmod#40 at .\file.jl:1282
chmod at .\file.jl:1281 [inlined]
#compilecache#1094 at .\loading.jl:3023
compilecache at .\loading.jl:2949
compilecache at .\loading.jl:2949
unknown function (ip: 0000022cfeebc2c4)
#1082 at .\loading.jl:2492
#mkpidlock#7 at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:95
unknown function (ip: 0000022cfeebbfcb)
mkpidlock at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:92
#mkpidlock#6 at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:90 [inlined]
mkpidlock at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:90
jfptr_mkpidlock_45840.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
do_apply at C:/workdir/src\builtins.c:831
#trymkpidlock#11 at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:116
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
do_apply at C:/workdir/src\builtins.c:831
trymkpidlock at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:114
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_latest at C:/workdir/src\builtins.c:875
#invokelatest#2 at .\essentials.jl:1057 [inlined]
invokelatest at .\essentials.jl:1052 [inlined]
#maybe_cachefile_lock#1104 at .\loading.jl:3609
maybe_cachefile_lock at .\loading.jl:3606 [inlined]
_require at .\loading.jl:2488
__require_prelocked at .\loading.jl:2315
jfptr___require_prelocked_71550.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_in_world at C:/workdir/src\builtins.c:894
#invoke_in_world#3 at .\essentials.jl:1089 [inlined]
invoke_in_world at .\essentials.jl:1086 [inlined]
_require_prelocked at .\loading.jl:2302
macro expansion at .\loading.jl:2241 [inlined]
macro expansion at .\lock.jl:273 [inlined]
__require at .\loading.jl:2198
jfptr___require_71487.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_in_world at C:/workdir/src\builtins.c:894
#invoke_in_world#3 at .\essentials.jl:1089 [inlined]
invoke_in_world at .\essentials.jl:1086 [inlined]
require at .\loading.jl:2191
jfptr_require_71476.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
call_require at C:/workdir/src\toplevel.c:486 [inlined]
eval_import_path at C:/workdir/src\toplevel.c:523
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:759
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:886
ijl_toplevel_eval at C:/workdir/src\toplevel.c:952 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:994
eval at .\boot.jl:430 [inlined]
eval_user_input at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:245
repl_backend_loop at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:342
#start_repl_backend#59 at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:327
start_repl_backend at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:324
#run_repl#72 at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:483
run_repl at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:469
jfptr_run_repl_10352 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\share\julia\compiled\v1.11\REPL\u0gqU_e6ieL.dll (unknown line)
#1139 at .\client.jl:446
jfptr_YY.1139_15054 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\share\julia\compiled\v1.11\REPL\u0gqU_e6ieL.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_latest at C:/workdir/src\builtins.c:875
#invokelatest#2 at .\essentials.jl:1055 [inlined]
invokelatest at .\essentials.jl:1052 [inlined]
run_main_repl at .\client.jl:430
repl_main at .\client.jl:567 [inlined]
_start at .\client.jl:541
jfptr__start_73819.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
true_main at C:/workdir/src\jlapi.c:900
jl_repl_entrypoint at C:/workdir/src\jlapi.c:1059
mainCRTStartup at C:/workdir/cli\loader_exe.c:58
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 3085715 (Pool: 3085594; Big: 121); GC: 4

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffecfc00690 -- fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2353
in expression starting at REPL[2]:1
fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2353
uv__fs_work at /workspace/srcdir/libuv\src/win\fs.c:3205
uv_fs_chmod at /workspace/srcdir/libuv\src/win\fs.c:3761
jl_fs_chmod at C:/workdir/src\jl_uv.c:614
#chmod#40 at .\file.jl:1282
chmod at .\file.jl:1281 [inlined]
#rm#10 at .\file.jl:280
rm at .\file.jl:273 [inlined]
tryrmopenfile at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:313
close at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:343
jfptr_close_50607.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
run_finalizer at C:/workdir/src\gc.c:299
jl_gc_run_finalizers_in_list at C:/workdir/src\gc.c:389
run_finalizers at C:/workdir/src\gc.c:435
ijl_atexit_hook at C:/workdir/src\init.c:299
ijl_exit at C:/workdir/src\init.c:207
jl_exception_handler at C:/workdir/src\signals-win.c:337 [inlined]
jl_exception_handler at C:/workdir/src\signals-win.c:229
__julia_personality at C:/workdir/src\win32_ucontext.c:28
_chkstk at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlFindCharInUnicodeString at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
KiUserExceptionDispatcher at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
fs__chmod at /workspace/srcdir/libuv\src/win\fs.c:2353
uv__fs_work at /workspace/srcdir/libuv\src/win\fs.c:3205
uv_fs_chmod at /workspace/srcdir/libuv\src/win\fs.c:3761
jl_fs_chmod at C:/workdir/src\jl_uv.c:614
#chmod#40 at .\file.jl:1282
chmod at .\file.jl:1281 [inlined]
#compilecache#1094 at .\loading.jl:3023
compilecache at .\loading.jl:2949
compilecache at .\loading.jl:2949
unknown function (ip: 0000022cfeebc2c4)
#1082 at .\loading.jl:2492
#mkpidlock#7 at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:95
unknown function (ip: 0000022cfeebbfcb)
mkpidlock at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:92
#mkpidlock#6 at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:90 [inlined]
mkpidlock at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:90
jfptr_mkpidlock_45840.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
do_apply at C:/workdir/src\builtins.c:831
#trymkpidlock#11 at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:116
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
do_apply at C:/workdir/src\builtins.c:831
trymkpidlock at C:\workdir\usr\share\julia\stdlib\v1.11\FileWatching\src\pidfile.jl:114
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_latest at C:/workdir/src\builtins.c:875
#invokelatest#2 at .\essentials.jl:1057 [inlined]
invokelatest at .\essentials.jl:1052 [inlined]
#maybe_cachefile_lock#1104 at .\loading.jl:3609
maybe_cachefile_lock at .\loading.jl:3606 [inlined]
_require at .\loading.jl:2488
__require_prelocked at .\loading.jl:2315
jfptr___require_prelocked_71550.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_in_world at C:/workdir/src\builtins.c:894
#invoke_in_world#3 at .\essentials.jl:1089 [inlined]
invoke_in_world at .\essentials.jl:1086 [inlined]
_require_prelocked at .\loading.jl:2302
macro expansion at .\loading.jl:2241 [inlined]
macro expansion at .\lock.jl:273 [inlined]
__require at .\loading.jl:2198
jfptr___require_71487.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_in_world at C:/workdir/src\builtins.c:894
#invoke_in_world#3 at .\essentials.jl:1089 [inlined]
invoke_in_world at .\essentials.jl:1086 [inlined]
require at .\loading.jl:2191
jfptr_require_71476.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
call_require at C:/workdir/src\toplevel.c:486 [inlined]
eval_import_path at C:/workdir/src\toplevel.c:523
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:759
jl_toplevel_eval_flex at C:/workdir/src\toplevel.c:886
ijl_toplevel_eval at C:/workdir/src\toplevel.c:952 [inlined]
ijl_toplevel_eval_in at C:/workdir/src\toplevel.c:994
eval at .\boot.jl:430 [inlined]
eval_user_input at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:245
repl_backend_loop at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:342
#start_repl_backend#59 at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:327
start_repl_backend at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:324
#run_repl#72 at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:483
run_repl at C:\workdir\usr\share\julia\stdlib\v1.11\REPL\src\REPL.jl:469
jfptr_run_repl_10352 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\share\julia\compiled\v1.11\REPL\u0gqU_e6ieL.dll (unknown line)
#1139 at .\client.jl:446
jfptr_YY.1139_15054 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\share\julia\compiled\v1.11\REPL\u0gqU_e6ieL.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
jl_f__call_latest at C:/workdir/src\builtins.c:875
#invokelatest#2 at .\essentials.jl:1055 [inlined]
invokelatest at .\essentials.jl:1052 [inlined]
run_main_repl at .\client.jl:430
repl_main at .\client.jl:567 [inlined]
_start at .\client.jl:541
jfptr__start_73819.1 at C:\Users\USER\AppData\Local\Programs\Julia-1.11.1\lib\julia\sys.dll (unknown line)
jl_apply at C:/workdir/src\julia.h:2157 [inlined]
true_main at C:/workdir/src\jlapi.c:900
jl_repl_entrypoint at C:/workdir/src\jlapi.c:1059
mainCRTStartup at C:/workdir/cli\loader_exe.c:58
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
Allocations: 3184843 (Pool: 3184717; Big: 126); GC: 5
```
</details>

**Comment by vtjnash** [comment] 2024-10-17 13:16
Duplicate of https://github.com/JuliaLang/libuv/issues/23

**Comment by vtjnash** [comment] 2024-10-17 13:16
Duplicate of https://github.com/JuliaLang/julia/issues/41642#issue-947862182

**Closed by vtjnash** 2024-10-17 13:16 UTC
