### ISSUE TITLE
Misplaced label in code_native on LLVM3.7

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#13257] opened 2015-09-21 17:32 UTC
`@code_native` appears to be a little broken on LLVM 3.7. The labels are all printed at the very beginning, which is **not** very helpful to figure out the control flow.....

```asm
julia> function f(a)
           s = zero(eltype(a))
           @inbounds for i in 1:length(a)
               s += a[i]
           end
           s
       end
f (generic function with 1 method)

julia> @code_native f(Int[])
L16:L29:        .text
        movq    8(%rdi), %rcx
        xorl    %eax, %eax
        testq   %rcx, %rcx
        jle     L29
        movq    (%rdi), %rdx
        xorl    %eax, %eax
        addq    (%rdx), %rax
        addq    $8, %rdx
        addq    $-1, %rcx
        jne     L16
        retq
        nop
        pushq   %rax
        movq    (%rsi), %rdi
        movabsq $f, %rax
        callq   *%rax
        movabsq $jl_box_int64, %rcx
        movq    %rax, %rdi
        callq   *%rcx
        popq    %rdx
        retq
```

@vtjnash I remember you have a PR about `code_native`?
Also @Keno 

Edit: add missing `**not**`

**Comment by ihnorton** [comment] 2015-09-21 17:35
#12060?

**Comment by vtjnash** [comment] 2015-09-21 17:46
yep, duplicate of #12060

**Closed by vtjnash** 2015-09-21 17:46 UTC
