### ISSUE TITLE
Impossible values of allunique() and allequal()

### ISSUE THREAD

**Issue by Eldriitch** [JuliaLang/julia#55134] opened 2024-07-15 19:36 UTC
With the following struct, `allunique` and `allequal` are giving incompatible (and mathematically impossible!) results. 
MWE:
```julia
module MWE
struct Problem
    position::Array{Float64}
    value::Float64
end
Base.:(==)(a::Problem, b::Problem) = a.position == b.position && a.value == b.value
end
```
and then in the REPL
```julia
julia> X = [MWE.Problem([0.0,0.0,0.0], 4*pi) for i in 1:32];

julia> allunique(X)
true
julia> allequal(X)
true
```
And even more confusingly
```julia
julia> allunique(X[1:31])
false
julia> allequal(X[1:31])
true
```
So not only are we getting incompatible values of `allunique` and `allequal`, we also fail to have `allunique(X) => allunique(X[1:end])`.
Clearly `allunique` is behaving both contrary to the documentation and any reasonable expectation, for iterators with at least 32 entries.  
Julia versioninfo:
```
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
```

**Comment by mbauman** [comment] 2024-07-15 19:47
When you change how a struct defines equality, you must also symmetrically change how it hashes.  Check out [AutoHashEquals.jl](https://github.com/JuliaServices/AutoHashEquals.jl).

Closing as a duplicate of https://github.com/JuliaLang/julia/issues/12198.

**Closed by mbauman** 2024-07-15 19:47 UTC

**Comment by Eldriitch** [comment] 2024-07-15 19:48
I see -- that makes sense. Not great that the documentation is just... literally wrong then.

**Comment by mbauman** [comment] 2024-07-15 20:24
The biggest issue that I see is that the `==` docstring could be worded more strongly in what it means to implement. See my suggested improvement in #55135.
