### ISSUE TITLE
make dist -> no python

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#10268] opened 2015-02-21 12:58 UTC
Hi there, I tried to build the newest master on windows like always, but I got this error message:
```
Sim@Sn MSYS ~/julia
$ make dist
rm -fr julia-*.tar.gz julia*.exe julia-*.7z julia-dcfe82f079
make[1]: Entering directory '/home/Sim/julia'
    CC usr/bin/stringreplace
make[2]: Entering directory '/home/Sim/julia/doc'
make -C /home/Sim/julia/deps install-virtualenv
make[3]: Entering directory '/home/Sim/julia/deps'
/home/Sim/julia/deps/jldownload virtualenv-1.11.6.tar.gz https://pypi.python.org                                                                                                                                                 /packages/source/v/virtualenv/virtualenv-1.11.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1572k  100 1572k    0     0   611k      0  0:00:02  0:00:02 --:--:--  623k
/home/Sim/julia/deps/jlchecksum virtualenv-1.11.6.tar.gz
`which gtar 2>/dev/null || which tar 2>/dev/null` zxf virtualenv-1.11.6.tar.gz
touch -c virtualenv-1.11.6/virtualenv.py
which: no python in (/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python:/home/S                                                                                                                                                 im/julia/usr/lib:/home/Sim/julia/usr/lib/julia:/c/Program Files/7-zip:/home/Sim/                                                                                                                                                 julia/usr/lib:/home/Sim/julia/usr/lib/julia:/c/Program Files/7-zip)
"" virtualenv-1.11.6/virtualenv.py julia-env
/bin/sh: : command not found
Makefile:1773: recipe for target 'julia-env' failed
make[3]: *** [julia-env] Error 127
make[3]: Leaving directory '/home/Sim/julia/deps'
Makefile:23: recipe for target 'virtualenv' failed
make[2]: *** [virtualenv] Error 2
make[2]: Leaving directory '/home/Sim/julia/doc'
Makefile:33: recipe for target 'doc/_build/html' failed
make[1]: *** [doc/_build/html] Error 2
make[1]: Leaving directory '/home/Sim/julia'
Makefile:369: recipe for target 'dist' failed
make: *** [dist] Error 2
```
Best,
Simon

**Comment by tkelman** [comment] 2015-02-21 13:48
Python is a build-time dependency of LLVM, how have you been getting away without it?

**Comment by SimonDanisch** [comment] 2015-02-21 14:37
Good question.. I'll look into it, if I tinkered with anything... But I thought I haven't touched anything since I my last build, which was circa 1-2 weeks ago...

**Comment by tkelman** [comment] 2015-02-21 14:46
Check what `deps/llvm-3.3/build_Release/config.log` says about whether or not it found python on your system. I thought I've seen LLVM fail to build when it couldn't find python, but it might only need it to build its test suite. Not positive. Or there's a chance that whatever LLVM's configure does to find Python when we don't specify it explicitly is more sophisticated than the `deps/find_python2` script. We're building html docs into `make install` now (see PR 10253), so you'll need an installation of Python for that. Getting it from MSYS2's package manager should work. Cygwin's python has been working fine in cross-compile for me.

**Comment by SimonDanisch** [comment] 2015-02-21 18:42
Hm... I installed python2 and python 3 with pacman and now get this:
```cmd
$ make dist
rm -fr julia-*.tar.gz julia*.exe julia-*.7z julia-dcfe82f079
make[1]: Entering directory '/home/Sim/julia'
make[2]: Entering directory '/home/Sim/julia/doc'
make -C /home/Sim/julia/deps install-virtualenv
make[3]: Entering directory '/home/Sim/julia/deps'
"/usr/bin/python2" virtualenv-1.11.6/virtualenv.py julia-env
New python executable in julia-env/bin/python2
Also creating executable in julia-env/bin/python
Installing setuptools, pip...done.
Traceback (most recent call last):
  File "virtualenv-1.11.6/virtualenv.py", line 2338, in <module>
    main()
  File "virtualenv-1.11.6/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "virtualenv-1.11.6/virtualenv.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "virtualenv-1.11.6/virtualenv.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "virtualenv-1.11.6/virtualenv.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/Sim/julia/deps/julia-env/bin/python2 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code -11
Makefile:1773: recipe for target 'julia-env' failed
make[3]: *** [julia-env] Error 1
make[3]: Leaving directory '/home/Sim/julia/deps'
Makefile:23: recipe for target 'virtualenv' failed
make[2]: *** [virtualenv] Error 2
make[2]: Leaving directory '/home/Sim/julia/doc'
Makefile:33: recipe for target 'doc/_build/html' failed
make[1]: *** [doc/_build/html] Error 2
make[1]: Leaving directory '/home/Sim/julia'
Makefile:369: recipe for target 'dist' failed
make: *** [dist] Error 2
```

**Comment by SimonDanisch** [comment] 2015-02-21 19:09
```cmd
configure:12343: checking for python
configure:12361: found /python/python
configure:12378: result: /python/python
configure:12388: checking for python >= 2.5
configure:12396: result: /python/python (2.7.8)
```

**Comment by nalimilan** [comment] 2015-02-21 22:40
Looks like you're not completely alone on the Web with that error. This page has a workaround (at the bottom), maybe it gives a hint about the problem: https://www.hartmutpfarr.de/virtuelle_python_umgebungen

**Comment by SimonDanisch** [comment] 2015-02-21 23:04
Hmm... I tried to follow the instructions, but pip simply segfaults...
tried this: https://github.com/pypa/pip/issues/1695
still segfault...
Not sure if have followed everything correctly, though.
For someone who neither really knows python nor msys, the article is a little confusing;)

**Comment by nalimilan** [comment] 2015-02-22 10:14
I'm not familiar with them either... Could you recap exactly what you did and the results?

BTW, you said "I tried to build the newest master", but this error happens when calling `make dist`, not when calling `make release`, right? Just to check I didn't make a mistake in the Makefile.

If it's so hard to get right on MSys, we could as well disable the generation of HTML docs by default...

**Comment by SimonDanisch** [comment] 2015-02-22 10:24
yes, it's `make dist`... Julia compiles and passes the tests fine.

**Comment by SimonDanisch** [comment] 2015-02-22 10:27
```
pacman -S python
pacman -S python2
pacman -S setuptools
easy_install2.7 install pip
pip install virtuelenv, ...
--> segfault (also with pip --version)
```
Names might be wrong, as I can't access the article anymore
then the solution from the issue:
```
pacman -S libuuid-devel
```

**Comment by tkelman** [comment] 2015-02-22 10:51
I may have been wrong earlier when I said msys2's python might be good enough. The fact that LLVM found one at `/python/python` and that worked for it means we should probably be finding it via `deps/find_python2`. Try uninstalling the msys2 pacman python, does `which python` not return the `/python/python` result? Our instructions in README.Windows.md might be a bit wonky w.r.t. the mounting of paths for python and mingw-w64...

**Comment by SimonDanisch** [comment] 2015-02-22 11:27
```
mount: warning - /python does not exist.
mount: warning - /mingw does not exist.
...
which python
which: no python in (/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python)
```
.bashrc:
```
mount C:/Python27 /python
mount C:/mingw-builds/x64-4.8.1-win32-seh-rev5/mingw64 /mingw
export PATH=/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python
```

2015-02-22 11:52 GMT+01:00 Tony Kelman <notifications@github.com>:

**Comment by SimonDanisch** [comment] 2015-02-22 11:28
```
mount: warning - /python does not exist.
mount: warning - /mingw does not exist.
...
which python
which: no python in (/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python)
```
.bashrc:
```
mount C:/Python27 /python
mount C:/mingw-builds/x64-4.8.1-win32-seh-rev5/mingw64 /mingw
export PATH=/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/python
```

**Comment by tkelman** [comment] 2015-02-22 11:30
`ls -al /python` ?
Odd that `which` isn't finding it but LLVM's configure did...

**Comment by SimonDanisch** [comment] 2015-02-22 11:33
```cmd
$ ls -al /python
total 1132
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Dec 26 15:56 .
drwxr-xr-x  1 Sim              +Benutzer      0 Feb 21 23:57 ..
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Sep  2 03:32 DLLs
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Sep  2 03:32 Doc
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Sep  2 03:32 include
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Jan  7 00:56 Lib
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Sep  2 03:32 libs
-rwxrwx---+ 1 +SYSTEM          +SYSTEM    38578 Jun  1  2014 LICENSE.txt
-rwxrwx---+ 1 +Administratoren Sim       190929 Nov 25 20:43 matplotlib-wininst.log
-rwxrwx---+ 1 +SYSTEM          +SYSTEM   389036 Jun 30  2014 NEWS.txt
-rwxrwx---+ 1 +SYSTEM          +SYSTEM    26624 Jun 30  2014 python.exe
-rwxrwx---+ 1 +SYSTEM          +SYSTEM    27136 Jun 30  2014 pythonw.exe
-rwxrwx---+ 1 +SYSTEM          +SYSTEM    53978 Jun 30  2014 README.txt
-rwxrwx---+ 1 +Administratoren Sim       225280 Nov 25 20:43 Removematplotlib.exe
d---rwx---+ 1 Sim              Kein           0 Dec 26 15:56 Scripts
d---rwx---+ 1 Sim              Kein           0 Dec 26 15:56 share
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Sep  2 03:32 tcl
drwxrwx---+ 1 +SYSTEM          +SYSTEM        0 Jun 23  2014 Tools
-rwxrwx---+ 1 +SYSTEM          +SYSTEM    49664 Jun 30  2014 w9xpopen.exe
```

**Comment by tkelman** [comment] 2015-02-25 08:41
@SimonDanisch can you try changing the path line in your `.bashrc` to
```
export PATH=/usr/local/bin:/usr/bin:/opt/bin:/mingw/bin:/c/Python27
```
? MSYS2 appears to be doing something strange with this mount business. I personally always used `/etc/fstab` for setting the mingw paths with msys (1 or 2, and using the corresponding `mingw64_shell.bat` for msys2).

**Comment by SimonDanisch** [comment] 2015-02-27 11:36
Okay this leads to:
```cmd
$ which python
/c/Python27/python
```
And:
```cmd
$ make dist
rm -fr julia-*.tar.gz julia*.exe julia-*.7z julia-32aee08d0b
make[1]: Entering directory '/home/Sim/julia'
    CC usr/bin/stringreplace
make[2]: Entering directory '/home/Sim/julia/doc'
touch -c /home/Sim/julia/deps/julia-env/bin/activate
. /home/Sim/julia/deps/julia-env/bin/activate && pip install sphinx==1.2.3 \
              && pip install -r requirements.txt
/bin/sh: /home/Sim/julia/deps/julia-env/bin/activate: No such file or directory
Makefile:29: recipe for target '/home/Sim/julia/deps/julia-env/bin/sphinx-build' failed
make[2]: *** [/home/Sim/julia/deps/julia-env/bin/sphinx-build] Error 1
make[2]: Leaving directory '/home/Sim/julia/doc'
Makefile:33: recipe for target 'doc/_build/html' failed
make[1]: *** [doc/_build/html] Error 2
make[1]: Leaving directory '/home/Sim/julia'
Makefile:371: recipe for target 'dist' failed
make: *** [dist] Error 2
```
After some tinkering, this seems to be the problem:
```cmd
pip install sphinx==1.2.3
bash: /usr/bin/pip: /c/Python27^M: bad interpreter: Permission denied
```
which this thread seems to solve:
http://www.zhgzw.com/4037421/codep1/cant-install-via-pip-with-virtualenv
But, I don't really know where my virtual env is, and if C:\mingw-builds\msys64\usr\bin\pip is even the right one to edit... I played around with it, but couldn't really get it right.

**Comment by tkelman** [comment] 2015-02-28 10:09
That looks like a line-endings issue, you might have a partially installed pip from the previous attempts here. I just pushed something to master which may or may not help. Try
```
git pull
make -C deps distclean-virtualenv
```

**Comment by SimonDanisch** [comment] 2015-02-28 13:07
I again get this, which I probably have misinterpreted before:
```cmd
$ make dist
rm -fr julia-*.tar.gz julia*.exe julia-*.7z julia-34bb0b6fb4
make[1]: Entering directory '/home/Sim/julia'
make[2]: Entering directory '/home/Sim/julia/doc'
touch -c /home/Sim/julia/deps/julia-env/bin/activate
. /home/Sim/julia/deps/julia-env/bin/activate && pip install sphinx==1.2.3 \
              && pip install -r requirements.txt
/bin/sh: /home/Sim/julia/deps/julia-env/bin/activate: No such file or directory
Makefile:27: recipe for target '/home/Sim/julia/deps/julia-env/bin/sphinx-build' failed
make[2]: *** [/home/Sim/julia/deps/julia-env/bin/sphinx-build] Error 1
make[2]: Leaving directory '/home/Sim/julia/doc'
Makefile:33: recipe for target 'doc/_build/html' failed
make[1]: *** [doc/_build/html] Error 2
make[1]: Leaving directory '/home/Sim/julia'
Makefile:371: recipe for target 'dist' failed
make: *** [dist] Error 2
```
And indeed, there is no file activate in bin...

**Comment by tkelman** [comment] 2015-02-28 13:12
Does `/home/Sim/julia/deps/julia-env` exist? If not, you'll need to run `make -C deps install-virtualenv` which should have happened automatically but you're probably in some strange partial state right now

**Comment by SimonDanisch** [comment] 2015-02-28 13:17
It did exist, just activate (or probably more files) are missing.
install-virtualenv errors:
```cmd
$ make -C deps install-virtualenv
make: Entering directory '/home/Sim/julia/deps'
/home/Sim/julia/deps/jldownload virtualenv-1.11.6.tar.gz https://pypi.python.org/packages/source/v/virtualenv/virtualenv-1.11.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   327  100   327    0     0    362      0 --:--:-- --:--:-- --:--:--   510
100 1572k  100 1572k    0     0   321k      0  0:00:04  0:00:04 --:--:--  413k
/home/Sim/julia/deps/jlchecksum virtualenv-1.11.6.tar.gz
`which gtar 2>/dev/null || which tar 2>/dev/null` zxf virtualenv-1.11.6.tar.gz
touch -c virtualenv-1.11.6/virtualenv.py
"/c/Python27/python" virtualenv-1.11.6/virtualenv.py julia-env
New python executable in julia-env\Scripts\python.exe
Installing setuptools, pip...done.
[ -e julia-env/Scripts ] && ! [ -e julia-env/bin ] && cmd //C mklink //J julia-env\\bin julia-env\\Scripts
Makefile:1773: recipe for target 'julia-env' failed
make: *** [julia-env] Error 1
make: Leaving directory '/home/Sim/julia/deps'
```

**Comment by tkelman** [comment] 2015-02-28 13:29
Oh, `distclean-virtualenv` wasn't cleaning things as thoroughly as I thought. Try `rm -rf deps/julia-env`

**Comment by SimonDanisch** [comment] 2015-02-28 14:19
Okay this finally worked on second try... To document the error, here's what happened:
```cmd
$ make dist
rm -fr julia-*.tar.gz julia*.exe julia-*.7z julia-34bb0b6fb4
make[1]: Entering directory '/home/Sim/julia'
make[2]: Entering directory '/home/Sim/julia/doc'
touch -c /home/Sim/julia/deps/julia-env/bin/activate
. /home/Sim/julia/deps/julia-env/bin/activate && pip install sphinx==1.2.3 \
              && pip install -r requirements.txt
Downloading/unpacking sphinx==1.2.3
Downloading/unpacking Jinja2>=2.3 (from sphinx==1.2.3)
  Running setup.py (path:C:\mingw-builds\msys64\home\Sim\julia\deps\julia-env\build\Jinja2\setup.py) egg_info for package Jinja2

    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs\_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking Pygments>=1.2 (from sphinx==1.2.3)
Downloading/unpacking docutils>=0.7 (from sphinx==1.2.3)
  Running setup.py (path:C:\mingw-builds\msys64\home\Sim\julia\deps\julia-env\build\docutils\setup.py) egg_info for package docutils

    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking markupsafe (from Jinja2>=2.3->sphinx==1.2.3)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:C:\mingw-builds\msys64\home\Sim\julia\deps\julia-env\build\markupsafe\setup.py) egg_info for package markupsafe

Installing collected packages: sphinx, Jinja2, Pygments, docutils, markupsafe
  Running setup.py install for Jinja2

    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs\_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
  Running setup.py install for docutils

    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
  Running setup.py install for markupsafe

    building 'markupsafe._speedups' extension
    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Failure information, if any, is above.
    Retrying the build without the C extension now.


    ==========================================================================
    WARNING: The C extension could not be compiled, speedups are not enabled.
    Plain-Python installation succeeded.
    ==========================================================================
Successfully installed sphinx Jinja2 Pygments docutils markupsafe
Cleaning up...
Obtaining JuliaDoc from git+https://github.com/JuliaLang/JuliaDoc.git@15e0f6f97ecd08f93504b639956047968e3e6a42#egg=JuliaDoc (from -r requirements.txt (line 1))
  Cloning https://github.com/JuliaLang/JuliaDoc.git (to 15e0f6f97ecd08f93504b639956047968e3e6a42) to c:\mingw-builds\msys64\home\sim\julia\deps\julia-env\src\juliadoc
fatal: unable to access 'https://github.com/JuliaLang/JuliaDoc.git/': error setting certificate verify locations:
  CAfile: /usr/ssl/certs/ca-bundle.crt
  CApath: none
  Complete output from command C:\mingw-builds\msys64\usr\bin\git.exe clone -q https://github.com/JuliaLang/JuliaDoc.git C:\mingw-builds\msys64\home\Sim\julia\deps\julia-env\src\juliadoc:

----------------------------------------
Cleaning up...
Command C:\mingw-builds\msys64\usr\bin\git.exe clone -q https://github.com/JuliaLang/JuliaDoc.git C:\mingw-builds\msys64\home\Sim\julia\deps\julia-env\src\juliadoc failed with error code 128 in None
Storing debug log for failure in C:\mingw-builds\msys64\home\Sim\pip\pip.log
Makefile:27: recipe for target '/home/Sim/julia/deps/julia-env/bin/sphinx-build' failed
make[2]: *** [/home/Sim/julia/deps/julia-env/bin/sphinx-build] Error 1
make[2]: Leaving directory '/home/Sim/julia/doc'
Makefile:33: recipe for target 'doc/_build/html' failed
make[1]: *** [doc/_build/html] Error 2
make[1]: Leaving directory '/home/Sim/julia'
Makefile:371: recipe for target 'dist' failed
make: *** [dist] Error 2
```
Googling the github error, this was the easiest solution:
`git config --system http.sslverify false` from [stackoverflow](http://stackoverflow.com/questions/3778042/github-error-cloning-my-private-repository)
than `make dist` actually worked! :)
...buuuuut julia actually doesn't start... weird, this time, there also was only sys.ij in lib/julia in the installed julia folder...I'll see if a clean rebuild and such will solve it

**Comment by tkelman** [comment] 2015-02-28 14:24
> `git config --system http.sslverify false`

That sounds not very secure... probably fixable by updating your ca-certificates package from pacman.

**Comment by SimonDanisch** [comment] 2015-02-28 14:53
hm. So the compiled version works, but not the installed version from make dist... I copied all files from `julia/usr/lib/julia` into `julia/lib/julia`...

**Comment by SimonDanisch** [comment] 2015-02-28 14:54
okay, somehow ca-certificates wasn't installed anymore, installing it fixed it

**Comment by tkelman** [comment] 2015-02-28 14:56
> okay, somehow ca-certificates wasn't installed anymore, installing it fixed it

Good to know.

> So the compiled version works, but not the installed version from make dist

You might need to clear out `dist-extras` and rerun `make win-extras`, I made some changes there recently. Hopefully you have libxml2 and sha256sum already installed.

Just to let you know, I personally do not use MSYS2 to build Julia, and haven't for a long time. Last I checked the version of MinGW-w64 that we recommend for MSYS2 builds is not able to compile LLVM 3.5. I don't think anyone ever figured out why that is. I've moved to cross-compiling from Cygwin, and do pretty much all of my source builds that way.

**Comment by SimonDanisch** [comment] 2015-02-28 15:01
Hm, I executed `make cleanall` and also `make win-extras`... Well I might try cygwin, as I also want to compile Julia for Cxx, which doesn't work on msys2 ( though I don't know at all about the why).
So do you think the readme should be changed to treat cygwin as the preferred method?

**Comment by tkelman** [comment] 2015-02-28 15:06
Probably, it requires less fiddling with paths and it's what we're using on the buildbots, though it is explicitly cross-compiling which might be confusing for some people. I'm not sure whether Cxx will work with a Cygwin-cross-compiled Windows Julia either. Maybe the msys2 issue is just the same llvm 3.5 thing, in which case it could be worth trying.

**Comment by tkelman** [comment] 2015-02-28 15:08
I don't think `make cleanall` deletes `dist-extras`, you can just do `rm -rf dist-extras` for that.

**Comment by SimonDanisch** [comment] 2015-02-28 15:09
The answers sounded a little like this in Keno/Cxx.jl#62

**Comment by SimonDanisch** [comment] 2015-02-28 20:06
ha! cygwin worked without any problems whatsoever... took a long time to install and build, so I still don't know about cxx!

**Comment by tkelman** [comment] 2015-02-28 20:09
Including the installed version from `make dist`? I'm guessing yes since that's how the nightlies are being built and we haven't had any complaints about them. Should we close this issue, or leave it open as a "endorse the cygwin build method" doc todo?

**Comment by SimonDanisch** [comment] 2015-03-01 12:36
Well the issue isn't fixed yet, right? We just have an acceptable workaround...
And cygwin isn't the hero I have hoped for...still get the same error for Keno/Cxx.jl#62

**Comment by tkelman** [comment] 2015-03-01 19:22
Other than the Python doc-building issues with msys which are now fixed, I'm not at all clear what the remaining issue is. Cxx.jl doesn't work on Windows yet, but that's not what this issue is for. If you're trying to build Julia with a newer-than-3.3 version of LLVM on Windows then you're likely to hit problems until we officially make the switch.

If you're building with LLVM 3.3 in msys and the installed version of Julia from `make dist` doesn't work, you're going to need to provide more information about what you're seeing.

**Comment by SimonDanisch** [comment] 2015-03-01 19:37
Sorry, that was unclear from my side... Well, non cxx via `make dist` +
`msys2` just quits, like if i haven't moved the dll's. Without installing
it, the compiled version works. The cxx version doesn't work and i reported
it at the correct issue ;) just wanted to share this here!

**Comment by tkelman** [comment] 2015-03-01 19:57
Exactly which dll's are you referring to? I think I know the cause here, the msys recommended compilers aren't compatible with the ones the opensuse build service uses to make winrpm packages. We should actually try switching the recommended msys compilers to the ones from opensuse that you can install via `WinRPM.install("gcc")`, though I haven't done a full build of Julia with those.

**Comment by ihnorton** [comment] 2015-04-15 02:51
Please re-open/comment if needed.

**Closed by ihnorton** 2015-04-15 02:51 UTC
Labels: build, windows
