### ISSUE TITLE
Type inference hangs indefinitely

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLang/julia#40210] opened 2021-03-26 11:13 UTC
A user of my package [BinningAnalysis.jl](https://github.com/crstnbr/BinningAnalysis.jl) approached me yesterday with the following peace of code. 
```Julia
using BinningAnalysis
mutable struct MyStruct
    x::LogBinner{Float64,32}
end
function run!(s::MyStruct)
    push!(s.x, rand())
end
s = MyStruct(LogBinner(Float64))
run!(s)
```

His observation (which I can reproduce on both Julia 1.5 and 1.6) was that `run!(s)` takes forever / hangs indefinitely. To investigate the issue I tried `@code_warntype run!(s)` which also hung indefinitely. Just by inspection, I realised that the underlying issue is that a third type parameter has [recently](https://github.com/crstnbr/BinningAnalysis.jl/pull/65) been added to the type `LogBinner`. Just by upgrading BinningAnalysis, the type of the field `x` has subtly changed from concrete to abstract. If I adjust the field's type appropriately, everything is fast again.

Reasons for filing this issue:
1) While it is understood that using abstract types for fields is a performance gotcha, Julia shouldn't hang indefinitely here.
2) The fact, that `LogBinner{Float64,32}` is abstract is very subtle / hard to realise for the user. Perhaps we should force users to specify all type parameters?

**Comment by KristofferC** [comment] 2021-03-26 12:02
The actual subtype query that hangs:

```
using BinningAnalysis

x = Tuple{V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V, V} where V<:BinningAnalysis.AbstractVarianceAccumulator{Float64}

y = Tuple{Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}, Union{BinningAnalysis.Compressor{Float64}, V}} where V<:BinningAnalysis.AbstractVarianceAccumulator{Float64}

x <: y
```

**Comment by crstnbr** [comment] 2021-04-14 07:37
Perhaps this should get the labels "inference" and "bug"?

**Comment by vtjnash** [comment] 2022-03-29 22:10
Duplicate of https://github.com/JuliaLang/julia/issues/39967

**Comment by vtjnash** [comment] 2022-03-29 22:10
Duplicate of https://github.com/JuliaLang/julia/issues/22389

**Closed by vtjnash** 2022-03-29 22:10 UTC
Labels: bug, types and dispatch
