### ISSUE TITLE
Julia fails to clone repository

### ISSUE THREAD

**Issue by zappotek** [JuliaLang/julia#30640] opened 2019-01-08 03:11 UTC
I have just installed a new version of linux (Manjaro) and am trying to get julia up and running again. 
When using Pkg to install, I am hit with the following error:

```
Cloning default registries into /home/tharsis/.julia/registries
Cloning registry General from "https://github.com/JuliaRegistries/General.git"
ERROR: LoadError: failed to clone from https://github.com/JuliaRegistries/General.git, error: GitError(Code:ERROR, Class:SSL, SSL error: 0xffff8880 - SSL - A fatal alert message was received from our peer)
Stacktrace:
 [1] pkgerror(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:120
 [2] #clone#2(::String, ::Base.Iterators.Pairs{Symbol,LibGit2.CachedCredentials,Tuple{Symbol},NamedTuple{(:credentials,),Tuple{LibGit2.CachedCredentials}}}, ::Function, ::String, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GitTools.jl:107
 [3] #clone at ./none:0 [inlined]
 [4] (::getfield(Pkg.Types, Symbol("##51#55")))(::LibGit2.CachedCredentials) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:937
 [5] shred!(::getfield(Pkg.Types, Symbol("##51#55")), ::LibGit2.CachedCredentials) at ./secretbuffer.jl:184
 [6] #registries#50(::Bool, ::Function) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:933
 [7] registries at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:917 [inlined]
 [8] #find_registered!#59(::Bool, ::Function, ::Pkg.Types.EnvCache, ::Array{String,1}, ::Array{Base.UUID,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:999
 [9] find_registered! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:968 [inlined]
 [10] registry_resolve!(::Pkg.Types.EnvCache, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Types.jl:839
 [11] #add_or_develop#13(::Symbol, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:57
 [12] #add_or_develop at ./none:0 [inlined]
 [13] #add_or_develop#12 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:29 [inlined]
 [14] #add_or_develop at ./none:0 [inlined]
 [15] #add_or_develop#11 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:28 [inlined]
 [16] #add_or_develop at ./none:0 [inlined]
 [17] #add_or_develop#10 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:27 [inlined]
 [18] #add_or_develop at ./none:0 [inlined]
 [19] #add#18 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:69 [inlined]
 [20] add(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:69
 [21] top-level scope at /home/tharsis/.atom/packages/julia-client/script/boot_repl.jl:22
 [22] include at ./boot.jl:317 [inlined]
 [23] include_relative(::Module, ::String) at ./loading.jl:1044
 [24] include(::Module, ::String) at ./sysimg.jl:29
 [25] exec_options(::Base.JLOptions) at ./client.jl:266
 [26] _start() at ./client.jl:425
in expression starting at /home/tharsis/.atom/packages/julia-client/script/boot_repl.jl:1

Julia has exited. Press Enter to start a new session.
```
`
I got a similar problem to the first using Pkg.clone() on my previous installation - all issues I could find  were using a proxy of some kind - I am not.

I manually cloned the registries, and tried again, and was able to successfully install a few packages.
But when I try to install Atom, I am hit with the following:

```
Pkg.add("Atom")
ERROR: The following package names could not be resolved:
 * Atom (not found in project, manifest or registry)
Please specify by known 'name=uuid'.
```

I used a [workaround](https://discourse.julialang.org/t/atom-not-found-in-project-manifest-or-registry/13380) that others had used in previous versions to avoid this issue, but when I try to continue I get the first error message again.

Any help would be greatly appreciated, I have very much enjoyed learning and programming Julia, and am excited to get back to it :)

**Comment by zappotek** [comment] 2019-01-25 15:33
I was able to fix the problem  by creating the `~/.julia/environments/v1.0/` directory, and touching `Project.toml` and `Manifest.toml` within, and creating `~/.julia/registries/`.

Julia appears to be failing to create the environments directory in arch based distributions (another issue [here](https://discourse.julialang.org/t/arpack-does-not-build-in-1-0-manjaro-linux/14515)

Does anyone know where julia attempts to create these directories so I can take a look?

**Comment by fredrikekre** [comment] 2019-01-25 15:38
Duplicate of your own issue at https://github.com/JuliaLang/Pkg.jl/issues/1013?

**Closed** 2019-01-25 15:50 UTC

**Comment by fredrikekre** [comment] 2019-01-25 15:57
Eh, it was the Pkg issue that was duplicate of this. I got confused with two identical issues. Lets discuss over there though.

**Comment by StefanKarpinski** [comment] 2019-01-25 16:00
Yes, this is definitely a Pkg issue, not a Julia issue.
