### ISSUE TITLE
CI failure on test set mutated ENV and did not restore the original values

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#52516] opened 2023-12-13 16:36 UTC
Seeing a very high rate of failures of this test, since it appears that it has to fail twice (due to a CI configuration bug?) before it will be reported:
```
      From worker 2:	┌ Error: The `cmdlineargs` test set mutated ENV and did not restore the original values
      From worker 2:	│   testset_name = "cmdlineargs"
      From worker 2:	│   testset_path = "C:\\buildkite-agent\\builds\\win2k22-amdci6-0\\julialang\\julia-master\\julia-a1ef2f3325\\share\\julia\\test\\cmdlineargs"
      From worker 2:	└ @ Main C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\test\testdefs.jl:62
FileWatching                                    (13) |        started at 2023-12-12T21:13:20.293
cmdlineargs                                      (2) |         failed at 2023-12-12T21:13:20.420
Error During Test at C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\test\testdefs.jl:24
  Got exception outside of a @test
  The `cmdlineargs` test set mutated ENV and did not restore the original values
  Stacktrace:
    [1] error(s::String)
      @ Base .\error.jl:35
    [2] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\test\testdefs.jl:67 [inlined]
    [3] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\stdlib\v1.11\Test\src\Test.jl:1598 [inlined]
    [4] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\test\testdefs.jl:26 [inlined]
    [5] macro expansion
      @ .\timing.jl:513 [inlined]
    [6] runtests(name::String, path::String, isolate::Bool; seed::UInt128)
      @ Main C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\test\testdefs.jl:24
    [7] runtests
      @ Main C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\test\testdefs.jl:5 [inlined]
    [8] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{seed::UInt128})
      @ Base .\essentials.jl:957
    [9] (::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}})()
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:286
   [10] run_work_thunk(thunk::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:70
   [11] (::Distributed.var"#109#111"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-0\julialang\julia-master\julia-a1ef2f3325\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:286
```
on https://buildkite.com/julialang/julia-master/builds/31139#018c5fa6-5a37-4234-abaf-66ff425cf75c

```
Error in testset InteractiveUtils:
Error During Test at C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:24
  Got exception outside of a @test
  The `InteractiveUtils` test set mutated ENV and did not restore the original values
  Stacktrace:
    [1] error(s::String)
      @ Base .\error.jl:35
    [2] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:67 [inlined]
    [3] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Test\src\Test.jl:1598 [inlined]
    [4] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:26 [inlined]
    [5] macro expansion
      @ .\timing.jl:513 [inlined]
    [6] runtests(name::String, path::String, isolate::Bool; seed::UInt128)
      @ Main C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:24
    [7] runtests
      @ Main C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:5 [inlined]
    [8] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{seed::UInt128})
      @ Base .\essentials.jl:957
    [9] (::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}})()
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:286
   [10] run_work_thunk(thunk::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:70
   [11] (::Distributed.var"#109#111"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-2\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:286
```
```
Error in testset loading:
Error During Test at C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:24
  Got exception outside of a @test
  The `loading` test set mutated ENV and did not restore the original values
  Stacktrace:
    [1] error(s::String)
      @ Base .\error.jl:35
    [2] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:67 [inlined]
    [3] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Test\src\Test.jl:1598 [inlined]
    [4] macro expansion
      @ C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:26 [inlined]
    [5] macro expansion
      @ .\timing.jl:513 [inlined]
    [6] runtests(name::String, path::String, isolate::Bool; seed::UInt128)
      @ Main C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:24
    [7] runtests
      @ Main C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\test\testdefs.jl:5 [inlined]
    [8] invokelatest(::Any, ::Any, ::Vararg{Any}; kwargs::@Kwargs{seed::UInt128})
      @ Base .\essentials.jl:957
    [9] (::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}})()
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:286
   [10] run_work_thunk(thunk::Distributed.var"#110#112"{Distributed.CallMsg{:call_fetch}}, print_error::Bool)
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:70
   [11] (::Distributed.var"#109#111"{Distributed.CallMsg{:call_fetch}, Distributed.MsgHeader, Sockets.TCPSocket})()
      @ Distributed C:\buildkite-agent\builds\win2k22-amdci6-1\julialang\julia-master\julia-eba10ddfbb\share\julia\stdlib\v1.11\Distributed\src\process_messages.jl:286
```

on https://buildkite.com/julialang/julia-master/builds/31135#_

**Comment by giordano** [comment] 2023-12-13 16:47
Duplicate of #52513

**Closed** 2023-12-13 16:59 UTC
Labels: ci
