### ISSUE TITLE
parallel RNG

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#94] opened 2011-07-03 16:15 UTC
How should parallel RNG be addressed? Codes that do parallel RNG:

This is an MPI code that does not seem to be maintained:
http://sprng.cs.fsu.edu/

A derivative of Mersenne Twister:
http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/DC/dc.html

At the very least,when randomize() is called, it should include the processor's number along with time to select a different seed on every processor.

**Comment by wildart** [comment] 2015-07-27 22:51
I wrote [dSFMTjump](https://github.com/wildart/dSFMTjump.jl) package which works with `MersenneTwister` type.

**Comment by ViralBShah** [comment] 2015-07-28 11:03
I have been wanting to write that translation for a while. I would love to have this in Base, since it is a tiny amount of code and greatly useful in a number of situations. Could you submit a PR?

**Comment by wildart** [comment] 2015-07-28 17:34
Sure, I'd like to see this in Base as well.

**Comment by jakebolewski** [comment] 2015-08-11 21:46
Seems to be addressed by #12498.

**Comment by andreasnoack** [comment] 2015-08-11 23:22
I think it is too early to close this one. The jump function is one step, but we should have a complete setup for parallel rng in place before we close here.

**Comment by tkf** [comment] 2019-07-29 00:02
How current threading and RNG work may not be ideal in terms of reproducibility because `Random.seed!(seed)` is not enough to control all thread-local RNG states:

```julia
using Random

Random.seed!(1)

Threads.@threads for _ in 1:Threads.nthreads()
    @show Threads.threadid(), rand()
end
```

Users need to do something like the following to initialize all RNGs.

```julia
using Future

Random.seed!(1)
for i in 2:Threads.nthreads()
    Random.THREAD_RNGs[i] = Future.randjump(Random.THREAD_RNGs[i - 1], big(10)^20)
end
```

I wonder if it makes sense to invoke above code with `seed!` on `GLOBAL_RNG` by default.  It should make code using static scheduling reproducible.  On the other hand, maybe it does not make sense as Julia uses dynamic scheduling, so that most of the code would loose reproducibility when relying on thread-local state anyway?

**Comment by vtjnash** [comment] 2020-01-15 18:55
We explicitly stated that we did not want `seed!` to do that by default as it conflicts with numerous other design goals. We'd perhaps consider accepting PRs that added it as a helper function though, but no promises. Note that the original issue was about `Distributed` (e.g. processes not threads), though any helper function now should probably take both into account.

Closing as "won't fix," though there is at least, no changes planned to the default behavior.

**Closed by vtjnash** 2020-01-15 18:55 UTC
Labels: RNG, parallel
