### ISSUE TITLE
Reading serialized primitive types on a different machine fails

### ISSUE THREAD

**Issue by aplavin** [JuliaLang/julia#53544] opened 2024-03-01 12:04 UTC
First, I created this issue on InlineStrings.jl repo (https://github.com/JuliaStrings/InlineStrings.jl/issues/75), but noticed that they don't do anything specific to define (de)serialization for their types. InlineString types are defined at https://github.com/JuliaStrings/InlineStrings.jl/blob/bca08b0aca8bbe78e488cb7924f51f1aac4611b7/src/InlineStrings.jl#L57. I guess, the issue is related to them being `primitive`?..

Anyway, this appears to be a more general issue, not specific to any package.
Here is the perfectly reproducible description of the issue.

I serialized an object (with InlineStrings inside) on one machine, and wanted to read it from another computer. Sometimes it works, sometimes doesn't. The minimal non-working example I found is this:
```julia
obj = [(a = InlineString15("a"), b = InlineString("b"),)]
# computer 1:
serialize("file", obj)
# computer 2:
deserialize("file", obj)
# throws
ERROR: EOFError: read end of file
Stacktrace:
  [1] unsafe_read
    @ ./iobuffer.jl:175 [inlined]
  [2] unsafe_read(s::IOBuffer, p::Ptr{@NamedTuple{a::InlineStrings.String15, b::InlineStrings.String1}}, n::Int64)
    @ Base ./io.jl:774
  [3] read!(s::IOBuffer, a::Vector{@NamedTuple{a::InlineStrings.String15, b::InlineStrings.String1}})
    @ Base ./io.jl:792
  [4] deserialize_array(s::Serializer{IOBuffer})
    @ Serialization ~/.julia/juliaup/julia-1.10.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:1241
  [5] handle_deserialize(s::Serializer{IOBuffer}, b::Int32)
    @ Serialization ~/.julia/juliaup/julia-1.10.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:865
  [6] deserialize(s::Serializer{IOBuffer})
    @ Serialization ~/.julia/juliaup/julia-1.10.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:814
  [7] handle_deserialize(s::Serializer{IOBuffer}, b::Int32)
    @ Serialization ~/.julia/juliaup/julia-1.10.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:920
  [8] deserialize
    @ ~/.julia/juliaup/julia-1.10.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:814 [inlined]
  [9] deserialize
    @ ~/.julia/juliaup/julia-1.10.1+0.aarch64.apple.darwin14/share/julia/stdlib/v1.10/Serialization/src/Serialization.jl:801 [inlined]
```
Same package versions, same Julia version. Computer 1 is linux x64, computer 2 is macbook m2.

I have a bunch of files like this, so had to re-read them on computer 1, get rid of inlinestrings (they just happened to be there, not on purpose), and write back.
Would be nice to make serialization of such types more compatible!

<details>
<summary>If others encounter this issue, here's an easy way to convert all inlinestrings to strings</summary>

```julia
using AccessorsExtra, InlineStrings
obj = modify(String, obj, RecursiveOfType(InlineString))
```

</details>

**Comment by vtjnash** [comment] 2024-03-01 17:20
Duplicate of https://github.com/JuliaLang/julia/issues/11135

**Closed** 2024-03-02 03:04 UTC
Labels: stdlib
