### ISSUE TITLE
Intermittently broken precompile

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#13200] opened 2015-09-18 04:11 UTC
Update: Just to be clear, this issue doesn't seem to be OSX specific althought it does happen more often on OSX travis.

Original post:

This started to happen on the OSX Travis CI since a few days ago for both 0.4 and master. (Also possible that the OSX travis was just not enabled before that). [This](https://travis-ci.org/JuliaLang/GZip.jl/jobs/80945483) is a typical failed build (output attached in case someone restarted that build).

The corresponding Linux build looks fine.

```julia
INFO: Package database updated
INFO: Recompiling stale cache file /Users/travis/.julia/lib/v0.4/Requests.ji for module Requests.
WARNING: Module JSON uuid did not match cache file
ERROR: LoadError: LoadError: __precompile__(true) but require failed to create a precompiled cache file
 in require at /Users/travis/julia/lib/julia/sys.dylib
 in include at /Users/travis/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
 in include at /Users/travis/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
 in require at /Users/travis/julia/lib/julia/sys.dylib
 in process_options at /Users/travis/julia/lib/julia/sys.dylib
 in _start at /Users/travis/julia/lib/julia/sys.dylib
while loading /Users/travis/.julia/v0.4/Coverage/src/coveralls.jl, in expression starting on line 5
while loading /Users/travis/.julia/v0.4/Coverage/src/Coverage.jl, in expression starting on line 185
```

**Comment by Keno** [comment] 2015-09-18 04:50
I've seen this kind of thing several times (on OS X). Usually it's fine the next time I start julia though.

**Comment by yuyichao** [comment] 2015-09-19 01:11
Ref https://github.com/JuliaLang/julia/pull/13182#issuecomment-141582919 This might not be OSX specific (but it only happens on Travis OSX and not Travis Linux AFAICT)

**Comment by yuyichao** [comment] 2015-09-19 17:10
I've just seen this locally as well. It happend when I run `Pkg.test("Cairo")` after removing all the cache files.

**Comment by jiahao** [comment] 2015-09-19 17:13
It can be reproduced ~50% of the time running the World of Julia script.

**Comment by tkelman** [comment] 2015-09-24 04:09
This happens 100% of the time if you run `vagrant up nightlyMZ` in PackageEvaluator with 0.4.0-rc1 or newer. Badly needs fixing.

**Comment by Keno** [comment] 2015-09-26 19:58
I just saw this, not sure if it's related, but seems bad as well:
```
julia> using Plots
[Plots.jl] Default backend: pyplot

julia> using GtkInteract
ERROR: LoadError: MethodError: `module_uuid` has no method matching module_uuid(::Type{ColorTypes.Color{T,N}})
 in stale_cachefile at ./loading.jl:441
 in recompile_stale at ./loading.jl:457
 in _require_from_serialized at ./loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in stale_cachefile at ./loading.jl:439
 in recompile_stale at ./loading.jl:457
 in _require_from_serialized at ./loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
while loading /Users/kfischer/.julia/v0.5/GtkInteract/src/GtkInteract.jl, in expression starting on line 12

julia>
```

**Comment by timholy** [comment] 2015-09-26 22:56
That error means that you've got some conflict between `Colors` and `Color` somewhere on your system: something is expecting a module named `Color`, but in reality it's a type.

**Comment by tkelman** [comment] 2015-10-03 16:52
I got this to happen fairly reliably when doing `Pkg.add("GeoIP"); Pkg.test("GeoIP")` starting from a clean no-packages state on linux64

**Comment by mdcfrancis** [comment] 2016-01-13 16:51
My issue which was closed as a dupe includes a reproducible (simple) example which depends on no external packages. 

https://github.com/JuliaLang/julia/issues/14663

The problem occurs when a dependent module 'uses' a package which does not have __precompile__ set and then you use this module. This only occurs first time round with an empty lib directory.

**Comment by vtjnash** [comment] 2016-01-13 17:10
that is simply a usage error. `__precompile__(true)` is a user-annotation stating that all of the preconditions for compilation are going to be met. one of those conditions is that all modules that it uses also has that flag set. the system doesn't have a way to check many of the preconditions, but they will cause various other parts of the system to fail. documentation for this should be added to http://docs.julialang.org/en/latest/manual/modules/#module-initialization-and-precompilation if something is missing

**Comment by mdcfrancis** [comment] 2016-01-13 17:33
@vtjnash as a user error I'd expect the top level package to error on precompile, it does not and causes the crash outlined here. I'd happily see the the precompile error out if all child modules are not so annotated, but I suspect it will break current usage. Perhaps a warning ? 

The reproduction supplied boils the issue down to something which does not require a lot of moving parts, but is based on the real problem -

The manifestation of this issue in iJulia etc is due to BinDeps.jl not having precompile set and Conda.jl does (which calls import BinDeps). In isolation this causes no issue (e.g. when you call these on their own), but when you install a package through REQUIRE the 'build step' breaks (this is due to the reuse of the build child process in the package manager.) Specifically you can reproduce the problem by having LibCURL and PyCall in a parent REQUIRE file.

The reason that people see this as intermittent is that it depends on the order of the build and the set of packages specified in the build. Additionally once you have successfully precompiled  you are good to go from then on. It is only when you try and build a package with many dependencies in a clean area that this rears its head. 

I hope that helps.

**Comment by tkelman** [comment] 2016-01-13 17:44
If BinDeps is safe to precompile, we could fix that case by adding the precompile directive to it. Better checking, if possible, would be worth trying to do.

**Comment by mdcfrancis** [comment] 2016-01-13 17:53
It certainly seems safe since any users of Conda are doing this today.

**Closed** 2016-01-24 04:07 UTC
Labels: bug, precompile

**Comment by JeffBezanson** [comment] 2016-02-12 18:09
I think we should reopen this. If we don't support precompiling a module whose dependencies can't be precompiled, we should throw an error as soon as possible to prevent unpredictable breakage later.

**Comment by vtjnash** [comment] 2016-02-12 18:10
that's not really something the system can test for

**Comment by tkelman** [comment] 2016-02-12 18:40
We can't check whether dependencies have marked `__precompile__(true)` ?

**Comment by sbromberger** [comment] 2016-03-25 18:59
FWIW, I'm running into this today with `using Gadfly`. Not quite sure how to fix.

**Comment by skanskan** [comment] 2018-01-23 20:46
I've just installed VS Code and Julia v0.7 and i'm having this same problem:

C:\Users\joe\.vscode-insiders\extensions\julialang.language-julia-0.9.1\scripts\languageserver\packages\Nullables\src\nullable.jl:392
in expression starting at C:\Users\joe\.vscode-insiders\extensions\julialang.language-julia-0.9.1\scripts\languageserver\packages\Nullables\src\Nullables.jl:4
ERROR: LoadError: LoadError: Failed to precompile Nullables to C:\Users\joe\.vscode-insiders\extensions\julialang.language-julia-0.9.1\scripts\languageserver\julia_pkgdir\lib\v0.7\Nullables.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] compilecache(::String) at .\loading.jl:648
 [3] compilecache at .\loading.jl:605 [inlined]
 [4] _require(::Symbol) at .\loading.jl:440
 [5] require(::Symbol) at .\loading.jl:333
 [6] include(::Module, ::String) at .\boot.jl:292
 [7] include_relative(::Module, ::String) at .\loading.jl:521
 [8] include at .\sysimg.jl:26 [inlined]
 [9] include(::String) at C:\Users\joe\.vscode-insiders\extensions\julialang.language-julia-0.9.1\scripts\languageserver\packages\JSON\src\JSON.jl:3
 [10] top-level scope
 [11] include(::Module, ::String) at .\boot.jl:292
 [12] include_relative(::Module, ::String) at .\loading.jl:521
 [13] include(::Module, ::String) at .\sysimg.jl:26
 [14] top-level scope
 [15] eval at .\boot.jl:295 [inlined]
 [16] top-level scope at .\<missing>:2
in expression starting at C:\Users\joe\.vscode-insiders\extensions\julialang.language-julia-0.9.1\scripts\languageserver\packages\JSON\src\Parser.jl:5
in expression starting at C:\Users\joe\.vscode-insiders\extensions\julialang.language-julia-0.9.1\scripts\languageserver\packages\JSON\src\JSON.jl:10
ERROR: LoadError: Failed to precompile JSON to C:\Users\joe\.vscode-insiders\extensions\julialang.language-julia-0.9.1\scripts\languageserver\julia_pkgdir\lib\v0.7\JSON.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]

and so on
