### ISSUE TITLE
Dead code elimination does not affect inlining heuristics

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#42449] opened 2021-10-01 07:57 UTC
I found the following failure of optimization in my code. It looks like it should be easy to fix, but not being a compiler hacker, it's difficult to tell the difference between "this is easy" and "this is nearly impossible" and even "it doesn't work that way".

```
function foo(x::Integer, y::Bool=(x isa Int))
           if y
               x * "string"
           else
               x + one(x)
           end
       end
```
Then
```
julia> @code_native debuginfo=:none dump_module=false foo(0x01)
	.section	__TEXT,__text,regular,pure_instructions
	subq	$8, %rsp
	movabsq	$foo, %rax
	xorl	%esi, %esi
	callq	*%rax
	popq	%rcx
	retq
	nopw	%cs:(%rax,%rax)
```
What happens is that in the first function call, `foo(x::UInt8)`, it realizes `y` is a constant `false`. It then calls `foo(::UInt8, Const(false))`. _That_ call does not inline, due to the possible error throw when doing `x::UInt8 + "string"`. But because of the `Const(false)`, that error throw is not possible in the first place, as it's placed in a branch that can be statically known to never happen.

So to me it looks like the heuristic of whether the two-argument function should be inlined is mis-calculated, since it doesn't take the dead-code elimination of the const into account.

If it did take dead-code elimination into account, the entire function would be compiled to basically a `leal` instruction, which would be cool.

**Comment by JeffBezanson** [comment] 2021-10-04 22:25
This appears to be a regression in 1.7.

**Comment by JeffBezanson** [comment] 2021-10-05 01:02
Bisect likes 22f84e7d472ed9efaeaa1c118569f0b1feda146a for this. @Keno Was that expected to affect inlining?

**Comment by Keno** [comment] 2021-10-05 01:03
It was not. Probably an oversight somewhere.

**Comment by ianatol** [comment] 2021-10-06 23:43
Possibly related to #42317?

**Comment by aviatesk** [comment] 2021-12-17 10:41
Seems to be fixed on the latest master (I forgot which exact commit fixes this though):
```julia
julia> function foo(x::Integer, y::Bool=(x isa Int))
                  if y
                      x * "string"
                  else
                      x + one(x)
                  end
              end
foo (generic function with 2 methods)

julia> @code_typed foo(0x01)
CodeInfo(
1 ─ %1 = Base.add_int(x, 0x01)::UInt8
└──      return %1
) => UInt8

julia> @code_native foo(0x01)
	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 12, 0
	.globl	_julia_foo_676                  ## -- Begin function julia_foo_676
	.p2align	4, 0x90
_julia_foo_676:                         ## @julia_foo_676
; ┌ @ REPL[2]:1 within `foo`
	.cfi_startproc
## %bb.0:                               ## %top
                                        ## kill: def $edi killed $edi def $rdi
; │ @ REPL[2]:2 within `foo` @ REPL[2]:5
; │┌ @ int.jl:87 within `+`
	leal	1(%rdi), %eax
; │└
; │ @ REPL[2]:2 within `foo`
                                        ## kill: def $al killed $al killed $eax
	retq
	.cfi_endproc
; └
                                        ## -- End function
.subsections_via_symbols
```

**Closed by aviatesk** 2021-12-17 10:41 UTC
Labels: regression, optimizer

**Comment by aviatesk** [comment] 2021-12-17 10:42
Maybe https://github.com/JuliaLang/julia/pull/42529.
