### ISSUE TITLE
`try - finally` improperly "stores" assertion stacks and releases on future error

### ISSUE THREAD

**Issue by adienes** [JuliaLang/julia#56098] opened 2024-10-10 21:02 UTC
MWE:

```
for x in 1:10
    try
        @assert false
    finally
        continue
    end
end

xyz
```

```
ERROR: LoadError: UndefVarError: `xyz` not defined in `Main`
in expression starting at /Users/andy/test.jl:9

caused by: AssertionError: false
Stacktrace:
 [1] top-level scope
   @ ~/test.jl:3

caused by: AssertionError: false
Stacktrace:
 [1] top-level scope
   @ ~/test.jl:3

caused by: AssertionError: false
Stacktrace:
 [1] top-level scope
   @ ~/test.jl:3

caused by: AssertionError: false
Stacktrace:
 [1] top-level scope
   @ ~/test.jl:3

... x10
```

note that this does not occur if `catch` is used rather than `finally`

it looks like this is quite old, and regressed sometime between `1.1` and `1.2` (!!) but I was just checking versions on juliaup and don't have a full bisection to the exact commit.

**Comment by vtjnash** [comment] 2024-10-10 21:31
Duplicate of https://github.com/JuliaLang/julia/issues/28421

**Closed** 2024-10-10 21:42 UTC
Labels: bug, error handling, duplicate, correctness bug ⚠

**Comment by adienes** [comment] 2024-10-10 21:45
funny timing given that it looks like the other issue got necro'd just hours ago
