### ISSUE TITLE
Handling of overlong character literals

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#25645] opened 2018-01-19 23:56 UTC
After the change of `Char` representation it is possible to get overlong characters from a `String`, e.g.:
```
julia> c = String([0xc0,0xa0])[1]
'\xc0\xa0': [overlong] Unicode U+0020 (category Zs: Separator, space)
```
However, if you try to write this as a character literal you get:
```
julia> '\xc0\xa0'
' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
```
so they are converted to their not-overlong equivalents.

I know it is a corner case, but I suppose that this behavior is not intentional.
So the question is is this a behavior we want (or we want character literal to be parsed exactly as written)?

**Comment by JeffBezanson** [comment] 2018-01-20 00:12
Duplicate of #25072

**Closed** 2018-01-20 03:07 UTC
