### ISSUE TITLE
SharedArray Bus error

### ISSUE THREAD

**Issue by jltmtz** [JuliaLang/julia#15155] opened 2016-02-19 21:52 UTC
I am running a program that spawns several local processes and then gathers the results back. It works fine most of the time, but if I let it run for around a day, I eventually get this error:

```
signal (7): Bus error
setindex! at sharedarray.jl:285
jlcall_setindex!_22036 at  (unknown line)
jl_apply_generic at /ubc/cs/research/tracking-raid/julm/libraries/julia-4.0/julia-e5c6964a49/bin/../lib/julia/libjulia.so (unknown line)

(more stuff from my own code)
```

Like I said, the error is somewhat erratic in that this piece of code runs many many times and then suddenly fails.

**Comment by tkelman** [comment] 2016-02-20 01:04
Can you point us to something reproducible that we would be able to run? Without that I don't think there's enough to go on here yet.

**Comment by ViralBShah** [comment] 2016-02-21 17:57
Cc @amitmurthy

**Comment by ViralBShah** [comment] 2016-02-21 17:57
Definitely need a reproducible test case.

**Comment by JaredCrean2** [comment] 2016-02-21 22:51
I have seen the same thing running a serial code for roughly 9 hours, but I haven't been able to reproduce it with any consistency.

**Comment by skariel** [comment] 2016-02-23 08:36
I have a similar thing, I think it happens only when I use very large arrays. Using smaller ones with same code everything is OK.

**Comment by jltmtz** [comment] 2016-02-23 09:35
Sorry, I tried but I wasn't able to reproduce.

Should I close this issue or leave it open for others/future reference? Currently google returns nothing when one googles this error.

**Comment by amitmurthy** [comment] 2016-02-23 11:57
Since other folks have also reported the same issue, lets leave it open for now.

**Comment by amitmurthy** [comment] 2016-03-14 03:52
This issue appears to the be the same as https://github.com/JuliaLang/julia/issues/15415 . Closing it for now. If on 0.5 please try with calling finalizers to force an early release. If on 0.4 you will need https://github.com/JuliaLang/julia/pull/15441 merged to do the same.

Please reopen if you have a reproducible test case different from #15415

**Closed by amitmurthy** 2016-03-14 03:52 UTC
Labels: needs-more-info, parallel
