### ISSUE TITLE
Document nextind and prevind

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#46821] opened 2022-09-18 07:35 UTC
The `nextind` and `prevind` functions are exported but have docstring only for strings. However, they are also defined for arrays, tuples, and named tuples.

Since they part of a public API they should be documented I think. I do not know how to document them as I am not sure what contract they must follow (especially for out-of-bounds values and values on the border). This documentation is needed so that custom array types know how to properly implement them.

x-ref: https://github.com/JuliaData/SentinelArrays.jl/pull/75

**Comment by inkydragon** [comment] 2022-09-18 10:24
```
julia> VERSION
v"1.9.0-DEV.1132"
julia> methods(nextind)
# 10 methods for generic function "nextind" from Base:
  [1] nextind(t::Tuple, i::Integer)
     @ tuple.jl:74
  [2] nextind(::AbstractArray, i::Integer)
     @ abstractarray.jl:195
  [3] nextind(t::NamedTuple, i::Integer)
     @ namedtuple.jl:145
  [4] nextind(a::AbstractArray{<:Any, N}, i::CartesianIndex{N}) where N
     @ Base.IteratorsMD multidimensional.jl:141
  [5] nextind(s::String, i::Int64)
     @ strings\string.jl:163
  [6] nextind(s::SubString{String}, i::Int64)
     @ strings\substring.jl:108
  [7] nextind(s::AbstractString, i::Int64)
     @ strings\basic.jl:553
  [8] nextind(s::AbstractString, i::Int64, n::Int64)
     @ strings\basic.jl:555
  [9] nextind(s::AbstractString, i::Integer)
     @ strings\basic.jl:552
 [10] nextind(s::AbstractString, i::Integer, n::Integer)
     @ strings\basic.jl:551
```

- `Tuple`
https://github.com/JuliaLang/julia/blob/f794bdd98b3dd0b05b76ee160a17c73732bf941e/base/tuple.jl#L73-L74
- `NamedTuple`
https://github.com/JuliaLang/julia/blob/f794bdd98b3dd0b05b76ee160a17c73732bf941e/base/namedtuple.jl#L145-L146
- `AbstractArray`
https://github.com/JuliaLang/julia/blob/f794bdd98b3dd0b05b76ee160a17c73732bf941e/base/abstractarray.jl#L197-L198
- `AbstractArray{<:Any, N}`
https://github.com/JuliaLang/julia/blob/f794bdd98b3dd0b05b76ee160a17c73732bf941e/base/multidimensional.jl#L141-L152

I guess the definition of `nextind/prevind` is simple: to go backwards or forwards by one step, regardless of index out-of-bounds.

**Comment by Seelengrab** [comment] 2022-09-18 10:26
Duplicate of https://github.com/JuliaLang/julia/issues/42084

**Closed** 2022-09-18 12:08 UTC
Labels: doc
