### ISSUE TITLE
Unable to use 'libjulia.dll' in a C# application on Windows 8.1

### ISSUE THREAD

**Issue by StevenLiekens** [JuliaLang/julia#8931] opened 2014-11-07 14:12 UTC
The documentation gave me the impression that I can use .NET P/Invokes to run Julia scripts in a .NET environment. I tried porting the embedding.c program to C#, but I always get one or more errors.

My code:

````C#
using System.Runtime.InteropServices;

class Program
{
    [DllImport("libjulia.dll")]
    public static extern void jl_init(string julia_home_dir);

    [DllImport("libjulia.dll")]
    public static extern void jl_eval_string(string str);

    static void Main(string[] args)
    {
        jl_init(null);
        jl_eval_string("print(sqrt(2.0))");
    }
}
````

When executed, it throws an [AccessViolationException](http://msdn.microsoft.com/en-us/library/system.accessviolationexception(v=vs.110).aspx), which I believe is the .NET equivalent of a segfault.

> \>.\Program.exe
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x5a6e35f324 -- unknown function (ip: 1849029412)
> unknown function (ip: 1849029412)
> abstract_call_gf at inference.jl:622
> unknown function (ip: 1840590556)
> abstract_call at inference.jl:835
> unknown function (ip: 1840590556)
> abstract_eval_call at inference.jl:927
> abstract_eval at inference.jl:952
> unknown function (ip: 1840590556)
> abstract_interpret at inference.jl:1115
> unknown function (ip: 1840590556)
> typeinf at inference.jl:1436
>  at  (unknown line)
> unknown function (ip: 1840590556)
> typeinf_ext at inference.jl:1236
> unknown function (ip: 1840590556)
> unknown function (ip: 1840586610)
> unknown function (ip: 1840588250)
> unknown function (ip: 1840590657)
> unknown function (ip: 1840641231)
> unknown function (ip: 1840890118)
> unknown function (ip: 1840863696)
> unknown function (ip: 1840926177)
> unknown function (ip: -1234565522)
> unknown function (ip: -1235658528)
> unknown function (ip: -1104811560)
> unknown function (ip: -1104811200)
> unknown function (ip: -1104811384)
> unknown function (ip: -1104812144)
> unknown function (ip: 1)
> unknown function (ip: -879819355)
> unknown function (ip: 373044544)
> unknown function (ip: -1104811200)
> unknown function (ip: -1235658528)
> unknown function (ip: -1235658528)
> unknown function (ip: -1104812144)
> unknown function (ip: -1234565522)
> unknown function (ip: -1104812112)
> unknown function (ip: -1235658528)
> unknown function (ip: -879819355)
> unknown function (ip: -1102667552)
> unknown function (ip: 1840926111)
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x5a6e35f324 -- unknown function (ip: 1849029412)
> unknown function (ip: 1840926112)
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x5a6e35f324 -- unknown function (ip: 1849029412)
> unknown function (ip: 1840926112)
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x5a6e35f324 -- unknown function (ip: 1849029412)
> unknown function (ip: 1840926112)
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x5a6e35f324 -- unknown function (ip: 1849029412)
> unknown function (ip: 1840926112)
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x5a6e35f324 -- unknown function (ip: 1849029412)
> unknown function (ip: 1840926112)
> 
> Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
> Exception: EXCEPTION_ACCESS_VIOLATION at 0x5a6e35f324 -- unknown function (ip: 1849029412)
> unknown function (ip: 1840926112)
> 
> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Brain2.Julia.Console.Program.jl_init(String julia_home_dir)
>    at Brain2.Julia.Console.Program.Main(String[] args)

I'm using Visual Studio 2012 and .NET 4.5

Tested with v0.3.2 (Current Release) for both x86 and x64 and also with v0.4.0-dev-7a7110b-win64

> Julia Version 0.4.0-dev+1318
> Commit 7a7110b* (2014-10-27 03:52 UTC)
> Platform Info:
>   System: Windows (x86_64-w64-mingw32)
>   CPU: Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
>   WORD_SIZE: 64
>   BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
>   LAPACK: libopenblas
>   LIBM: libopenlibm
>   LLVM: libLLVM-3.3

**Comment by ihnorton** [comment] 2015-02-22 06:46
[this code](https://gist.github.com/ihnorton/0cbe2ed595d539e859c4) works fine on 0.4 with x86 windows 8.1. Note the change in calling convention attribute; before that change, I had a `PInvokeStackBalance` warning for both calls (although they worked correctly). No stack size changes were made, so not sure if this is:
- not an issue on x86
- fixed by some part of Jameson's recent work
- something else

But in any case as I can't reproduce reproduce and there has been no update, I will close. Please comment if this is still an issue and we will reopen.

**Closed by ihnorton** 2015-02-22 06:46 UTC
Labels: windows

**Comment by kp-lighthousedatalab** [comment] 2017-04-13 21:09
I am not able to initialize Julialib.dll using Julia-0.4.7 (64-Bit) from C# .net (Framework v4.6)

We explicitly require 64 bit of julia to do our work

Please let me know if anyone has a solution.

**Comment by vtjnash** [comment] 2017-04-13 21:14
The [Discourse forum](http://discourse.julialang.org) is a better place for getting help on usage questions. It'll be easier to answer your question over there, where there are better controls for message formatting and threading.

**Comment by ststeiger** [comment] 2018-06-07 12:17
This works for me:

```

namespace TelSearch
{


    class Program
    {

#if true 
        private const string SHARED_OBJECT_EXTENSION = @".dll";
        private const string JULIA_HOME = @"D:\Programme\Julia-0.6.3\";
        
        private const string JULIA_CPP_DLL = JULIA_HOME + @"bin\libstdc++-6.dll";
        private const string JULIA_LLVM_DLL = JULIA_HOME + @"bin\LLVM.dll";
        private const string JULIA_DLL = JULIA_HOME + @"bin\libjulia.dll";

#else
        private const string SHARED_OBJECT_EXTENSION = @".so";
        private const string JULIA_HOME = "/root/Downloads/julia-d55cadc350/";
        
        private const string JULIA_CPP_DLL = JULIA_HOME + "lib/julia/libstdc++.so.6";
        private const string JULIA_LLVM_DLL = JULIA_HOME + "lib/julia/libLLVM.so";
        private const string JULIA_DLL = JULIA_HOME + "lib/libjulia.so";

#endif


        delegate void jl_init_t();
        delegate void jl_eval_string_t(string message);
        delegate void jl_atexit_hook_t(int status);


        //private const string DLL = "libjulia.so";
        //private const string DLL = "/usr/lib/x86_64-linux-gnu/julia/libjulia.so";
        private const string DLL = "/root/Downloads/julia-d55cadc350/lib/libjulia.so";


        enum JL_IMAGE_SEARCH : int 
        {
            JL_IMAGE_CWD = 0,
            JL_IMAGE_JULIA_HOME = 1,
            //JL_IMAGE_LIBJULIA = 2,
        }


        // typedef enum { JL_IMAGE_CWD = 0, JL_IMAGE_JULIA_HOME = 1, //JL_IMAGE_LIBJULIA = 2, } JL_IMAGE_SEARCH;
        // JL_DLLEXPORT void julia_init(JL_IMAGE_SEARCH rel);
        [System.Runtime.InteropServices.DllImport(DLL)]
        static extern void jl_init(JL_IMAGE_SEARCH rel);

        // JL_DLLEXPORT void jl_init_with_image(const char* julia_home_dir, const char* image_relative_path);
        [System.Runtime.InteropServices.DllImport(DLL)]
        static extern void jl_init(string julia_home_dir, string image_relative_path);

        // no function with such signature in julia...
        // [System.Runtime.InteropServices.DllImport(DLL)]
        // public static extern void jl_init(string julia_home_dir);

        // JL_DLLEXPORT void jl_init(void);
        [System.Runtime.InteropServices.DllImport(DLL)]
        static extern void jl_init();

        // JL_DLLEXPORT jl_value_t *jl_eval_string(const char *str);
        [System.Runtime.InteropServices.DllImport(DLL)]
        static extern void jl_eval_string(string message);


        // JL_DLLEXPORT void jl_atexit_hook(int status);
        [System.Runtime.InteropServices.DllImport(DLL)]
        static extern void jl_atexit_hook(int status);


        public static void SetPath()
        {
            bool isPosixOs = System.Environment.OSVersion.Platform == System.PlatformID.Unix;
            // System.PlatformID.Unix = true for Linux & Mac & Unix 
            string envSeparator = isPosixOs ? ":" : ";";
            char pathSeparator = System.IO.Path.DirectorySeparatorChar;

            string[] paths = new string[]
            {
                 JULIA_HOME 
                ,System.IO.Path.Combine(JULIA_HOME, "bin") 
                ,System.IO.Path.Combine(JULIA_HOME, "lib") 
                ,System.IO.Path.Combine(JULIA_HOME, "lib", "julia") 
            };

            for (int i = 0; i < paths.Length; ++i)
            {
                if (paths[i].EndsWith(pathSeparator))
                {
                    paths[i] = paths[i].Substring(0, paths[i].Length - 1);
                } // End if (paths[i].EndsWith(System.IO.Path.DirectorySeparatorChar)) 

            } // Next i 
            
            string additional_paths = string.Join(envSeparator, paths);

            string path = System.Environment.GetEnvironmentVariable("PATH");
            if (!path.EndsWith(envSeparator))
            {
                if (!string.IsNullOrEmpty(additional_paths))
                {
                    path += envSeparator;
                    path += additional_paths;
                    System.Environment.SetEnvironmentVariable("PATH", path, System.EnvironmentVariableTarget.Process);
                    
                    if (isPosixOs)
                    {
                        //System.Environment.SetEnvironmentVariable("LD_LIBRARY_PATH", "/usr/lib/x86_64-linux-gnu/julia"); //, System.EnvironmentVariableTarget.Process);
                        System.Environment.SetEnvironmentVariable("LD_LIBRARY_PATH", additional_paths);
                    } // End if (isPosixOs) 

                } // End if (!string.IsNullOrEmpty(additional_paths)) 

            } // End if (!path.EndsWith(envSeparator))

            if (isPosixOs)
                System.Environment.SetEnvironmentVariable("LD_PRELOAD", DLL);
        } // End Sub SetPath 


        public static void Ancient()
        {
            // string home = "/usr/lib/x86_64-linux-gnu/julia";
            // string home = "/usr/lib/x86_64-linux-gnu";
            // string home = "/usr/lib";
            // System.IO.Directory.SetCurrentDirectory("/usr/bin");
            // System.IO.Directory.SetCurrentDirectory("/root/Downloads/julia-d55cadc350/bin");

            // string home = "/usr/bin";
            // string home = "/root/Downloads/julia-d55cadc350";
            // string home = "/root/Downloads/julia-d55cadc350/lib/julia";
            // string home = "/root/Downloads/julia-d55cadc350/bin";

            // jl_init(null);
            // jl_init(home);

            jl_init();
            jl_eval_string("println(sqrt(2.0))");
            jl_atexit_hook(0);
        } // End Sub Ancient 



        public static void foo()
        {
            jl_init(@"C:\Users\steven liekens.BRAIN2\AppData\Local\julia-e44b593905\bin", "");


        }


        // export LD_PRELOAD="/root/Downloads/julia-d55cadc350/lib/libjulia.so"
        // dotnet TelSearch.dll 
        static void Main(string[] args)
        {
            SetPath();
            
            // D:\Programme\Julia-0.6.3\bin\libstdc++-6.dll
            // D:\Programme\Julia-0.6.3\bin\libstdc++-6.dll

            // System.IntPtr hmoduleCPP = Platform.SharedLibrary.Load(JULIA_CPP_DLL);
            // System.IntPtr hmoduleLLVM = Platform.SharedLibrary.Load(JULIA_LLVM_DLL);
            System.IntPtr hmodule = Platform.SharedLibrary.Load(JULIA_DLL);
            
            jl_init_t init = Platform.SharedLibrary.LoadSymbol<jl_init_t>(hmodule, "jl_init");
            jl_eval_string_t eval_string = Platform.SharedLibrary.LoadSymbol<jl_eval_string_t>(hmodule, "jl_eval_string");
            jl_atexit_hook_t atexit_hook = Platform.SharedLibrary.LoadSymbol<jl_atexit_hook_t>(hmodule, "jl_atexit_hook");

            init();
            eval_string("println(sqrt(2.0))");
            atexit_hook(0);
            

            Platform.SharedLibrary.Unload(hmodule);
            // Platform.SharedLibrary.Unload(hmoduleLLVM);
            // Platform.SharedLibrary.Unload(hmoduleCPP);

            System.Console.WriteLine(System.Environment.NewLine);
            System.Console.WriteLine(" --- Press any key to continue --- ");
            System.Console.ReadKey();
        } // End Sub Main 


    } // End Class Program 
    

} // End Namespace TelSearch 

```
