### ISSUE TITLE
Partial blocking reads throw EOFError instead of blocking until read complete (e.g., reading Int from /dev/random)

### ISSUE THREAD

**Issue by hessammehr** [JuliaLang/julia#13559] opened 2015-10-12 09:09 UTC
(Look further down for what seems to be the real problem)
Using Julia 0.4.0 on Linux (Ubuntu 14.10 as well as the latest Manjaro) `rand(RandomDevice(false), 100)` almost always fails with `EOFError` after the first few numbers. `RandomDevice(true)` works flawlessly.

The following fails similarly and seems to be how `rand(RandomDevice(false), n)` gets its random data.
```julia
a = open("/dev/random")
for i in 1:100
    read(a, Int64)
end
```

```
ERROR: EOFError: read end of file
 in read at iostream.jl:170
```

**Comment by nalimilan** [comment] 2015-10-12 11:49
BTW, with latest git master, `?RandomDevice` does not mention the `unlimited::Bool` argument. How did you find out that you could use it?

**Comment by hessammehr** [comment] 2015-10-12 18:29
It's still there in master at random.jl:35. Interestingly, you can't call it as
```julia
RandomDevice(unlimited=false)
```
```
=> ERROR: MethodError: `call` has no method matching call(::Type{RandomDevice})
```
even though ` RandomDevice(false)` works as expected.
```julia
RandomDevice(unlimited=false)
```
```
=> RandomDevice(IOStream(<file /dev/random>))
```

There're definitely things about Julia constructors that I have yet to learn .

**Comment by pao** [comment] 2015-10-12 18:30
Is the expected behavior a different error?

An error is almost certainly assured: "When the entropy pool is empty, reads from /dev/random will block until additional environmental noise is gathered." (http://man7.org/linux/man-pages/man4/random.4.html)

**Comment by pao** [comment] 2015-10-12 18:31
@hessammehr, that's because specifying the name of the parameter only works when the argument is a keyword argument (after a semicolon in the formal parameter list).

**Comment by hessammehr** [comment] 2015-10-12 18:38
@pao I was expecting the function to block until all 100 random numbers were ready, which it certainly does for a while. In fact, it will pause indefinitely if you don't give it any entropy, i.e., don't touch the mouse and keyboard, no network requests, etc.) Pressing random keys on the keyboard will cause the function to fail (and sometimes not) and return a partially filled array of random numbers.

**Comment by pao** [comment] 2015-10-12 18:41
Ah, thanks, that's much clearer. Wonder if that makes this a libuv-related thing?

**Comment by hessammehr** [comment] 2015-10-12 18:46
That's what I think. It seems to come from iostream.jl:170, which is a ccall, presumably to libuv.

**Comment by hessammehr** [comment] 2015-10-12 19:57
Correction, Julia's `function read{T<:Union{UInt16, Int16, UInt32, Int32, UInt64, Int64}}(s::IOStream, ::Type{T})` calls into `src/sys.c:301`, where the error is thrown
```C
DLLEXPORT uint64_t jl_ios_get_nbyte_int(ios_t *s, const size_t n)
{
    assert(n <= 8);
    size_t ret = ios_readprep(s, n);
    if (ret < n)
        throw_eof_error();
```

`ios_readprep(s,n)` in turns calls into `support/ios.c:321`, which calls `_os_read` in the same file and ultimately the system `read` function. Now, according to the `read(2)` manual page, a return value smaller than expected doesn't necessarily mean EOF. But the code above will throw `EOFError` if anything less than n bytes is read.

**Comment by wildart** [comment] 2015-10-13 00:02
`unlimeted` flag provides distinction between `/dev/urandom` and `/dev/random`. `/dev/random` is blocking when entropy pool is exhausted, while `/dev/urandom` behaves as pseudo-random generator if there is not sufficient entropy. I guess access to both devices is non-blocking, so you see an error for `/dev/random` on empty pool. See http://man7.org/linux/man-pages/man4/random.4.html.

**Comment by pao** [comment] 2015-10-13 01:58
@wildart, I already quoted the man page.

**Comment by wildart** [comment] 2015-10-13 04:08
My bad, I guess a solution should be in different reading mode (blocking and non-blocking) for different deceives.

**Comment by hessammehr** [comment] 2015-10-13 07:12
The following works fine.
```julia
rand(RandomDevice(false),Int8, 100)
```
and so does this:
```julia
a = open("/dev/random", "r")
for i in 1:100
    read(a, Int8)
end
```
Both also work with `Int16`, `Int32`, and `Float32`, even when the function call blocks to wait for entropy.

**Comment by hessammehr** [comment] 2015-10-13 07:34
This might help understand the problem:
```C
#include <unistd.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>

int main() {
        printf("sizeof(unsigned long int) = %d\n", sizeof(unsigned long int));
        int a = open("/dev/random", O_RDONLY), cnt, ret;
        unsigned long int res;
        for (cnt=0;cnt<1000;cnt++) {
                ret = read(a, (void*) &res, sizeof(long int));
                printf("Returned: %d Read:%lu Errno:%s\n", ret, res, strerror(errno));
        }
}
```

A typical run of the above code will correctly read 8 bytes per iteration for the first few iterations:
```
sizeof(unsigned long int) = 8
Returned: 8 Read:6129408719018679362 Errno:Success
Returned: 8 Read:7851765565466219663 Errno:Success
```
then exhaust /dev/random and start returning 6 bytes per iteration indefinitely, but never less.
```
Returned: 7 Read:7790287781257302767 Errno:Success
Returned: 6 Read:7790267631181720159 Errno:Success
Returned: 6 Read:7790290698167501351 Errno:Success
Returned: 6 Read:7790370641659074752 Errno:Success
```

**Comment by pao** [comment] 2015-10-13 12:46
Is this a valid summary: If Julia performs a partial read, it produces `EOFError`, even when the underlying `read` call should block? (At least with `/dev/random`.) That seems consistent with the idea with large reads failing. I'm going to tentatively retitle and relabel based on that; let us know if I got it wrong.

**Comment by hessammehr** [comment] 2015-10-13 17:07
Thanks, here's a small revision: "If Julia performs a partial read from a blocking source (e.g. `/dev/random` or `/dev/tty`) it fails with EOFError when the number of bytes read is smaller than the datatype Julia is trying to reading."

So far I have found that `/dev/random`, when exhausted and blocking, yields data in 6-byte chunks. `/dev/tty` on the other hand, gives single bytes per read.

**Comment by hessammehr** [comment] 2015-10-13 17:08
@pao Do you think I should revise my first comment so it doesn't confuse people?

**Comment by StefanKarpinski** [comment] 2015-10-13 18:20
No, I think having the issue history intact is good. Maybe add a note indicating to look further down for the real problem.

**Comment by hessammehr** [comment] 2015-10-14 07:37
Making the following change at `sys.c:305` fixed the problem on my Linux machine.
```julia
DLLEXPORT uint64_t jl_ios_get_nbyte_int(ios_t *s, const size_t n)
{
    assert(n <= 8);
    size_t ret = ios_readprep(s, n);
    if (ret < n)
        throw_eof_error();
```
to
```julia
DLLEXPORT uint64_t jl_ios_get_nbyte_int(ios_t *s, const size_t n)
{
    assert(n <= 8);
    size_t ret = ios_readprep(s, n);
    if (ret == 0)
        throw_eof_error();
```
If `ios_readprep` is expected to follow the UNIX `read(2)` semantics, reading less than the expected number of bytes does not imply EOF. `file` tests are still passing and Julia correctly complains on actual EOFs in input.

**Comment by nalimilan** [comment] 2015-10-14 09:02
Could you make a pull request with this change? That would run the full testsuite on it. Can you also check that blocking waiting for more input is consistent with the behaviour described in the docs?

Could be good to add a test too.

**Comment by hessammehr** [comment] 2015-10-14 18:18
@nalimilan The docs are pretty sparse for `read`:

>    read(stream, type, dims)
>    Read a series of values of the given type from a stream, in canonical binary representation. dims is either a tuple or a series of integer arguments specifying the size of Array to return.

`readbytes` is a little more explicit

>    readbytes(stream, nb=typemax(Int); all=true)
>    Read at most nb bytes from the stream, returning a Vector{UInt8} of the bytes read.
>    If all is true (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If all is false, at most one read call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the all option.


```julia
readbytes(open("/dev/random","r"), 10, all=true)
```

The above has desired property of blocking until all 10 bytes have been read. Perhaps the random number generator can use `readbytes` instead of `read`, then?

**Comment by nalimilan** [comment] 2015-10-14 20:44
While it doesn't sound unreasonable to expect both `read` and `readbytes` to behave the same and block until enough bytes can be read, somebody more knowledgeable than me will have to comment.

**Comment by hessammehr** [comment] 2015-10-14 20:59
I am no expert but to me the reasonable (least surprising) thing would be for `read` to block until at least one element of the requested type has been read. That is, `read(stream, Int64, 5)` should read between 8 and 40 bytes, blocking if less than 8 bytes are available. It seems like the current behavior is to block until the stream makes any number of device-dependent bytes available to read, which might be less than 8 (6 for `/dev/random` and 1 for `/dev/tty` on my computer), hence the `EOFError`.

I think we can agree that an `EOFError` should not be thrown unless the stream is definitely terminated, i.e., closed socket, detached tty, or end of a regular file.

**Comment by JeffBezanson** [comment] 2015-10-21 14:31
Looks like a fix for this has been merged? Plz reopen if I'm missing something.

**Closed by JeffBezanson** 2015-10-21 14:31 UTC
Labels: bug, I/O
