### ISSUE TITLE
Can't initalize a function with no methods inside a macro

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#34164] opened 2019-12-20 19:23 UTC
MWE:
```julia
julia> macro foo1(s)
           quote
               function $(esc(s)) end
           end
       end
@foo1 (macro with 1 method)

julia> @foo1 f
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope at REPL[6]:1

julia> macro foo2(s)
           quote
               function $(esc(s))() end
           end
       end
@foo2 (macro with 1 method)

julia> @foo2 f
f (generic function with 1 method)
```
whereas outside a macro that syntax works fine:
```julia
julia> function foo end
foo (generic function with 0 methods)
```

**Comment by vtjnash** [comment] 2019-12-20 20:30
It's a macroexpand hygiene bug. @JeffBezanson is this probably enough?
```diff
diff --git a/src/macroexpand.scm b/src/macroexpand.scm
index cffae76a68..5a17c55a24 100644
--- a/src/macroexpand.scm
+++ b/src/macroexpand.scm
@@ -365,7 +365,7 @@
                        (cdr e))))
 
            ((= function)
-            (if (and (pair? (cadr e)) (function-def? e))
+            (if (and (pair? (cadr e)) (function-def? e) (not (null? (cddr e))))
                 ;; in (kw x 1) inside an arglist, the x isn't actually a kwarg
                 `(,(car e) ,(resolve-in-function-lhs (cadr e) env m parent-scope inarg)
                   ,(resolve-expansion-vars-with-new-env (caddr e) env m parent-scope inarg))
```

This secondary example is perhaps a bit off still (since the printing is misleading), but not any worse than before:
```
julia> @macroexpand @foo1 sin(a)
quote function sin(a) end end  # looks fine

julia> julia> Meta.show_sexpr(ans)
(:block, (:function, (:call, :sin, :a)) ) # missing (:block) argument to be valid syntax

julia> @foo1 sin()
(type-error car cons ())
unexpected error: #0 (caddr (function (call sin)))
#1 (expand-function-def-
 (function (call sin)))
ERROR: syntax: malformed expression
Stacktrace:
 [1] top-level scope at REPL[8]:1
```

**Comment by JeffBezanson** [comment] 2019-12-21 00:12
Yes, seems like just avoiding that path in this case is fine.

Ideally: when `function $(esc(s)) end` is first parsed, the decision should be made as to whether it's a method definition or a new 0-method function definition. It's arguably the latter (though quite ambiguous). So if anything other than a symbol(-ish) is interpolated in, it should be an error e.g. "invalid function name".

**Comment by laborg** [comment] 2022-02-18 13:49
Can't reproduce anymore. I guess this was fixed by https://github.com/JuliaLang/julia/pull/38402

**Closed** 2022-02-18 15:10 UTC
Labels: macros
