### ISSUE TITLE
A variety of errors arising from adding methods to Base operators

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#26438] opened 2018-03-13 05:19 UTC
```julia
Base.:+(x::Int, y::Int) = println(x, y)
# 'julia' terminated by signal SIGSEGV (Address boundary error)

Base.:+(x::Int, y::Int) = 1
# KeyError: key :normal not found in getindex(::Dict{Any,Any}, ::Symbol) at ./dict.jl:478

Base.:+(x::Int, y) = 1
# fatal: error thrown and no exception handler available:
# MethodError(f=typeof(Base.:(+))(), args=(55, 1), world=0x00000000000069e3)

Base.:+(x, y::Int) = 1
# As above, but sometimes "signal (4): Illegal instruction: 4" instead

Base.:+(x, y) = 1 # this works!
```

```
julia> versioninfo()
Julia Version 0.7.0-DEV.4564
Commit 46dcb35e1b (2018-03-12 15:00 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = subl
```

**Comment by JeffBezanson** [comment] 2018-03-13 05:38
Duplicate of #20945 and several others. If we can't add integers correctly we can't really do anything. By saying `Base.:+(x::Int, y::Int) = 1` you're saying that *all* code in Base that adds Ints should get `1` as the answer. All counters, indexing, you name it, are then broken.

**Closed by JeffBezanson** 2018-03-13 05:38 UTC
