### ISSUE TITLE
Build failure with icc

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#10463] opened 2015-03-10 05:39 UTC
icc v14.0.1

````
julia 01:38:26 {master} ~/julia-icc$ make
    CC src/task.o
task.c(332): catastrophic error: Cannot match asm operand constraint
compilation aborted for task.c (code 1)
make[1]: *** [task.o] Error 1
make: *** [julia-src-release] Error 2
````

**Comment by tkelman** [comment] 2015-03-10 06:11
duplicate of #9656

**Closed by tkelman** 2015-03-10 06:11 UTC
Labels: build
