### ISSUE TITLE
Random segmentation fault associated with usage of Plots.jl on macOS arm64

### ISSUE THREAD

**Issue by truedichotomy** [JuliaLang/julia#43866] opened 2022-01-19 20:31 UTC
I'm experiencing a rather random segmentation fault in Julia 1.7.1 running a script using Plots.jl on a macOS Apple Silicon machine. I'm not sure where to start to isolate the problem.

```
signal (11): Segmentation fault: 11
in expression starting at /Users/gong/GitHub/covid19/plot_covid19.jl:95
^ at ./math.jl:0 [inlined]
bounding_order_of_magnitude at /Users/gong/.julia/packages/PlotUtils/xekml/src/ticks.jl:11
optimize_ticks_typed at /Users/gong/.julia/packages/PlotUtils/xekml/src/ticks.jl:197
unknown function (ip: 0x1167d539b)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
#optimize_ticks#42 at /Users/gong/.julia/packages/PlotUtils/xekml/src/ticks.jl:154
optimize_ticks##kw at /Users/gong/.julia/packages/PlotUtils/xekml/src/ticks.jl:152
unknown function (ip: 0x1167d13f7)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
optimal_ticks_and_labels at /Users/gong/.julia/packages/Plots/9C6z9/src/axes.jl:170
unknown function (ip: 0x1167d0423)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
do_apply at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
get_ticks at /Users/gong/.julia/packages/Plots/9C6z9/src/axes.jl:320
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
#get_ticks#95 at /Users/gong/.julia/packages/Plots/9C6z9/src/axes.jl:241
get_ticks at /Users/gong/.julia/packages/Plots/9C6z9/src/axes.jl:224 [inlined]
tick_padding at /Users/gong/.julia/packages/Plots/9C6z9/src/backends.jl:78
_update_min_padding! at /Users/gong/.julia/packages/Plots/9C6z9/src/backends.jl:108
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
iterate at ./generator.jl:47 [inlined]
_collect at ./array.jl:744
collect_similar at ./array.jl:653 [inlined]
map at ./abstractarray.jl:2849 [inlined]
_update_min_padding! at /Users/gong/.julia/packages/Plots/9C6z9/src/layouts.jl:290
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
iterate at ./generator.jl:47 [inlined]
_collect at ./array.jl:744
collect_similar at ./array.jl:653 [inlined]
map at ./abstractarray.jl:2849 [inlined]
_update_min_padding! at /Users/gong/.julia/packages/Plots/9C6z9/src/layouts.jl:290
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
prepare_output at /Users/gong/.julia/packages/Plots/9C6z9/src/plot.jl:224
show at /Users/gong/.julia/packages/Plots/9C6z9/src/output.jl:213 [inlined]
html at /Users/gong/.julia/packages/Plots/9C6z9/src/output.jl:63
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
savefig at /Users/gong/.julia/packages/Plots/9C6z9/src/output.jl:123
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
do_call at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_interpret_toplevel_thunk at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
include_string at ./loading.jl:1196
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_include at ./loading.jl:1253
include at ./client.jl:451 [inlined]
top-level scope at ./timing.jl:220
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
include_string at ./loading.jl:1196
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_include at ./loading.jl:1253
include at ./client.jl:451
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
do_call at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_interpret_toplevel_thunk at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
eval_user_input at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
repl_backend_loop at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:244
start_repl_backend at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:229
#run_repl#47 at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:362
run_repl at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:349
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
#930 at ./client.jl:394
jfptr_YY.930_29470 at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_f__call_latest at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
#invokelatest#2 at ./essentials.jl:716 [inlined]
invokelatest at ./essentials.jl:714 [inlined]
run_main_repl at ./client.jl:379
exec_options at ./client.jl:309
_start at ./client.jl:495
jl_sysimg_fvars_base at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
true_main at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_repl_entrypoint at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
Allocations: 168653373 (Pool: 168534659; Big: 118714); GC: 95
```

```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```

**Comment by Keno** [comment] 2022-01-19 22:33
Try with #43664

**Comment by giordano** [comment] 2022-01-20 01:07
Looks like a duplicate of #43285, which was a duplicate of #41440 and #42295, all of them fixed by #43664

**Closed** 2022-01-20 01:32 UTC
Labels: apple silicon
