### ISSUE TITLE
Build: failing `Float16` `intrinsics` on `1.6.6` or `1.7.2` on `ubuntu 22.04`

### ISSUE THREAD

**Issue by t-bltg** [JuliaLang/julia#45433] opened 2022-05-23 18:39 UTC
I'm building julia `1.6.6` on `ubuntu 22.04` with `gcc 11.2.0` from source archives.
```bash
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
$ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
[...]
$ ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3) 2.35
[...]
```

I have two unrelated patches applied, https://github.com/JuliaLang/julia/pull/45419 and https://github.com/JuliaLang/julia/pull/43717 for the build to end without errors.
I'm building all dependencies with `USE_BINARYBUILDER := 0` and a `prefix` set, and standard `make -j`, `make install`.

Lots of `Float16` intrinsics tests are failing, running `$ julia -e 'Base.runtests("intrinsics")'`:
```julia
Test   (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
intrinsics  (1) |        started at 2022-05-24T14:18:57.744
intrinsics  (1) |         failed at 2022-05-24T14:19:02.184
Test Failed at [...]/share/julia/test/intrinsics.jl:128
  Expression: f() === Base.invokelatest(Core.Intrinsics.neg_float, Float16(3.3))
   Evaluated: Float16(-3.3) === Float16(-3.97e-5)
[...]
```

Here is a simple reproducer:
```julia
using InteractiveUtils, Test

main() = begin
  @test Core.Intrinsics.fptrunc(Float16, 4.4) ≈ 4.4
  @test Float16(4.4f0) ≈ 4.4
  @test Float16(4.4) ≈ 4.4
  return
end

main()
versioninfo()

@test Core.Intrinsics.fptrunc(Float16, 4.4) ≈ 4.4
@test Float16(4.4f0) ≈ 4.4
@test Float16(4.4) ≈ 4.4  # KO !!
```

And the output:
```julia
$ julia fail.jl
Julia Version 1.6.6
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, sandybridge)
Test Failed at [...]/fail.jl:15
  Expression: Float16(4.4) ≈ 4.4
   Evaluated: Float16(6.1e-6) ≈ 4.4
ERROR: LoadError: There was an error during testing
in expression starting at [...]/fail.jl:15
```

Same failures observed when building and testing `1.7.2`. This used to build fine with tests passing on `ubuntu 20.04`.

Has anyone seen that before ? Does anyone have any clue on which library or code section might be failing ?

**Comment by t-bltg** [comment] 2022-05-24 12:15
The problem seem to originate from https://github.com/JuliaLang/julia/blob/fc52b3f1a7386400e3035fe3ab4283df03e968bd/src/intrinsics.cpp#L1187.

If I un-comment https://github.com/JuliaLang/julia/blob/fc52b3f1a7386400e3035fe3ab4283df03e968bd/src/intrinsics.cpp#L1118, the test passes.

**Comment by vtjnash** [comment] 2022-05-24 14:17
Duplicate of https://github.com/JuliaLang/julia/issues/44829

**Comment by t-bltg** [comment] 2022-05-24 20:38
Thanks @vtjnash for pointing this issue. Will close when we have backported patches.

**Closed** 2022-06-29 17:22 UTC
