### ISSUE TITLE
'make test' fails for julia-1.10.4

### ISSUE THREAD

**Issue by sergstesh** [JuliaLang/julia#54771] opened 2024-06-11 23:26 UTC
This bug report is a direct continuation of https://github.com/JuliaLang/julia/issues/54234 , the HW is the same as in https://github.com/JuliaLang/julia/issues/54234 .

Output of versioninfo():

```
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd4843 (2024-06-04 10:41 UTC)
Build Info:

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) N100
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)

julia> 
```
.

Output of 'uname -a':

```
sergei@slaptop:~$ uname -a
Linux slaptop 6.5.0-0.deb12.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1~bpo12+1 (2023-11-23) x86_64 GNU/Linux
sergei@slaptop:~$ 

```
.

I downloaded Julia tarball from https://github.com/JuliaLang/julia/releases/download/v1.10.4/julia-1.10.4-full.tar.gz , unpacked it the usual way, did 'cd julia-1.10.4' and built Julia using the following command line:

`nice -n 19 make test 1>make_test.log 2>&1`

.

In the 'make_test.log' file I've noticed the following lines:

```
   1308   Expression: BLAS.axpy!(α, a, copy(b)) ≈ α * a + b
   1309    Evaluated: ComplexF64[1.9330187934128453 - 8.970730564994865im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im,    1309 -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0   1309 .8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im] ≈    1309 ComplexF64[-0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.433448   1309 8396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206   1309 773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im]
   1310 
```
.

There are other failures too.

It has to be noted that the problem was fixed in julia-1.11.0-beta1 - see https://github.com/JuliaLang/julia/issues/54234#issuecomment-2078007628 , but it's back in julia-1.10.4 . See the uploaded 'make_test.log' file for complete details.
[make_test.log](https://github.com/user-attachments/files/15795640/make_test.log)

**Comment by giordano** [comment] 2024-06-12 08:09
Duplicate of #54234

**Closed by giordano** 2024-06-12 08:09 UTC

**Comment by sergstesh** [comment] 2024-06-12 08:29
Wii there be an admission that there is a regression ?

**Comment by giordano** [comment] 2024-06-12 08:39
Regression compared to what? It's the _same_ error as Julia v1.10.2.

**Comment by sergstesh** [comment] 2024-06-12 08:48
> Regression compared to what?

In my opening statement I wrote:

> It has to be noted that the problem was fixed in julia-1.11.0-beta1 - see https://github.com/JuliaLang/julia/issues/54234#issuecomment-2078007628 , but it's back in julia-1.10.4 . See the uploaded 'make_test.log' file for complete details.
.

I.e. on the surface it looks like somebody switched back to old(er) OpenBLAS version,  and if it's the case, it's a Julia developer (not an  OpenBLAS one) who did the switching.

...

Have a look into https://github.com/user-attachments/files/15795640/make_test.log - to me it feels like there are failure of different than in julia-1.10.2 .

**Comment by giordano** [comment] 2024-06-12 09:20
In case it wasn't clear, 1.10.4 comes after 1.10.2 (and 1.10.3), and _**before**_ 1.11, so nothing was switched back, simply nothing was changed between 1.10.2 and 1.10.4.

**Comment by sergstesh** [comment] 2024-06-12 09:28
> nothing was changed between 1.10.2 and 1.10.4

and this is exactly the problem. Because the fix for one problem was known, i.e. the so called backporting should have been done, but it wasn't.

...

Have you looked into https://github.com/user-attachments/files/15795640/make_test.log file ? If I'm not mistaken, as I wrote above, there are kinds of failures in julia-1.10.4 not present in  julia-1.10.2 .

**Comment by giordano** [comment] 2024-06-12 17:20
> and this is exactly the problem.

No, it it's not.  This doesn't justify opening a new ticket for all bugfixes that haven't been backported, otherwise we'd have 10x more duplicate tickets in this repository.

> Because the fix for one problem was known, i.e. the so called backporting should have been done, but it wasn't.

The "bugfix" consists in using a newer version of OpenBLAS, but backporting binary libraries is done only under certain conditions.  Also, if you really care about using a newer version of OpenBLAS you can download from https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases the tarball for your platform and in Julia run
```julia
using LinearAlgebra.BLAS
BLAS.lbt_forward("/path/to/libopenblas64_.so"; clear=true)
```

> Have you looked into [user-attachments/files/15795640/make_test.log](https://github.com/user-attachments/files/15795640/make_test.log) file ?

As a matter of fact, I did, yes.

> If I'm not mistaken, as I wrote above, there are kinds of failures in julia-1.10.4 not present in julia-1.10.2 .

The ***only*** error I see is
```
The global RNG seed was 0x5b3303e31e5ffa7e7f2b95c8d10de0a.

Error in testset LinearAlgebra/blas:
Test Failed at /media/sergei/4c7aa17d-44cf-423c-b211-ce583883925c/home/sergei/Downloads/julia-1.10.4/usr/share/julia/stdlib/v1.10/LinearAlgebra/test/blas.jl:712
  Expression: BLAS.axpy!(α, a, copy(b)) ≈ α * a + b
   Evaluated: ComplexF64[1.9330187934128453 - 8.970730564994865im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im, -0.6963896877405945 + 0.8611170231579576im] ≈ ComplexF64[-0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im, -0.4334488396252506 - 0.12206773565732487im]

make[1]: *** [Makefile:30: default] Error 1
make: *** [Makefile:619: test] Error 2
```
which is ***exactly the same*** error as the one you reported in https://github.com/JuliaLang/julia/issues/54234#issue-2261916017.  If you see something else, you haven't shared it.
