### ISSUE TITLE
Math operations with ```Int``` does not warn overflow

### ISSUE THREAD

**Issue by felipemarkson** [JuliaLang/julia#44565] opened 2022-03-11 15:14 UTC
Hi, I guess that could be a bug, but overflows shouldn't be warned?

```bash
julia> typemax(Int) + 1
-9223372036854775808
```

```bash
julia> typemax(Int)^2
-1
```

```bash
julia> typemax(Int)*2
-2
```

Compilation: Generic Linux on x86 64-bit 
Version: Julia v1.6.5 (LTS)

**Comment by oscardssmith** [comment] 2022-03-11 15:19
dup of https://github.com/JuliaLang/julia/issues/22539

**Comment by felipemarkson** [comment] 2022-03-11 15:27
Yeah, sure, I saw that Issue. But this shouldn't be warned?
I think this silent overflow can cause huge bugs in production projects.
Not everybody knows that you need to use BigInt or could be a function that causes the overflow and the programmer is not warned.

**Comment by oscardssmith** [comment] 2022-03-11 15:37
The problem isn't warning, the problem is that warning without tanking performance. This is probably achievable for exponentiation, but definitely isn't for addition/multiplication.

**Comment by felipemarkson** [comment] 2022-03-11 15:48
I understand that, but could you please appoint me where the code could be changed to implement it?

I want to make some tests and benchmarks.

**Comment by felipemarkson** [comment] 2022-03-11 15:49
> dup of #22539

I also think this is not a duplication of that issue.

**Comment by oscardssmith** [comment] 2022-03-11 15:52
Base/int.jl:87 for addition, and 88 for multiplication. Good luck.

**Comment by KristofferC** [comment] 2022-03-11 15:53
A warning is a problem. It should either error or do nothing, but not warn.

**Comment by felipemarkson** [comment] 2022-03-11 16:08
I don't know.
In my experience with embedded systems, you can make some deep tricks with overflows to get some performance.
But I guess Julia has not the intent to support these devices.

**Comment by felipemarkson** [comment] 2022-03-11 16:10
@oscardssmith Could you re-open this issue?
So, I can make some tests and demonstrate them here.

**Comment by oscardssmith** [comment] 2022-03-11 16:15
OK. That said, be warned that erroring (or warning) is a breaking change that can't happen until 2.0, and is unlikely to be merged unless the error has no runtime cost (which it will).

**Comment by KristofferC** [comment] 2022-03-11 16:19
There is nothing really to discuss here. You can take a look at https://github.com/JuliaLang/julia/pull/21600 for erroring for pow.

**Comment by Seelengrab** [comment] 2022-03-11 16:30
The reason this issue was (originally) closed to quickly is because there already has been a tremendous amount of discussion about this, e.g. [on discourse](https://discourse.julialang.org/t/discussion-about-integer-overflow/69627). Julia [just isn't at that stage of development anymore](https://discourse.julialang.org/t/psa-julia-is-not-at-that-stage-of-development-anymore/44872), where such things are considered.

**Comment by felipemarkson** [comment] 2022-03-11 16:35
Ok, but this is a problem and must be documented somewhere.
Not for discussion, but other people can reference it and know about it.

**Comment by Seelengrab** [comment] 2022-03-11 16:37
> Okay, but this is a problem and should be documented somewhere.

This is already prominently answered, in the [FAQ of the documentation](https://docs.julialang.org/en/v1/manual/faq/#faq-integer-arithmetic).

**Comment by felipemarkson** [comment] 2022-03-11 16:59
Ok, thanks!

I'm closing this issue since this discussion was already done and is documented in the [Integers Documentation](https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#Integers) and in the [FAQ of the documentation](https://docs.julialang.org/en/v1/manual/faq/#faq-integer-arithmetic).

**Closed** 2022-03-11 17:00 UTC
