### ISSUE TITLE
Parsing change makes Julia confused about negative numbers

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#12771] opened 2015-08-23 20:24 UTC
After 56360a7ee1ebc6028ce16f352749843bee48cf76,
```
julia> -(3)^2
9
```
It's more than a little scary that this didn't get caught by tests. Picked up in https://github.com/JuliaGraphics/Colors.jl/pull/5.

**Comment by stevengj** [comment] 2015-08-23 21:06
Yes, having `-3^2 == -9` but `-(3)^2 == 9` is kinda messed up.

**Comment by JeffBezanson** [comment] 2015-08-23 23:09
If helpful, feel free to revert that and add tests.

In the meantime, we should decide which syntax is better. I think it's arguable that `<identifier>( ... )` should basically always be considered a function call. As it is, we have the sketchy corner case that `+(x,y)` is a 2-argument call to `+`, but `+(x,y)^2` is parsed as `+((x,y)^2)`. As one piece of evidence, 56360a7ee1ebc6028ce16f352749843bee48cf76 simplified the parsing code.

**Comment by timholy** [comment] 2015-08-23 23:16
This one is a no-brainer. Consider:
```jl
julia> x, y = rand(), rand()
(0.8719595038334775,0.37596565160604123)

julia> exp(-(x-y)^2)
1.2789122365613017

julia> x-y
0.4959938522274363

julia> exp(-0.4959938522274363^2)
0.7819144828020161
```
If this really has to be a "decision," we've got a really, really big problem on our hands.

**Comment by timholy** [comment] 2015-08-23 23:20
I will revert it in the meantime.

**Comment by KristofferC** [comment] 2015-08-23 23:36
What an interesting clash between mathematical notation and function evaluation. My Ph.D supervisor likes to always write `a[b+c]` for `ab + ac` to distinguish it from the value of the function `a` evaluated at `b+c`. Making parenthesis mean both function evaluation and operator precedence is actually kind of a failure of notation.

**Comment by timholy** [comment] 2015-08-23 23:46
Yes, I agree this is truly awful. Too awful to be interesting :frowning:.

**Comment by eschnett** [comment] 2015-08-23 23:48
There's also a conflict with tuple notation. Currently, `-` is not defined for tuples, but if it was, then `-(1,2)` should probably invoke the unary minus with a tuple.

Personally, I find the notation operator-as-operator is more important. Hence operator-as-function-call can have a slightly more complex syntax, such as `(-)(1,2)`. (This is incidentally similar to Haskell's notation.)

We only need to do this for unary (prefix) operators, and only for function calls. Most operators are infix or postfix and are not affected, and function definitions should also be fine.

**Comment by KristofferC** [comment] 2015-08-23 23:53
Also, I am really surprised not a single test failed with this!!!

**Comment by ScottPJones** [comment] 2015-08-23 23:56
Not me, there's still a lot that is not covered by the tests, and even when those are complete, I don't know if anybody has used any coverage tools on the C, C++, and Scheme code that also makes up Julia.

**Comment by KristofferC** [comment] 2015-08-23 23:57
No matter the coverage "holes" it is still astonishing that not a single test relied on this.

**Comment by eschnett** [comment] 2015-08-24 00:05
Most of the tests only look at the value of expressions. That leaves many holes, because e.g. operators may not be defined on tuples (and hence these are not tested), or parsing errors may have no effect on the value (e.g. when involving `+`). A set of dedicated parser tests may make it easier to get better coverage.

**Comment by timholy** [comment] 2015-08-24 00:21
Agreed with the astonishment. That's the worst part of it.

**Comment by stevengj** [comment] 2015-08-24 01:44
I agree that `-(x-y)^2 == -((x-y)^2)` is too well established to consider changing the precedence of unary `+` and `-` for cases like this.   If everyone else agrees, we should simply close this issue with a commit that adds a test.

**Comment by JeffBezanson** [comment] 2015-08-24 01:48
Yes that's probably fine. The only weird case seems to be `+((1,2))`. Maybe we can handle it using look ahead for two parens. Can anybody think of another bad case in the established parsing?

**Comment by Sisyphuss** [comment] 2015-08-24 01:54
If we allow `+((1,2))`, should we also allow `+([1,2])`, and then `+((1,2),(3,4,5))`?
@eschnett

**Comment by timholy** [comment] 2015-08-24 01:58
I added one test in #12772, but it didn't test the `x,y` case.

**Comment by JeffBezanson** [comment] 2015-08-24 01:59
Those other cases don't have the same problem.

**Comment by vtjnash** [comment] 2015-08-24 02:09
>Maybe we can handle it using look ahead for two parens. Can anybody think of another bad case in the established parsing

`-((1))^2` is another similar borderline odd case

**Comment by JeffBezanson** [comment] 2015-08-24 02:18
I don't think `-((1))^2` does anything too unintuitive. To me the issue is that it's surprising for `+((1,2))` to be a 2-argument call to `+`. Even the parsing of `+((1,2))^2` is ok compared to that.

**Comment by Sisyphuss** [comment] 2015-08-24 02:19
Em, if we are not going to define the unary operator `-` for Tuple, it will be senseless to make `+((1,2)) == (1,2)`.

**Comment by Sisyphuss** [comment] 2015-08-24 02:25
If we *are* going to define `-` for Tuple, `-((1))^2` will be something ambiguous.

**Comment by lobingera** [comment] 2015-08-24 05:08
Isn't it now time to think about formal language specification and parser generation?

I have the feeling discussing about what could be correct syntax and then *tweak* the parser to do this will end badly.

**Comment by eschnett** [comment] 2015-08-24 13:44
@Sisyphuss I doesn't matter whether Base defines these unary operators; even if not, users may still want to do so.

Also, `-((1))^2` is not ambiguous, as there are no tuples involved.

**Comment by Sisyphuss** [comment] 2015-08-24 14:01
@eschnett  consider `-((1,2)).^2`, if we are also going to define the `.^` operator for tuples.

**Comment by vtjnash** [comment] 2015-08-24 18:43
>  don't think -((1))^2 does anything too unintuitive.

not presently, but your question was whether look ahead for two parens would be a good heuristic, and that is a counter-example case where two parens don't indicate that `-` is a function call instead of parentheses

**Comment by JeffBezanson** [comment] 2015-08-26 03:03
I've reopened #12755.

**Closed by JeffBezanson** 2015-08-26 03:03 UTC
Labels: decision, parser, priority, regression
