### ISSUE TITLE
Linker script `julia.expmap.in` references symbols that may be not defined

### ISSUE THREAD

**Issue by LebedevRI** [JuliaLang/julia#50414] opened 2023-07-04 22:58 UTC
When trying to compile julia master on debian sid using this [Make.user](https://github.com/JuliaLang/julia/files/11952606/Make.user.txt),
if the linker is LLVM LLD 16, there's a bit of a warnings in the output:
```
    LINK /builddirs/julia-dev/usr/lib/libjulia-internal-debug.so.1.11.0
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'asprintf' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'localtime_r' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'add_library_mapping' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '_IO_stdin_used' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'llvmGetPassPluginInfo' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'environ' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '__progname' failed: symbol not defined
    LINK /builddirs/julia-dev/usr/lib/libjulia-internal-debug.so.1.11
    LINK /builddirs/julia-dev/usr/lib/libjulia-internal-debug.so
    LINK /builddirs/julia-dev/usr/lib/libjulia-codegen-debug.so.1.11.0
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '__stack_chk_guard' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'asprintf' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'arraylist_grow' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'small_arraylist_grow' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'small_typeof' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'rec_backtrace' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'libsupport_init' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'localtime_r' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'memhash' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'memhash32' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'memhash32_seed' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'memhash_seed' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'restore_signals' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'add_library_mapping' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'jlbacktrace' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'jlbacktracet' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '_IO_stdin_used' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '_Z24jl_coverage_data_pointerN4llvm9StringRefEi' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '_Z22jl_coverage_alloc_lineN4llvm9StringRefEi' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '_Z22jl_malloc_data_pointerN4llvm9StringRefEi' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol 'environ' failed: symbol not defined
ld: warning: version script assignment of 'JL_LIBJULIA_1.11' to symbol '__progname' failed: symbol not defined
    LINK /builddirs/julia-dev/usr/lib/libjulia-codegen-debug.so.1.11
    LINK /builddirs/julia-dev/usr/lib/libjulia-codegen-debug.so
    JULIA /builddirs/julia-dev/usr/lib/julia/corecompiler.ji
```
... and if LLVM LLD 17 is used, those warnings are errors for some reason,
which makes building impossible. This is quite unfortunate.

cc @topolarity @vtjnash

**Comment by Zentrik** [comment] 2024-07-28 23:21
Seems to be a duplicate of https://github.com/JuliaLang/julia/issues/54533.

**Closed** 2024-12-11 08:31 UTC
Labels: building
