### ISSUE TITLE
const local variable is not constant at all

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#10575] opened 2015-03-19 14:57 UTC
```
julia> function f()
       const a = 1;
       a = 2;
       return a;
       end
f (generic function with 1 method)

julia> f()
2
```

Although it is not that important for the compiler/optimizer to declare a local constant variable as it can probably figure out itself, it is still useful as a hint/constraint for the user to avoid stupid error or breakage sometimes.

IMHO, as long as local const variable is a valid syntax, it should at least give a warning if the value/binding changes (just as the global one). It might even make sense to be more restrictive and make that an error instead of a warning.

**Comment by simonster** [comment] 2015-03-19 15:06
Duplicate of #5148

**Closed by simonster** 2015-03-19 15:06 UTC
