### ISSUE TITLE
Unreachable reached error

### ISSUE THREAD

**Issue by fverdugo** [JuliaLang/julia#32322] opened 2019-06-14 15:35 UTC
Dear Julia developers,

I am experiencing a Julia internal error in my code.

Executing the code that causes the error should be easy since the package is registered and I have created a branch that exposes the error (see below). Unfortunately, the code is quite large and I have not been able to find a MWE.

The error is reproduced also in travis CI (https://travis-ci.com/gridap/Gridap.jl/jobs/208161738)

Help will be highly appreciated! Sorry if this is a known issue..

Thanks in advance!

Francesc

```
$ mkdir kk
$ cd kk
$ julia --project=.
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, sandybridge)

(kk) pkg> add Gridap#unreachable_reached
...
(kk) pkg> test Gridap
...
Unreachable reached at 0x7ff06fe5a485

signal (4): Illegal instruction
in expression starting at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/CellValuesTests/CellMapApplyTests.jl:31
test_iter_cell_map at /home/verdugo/.julia/packages/Gridap/novAZ/src/REFACTORED/CellValues/CellMaps.jl:130
unknown function (ip: 0x7ff06fe5a4fc)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1864
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:323
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:411
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:362 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:773
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff07fadb89f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:764
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:179
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:614
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:883
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:826
include at ./boot.jl:326 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29 [inlined]
include at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/CellValuesTests/runtests.jl:1
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:323
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:411
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:362 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:773
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:689
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:689
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff07fc9014f)
unknown function (ip: 0x27)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:764
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:179
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:614
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:883
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:826
include at ./boot.jl:326 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29 [inlined]
include at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/runtests.jl:1
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:323
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:411
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:362 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:773
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:689
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:689
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff06bc3ee4f)
unknown function (ip: 0x2b)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:764
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:179
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:614
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:883
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:826
include at ./boot.jl:326 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
include at ./client.jl:403
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:323
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:411
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:362 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:773
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff07f43a03f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:764
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:883
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:826
include at ./boot.jl:326 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
include at ./client.jl:403
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1864
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:323
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:411
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:362 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:773
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7ff07f347a7f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:764
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:713
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:793
eval at ./boot.jl:328
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
exec_options at ./client.jl:243
_start at ./client.jl:436
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2219
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1571 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:96
main at /buildworker/worker/package_linux64/build/ui/repl.c:217
__libc_start_main at /build/glibc-6V9RKT/glibc-2.19/csu/libc-start.c:287
_start at /opt/julia/julia-1.1.0/bin/julia (unknown line)
Allocations: 57362902 (Pool: 57354969; Big: 7933); GC: 128
ERROR: Package Gridap errored during testing

```

**Comment by JeffBezanson** [comment] 2019-06-14 19:29
Could you try master or 1.2-rc1?

**Comment by fverdugo** [comment] 2019-06-14 20:33
with 1.2-rc1.0 the issue does not appear. However, with 1.0.4. the problem is also there (see below).

There is any workaround to avoid the internal error? I would be very grateful if you can give some hint. I would like that my code runs with the LTS version.

Thanks!

```
verdugo@goya:~/Documents/kk/bar$ ~/Downloads/julia-1.0.4/bin/julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.4 (2019-05-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.0.4
Commit 38e9fb7f80 (2019-05-16 03:38 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)

(bar) pkg> add Gridap#unreachable_reached
...
(bar) pkg> test Gridap
...
Unreachable reached at 0x7f518c9dc59a

signal (4): Illegal instruction
in expression starting at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/CellValuesTests/CellMapApplyTests.jl:31
test_iter_cell_map at /home/verdugo/.julia/packages/Gridap/novAZ/src/REFACTORED/CellValues/CellMaps.jl:130
unknown function (ip: 0x7f518c9dc61c)
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1809
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:430
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:363 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:682
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:806
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f517082ea3f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:815
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:805
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:232
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:655
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:838
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:839
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1044
include at ./sysimg.jl:29 [inlined]
include at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/CellValuesTests/runtests.jl:1
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
macro expansion at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/CellValuesTests/runtests.jl:27 [inlined]
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
top-level scope at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/CellValuesTests/runtests.jl:27
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1809
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:799
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:232
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:655
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:838
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:839
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1044
include at ./sysimg.jl:29 [inlined]
include at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/runtests.jl:1
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
macro expansion at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/runtests.jl:8 [inlined]
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
macro expansion at /home/verdugo/.julia/packages/Gridap/novAZ/test/REFACTORED/runtests.jl:8 [inlined]
top-level scope at ./util.jl:156 [inlined]
top-level scope at ./none:0
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1809
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:799
jl_eval_module_expr at /buildworker/worker/package_linux64/build/src/toplevel.c:232
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:655
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:838
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:839
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1044
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
include at ./client.jl:392
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:430
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:363 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:682
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:806
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f5193bfe4ef)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:815
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:805
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:838
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:839
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1044
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
include at ./client.jl:392
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1809
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:324
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:430
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:363 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:682
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:806
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f5193ae7d9f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:815
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:805
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:754
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/builtins.c:622
eval at ./boot.jl:319
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
exec_options at ./client.jl:243
_start at ./client.jl:425
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2162
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1537 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:112
main at /buildworker/worker/package_linux64/build/ui/repl.c:233
__libc_start_main at /build/glibc-6V9RKT/glibc-2.19/csu/libc-start.c:287
_start at /home/verdugo/Downloads/julia-1.0.4/bin/julia (unknown line)
Allocations: 54125401 (Pool: 54117119; Big: 8282); GC: 121
ERROR: Package Gridap errored during testing
```

**Comment by fverdugo** [comment] 2019-06-17 16:47
@JeffBezanson regarding the internal error, I would like to know if it will be fixed in a future patch in 1.0?

I also would be very grateful if you can provide some hints abound the pattern that can lead to this internal error (e.g., is there any other issue discussing this? )

Thanks!

**Comment by JeffBezanson** [comment] 2019-06-18 23:09
I've been trying to backport a fix for this, and so far it's not looking good. The commit that fixed it seems to be 74305bf2c43546bf76843b72ff0d268a3fe16920. However, without some earlier commits (at least e4aa541ee66282aefe49ba3aa751b170b463d4f6, 6594acc254dd721aa5b42df41d9c0f708644d099) that causes breakage, and those other commits can change method sorting. So we're a bit stuck.

**Comment by JeffBezanson** [comment] 2019-06-19 01:40
I was able to work around this by removing the diagonal constraint from `test_iter_cell_value`, e.g.:
```
function test_iter_cell_value(icv::CellValue{T},a::AbstractArray) where T
```
These kinds of problems are often caused by diagonal or "triangular" (`{A, B<:T{A}}`) constraints in method or struct definitions. The trick is to look at the top of the stack trace an see if we're trying to call something like that.

Will close since this is fixed on master.

**Closed by JeffBezanson** 2019-06-19 01:40 UTC
Labels: types and dispatch

**Comment by fverdugo** [comment] 2019-06-19 07:29
@JeffBezanson Thanks for the detailed answer. The workaround I have been using in my code is to completely remove type annotations in the concerned functions, which goes in the same direction as the workaround you suggest.

Thanks again for the help!

Francesc
