### ISSUE TITLE
Allow keyword arguments in new

### ISSUE THREAD

**Issue by jhasse** [JuliaLang/julia#10370] opened 2015-03-01 17:10 UTC
I found some discussion about this in https://github.com/JuliaLang/julia/issues/10146#issuecomment-73742855, but no dedicated issue.

What I would expect this to look like:

``` julia
type Foo
    a::Int32
    b::Int32
    c::Int32

    function Foo()
        return new(c = 123) # a and b undefinied
    end
end
```

**Comment by JeffBezanson** [comment] 2020-07-24 16:39
Duplicate of #36789; will close this since the newer issue has a more detailed writeup.

**Closed by JeffBezanson** 2020-07-24 16:39 UTC
Labels: design, keyword arguments, lowering
