### ISSUE TITLE
(Gentoo) Compile error: segmentation fault

### ISSUE THREAD

**Issue by alem0lars** [JuliaLang/julia#13805] opened 2015-10-28 17:08 UTC
Relevant output:

```
g++ -m64 -shared -fPIC -L/var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia -L/var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib -L/var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib -o /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/sys0.so /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/sys0.o \
        $([ Linux = Darwin ] && echo -Wl,-undefined,dynamic_lookup || echo -Wl,--unresolved-symbols,ignore-all ) \
        $([ Linux = WINNT ] && echo -ljulia -lssp)
true -ignore /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/sys0.so

signal (11): Segmentation fault
unknown function (ip: 1815341531)
unknown function (ip: 1815341593)
unknown function (ip: 1815341546)
unknown function (ip: 1815341546)
unknown function (ip: 1815341895)
unknown function (ip: 1815343642)
unknown function (ip: 1814474728)
unknown function (ip: 1998111050)
unknown function (ip: 1998111323)
unknown function (ip: 1998128967)
unknown function (ip: 1998110708)
unknown function (ip: 1998126595)
unknown function (ip: 1983156185)
unknown function (ip: 1998110708)
unknown function (ip: 1983157641)
dlopen at /lib64/libdl.so.2 (unknown line)
jl_uv_dlopen at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/dlload.c:48
jl_load_dynamic_library_ at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/dlload.c:135
get_library at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/ccall.cpp:92
runtime_sym_lookup at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/ccall.cpp:152
emit_cglobal at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/ccall.cpp:544
emit_intrinsic at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/intrinsics.cpp:833
emit_call at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:2206
emit_expr at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:2669
emit_function at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:3797
jl_eh_restore_state at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/julia.h:1175
jl_compile at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:661
jl_get_specialization at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/gf.c:1350
emit_known_call at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:1608
emit_call at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:2206
emit_expr at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:2669
emit_assignment at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:2486
emit_function at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:3797
jl_eh_restore_state at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/julia.h:1175
jl_compile at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:661
jl_get_specialization at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/gf.c:1350
emit_known_call at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:1608
emit_call at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:2206
emit_expr at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:2669
emit_function at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:3797
jl_eh_restore_state at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/julia.h:1175
jl_compile at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/codegen.cpp:661
jl_trampoline at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/builtins.c:782
jl_apply at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/gf.c:1429
jl_apply at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/julia.h:1174
jl_init_restored_modules at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/dump.c:1124
julia_init at /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/src/init.c:969
unknown function (ip: 4199610)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 4199689)
unknown function (ip: 0)
/bin/sh: line 3: 31269 Segmentation fault      /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/bin/julia --build /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/sys -J/var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/$([ -e /var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/sys.ji ] && echo sys.ji || echo sys0.ji) -f sysimg.jl
*** This error is usually fixed by running 'make clean'. If the error persists, try 'make cleanall'. ***
Makefile:127: recipe for target '/var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/sys.o' failed
make[1]: *** [/var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0/usr/lib/julia/sys.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-lang/julia-0.3.0/work/julia-0.3.0'
Makefile:37: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by jiahao** [comment] 2015-10-28 17:11
> `*** This error is usually fixed by running 'make clean'. If the error persists, try 'make cleanall'. ***`

Have you tried doing so?

**Comment by alem0lars** [comment] 2015-10-28 17:14
Yes, same error

**Comment by jiahao** [comment] 2015-10-28 17:18
`julia-0.3.0` is a year old. Have you tried with v0.3.12 or v0.4.0? Also, what kind of system are you building on?

**Comment by alem0lars** [comment] 2015-10-28 17:18
Gentoo

**Comment by tkelman** [comment] 2015-10-28 17:30
> The last ebuild available is 0.3.0.

It's probably not safe to rely on that either if the maintainer hasn't been keeping up with upstream or confirming that it builds successfully.

Just do `git clone https://github.com/JuliaLang/julia -b release-0.3 && cd julia && make`, or use release-0.4 for the most recent release.

**Comment by omus** [comment] 2015-10-29 22:07
I can confirm that building from the source repo for `release-0.3`, `release-0.4`, and `v0.3.0` works on Gentoo.

**Comment by madjestic** [comment] 2016-02-12 23:04
make[1]: Entering directory '/var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3'
Warning: git information unavailable; versioning information limited
 cd base && /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/julia -C native --output-o /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/lib/julia/sys.o  -f -J /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/lib/julia/inference.ji sysimg.jl || { echo '*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***' && false; } 
exports.jl
essentials.jl
docs/bootstrap.jl
base.jl
reflection.jl
build_h.jl
version_git.jl
c.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
refpointer.jl
functors.jl
abstractarray.jl
subarray.jl
array.jl
hashing.jl
rounding.jl
float.jl
complex.jl
rational.jl
abstractarraymath.jl
arraymath.jl
simdloop.jl
reduce.jl
bitarray.jl
intset.jl
dict.jl
set.jl
iterator.jl
osutils.jl
char.jl
ascii.jl
iobuffer.jl
string.jl
strings/types.jl
strings/basic.jl
strings/search.jl
strings/util.jl
strings/io.jl
unicode.jl
unicode/UnicodeError.jl
unicode/types.jl
unicode/checkstring.jl
unicode/utf8.jl
unicode/utf16.jl
unicode/utf32.jl
unicode/utf8proc.jl
parse.jl
shell.jl
regex.jl
pcre.jl
base64.jl
io.jl
iostream.jl
libc.jl
libdl.jl
env.jl
path.jl
intfuncs.jl
nullable.jl
task.jl
lock.jl
show.jl
stream.jl
uv_constants.jl
socket.jl
stat.jl
fs.jl
process.jl
multimedia.jl
grisu.jl
file.jl
methodshow.jl
floatfuncs.jl
math.jl
float16.jl
cartesian.jl
multidimensional.jl
primes.jl
reducedim.jl
ordering.jl
collections.jl
sort.jl
version.jl
gmp.jl
mpfr.jl
combinatorics.jl
hashing2.jl
dSFMT.jl
random.jl
printf.jl
meta.jl
Enums.jl
serialize.jl
channels.jl
multi.jl
managers.jl
loading.jl
poll.jl
mmap.jl
sharedarray.jl
datafmt.jl
deepcopy.jl
interactiveutil.jl
replutil.jl
test.jl
i18n.jl
Terminals.jl
LineEdit.jl
REPLCompletions.jl
REPL.jl
client.jl
util.jl

signal (11): Segmentation fault
unknown function (ip: 0x7f1e7e265fbb)
unknown function (ip: 0x7f1e7e265fca)
unknown function (ip: 0x7f1e7e265fca)
unknown function (ip: 0x7f1e7e266127)
unknown function (ip: 0x7f1e7e2667fa)
unknown function (ip: 0x7f1e7e192fe8)
unknown function (ip: 0x7f2084b7f13a)
unknown function (ip: 0x7f2084b7f24b)
unknown function (ip: 0x7f2084b836e7)
unknown function (ip: 0x7f2084b7efe4)
unknown function (ip: 0x7f2084b82da3)
unknown function (ip: 0x7f2082f0cfd9)
unknown function (ip: 0x7f2084b7efe4)
unknown function (ip: 0x7f2082f0d589)
dlopen at /lib64/libdl.so.2 (unknown line)
jl_uv_dlopen at /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f208382d361)
unknown function (ip: 0x7f2083800c6d)
unknown function (ip: 0x7f2083801c7b)
unknown function (ip: 0x7f2083816bad)
unknown function (ip: 0x7f208380e371)
unknown function (ip: 0x7f20838149f2)
unknown function (ip: 0x7f20838198a3)
unknown function (ip: 0x7f208381be79)
unknown function (ip: 0x7f208381c07c)
unknown function (ip: 0x7f20837de2ef)
jl_trampoline at /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/../lib/libjulia.so (unknown line)
jl_apply_generic at /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f208382a333)
unknown function (ip: 0x7f20838296e1)
unknown function (ip: 0x7f208382a319)
unknown function (ip: 0x7f20838296e1)
unknown function (ip: 0x7f208382a5f7)
unknown function (ip: 0x7f208382a8a7)
unknown function (ip: 0x7f208383bccf)
unknown function (ip: 0x7f208383c4b5)
jl_load at /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f1e8022604c)
jl_apply_generic at /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x7f1e7f61e102)
unknown function (ip: 0x7f208382a333)
unknown function (ip: 0x7f20838296e1)
unknown function (ip: 0x7f208383b985)
unknown function (ip: 0x7f208383bfbc)
unknown function (ip: 0x7f208383bc65)
unknown function (ip: 0x7f208383c4b5)
jl_load at /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/../lib/libjulia.so (unknown line)
unknown function (ip: 0x401964)
unknown function (ip: 0x401d33)
unknown function (ip: 0x40174f)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x401799)
unknown function (ip: (nil))
/bin/sh: line 1: 18593 Segmentation fault      /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/bin/julia -C native --output-o /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/lib/julia/sys.o -f -J /var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/lib/julia/inference.ji sysimg.jl
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
Makefile:200: recipe for target '/var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/lib/julia/sys.o' failed
make[1]: *** [/var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3/usr/lib/julia/sys.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/dev-lang/julia-0.4.3/work/julia-0.4.3'
Makefile:69: recipe for target 'julia-sysimg-release' failed
make: *** [julia-sysimg-release] Error 2
 * ERROR: dev-lang/julia-0.4.3::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=dev-lang/julia-0.4.3::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/julia-0.4.3::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-lang/julia-0.4.3nu madjestic # locate julia

**Comment by tkelman** [comment] 2016-02-13 01:51
Can you specify exactly which libraries you're building against and what make flags you are setting? This is probably a failure to load blas or something similar.

**Comment by nalimilan** [comment] 2016-02-13 10:47
What LLVM version are you using? What's the full `make` call?

**Comment by madjestic** [comment] 2016-02-14 00:10
The make.conf:

`# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
CFLAGS="-march=native -O2 -pipe"
CXXFLAGS="${CFLAGS}"
# WARNING: Changing your CHOST is not something that should be done lightly.
# Please consult http://www.gentoo.org/doc/en/change-chost.xml before changing.
CHOST="x86_64-pc-linux-gnu"
# These are the USE flags that were used in addition to what is provided by the
# profile used for building.
# kdepim is required by calligra office
USE="-java -sddm -systemd uvm emacs vdpau profile mmx sse sse2 icu unicode ipv6 alsa acpi git X png jpg tga theora vorbis ogg mpeg mjpeg quicktime ffmpeg lame x264 xvid win32codecs mp3 aac schroedinger template_haskell savedconfig consolekit networkmanager nvidia kdepim"

# ABI_X86="64 32"

LINGUAS="en"

INPUT_DEVICES="evdev keyboard mouse synaptics wacom joystick"

GENTOO_MIRRORS="rsync://mirror.leaseweb.com/gentoo/ http://mirror.leaseweb.com/gentoo/ ftp://mirror.leaseweb.com/gentoo/ ftp://gentoo.tiscali.nl/pub/mirror/gentoo/ http://gentoo.tiscali.nl/ ftp://ftp.snt.utwente.nl/pub/os/linux/gentoo http://ftp.snt.utwente.nl/pub/os/linux/gentoo rsync://ftp.snt.utwente.nl/gentoo"

# SYNC="rsync://rsync2.nl.gentoo.org/gentoo-portage"

# Keep some CPU cores always available
MAKEOPTS="-j5"

PORTDIR="/usr/portage"
source /var/lib/layman/make.conf

VIDEO_CARDS="nvidia intel"

CALLIGRA_FEATURES="krita words plan stage karbon"`

The LLVM version is 3.5.0

Does it answer the 
> What's the full make call?
?

**Comment by tkelman** [comment] 2016-02-14 03:04
No, not really. Can you link to what "emergr from the main portage tree" means as far as dependency library versions and which `USE_SYSTEM_` flags are being used?

LLVM 3.5 is not supported. Julia 0.4 needs to use LLVM 3.3, and master needs to use 3.7. Anything else and you're going to have performance issues or crashes.

**Comment by madjestic** [comment] 2016-02-14 15:58
I am using this ebuild to build julia, it's a part of the standard gentoo repository (aka main portage tree):
[https://packages.gentoo.org/packages/dev-lang/julia](url=https://packages.gentoo.org/packages/dev-lang/julia)

Here's the contents of the build script from the link (as a copy on my hard-drive):
```
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=5

RESTRICT="test"

inherit elisp-common eutils multilib pax-utils toolchain-funcs

DESCRIPTION="High-performance programming language for technical computing"
HOMEPAGE="http://julialang.org/"
SRC_URI="
	https://github.com/JuliaLang/${PN}/releases/download/v${PV}/${P}.tar.gz
	https://dev.gentoo.org/~tamiko/distfiles/${P}-bundled.tar.gz
"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86 ~amd64-linux ~x86-linux"
IUSE="emacs"

RDEPEND="
	dev-lang/R:0=
	dev-libs/double-conversion:0=
	dev-libs/gmp:0=
	dev-libs/libgit2:0=
	dev-libs/mpfr:0=
	dev-libs/openspecfun
	sci-libs/arpack:0=
	sci-libs/camd:0=
	sci-libs/cholmod:0=
	sci-libs/fftw:3.0=
	sci-libs/openlibm:0=
	sci-libs/spqr:0=
	sci-libs/umfpack:0=
	sci-mathematics/glpk:0=
	>=sys-devel/llvm-3.5:0=
	>=sys-libs/libunwind-1.1:7=
	sys-libs/readline:0=
	sys-libs/zlib:0=
	virtual/blas
	virtual/lapack
	emacs? ( app-emacs/ess )"

DEPEND="${RDEPEND}
	dev-util/patchelf
	virtual/pkgconfig"

PATCHES=(
	"${FILESDIR}"/${P}-fix_build_system.patch
)

src_prepare() {
	mv "${WORKDIR}"/bundled/dsfmt-2.2.3.tar.gz deps/ || die
	mv "${WORKDIR}"/bundled/libuv-efb40768b7c7bd9f173a7868f74b92b1c5a61a0e.tar.gz deps/ || die
	mv "${WORKDIR}"/bundled/pcre2-10.20.tar.bz2 deps/ || die
	mv "${WORKDIR}"/bundled/Rmath-julia-0.1.tar.gz deps/ || die
	mv "${WORKDIR}"/bundled/utf8proc-85789180158ac7fff85b9f008828d6ac44f072ea.tar.gz deps/ || die
	rmdir "${WORKDIR}"/bundled || die

	epatch "${PATCHES[@]}"

	# Sledgehammer:
	# - prevent fetching of bundled stuff in compile and install phase
	# - respect CFLAGS
	# - respect EPREFIX and Gentoo specific paths
	# - fix BLAS and LAPACK link interface

	sed -i \
		-e 's|$(JLDOWNLOAD)|${EPREFIX}/bin/true|' \
		-e 's|git submodule|${EPREFIX}/bin/true|g' \
		-e "s|GENTOOCFLAGS|${CFLAGS}|g" \
		-e "s|/usr/include|${EPREFIX%/}/usr/include|g" \
		deps/Makefile || die

	local libblas="$($(tc-getPKG_CONFIG) --libs-only-l blas)"
	libblas="${libblas%% *}"
	libblas="lib${libblas#-l}"
	local liblapack="$($(tc-getPKG_CONFIG) --libs-only-l lapack)"
	liblapack="${liblapack%% *}"
	liblapack="lib${liblapack#-l}"

	sed -i \
		-e "s|\(JULIA_EXECUTABLE = \)\(\$(JULIAHOME)/julia\)|\1 LD_LIBRARY_PATH=\$(BUILD)/$(get_libdir) \2|" \
		-e "s|GENTOOCFLAGS|${CFLAGS}|g" \
		-e "s|LIBDIR = lib|LIBDIR = $(get_libdir)|" \
		-e "s|/usr/lib|${EPREFIX}/usr/$(get_libdir)|" \
		-e "s|/usr/include|${EPREFIX}/usr/include|" \
		-e "s|\$(BUILD)/lib|\$(BUILD)/$(get_libdir)|" \
		-e "s|^JULIA_COMMIT = .*|JULIA_COMMIT = v${PV}|" \
		-e "s|-lblas|$($(tc-getPKG_CONFIG) --libs blas)|" \
		-e "s|= libblas|= ${libblas}|" \
		-e "s|-llapack|$($(tc-getPKG_CONFIG) --libs lapack)|" \
		-e "s|= liblapack|= ${liblapack}|" \
		Make.inc || die

	sed -i \
		-e "s|,lib)|,$(get_libdir))|g" \
		-e "s|\$(BUILD)/lib|\$(BUILD)/$(get_libdir)|g" \
		Makefile || die

	sed -i \
		-e "s|ar -rcs|$(tc-getAR) -rcs|g" \
		src/Makefile || die
}

src_configure() {
	# julia does not play well with the system versions of
	# dsfmt, libuv, pcre2 and utf8proc
	cat <<-EOF > Make.user
		USE_SYSTEM_DSFMT=0
		USE_SYSTEM_LIBUV=0
		USE_SYSTEM_PCRE=0
		USE_SYSTEM_RMATH=0
		USE_SYSTEM_UTF8PROC=0
		USE_LLVM_SHLIB=1
		USE_SYSTEM_ARPACK=1
		USE_SYSTEM_BLAS=1
		USE_SYSTEM_FFTW=1
		USE_SYSTEM_GMP=1
		USE_SYSTEM_GRISU=1
		USE_SYSTEM_LAPACK=1
		USE_SYSTEM_LIBGIT2=1
		USE_SYSTEM_LIBM=1
		USE_SYSTEM_LIBUNWIND=1
		USE_SYSTEM_LLVM=1
		USE_SYSTEM_MPFR=1
		USE_SYSTEM_OPENLIBM=1
		USE_SYSTEM_OPENSPECFUN=1
		USE_SYSTEM_PATCHELF=1
		USE_SYSTEM_READLINE=1
		USE_SYSTEM_SUITESPARSE=1
		USE_SYSTEM_ZLIB=1
		VERBOSE=1
	EOF

}

src_compile() {
	emake cleanall
	emake julia-release \
		prefix="/usr" DESTDIR="${D}" CC="$(tc-getCC)" CXX="$(tc-getCXX)"
	pax-mark m $(file usr/bin/julia-* | awk -F : '/ELF/ {print $1}')
	emake
	use emacs && elisp-compile contrib/julia-mode.el
}

src_test() {
	emake test
}

src_install() {
	emake install \
		prefix="/usr" DESTDIR="${D}" CC="$(tc-getCC)" CXX="$(tc-getCXX)"
	cat > 99julia <<-EOF
		LDPATH=${EROOT%/}/usr/$(get_libdir)/julia
	EOF
	doenvd 99julia

	if use emacs; then
		elisp-install "${PN}" contrib/julia-mode.el
		elisp-site-file-install "${FILESDIR}"/63julia-gentoo.el
	fi
	dodoc README.md

	mv "${ED}"/usr/etc/julia "${ED}"/etc || die
	rmdir "${ED}"/usr/etc || die
	rmdir "${ED}"/usr/libexec || die
	mv "${ED}"/usr/share/doc/julia/{examples,html} \
		"${ED}"/usr/share/doc/${P} || die
	rmdir "${ED}"/usr/share/doc/julia || die
	if [[ $(get_libdir) != lib ]]; then
		mkdir -p "${ED}"/usr/$(get_libdir) || die
		mv "${ED}"/usr/lib/julia "${ED}"/usr/$(get_libdir)/julia || die
	fi
}

pkg_postinst() {
	use emacs && elisp-site-regen
}

pkg_postrm() {
	use emacs && elisp-site-regen
}
```

I am not sure what do you mean by "USE_SYSTEM_"
The system use flags that are used to build the julia package are the following:

`USE="-java -sddm -systemd uvm emacs vdpau profile mmx sse sse2 icu unicode ipv6 alsa acpi git X png jpg tga theora vorbis ogg mpeg mjpeg quicktime ffmpeg lame x264 xvid win32codecs mp3 aac schroedinger template_haskell savedconfig consolekit networkmanager nvidia kdepim"`

of which only 'emacs' use flag seems to apply to building julia package.

**Comment by madjestic** [comment] 2016-02-14 16:03
Reading a bit further, there seems to be a bug open for this: [https://bugs.gentoo.org/show_bug.cgi?id=572546](https://bugs.gentoo.org/show_bug.cgi?id=572546)

So, you should probably ignore this.

**Comment by yuyichao** [comment] 2016-03-30 23:39
The original issue is for 0.3.0, the second issue reported here is downstream.

**Closed by yuyichao** 2016-03-30 23:39 UTC
Labels: build, linux
