### ISSUE TITLE
Document that `@testset` introduces a local scope

### ISSUE THREAD

**Issue by georgematheos** [JuliaLang/julia#35287] opened 2020-03-28 15:58 UTC
`@testset` internally creates a try/catch block to run the tests in, so the tests are run in a local scope.  However, since the syntax is `@testset "..." begin ... end`, it is natural to assume the code is run in a `begin` block, which is globally scoped.

This can lead to confusing behavior where functions defined within a testset capture variables defined outside the function, since we are in a local scope, but users may not realize this.  I suggest we at least document this local scoping behavior of `@testset`, or perhaps change the syntax to `@testset "..." let ... end` to make it more apparent that this introduces a local scope.

**Comment by vtjnash** [comment] 2020-03-28 19:32
Duplicate of #23081

**Comment by StefanKarpinski** [comment] 2020-03-28 21:13
They are related but not the same.

**Closed** 2020-06-16 15:58 UTC
Labels: doc, help wanted
