### ISSUE TITLE
RIP-relative addressing for global constants

### ISSUE THREAD

**Issue by RauliRuohonen** [JuliaLang/julia#24898] opened 2017-12-03 12:48 UTC
This is purely a performance issue, and likely a minor one, but it's one more thing where Julia could be on par with C eventually.

The code

```julia
const F = Ref(0)

foo() = F[]

code_native(foo, ())
```

on Julia master produces the x86-64 assembly

```assembly
        movabsq $4663592512, %rax       ## imm = 0x115F8C640
        movq    (%rax), %rax
        retq
```

This is pretty good — just three instructions, not much left to take away! However, GCC does better on the equivalent

```C++
struct Foo {
    long x;
};

Foo F = {0};

extern "C" long foo() {
    return F.x;
}
```

yielding

```assembly
        movq    _F(%rip), %rax
        ret
```

Ideally, Julia would produce RIP-relative addressing like GCC and Clang do. This is similar to #9894, but for global constants instead of C functions.

Since Julia is more dynamic than C, I wouldn't be suprised if data and code were generally stored too far away from each other for RIP addressing to be possible (the offset must fit in Int32, and dynamic memory can be all over the place). That may mean that this is not purely a codegen issue, but also a memory layout issue.

Still, it should be feasible to ensure that "C-like globals" are allocated close enough to code, and so enable RIP addressing for them. It'd probably suffice to recognize

```julia
const some_global = MutableStructOrBitstypeConstructor() # possibly exposed by inlining
```

after inlining and to place it in "the code segment". Mutable structs are the only non-bitstype types with fixed location (from compiler's perspective), so these should be all. In contrast, standard arrays can change location when resized, so RIP addressing won't work, as the code would become invalid. Static arrays would work though, and that is also what C provides.

versioninfo():

```
Julia Version 0.7.0-DEV.2720
Commit dba7e57d8f (2017-12-01 07:19 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
Environment:
```

**Comment by yuyichao** [comment] 2017-12-03 15:50
This isn't really fixable.

**Comment by Keno** [comment] 2017-12-03 16:05
Note that if you statically compile julia, you get the same code as C, because we have guarantees on data placement.

**Comment by yuyichao** [comment] 2017-12-03 16:23
Yes, static compiling and sysimg can work, not for the jit and the reason is explained in the issue itself very well already.

There's no way we can guarantee `"C-like globals"` and all julia data are by semantic extern. The absolute address for the JIT is already the best we can possibly do.

**Comment by RauliRuohonen** [comment] 2017-12-05 18:10
> This isn't really fixable.

Do you mean that it would require too much changes to Julia's implementation details or MCJIT to be worth fixing? If so, fair enough.

I tried to look into why this is difficult, but couldn't really figure it out. My best guess is that the problem is this [relocation method](https://docs.julialang.org/en/stable/devdocs/compiler/#High-level-Overview-of-the-Native-Code-Generation-Process-1):

> When emitting code to an object file, pointers will be emitted as relocations. [The deserializer implements] a custom manual mechanism similar to a Global Offset Table (GOT) to restore them.

This type of thing will not be possible with RIP-relative addressing if the data and the code can move arbitrarily relative to each other, but it works fine with absolute addressing. There shouldn't be any need to relocate non-precompiled code or write it into a file, though. And even for code that needs to be relocated, one can store the globals and code in a single chunk that's relocated in its entirety, in which case the data and code do not move relative to each other, and so the relative addresses do not need to be modified (this is why C can use RIP-relative addressing in shared libraries).

The only other possible reasons I could think of were that either MCJIT has suboptimal codegen, or that MCJIT somehow makes it difficult to place data and code close to each other.

Finally, I wonder if it just seems difficult, because I may have explained what I had in mind unclearly:

> There's no way we can guarantee "C-like globals" and all julia data are by semantic extern.

I didn't mean doing this for "all julia data", just global constants of fixed size that are either bitstypes, or mutable structs allocated so that the compiler can statically see at the allocation site that it's going to be stored in a global const. I.e. the type of stuff that you know at allocation time is never going to be freed, so you could just use a bump-the-pointer region allocator for all of it, in a region near where the code is (or asking MCJIT to do the allocations in a data segment near the code, if it allows that).

**Comment by Keno** [comment] 2017-12-05 18:42
The problem is the ordering of operations. We first generate the code, then allocate the memory and then resolve the relocations. We don't discover the relative positions of memory and code until the last step. There's also the problem that in order to allocate the memory, we need to know how big it is, which we don't until we've generated the code. It's probably possible to do some reordering here, e.g. doing memory allocation and relocation just before MC emission, but that's a bunch of work for unclear benefit. If you care about performance at this level, you should probably be statically compiling your application anyway.

**Comment by KristofferC** [comment] 2018-01-05 13:20
Closing since there doesn't seem to be any actionable here.

**Closed by KristofferC** 2018-01-05 13:20 UTC
Labels: codegen, won't fix
