### ISSUE TITLE
First call to `peakflops(;parallel=true)` errors in 1.10.

### ISSUE THREAD

**Issue by christiangnrd** [JuliaLang/julia#52040] opened 2023-11-06 04:25 UTC
Edit: Fixed by #52045

While I didn't do a full bisect, this does not happen on 1.9.3, nor the master branch, but it happens on 1.10.0-alpha1 and 1.10.0-rc1.

The first REPL call to `peakflops(;parallel=true)` errors as show below in 1.10.

```
julia> versioninfo()
Julia Version 1.10.0-rc1
Commit 5aaa9485436 (2023-11-03 07:44 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i9-11900 @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, rocketlake)
  Threads: 23 on 16 virtual cores
Environment:
  JULIA_NUM_THREADS = auto

julia> peakflops(;parallel=true)
ERROR: MethodError: no method matching nworkers()
The applicable method may be too new: running in world age 31434, while current world is 31435.

Closest candidates are:
  nworkers(::Distributed.WorkerPool) (method too new to be called from this world context.)
   @ Distributed ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/Distributed/src/workerpool.jl:139
  nworkers() (method too new to be called from this world context.)
   @ Distributed ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/Distributed/src/cluster.jl:900
  nworkers(::Distributed.AbstractWorkerPool) (method too new to be called from this world context.)
   @ Distributed ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/Distributed/src/workerpool.jl:148

Stacktrace:
 [1] peakflops(n::Int64; eltype::DataType, ntrials::Int64, parallel::Bool)
   @ LinearAlgebra ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/LinearAlgebra/src/LinearAlgebra.jl:622
 [2] peakflops(n::Int64; eltype::DataType, ntrials::Int64, parallel::Bool)
   @ InteractiveUtils ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/InteractiveUtils/src/InteractiveUtils.jl:336
 [3] peakflops
   @ InteractiveUtils ~/.julia/juliaup/julia-1.10.0-rc1+0.x64.linux.gnu/share/julia/stdlib/v1.10/InteractiveUtils/src/InteractiveUtils.jl:331 [inlined]
 [4] top-level scope
   @ REPL[2]:1

julia> peakflops(;parallel=true)
4.3407102568400824e11
```

**Comment by jaakkor2** [comment] 2023-11-06 07:27
Reproduced on Windows.

Note that `using Revise; peakflops(; parallel=true)` does not error.

**Comment by giordano** [comment] 2023-11-06 08:20
Duplicate of #51756

**Comment by christiangnrd** [comment] 2023-11-06 12:10
Close or wait for it to be backported?

**Comment by ViralBShah** [comment] 2023-11-06 13:19
Keep this open until backported.

**Comment by ufechner7** [comment] 2023-11-07 01:59
Isn't it backporteted now? See: https://github.com/JuliaLang/julia/pull/52045

**Comment by christiangnrd** [comment] 2023-11-07 02:14
I was planning on closing it once 1.10.0-rc2 came out

**Comment by christiangnrd** [comment] 2023-11-07 02:16
That way if someone encounters it and forgets to check the closed issues (like I did) they won't miss it.

**Comment by KristofferC** [comment] 2023-11-07 17:02
People also tend to forget the open issues ;). I think it is fine to close this.

**Closed by KristofferC** 2023-11-07 17:02 UTC
