### ISSUE TITLE
StackOverflow from function definition

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#31861] opened 2019-04-28 10:57 UTC
This is also present in Julia v1.1:
```julia
julia> struct ProductSpace{T<:Tuple}
       end

julia> using StaticArrays
[ Info: Precompiling StaticArrays [90137ffa-7385-5640-81b9-e52037218182]

julia> function convert_space(::Type{ProductSpace{Tuple{SVector{M,T},T}}}, x::SVector{N,T}) where {N,M,T}
       end
convert_space (generic function with 1 method)

julia> function convert_space(::Type{ProductSpace{Tuple{T,SVector{M,T}}}}, x::SVector{N,T}) where {N,M,T}
       end
ERROR: StackOverflowError:
Stacktrace:
 [1] top-level scope at REPL[4]:1

julia> versioninfo()
Julia Version 1.3.0-DEV.121
Commit dc6c7c7e6f (2019-04-27 03:49 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.5.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by dlfivefifty** [comment] 2019-04-28 10:58
Very similar to closed issue https://github.com/JuliaLang/julia/issues/31082

**Comment by daanhb** [comment] 2019-07-17 11:49
Also similar I think to issue #26487 (which arose from similar code in the same package).

**Comment by OlivierHnt** [comment] 2020-07-18 17:09
Follow-up of [a question on Discourse](https://discourse.julialang.org/t/surprising-stackoverflowerror/43277/3). Perhaps this issue is related to the following StackOverflowError:

```Julia
julia> f(x::T, y::T, z::S) where {S,T<:Vector{S}} = "method 1"
f (generic function with 1 method)

julia> f(x::T, z::S, y::T) where {S,T<:Vector{S}} = "method 2"
ERROR: StackOverflowError:
Stacktrace:
 [1] top-level scope at REPL[2]:1

julia> methods(f)
# 2 methods for generic function "f":
[1] f(x::T, y::T, z::S) where {S, T<:Array{S,1}} in Main at REPL[1]:1
[2] f(x::T, z::S, y::T) where {S, T<:Array{S,1}} in Main at REPL[2]:1

julia> f([1,2],1,[1,2])
"method 2"

julia> f([1,2],[1,2],1)
"method 1"
```

**Comment by martinholters** [comment] 2020-08-06 09:44
Duplicate of #26487

Replacing `ProductSpace` with `Val` and `SVector{_,T}` with `Val{T}` leads to the same reduction as in #26487, so closing as dup.

**Closed by martinholters** 2020-08-06 09:44 UTC
Labels: types and dispatch
