### ISSUE TITLE
throw dlopen error when 32-bit library is loaded from 64-bit Julia

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#11441] opened 2015-05-26 15:40 UTC
(or vice versa).   Right now, this seems to just crash(?) (stevengj/PyCall.jl#148).  Can `dlopen` (i.e. libuv) detect the architecture of a library file and throw an exception?

(Would be good to try this outside of PyCall to verify that it really crashes and is not PyCall's fault.  But I think PyCall should throw an error if `dlopen` does.)

**Comment by yuyichao** [comment] 2015-05-26 21:58
It does give an error on linux. The error is "no error" (as with any dlopen error) though...

```julia
julia> Libdl.dlopen("/usr/lib32/libpython2.7.so")
ERROR: could not load module /usr/lib32/libpython2.7.so: no error
 in dlopen at ./libdl.jl:44
```

**Comment by vtjnash** [comment] 2015-05-27 13:11
Duplicate of https://github.com/JuliaLang/julia/issues/4204

**Closed** 2015-05-27 13:17 UTC
