### ISSUE TITLE
Pkg.checkout throws error on julia 0.5 RC2

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#17995] opened 2016-08-12 17:05 UTC
````
julia> Pkg.checkout("DataStreams", "0.0.6")
INFO: Checking out DataStreams 0.0.6...
ERROR: GitError(Code:ERROR, Class:Merge, There is no tracking information for the current branch.)
 in #123 at .\libgit2\libgit2.jl:414 [inlined]
 in with(::Base.LibGit2.##123#128{Base.LibGit2.GitRepo}, ::Void) at .\libgit2\types.jl:638
 in (::Base.LibGit2.##119#124{String,String,Bool,Base.LibGit2.MergeOptions,Base.LibGit2.CheckoutOptions,Base.LibGit2.GitRepo})(::Base.LibGit2.GitReference) at .\libgit2\libgit2.jl:412
 in with(::Base.LibGit2.##119#124{String,String,Bool,Base.LibGit2.MergeOptions,Base.LibGit2.CheckoutOptions,Base.LibGit2.GitRepo}, ::Base.LibGit2.GitReference) at .\libgit2\types.jl:638
 in (::Base.#kw##merge!)(::Array{Any,1}, ::Base.#merge!, ::Base.LibGit2.GitRepo) at .\<missing>:0
 in (::Base.Pkg.Entry.##18#20{String,String,Bool,Bool})(::Base.LibGit2.GitRepo) at .\pkg\entry.jl:231
 in transact(::Base.Pkg.Entry.##18#20{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at .\libgit2\libgit2.jl:520
 in with(::Base.Pkg.Entry.##17#19{String,String,Bool,Bool}, ::Base.LibGit2.GitRepo) at .\libgit2\types.jl:638
 in checkout(::String, ::String, ::Bool, ::Bool) at .\pkg\entry.jl:227
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#checkout,Tuple{String,String,Bool,Bool}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in checkout(::String, ::String) at .\pkg\pkg.jl:170

julia> Pkg.status()
6 required packages:
 - ExcelReaders                  0.6.0
 - Gallium                       0.0.3
 - Lora                          0.5.4
 - Mimi                          0.2.0
 - NamedTuples                   1.0.0
 - TypedTables                   0.1.1+             julia-0-5
59 additional packages:
 - ASTInterpreter                0.0.3
 - AbstractTrees                 0.0.3
 - ArgParse                      0.3.1
 - BinDeps                       0.4.2
 - COFF                          0.0.1
 - CRC                           1.1.1
 - Calculus                      0.1.15
 - CategoricalArrays             0.0.2
 - ColorTypes                    0.2.5
 - Colors                        0.6.6
 - Compat                        0.8.6
 - Conda                         0.2.3
 - DWARF                         0.0.3
 - DataArrays                    0.3.8
 - DataFrames                    0.7.4+             nl/nullable
 - DataStreams                   0.0.7              0.0.6
 - DataStructures                0.4.5
 - Dates                         0.4.4
 - Distributions                 0.10.2
 - DocStringExtensions           0.1.0
 - Docile                        0.5.23
 - Documenter                    0.2.0
 - ELF                           0.0.3
 - FileIO                        0.1.0
 - FixedPointNumbers             0.1.4
 - Formatting                    0.1.5
 - ForwardDiff                   0.2.2
 - FunctionWrappers              0.0.0-             master (unregistered)
 - GZip                          0.2.20
 - Graphs                        0.6.0
 - JSON                          0.6.0
 - JuliaParser                   0.7.4
 - LegacyStrings                 0.1.1
 - LibExpat                      0.2.0
 - MachO                         0.0.3
 - MacroTools                    0.3.2              master
 - NaNMath                       0.2.1
 - NullableArrays                0.0.7
 - ObjFileBase                   0.0.3
 - PDMats                        0.4.2
 - PyCall                        1.7.0
 - Query                         0.0.0-             master (unregistered)
 - Reactive                      0.3.4
 - Reexport                      0.0.3
 - ReverseDiffSource             0.2.3
 - Rmath                         0.1.2
 - SHA                           0.2.0
 - SQLite                        0.3.3+             master
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.9.0
 - StatsFuns                     0.3.0
 - StructIO                      0.0.2
 - TerminalUI                    0.0.2
 - TextWrap                      0.1.6
 - URIParser                     0.1.6
 - VT100                         0.0.2
 - WeakRefStrings                0.1.2
 - WinRPM                        0.2.0
 - Zlib                          0.1.12

julia>
````
Looking at the repo itself, there also seems some data corruption, in particular the upstream info seems to be deleted:
````
C:\Users\anthoff\.julia\v0.5\DataStreams [0.0.6]> git status
On branch 0.0.6
Your branch is based on 'origin/0.0.6', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
nothing to commit, working directory clean
C:\Users\anthoff\.julia\v0.5\DataStreams [0.0.6]>
````

**Comment by tkelman** [comment] 2016-08-12 17:43
possibly duplicate of #17146

**Comment by KristofferC** [comment] 2016-08-12 17:45
Looks like an exact dup?

**Closed** 2016-08-23 21:01 UTC
Labels: packages
