### ISSUE TITLE
"check_ambiguous_visitor: Assertion `!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)' failed" when "using Makie" in julia-debug

### ISSUE THREAD

**Issue by KestutisMa** [JuliaLang/julia#32747] opened 2019-07-31 10:08 UTC
I am debugging PackageCompiler issue, which looks like is on Julia's C side: https://github.com/JuliaLang/julia/issues/32733 and https://github.com/TsurHerman/Fezzik/issues/3
I compiled (in Arch Linux, gcc v9.1) julia with `make debug`. Started julia-debug REPL, command `using Makie` just trowed error (using regular version of julia error is not trowed):
```
julia> using Makie
[ Info: Precompiling Makie [ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]
[Detaching after vfork from child process 25323]
julia-debug: /home/kest/Projects/julia/src/gf.c:1188: check_ambiguous_visitor: Assertion `!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)' failed.

signal (6): Aborted
in expression starting at /home/kest/.julia/packages/StructArrays/RkrVr/src/structarray.jl:80
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
...
```
```
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
DEBUG build
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```
Maybe somebody can comment?

**Comment by TsurHerman** [comment] 2019-08-01 09:09
Ok it is enough to just build julie-debug and then run 
`using StructArrays`
it crashes with

> gf.c:1188: check_ambiguous_visitor: Assertion `!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)' failed

it does not crash on the regular build of julia.

**Comment by TsurHerman** [comment] 2019-08-01 09:21
changing gf.c from line 1110

> else if (closure->after) {
>         assert(!jl_subtype((jl_value_t*)sig, (jl_value_t*)type));
>         msp = jl_type_morespecific_no_subtype((jl_value_t*)type, (jl_value_t*)sig);
>     }


to return :
 
> else if (closure->after) {
>         return 1;
>         assert(!jl_subtype((jl_value_t*)sig, (jl_value_t*)type));
>         msp = jl_type_morespecific_no_subtype((jl_value_t*)type, (jl_value_t*)sig);
>     }

If I understand correctly, this change makes it that some corner case ambiguities in generated functions are ignored...

Anyway, this change makes PackageCompiler not segfault on incrementally building Makie and Electron.
Which greatly enhances the usefulness of that package

I am tagging a couple of the PackageCompiler guys
@SimonDanisch @NHDaly

**Comment by KestutisMa** [comment] 2019-08-01 14:51
Tested on Julia v1.1.1 build, can confirm at this case that segfaults are gone. Nice job!
Probably somebody could advice if it is safe modification?

**Comment by KestutisMa** [comment] 2019-08-01 15:17
Probably happy to early, tried brute_build_julia() this file after I compiled Interact, Blink, Makie:
```
# // Noble lygciu skaiciavimas
function kernel1!(V_,
	I,
	n_,
	m_,
	h_,
	dt_sim,
	cellCountY,
    cellCountX, i)

   	for y = 1:cellCountY
       	for x = 1:cellCountX
            V = V_[y,x];
            n = n_[y,x];
            m = m_[y,x];
            h = h_[y,x];
            g_Na_max = 4.0; g_K_add = 0.002; g_L = 0.0; E_Na = 40.0; E_L = -60.0; Area = 7.6e-3;
            alpha_n = 0.0; beta_n = 0.0; alpha_m = 0.0; beta_m = 0.0; alpha_h = 0.0; beta_h = 0.0; g_Na = 0.0; g_K1 = 0.0; g_K2 = 0.0; i_Na = 0.0; i_K = 0.0; i_Leak = 0.0; i_ion = 0.0;
           	i_Leak = g_L * (V - E_L);
            #  //------------potassium
            alpha_n = .0003 * (-V - 50.) / (exp((-V - 50.) / 10.) - 1.);
            beta_n = .002 * exp((-V - 90.) / 80.);
            n = n + (alpha_n * (1 - n) - beta_n * n) * dt_sim;
            g_K1 = .012 * exp((-V - 90.) / 50.) + .00015 * exp((V + 90.) / 60.);
            g_K2 = .012 * n * n * n * n;
            i_K = (g_K1 + g_K2 + g_K_add) * (V + 100.);
            #  //------------ - sodium
            alpha_h = .166 * exp((-V - 90.) / 20.);
            beta_h = 1. / (1. + exp((-V - 42.) / 10.));
            h = h + (alpha_h * (1. - h) - beta_h * h) * dt_sim;
            alpha_m = .1 * (-V - 48.) / (exp((-V - 48.) / 15.) - 1.);
            beta_m = .12 * (V + 8.) / (exp((V + 8.) / 5.) - 1.);
            m = m + (alpha_m * (1. - m) - beta_m * m) * dt_sim;
            g_Na = m * m * m * h * g_Na_max;
           	i_Na = (g_Na + .0014) * (V - E_Na);

            i_ion = (i_Na + i_K + i_Leak);

            n_[y,x] = n;
            m_[y,x] = m;
            h_[y,x] = h;

            if (x > 1 && x < cellCountX && y > 1 && y < cellCountY ) # // TODO: separete if x ... if y ..., will get extra line simulated
                dx1 = V_[y,x - 1] - V; #// each thread compares two cells: right(x+1) and up (y+1) with current cell (x,y)
                dx2 = V_[y,x + 1] - V;
                dy1 = V_[y - 1,x] - V;
                dy2 = V_[y + 1, x] - V;
                gjX = 125e-9;
                gjY = 125e-9 / 4;
                I[y,x] = -Area * i_ion + 1000 * ( gjX * dx1 + gjX * dx2 + gjY * dy1 + gjY * dy2 );
            end
        end
    end
end

function kernel2!(I, V_, V_reg, cellCountY, cellCountX, dt_sim, dt_reg, i)
    Cm = .12; Area = 7.6e-3;#// mm2 3e-8*1e6, //7.6e-5, //veikia prie 1.96e-8*1e6, //bandymu keliu, plotas nebutinai yra tikras last., tiesiog kad vyktu sklidimas prie realaus PJ laidumo88
   	for y = 1:cellCountY
      		for x = 1:cellCountX

            if (i * dt_sim) % dt_reg == 0
                i_reg = Int(i * dt_sim / dt_reg);
                V_reg[i_reg,y,x] = V_[y,x];
            end
            # V_reg[i,y,x] = V_[y,x];

            V = V_[y,x];

            up = 100 + 60;
            # I_ext = (i > 100 && i < 100 + 2) ? 0.2 : 0
            I_ext = ( (i > 100 && i < 100 + 2)
                ||  (i > up && i < up + 2) ) &&
                    (y > 16 - 2 && y < 16 + 2 && x > 16 - 2 && x < 16 + 2) ? 0.2 : 0;
            # display(I[y,x])
            # error("")
            V_[y,x] = V + dt_sim * (I_ext + I[y,x]) / (Cm * Area);
        end
    end
end

# using AbstractPlotting
import Makie
const mk = Makie

function run()
    Makie.AbstractPlotting.__init__()
#pagal NobleCppLinux 2019-07-16

    dt_sim = .1; #.01simuliacijos dT ms
    sim_t = 400; #simulacijos trukme ms
    dt_reg = .1; #.01isvedimo dT ms
    N_reg = Int(sim_t / dt_reg);# koks isvedimo matricu dydis
    N_sim = Int(sim_t / dt_sim); # simulacijos trukme, iteracijomis
    cellCountY = 32;
    cellCountX = 32;

    n = zeros(cellCountY, cellCountX)
    m = zeros(cellCountY, cellCountX)
    h = zeros(cellCountY, cellCountX)
    I = zeros(cellCountY, cellCountX)
    V = zeros(cellCountY, cellCountX); V .= -85.0;
    V_reg = zeros(N_reg, cellCountY, cellCountX)
# T_reg = Array{Float64,3}(undef,N,sizeY,sizeX)
    vv = []#zeros(N_reg)

# s = contour(rand(sizeX,sizeY), levels = 5, linewidth = 0, fillrange = true)
    # s = Scene(backgroundcolor = :grey)
    # clicks = AbstractPlotting.Node(Point2f0[(0, 0)])
    # s1 = scatter(clicks, color = :red, marker = '+', markersize = 2)
    s1 = mk.heatmap(V)    
    s2 = mk.lines(zeros(2))
    s = mk.vbox(mk.title(s1, "V map";  textsize = 15),
             mk.title(s2, "V[16,16]"; textsize = 15))
    display(s)
    # on(s1.events.mousebuttons) do buttons
    #     if ispressed(s1, Mouse.left)
    #         pos = to_world(s1, Point2f0(s1.events.mouseposition[]))
    #         push!(clicks, push!(clicks[], pos))
    #     end
    #     return
    # end

    i_reg = 0
    for i = 1:N_sim
        if i / N_sim * 100 % 10 == 0
            print(i / N_sim * 100, "% ")
        end
        kernel1!(V, I, n, m, h, dt_sim, cellCountY, cellCountX, i)
        # display(V[32,32])
        kernel2!(I, V, V_reg, cellCountY, cellCountX, dt_sim, dt_reg, i)
        # display(V)
        # error("")
        if i % 100 == 0
            # vv[i_reg] = V[16, 16]
            push!(vv, V[16, 16])
            # i_reg++
            s1[end][1] = V.+1
            s2[end][1] = vv
            mk.update_limits!(s2)
            mk.update!(s2)
            sleep(1 / 24)
        end
    # s[end][1] = reshape(V, cellCountY, cellCountX);
    end
s = mk.lines(reshape(V_reg, N_reg, cellCountY, cellCountX)[:,32,32])
    s2[end][1] = vv

end

run()
```
And that showed:
```
emit_function at /home/kest/Projects/julia/src/codegen.cpp:6277
jl_compile_linfo at /home/kest/Projects/julia/src/codegen.cpp:1144
emit_invoke at /home/kest/Projects/julia/src/codegen.cpp:3145
emit_expr at /home/kest/Projects/julia/src/codegen.cpp:3948
emit_ssaval_assign at /home/kest/Projects/julia/src/codegen.cpp:3662
emit_stmtpos at /home/kest/Projects/julia/src/codegen.cpp:3854 [inlined]
emit_function at /home/kest/Projects/julia/src/codegen.cpp:6277
jl_compile_linfo at /home/kest/Projects/julia/src/codegen.cpp:1144
jl_compile_hint at /home/kest/Projects/julia/src/gf.c:1950
jl_compile_specializations at /home/kest/Projects/julia/src/precompile.c:378
jl_precompile at /home/kest/Projects/julia/src/precompile.c:387 [inlined]
jl_write_compiler_output at /home/kest/Projects/julia/src/precompile.c:34
jl_atexit_hook at /home/kest/Projects/julia/src/init.c:222
main at /home/kest/Projects/julia/ui/repl.c:218
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
_start at /home/kest/Projects/julia/usr/bin/julia (unknown line)
ERROR: failed process: Process(`/home/kest/Projects/julia/usr/bin/julia --optimize=3 --output-o=/home/kest/.julia/packages/PackageCompiler/CJQcs/sysimg/sys.a -g1 --track-allocation=none --startup-file=no --code-coverage=none --history-file=yes --inline=yes --math-mode=ieee --handle-signals=yes --warn-overwrite=no --compile=yes --depwarn=yes --cpu-target=native --track-allocation=none --sysimage-native-code=yes --sysimage=/home/kest/Projects/julia/usr/lib/julia/sys.so -g1 --compiled-modules=yes --optimize=2 /home/kest/.julia/packages/PackageCompiler/CJQcs/sysimg/run_julia_code.jl`, ProcessExited(1)) [1]
Stacktrace:
 [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
 [2] pipeline_error at ./process.jl:785 [inlined]
 [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
 [4] run at ./process.jl:724 [inlined]
 [5] #run_julia#1 at /home/kest/.julia/packages/PackageCompiler/CJQcs/src/compiler_flags.jl:225 [inlined]
 [6] #run_julia at ./none:0 [inlined]
 [7] #compile_incremental#62(::Bool, ::Bool, ::Bool, ::Nothing, ::Function, ::Nothing, ::String) at /home/kest/.julia/packages/PackageCompiler/CJQcs/src/incremental.jl:137
 [8] #compile_incremental at ./none:0 [inlined]
 [9] #brute_build_julia#5(::Bool, ::Bool, ::Function) at /home/kest/.julia/packages/Fezzik/Uvmuj/src/bootstrap.jl:209
 [10] brute_build_julia() at /home/kest/.julia/packages/Fezzik/Uvmuj/src/bootstrap.jl:82
 [11] top-level scope at none:0
```

**Comment by JeffBezanson** [comment] 2019-08-02 18:29
Basically a duplicate of #29594. It's possible we should just remove the assertion, since it clearly does not actually hold (we'd just like it to).


> Anyway, this change makes PackageCompiler not segfault on incrementally building Makie and Electron.

Is the segfault the same as this assertion failure in debug mode, or is it a separate symptom?

**Comment by TsurHerman** [comment] 2019-08-02 20:45
> Is the segfault the same as this assertion failure in debug mode, or is it a separate symptom?

Yes, this specific segfault is caused by this assertion failure.

However, there are other assertions that trigger segfaults when continuing the process of incremental building of the system.
further removing the assertions left the sysimg unstable and the process crashed.
see https://github.com/TsurHerman/Fezzik/issues/3#issuecomment-517641018
for a record of the segfaults.

One of the assertions is a world age assertion, which I think is due to the fact that it was compiling a stateful module like Interact.jl or AbstractPlotiing.jl that might hold a reference for a Task.

**Closed** 2019-08-16 17:05 UTC
