### ISSUE TITLE
searchsorted (and variants) do not check equality?

### ISSUE THREAD

**Issue by mtanneau** [JuliaLang/julia#44102] opened 2022-02-10 00:57 UTC
The following behaviors have been causing bugs in some code of mine:

```julia
searchsortedlast([0.0, 1.0], +0.0)  # returns 1
searchsortedlast([0.0, 1.0], -0.0)  # returns 0

searchsorted([0.0], +0.0)  # returns 1:1
searchsorted([0.0], -0.0)  # returns 1:0

searchsorted([0.0], 0.0; lt=<=)  # returns 2:1
```

In all cases I encountered, I could get away with it by using `searchsortedXXXX(args... ; lt=<)`.

However, assuming the above behavior is what's intended, I believe there's an inconsistency in the docs.
For instance, for `searchsorted`:
>    searchsorted(a, x; by=\<transform\>, lt=\<comparison\>, rev=false)
>
>Return the range of indices of a which compare as equal to x (using binary search) according to
>the order specified by the by, lt and rev keywords, assuming that a is already sorted in that order.
>Return an empty range located at the insertion point if a does not contain values equal to x.

It's hard to believe that `[0.0]` does not contain any value equal to `0.0` 😅

If it's a bug, I probably can't fix it, but if it's intended and clarifying the docs would be satisfactory, then I'm happy to do so.

**Comment by Moelf** [comment] 2022-02-10 01:15
>searchsorted([0.0], 0.0; lt=<=)  # returns 2:1
It's hard to believe that [0.0] does not contain any value equal to 0.0 sweat_smile

as I have said in Slack, `<=` is literally not "is less" in any sense:

`X is less than X` should always be false, but it's true for `<=`, which is why it messed up the result

**Comment by mtanneau** [comment] 2022-02-10 01:34
> `X is less than X` should always be false

Did you mean "strict" order? 
Total orders are reflexive, so if `<=` is a total order, you should have `x <= x` forall `x`.

In any case: when I read "which compare as equal to `x`" in the docs, I expect `0.0` to compare as equal to `0.0`.
I had a similar confusion with "less than or equal to" and "greater than or equal to" in the docs of `searchsortedlast` and `searchsortedfirst`, respectively.

All I'm saying is that, if there's room to make the docs a little clearer, it may avoid other people running into a similar issue.

**Comment by nalimilan** [comment] 2022-02-20 14:44
I agree with @mtanneau that the mention of "or equal" in the docstring is incredibly confusing. This is made even worse by the fact that the default value for `lt` (i.e. `isless`) isn't even shown in the signature.

IIUC "less than or equal" actually means "not greater than according to `lt`", right? This should be mentioned IMO, together with the fact that this relies on a total order. We could also show an example with `-0.0`.

@mtanneau Would you feel like making a PR to propose clarifications?

This has been reported before at https://github.com/JuliaLang/julia/issues/35179. It also caused a bug in the StatsBase implementation of histograms (https://github.com/JuliaStats/StatsBase.jl/issues/766).

**Comment by Moelf** [comment] 2022-02-20 15:08
>Did you mean "strict" order?

I just mean it semantically, what ever "less than" definition you use (plug in different `lt`), a `lt(a, a)` should always always be false.

But `lt = <=` fails this criterion, using `<=` as `lt` does not make sense to me.

**Comment by petvana** [comment] 2022-02-20 19:33
It seems to be related to (kind of duplicate of) #11429. The behavior is undefined for ill-behaved user-specified comparisons, and Julia may even crash during sorting.

**Comment by mtanneau** [comment] 2022-02-21 01:33
> @mtanneau Would you feel like making a PR to propose clarifications?

Yes, I'll try and come up with something this week

**Comment by StefanKarpinski** [comment] 2023-01-27 22:08
I think that checking equality is a good idea.

**Closed** 2023-07-07 22:14 UTC
Labels: doc, search & find
