### ISSUE TITLE
Feature request: Syntax highlighting for `methods`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#39782] opened 2021-02-22 06:20 UTC
In 1.6, stack traces got syntax highlighting in the REPL, but `methods` did not.
Syntax highlighting would help with readability. Presumably the code can be reused.

**Comment by kahanikaar** [comment] 2021-02-28 20:10
I would like to work on this issue, will be grateful for guidance to approach this. @dpsanders @JeffBezanson

**Comment by JeffBezanson** [comment] 2021-05-24 18:27
Duplicate of #40913. Closing this one, since that has more discussion.

**Closed by JeffBezanson** 2021-05-24 18:27 UTC
Labels: display and printing, good first issue
