### ISSUE TITLE
Give link to type definition when no documentation is found

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#21029] opened 2017-03-14 22:08 UTC
```
?LinSpace
```
gives no information about where the type definition is located. It would be useful to provide a link to the type definition.

```
help?> LinSpace
search: LinSpace linspace

  No documentation found.

  Base.LinSpace is of type UnionAll.

  Summary:

  struct UnionAll <: Type{T}

  Fields:

  var  :: TypeVar
  body :: Any
```

**Comment by m-j-w** [comment] 2017-03-20 18:03
As described by dpsanders, when using the REPL help system on a type wrapped by a UnionAll, the output contains the fields of the UnionAll, rather on the wrapped type:
```jl
julia> struct t1{M,N} <: Number
          a::M
          b::N
       end

help?> t1
search: Int16 Int128 rot180 UInt16 UInt128 @int128_str Float16 @uint128_str @vectorize_1arg

  No documentation found.

  t1 is of type UnionAll.

  Summary:

  struct UnionAll <: Type{T}

  Fields:

  var  :: TypeVar
  body :: Any

julia> abstract type at{M,N} <: Number end

help?> at
search: abstract type atan atanh atand atan2 atexit At_mul_B atreplinit At_rdiv_B At_mul_Bt At_mul_B! At_ldiv_B At_rdiv_Bt At_mul_Bt! At_ldiv_Bt At_ldiv_B!

  No documentation found.

  at is of type UnionAll.

  Summary:

  struct UnionAll <: Type{T}

  Fields:

  var  :: TypeVar
  body :: Any
```
A possible solution to present better help to an average user could be adding e.g. the following to `base/docs/Docs.jl` which unwraps the UnionAll and gives the information on the contained type instead:
```jl
function summarize(io::IO, U::UnionAll, binding)
    summarize(io, Base.unwrap_unionall(U), binding)
    println(io, "Note, ```", Base.typename(U),
            "``` is represented by a wrapping type ```UnionAll``` that " *
            "describes the bounds of its type parameters.\n")
end
```
The above output then becomes
```jl
julia> struct t1{M,N} <: Number
          a::M
          b::N
       end

help?> t1
search: Int16 Int128 rot180 UInt16 UInt128 @int128_str Float16 @uint128_str @vectorize_1arg

  No documentation found.

  Summary:

  struct t1{M,N} <: Number

  Fields:

  a :: M
  b :: N

  Note, t1 is represented by a wrapping type UnionAll that describes the bounds of its type parameters.

julia> abstract type at{M,N} <: Number end

help?> at
search: abstract type atan atanh atand atan2 atexit At_mul_B atreplinit At_rdiv_B At_mul_Bt At_mul_B! At_ldiv_B At_rdiv_Bt At_mul_Bt! At_ldiv_Bt At_ldiv_B!

  No documentation found.

  Summary:

  abstract type at{M,N} <: Number

  Note, at is represented by a wrapping type UnionAll that describes the bounds of its type parameters.
```

The function above is available at 6fe7b21842043e80dac7f37cec8d625f1701caf2.

(this was originally intended as a new issue of its own...)

**Comment by nalimilan** [comment] 2017-05-31 13:42
Marking as regression as per https://github.com/JuliaLang/julia/issues/22156.

**Comment by giordano** [comment] 2017-05-31 16:38
@m-j-w Would you mind preparing a PR with your fix? :-)

**Closed** 2021-01-25 20:04 UTC
Labels: doc, docsystem, regression
