### ISSUE TITLE
`@test` does not work with new keyword argument syntax.

### ISSUE THREAD

**Issue by lassepe** [JuliaLang/julia#39121] opened 2021-01-06 13:54 UTC
The new keyword argument syntax that uses the name of the rvalue as the keyword if no name is given does not seem to work with the `Test.@test` macro.

Fore example:

```julia
using Test: @test

atol = 1
@test isapprox(0.1, 0; atol = atol) # works
@test isapprox(0.1, 0; atol)        # fails
```

Other macros like `@assert isapprox(0.1, 0; atol)` work as expected.

**Comment by simeonschaub** [comment] 2021-01-07 09:09
Duplicate of #38215

**Closed by simeonschaub** 2021-01-07 09:09 UTC
Labels: keyword arguments, testsystem
