### ISSUE TITLE
invalid construction, Vector{Tuple{:a, :b}}, creates a traceback rather than an error

### ISSUE THREAD

**Issue by clarkevans** [JuliaLang/julia#40742] opened 2021-05-07 12:29 UTC
This is illegal construction, but rather than being an error, it creates a traceback.

```
julia> versioninfo()
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, goldmont)

julia> T = Vector{Tuple{:a, :b}}
Vector{Tuple{:a, :b}} (alias for Array{Tuple{:a, :b}, 1})

julia> T()
Internal error: encountered unexpected error in runtime:
MethodError(f=Core.Compiler.widenconst, args=(:a,), world=0x00000000000010a8)
jl_method_error_bare at /buildworker/worker/package_linux64/build/src/gf.c:1812
jl_method_error at /buildworker/worker/package_linux64/build/src/gf.c:1830
jl_lookup_generic_ at /buildworker/worker/package_linux64/build/src/gf.c:2400 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2415
...
```

**Comment by simeonschaub** [comment] 2021-05-07 17:06
reproduces on master as well

**Comment by simeonschaub** [comment] 2021-05-07 17:25
Reduced to:
```
julia> f() = getfield(Ref{Tuple{:a}}()[], 1)
f (generic function with 1 method)

julia> @code_warntype f()
ERROR: MethodError: no method matching widenconst(::Symbol)
Closest candidates are:
  widenconst(::Union{Core.Compiler.Conditional, Core.InterConditional}) at compiler/typelattice.jl:270
  widenconst(::Type) at compiler/typelattice.jl:285
  widenconst(::Core.Const) at compiler/typelattice.jl:271
  ...
Stacktrace:
  [1] widenreturn(rt::Any, bestguess::Any, nslots::Int64, slottypes::Vector{Any}, changes::Vector{Any})
    @ Core.Compiler ./compiler/abstractinterpretation.jl:1629
  [2] typeinf_local(interp::Core.Compiler.NativeInterpreter, frame::Core.Compiler.InferenceState)
    @ Core.Compiler ./compiler/abstractinterpretation.jl:1715
  [3] typeinf_nocycle(interp::Core.Compiler.NativeInterpreter, frame::Core.Compiler.InferenceState)
    @ Core.Compiler ./compiler/abstractinterpretation.jl:1875
  [4] _typeinf(interp::Core.Compiler.NativeInterpreter, frame::Core.Compiler.InferenceState)
    @ Core.Compiler ./compiler/typeinfer.jl:226
  [5] typeinf(interp::Core.Compiler.NativeInterpreter, frame::Core.Compiler.InferenceState)
    @ Core.Compiler ./compiler/typeinfer.jl:209
  [6] typeinf_code(interp::Core.Compiler.NativeInterpreter, method::Method, atypes::Any, sparams::Core.SimpleVector, run_optimizer::Bool)
    @ Core.Compiler ./compiler/typeinfer.jl:847
[...]
```
Does it make sense for `getindex(::Ref{Tuple{:a}})` to infer to `Tuple{:a}` or should that be `Union{}` instead? Or alternatively, should `getfield_tfunc` just be made more robust?

**Comment by vtjnash** [comment] 2021-05-07 18:04
Ah, that seems to make this a duplicate of https://github.com/JuliaLang/julia/issues/39988

**Closed** 2021-05-28 19:55 UTC
Labels: bug, inference
