### ISSUE TITLE
Pkg.build fails with LoadError: Unable to open libLLVM!

### ISSUE THREAD

**Issue by markleary** [JuliaLang/julia#29720] opened 2018-10-18 20:10 UTC
Using Julia 0.7.0 on RHEL 7.5.  Julia was installed from julia-epel-7 repo referenced in the documentation (https://copr.fedorainfracloud.org/coprs/nalimilan/julia/).  Building any package fails with:

ERROR: LoadError: LoadError: Unable to open libLLVM!

llvm6-libs.x86_64-6.0.0-4.el7 package was installed from the julia repo.  This rpm installs libLLVM to /usr/lib64/llvm6/lib/.  For some reason the build process does not find the lib.  I worked around the issue by creating a symlink in /usr/lib64:

`ln -s /usr/lib64/llvm6/lib/libLLVM-6.0.0.so /usr/lib64/libLLVM.so`

With this symlink in place, packages build successfully.

**Julia versioninfo():**

```
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E7-8880 v3 @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

**build log:**

```
ERROR: LoadError: LoadError: Unable to open libLLVM!
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] (::getfield(BinaryProvider, Symbol("#open_libllvm#114")))() at /bbkinghome/mleary/.julia/packages/BinaryProvider/1nGWd/src/PlatformNames.jl:650
 [3] detect_cxx11_string_abi() at /bbkinghome/mleary/.julia/packages/BinaryProvider/1nGWd/src/PlatformNames.jl:653
 [4] detect_compiler_abi() at /bbkinghome/mleary/.julia/packages/BinaryProvider/1nGWd/src/PlatformNames.jl:666
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include at ./sysimg.jl:29 [inlined]
 [9] include(::String) at /bbkinghome/mleary/.julia/packages/BinaryProvider/1nGWd/src/BinaryProvider.jl:1
 [10] top-level scope at none:0
 [11] top-level scope at none:2
in expression starting at /bbkinghome/mleary/.julia/packages/BinaryProvider/1nGWd/src/PlatformNames.jl:683
in expression starting at /bbkinghome/mleary/.julia/packages/BinaryProvider/1nGWd/src/BinaryProvider.jl:12
ERROR: LoadError: Failed to precompile BinaryProvider [b99e7846-7c00-51b0-8f62-c81ae34c0232] to /bbkinghome/mleary/.julia/compiled/v0.7/BinaryProvider/ek6VZ.ji.
Stacktrace:
 [1] include(::String) at ./client.jl:398
 [2] top-level scope at none:0
in expression starting at /bbkinghome/mleary/.julia/packages/Rmath/Py9gH/deps/build.jl:1
```

**julia-epel-7.repo**

```
[julia-epel-7]
name=Copr repo for julia owned by nalimilan
baseurl=https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia/epel-7-$basearch/
enabled=True
gpgcheck=True
gpgkey=https://copr-be.cloud.fedoraproject.org/results/nalimilan/julia/pubkey.gpg
skip_if_unavailable=True
```

**Comment by egnha** [comment] 2018-10-25 07:36
@nalimilan Even on 1.0.1, I run into a similar problem (`ERROR: LoadError: LoadError: Unable to open libLLVM!`) when attempting to build ZMQ and MBedTLS, as part of the IJulia build. Could you kindly point me to the fix?

**Comment by moppymopperson** [comment] 2018-10-25 08:18
I'm having the same issue as @egnha, though I'm on Ubuntu 18.

**Comment by nalimilan** [comment] 2018-10-26 18:22
@egnha I can't reproduce on Fedora 28 nor on Centos 7. What OS and what exact version of the package are you using?

Cc: @cdluminate for Debian/Ubuntu.

**Comment by cdluminate** [comment] 2018-10-27 03:32
@nalimilan Cannot reproduce on both amd64 and ppc64el. Tested with julia version `Debian ⛬  julia/1.0.1-2`

**Comment by cdluminate** [comment] 2018-10-27 03:40
Maybe something wrong with the shared lib / symlink `/usr/lib/x86_64-linux-gnu/julia/libLLVM.so
` ?

These files / symlinks are included in the official binary tarball.
```
~/b/julia-1.0.0 ❯❯❯ find | rg LLVM
./lib/julia/libLLVM-6.0.so
./lib/julia/libLLVM.so
./lib/julia/libLLVM-6.0.0.so
```

**Comment by nazywamsiepawel** [comment] 2018-10-29 10:38
I'm having the same issue on macOS Mojave, 10.14 with an anaconda setup and Julia v1.0.1

I create a new environment, install julia via `conda install -c conda-forge julia`

In order to access Julia via jupyter notebooks I do the following:

`
using Pkg 
Pkg.add("IJulia")
`

All goes fab,but then then opening `jupyter notebook` and selecting Julia yields the following:

`Blosc not installed properly, run Pkg.build("ZMQ"), restart Julia and try again`

Hoping for a successful resolution of the above, I run:

`
using Pkg 
Pkg.build("ZMQ")
`

Which slaps me back with the error that we are all experiencing here:

`
 Error: Error building `ZMQ`: 
│ ERROR: LoadError: LoadError: Unable to open libLLVM!
`

Is there anything wrong with the process I'm following? It's the first time I'm trying to get Julia to work with Jupyter Notebook. 

**Julia info**

`
Julia Version 1.0.1
Platform Info:
  OS: macOS (x86_64-apple-darwin16.7.0)
  CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
`

**Comment by MaxBalashov** [comment] 2018-10-29 11:51
> I'm having the same issue on macOS Mojave, 10.14 with an anaconda setup and Julia v1.0.1
> 
> I create a new environment, install julia via `conda install -c conda-forge julia`
> 
> In order to access Julia via jupyter notebooks I do the following:
> 
> `using Pkg Pkg.add("IJulia")`
> 
> All goes fab,but then then opening `jupyter notebook` and selecting Julia yields the following:
> 
> `Blosc not installed properly, run Pkg.build("ZMQ"), restart Julia and try again`
> 
> Hoping for a successful resolution of the above, I run:
> 
> `using Pkg Pkg.build("ZMQ")`
> 
> Which slaps me back with the error that we are all experiencing here:
> 
> `Error: Error building`ZMQ`: │ ERROR: LoadError: LoadError: Unable to open libLLVM! `
> 
> Is there anything wrong with the process I'm following? It's the first time I'm trying to get Julia to work with Jupyter Notebook.
> 
> **Julia info**
> 
> `Julia Version 1.0.1 Platform Info: OS: macOS (x86_64-apple-darwin16.7.0) CPU: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz WORD_SIZE: 64 LIBM: libopenlibm LLVM: libLLVM-6.0.0 (ORCJIT, skylake)`

I also have such problem!

**Comment by quentinlouis** [comment] 2018-11-01 12:04
Same problem for me !

**Comment by rnevils** [comment] 2018-11-01 16:47
@nazywamsiepawel I am having same issue, Mojave 10.14, installing Julia via anaconda and trying to use jupyter.  However, I was able to to get Julia working with juypter notebooks by avoiding Anaconda altogether. Using homebrew to install Julia, then running
``` 
using IJulia 
notebook()
```
worked for me. However I this is only the notebooks and I still want to be able to use JuypterLab

**Comment by liushuya7** [comment] 2018-11-01 20:33
I'm having the exact same Issue when I tried to use IJulia via Anaconda. But problem solved when I switched to [JuliaPro](https://juliacomputing.com/products/juliapro.html#comparison).

**Comment by zlewko** [comment] 2018-11-04 14:48
same issue on ubuntu 18.04 when julia is installed via anaconda.  

corrected with:
ln -s  /usr/lib/llvm-6.0/lib/libLLVM-6.0.0.so /usr/lib/libLLVM.so

**Comment by GabrielEdogawa** [comment] 2018-11-14 18:34
> same issue on ubuntu 18.04 when julia is installed via anaconda.
> 
> corrected with:
> ln -s /usr/lib/llvm-6.0/lib/libLLVM-6.0.0.so /usr/lib/libLLVM.so

Yeah but I guess the solution differs in Mac. Can somebody show me where I can find libLLVM-6.0.0 in Mac system? I performed the same installation steps of the same version of Julia in a same Mac system with @nazywamsiepawel and I even do not know where to find that library.

**Comment by versipellis** [comment] 2018-11-19 20:47
Confirming the same issue on Ubuntu 18.10, Julia 1.0.2, conda 4.5.11.

**Comment by kirksw** [comment] 2018-12-04 21:32
Note that the above two links are missing the final slash, depending on your machine there will be 5.0 or 6.0. Ubuntu 18.04 has 6.0.

ln -s /usr/lib/llvm-6.0/lib/lib**/**LLVM-6.0.0.so /usr/lib/libLLVM.so

**Comment by mbudisic** [comment] 2019-01-02 22:09
Confirming the same issue on Ubuntu 18.10, Julia 1.0.3, conda 4.5.12.

Fixed by softlinking as above.

**Comment by yuvilio** [comment] 2019-01-06 18:49
Same here, `ln -s` fixed. Obviously the llvm's library path may slightly differ on different linux distros (and which package one uses to provide it)  or other operatiing systems. For my Ubuntu 18.10 setup,  it happened to be provided by a few packages including  `libjulia1`.

Similarly fixed it with tracking the file down and making the libLLVM available in the more generic library path:
```bash
$ dpkg -S libLLVM.so 
llvm-6.0-dev: /usr/lib/llvm-6.0/lib/libLLVM.so
libjulia1: /usr/lib/x86_64-linux-gnu/julia/libLLVM.so
$ sudo ln -s /usr/lib/x86_64-linux-gnu/julia/libLLVM.so /usr/lib/libLLVM.so
$
```

The install requiring it, (`Pkg.add("IJulia")` in my case) worked smoothly after.

**Comment by krinsman** [comment] 2019-01-17 03:51
Maybe this issue should be merge with (or vice versa) https://github.com/JuliaPackaging/BinaryProvider.jl/issues/130

**Comment by krinsman** [comment] 2019-01-17 05:06
Since this is an issue with the conda-forge julia package, the solution might be found in the current build script for that package, found here:

https://github.com/conda-forge/julia-feedstock/blob/master/recipe/build.sh

In particular, note that the package does not install the conda-forge `llvm` package for Julia to use by default, and that the following flag is used in the make: `USE_SYSTEM_LLVM=0`.

**Comment by j-fu** [comment] 2019-04-04 14:58
Same issue on OpenSUSE 15, here we need `ln -s /usr/lib64/libLLVM.so.5 ~/local/lib64/libLLVM.so`. Linking in to user directory on `LD_LIBRARY_PATH` didn't work, so I hope for the sysadmin on our central server...

**Comment by j-fu** [comment] 2019-04-05 09:08
> Same issue on OpenSUSE 15 with julia 1.0.3 from the science repo, here we need `ln -s /usr/lib64/libLLVM.so.5 /usr/lib64/libLLVM.so`.
> An alternative without root access is to link to a user accessible directory on LD_LIBRARY_PATH:
> 
> ```
> $ mkdir $HOME/lib64
> $ ln -s /usr/lib64/libLLVM.so.5 $HOME/lib64/libLLVM.so
> $ export LD_LIBRARY_PATH=$HOME/lib64/.$LD_LIBRARY_PATH
> ```

Update (thanks to our sysadmin): OpenSuse 15 has a package llvm-devel which creates the link.
So this might be an issue of package dependencies to be addressed in the distro.

**Comment by nalimilan** [comment] 2019-04-05 12:00
Can you file an issue against the OpenSUSE repo (and post the link here)?

**Comment by j-fu** [comment] 2019-04-05 14:05
> > Same issue on OpenSUSE 15 with julia 1.0.3 from the science repo, here we need `ln -s /usr/lib64/libLLVM.so.5 /usr/lib64/libLLVM.so`.
> > An alternative without root access is to link to a user accessible directory on LD_LIBRARY_PATH:
> > ```
> > $ mkdir $HOME/lib64
> > $ ln -s /usr/lib64/libLLVM.so.5 $HOME/lib64/libLLVM.so
> > $ export LD_LIBRARY_PATH=$HOME/lib64/.$LD_LIBRARY_PATH
> > ```
> 
> Update (thanks to our sysadmin): OpenSuse 15 has a package llvm-devel which creates the link.
> So this might be an issue of package dependencies to be addressed in the distro.
Update: Similar discussion is already running on https://bugzilla.opensuse.org/show_bug.cgi?id=1114692 .
I put  in my 2cts in there and gave the link to the discussion here.

**Comment by nalimilan** [comment] 2019-04-05 15:27
Thanks. Actually it looks like the problem is just that OpenSUSE should use `USE_LLVM_SHLIB=1` instead of `USE_LLVM_SHLIB=0` in the [juliabuildopts](https://build.opensuse.org/package/view_file/science/julia/juliabuildopts?expand=1) file.

**Comment by j-fu** [comment] 2019-10-07 13:25
Thanks for the hint. Over at OpenSuse they tried it and it worked: https://bugzilla.opensuse.org/show_bug.cgi?id=1114692#c7
On Tumbleweed I was able to check this - it is there now.

**Comment by ViralBShah** [comment] 2020-12-17 14:45
Let's reopen if still an issue.

**Closed by ViralBShah** 2020-12-17 14:45 UTC

**Comment by eahenle** [comment] 2022-09-22 21:50
Currently running into this issue when running the following CI workflow on GHA:

```yaml
runs-on: windows-latest

steps:
      - name: checkout commit
        uses: actions/checkout@master

      - name: set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.8.1'
      
      - name: build package
        uses: julia-actions/julia-buildpkg@latest
```

**Comment by WT215** [comment] 2022-11-22 16:43
> CI workflow on GHA

can you explained more on how to implement this please? Many thanks!

**Comment by WT215** [comment] 2022-11-22 16:43
> Currently running into this issue when running the following CI workflow on GHA:
> 
> ```yaml
> runs-on: windows-latest
> 
> steps:
>       - name: checkout commit
>         uses: actions/checkout@master
> 
>       - name: set up Julia
>         uses: julia-actions/setup-julia@latest
>         with:
>           version: '1.8.1'
>       
>       - name: build package
>         uses: julia-actions/julia-buildpkg@latest
> ```

can you explained more on how to implement this please? Many thanks!

**Comment by eahenle** [comment] 2023-01-09 17:01
@gustaphe No ☹️ 

I have found the upstream issue, though: https://github.com/JuliaPackaging/BinaryProvider.jl/issues/211
In my case, one of my package's dependencies uses `BinaryProvider`, which is deprecated.

**Comment by msanchezr99** [comment] 2023-09-12 04:47
Having this issue in Windows 10. I try to run "using Plots" and it shows FFMPEG not installed properly. It says I must run "build FFMPEG" but when I do it shows load error saying unable to open libLLVM. Don't know what to do!

**Comment by droodman** [comment] 2024-03-31 19:47
I'm exactly same issue as described by @msanchezr99, except in Windows 11 Pro 23H2. It's preventing me from `using Plots`.

**Comment by gustaphe** [comment] 2024-04-08 15:41
@droodman  broken link.
