### ISSUE TITLE
Broadcast on nested Arrays gives suboptimal type information

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#11119] opened 2015-05-03 23:59 UTC
```
a = Array(Array{Float64,1},2)
a[1] = [1.;2.;3.]
a[2] = [3.;4.;5.]
broadcast(*,[2.;3.],a)
```
gives
```
2-element Array{Any,1}:
 [2.0,4.0,6.0]
 [9.0,12.0,15.0]
```
I would have expected an `Array{Array{Float64,1},1}`.

**Comment by simonster** [comment] 2015-05-05 15:00
Right now the return type is determined using `promote_eltype` or by a set of ad-hoc functions in broadcast.jl. To get this right generally, it seems like we need to either (ab)use type inference or use a trick similar to `map`.

**Comment by stevengj** [comment] 2016-05-05 14:24
`map(*, [2.,3.], a)` gives an `Array{Array{Float64,1},1}`, so this is another instance that would apparently be fixed by adapting `map`'s algorithm to `broadcast` (#16164).   Duplicate of #4883.

**Closed by stevengj** 2016-05-05 14:24 UTC
