### ISSUE TITLE
Feature: a way for macros to determine when they're in the top scope

### ISSUE THREAD

**Issue by mnemnion** [JuliaLang/julia#53327] opened 2024-02-13 22:58 UTC
I ran directly into this issue, and [found some discussion](https://discourse.julialang.org/t/should-macros-get-an-istoplevel-or-scope-argument/44850) about it, but not a corresponding issue. Apologies if this is already in the tracker and I missed it.

There are a number of subtle differences between globally-scoped Julia and locally-scoped Julia. I have a pair of macros in the package I'm developing, which declare variables. It would be sensible for these to be constants, but `const` is only allowed in the top scope. And `@rule :name  ←  [etc...]`, which is the rough syntax of one of these macros, can't be written `const @rule :name  ←  [etc...]` because it's a syntax error. 

I would love it if there was no such thing as "top-level Julia syntax" and "local Julia syntax", but I'll limit myself to a one-sentence kvetch about that. A magic variable like `__module__` or `__source__` that indicated which context the macro is executing in, like a Bool `__toplevel__`, would let me write macros which account for the differences between those contexts, which would be plenty.

**Comment by MasonProtter** [comment] 2024-02-16 14:59
Duplicate of https://github.com/JuliaLang/julia/issues/34168

**Closed** 2024-02-16 15:00 UTC
