### ISSUE TITLE
 Allow '∀' and '∃' to be parsed as symbols

### ISSUE THREAD

**Issue by 0x0f0f0f** [JuliaLang/julia#39271] opened 2021-01-15 13:10 UTC
I'm building a DSL for symbolic things. I couldn't parse unicode characters for forall '∀' and  exists '∃' as symbols (function names) in 1.6.0-beta1.

**Comment by Seelengrab** [comment] 2021-01-15 13:24
Duplicate of #19012

**Closed** 2021-01-15 14:34 UTC
