### ISSUE TITLE
Illegal instruction in Julia 1.0.0/1.1.0 (but not in 0.7.0)

### ISSUE THREAD

**Issue by oyamad** [JuliaLang/julia#29468] opened 2018-10-02 05:04 UTC
(Initially posted in QuantEcon/Games.jl#92)

Apologies if already known, but the following code leads to "Illegal instruction: 4" with Julia 1.0.0 and 1.1.0 (Nightly), but not with 0.7.0:

```jl
struct A{N,T}
    arr::Array{T,N}
end

struct B{N,T}
    as::NTuple{N,A{N,T}}
end

B(as::A{N,T}...) where {N,T} = B(as)
```

```jl
a1 = A(zeros(2, 2))
a2 = A(zeros(2, 2))
B(a1, a2)
```

```
Unreachable reached at 0x108a94186

signal (4): Illegal instruction: 4
in expression starting at no file:0
Type at ./REPL[3]:1
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x114d65a4f)
unknown function (ip: 0xffffffffffffffff)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:787
jl_toplevel_eval_in at /Users/osx/buildbot/slave/package_osx64/build/src/builtins.c:622
eval at ./boot.jl:319
eval_user_input at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:85
macro expansion at /Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:117 [inlined]
#28 at ./task.jl:259
jl_apply at /Users/osx/buildbot/slave/package_osx64/build/src/./julia.h:1536 [inlined]
start_task at /Users/osx/buildbot/slave/package_osx64/build/src/task.c:268
Allocations: 1032878 (Pool: 1032627; Big: 251); GC: 1
Illegal instruction: 4
```

```jl
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
```

```jl
julia> versioninfo()
Julia Version 1.1.0-DEV.352
Commit 4851fab9b4 (2018-10-01 13:53 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
```

**Comment by SimonDanisch** [comment] 2018-10-02 09:49
```Julia
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.365 (2018-10-02)
 _/ |\__'_|_|_|\__'_|  |  jb/fix29269/67c5f6e317 (fork: 4 commits, 0 days)
|__/                   |

```
@JeffBezanson this still runs into the error even on your branch (I merged master into the branch, just in case that messes things up?)

**Comment by SimonDanisch** [comment] 2018-10-02 12:20
I checked 0.7 as well:

* the issue here is working fine on 0.7, not on 1.0 or jb/fix29269/
* #29066 doesn't work on any of the above versions
* #29066 doesn't work on any version either
* the second issue I mention in #29066 seems to work fine in julia 0.7, but hard to tell since it wasn't deterministic

**Comment by vtjnash** [comment] 2018-10-02 15:28
dissected it to this type-intersection bug:
```julia
julia> struct A{N}; end;

julia> typeintersect(Tuple{Vararg{A{N}, N}} where N,
                     Tuple{A{2}, Vararg{A{2}}})
Union{} # bad

julia> typeintersect(Tuple{Vararg{A{N}, N}} where N,
                     Tuple{Vararg{A{2}}})
Tuple{A{2}, A{2}} # more correct
```


Unrelated to the crash, I also noticed that the given second answer is actually wrong also. The correct answer is:
```julia
Union{Tuple{}, Tuple{A{2}, A{2}}}
```
since `N=0` is also a valid solution to the above constraints.

**Comment by vtjnash** [comment] 2018-10-02 15:33
(note this worked / didn't crash in v0.7 because we inhibited inference of the deprecated construct-to-convert method signature, and not a new type system or dispatch regression).

**Closed** 2018-10-03 20:14 UTC
Labels: bug, types and dispatch
