### ISSUE TITLE
Single line Parametric method with parametric return type throws UndefVarError

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaLang/julia#39391] opened 2021-01-25 18:00 UTC
```julia
myfunc(myvar::AbstractMyType{T})::Array{T} where {T} = myvar.myproperty
```
throws `UndefVarError: T not defined` but 

```julia
function myfunc(myvar::AbstractMyType{T})::Array{T} where {T}
  myvar.myproperty
end
```
works absolutely fine. Is there something I am missing?

**Comment by DhruvaSambrani** [comment] 2021-01-25 18:01
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Program Files\VSCodium\VSCodium.exe"
  JULIA_NUM_THREADS = 8

**Comment by DhruvaSambrani** [comment] 2021-01-25 18:06
Possibly related, 
```retone(myvar::AbstractMyType{T})::Int where {T} = 2```
Gives an unused T warning in VSCodium. Maybe it is parsing it differently than what I'm assuming it should. (as in the "correctly working" example above)

**Comment by JeffBezanson** [comment] 2021-01-25 18:19
Duplicate of #21847. Unfortunately this is just kind of an impossible syntax situation.

**Closed by JeffBezanson** 2021-01-25 18:19 UTC
