### ISSUE TITLE
Assertion error on `codeinst->max_world` when loading Parquet2

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#53586] opened 2024-03-04 11:16 UTC
```
julia> using Parquet2
Assertion failed: (jl_atomic_load_relaxed(&codeinst->max_world) == WORLD_AGE_REVALIDATION_SENTINEL), function jl_insert_backedges, file staticdata_utils.c, line 1258.

[69615] signal 6: Abort trap: 6
in expression starting at REPL[2]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
pthread_kill at /usr/lib/system/libsystem_pthread.dylib (unknown line)
abort at /usr/lib/system/libsystem_c.dylib (unknown line)
__assert_rtn at /usr/lib/system/libsystem_c.dylib (unknown line)
jl_insert_backedges at /Users/kristoffercarlsson/julia1.11/src/./staticdata_utils.c:1258 [inlined]
jl_restore_package_image_from_stream at /Users/kristoffercarlsson/julia1.11/src/staticdata.c:3653
jl_restore_incremental_from_buf at /Users/kristoffercarlsson/julia1.11/src/staticdata.c:3693 [inlined]
```

https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/0520b80_vs_bd47eca/Parquet2.primary.log

**Comment by vtjnash** [comment] 2024-03-08 20:11
I think I traced this down to basically this sort of type confusion:
```
julia> Val{(Val{T} where T>:Missing)} == Val{(Val{Union{Missing, T}} where T)}
false

julia> Val{(Val{T} where T>:Missing)} <: Val{(Val{Union{Missing, T}} where T)}
true

julia> Val{(Val{T} where T>:Missing)} >: Val{(Val{Union{Missing, T}} where T)}
true
```
There is a few more details to it, but that is some of the crux of it.

**Comment by vtjnash** [comment] 2024-03-12 18:21
Duplicate of https://github.com/JuliaLang/julia/issues/53109

**Closed by vtjnash** 2024-03-12 18:21 UTC
Labels: regression, types and dispatch
