### ISSUE TITLE
`sum` function marks a one dimensional array as 2 dimensions

### ISSUE THREAD

**Issue by affans** [JuliaLang/julia#27963] opened 2018-07-06 16:56 UTC
I came about this when using the `sum` function and `DataFrames()`. Consider the following short example.

```
Df = DataFrame()
M = reshape(rand(1:20, 16), (4, 4))
Msum = sum(M, 2)
Df[:c1] = Msum

Main> Df[:c1] = Msum
ERROR: ArgumentError: setindex!(::DataFrame, ...) only broadcasts scalars, not arrays
Stacktrace:
 [1] setindex!(::DataFrames.DataFrame, ::Array{Int64,2}, ::Symbol) at /Users/abmlab/.julia/v0.6/DataFrames/src/dataframe/dataframe.jl:372
 [2] eval(::Module, ::Any) at ./boot.jl:235
```

but if I do this 

```
tarr = zeros(Int64, 4)
Df[:c1] = tarr
```

It works. Both are one dimensional arrays with 4 elements, so what gives? I think its a problem with dimensions. See following

```
Main> Msum = sum(M, 2)
4×1 Array{Int64,2}:
 29
 29
 35
 41
```

so the `sum` function produces a one dimensional array but the type is set to `Array{Int64, 2}`. This is further seen by 

```
Main> size(Msum)
(4, 1)

Main> size(tarr)
(4,)
```

Is this a bug or is this expected behaviour. How can I change the dimension from the `sum` function to 1? The `reshape` function dosn't work. 

edit: `reshape` does work by running `reshape(Msum, (15, ))`

**Comment by JeffBezanson** [comment] 2018-07-06 17:09
See #16606
`reshape` or `squeeze` should work here.

**Comment by affans** [comment] 2018-07-07 20:08
What is the difference between an array that has size `(4, 1)` and `(4, )`?

**Comment by JeffBezanson** [comment] 2018-07-11 15:10
Size `(4,)` is a vector, size `(4, 1)` is a 1-column matrix. True, some sources in mathematics conflate these, but we treat them as different.

Closing as duplicate of #16606

**Closed by JeffBezanson** 2018-07-11 15:10 UTC
