### ISSUE TITLE
Pkg errors on registry update with 1.6.0-rc2 on Windows (regression vs rc1)

### ISSUE THREAD

**Issue by jebej** [JuliaLang/julia#40022] opened 2021-03-14 15:38 UTC
I have been using rc1 on two Windows computers without issues, but rc2 fails to update the registry with the following error (same on both computers). I still have rc1 installed and it works fine.

EDIT: I should have mentioned that I have `JULIA_PKG_SERVER = pkg.julialang.org` set.

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-rc2 (2021-03-11)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.6) pkg> up
    Updating registry at `C:\Users\Jeremy\.julia\registries\General`
┌ Warning: could not download https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/4829592030c9a379b640a8b446f95a2c78947499
└ @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:1152
ERROR: "C:\\Users\\Jeremy\\AppData\\Local\\Temp\\jl_WP1SFr\\Registry.toml": No such file
Stacktrace:
  [1] error(::String, ::String)
    @ Base .\error.jl:42
  [2] readstring
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\TOML\src\TOML.jl:21 [inlined]
  [3] parsefile(f::String)
    @ TOML C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\TOML\src\TOML.jl:43
  [4] read_registry(reg_file::String; cache::Bool)
    @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:1071
  [5] (::Pkg.Types.var"#94#97"{String, Pkg.Types.RegistrySpec, SubString{String}})(tmp::String)
    @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:1161
  [6] mktempdir(fn::Pkg.Types.var"#94#97"{String, Pkg.Types.RegistrySpec, SubString{String}}, parent::String; prefix::String)
    @ Base.Filesystem .\file.jl:729
  [7] mktempdir
    @ .\file.jl:727 [inlined]
  [8] update_registries(ctx::Pkg.Types.Context, regs::Vector{Pkg.Types.RegistrySpec}; force::Bool)
    @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:1148
  [9] up(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; level::Pkg.Types.UpgradeLevel, mode::Pkg.Types.PackageMode, update_registry::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:236
```

**Comment by KristofferC** [comment] 2021-03-14 16:12
My guess is that this is the same root cause as https://github.com/JuliaLang/julia/issues/40000.

What happens if you remove the registry and then do:

```
Pkg.update()
```

?

**Comment by jebej** [comment] 2021-03-14 16:34
> My guess is that this is the same root cause as #40000.

I'm not so sure that it is: I can't get the registry to update, but if I update it with rc1 then package installation works fine.



> What happens if you remove the existing registry and then do:
> 
> ```
> Pkg.update()
> ```
> 
> ?

It returns the below error (no backtrace for some reason?), though I can see in the temp folder that the registry is downloaded successfully....

```
(@v1.6) pkg> up
  Installing known registries into `C:\Users\Jeremy\.julia`
ERROR: could not download https://pkg.julialang.org/registry/23338594-aafe-5451-b93e-139f81909106/5613b56af4bb11b08a2d5fa4312ca0f87e73f042
```

**Comment by PaulSoderlind** [comment] 2021-03-14 16:36
in my case
```
installing known registries into `C:\Users\XXX\.julia`
     Cloning registry from "https://github.com/JuliaRegistries/General.git"
       Added registry `General` to `C:\Users\XXX\.julia\registries\General`
    Updating registry at `C:\Users\XXX\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
┌ Warning: failed to extract archive downloaded from https://pkg.julialang.org/package/02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a/afd2b541e8fd425cd3b7aa55932a257035ab4a70
└ @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:590
...
```

**Comment by jebej** [comment] 2021-03-14 16:38
> in my case

That seems like an even weirder issue since, if I understand correctly, it is using git to download the registry, but then fails on a pkg server operation...

**Comment by KristofferC** [comment] 2021-03-14 16:48
Closing in favour of https://github.com/JuliaLang/julia/issues/40024.

**Closed by KristofferC** 2021-03-14 16:48 UTC
