### ISSUE TITLE
Allocations in matrix view

### ISSUE THREAD

**Issue by rvignolo** [JuliaLang/julia#37888] opened 2020-10-05 14:11 UTC
Hi! I was wondering if these allocations are expected:

```julia
julia> mat = zeros(10,10);
julia> @btime view($mat, :);
  42.426 ns (2 allocations: 80 bytes)
```

I have discussed this on the Slack channel and people point out to me that:
>It is creating a new vector, just reusing the same backing memory. So the allocations are from the new vector's metadata:
```julia
julia> dump(view(zeros(2,2), :))
SubArray{Float64,1,Array{Float64,1},Tuple{Base.Slice{Base.OneTo{Int64}}},true}
  parent: Array{Float64}((4,)) [0.0, 0.0, 0.0, 0.0]
  indices: Tuple{Base.Slice{Base.OneTo{Int64}}}
    1: Base.Slice{Base.OneTo{Int64}}
      indices: Base.OneTo{Int64}
        stop: Int64 4
  offset1: Int64 0
  stride1: Int64 1
```
>check the parent attribute: It's a 1-D array

Here's my version info:
```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, haswell)
```

**Comment by simeonschaub** [comment] 2020-10-05 19:46
Is there a reason `view(::Array, ...)` calls `reshape`? The underlying issue seems to be the following:
```julia
julia> _reshape(x::Matrix{Float64}, len::Int) = ccall(:jl_reshape_array, Vector{Float64}, (Any, Any, Any), Vector{Float64}, x, (len,))
_reshape (generic function with 1 method)

julia> using BenchmarkTools
julia> mat = zeros(10,10);
julia> @btime _reshape($mat, 100);  34.108 ns (1 allocation: 64 bytes)
```
Perhaps `jl_reshape_array` could be changed to require less pointers?

**Comment by mbauman** [comment] 2024-11-06 16:52
Duplicate of #36313

**Closed by mbauman** 2024-11-06 16:52 UTC
Labels: performance, arrays
