### ISSUE TITLE
What does `zero` promise?

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#51478] opened 2023-09-27 13:05 UTC
The docstring of `zero` states:
> Get the additive identity element for the type of x

What does this mean? Presumably that `zero(x) + x == x`. But it's not quite clear.
For example,  `NaN + zero(NaN) != NaN`. Maybe it's a different meaning of equality that's meant, like `isequal`? But then we have `!isequal(-0.0 + zero(-0.0), -0.0)`. So zero doesn't seem to be right for `Float64` no matter the sense.

Also, `zero(1) !== zero(1.0)`. Does this imply that `typeof(zero(x)) == typeof(x)`? But this is not the case for `zero(1:1)::Vector{Int}`.

Related: #51475

**Comment by mbauman** [comment] 2023-09-27 13:18
Duplicate of #34003

**Closed by mbauman** 2023-09-27 13:18 UTC
