### ISSUE TITLE
cholfact does not free memory

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#11698] opened 2015-06-13 02:28 UTC
After reading [this post](https://groups.google.com/forum/#!topic/julia-users/4aSWQTJPFKc) on the mailing list I started bisecting and found that after https://github.com/JuliaLang/julia/commit/2ecb6d5c58e8 the function `cholfact` does no longer free its memory after use. It is a quite big commit but my guess is that some "finalizer command" is not sent to cholmod for it to release its internal memory.

The test script I used is the same one as in the mailing list:

```julia
function f(n)
  A = speye(n)
  fact = cholfact(A)
  for i=1:1000
    fact = cholfact(A)
  end
end
```

The memory allocations are not seen by `@time` so some external program like `htop` can be used. This is the status after running the test script a couple of times for `n = 10_000`:

![screenshot from 2015-06-13 04 25 59](https://cloud.githubusercontent.com/assets/1282691/8142661/52f5a70c-1184-11e5-88d6-d7e9ccaccaf6.png)

The memory is not reclaimed until Julia is exited.

CC @andreasnoack

**Comment by andreasnoack** [comment] 2015-06-13 03:15
Thanks for finding this. I'm not sure what the problem is. If I ask Julia to run the finalizer on a specific object and run the gc then all memory appears to be freed, i.e.
```jl
julia> A = sprandn(10000,10000,0.01);

julia> A = A + A' + 100I;

julia> F = cholfact(A)
Base.SparseMatrix.CHOLMOD.Factor{Float64,Int64}
type:          LLt
method: supernodal
maxnnz:          0
nnz:      48168362

julia> finalize(F)

julia> gc()
```
This causes Julia's memory usage to jump from 200MB to 2GB and back to 200MB again. @carnaval do you have any idea why the memory is not freed in @KristofferC's loop?

**Comment by KristofferC** [comment] 2015-06-13 11:37
Interestingly, at the commit https://github.com/JuliaLang/julia/commit/2ecb6d5c58e8 not even calling `finalize` and `gc` explicitly cleaned up any memory. However, after rebuilding on latest master it now cleans up like you said.

I guess for now, as a workaround you have to call `finalize` manually.

**Comment by timholy** [comment] 2015-06-13 12:03
If I were to guess, the reason it's not done automatically is that the memory is allocated by SuiteSparse. Hence it doesn't show up in the GC's accounting---each `Factor` object looks quite tiny as far as the GC is concerned.

If we want this situation to improve, we might need to wrap the `Factor` object (which mirrors SuiteSparse's structure) inside a type that also holds references to the buffers (using `pointer_to_array`).

**Comment by andreasnoack** [comment] 2015-06-13 12:12
But in @KristofferC's example, the memory is never freed even when `gc` is called explicitly so I'm wondering if the finalizers are not called for some reason.

The old solution was closer to what you suggest, but in 2ecb6d5 I decided that it was easier to let CHOLMOD handle the memory management by using finalizers.

**Comment by KristofferC** [comment] 2015-06-13 12:34
What guarantees does running `gc()` make? Does it always collect all objects with no refs and run potential finalizers on all of them? Or is it free to ignore objects it considers unimportant?

**Comment by carnaval** [comment] 2015-06-13 17:44
This is a lack of memory pressure. The gc has no way to know how much memory was allocated so it prefers just doing nothing. You can use the jl_gc_counted_* family to apply memory pressure when allocating using an external library which will be freed by a finalizer. See bigints in base for an example.

Its fine if you only use an approximation of how much memory was allocated but be careful to match the counted_alloc with a counted_free of the same size.

**Comment by KristofferC** [comment] 2015-06-13 19:33
I am not very familiar with Cholmod but the manual mentions `size_t memory_inuse ; /* current memory usage in bytes */` which we should be able to query and use?

**Comment by andreasnoack** [comment] 2015-06-13 20:29
I'm investigating this right now and I think I know what the problem is. There is a genuine leak here because CHOLMOD is not called correctly after my change in 2ecb6d5. The problem is that `cholmod_start` cannot be called more than once so the way the common structs are provided right now has to change. I'll prepare a fix.

**Comment by ViralBShah** [comment] 2015-06-14 09:54
Will this solve the issue, or will the lack of memory pressure still exist, since Julia does not see the full memory utilization of the library? Is there a way to tell the Julia GC that the real memory allocation is much higher?

**Comment by KristofferC** [comment] 2015-06-14 13:42
@carnaval mentioned the `jl_gc_counted_malloc` and company defined here: https://github.com/JuliaLang/julia/blob/84f14d1e6a6650f75506e5ec9b6d9bcdd64e168c/src/gc.c#L2708

These are used by BigInts here https://github.com/JuliaLang/julia/blob/539c818c4e3afc3fb849135675aaf3d72a6f23f2/base/gmp.jl#L64

However, if I understand it correctly these are functions that actually used to do allocations themselves. What we want to do is just to inform the gc that the `Factor` object actually is quite large. Maybe @timholy's method (IIUC) of having the actual arrays in the type is the way to go.

**Comment by ViralBShah** [comment] 2015-06-14 14:34
I originally thought @carnaval 's comment was for future work. Now that you mention it, I do recollect the similar situation with BigInts.

**Comment by carnaval** [comment] 2015-06-14 16:01
@KristofferC of course you're right, the bigint stuff also allocates the memory. Had a brain freeze there, I was thinking about jl_gc_count_allocd ( https://github.com/JuliaLang/julia/blob/84f14d1e6a6650f75506e5ec9b6d9bcdd64e168c/src/gc.c#L965 ) but it does not have a free version since for now it is only used for arrays when ownership was transferred to us.

You can add a jl_gc_count_free but it would indeed be easier to just use pointer_to_array with own=true if you can let the gc do the freeing.

**Comment by andreasnoack** [comment] 2015-06-14 16:51
The lacking memory pressure is a separate issue. We can use the Julia gc tracked allocator functions in CHOLMOD with a little care although I don't see a `jl_gc_counted_calloc` which might be necessary. I've tried this and it seems to work, but it doesn't solve the problem here. The real issue is the way we call `cholmod_start`. I couldn't find `cholmod_core.c` online, so I'll cite it here:
```
Do not call this routine [cholmod_start] after any other CHOLMOD routine (except
 * cholmod_finish, to start a new CHOLMOD session), or a memory leak will
 * occur.
```

I also just remembered why I decided not to use Julia allocated buffers for CHOLMOD. Quite a few functions in the library resizes the buffers which caused segfaults.

**Comment by tkelman** [comment] 2015-06-14 18:52
Does `cholmod_start` need to be specially handled by a module `__init__` method then?

**Comment by andreasnoack** [comment] 2015-06-14 19:04
Yes. I have almost a fix ready and that is exactly how I did it.

**Comment by KristofferC** [comment] 2015-06-23 23:57
I am still having problems here it seems.

```julia
function f(n)
         A = speye(n)
         fact = cholfact(A)
         for i=1:1000
           fact = cholfact(A)
         end
       end

f(60_000)
gc()
```

gives:

![screenshot from 2015-06-24 01 54 01](https://cloud.githubusercontent.com/assets/1282691/8319847/e89af7f2-1a13-11e5-8e37-f29c30e1f3b4.png)

Calling `finalize` explicitly on `fact` in the loop reduces memory consumption but does not completely fix it.
![screenshot from 2015-06-24 01 56 53](https://cloud.githubusercontent.com/assets/1282691/8319888/4c6760ae-1a14-11e5-81c8-4e75b8871cf3.png)

**Comment by andreasnoack** [comment] 2015-06-24 04:04
Yes. You are right. It seems to be much less now, but something is still leaking. I'll look more into it.

**Comment by andreasnoack** [comment] 2015-07-05 01:55
I believe this is fixed by #11877. @KristofferC, please take a look and see if you still see a problem, but be aware that there might be [other things](#10159) leaking.

**Comment by yuyichao** [comment] 2015-07-05 02:01
@andreasnoack Seems that github treat `#<number>` in the link as tag instead of issue number.

**Comment by KristofferC** [comment] 2015-07-05 02:59
I am on vacation and will not have access to a computer for a couple of weeks. I can test when I am back. If I remember correctly the memory leak was proportional to the size of the matrix being factorised which makes me believe it is something with cholmod.

**Comment by andreasnoack** [comment] 2015-07-05 03:02
Was that on Linux? I've only tried on Mac so far.

**Comment by KristofferC** [comment] 2015-07-05 03:24
Yes Linux 64 bit.

**Comment by andreasnoack** [comment] 2015-07-07 10:54
I've just tried on Ubuntu 15.04 and indeed it appears that there is a significant leak there. It is really puzzling because I've confirmed that memory is not leaking on Mac and Windows. I'll look further into this.

**Comment by KristofferC** [comment] 2015-07-07 15:03
That is quite surprising, indeed. Is there still a (smaller) leak when you explicitly call `finalize` on the factor object in the loop?

**Comment by andreasnoack** [comment] 2015-07-10 00:15
Okay, I learned something new today: memory is often not released to the system. According to the [libc documentation](http://www.gnu.org/software/libc/manual/html_node/Freeing-after-Malloc.html):

"Occasionally, free can actually return memory to the operating system and make the process smaller. Usually, all it can do is allow a later call to malloc to reuse the space. In the meantime, the space remains in your program as part of a free-list used internally by malloc."

That fits well with the behavior here so I'll close.

**Closed by andreasnoack** 2015-07-10 00:15 UTC
Labels: sparse
