### ISSUE TITLE
Can't drop positional argugment in function with keyword arguments

### ISSUE THREAD

**Issue by gaurav-arya** [JuliaLang/julia#48986] opened 2023-03-12 16:06 UTC
This is fine
```
julia> f(_) = 3
f (generic function with 1 method)
```
but this is not
```
julia> g(_; x) = 3
ERROR: syntax: all-underscore identifier used as rvalue around REPL[13]:1
Stacktrace:
 [1] top-level scope
   @ REPL[13]:1
```
Version info:
```
julia> versioninfo()
Julia Version 1.9.0-beta3
Commit 24204a73447 (2023-01-18 07:20 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, tigerlake)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

**Comment by simeonschaub** [comment] 2023-03-12 17:34
Duplicate of #32727

**Closed by simeonschaub** 2023-03-12 17:34 UTC
