### ISSUE TITLE
Use of variables defined inside if-else can poison inference

### ISSUE THREAD

**Issue by thchr** [JuliaLang/julia#42996] opened 2021-11-08 01:58 UTC
Consider the following function `f`:
``` jl
function f()
    if rand(Bool)
        idxs = [[1,2],[1,2,3]]
    else
        idxs = [[1,2],[1,2,3]]
    end

    return idxs
end
```
As well as the functionally identical variation `g`:
```jl
function g()
    if rand(Bool)
        idxs = [[1,2],[1,2,3]]
    else
        idxs = [[1,2],[1,2,3]]
    end

    [idxs[j] for j in 1:length(idxs)]
    return idxs
end
```
Here, `f` will infer perfectly fine - but adding an iterator over `idxs` in `g` (which, notably, is not used for anything) will cause inference to give up, inferring `Any` as return value. Effectively, using the iterator poisons everything.

Defining and using variables this way is definitely an anti-pattern (and can be avoided in several ways) but since`f` works just fine (and e.g., is not disallowed) it struck me as unintended that `g` does not.

**Comment by oscardssmith** [comment] 2021-11-08 02:03
This is a bug. Can reproduce on master.

**Comment by simeonschaub** [comment] 2021-11-08 02:35
This is just another duplicate of #15276.

**Closed by simeonschaub** 2021-11-08 02:35 UTC
Labels: bug, inference

**Comment by oscardssmith** [comment] 2021-11-08 02:40
@simeonschaub how? This doesn't have a closure.

**Comment by simeonschaub** [comment] 2021-11-08 02:47
Untyped array comprehensions are lowered using closures

**Comment by thchr** [comment] 2021-11-08 03:25
Okay, reading parts of #15276, I guess I can see how this is related to capturing in closures if comprehensions are lowered via closures: thanks!

One thing I don't understand though is what the role of the if-else clause is here? E.g., the following variation infers fine (going by memory):
```jl
function h()
    idxs = Vector{Int}[]
    if rand(Bool)
        append!(idxs, [[1,2],[1,2,3]])
    else
        append!(idxs, [[1,2],[1,2,3]])
    end
    [idxs[j] for j in 1:length(idxs)]
    return idxs
end
```

**Comment by simeonschaub** [comment] 2021-11-08 06:15
What matters is that there are multiple assignments to a variable that is captured by the closure. In your second example, `idxs` is only assigned once and then only ever gets mutated, so the type of `idxs` can never change.
In the original example, the assignments do happen to be inside mutually exclusive branches, so theoretically lowering could actually figure out that there's no need to box `idxs` in this particular case. I suspect this kind of analysis is probably sufficiently nontrivial to implement in our current logic that we might as well just try to come up with a more general solution to #42996-like issues instead.
