### ISSUE TITLE
Do not truncate zip inputs

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#20499] opened 2017-02-07 17:12 UTC
Like Python, Julia's `zip(a, b)` ignores the tail end of its input sequences when they are of unequal length (but see #17928). I've yet to encounter a problem where I wanted that behavior, and I would much prefer seeing an error when the inputs are of unequal length. Are there applications where truncation is very convenient?

**Comment by StefanKarpinski** [comment] 2017-02-07 17:57
I believe that truncation is generally useful for combining infinite iterators with finite ones. I do agree that if two finite iterators have different lengths, an error is better.

**Comment by JeffBezanson** [comment] 2017-02-07 20:22
Duplicate of #17928?

**Comment by StefanKarpinski** [comment] 2017-02-08 14:09
I would close that one in favor of this since that was a specific confusing case, whereas this is explicitly a decision issue about whether the underlying general behavior is a good idea or not.

**Comment by stevengj** [comment] 2017-04-11 15:33
A similar issue arises from `Generator(f, iters...)`, which [on discourse](https://discourse.julialang.org/t/blog-post-loop-fusion-and-vectorization-in-julia-0-6/1634/26?u=stevengj) was noted to cause silent truncation for `map(+, (1,2), 3)`.

My gut feeling is that if all the iterators have lengths (`iteratorsize(itr)::Union{HasLength,HasShape}`), then a length mismatch should be an exception.

**Comment by StefanKarpinski** [comment] 2017-04-12 22:25
I think that we should be even stricter and *only* allow truncation of infinite streams. Or does !haslength mean that a stream is infinite? I would interpret it as having unknown length, but I may be misunderstanding the trait.

**Comment by JeffBezanson** [comment] 2017-04-12 22:55
No, you're right, !haslength just means the length is unknown. But what if you want to do something like zip the line iterators of two files, deciding whether to stop as you go? That should be allowed.

**Comment by StefanKarpinski** [comment] 2017-04-13 14:59
Yes, fair enough.

**Comment by cstjean** [comment] 2017-04-15 12:37
I feel like providing both `zip` and `truncating_zip` is a cleaner, simpler solution than special-casing `zip`'s behaviour.

**Comment by ararslan** [comment] 2017-07-13 20:39
It might be nice to provide a keyword argument to `zip` that dictates whether to truncate to a common length. For example, `zip(1:10, 1:3, trunc=true)` would iterate over `(1,1), (2,2), (3,3)` and `zip(1:10, 1:3, trunc=false)` would throw an error because the inputs are not the same length.

Since we allow isbits values for type parameters, perhaps we could even parameterize `Zip` based on whether it should truncate.

Anyway, just an idea.

**Comment by StefanKarpinski** [comment] 2017-07-18 18:08
I would spell that keyword out fully, otherwise it kind of looks like you want to apply the `trunc` function to every value (which makes no sense).=, i.e. `zip(1:10, 1:3, truncate=true)`. Some gut feeling tells me that it would be better to have a function which does the truncation for you, but then that function ends up just being a truncating `zip`, at which point having a keyword seems better.

**Comment by nalimilan** [comment] 2018-01-16 21:52
I think we should fix this for 0.7. See #25583 for a problematic illustration.

**Comment by JeffBezanson** [comment] 2018-01-17 00:21
I believe this is only a problem with `reverse`. If `reverse` is the problematic case, it should throw the error instead of punishing all users of `zip` (such as myself).

**Comment by stevengj** [comment] 2018-01-17 16:59
My feeling is that both `zip` and `reverse` should have checks.

`zip` should throw an error for zipping `HasLength` iterators of unequal lengths, but should allow infinite or unknown lengths to truncate.

`reverse` should also throw an error for `zip` of infinite or unknown lengths.

**Comment by JeffBezanson** [comment] 2018-01-17 17:17
I continue to find it hard to see why truncating zip is a problem. Maybe part of the reason is that iterators are inherently lazy; by design you can take as much or as little from an iterator as you want. So it seems weird for it to be an error not to consume all of an iterator.

This thread is very short on real, compelling arguments. I see an "I would much prefer" and a "gut feeling", and not much more than that. So I remain opposed to this change.

**Comment by JeffBezanson** [comment] 2018-01-18 02:12
In my view, that's because `hcat` explicitly operates on the shapes of arguments, so they have to match in a certain way. But iterators just pull a sequence of values.

**Comment by StefanKarpinski** [comment] 2018-01-18 19:35
Triage: we're already getting late in the game here and there are significant design and feasibility questions about how to even make this require same length without breaking things. Python and Lisp have the same truncating behavior as we have now, so this seems like it can't be that bad.

**Closed** 2018-01-18 19:35 UTC
Labels: collections, decision

**Comment by PallHaraldsson** [comment] 2021-07-11 18:56
>Python and Lisp have the same truncating behavior as we have now, so this seems like it can't be that bad.

FYI: Python considers it a mistake (and will add optional strict):
https://www.python.org/dev/peps/pep-0618/

I saw in other issue: "Triage decided not to throw an error when zip is passed arguments with different lengths", I guess referring to Jeff removing triage, and Stefan closing. It's not too late to do as Python, optional, but is too late to error different lengths?
