### ISSUE TITLE
add a way to test whether exported symbols are documented

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#51174] opened 2023-09-04 12:45 UTC
As [discussed on discourse](https://discourse.julialang.org/t/check-if-a-function-has-a-docstring/103489), it would be nice to have a (documented) way to test whether all exported symbols in a module have docstrings.  Currently, this seems to require undocumented internals?

Something like:
```jl
# hasdoc should go in Base.Docs; might also be accomplished by refactoring Base.Docs.doc somehow
using  Base.Docs: Binding, defined, getdoc, resolve, meta, modules, aliasof
hasdoc(mod::Module, sym::Symbol) = hasdoc(Base.Docs.Binding(mod, sym))
function hasdoc(binding::Binding, sig::Type = Union{})
    defined(binding) && !isnothing(getdoc(resolve(binding), sig)) && return true
    for mod in modules
        dict = meta(mod; autoinit=false)
        !isnothing(dict) && haskey(dict, binding) && return true
    end
    alias = aliasof(binding)
    return alias == binding ? false : hasdoc(alias, sig)
end

# possible function for the Test module
function check_documented(mod::Module)
    nodocs = filter!(sym -> !hasdoc(mod, sym), names(mod))
    isempty(nodocs) || error("missing docstrings in $mod: $nodocs")
end
```
For example, this catches some missing docstrings in `Base` and several standard libraries:
```jl
julia> check_documented(Base)
ERROR: missing docstrings in Base: [:CanonicalIndexError, :CapturedException, :InvalidStateException]

julia> check_documented(LinearAlgebra)
ERROR: missing docstrings in LinearAlgebra: [:ColumnNorm, :LAPACKException, :NoPivot, :RankDeficientException, :RowMaximum, :RowNonZero, :copy_transpose!]

julia> check_documented(Markdown)
ERROR: missing docstrings in Markdown: [Symbol("@doc_str"), Symbol("@md_str"), :html, :latex]

julia> check_documented(Pkg)
ERROR: missing docstrings in Pkg: [Symbol("@pkg_str"), :PKGMODE_MANIFEST, :PKGMODE_PROJECT, :PRESERVE_ALL, :PRESERVE_ALL_INSTALLED, :PRESERVE_DIRECT, :PRESERVE_NONE, :PRESERVE_SEMVER, :PRESERVE_TIERED, :PRESERVE_TIERED_INSTALLED, :Pkg, :PreserveLevel, :Registry, :UPLEVEL_MAJOR, :UPLEVEL_MINOR, :UPLEVEL_PATCH]
```

**Comment by Krastanov** [comment] 2023-09-04 14:51
dupe of the issue submitted just before this one https://github.com/JuliaLang/julia/issues/51169 (but the issue description here is quite a bit more detailed)

**Comment by jariji** [comment] 2023-09-04 17:21
A docstring is the place for showing the interface of a function, regardless of whether the caller is inside or outside of the same module. It is useful both for writing callers and for modifying the function itself.

Therefore I prefer to check that all functions have docstrings, not just public ones.

**Comment by stevengj** [comment] 2023-09-05 13:43
> Therefore I prefer to check that all functions have docstrings, not just public ones.

Sure, for people that want this, that could be a keyword to `check_documented` (mirroring the `all` keyword argument in [`names`](https://docs.julialang.org/en/v1/base/base/#Base.names)).

The main thing is to export a `hasdoc` function, and then you can check whatever you want (e.g. require that all non-underscored symbols have docstrings, or all functions beginning with the letter "d").

**Comment by vtjnash** [comment] 2023-09-05 19:38
This possibly should be an issue for https://github.com/JuliaTesting/Aqua.jl, which seems to be the goto place for better quality tests over what is in Test.

**Comment by Krastanov** [comment] 2023-09-05 20:37
Documenter also has some checks along these lines that can be part of CI when `strict=true` is set. It might make sense to host that functionality there.

**Comment by jariji** [comment] 2023-09-05 20:48
There is no way to tell programmatically if a function is API without testing whether it has documentation and that [will remain true](https://github.com/JuliaLang/julia/pull/50105#issuecomment-1696000690) after `public` is added. Determining whether a function is part of API seems like a sufficiently basic task that it seems more appropriate to include it with Julia.

**Comment by Seelengrab** [comment] 2023-09-07 07:34
See also https://github.com/JuliaLang/julia/issues/26919 and https://github.com/JuliaLang/julia/issues/31202. Both have a (now broken) script for this.

**Comment by stevengj** [comment] 2023-09-08 14:45
Regardless of where the tests belong (Test, Aqua, etcetera), I think `Base.Docs` needs provide a `hasdoc` function or similar, because its implementation is closely tied to `Base.Docs` internals.

**Comment by jariji** [comment] 2023-11-12 20:18
It seems like the `hasdoc` function can be added separately from any `check_` functionality. @stevengj is your `hasdoc` ready for a PR?

**Comment by stevengj** [comment] 2023-11-12 23:48
Yes, someone should go ahead and make a PR with the `hasdoc` implementation and a test.  Additional refinement can happen in the PR.

**Closed** 2023-12-05 18:24 UTC
Labels: good first issue, docsystem, testsystem, feature

**Comment by jariji** [comment] 2023-12-05 19:11
Not quite done - that PR adds `Docs.hasdoc` but we still need

```jl
function check_documented(mod::Module)
    nodocs = filter!(sym -> !hasdoc(mod, sym), names(mod))
    isempty(nodocs) || error("missing docstrings in $mod: $nodocs")
end
```

in `Docs` or `Test`. @Seelengrab can you explain why you prefer `check_documented` in `Docs`  rather than `Test`?

**Comment by Seelengrab** [comment] 2023-12-05 20:37
Why should `Test` depend on `Docs` for something that is purely `Docs` functionality? Either having that in `Docs` or in an extension of `Test` weakly depending on `Docs` would be fine IMO.
