### ISSUE TITLE
Julia 1.10 LLVM Error

### ISSUE THREAD

**Issue by pxl-th** [JuliaLang/julia#50020] opened 2023-05-31 17:55 UTC
Observed initially in NNlib softmax implementation:
```julia
julia> versioninfo()
Julia Version 1.10.0-DEV.1406
Commit ca3270b06f4 (2023-05-31 09:33 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 5800X 8-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
  Threads: 5 on 16 virtual cores

julia> x = ones(Float16, 5);

julia> @fastmath reduce(max, x; dims=Colon(), init=float(Float16)(-Inf))
LLVM ERROR: Cannot select: 0x1480a08: v16f16 = X86ISD::FMAX nnan ninf nsz arcp contract afn reassoc 0x1499ca0, 0x146c370, array.jl:938 @[ reduce.jl:60 @[ reduce.jl:48 @[ reduce.jl:44 ] ] ]
  0x1499ca0: v16f16,ch = CopyFromReg 0x11bdf18, Register:v16f16 %9, array.jl:938 @[ reduce.jl:60 @[ reduce.jl:48 @[ reduce.jl:44 ] ] ]
    0x1474a80: v16f16 = Register %9
  0x146c370: v16f16,ch = CopyFromReg 0x11bdf18, Register:v16f16 %10, array.jl:938 @[ reduce.jl:60 @[ reduce.jl:48 @[ reduce.jl:44 ] ] ]
    0x146be28: v16f16 = Register %10
In function: julia_mapfoldl_impl_136

[10579] signal (6.-6): Aborted
```

**Comment by gbaraldi** [comment] 2023-05-31 18:10
Duplicate of https://github.com/JuliaLang/julia/issues/49907

**Closed** 2023-05-31 18:14 UTC
