### ISSUE TITLE
“basename” does not support gbk encoding

### ISSUE THREAD

**Issue by zpcpi** [JuliaLang/julia#48648] opened 2023-02-11 06:46 UTC
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)      
  CPU: 8 × Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, haswell)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =

code
`path = "d:\\\\AppData\\\\Local\\\\Programs\\\\Julia-1.8.5\\\\bin\\\\libLLVM-13jl.dll"
basename(path) # "libLLVM-13jl.dll"

path = String(Base.libllvm_path()) # "d:\\\\Users\\\\\\xc5\\xf4\\xb3\\xcc\\\\AppData\\\\Local\\\\Programs\\\\Julia-1.8.5\\\\bin\\\\libLLVM-13jl.dll"
basename(path) # ERROR: type Nothing has no field captures
`

Base.libllvm_path()
GBK: "d:\\\\Users\\\\鹏程\\\\AppData\\\\Local\\\\Programs\\\\Julia-1.8.5\\\\bin\\\\libLLVM-13jl.dll"

**Comment by melonedo** [comment] 2023-02-11 06:57
Probably caused by #45126, since `basename` needn't support illegal encodings.

**Comment by vtjnash** [comment] 2023-02-12 22:44
We may need to ensure utf8 is disabled for path regexes (or all ascii-only regexes which don't use character classes?)

**Comment by vtjnash** [comment] 2023-02-14 21:47
fixed by https://github.com/JuliaLang/julia/pull/45127

**Closed by vtjnash** 2023-02-14 21:47 UTC
Labels: bug, filesystem
