### ISSUE TITLE
Regression in error message for `const x`

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#45075] opened 2022-04-24 16:14 UTC
Julia `master` (and 1.8):
```
julia> const x
ERROR: `body` expression must terminate in `return`. Use `block` instead.
```

Julia 1.7:
```
julia> const x
ERROR: syntax: expected assignment after "const"
Stacktrace:
 [1] top-level scope
```

**Comment by simeonschaub** [comment] 2022-04-24 16:16
Duplicate of https://github.com/JuliaLang/julia/issues/45024

**Closed by simeonschaub** 2022-04-24 16:16 UTC
