### ISSUE TITLE
Set environment for remote workers?

### ISSUE THREAD

**Issue by ericaddison** [JuliaLang/julia#24535] opened 2017-11-08 16:40 UTC
Hello Julia-ers!

When adding remote workers with `addprocs()`, I would really love to be able to send my current working environment along for the new Julia workers. Currently this does not happen for workers added using an `SSHManager`, though local workers do seem to inherit the same environment. 

After browsing the repo, I think that this behavior could (gulp) easily be added by extending the code in [managers.jl](https://github.com/JuliaLang/julia/blob/0d7248e2ff65bd6886ba3f003bf5aeab929edab5/base/distributed/managers.jl#L177) to set all, or some specified subset, of the current environment variables in the same way that `JULIA_WORKER_TIMEOUT` is set. Of course that might not be the default behavior, but maybe an option? Maybe something like (but not identical to):
```julia
    # the default worker timeout
    tval = haskey(ENV, "JULIA_WORKER_TIMEOUT") ?
        `export JULIA_WORKER_TIMEOUT=$(ENV["JULIA_WORKER_TIMEOUT"])\;` : ``

    envvals = map(key->`export $(key)=$(ENV[key])\;`, keys(ENV))

    # Julia process with passed in command line flag arguments
    cmd = `cd $dir '&&' $tval $envvals $exename $exeflags`
```

Is this a reasonable thing to propose? Please let me know if this is a terrible idea! Otherwise I will be happy to attempt to implement this. I just wanted to float the idea here first.

Thanks!

**Comment by amitmurthy** [comment] 2017-11-22 08:50
I think this should be done via a `SSHManager` specific keyword arg to `addprocs`. `addprocs(....; env=[])`, i.e., the default would be no envvar set explicitly on the workers.

**Comment by ericaddison** [comment] 2017-11-22 14:35
That makes sense. I have a functioning implementation at work ... just trying to jump through the right hoops to release it :)

**Comment by NeonNeon** [comment] 2019-03-12 12:16
Any update on this issue?

**Comment by ericaddison** [comment] 2019-03-12 16:54
Hi! Unfortunately I was not able to get approval to release my work before I left my job at the time. There is some small chance that @samtkaplan may have some info...

**Comment by JeffBezanson** [comment] 2019-12-03 23:32
Duplicate of #18074

**Closed by JeffBezanson** 2019-12-03 23:32 UTC
Labels: parallel

**Comment by mgkuhn** [comment] 2021-07-10 10:02
For the record: Julia 1.6 added a new `env=["JULIA_DEPOT_PATH"=>"/depot", ...]` keyword argument to [Distributed.addprocs](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.addprocs) that solves this issue.
