### ISSUE TITLE
In function short form, where clause is captured by return type instead of the whole sig

### ISSUE THREAD

**Issue by o314** [JuliaLang/julia#33386] opened 2019-09-25 17:05 UTC
## Situation

Let's consider the surface expr obtained when parsing short function forms

```julia
f(x::A) = body                          # (= (call f (:: x A)) body)
f(x::A, y::B) = body                    # (= (call f (:: x A) (:: y B)) body)

f(::A) = body                           # (= (call f (:: A)) body)
f()::A = body                           # (= (:: (call f) A) body)
f(::A)::B = body                        # (= (:: (call f (:: A)) B) body)

f(x::A) where A = body                  # (= (where (call f (:: x A)) A) body)
f()::A where A = body                   # (= (:: (call f) (where A A)) body)
f(::A)::B where A = body                # (= (:: (call f (:: A)) (where B A)) body)
f(::A)::B where B = body                # (= (:: (call f (:: A)) (where B B)) body)
f(::A)::B where {A,B} = body            # (= (:: (call f (:: A)) (where B A B)) body)
```

As soon as we add a return type and a where clause, the return type predates the where clause.
Statistically, it seems that the where clause can concern either input type, io type more frequently  that only output type.

If we want to obtain a where clause on the whole sig, we have to parenthesis things

```julia
(f()::A) where A = body                 # (= (where (:: (call f) A) A) body)
(f(::A)::B) where B = body              # (= (where (:: (call f (:: A)) B) B) body)
(f(::A)::B) where {A,B} = body          # (= (where (:: (call f (:: A)) B) A B) body)
```

Harder to read and understand.

Also notice that it does not follow the default for the long form function

```julia
# long form, where above call by default
function f(::A)::B where {A,B}; body end    # (function (where (:: (call f (:: A)) B) A B) body)

# short form, where above call if parenthesised otherwise under
(f(::A)::B) where {A,B} = body              # (= (where (:: (call f (:: A)) B) A B) body)
f(::A)::B where {A,B} = body                # (= (:: (call f (:: A)) (where B A B)) body)
```

## Proposal

let's the where clause being bound to the whole sig by default when both return type and where clause are present.

**Comment by JeffBezanson** [comment] 2019-09-27 04:42
Duplicate of #21847 and #31560.

**Closed** 2019-09-27 04:43 UTC
