### ISSUE TITLE
MKL building troubles on v1.2.0

### ISSUE THREAD

**Issue by kiranshila** [JuliaLang/julia#33691] opened 2019-10-27 16:17 UTC
I apologize in advance that this issue seems to be beaten to death, but I believe building Julia with MKL is still rather broken, at least on MacOS.

My am running MacOS Catalina, although it also didn't work on Mavericks.

## How to reproduce
Install the latest MKL from Intel - then clone Julia - then checkout v1.2.0
```bash
git clone git://github.com/JuliaLang/julia.git
cd julia
git checkout v1.2.0
```
As per the MKL instructions, I source the environment variables from MKL. On macOS, this install is in the following location.
```bash
source /opt/intel/bin/compilervars.sh intel64
```
Finally, I make the `Make.user` file and build
```bash
echo "USE_INTEL_MKL = 1" >> Make.user
make -j4
```
So, the build gets reasonably far, but quits here

```make
Got SONAMES of
    PERL base/pcre_h.jl
    CC usr/lib/libccalltest.dylib
    CC usr/lib/libllvmcalltest.dylib
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    CC src/support/hashing.o
make[1]: *** [/Users/kiranshila/Desktop/Projects.nosync/Julia/julia/usr/lib/julia/libmkl_rt.dylib] Error 1
make[1]: *** Waiting for unfinished jobs....
```
It seems there is a problem with usr/lib/julia/libmkl_rt.dylib
I look at that directory and it is completely empty
```bash
ls usr/lib/julia
```

## How I got it to build
I read in another issue that I need to source a different file, so I tried repeating the above steps with this modification to the call to `source`
```bash
source /opt/intel/mkl/bin/mklvars.sh intel64
```
But I get the exact same issue

I then tried just symlinking the missing libs directly into usr/lib/julia from a fresh clone using the source command from the instructions
```bash
cd ..
rm -rd julia
git clone git://github.com/JuliaLang/julia.git
cd julia
git checkout v1.2.0
source /opt/intel/bin/compilervars.sh intel64
echo "USE_INTEL_MKL = 1" >> Make.user
mkdir -p usr/lib/julia # This didn't exist yet in fresh clone
ln -s /opt/intel/mkl/lib/libmkl_rt.dylib usr/lib/julia/libmkl_rt.dylib
make -j4
```
This gets past the first roadblock as now that library is visible. Now, after the build steps get to building with Julia, I get this error during `Generating precompile statements...`
```julia
error during bootstrap:
LoadError("sysimg.jl", 16, LoadError("/Users/kiranshila/Desktop/Projects.nosync/Julia/julia/usr/share/julia/stdlib/v1.2/SuiteSparse/src/SuiteSparse.jl", 24, LoadError("/Users/kiranshila/Desktop/Projects.nosync/Julia/julia/usr/share/julia/stdlib/v1.2/SuiteSparse/src/umfpack.jl", 66, ErrorException("error compiling top-level scope: could not load library \"libsuitesparse_wrapper\"\ndlopen(libsuitesparse_wrapper.dylib, 1): Library not loaded: @rpath/libirc.dylib\n  Referenced from: /Users/kiranshila/Desktop/Projects.nosync/Julia/julia/usr/lib/libcholmod.3.0.13.dylib\n  Reason: image not found"))))
```
Which to me reads that libirc.dylib isn't found. I found it and symlinked it in as before
```bash
ln -s /opt/intel/compilers_and_libraries_2019.5.281/mac/compiler/lib/libirc.dylib usr/lib/julia/libirc.dylib
```
Finally Julia built! Checking the build
```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

julia> LinearAlgebra.versioninfo()
BLAS: libmkl_rt
LAPACK: libmkl_rt
```

So, it looks like it worked, but that was many hoops to jump through. The issue then is how can we fix the build scripts such that the symlinking isn't broken so others on MacOS don't have to spend a few days digging and troubleshooting.

**Comment by ViralBShah** [comment] 2019-10-27 16:20
Did you try using MKL.jl?

**Comment by kiranshila** [comment] 2019-10-27 16:37
@ViralBShah I did not as I am interested in building from source.

**Comment by ViralBShah** [comment] 2019-10-27 16:40
Yes, but we are hoping to move in the general direction of MKL.jl. You can still build Julia from source, and then use MKL.jl.

**Comment by kiranshila** [comment] 2019-10-27 16:45
That would indeed be a more portable solution. Thanks Viral for looking into this!

**Comment by kiranshila** [comment] 2019-10-27 16:48
It might be beneficial to update the build docs to suggest people try MKL.jl first if that is their sole reason for building from source.

**Comment by ViralBShah** [comment] 2019-10-27 17:25
I just tried out MKL.jl on mac, and it seemed to work fine.

**Comment by kiranshila** [comment] 2019-10-27 17:50
Yep, just tried and it works for me as well. This seems like the solution.

The same problem occurs however when trying to use Intel's libm, where all the libraries are missing from usr/lib/julia. I think there is a problem with the symlinking in the makefile. The following commands fix those as well.

```bash
ln -s /opt/intel/compilers_and_libraries_2019.5.281/mac/compiler/lib/libimf.dylib usr/lib/julia/libimf.dylib
ln -s /opt/intel/compilers_and_libraries_2019.5.281/mac/compiler/lib/libintlc.dylib usr/lib/julia/libintlc.dylib
```

**Comment by ViralBShah** [comment] 2019-10-29 02:59
The use of MKL.jl is documented in the FAQ: https://github.com/JuliaLang/julia/pull/31570/files

**Comment by crstnbr** [comment] 2020-04-18 08:50
I can confirm that the instructions by @kiranshila work for Julia 1.4.0 on macOS Catalina 10.15.4.

However, I'm a bit worried by messages like this during the build process:
```
ld: warning: directory not found for option '-L/opt/intel/compilers_and_libraries_2020.1.216/mac/mkl/lib/intel64'
```
The intel64 subfolder doesn't exist in MKL for Mac.

It really is a pity that building with MKL is much more bumpy than on linux. While MKL.jl is great, since I need to compile Julia from source anyways (for Intel LIBM and JIT Flags etc) I'd much prefer integrating MKL directly.

**Comment by ViralBShah** [comment] 2020-04-20 13:08
I think this issue probably needs to be filled in mkl.jl.

**Comment by KristofferC** [comment] 2020-04-20 13:25
Why? This is about building Julia itself with MKL and nothing about using MKL.jl:

> While MKL.jl is great, since I need to compile Julia from source anyways (for Intel LIBM and JIT Flags etc) I'd much prefer integrating MKL directly.

**Comment by ViralBShah** [comment] 2020-04-20 13:27
The ld warning is not.

**Comment by kiranshila** [comment] 2020-04-23 14:03
To be honest, even on a fresh copy of mkl and julia on Linux, I can't get Julia+MKL to build. It looks like Intel updated their linker script, and it doesn't even run on my system. I have found some people's script to fix it, but I gave up a while ago and just use MKL.jl.

I've been recommending all my friends do the same, because fixing all the linker errors is more hassle than its worth.

**Comment by ViralBShah** [comment] 2020-04-23 14:10
Note that packages will still use OpenBLAS_jll and OpenBLAS32_jll. We do not yet have a good way to make every BLAS user use MKL. So, building with MKL or using MKL.jl will most likely only give you MKL for `LinearAlgebra`, but not system wide.

**Comment by kiranshila** [comment] 2020-04-23 14:15
I opened a PR to append the build docs #35569

**Comment by KristofferC** [comment] 2020-04-23 14:15
> Note that packages will still use OpenBLAS_jll and OpenBLAS32_jll. We do not yet have a good way to make every BLAS user use MKL. So, building with MKL or using MKL.jl will most likely only give you MKL for LinearAlgebra, but not system wide.

Not sure what this means. The vast majority of BLAS/Lapack calls go through LinearAlgebra so most packages that use BLAS will in fact use MKL. There are a few packages that explicitly call into OpenBLAS using the jll package but that is just a few.

**Comment by ViralBShah** [comment] 2020-12-17 00:00
I recently built Julia master with MKL and seems to work fine. Let's open a new issue if this is still a problem.

**Comment by crstnbr** [comment] 2020-12-17 08:37
> I recently built Julia master with MKL and seems to work fine. Let's open a new issue if this is still a problem.

I just tried it the other day and it didn't work at all. I would like to try again. Did you use the instructions of the OP?

**Comment by ViralBShah** [comment] 2020-12-17 15:02
I just built one on release-1.6 with just those two things on linux. Can you make a PR for mac specific additional instructions?

**Comment by ViralBShah** [comment] 2020-12-17 15:03
It would be nice to fix the build so that no instructions are necessary.

**Comment by rmcsqrd** [comment] 2021-03-30 02:13
Did the PR with additional instructions ever get submitted? I am having issues with `] build MKL` on maxOS 10.15.7. Julia version info:

```
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

The error I get is:

```
# THIS WORKS
(antfarm) pkg> add MKL
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Updating `~/Programming/antfarm/Project.toml`
  [33e6dc65] + MKL v0.4.0
Updating `~/Programming/antfarm/Manifest.toml`
  [33e6dc65] + MKL v0.4.0
  [9b87118b] + PackageCompiler v1.2.5


# THIS DOES NOT WORK
(antfarm) pkg> build MKL
   Building MKL → `~/.julia/packages/MKL/3H9w2/deps/build.log`
┌ Error: Error building `MKL`:
│ error during bootstrap:
│ LoadError("/var/folders/1s/xd8bsr_939sbp1zvyzxcp_4r0000gn/T/jl_Vqvj3w/sysimage_packagecompiler_03897be6-90fc-11eb-2513-0bed9d3ae1d2.jl", 16, ArgumentError("Package MKL not found in current path:\n- Run `import Pkg; Pkg.add(\"MKL\")` to install the MKL package.\n"))
│ require at ./loading.jl:893
│ jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1690 [inlined]
│ do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:117
│ eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:428
│ jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:660
│ top-level scope at /var/folders/1s/xd8bsr_939sbp1zvyzxcp_4r0000gn/T/jl_Vqvj3w/sysimage_packagecompiler_03897be6-90fc-11eb-2513-0bed9d3ae1d2.jl:63
│ jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:840
│ jl_parse_eval_all at /Users/julia/buildbot/worker/package_macos64/build/src/ast.c:913
│ jl_load_rewrite at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:914 [inlined]
│ jl_load at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:919
│ exec_program at /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia (unknown line)
│ true_main at /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia (unknown line)
│ main at /Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia (unknown line)
│
│ [ Info: Splicing in code to load MKL in /Applications/Julia-1.5.app/Contents/Resources/julia/bin/../share/julia/base/sysimg.jl
│ [ Info: getting precompile script from: https://raw.githubusercontent.com/JuliaLang/julia/release-1.5/contrib/generate_precompile.jl
│ [ Info: PackageCompiler: creating base system image (incremental=false)...
│ ERROR: LoadError: failed process: Process(`/Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia --color=yes --startup-file=no --cpu-target native --sysimage=/var/folders/1s/xd8bsr_939sbp1zvyzxcp_4r0000gn/T/jl_Vqvj3w/corecompiler.ji -g1 -O0 --output-ji=/var/folders/1s/xd8bsr_939sbp1zvyzxcp_4r0000gn/T/jl_Vqvj3w/sys.ji /var/folders/1s/xd8bsr_939sbp1zvyzxcp_4r0000gn/T/jl_Vqvj3w/sysimage_packagecompiler_03897be6-90fc-11eb-2513-0bed9d3ae1d2.jl`, ProcessExited(1)) [1]
│
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] read(::Cmd) at ./process.jl:412
│  [3] (::PackageCompiler.var"#2#3"{String,Array{String,1},String,String,String,String})() at /Users/riomcmahon/.julia/packages/PackageCompiler/3BsME/src/PackageCompiler.jl:166
│  [4] cd(::PackageCompiler.var"#2#3"{String,Array{String,1},String,String,String,String}, ::String) at ./file.jl:104
│  [5] create_fresh_base_sysimage(::Array{String,1}; cpu_target::String) at /Users/riomcmahon/.julia/packages/PackageCompiler/3BsME/src/PackageCompiler.jl:149
│  [6] create_sysimage(::Array{Symbol,1}; sysimage_path::Nothing, project::String, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::String, base_sysimage::Nothing, isapp::Bool) at /Users/riomcmahon/.julia/packages/PackageCompiler/3BsME/src/PackageCompiler.jl:433
│  [7] top-level scope at /Users/riomcmahon/.julia/packages/MKL/3H9w2/src/install.jl:128
│  [8] eval at ./boot.jl:331 [inlined]
│  [9] change_blas_library(::String) at /Users/riomcmahon/.julia/packages/MKL/3H9w2/src/install.jl:126
│  [10] enable_mkl_startup() at /Users/riomcmahon/.julia/packages/MKL/3H9w2/src/install.jl:103
│  [11] top-level scope at /Users/riomcmahon/.julia/packages/MKL/3H9w2/deps/build.jl:13
│  [12] include(::String) at ./client.jl:457
│  [13] top-level scope at none:5
│ in expression starting at /Users/riomcmahon/.julia/packages/MKL/3H9w2/deps/build.jl:13
└ @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:949

```
Thanks.

**Comment by lrsantos11** [comment] 2021-04-20 12:57
Same here @rmcsqrd but in the following enviroment
```julia
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```

**Comment by ffucci** [comment] 2021-05-12 17:07
I'm on macOS Big Sur,  after I add the package MKL.jl, build MKL and reload again I still get openblas64

julia> using LinearAlgebra

julia> BLAS.vendor()
:openblas64

**Comment by giordano** [comment] 2021-05-12 17:51
Note that using [`MKL.jl`](https://github.com/JuliaLinearAlgebra/MKL.jl) should be _way_ easier to use with Julia v1.7 (the version currently in development), thanks to the use of [`libblastrampoline`](https://github.com/staticfloat/libblastrampoline).  It'd be great if you could try it out.  There is likely not much more to do here in that regard.

**Comment by ffucci** [comment] 2021-05-13 10:17
I tried also by compiling the version present in master, trying to add MKL.jl and build MKL and I still have the same problem that LinearAlgebra does not use :mkl but :openblas64.

>  julia> using LinearAlgebra

julia> BLAS.vendor()
:openblas64

julia> versioninfo()
Julia Version 1.7.0-DEV.1089
Commit d6c092d6d7* (2021-05-11 20:39 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin20.3.0)
  CPU: Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)

Do you have ideas on how it's possible to fix or at least debug the problem?

**Comment by giordano** [comment] 2021-05-13 10:26
Quoting from the [`README.md`](https://github.com/JuliaLinearAlgebra/MKL.jl/blob/d0b2c05179a6014b67e0e712037e2edc4bf0ca64/README.md#to-check-installation) of `MKL.jl`:

> ## To Check Installation:
> 
> ```julia
> julia> using LinearAlgebra
> 
> julia> BLAS.vendor()  # Prior to Julia v1.7
> :mkl
> 
> julia> BLAS.get_config()  # Julia v1.7 and later
> LinearAlgebra.BLAS.LBTConfig(LinearAlgebra.BLAS.LBTLibraryInfo[LinearAlgebra.BLAS.LBTLibraryInfo("/Users/viral/.julia/artifacts/073ff95e2c63501547247d6e1321bf4ee2a78933/lib/libmkl_rt.1.dylib", Ptr{Nothing} @0x00007fb6a5ef4820, "", UInt8[0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff  …  0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01], :ilp64, :plain)], [:f2c_capable], ["LAPACKE_c_nancheck", "LAPACKE_cbbcsd", "LAPACKE_cbbcsd_work", "LAPACKE_cbdsqr", "LAPACKE_cbdsqr_work", "LAPACKE_cgb_nancheck", "LAPACKE_cgb_trans", "LAPACKE_cgbbrd", "LAPACKE_cgbbrd_work", "LAPACKE_cgbcon"  …  "zunmlq_", "zunmql_", "zunmqr_", "zunmr2_", "zunmr3_", "zunmrq_", "zunmrz_", "zunmtr_", "zupgtr_", "zupmtr_"])
> ```

I guess you need to try `BLAS.get_config()`

**Comment by ffucci** [comment] 2021-05-13 10:38
I get the same as you, why BLAS vendor is still :openblas64 and does not change to :mkl, even if the config is libmkl_rt.so?

**Comment by giordano** [comment] 2021-05-13 10:40
Because `BLAS.vendor()` is deprecated:
https://github.com/JuliaLang/julia/blob/c3a31804a88beb4b05c8fd4b0981e76d14058311/stdlib/LinearAlgebra/src/blas.jl#L91-L100

**Comment by ViralBShah** [comment] 2021-05-19 21:55
I'm going to close this issue here, but relevant discussion for those interested in getting MKL built into the system image is at: https://github.com/JuliaLinearAlgebra/MKL.jl/issues/60

**Closed by ViralBShah** 2021-05-19 21:55 UTC
Labels: build, mac
