### ISSUE TITLE
Markdown: add ability to not escape html characters in markdown

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [JuliaLang/julia#35523] opened 2020-04-19 17:19 UTC
Currently, when exporting markdown to html, all html special characters are escaped:

```julia
using Markdown
a = Markdown.parse("This is *important* text with <i>html</i> in it");
# parsed as
Markdown.Paragraph(Any["This is ", Markdown.Italic(Any["important"]), " text with <i>html</i> in it"])
# then exporting to html
Markdown.html(a)
# output below
"<p>This is <em>important</em> text with &lt;i&gt;html&lt;/i&gt; in it</p>\n"
```

and there is no way of getting such an output:

```html
<p>This is <em>important</em> text with <i>html</i> in it</p>
```

So, this issue is a feature request.

It could even be the default behavior for all markdown blocks except code block.

(similar to #34042)

**Comment by fredrikekre** [comment] 2020-04-19 17:28
Duplicate of #17837 (It is escaped since the parser doesn't know this is HTML and thus has to escape it.)

**Comment by KDr2** [comment] 2020-04-20 06:42
I also request a new feature of `Markdown` here: **Comment Support**.

It  was discussed recently here: https://discourse.julialang.org/t/does-markdown-support-comments/37607

If we have a way to not escape HTML tags as it is proposed in this issue, I think we can use `<!-- -->` as comments then?

**Comment by stevengj** [comment] 2020-05-07 13:50
Closing as a duplicate.

**Closed by stevengj** 2020-05-07 13:50 UTC
