### ISSUE TITLE
scope of keyword argument default values

### ISSUE THREAD

**Issue by longqian95** [JuliaLang/julia#17240] opened 2016-07-02 04:56 UTC
a=1
f(;a=a)=a
f() will generate "UndefVarError" error.
There is no problem if it is a normal argument.

**Comment by dhoegh** [comment] 2016-07-02 09:16
Could you provide the output of `versioninfo()`, as i cannot reproduce the error.

**Comment by longqian95** [comment] 2016-07-03 03:25
I think whether it is intended or not, f(a=a) and f(;a=a) should be consistent: both are OK or both are error. Current situation is confusing.

**Comment by ivarne** [comment] 2016-07-05 12:55
+1 for consistent behaviour. (obviously)

**Comment by ivarne** [comment] 2016-07-05 13:05
Tentativly marking this as a regression due for 0.5.

**Comment by cstjean** [comment] 2016-07-05 13:32
+1 for consistency too, but it fails on Julia 0.4.5, so it's not a regression. Furthermore, the docs say it's [intended behaviour](http://docs.julialang.org/en/release-0.4/manual/functions/#keyword-arguments)

> Optional and keyword arguments differ slightly in how their default values are evaluated. When optional argument default expressions are evaluated, only previous arguments are in scope. In contrast, all the arguments are in scope when keyword arguments default expressions are evaluated.

I don't understand why all keyword arguments are in scope if their value is undefined...

**Comment by StefanKarpinski** [comment] 2016-07-06 00:24
I'm all for changing this in the future, but it will have to be in 0.6.

**Comment by JeffBezanson** [comment] 2017-07-20 17:54
Resolved: change to "`let*`" (successive nested scopes) scoping.

**Closed** 2017-07-26 20:26 UTC
Labels: breaking, design, keyword arguments
