### ISSUE TITLE
Spurious ambiguity/method table corruption with more than 14 methods

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#20056] opened 2017-01-16 01:16 UTC
The following throws an ambiguity error even though there shouldn't be one. Removing any of the first 10 unrelated methods causes the error to go away. This affects both master and jb/subtype with the same method number threshold.

```jl
g() = nothing
g(a, b, c, d) = nothing
g(a, b, c, d, e) = nothing
g(a, b, c, d, e, f) = nothing
g(a, b, c, d, e, f, g) = nothing
g(a, b, c, d, e, f, g, h) = nothing
g(a, b, c, d, e, f, g, h::Int64) = nothing
g(a, b, c, d, e, f, g, h::Int32) = nothing
g(a, b, c, d, e, f, g, h::Int16) = nothing
g(a, b, c, d, e, f, g, h::Int8) = nothing

#
g{T<:Number}(x::T, y::T) = nothing
g{T<:Float64}(x::T, y::T) = 1
g{T<:AbstractFloat}(x::Float64, y::T) = 2
g{T<:AbstractFloat}(x::T, y::Float64) = 3
g(1.0, 1.0)
```

Original report at https://discourse.julialang.org/t/why-is-this-a-method-ambiguity/1502 @JeffBezanson @vtjnash

**Comment by vtjnash** [comment] 2017-01-16 01:52
> g{T<:Float64}(x::T, y::T) = 1

the dispatch table considers this to be slightly distinct from `Float64`, making the ambiguity of this method ordering ambiguous

**Comment by yuyichao** [comment] 2017-01-16 01:59
A possibly related bug is

```jl
julia> abstract A1

julia> abstract A2 <: A1

julia> abstract A3 <: A2

julia> f{T<:A2}(::Type{T}, ::Type{T}) = 1
f (generic function with 1 method)

julia> f{T<:A1}(::Type{A2}, ::Type{T}) = 2
f (generic function with 2 methods)

julia> f{T<:A1}(::Type{T}, ::Type{A2}) = 2
f (generic function with 3 methods)

julia> f(A2, A2)
1
```

Both on master and on jb/subtype. I think we can special case `g{T<:Float64}(x::T, y::T) = 1` to be unambiguous since `T` can't be `Union{}`.

**Comment by JeffreySarnoff** [comment] 2017-01-16 20:17
Given a TypeVar V where V.lb == V.ub and a TypeVar W where W.lb != W.ub, V is more specific than W.  
Should V.lb be W.lb, W.ub or a subtype of W.ub that is a supertype of W.lb, V dominates W for dispatch.

**Comment by JeffBezanson** [comment] 2017-01-31 22:52
@vtjnash This seems related to `MAX_METHLIST_COUNT` in typemap. Is `jl_method_convert_list_to_cache` supposed to work for a sorted list, or should I just add a check for `!tparams->unsorted` and bypass list-to-cache in that case?

**Comment by vtjnash** [comment] 2017-02-01 00:05
No, that's vital for performance. The issue is that it needs to recognize that `g{T <: Float64}(x::T, y::T) = 1` and `g(x::Float64, y::Float64) = 1` are synonyms for specialization when partitioning the dispatch graph.

**Comment by vtjnash** [comment] 2022-03-29 21:15
both fixed now (side-effect of unsorted-method-table work)
```
g(x::T, y::T) where {T<:Number} = nothing
g(x::T, y::T) where {T<:Float64} = 1
g(x::Float64, y::T) where {T<:AbstractFloat} = 2
g(x::T, y::Float64) where {T<:AbstractFloat} = 3
g(1.0, 1.0)
```
```
julia> abstract type A1; end

julia> abstract type A2 <: A1; end

julia> abstract type A3 <: A2; end

julia> f(::Type{T}, ::Type{T}) where {T<:A2} = 1
f (generic function with 1 method)

julia> f(::Type{A2}, ::Type{T}) where {T<:A1} = 2
f (generic function with 2 methods)

julia> f(::Type{T}, ::Type{A2}) where {T<:A1} = 2
f (generic function with 3 methods)

julia> f(A2, A2)
ERROR: MethodError: f(::Type{A2}, ::Type{A2}) is ambiguous. Candidates:
  f(::Type{T}, ::Type{T}) where T<:A2 in Main at REPL[9]:1
  f(::Type{A2}, ::Type{T}) where T<:A1 in Main at REPL[10]:1
  f(::Type{T}, ::Type{A2}) where T<:A1 in Main at REPL[11]:1
Possible fix, define
  f(::Type{A2}, ::Type{A2})
Stacktrace:
 [1] top-level scope
   @ REPL[12]:1
```

**Closed by vtjnash** 2022-03-29 21:15 UTC
Labels: types and dispatch
