### ISSUE TITLE
Extra space in @sprintf("%.6g", 1.0)

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#16099] opened 2016-04-28 16:30 UTC
The space at the end here seems to be a bug:
```
julia> @sprintf("%.6g", 1.0)
"1 "
```

**Comment by dpsanders** [comment] 2016-04-28 16:31
Fixed on 0.5; sorry for the noise.

**Comment by StefanKarpinski** [comment] 2016-04-28 16:44
Probably should be backported though.

**Comment by tkelman** [comment] 2016-04-29 00:29
If not too disruptive. Blame or bisect to identify what the fix was?

**Comment by tkelman** [comment] 2016-09-13 09:20
if anyone identifies the fix for this we can put the backport pending label back there - will need to happen soon to make 0.4.7 which might be the last 0.4 release though

**Comment by garrison** [comment] 2016-09-21 02:34
This is a duplicate of #14331; ddd0f05 seems (on the surface) to be the commit that fixed it.

**Comment by tkelman** [comment] 2016-09-21 03:20
Thanks. Closing and moving the backport label to https://github.com/JuliaLang/julia/pull/14348 then. If we make an 0.4.8 we can test it then.

**Closed by tkelman** 2016-09-21 03:20 UTC
Labels: backport pending 0.4
