### ISSUE TITLE
Build failure on Win/MSYS2

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#13471] opened 2015-10-06 23:22 UTC
Either on a fresh clone or from my previously working build setup I'm getting now

```
checking size of mp_limb_t... 0
configure: error: Oops, mp_limb_t doesn't seem to work
Makefile:1798: recipe for target 'build/gmp-6.0.0/config.status' failed
```

**Comment by tkelman** [comment] 2015-10-07 00:07
Which toolchain are you using? Please post the full configure output and the `config.log` file from `build/gmp-6.0.0`.

**Comment by joa-quim** [comment] 2015-10-07 00:33
The toolchain is the one recommended in the Windows building instruction (MSYS2 plus the download of the other gcc compiler).

The `config.log` is in http://w3.ualg.pt/~jluis/ftp/tmp/config.zip

The configure output is short (maybe because it's from a second run)

```
a - spqr_type.o
a - spqr_tol.o
checking for suitable m4... m4
checking if m4wrap produces spurious output... no
checking how to switch to text section... .text
checking how to switch to data section... .data
checking for assembler label suffix... :
checking for assembler global directive... .globl
checking for assembler global directive attribute...
checking if globals are prefixed by underscore... no
checking how to switch to read-only data section...     .section .rdata,"dr"
checking for assembler .type directive...
checking for assembler .size directive...
checking for assembler local label prefix... L
checking for assembler byte directive... .byte
checking how to define a 32-bit word... .long
checking if .align assembly directive is logarithmic... no
checking if the .align directive accepts an 0x90 fill in .text... yes
checking size of void *... 8
checking size of unsigned short... 2
checking size of unsigned... 4
checking size of unsigned long... 4
checking size of mp_limb_t... 0
configure: error: Oops, mp_limb_t doesn't seem to work
Makefile:1798: recipe for target 'build/gmp-6.0.0/config.status' failed
```

**Comment by tkelman** [comment] 2015-10-07 00:35
whoops, duplicate of #13206. needs a makefile patch apparently

**Closed by tkelman** 2015-10-07 00:35 UTC
Labels: windows
