### ISSUE TITLE
Array views and resize

### ISSUE THREAD

**Issue by chethega** [JuliaLang/julia#25743] opened 2018-01-25 14:39 UTC
```
a=collect(1:4);
b=view(a,:) ;
popfirst!(a);
b
4-element view(::Array{Int64,1}, :) with eltype Int64:
 2
 3
 4
 0
```
Ok, I get to see unallocated memory. 

```
a=[Int[] for a=1:8]
b=view(a,:) 
popfirst!(a)
popfirst!(a)
..
b
Segmentation fault (core dumped)
```
Also on 0.62, using shift! instead of popfirst!.

**Comment by StefanKarpinski** [comment] 2018-01-25 15:39
You're not actually seeing unallocated memory, if I understand this correctly, you're seeing allocated memory that belongs to `a` but which it isn't currently using, which is quite different. If `a` were moved by `realloc` then `a` and `b` would become detached from each other, which is a possibility when you resize an array that you have a view into.

**Comment by chethega** [comment] 2018-01-25 16:01
As far as I understood popfirst! increments `pointer(a)`, which means that `b[n]` now points to `b[n+1]` which is beyond the bounds of the memory allocated for `a`; classic OOB. realloc should actually not make a problem, I think?

**Comment by chethega** [comment] 2018-01-25 16:08
```
A = [UInt(i) for i=1:256]
b=view(A,:);
for i=1:30 shift!(A) end
b[length(b)-30: length(b)]
31-element Array{UInt64,1}:
 0x0000000000000100
 0x000055839d3a3948
 0x0000000000000121
 0x000055839d431d20
 0x000055839c2e18c0
 0x0000000000000102
 0x0000000000000118
 0x0000000000000000
 0x0000000000000000
 0x0000000000000067
                  ���
 0x000055839d3a39d0
 0x000055839d3a39e8
 0x000055839bef56a4
 0x000055839bef56c4
 0x000055839bef7a30
 0x000055839d3a39f0
 0x000055839d4466e0
 0x000055839c4bbb40
 0x000055839d3a3a00
```

**Comment by mbauman** [comment] 2018-01-25 16:44
Yes, this is definitely a wart, but I'm not sure how much we can do about it.  Views check the bounds of the parent upon construction, and then assume that the parent does not change size upon subsequent accesses.  We've worked very hard to get views as fast as possible — adding additional checks to make sure things haven't changed "behind our backs" is a significant cost.

At a minimum, we should add a much more prominent warning to the documentation.

**Comment by chethega** [comment] 2018-01-25 17:05
This only applies to views into vectors. Views into higher-dim arrays can keep the `@inbounds` of the access into the parent. View get and set should be `@propagate_inbounds`, so that users of `@inbounds` loose no performance.

I am not sure that it makes a big performance difference whether we do one or two bound-checks on each access into the view. For access in loops, llvm's inductive range check elimination might be helpful, and maybe LICM is already capable of turning both range checks into a single one. For access out of loops, who cares about the fractional cycle spent on a range check? Currently we don't do an IRCE pass, and I am not sure how helpful or expensive it is. In my dream world, LLVM would remove all bound checks in "obviously inbounds" code like `for i=1:length(V) V[i] end` or `for v in V v end`.

Alternatively one could play with the array flags? Such that a vector becomes un-resizeable once a view has been taken. I do not like this idea, but it is an option.

Alternatively one could document that deleting elements from the front of a vector may segfault if a view exists; if the eltype is not bitstype, then it might also segfault on deleting from the back (the gc cannot find the former `a[end]` anymore and frees it; `b[end]` still holds a reference). I do not like the idea; if I want my access to be fast and unsafe, I play pointer games. If I want non-segfaulting easy-to-understand code then I use views.

**Comment by mbauman** [comment] 2018-01-25 17:16
It also applies to any custom arrays that support `resize!`, so I'd prefer not to just special-case `Vector` specifically.

That's a good point about `@propagate_inbounds` — when we first developed views that tool wasn't in our toolbox yet.  It's definitely worth quantifying how big of an effect this would be and making sure that the trade-off calculations we made long ago are still valid.

**Comment by chethega** [comment] 2018-01-25 17:32
Regarding deletion from the end segfaulting for non-bitstypes:

```
a = Any[[UInt(i)] for i=1:256];
b = view(a,:);
resize!(a,0);
b[1:3]
3-element Array{Any,1}:
 UInt64[0x0000000000000001]
 UInt64[0x0000000000000002]
 UInt64[0x0000000000000003]
gc(); x= Any[]; for i=1:100_000 x=Any[i]; end; gc();
b[1:3]
Segmentation fault (core dumped)
```

**Comment by chethega** [comment] 2018-01-25 17:40
...and I am not so sure about `@propagate_inbounds` anymore.

Is the following supposed to be safe in julia, if V is an AbstractArray? 
```
assert(typeof(V) <:AbstractArray)
for i in eachindex(V)
    @inbounds V[i]
end
```

**Comment by mbauman** [comment] 2018-01-25 18:15
Yes, that should be a safe usage of `@inbounds`.  So, yes, `@propagate_inbounds` cannot work here.  If the SubArray cannot trust the size of the parent array to be constant, then it must _always_ check it on every single access.

It's not just resizing vectors that break this assumption.  You can also modify the indices of the view behind its back:

```
julia> I = [1]
       A = [2]
       V = @view A[I]
1-element view(::Array{Int64,1}, [1]) with eltype Int64:
 2

julia> I[1] = 100000;

julia> V
1-element view(::Array{Int64,1}, [100000]) with eltype Int64:
 0

julia> I[1] = 10000000000;

julia> V
1-element view(::Array{Int64,1}, [10000000000]) with eltype Int64:

signal (11): Segmentation fault: 11
```

We have a number of performance tests for views in BaseBenchmarks.jl.  If you're really curious about this you could try seeing how much of an effect the bounds checks have now that both LLVM and Julia have changed significantly since we last examined this.

**Comment by chethega** [comment] 2018-01-25 18:59
Oh my god. For simple views, I wanted to propose that each access checks that the entire view is inbounds of the parent; that way, LLVM has an easier time of hoisting the check out of loops (because the condition is independent of the index we access)-- but this can only work well if LLVM manages to figure out that the loop body does not change the parent's size (and the view's immutable values). I am unsure how reliable this is (alignment analysis; ccall in unlikely branches).

Maybe add a parameter (keyword once we can dispatch on it) like `safety = Base.safe` (check the parent bounds, no `@propagate_inbounds`; for the non-generic case of Base-Arrays, try to figure out something that LLVM can hoist out of loops) , `safety=Base.semisafe` (current behavior), `safety=Base.recklessly_unsafe` (if possible copy pointer(parent); then we become bitstype and are always non-allocating but the user needs to possibly sprinkle `@gc_preserve`).

**Comment by ederag** [comment] 2018-05-03 21:39
it seems to be fixed with current dev version
```
a = Any[[UInt(i)] for i=1:256];
b = view(a,:);
resize!(a,0);
b[1:3]
ERROR: BoundsError: attempt to access 0-element view(::Array{Any,1}, :) with eltype Any at index [1:3]                                                    
Stacktrace:
 [1] throw_boundserror(::SubArray{Any,1,Array{Any,1},Tuple{Base.Slice{Base.OneTo{Int64}}},true}, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:464
 [2] checkbounds at ./abstractarray.jl:429 [inlined]
 [3] _getindex at ./multidimensional.jl:622 [inlined]
 [4] getindex(::SubArray{Any,1,Array{Any,1},Tuple{Base.Slice{Base.OneTo{Int64}}},true}, ::UnitRange{Int64}) at ./abstractarray.jl:942
 [5] top-level scope
```

```
Julia Version 0.7.0-DEV.4924
Commit 316f117f04* (2018-04-25 18:05 UTC) 
```

**Comment by mbauman** [comment] 2018-05-03 22:00
That's only the case for `Any[]` arrays — they're missing the bounds check elision that occurs in concretely typed cases.  Try it with `a =[[UInt(i)] for i=1:256]`.

**Comment by ederag** [comment] 2018-05-03 22:36
Right.
```
julia> a =[[UInt(i)] for i=1:256];

julia> b = view(a,:);

julia> resize!(a,0);

julia> b[1:3]
3-element Array{Array{UInt64,1},1}:
 [0x0000000000000001]
 [0x0000000000000002]
 [0x0000000000000003]

julia> GC.gc(); x= Any[]; for i=1:100_000 x=Any[i]; end; GC.gc();
┌ Warning: Deprecated syntax `implicit assignment to global variable `x``.
│ Use `global x` instead.
└ @ nothing none:0

julia> b[1:3]
3-element Array{Array{UInt64,1},1}:
 [0x0000000000000001]
 [0x0000000000000002]
 [0x0000000000000003]
```
no crash here (tried several times, but it might still be random).

And your example does segfault reproducibly:
```
I = [1]
A = [2]
V = @view A[I]
I[1] = 100000;
V
I[1] = 10000000000;
V

1-element view(::Array{Int64,1}, [10000000000]) with eltype Int64:
signal (11): Segmentation fault
```

**Comment by ViralBShah** [comment] 2022-02-25 17:23
I don't get a segfault any more with the example.

**Closed by ViralBShah** 2022-02-25 17:23 UTC
Labels: arrays

**Comment by mbauman** [comment] 2022-02-25 17:55
It's still corrupting out of bounds.  Nothing has changed in the design here — mutating lengths of parents or the values of indices behind `SubArray`'s back will always do this.

That said, I still support closing this issue.  It's now documented in `view`:

> The behavior is undefined if the shape of the parent array is changed after view is called because there is no bound check for the parent array; e.g., it may cause a segmentation fault.
