### ISSUE TITLE
A_mul_B! is broken for matrices that are not small and square

### ISSUE THREAD

**Issue by NickMcNutt** [JuliaLang/julia#13593] opened 2015-10-13 20:49 UTC
`A_mul_B!(B, A, B)` replaces B with all zeros for the case where A is not small and square:

```julia
X = randn(3, 2)
Y = randn(3, 3)
Z = randn(3, 4)

M = randn(3, 3)
R = expm(M - M')

display(A_mul_B!(X, R, X))
display(A_mul_B!(Y, R, Y))
display(A_mul_B!(Z, R, Z))
```

outputs:

```
3x2 Array{Float64,2}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

3x3 Array{Float64,2}:
 1.6548     0.742438  -1.50673
 0.282773  -1.35856   -0.39896
 0.700949  -1.27408   -0.846028

3x4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
```

Here's my version info:

```
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by KristofferC** [comment] 2015-10-13 20:54
Working as intended, the overwritten matrix is not allowed to alias with any of the input matrices, see the docs: http://docs.julialang.org/en/release-0.4/stdlib/math/?highlight=a_mul_b!#Base.A_mul_B!

**Comment by jiahao** [comment] 2015-10-13 20:54
Duplicate of #11756?

**Comment by andreasnoack** [comment] 2015-10-13 20:58
As mentioned by @KristofferC, this is documented behavior. You are never allowed to alias input and output matrices in general matrix multiplication. The small matrices handled in special way because of performance and it happens that it also allows aliasing.

**Comment by NickMcNutt** [comment] 2015-10-13 20:59
Okay, I had simply used `?A_mul_B!` instead of looking it up in the docs:

```

  A_mul_B!(Y, A, B) -> Y

  Calculates the matrix-matrix or matrix-vector product A⋅B and stores the result in Y, overwriting the existing
  value of Y.

  julia> A=[1.0 2.0; 3.0 4.0]; B=[1.0 1.0; 1.0 1.0]; A_mul_B!(B, A, B);

  julia> B
  2x2 Array{Float64,2}:
   3.0  3.0
   7.0  7.0
```

A little more searching reveals I'm not the first to run into this situation:

https://github.com/JuliaLang/julia/issues/13488

Does this behavior not seem unintuitive/inconsistent to anyone else?

**Closed by andreasnoack** 2015-10-13 20:58 UTC

**Comment by KristofferC** [comment] 2015-10-13 20:59
We could possibly check for `===` equality and error out but that is of course no guarantee in general that there is no aliasing.

**Comment by andreasnoack** [comment] 2015-10-13 21:08
@NickMcNutt You are right that other people have also been surprices by this, but it's a fact of life that two matrices cannot be multiplied in place unless they have special structure.

@KristofferC We could add this check to the GEMM wrapper.
