### ISSUE TITLE
Threads macro load balancing option

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#32207] opened 2019-05-31 16:20 UTC
As discussed with @JeffBezanson in the Slack, `@threads` still uses a static schedule. However, there are some cases where we are using it as a simple way to express a lot of similar computations to be done on threads, each of which is actually quite expensive and not the same size. Thus for our purposes it would make sense to utilize `@par` to get the dynamic scheduling, but it makes sense "aesthetics-wise" to just put `@threads` on the loop. Thus it would make sense to have something like `@threads dynamic for i in ...` where

```julia
macro par(expr)
    thunk = esc(:(()->($expr)))
    quote
        local task = Task($thunk)
        task.sticky = false
        schedule(task)
        task
    end
end
```

it turns the loop

```julia
_f = (i) -> # inner expression of the loop
for i in 1:100
  @par _f(i)
end
```

If I'm not mistaken that's all that's necessary?

**Comment by quinnj** [comment] 2019-05-31 16:23
We should probably also think about `asyncmap`; maybe it could take a `dynamic=true` keyword argument or something.

**Comment by vchuravy** [comment] 2019-05-31 16:24
Not quite, I think the right way of doing this is to enhance `@async` so that it can set `task.sticky`, since you will need an `@sync`. 

``` julia
@sync for i in 1:100
  @async par=true _f(i)
end
```

**Comment by stevengj** [comment] 2019-05-31 16:49
Should it just default to a dynamic schedule once partr is working well?   That's what Cilk does, right?

**Comment by StefanKarpinski** [comment] 2019-05-31 18:06
Balanced workload is the exception rather than the rule, so imo, yes.

**Comment by JeffBezanson** [comment] 2019-06-01 21:32
Duplicate of #21017

**Comment by andreasnoack** [comment] 2019-07-02 12:08
Why not close if it's a duplicate?

**Closed** 2019-07-02 13:20 UTC
Labels: multithreading
