### ISSUE TITLE
Encountered Segfault in `jl_compilation_sig` from Revise when changing branches involved changed package dependencies

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#44913] opened 2022-04-08 17:05 UTC
This is probably a low priority, but I hit a segfault today when i was changing branches on my project, and Revise attempted to delete a bunch of code that had been removed on the new branch (and also we changed the Manifest and the installed set of packages).

```julia
julia> XUnit.runtests(["RAI/Database/Proto conversion/InMemoryRelationLocator"])
WARNING: redefinition of constant _DBG. This may fail, cause incorrect answers, or produce other errors.
WARNING: redefinition of constant _tracing. This may fail, cause incorrect answers, or produce other errors.
┌ Warning: 2022-04-08T13:01:30.915
│ /Users/nathandaly/work/raicode2/src/LazyCSV/LazyCSV.jl no longer exists, deleted all methods
└ @ Revise ~/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:651
┌ Warning: 2022-04-08T13:01:31.052
│ /Users/nathandaly/work/raicode2/src/LazyCSV/util.jl no longer exists, deleted all methods
└ @ Revise ~/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:651
┌ Warning: 2022-04-08T13:01:31.134
│ /Users/nathandaly/work/raicode2/src/LazyCSV/buffered_vector.jl no longer exists, deleted all methods
└ @ Revise ~/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:651

signal (11): Segmentation fault: 11
in expression starting at none:1
jl_compilation_sig at /Users/nathandaly/builds/julia-1.7/src/gf.c:581
cache_method at /Users/nathandaly/builds/julia-1.7/src/gf.c:1027
ml_matches at /Users/nathandaly/builds/julia-1.7/src/gf.c:3130
jl_matching_methods at /Users/nathandaly/builds/julia-1.7/src/gf.c:1895
_methods_by_ftype at ./reflection.jl:908 [inlined]
_methods_by_ftype at ./reflection.jl:902 [inlined]
_methods_by_ftype at ./reflection.jl:899 [inlined]
#77 at /Users/nathandaly/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:249
unknown function (ip: 0x59c92272ff)
_jl_invoke at /Users/nathandaly/builds/julia-1.7/src/gf.c:0 [inlined]
jl_apply_generic at /Users/nathandaly/builds/julia-1.7/src/gf.c:2429
with_logstate at ./logging.jl:511
with_logger at ./logging.jl:623 [inlined]
delete_missing! at /Users/nathandaly/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:243 [inlined]
delete_missing! at /Users/nathandaly/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:305
handle_deletions at /Users/nathandaly/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:648
#revise#96 at /Users/nathandaly/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:747
revise at /Users/nathandaly/work/jl_depots/raicode2/packages/Revise/VskYC/src/packagedef.jl:735
unknown function (ip: 0x59df19657f)
_jl_invoke at /Users/nathandaly/builds/julia-1.7/src/gf.c:0 [inlined]
jl_apply_generic at /Users/nathandaly/builds/julia-1.7/src/gf.c:2429
jl_apply at /Users/nathandaly/builds/julia-1.7/src/./julia.h:1788 [inlined]
jl_f__call_latest at /Users/nathandaly/builds/julia-1.7/src/builtins.c:757
#invokelatest#2 at ./essentials.jl:716 [inlined]
invokelatest at ./essentials.jl:714
_jl_invoke at /Users/nathandaly/builds/julia-1.7/src/gf.c:0 [inlined]
jl_apply_generic at /Users/nathandaly/builds/julia-1.7/src/gf.c:2429
jl_apply at /Users/nathandaly/builds/julia-1.7/src/./julia.h:1788 [inlined]
do_call at /Users/nathandaly/builds/julia-1.7/src/interpreter.c:126
eval_stmt_value at /Users/nathandaly/builds/julia-1.7/src/interpreter.c:166 [inlined]
eval_body at /Users/nathandaly/builds/julia-1.7/src/interpreter.c:583
jl_interpret_toplevel_thunk at /Users/nathandaly/builds/julia-1.7/src/interpreter.c:731
jl_toplevel_eval_flex at /Users/nathandaly/builds/julia-1.7/src/toplevel.c:885
jl_toplevel_eval_flex at /Users/nathandaly/builds/julia-1.7/src/toplevel.c:830
jl_toplevel_eval at /Users/nathandaly/builds/julia-1.7/src/toplevel.c:894 [inlined]
jl_toplevel_eval_in at /Users/nathandaly/builds/julia-1.7/src/toplevel.c:944
eval at ./boot.jl:373 [inlined]
eval_user_input at /Users/nathandaly/builds/julia-1.7/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
repl_backend_loop at /Users/nathandaly/builds/julia-1.7/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:246
start_repl_backend at /Users/nathandaly/builds/julia-1.7/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:231
#run_repl#47 at /Users/nathandaly/builds/julia-1.7/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:364
run_repl at /Users/nathandaly/builds/julia-1.7/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:351
_jl_invoke at /Users/nathandaly/builds/julia-1.7/src/gf.c:0 [inlined]
jl_apply_generic at /Users/nathandaly/builds/julia-1.7/src/gf.c:2429
#930 at ./client.jl:394
jfptr_YY.930_25887 at /Users/nathandaly/builds/julia-1.7/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/nathandaly/builds/julia-1.7/src/gf.c:0 [inlined]
jl_apply_generic at /Users/nathandaly/builds/julia-1.7/src/gf.c:2429
jl_apply at /Users/nathandaly/builds/julia-1.7/src/./julia.h:1788 [inlined]
jl_f__call_latest at /Users/nathandaly/builds/julia-1.7/src/builtins.c:757
#invokelatest#2 at ./essentials.jl:716 [inlined]
invokelatest at ./essentials.jl:714 [inlined]
run_main_repl at ./client.jl:379
exec_options at ./client.jl:309
_start at ./client.jl:495
jfptr__start_25874 at /Users/nathandaly/builds/julia-1.7/usr/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/nathandaly/builds/julia-1.7/src/gf.c:0 [inlined]
jl_apply_generic at /Users/nathandaly/builds/julia-1.7/src/gf.c:2429
jl_apply at /Users/nathandaly/builds/julia-1.7/src/./julia.h:1788 [inlined]
true_main at /Users/nathandaly/builds/julia-1.7/src/jlapi.c:559
jl_repl_entrypoint at /Users/nathandaly/builds/julia-1.7/src/jlapi.c:701
Allocations: 458407397 (Pool: 458194419; Big: 212978); GC: 116
```

```julia
julia> VERSION
v"1.7.2"
```

**Comment by vtjnash** [comment] 2022-04-12 20:11
Duplicate of #43040

**Closed by vtjnash** 2022-04-12 20:11 UTC
Labels: bug
