### ISSUE TITLE
Module at top level scope

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#21009] opened 2017-03-13 17:23 UTC
```julia
julia> begin
           module A
           1
           end
       end
ERROR: syntax: module expression not at top level
```

Theoretically this should work, because module A is indeed in global scope? Would be helpful to get working for macros which operate on large blocks of global code

**Comment by JeffBezanson** [comment] 2017-03-13 20:39
You can do this by returning an expression with head `:toplevel`.

**Comment by bramtayl** [comment] 2017-03-13 22:04
I managed to get this working like this:

```
is_module(a) = false
is_module(e::Expr) = e.head == :module

map_expression(f, a) = a
map_expression(f, e::Expr) = Expr(e.head, f.(e.args)...)

move_module_to_global(e::Expr) = 
    if e.head == :block && any( is_module.(e.args) )
        Expr(:toplevel, e.args...)
    elseif e.head == :block
        Expr(:block, move_module_to_global.(e.args...) )
    else 
        e 
    end

macro identity(e)
    e |> move_module_to_global |> esc
end

@identity begin
    module A 
    b = 1
    end 
    A.b
end
```

Which works for my purposes, but I think its worth including the same semantics in base

**Comment by JeffBezanson** [comment] 2017-03-13 23:08
I think this is mostly a duplicate of #2586. It's tricky, since it's not generally correct to just replace `block` with `toplevel`, or to move code around.

**Comment by bramtayl** [comment] 2017-03-14 04:15
Actually, the solution above has a slight issue. Even though it correctly defines the module, it returns `nothing`

**Comment by mauro3** [comment] 2017-03-15 13:56
I thought that `begin...end` blocks are supposed to have no impact on scope.  That is at least what the docs say.  Or does "top level" refer to some other thing? (Note that `if` suffers the same issue)

**Comment by yuyichao** [comment] 2017-03-15 14:05
This is not scope. And `Expr(:toplevel)` is not `begin end`.

**Comment by mauro3** [comment] 2017-03-15 14:17
Maybe the error could be more specific what "top level" it is?

**Comment by JeffBezanson** [comment] 2017-03-17 18:54
Also related to #10472. If `local` were not allowed in global scope, then `begin end` could indeed be equivalent to a `:toplevel` expr.

**Comment by bramtayl** [comment] 2017-03-30 05:14
A seemingly easy fix would just be to pass through code post macro-parsing pre-lowering and (repeatedly) remove any begin end bookends at top-level.

**Comment by vtjnash** [comment] 2018-06-08 23:59
You could just use `eval` directly and do:
```julia
abstract type Zmod <: Integer end
function constructZmodn(n)
    name = parse("Z$n", raise = true)
    eval(:(primitive type name <: Zmod 8 end))
    #eval reinterpret behavior
    #eval ops
end
constructZmodn(3)
```

**Comment by jamesjscully** [comment] 2018-06-09 01:53
I figured that I wouldn't be able to define methods on types that didn't exist at parse time. Is this false?
I got it to work with:
```
macro constructZmodn(n)
    name = parse("Z$n")
    esc(quote
        primitive type $(name) <: Zmod 8 end
        Base.convert(::Type{$(name)}, x::T) where {T<:Integer} = reinterpret($name, x % $n)
        Base.convert(::Type{UInt8}, x::$(name)) = reinterpret(UInt8, x)        
        $(name)(x::T) where {T <: Integer} = reinterpret($(name),x)
    end)
end
```
But the weird thing is if I define more methods in a for loop within the same `esc(quote ... end)` block, I get an error saying that type definitions aren't allowed in local scope. Needless to say this is very counter-intuitive behavior. Here's the code that doesn't work. (on 6.3 now because my 7.0 alpha install broke inadvertently)
```
macro constructZmodn(n)
    name = parse("Z$n")
    esc(quote
        primitive type $(name) <: Zmod 8 end
        Base.convert(::Type{$(name)}, x::T) where {T<:Integer} = reinterpret($name, x % $n)
        Base.convert(::Type{UInt8}, x::$(name)) = reinterpret(UInt8, x)        
        $(name)(x::T) where {T <: Integer} = reinterpret($(name),x)
        for op in [:+,:-,:*,:/]
            (op)(x::$(name), y::$(name)) = op(x,y) % $n
        end
    end)
end
```
However, If I take for loop out of the escape block and escape inside the loop everything works as expected:
```
macro constructZmodn(n)
    name = parse("Z$n")
    esc(quote
        primitive type $(name) <: Zmod 8 end
        Base.convert(::Type{$(name)}, x::T) where {T<:Integer} = reinterpret($name, x % $n)
        Base.convert(::Type{UInt8}, x::$(name)) = reinterpret(UInt8, x)        
        $(name)(x::T) where {T <: Integer} = reinterpret($(name),x)
    end)
    for op in [:+,:-,:*,:/]
        esc(:((op)(x::$(name), y::$(name)) = op(x,y) % $n))
    end
end
```

**Comment by jamesjscully** [comment] 2018-06-09 02:10
Actually it doesn't work in the last example. The constructor Z6 is not in the global namespace. It only appeared to be because I didn't restart the REPL.

**Closed** 2019-02-17 15:33 UTC
