### ISSUE TITLE
ARM segfault while generating inference.ji

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#17659] opened 2016-07-28 01:17 UTC
I'm building Julia 0.5 (master) on my Raspberry Pi. This aborts with
```
make[1]: Entering directory '/home/pi/src/julia-0.5'
 cd /home/pi/src/julia-0.5/base && /home/pi/src/julia-0.5/usr/bin/julia -C arm1176jzf-s --output-ji /home/pi/src/julia-0.5/usr/lib/julia/inference.ji --startup-file=no coreimg.jl
Segmentation fault
Makefile:215: recipe for target '/home/pi/src/julia-0.5/usr/lib/julia/inference.ji' failed
make[1]: *** [/home/pi/src/julia-0.5/usr/lib/julia/inference.ji] Error 139
make[1]: Leaving directory '/home/pi/src/julia-0.5'
Makefile:96: recipe for target 'julia-inference' failed
make: *** [julia-inference] Error 2
```

**Comment by tkelman** [comment] 2016-07-28 01:33
duplicate of https://github.com/JuliaLang/julia/issues/17577?

**Comment by yuyichao** [comment] 2016-07-28 03:03
More likely https://github.com/JuliaLang/julia/issues/17645

**Closed by yuyichao** 2016-07-28 03:03 UTC
Labels: arm

**Comment by eschnett** [comment] 2016-07-28 03:38
#17645 shows the same symptoms, but the remedy there didn't help. I'm using `USE_SYSTEM_LLVM=1`, with LLVM 3.7.0. Is that a bad idea?

**Comment by nalimilan** [comment] 2016-07-28 08:57
In my experience `USE_SYSTEM_LLVM=1` makes inference fail on ARM (https://github.com/JuliaLang/julia/issues/10602). It would be interesting to know whether somebody managed to get the build pass on ARM with that option set.

**Comment by yuyichao** [comment] 2016-07-28 09:30
I'm using `USE_SYSTEM_LLVM=1` with either llvm SVN/patched 3.7.1/alarm stock 3.8.0.

**Comment by ViralBShah** [comment] 2016-08-06 14:05
Looks like the buildbot successfully built a binary a few hours ago. I wonder if this is spurious or if the issue got addressed with the recent arm PR and other compiler PRs.

@josefsachsconning Can you test on your setup?

**Comment by josefsachsconning** [comment] 2016-08-06 16:59
My build has been running for 2.5 hours on my Raspberry Pi.  Looks like it's using a lot more memory than it used to, swapping a lot on my 1 GB system.

**Comment by ViralBShah** [comment] 2016-08-06 17:53
My build just went through and is failing:

```
signal (11): Segmentation fault
while loading coreio.jl, in expression starting on line 9
Allocations: 143308 (Pool: 143234; Big: 74); GC: 0
Segmentation fault
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/home/viral/julia/usr/lib/julia/sys.o] Error 1
make: *** [julia-sysimg-release] Error 2
```

**Comment by ViralBShah** [comment] 2016-08-06 17:54
Perhaps I am filing this in the wrong issue.

**Comment by josefsachsconning** [comment] 2016-08-07 00:59
The build is being killed by oom-killer on my 1 GB Raspberry Pi 3. I'll try again after I connect a USB hard drive and add swap space on it.

**Comment by josefsachsconning** [comment] 2016-08-14 18:49
I have added swap to my Raspberry Pi, and successfully built 0.6.0-dev.212.
