### ISSUE TITLE
["A";"B";;"C";"D"] works in v1.7.2 but gives an error in v1.7.3

### ISSUE THREAD

**Issue by jonaswickman** [JuliaLang/julia#46133] opened 2022-07-21 21:31 UTC
In julia v1.7.2 you can write
```
["A";"B";;"C";"D"]
```
which gives you a matrix:
```
2×2 Matrix{String}:
 "A"  "C"
 "B"  "D"
```
In version 1.7.3 however you get an error message:
```
ERROR: MethodError: no method matching size(::String, ::Int64)
Closest candidates are:
  size(::Union{LinearAlgebra.QR, LinearAlgebra.QRCompactWY, LinearAlgebra.QRPivoted}, ::Integer) at ~/Files/Programs/Julia/julia-1.7.3/share/julia/stdlib/v1.7/LinearAlgebra/src/qr.jl:566
  size(::Union{LinearAlgebra.Hermitian{T, S}, LinearAlgebra.Symmetric{T, S}} where {T, S}, ::Any) at ~/Files/Programs/Julia/julia-1.7.3/share/julia/stdlib/v1.7/LinearAlgebra/src/symmetric.jl:201
  size(::Union{LinearAlgebra.Cholesky, LinearAlgebra.CholeskyPivoted}, ::Integer) at ~/Files/Programs/Julia/julia-1.7.3/share/julia/stdlib/v1.7/LinearAlgebra/src/cholesky.jl:495
  ...
Stacktrace:
 [1] _typed_hvncat_dims(#unused#::Type{String}, dims::Tuple{Int64, Int64}, row_first::Bool, as::NTuple{4, String})
   @ Base ./abstractarray.jl:2328
 [2] _typed_hvncat(::Type, ::Tuple{Int64, Int64}, ::Bool, ::String, ::Vararg{String})
   @ Base ./abstractarray.jl:2304
 [3] _hvncat(::Tuple{Int64, Int64}, ::Bool, ::String, ::Vararg{String})
   @ Base ./abstractarray.jl:2133
 [4] hvncat(::Tuple{Int64, Int64}, ::Bool, ::String, ::Vararg{String})
   @ Base ./abstractarray.jl:2129
 [5] top-level scope
   @ REPL[2]:1
```

Full version info for both versions:
```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```
```
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

**Comment by jmkuhn** [comment] 2022-07-22 01:11
Need to backport https://github.com/JuliaLang/julia/pull/45365.

**Comment by giordano** [comment] 2022-07-22 18:03
Duplicate of #45461?

**Comment by BioTurboNick** [comment] 2022-07-22 18:30
As a workaround, you can define
```
size(x::String, y::Int) = Base.cat_size(x, y)
```

**Closed** 2022-07-22 18:34 UTC
