### ISSUE TITLE
`StringRef::data()` erroneously assumed to be null terminated

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#10098] opened 2015-02-06 03:59 UTC
PR #10097 fixes a few instances in which it is [erroneously](http://llvm.org/docs/ProgrammersManual.html#llvm-adt-stringref-h) assumed that `StringRef::data()` returns a null-terminated string.  However, there are still a few calls to `data()` remaining in [this block of debuginfo.cpp](https://github.com/JuliaLang/julia/blob/065da95d921b18ac82b19a0231fca85f40d9febc/src/debuginfo.cpp#L754).  Fixing these is a bit more complicated, as we'd like to set `name` and `filename` to be null terminated strings, but we do not necessarily have such strings available.  And if we were to allocate new strings, we'd need to change the API a bit and free the strings elsewhere.

**Comment by ihnorton** [comment] 2015-02-06 04:13
dupe of #9195 (pr welcome if you get around to it)

**Closed by ihnorton** 2015-02-06 04:13 UTC

**Comment by garrison** [comment] 2015-02-06 04:24
This is not the same issue as #9195.  Calling `StringRef::data()` and assuming it is null-terminated is the problem I am reporting here.  Perhaps one way of "fixing" the current issue would be to use `strndup` and create yet another memory leak in `debuginfo.cpp`, but I doubt that makes any sense.

**Comment by ihnorton** [comment] 2015-02-06 04:38
Fair enough, but the fix is the same - "we'd need to change the API a bit and free the strings elsewhere."

**Comment by ihnorton** [comment] 2015-02-06 04:44
I edited that issue to include this.

**Comment by garrison** [comment] 2015-02-06 04:45
Perfect, thanks @ihnorton.
