### ISSUE TITLE
Ref docstring should note clearly that it's an abstract type

### ISSUE THREAD

**Issue by DanielVandH** [JuliaLang/julia#55321] opened 2024-07-31 09:38 UTC
The docstring for `Ref` gives no indication that it's an abstract type (or, if it does and I've missed it, it certainly isn't clear). I think there should be a note or admonition warning that the type `Ref{T}` is an abstract type, since I don't believe it is as widely known that this is the case.

Indeed, searching for `::Ref` in package codes shows a good amount of code that uses it as the type for a field in a struct, which I imagine the majority of authors are doing under the impression that it's a concrete type

**Comment by MasonProtter** [comment] 2024-07-31 09:44
Just to lay some bread crumbs so it's easier to follow up, here's at least one connected issue: https://github.com/JuliaLang/julia/issues/49004

The docstring for `Ref` probably just needs to be totally rewritten. 

My preference would be that we just take the docstring from `Ref` and place it on `RefValue` instead, and then export `RefValue`. The docstring for `Ref` can then be rewritten from scratch.

**Comment by DanielVandH** [comment] 2024-07-31 09:50
Putting the docstring onto `RefValue`, and cleaning it up a bit, also has the benefit that it can be better explained how `Ref` is commonly used for allowing a field to be mutated in a `struct`, just like how `Ref` briefly mentions at the end that it is sometimes used in broadcasting.

**Comment by vtjnash** [comment] 2024-07-31 13:12
RefValue is not public, intentionally though. Users that want a mutable field should be using `mutable` since it is much faster than RefValue.

**Comment by MasonProtter** [comment] 2024-07-31 13:40
Why is `RefValue` intentionally not public though?



> Users that want a mutable field should be using `mutable` since it is much faster than RefValue.

Mutable fields are not the only use-case for something like this. For example, there's
```
const x::RefValue{T} = Ref{T}()
```
and many other legitimate reasons to want to have a zero-dimensional indexable, mutable container.

**Comment by MasonProtter** [comment] 2024-07-31 13:42
Another case is things like
```
function f(rx::Ref)
    x = rx[]
    do_something(x)
end
```
but since the contract for `Ref` is completely broken by all of its subtypes except `RefValue`, this is not actually a valid generic function, and it should **only** be accepting `f(::RefValue)`.

**Comment by DanielVandH** [comment] 2024-07-31 14:11
As mentioned, `Ref` is definitely still valuable for this purpose, and it's certainly used frequently enough that I think making `RefValue` could be valuable. Even if not, at the very least it would still be useful to clarify the type of `Ref` in its docstring - not everyone is aware of this. It doesn't help that a lot of abstract types have the prefix `Abstract` while `Ref` doesn't, making it something you'd have no reason to assume could be abstract in the first place.

Making `RefValue` public or otherwise is maybe worth its own issue since these are two separate problems

**Comment by vtjnash** [comment] 2024-08-02 20:39
> ```const x::RefValue{T} = Ref{T}()```

This probably should not be a legal expression anymore, since you are declaring it both mutable and constant, and Keno's changes are going to disallow that.

> it should only be accepting

There are many other subtypes of Ref that would work fine there. The `Ptr` case doesn't violate any API, it just doesn't have any data there accessible to Julia (similar to how other Ref objects will throw if the value contained inside is #undef or is referencing something out of bounds)

**Comment by KristofferC** [comment] 2024-08-02 21:27
> This probably should not be a legal expression anymore, since you are declaring it both mutable and constant,

Could you elaborate on this. What is different about this and a constant vector or dict? The constness is referring to the binding?

**Comment by vtjnash** [comment] 2024-08-02 21:57
After Kenow's change, the `::Type` part of the expression makes a mutable binding in one world. The `const` part then replaces and shadows that in a different world.

**Comment by MasonProtter** [comment] 2024-08-02 22:03
> This probably should not be a legal expression anymore, since you are declaring it both mutable and constant, and Keno's changes are going to disallow that.

That'd be quite the breaking change.

**Comment by johnomotani** [comment] 2024-09-28 14:53
> Users that want a mutable field should be using mutable since it is much faster than RefValue.

@vtjnash could you clarify this please? I thought the general performance advice is "use an immutable `struct` instead of a `mutable struct`". If I have some gigantic struct with 100 fields, and 99 of those can be immutable but the 100'th is a `Bool` I want to be able to toggle between true/false, your statement implies that I should use a `mutable struct` but I would find that surprising!

**Comment by vtjnash** [comment] 2024-09-28 15:21
Yes, a mutable struct would probably be much better there most of the time, even if only because of the number of constant fields. The general advice is wrong, since it only applies to specific cases (albeit frequent cases, it is not general)

**Comment by nsajko** [comment] 2024-09-29 05:20
Duplicate of #38133.

**Closed by nsajko** 2024-09-29 05:20 UTC
Labels: domain:docs

**Comment by DanielVandH** [comment] 2024-09-29 06:04
I don't see why this is a dupe of that issue? This is purely about asking that it be documeted properly.

**Comment by nsajko** [comment] 2024-09-29 06:12
This one has a better title and OP, but they seem to be the exact same issue.
