### ISSUE TITLE
libcurl problems with libgit2 on master

### ISSUE THREAD

**Issue by lkuper** [JuliaLang/julia#13472] opened 2015-10-07 00:27 UTC
I'm seeing the following issue when trying to use `Pkg.init()` on a fresh build of master:

```
$ ./julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+640 (2015-10-06 18:24 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 128f8c6 (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> Pkg.init()
INFO: Initializing package repository /home/lkuper/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:140E0114:SSL routines:SSL_shutdown:uninitialized)
 [inlined code] from libgit2/error.jl:96
 in clone at libgit2/repository.jl:185
 in clone at libgit2.jl:303
 in anonymous at pkg/dir.jl:49
 in cd at file.jl:22
 in init at pkg/dir.jl:47
 in init at pkg.jl:23
```

I started seeing this after pulling and rebuilding to fix the libgit2 SSL certificate issue in #13399.  I'm now seeing this error instead of the certificate error.  There's more discussion on that bug.

This is on Ubuntu 14.04, and I have `libssl-dev` installed.  I've already tried `make -C deps distclean-libgit2`.  I even did a `make distcleanall` to make extra sure.  

Before I deleted my `~/.julia/v0.5` directory (because I hoped that doing that and running `Pkg.init()` might solve the problem), I was seeing a similar error message from `Pkg.update()`.

I'm also having the same problem on CentOS with `openssl-devel` installed.

**Comment by tkelman** [comment] 2015-10-07 01:06
Can you try changing the branch and sha in `deps/libgit2.version` to `master` and ac69a82358ef444de433a8e0af62a4b6bd5c2c4e then `make -C deps distclean-libgit2 && make` ? @wildart was implying that maybe master of libgit2 would give a more informating error here.

**Comment by wildart** [comment] 2015-10-07 01:30
As I wrote in #13399, some connectivity problem raised an error which was overwritten by an incorrect SSL shutdown. SSL shutdown now is fixed a week ago in `master` branch, so correct error reporting is expected. However, `master` branch introduced some changes into fetch related structures, so julia segfaults now on libgit2 master build.
This patch should solve segfaults and get you to correct error report with libgit2 master branch:
```
@@ -179,16 +179,19 @@ immutable FetchOptions
     prune::Cint
     update_fetchhead::Cint
     download_tags::Cint
+    custom_headers::StrArrayStruct
 end
 FetchOptions(; callbacks::RemoteCallbacks = RemoteCallbacks(),
                prune::Cint = Consts.FETCH_PRUNE_UNSPECIFIED,
                update_fetchhead::Cint = one(Cint),
-               download_tags::Cint = Consts.REMOTE_DOWNLOAD_TAGS_AUTO
+               download_tags::Cint = Consts.REMOTE_DOWNLOAD_TAGS_AUTO,
+               custom_headers::StrArrayStruct=StrArrayStruct()
 ) = FetchOptions(one(Cuint),
                  callbacks,
                  prune,
                  update_fetchhead,
-                 download_tags)
+                 download_tags,
+                 custom_headers)
 
 immutable CloneOptions
     version::Cuint
```

**Comment by lkuper** [comment] 2015-10-07 23:41
@tkelman Thanks.  I just tried that and then built Julia with @wildart's patch.  Sure enough, I now see a more informative error message ("Connection timed out").  The problem is that under Julia 0.3.11 on the same machine with the same git configuration, `Pkg.init()`, `Pkg.update()`, etc., all work fine.  That's why I'm wondering if the issue could have been introduced in the changes to libgit2 somehow.  What else would be causing different versions of Julia to behave differently here?

**Comment by tkelman** [comment] 2015-10-07 23:45
It's almost certainly libgit2. You could try the release-0.4 branch (or rc4 binaries) which would be closer to master but without using libgit2 for Pkg, but it would most likely be consistent with 0.3.x. @wildart do you know if there some debug env var or build option that could get libgit2 to be more chatty about what's going on?

**Comment by lkuper** [comment] 2015-10-07 23:47
As mentioned in #13399, I'm behind a firewall and I have

```
[url "https://"]
	insteadOf = git://
```

in my ~/.gitconfig, so I guess I'm suspicious that somehow Julia 0.3.11 is seeing my .gitconfig while Julia master is not.

**Comment by lkuper** [comment] 2015-10-07 23:49
@tkelman Okay, I'll see what happens with v0.4.0-rc4.

**Comment by lkuper** [comment] 2015-10-08 01:04
Confirming that `Pkg.init()` and `Pkg.update()` work fine on v0.4.0-rc4.  So it seems like the problem is only on master.

**Comment by wildart** [comment] 2015-10-08 01:53
Ah, proxy. If `libgit2` was build with `libcurl` support, then a standard proxy configuration should work
```
HTTP_PROXY=http://proxy.mycompany:80
$ git config --global http.proxy $HTTP_PROXY
```

**Comment by lkuper** [comment] 2015-10-08 02:51
@wildart Aha!  I did not have libcurl.  A message about this goes by while libgit2 builds:

```
-- checking for module 'libcurl'
--   package 'libcurl' not found
```

but I didn't realize it was a problem.  Should libcurl be listed as a dependency in https://github.com/JuliaLang/julia#required-build-tools-and-external-libraries, at least with a note saying that users behind a firewall need it?

Unfortunately, on CentOS, after a seemingly successful `yum install libcurl` and `make -C deps distclean-libgit2`, I still see `package 'libcurl' not found` during the build.  On Ubuntu, the same thing happens after `apt-get install libcurl4-gnutls-dev`.

**Comment by tkelman** [comment] 2015-10-08 03:01
You probably need `libcurl-devel` or whatever other package provides the curl.pc (or libcurl.pc?) pkg-config file for libgit2's build to find it. Documenting this would be good if it's necessary for proxying, and we may also want to do something about this in the generic linux binaries. Can you test https://status.julialang.org/download/linux-x86_64 in your environment?

**Comment by tkelman** [comment] 2015-10-08 03:15
aha - try commenting out https://github.com/JuliaLang/julia/blob/fb4b161ece65a6e48451f97aa2bfd0ba986b2709/Make.inc#L204

**Comment by lkuper** [comment] 2015-10-08 03:44
I like how I'm apparently the first person in the world to try to use 0.5.0-dev behind a corporate firewall.

**Comment by tkelman** [comment] 2015-10-08 03:52
Thanks for being the guinea pig! 0.4.0 is imminent (like, later tonight if my currently running pkgeval jobs look good) so I think most people interested in stability have been working from release-0.4. We also only merged #11196 last week, so the issues aren't taking all that long to discover.

**Comment by wildart** [comment] 2015-10-08 04:12
@lkuper Appreciated 
<img src="https://cloud.githubusercontent.com/assets/38350/10357486/aa6a7e2c-6d50-11e5-9d6e-6fc68c24483e.png" width="250">

**Comment by felipenoris** [comment] 2015-10-13 00:25
Apparently this is why I couldn't compile Julia on windows on https://github.com/JuliaLang/julia/pull/13501.
I tried to compile Julia on a fresh ubuntu VM and I got this:
```
patching file CMakeLists.txt
Hunk #1 FAILED at 217.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:328 (find_package_handle_standard_args)
  CMakeLists.txt:220 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/felipenoris/Documents/julia/deps/build/libgit2/CMakeFiles/CMakeOutput.log".
Makefile:2036: recipe for target 'build/libgit2/Makefile' failed
make[1]: *** [build/libgit2/Makefile] Error 1
Makefile:78: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

This is a fresh Ubuntu 15 VM with this already applied:
```
sudo apt-get install git gfortran m4 cmake curl
```

Looking for libcurl I got this:
```
/$ sudo find . -iname '*libcurl*'
./var/lib/dpkg/info/libcurl3-gnutls:i386.postinst
./var/lib/dpkg/info/libcurl3:i386.list
./var/lib/dpkg/info/libcurl3-gnutls:i386.symbols
./var/lib/dpkg/info/libcurl3:i386.postrm
./var/lib/dpkg/info/libcurl3-gnutls:i386.postrm
./var/lib/dpkg/info/libcurl3:i386.postinst
./var/lib/dpkg/info/libcurl3-gnutls:i386.shlibs
./var/lib/dpkg/info/libcurl3:i386.md5sums
./var/lib/dpkg/info/libcurl4-openssl-dev:i386.list
./var/lib/dpkg/info/libcurl3:i386.symbols
./var/lib/dpkg/info/libcurl3:i386.shlibs
./var/lib/dpkg/info/libcurl3-gnutls:i386.md5sums
./var/lib/dpkg/info/libcurl4-openssl-dev:i386.md5sums
./var/lib/dpkg/info/libcurl3-gnutls:i386.list
./var/cache/apt/archives/libcurl3-gnutls_7.38.0-3ubuntu2.2_i386.deb
./var/cache/apt/archives/libcurl4-openssl-dev_7.38.0-3ubuntu2.2_i386.deb
./var/cache/apt/archives/libcurl3_7.38.0-3ubuntu2.2_i386.deb
./usr/share/aclocal/libcurl.m4
./usr/share/doc/libcurl3-gnutls
./usr/share/doc/libcurl3
./usr/share/doc/libcurl4-openssl-dev
./usr/share/lintian/overrides/libcurl3-gnutls
./usr/share/lintian/overrides/libcurl3
./usr/lib/i386-linux-gnu/libcurl.so.4.3.0
./usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
./usr/lib/i386-linux-gnu/libcurl.so.4
./usr/lib/i386-linux-gnu/libcurl-gnutls.so.4.3.0
./usr/lib/i386-linux-gnu/libcurl.a
./usr/lib/i386-linux-gnu/pkgconfig/libcurl.pc
./usr/lib/i386-linux-gnu/libcurl.so
./usr/lib/i386-linux-gnu/libcurl-gnutls.so.3
./usr/lib/i386-linux-gnu/libcurl.so.3
./usr/lib/i386-linux-gnu/libcurl.la
```

**Comment by tkelman** [comment] 2015-10-13 00:29
@felipenoris that's a different issue #13389, you need to install `libssl-dev`

**Comment by SamSchlegel** [comment] 2015-11-06 17:30
Just ran into this issue building on Scientific Linux 6 on a machine that's behind a proxy. As tkelman mentioned, the problem is due to the change in https://github.com/JuliaLang/julia/commit/bb4eddcfae5bf536796f1867abefa702616620f4. Setting `PKG_CONFIG_LIBDIR` to only look at our libraries means that `libgit2` won't find `libcurl`. Due to [libgit2#2555](https://github.com/libgit2/libgit2/issues/2555) this means it will build without proxy support.

Commenting the `PKG_CONFIG_LIBDIR` line from `Make.inc` does fix the issue, but I think the better solution is to set `PKG_CONFIG_PATH` instead as this will allow our libraries to take precedence, but won't disable inclusion of system libraries as a fallback.

**Comment by SamSchlegel** [comment] 2015-11-06 17:36
Though that would need to be tested to see if it would introduce a regression with respect to #12514

**Comment by tkelman** [comment] 2015-11-10 04:27
Or we could make the setting mac only. I'm not sure what the proxy situation is like on mac, whether libgit2 needs libcurl there.

**Comment by kpamnany** [comment] 2015-11-10 19:42
I needed to revert https://github.com/JuliaLang/julia/pull/12590 on both CentOS 7 and OS X to get libgit2 to find libcurl to get Pkg working behind our firewall.

**Comment by JeffBezanson** [comment] 2016-01-05 22:47
Bump. I also just needed to comment out the `PKG_CONFIG_LIBDIR` line.

**Comment by tkelman** [comment] 2016-01-05 22:53
Once libgit2 0.24.0 is out I plan on modifying our libgit2 build to link against mbedtls rather than openssl. I'm not sure what the proxy situation is going to be - if we need to link to libcurl, it's going to take a bit of work to get `make binary-dist` to still work for creating standalone binaries.

**Comment by mdcfrancis** [comment] 2016-02-02 16:30
mbedtls does not fix the proxy issue - you will still need curl. The code in libgit2 does not deal with proxies.

**Comment by lkuper** [comment] 2016-02-03 20:41
Super-late follow-up: @tkelman was correct in https://github.com/JuliaLang/julia/issues/13472#issuecomment-146404141 that I needed `libcurl-devel`.  To recap, just in case it helps anyone else, these were the steps I needed to follow to work around this issue on CentOS:

- `sudo yum install libcurl-devel`
- comment out the `PKG_CONFIG_LIBDIR` line in Make.inc
- `make -C deps clean-libgit2 && make clean && make`

**Comment by Ayush-iitkgp** [comment] 2016-03-03 12:55
@lkuper thanks. Your solution did work on Ubuntu 14.04. Instead of first command, Ubuntu users need to run
**sudo apt-get install libcurl3
sudo apt-get install libcurl4-openssl-dev **

**Comment by wildart** [comment] 2016-03-24 10:09
I do not think that `libgit2` will have a native proxy support any time soon, or ever. So, if we want proxy support, we need to add `libcurl` as the dependency. 
BTW, last time I checked major Linux distros, latest `libgit2` (0.23 or 0.24) is built with `libssl`, `libssh` and `libcurl` support which means in future we can drop building our `libgit2` binary.

**Comment by tkelman** [comment] 2016-03-24 11:05
We're going to need to support distros like centos 6 for a very long time, unfortunately. So no, we can't rely on system libgit2 being new enough everywhere.

**Comment by StefanKarpinski** [comment] 2016-03-24 13:29
Getting things from the Internet is a pretty basic requirement these days, so including `libcurl` seems like a plausible thing to do, especially if it means we can avoid some of the cross-platform connectivity issues that some people seems to be having since we switched to `libgit2`. Even better if we can make proxy support smoother and/or more transparent.

**Comment by mdcfrancis** [comment] 2016-03-24 13:43
Given the issues we have had with working behind a proxy, having libcurl in the core set of libraries would definitely help. There are many gotchas in the http world.

**Comment by tkelman** [comment] 2016-03-25 08:42
Curl is one more thing to build, but we can probably manage it. The tricky part is actually building a version of curl that's useful enough and making it self-contained so it can be redistributed properly. Curl by itself doesn't do https, it needs a separate TLS library AIUI, and I'm not sure whether it'll be possible to make curl use mbedtls if we get libgit2 to do so. Worth trying. There's also the option of relying on a system version of libcurl being present (at least on linux) and trying to get libgit2 to use that for proxy support, since curl's api is much more stable across distro versions than libgit2's.

**Comment by nalimilan** [comment] 2016-03-25 11:15
I guess we can count on libcurl being available on any Linux distro, right? Windows is the place where shipping our own library would really help IIUC.

**Comment by wildart** [comment] 2016-03-25 12:20
I agree with @nalimilan, there is no need for building `libcurl`, the system library will suffice.

**Comment by tkelman** [comment] 2016-03-28 13:09
What's the situation with proxies on Windows? I have no way of testing any of this.

**Comment by SamSchlegel** [comment] 2016-03-28 20:26
The winhttp transport in libgit2 supports proxying http requests, so it should be fine.

**Comment by nalimilan** [comment] 2016-03-29 09:21
> I believe they get their proxy info from the git config as opposed to the system config, however.

That would be a showstopper. People should be able to install packages without editing their git configuration (and without using git at all).

**Comment by SamSchlegel** [comment] 2016-03-29 10:26
libgit2 attempts to get the proxy configuration in three steps :

1. Checks the git config for a `remote.<name>.proxy` config setting
2. Checks for an `http.proxy` config setting.
3. Checks for an HTTP_PROXY/HTTPS_PROXY environment variable

(Source: https://github.com/libgit2/libgit2/blob/master/src/remote.c#L786)

It will take the first one that it can find. Most users who deal with this issue also have to set the git proxy to access other external non-http(s) repos. For users who don't use git, an environment variable seems perfectly reasonable.

**Comment by tkelman** [comment] 2016-08-01 11:28
If there's any good news here, it's that recent versions of libcurl support linking against mbedtls (https://github.com/curl/curl/pull/496) so this might not actually take all that much addition to the build system to get working.

**Comment by mdcfrancis** [comment] 2016-08-02 17:35
Is there any update here - given the 0.5.0-rc0 does not work from behind a firewall ?

**Comment by mdcfrancis** [comment] 2016-08-02 17:39
For reference, we typically have both proxy information in the git config and also as the standard using environment, HTTP_PROXY, HTTPS_PROXY and NO_PROXY

**Comment by aviks** [comment] 2016-08-02 17:55
@mdcfrancis is this nor working for you on Windows or Linux?

**Comment by mdcfrancis** [comment] 2016-08-02 17:59
This is Linux - I've not tried on windows as we are not typically running on that platform.

**Comment by tkelman** [comment] 2016-08-02 19:21
There is no active pull request in progress to address this as far as I know.

**Comment by kpamnany** [comment] 2016-08-02 20:34
I've had to revert https://github.com/JuliaLang/julia/pull/12590 on my MBP every time I've built Julia in order to get proxy support working. I'm not sure whose Mac https://github.com/JuliaLang/julia/issues/12514 was causing problems on, but the "fix" (in https://github.com/JuliaLang/julia/pull/12590) causes problems on mine.

**Comment by tkelman** [comment] 2016-08-02 20:46
If we were to link against system libcurl, then our binaries wouldn't be self-contained. So I don't think straight reversion is a valid solution, though it's fine as a local workaround if you're building from source. We'd need to either allow linking against the system libcurl but be sure we copy the necessary pieces from the buildbot system into the binaries so that they're functional when used elsewhere; or add a source build of libcurl in the makefiles here (likely linking against our source build of mbedtls, to make it more feasible to not depend on openssl in the future).

**Comment by ViralBShah** [comment] 2016-08-02 21:18
I suspect this can be a 0.5.x feature? Source build of libcurl seems to be the most robust solution.

**Comment by tkelman** [comment] 2016-08-02 21:24
Yeah I suspect this would be backportable.

**Comment by mdcfrancis** [comment] 2016-08-02 21:41
Just to be clear as it stands 0.5.0 does not work (and has not worked since Oct 2015) and if it goes out in this state it will continue to not work for anybody who is behind a firewall (short of them building Julia locally and changing the Make.ini)- libcurl works across platforms (including windows) and correctly abstracts many of these issues away. I don't understand why there is such a reluctance to use it? FWIW the Julia webstack moving away from libcurl to mbedtls is also broken under some conditions behind firewalls.

**Comment by tkelman** [comment] 2016-08-02 21:58
I wouldn't describe it as "reluctance to use it," just a lack of having dedicated the resources to solve this properly yet. The fix would resemble https://github.com/JuliaLang/julia/pull/17391/files (or about half of it). We got SSH mostly working, we haven't gotten proxies done yet.

**Comment by mdcfrancis** [comment] 2016-08-02 22:02
It looks like the suggested work around may not work for local git repos see my issue I just opened.

**Comment by wildart** [comment] 2016-08-03 01:02
I might be able to add basic proxy support in scope of #17471.

**Comment by StefanKarpinski** [comment] 2016-08-03 04:58
This libgit2 for network transport situation is a nightmare. Can we just bundle git and go back to using it for transport operations? It was always pretty good at those anyway – the things it's lousy at is all the little operations on local git repos.

**Comment by tkelman** [comment] 2016-08-03 05:30
> It was always pretty good at those anyway

Except for https://github.com/JuliaLang/julia/issues/17142 and https://github.com/JuliaLang/julia/issues/14616 and https://github.com/JuliaLang/julia/issues/13949

**Comment by ViralBShah** [comment] 2016-08-03 11:29
I think we are pretty close. I had to apply a small one line patch to mbedtls and building libcurl with mbedtls works out easily. Next step is to get libgit2 to use libcurl. If all goes well, I will put up a PR by tomorrow. I don't think we should have this block the 0.5 release, but it can be in 0.5.1.

**Comment by mdcfrancis** [comment] 2016-08-03 12:34
@ViralBShah - so based on this I take it that 0.5.0 is officially NOT supported behind firewalls and it may be worth coming back for 0.5.1, but that is assuming that the other git issues are also resolved.

**Comment by mdcfrancis** [comment] 2016-08-03 12:52
By my definition this is a breaking change, we have gone from a working system to one that no longer provides even basic functionality e.g. Pkg.init() no longer functions. The SSL changes for libgit2 now means that you have to either run an ssl_agent on Ubuntu or keep hitting enter for each local git repo. These are both serious regressions, to the point where I can not even consider upgrading.

**Comment by ViralBShah** [comment] 2016-08-03 13:55
My only point was whether this is an API regression for the 0.5 release process, which it is not, and that allows us to quickly release the missing functionality later.

Yes, from a user standpoint, it is a regression from 0.4. Depending on how soon we have this ready and tested, we can consider it for inclusion in 0.5, or in 0.5.1. We'll know in a couple of days.

**Comment by tkelman** [comment] 2016-08-03 14:26
A pure-Julia TLS implementation is a big job, what's the benefit exactly compared to building and shipping a few widely-used, well-established C libraries?

**Comment by wildart** [comment] 2016-08-03 14:31
So we handle our own code and do wait until C-libraries will add any related to us changes in their well-established code base.

**Comment by ViralBShah** [comment] 2016-08-03 14:41
#17783 should hopefully help resolve this by building curl in the julia tree. Need help from folks to test it on various platforms and behind firewalls.

**Comment by mdcfrancis** [comment] 2016-08-03 14:51
I'm a little confused, why mbedtls? Why not a regular build of curl ?

**Comment by tkelman** [comment] 2016-08-03 14:57
The rest of the Julia webstack is using mbedtls, and openssl has a sometimes-problematic license https://github.com/JuliaLang/julia/issues/10763 in that it's not entirely GPL compatible.

**Comment by mdcfrancis** [comment] 2016-08-03 15:28
Personally I'd far rather see the GPL licensed libraries be external from core Julia ... they confuse the whole 'it's MIT licensed' part in any case. The julia webstack also has issues with proxies ...

**Comment by tkelman** [comment] 2016-08-03 15:52
They will be, but they aren't yet (at least not by default). This same licensing problem means the libgit2 packaged in debian doesn't even support https - https://github.com/JuliaLang/julia/issues/17661. mbedtls would be a path to fixing that, if we can get it upstreamed.

**Comment by ViralBShah** [comment] 2016-08-03 18:14
@mdfrancis Having mbedtls used in Julia does not make Julia GPL. As you already know, this has been amply discussed elsewhere. Let's not restart this discussion here.

**Comment by mdcfrancis** [comment] 2016-08-04 13:08
@ViralBShah yes should not have brought that up here - mebdtls is apache, so no issue.

**Closed** 2016-08-07 11:11 UTC
Labels: libgit2, packages

**Comment by ViralBShah** [comment] 2016-08-07 16:28
@lkuper @mdcfrancis Would be great if you can try out the latest nightlies tomorrow, now that curl support is on master.

**Comment by mdcfrancis** [comment] 2016-08-07 16:52
Will build and test tomorrow.

**Comment by mdcfrancis** [comment] 2016-08-08 13:31
@ViralBShah I just tested against master and I can confirm that it works in my environment. 
```

michael@shadow:~/src/julia5/deps/build/libgit2-211e117a0590583a720c53172406f34186c543bd$ ldd  libgit2.so
	linux-vdso.so.1 =>  (0x00007ffe9cf86000)
	libcurl.so.4 => /home/michael/src/julia5/usr/lib/libcurl.so.4 (0x00007f9470df0000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9470bd7000)

```
libcurl apears to be linking the system tls library is that expected ? 

```
michael@shadow:~/src/julia5/deps/build/libgit2-211e117a0590583a720c53172406f34186c543bd$ ldd  /home/michael/src/julia5/usr/lib/libcurl.so.4 
	linux-vdso.so.1 =>  (0x00007fff40193000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f726cd81000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f726cb67000)
	libssl.so.1.0.0 => /home/michael/src/julia5/usr/lib/libssl.so.1.0.0 (0x00007f726c908000)
	libcrypto.so.1.0.0 => /home/michael/src/julia5/usr/lib/libcrypto.so.1.0.0 (0x00007f726c52c000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f726c31d000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f726c0cc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f726beb3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f726baee000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f726b830000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f726b5b0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f726b3ac000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f726b191000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f726af76000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f726ad38000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f726ab1a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f726d21c000)

```

We may want to re-open this issue till it is backported - the automatic issue closing based on commit message seems to have closed the issue.

**Comment by wildart** [comment] 2016-08-08 13:37
@mdcfrancis How come your `libgit2` build does not have any dependency on TLS library? `libcrypto` should be referenced.

@ViralBShah It looks like `pkg-config` picks system libraries for `libcurl` instead of `mbedtls`.

**Comment by mdcfrancis** [comment] 2016-08-08 13:41
It looks like unbuntu is shipping gnutls
`
 libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f726b830000)`

**Comment by tkelman** [comment] 2016-08-08 13:42
Needs a bit more work on top of #17783 to actually make sure the right things are getting linked. Linking to gnutls is not what we want, we should be ensuring curl doesn't link to system libraries so our binaries are self-contained.

**Comment by mdcfrancis** [comment] 2016-08-08 13:42
I truncated the ldd, here is the full one 

```
michael@shadow:~/src/julia5/deps/build/libgit2-211e117a0590583a720c53172406f34186c543bd$ ldd  /home/michael/src/julia5/usr/lib/libcurl.so.4 
	linux-vdso.so.1 =>  (0x00007fff40193000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f726cd81000)
	librtmp.so.0 => /usr/lib/x86_64-linux-gnu/librtmp.so.0 (0x00007f726cb67000)
	libssl.so.1.0.0 => /home/michael/src/julia5/usr/lib/libssl.so.1.0.0 (0x00007f726c908000)
	libcrypto.so.1.0.0 => /home/michael/src/julia5/usr/lib/libcrypto.so.1.0.0 (0x00007f726c52c000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f726c31d000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f726c0cc000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f726beb3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f726baee000)
	libgnutls.so.26 => /usr/lib/x86_64-linux-gnu/libgnutls.so.26 (0x00007f726b830000)
	libgcrypt.so.11 => /lib/x86_64-linux-gnu/libgcrypt.so.11 (0x00007f726b5b0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f726b3ac000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f726b191000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f726af76000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f726ad38000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f726ab1a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f726d21c000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f726a906000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f726a6c4000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f726a4bf000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f726a2b6000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f726a02e000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f7269d8d000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f7269b89000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f7269956000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f7269741000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f7269539000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f7269310000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f7269102000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f7268eb9000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f7268c00000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f72689c7000)

```

**Comment by mdcfrancis** [comment] 2016-08-08 13:44
This is great progress though, as now the proxy support and ssh for libgit2 are working with combined internal and external repositories.

**Comment by wildart** [comment] 2016-08-08 15:48
Surely, we didn't what `libcurl` to link to openssl binaries copied by `libgit2` build script
```
 libssl.so.1.0.0 => /home/michael/src/julia5/usr/lib/libssl.so.1.0.0 (0x00007f726c908000)
 libcrypto.so.1.0.0 => /home/michael/src/julia5/usr/lib/libcrypto.so.1.0.0 (0x00007f726c52c000)
```

**Comment by tkelman** [comment] 2016-08-08 15:52
I guess that's fine for now while we still have those, but our intent was to have it link against mbedtls for consistency across both osx and linux. Clearly we're not invoking curl's configure script in a specific enough way for it to do what we actually want it to do.

**Comment by ViralBShah** [comment] 2016-08-08 17:09
I find `cmake` a bit more difficult than `autoconf` personally, which is perhaps why this needs someone else to do all the right cmake incantations to pick the right libraries.

**Comment by tkelman** [comment] 2016-08-08 17:20
You used configure to build curl.

**Comment by ViralBShah** [comment] 2016-08-08 18:36
Ah then it was libgit2 that was using cmake to detect curl.

**Comment by lkuper** [comment] 2016-08-09 01:33
@ViralBShah I'm building master now and ought to be able to try it out tomorrow.  Have to rebuild LLVM first. :)

**Comment by lkuper** [comment] 2016-08-10 00:30
Just built master and can confirm that `Pkg.init()` works behind our firewall without my needing to manually change anything in Make.inc.  Thanks to everyone for their hard work fixing this issue. :+1:

**Comment by StefanKarpinski** [comment] 2016-08-10 00:37
I second that – especially @wildart, @keno and @tkelman for all the hard work.

**Comment by wildart** [comment] 2016-08-10 00:42
Kudos to @ViralBShah as well.

**Comment by Ayush-iitkgp** [comment] 2016-09-03 19:32
@lkuper Could you please guide me on how you got the latest changes working?
I uncommented the `PKG_CONFIG_LIBDIR` line in Make.inc
and ran `make -C deps clean-libgit2 && make clean && make`

and ended up screwing my working julia set up.

**Comment by lkuper** [comment] 2017-04-19 18:15
BTW, is there any workaround for this issue on 0.5 if one is *not* building Julia from source?

**Comment by tkelman** [comment] 2017-04-19 19:42
Can you be more specific? What's the issue exactly?

**Comment by lkuper** [comment] 2017-04-19 20:34
@tkelman I installed Julia 0.5.1 on Ubuntu 16.04 via [ppa:staticfloat/juliareleases](https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases).  I ran `sudo apt-get install libcurl3` and `sudo apt-get install libcurl4-openssl-dev`.  I think I have all the correct proxy-related env vars and git proxy settings (`HTTP_PROXY`, `git config --global http.proxy $HTTP_PROXY`, and so on_.  When I try to install a package via `Pkg.add`, I get:

```
ERROR: GitError(Code:ERROR, Class:OS, Failed to connect to github.com: Connection timed out)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:191
 in #clone#112(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at ./<missing>:0
 in (::Base.Pkg.Dir.##4#6{String,String})() at ./pkg/dir.jl:49
 in cd(::Base.Pkg.Dir.##4#6{String,String}, ::String) at ./file.jl:59
 in init(::String, ::String) at ./pkg/dir.jl:47
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:28
 in add(::String) at ./pkg/pkg.jl:100
```

The [above fix](https://github.com/JuliaLang/julia/issues/13472#issuecomment-179454292) involves modifying `Make.inc` and rebuilding Julia, so I'm wondering if there is a fix for a non-source install of Julia.

**Comment by tkelman** [comment] 2017-04-19 20:53
Don't use the ppa, that's not been recommended for a long time. Try with the generic linux binaries.

**Comment by lkuper** [comment] 2017-04-19 21:22
@tkelman Thanks for the heads up; that fixed it!  I had no idea the PPA was no longer recommended.
