### ISSUE TITLE
Base.summarysize() incorrect for Array of structs

### ISSUE THREAD

**Issue by herzfeldd** [JuliaLang/julia#41941] opened 2021-08-20 01:40 UTC
I have been trying to determine why a program that I am running reports a 4x difference in the amount of resident memory that Linux says Julia is requesting versus the output of `Base.summarysize()`. I am unclear if this is a bug or just my naivete:

Declare a new structure with a single `Dict` child:
```julia
struct Container{K, V}
    child::Dict{K, V}
end
```
Create two examples, each with 1000 byte random data:
```julia
container_1 = Container(Dict(:test => rand(UInt8, 1000)))
container_2 = Container(Dict(:test => rand(UInt8, 1000)))
```

Asking for their size yield 1504 and 1504 for `container_1` and `container_2`. However,
```julia
Base.summarysize([container_1, container_2])
````
returns 56 bytes rather than a value greater than 1504 + 1504. 

Note that using standard `Dicts` works fine:
```julia
dict_1 = Dict(:test => rand(UInt8, 1000))
dict_2 = Dict(:test => rand(UInt8, 1000))
println(Base.summarysize(dict_1))
println(Base.summarysize(dict_2))
println(Base.summarysize([dict_1, dict_2]))
```
Returns, as expected: `dict_1` => 1496 bytes, `dict_2` => 1496 bytes, and `[dict_1, dict_2]` => 3048 bytes.

Version info:
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 3
```

**Comment by vtjnash** [comment] 2021-08-20 02:53
Duplicate of #40773

**Closed by vtjnash** 2021-08-20 02:53 UTC
