### ISSUE TITLE
Surprising and inconsistent variable scope behavior

### ISSUE THREAD

**Issue by marekpetrik** [JuliaLang/julia#47733] opened 2022-11-29 04:42 UTC
Tested with Julia 1.8.3, and 1.9 alpha

## Example 1: Global variable created before assignment

I understand that the scope of the variables in Julia is a tricky issue. However, I was surprised to see that a variable can be assigned from a nested scope even before it is created. 

Running the following code
```julia
function f()
    for i ∈ 1:10
        t = i
    end
    return t
    t = 1
end
@show f()
```
returns 
```
julia> f() = 10
```
I find this quite counterintuitive since the assignment `t = 1` is never actually executed.  Even though this behavior is somewhat unexpected, I guess it is consistent with the discussion at [Scope of Variables](https://docs.julialang.org/en/v1/manual/variables-and-scoping/) starting with the paragraph:
"This demonstrates some important aspects of scope: in a scope, each variable can only have one meaning, and that meaning is determined regardless of the order of expressions."

The following example illustrates an apparent inconsistency.

## Example 2: Global variable not created before assignment

Assuming that the meaning of a variable in a scope is determined regardless of the order of the statements, I would expect the following code to perform identically to Example 1
```julia
function f_global()
    for i ∈ 1:10
        global t = i
    end
    return t
    t = 1
end
@show f_global()
```
However, this function fails with an error that `t` is not defined. 

I cannot tell which one of the two behaviors is intended, but the inconsistency seems very much like a bug to me. 

## Example 3: Error prone behavior

The out-of-order variable scope in Example 1 may appear benign, but it can introduce some unexpected behavior when loops are run in parallel. For example, the following code fails for reasons that may not be readily apparent or intuitive (when run with `julia -t=4`)
```julia
function f_race()
    Threads.@threads for i ∈ 1:10
        t = i
        sleep(0.1)
        @assert t == i
    end
    t = 1
end
@show f_race()
```

**Comment by elextr** [comment] 2022-11-29 07:45
From my inexperienced viewpoint, this is intended and is documented.

From your example 1 in [here](https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Local-Scope) it says "This is true even if the outer local is declared after (in the sense of textually below) an inner block." which is the case for `t = 1`.  Also "you can only shadow a local by explicitly declaring a new local in a nested scope with the local keyword." so the inner assignment is not a declaration. The fact that `t = 1` is never executed doesn't matter, Julia is not a dynamic language like Python, declarations only need to exist, not be executed.

Example 2 you have specified that you want to assign to a global `t`, but it does not exist, so you get an error.  As the docs say the rule above applies to nested _local_ scopes, not global scope.  

Example 3 certainly illustrates racey behaviour that will occur when concurrent executions perform uncoordinated modification of the same variable.  The only "issue" is the case that the programmer might miss the effect of the following declaration.

**Comment by JeffBezanson** [comment] 2022-11-30 20:54
Example 2 is ok because inner local scopes can override outer scopes; for example
```
julia> let x = 1
        for i = 1:1
         local x = 2
        end
        x
       end
1
```

here the `local` (or equivalently `global`) declaration only applies to the scope inside the `for` loop. However if there is no declaration inside the loop, variables are inherited from the outer scope. So everything here works as intended AFAICT.

**Closed by JeffBezanson** 2022-11-30 20:54 UTC
