### ISSUE TITLE
"Edit on GitHub" button on Standard Library pages are broken

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/julia#51372] opened 2023-09-18 16:55 UTC
It looks like every "Edit on GitHub" button on Standard Library pages are broken.
For example:
on `https://docs.julialang.org/en/v1/stdlib/Logging/`, it goes to `https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.9/Logging/docs/src/index.md`

**Comment by LilithHafner** [comment] 2023-09-18 18:02
Duplicate of #50035

**Closed by LilithHafner** 2023-09-18 18:02 UTC
Labels: doc, stdlib
