### ISSUE TITLE
REPL error upon tab-completion of incomplete macro

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#34197] opened 2019-12-25 17:39 UTC
```julia
julia> @Base.syn┌ Error: Error in the keymap
│   exception =
│    LoadError: UndefVarError: @Base not defined
│    Stacktrace:
│     [1] top-level scope
│     [2] lower at ./meta.jl:123 [inlined]
│     [3] get_type(::Expr, ::Module) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPLCompletions.jl:421
│     [4] complete_symbol(::String, ::REPL.REPLCompletions.var"#21#25", ::Module) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPLCompletions.jl:122
│     [5] completions(::String, ::Int64, ::Module) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPLCompletions.jl:703
│     [6] completions(::String, ::Int64) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPLCompletions.jl:573
│     [7] complete_line(::REPL.REPLCompletionProvider, ::Any) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:372
│     [8] complete_line(::REPL.LineEdit.PromptState, ::Any) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:329
│     [9] complete_line(::REPL.LineEdit.MIState) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:320
│     [10] edit_tab(::REPL.LineEdit.MIState, ::Any, ::Any) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2032 (repeats 2 times)
│     [11] (::REPL.LineEdit.var"#109#162")(::Any, ::Any, ::Vararg{Any,N} where N) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2073
│     [12] #invokelatest#1 at ./essentials.jl:712 [inlined]
│     [13] invokelatest at ./essentials.jl:711 [inlined]
│     [14] (::REPL.LineEdit.var"#22#23"{REPL.LineEdit.var"#109#162",String})(::Any, ::Any) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:1364
│     [15] prompt!(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2446
│     [16] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2349
│     [17] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:1055
│     [18] run_repl(::REPL.AbstractREPL, ::Any) at /home/keno/julia/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:206
│     [19] (::Base.var"#766#768"{Bool,Bool,Bool,Bool})(::Module) at ./client.jl:383
│     [20] #invokelatest#1 at ./essentials.jl:712 [inlined]
│     [21] invokelatest at ./essentials.jl:711 [inlined]
│     [22] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:367
│     [23] exec_options(::Base.JLOptions) at ./client.jl:305
│     [24] _start() at ./client.jl:484
│    in expression starting at none:1
└ @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.4/REPL/src/LineEdit.jl:2448
```

**Comment by cafaxo** [comment] 2019-12-25 20:20
Is this a duplicate of #27184?

**Comment by Liozou** [comment] 2021-12-24 13:56
Closing as duplicate since #40621 fixed this issue (and is backported).

**Closed by Liozou** 2021-12-24 13:56 UTC
Labels: REPL
