### ISSUE TITLE
Specialization for keyword arguments of the form Type{T}

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#39866] opened 2021-03-01 13:03 UTC
I observed some unexpected specialization behavior with keyword arguments.
```julia
julia> function f(x; as::Type{T} = Int) where {T}
         return T(x)
       end
```
Then
```julia
julia> @code_warntype f(1, as = Float64)
```
seems to indicate that it is not really specializing, but juggling around with `DataType`. I would have expected this with just `as::Type = Int` because of some specialization heuristic I know from positional arguments.

Is this intended? Or maybe `@code_warntype` is lying to me? Reproduced on julia 1.5 and 6 days old master.

Edit: Maybe this is https://github.com/JuliaLang/julia/issues/37797? Don't know enough about the internals.

**Comment by jakobnissen** [comment] 2021-03-01 15:15
Duplicate of https://github.com/JuliaLang/julia/issues/32834, I think.

**Comment by thofma** [comment] 2021-03-02 08:25
Why? OP in #32834 says
> @code_typed shows you fully specialized code, even though in reality this call will not be specialized

On the other hand I am asking why my example does not specialize (in my example `@code_warntype` is not showing fully specialized code as in #32834).

**Closed** 2023-03-10 16:20 UTC
