### ISSUE TITLE
WARNING: deprecated syntax "{a,b, ...}"

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#11869] opened 2015-06-25 22:51 UTC
These warnings are being triggered in the right place?

>WARNING: deprecated syntax "{a,b, ...}" at /home/julio/.julia/v0.4/ImageQuilting/src/iqsim.jl:62.
Use "Any[a,b, ...]" instead.

>WARNING: deprecated syntax "{a,b, ...}" at /home/julio/.julia/v0.4/ImageQuilting/src/iqsim.jl:126.
Use "Any[a,b, ...]" instead.

>WARNING: deprecated syntax "{a,b, ...}" at /home/julio/.julia/v0.4/ImageQuilting/src/iqsim.jl:133.
Use "Any[a,b, ...]" instead.

>WARNING: deprecated syntax "{a,b, ...}" at /home/julio/.julia/v0.4/ImageQuilting/src/iqsim.jl:140.
Use "Any[a,b, ...]" instead.

>WARNING: deprecated syntax "{a,b, ...}" at /home/julio/.julia/v0.4/ImageQuilting/src/iqsim.jl:152.
Use "Any[a,b, ...]" instead.

>WARNING: deprecated syntax "{a,b, ...}" at /home/julio/.julia/v0.4/ImageQuilting/src/iqsim.jl:152.
Use "Any[a,b, ...]" instead.

>WARNING: deprecated syntax "{a,b, ...}" at /home/julio/.julia/v0.4/ImageQuilting/src/iqsim.jl:212.
Use "Any[a,b, ...]" instead.

The source code: https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl

**Comment by juliohm** [comment] 2015-06-29 03:01
The associated lines:

* https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L62
* https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L126
* https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L133
* https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L140
* https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L152
* https://github.com/juliohm/ImageQuilting.jl/blob/master/src/iqsim.jl#L212

What I can do avoid the warnings?

**Comment by yuyichao** [comment] 2015-06-29 03:06
> These warnings are being triggered in the right place?

They are just off by one line.

> What I can do avoid the warnings?

Fix the deprecated syntax as suggested? I think `Any[...]` works on 0.3 as well.

**Comment by juliohm** [comment] 2015-06-29 03:09
@yuyichao, the first warning is off by one line, but that is not the issue. I don't see any problem with the current syntax, specially in the other warnings.

**Comment by yuyichao** [comment] 2015-06-29 03:30
You mean this?

* https://github.com/juliohm/ImageQuilting.jl/blob/c677e420f88954e4cd91a8107f73a72d9f52b8da/src/iqsim.jl#L63
* https://github.com/juliohm/ImageQuilting.jl/blob/c677e420f88954e4cd91a8107f73a72d9f52b8da/src/iqsim.jl#L127
* https://github.com/juliohm/ImageQuilting.jl/blob/c677e420f88954e4cd91a8107f73a72d9f52b8da/src/iqsim.jl#L134
* https://github.com/juliohm/ImageQuilting.jl/blob/c677e420f88954e4cd91a8107f73a72d9f52b8da/src/iqsim.jl#L141
* https://github.com/juliohm/ImageQuilting.jl/blob/c677e420f88954e4cd91a8107f73a72d9f52b8da/src/iqsim.jl#L153
* https://github.com/juliohm/ImageQuilting.jl/blob/c677e420f88954e4cd91a8107f73a72d9f52b8da/src/iqsim.jl#L221

I didn't try to run it myself but according to your post, they are all off by one line except the last one. 

Closing this one since it doesn't really belong to the issue tracker. If you need help fixing those, please post on [julia-user](https://groups.google.com/forum/?fromgroups=#!forum/julia-users). If you still see wrong line number reported for deprecation warning with latest master, please feel free to file a separate issue for that.

**Closed by yuyichao** 2015-06-29 03:30 UTC

**Comment by juliohm** [comment] 2015-06-29 03:33
Thank you @yuyichao, now I see that all the warnings are off by one. Sorry for the misunderstanding.

**Comment by juliohm** [comment] 2015-06-29 03:37
@yuyichao , what about the last occurrence?

**Comment by yuyichao** [comment] 2015-06-29 03:40
What about it?

https://github.com/juliohm/ImageQuilting.jl/blob/c677e420f88954e4cd91a8107f73a72d9f52b8da/src/iqsim.jl#L221 ?

**Comment by juliohm** [comment] 2015-06-29 03:44
I don't know how line 212 is related to 221, good catch!

**Comment by yuyichao** [comment] 2015-06-29 03:49
As I said, if you can consistently see incorrect line number being reported for deprecation warning without macro. Feel free to file an issue for that.

I think @Keno is trying to improve this so it might be better to test it on the current master first. A smaller independent script to reproduce the issue would also be better.
