### ISSUE TITLE
ReadFile is stream-blocking on windows

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#7174] opened 2014-06-08 19:48 UTC
For some reason jl_is_pty (or more precisely the pNtQueryInformationFile in uv_get socketname) blocks until another character is received on stdin.

**Comment by tkelman** [comment] 2015-06-11 03:20
We seem to have had a regression with mintty here recently. Looking into it.

**Comment by vtjnash** [comment] 2015-06-11 03:49
following https://github.com/JuliaLang/julia/pull/11554, is there now a call to `raw!` that doesn't first call `stop_reading`? we should probably just have `raw!` also have a pair of stop_reading/start_reading calls for windows.

**Comment by tkelman** [comment] 2015-06-11 04:07
So partially undo 5863b486435b86d9db25973a684ef4428f563a73 in the `@windows_only` case? Will try that.

**Comment by vtjnash** [comment] 2015-06-11 04:10
or just add an explicit Base.stop_reading/Base.start_reading inside the `raw!` function (windows only). that may be easier than reverting that commit (although either may be good for testing / bisecting)

**Comment by tkelman** [comment] 2015-06-11 04:11
I just meant a piece of it, presumably only the changes to base/REPL.jl or base/LineEdit.jl matter here. Or I could go find where `raw!` is defined and try that too.

**Comment by tkelman** [comment] 2015-06-11 05:22
Do you mean like
```patch
diff --git a/base/Terminals.jl b/base/Terminals.jl
index a62e4b8..b1dbda0 100644
--- a/base/Terminals.jl
+++ b/base/Terminals.jl
@@ -136,18 +136,21 @@ cmove_col(t::UnixTerminal, n) = write(t.out_stream, "$(CSI)$(n)G")
 end
 @windows ? begin
     function raw!(t::TTYTerminal,raw::Bool)
+        stop_reading(t)
         if ispty(t.in_stream)
             run(if raw
                     `stty raw -echo onlcr -ocrnl opost`
                 else
                     `stty sane`
                 end,t.in_stream,t.out_stream,t.err_stream)
-            true
+            ret = true
         else
-            ccall(:jl_tty_set_mode,
+            ret = ccall(:jl_tty_set_mode,
                  Int32, (Ptr{Void},Int32),
                  t.in_stream.handle, raw) != -1
         end
+        start_reading(t)
+        return ret
     end
 end : begin
     raw!(t::TTYTerminal, raw::Bool) = ccall(:uv_tty_set_mode,
```

? I tried that but it didn't seem to help.

**Comment by vtjnash** [comment] 2015-06-11 13:09
yeah, that's what i was thinking

**Comment by tkelman** [comment] 2015-06-11 21:15
Okay bisect confirms 5863b486435b86d9db25973a684ef4428f563a73 is at fault, any idea for other things to try? Other portions of that commit that may need partial windows-only reversion that I may have missed?

**Comment by tkelman** [comment] 2015-06-21 05:21
I'm seeing the `repl` test occasionally freeze when I run it from outside mintty, might be related?

**Comment by tkelman** [comment] 2015-07-01 20:48
@vtjnash had a very good guess here: while frozen waiting for another input, `stty.exe` is running.

**Comment by Keno** [comment] 2015-07-01 20:49
We should probably just rewrite the relevant parts of stty ourselves then.

**Comment by vtjnash** [comment] 2015-07-01 21:00
tkelmen's test proves that it is the fault of julia's REPL, not stty.

**Comment by vtjnash** [comment] 2015-07-16 05:55
synchronization mutexes is really not fun :(.

the original fix for this had a race condition if uv_read_stop was called shortly after uv_read_start or a successful read, and before the uv_pipe_zero_readfile_thread_proc thread started. There needs to be one additional check that the pipe is still active before committing to the blocking read after setting up the thread handle mutex. 

i believe this is fixed by https://github.com/JuliaLang/libuv/commit/bd8cf2ada19dd071ee1e70d19331c6903f9fa943?w=1

**Comment by tkelman** [comment] 2015-07-16 06:40
Yes, from initial testing it looks like that fixes the issue, thanks!

(`?w=1` sure is useful)

**Closed** 2015-07-16 18:59 UTC
Labels: bug, I/O, windows
