### ISSUE TITLE
assertion failure in precompile on Julia 0.4.5

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#16546] opened 2016-05-24 03:03 UTC
I boiled down stevengj/PyCall.jl#269 to a minimal example.   To see the failure, you need a build of 0.4 with LLVM assertions enabled, e.g. https://github.com/staticfloat/homebrew-julia on OSX (0.4.5, LLVM 3.3).   `using Foo` with the following module:
```jl
__precompile__()

module Foo

type PyObject
    o::Ptr{Void} # the actual PyObject*
end

PyNULL() = PyObject(C_NULL)

function jl_Function_call(self_::Ptr{Void}, args_::Ptr{Void}, kw_::Ptr{Void})
    args = PyNULL()
    try
      return C_NULL
    catch e
    finally
        args.o = C_NULL # don't decref
    end
    return C_NULL
end

precompile(jl_Function_call, (Ptr{Void},Ptr{Void},Ptr{Void}))

end # module Foo
```
reliably yields:
```
Assertion failed: (ctx->gensym_assigned.at(idx)), function emit_expr, file codegen.cpp, line 3155.
```

I'm not sure if this happens on 0.5 with assertions enabled, since I don't have such a build at the moment.

cc: @staticfloat

**Comment by stevengj** [comment] 2016-05-24 18:02
It looks like this is exactly the issue that was fixed in bf43f2d8a2035d48929ad8e5538112ed85411d5f, so presumably that patch should just be backported.

**Comment by staticfloat** [comment] 2016-05-24 18:03
I cannot reproduce this on 0.5 using LLVM 3.5, 3.7 or 3.8.  I can't get 0.5 to compile against LLVM 3.3.

I can reproduce this on 0.4.5 using LLVM 3.3 and 3.5, so this does indeed look like a Julia bug and not one from LLVM.

**Comment by vtjnash** [comment] 2016-05-24 18:34
I think https://github.com/JuliaLang/julia/pull/16244 should have fixed this for master

**Comment by stevengj** [comment] 2016-05-24 20:40
@vtjnash, can we simply backport bf43f2d8a2035d48929ad8e5538112ed85411d5f to 0.4, or is a more complicated patch required?

**Comment by vtjnash** [comment] 2016-07-19 22:42
Closing since this is fixed on master

**Closed** 2016-07-19 22:41 UTC
Labels: backport pending 0.4, bug, precompile

**Comment by tkelman** [comment] 2016-07-19 22:47
could you answer the above question?

**Comment by vtjnash** [comment] 2016-07-19 22:54
It's wrong (it'll just hide the actual error), but it won't hurt anything either (since in this case, the error in this case is in a non-function piece of the code), so I guess go for it
