### ISSUE TITLE
embedding example output different on mingw console and windows cmd

### ISSUE THREAD

**Issue by armgong** [JuliaLang/julia#9377] opened 2014-12-16 05:32 UTC
julia version master branch on win32 and 64 build, output  on mingw console lost most output !

![screen](https://cloud.githubusercontent.com/assets/4819374/5449028/e1a8f556-8527-11e4-8307-b54a7a98029b.PNG)

**Comment by ihnorton** [comment] 2015-02-22 07:42
I added an export declaration around the callback, so that part now works.

As far as the difference in output between cmd and mintty, the cause is the dreaded mintty [issue #56](https://code.google.com/p/mintty/issues/detail?id=56) and I'm not sure how much we can do about it.

**Comment by ihnorton** [comment] 2015-02-22 16:57
After reading through that mintty issue, I'm closing this. Fixing the broken nonsense of the windows console system is out of scope.

**Closed by ihnorton** 2015-02-22 16:57 UTC
Labels: I/O, windows, won't fix

**Comment by ihnorton** [comment] 2015-02-22 16:59
(I suppose we could try pinging https://github.com/satyanadella!)

**Comment by tkelman** [comment] 2015-02-23 07:58
might be in better shape on windows 10?
