### ISSUE TITLE
Pkg.update() stalls

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14616] opened 2016-01-09 17:18 UTC
I find that `Pkg.udpate()` stalls almost every time when updating a package to a new version. This is how a typical output looks like:
```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Gadfly...
INFO: Updating cache of Clang...
INFO: Updating cache of Compose...
INFO: Updating cache of Clang...
INFO: Updating SmallInts...
INFO: Updating MPI...
INFO: Updating FloatHigher...
INFO: Updating Hwloc...
INFO: Updating JLD...
INFO: Updating AutoBenchmark...
INFO: Updating PETSc...
INFO: Updating ClusterManagers...
INFO: Updating HDF5...
INFO: Updating Variants...
INFO: Updating HelloWorld...
INFO: Updating WideInts...
INFO: Updating Elemental...
INFO: Updating Persist...
INFO: Computing changes...
INFO: Upgrading Compose: v0.4.0 => v0.4.1
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of Gadfly...
INFO: Updating cache of Clang...
INFO: Updating cache of Compose...
INFO: Updating cache of Clang...
INFO: Updating SmallInts...
INFO: Updating MPI...
INFO: Updating FloatHigher...
INFO: Updating Hwloc...
INFO: Updating JLD...
INFO: Updating AutoBenchmark...
INFO: Updating PETSc...
INFO: Updating ClusterManagers...
INFO: Updating HDF5...
INFO: Updating Variants...
INFO: Updating HelloWorld...
INFO: Updating WideInts...
INFO: Updating Elemental...
INFO: Updating Persist...
INFO: Computing changes...
INFO: Upgrading Compose: v0.4.0 => v0.4.1
```
Here, nothing happens any more. To remedy this, I can e.g. abort, and then manually `git fetch` this repository. Alternatively, I can `Pkg.checkout("Compose"); Pkg.free("Compose")`. Both usually remedy the hang.

```
julia> versioninfo()
Julia Version 0.4.3-pre+8
Commit 8402319* (2016-01-09 00:36 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.2.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment] 2016-01-09 18:22
What version of git are you using? Does `make test-git test-pkg` pass?

**Comment by eschnett** [comment] 2016-01-09 20:49
```
$ git --version
git version 2.7.0
```

This seems to hang:
```
$ make test-git test-pkg
make[1]: Nothing to be done for `libjulia-release'.
make[1]: Nothing to be done for `julia-release'.
fatal: bad revision '^origin/release-0.4'
fatal: Not a valid object name origin/release-0.4
make[1]: `/Users/eschnett/src/julia/usr/lib/julia/inference.ji' is up to date.
make[1]: `/Users/eschnett/src/julia/usr/lib/julia/sys.dylib' is up to date.
make[1]: Nothing to be done for `libccalltest'.
 /Users/eschnett/src/julia/usr/bin/julia --check-bounds=yes --startup-file=no ./runtests.jl git
     * git                  
```

**Comment by eschnett** [comment] 2016-01-09 20:56
... no, it doesn't -- all tests pass.

**Comment by SimonDanisch** [comment] 2016-04-08 10:36
I might have run into something similar.
```Julia
Pkg.update()
```
```Julia
Pkg.add("X") # I guess that it was Gallium doesn't matter
```
Both hang, even after `rm("~/.julia/v0.5");Pkg.init()`
It seems pretty reproducible (although it hangs at different packages).
Second run of `Pkg.add("X")` seems to work right now (not sure if this is just a random fluctuation).

`julia runtests.jl pkg libgit2 libgit2-online` passes.

When interrupting:
```Julia
julia> Pkg.add("Gallium")
INFO: Cloning cache of ASTInterpreter from https://github.com/Keno/ASTInterpreter.jl.git
INFO: Cloning cache of AbstractTrees from https://github.com/Keno/AbstractTrees.jl.git
INFO: Updating cache of ColorTypes...
INFO: Cloning cache of DWARF from https://github.com/Keno/DWARF.jl.git
INFO: Cloning cache of ELF from https://github.com/Keno/ELF.jl.git
INFO: Cloning cache of Gallium from https://github.com/Keno/Gallium.jl.git
INFO: Cloning cache of MachO from https://github.com/Keno/MachO.jl.git
INFO: Cloning cache of ObjFileBase from https://github.com/Keno/ObjFileBase.jl.git





^CERROR: type InterruptException has no field msg
 in prefetch(::ASCIIString, ::ASCIIString, ::Array{ASCIIString,1}) at ./pkg/cache.jl:47
 in resolve(::Dict{ByteString,Base.Pkg.Types.VersionSet}, ::Dict{ByteString,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{ByteString,Tuple{VersionNumber,Bool}}, ::Dict{ByteString,Base.Pkg.Types.Fixed}, ::Dict{ByteString,VersionNumber}) at ./pkg/entry.jl:444
 in resolve(::Dict{ByteString,Base.Pkg.Types.VersionSet}, ::Dict{ByteString,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{ByteString,Tuple{VersionNumber,Bool}}) at ./pkg/entry.jl:414
 in edit(::Any, ::ASCIIString, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet}) at ./pkg/entry.jl:414
 in (::Base.Pkg.Entry.##2#5{ASCIIString,Base.Pkg.Types.VersionSet})() at ./task.jl:308
 in sync_end() at ./task.jl:274
 [inlined code] from ./task.jl:283
 in add(::ASCIIString, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:57
 [inlined code] from ./int.jl:32
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{ASCIIString}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{ASCIIString}}, ::ASCIIString) at ./file.jl:48
 in #cd#1(::Array{Any,1}, ::Any, ::Any, ::ASCIIString, ::Vararg{ASCIIString}) at ./pkg/dir.jl:31
 [inlined code] from ./boot.jl:304
 in add(::ASCIIString) at ./pkg.jl:83
 in eval(::Module, ::Any) at ./boot.jl:237
```

```Julia
julia> versioninfo()
Julia Version 0.5.0-dev+3438
Commit a92c7ff (2016-04-07 15:46 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by wildart** [comment] 2016-04-11 16:48
@eschnett Are you behind proxy?

**Comment by kescobo** [comment] 2016-05-14 22:06
I'm having this same issue - MacOSX El Capitan. `git version 2.6.4 (Apple Git-63)`. Julia `v"0.4.5"`

It stalls on different packages each time, but it's happened consistently. If I clear out `~/.julia/v0.4/` and then reinstall stuff, it usually works the first couple of updates. It happens so often now that I made a bash script to move `REQUIRE`, remove the package folder then reinitialize and install everything.

Thanks @eschnett for the `Pkg.free()` option - I'll give this a shot next time.

**Comment by jiahao** [comment] 2016-05-16 23:30
I notice that when it happens to me, a process like `git-upload-pack /Users/jiahao/.julia/v0.4/.cache/Compat` is running. If you run this git command by itself it will spit out some output like

```
00c9b21ef68dd9cd769dc60cbba14222473d7743d663 HEADmulti_ack thin-pack side-band side-band-64k ofs-delta shallow no-progress include-tag multi_ack_detailed symref=HEAD:refs/heads/master agent=git/2.8.2
0043647acfcb5f50b8c8642d59bef7ce6ed6537bf363 refs/heads/cb/bitrand
...
003e3bee4b68e6f80c86fb32ad34c277d9eb33d7fca8 refs/tags/v0.7.9
0041e7a4884edda5d830f25cb646a2aebc376125a94d refs/tags/v0.7.9^{}
0000
```

but not terminate. If you manually kill this process, `Pkg.update()` continues on for a bit but eventually (if you keep killing `git-upload-pack`) complains with

```
ERROR: Compat: fetch failed to get commit b21ef68dd9, please file an issue at https://github.com/JuliaLang/Compat.jl/issues
 in error at ./error.jl:21
 in fetch at pkg/write.jl:21
 in update at pkg/write.jl:44
 in resolve at ./pkg/entry.jl:459
 in update at ./pkg/entry.jl:313
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45
```

Googling around shows that `git-upload-pack` hanging occasionally happens to various people. [This post](https://jfesblog.wordpress.com/2015/02/18/git-upload-pack-hangs-when-doing-git-clone-via-ssh/) might be a clue indicating some sort of SSH issue with a heavily customized login script.

**Comment by tkelman** [comment] 2016-05-16 23:38
Never happens with libgit2-based Pkg on 0.5, right? Depending how curious you get about wanting to fix this on 0.4, may be worth hanging out on git's freenode irc channel and asking for advice on profiliing/tracing exactly what it's doing.

**Comment by jiahao** [comment] 2016-05-16 23:42
At least for me, it never happens on 0.5.

**Comment by jiahao** [comment] 2016-05-16 23:52
Maybe something about the environment needs to get set but doesn't?

```
ᐅ  git --work-tree=/Users/jiahao/.julia/v0.4/Colors --git-dir=/Users/jiahao/.julia/v0.4/Colors/.git fetch -q /Users/jiahao/.julia/v0.4/.cache/Colors +refs/\*:refs/remotes/cache/\*
warning: no common commits
acidflask➜  pkg : release-0.4 ✔ : ᐅ  exec git --work-tree=/Users/jiahao/.julia/v0.4/Colors --git-dir=/Users/jiahao/.julia/v0.4/Colors/.git fetch -q /Users/jiahao/.julia/v0.4/.cache/Colors +refs/\*:refs/remotes/cache/\*

(hangs)
```

**Comment by kescobo** [comment] 2016-05-17 14:05
@tkelman I haven't noticed it on v0.5, but I'm doing almost everything in 0.4 so I don't have many packages installed there (I mostly just run `git pull && make` and the `Pkg.update()` once every few weeks). 

Looks like @SimonDanisch is [having issues](https://github.com/JuliaLang/julia/issues/14616#issuecomment-207368984) on 0.5 though...

**Comment by SimonDanisch** [comment] 2016-05-17 15:56
I actually noticed, that I can reproduce this with git alone...
It seems like I just don't notice that git hangs from time to time in my everyday usage and it just becomes apparent when batching a lot of commands... Or it's the batching itself. Not sure!
Are there any well known issues with git hanging? I googled a bit and just found topics which seemed unrelated. I'm on linux and the hanging is sporadic and mostly doesn't hang when tried a second time.
I'm not a 100% sure, but I should have a pretty stable internet connection.

**Comment by tkelman** [comment] 2016-05-18 19:47
Something I used to see with Cygwin's git is it would freeze unless you ran it as `PATH=/usr/bin git` but that may be specific to Cygwin. Worth trying for those of you who have this happen often though? May need to modify the path to where git lives for your own installation.

**Comment by kescobo** [comment] 2016-05-18 20:24
Just started happening again:

```
julia> Pkg.update()
INFO: Updating METADATA...
INFO: Updating cache of FixedSizeArrays...
INFO: Updating cache of DataFrames...
INFO: Updating cache of Distances...
INFO: Updating cache of Mustache...
INFO: Updating cache of Colors...
INFO: Updating CodeTools...
INFO: Computing changes...
INFO: Upgrading Colors: v0.6.3 => v0.6.4
^CERROR: InterruptException:

julia> Pkg.checkout("Colors"); Pkg.free("Colors")
INFO: Checking out Colors master...
INFO: Pulling Colors latest master...
INFO: Upgrading Compat: v0.7.17 => v0.7.18
^CERROR: InterruptException:

julia> Pkg.checkout("Compat")
INFO: Checking out Compat master...
INFO: Pulling Compat latest master...
INFO: Upgrading DataFrames: v0.7.0 => v0.7.2
^CERROR: InterruptException:
```

I didn't want to go through doing that for every package. I checked running processes -
```
KBLaptop$ ps aux | grep git
KBLaptop        43825   0.0  0.0  2464544      8   ??  S    Sat12PM   0:00.01 git-upload-pack /Users/KBLaptop/.julia/v0.4/.cache/DataArrays
KBLaptop        43824   0.0  0.0  2477160      8   ??  S    Sat12PM   0:00.05 git --work-tree=/Users/KBLaptop/.julia/v0.4/DataArrays --git-dir=/Users/KBLaptop/.julia/v0.4/DataArrays/.git fetch -q /Users/KBLaptop/.julia/v0.4/.cache/DataArrays +refs/*:refs/remotes/cache/*
KBLaptop        13132   0.0  0.0  2475668      8   ??  S    Thu03PM   0:00.02 git-upload-pack /Users/KBLaptop/.julia/v0.4/.cache/Compat
KBLaptop        13131   0.0  0.0  2502552      8   ??  S    Thu03PM   0:00.08 git --work-tree=/Users/KBLaptop/.julia/v0.4/Compat --git-dir=/Users/KBLaptop/.julia/v0.4/Compat/.git fetch -q /Users/KBLaptop/.julia/v0.4/.cache/Compat +refs/*:refs/remotes/cache/*
KBLaptop        79920   0.0  0.0  2485628      8   ??  S    28Apr16   0:00.02 git-upload-pack /Users/KBLaptop/.julia/v0.4/.cache/DataStructures
KBLaptop        79918   0.0  0.0  2503364      8   ??  S    28Apr16   0:00.03 git --work-tree=/Users/KBLaptop/.julia/v0.4/DataStructures --git-dir=/Users/KBLaptop/.julia/v0.4/DataStructures/.git fetch -q /Users/KBLaptop/.julia/v0.4/.cache/DataStructures +refs/*:refs/remotes/cache/*
KBLaptop        83839   0.0  0.0  2445080    820 s001  S+    4:12PM   0:00.01 grep git
KBLaptop        83816   0.0  0.0  2475936   1704 s005  S+    4:10PM   0:00.01 git-upload-pack /Users/KBLaptop/.julia/v0.4/.cache/DataFrames
KBLaptop        83815   0.0  0.0  2504616   3264 s005  S+    4:10PM   0:00.21 git --work-tree=/Users/KBLaptop/.julia/v0.4/DataFrames --git-dir=/Users/KBLaptop/.julia/v0.4/DataFrames/.git fetch -q /Users/KBLaptop/.julia/v0.4/.cache/DataFrames +refs/*:refs/remotes/cache/*
```

Killing those processes didn't resolve the hang as it does for @jiahao - it just ends the update:
```
...INFO: Upgrading Distances: v0.3.0 => v0.3.1
ERROR: Distances: fetch failed to get commit b608c83906, please file an issue at https://github.com/JuliaStats/Distances.jl/issues
 in error at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in fetch at pkg/write.jl:21
 in update at pkg/write.jl:44
 in resolve at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in update at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
```

@tkelman - looks like my git is in the right place (I'm on Mac OS)

```
KBLaptop$ which git
/usr/bin/git
```

Any other ideas?

**Comment by tkelman** [comment] 2016-05-18 20:34
I'd see if it's reproducible by calling git from the command line directly outside of julia, then go to git's mailing list or irc channel for further debugging suggestions if so.

**Comment by deansher** [comment] 2016-05-22 17:05
I had exactly the same symptoms as @kescobo, also on OSX. I realized from the title bar of Julia's terminal window that the hang was in (for example)

    git-upload-pack ~/.julia/v0.4/.cache/Conda

This command hung consistently at the shell, also.

Googling around, I found a fair number of comments about `git-upload-pack` hanging. One [comment](http://apple.stackexchange.com/a/233332), specifically about OSX, stated that a reboot solved the problem. It appears that a reboot did the same for me.

I can't be sure that the reboot solved the problem, because before rebooting I tried another fix, which is still in place. That other fix was an addition to `~/.juliarc.jl` to use the `git` installed by `homebrew` instead of Julia 0.4.5's built-in `git`. I am pretty sure now that that was unnecessary and that the reboot was the answer, but for completeness, here's how I convinced Julia to use `homebrew`'s `git`:

```julia
let 
  ps = split(ENV["PATH"], ":")
  ps = filter(ps) do (p) !contains(p, "libexec/git-core") end
  path = join(ps, ":")
  ENV["PATH"]=path
end
pop!(ENV, "GIT_EXEC_PATH")
```

**Comment by tkelman** [comment] 2016-08-03 05:34
> At least for me, it never happens on 0.5.

Closing. Open new issues for any libgit2-based-Pkg problems in 0.5 (of which there are still several, but I don't think we've seen this one).

We could consider upgrading the embedded git in a backport for 0.4.7 if anyone wants to test and can confirm that is less likely to hit this error, but that may not be worth the trouble right now.

**Closed by tkelman** 2016-08-03 05:34 UTC
Labels: packages, upstream
