### ISSUE TITLE
Cannot tag `Hwloc`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#21522] opened 2017-04-24 14:03 UTC
I just accepted a pull required for the `Hwloc` package to make it compatible with Julia 0.6. I now want to tag a new minor release, so that people can depend on this change. Unfortunately, I see error messages when trying to publish this tag. I tried this both from a 0.6 and 0.5 Julia release.

I did this:
```
Pkg.update()
using PkgDev
PkgDev.tag("Hwloc", :minor)
PkgDev.publish()
```

The last step -- `Pkg.publish()` -- fails (see below). The first step -- `Pkg.update()` -- probably reported some warning or errors at some point. It often does this, since I have some experimental packages. When I run `Pkg.update()` or `Pkg.status()` now, there are no errors or warnings reported.

This is the error I see (with Julia 0.5):
```
julia> PkgDev.publish()
INFO: Validating METADATA
ERROR: packages with unsatisfiable requirements found:
    EEG v0.0.3 – no valid versions exist for package ImageFiltering

 in check_metadata(::Set{String}) at /Users/eschnett/.julia/v0.5/PkgDev/src/entry.jl:301
 in (::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String})(::Base.LibGit2.GitRepo) at /Users/eschnett/.julia/v0.5/PkgDev/src/entry.jl:93
 in with(::PkgDev.Entry.##4#9{String,Dict{String,Array{String,1}},String}, ::Base.LibGit2.GitRepo) at ./libgit2/types.jl:701
 in publish(::String, ::String) at /Users/eschnett/.julia/v0.5/PkgDev/src/entry.jl:64
 in publish() at /Users/eschnett/.julia/v0.5/PkgDev/src/PkgDev.jl:70
```

I have several suggestions here.

1. I just want to publish a new tag. This should not require me to debug my full package layout. It's easy to get stuck in the woods with packages, in particular if you develop packages yourself or look at the head of other packages. It's at the same time very difficult to work around this since Julia packages are installed globally, i.e. I can't simply install a new, separate version of Julia where I would only check out, tag, and publish `Hwloc`. (These guys <http://haskellstack.org> solved the same problem for Haskell.)

2. The error message is a mouthful. The package manager should be mature enough to give a clear error message and not dump a full stack trace from `libgit2` onto me; I don't care how `PkgDev` communicates with git servers.

3. Both `Pkg.status()` or `Pkg.update()` should complain as well. Since they don't it's difficult to debug this.

4. When I re-tried a few days later, `Pkg.update()` got stuck even worse since there were other upstream changes to `METADATA` in the mean time, and Julia told me to "resolve things manually". I did (`git checkout -- .` to overwrite all local uncommitted changes that shouldn't have been there in the first place, and then a `git pull --rebase`). Unfortunately, this just brought me back to the original problem.

5. There are no instructions for working around this. I would be happy to issue some manual git commands if Julia is getting too confused -- a pointer to instructions would be much appreciated. This page https://docs.julialang.org/en/stable/manual/packages/#package-development is already quite details; I think it should also list the errors people can receive, and how to resolve or work around them. In this case, pointing to instructions for manually cloning, pushing, and creating a pull request would be good. I think these instructions would be similar to those for package development proper, including creating a branch after the fact.

**Comment by tkelman** [comment] 2017-04-25 13:34
Duplicate of https://github.com/JuliaLang/julia/issues/21430, which should be fixed on 0.6 as of https://github.com/JuliaLang/julia/commit/c6e017801194db17867e0bb11e84e59e8c803539.

Every other error gives you a stacktrace. I don't understand why anyone would want errors from the package manager to be treated any differently than errors from all other code.

`Pkg.status()` and `Pkg.update()` are for users, they don't do full consistency checks of metadata - `PkgDev.publish()` is for package developers and does. You can manually re-run `PkgDev.Entry.check_metadata()`, which the stacktrace conveniently indicates was the function that failed.

**Comment by KristofferC** [comment] 2017-04-25 14:01
> Every other error gives you a stacktrace. I don't understand why anyone would want errors from the package manager to be treated any differently than errors from all other code.

Failures from the package manager are almost always not because of an error in any of the functions being called but due problems with external things (like METADATA state or git repo state). We could look at the choices made by some other semi popular languages:

Pip:
```
➜  ~ pip install foo
Collecting foo
  Could not find a version that satisfies the requirement foo (from versions: )
No matching distribution found for foo
```

R:
```
> install.packages("foo")
Installing package into ‘/home/kristoffer/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning message:
package ‘foo’ is not available (for R version 3.2.3) 
```

Julia:
```
julia> Pkg.add("Foo")
ERROR: unknown package Foo
macro expansion at ./pkg/entry.jl:53 [inlined]
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at ./task.jl:335
Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:50
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:70
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:36
 [7] add(::String) at ./pkg/pkg.jl:106
```

**Comment by StefanKarpinski** [comment] 2017-04-25 14:09
![0037f0fb08cfd33d8bad84a951c718895bdb9d9479a0230e96c4c0982ab009c8](https://cloud.githubusercontent.com/assets/153596/25389647/301a3a74-299f-11e7-9ddc-e964656bef59.jpg)

But seriously, not really helpful – @KristofferC is aware of that. His point is that the error originates from external state which is largely beyond the control of the package manager functions.

**Comment by tkelman** [comment] 2017-04-25 14:11
O/T, but that's the case for lots of things
```
julia> open("doesntexist")
ERROR: SystemError: opening file doesntexist: No such file or directory
 in #systemerror#51 at .\error.jl:34 [inlined]
 in systemerror(::String, ::Bool) at .\error.jl:34
 in open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at .\iostream.jl:89
 in open(::String) at .\iostream.jl:98
```

Special casing exceptions that you are tired of seeing the call stack for isn't a sustainable solution to the issue.

**Comment by StefanKarpinski** [comment] 2017-04-25 14:16
What about the idea I proposed some time ago of having a `TerseError` type that wraps another error object and displays in the REPL without a stack trace? The constraints here are:

1. Don't want to see a big stack trace for a common error where the stack trace is unhelpful;
2. Don't want to suppress the error either in case it's encountered programmatically.

The name `TerseError` is a bit weird, maybe `ErrorNoStackTrace` or `InteractiveError`?

**Comment by tkelman** [comment] 2017-04-25 14:25
If used very sparingly, maybe. I want to see what happened between what I executed and an error, pretty close to always. I wouldn't want special-cased hidden stacktraces proliferating too widely to save a few lines of output. Otherwise it gets to be `RerunThatAsAScriptToSeeWhatHappenedError`.

**Comment by andreasnoack** [comment] 2017-04-26 00:58
> I want to see what happened between what I executed and an error, pretty close to always

You are not a typical Julia user. I think many non-developers would prefer to avoid the stack trace. Probably the reason why you'll have to ask for it in `R`.

```R
> lm(foo)
Error in stats::model.frame(formula = foo, drop.unused.levels = TRUE) : 
  object 'foo' not found
> traceback()
4: stats::model.frame(formula = foo, drop.unused.levels = TRUE)
3: eval(expr, envir, enclos)
2: eval(mf, parent.frame())
1: lm(foo)
```

**Comment by tkelman** [comment] 2017-04-26 01:16
> I think many non-developers would prefer to avoid the stack trace.

Given an option between seeing information about an error and not seeing it, I don't think that's well-founded. Drawing artificial distinctions between users and developers goes pretty strongly against the way Julia is designed.

If you get an error, it's incredibly valuable information to see why you got the error and how what you did got there. Especially when things are as deeply nested as they tend to be in Julia, and when so much of the internals are visible and exposed, by design, in the same language as user code.

**Comment by martinholters** [comment] 2017-04-26 10:00
In general, it's probably very hard to decide whether a stacktrace contains valuable information. Consider
```
ERROR: SystemError: opening file inprutdata: No such file or directory
Stacktrace:
 [1] #systemerror#44 at ./error.jl:64 [inlined]
 [2] systemerror(::String, ::Bool) at ./error.jl:64
 [3] open(::String, ::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./iostream.jl:104
 [4] open(::Base.#readstring, ::String) at ./iostream.jl:150
 [5] #readdlm_auto#11(::Array{Any,1}, ::Function, ::String, ::Char, ::Type{T} where T, ::Char, ::Bool) at ./datafmt.jl:134
 [6] #readdlm#7(::Array{Any,1}, ::Function, ::String, ::Char, ::Char) at ./datafmt.jl:81
 [7] #readdlm#5(::Array{Any,1}, ::Function, ::String) at ./datafmt.jl:64
 [8] readdlm(::String) at ./datafmt.jl:64
#...
```
If the command that lead to this was `run_simulation_on("inprutdata")`, the error message is probably enough. OTOH, if it was `run_simulation()`, the stacktrace might be useful to find out where the wrong filename comes from. The solution would be to have `run_simulation_on` either check the existence of the input file and error itself if needed or have it wrap the loading code in a `try`/`catch`. While this might be justified sometimes, it would lead to error handling code sprinkled all over the place if applied as _the_ solution here. Apart from performance concerns, this defeats some of the benefits of having throwable exceptions for error reporting in the first place.

The "might be justified sometimes" notwithstanding, in general I'm on @tkelman's side here of rather erring on the side of too much information than too little.

**Comment by KristofferC** [comment] 2017-04-26 12:07
No one is really arguing for removing the stacktrace for `open` so it seems misguided to talk much more about `open` and co. 

Seeing something like below stacked 4-5 times after each other every time I run `Pkg.update()` does not make me go "wow, such good diagnostics" but more like "wtf just happened..."

![image](https://cloud.githubusercontent.com/assets/1282691/25433615/452ec6ce-2a89-11e7-9307-6318326e6b30.png)

**Comment by tkelman** [comment] 2017-04-26 12:13
Yes and we should do something specific about #16372, but in a way that's less likely to let through actual issues than #20819 would be.

**Comment by KristofferC** [comment] 2017-04-26 12:14
Yeah, so regarding

> Special casing exceptions that you are tired of seeing the call stack for isn't a sustainable solution to the issue.

It seems that special casing those few cases where it makes sense is a solution?

**Comment by tkelman** [comment] 2017-04-26 12:16
The solution to #16372 is turning something that currently is an exception into not-an-exception.

**Comment by simonbyrne** [comment] 2018-08-10 17:15
This has changed considerably with the new Pkg. If still an issue, please open at https://github.com/JuliaLang/Pkg.jl

**Closed by simonbyrne** 2018-08-10 17:15 UTC
Labels: packages
