### ISSUE TITLE
readbytes stops prematurely

### ISSUE THREAD

**Issue by denizyuret** [JuliaLang/julia#10282] opened 2015-02-22 13:02 UTC
I cannot get the following command the complete:
```
a=readbytes(`wget -O- http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz` |> `zcat`)
```

It works without zcat.  It works with smaller files (the file causing the problem above is ~9MB).  It works in regular shell outside of Julia.  I replicated the behavior on v0.3, v0.4 on linux and osx.

**Comment by denizyuret** [comment] 2015-02-22 13:29
Hm, it doesn't seem to have anything to do with the download or the pipe, I can replicate the same behavior with a local file:
```
a=readbytes(`zcat train-images-idx3-ubyte.gz`)
```
Smaller files work, so this is probably hitting an OS limit?

**Comment by ihnorton** [comment] 2015-02-22 16:46
I can reproduce on linux, but I believe this is a dupe of #8789.

**Comment by stevengj** [comment] 2015-02-23 17:35
i.e. the problem is an OS limitation on writing and reading in the same kernel thread.

**Comment by jakebolewski** [comment] 2015-06-02 00:31
closing as a dupe of #8789

**Closed by jakebolewski** 2015-06-02 00:31 UTC
Labels: I/O

**Comment by nbaum** [comment] 2015-06-02 02:01
I think this is actually a dupe of #10655 :)
