### ISSUE TITLE
Regression in broadcasting with adjoint

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#39690] opened 2021-02-16 17:19 UTC
Code to repro is:

```jl
using BenchmarkTools
perf_op_bcast!(R, x, y) = R .= 3 .* x .- 4 .* y.^2 .+ x .* y .- x .^ 3
x = rand(10^3)
y = rand(10^3)'
X = rand(10^3, 10^3)
R = Matrix{Float64}(undef, length(x), length(y))
@btime perf_op_bcast!($R, $x, $y)
```

On RC1:

``` 
  1.326 ms (0 allocations: 0 bytes)
```

on 1.5.3:

``` 
 273.757 μs (0 allocations: 0 bytes)
```

**Comment by kimikage** [comment] 2021-02-17 05:12
FWIW, changing `Adjoint` to `Matrix` (`y = collect(rand(10^3)')`) makes the benchmark on v1.5.3 as slow as on v1.6.0-rc1.

**Comment by kimikage** [comment] 2021-02-17 08:03
I simplified the example a bit. 
```julia
perf_op_bcast1!(R, x, y) = R .= x .+ y .+ x .* y;
perf_op_bcast2!(R, x, y) = R .= x .+ x .+ x .* y;
x = rand(10^3);
y = rand(10^3)';
R = Matrix{Float64}(undef, length(x), length(y));
```
```julia
julia> @code_lowered perf_op_bcast1!(R, x, y)
CodeInfo(
1 ─ %1 = Base.broadcasted(Main.:+, x, y)
│   %2 = Base.broadcasted(Main.:*, x, y)
│   %3 = Base.broadcasted(Main.:+, %1, %2)
│   %4 = Base.materialize!(R, %3)
└──      return %4
)

julia> @code_lowered perf_op_bcast2!(R, x, y)
CodeInfo(
1 ─ %1 = Base.broadcasted(Main.:+, x, x)
│   %2 = Base.broadcasted(Main.:*, x, y)
│   %3 = Base.broadcasted(Main.:+, %1, %2)
│   %4 = Base.materialize!(R, %3)
└──      return %4
)
```
```julia
julia> @btime perf_op_bcast1!($R, $x, $y);
  205.400 μs (0 allocations: 0 bytes) # v1.5.3
  205.900 μs (0 allocations: 0 bytes) # v1.6.0-rc1

julia> @btime perf_op_bcast2!($R, $x, $y);
  204.000 μs (0 allocations: 0 bytes) # v1.5.3
  949.600 μs (0 allocations: 0 bytes) # v1.6.0-rc1
```
The difference in speed is due to the success or failure of vectorization, but the cause has not been identified. It might be due to the cost estimation of inlining.

**Comment by KristofferC** [comment] 2021-02-17 08:05
> The difference in speed is due to the success or failure of vectorization, but the cause has not been identified. It might be due to the cost estimation of inlining.

I'm running a bisection.

**Comment by KristofferC** [comment] 2021-02-17 08:22
Bisected to  2ca0cc91d1cc6f7d1ff7e04aef6b09cd059947ae cc @vtjnash

**Comment by vtjnash** [comment] 2021-03-31 01:57
I think we've tended to see this happening due to an excess of `@inline` markers in the broadcast.jl file, tending to hurt performance here on average. But I don't know this specific case.

**Comment by vtjnash** [comment] 2021-11-23 19:08
appears to be fixed on master

**Closed** 2021-11-23 19:07 UTC
Labels: performance, regression
