### ISSUE TITLE
proposal: support dispatching on a vararg with at least one of a narrower type

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#42455] opened 2021-10-01 15:05 UTC
As discussed in #42222, it is often useful to require a vararg to be non-empty.  However, a generalization of that idea is that one often wants to dispatch on vararg where *at least one* of the vararg entries is a *narrower* type, in order to avoid type piracy.  (See e.g. [this example](https://github.com/JuliaDiff/ChainRulesCore.jl/pull/473#discussion_r718908483) in ChainRulesCore, cc @oxinabox.)

For example, suppose that `Base` defines a function `foo(x::Number...) = 1`.    Now, in my own package I want to define a more specialized version of `foo` when `x...` includes at least one element of `MyNumber`:
```jl
foo(x::Union{Number,MyNumber}...) = 2
```
Unfortunately, the second method is type piracy, and overrides the `Base` method in *all* cases.

If we had a syntax to declare that at least one of the arguments was a `MyNumber`, and corresponding support in the dispatch system, that would allow us to obtain the desired dispatch behavior.

Syntactically, my suggestion would be to define a new variant of `Vararg{T,N}`, e.g. `VarargOne{T1, T, N}`, to denote a tuple of `N > 0` elements of type `Union{T,T1}`, at least one of which is of type `T1`.    This would allow e.g.
```jl
foo(x::VarargOne{MyNumber,Number,N}) where {N} = 2
```

**Comment by simeonschaub** [comment] 2021-10-01 15:13
Duplicate of #39878?

**Comment by stevengj** [comment] 2021-10-01 15:14
Note that this is non-breaking AFAICT, since `Vararg` is just an identifier, not a keyword — you can already give it a different definition in a local scope, and hence `VarargOne` could be treated similarly.  (Though no current packages define a `VarargOne` symbol.)

**Comment by stevengj** [comment] 2021-10-01 15:17
@simeonschaub, good catch — this proposal seems to be more specific (e.g. it defines a new tuple type, not just a dispatch rule, and doesn't require parser changes), but I can fold it into the other issue if desired.

**Closed** 2021-10-01 15:21 UTC
Labels: speculative, types and dispatch
