### ISSUE TITLE
Apple m1 1.8.0 rc3. Ctrl+C hangs when I try to shut down Pluto

### ISSUE THREAD

**Issue by bwanab** [JuliaLang/julia#46274] opened 2022-08-07 18:53 UTC
To reproduce:

using Pluto
Pluto.run()[ Info: Loading...
┌ Info: 
└ Opening http://localhost:1234/?secret=Sq4F6hdT in your default browser... ~ have fun!
┌ Info: 
│ Press Ctrl+C in this terminal to stop Pluto

hit Ctrl+C. Sometimes it works after a long delay, but it usually hangs forever.

**Comment by alecloudenback** [comment] 2022-08-14 13:28
I think this might be normal behavior. When actively running something, there are points when the code is not able to listen for the interrupt. Does it consistently work as long as hold the key down for a few seconds to give it a chance to hit a point where it will yield?

**Comment by bwanab** [comment] 2022-08-14 16:01
It’s pretty inconsistent. Sometimes that works and sometimes it doesn’t.

My comparison point is that I’d been using Pluto on an intel Mac with Julia 1.7.x and upon hitting ctrl+c, the effect was nearly instantaneous. So, what I’m seeing is the confluence of two changes, i.e. M1 Mac and Julia 1.8.x. I no longer have my intel Mac to try 1.8 with to see if the issue is 1.8 vs. M1 processor.

**Comment by bwanab** [comment] 2022-08-14 18:00
Here’s a little more information. When it doesn’t work, this is what I get:

^C^Cfatal: error thrown and no exception handler available.
InterruptException()
ijl_task_get_next at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
poptask at ./task.jl:921
wait at ./task.jl:930
task_done_hook at ./task.jl:634
jfptr_task_done_hook_45461 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
jl_finish_task at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
start_task at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
^

**Comment by fonsp** [comment] 2022-09-05 10:39
This might be caused by #46635. @bwanab does Pluto exit when you hold down Ctrl+C?

**Comment by bwanab** [comment] 2022-09-05 12:00
Most of the time, yes, but 1 out of 4 or 5 times it doesn't resulting in the error dump that I gave in a previous message.


This certainly isn't a dealbreaker type of error, but I suspect it's indicative of a problem somewhere in the stack.


BTW, thanks for Pluto!

On Monday, September 5, 2022 06:39:19 (-04:00), Fons van der Plas wrote:



This might be caused by #46635. @bwanab does Pluto exit when you hold down Ctrl+C?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.


-- 
Sent with Vivaldi Mail. Download Vivaldi for free at vivaldi.com

**Comment by fonsp** [comment] 2022-09-21 12:18
This issue is caused by #46635, which will be fixed in Julia 1.9. In the meantime, we will release a workaround (https://github.com/fonsp/Pluto.jl/pull/2293) in Pluto 0.19.12 🌀

**Closed by fonsp** 2022-09-21 12:18 UTC
