### ISSUE TITLE
flaky test in filewatching stdlib?

### ISSUE THREAD

**Issue by nsajko** [JuliaLang/julia#55670] opened 2024-09-02 15:05 UTC
A test failed in a CI run on #55521 on the "test x86_64-linux-gnuassertrr" job:

```
FileWatching                                     (12) |         failed at 2024-09-02T08:35:51.858
Test Failed at /cache/build/tester-amdci4-9/julialang/julia-master/julia-a0fe172fb8/share/julia/stdlib/v1.12/FileWatching/test/pidfile.jl:239
  Expression: 8 < t < 20
   Evaluated: 8 < 47.819079585 < 20
```

Context within test suite:

https://github.com/JuliaLang/julia/blob/39f2ad1e941fd092b906d60e8d23c004e8ee5b7e/stdlib/FileWatching/test/pidfile.jl#L204-L241

**Comment by giordano** [comment] 2024-09-02 15:37
Duplicate of #55240

**Closed by giordano** 2024-09-02 15:37 UTC
Labels: test, stdlib
