### ISSUE TITLE
Underscore '_' function argument with keywords is failing

### ISSUE THREAD

**Issue by filchristou** [JuliaLang/julia#48704] opened 2023-02-17 12:43 UTC
I would totally expect the following code to work, but it errors.

```julia
julia> myf(a::Int, _::Function) = a # works fine
myf (generic function with 2 methods)

julia> myf(a::Int, _::Function; mynum) = a + mynum # errors
ERROR: syntax: all-underscore identifier used as rvalue around REPL[21]:1
Stacktrace:
 [1] top-level scope
   @ REPL[21]:1
```

Julia installed from binaries on a Debian 11 machine.
Julia Version 1.8.4
Commit 00177ebc4fc (2022-12-23 21:32 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × 12th Gen Intel(R) Core(TM) i5-1235U
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, goldmont)
  Threads: 1 on 12 virtual cores

**Comment by fredrikekre** [comment] 2023-02-17 12:58
Duplicate of #32727

**Closed by fredrikekre** 2023-02-17 12:58 UTC
