### ISSUE TITLE
Pkg.add() does work, while Pkg.update() doesn't !

### ISSUE THREAD

**Issue by mouryarahul** [JuliaLang/julia#18476] opened 2016-09-13 11:32 UTC
Hi, I'm using Julia-0.4.6, and my machine is behind firewall, thus I configured git to use https protocol instead using: git config --global url."https://".insteadOf git://

Under this setting, I'm able to install packages using Pkg.add(), however, when I issue Pkg.update(), I get following error:
julia>Pkg.update()
INFO: Updating METADATA...
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
ERROR: failed process: Process(`git pull --rebase -q`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:555
 in run at process.jl:531
 in anonymous at pkg/entry.jl:283
 in withenv at env.jl:160
 in anonymous at pkg/entry.jl:282
 in cd at ./file.jl:22
 in update at ./pkg/entry.jl:272
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45

What could the reason for such behavior? Any workaround?

Thanks!

**Comment by KristofferC** [comment] 2016-09-13 11:37
`Cannot pull with rebase: You have unstaged changes.`

This means that you have local changes in your `.julia/v0.x/METADATA/` folder that have not been committed. Going into the METADATA folder and undoing these change should fix it. You can also run something like `git stash` to stash away the changes.

**Comment by mouryarahul** [comment] 2016-09-13 11:53
@KristofferC Thanks for the reply. 
I did as you suggested:
rmourya@blade-1-03:~/.julia/v0.4/METADATA$ git stash                      
Saved working directory and index state WIP on metadata-v2: 3849394 Merge pull request #6343 from ssfrr/metadata-v2
HEAD is now at 3849394 Merge pull request #6343 from ssfrr/metadata-v2
rmourya@blade-1-03:~/.julia/v0.4/METADATA$ git pull
Already up-to-date.

However, I'm still get same error when I run Pkg.update().

**Comment by tkelman** [comment] 2016-09-14 01:44
When you double-post something, please at least add a cross-link between the two. https://groups.google.com/forum/#!topic/julia-users/1iFRxQdMO7s

Continue on the mailing list since this is most likely working as intended, if you've made any local modifications. If the modifications were made as a consequence of something Pkg did wrong, we can reopen.

**Closed by tkelman** 2016-09-14 01:44 UTC
Labels: packages
