### ISSUE TITLE
Underscore argument names does not work with keyword arguments

### ISSUE THREAD

**Issue by jagot** [JuliaLang/julia#35013] opened 2020-03-05 09:00 UTC
I discovered that the following does not work:
```julia
julia> muladd!(_, ::Nothing, _; kwargs...) = nothing
ERROR: syntax: all-underscore identifier used as rvalue around REPL[2]:1
Stacktrace:
 [1] top-level scope at REPL[2]:1
```
whereas without kwargs, it's fine:
```julia
julia> muladd!(_, ::Nothing, _) = nothing
muladd! (generic function with 1 method)
```

**Comment by JeffBezanson** [comment] 2020-03-06 08:06
duplicate of #32727

**Closed by JeffBezanson** 2020-03-06 08:06 UTC
Labels: bug, lowering
