### ISSUE TITLE
Behavior of `Ref` in broadcast

### ISSUE THREAD

**Issue by goretkin** [JuliaLang/julia#24880] opened 2017-12-01 23:44 UTC
I understand `Ref` as a length-1 array (tell me how flawed this is), but that's not how it behaves in a broadcast. From the discussion at https://discourse.julialang.org/t/broadcasting-and-arrays-of-arrays/7444/5 :

```julia

julia> [1, 2] .- Ref([1, 2])  # behaves like [1, 2] .- [1]
2-element Array{Int64,1}:
 0
 1

julia> [1, 2] .- [[1, 2]]
2-element Array{Array{Int64,1},1}:
 [0, -1]
 [1, 0] 
```
(thanks @rdeits )

**Comment by timholy** [comment] 2017-12-02 01:20
One part of the problem is
```julia
julia> eltype(Ref([1,2]))
Int64

julia> eltype(Ref(3))
Int64
```
That seems broken.

**Comment by KristofferC** [comment] 2017-12-02 01:31
Ah, the classical https://github.com/JuliaLang/julia/issues/15303 mixup.

**Comment by vtjnash** [comment] 2017-12-02 03:56
I think that’s actually https://github.com/JuliaLang/julia/pull/21527

**Comment by vtjnash** [comment] 2018-05-05 02:25
will be fixed when deprecations get deleted
```
julia> eltype(Ref{Vector{Int}}([1,2]))
Array{Int64,1}
```

**Closed by vtjnash** 2018-05-05 02:25 UTC
Labels: broadcast
