### ISSUE TITLE
Kernel 0.3.11 keeps on dying on JuliaBox

### ISSUE THREAD

**Issue by allaffa** [JuliaLang/julia#13402] opened 2015-10-01 15:45 UTC
Hi everyone,

I am touching base with you since I have been trying to use the 0.3.11 version of the Julia kernel on JuliaBox for almost a week without success. Every time I switch to such kernel, the kernel dies as soon as it gets restarted and the problem is persistent.
I would like to know if anyone else is encountering the same issue and what I might do in order to get such issue solved.

Thank you very much in advance.

**Comment by jiahao** [comment] 2015-10-01 16:05
Duplicate of JuliaLang/JuliaBox#305

**Closed by jiahao** 2015-10-01 16:05 UTC
