### ISSUE TITLE
`Base.runtests(["Pkg"])` hangs

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#52562] opened 2023-12-17 14:49 UTC
```
julia> Base.runtests(["Pkg"])
Running parallel tests with:
  getpid() = 5539
  nworkers() = 1
  nthreads() = 1
  Sys.total_memory() = 7.274 GiB
  Sys.free_memory() = 1.777 GiB

Test  (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
Pkg        (1) |        started at 2023-12-17T08:10:38.155
┌ Info: Pkg Server metadata:
│ HTTP/2 301 
│ server: Varnish
│ retry-after: 0
│ location: https://us-east.pkg.julialang.org/
[...]
    Updating `/tmp/jl_CXNkw2/environments/v1.11/Project.toml`
  [7876af07] + Example v0.5.4 `https://github.com/JuliaLang/Example.jl#master`
    Updating `/tmp/jl_CXNkw2/environments/v1.11/Manifest.toml`
  [7876af07] + Example v0.5.4 `https://github.com/JuliaLang/Example.jl#master`
    Updating `/tmp/jl_CXNkw2/environments/v1.11/Project.toml`
  [7876af07] - Example v0.5.4 `https://github.com/JuliaLang/Example.jl#master`
    Updating `/tmp/jl_CXNkw2/environments/v1.11/Manifest.toml`
  [7876af07] - Example v0.5.4 `https://github.com/JuliaLang/Example.jl#master`
     Cloning git-repo `https://github.com/DoesNotExist/DoesNotExist.jl`
Username for 'https://github.com': 
```

`Base.runtests(["sorting", "Pkg"]; ncores=2)`, on the other hand, works fine. Presumably because in the latter case Pkg tests are run in a separate worker with a stdin other than stdin, so Pkg can detect that prompting for credentials is fruitless.

**Comment by IanButterworth** [comment] 2023-12-17 16:21
It'd be great if we can figure out a way to force git cli to not prompt for credentials here and on Pkg repo CI. At best it adds noise at worst it does this.

The alternative is not test the mode where Pkg uses the git cli but given that's often recommended it wouldn't be great

**Comment by vtjnash** [comment] 2024-02-13 02:20
I think Pkg was going to try to fix this recently, but I still see it broken

**Comment by IanButterworth** [comment] 2024-02-13 02:39
I implemented your suggestion in https://github.com/JuliaLang/Pkg.jl/pull/3778 which landed here in https://github.com/JuliaLang/julia/pull/53220

You see it beyond that bump?

**Comment by vtjnash** [comment] 2024-02-13 02:55
I think multiprocess may work because we run the workers with `Cmd(detach=true)`, so they do not get stdin as their controlling tty. I thought I still ran into today with `cd test && ../julia runtests.jl  Pkg`, but if you think it is fixed, then feel free to close this.

**Comment by vtjnash** [comment] 2024-02-13 14:31
According to gdb, the problem is in Pkg not in git. The git process has exited and there no open IO or process handles. And yet the Pkg test has deadlocked itself.

**Comment by IanButterworth** [comment] 2024-02-13 14:37
Can you SIGUSR1 profile it?

**Comment by vtjnash** [comment] 2024-02-13 14:42
Yes, I sent you the trace on the Pkg issue

**Closed** 2024-02-13 14:42 UTC
Labels: bug, packages, ci
