### ISSUE TITLE
perf regression in `@pure` changes

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#13735] opened 2015-10-23 00:16 UTC
Running @timholy 's test case from #13350:

commit 7dcc01be36a854bf95915f1cdf157df7c722ea68:

```
Without parentheses:
  0.567878 seconds (16.01 M allocations: 488.552 MB, 5.03% gc time)
With parentheses:
  0.421889 seconds (11 allocations: 480 bytes)
```

commit 8ce7a02f6bed51a09600307f395d8c6887f0f104

```
Without parentheses:
  2.149215 seconds (70.01 M allocations: 1.654 GB, 5.22% gc time)
With parentheses:
  2.251477 seconds (74.00 M allocations: 1.773 GB, 5.45% gc time)
```

cc @vtjnash

**Comment by vtjnash** [comment] 2016-02-27 21:11
duplicate of #14294

**Closed by vtjnash** 2016-02-27 21:11 UTC
Labels: performance, regression
