### ISSUE TITLE
Add groupinds utility to Base

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#34818] opened 2020-02-19 16:28 UTC
A common pattern with collections is the "groupinds" pattern. The pattern consists of collecting the indices of the entries of the collection into subsets with common value. For example:

```Julia
v = [(1,2), (1,2), (1,3), (7,3)]
```

could be grouped into:

```Julia
[[1,2], [3], [4]]
```

because the two first indices of `v` have the same value `(1,2)`.

Could we have this pattern implemented in Base? Below is a draft implementation by @jagot:

```Julia
function group_by(v; f=identity, by=identity)
    isempty(v) && return [[]]
    e = first(v)
    m = Dict{typeof(by(e)),Vector{typeof(f(1=>e))}}()
    for (i,e) in enumerate(v)
        push!(get!(m, by(e), []), f(i=>e))
    end
    values(m)
end
```

**Comment by KristofferC** [comment] 2020-02-19 16:37
Duplicate of #32331

**Closed by KristofferC** 2020-02-19 16:37 UTC

**Comment by mcabbott** [comment] 2020-02-19 16:38
See also https://github.com/JuliaLang/julia/issues/1845 about `unique`'s indices. 

Using [GroupSlices.jl](https://github.com/mcabbott/GroupSlices.jl), the operation described here is `groupinds(groupslices(v))`.
