### ISSUE TITLE
Unicode modifiers for adjoint operator

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#34507] opened 2020-01-24 21:46 UTC
The original motivation for this is having a nicer syntax for `transpose` and `conj`, where the most appropriate I could come up with was `M'ᵀ` and `z'ᶜ`. Currently this would only be possible by special casing `transpose` and `conj` at a parser level, but if #33683 was merged, one could extend the concept of Unicode modifiers for infix operators to `'` very nicely. This would also be useful for packages like Zygote, which like to pun on `'` as notation for taking the derivative, which could then export e.g. `'ᴰ` instead.
A problem is that currently, `a'ᵀb` is valid syntax for `adjoint(a) * (ᵀb)`, which is quite unfortunate, since this is different from other infix operators like `+`, where the modifier gets parsed as part of the operator, even if there is no whitespace in between. I therefore believe that parsing these as part of the operator will make for more consistency, but as this is technically breaking, it might be necessary to deprecate this syntax for one minor release first. Eventually it might make sense to disallow modifiers in front of variable names altogether, but that would be a separate issue.

**Comment by stevengj** [comment] 2020-01-27 21:34
Yes, I guess it is kind of weird that we allow category Lm (Letter, modifier) [to start identifiers](https://github.com/JuliaLang/julia/blob/a5c422fea8ca32baac92501768713b704d3611c3/src/flisp/julia_extensions.c#L62).  We probably should have discussed that in #6805 😢.  The same issue was also discussed in #28441.   Unfortunately, it would be breaking to disallow identifiers starting with Lm now, and I'm skeptical that this counts as a "minor change" that we can do in 1.x.

In any case, allowing Unicode modifiers for `'` seems reasonable, analogous to #22089, I guess?

**Comment by stevengj** [comment] 2020-01-27 21:36
Duplicate of #28494?

**Comment by simeonschaub** [comment] 2020-01-27 22:25
The unfortunate thing is that I don't see any non-breaking way to introduce this feature. Currently, even `a'ᵀ` is valid syntax, and I would argue that it's less breaking to throw a clear error here than just to silently interpret it as something different. Whether it is then still worth making this change is up to discussion.

> Duplicate of #28494?

Oh, I didn't discover that. Also seems to propose some of the changes made in #33683. The concrete proposal is a bit different though, so should I still leave this issue open?

**Comment by StefanKarpinski** [comment] 2020-01-27 22:26
Any easy way to see if any packages are using this feature is to make it a syntax error and then run PkgEval.

**Comment by simeonschaub** [comment] 2020-01-27 22:46
What would be the usual protocol for that? Should I open a PR here?

**Comment by StefanKarpinski** [comment] 2020-01-28 04:05
It would be to make a [NO NOT MERGE] PR that causes the relevant syntax to be an error and then ask someone to trigger PkgEval. Might be easier to grep through all the registered packages though.

**Comment by stevengj** [comment] 2020-01-28 14:07
Created a PR in #34549 if someone wants to trigger PkgEval on that.

**Comment by c42f** [comment] 2020-02-27 01:56
As mentioned in https://github.com/JuliaLang/julia/pull/34549#issuecomment-591730008, a survey of the fairly small number of packages which were broken by trying this out identified the following being used as postfix operators in category Lm:

```
(x)ᵀ   ↦  x'ᵀ    (category Lm)
(x)ˣ   ↦  x'ˣ    (category Lm)
```

But there was also the following in AbstractTensors

```
(x)⁻¹  ↦  x'⁻¹   (category Sm,No)
(x)₊   ↦  x'₊    (category Sm)
(x)₋   ↦  x'₋    (category Sm)
(x)ǂ             (category Lo)
```

Currently it seems we allow a lot of category Sm to begin an identifier, for example:

```julia
julia> ₋x = 1
1
```

So we'd also have trouble with parsing things like `x'⁻¹y` which currently produces

```julia
julia> :(x'⁻¹y)
:(x' * ⁻¹y)
```

Maybe this isn't a problem but it's kind of annoying.

**Comment by simeonschaub** [comment] 2020-03-03 14:37
What does triage think would be the best way forward here? Is the change in #34549 acceptable for a minor release, considering what PkgEval revealed? A probably less breaking alternative would be to only change the parsing of modifiers right after `'` to be consistent with how we do it for infix operators, although in this case, it might make sense to have a deprecation period, where make this syntax a syntax error.

**Comment by baggepinnen** [comment] 2020-03-25 20:55
While I like the proposals in this issue, I just wanted to share that many characters don't render well in Chrome for Android. 
![Screenshot_20200326-045340](https://user-images.githubusercontent.com/3797491/77584470-d1093e00-6f1d-11ea-9c98-31405ba0a5a4.jpg)

**Comment by simeonschaub** [comment] 2020-04-16 19:34
Just bumping this again. Is there any consensus forming?

**Closed** 2020-10-16 18:10 UTC
Labels: parser, speculative, unicode
