### ISSUE TITLE
mpfr_sprintf is not working anymore after: using ImageView

### ISSUE THREAD

**Issue by rtdietrich** [JuliaLang/julia#33481] opened 2019-10-06 13:29 UTC
A few days ago I came across the following problem and to the conclusion that it was a bug.

After adding the package "ImageView" the command "sin(BigFloat(3))" can only be executed with an error message (see screenshot).

Affected is Julia 1.2/1.3 RC3 and the current nightly version.

The error can be reproduced on my Windows 10 system (Core-i3 4 GByte RAM - Developer-Mode) as often as I want, even if I have completely reinstalled Windows. 
It is noticeable that after 1 out of 10 attempts to uninstall Julia and reinstall, no error occurred.

Also with the installation on another computer it worked immediately error free.

I already reported this to a member of JuliaImages/ImageView.jl (timholy) and he advised me to report this as a Julia bug. ( https://github.com/JuliaImages/ImageView.jl/issues/181 )

![Julia-Issue](https://user-images.githubusercontent.com/13079745/66269847-c5319e80-e84d-11e9-8ddd-dd5e4b1315f7.png)

**Comment by rtdietrich** [comment] 2019-10-06 18:52
Addition: I have now also done tests under VirtualBox. Mint-Linux 19.2 and Win-10 (VBox-image directly from Microsoft). Both tests returned the same error message.

**Comment by fredrikekre** [comment] 2019-10-10 12:31
Repro:
```
fmt = "%.Re"
x = BigFloat(0.5403023058681398);
buf = Base.StringVector(0)
s = Base.MPFR._calculate_buffer_size!(buf, fmt, x)
resize!(buf, s + 1)
n = ccall((:mpfr_sprintf,:libmpfr), Int32, (Ptr{UInt8}, Ptr{UInt8}, Ref{BigFloat}...), buf, fmt, x)
buf[2]
```
where `buf[2]` is `0x2e` (`.`) in a clean env and `0x2c` (`,`) after loading `ImageView`.
This happens at this `ccall`, which behaves differently after loading `ImageView`: https://github.com/JuliaLang/julia/blob/581f81c9d7b4c1b8d40f5c165ead05858c58c1f1/base/mpfr.jl#L973
causing this string: https://github.com/JuliaLang/julia/blob/581f81c9d7b4c1b8d40f5c165ead05858c58c1f1/base/mpfr.jl#L960 to have a `,` instead of a `.`.

**Comment by KristofferC** [comment] 2019-10-10 12:37
Seems like MPFR is locale-aware and prints the decimal delimiter depending on the current locale. Loading ImageView probably sets the locale somehow.

**Comment by fredrikekre** [comment] 2019-10-10 13:02
The problem is Gtk: https://github.com/JuliaGraphics/Gtk.jl/issues/308, https://github.com/JuliaLang/julia/issues/21494, and 
Duplicate of #7167

**Closed by fredrikekre** 2019-10-10 13:02 UTC
