### ISSUE TITLE
Warn when comparing Char and String

### ISSUE THREAD

**Issue by Timeroot** [JuliaLang/julia#47619] opened 2022-11-17 23:05 UTC
More than once I've made a mistake like,
```
for line = lines
 headchar = line[1]
 if headchar == "X"
   break
 end
 ...
end
```
... and then it never stops because it starts with 'X', not "X". It usually takes me a minute to realize why it's not working.

How feasible would it be to special-case a warning when checking a character and string for equality? Sort of similar to how 
```
5 in Dict(5 => "yes", 3 => "no")
```
produces a special warning,
```
AbstractDict collections only contain Pairs;
Either look for e.g. A=>B instead, or use the `keys` or `values`
function if you are looking for a key or value respectively.

Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] in(p::Int64, a::Dict{Int64, String})
   @ Base .\abstractdict.jl:28
```

I'm not familiar enough with the dispatch performance, but I could imagine that adding this check in the wrong place could impact performance heavily (by incurring a check+dispatch on every single instance of `==` anywhere). If the performance impact is minimal though, it might be handy.

**Comment by Seelengrab** [comment] 2022-11-17 23:24
Sadly a duplicate of https://github.com/JuliaLang/julia/issues/40717

**Closed** 2022-11-18 02:14 UTC
Labels: duplicate, equality
