### ISSUE TITLE
Segfault with custom sort comparison function

### ISSUE THREAD

**Issue by tecosaur** [JuliaLang/julia#44698] opened 2022-03-22 09:59 UTC
Julia seems to segfault every now and then for me, but I usually don't have a good MWE.

This time I do! It's with a sort with a comparison function that's slightly simpler that what I'm using in practice.

```julia
julia> sortperm(rand(rand(1000), 100000), rev=true, lt = (a, b) -> (a < b) || (a == b))

signal (11): Segmentation fault
in expression starting at REPL[1]:1
getindex at ./array.jl:861 [inlined]
lt at ./ordering.jl:116 [inlined]
partition! at ./sort.jl:560
sort! at ./sort.jl:575
```

Full segfault message: http://ix.io/3T9p

-----

```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen Threadripper 3970X 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
Environment:
  JULIA_NUM_THREADS = 60
```

**Comment by fredrikekre** [comment] 2022-03-22 10:21
It is an out-of-bounds access:
```
$ julia --check-bounds=yes -q

julia> sortperm(rand(rand(1000), 100000), rev=true, lt = (a, b) -> (a < b) || (a == b))
ERROR: BoundsError: attempt to access 100000-element Vector{Int64} at index [0]
Stacktrace:
 [1] getindex
   @ ./array.jl:924 [inlined]
 [2] partition!(v::Vector{Int64}, lo::Int64, hi::Int64, o::Base.Order.Perm{Base.Order.ReverseOrdering{Base.Order.Lt{Base.Order.var"#1#3"{var"#1#2", typeof(identity)}}}, Vector{Float64}})
   @ Base.Sort ./sort.jl:561
 [3] sort!(v::Vector{Int64}, lo::Int64, hi::Int64, a::Base.Sort.QuickSortAlg, o::Base.Order.Perm{Base.Order.ReverseOrdering{Base.Order.Lt{Base.Order.var"#1#3"{var"#1#2", typeof(identity)}}}, Vector{Float64}})
   @ Base.Sort ./sort.jl:576
 [4] sort!(v::Vector{Int64}, lo::Int64, hi::Int64, a::Base.Sort.QuickSortAlg, o::Base.Order.Perm{Base.Order.ReverseOrdering{Base.Order.Lt{Base.Order.var"#1#3"{var"#1#2", typeof(identity)}}}, Vector{Float64}}) (repeats 4 times)
   @ Base.Sort ./sort.jl:581
 [5] sort!(v::Vector{Int64}, alg::Base.Sort.QuickSortAlg, order::Base.Order.Perm{Base.Order.ReverseOrdering{Base.Order.Lt{Base.Order.var"#1#3"{var"#1#2", typeof(identity)}}}, Vector{Float64}})
   @ Base.Sort ./sort.jl:665
 [6] sortperm(v::Vector{Float64}; alg::Base.Sort.QuickSortAlg, lt::Function, by::Function, rev::Bool, order::Base.Order.ForwardOrdering)
   @ Base.Sort ./sort.jl:931
```

**Comment by tecosaur** [comment] 2022-03-22 10:25
Interesting. I thought that equality would be fine since `sortperm([1, 2, 1], lt = <=)` is fine, but it seems with more numbers it isn't.

**Comment by barucden** [comment] 2022-03-22 10:47
Maybe we could add the two checks `i < hi` and `j > lo`, respectively, [here](https://github.com/JuliaLang/julia/blob/v1.7.2/base/sort.jl#L559-L560)?

**Comment by petvana** [comment] 2022-03-22 11:48
Duplicate of https://github.com/JuliaLang/julia/issues/11429. The behavior is undefined for ill-behaved user-specified comparisons

**Closed** 2022-03-22 12:03 UTC
