### ISSUE TITLE
Unreachable reached during testing of NeuralNetworkReachability.jl

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#52961] opened 2024-01-18 14:24 UTC
NeuralNetworkReachability.jl has started crashing on PkgEval, with an unreachable instruction reached: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-01/16/NeuralNetworkReachability.primary.log

```
Unreachable reached at 0x7fb513d0c153

[17] signal 4 (2): Illegal instruction
in expression starting at /home/pkgeval/.julia/packages/NeuralNetworkReachability/uRRcL/test/ForwardAlgorithms/forward.jl:166
Verisig at /home/pkgeval/.julia/packages/NeuralNetworkReachability/uRRcL/src/ForwardAlgorithms/Verisig.jl:26
macro expansion at /home/pkgeval/.julia/packages/NeuralNetworkReachability/uRRcL/test/ForwardAlgorithms/forward.jl:181 [inlined]
macro expansion at /source/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:1598 [inlined]
top-level scope at /home/pkgeval/.julia/packages/NeuralNetworkReachability/uRRcL/test/ForwardAlgorithms/forward.jl:167
_jl_invoke at /source/src/gf.c:2905 [inlined]
ijl_invoke at /source/src/gf.c:2912
jl_toplevel_eval_flex at /source/src/toplevel.c:932
jl_toplevel_eval_flex at /source/src/toplevel.c:884
ijl_toplevel_eval_in at /source/src/toplevel.c:992
```

I reduced this to the following snippet, depending on Requires.jl and Example.jl:

```julia
module Package

require(mod, pkg; str="") = @assert isdefined(mod, pkg) (str == " $str" * (" " * "") * ")")
foobar() = require(@__MODULE__, :Example)

using Requires
__init__() = @require Example = "7876af07-990d-54b4-ab0e-23690620f79a" begin end

end


using .Package
try
    Package.foobar()
catch
end

import Example
Package.foobar()
```

```
Unreachable reached at 0x7fceda30703f

[3018479] signal 4 (2): Illegal instruction
in expression starting at /home/maleadt/julia/wip.jl:19
foobar at /home/maleadt/julia/wip.jl:4
unknown function (ip: 0x7fceda307072)
_jl_invoke at /source/src/gf.c:2913 [inlined]
ijl_apply_generic at /source/src/gf.c:3095
```

Bisected to 358540cf46c683f3a6881242722f4b610c376a50 from #52085; cc @aviatesk.

**Comment by vtjnash** [comment] 2024-03-12 15:50
Duplicate of https://github.com/JuliaLang/julia/issues/53613

**Closed by vtjnash** 2024-03-12 15:50 UTC
Labels: regression
