### ISSUE TITLE
Fail to compute rank(Matrix{BigFloat})

### ISSUE THREAD

**Issue by putianyi889** [JuliaLang/julia#38621] opened 2020-11-30 11:40 UTC
```julia
julia> rank(BigFloat[1 1;1 0])
ERROR: MethodError: no method matching svdvals!(::Array{BigFloat,2})
Closest candidates are:
  svdvals!(::SymTridiagonal) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\tridiag.jl:350
  svdvals!(::StridedArray{T, 2}) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\svd.jl:193
  svdvals!(::StridedArray{T, 2}, ::StridedArray{T, 2}) where T<:Union{Complex{Float32}, Complex{Float64}, Float32, Float64} at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\svd.jl:501
  ...
Stacktrace:
 [1] svdvals(::Array{BigFloat,2}) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\svd.jl:218
 [2] #rank#15 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:985 [inlined]
 [3] rank(::Array{BigFloat,2}) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\LinearAlgebra\src\generic.jl:984
 [4] top-level scope at none:1
```

**Comment by stevengj** [comment] 2020-11-30 22:22
Duplicate of https://github.com/JuliaLang/julia/issues/5429.

For now, you can use https://github.com/JuliaLinearAlgebra/GenericSVD.jl

**Closed** 2020-11-30 22:23 UTC
Labels: linear algebra
