### ISSUE TITLE
Scoping: blocks allow binding and changing globals without declaring it so

### ISSUE THREAD

**Issue by tonyhffong** [JuliaLang/julia#7234] opened 2014-06-12 20:47 UTC
In repl when I do this:
```
foo = 1
bar() = (foo=foo+1)
bar()
```
I get `ERROR: foo not defined`. So far so good.

But if I write it like this:
```
begin
  foo = 1
  bar() = (foo=foo+1)
  bar()
end
```
I get 2.

Wrapping it in block changes the behavior. Apparently the bar() inside a block can access foo without declaring it global. And outside the block, I can see foo, so foo is really a global.

**Comment by ViralBShah** [comment] 2015-01-02 06:06
The `begin-end` blocks not introducing new scope is already documented. Not sure what further to do here.

**Comment by jiahao** [comment] 2015-01-02 06:33
The challenge is to explain clearly why this happens:

```jl
julia> begin foo=1; bar() = (foo=foo+1); bar() end
2

julia> begin baz()=(foo=foo+1); baz() end
ERROR: foo not defined
 in baz at none:1
```

**Comment by mauro3** [comment] 2015-06-15 07:45
I think this is a bug! Please relabel this with `bug` and remove the `doc` label.

IMO, begin-end block should have nothing to do with scope: they don't introduce a new scope, nor should they modify the scoping rules of containing blocks. However, in this example the scoping rules for the function `bar` changes from hard-scope to semi-soft-scope (see #10559).  Note that the same applies to if-blocks:
```
julia> if true; foo=1; bar() = (foo=foo+1); bar() end
2

julia> if true; bar() = (foo=foo+1); bar() end
ERROR: foo not defined
 in bar at none:1
```

If this is not a bug but a feature, could someone please explain the use case and argue why special-special casing begin-end and if-end blocks is worth the extra language complexity.  I plan to update the scope-docs in the near future and resolving this would be helpful.

**Comment by ScottPJones** [comment] 2015-06-15 11:47
Definitely looks like a serious bug to me, both for `if` and `begin`/`end`.

**Comment by mauro3** [comment] 2015-06-15 19:03
See Jeff's related comment: https://github.com/JuliaLang/julia/issues/10559#issuecomment-112146233

**Comment by JeffBezanson** [comment] 2015-06-15 19:23
Actually this bug might be the evil twin of another "bug":

```
julia> begin
         local x = 1
       end
1

julia> x
ERROR: UndefVarError: x not defined
```

This is the good twin because people are ok with this behavior. But the problem is that if `begin` doesn't introduce a new scope, what is the `local x` local *to*? We might want to disallow this.

**Comment by ScottPJones** [comment] 2015-06-15 19:33
That just seems like a bug to me, not a "good" one, because if begin/end doesn't make a new scope level, local needs to mean a local in the scope test the begin is in.

**Comment by ssfrr** [comment] 2015-06-16 01:24
> if begin doesn't introduce a new scope, what is the local x local to?

Seems like it should behave the same as `local x = 1` at global scope, unless there's something I'm missing.

**Comment by mauro3** [comment] 2015-06-16 07:01
Then we're fine...
```
julia> local x=1
1

julia> x
ERROR: UndefVarError: x not defined
```
But probably both should throw an error on assignment. This is issue #10472.

**Closed** 2015-06-22 04:35 UTC
Labels: bug
