### ISSUE TITLE
Ambiguous behavior of Tuple constructor with mismatched array length

### ISSUE THREAD

**Issue by gryumov** [JuliaLang/julia#55498] opened 2024-08-15 12:06 UTC
Ambiguous behavior of Tuple constructor with mismatched array length.

```julia
julia> Tuple{String}(Any["x", "y", 1, 2, 3])
("x",)

julia> Tuple{String,String}(["x", "y", 1])
("x", "y")
```

```julia
julia> versioninfo()
Julia Version 1.9.4
Commit 8e5136fa297 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 8 on 6 virtual cores
Environment:
  JULIA_HOME = /Users/stanislav/julia/usr/bin
  JULIA_PKG_USE_CLI_GIT = true
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 8
```

**Comment by adienes** [comment] 2024-08-15 12:49
I believe this is a dup of https://github.com/JuliaLang/julia/issues/37132

**Comment by mbauman** [comment] 2024-08-15 12:59
Duplicate of #52657

**Closed by mbauman** 2024-08-15 12:59 UTC
