### ISSUE TITLE
Bug in dispatching on a union containing a UnionAll type

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#37793] opened 2020-09-29 04:52 UTC
MWE:
```julia
julia> g(::Ref{Union{Int, Other}}) where {Other} = Other
g (generic function with 1 method)

julia> g(Ref{Union{Int, Float64}}(1))
Float64

julia> g(Ref{Union{Int, Array}}(1))
ERROR: MethodError: no method matching g(::Base.RefValue{Union{Int64, Array}})
Closest candidates are:
  g(::Ref{Union{Int64, Other}}) where Other at REPL[3]:1
Stacktrace:
 [1] top-level scope at REPL[5]:1

julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943* (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 2600 Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
Environment:
  JULIA_NUM_THREADS = 6

```
Seems like a bug with `UnionAll` to me.

_Originally posted by @MasonProtter in https://github.com/JuliaLang/julia/issues/37790#issuecomment-700409442_

**Comment by MasonProtter** [comment] 2020-09-29 14:52
In https://github.com/JuliaLang/julia/issues/37790#issuecomment-700445999, @vtjnash says that it's desirable to make it so that concrete types behave like `UnionAll` types here rather than the other way around. To me, this sounds bad, but can you explain a bit about why?

**Comment by JeffBezanson** [comment] 2020-09-29 20:59
Duplicate of #26135

**Closed by JeffBezanson** 2020-09-29 20:59 UTC
