### ISSUE TITLE
UndefVarError: F not defined bar(h::F)::String where {F<:Foo} = h.x

### ISSUE THREAD

**Issue by gryumov** [JuliaLang/julia#48368] opened 2023-01-20 20:51 UTC
```julia
julia> struct Foo
           x::String
       end

julia> bar(h::F)::String where {F<:Foo} = h.x
ERROR: UndefVarError: F not defined
Stacktrace:
 [1] top-level scope
   @ none:1


julia> versioninfo()
Julia Version 1.8.4
Commit 00177ebc4f* (2022-12-23 21:32 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.1.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 8 on 6 virtual cores
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 8
```

**Comment by JeffBezanson** [comment] 2023-01-20 21:38
Duplicate of #21847. An unfortunate consequence of various other syntax choices. For now you need to parenthesize the function signature and return type.

**Closed by JeffBezanson** 2023-01-20 21:38 UTC
