### ISSUE TITLE
Bug in `hasmethod(f, Tuple{T} where T)` - Julia REPL has crashed

### ISSUE THREAD

**Issue by o314** [JuliaLang/julia#33015] opened 2019-08-21 23:31 UTC
```julia
f(x::T) where T = 1
hasmethod(f, Tuple{T} where T)
```

crash the julia repl on julia 1.1.1, windows 7

**Comment by o314** [comment] 2019-08-22 00:19
```julia
function isiterable(T)::Bool
    return hasmethod(iterate, Tuple{T})
end
```
@ https://github.com/JuliaLang/julia/blob/v1.2.0/base/essentials.jl#L910-L918

is ok but typevar is jit bound and no free as in former post IMHO

**Comment by JeffBezanson** [comment] 2019-08-22 16:20
Duplicate of #31353, and has been fixed.

**Closed by JeffBezanson** 2019-08-22 16:20 UTC
