### ISSUE TITLE
Variadic (or "Varargs") destructuring of tuples

### ISSUE THREAD

**Issue by lilinjn** [JuliaLang/julia#9870] opened 2015-01-21 15:27 UTC
In julia, is there some syntax similar to 
`(x,z...) = (1,2,3)` which would result in
`x=1` & `z=(2,3)`?  

If not, are there reasons why this was not supported, or perhaps this could be a reasonable feature request (or, more constructively, prior to working on a PR, do others have thoughts about this)?

Ideally, since nested destructuring e.g. `(a,(b,c)) = (1,(2,3))` works as expected, any variadic version would also work e.g.
`(a,(b,c,d...),e...) = (1,(2,3,4,5),6,7)` would yield 

    a=1
    b=2
    c=3
    d=(4,5)
    e=(6,7)

And perhaps

`(a,(b,c,d...),e..., nexttolast, last) = (1,(2,3,4,5),6,7,8,9,10)` would yield

    a=1
    b=2
    c=3
    d=(4,5)
    e=(6,7,8)
    nexttolast=9
    last=10

While `(a,(b,c,d...),e..., nexttolast, last) = (1,(2,3,4,5),9,10)` would yield
  
    a=1
    b=2
    c=3
    d=(4,5)
    e=()
    nexttolast=9
    last=10

And finally `(a,(b,c,d...),e..., nexttolast, last) = (1,(2,3,4,5),10)` would result in an error, just 
like the current behavior for `(a,b) = 1`

**Comment by mschauer** [comment] 2015-01-21 16:01
The package https://github.com/kmsquire/Match.jl allows to do this 
``` 
> a, b, c = @match (1,2,(3,)) (a,b, (c,))
(1, 2, 3)
```

**Comment by jiahao** [comment] 2015-01-21 16:05
```
x, z = 1, 2, 3
```

This is a usage question for the julia-users mailing list. The issue tracker is for bug reports.

**Comment by timholy** [comment] 2015-01-21 16:16
You could interpret this as a feature request for such syntax.

@lilinjn, `tuplesplit(x) = x[1], tuple(x[2:end]...)` should get you started. To me that looks like attractive syntax, so if you can figure out how to add it to the parser, a PR might be nice. (Just my opinion.)

**Comment by StefanKarpinski** [comment] 2015-01-21 16:16
@jiahao, the topmost syntax doesn't work:

```jl
julia> (x,z...) = (1,2,3)
ERROR: syntax: invalid assignment location
```

I'm pretty sure I've proposed this before and I think we can reasonably view this issue as a feature request for this syntax.

**Comment by ivarne** [comment] 2015-01-21 16:20
Implementing this can also prepare the way for deprecating the sometimes surprising behaviour where `a, b = 1,2,3` discards the third value.

**Comment by StefanKarpinski** [comment] 2015-01-21 16:23
I'm torn about discarding trailing values. It makes it possible to have silent bugs where you drop values that you didn't mean to, but on the other hand, it allows gracefully extending APIs by returning additional values without breaking old call sites, which is a very handy property.

**Comment by jiahao** [comment] 2015-01-21 16:23
Sorry, misread.

**Comment by lilinjn** [comment] 2015-01-21 18:54
Thanks for the feedback -- I should have been more clear that I was seeking comments prior to working on a potential PR (as well as making sure that I wasn't missing some alternate syntax).

**Comment by StefanKarpinski** [comment] 2015-01-21 19:05
No worries – I thought it was clear enough. A PR would be excellent and most appreciated!

**Comment by JeffBezanson** [comment] 2015-01-21 19:22
duplicate of #2626

**Comment by StefanKarpinski** [comment] 2015-01-21 20:20
See? I knew it was a good idea.

**Closed** 2015-01-27 03:27 UTC
Labels: feature, speculative
