### ISSUE TITLE
DataFrames install seems to get stuck in a task loop

### ISSUE THREAD

**Issue by swt30** [JuliaLang/julia#11623] opened 2015-06-09 00:47 UTC
I can't get DataFrames to install into a clean .julia folder using the latest Julia builds. It sticks on 
```
INFO: Cloning cache of DataFrames from git://github.com/JuliaStats/DataFrames.jl.git
```

This is the only package I found this behaviour on - all the others I use seem fine, whether installed one by one or in bulk via REQUIRE. Unless they depend on DataFrames, of course.

Here's the trace when interrupted:
```
ERROR: InterruptException:
 in yieldto at ./task.jl:21
 in wait at ./task.jl:309
 in wait at ./task.jl:225
 in wait at task.jl:58
 in sync_end at ./task.jl:336
 in add at pkg/entry.jl:344
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23
 in process_options at ./client.jl:280
 in _start at ./client.jl:404
```

A bisect shows that this behaviour started after 5863b486435b86d9db25973a684ef4428f563a73.

**Comment by swt30** [comment] 2015-06-09 00:53
After `^C`-ing it, if I do `Pkg.add("DataFrames")

**Comment by vtjnash** [comment] 2015-06-09 01:29
Can you test the following patch to see if it fixes your issue:
```diff
diff --git a/base/process.jl b/base/process.jl
--- a/base/process.jl
+++ b/base/process.jl
@@ -465,8 +465,9 @@ end
 
 function readbytes(cmd::AbstractCmd, stdin::AsyncStream=DevNull)
     (out,pc) = open(cmd, "r", stdin)
+    bytes = readbytes(out)
     !success(pc) && pipeline_error(pc)
-    return readbytes(out)
+    return bytes
 end
 
 function readall(cmd::AbstractCmd, stdin::AsyncStream=DevNull)
```

**Comment by bzklrm** [comment] 2015-06-09 09:01
I have the same problem, and this patch doesn't fix it for me.

**Comment by swt30** [comment] 2015-06-09 10:24
No luck, I'm afraid - hangs at the same places, with the same traces as before.

**Comment by axsk** [comment] 2015-06-09 10:43
I get 
```
INFO: Cloning cache of DataFrames from git://github.com/JuliaStats/DataFrames.jl.git
^CERROR: InterruptException:
 in process_events at ./stream.jl:585
 in wait at ./task.jl:298
 in wait at ./task.jl:225
 in stream_wait at ./stream.jl:281
 in wait at ./process.jl:608
 in readbytes at process.jl:468
 in prefetch at pkg/cache.jl:44
 in update at ./pkg/entry.jl:282
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in update at ./pkg.jl:45
```

after clearing the .cache folder. Without clearing it just hangs at 
```
INFO: Updating METADATA...
```

**Comment by scidom** [comment] 2015-06-09 12:52
I think the problem is not specific to `DataFrames` but rather more general, since `Pkg.update()` is broken since yesterday (it shows `INFO: Updating METADATA...` forever).

**Comment by rickhg12hs** [comment] 2015-06-10 00:59
This is pretty annoying.  After hoping to fix things by wiping out `~/.julia/v0.4` and then `Pkg.init()` followed by restoring `~/.julia/v0.4/REQUIRE` and `Pkg.resolve()`, it fails as above.  And now I have no packages.

**Comment by scidom** [comment] 2015-06-10 01:03
@JeffBezanson @StefanKarpinski @ViralBShah, just bringing this seemingly major issue to your attention as it seems to affect several users, as it breaks the package manager (it's been a day or two since breakage) and can lead to not being able to install any packages.

**Comment by tkelman** [comment] 2015-06-10 01:30
Clearly this needs to be fixed, but can't you revert to 0a2dc356063b4367e31104ba70ad296dd3a38c50 for now?

**Comment by vtjnash** [comment] 2015-06-10 01:58
https://github.com/JuliaLang/julia/issues/11623#issuecomment-110190671 fixes the issue for me and should be pushed to master (i've been working on a different PR and thus haven't had a clean julia instance to apply it to for the last couple days)

**Comment by tkelman** [comment] 2015-06-10 08:56
I was able to reproduce and that patch fixed it for me, so I pushed it as bfc74b294bfa690fe74c989646bc24fd38cbacbb

**Comment by scidom** [comment] 2015-06-10 09:12
Yes, it works now (in fact the package manager is now blazingly fast), we may close this issue.

**Comment by odysseus9672** [comment] 2015-06-10 09:36
Works for me, too.

**Closed** 2015-06-10 09:48 UTC

**Comment by swt30** [comment] 2015-06-10 12:06
I must have done something something wrong when testing the patch because, yes, everything runs smoothly now. Thanks!

**Comment by StefanKarpinski** [comment] 2015-06-10 16:05
Thanks for taking care of this, @vtjnash and @tkelman, and for reporting, @swt30.

**Comment by dwschulze** [comment] 2016-10-18 06:49
Same thing is broken in julia-1ea0de18a6  (v 0.6).

**Comment by nalimilan** [comment] 2016-10-18 07:27
@dwschulze Please file a new issue, as it's unlikely to be the very same problem.
