### ISSUE TITLE
Long array literal leads to OverflowError

### ISSUE THREAD

**Issue by joehuchette** [JuliaLang/julia#12171] opened 2015-07-15 22:23 UTC
Loading the array literal in [this gist](https://gist.github.com/joehuchette/fc42eaab6540eb06aa86) either at the REPL or via ``include`` leads to an ``ERROR: OverflowError()`` on ``v"0.4.0-dev+5994"``, but works fine on v0.3.8.

**Comment by JeffBezanson** [comment] 2015-07-15 22:24
#11320

**Comment by yuyichao** [comment] 2015-07-16 00:19
This is exactly the same error with https://github.com/JuliaLang/julia/issues/11884 and as @JeffBezanson points out is in general #11320. This overflow error should be fixed by https://github.com/JuliaLang/julia/pull/11888.

The first part of that could easily be merged which should fix this issue. I'm not sure what is the best way to do the second part (variable length field descriptor) yet (being conservative might be a good start and should works at least for all tuples.)

Close as duplicate of issues mentioned above.

**Closed by yuyichao** 2015-07-16 00:19 UTC
