### ISSUE TITLE
parse_json regression in String allocations

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#49249] opened 2023-04-04 14:01 UTC
[This commit](https://github.com/JuliaLang/julia/commit/56950e270863c0225b860e313451f70defa82c6d) (https://github.com/JuliaLang/julia/pull/48996) caused a regression in parse_json. Maybe related to https://github.com/JuliaLang/julia/issues/49241? @oscardssmith

**Comment by oscardssmith** [comment] 2023-04-04 16:19
is there a known mechanism by which improving effects could regress performance?

**Comment by vtjnash** [comment] 2023-04-04 19:28
https://github.com/JuliaLang/julia/issues/49241 is the only mechanism I know of currently, which is why I linked to that. Depends on what was changed in that commit though

**Comment by gbaraldi** [comment] 2023-07-13 19:52
We went from
![image](https://github.com/JuliaLang/julia/assets/28694980/09189ca1-886e-4c49-93d9-948c4ac61661)
to
![image](https://github.com/JuliaLang/julia/assets/28694980/e7e27f6c-a91d-43bf-b9dd-6056a886fd9d)

So we are boxing a lot of ints and tuples that we didn't before.

**Comment by oscardssmith** [comment] 2023-08-10 21:06
Is this fixed by https://github.com/JuliaLang/julia/pull/50444?

**Comment by gbaraldi** [comment] 2023-08-10 22:37
No

**Comment by oscardssmith** [comment] 2023-08-10 22:47
Why not? was this issue not caused by #49241? If not, do we have another potential reason why improving effects would regress performance?

**Comment by gbaraldi** [comment] 2023-08-10 22:49
This is a separate issue that was just triggered by that change. But @aviatesk looked into it and I think it's something due to results not being inlineable and fun.

**Comment by JeffBezanson** [comment] 2023-08-15 18:41
duplicate of #50458.

**Closed by JeffBezanson** 2023-08-15 18:41 UTC
Labels: performance, regression
