### ISSUE TITLE
Logical operators (& | ^) are parsed as binary operators

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#14819] opened 2016-01-27 21:44 UTC
Parsing the expression (`1 + 2 + 3`) leads to `Expr(:call, :+, 1, 2, 3)`, i.e. the `+` operator is parsed into a single expression.

However, the logical operators `&`, `|`, `^` are parsed into a binary tree `Expr(:call, :&, 1, Expr(:call, :&, 2, 3))`.

Yet if you create the flat expression `Expr(:call, :&, 1, 2, 3)`, it is evaluated correctly, i.e. Base can already handle this.

I suggest to change the parsing of the logical operators to match those of the arithmetic operators for consistency.

**Comment by JeffBezanson** [comment] 2016-01-27 22:37
Dup of #7368.

Honestly, I hesitate. Look at the ugliness needed to support this: https://github.com/JuliaLang/julia/blob/91dcdaa6736e2c8287fa3bb3f6f6c7eabd8e5218/base/operators.jl#L82-L108
This is also the cause of various performance issues.

I guess to be consistent we'd have to parse all associative operators this way?

**Comment by eschnett** [comment] 2016-01-27 23:48
This code is ugly because variable-length argument lists are expensive, so people need to try and avoid them.

In fact, there is a significant slowdown if one adds more than five integers without using parentheses. This is (in the short term) an argument for parsing everything as binary operation.

Is there a case in Base that optimizes these long sums, e.g. when adding matrices? If so, is this relevant in practice? I'd guess that one usually adds multiples of matrices, not just matrices. Plus, performance-critical code handling matrices is much rarer than adding a series of scalars, where people can rightfully expect high performance without Julia introducing boxing.

**Comment by eschnett** [comment] 2016-01-27 23:58
I was confused by the output of `@code_native`; the limit seems to be adding more than 9 integers.

**Comment by JeffBezanson** [comment] 2016-02-06 06:02
closing as dup of #7368

**Closed by JeffBezanson** 2016-02-06 06:02 UTC
