### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION in julia 1.5

### ISSUE THREAD

**Issue by atbug** [JuliaLang/julia#36976] opened 2020-08-09 00:50 UTC
To reproduce
```julia
x = zeros(ComplexF64, 10001)
x' * x
```

The error message is
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION  with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a3e7280 --  at 0x1a3e7280 --  OLATION  with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a3e7280 --  OLATION  with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a3e7280 -- unknown function (ip: 000000001A3E7280)
in expression starting at REPL[10]:1
in expression starting at REPL[10]:1
 )
  reproduce this fault, and any error messages that follow (in their entirety). Thanks.
```

```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

Does not happen on julia 1.4.2.

**Comment by chethega** [comment] 2020-08-09 01:06
Cannot reproduce on
```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc* (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5###U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-10.0.1 (ORCJIT, broadwell)
```

**Comment by atbug** [comment] 2020-08-09 01:14
Is is really something wrong with my machine? Can anyone with i5-9265U or i9-9900(https://github.com/JuliaPy/PyPlot.jl/issues/477) test this issue?

**Comment by runapp** [comment] 2020-08-09 01:27
Confirmed on Win10 1909(18363)

```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 3500X 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)
```

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception:
Please submit a bug repor at 0x1a51b500 --  at 0x1a51b500 --  g report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a51b500 -- unknown function (ip: 000000001A51B500)
  reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a51b500 -- unknown function (ip: 000000001A51B500)
  reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a51b500 -- unknown function (ip: 000000001A51B500)
in expression starting at REPL[2]:1
in expression starting at REPL[2]:1
 0)
  reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception:
```

**Comment by chethega** [comment] 2020-08-09 01:36
Can you post the output of 
```
julia> LinearAlgebra.BLAS.determine_vendor()
:openblas

julia> LinearAlgebra.BLAS.openblas_get_config()
"OpenBLAS 0.3.10 NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=64"
```

**Comment by atbug** [comment] 2020-08-09 01:36
```julia
julia> LinearAlgebra.BLAS.determine_vendor()
:openblas64

julia> LinearAlgebra.BLAS.openblas_get_config()
"OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=32"
```

**Comment by chethega** [comment] 2020-08-09 01:56
Ok, I tested on the official release, cannot reproduce either:
```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5###U CPU @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)

julia> LinearAlgebra.BLAS.determine_vendor()
:openblas64

julia> LinearAlgebra.BLAS.openblas_get_config()
"OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=32"
```
So it does appear to be a windows-specific issue. I think somebody else with access to a windows machine needs to take over here :(

**Comment by masuday** [comment] 2020-08-09 02:52
It happens on Julia 1.5 or later (including nightly build) in windows with "libopenblas64_.dll" (33,470,581 bytes). This issue was solved when:

- I replaced the DLL with the previous version (supplied in Julia 1.4.1, libopenblas64_.dll 33,747,481 bytes).
- Or, I put `LinearAlgebra.BLAS.set_num_threads(1)`.

By the way, The error occurred on my AMD PC as well.

```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 PRO 2400GE w/ Radeon Vega Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver1)

julia> LinearAlgebra.BLAS.openblas_get_config()
"OpenBLAS 0.3.9  USE64BITINT DYNAMIC_ARCH NO_AFFINITY Zen MAX_THREADS=32"
```

**Comment by andreasnoack** [comment] 2020-08-18 07:29
See also https://github.com/JuliaLang/julia/issues/36522#issuecomment-674316590 for some more debug info. @masuday would you be able to make a small Fortran repro of this and file this as an issue in the OpenBLAS repo?

**Comment by masuday** [comment] 2020-08-18 13:50
@andreasnoack Sure. I will try it.

**Comment by masuday** [comment] 2020-08-18 20:05
I can reproduce this issue using a Fortran program with OpenBLAS v0.3.9 and v0.3.10 (master) compiled by myself on Windows. I will file it to the OpenBLAS repo.

```Fortran
program test_zdot
   implicit none
   integer :: n,inc
   complex*16 :: val
   complex*16,allocatable :: zx(:)

   interface
      COMPLEX*16 FUNCTION zdotc(N,ZX,INCX,ZY,INCY)
         INTEGER incx,incy,n
         COMPLEX*16 zx(*),zy(*)
      END FUNCTION zdotc
   end interface

   read(*,*) n
   allocate(zx(n))
   zx(:) = 0.0
   inc = 1
   val = zdotc(n,zx,inc,zx,inc)
   print *,val
end program test_zdot
```

```
# compilation
gfortran test_zdot.f90 libopenblas.dll.a

# okay case
$ ./a.out
10
               (0.0000000000000000,0.0000000000000000)

# current issue
10001

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0xffffffff
Segmentation fault
```

**Comment by masuday** [comment] 2020-08-20 16:34
FYI: A workaround is to use `OPENBLAS_CORETYPE=Nehalem`.

**Comment by masuday** [comment] 2020-08-24 12:43
This issue was fixed (https://github.com/xianyi/OpenBLAS/pull/2791). Probably the next version of OpenBLAS ships this fix.

**Comment by andreasnoack** [comment] 2020-08-24 13:45
Great. Thanks for following through.

**Comment by masuday** [comment] 2020-10-27 18:31
This problem was fixed in OpenBLAS 0.3.12. I confirmed the above MWE worked with the new OpenBLAS but I haven't try Julia.

**Comment by mkitti** [comment] 2021-01-22 00:45
xref https://discourse.julialang.org/t/dot-abruptly-ends-julia-session/53748

I can reproduce this error on Version 1.6.0-beta1.0
```julia
julia> versioninfo()
Julia Version 1.6.0-beta1.0
Commit b84990e1ac (2021-01-08 12:42 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
```

**Comment by tknopp** [comment] 2021-03-22 15:04
@KristofferC, @ararslan: This is a severe bug that should not slip into into the 1.6 release. Not sure if it is solved by #39216 but with rc3 we have a windows machine where Julia still segfaults. Or is #39216 not in rc3?

**Comment by KristofferC** [comment] 2021-03-22 15:13
It looks like that has not been included in 1.6. The 1.6 release is however imminent so it is possible that will go into 1.6.1. I'll add a backport label to it though so it isn't forgotten.

**Comment by tknopp** [comment] 2021-03-22 15:34
yes, please do so. Would shipping 1.6.0 on windows with 1 thread BLAS be an option? I mean: publishing with segfaults is much worse.

**Comment by KristofferC** [comment] 2021-03-22 15:53
> Would shipping 1.6.0 on windows with 1 thread BLAS be an option

I don't think that is an option, no.

**Comment by tknopp** [comment] 2021-03-22 16:13
Hm, I would have assumed that shipping Julia with a known segfault is a release blocker. It actually surprises me that there have not been more users stumbling over this bug. But anyway, I just wanted to give you feedback regarding the post https://discourse.julialang.org/t/julia-v1-6-0-rc3-is-now-available that rc3 does not work on our windows system and that it crashes with a segmentation fault.

**Comment by KristofferC** [comment] 2021-03-22 16:19
I thought this had been happening since 1.5.0? So releasing 1.6.0 (with all of its improvement) does not make the current situation any worse?

**Comment by mkitti** [comment] 2021-03-22 16:24
> I thought this had been happening since 1.5.0? So releasing 1.6.0 (with all of its improvement) does not make the current situation any worse?

Correct. This crashes 1.5.0.

```
PS > julia

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0 (2020-08-01)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

julia> x = zeros(ComplexF64, 10001);

julia> x' * x

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION  with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a3a7280 --  at 0x1a3a7280 --  OLATION  with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x1a3a7280 -- unknown function (ip: 000000001A3A7280)
in expression starting at REPL[3]:1
in expression starting at REPL[3]:1
 0)
  reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception:
```

**Comment by tknopp** [comment] 2021-03-22 17:16
Julia 1.6 will be an incredible release and I am looking forward to it. I don't share your opinion that a regression that slipped into 1.5 is ok to be in 1.6 just because not enough people have complained about it. I think this just shows that Julia has a small user base on windows. But go ahead, I have implemented the workaround in my package (https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/master/src/MRIReco.jl#L40) and will remove it once #36976 is fixed.

**Comment by mkitti** [comment] 2021-03-22 17:46
@tknopp I sympathize as I usually use Julia on Windows for work. However, we're pretty late in the Julia 1.6.0 release process. I hope for a speedy 1.6.1 release to resolve this.

Also is there room in NEWS.md for known defects and workarounds?

**Comment by deltaeecs** [comment] 2021-03-23 03:34
reproduce on 1.5.4 and 1.6.0-rc3 on win10

versioninfo():
Julia Version 1.5.4
Commit 69fcb5745b (2021-03-11 19:13 UTC)       
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia

Julia Version 1.6.0-rc3
Commit 23267f0d46 (2021-03-16 17:04 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia

**Comment by vtjnash** [comment] 2021-03-30 15:29
Fixed by https://github.com/JuliaLang/julia/pull/39216 (for v1.6.1 and master)

**Closed by vtjnash** 2021-03-30 15:29 UTC
Labels: external dependencies, linear algebra, regression

**Comment by Charles314** [comment] 2022-07-21 05:10
Please solve this issue

**Comment by mkitti** [comment] 2022-07-21 08:18
> Please solve this issue

Please be more specific. The issue is currently considered to be solved in the latest versions of Julia but may be pending backport to the 1.6 LTS branch.

I recommend creating a new issue describing the version of Julia you are using and how to reproduce the problem with a minimum working example.
