### ISSUE TITLE
`sprint(; context=io)` loses `displaysize` of `io`

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#42649] opened 2021-10-14 13:58 UTC
```jl
julia> displaysize(stdout)
(17, 160)

julia> displaysize(IOContext(stdout))
(17, 160)

julia> sprint(; context=stdout) do io
           print(io, displaysize(io))
       end
"(24, 80)"
```

Imo, the last one should be consistent with the others.

Workaround:

```jl
julia> ioc = IOContext(stdout, :displaysize=>displaysize(stdout));

julia> sprint(; context=ioc) do io
           print(io, displaysize(io))
       end
"(17, 160)"
```

**Comment by vtjnash** [comment] 2021-10-14 14:16
This is mainly intentional, though a frequently asked question. The rationale being that even if the terminal was that size, the portion of the terminal relevant to the inner `print` is only a subset of that size, so we instead just use the default value.

**Comment by jmichel7** [comment] 2021-10-15 10:23
If an `IOContext` loses its `:displaysize` in some circumstances, this should be documented.

**Comment by vtjnash** [comment] 2022-01-07 22:26
Duplicate of #34721

**Closed by vtjnash** 2022-01-07 22:26 UTC
