### ISSUE TITLE
pipeline errors with a IOBuffer as first argument

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#15479] opened 2016-03-13 19:21 UTC
According to the docs pipeline accepts a IOBuffer as first argument, but  (and see [also](https://groups.google.com/forum/#!topic/julia-users/-66VWszB-mM))

```
julia> run(pipeline(IOBuffer("a xyz b"), `grep xyz`))
ERROR: MethodError: `uvtype` has no method matching uvtype(::Base.AbstractIOBuffer{Array{UInt8,1}})
 in _jl_spawn at process.jl:253
 in anonymous at process.jl:415
 in setup_stdio at process.jl:403
 in spawn at process.jl:414
 in spawn at process.jl:293
 in run at process.jl:530
```

**Comment by vtjnash** [comment] 2016-03-13 20:12
documentation isn't really intended to be legalistic. the operating system only understands how to use native I/O streams (like `Pipe`), while Julia can create many other types of I/O stream.

**Comment by Keno** [comment] 2016-03-13 20:14
This seems like a reasonable feature request though. The semantics seem pretty clear (write the contents of the IOBuffer as STDIN).

**Comment by vtjnash** [comment] 2016-03-13 21:23
we already have an API for that (`writeall`). but that's not the right semantics for this (IOBuffer is a File abstraction, not a Stream abstraction). then there's also the problem of defining the error handling model.

re-closing as "not a bug".

**Comment by tkelman** [comment] 2016-03-13 21:25
> According to the docs pipeline accepts a IOBuffer as first argument

We should at least clarify the docs then? Maybe not intended to be legalistic, but if people are getting confused that's a doc bug.

**Comment by joa-quim** [comment] 2016-03-13 21:34
To clarify [IOBuffer ](http://www.google.com/url?q=http%3A%2F%2Fdocs.julialang.org%2Fen%2Frelease-0.4%2Fstdlib%2Fio-network%2F%23Base.IOBuffer&sa=D&sntz=1&usg=AFQjCNGWleEngmk5sE7IVGZaWPzJ_Eo1zw) says

```
IOBuffer() → IOBuffer
    Create an in-memory I/O stream.
```

but than I can't use it in pipeline. How can I use then? I mean I can I put my string in STDIN and call pipeline on it?

**Comment by vtjnash** [comment] 2016-03-13 22:33
SO or julia-users is a better place for questions (you're looking for `open(p, "w")`, not IOBuffer)

**Comment by joa-quim** [comment] 2016-03-13 23:26
Sorry, it seamed appropriate to ask the question here since it's an consequence of doc contradiction. And BTW I had asked [this ](https://groups.google.com/forum/#!topic/julia-users/-66VWszB-mM)before in julia-users. (and I still need help)

**Comment by nalimilan** [comment] 2016-03-14 09:49
Reopening as a doc issue. Though adding a method which would raise an error with an explanation would be even more helpful.

**Comment by stevengj** [comment] 2018-02-15 21:14
See also #26061, where @vtjnash suggested `pipeline(exename, stdin=IOBuffer(input))`, and the implementation could be modeled on the code in that PR.

**Comment by KristofferC** [comment] 2019-03-23 12:28
Works now, https://github.com/JuliaLang/julia/pull/30278.

**Closed by KristofferC** 2019-03-23 12:28 UTC
Labels: doc
