### ISSUE TITLE
Keyword arguments can be placed anywhere in a function call

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/julia#54481] opened 2024-05-15 20:06 UTC
Is this intended?

```julia
julia> cat(dims=1, ones(3), zeros(3))
6-element Vector{Float64}:
 1.0
 1.0
 1.0
 0.0
 0.0
 0.0

julia> cat(ones(3), dims=1, zeros(3))
6-element Vector{Float64}:
 1.0
 1.0
 1.0
 0.0
 0.0
 0.0
```

```julia
Julia Version 1.10.3
Commit 0b4590a550 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 12 default, 2 interactive, 7 GC (on 12 virtual cores)
```

**Comment by adienes** [comment] 2024-05-15 20:35
duplicate of https://github.com/JuliaLang/julia/issues/37589

**Closed** 2024-05-15 21:23 UTC
