### ISSUE TITLE
Plain old multiplication much slower than Matlab 2013a

### ISSUE THREAD

**Issue by mb1234** [JuliaLang/julia#14576] opened 2016-01-06 19:06 UTC
Julia 0.4:
julia> A=rand(3000,3000);B=rand(3000,3000);
julia> tic();for k=1:50;C=A.*B;end;toc()
elapsed time: 2.386786733 seconds
2.386786733

Matlab 2013a:

> > A=rand(3000);B=rand(3000);
> > tic;for k=1:50;C=A.*B;end;toc
> > Elapsed time is 1.501691 seconds.

This is on a 2 core machine. I also ran it on another computer with 6 cores and the difference is greater (about 4x). So it seems Matlab is using parallelism for .\* while Julia isn't. A little experimentation in Matlab shows that it drops to 1 core when the matrix size is 191x191 or smaller.

**Comment by KristofferC** [comment] 2016-01-06 19:10
What is the issue here? Julia does not run multithreaded code get so naturally it will be slower. Your best bet right now is the ParallelAccelerator.jl package.

**Comment by JeffBezanson** [comment] 2016-01-06 19:13
Duplicate of #1802

**Comment by iamed2** [comment] 2016-01-07 03:29
in Julia 0.5 (it's roughly the same as 0.4):
```
julia> A=rand(3000,3000);B=rand(3000,3000);

julia> tic();for k=1:50;C=A.*B;end;toc()
elapsed time: 2.408215731 seconds
2.408215731

julia> tic();for k=1:50;C=A.*B;end;toc()
elapsed time: 1.662830871 seconds
1.662830871
```

MATLAB 2012b:
```
>> A=rand(3000);B=rand(3000);
tic;for k=1:50;C=A.*B;end;toc
Elapsed time is 1.429565 seconds.
>> tic;for k=1:50;C=A.*B;end;toc
Elapsed time is 1.455223 seconds.
```

Also on a 2 core machine. Seems like there is an initial compilation pass involved that is skewing the difference?

**Comment by KristofferC** [comment] 2017-01-22 13:32
Closing as dup of #1802.

**Closed by KristofferC** 2017-01-22 13:32 UTC
Labels: performance
