### ISSUE TITLE
Extend reinterpret to immutable isbits() type

### ISSUE THREAD

**Issue by uliano** [JuliaLang/julia#13701] opened 2015-10-21 04:26 UTC
```
julia> immutable Words32
         lo::UInt32
         hi::UInt32
       end
julia> isbits(Words32)
true
julia> a=UInt64(0x123456789abcdef0)
0x123456789abcdef0
julia> b=reinterpret(Words32,a)
ERROR: reinterpret: expected bits type as first argument
 in reinterpret at essentials.jl:115
```

Besides the contradiction isbits() != bits type I think that would definitely be useful to be able to reinterpret immutables

**Comment by timholy** [comment] 2015-10-21 14:44
Works if you put `a` inside an array.

**Comment by uliano** [comment] 2015-10-21 14:52
I know, there are many other more or less inefficient ways to get it "working", and some quite efficient (the cost is just one shift), I don't think the point is to just have it working, In C I can do that at NO cost, if Julia wants to "solve" the 2 language inconvenience it should eventually be able to do the same.

**Comment by JeffBezanson** [comment] 2015-10-21 15:19
I think this should work for Tuple types, but it probably shouldn't work for arbitrary user-defined types, since that would violate abstraction.

**Comment by vtjnash** [comment] 2015-10-21 16:26
the shift solution is probably slightly cheaper since it is less likely to inhibit other optimizations, but is otherwise identical to the "direct cast". you can't do this in C without violating the C standard (for tbaa) or writing some fairly verbose union code (or use mask and shift). and likely in the ideal case, all of these will lower to the same shift code in assembly.

**Comment by uliano** [comment] 2015-10-21 18:41
@vtjnash I think that either "fairly verbose" (but fast) union code either equally verbose but afaik C99 standard following code
```
typedef struct words32 {
    uint32_t lo;
    uint32_t hi;
} Words32;
Words32 b;
uint64_t a = 0x123456789abcdef0;
b=*(Words32 *)&a;
printf("0x%08x\n0x%08x\n",b.lo,b.hi);
```
giving
```
0x9abcdef0
0x12345678
```
are faster than shifts or the like.

@JeffBezanson I'm quite novice in Julia and I don't understand what do you mean by "violate abstraction". About tuples you mean something like this?
```
julia> a=0x123456789abcdef0
0x123456789abcdef0
julia> b=reinterpret(Tuple{UInt32,UInt32},a)
ERROR: reinterpret: expected bits type as first argument
 in reinterpret at essentials.jl:115
```

**Comment by vtjnash** [comment] 2015-10-21 19:24
> b=*(Words32 *)&a;

as I said before, this isn't standards-compliant C code and the result of this load is undefined (e.g. the compiler is free to delete it). use `-Wall -Werror` and it won't compile due to the tbaa violation. 

> are faster than shifts or the like.

please benchmark it and/or look at the native code. Your code example has endian issues and is less efficient (slower) than a simple shift.

**Comment by StefanKarpinski** [comment] 2015-10-21 21:48
Whether there are other approaches or not (there are), would it be feasible to make reinterpret work for this kind of cast as it does in C?

**Comment by uliano** [comment] 2015-10-22 04:36
@vtjnash Sure it has endian issue all dirty stuff like that have, on clang I have no violation whatsoever:
```
uliano@MBookPro:~/Desktop$ clang -Wall -Werror test.c
uliano@MBookPro:~/Desktop$ ./a.out
0x9abcdef0
0x12345678
```
then about "simple" shift, think the shifting overhead if I would have liked to split into 8 bytes.

**Comment by uliano** [comment] 2015-10-22 04:45
About tuples. I don't know Julia internals but if there is a cost in accessing tuple elements that would make the tuple approach useless. I'assuming that the access to members of a concrete immutable type (all member types specified) would be ahead of time at no cost (as is in C for accessing struct members). If this is not the case this issue become secondary to that.

**Comment by timholy** [comment] 2015-10-22 09:06
A tuple-type `Tuple{T1,T2}` is essentially an immutable with fields that can be accessed by number but not by name.

**Comment by uliano** [comment] 2015-10-22 10:16
The question is whether the address of each field in the tuple (and also in "concrete" immutables such as above) can be known compile time in order to spare integer arithmetic otherwise needed to reach the field itself (we would save a shift to pay for reaching the field)

**Comment by timholy** [comment] 2015-10-22 14:09
@uliano, you can answer all these questions yourself:
```jl
julia> foo{TT}(t::TT) = t[2]  # tuples aren't specialized by default, but we can force it
foo (generic function with 1 method)

julia> @code_native foo((Int8(5), UInt(15)))
        .text
Filename: none
Source line: 1
        pushq   %rbp
        movq    %rsp, %rbp
Source line: 1
        movq    8(%rdi), %rax
        popq    %rbp
        ret

julia> @code_native foo((Int(5), UInt(15)))
        .text
Filename: none
Source line: 1
        pushq   %rbp
        movq    %rsp, %rbp
Source line: 1
        movq    8(%rdi), %rax
        popq    %rbp
        ret

julia> @code_native foo((Int128(5), UInt(15)))
        .text
Filename: none
Source line: 1
        pushq   %rbp
        movq    %rsp, %rbp
Source line: 1
        movq    16(%rdi), %rax
        popq    %rbp
        ret
```

**Comment by vtjnash** [comment] 2015-10-22 16:27
@uliano you need to turn on optimizations, or the compiler doesn't run this warning pass. it also seems that clang doesn't detect this error? gcc is able to detect the error and emits the expected warning:
```
~$ /opt/local/bin/gcc-mp-4.9 -Wall -Werror -Os test.c 
test.c: In function 'main':
test.c:11:5: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
     Words32 b=*(Words32*)&a;
     ^
cc1: all warnings being treated as errors
```

> then about "simple" shift, think the shifting overhead if I would have liked to split into 8 bytes.

this is just wrong, please stop repeating it. the assembly sequence to extract the high bytes of a register is the shift operation. unlike the 8086, there is no ah / al register pairs. and both clang and gcc constant fold the entire thing away for your example anyways until there's not really anything left to test.

**Comment by simonbyrne** [comment] 2015-10-22 16:32
@uliano see [here](http://stackoverflow.com/a/98356/392585) for a description of what is/isn't valid for C behaviour.

**Comment by uliano** [comment] 2015-10-23 07:59
tnks @simonbyrne, I learned something I wasn't aware: I have sometimes used "bad" type punning like that in the last 2 decades, maybe I have just been lucky or maybe even gcc if you let him generate the code behaves as expected 

```
$ gcc-5 -Wall -O5 test.c
test.c: In function 'main':
test.c:11:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     b=*(Words32 *)&a;
     ^
$ ./a.out
0x9abcdef0
0x12345678
```
clang doesn't complain even with optimizations and flags
```
$ clang -Wall -Werror -Ofast --pedantic --pedantic-errors test.c
$ ./a.out
0x9abcdef0
0x12345678
```
however even if pointer casting is formally unspecified by the standard it appears that at least since C99 it is allowed through "fairly verbose" union code. here some examples in code that runs within Julia:

https://github.com/JuliaLang/openlibm/blob/master/src/math_private.h

About shifts, I'm very uncomfortable with x86 assembly (so I'm not sure about the following) however, at least when accessing memory, it seems to me that no shift is used, I tried with bytes as they have the smaller granularity, both with tuples and immutables

```
function f(t)
  t[6]
end

@code_native f((Uint8(7), UInt8(6),Uint8(5), UInt8(4),Uint8(3), UInt8(2),Uint8(1), UInt8(0)))

.section	__TEXT,__text,regular,pure_instructions
Filename: In[13]
Source line: 2
pushq	%rbp
movq	%rsp, %rbp
Source line: 2
movb	5(%rdi), %al
popq	%rbp
ret


immutable B8
  a::UInt8
  b::UInt8
  c::UInt8
  d::UInt8
  e::UInt8
  f::UInt8
  g::UInt8
  h::UInt8
end

function g(a::B8)
  return a.f
end

@code_native g(B8(7,6,5,4,3,2,1,0))

.section	__TEXT,__text,regular,pure_instructions
Filename: In[9]
Source line: 2
pushq	%rbp
movq	%rsp, %rbp
Source line: 2
movb	5(%rdi), %al
Source line: 2
popq	%rbp
ret
```

said that, I think this discussion is going a little out of focus which in my opinion is:

would it be desirable in Julia to be able to efficiently access sub units of types like it is in C?

**Comment by StefanKarpinski** [comment] 2015-10-23 11:08
There are two issues here:

1. Is there a performance issue in Julia compared to C. The answer seems to be "no" – doing the shift is not a performance problem. Your sense that C is "doing less work" is based on a mental model of what C code compiles down and operation costs that probably isn't accurate: it only syntactically looks like C is doing less work – there's a strong chance that a C compiler would implement this operation the same way.

2. Regardless of performance, can we have Julia's reinterpret work in this case – it already works in the array case, can it also be made to work in the scalar case? This could sometimes be convenient and it's a little odd to have cases where `reinterpret(T, [v])` works but `reinterpret(T, v)` doesn't or vice versa.

**Comment by vtjnash** [comment] 2016-03-26 03:02
duplicate of https://github.com/JuliaLang/julia/issues/10140

**Closed by vtjnash** 2016-03-26 03:02 UTC
