### ISSUE TITLE
`@less [1,2][end]` throws `UndefVarError`

### ISSUE THREAD

**Issue by h-larsson** [JuliaLang/julia#44596] opened 2022-03-13 01:04 UTC
MWE:
```
julia> a = [1,2]
2-element Vector{Int64}:
 1
 2

julia> @less a[1] # WORKS

julia> @less a[end] # ERROR
ERROR: UndefVarError: end not defined
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```
This also does not work for `@code_native a[end]` and similar variants. 

Julia version:
```
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)


```

**Comment by fredrikekre** [comment] 2022-03-13 13:26
Duplicate of #37379.

**Closed by fredrikekre** 2022-03-13 13:26 UTC
