### ISSUE TITLE
`resize!` is O(N) when downsizing.

### ISSUE THREAD

**Issue by sgaure** [JuliaLang/julia#56359] opened 2024-10-28 08:47 UTC
From https://discourse.julialang.org/t/why-does-a-vector-with-10-times-more-elements-takes-2x-5x-less-time-to-pre-allocate/121828/7?u=sgaure

This isn't as it should be. Downsizing a bits vector shouldn't be dependent on the size?

```
using Plots

function f(n)
    a = Vector{Int}(undef, n)
    s = time_ns()
    resize!(a, 8)
    time_ns() - s
end

x = 8:10:1000000
y = f.(x)

plot(x, y)
versioninfo()
```
![Image](https://github.com/user-attachments/assets/5ca732a9-2085-4e07-b653-973adb994a5f)
```
Julia Version 1.11.1
Commit 8f5b7ca12ad (2024-10-16 10:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen Threadripper PRO 5945WX 12-Cores
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver3)
Threads: 24 default, 0 interactive, 12 GC (on 24 virtual cores)
```

**Comment by vtjnash** [comment] 2024-10-28 13:06
It looks like LLVM may have decided it was profitable to vectorize that for loop instead, since it doesn't contain any instructions that would hinder that :joy: (literally, it doesn't contain any instructions and could be removed). See `@code_llvm raw=true Base._deleteend!(Int[], 0)`

Aside: the `resize!` function, particularly when used repeatedly, is intended to override the normal heuristics in order to allow the use to guarantee `O(n)` behavior instead of the default `O(1)` behavior

**Comment by KristofferC** [comment] 2024-10-28 13:07
Accessing a mutable field etc in

https://github.com/JuliaLang/julia/blob/2cdfe062952c3a1168da7545a10bfa0ec205b4db/base/array.jl#L219

is probably enough to not allow the loop at 

https://github.com/JuliaLang/julia/blob/2cdfe062952c3a1168da7545a10bfa0ec205b4db/base/array.jl#L1242-L1244

to fold away.

**Comment by KristofferC** [comment] 2024-10-28 13:08
> Aside: the resize! function, particularly when used repeatedly, is intended to override the normal heuristics in order to allow the use to guarantee O(n) behavior instead of the default O(1) behavior

I thought that was `sizehint!` if I understand what you are referring to.

**Comment by vtjnash** [comment] 2024-10-28 13:29
Ah, maybe that is `sizehint!`. I assumed resize called that, but maybe not.

But yes, it is just the loop that remains, nothing from the function

**Comment by oscardssmith** [comment] 2024-10-28 13:35
I think the only reason this doesn't get optimized is that we don't know that
```
│   %7 = $(Expr(:gc_preserve_begin, :(%6)))
│        $(Expr(:gc_preserve_end, :(%7)))
```
with nothing in between can be deleted (or alternatively, the problem is that we gc_preserve even in the bitstype case)

**Comment by oscardssmith** [comment] 2024-10-28 13:42
fixed by https://github.com/JuliaLang/julia/pull/56364

**Comment by oscardssmith** [comment] 2024-10-28 13:44
@gbaraldi could the allocopt pass get smarter so the original version of this gets solved?

**Comment by gbaraldi** [comment] 2024-10-28 15:25
Potentially yes

**Closed** 2024-10-28 21:57 UTC
Labels: performance, regression 1.11
