### ISSUE TITLE
slow sparse matrix-vector product with a view(transpose(B))

### ISSUE THREAD

**Issue by tomhaber** [JuliaLang/julia#37801] opened 2020-09-29 13:03 UTC
I noticed that doing the following
`mul!(C, A, view(B,:,j)) # where A is a SparseMatrixCSC and B is transpose(any matrix)`,
falls back to the generic matvecmul.

The thing that breaks it, is the transpose. Without that it works as expected.
Of course, if I know that B is a transpose of some matrix, the code would just access the row j of that matrix instead.

BTW: I'm trying to avoid unnecessary copies of the B[:,j] vectors.

**Comment by dkarrasch** [comment] 2020-10-02 15:18
The question is whether in

https://github.com/JuliaLang/julia/blob/7344d19e6f2dfe162dcbdf610fd311056c669eaf/stdlib/SparseArrays/src/linalg.jl#L28

`StridedVector` can be relaxed to `AbstractVector`, and I don't see why not. @mbauman might be able to tell quickly.

**Comment by mbauman** [comment] 2020-10-02 15:37
IIRC a lot of the `mul!` methods can be similarly widened, but last time I looked into this it was a bit of an ambiguity quagmire that required a lot of simultaneous work.

Duplicate of #33219

**Closed by mbauman** 2020-10-02 15:37 UTC
Labels: linear algebra, sparse
