### ISSUE TITLE
REPL: cannot assign variables whose names match a name exported from Base after any tab autocompletion

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#30234] opened 2018-12-02 02:10 UTC
If you press tab twice to autocomplete a name, the variable `names` is no longer assignable in global scope. 

In a new REPL session:

```
julia> f<tab><tab>
factorial   fieldoffset  finalizer    findnext     flipsign     for
false       fieldtype    finally      findprev     float        foreach
falses      filemode     findall      first        floatmax     frexp
fd          filesize     findfirst    firstindex   floatmin     fullname
fdio        fill         findlast     fld          floor        function
fetch       fill!        findmax      fld1         flush        functionloc
fieldcount  filter       findmax!     fldmod       fma
fieldname   filter!      findmin      fldmod1      foldl
fieldnames  finalize     findmin!     flip         foldr
julia> names = 10
ERROR: cannot assign variable Base.names from module Main
Stacktrace:
 [1] top-level scope at none:0

julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = subl
```

I saw a few related issues (e.g. https://github.com/JuliaLang/julia/issues/23677) but am not sure if they describe the same issue. If they do, feel free to close.

**Comment by cstjean** [comment] 2018-12-03 16:47
Not just `names`; any Base function.

```julia
julia> sin = 1
ERROR: cannot assign variable Base.sin from module Main
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by mauro3** [comment] 2018-12-03 18:59
Note that in 0.6 this only threw a warning:
```
julia> sin = 1
WARNING: imported binding for sin overwritten in module Main
1
```

**Comment by JeffBezanson** [comment] 2018-12-03 19:05
Maybe fixed by #29962?

**Comment by StefanKarpinski** [comment] 2018-12-03 20:00
No, still happens on master.

**Comment by StefanKarpinski** [comment] 2018-12-03 20:05
Weird: I just stopped and restarted Julia and now can't reproduce this. Freshly built Julia. 💢

**Comment by StefanKarpinski** [comment] 2018-12-03 20:21
This seems to reproduce it reliably in a fresh session:
```jl
julia> using Linear<tab>Algebra

julia> sin = 1
ERROR: cannot assign variable Base.sin from module Main
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by cstjean** [comment] 2018-12-03 20:50
On a fresh 1.0.2 session, `si<tab>n = 1` triggers it every time for me.

**Comment by StefanKarpinski** [comment] 2018-12-03 20:55
That's a different (similar) bug and is already fixed on master.

**Closed** 2018-12-05 00:41 UTC
Labels: REPL
