### ISSUE TITLE
Segmentation fault while defining a tricked out convert method

### ISSUE THREAD

**Issue by shashi** [JuliaLang/julia#11160] opened 2015-05-06 13:42 UTC
```julia
Version 0.4.0-dev+4464 (2015-04-23 00:49 UTC)
Commit 7e63e6a* (13 days old master)
x86_64-linux-gnu

julia> typealias Try{T} Union(T, Exception)
Union(Exception,T)

julia> Base.convert{T}(::Type{Try{T}}, x) = convert(T, x)
Segmentation fault (core dumped)
```

(same error if I skip the type alias)

On 0.3.5 this results in an infinite loop printing
```
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
convert at none:1
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
convert at none:1
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
convert at none:1
^CSegmentation fault (core dumped)
```

Also this convert method is probably dumb. My intent is to allow `x` to be converted, say, from `Int64` to a `Try{Float64}`. Am I trying the right thing?

**Comment by JeffBezanson** [comment] 2015-05-25 20:04
I don't get the segfault. Is there a call to this `convert` definition that triggers it?

We don't seem to be able to match `Type{Union(Float64,Exception)}` to `Type{Union(T,Exception)}` at all currently.

**Comment by dhoegh** [comment] 2015-05-25 20:18
I can reproduce this on 0.3.8 and mater on windows.

**Comment by mauro3** [comment] 2015-05-28 13:35
On linux segaults on 0.3.9-pre+27 but not on 0.4.0-dev+5005

**Comment by andrewcooke** [comment] 2015-06-06 18:30
is this related - https://groups.google.com/forum/#!topic/julia-users/8Iyoq0hnnWI

**Comment by yuyichao** [comment] 2015-06-06 18:59
I think the segfault is related to the wierd type breaking GC's expectation

**Comment by vtjnash** [comment] 2016-04-10 05:24
it looks like the second case is fixed on master:
```
julia> abstract C{T<:Union(Void,Int)}
WARNING: Union(args...) is deprecated, use Union{args...} instead.
 [inlined code] from error.jl:26
 in depwarn(::ASCIIString, ::Symbol) at deprecated.jl:64
 in Union(::Type{T}, ::Type{T}) at deprecated.jl:50
 in eval(::Module, ::Any) at ./boot.jl:236
while loading no file, in expression starting on line 0

julia> type D{T}<:C{T} d::T end

julia> D(nothing)
D{Void}(nothing)

julia> D(1)
D{Int64}(1)

julia> D(1.1)
ERROR: TypeError: C: in T, expected T<:Union{Int64,Void}, got Type{Float64}
 in D{T}(::Float64) at none:1
 in eval(::Module, ::Any) at ./boot.jl:236
```

i'm not sure what to make of that first case, since it sounds like it perhaps fixed in an early v0.4-dev build?

**Comment by timholy** [comment] 2016-04-22 11:13
Both still seem fixed, so closing.

**Closed by timholy** 2016-04-22 11:13 UTC
Labels: bug, needs-tests, types and dispatch

**Comment by shashi** [comment] 2016-04-22 11:29
:+1:
