### ISSUE TITLE
Pkg.Read.installed() should probably not be swallowing unexpected exceptions

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#13589] opened 2015-10-13 19:28 UTC
See [here](https://github.com/JuliaLang/julia/blob/2b8773f69498c062001495ada7268976cab49121/base/pkg/read.jl#L186-L187). One of these exceptions was a bug in the code that I fixed (#13572). @tkelman suggests that perhaps anything that's not a PkgError should be rethrown, but I don't know enough about the cases where exceptions are thrown in this code to feel comfortable making that change.

cc @wildart

**Comment by wildart** [comment] 2015-10-14 00:49
You'll find several places where exceptions is swallowed. My reason was to provide better experience while working with Pkg. Usually, exception is dumped in functions which iterate through all packages. There are some errors that cannot be resolved and relate to limitations in libgit2 library, e.g. unsupported protocols. If such error would occur and exceptions is not swallowed, and there is no way to resolve it with the means provided by Pkg, the function, which has raised this exception if it called in a loop, would terminate it. If an underlying reason of the error cannot be resolved (see above), the loop will always be terminated in same place making Pkg unusable until the problem would be resolved with external measures (e.g. we will not provide `git` with julia binary package on windows). So, the decision was gracefully exit from such situations. 

One of the solutions is to provide information about dumped exceptions. Or go back to throwing errors, which I dislike because. REPL, as UI, should provide some usability standards, which means that some exceptions should be caught and do not hinder user experience.

**Comment by tkelman** [comment] 2015-10-14 00:56
I think the recently encountered bug shows pretty clearly that these try-catches should be more careful to distinguish between exceptions that are anticipated to happen from those that aren't, and only try to hide or work around the former.

**Comment by wildart** [comment] 2015-10-14 01:04
I agree, such cases should have been handled better.

**Comment by jakebolewski** [comment] 2015-10-14 15:36
You should only swallow  LigGit2 exceptions with error codes / error classes that you anticipate being a problem, not all exceptions.

**Comment by simonster** [comment] 2015-10-14 16:34
It might also be useful to wrap the exception when rethrowing it to provide information about the package that Pkg was processing when it was thrown, to aid in reproducing such issues later.

**Comment by wildart** [comment] 2015-10-15 23:59
Issue #13584 shows how unhanded exception makes Pkg unusable. I still think that any operation on a single package can terminate with exception. But during batch operations on number of packages, exceptions should be reported and swallowed.

**Comment by tkelman** [comment] 2015-10-16 00:22
That's a failure in dependency resolution, not something that can be continued from. Particularly while Pkg is in such an under construction state, we shouldn't be hiding any failure conditions at all. It's just too brittle, failures should make themselves known so they can be fixed. I like the idea of including additional information in the exception type, otherwise we'll never be able to reliably tell apart conditions that could be nonfatal (eventually, once things are working more robustly) from exceptions caused by implementation bugs in Pkg.

**Comment by tkelman** [comment] 2015-10-17 17:56
one case was fixed by https://github.com/JuliaLang/julia/commit/ad7a263440fbe27496183eb97bb8d0cfcdc62424, but there are likely others that still need fixing

**Comment by wildart** [comment] 2016-05-10 22:09
`Pkg.Read` functions pass all exceptions to the parent module.

**Closed by wildart** 2016-05-10 22:09 UTC
Labels: error handling, packages
