### ISSUE TITLE
.julia directory at $HOME

### ISSUE THREAD

**Issue by qlcom** [JuliaLang/julia#37503] opened 2020-09-10 06:34 UTC
julia should not create `.juila` directory at `$HOME`. 

It should follow xdg directory guidelines.

**Comment by DilumAluthge** [comment] 2020-09-10 06:40
Duplicate of https://github.com/JuliaLang/julia/issues/4630

**Comment by qlcom** [comment] 2020-09-10 07:04
like `go`, `julia` can have a `~/.config/julia/env` for storing environment variables. so we can choose which directory to use.

**Closed** 2020-09-10 07:03 UTC

**Comment by fredrikekre** [comment] 2020-09-10 07:07
You can just set `JULIA_DEPOT_PATH` of you are bot happy with `~/.julia`.

**Comment by qlcom** [comment] 2020-09-10 07:12
@fredrikekre thank you.

**Comment by KristofferC** [comment] 2020-09-10 07:27
Does everything respect that? I don't think the repl log file would.

**Comment by DilumAluthge** [comment] 2020-09-10 07:30
I believe that everything respects that environment variable.
```
$ ls ~/.julia
ls: /Users/dilum/.julia: No such file or directory
$ ls /Users/dilum/Downloads/foo/bar
ls: /Users/dilum/Downloads/foo/bar: No such file or directory
$ export JULIA_DEPOT_PATH="/Users/dilum/Downloads/foo/bar"
$ ls ~/.julia
ls: /Users/dilum/.julia: No such file or directory
$ ls /Users/dilum/Downloads/foo/bar
ls: /Users/dilum/Downloads/foo/bar: No such file or directory
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.878 (2020-09-09)
 _/ |\__'_|_|_|\__'_|  |  Commit 08486888ba (0 days old master)
|__/                   |

julia> 1 + 1
2

julia> exit()
$ ls ~/.julia
ls: /Users/dilum/.julia: No such file or directory
$ ls /Users/dilum/Downloads/foo/bar
logs
$ ls /Users/dilum/Downloads/foo/bar/logs
repl_history.jl
$ cat /Users/dilum/Downloads/foo/bar/logs/repl_history.jl
# time: 2020-09-10 03:29:28 EDT
# mode: julia
	1 + 1
# time: 2020-09-10 03:29:29 EDT
# mode: julia
	exit()
```

**Comment by KristofferC** [comment] 2020-09-10 09:44
Yep, seems so. That's good then.
