### ISSUE TITLE
julia --lisp doesn't work on Windows

### ISSUE THREAD

**Issue by nickleeh** [JuliaLang/julia#11481] opened 2015-05-29 07:37 UTC
I am running Julia v"0.3.8" on Windows 7. when I try to launch FemtoLisp by:

    julia --lisp

I got this display and quit:

    PS C:\Users\Nick> julia --lisp                                                  
    ;  _                                                                            
    ; |_ _ _ |_ _ |  . _ _                                                          
    ; | (-||||_(_)|__|_)|_)                                                         
    ;-------------------|---------------------------------------------------------- 
                                                                                
    >                                                                               
    PS C:\Users\Nick>                                                               

It quit immediately, any boby knows why?

**Comment by JeffBezanson** [comment] 2015-05-29 08:10
Looks same as #4564.

**Comment by tkelman** [comment] 2015-05-29 08:32
It works in mintty but immediately exits in cmd, so apparently femtolisp's tty detection isn't as portable as julia's.

**Comment by ScottPJones** [comment] 2015-05-29 08:55
OT: BTW: what is the "easter egg" to get to s-expr Julia? `--gerry`?

**Comment by JeffBezanson** [comment] 2015-05-29 16:11
Strange. I believe it just calls `ios_getc`, which just calls `read`. This runs before `julia_init` is called, so libuv setup stuff has not happened. I'd like to know what's going on.

**Comment by tkelman** [comment] 2015-05-29 16:29
Happy to test stuff out. What do you suggest I try?

**Comment by JeffBezanson** [comment] 2015-05-29 16:42
In #4564 several people reported it working, so the problem must be pretty subtle. I'd hate to spend time on this. Does a simple console program that just calls `read` on STDIN work?

**Comment by tkelman** [comment] 2015-05-29 17:51
in cmd:
```
(gdb) b _os_read
Breakpoint 1 at 0x4243f1: file ios.c, line 91.
(gdb) r
Starting program: /home/Tony/julia/src/flisp/flisp-debug
[New Thread 2544.0x1b24]

Breakpoint 1, _os_read (fd=3, buf=0x3271fb0, n=131072, nread=0x22f268)
    at ios.c:91
91      {
(gdb) c
Continuing.
;  _
; |_ _ _ |_ _ |  . _ _
; | (-||||_(_)|__|_)|_)
;-------------------|-------------------------------------------------------

>
Breakpoint 1, _os_read (fd=0, buf=0x30c0080, n=131072, nread=0x22eda8)
    at ios.c:91
91      {
(gdb) s
95              r = read((int)fd, buf, LIMIT_IO_SIZE(n));
(gdb)
96              if (r > -1) {
(gdb)
100             if (!_enonfatal(errno)) {
(gdb)
_enonfatal (err=12) at ios.c:72
```

in mintty:
```
Reading symbols from src/flisp/flisp-debug...done.
(gdb) b _os_read
Breakpoint 1 at 0x4243f1: file ios.c, line 91.
(gdb) r
Starting program: /home/Tony/julia/src/flisp/flisp-debug
[New Thread 3368.0x1054]

Breakpoint 1, _os_read (fd=3, buf=0x3521fa0, n=131072, nread=0x22f268) at ios.c:91
91      {
(gdb) c
Continuing.
;  _
; |_ _ _ |_ _ |  . _ _
; | (-||||_(_)|__|_)|_)
;-------------------|----------------------------------------------------------

>
Breakpoint 1, _os_read (fd=0, buf=0x32a0080, n=131072, nread=0x22eda8) at ios.c:91
91      {
(gdb) s
95              r = read((int)fd, buf, LIMIT_IO_SIZE(n));
(gdb)
```
(and waits for input as expected)

Something about fd 0 acting differently whether in cmd vs mintty, I suspect.

**Comment by JeffBezanson** [comment] 2015-05-29 17:57
What is `strerror(12)`?

**Comment by tkelman** [comment] 2015-05-29 18:02
```
(gdb) print strerror(12)
$4 = 51951888
(gdb) print (char*)strerror(12)
$5 = 0x318b910 "Not enough space"
```

So maybe the buffer is being allocated differently between the two? Having a hard time tracking down where that first gets allocated.

**Comment by ViralBShah** [comment] 2015-06-01 17:24
@ScottPJones I request you not bring up off topic discussions. Prefixing them OT does not make it ok to do so. It just increases the noise level for everyone.

**Comment by ScottPJones** [comment] 2015-06-01 18:13
@ViralBShah Sorry, that was actually meant as a serious question (although maybe should have been asked in Julia-dev instead), even if asked in a joking fashion... for my project with Julia, we'd like to be able to access the s-expr REPL that Gerry had apparently asked for...

**Comment by JeffBezanson** [comment] 2015-06-01 18:26
The s-expr REPL is not going to happen.

**Comment by ScottPJones** [comment] 2015-06-01 18:32
OK, thanks, we'll just roll our own simple parser... no problem!

**Comment by JeffBezanson** [comment] 2015-06-01 18:36
`Meta.show_sexpr` might help. Can be useful when metaprogramming. Other than that I'm not sure why you'd want this.

**Comment by ScottPJones** [comment] 2015-06-01 18:41
We just want to expose a very limited set of Julia functionality, just (function args), with a limited set of available functions... I just thought I might skip some work if there was already a s-expr mode parser...

**Comment by vtjnash** [comment] 2015-07-16 07:00
an alternate translation for error 12 is ENOMEM (https://msdn.microsoft.com/en-us/library/t3ayayh1.aspx)

(fwiw, i still can't reproduce in either cmd or powershell on my windows 10 machine)

**Comment by tkelman** [comment] 2015-07-16 07:07
might have been fixed by the windows 10 console rewrite, still happens for me on win 7 in cmd

**Comment by vtjnash** [comment] 2015-07-16 07:21
does it help if you reduce the max size in ios.c from `LIMIT_IO_SIZE` to something a lot smaller?

**Comment by tkelman** [comment] 2015-07-18 02:49
Yes - this patch fixes the issue but appears to cause a bootstrap segfault
```
diff --git a/src/support/ios.c b/src/support/ios.c
index 73ccc54..f54814e 100644
--- a/src/support/ios.c
+++ b/src/support/ios.c
@@ -92,7 +92,7 @@ static int _os_read(long fd, void *buf, size_t n, size_t *nread)
     ssize_t r;

     while (1) {
-        r = read((int)fd, buf, LIMIT_IO_SIZE(n));
+        r = read((int)fd, buf, LIMIT_IO_SIZE(n) >> 3);
         if (r > -1) {
             *nread = (size_t)r;
             return 0;
```

**Comment by vtjnash** [comment] 2015-07-18 03:47
you should edit the max directly in the LIMIT_IO_SIZE macro

**Comment by tkelman** [comment] 2015-07-18 07:17
Do you mean just decreasing the value of `MAXSIZE` ? I'm trying that but it doesn't seem to help so far.

**Comment by tkelman** [comment] 2016-07-10 23:14
This seems to work now on master. Not sure what fixed it.
```
Microsoft Windows [Version 10.0.14385]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Tony>C:\cygwin64\home\Tony\julia\usr\bin\julia --lisp
;  _
; |_ _ _ |_ _ |  . _ _
; | (-||||_(_)|__|_)|_)
;-------------------|----------------------------------------------------------

> (print "hello world")
"hello world"#t

> (exit)

C:\Users\Tony>
```

**Comment by twadleigh** [comment] 2016-08-25 17:12
I'm still having this issue with 0.5-rc3. I'm on Windows 7.

**Comment by twadleigh** [comment] 2016-08-27 23:21
@vtjnash I've tried decreasing `MAXSIZE` to `0x000fffff` with no change (like @tkelman was seeing). Any other ideas?

**Comment by musm** [comment] 2016-08-28 01:59
as with tkelman I can confirm on windows 10 this is not a problem

**Comment by vtjnash** [comment] 2016-09-01 04:01
A few observations:
1. libuv handles this by fetching at most 8192 bytes at a time when dealing with the Windows Console API (https://github.com/libuv/libuv/blob/v1.x/src/win/tty.c#L445)
2. the limitation is documented, but makes absolutely no sense as written: (https://msdn.microsoft.com/en-us/library/windows/desktop/ms684958(v=vs.85).aspx). translation: "an unnecessary copy of the output buffer will be made from a shared heap which has a max size of 64 KB"
3. access to the source code (or a fair facsimile) makes it instantly clear what is going wrong: https://doxygen.reactos.org/dd/dfb/dll_2win32_2kernel32_2client_2console_2readwrite_8c_source.html#l00098. I'm still clueless as to why it's implemented this way.
4. we could handle a return of ENOMEM by repeatedly cutting the requested buffer size in half in ios.c (down to some minimum such as 80)

**Comment by twadleigh** [comment] 2016-09-01 21:10
@vtjnash I'll experiment with a fix like you propose.

**Closed** 2016-09-05 06:24 UTC
Labels: windows
