### ISSUE TITLE
Dict(kw...)

### ISSUE THREAD

**Issue by jw3126** [JuliaLang/julia#25206] opened 2017-12-20 07:27 UTC
A common pattern is converting keyword arguments into a `Dict` for easier manipulation. On master this currently throws an error:
```julia
julia> f(;kw...) = Dict(kw...)
f (generic function with 1 method)

julia> f(a=1)
ERROR: ArgumentError: Dict(kv): kv needs to be an iterator of tuples or pairs
Stacktrace:
 [1] Dict(::Int64) at ./dict.jl:147
 [2] #f#1 at ./REPL[1]:1 [inlined]
 [3] (::getfield(, Symbol("#kw##f")))(::NamedTuple{(:a,),Tuple{Int64}}, ::typeof(f)) at ./<missing>:0
 [4] top-level scope
```
I think a `depwarn` would be better. Especially for code that needs to work on `v0.6` and master.

**Comment by fredrikekre** [comment] 2017-12-20 07:44
See #25179, you can use `f(;kw...) = Dict(pairs(kw))` and `f(;kw...) = Dict(Compat.pairs(kw))` on 0.6

**Comment by jw3126** [comment] 2017-12-20 07:47
Thanks! Is there a reason other then lack of time for this having no depwarn?

**Comment by jw3126** [comment] 2017-12-20 07:50
I am often in the situation that I have a package want to quickly try a feature on master. In this case I don't care if my package (or dependencies!) throw tons of depwarns, but an error is a problem. Thats why I would prefer a depwarn.

**Comment by JeffBezanson** [comment] 2017-12-20 13:37
`kw` will now support many dict operations, so it's possible a `Dict` is not needed anymore. Out of curiosity, what do you need the `Dict` for? (It doesn't negate the issue of course, just wondering about use cases.)

**Comment by JeffBezanson** [comment] 2017-12-20 13:50
Also duplicate of #25177

**Closed by JeffBezanson** 2017-12-20 13:50 UTC

**Comment by jw3126** [comment] 2017-12-20 17:57
I don't specifically need a `Dict`, just things like `kw[:some_option]`. And in `v0.6` doing `Dict(kw...)` is a common trick to achieve this.

**Comment by JeffBezanson** [comment] 2017-12-20 18:05
`kw[:some_option]` should work now, as well as `kw.some_option`.
