### ISSUE TITLE
Can't do type creation inside macro when templating is used

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaLang/julia#9312] opened 2014-12-11 12:26 UTC
The following throws the error "ERROR: error compiling anonymous: type definition not allowed inside a local scope":

```julia
module FooModule
     macro foo(Typ,Abs)
     return esc(quote
           abstract $Abs{T}
           immutable $Typ{T} <: $Abs{T} end
           end
           )
       end
    @foo(FooTyp,FooAbs)
end
```

The following without the templated abstract type doesn't throw an error:

```julia
module FooModule2
     macro foo(Typ,Abs)
     return esc(quote
           abstract $Abs
           immutable $Typ{T} <: $Abs end
           end
           )
       end
    @foo(FooTyp,FooAbs)
end
```
[@ivarne- edited to add quoting]

**Comment by ihnorton** [comment] 2015-01-02 05:30
Not yet sure why this changed. See also #2586.

**Comment by ihnorton** [comment] 2015-01-02 17:06
@dlfivefifty here is a (possible) work-around:
```
macro foo(Typ,Abs)
            return esc(quote
                  abstract $Abs{T}
                  immutable $Typ{S} <: $Abs{S} end
                  end
                  )
              end
```

Since @JeffBezanson seems to be on right now -- if you see this, can you comment on whether this is more than a dupe of #2586 (and #4893)? I looked at the lowering for Sheehan's examples as well as the code below:

```julia
macro foo()
           esc(:(abstract Sup{T}))
       end
@foo
julia> macro bar(AbsSub)
           esc(quote immutable $AbsSub{T} end end)
       end

julia> @bar(Sub)
```

From what I can tell the difference is that there is a lambda capture in Sheehan's example, and I believe what is happening is that `T` is being incorrectly (?) classified as a local variable when it should only be a `TypeVar` for both declarations. (therefore the code goes through the compiler and hits this error message).

**Comment by dlfivefifty** [comment] 2015-01-02 22:34
That seems to fix the toy example, thanks!    I can't test the real example in 0.4 because the code is also hit by https://github.com/JuliaLang/julia/issues/9378

**Comment by yuyichao** [comment] 2015-05-05 23:22
Probably related (the "local T declare twice" error)

```julia
try
    @eval begin
        abstract A1{T}
        abstract B1{T} <: A1{T}
    end
catch e
    println(e)
end

abstract A2{T}
abstract B2{T} <: A2{T}

try
    @eval begin
        abstract A3{T}
        type B3{T} <: A3{T}
        end
    end
catch e
    println(e)
end

abstract A4{T}
type B4{T} <: A4{T}
end
```

Output
```julia
ErrorException("syntax: local \"T\" declared twice")
ErrorException("error compiling anonymous: type definition not allowed inside a local scope")
```

**Comment by JeffBezanson** [comment] 2015-07-20 16:54
Just tried this and it seems to be fixed.

**Closed by JeffBezanson** 2015-07-20 16:54 UTC
Labels: bug, regression
