### ISSUE TITLE
bitarray test failure on arm

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#12342] opened 2015-07-28 09:50 UTC
````
     * bitarray             LLVM ERROR: Cannot select: 0x5c645c0: v2i64 = ctpop 0x5c65190 [ORD=14] [ID=48] dbg:linalg/bitarray.jl:10:1
  0x5c65190: v2i64 = bitcast 0x5c65100 [ORD=12] [ID=46] dbg:linalg/bitarray.jl:10:1
    0x5c65100: v4i32 = and 0x5df9480, 0x5c64f50 [ORD=12] [ID=44] dbg:linalg/bitarray.jl:10:1
      0x5df9480: v4i32 = bitcast 0x5d7f3a0 [ORD=12] [ID=40] dbg:linalg/bitarray.jl:10:1
        0x5d7f3a0: v2f64,ch = load 0x5d81b10, 0x5d7f790, 0x5c64770<LD16[%scevgep31](align=8)(tbaa=!"jtbaa_user")> [ORD=10] [ID=34] dbg:linalg/bitarray.jl:10:1
          0x5d7f790: i32 = add 0x5d7f9d0, 0x5c644a0 [ORD=9] [ID=27]
            0x5d7f9d0: i32,ch = CopyFromReg 0x5d81b10, 0x5c64260 [ORD=2] [ID=20]
              0x5c64260: i32 = Register %vreg10 [ID=1]
            0x5c644a0: i32 = Constant<16> [ID=5]
          0x5c64770: i32 = undef [ID=3]
      0x5c64f50: v4i32 = bitcast 0x5c64a40 [ORD=12] [ID=42] dbg:linalg/bitarray.jl:10:1
        0x5c64a40: v2f64,ch = load 0x5d81b10, 0x5d7f5e0, 0x5c64770<LD16[%scevgep35](align=8)(tbaa=!"jtbaa_user")> [ORD=7] [ID=37] dbg:linalg/bitarray.jl:10:1
          0x5d7f5e0: i32 = add 0x5d7faf0, 0x5c644a0 [ORD=6] [ID=30]
            0x5d7faf0: i32,ch = CopyFromReg 0x5d81b10, 0x5c64650 [ORD=3] [ID=21]
              0x5c64650: i32 = Register %vreg9 [ID=2]
            0x5c644a0: i32 = Constant<16> [ID=5]
          0x5c64770: i32 = undef [ID=3]
In function: julia_dot_23929
````

````
(precise)viral@localhost:~/julia/test$ ../julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6253 (2015-07-26 15:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit a97b24b* (1 day old master)
|__/                   |  arm-linux-gnueabihf
````

**Comment by ViralBShah** [comment] 2015-09-22 12:05
Not crashing when I use master and LLVM 3.7.0.

**Comment by yuyichao** [comment] 2016-01-03 22:32
Apparently I was really bad at searching for issues this morning....

This is happening on master+LLVM37 now. Given Keno has pointed out the cause in https://github.com/JuliaLang/julia/issues/14553 I'll close this one and track this issue in https://github.com/JuliaLang/julia/issues/14553 instead....

**Closed by yuyichao** 2016-01-03 22:32 UTC
Labels: arm
