### ISSUE TITLE
Reconsider String constructor emptying its argument

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#49711] opened 2023-05-10 07:26 UTC
`String(::Vector{UInt8})` empties its argument, which is documented behavior but still very surprising. 

I'm not sure if there is a possible path to changing APIs like this in 1.x, but it could help users avoid surprises.

Discussion at https://discourse.julialang.org/t/constructing-string-x-vector-uint8-empties-the-vector/58816

**Comment by KristofferC** [comment] 2023-05-10 07:53
Why do you think the current situation is the way it is?

**Comment by jakobnissen** [comment] 2023-05-10 11:04
Duplicate of https://github.com/JuliaLang/julia/issues/32528, in which you can find more discussion, and in which is already on the Julia 2.0 milestone.

**Closed by jakobnissen** 2023-05-10 11:04 UTC
