### ISSUE TITLE
Python-like else clause on for loops in Julia?

### ISSUE THREAD

**Issue by kilminster** [JuliaLang/julia#13026] opened 2015-09-09 05:34 UTC
Python's for-else construct as described for example in section 4.4, [here](https://docs.python.org/2/tutorial/controlflow.html), is sometimes very useful.  (The idea is that the else clause will be executed after the loop completes normally, but not if we break out of the loop.)  Could something similar be added to Julia?

As an example, code like:
```julia
converged=true
for i=1:n
    if !isapprox(y[i],ynew[i])
        converged=false
        break
    end
end
if converged
    return y
end
```
could become:
```julia
for i=1:n
    if !isapprox(y[i],ynew[i])
        break
    end
else
    return y
end
```

**Comment by jiahao** [comment] 2015-09-09 05:38
Please try searching the existing issues before you open a new one.

Duplicate of #1289

**Closed by jiahao** 2015-09-09 05:38 UTC

**Comment by kilminster** [comment] 2015-09-09 05:39
I'm sorry, I did try searching, obviously not well enough.

**Comment by jiahao** [comment] 2015-09-09 05:43
For your use case, you can write

```jl
for i=1:n
    if !(y[i] ≈ ynew[i])
        @goto converged
    end
end
error("Not converged")
@label converged
return y
```

which was what emerged from the discussion in that referenced issue.
