### ISSUE TITLE
tmpname(parent) does not respect parent

### ISSUE THREAD

**Issue by nico202** [JuliaLang/julia#35785] opened 2020-05-07 09:23 UTC
Hello! I'm packaging julia 1.4.1 for guix, and this test is failing

https://github.com/JuliaLang/julia/blob/381693d3dfc9b7072707f6d544f82f6637fc5e7c/test/file.jl#L70

I can reproduce it with:

```jl
using Test
using Random

function run()
    @testset "tempname with parent" begin
        t = tempname()
        @test dirname(t) == tempdir()
        mktempdir() do d
            t = tempname(d)
            @test dirname(t) == d
        end
        @test_throws ArgumentError tempname(randstring())
    end
end
# tempdir() uses the first environment variable found in the ordered list TMPDIR, TMP, TEMP, and TEMPDIR. If none of these are found, the path "/tmp" is used.
# Let's check all those variables are currently empty
all_empty() = @test all(isnothing.(get.(Ref(ENV), ["TMPDIR", "TMP", "TEMP", "TEMPDIR"], nothing)))
all_empty()

# Check the test passes when no "TEMP" variable is set
@info "No env var"
run()

@info "TMPDIR var"
withenv("TMPDIR" => mktempdir()) do
    run()
end
all_empty()
```

Can anybody confirm the same happens with the official build?

Thanks, Nicolò

**Comment by nico202** [comment] 2020-05-07 10:07
Actually I found this:
https://github.com/JuliaLang/julia/blob/178ac974b5e9f649c0ffb3ed78752dc9241b7a5a/base/file.jl#L548
```jl
parent = "/tmp"
temp_prefix = "jl_debug_"

p = ccall(:tempnam, Cstring, (Cstring, Cstring), parent, temp_prefix)
systemerror(:tempnam, p == C_NULL)
@show unsafe_string(p)
Libc.free(p)

withenv("TMPDIR" => mktempdir()) do
    p = ccall(:tempnam, Cstring, (Cstring, Cstring), parent, temp_prefix)
    systemerror(:tempnam, p == C_NULL)
    @show unsafe_string(p)
    Libc.free(p)
end
```

tempnam is ignoring `parent` and following TMPDIR only

**Comment by nico202** [comment] 2020-05-07 10:09
According to https://linux.die.net/man/3/tempnam:

1. In case the environment variable TMPDIR exists and contains the name of an appropriate directory, that is used.
2. Otherwise, if the dir argument is non-NULL and appropriate, it is used.

So the current use is wrong

**Comment by nico202** [comment] 2020-05-07 10:10
http://man7.org/linux/man-pages/man3/tempnam.3.html

>       Never use this function.  Use mkstemp(3) or tmpfile(3) instead.

cool

**Comment by nico202** [comment] 2021-03-26 21:27
This still happens on v1.6.0

**Comment by vchuravy** [comment] 2021-04-05 22:23
maybe duplicate of #38873?

x-ref: #38879

**Closed** 2021-12-28 10:36 UTC
Labels: bug
