### ISSUE TITLE
Crash when running "success(`X`)" where X is anything which should cause the function to return false

### ISSUE THREAD

**Issue by MoonCoral** [JuliaLang/julia#23266] opened 2017-08-15 13:03 UTC
I first raised this issue in JuliaLang/BinDeps.jl#240 as it causes a failure in that Package similar to past issues. But after narrowing down the cause, it seems that the problem is within julia itself.

The issue is that statements such as
```julia
success(`apt-get -v`)
success(`sudo -v`)
success(`sudo`)
success(`IDoNotExist`)
...
```
cause julia to crash. This happens both with 0.6 and a recent nightly.

I'm on windows 10, so these should return false as they don't exist.

Pruning "C:\WINDOWS\SYSTEM32" from the path fixes the issue.
I have a bash.exe in that folder as I have [WSL](https://blogs.msdn.microsoft.com/wsl/) enabled. However copying that file to another folder on the path restores the full capability of WSL without reintroducing the issue.

Some error messages:
[gist (including contents of system32)](https://gist.github.com/MoonCoral/678f6ffd9676133f58f11cbd1a3b288b)
[salient comment in the original issue](https://github.com/JuliaLang/BinDeps.jl/issues/240#issuecomment-322241709)

**Comment by vtjnash** [comment] 2017-08-15 14:06
Can you compare the `Libdl.dllist()` results from the two cases (wrt %PATH%)? Possibly also download depends22.exe from http://www.dependencywalker.com and see if the path variable is affecting anything.

**Comment by StefanKarpinski** [comment] 2017-08-15 15:13
> I'm on windows 10, so these should return false as they don't exist.

This seems to be your problem – calling a non-existent command does not return false, it's an error. This is documented in the help message for `success` as well as the section on running external processes:

> `success(command)`
> 
> Run a command object, constructed with backticks, and tell whether it was successful (exited with a code of 0). An exception is raised if the process cannot be started.

**Comment by tkelman** [comment] 2017-08-15 15:43
It should error, but not segfault

**Comment by MoonCoral** [comment] 2017-08-15 15:45
```julia
try success(`sudo -V`) catch e false end
```
Crashes julia.exe too. The problem is not that an exception is raised but that julia crashes even when the exception is handled.

**Comment by MoonCoral** [comment] 2017-08-15 16:46
Libdl.dllist() returns the same in each case albeit ordered differently.

"depends" lists some errors, but I'm pretty lost in puzzling out it's output I'm afraid.

**Comment by musm** [comment] 2017-08-15 18:33
where have you installed julia? Is it in a WSL directory or a windows path?

**Comment by MoonCoral** [comment] 2017-08-15 18:47
Default location when installing with the installer provided in [https://julialang.org/downloads/](https://julialang.org/downloads/)

**Comment by RainerHeintzmann** [comment] 2018-04-02 17:52
I just freshly installed the free JuliaPro:

Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

and it the REPL did not run out of the box, which could be traced to a failure to compile BinDeps.jl
INFO: Precompiling module BinDeps.
ERROR: Failed to precompile BinDeps to C:\Users\pi96doc\.julia\lib\v0.6\BinDeps.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405

which in turn seems to be related to this issue here.
success(`bash`)
crashes julia, closing the window (as does success(`xyz`)). However, if Julia is started from the cmd command in Windows 10, one can sometimes see an error message. This seems to randomly vary from case to case, but here is a particularly long example case:

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7fff22d196aa --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7fff22d196aa --
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7fff22d196aa -- SYSTEM ERROR: Failed to report error to REPL frontend

Hope this helps to solve the issue and make JuliaPro work with my Windows 10 system.

**Closed** 2022-03-18 00:11 UTC
Labels: windows
