### ISSUE TITLE
Odd behavior with native FMA instructions when first launching Julia

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#35055] opened 2020-03-09 20:34 UTC
I experienced  weird response when it comes to FMA on Julia 1.4 . 

First started Julia from the command line, without any flags (downloaded from julialang.org). Then I checked `mulladd` with code_native and find it's not using FMA CPU instructions and  `Base.Math.FMA_NATIVE` also showed false... that was strange since as long as I've used julia this was always true and FMA always used native instruction.

Then I started Julia with `-O3`. Check thing again... `muladd` is correctly using native FMA, but `Base.Math.FMA_NATIVE` is false (makes sense since it's a precompile constant, but should  be fixed regardless). 

Then the strange behavior shows up. I then check julia again (without `-O3` flag) and native FMA is working correctly in `muladd`   (Base.Math.FMA_NATIVE still false).

**Comment by KristofferC** [comment] 2020-03-09 20:37
`FMA_NATIVE` is broken: https://github.com/JuliaLang/julia/issues/33011.

**Comment by musm** [comment] 2020-03-09 20:38
Thanks, updated issue to reflect the fact that when I first launched julia it was not using native FMA, but then ended up correctly using FMA after launching with `-03`.

**Comment by simonbyrne** [comment] 2021-11-18 05:23
Closing as duplicate of #33011.

**Closed by simonbyrne** 2021-11-18 05:23 UTC
