### ISSUE TITLE
Source link 404

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#53830] opened 2024-03-23 19:33 UTC
The source link from https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.adjoint! is https://github.com/JuliaLang/julia/blob/bd47eca2c8aacd145b6c5c02e47e2b9ec27ab456/usr/share/julia/stdlib/v1.10/SparseArrays/src/sparsematrix.jl#L1427-L1435 which doesn't exist.

**Comment by giordano** [comment] 2024-03-24 02:44
Duplicate of #53594, #50035 and I don't know how many other tickets

**Closed by giordano** 2024-03-24 02:44 UTC
