### ISSUE TITLE
minor issue with dsymutil

### ISSUE THREAD

**Issue by Fedster** [JuliaLang/julia#15655] opened 2016-03-28 17:21 UTC
I all, very latest git pull on OS X 10.11.4, latest everything I get make clean; make:

```
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
rm -f *# *~
rm -f pcre_h.jl
rm -f errno_h.jl
rm -f build_h.jl
rm -f build_h.jl.phony
rm -f fenv_constants.jl
rm -f uv_constants.jl
rm -f file_constants.jl
rm -f version_git.jl
rm -f version_git.jl.phony
rm -rf _build/*
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
rm -fr /usr/local/julia/usr/lib/libjulia* /usr/local/julia/usr/lib/libccalltest*
rm -f ./julia_flisp.boot ./julia_flisp.boot.inc
rm -f ./*.dbg.obj ./*.o *~ ./*.dylib ./*.a *#
rm -f ./julia_version.h
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
rm -f *.o *.dbg.obj
rm -f /usr/local/julia/usr/bin/julia*
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
rm -f *~
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C micro clean
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C shootout clean
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
rm -f *.txt *~
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
    CC src/jltypes.o
    CC src/gf.o
    FLISP src/julia_flisp.boot
    FLISP src/julia_flisp.boot.inc
    CC src/ast.o
    CC src/builtins.o
    CC src/module.o
    CC src/codegen.o
    CC src/disasm.o
    CC src/debuginfo.o
    CC src/interpreter.o
    CC src/alloc.o
    CC src/dlload.o
    CC src/sys.o
    CC src/init.o
    CC src/task.o
    CC src/array.o
    CC src/dump.o
    CC src/toplevel.o
    CC src/jl_uv.o
    CC src/jlapi.o
    CC src/signal-handling.o
    CC src/llvm-simdloop.o
    CC src/simplevector.o
    CC src/gc.o
    LINK usr/lib/libjulia.dylib
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
    CC ui/repl.o
    LINK usr/bin/julia
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
    PERL base/pcre_h.jl
    PERL base/errno_h.jl
    PERL base/build_h.jl.phony
    PERL base/fenv_constants.jl
    PERL base/file_constants.jl
    PERL base/uv_constants.jl
    PERL base/version_git.jl.phony
Copying in usr/share/doc/julia/examples
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
    JULIA usr/lib/julia/inference0.ji
essentials.jl
reflection.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
abstractarray.jl
array.jl
hashing.jl
nofloat_hashing.jl
functors.jl
reduce.jl
intset.jl
dict.jl
iterator.jl
inference.jl
    JULIA usr/lib/julia/inference.ji
essentials.jl
reflection.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
abstractarray.jl
array.jl
hashing.jl
nofloat_hashing.jl
functors.jl
reduce.jl
intset.jl
dict.jl
iterator.jl
inference.jl
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
    JULIA usr/lib/julia/sys.o
exports.jl
essentials.jl
docs/bootstrap.jl
base.jl
reflection.jl
build_h.jl
version_git.jl
c.jl
options.jl
promotion.jl
tuple.jl
range.jl
expr.jl
error.jl
bool.jl
number.jl
int.jl
operators.jl
pointer.jl
refpointer.jl
functors.jl
abstractarray.jl
subarray.jl
array.jl
hashing.jl
rounding.jl
float.jl
complex.jl
rational.jl
abstractarraymath.jl
arraymath.jl
simdloop.jl
reduce.jl
bitarray.jl
intset.jl
dict.jl
set.jl
iterator.jl
osutils.jl
char.jl
ascii.jl
iobuffer.jl
string.jl
strings/types.jl
strings/basic.jl
strings/search.jl
strings/util.jl
strings/io.jl
unicode.jl
unicode/UnicodeError.jl
unicode/types.jl
unicode/checkstring.jl
unicode/utf8.jl
unicode/utf16.jl
unicode/utf32.jl
unicode/utf8proc.jl
parse.jl
shell.jl
regex.jl
pcre.jl
base64.jl
io.jl
iostream.jl
libc.jl
libdl.jl
env.jl
path.jl
intfuncs.jl
nullable.jl
task.jl
lock.jl
show.jl
stream.jl
uv_constants.jl
socket.jl
stat.jl
fs.jl
process.jl
multimedia.jl
grisu.jl
file.jl
methodshow.jl
floatfuncs.jl
math.jl
float16.jl
cartesian.jl
multidimensional.jl
primes.jl
reducedim.jl
ordering.jl
collections.jl
sort.jl
version.jl
gmp.jl
mpfr.jl
combinatorics.jl
hashing2.jl
dSFMT.jl
random.jl
printf.jl
meta.jl
Enums.jl
serialize.jl
channels.jl
multi.jl
managers.jl
loading.jl
poll.jl
mmap.jl
sharedarray.jl
datafmt.jl
deepcopy.jl
interactiveutil.jl
replutil.jl
test.jl
i18n.jl
Terminals.jl
LineEdit.jl
REPLCompletions.jl
REPL.jl
client.jl
util.jl
linalg.jl
broadcast.jl
statistics.jl
sparse.jl
irrationals.jl
dft.jl
dsp.jl
sysinfo.jl
quadgk.jl
fastmath.jl
pkg.jl
profile.jl
Dates.jl
markdown/Markdown.jl
docs/Docs.jl
deprecated.jl
require.jl
docs/helpdb.jl
docs/basedocs.jl
/usr/local/julia/base/precompile.jl
    LINK usr/lib/julia/sys.dylib
dsymutil: Not enough positional command line arguments specified!
Must specify at least 1 positional arguments: See: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -help
/bin/sh: line 0: test: -gt: unary operator expected
    CC usr/lib/libccalltest.dylib
```

**Comment by tkelman** [comment] 2016-03-28 17:38
Duplicate of #15594. For output that long, better to post to gist.github.com and just leave a link.

**Closed by tkelman** 2016-03-28 17:38 UTC
