### ISSUE TITLE
Segfault in cmdline tests

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#47016] opened 2022-10-03 02:53 UTC
I found this segfault in a failed CI run:
```
filesystem                                       (4) \|        started at 2022-10-02T07:29:59.753
filesystem                                       (4) \|     0.31 \|   0.00 \|  0.0 \|      17.47 \|  1935.83
download                                         (4) \|        started at 2022-10-02T07:30:00.065
cmdlineargs                                      (2) \|         failed at 2022-10-02T07:30:07.798
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-aarch64-3.0/build/default-macmini-aarch64-3-0/julialang/julia-master/julia-54a6410fd3/share/julia/test/cmdlineargs.jl:258
Expression: read(`$exename -p2 -t2 -e $code`, String) == "6"
Evaluated: "6      From worker 3:\t\n      From worker 3:\t[42540] signal (11): Segmentation fault: 11\n      From worker 3:\tin expression starting at none:0\n" == "6"

SparseArrays/allowscalar                         (5) \|        started at 2022-10-02T07:30:10.676
SparseArrays/allowscalar                         (5) \|     0.30 \|   0.00 \|  1.4 \|      29.02 \|   272.42
```
https://buildkite.com/julialang/julia-master/builds/16424#0183984f-99a3-4b19-8f82-a213bfd51983

**Comment by vtjnash** [comment] 2022-10-03 14:44
Duplicate of https://github.com/JuliaLang/julia/issues/46537

**Closed by vtjnash** 2022-10-03 14:44 UTC
Labels: bug, heisenbug, ci
