### ISSUE TITLE
Cannot sum ComplexF64 ranges

### ISSUE THREAD

**Issue by nick-cao** [JuliaLang/julia#49992] opened 2023-05-30 04:23 UTC
Running the code:
```
(0.0:5.0)*im + (0.0:5.0)*im
```
produces the following error
```
ERROR: MethodError: no method matching nbitslen(::Type{ComplexF64}, ::Int64, ::Int64)

Closest candidates are:
  nbitslen(::Type{T}, ::Any, ::Any) where T<:Union{Float16, Float32, Float64}
   @ Base twiceprecision.jl:253
  nbitslen(::Any, ::Any)
   @ Base twiceprecision.jl:257
```
The problem is unique to complex floats: there is no problem with `(0:5)*im + (0:5)*im`.

```
versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 6 on 6 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 6
```

**Comment by Seelengrab** [comment] 2023-05-30 05:03
I'm a bit confused - I wouldn't expect ranges to be usable like that at all, as julia (generally) doesn't have such vectorized summation and using explicit broadcasting instead.

**Comment by nick-cao** [comment] 2023-05-30 05:34
The documentation for [Base.range](https://docs.julialang.org/en/v1/base/math/#Base.range) states that ranges are a "specialized array with evenly spaced elements and optimized storage". Therefore, one would expect it to behave like adding together two vectors, under the usual rules of vector addition. Hence, I would expect it to return `0.0 + 0.0im:0.0 + 2.0im:0.0 + 10.0im`. This would be consistent with how `(0.0:5.0) + (0.0:5.0)` and `(0:5)*im + (0:5)*im` work.

**Comment by oscardssmith** [comment] 2023-05-30 12:24
specifically this works because vector addition is a well defined operation (unlike vector+scalar)

**Comment by nsajko** [comment] 2023-06-04 15:55
This should also get a `ranges` label.

**Comment by LilithHafner** [comment] 2023-06-04 16:45
`Base.TwicePrecision{T}` is only fully defined for concrete `T <: Base.IEEEFloat`. Consequently, I am unsurprised that  `Base.TwicePrecision{ComplexF64}` has problems. I think a better type for the internals of complex floating point ranges this might be `Complex{Base.TwicePrecision{Float64}}` (which would require `Base.TwicePrecision <: Real`).

**Comment by nsajko** [comment] 2023-06-04 17:39
@LilithHafner I thought so too before, but it seems like a no-go, at least not without major rework, see #49589 (and #49569).

**Comment by nsajko** [comment] 2023-06-04 17:41
But,

> which would require `Base.TwicePrecision <: Real`

This is not necessarily a good idea.

**Comment by LilithHafner** [comment] 2023-06-04 18:28
Can you provide an example of where `Complex{Base.TwicePrecision{Float64}}` would not "just work" (provided `Base.TwicePrecision <: Real`).

What problems would `Base.TwicePrecision <: Real` cause, keeping in mind that `TwicePrecision` is an internal type, so direct usage of it is not supported?

**Comment by nsajko** [comment] 2023-06-04 20:55
See https://github.com/JuliaLang/julia/pull/49616#discussion_r1183830879, it seems difficult to support unitlike types (which are not `<:Number`) when `TwicePrecision` is restricted to `TwicePrecision{<:Number}`.

Furthermore, having the type parameter be `Complex` (as is currently possible) enables easy code reuse for multi-word addition. This makes sense for an orthogonal representation of complex number, such as `Complex`. I mentioned this in #49589.

**Comment by LilithHafner** [comment] 2023-06-04 22:59
I see... TwicePrecision does not implement enough methods to support `Complex{TwicePrecision{Float64}}` (e.g. `isfinite(::TwicePrecision)`) and its methods are not generic enough to support `TwicePrecision{Complex{Float64}}` (e.g. `TwicePrecision{T}` uses `precision(::T)`. This is tricky.

**Comment by jishnub** [comment] 2023-09-11 15:49
Duplicate of https://github.com/JuliaLang/julia/issues/32792

**Closed by jishnub** 2023-09-11 15:49 UTC
Labels: bug, complex, ranges
