### ISSUE TITLE
Crash with illegal instruction after entering 'x' return in REPL

### ISSUE THREAD

**Issue by ccube** [JuliaLang/julia#37968] opened 2020-10-09 22:50 UTC
julia repl v 1.5.2 crashes when you enter a char ('x')
[crash.log](https://github.com/JuliaLang/julia/files/5357941/crash.log)

**Comment by vtjnash** [comment] 2020-10-09 22:57
```
julia> 'x'
Invalid instruction at 0x7f2b03552c07: 0x66, 0x0f, 0x3a, 0x0f, 0xc0, 0x08, 0x0f, 0x29, 0x84, 0x24, 0xb0, 0x03, 0x00, 0x00, 0xe8

signal (4): Illegal instruction
in expression starting at none:0
```

I suspect your processor family is unsupported (too old AMD)

Duplicate of https://github.com/JuliaLang/julia/issues/35215

**Closed by vtjnash** 2020-10-09 22:57 UTC
