### ISSUE TITLE
Base.runtests() failed with julia 0.6.2 binaries

### ISSUE THREAD

**Issue by ajgiuliani** [JuliaLang/julia#25761] opened 2018-01-26 13:25 UTC
Julia 0.6.2 has been downloaded and run on Ubuntu 16.04.
Base.runtests() gave the following output:

```
    cmdlineargs         |      137                      137
    distributed         |                          No tests
    compile             |       88                       88
    FAILURE
Error in testset file:
Test Failed
  Expression: download("ba\0d", "good")
    Expected: ArgumentError
      Thrown: Base.UVError
ERROR: LoadError: Test run finished with errors
while loading /home/station/Programs/julia-d386e40c17_old/julia-d386e40c17/share/julia/test/runtests.jl, in expression starting on line 29
ERROR: A test has failed. Please submit a bug report (https://github.com/JuliaLang/julia/issues)
including error messages above and the output of versioninfo():
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

Stacktrace:
 [1] runtests(::Array{String,1}, ::Int64) at ./interactiveutil.jl:691
 [2] runtests() at ./interactiveutil.jl:680
```
Regards,
Alex

**Comment by ararslan** [comment] 2018-01-26 20:15
I'm unable to reproduce this; I just tried on Elementary OS (based on Ubuntu 16.04), and all tests pass.
```
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by ajgiuliani** [comment] 2018-01-27 08:32
I must admit that I am surprised, as it's a fresh Ubuntu installation.
versioninfo gives back the following:
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)

Any idea of the origin of the error ? What should I do ?

**Comment by ararslan** [comment] 2018-01-27 21:48
I'm not sure. If you run `Base.runtests()` again, does it fail in the same way?

**Comment by tkelman** [comment] 2018-01-28 01:37
This happens when you have wget installed but not curl. The error type is inconsistent between the two for this case.

**Comment by ajgiuliani** [comment] 2018-01-29 10:41
Thank you, remplacing wget by curl solved the problem.
Nevertheless, wget is mentioned in the required tools for compiling Julia.  Should't the incompatibility between wget and the tests be mentioned somewhere (like on the plateform specific instructions) ?

**Comment by tkelman** [comment] 2018-01-29 12:29
The inconsistency in exception type should be fixed, it's not an intentional failure

**Comment by ajgiuliani** [comment] 2018-01-29 12:36
OK. Thank's for your help.

**Comment by martinholters** [comment] 2018-01-29 12:40
Do we have a dedicated issue for the wrong exception type? Otherwise, we should reopen this.

**Comment by ajgiuliani** [comment] 2018-01-29 12:43
No, there's nothing dedicated.

**Comment by fredrikekre** [comment] 2018-01-29 13:28
#22783

**Closed by fredrikekre** 2018-01-29 13:28 UTC
