### ISSUE TITLE
Feature request: better error message for @which a .+ b

### ISSUE THREAD

**Issue by yuxiliu1995** [JuliaLang/julia#34192] opened 2019-12-25 00:58 UTC
```julia
julia> @which [2 3] .+ [1 2]
ERROR: UndefVarError: .+ not defined
```

My intuition is something like `a .+ b` gets changed to `broadcasted_+(a, b)`, and was hoping it would return something like
`broadcasted_+(a::Array{Int64}...)`
but now I see it wouldn’t make sense.

The error message could be made to say something like
`Did you mean '@which broadcast(+, a, b)'?`

**Comment by mbauman** [comment] 2019-12-31 19:09
Duplicate of #28615

**Closed by mbauman** 2019-12-31 19:09 UTC
