### ISSUE TITLE
Running success(`powershell -h`) shows help text

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#14314] opened 2015-12-07 23:12 UTC
On a x64 Windows 10 system, calling ``success`` to run Powershell shows the output of PowerShell:

````
julia> success(`powershell -h`)

PowerShell[.exe] [-PSConsoleFile <file> | -Version <version>]
    [-NoLogo] [-NoExit] [-Sta] [-Mta] [-NoProfile] [-NonInteractive]
    [-InputFormat {Text | XML}] [-OutputFormat {Text | XML}]
    [-WindowStyle <style>] [-EncodedCommand <Base64EncodedCommand>]
    [-File <filePath> <args>] [-ExecutionPolicy <ExecutionPolicy>]
    [-Command { - | <script-block> [-args <arg-array>]
                  | <string> [<CommandParameters>] } ]

PowerShell[.exe] -Help | -? | /?

-PSConsoleFile
    Loads the specified Windows PowerShell console file. To create a console
    file, use Export-Console in Windows PowerShell.

-Version
    Starts the specified version of Windows PowerShell.
    Enter a version number with the parameter, such as "-version 2.0".

-NoLogo
    Hides the copyright banner at startup.

-NoExit
    Does not exit after running startup commands.

-Sta
    Starts the shell using a single-threaded apartment.
    Single-threaded apartment (STA) is the default.

-Mta
    Start the shell using a multithreaded apartment.

-NoProfile
    Does not load the Windows PowerShell profile.

-NonInteractive
    Does not present an interactive prompt to the user.

-InputFormat
    Describes the format of data sent to Windows PowerShell. Valid values are
    "Text" (text strings) or "XML" (serialized CLIXML format).

-OutputFormat
    Determines how output from Windows PowerShell is formatted. Valid values
    are "Text" (text strings) or "XML" (serialized CLIXML format).

-WindowStyle
    Sets the window style to Normal, Minimized, Maximized or Hidden.

-EncodedCommand
    Accepts a base-64-encoded string version of a command. Use this parameter
    to submit commands to Windows PowerShell that require complex quotation
    marks or curly braces.

-File
    Runs the specified script in the local scope ("dot-sourced"), so that the
    functions and variables that the script creates are available in the
    current session. Enter the script file path and any parameters.
    File must be the last parameter in the command, because all characters
    typed after the File parameter name are interpreted
    as the script file path followed by the script parameters.

-ExecutionPolicy
    Sets the default execution policy for the current session and saves it
    in the $env:PSExecutionPolicyPreference environment variable.
    This parameter does not change the Windows PowerShell execution policy
    that is set in the registry.

-Command
    Executes the specified commands (and any parameters) as though they were
    typed at the Windows PowerShell command prompt, and then exits, unless
    NoExit is specified. The value of Command can be "-", a string. or a
    script block.

    If the value of Command is "-", the command text is read from standard
    input.

    If the value of Command is a script block, the script block must be enclosed
    in braces ({}). You can specify a script block only when running PowerShell.exe
    in Windows PowerShell. The results of the script block are returned to the
    parent shell as deserialized XML objects, not live objects.

    If the value of Command is a string, Command must be the last parameter
    in the command , because any characters typed after the command are
    interpreted as the command arguments.

    To write a string that runs a Windows PowerShell command, use the format:
        "& {<command>}"
    where the quotation marks indicate a string and the invoke operator (&)
    causes the command to be executed.

-Help, -?, /?
    Shows this message. If you are typing a PowerShell.exe command in Windows
    PowerShell, prepend the command parameters with a hyphen (-), not a forward
    slash (/). You can use either a hyphen or forward slash in Cmd.exe.

EXAMPLES
    PowerShell -PSConsoleFile SqlSnapIn.Psc1
    PowerShell -version 2.0 -NoLogo -InputFormat text -OutputFormat XML
    PowerShell -Command {Get-EventLog -LogName security}
    PowerShell -Command "& {Get-EventLog -LogName security}"

    # To use the -EncodedCommand parameter:
    $command = 'dir "c:\program files" '
    $bytes = [System.Text.Encoding]::Unicode.GetBytes($command)
    $encodedCommand = [Convert]::ToBase64String($bytes)
    powershell.exe -encodedCommand $encodedCommand
true

julia>
````

I believe the whole output from Powershell should actually not be displayed in this case.

Doing something similiar but with CMD seems to work correctly:

````
julia> success(`cmd /C dir`)
true

julia>
````

Here is my version info:

````
julia> versioninfo()
Julia Version 0.4.2
Commit bb73f34 (2015-12-06 21:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia>
````

**Comment by yuyichao** [comment] 2015-12-07 23:30
Does this have any similarity with some special files wired directly to the terminal on linux that is very hard to suppress the output.

```jl
julia> success(`sh -c 'echo 0 > /dev/tty'`)
0
true
```

**Comment by dhoegh** [comment] 2015-12-08 21:34
I have also seen this on windows 8, but not on windows 7.

**Comment by Ismael-VC** [comment] 2015-12-10 23:58
I can confirm this doesn't happen on Windows 7:

```julia
julia> VERSION
v"0.4.0"

julia> success(`powershell -h`)
true
```

```julia
julia> VERSION
v"0.5.0-dev+350"

julia> success(`powershell -h`)
true
```

Using Windows 7 Professional (x86_64-w64-mingw32)

**Comment by davidanthoff** [comment] 2015-12-11 00:46
@Ismael-VC What version of Powershell are you using? I think one can upgrade PowerShell on Win7 to the latest version by installing the Windows Management Framework.

**Comment by tkelman** [comment] 2015-12-11 01:04
On Win 7, slightly old Julia 0.4-pre, I get
```
julia> success(`powershell -h`)
true
julia> success(`powershell -Command "\$PSVersionTable.PSVersion"`)
true
julia> print(readall(`powershell -Command "\$PSVersionTable.PSVersion"`))
Major  Minor  Build  Revision
-----  -----  -----  --------
3      0      -1     -1
```

**Comment by Ismael-VC** [comment] 2015-12-11 01:24
@davidanthoff I'm using:

```julia
julia> print(readall(`powershell -Command "\$PSVersionTable.PSVersion"`))

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

I'll install Windows Management Framework in order to test with the latest version.

**Comment by Ismael-VC** [comment] 2015-12-11 02:02
I've updated `powershell` and still get the same results:

```julia
julia> VERSION
v"0.4.0"

julia> success(`powershell -h`)
true

julia> print(readall(`powershell -Command "\$PSVersionTable.PSVersion"`))

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

```julia
julia> VERSION
v"0.5.0-dev+350"

julia> success(`powershell -h`)
true

julia> print(readall(`powershell -Command "\$PSVersionTable.PSVersion"`))

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

**Comment by Ismael-VC** [comment] 2015-12-11 02:17
I don't know if this is meaningfull, but I'll leave it here anyway:

```julia
julia> VERSION
v"0.4.1"

julia> success(`cmd /h`)
true
```

Using windows XP 32 bits (virtualized).

**Comment by davidanthoff** [comment] 2015-12-11 03:28
Windows 10 has WMF 5 (and therefore PowerShell 5) by default. There is a production preview download for older versions of Windows [here](https://www.microsoft.com/en-us/download/details.aspx?id=48729). Would be interesting to know whether Win7 with WMF5 has the same problem or not...

**Comment by Ismael-VC** [comment] 2015-12-11 05:27
I confirm it's WMF5 causing this:

shell> powershell -Command "\$PSVersionTable.PSVersion"

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10514  6

**Comment by sunoru** [comment] 2016-03-06 11:33
With the powershell version of 1 or 2 the help text doesn't appear so I use ``success(`powershell -v 2 -h`)`` to avoid this... Maybe another method to check the existence of powershell should be used?

**Comment by tkelman** [comment] 2016-03-06 12:03
That looks easy enough. Let's just do that for now. Thanks!

**Comment by vtjnash** [comment] 2016-06-29 02:09
not a bug here. (fixed in https://github.com/JuliaLang/BinDeps.jl/issues/192)

**Closed** 2016-06-29 02:09 UTC
Labels: windows

**Comment by tkelman** [comment] 2016-06-29 02:11
Does seem like libuv could be trying to do something less annoying here.

**Comment by vtjnash** [comment] 2016-06-29 02:15
libuv's not at fault. powershell simply changed their printing behavior for the `-v` flag across a version update

**Comment by tkelman** [comment] 2016-06-29 02:29
It's not `-v`, it's all powershell output is now getting printed from libuv spawn commands that shouldn't be printing them.
