### ISSUE TITLE
abstractarray cat3v inferred test

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#50550] opened 2023-07-14 14:14 UTC
```
The global RNG seed was 0x2fa9baa4eecda6ff6ae4a326ff42a832.

Error in testset abstractarray:
Error During Test at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/julia-22502b8753/share/julia/test/abstractarray.jl:762
  Test threw exception
  Expression: #= /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/julia-22502b8753/share/julia/test/abstractarray.jl:762 =# @inferred(cat3v(As)) == zeros(2, 2, 2)
  return type Array{Float64, 3} does not match inferred return type Array{_A, 3} where _A
  Stacktrace:
   [1] error(s::String)
     @ Base ./error.jl:35
   [2] macro expansion
     @ Main.Test82Main_abstractarray /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/julia-22502b8753/share/julia/stdlib/v1.11/Test/src/Test.jl:669 [inlined]
   [3] test_cat(::Type{Main.Test82Main_abstractarray.TestAbstractArray})
     @ Main.Test82Main_abstractarray /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/julia-22502b8753/share/julia/test/abstractarray.jl:762
ERROR: LoadError: Test run finished with errors
in expression starting at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/julia-22502b8753/share/julia/test/runtests.jl:95
```
https://buildkite.com/julialang/julia-master/builds/25873#018950e3-eedd-41e0-8a96-bbd23fe9154e

**Comment by Keno** [comment] 2023-07-14 14:45
This reproduces with the sequence of tests on that worker:
```
$ JULIA_CPU_THREADS=1 ./usr/bin/julia test/runtests.jl LinearAlgebra/special LinearAlgebra/lapack LinearAlgebra/pinv compiler/effects compiler/codegen compiler/EscapeAnalysis/interprocedural strings/util char triplequote intrinsics hashing tuple abstractarray

Running parallel tests with:
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 1
  Sys.total_memory() = 503.822 GiB
  Sys.free_memory() = 388.686 GiB

Test                                (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
LinearAlgebra/special                    (1) |        started at 2023-07-14T14:38:20.077
LinearAlgebra/special                    (1) |   169.28 |   2.72 |  1.6 |   13233.10 |   856.03
LinearAlgebra/lapack                     (1) |        started at 2023-07-14T14:41:09.453
LinearAlgebra/lapack                     (1) |    55.06 |   1.09 |  2.0 |    3033.09 |  1205.91
LinearAlgebra/pinv                       (1) |        started at 2023-07-14T14:42:04.512
LinearAlgebra/pinv                       (1) |    10.89 |   0.37 |  3.4 |     978.34 |  1248.11
compiler/effects                         (1) |        started at 2023-07-14T14:42:15.400
compiler/effects                         (1) |     2.21 |   0.02 |  1.0 |     184.84 |  1258.30
compiler/codegen                         (1) |        started at 2023-07-14T14:42:17.606
compiler/codegen                         (1) |     4.80 |   0.95 | 19.9 |     158.77 |  1258.50
compiler/EscapeAnalysis/interprocedural  (1) |        started at 2023-07-14T14:42:22.409
compiler/EscapeAnalysis/interprocedural  (1) |     8.77 |   0.19 |  2.1 |     487.50 |  1258.50
strings/util                             (1) |        started at 2023-07-14T14:42:31.181
strings/util                             (1) |     7.32 |   0.21 |  2.9 |     585.67 |  1327.54
char                                     (1) |        started at 2023-07-14T14:42:38.504
char                                     (1) |     1.91 |   0.04 |  2.1 |     109.52 |  1327.54
triplequote                              (1) |        started at 2023-07-14T14:42:40.420
triplequote                              (1) |     0.03 |   0.00 |  0.0 |       1.20 |  1327.54
intrinsics                               (1) |        started at 2023-07-14T14:42:40.450
intrinsics                               (1) |     1.92 |   0.05 |  2.4 |     121.24 |  1327.54
hashing                                  (1) |        started at 2023-07-14T14:42:42.373
hashing                                  (1) |    14.40 |   0.37 |  2.6 |    3145.29 |  3354.50
tuple                                    (1) |        started at 2023-07-14T14:42:56.779
tuple                                    (1) |     6.58 |   0.22 |  3.3 |     578.72 |  3354.55
abstractarray                            (1) |        started at 2023-07-14T14:43:03.359
abstractarray                            (1) |         failed at 2023-07-14T14:44:31.316
Error During Test at /home/keno/julia/test/abstractarray.jl:762
  Test threw exception
  Expression: #= /home/keno/julia/test/abstractarray.jl:762 =# @inferred(cat3v(As)) == zeros(2, 2, 2)
  return type Array{Float64, 3} does not match inferred return type Array{_A, 3} where _A
  Stacktrace:
   [1] error(s::String)
     @ Base ./error.jl:35
   [2] macro expansion
     @ Main.Test98Main_abstractarray ~/julia/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:669 [inlined]
   [3] test_cat(::Type{Main.Test98Main_abstractarray.TestAbstractArray})
     @ Main.Test98Main_abstractarray ~/julia/test/abstractarray.jl:762
```

**Comment by Keno** [comment] 2023-07-14 15:03
Reproduces with just `hashing`:
```
JULIA_CPU_THREADS=1 ./usr/bin/julia test/runtests.jl hashing abstractarray
Running parallel tests with:
  nworkers() = 1
  nthreads() = 1
  Sys.CPU_THREADS = 1
  Sys.total_memory() = 503.822 GiB
  Sys.free_memory() = 387.623 GiB

Test      (Worker) | Time (s) | GC (s) | GC % | Alloc (MB) | RSS (MB)
hashing        (1) |        started at 2023-07-14T15:00:14.741
hashing        (1) |    13.55 |   0.23 |  1.7 |    3221.62 |  2492.21
abstractarray  (1) |        started at 2023-07-14T15:00:28.385
abstractarray  (1) |         failed at 2023-07-14T15:01:54.298
Error During Test at /home/keno/julia/test/abstractarray.jl:762
  Test threw exception
  Expression: #= /home/keno/julia/test/abstractarray.jl:762 =# @inferred(cat3v(As)) == zeros(2, 2, 2)
  return type Array{Float64, 3} does not match inferred return type Array{_A, 3} where _A
  Stacktrace:
   [1] error(s::String)
     @ Base ./error.jl:35
   [2] macro expansion
     @ Main.Test35Main_abstractarray ~/julia/usr/share/julia/stdlib/v1.11/Test/src/Test.jl:669 [inlined]
   [3] test_cat(::Type{Main.Test35Main_abstractarray.TestAbstractArray})
     @ Main.Test35Main_abstractarray ~/julia/test/abstractarray.jl:762
```

**Comment by Keno** [comment] 2023-07-14 15:17
The issue is `using SparseArrays`, which adds extra `cat` methods, that cause failure to infer. https://github.com/JuliaLang/julia/pull/49322 does look like the likely culprit, so assigning this back to @vtjnash for now.

**Comment by vtjnash** [comment] 2023-07-14 15:20
Seems to come from the type-piracy of SparseArrays:
```
julia> using SparseArrays
julia> @inferred(cat3v([zeros(2, 2) for _ = 1:2]))
```

**Comment by vtjnash** [comment] 2023-07-14 18:39
We probably should just remove SparseArrays from that test file, since we removed SparseArrays from Base

**Comment by NHDaly** [comment] 2023-07-30 00:45
We talked this week about disabling this test. Is that still how we want to proceed? I'm not familiar enough to say if it's a good test or not.

**Closed** 2023-08-02 15:41 UTC
Labels: ci
