### ISSUE TITLE
Error messages in convert sometimes put extra braces after eltype

### ISSUE THREAD

**Issue by jishnub** [JuliaLang/julia#40643] opened 2021-04-28 07:07 UTC
```julia
julia> using OffsetArrays, LinearAlgebra

julia> convert(OffsetArray{ComplexF64,2, Diagonal{ComplexF64,Vector{ComplexF64}}}, OffsetArray(zeros(ComplexF64,3,3), 0,0))
ERROR: MethodError: Cannot `convert` an object of type 
  OffsetArray{Complex{Float64{}},2,Matrix{ComplexF64}} to an object of type 
  OffsetArray{Complex{Float64{}},2,Diagonal{ComplexF64, Vector{ComplexF64}}}
Closest candidates are:
  convert(::Type{T}, ::Factorization) where T<:AbstractArray at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/LinearAlgebra/src/factorization.jl:58
  convert(::Type{T}, ::T) where T<:AbstractArray at abstractarray.jl:16
  convert(::Type{T}, ::T) where T at essentials.jl:228
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[16]:1

julia> VERSION
v"1.7.0-DEV.1025"
```

The eltype in the error message is displayed as `Complex{Float64{}}` instead of `Complex{Float64}`. This only happens for some combinations of types.

**Comment by vtjnash** [comment] 2021-04-28 14:37
Duplicate of https://github.com/JuliaLang/julia/issues/36644

**Closed by vtjnash** 2021-04-28 14:37 UTC
Labels: error messages
