### ISSUE TITLE
new postfix `transpose()` operator different from `'`

### ISSUE THREAD

**Issue by johnalx** [JuliaLang/julia#35593] opened 2020-04-24 22:37 UTC
Can we introduce a new postfix operator for the transpose, like `A^⊤` or `A̕` ?

It would of great help to us who write expressions with a lot of transposes. For example:

    a = (transpose(s)*A*s)\s*(Q-transpose(s)*p+U*transpose(R)*κ)

and it would more true to form if the multiple calls to `transpose()` were replaced with something more terse. Even if the language defaulted to transpose for `A'` unless it knew a complex data type was used when the adoint is more appropriate.

**Comment by MasonProtter** [comment] 2020-04-25 00:02
Ref https://github.com/JuliaLang/julia/issues/34507

If you like, you can always do this:
```julia
struct Transposer end
const ᵀ = Transposer() #typed \^T<TAB>
Base.:(*)(x, ::Transposer) = transpose(x)
```
```julia
julia> rand(5)ᵀ*randn(5,5)*rand(5)
0.7409506780313673
```

**Comment by musm** [comment] 2020-04-25 01:59
https://github.com/musm/EasyTranspose.jl

**Comment by johnalx** [comment] 2020-04-27 12:21
> Ref #34507, #21037
> 
> If you like, you can always do this:
> 
> ```julia
> struct Transposer end
> const ᵀ = Transposer() #typed \^T<TAB>
> Base.:(*)(x, ::Transposer) = transpose(x)
> ```
> 
> ```julia
> julia> rand(5)ᵀ*randn(5,5)*rand(5)
> 0.7409506780313673
> 
> julia> A = rand(5); (A)ᵀ*rand(5, 5)*A
> 2.7952114562233827
> ```

Yet the following does not work

    z = rand(3)
    zᵀ*z    # ERROR: UndefVarError: zᵀ not defined

**Comment by MasonProtter** [comment] 2020-04-27 14:22
It works if you surround `z` in parentheses. 
```julia
julia> (z)ᵀ*z
1.4221674642522308
```

I should also reference this PR: https://github.com/JuliaLang/julia/pull/34549 where they run PkgEval to show what registered packages would be effected by changing the meaning of `zᵀ` from just a variable named `zᵀ` to `transpose(z)`. The list of broken packages is quite small, but the Julia devs take breaking changes very seriously.

**Comment by JeffBezanson** [comment] 2020-04-27 21:18
duplicate of #21037

**Comment by JeffBezanson** [comment] 2020-04-27 21:19
> Even if the language defaulted to transpose for `A'` unless it knew a complex data type was used when the adoint is more appropriate.

Isn't that already the case --- adjoint and transpose are equivalent for reals?

**Closed by JeffBezanson** 2020-04-27 21:18 UTC
