### ISSUE TITLE
Stop hiding math intrinsics from llvm

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#19640] opened 2016-12-18 19:47 UTC
Currently we hide math intrinsics (e.g. `exp`, `log`, etc) from LLVM to avoid it using the wrong libm for constant folding and in the JIT. However, esp on highly parallel architectures such as KNL and probably on GPUs as well, LLVM can vectorize those functions and in fact needs to if we want to get performance. However, this of course doesn't work if LLVM doesn't know that those functions exist. We should find a proper solution to it using the wrong libm and switch back to using the intrinsics.

**Comment by simonbyrne** [comment] 2016-12-18 21:50
Dupe of #15265 and/or #12830?

**Comment by Keno** [comment] 2016-12-18 21:54
Yes, it's pretty much #12830 + patches to LLVM to tell it which libm to use.

**Comment by StefanKarpinski** [comment] 2017-01-03 18:15
Is this a 1.0 issue?

**Comment by oxinabox** [comment] 2017-02-11 08:04
See also https://github.com/JuliaMath/Libm.jl/pull/8

**Comment by vtjnash** [comment] 2019-06-26 22:31
We don't have as many intrinsics anymore, as many have now been translated into Julia. Additionally, we now use Cassette for this ("should find a proper solution ... and switch back"). Closing in favor of #15265.

**Closed by vtjnash** 2019-06-26 22:31 UTC
Labels: maths, simd
