### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION at 0x41aa28b9 -- * at .\float.jl:405 [inlined]

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/julia#33603] opened 2019-10-18 13:05 UTC
```julia
julia> versioninfo()
Julia Version 1.3.0-rc2.0
Commit a04936e3e0 (2019-09-12 19:49 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = C:\\Users\\necka\\AppData\\Local\\Programs\\Microsoft\ VS\ Code\\Code.exe
  JULIA_NUM_THREADS = 8
  JULIA_PKG_DEVDIR = D:\Coding\Julia\dev
```

First few lines:
```julia
julia> model, xaxis, pars = preparedata(tmp, optim=0.001);

julia> Flux.train!(pars...);
-7.303327568437573 (tracked) and 0.04043347084933088 (tracked) and 26.60526490340767 (tracked)
-652.3926697516449 (tracked) and 651.8108443309218 (tracked) and 8611.631141070013 (tracked)
-5.851299510022969 (tracked) and 0.5809192141317354 (tracked) and 17.235646818933102 (tracked)
-5.467460876668256 (tracked) and 0.2655921309714975 (tracked) and 14.975996403634543 (tracked)
-4.979034316178533 (tracked) and 0.34604497856104866 (tracked) and 12.288806690180166 (tracked)
-4.5096431427469765 (tracked) and 0.4426934760750521 (tracked) and 9.877097671610452 (tracked)
-4.827889440051153 (tracked) and 1.4971893497457653 (tracked) and 7.8648350149301995 (tracked)
-4.51732613913725 (tracked) and 1.7015025259913739 (tracked) and 6.1356115589410996 (tracked)

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x41aa28b9 -- * at .\float.jl:405 [inlined]
* at .\promotion.jl:310 [inlined]
_broadcast_getindex_evalf at .\broadcast.jl:630 [inlined]
_broadcast_getindex at .\broadcast.jl:603 [inlined]
getindex at .\broadcast.jl:563 [inlined]
```
Full report: https://gist.github.com/rapus95/55a22a5ae56e15c9b69737692ddbf112

`preparedata` produces an output like that:
```julia
using JuliaDB, Flux, Plots, JuliaDBMeta, Interpolations, DSP, OffsetArrays, RecipesBase
#[...]
model = Chain(toWHCB, Conv((len,1), 1=>1), fromWHCB)
#[...]
return model, (x[1] for x in iter), (makeloss(model), params(model), (x[2:3] for x in iter), ADAM())
#thus model,      xaxis         ,   pars = (loss ,     params, iterator(input, reference output), optimizer)
```
As the code is not public available, I right now can't simply post it entirely here, but you can ask if there is more information that would be good if provided!

For now, Computer Sciences solution will be used: Doesn't work? Stop, Start, try again... Though program stops/crashes itself here, thus speeding up that workflow. 🙃

I'm really curious how I made float.jl crash that severe!

EDIT: ran into it again. But it doesn't seem to be arbitrarily reproducible. Fits nice into the Flux area. There I can't reproduce my results either... 🤦‍♂ New crash result, in case it helps, is in the same gist as the first file. On further crashes I will add them there aswell.

**Comment by vchuravy** [comment] 2019-10-18 14:51
This looks like a Flux specific issue, are you using GPUs? If so it looks like you might be executing GPU-specific code on the CPU.

**Comment by rapus95** [comment] 2019-10-18 14:54
```julia
using JuliaDB, Flux, Plots, JuliaDBMeta, Interpolations, DSP, OffsetArrays, RecipesBase
```
as by this I at least wouldn't use GPU intentionally. 🙈

**Comment by vchuravy** [comment] 2019-10-18 14:59
Without a reproducer it is going to be very hard to divine anything from this. Can you minimize the code to a simpler case?
Alternatively you can try using rr/gdb and look at what code is trying to run.

**Comment by rapus95** [comment] 2019-10-18 15:28
Can't say for sure but I found bug that can cause checked out of memory access. Has to do with reshaping of OffsetArrays. Now I got a very small MWE:
```julia
reshape(OffsetArray([-1:0...], -1:0), :, 1)
```
Where to report that now?
As it is a rather severe bug that CAN produce the errors I stumbled over, if the allocated array is at the border of the memory.

**Comment by vchuravy** [comment] 2019-10-18 18:09
Probably OffsetArrays.jl proper. Does it also reproduce with `julia
--check-bounds=yes`?

Make sure to start your version of Julia and OffsetArrays.

**Comment by vchuravy** [comment] 2019-10-21 17:11
Closing in favour of #33614

**Closed by vchuravy** 2019-10-21 17:11 UTC
