### ISSUE TITLE
map doesn't stop on exhausted tuple

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#49291] opened 2023-04-08 02:26 UTC
```jl
  map(f, c...) -> collection


  Transform collection c by applying f to each element. For multiple collection arguments, apply f
  elementwise, and stop when when any of them is exhausted.

julia> map(==, [10], [10,11])
1-element Vector{Bool}:
 1

julia> map(==, (10,), (10,11))
ERROR: BoundsError: attempt to access Tuple{} at index [1]
```

**Comment by Seelengrab** [comment] 2023-04-08 07:43
This seems to be explicitly being tested for:

https://github.com/JuliaLang/julia/blob/804da71a547d8211008572e0627510059d21f9ce/test/tuple.jl#L268-L269

Though I don't know why.

**Comment by N5N3** [comment] 2023-04-08 07:49
Duplicated with #42216

**Comment by JeffBezanson** [comment] 2023-04-12 15:55
Closing as duplicate of #42216

**Closed by JeffBezanson** 2023-04-12 15:55 UTC
