### ISSUE TITLE
Reduced precision in rand() on [0, 1) compared to python

### ISSUE THREAD

**Issue by RPigott** [JuliaLang/julia#32187] opened 2019-05-30 03:01 UTC
Something about julia `rand()` floats has been bugging me for a while.

The crux of this issue is:

```julia
Using PyCall
PyRandom = pyimport(:random)
pyrand(dims...) = [PyRandom.random() for _ in zeros(dims...)]

julia> sum(hcat(collect.(bitstring.(pyrand(10000)))...)[end, :] .== '1')
2487
julia> sum(hcat(collect.(bitstring.(rand(10000)))...)[end, :] .== '1')
0
```
That is, the last bit of the mantissa for floats generated by `rand()` in julia is always '0'. In Python it's '1' 1 out of 4 times, 50% of the time for numbers > 0.5.

It looks like the definition of `rand()` falls to the second method here:
https://github.com/JuliaLang/julia/blob/6d23d520dfc666d307951b020f5204fbaf5c4291/stdlib/Random/src/generation.jl#L32-L36
where we get a 52 bit UInt52, shove it in the mantissa of a Float64 with the exponent set to 0 and subtract 1.0 to transform [1.0, 2.0) to [0.0, 1.0). The density of floats on these intervals is not uniform, so bits near the end are reduced to zero when the random number falls in an interval with a smaller epsilon than that in [1.0, 2.0). So [0.0, 1.0) has last bit '0', [0.0, 0.5) has last 2 bits '00' etc.

IEEE754 doubles may have a 52-bit fraction, but they have a 53-bit significand, which Python correctly represents by instead generating a random 53-bit UInt and dividing by essentially typemax(UInt53).
https://github.com/python/cpython/blob/80878312316bfb4011157f13cf040f6d885f808b/Modules/_randommodule.c#L138-L163
So Python random floats have [0.0, 0.5) last bit '0', [0.0, 0.25) last 2 bits '00' etc.

I think, in an ideal world, generating a random float on [0.0, 1.0) might involve picking a uniform random real on [0.0, 1.0) and then picking the closest float representation. If I'm not mistaken, all mantissa bits in this case would have equal chance to be '1'. That's hard, and floats don't have uniform density, so instead we pick randomly from floats in [0.0, 1.0) with uniform density 1 / 2^52. I get that much, but Python is picking from twice as big a pool of floats in [0.0, 1.0) with uniform density 1 / 2^53. So isn't that strictly better?

Does one bit even matter? Is there a performance benefit or something for choosing 1 / 2^52 floats? Is it desirable for some other reason? Would you accept a PR that changes julia `rand()` floats to be more like Python `random()` floats in this regard?

**Comment by ViralBShah** [comment] 2019-05-30 13:08
cc @rfourquet

**Comment by chethega** [comment] 2019-05-30 14:17
The issue is much deeper than the last bit (really, who cares about the LSB). The loss of precision / bias is huge for small numbers. Consider `Float32`: The correct probability of hitting zero by `rand(Float32)` would be about `nextfloat(0.0f0)==1.0f-45` (i.e. never). However,
```julia> function genzero()
       n=0
       while rand(Float32)!=0
       n+=1
       end
       return n
       end
julia> for i=1:30
       @show genzero()
       end
genzero() = 10667263
genzero() = 9663774
genzero() = 1169701
genzero() = 6097731```

> That's hard,

It is not really hard. The mantissa bits want to be uniform random and the exponent wants to be exponentially distributed, with appropriate special casing for subnormals. Exponential distribution is easy by just counting `leading_zeros` on an infinite uniformly random bitstring. Subnormals and zero want to have vanishingly small probability, so we can ignore that case. If we took 64 bit uniform random input, we could generate reasonably fast reasonably good random Float64 by `f3(x::UInt64)= begin tz = trailing_zeros(x); reinterpret(Float64, (x>>12) | (1022-tz)<<52) end`. The function `f3` is written that way, because (with probability 1 in 4000) it has a correlation between lower bits and exponent. If we did ``f4(x::UInt64)= begin lz =leading_zeros(x); reinterpret(Float64, ( (x<<12)>>12) | (1022-lz)<<52) end` we would instead get a correlation bitween exponent and high bits, which is worse.

As far as I recall, the current bias in the low bits was deemed acceptable for most applications, due to the speed gain with the current mersenne twister implementation.

Personally, I would prefer a `rand` that never outputs `0.0`, like the above `f3`. That would relieve people of special casing stuff that should have probability "approx never ever", and give more correct tails for distributions like `log(rand(Float32))` or `1/rand(Float32)`.

**Comment by mbauman** [comment] 2019-05-30 15:47
Previously: https://github.com/JuliaLang/julia/issues/16344

**Comment by KristofferC** [comment] 2019-05-30 18:32
Closing as dup.

**Closed by KristofferC** 2019-05-30 18:32 UTC
Labels: RNG

**Comment by mbauman** [comment] 2019-05-30 19:04
Just to be clear, this is an intentional performance tradeoff.  If it's possible to generate that last bit efficiently and without bias, then yes, it'd be great to have!  But as Simon Byrne enumerates in https://github.com/JuliaLang/julia/issues/16344#issuecomment-219001816, doing so is quite the challenge.

Of note:

```python
In [1]: import random

In [2]: %timeit random.random()
The slowest run took 59.89 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 3: 115 ns per loop
```

```julia
julia> @benchmark rand() evals=10000000
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     4.711 ns (0.00% GC)
  median time:      4.717 ns (0.00% GC)
  mean time:        4.723 ns (0.00% GC)
  maximum time:     4.878 ns (0.00% GC)
  --------------
  samples:          106
  evals/sample:     10000000
```
