### ISSUE TITLE
tuple construction problem

### ISSUE THREAD

**Issue by GaborOszlanyi** [JuliaLang/julia#9918] opened 2015-01-25 08:45 UTC
I experience the following problem using the 0.3.5 binary on Windows 7.
Could anyone confirm, please ?

I could go back to previous binary versions,
0.3.3 was OK, the problem appeared in 0.3.4.

```
julia> 1,2,3
(1,2,0)
julia> (1,2,3)
(1,2,0)
julia> t=(1,2,3)
(1,2,0)
julia> t=tuple(1,2,3)
(1,2,0)

julia> versioninfo()
Julia Version 0.3.5
Commit a05f87b* (2015-01-08 22:33 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by tkelman** [comment] 2015-01-25 08:55
Duplicate of #7434. It's a display-only issue on Haswell processors, you should see `t[3] == 3`. I think it's been around for the entire 0.3 series as well.

**Closed by tkelman** 2015-01-25 08:55 UTC

**Comment by GaborOszlanyi** [comment] 2015-01-25 09:01
Thank you for the prompt reply,
good to know that it is a display-only issue.
Anyhow, version 0.3.3 did display tuples correctly.

**Comment by tkelman** [comment] 2015-01-25 09:04
> Anyhow, version 0.3.3 did display tuples correctly.

Also on win64, on the same haswell processor? That's quite surprising.

**Comment by GaborOszlanyi** [comment] 2015-01-25 09:08
Yes, on win64 and on the same haswell processor.
