### ISSUE TITLE
`repeat` for zero-dimensional arrays

### ISSUE THREAD

**Issue by yurivish** [JuliaLang/julia#29020] opened 2018-09-03 18:36 UTC
**Summary:** `repeat` does not work with 0-d arrays when used as `repeat(arr, outer=...)`. The documentation suggests that this should work.

**Details**

The function `repeat` with the `outer` argument replicates the contents of an array to the specified lengths along the given dimensions.

```julia
julia> repeat([5, 6], outer=(2, 2, 2))
4×2×2 Array{Int64,3}:
[:, :, 1] =
 5  5
 6  6
 5  5
 6  6

[:, :, 2] =
 5  5
 6  6
 5  5
 6  6
```

The array argument to `repeat` may be of lower dimension than the desired output, as in the result above — and everything works. 

But it does not work with zero-dimensional arrays:

```julia
julia> repeat(collect(5), outer=(2, 2))
```
Even though

```julia
julia> collect(5)[:]
1-element Array{Int64,1}:
 5

julia> collect(5)[:, :]
1×1 Array{Int64,2}:
 5
```

The `repeat` docstring states "The i-th element of outer  specifies the number of times that a slice along the i-th dimension of A  should be repeated.", which I think indicates that repeating a 0d array should return (e.g. return `[5 5; 5 5]` for the above example) since they can be sliced in higher dimensions.

**Comment by raghav9-97** [comment] 2018-12-18 11:31
In function repeat we can check if size(A) == () then A = A[:, :] but in this way if we return A then modified array would be returned.

**Comment by raghav9-97** [comment] 2018-12-19 05:20
```
julia> repeat(collect(5) ,outer=(2,2))
2×2 Array{Int64,2}:
 5  5
 5  5
```
I can't reproduce this issue in my system.
```versioninfo()
Julia Version 1.2.0-DEV.35
Commit eddcbd7 (2018-12-18 21:59 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by raghav9-97** [comment] 2018-12-20 17:40
I believe this issue has been resolved in Julia ver. 1.2.0 but there is no existing test.I can add a few tests using repeat with 0-dimensional arrays.

**Comment by fredrikekre** [comment] 2018-12-21 19:58
#30477

**Closed by fredrikekre** 2018-12-21 19:58 UTC
Labels: arrays, bug
