### ISSUE TITLE
codegen assertion in BitIntegers

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#34288] opened 2020-01-06 21:23 UTC
With #34287 running `]test BitIntegers`:
```
julia: /home/jeff/src/julia/src/cgutils.cpp:514: unsigned int convert_struct_offset(llvm::Type*, unsigned int): Assertion `SL->getElementOffset(idx) == byte_offset' failed.

signal (6): Aborted
in expression starting at /home/jeff/.julia/packages/BitIntegers/4QmBA/test/runtests.jl:333
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f5b6a6b2bf5)
__assert_fail at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
convert_struct_offset at /home/jeff/src/julia/src/cgutils.cpp:514
convert_struct_offset at /home/jeff/src/julia/src/cgutils.cpp:527 [inlined]
convert_struct_offset at /home/jeff/src/julia/src/cgutils.cpp:520 [inlined]
emit_struct_gep at /home/jeff/src/julia/src/cgutils.cpp:525
emit_getfield_knownidx at /home/jeff/src/julia/src/cgutils.cpp:1672
emit_builtin_call at /home/jeff/src/julia/src/codegen.cpp:2872
```

**Comment by vtjnash** [comment] 2020-01-06 22:15
Duplicate of https://github.com/JuliaLang/julia/issues/32414

**Comment by rfourquet** [comment] 2020-03-04 11:30
The fix for the duplicate doesn't seem to fix this issue, so re-opening. Sorry if I messed my testing and got this wrong.

**Comment by rfourquet** [comment] 2020-03-04 11:39
Minimal repro:
```
using BitIntegers
BitIntegers.@define_integers 24
Base.sub_with_overflow(typemin(UInt24)+UInt24(3), UInt24(3)) == (typemin(UInt24), false)
```

**Comment by rfourquet** [comment] 2021-05-12 08:01
The minimal repro above seems to have been fixed in 1.6. But I found another "Internal error" in today's master (d6c092d6d7):
```julia
julia> using BitIntegers

julia> BitIntegers.@define_integers 24; x = UInt24(0);

julia> x
Internal error: encountered unexpected error in runtime:
MethodError(f=Main.UInt24, args=(0,), world=0x0000000000001133)
jl_method_error_bare at /local/src/julia/src/gf.c:1818
jl_method_error at /local/src/julia/src/gf.c:1836
jl_lookup_generic_ at /local/src/julia/src/gf.c:2406 [inlined]
jl_apply_generic at /local/src/julia/src/gf.c:2421
convert at ./number.jl:7
zero at ./number.jl:292
_jl_invoke at /local/src/julia/src/gf.c:2243 [inlined]
jl_apply_generic at /local/src/julia/src/gf.c:2425
[...]
```
It's a relatively recent error which was not there in d524f21917 (81 days old master)

**Closed** 2021-06-14 19:41 UTC
Labels: bug, codegen

**Comment by atbug** [comment] 2022-05-26 06:01
I am seeing the same error message in 1.7:

https://github.com/Hop-developers/Hop.jl/runs/6604926044

**Comment by KristofferC** [comment] 2022-05-26 06:33
Could you open a new issue about it?
