### ISSUE TITLE
Document A_ldiv_B!

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#13940] opened 2015-11-10 20:40 UTC
The docs don't have an entry for `A_ldiv_B!`, but it has (in version 0.4.0-rc3) 37 methods.  Adding a short entry to the docs specifying the order of the arguments would be very helpful.

**Comment by nalimilan** [comment] 2015-11-10 21:59
Would you make a PR to fix that?

**Comment by JaredCrean2** [comment] 2015-11-10 23:52
Sure, but I have never done  PR before.  Can you talk me through it?

**Comment by jiahao** [comment] 2015-11-11 03:20
@JaredCrean2 start with https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#improving-documentation and feel free to ask if you have any questions. (If you have questions, then probably you've found a place to improve the CONTRIBUTING docs too.)

**Comment by jiahao** [comment] 2015-11-11 14:55
Closing as duplicate of #13110

**Closed by jiahao** 2015-11-11 14:55 UTC
Labels: doc, linear algebra
