### ISSUE TITLE
Copying code using tabs to indent causes REPL to dump all Base exports

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaLang/julia#41052] opened 2021-06-01 20:43 UTC
This is relevant to Pluto.jl, which uses tabs to indent.

If you copy over multiple lines of code into the REPL from a Pluto notebook, it dumps the list of Base exports.

I suggest that tabs at the beginning of input should be ignored.

Example (copy whitespace):
```
		range1 = 1:5
```

Related to #37815

**Comment by KristofferC** [comment] 2021-06-01 20:50
Windows I guess?

**Comment by BioTurboNick** [comment] 2021-06-01 20:52
Yes, it seems to only affect the Windows Terminal and console, not when running in WSL.

**Comment by BioTurboNick** [comment] 2021-06-01 20:53
Actually pressing tab twice in WSL does trigger it, but pasting doesn't.

**Comment by manuelbb-upb** [comment] 2021-11-26 09:40
I experience the same issue in VSCode under Linux (KDE Neon/Ubuntu) with the “Send Current Line or Selection to REPL” command.

**Comment by vtjnash** [comment] 2024-07-24 16:27
Duplicate of https://github.com/JuliaLang/julia/issues/53763

**Closed by vtjnash** 2024-07-24 16:27 UTC
Labels: system:windows, stdlib:REPL
