### ISSUE TITLE
unreachable reached when struct constructor trys to convert a `Vector{Union{Nothing, T} where T}` to a `Vector{Any}`

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#38091] opened 2020-10-19 01:53 UTC
MWE:

```julia
struct Foo
   a::Vector{Any}
end

xs = Vector{Union{Nothing, T} where T}([2, 3])
Foo(xs)
```

this leads to "illegal hardware instruction" on both Julia 1.5.2 and julia 1.6.0-DEV.1184 

The lowered code and typed code seems fine, but `code_llvm` gives

```
julia> @code_llvm Foo(xs)
;  @ REPL[1]:2 within `Foo'
define [1 x {}*] @julia_Foo_491({}* nonnull align 16 dereferenceable(40) %0) {
top:
  call void @llvm.trap()
  unreachable
}
```

also I find that the result of `convert` and `Vector{Any}(x)` does not match, though `convert` actually (should) calls `Vector{Any}` to convert `xs` to `Vector{Any}` (https://github.com/JuliaLang/julia/blob/master/base/array.jl#L554), e.g

```julia-repl
julia> convert(Vector{Any}, xs)
2-element Vector{Union{Nothing, T} where T}:
 2
 3

julia> Vector{Any}(xs)
2-element Vector{Any}:
 2
 3
```

This is because Julia thinks `xs` of type `Vector{Union{Nothing, T} where T}` is a `Vector{Any}`, so `convert` returns `xs` directly but I'm not sure if this is actually true...

**Comment by vtjnash** [comment] 2020-10-19 16:49
It is trivially true:
```
julia> Any == Union{Nothing, T} where T
true
```

But datatype creation is not handling this

**Comment by vtjnash** [comment] 2020-10-19 16:49
Duplicate of #35130

**Closed by vtjnash** 2020-10-19 16:49 UTC
Labels: bug
