### ISSUE TITLE
`b"\\\\" == b"\\"`, is this intended?

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#46243] opened 2022-08-03 06:17 UTC
Currently, we have
```
julia> b"\\\\" == b"\\"
true
```

Which I can't understand. Something adjecant is mentioned in the manual here: https://docs.julialang.org/en/v1/manual/strings/#man-raw-string-literals,
but this does not really cover why `length(b"\\\\") == 1`.

**Comment by simeonschaub** [comment] 2022-08-03 09:02
Looks like backslashes here get unescaped twice, once in the parser and once when `unescape_string` is called inside `@b_str`. Somewhat related to #41041

**Comment by mgkuhn** [comment] 2022-08-03 13:34
Duplicate of #39092, where I provide a detailed explanation of what happens.

**Closed** 2022-08-03 13:37 UTC
Labels: bug, strings

**Comment by vtjnash** [comment] 2022-08-03 19:02
It would probably be good to fix this, but breaking
