### ISSUE TITLE
LinearAlgebra.I acts like `ones` when broadcast on the nightly/beta2

### ISSUE THREAD

**Issue by ArnavSood** [JuliaLang/julia#28252] opened 2018-07-24 04:12 UTC
See below for Minimum Working Example or whatever that's called (**edit**: add versioninfo()): 

```
julia> x = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> using LinearAlgebra

julia> x .-= LinearAlgebra.I
┌ Warning: broadcast will default to iterating over its arguments in the future. Wrap arguments of
│ type `x::UniformScaling{Bool}` with `Ref(x)` to ensure they broadcast as "scalar" elements.
│   caller = ip:0x0
└ @ Core :-1
2×2 Array{Int64,2}:
 0  1
 2  3

julia> x .-= Ref(LinearAlgebra.I)
2×2 Array{Int64,2}:
 -1  0
  1  2

julia> versioninfo()
Julia Version 0.7.0-beta2.90
Commit 789ad046b1 (2018-07-24 03:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.0.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by traktofon** [comment] 2018-07-24 10:12
As far as I can tell julia-0.6 behaves in the same way. What is the bug here?

**Comment by StefanKarpinski** [comment] 2018-07-24 16:05
@andreasnoack, @mbauman?

**Comment by ArnavSood** [comment] 2018-07-24 16:05
Thanks, wasn’t aware of v0.6 behavior. Maybe it’s not a bug, as much as highly unintuitive notation. When you write M .-= I, you expect (I think) an elementwise subtraction with an identity matrix.

**Comment by martinholters** [comment] 2018-07-24 16:19
This seems like a good example of why the "when in doubt treat it as a scalar"-rule is problematic.

**Comment by mbauman** [comment] 2018-07-24 17:22
Yes, Martin has the right thought here — in 0.6 we default to treating all objects as scalars.  In 0.7 we have deprecated this behavior so you'll get a deprecation warning.  In 1.0 it won't work at all until we add special broadcasting support for `I`.

Duplicate of #23197.

**Closed by mbauman** 2018-07-24 17:22 UTC
