### ISSUE TITLE
Scoping bug with logging macros

### ISSUE THREAD

**Issue by fredrikekre** [JuliaLang/julia#39199] opened 2021-01-11 21:31 UTC
This seems a bit strange:
```julia
julia> function f()
           x = 1
           @debug x = 2
           return x
       end
f (generic function with 1 method)

julia> f()
1

julia> ENV["JULIA_DEBUG"] = "all"
"all"

julia> f()
┌ Debug: 2
└ @ Main REPL[1]:3
2
```
Only happens when the assignment is part of the log message and not e.g. for:
```julia
julia> function f()
           x = 1
           @debug "hello" x = 2
           return x
       end
f (generic function with 1 method)

julia> f()
1

julia> ENV["JULIA_DEBUG"] = "all"
"all"

julia> f()
┌ Debug: hello
│   x = 2
└ @ Main REPL[1]:3
1
```

**Comment by StefanKarpinski** [comment] 2021-04-07 16:37
@c42f, can you take a look at this? Seems like there's a missing local scope block in the implementation.

**Comment by vtjnash** [comment] 2021-04-08 02:23
Everything seems intentional here. Assigning a keyword argument in a function call doesn't alter a local variable of the same name, and debug statements are not executed if they are disabled.

**Comment by StefanKarpinski** [comment] 2021-04-08 16:53
I guess the issue here is that in the first version `x = 2` is an expression which is evaluated in the current scope in order to produce a debug message, not as a key-value pair of metadata for the debug message. Not sure if there's some limitation on debug message expressions or values which should be imposed here.

**Comment by KristofferC** [comment] 2021-04-08 17:14
I agree with Jameson that the current behavior looks reasonable.

**Comment by vtjnash** [comment] 2021-04-08 17:59
@StefanKarpinski It is similar to doing this, which we don't impose a limitation on either: 
```
julia> (f = sin)(3)
0.1411200080598672

julia> f
sin (generic function with 13 methods)
```

**Comment by StefanKarpinski** [comment] 2021-04-27 20:18
Yeah, so closing as not a bug then.

**Closed by StefanKarpinski** 2021-04-27 20:18 UTC
Labels: logging

**Comment by c42f** [comment] 2021-04-28 02:58
I could go either way on this.

The current behavior isn't exactly buggy, but it seems like a bit of a footgun for the enabled-ness of logging statements to affect the values of local variables. Generally, I think that enabling logging should only have one very specific kind of side effect (producing log statements).

Perhaps we should just wrap the code emitted by `@debug` and friends in a `let`?

**Comment by StefanKarpinski** [comment] 2021-04-28 15:48
That just makes the "bug" harder to trigger: if there's no outer local binding for `x` then you won't see it affected here, but if there is one (as in the original post here), then you will see it affected. If there's going to be some limitation here, it seems like it should be that the log message expression out to produce a string of some kind.

**Comment by c42f** [comment] 2021-05-14 05:36
Hm yes, it would require analyzing the code to determine which variables are assigned. Seems complicated and potentially surprising in its own way.
