### ISSUE TITLE
Should `?` not be allowed as an identifier name?

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#19061] opened 2016-10-22 07:35 UTC
Given its role in ternary expressions (and perhaps in more upcoming syntactic constructs?), isn't letting `?` be used as a variable name allowing too much room for potential confusion?

```
julia>  ? = true
true

julia>  ??!?:?
false

julia>  !??!?:!??!?:?
true

julia>  !???:!?:?
false:true

julia> (x->(?->?(?))(?->x(x->?(?)(x))))(x->(?->(?==0?1:(?*x(?-1))))).(?:?<<?<<?)
4-element Array{Int64,1}:
  1
  2
  6
 24
```

(also isn't it amazing that these even parse?) Anyway, I suppose, unless one really wants to use `?` as a function or macro name, that this possibility could be deprecated?

**Comment by tkelman** [comment] 2016-10-22 10:30
Duplicate of https://github.com/JuliaLang/julia/issues/6286 ? Now that `@unix?` macros are deprecated we can hopefully tweak the parsing here now.

**Closed** 2016-10-22 12:29 UTC
Labels: parser

**Comment by andyferris** [comment] 2016-10-22 13:01
Haha I discovered this recently and kind of trolled myself by creating [this](https://gist.github.com/andyferris/b1bd9d4f251e00bc3639d4ae47868e41) (an attempt originally inspired by trying to have a more *Swift*-like syntax for nullables).

Do you think `?` could parse successfully as a prefix unary operator without screwing with the ternary?

**Comment by nalimilan** [comment] 2016-10-22 16:04
Note that in Swift and C#, the `?` denoting nullable/optional is a suffix.
