### ISSUE TITLE
Core.Compiler.UnitRange BoundsError

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#27593] opened 2018-06-15 13:23 UTC
Package commit: https://github.com/JuliaData/Parsers.jl/commit/c3cc3d0f2a4a59c7183597310641a8bdd56ca8d8
Code to reproduce:
```julia
r = Parsers.xparse(IOBuffer("0e+01234567890123456789"), Float64)
```

Backtrace:
```julia
julia> r = Parsers.xparse(IOBuffer("0e+01234567890123456789"), Float64)
Internal error: encountered unexpected error in runtime:
BoundsError(a=Core.Compiler.UnitRange{Int64}(start=1, stop=228), i=0)
rec_backtrace at /Users/jacobquinn/julia/src/stackwalk.c:94
record_backtrace at /Users/jacobquinn/julia/src/task.c:246 [inlined]
jl_throw at /Users/jacobquinn/julia/src/task.c:577
throw_boundserror at ./abstractarray.jl:483
getindex at ./range.jl:473
jfptr_getindex_2684 at /Users/jacobquinn/julia/usr/lib/julia/sys.dylib (unknown line)
#328 at ./compiler/ssair/inlining2.jl:154
map! at ./abstractarray.jl:1958
cfg_inline_item! at ./compiler/ssair/inlining2.jl:153
cfg_inline_item! at ./compiler/ssair/inlining2.jl:100 [inlined]
batch_inline! at ./compiler/ssair/inlining2.jl:466
ssa_inlining_pass! at ./compiler/ssair/inlining2.jl:57 [inlined]
run_passes at ./compiler/ssair/driver.jl:168
optimize at ./compiler/optimize.jl:183
typeinf at ./compiler/typeinfer.jl:436
typeinf_edge at ./compiler/typeinfer.jl:137
abstract_call_method at ./compiler/abstractinterpretation.jl:303
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:78
abstract_call at ./compiler/abstractinterpretation.jl:712
abstract_eval_call at ./compiler/abstractinterpretation.jl:741
abstract_eval at ./compiler/abstractinterpretation.jl:813
abstract_interpret at ./compiler/abstractinterpretation.jl:931
typeinf_work at ./compiler/typeinfer.jl:273
typeinf at ./compiler/typeinfer.jl:407
typeinf_frame at ./compiler/typeinfer.jl:96 [inlined]
typeinf_code at ./compiler/typeinfer.jl:191
typeinf_ext at ./compiler/typeinfer.jl:233
jfptr_typeinf_ext_12 at /Users/jacobquinn/julia/usr/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/jacobquinn/julia/src/./julia.h:1540 [inlined]
jl_apply_with_saved_exception_state at /Users/jacobquinn/julia/src/rtutils.c:257
jl_type_infer at /Users/jacobquinn/julia/src/gf.c:274
jl_compile_method_internal at /Users/jacobquinn/julia/src/gf.c:1778
jl_fptr_trampoline at /Users/jacobquinn/julia/src/gf.c:1822
do_call at /Users/jacobquinn/julia/src/interpreter.c:324
eval_body at /Users/jacobquinn/julia/src/interpreter.c:559
jl_interpret_toplevel_thunk_callback at /Users/jacobquinn/julia/src/interpreter.c:798
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x11fb87a8f)
unknown function (ip: 0x1)
jl_interpret_toplevel_thunk at /Users/jacobquinn/julia/src/interpreter.c:807
jl_toplevel_eval_flex at /Users/jacobquinn/julia/src/toplevel.c:856
jl_toplevel_eval_in at /Users/jacobquinn/julia/src/builtins.c:631
eval at ./boot.jl:316
eval_user_input at /Users/jacobquinn/julia/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:85
macro expansion at /Users/jacobquinn/julia/usr/share/julia/stdlib/v0.7/REPL/src/REPL.jl:116 [inlined]
#28 at ./task.jl:254
jl_fptr_trampoline at /Users/jacobquinn/julia/src/gf.c:1823
jl_apply at /Users/jacobquinn/julia/src/./julia.h:1540 [inlined]
start_task at /Users/jacobquinn/julia/src/task.c:268
```

Version: Version 0.7.0-alpha.0

cc: @Keno @vtjnash

**Comment by martinholters** [comment] 2018-06-15 13:38
Duplicate of #27456

**Closed by martinholters** 2018-06-15 13:38 UTC
