### ISSUE TITLE
`begin`/`end` wrong with `CartesianIndices`

### ISSUE THREAD

**Issue by chriselrod** [JuliaLang/julia#40601] opened 2021-04-25 02:16 UTC
Following this LoopVectorization issue asking for `begin`/`end` support: https://github.com/JuliaSIMD/LoopVectorization.jl/issues/246

I was curious how Base Julia correctly handled `begin`/`end` with `CartesianIndex`.
```julia
julia> i = CartesianIndex((1,2))
CartesianIndex(1, 2)

julia> A = rand(6,5,4,3,2);

julia> A[i,begin,end,2]
ERROR: BoundsError: attempt to access 6×5×4×3×2 Array{Float64, 5} at index [1, 2, 1, 4, 2]
Stacktrace:
 [1] getindex
   @ ./array.jl:834 [inlined]
 [2] getindex(::Array{Float64, 5}, ::CartesianIndex{2}, ::Int64, ::Int64, ::Int64)
   @ Base ./multidimensional.jl:638
 [3] top-level scope
   @ REPL[17]:1

julia> A[i,begin,begin,begin]
0.5712471105637651

julia> A[i,begin,begin,end]
ERROR: BoundsError: attempt to access 6×5×4×3×2 Array{Float64, 5} at index [1, 2, 1, 1, 3]
Stacktrace:
 [1] getindex
   @ ./array.jl:834 [inlined]
 [2] getindex(::Array{Float64, 5}, ::CartesianIndex{2}, ::Int64, ::Int64, ::Int64)
   @ Base ./multidimensional.jl:638
 [3] top-level scope
   @ REPL[19]:1
```
The `Meta.@lower`, shown separately because it messes up highlighting of all downstream code (edit: edited it to close the opening "`"):
```julia
julia> Meta.@lower A[i,begin,end,2]
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = Base.firstindex(A, 2)
│   %2 = Base.lastindex(A, 3)
│   %3 = Base.getindex(A, i, %1, %2, 2)
└──      return %3
))))
```
`begin`/`end` is syntax based, so the second index -> `firstindex(A,2)`/`lastindex(A,2)`, without considering that the first index could be of varying dimension.

**Comment by simeonschaub** [comment] 2021-04-25 07:44
Duplicate of #35681

**Closed by simeonschaub** 2021-04-25 07:44 UTC
