### ISSUE TITLE
TTFP regression since 1.7

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#44293] opened 2022-02-21 14:35 UTC
I discovered a 25% regression in compilation time from 1.7.2 to master (0b48b91c9) when running a workflow for some work code. My work code is really hard to boil down to a MWE because it makes use of packages from a local registry, reference data sets, and operates on specific files in a workflow.

But at least some of the regression is due to a regression in Plots.jl.

The following code:
```julia
@time begin
    using Plots
    Plots.savefig(plot([1,2,3,4], [1,2,3,4]), "path.pdf")
end
```
Has the following timings:
* 1.7.2: 10.7 seconds
* Master: 14.3 seconds

But wait, Plots.jl makes use of `Base.Experimental.@max_methods`, which is only available in 1.8. What happens if we simply comment that out?
* Master (with default `max_methods`): 19.5 seconds.

**Comment by KristofferC** [comment] 2022-02-21 14:43
Looks like https://github.com/JuliaPlots/Plots.jl/issues/4079.

**Comment by aviatesk** [comment] 2022-02-21 14:43
Maybe is this a duplicate of https://github.com/JuliaLang/julia/issues/43157#issuecomment-1022171386?

**Comment by timholy** [comment] 2022-02-22 11:57
If you launch Julia with `--compiled-modules=no` you get 54.6s on 1.7 and 44.5s on 1.8. Because of lines like [this](https://github.com/JuliaPlots/Plots.jl/blob/e31d05682006b05eafd6be8ed25d449c4ef224c7/deps/SnoopCompile/precompile/1.7/precompile_Plots.jl#L68), that may be a reasonably-fair comparison. And of course that's not even including #43990.

**Comment by jakobnissen** [comment] 2022-02-22 12:39
Does that mean it's nearly certainly not a true regression, but instead, as Kristoffer said, due to Plots not precompiling on master? If so, this issue can happily be closed

**Closed** 2022-02-22 12:52 UTC
