### ISSUE TITLE
Full crash of Julia

### ISSUE THREAD

**Issue by PaulDebus** [JuliaLang/julia#37003] opened 2020-08-11 14:20 UTC
Hello,

so I found a hard crash of Julia from a small piece of code

```julia
using Random
a = reshape(shuffle(0:15), 4, 4)
b = reshape(transpose(a), 1, :)
circshift(b, -1))
```
And the resulting crash "report" is:
```
Illegal inttoptr
	  %uglygep88 = ptrtoint i8 addrspace(13)* %uglygep to i64
Illegal inttoptr
	  %scevgep8990 = ptrtoint i64 addrspace(13)* %scevgep89 to i64
Illegal inttoptr
	  %215 = inttoptr i64 %214 to i8 addrspace(13)*
Illegal inttoptr
	  %umax9192 = inttoptr i64 %umax91 to i64 addrspace(13)*

signal (6): Aborted
in expression starting at /home/paul/test.jl:4
gsignal at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f98b857fd04)
_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-8.so.1 (unknown line)
_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-8.so.1 (unknown line)
_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE at /usr/bin/../lib/x86_64-linux-gnu/libLLVM-8.so.1 (unknown line)
unknown function (ip: 0x7f98b8669ac1)
unknown function (ip: 0x7f98b866c2d8)
unknown function (ip: 0x7f98b866c8cd)
unknown function (ip: 0x7f98b85a7b4a)
unknown function (ip: 0x7f98b85d9082)
unknown function (ip: 0x7f98b85fe84b)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
unknown function (ip: 0x7f98b861175b)
unknown function (ip: 0x7f98b8611389)
unknown function (ip: 0x7f98b86118f0)
unknown function (ip: 0x7f98b86129c8)
unknown function (ip: 0x7f98b8613616)
unknown function (ip: 0x7f98b862be08)
unknown function (ip: 0x7f98b8607105)
jl_load at /usr/bin/../lib/x86_64-linux-gnu/libjulia.so.1 (unknown line)
include at ./Base.jl:377
exec_options at ./client.jl:288
_start at ./client.jl:484
jfptr__start_2075.clone_1 at /usr/lib/x86_64-linux-gnu/julia/sys.so (unknown line)
unknown function (ip: 0x5585861d29d9)
unknown function (ip: 0x5585861d25a6)
__libc_start_main at /usr/bin/../lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x5585861d264d)
Allocations: 2505 (Pool: 2493; Big: 12); GC: 0
Aborted (core dumped)
```

`versioninfo` is:
```
Julia Version 1.4.1
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

Please let me know if I can help in any way!

**Comment by masuday** [comment] 2020-08-11 14:29
I can't reproduce it in 1.4.0 (Linux), 1.4.1 (Windows) and 1.5.0 (Windows & Linux).

**Comment by affans** [comment] 2020-08-11 14:35
Also can not reproduce on 1.4.0
```
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, broadwell)
```
You do have an extra closing parenthesis in `circshift(b, -1))` is this just a typo?

You may also try to use the julia `rr`  tool

**Comment by PaulDebus** [comment] 2020-08-11 14:40
> Also can not reproduce on 1.4.0
> 
> ```
> julia> versioninfo()
> Julia Version 1.4.0
> Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
> Platform Info:
>   OS: Linux (x86_64-pc-linux-gnu)
>   CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-8.0.1 (ORCJIT, broadwell)
> ```
> 
Hm... I checked on a different machine with the same Linux install but different hardware and I could reproduce it.

> You do have an extra closing parenthesis in `circshift(b, -1))` is this just a typo?
> 
Yep, that's a typo 
> You may also try to use the julia `rr` tool
Yes, I am going to try that. Only need to install Julia 1.5

**Comment by PaulDebus** [comment] 2020-08-11 14:47
So I tried with a fresh 1.5 installation and cannot reproduce the problem either. So I cannot use the `rr` tool. If nobody else can reproduce that, I maybe have to talk to the package maintainer of Ubuntu/Pop OS

**Comment by thofma** [comment] 2020-08-11 15:00
This does not look like the official julia binary. Can you reproduce with the official binary from https://julialang.org/downloads/oldreleases/?

**Comment by PaulDebus** [comment] 2020-08-11 15:03
They are installed via the package manager. It should be this package: https://packages.ubuntu.com/focal/julia

**Comment by KristofferC** [comment] 2020-08-11 15:04
Report it to the distribution then. The official way to use Julia is by using the binaries at https://julialang.org/downloads/

**Closed by KristofferC** 2020-08-11 15:04 UTC

**Comment by mbauman** [comment] 2020-08-11 15:25
Specifically, this is happening because they're using a shared system LLVM.  Julia uses LLVM very heavily and requires carrying forward patches for nearly every LLVM release:

https://github.com/JuliaLang/julia/tree/release-1.4/deps/patches

Without these patches, Julia will fail tests and generally be buggy.

**Comment by PaulDebus** [comment] 2020-08-11 15:34
> Specifically, this is happening because they're using a shared system LLVM. Julia uses LLVM very heavily and requires carrying forward patches for nearly every LLVM release:
> 
> https://github.com/JuliaLang/julia/tree/release-1.4/deps/patches
> 
> Without these patches, Julia will fail tests and generally be buggy.

Good to know, thank you! And sorry for the noise

**Comment by StefanKarpinski** [comment] 2020-08-11 21:16
No problem. But please do report it to Ubuntu! The distros are very reluctant to allow Julia to use its own LLVM, which leads to almost every distro version of Julia being broken. The more people make noise to them about this, the more likely they are to actually do something about it and build Julia with its own patched LLVM.
