### ISSUE TITLE
Upgrade to LLVM 3.9

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#19123] opened 2016-10-26 23:14 UTC
Related but closed: #18863. What's the status of this?

**Comment by vchuravy** [comment] 2016-10-27 00:03
#19054 had the important bits and pieces of #18863 and from what I can tell we need:
[ ] Patch `llvm-3.8.0_threads` for 3.9
[ ] Patch `llvm-win64-reloc-dwarf` for 3.9
[ ] CMake >= 3.4.3 on Travis
[ ] Update buildbots
[ ] Homebrew tap

**Comment by tkelman** [comment] 2016-10-27 00:22
- [ ] make sure tests pass everywhere
- [ ] update appveyor binaries

**Comment by tkelman** [comment] 2016-10-27 16:17
Note that the threads patch was initially borrowed from rust (who have the same toolchain C++11 threads issue we do with mingw), so we should check if they have a rebased version we could use to save ourselves a bit of time there.

**Comment by vchuravy** [comment] 2016-10-28 06:43
Something else I just noticed is that the Intel Compiler 2016_update2 is not able to build llvm. See https://sft.its.cern.ch/jira/browse/ROOT-8233 and even when applying that patch I his a segmentation fault on startup in llvm (haven't had time to investigate that further). The first problem should be solved with the latest update, but I haven't gotten my hands on it yet.

**Comment by tkelman** [comment] 2016-10-28 07:17
Looks like that's icc's bug, but llvm continues to do an incredible job of finding new ways to break every other compiler...

**Comment by ihnorton** [comment] 2016-10-28 16:48
> Note that the threads patch was initially borrowed from rust (who have the same toolchain C++11 threads issue we do with mingw)

Worth keeping an eye on: https://github.com/lhmouse/mcfgthread

There was some [discussion on the gcc list in April](https://gcc.gnu.org/ml/gcc/2016-06/msg00062.html), but I don't see any response or recent activity, so it is unclear if/when it might go in to mainline. There is some further discussion/development on [mingw-w64-public(https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/6ce22d7b.252f6d.15599d7f5cd.Coremail.lh_mouse%40126.com/#msg35189137).

lhmouse does have a forked toolchain build [here](https://www.lhmouse.com/gcc-mcf/).

(related: https://github.com/meganz/mingw-std-threads -- header-only, but does not implement `call_once` `std::async`, and a handful of other things. `call_once` was the only issue I encountered when I tried building LLVM against it a while back)

**Comment by tkelman** [comment] 2016-10-28 17:00
Yes, though unless that somehow gets backported to gcc 4, we'll need to worry about https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77333... or come up with a proper fix to gmp's build system so it works with clang on windows and start using that (ref https://github.com/JuliaLang/julia/pull/15488 which doesn't work in cross-compile).

**Comment by Keno** [comment] 2016-10-28 20:50
Another issue we'll start seeing is that LLVM symbols conflict with graphics drivers on Linux distributions that have (stupidly) chosen to dynamically link LLVM into their graphics drivers. I have a patch (https://reviews.llvm.org/D13330) that adds capabilities to clang, to avoid generating the problematic symbols, but I doubt similar capabilities will make it into gcc anytime soon.

**Comment by kpamnany** [comment] 2016-11-02 17:50
Does this work at all on Linux? Need LLVM 3.9 to start testing Julia performance on KNL.

**Comment by yuyichao** [comment] 2016-11-02 17:59
Stock/patched LLVM 3.9.0 should work with no problem on x86/x64 linux.

**Comment by andreasnoack** [comment] 2016-11-02 18:00
@kpamnany I had to use LLVM-svn on KNL but it worked fine (~a month ago.)

**Comment by yuyichao** [comment] 2016-11-02 18:08
@kpamnany Apply https://reviews.llvm.org/D26123 or a commit before https://reviews.llvm.org/rL285426 if you want a llvm-svn build without assertion enabled.

**Comment by StefanKarpinski** [comment] 2016-11-11 19:55
Bump. What's the status here?

**Comment by tkelman** [comment] 2016-11-12 00:49
https://github.com/JuliaLang/julia/pull/19138 can be merged, but bootstrap crashes on both win32 and win64 last time I tried with 3.9.

**Comment by StefanKarpinski** [comment] 2016-11-12 01:49
What's necessary to get this not to crash?

**Comment by ViralBShah** [comment] 2016-11-12 11:40
@keno is necessary, perhaps?

**Comment by vchuravy** [comment] 2016-12-05 06:37
With #19138 both Win32 and Win64 build successfully and with #19493 my local Win64 builds passes all tests.

I didn't have much time to look into the Win32 build, but I am seeing a failure in the threading tests for `a = Atomic{Int64}(); a[] = 1`.

**Comment by tkelman** [comment] 2016-12-15 01:18
@vchuravy that's what https://reviews.llvm.org/D27653 is intended to address, right?

**Comment by yuyichao** [comment] 2016-12-15 01:44
Yes. But I don't think that's the right solution. I think the long term solution is to make sure we can find `libatomic` on windows (which can possibly be MSVC compatible once MSVC supports it if gcc devs does the right thing) and the simplest short term solution is to remove szclass 12 on 32bit.

**Comment by tkelman** [comment] 2016-12-15 02:11
> remove szclass 12 on 32bit

What effect would that have? Things are working without requiring libatomic on llvn 3.7. There actually is no toolchain option that can build llvm 3.7 correctly on win32 and includes libatomic as far as I'm aware.

**Comment by yuyichao** [comment] 2016-12-15 02:20
> What effect would that have?

Larger memory consumption.

> Things are working without requiring libatomic on llvn 3.7

Due to a LLVM bug.

**Comment by tkelman** [comment] 2016-12-15 02:26
What other consequences does the llvm bug have? A memory regression on 32 bit might be fine if it's not too large. Can we avoid libatomic or do we need to fix gcc 5+ (or libgmp's build system) to be able to have a toolchain that can build both llvm 3.9 and release-0.5 julia?

**Comment by yuyichao** [comment] 2016-12-15 02:35
> What other consequences does the llvm bug have?

The instructions it generates violates the platform ABI, which shouldn't cause too much issue due to our limited use of it currently.

> Can we avoid libatomic

That's why I mentioned a short term solution? Or are you talking about something else?

**Comment by tkelman** [comment] 2016-12-15 02:53
crossing threads in my head here, sorry. what needs patching to remove szclass 12?

**Comment by yuyichao** [comment] 2016-12-15 03:04
https://github.com/JuliaLang/julia/pull/17598/commits/1857f075713ac14948ee28ae2bc79abbfba90003 Apart from the `MAX_ALIGN` part. It's quite easy to do if we decide that we need a short term solution (i.e. if we cannot get libatomic to work before we want to use llvm39 on windows).

**Comment by tkelman** [comment] 2016-12-16 02:00
So modifying the ifdef conditionals there to also include win32? What about i686 linux? Not sure whether llvm 3.9 has been tested there yet but we have buildbots that run tests there.

I can test this if anyone can propose the right patch; so could anyone else who has a win32 source build handy but I'm guessing there aren't that many aside from me.

**Comment by yuyichao** [comment] 2016-12-16 02:26
> So modifying the ifdef conditionals there to also include win32

Yes.

> What about i686 linux

I suspect this is less useful than win32 so may as well include it as well if we are going to change it on win32.

> Not sure whether llvm 3.9 has been tested there yet

I've tested it and the tests should all pass.

> I can test this if anyone can propose the right patch

If we decide to do this I'll write the patch. Or maybe we can test it first anyway?

**Comment by vchuravy** [comment] 2016-12-16 09:34
From my point of view removing `szclass 12` on 32bit (both Linux and Windows) is the right thing to do for now and once we can upgrade GCC we can revisit this.

I can test this over the weekend.

**Comment by vchuravy** [comment] 2016-12-19 18:48
#19647 implements @yuyichao suggestion and I tested it on 32bit linux and windows (via wine)

**Comment by tkelman** [comment] 2016-12-20 07:28
Tests pass for me with 3.9.0. We're in that annoying period where LLVM has tagged 3.9.1 but not released source tarballs, so maybe we should make our own again temporarily (if someone does this, may as well try to be consistent with how llvm makes their source releases look, in terms of a `.src` or whatever naming convention they use inside the tarball).

Someone will need to submit an llvm39-julia homebrew formula to the homebrew-julia tap, may as well make it 3.9.1 plus all our patches for consistency with how source builds will look.

**Comment by ViralBShah** [comment] 2016-12-27 06:12
Noting the homebrew tap for llvm39 PR here: https://github.com/staticfloat/homebrew-julia/pull/229

@vchuravy It seems that all the items in your list above are carried out. Can you checkmark them all if appropriate?

**Comment by ViralBShah** [comment] 2016-12-27 06:14
Should we close this one and focus on #19678 ?

**Comment by tkelman** [comment] 2016-12-27 06:22
#19678 will close this when merged.

**Comment by ViralBShah** [comment] 2016-12-27 06:47
Ah I missed that #19768 was a PR. Sorry about the noise.

**Closed** 2016-12-29 18:27 UTC
