### ISSUE TITLE
Base.runtests() for 0.4.1 fails

### ISSUE THREAD

**Issue by JeremyCavanagh** [JuliaLang/julia#13967] opened 2015-11-13 09:08 UTC
I've just had julia updated from 0.4.0 to 0.4.1 via homebrew and ran the tests just to check before getting too excited and I have attached the test output.

I am using a MacBook Air running OS X 10.9.5

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir4,1
  Processor Name:	Intel Core i7
  Processor Speed:	1.8 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	4 GB
  Boot ROM Version:	MBA41.0077.B12
  SMC Version (system):	1.74f4

[julia0.4.1-test-output.txt](https://github.com/JuliaLang/julia/files/33762/julia0.4.1-test-output.txt)

**Comment by tkelman** [comment] 2015-11-13 10:23
Issues that occur with the homebrew build but not the dmg binaries or a source build should generally be reported at https://github.com/staticfloat/homebrew-julia. You're missing libgfortran, try reinstalling brew's gcc.

**Comment by tkelman** [comment] 2015-11-14 07:35
closing as a duplicate of https://github.com/staticfloat/homebrew-julia/issues/191

**Closed by tkelman** 2015-11-14 07:35 UTC
Labels: mac
