### ISSUE TITLE
Feature request: `dims` keyword for `norm`

### ISSUE THREAD

**Issue by wesselb** [JuliaLang/julia#40058] opened 2021-03-16 08:08 UTC
In some cases, it would be really handy to be able to do this:

```julia
julia> a = randn(5, 100);

julia> norm(a, dims=1)  # Doesn't work
ERROR: MethodError: no method matching norm(::Matrix{Float64}; dims=2)

julia> sqrt.(sum(abs2, a, dims=1))  # Intended result (in this case, with `p=2`)
1×100 Matrix{Float64}:
 1.26534  0.763155  2.55044  2.38645  1.69696  …  1.71206  2.61463  2.81637  1.82003  1.69302
```

As a more advanced example, for a tensor `a` of shape `(m, n, k)`, `norm(a, dims=(2, 3))` would compute `norm(a[i, :, :])` for all `i` and return something of shape `(m, 1, 1)`.

**Comment by martinholters** [comment] 2021-07-20 12:11
```julia
julia> mapslices(norm, a; dims=1)
1×100 Matrix{Float64}:
 1.89751  3.06913  2.61767  3.51301  …  1.91144  0.557424  1.73838
```
Or `mapslices(norm, a; dims=(2,3))` for the second case.

Not sure we need to add this to `norm` directly?

**Comment by mcabbott** [comment] 2021-11-23 14:51
One reason would be performance:
```
julia> @btime mapslices(norm, $a; dims=1)
  min 25.375 μs, mean 28.602 μs (838 allocations, 22.94 KiB. GC mean 8.56%)

julia> @btime map(norm, eachcol($a))'
  min 795.500 ns, mean 901.633 ns (1 allocation, 896 bytes. GC mean 6.85%)

julia> sqrt!(x) = x .= sqrt.(x);

julia> @btime sqrt!(sum(abs2, $a, dims=1))
  min 258.864 ns, mean 349.105 ns (1 allocation, 896 bytes. GC mean 18.51%)
```
Although `norm` has many variants so there would be quite a bit of complication involved.

**Comment by mcabbott** [comment] 2021-12-13 02:25
Duplicate of #34830, BTW.

**Closed** 2021-12-13 13:54 UTC
