### ISSUE TITLE
Long backtraces sometimes fail on windows

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#51524] opened 2023-09-30 13:36 UTC
I'm not sure what's going on, but here's what I belileve is a MWE

```julia
# issue #28442
@testset "Long stacktrace printing" begin
    f28442(c) = g28442(c + 1)
    g28442(c) = c > 10000 ? (return backtrace()) : f28442(c+1)
    bt = f28442(1)
    io = IOBuffer()
    Base.show_backtrace(io, bt)
    output = split(String(take!(io)), '\n')
    @test lstrip(output[3])[1:3] == "[1]"
    @test occursin("g28442", output[3])
    @test lstrip(output[5])[1:3] == "[2]"
    @test occursin("f28442", output[5])
    @test occursin("the above 2 lines are repeated 5000 more times", output[7])
    @test lstrip(output[8])[1:7] == "[10003]"
end
```

From https://github.com/JuliaLang/julia/blob/d988f8fc1c9378ee1ae940714da167aa1d6e5a7e/test/errorshow.jl#L715C1-L729C4

This failed in CI several times recently

https://buildkite.com/julialang/julia-master/builds/28109#018ad1c1-e3d1-43cb-bde4-902204d183bf/768-1003
https://buildkite.com/julialang/julia-master/builds/28108#018ad1be-83e7-4e1a-98bf-9354bd1dafd7/778-1018
https://buildkite.com/julialang/julia-master/builds/28093#018ad03b-da9f-45cd-aa05-47b5f15a0d20/768-1008
https://buildkite.com/julialang/julia-master/builds/28075#018acc90-4a5e-4dd7-b241-cd8c14753824/778-1019
https://buildkite.com/julialang/julia-master/builds/28231#018ae4d5-27cc-4c4b-baf4-3abf2e1c383b/766-1082

Example failure

```
errorshow                                        (11) \|         failed at 2023-09-26T15:08:12.254
--
  | Error During Test at /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:725
  | Test threw exception
  | Expression: (lstrip(output[5]))[1:3] == "[2]"
  | BoundsError: attempt to access 4-element Vector{SubString{String}} at index [5]
  | Stacktrace:
  | [1] getindex(A::Vector{SubString{String}}, i1::Int64)
  | @ Base ./essentials.jl:13
  | [2] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:676 [inlined]
  | [3] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:725 [inlined]
  | [4] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:1599 [inlined]
  | [5] top-level scope
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:717
  | Error During Test at /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:726
  | Test threw exception
  | Expression: occursin("f28442", output[5])
  | BoundsError: attempt to access 4-element Vector{SubString{String}} at index [5]
  | Stacktrace:
  | [1] getindex(A::Vector{SubString{String}}, i1::Int64)
  | @ Base ./essentials.jl:13
  | [2] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:676 [inlined]
  | [3] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:726 [inlined]
  | [4] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:1599 [inlined]
  | [5] top-level scope
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:717
  | Error During Test at /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:727
  | Test threw exception
  | Expression: occursin("the above 2 lines are repeated 5000 more times", output[7])
  | BoundsError: attempt to access 4-element Vector{SubString{String}} at index [7]
  | Stacktrace:
  | [1] getindex(A::Vector{SubString{String}}, i1::Int64)
  | @ Base ./essentials.jl:13
  | [2] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:676 [inlined]
  | [3] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:727 [inlined]
  | [4] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:1599 [inlined]
  | [5] top-level scope
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:717
  | Error During Test at /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:728
  | Test threw exception
  | Expression: (lstrip(output[8]))[1:7] == "[10003]"
  | BoundsError: attempt to access 4-element Vector{SubString{String}} at index [8]
  | Stacktrace:
  | [1] getindex(A::Vector{SubString{String}}, i1::Int64)
  | @ Base ./essentials.jl:13
  | [2] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:676 [inlined]
  | [3] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:728 [inlined]
  | [4] macro expansion
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/stdlib/v1.11/Test/src/Test.jl:1599 [inlined]
  | [5] top-level scope
  | @ /cache/build/default-amdci4-5/julialang/julia-master/julia-54bae4a8e0/share/julia/test/errorshow.jl:717
```

AFAICT this only fails on Linux.

I'm going to skip this test on Linux to make CI greener, but skipping the test will not mean that this issue is fixed.

**Comment by vtjnash** [comment] 2023-09-30 15:04
Duplicate of https://github.com/JuliaLang/julia/issues/51465

**Closed by vtjnash** 2023-09-30 15:04 UTC
Labels: bug, regression
