### ISSUE TITLE
Incorrect lowered code when both chaining and broadcasting are involved with anonymous functions

### ISSUE THREAD

**Issue by pranshumalik14** [JuliaLang/julia#38884] opened 2020-12-15 01:35 UTC
There is a weird compile behaviour that should not happen. Consider the function:
```julia
@inline function num_unique(group_str::AbstractString)
    return group_str |> Set |> length
end
```
That is used in a super function (with two variants and their output and lowered code). Variant 1:
```julia
function sum_unique1(group_strs::Vector{<:AbstractString})
    # clump groups to one line before adding to set (removes the need for union)
    f = x -> replace(x, "\n" => "")
    return group_strs .|> f .|> num_unique |> sum
end
```
Output of variant 1 with some string vector as input: 
```
sum_unique1(group_strs) = 6703
```
Lowered code for variant 1:
```julia
@code_lowered sum_unique1(["abaz\nasd", "ashds\ndshgs"])
CodeInfo(
1 ─      #23 = %new(Main.:(var"#23#24"))
│        f = #23
│   %3 = Base.broadcasted(Main.:|>, group_strs, f)
│   %4 = Base.broadcasted(Main.:|>, %3, Main.num_unique)
│   %5 = Base.materialize(%4)
│   %6 = %5 |> Main.sum
└──      return %6
)
```
Now the okay-looking variant 2:
```julia
function sum_unique2(group_strs::Vector{<:AbstractString})
    # clump groups to one line before adding to set (removes the need for union)
    return group_strs .|> x -> replace(x, "\n" => "") .|> num_unique |> sum
end
```
Output of variant 2:
```
sum_unique2(group_strs) = [3, 16, 22, 22, ...] # is the output array where sum(output array) = 6703
```
Lowered code of variant 2:
```julia
@code_lowered sum_unique2(["abaz\nasd", "ashds\ndshgs"])
CodeInfo(
1 ─      #27 = %new(Main.:(var"#27#28"))
│   %2 = #27
│   %3 = Base.broadcasted(Main.:|>, group_strs, %2)
│   %4 = Base.materialize(%3)
└──      return %4 # doesn't even call sum and just exits!
)
```
This lowered code can be reproduced for the following function:
```julia
function sum_unique(group_strs::Vector{<:AbstractString})
   return group_strs .|> (x -> replace(x, "\n" => "") .|> num_unique |> sum)
end
```
Lowered code which is identical to the above "flawed" variant `sum_unique2()`:
```julia
@code_lowered sum_unique(["abaz\nasd", "ashds\ndshgs"])
CodeInfo(
1 ─      #11 = %new(Main.:(var"#11#12"))
│   %2 = #11
│   %3 = Base.broadcasted(Main.:|>, group_strs, %2)
│   %4 = Base.materialize(%3)
└──      return %4
)
```
Therefore the `sum` here was hidden inside the anonymous function and the output didn't change because of summing over a scalar. Also, interestingly, this problem goes away if chaining is done inside broadcasted function `num_unique` like below:
```julia
@inline function num_unique(group_str::AbstractString)
    # clump groups to one line before adding to set (removes the need for union)
    return group_str |> x -> replace(x, "\n" => "") |> Set |> length
end
``` 
And just wrapping the anonymous function in parenthesis also does the trick (of solving this issue):
```julia
function sum_unique(group_strs::Vector{<:AbstractString})
    # clump groups to one line before adding to set (removes the need for union)
    return group_strs .|> (x -> replace(x, "\n" => "")) .|> num_unique |> sum
end
```
But these ways of getting around this problem essentially express the same code (or should!). It will be great if this can be investigated a bit more. I am very new to Julia, so I haven't been able to go deeper (yet).

My Julia version info is below:
```julia
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = "/snap/code/51/usr/share/code/code"
  JULIA_NUM_THREADS = 
```

**Comment by cmcaine** [comment] 2020-12-15 10:54
This annoys me, too. The issue is that `->` binds looser than `|>`, so the `|>` get caught in the anonymous function.

This happens without broadcasting, too, but you don't notice because it doesn't matter there:

```julia
julia> f(x) = x |> y -> y - 3 |> cos
f (generic function with 1 method)

julia> @code_lowered f(1)
CodeInfo(
1 ─      #1 = %new(Main.:(var"#1#2"))
│   %2 = #1
│   %3 = x |> %2
└──      return %3
)

# Because f(x) is parsed like this:
g(x) = x |> y -> ((y - 3) |> cos)

# Which is equivalent to this:
h(x) = cos(x - 3)

@assert f(1) == g(1) == h(1)
```

I think the solution is that `.|>` (and maybe `|>`) should bind looser than `->`. This would be a breaking change, tho.

**Comment by pranshumalik14** [comment] 2020-12-15 11:06
`->` signifies an anonymous function and `|>` and `. |>` pipe operations, so it makes sense for them to have looser binding. Not what sense it makes to have it otherwise and why changing it would be a breaking change

**Comment by cmcaine** [comment] 2020-12-15 11:10
I don't know off hand of any code in the wild that would be broken by this change (which is Julia's "breaking change" definition, normally), but it's easy to construct an example and I would be very surprised if this change didn't break a variety of scripts and maybe even some libraries.

Breaking example:

```jl
# A vector of vectors of vectors
vvv = [[rand(10) for _ in 1:5] for _ in 1:5]
vvv .|> vv -> vv .|> v -> v .- 1

# Parsed as:
vvv .|> (vv -> vv .|> (v -> v .- 1))

# Under new rules, parsed as
vvv .|> (vv -> vv) .|> (v -> v .- 1) # error
```

**Comment by cmcaine** [comment] 2020-12-15 11:11
And I agree, it makes more sense to me for `->` to bind tighter than `|>`, but it's happened now and I don't think it could be changed until Julia 2. There's probably even issues about this already.

**Comment by cmcaine** [comment] 2020-12-15 11:13
Yep. Duplicate of #38761.

**Comment by DhruvaSambrani** [comment] 2020-12-15 11:39
Bring discussion over to #38761 and close this issue?

**Closed** 2020-12-15 11:51 UTC
