### ISSUE TITLE
Typed comprehension with begin/end is illegal syntax

### ISSUE THREAD

**Issue by lgoettgens** [JuliaLang/julia#55750] opened 2024-09-12 12:18 UTC
I have condensed my way too complicated code snipped that fails parsing to the following:
```julia
julia> [3 for _ in 1:2]
2-element Vector{Int64}:
 3
 3

julia> Int[3 for _ in 1:2]
2-element Vector{Int64}:
 3
 3

julia> [begin 3 end for _ in 1:2]
2-element Vector{Int64}:
 3
 3

julia> Int[begin 3 end for _ in 1:2]
ERROR: ParseError:
# Error @ REPL[7]:1:13
Int[begin 3 end for _ in 1:2]
#           └ ── Expected `]`
Stacktrace:
 [1] top-level scope
   @ none:1
```

Having just the comprehension works as expected. Adding either the eltype or wrapping the inside of the generator with `begin/end` works fine as well. However, doing both at once raises a ParseError, that I don't expect here.

The error occurs (up to some formatting differences) in all versions I tried it (1.6.7, 1.10.5, 1.11.0-rc3, and 1.12.0-DEV.1186).

**Comment by simeonschaub** [comment] 2024-09-12 13:03
Duplicate of #41664

**Closed by simeonschaub** 2024-09-12 13:03 UTC
