### ISSUE TITLE
Inconsistent behaviour when reassigning the I operator in LinearAlgebra

### ISSUE THREAD

**Issue by ArturDoshchyn** [JuliaLang/julia#45655] opened 2022-06-12 12:56 UTC
I have noticed that after loading the LinearAlgebra package, Julia can behave differently, and can either:

1. Allow me to reassign the I operator to, say, scalar value 2. Please see the screenshot. 
![image](https://user-images.githubusercontent.com/107352842/173234092-fc3a40a4-8a34-4e51-a9b9-a201c9a7b98e.png)

2. Or complain that operator LinearAlgebra.I cannot be reassigned. Please see the screenshot.
![image](https://user-images.githubusercontent.com/107352842/173234014-b7e445e0-2949-49ee-935e-9a2a2cb8efc7.png)

I believe that #2 is the much more desirable behaviour, but either way this should be consistent. I was not able to determine under which specific circumstances Julia complains and does not reassign I. From the examples above, it seems that the complaint happens if I is used at least once in the code prior to attempting reassignment.

Thank you very much for your help.

Best Regards,
Artur

**Comment by Seelengrab** [comment] 2022-06-12 15:35
This is intended - `I` is not an operator, but a regular object from `LinearAlgebra`. Since julia is semantically a dynamic language, first uses of any object depend on what has happened before. In your first example, while `using LinearAlgebra` makes `I` available for use, if you assign something to that binding before it's resolved to the `I` of `LinearAlgebra`, your new object shadows the other one. The `I` from `LinearAlgebra` is still available via `LinearAlgebra.I`, but since you explicitly set `I = ...`, your own object takes precedence.

In your second example, you request/read `I` first, which causes julia to look up whether something is bound to that symbol. It ends up finding the binding exported by `LinearAlgebra`, making the assignment afterwards fail (since the reassignment would have to happen semantically in `LinearAlgebra`, not `Main` - irrespective of that is `LinearAlgebra.I` defined as a `const`, so you could only replace it by another `UniformScaling(true)` either way).

**Closed** 2022-06-12 15:42 UTC

**Comment by simeonschaub** [comment] 2022-06-12 15:44
In the future, please quote your code instead of attaching a screenshot since that makes issues much easier to reproduce

**Comment by ArturDoshchyn** [comment] 2022-06-12 17:15
@Seelengrab  -- thank you so much for the detailed explanation, it makes perfect sense. I posted this only after not being able to find an explanation online, but in the future I will try to be even more careful at checking whether any behaviour is intended or not before posting here.

@simeonschaub  -- yes, of course, will do, thank you.
