### ISSUE TITLE
[WONTFIX] `fill()` is a footgun

### ISSUE THREAD

**Issue by LebedevRI** [JuliaLang/julia#55158] opened 2024-07-17 20:56 UTC
I've spent last 3+ days trying to understand why my code, wasn't doing what i expected it to do,
Reduced from a much larger code (a JuMP model):
```
import Combinatorics

function foo()
    v1 = [1 => 3, 1 => 4, 2 => 3, 2 => 4]
    v2 = [Pair{String, String}[], [2 => 4, 1 => 3], Pair{String, String}[]]

    v3 = 10
    v4 = length(v2)
    
    v5 = fill(fill(false, (v3, v3)), v4)
    for k in 1:v4
        for connection in v1
            r = (connection in v2[k])
            for cidx in Combinatorics.permutations(connection)
                (v5[k])[cidx...] = r
            end
        end
        if k>=2
            @show(v5[2])
        end
    end
end

foo()
```
After a while, i've finally noticed that this would output:
```
v5[2] = Bool[0 0 1 0 0 0 0 0 0 0; 0 0 0 1 0 0 0 0 0 0; 1 0 0 0 0 0 0 0 0 0; 0 1 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0]
v5[2] = Bool[0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0; 0 0 0 0 0 0 0 0 0 0]
```
... which is, while is a documented behavior, is really surprising :/

**Comment by mbauman** [comment] 2024-07-17 21:05
Duplicate of #41209

**Closed by mbauman** 2024-07-17 21:05 UTC

**Comment by LebedevRI** [comment] 2024-07-17 21:12
@mbauman thank you!
