### ISSUE TITLE
[CI] Intermittent stacktrace test failure on macOS

### ISSUE THREAD

**Issue by giordano** [JuliaLang/julia#49152] opened 2023-03-25 18:02 UTC
[Example](https://buildkite.com/julialang/julia-master/builds/22278#01871615-a97d-406f-9bdb-a99ad319801f/532-1316)
```
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/julia-a922b5966c/share/julia/test/stacktraces.jl:168
  Expression: (bt[2]).line == 42
   Evaluated: 370 == 42

Error in testset stacktraces:
Test Failed at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-macmini-x64-4.0/build/default-macmini-x64-4-0/julialang/julia-master/julia-a922b5966c/share/julia/test/stacktraces.jl:169
  Expression: (bt[2]).file === :foo
   Evaluated: var"./boot.jl" === foo
```

**Comment by vtjnash** [comment] 2023-03-28 21:50
I have bad news and good news for you. The good news is that this appears to be fixed in lld. The bad news is that we appear to be triggering a bug in the system linker program ld64. In particular it requires that each object file must be produced by a unique input file. But when we trigger this error, we have consecutive object files with the same N_SO, which triggers the logic to not include the second one in the final image:
```
[ 46506] 00000001 64 (N_SO         ) 01     0000   0000000000000000
[ 46507] 000d73e5 64 (N_SO         ) 00     0000   0000000000000000 './compiler/'
[ 46508] 000d73f1 64 (N_SO         ) 00     0000   0000000000000000 'tfuncs.jl'
[ 46509] 000d73fb 66 (N_OSO        ) 03     0001   000000006423479e '/Users/jameson/julia/x-bc/text_opt1.o'
[ 46510] 00000001 2e (N_BNSYM      ) 01     0000   0000000000137210
```
```
[ 85911] 00000001 64 (N_SO         ) 01     0000   0000000000000000
[ 85912] 000d73e5 64 (N_SO         ) 00     0000   0000000000000000 './compiler/'
[ 85913] 000d73f1 64 (N_SO         ) 00     0000   0000000000000000 'tfuncs.jl'
[ 85914] 0012cd7f 66 (N_OSO        ) 03     0001   00000000642347a1 '/Users/jameson/julia/x-bc/text_opt2.o'
[ 85915] 00000001 2e (N_BNSYM      ) 01     0000   00000000003b37e0
```

https://github.com/apple-oss-distributions/ld64/blob/59a99ab60399c5e6c49e6945a9e1049c42b71135/src/ld/OutputFile.cpp#L7284-L7292

To fix this, we probably need to guarantee that the first `.file` directive emitted into the source file (or its equivalent in the object file) is a unique identifier (e.g. the `.o` file name), perhaps via module-level inline assembly?

**Comment by gbaraldi** [comment] 2023-03-28 22:18
What macos version are you using to check this? Maybe this is fixed on latest macos?

**Comment by vtjnash** [comment] 2023-03-29 01:29
The link to the line in the source code with the issue is only 14 days old. I don't think they would have noticed this since.

**Comment by vtjnash** [comment] 2023-03-29 01:34
Notably, it looks like someone at Apple did attempt to fix the issue 9 years ago, but did not

**Comment by gbaraldi** [comment] 2023-03-29 02:54
They usually take a little while to open source their code, but yeah I doubt it.

**Comment by giordano** [comment] 2023-03-29 09:32
Weirdly enough, I don't see the version of `ld64` in https://opensource.apple.com/releases/

**Comment by gbaraldi** [comment] 2023-03-29 09:35
The latest commit on Jameson's link is 710 or something like that

**Comment by vtjnash** [comment] 2023-03-29 12:07
It is distributed independently from the OS releases. https://github.com/apple-oss-distributions/distribution-Developer_Tools/tree/developer-tools-130

**Comment by vtjnash** [comment] 2023-03-29 14:21
I submitted rdar://FB12085255 to report the issue to Apple. But now to attempt a workaround hack for us in the meantime. Unless someone thinks we should drop support and only allow `ld64.lld` as a linker?

**Closed** 2023-03-29 21:16 UTC
Labels: mac, ci
