### ISSUE TITLE
for loop over undefined variable segfaults

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaLang/julia#15641] opened 2016-03-27 14:08 UTC
```Julia
julia> a # not necessary, just illustrating that there is no a!
ERROR: UndefVarError: a not defined
 in eval(::Module, ::Any) at ./boot.jl:267
# you might need to execute this multiple times
julia> for key in a
end

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
jl_egal at /home/centos/buildbot/slave/package_tarball64/build/src/builtins.c:305
lookup at ./stacktraces.jl:102
process_backtrace at ./replutil.jl:437
show_backtrace at ./replutil.jl:422
unknown function (ip: 0x7f10d95c12a0)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
show_backtrace at ./replutil.jl:413
showerror at ./replutil.jl:411
#3 at ./REPL.jl:101
unknown function (ip: 0x7f10d95953c3)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
with_output_color at ./util.jl:317
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
[inline] at ./char.jl:51
print_response at ./REPL.jl:128
unknown function (ip: 0x7f10d95c751e)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
print_response at ./REPL.jl:121
unknown function (ip: 0x7f10d95ca0ee)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
#18 at ./REPL.jl:626
unknown function (ip: 0x7f10d95d58bf)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
run_interface at ./LineEdit.jl:1604
unknown function (ip: 0x7f12db40cc20)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
run_frontend at ./REPL.jl:859
run_repl at ./REPL.jl:168
unknown function (ip: 0x7f12e0de6230)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
_start at ./client.jl:360
unknown function (ip: 0x7f12db43f972)
[inline] at /home/centos/buildbot/slave/package_tarball64/build/src/julia_internal.h:69
jl_call_method_internal at /home/centos/buildbot/slave/package_tarball64/build/src/gf.c:1863
unknown function (ip: 0x401c64)
unknown function (ip: 0x40181f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
Allocations: 1660030 (Pool: 1658444; Big: 1586); GC: 3
Segmentation fault (core dumped)
```
Can't reproduce it outside the REPL.

```Julia
julia> versioninfo()
Julia Version 0.5.0-dev+3177
Commit 2a3aada (2016-03-16 13:12 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by yuyichao** [comment] 2016-03-27 14:12
Hmm, Can't reproduce in a fresh REPL on linux `0.5.0-dev+3274`.

**Comment by SimonDanisch** [comment] 2016-03-27 14:14
huh me neither... I should update Julia before reporting bugs. Should I close this, or should it stay open to make sure, that it's really fixed?

**Comment by vtjnash** [comment] 2016-03-27 15:02
since that commit is after d6a69647b1fbb73b7f77132a39d6b428ee18f2a8 but before 70c6e3473808d06fae02de69947a517a80476479, i think it can be considered fixed now

**Closed by vtjnash** 2016-03-27 15:02 UTC

**Comment by SimonDanisch** [comment] 2016-03-27 15:03
great :)
