### ISSUE TITLE
`convert` for Periods is a pun?

### ISSUE THREAD

**Issue by TotalVerb** [JuliaLang/julia#16109] opened 2016-04-28 23:19 UTC
Currently, `convert` is used to extract the magnitude of a quantity, or alternatively to give units to a dimensionless quantity. This happens in the `Dates` code in `Base`, and the behaviour has inspired similar behaviour in SIUnits.jl and Unitful.jl.

In Base, `convert` is generally used to convert between values of different types, but with same meaning. Since 1 and 1 second do not represent the same quantity, the use of `convert` to switch between them is a pun. In addition, it can lead to surprising behaviour. Note:

```julia
julia> convert(Base.Dates.Second, 60) 
60 seconds

julia> convert(Base.Dates.Minute, ans)
1 minute

julia> convert(Int, ans)
1
```

So we have converted an Int back to itself, but the conversion was lossy!

**Comment by quinnj** [comment] 2016-04-28 23:35
Hmm.....I'm not sure I see the actual problem; I think we're safely within the general meaning of `convert` here. I'm also wondering what else you'd expect to see here? It's not immediately obvious what other path we would take.

**Comment by TotalVerb** [comment] 2016-04-28 23:53
The problem is that `convert` is currently dimensionally incorrect.

Here is some food for thought. If I had a type `Radians` that represented a quantity multiplied by 2π:

```julia
immutable Radians
    val::Float64
end

convert(::Type{Radians}, x::Float64) = ???
```
then what should `convert` do here? I would argue that the correct conversion is `Radians(x / 2π)`. This preserves the mathematical meaning of a Radian. Since radians are dimensionless, this conversion cannot lead to any trouble.

But the `Period` conversion is not based at all on the mathematical meaning of a `Period`, but rather based off the number of units of measure. If we generalized that to the `Radians` type, we would end up with the conversion `Radians(x)` instead.

Because these two different approaches lead to a different result, it would seem that they are actually two distinct operations, and `convert` is therefore currently a pun. The operation of putting units on things should perhaps be given a new name, and not as an additional method on `convert`?

**Comment by tkelman** [comment] 2016-04-29 02:02
related: #15394

**Comment by jiahao** [comment] 2016-04-29 02:49
Duplicate of #10451

**Comment by toivoh** [comment] 2016-04-29 04:57
I agree with @TotalVerb that we need to introduce a mechanism for conversions between incommensurable units that does not rely on `convert`.

One way might be to have a `measure` function such that e.g.

    measure(s, 5s) = 5
    measure(m, 4m/s) = 4/s

eg you specify a unit to be divided out from the quantity.

**Comment by nalimilan** [comment] 2016-04-29 10:22
So basically to be consistent `convert` should always return the number of seconds or milliseconds. This is what @ivarne suggested [in the other issue](https://github.com/JuliaLang/julia/issues/10451#issuecomment-77777969).

**Comment by jiahao** [comment] 2016-04-29 16:58
Closing as duplicate

**Closed by jiahao** 2016-04-29 16:58 UTC
Labels: dates
