### ISSUE TITLE
Illegal instruction  (core dumped)

### ISSUE THREAD

**Issue by billb2050** [JuliaLang/julia#29268] opened 2018-09-19 17:02 UTC
julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 2600X Six-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, znver1)

julia> 

I hesitate to report this without providing reproducible code. 
However, for what it's worth...without showing too much of my poor beginning Julia coding skills, The following snippet caused an "Illegal instruction (core dumped)" as can be seen below. It is reproducible within my code, however, so far I am unable to reproduce the error by recreating a smaller portion of the code. 

I CAN tell you the error was caused by my erroneously using the Python style of appending strings 
with a  '+', out of habit (as can be seen below), instead of a '*'. Using a '*' to append, eliminated the "Illegal instruction"! Perhaps it is related to my other similar bug report where a "try" block was involved?

Code snippet follows...

    while 1==1
        again="!"
        try	
            println("trying"+again) # '+' caused the dump!
            again=" again!"

... [more code here!]

            break
        finally
            break
        end

Bill@billb-MS-7B79 ~/Mystuff/Julia $ ./names_SQL.jl 
Records to create 50
Unreachable reached at 0x7f53b40d3ef7

signal (4): Illegal instruction
in expression starting at /home/bill/Mystuff/Julia/names_SQL.jl:135
top-level scope at /home/bill/Mystuff/Julia/names_SQL.jl:201 [inlined]
top-level scope at ./none:0
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1829
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:781
jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:838
jl_load at /buildworker/worker/package_linux64/build/src/toplevel.c:821
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
exec_options at ./client.jl:229
_start at ./client.jl:421
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2182
jl_apply at /buildworker/worker/package_linux64/build/ui/../src/julia.h:1536 [inlined]
true_main at /buildworker/worker/package_linux64/build/ui/repl.c:112
main at /buildworker/worker/package_linux64/build/ui/repl.c:233
__libc_start_main at /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
_start at /usr/bin/julia (unknown line)
Allocations: 11410492 (Pool: 11409296; Big: 1196); GC: 22
Illegal instruction (core dumped)
bill@billb-MS-7B79 ~/Mystuff/Julia $

**Comment by JeffBezanson** [comment] 2018-09-20 18:58
Thanks for the report, it's always appreciated. It would be great to have some way to reproduce this though, or it will be hard to fix.

**Comment by KristofferC** [comment] 2019-10-15 13:36
Closing since no way to repro.

**Closed by KristofferC** 2019-10-15 13:36 UTC
Labels: needs more info
