### ISSUE TITLE
Illegal instruction from `((_, _, x) -> x).(Int, Int, spzeros(3))`

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#30118] opened 2018-11-22 06:47 UTC
Checked with current master 36d0116774378368bccbd4e21af58861c30566f3:

```julia
julia> versioninfo()
Julia Version 1.1.0-DEV.705
Commit 36d0116 (2018-11-21 20:37 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)

julia> using SparseArrays

julia> ((_, x) -> x).(Int, spzeros(3))
3-element SparseVector{Float64,Int64} with 0 stored entries

julia> ((_, _, x) -> x).(Int, Int, spzeros(3))
Unreachable reached at 0x7fc3987e0990

signal (4): Illegal instruction
in expression starting at no file:0
copy at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/higherorderfns.jl:965 [inlined]
materialize at ./broadcast.jl:756
jl_fptr_trampoline at /home/takafumi/repos/watch/julia/src/gf.c:1854
jl_apply_generic at /home/takafumi/repos/watch/julia/src/gf.c:2209
do_call at /home/takafumi/repos/watch/julia/src/interpreter.c:323
eval_value at /home/takafumi/repos/watch/julia/src/interpreter.c:411
eval_stmt_value at /home/takafumi/repos/watch/julia/src/interpreter.c:362 [inlined]
eval_body at /home/takafumi/repos/watch/julia/src/interpreter.c:759
jl_interpret_toplevel_thunk_callback at /home/takafumi/repos/watch/julia/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fc3a96b154f)
unknown function (ip: 0x8)
jl_interpret_toplevel_thunk at /home/takafumi/repos/watch/julia/src/interpreter.c:894
jl_toplevel_eval_flex at /home/takafumi/repos/watch/julia/src/toplevel.c:764
jl_toplevel_eval_in at /home/takafumi/repos/watch/julia/src/toplevel.c:793
eval at ./boot.jl:319
jl_apply_generic at /home/takafumi/repos/watch/julia/src/gf.c:2209
eval_user_input at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#26 at ./task.jl:259
jl_apply_generic at /home/takafumi/repos/watch/julia/src/gf.c:2209
jl_apply at /home/takafumi/repos/watch/julia/src/julia.h:1571 [inlined]
start_task at /home/takafumi/repos/watch/julia/src/task.c:572
unknown function (ip: 0xffffffffffffffff)
Allocations: 10894497 (Pool: 10891786; Big: 2711); GC: 23
zsh: illegal hardware instruction  ./julia --startup-file=no
```

[Update: #30120 fixes the following]
<strike>
Note that it is likely that `((_, _, x) -> x).(Int, Int, spzeros(3))` cannot be called due to method ambiguity (even if illegal instruction is fixed):

```julia
julia> ((_, _, _, x) -> x).(Int, Int, Int, zeros(3))  # works with normal array
3-element Array{Float64,1}:
 0.0
 0.0
 0.0

julia> ((_, _, _, x) -> x).(Int, Int, Int, spzeros(3))
ERROR: MethodError: SparseArrays.HigherOrderFns.capturescalars(::getfield(SparseArrays.HigherOrderFns, Symbol("##5#6")){Int64,getfield(Main, Symbol("##5#6"))}, ::Tuple{Base.RefValue{Type{Int64}},Base.RefValue{Type{Int64}},SparseVector{Float64,Int64}}) is ambiguous. Candidates:
  capturescalars(f, mixedargs::Tuple{Union{AbstractArray{0,N} where N, Ref},Ref{Type{T}},Vararg{Any,N} where N}) where T in SparseArrays.HigherOrderFns at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/higherorderfns.jl:1029
  capturescalars(f, mixedargs::Tuple{Ref{Type{T}},Vararg{Any,N} where N}) where T in SparseArrays.HigherOrderFns at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/higherorderfns.jl:1025
Possible fix, define
  capturescalars(::Any, ::Tuple{Ref{Type{T}},Ref{Type{T}},Vararg{Any,N} where N})
Stacktrace:
 [1] capturescalars at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/higherorderfns.jl:1025 [inlined]
 [2] _copy(::Function, ::Base.RefValue{Type{Int64}}, ::Vararg{Any,N} where N) at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/higherorderfns.jl:973
 [3] copy at /home/takafumi/repos/watch/julia/usr/share/julia/stdlib/v1.1/SparseArrays/src/higherorderfns.jl:965 [inlined]
 [4] materialize(::Base.Broadcast.Broadcasted{SparseArrays.HigherOrderFns.SparseVecStyle,Nothing,getfield(Main, Symbol("##5#6")),Tuple{Base.RefValue{Type{Int64}},Base.RefValue{Type{Int64}},Base.RefValue{Type{Int64}},SparseVector{Float64,Int64}}}) at ./broadcast.jl:756
 [5] top-level scope at none:0
```
</strike>

**Comment by Keno** [comment] 2018-11-22 21:37
So what happens here is that the caller infers on 
```
julia> code_typed(SparseArrays.HigherOrderFns._copy, Tuple{Function, Base.RefValue{Type{Int64}}, Base.RefValue{Type{Int64}}, SparseVector{Float64,Int64}}; optimize=true)
1-element Array{Any,1}:
 CodeInfo(
973 1 ─     (SparseArrays.HigherOrderFns.capturescalars)(f, args)::Union{}  │
    └──     $(Expr(:unreachable))::Union{}                                  │
) => Union{}
```
which it knows because of the ambiguity, but what we compile is:
```
julia> code_typed(SparseArrays.HigherOrderFns._copy, Tuple{Function, Base.RefValue{Type{Int64}}, Vararg{Any, N} where N}; optimize=true)
1-element Array{Any,1}:
 CodeInfo(
973 1 ─ %1  = SparseArrays.HigherOrderFns.:(##5#6)::Type{##5#6}pturescalars
    │   %2  = (Core.typeof)(f)::Type{#s55} where #s55<:Function
    │   %3  = (Core.apply_type)(%1, Int64, %2)::Type{##5#6{Int64,_1}} where _1
    │   %4  = %new(%3, f)::##5#6{Int64,_1} where _1      ││
    │   %5  = (Core._apply)(Base.argtail, args)::Tuple   ││╻  tail
    │   %6  = (SparseArrays.HigherOrderFns.capturescalars)(%4, %5)::Tuple{##3#4{_1,_2} where _2 where _1,Tuple}
    │   %7  = (Base.getfield)(%6, 1)::##3#4{_1,_2} where _2 where _1d_iterate
    │   %8  = (Base.getfield)(%6, 2)::Tuple              │╻  indexed_iterate
974 │   %9  = (Core.tuple)(%7)::Tuple{##3#4{_1,_2} where _2 where _1}
    │   %10 = (Core._apply)(SparseArrays.HigherOrderFns._copy, %9, %8)::Union{SparseMatrixCSC, SparseVector}
    └──       return %10                                 │
) => Union{SparseMatrixCSC, SparseVector}
```
which doesn't have any facility for erroring if the arguments would have triggered the ambiguous method. I'm gonna call this an inlining bug.

**Comment by maleadt** [comment] 2018-12-11 13:30
Appears to be fixed on `master`.

**Comment by Keno** [comment] 2018-12-11 15:55
I don't think this general bug is fixed yet. I had worked on fixing it (and have a small reprosucer somewhere), but unless I put it up and forgot avout it, this bug still exists.

**Comment by tkf** [comment] 2018-12-11 19:33
(FYI #30120 makes it possible to execute `((_, _, x) -> x).(Int, Int, spzeros(3))` but I suppose the compiler bug is still here.)

**Comment by maleadt** [comment] 2018-12-12 10:11
Ah, sorry for the wrongful close. FWIW, I reduced it to the following (just improving my creduce scripts and needed some worthwile candidates :slightly_smiling_face:):

```julia
a(x) = b(x...)
b(x...) = c(x)
c(::Tuple{Ref{<:Type}, Vararg}) = nothing
c(::Tuple{Ref, Ref}) = nothing

a((Base.RefValue{Type{Int64}}(), Ref(Int64)))
```

```
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.864 (2018-12-11)
 _/ |\__'_|_|_|\__'_|  |  Commit f49cb42fb0 (0 days old master)
|__/                   |

julia> a(x) = b(x...)
a (generic function with 1 method)

julia> b(x...) = c(x)
b (generic function with 1 method)

julia> c(::Tuple{Ref{<:Type}, Vararg}) = nothing
c (generic function with 1 method)

julia> c(::Tuple{Ref, Ref}) = nothing
c (generic function with 2 methods)

julia> a((Base.RefValue{Type{Int64}}(), Ref(Int64)))
Unreachable reached at 0x7f05ddc4b045

signal (4): Illegal instruction
in expression starting at no file:0
a at ./REPL[1]:1
jl_fptr_trampoline at /buildworker/worker/package_linux64/build/src/gf.c:1854
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2209
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:323
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:411
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:362 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:773
jl_interpret_toplevel_thunk_callback at /buildworker/worker/package_linux64/build/src/interpreter.c:885
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7f05f6d6a35f)
unknown function (ip: 0x5)
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:894
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:764
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:793
eval at ./boot.jl:328
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2209
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#26 at ./task.jl:259
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2209
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1571 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:572
unknown function (ip: 0xffffffffffffffff)
Allocations: 581819 (Pool: 581666; Big: 153); GC: 0
zsh: illegal hardware instruction  ./binary/bin/julia
```

**Comment by JeffBezanson** [comment] 2018-12-12 16:16
Another way to reproduce it:
```
c(::Tuple{Ref{<:Type}, Vararg}) = nothing
c(::Tuple{Ref, Ref}) = nothing
b(x...) = c(x)

julia> c((Base.RefValue{Type{Int64}}(), Ref(Int64)))
ERROR: MethodError: c(::Tuple{Base.RefValue{Type{Int64}},Base.RefValue{DataType}}) is ambiguous. Candidates:

julia> b(Base.RefValue{Type{Int64}}(), Ref(Int64))
# returns nothing; no error
```

**Closed** 2019-04-27 02:16 UTC
Labels: bug, optimizer
