### ISSUE TITLE
WARNING: replacing docs for 'foo :: Union{}' in module 'Main'. (0.6 only, new parameterization syntax)

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/julia#21190] opened 2017-03-28 06:58 UTC
The functions have different signatures, so I'm not sure why this warning is being thrown.

```
"""
    foo(x, y)
"""
function foo(x::Int, y::Vector{T}) where T
  return x + 1
end

"""
    foo(x, y, z)
"""
function foo(x::Int,y::Vector{T}, z::Vector{S}) where T where S
  return x + 2
end
```

**Comment by sbromberger** [comment] 2017-03-28 07:03
Just as another data point, nonparameterized methods don't seem to have a problem:
```
"""
    foo(x, y)
"""
function foo(x::Int, y::Vector)
  return x + 1
end

"""
    foo(x, y, z)
"""
function foo(x::Int,y::Vector, z::Vector)
  return x + 2
end
```
works as expected.

**Comment by sbromberger** [comment] 2017-03-28 07:07
BTW, all these examples work in Julia 0.5 (with the parameterization adjusted, of course) without warning.

**Comment by tkelman** [comment] 2017-03-28 10:15
can't reproduce on master. please include specific version info in issues.

**Comment by fredrikekre** [comment] 2017-03-28 11:09
Fixed by f65b8aba9abb9f0bd0f2da5fba8cc3eb1475cef1

**Closed** 2017-03-28 14:20 UTC

**Comment by sbromberger** [comment] 2017-03-28 14:46
Thanks. Sorry for not putting the version info in there; I was on a 4-day-old master.

**Comment by JeffBezanson** [comment] 2017-03-28 15:33
I now see `WARNING: replacing docs for 'Base.rem :: Union{}' in module 'Base'.` at the end of the sysimg build, both locally and in CI.

**Comment by tkelman** [comment] 2017-03-28 15:56
Different issue, that's https://github.com/JuliaLang/julia/pull/20759
