### ISSUE TITLE
Trying to subtype a function does not throw an error

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#17162] opened 2016-06-28 15:38 UTC
The following came up in a discussion with @davidagold, trying to subtype a function. `MyFuncs` is completely ignored, even when it hasn't yet been defined:

```
11:36 $ julia-dev
               [banner here]

julia> function f() <: MyFuncs
             end
f (generic function with 1 method)
```

**Comment by dpsanders** [comment] 2016-06-28 15:38
Is there a "correct" way to make a subclass of `Function`s on 0.5?

**Comment by dpsanders** [comment] 2016-06-28 15:42
But of course running the function gives an error:
```
julia> f()
ERROR: UndefVarError: MyFuncs not defined
 in f() at ./REPL[4]:1
 in eval(::Module, ::Any) at ./boot.jl:234
 in macro expansion at ./REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:46
```

**Comment by yuyichao** [comment] 2016-06-28 15:59
This is simply because `<: MyFuncs` is a valid expression and it's part of the function body. I don't think we have a special syntax for subtyping `Function`. You can always do `type A <: Function` of course.

**Comment by dpsanders** [comment] 2016-06-28 16:05
How do you then declare a particular function to be a subtype of `A`?

**Comment by yuyichao** [comment] 2016-06-28 16:13
You can't, other than just use call overload on your own type.

It is unclear what does `declare a particular function to be a subtype of A` mean. (the `function ... end` syntax defines a method, not a function)

**Comment by dpsanders** [comment] 2016-06-28 16:34
Good point. The underlying question was about traits for functions...

**Comment by JeffBezanson** [comment] 2016-06-28 17:33
It would be nice to allow this syntax. If `f` is a new function, you can in fact pick a supertype for it, which does not have to be `Function`. Of course, as @yuyichao said, if it's not a new function then you can't do this so there would be an error.

**Comment by JaredCrean2** [comment] 2016-06-28 23:03
I have done something like this with functors in 0.4 and would definitely like to see capability preserved now that functions are types that can be specialized on.

> Of course, as @yuyichao said, if it's not a new function then you can't do this so there would be an error.

Does that mean it would be an error to declare a second method for the function at all, or that the second method can't specify its supertype?

**Comment by yuyichao** [comment] 2016-06-28 23:08
There should be an error at least when you specify a parent type on a function that already has a different type. Adding methods to such a function should still be allowed.

**Comment by TotalVerb** [comment] 2016-06-29 02:48
Would this syntax be effectively equivalent with `immutable f <: MyFunction end` followed by the method definition?

**Comment by yuyichao** [comment] 2016-06-29 02:51
Roughtly, probably with slightly different printing.

**Comment by JaredCrean2** [comment] 2016-06-29 02:52
@yuyichao Cool, thanks for the clarification.

**Comment by TotalVerb** [comment] 2016-06-29 02:55
If `MyFunct` is a subtype of `Function`, then the printing should already be there. Otherwise, arguably, this syntax should not force any different printing.

**Comment by yuyichao** [comment] 2016-06-29 02:59
I'm only talking about `_f` vs `#f` for the generated type name....

**Comment by TotalVerb** [comment] 2016-06-29 03:00
Yes, you're right. In that case, I think this syntax is pretty nice and unambiguous.

**Comment by vtjnash** [comment] 2019-07-08 18:23
This works, and the original issue was a confusion over parser behavior (for unary `<:`) and not a bug, so I think the issue can be closed:

```julia
julia> struct _f <: Real; end

julia> const f = _f()
_f()

julia> f() = 3
_f()

julia> f()
3
```

**Comment by gszep** [comment] 2020-12-14 11:44
Hi there! I've tried to follow this discussion to apply methods to sub-types of `Function`. Here is an example of me avoiding individual definitions of `f(::AbstractVector)` and `g(::AbstractVector) `
```julia
struct Integrand <: Function end

# example integrands f(::Number),  g(::Number)
const f = Integrand()
function f( x::T ) where T<:Number
	return x^2 - x
end
const g = Integrand() 
function g( x::T ) where T<:Number
	return - log(x) + sin(x)
end

# this method applies to both f and g. I don't need to define f(::AbstractVector), g(::AbstractVector) separately
function (integrand::Integrand)( X::AbstractVector; dx=0.01 )
	return sum( x -> integrand(x)*dx, X )
end
```

**Comment by vtjnash** [comment] 2022-03-29 21:03
Closing, as noted above

**Closed** 2022-03-29 21:03 UTC
Labels: parser

**Comment by Dhruva2** [comment] 2022-04-21 08:52
> 

I tried copy pasting this in my REPL. It doesn't throw an error. But the function f(x) = x^2 - x is overwritten by declaring the function g. IE if I test f afterwards, I get f(x) = -log(x) + sin(x).
