### ISSUE TITLE
Help should report on deprecation of functions

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#24615] opened 2017-11-15 15:33 UTC
The help gives no info about the fact that a function is deprecated.
EDIT: Unless you notice that it is defined in `deprecated.jl`. 

Example:
```jl
help?> fft
search: fft fft! FFTW fftshift rfft ifft bfft ifft! bfft! ifftshift irfft brfft

  No documentation found.

  Base.DFT.fft is a Function.

  # 1 method for generic function "fft":
  [1] fft(args...; kwargs...) in Base.DFT at deprecated.jl:133

julia> fft()
ERROR: Base.DFT.fft has been moved to the package FFTW.jl.
Run `Pkg.add("FFTW")` to install it, restart Julia,
and then run `using FFTW` to load it.
Stacktrace:
 [1] error(::Function, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String, ::String) at ./error.jl:44
 [2] fft() at ./deprecated.jl:133
 [3] top-level scope
```

**Comment by fredrikekre** [comment] 2017-11-15 15:37
Duplicate of your own issue :) #18737

**Comment by yuyichao** [comment] 2017-11-15 15:40
......

**Closed by yuyichao** 2017-11-15 15:40 UTC

**Comment by dpsanders** [comment] 2017-11-15 15:44
Oops, sorry...
