### ISSUE TITLE
Access to method source

### ISSUE THREAD

**Issue by 0x75** [JuliaLang/julia#10187] opened 2015-02-13 12:40 UTC
Hello Julia Dev Team,

please implement the ability to access the sourcecode of a function by typing in the
function name. R has this ability and it is incredibly helpfull to read good, performant code 
and understand the system.
Article about the matter:
http://dorophone.blogspot.de/2011/07/duckspeak-vs-smalltalk.html

regards 0x75

**Comment by simonbyrne** [comment] 2015-02-13 12:44
You can use the `@less` macro for this, for example:
```
@less factor(10)
```

In future, this sort of question would best be asked on the [julia-users](https://groups.google.com/forum/?fromgroups=#!forum/julia-users) mailing list.

**Comment by StefanKarpinski** [comment] 2015-02-13 16:16
For what it's worth, I kind of want this too. One can't, for example, see what the source of functions entered in the REPL were – only functions where the source exists in a file somewhere and hasn't changed. One potential (clever) way to do this is to record the source lines of the inputs to the REPL as the `~/.julia_history` file since we are recording what people enter there.

**Comment by quinnj** [comment] 2015-02-13 16:22
It's something I've been meaning to play around with, see #7536

**Comment by simonbyrne** [comment] 2015-02-13 16:31
It would also be nice to be able to access the actual AST of a method, pre-lowering: i.e. obtain an AST that could be re-evaluated to give the same method. The method [here](http://stackoverflow.com/a/14883257/392585) no longer works.

**Comment by Jutho** [comment] 2015-02-13 16:36
I agree, very useful also in the context of stagedfunctions.

**Comment by StefanKarpinski** [comment] 2015-02-13 16:39
Let's reopen this for further discussion. I agree that pre-lowered AST would be great to have and with good enough pretty printing would suffice for most purposes.

**Comment by JeffBezanson** [comment] 2015-02-13 16:42
duplicate of #2625

**Closed by JeffBezanson** 2015-02-13 16:42 UTC
