### ISSUE TITLE
interpret call f(; x, y) as f(; x=x, y=y)

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#29333] opened 2018-09-23 19:39 UTC
Sorry if this is a dup but I couldn't find one.

I find it quite common that one calls functions with keyword arguments like

```jl
f(; x=x, y=y, this_was_a_bit_long=this_was_a_bit_long)
```

My proposal is to write this as

```jl
f(;x, y, this_was_a_bit_long)
```

and to parse that to the first example.

Since

```jl
f(; x, y)
```

is already a syntax error, I think this should be possible?

**Comment by yuyichao** [comment] 2018-09-23 20:09
This is implementable as a macro if you really need it and it doesn't enabling doing anything that couldn't be done while making the syntax much more confusing (even more so than the significance of `;` in the function definition).

It'll also give `f(; :a=>b)` and `x = :a=>b; f(; x)` completely different meanings.

**Comment by KristofferC** [comment] 2018-09-23 20:15
> This is implementable as a macro 

Of course, the whole point of introducing this as syntax is to avoid a macro.

> It'll also give `f(; :a=>b)` and `x = :a=>b; f(; x)` completely different meanings.

`f(a=b)` and `d = a=b; f(d)` already have completely different meanings. I don't think people find that very confusing.

**Comment by yuyichao** [comment] 2018-09-23 20:29
> `f(a=b)` and `x = a=b; f(x)`

For start, `=` is not an operator so that's very different.

And it did cause issues with macros in corner cases.

**Comment by ararslan** [comment] 2018-09-23 20:36
My biggest concern over this is that really it shouldn't matter what name you've given to a variable, but in this case you have to be careful if you rename anything, because it can subtly change behavior when using keyword arguments. Instead of just being able to rename your variable, you have to comb through all potential uses of it in this context, and if you miss one you get an unsupported keyword argument error (if you're lucky) or a different result entirely (if you aren't).

**Comment by yuyichao** [comment] 2018-09-23 23:28
> Renaming the variable a to some other name might give you a completely different behavior (e.g by calling it s).

This isn't a defence at all. It's all about the "subtleness" of the change and more precisely, the localness of the effect.

Of course you can't rename a variable that override another one without any observable effect. You don't even need that `let`, `a = 1; b = 2` will obviously be different if you rename `b` to `a`. However, the effect is caused by something that is **in the same scope** (by which I include parents and children ones). You can easily infer locally whether the override can happen or not. This is also why macro hygiene is so important, you can't expect the user to avoid naming conflict with name introduced in a invisible way by the macro author.

**Comment by JeffBezanson** [comment] 2018-09-24 15:59
This is already implemented here, commented out:
https://github.com/JuliaLang/julia/blob/8484f97844c452f15e628d4369ebc3007be0b81e/src/julia-syntax.scm#L1746
It's done during lowering, since `f(; x)` and `f(; x=x)` of course parse differently.

Given the precedent in Rust and other languages with some kind of object notation (e.g. C#, VB, JS) I think this is a reasonable feature. Some commentary from David Anthoff: https://github.com/JuliaLang/julia/pull/22194#issuecomment-305951643

**Comment by yurivish** [comment] 2018-09-24 16:09
I work extensively in Javascript/Typescript, where this is an extremely useful feature. 

It was originally prototyped in CoffeeScript (a compile-to-Javascript language with terser syntax) and then folded into Javascript proper in Javascript ES6.

If anyone is curious to read the discussion thread where this feature was proposed for Rust, here it is: https://github.com/rust-lang/rfcs/pull/1682

**Comment by StefanKarpinski** [comment] 2018-09-24 17:09
> I don't believe you can call something useful if it doesn't allow you to do anything new.

This is an absurd argument. If this was true we'd all just write assembly code.

**Comment by StefanKarpinski** [comment] 2018-09-24 17:14
I think the concern about this feature is essentially this. Currently, if you want to rename a variable to a new unique name, all you have to do is find every instance of it, following the scope rules, and change all those instances. (If you want to rename a variable to something else, you have to worry about name collisions, but that's complicated, so let's ignore it.) With this feature, that's no longer true, you have to also expand any instance `var` in this syntax from `f(; var)` to `f(var=var)` first and then you can rename the variable. That doesn't seem like a show-stopper to me, but that is the complication. I think on the balance, I'm in favor of having this feature.

**Comment by JeffBezanson** [comment] 2018-09-24 18:07
Yes, agreed. I think enough other (very widely used) languages have had this feature for long enough to safely conclude that it's not a disaster.

**Comment by yuyichao** [comment] 2018-09-24 19:11
> If this was true we'd all just write assembly code.

Well, writing assembly code requires significant knowledge of the hardware, is not portable, does not provide features (restrictions) to allow concepts of interfaces so that different code (modules) could interact with each other knowing what other code would use it, etc. All of these are enabling new functionalities that's not doable with assembly code. If theses were doable with macros on top of assembly language, then yes I would totally agree that we don't need any other languages. It seems that this is not the case though, implementation of many of these requires significant restrictions to what the user is allowed to do.

> I think the concern about this feature is essentially this. Currently, if you want to rename a variable to a new unique name, all you have to do is find every instance of it, following the scope rules, and change all those instances.

No, not at all, that's not even my objection. I wrote https://github.com/JuliaLang/julia/issues/29333#issuecomment-423856029 only because I think that is a minor issue and the defence against it is not valid.
What's more important objection for me, and why I bring it up first, is https://github.com/JuliaLang/julia/issues/29333#issuecomment-423844237, i.e. it breaks a simple rule of evaluation and makes it much harder for macros writers. (more below.)

> enough other (very widely used) languages

None of them has as flexible macro as ours. Only one of them has to make a choice in order to have that function at all (since others don't have macros as alternative).
More importantly though, **none of them** are using a syntax that's ambiguous. None of them are using a syntax that would otherwise construct an object that gives it completely different behavior for this, while in no other case makes adding temporary variable a syntactically significant change. (i.e. none of them allow `a = <...>; f(... a ...)` and `f(... <...> ...)` at the same time while having them mean different things).

This significance of creating temporary variables is basically what my biggest objection. I see the variable renaming as a readability and maintainability issue that's only a minor concern since it'll only give a harder life for people that want to use it, I'll be ok with it if that was the only issue. The significance of adding local variable, however, is not like that. All macro writers now have to be careful when splicing expressions and when creating local variables since they might change the semantics of the code they generate.

**Comment by yuyichao** [comment] 2018-09-24 19:21
In another word, I'll be ok with this if we disallow `f(; :a=>b)`.

**Comment by StefanKarpinski** [comment] 2018-09-27 18:19
> All macro writers now have to be careful when splicing expressions and when creating local variables since they might change the semantics of the code they generate.

This is always true?

**Comment by yuyichao** [comment] 2018-09-27 18:28
> So macros already have to pay close attention to what's spliced there.

It's one thing if you do this and get an error (current behavior), it's much worse if you do this and get working code with completely different result (proposed behavior).

**Comment by yuyichao** [comment] 2018-09-27 18:30
And that's exactly what https://github.com/JuliaLang/julia/issues/9972 is complaining about. Doing this will basically be reintroducing that issue.

**Comment by JeffBezanson** [comment] 2018-09-27 18:37
From triage: this is not urgent, we can let the debate go on longer.

**Comment by StefanKarpinski** [comment] 2018-10-19 18:29
Related discussion: https://discourse.julialang.org/t/group-of-variables-to-named-tuple-built-in-solution/16531

**Comment by piever** [comment] 2018-10-20 11:29
The use of this for table manipulations was already mentioned in the context of Query.jl, but even other data manipulation packages would get some benefits from it, for things that are otherwise a bit clumsy:

```julia
using IndexedTables
groupby(iris, :Species, select = :SepalLength) do v
    min, max = extrema(v)
    (; min, max)
end
```

I wonder whether this can be extended to more easily pass properties of a given object as keywords. For example:

```julia
map(i -> (; i.SepalLength, i.SepalWidth), iris)
```

instead of:

```julia
map(i -> (; SepalLength = i.SepalLength, SepalWidth = i.SepalWidth), iris)
```

LINQ as a special curly bracket syntax for it that is emulated by a macro in both JuliaDBMeta and Query but it'd be nice to be able to do this with normal syntax.

**Comment by StefanKarpinski** [comment] 2018-11-01 19:22
Triage remains in favor. @piever's suggestion is also nice. Not urgent, however.

**Comment by JeffBezanson** [comment] 2018-11-01 19:23
The suggestion about `(; i.SepalLength, i.SepalWidth)` is also already implemented and commented out :)

**Comment by mauro3** [comment] 2018-11-02 08:29
Presumably `(; i.j.k.SepalLength)` would be `(; SepalLength=i.j.k.SepalLength)`.

**Comment by yurivish** [comment] 2019-02-02 02:56
I leverage the fact that keyword arguments are not required to be at the end pretty strongly in my [Hyperscript](https://github.com/yurivish/Hyperscript.jl) package — In HTML attributes are specified at the start, and this lets you write `<a href="https://juliacon.org/2019">Click here!</a>` as `a(href="https://juliacon.org/2019", "Click here!")`.

**Comment by StefanKarpinski** [comment] 2019-02-02 21:41
Another argument in favor of this feature: what else would it mean? Even if we decide later that we want a different way to express this, what else would this particular syntax mean besides this?

**Comment by tpapp** [comment] 2019-02-06 12:33
FWIW, I have been experimenting with a [pair of macros](https://github.com/tpapp/EponymTuples.jl) for a few months now --- one that allows deconstructing dispatch on named tuple arguments and turned out to be very brittle and useless (because of matching the exact ordered set of names), but the other is 
```julia
@eponymtuple(a, b, c = 3)
```
which turns into
```julia
(a = a, b = b, c = 3)
```
I find it very useful to organize code in the following situations:

1. I am already using `NamedTuple`s to pass around model parameters, but occasionally need to modify a few parts as I keep transforming the model,
2. I use a complicated `struct` with many fields to describe a model, so the only sensible interface is the one defined by `Base.@kwdef`, and splatting this after the `;` saves a lot of typing and makes code much easier to read.

I can of course live with a macro, but adding this to `Base` would make a lot of sense from my POV.

**Comment by tomyun** [comment] 2020-01-07 22:23
Is there a chance that this feature gets released with 1.x in the near future?

**Comment by JeffBezanson** [comment] 2020-01-07 22:34
There's a chance of it; the main problem is this seems to be somewhat controversial, with many in favor but several opposed.

**Comment by ararslan** [comment] 2020-01-07 22:39
My concerns over this as a general feature still stand, but I've definitely felt many cases lately where it would be quite convenient.

**Comment by StefanKarpinski** [comment] 2020-01-07 23:14
The more I've thought about this, the more I'm in favor of `f(; x, y)` for `f(; x=x, y=y)` and `(; x, y)` for `(; x=x, y=y)` aka `(x=x, y=y)`. It's all nice and consistent and useful for both function calls and named tuples. When argument/field names are significant, it's just very common and convenient to use those names for the variables that holds the corresponding values.

**Comment by quinnj** [comment] 2020-01-07 23:43
I thought I had already commented this, but it looks like I never did; I'm also very much in favor of this. Having done a bunch of javascript/typescript lately, it's widely used and pretty handy; I've grown to really enjoy it. I also think it's a pretty "natural" feature; like, it's pretty easy to guess what it means just by looking at it (in a namedtuple or keyword arg context).

**Comment by tknopp** [comment] 2020-01-09 13:54
I also wanted this feature several times in the past and would be in favor if this moves forward. Without this feature I often try to abbreviate variable names or even abbreviate the keyword name in order to not increase the line length of a function call.

**Comment by JeffBezanson** [comment] 2020-01-09 18:37
I'll start on a PR.

I just realized one minor inconsistency is that `function f(; x)` already has a meaning, which is to make keyword arg `x` required, not `x=x`. I don't think it's a show-stopper though.

**Comment by ararslan** [comment] 2020-01-09 18:38
Function definitions are already different from call sites anyway, so I'd agree that it isn't a showstopper, but it is a bit unfortunate.

**Comment by StefanKarpinski** [comment] 2020-01-09 19:22
I don't really think that's so bad. Even if `function f(; x)` meant `function f(; x=x)`, that's a bit weird in that it creates a new binding for `x` inside of the function to whatever the outer `x` is. That's sometimes useful to do, I guess, but mainly only in global scope.

**Comment by quinnj** [comment] 2020-01-09 21:36
I thought the canonical way to do that was `f(; x=error("hey, you need to pass x")`

**Comment by ararslan** [comment] 2020-01-09 21:37
Not since #25830.

**Comment by tpapp** [comment] 2020-01-10 08:39
Given that the feature suggested is possible to implement in a package with a macro (eg [jw3126/EponymKeywordSyntax.jl](https://github.com/jw3126/EponymKeywordSyntax.jl)), I am not sure it should be in `Base`.

As much as I find the feature useful, I think that making this transformation only when explicitly requested would be the best approach for now.

**Closed** 2020-03-23 21:50 UTC
Labels: decision, enhancement, keyword arguments
