### ISSUE TITLE
Differentiate between Windows and MinGW

### ISSUE THREAD

**Issue by Neumann-A** [JuliaLang/julia#49867] opened 2023-05-17 22:29 UTC
Please differentiate between MinGW and a real Windows build with clang-cl (MSVC is not possible due to the current heavy use of inline assembly)
```
C:\Program Files\Microsoft Visual Studio\2022\Community>dumpbin E:\all\vcpkg\buildtrees\julia\x64-win-llvm-release-rel\usr\bin\libjulia-internal.dll /DEPENDENTS
Microsoft (R) COFF/PE Dumper Version 14.35.32217.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file E:\all\vcpkg\buildtrees\julia\x64-win-llvm-release-rel\usr\bin\libjulia-internal.dll

File Type: DLL

  Image has the following dependencies:

    libjulia.dll
    uv.dll
    utf8proc.dll
    KERNEL32.dll
    WS2_32.dll
    WINMM.dll
    dbghelp.dll
    getopt.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-utility-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-locale-l1-1-0.dll
```

It is possible to build however running/bootstrapping Julia itself as part of the build is currently stuck at:

```
ijl_errorf at E:\all\vcpkg\buildtrees\julia\x64-win-llvm-release-rel\usr\bin\libjulia-internal.dll (unknown line)
ijl_dlsym at E:\all\vcpkg\buildtrees\julia\x64-win-llvm-release-rel\usr\bin\libjulia-internal.dll (unknown line)
ijl_load_and_lookup at E:\all\vcpkg\buildtrees\julia\x64-win-llvm-release-rel\usr\bin\libjulia-internal.dll (unknown line)
unknown function (ip: 000001FE06044FC7)
abspath at .\path.jl:431
include at .\Base.jl:375
include at .\Base.jl:17
```

I fixed similar issues for pcre/libuv/utf8proc however here I don't directly see how to fix it since there is no `ccall` with a wrong dll name.

I would also appreciate if julia could move away from pure Makefile hell in 2023 which hardcodes to many platform dependent details of the build (e.g. `lib` prefix, `.a` suffix etc.....) and I also feel like the build script could be cut in half with that.

**Comment by mkitti** [comment] 2023-05-17 23:24
Visual Studio is not a supported compiler.  I recommend using the MSYS2 MINGW64 environment.

If you really want to start on this, start with the dependencies in deps, especially libLLVM. What do you want to switch to? Cmake hell?

**Comment by Neumann-A** [comment] 2023-05-18 12:42
> Visual Studio is not a supported compiler

That is why I use clang-cl which supports the gcc extension in use. 

> I recommend using the MSYS2 MINGW64 environment.

That environment is exactly what I want to avoid. 

> start with the dependencies in deps

Why? I already have all dependencies build with a consistent toolchain externally supplied. I don't have any need to even build them as part of Julia. Again it is 2023 use a package manager like vcpkg or conan to supply the needed dependencies. (And using a fork of libuv without mangling the names is certainly not a solution but a problem.)

> especially libLLVM

IS there a reason you point LLVM out? It is trivial to build with CMake although I wouldn't suggest it as a good cmake example. 

>  Cmake hell?

Since the current makefiles are already vendoring a lot of dependencies using CMake and it being widely available it would be an obvious choice. But I am fine with anything providing proper platform introspection and dependency lookup without having to reinvent the wheel. 
As far as I can tell Julia only has 4 or 5 library/executable targets and the rest is just preparing wrappers and precompiling stuff with julia. 

The main problem I currently encounter is a way to inject the correct dll names. For example the Julia scripts assume zlib to be named `libz.dll` however the true native windows name is `zlib1.dll`. Also what about static builds? Do I just whole archive that into libjulia-internal how it was done with utf8proc and libuv?

**Comment by mkitti** [comment] 2023-05-18 13:02
> use a package manager like vcpkg or conan to supply the needed dependencies. 

Many of our dependencies are heavily patched. LLVM I'd perhaps one of the largest at the moment.

In current default build process, most of the dependencies are pulled from discrete builds from recipes located at
https://github.com/JuliaPackaging/Yggdrasil

We effectively built our own package manager for binary dependencies. See https://binarybuilder.org/

**Comment by mkitti** [comment] 2023-05-18 13:06
> libuv

For libuv, see our running cooperative fork  at https://github.com/JuliaLang/libuv

**Comment by mkitti** [comment] 2023-05-18 13:11
I think th easiest first step here would be to try to get Julia to build in a msys2 clang ucrt environment:

https://www.msys2.org/docs/environments/

**Comment by mkitti** [comment] 2023-05-18 17:26
See https://github.com/JuliaLang/llvm-project.git for the LLVM that Julia vendors in.

**Comment by Neumann-A** [comment] 2023-05-20 12:02
> For libuv, see our running cooperative fork at https://github.com/JuliaLang/libuv

I switched to libuv master and it seems to be equivalent to that fork. Don't know why the github comparison still shows a diff when there is none. 

Hmm one major but solveable problem:
```
LoadError("e:\\all\\vcpkg\\buildtrees\\julia\\x64-win-llvm-release-rel\\usr\\share\\julia\\stdlib\\v1.10\\LibGit2\\src\\LibGit2.jl", 3, LoadError("e:\\all\\vcpkg\\buildtrees\\julia\\x64-win-llvm-release-rel\\usr\\share\\julia\\stdlib\\v1.10\\LibGit2\\src\\utils.jl", 45, ErrorException(precompile(Tuple{typeof(Base.sizeof), ErrorException})
precompile(Tuple{Type{Base.ImmutableDict{Symbol, Any}}, Base.ImmutableDict{Symbol, Any}, Symbol, ErrorException})
"could not load library \"libgit2\"\nThe specified module could not be found. "))))
```
I see this cosistenly with code like
```
    @check ccall((:git_libgit2_version, :libgit2), Cint,
                 (Ref{Cint}, Ref{Cint}, Ref{Cint}), major, minor, patch)
```
should `:libgit2` be a julia variable? I set libgit2 = "git2.dll" in the correct place but somehow the modules using `:<varname>` always fail in the `ccall` If i manually change it to `libgit2` and set the variable manually above the function it works as intended. So i assume there is some confusion which variables are actually available. 

However i was able to precompile `sys.ji` now, so it is just a matter of time to go the whole way. 

(If somebody wonders how i got the 128bit int intrinsics I used a hacky `clang_rt.builtins-x86_64.lib -NODEFAULTLIB:libcmt -export:__udivti3=__udivti3 -export:__divti3=__divti3` when linking libjulia-internal)

**Comment by Neumann-A** [comment] 2023-05-20 23:03
Current error:
```
precompile(Tuple{Type{FileWatching.FileEvent}, Bool, Bool, Bool})
└ Collect (Basic: ◑ , REPL 0/0: ◑ ) => Execute ◑ 38Failed to precompile __PackagePrecompilationStatementModule [top-level] to "C:\\Users\\iluin\\AppData\\Local\\Temp\\jl_lH3thS\\compiled\\v1.10\\jl_B6BF.tmp".
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base .\loading.jl:2378
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:2244
 [4] top-level scope
   @ none:3
└ Collect (Basic: ◐ , REPL 0/0: ◐ ) => Execute ◐ 38precompile(Tuple{typeof(Base.push!), Base.IntrusiveLinkedList{Task}, Task})
```
That is one I don't know what to do about since it doesn't really tell me why it failed and after that failure the build seems to be getting stuck at:
```
precompile(Tuple{typeof(Base.setproperty!), Task, Symbol, Bool})
└ Collect (Basic: ◒ , REPL 0/0: ◒ ) => Execute ◒ 38
```

**Comment by stahta01** [comment] 2023-05-23 09:33
The patch I used to build under MSys2 UCRT64 is
```
Subject: ucrt: Replace "msvcrt" with "ucrtbase"

Replace "-lmsvcrt" with "-lucrtbase" in base/linking.jl
Set CRTDLL_BASENAME to "ucrtbase".
Replace libmsvcrt.a with libucrtbase.a
---
 Makefile        | 2 +-
 base/linking.jl | 2 +-
 src/dlload.c    | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)

diff --git a/Makefile b/Makefile
index 0d85d19567..b40ee6045f 100644
--- a/Makefile
+++ b/Makefile
@@ -276,7 +276,7 @@ endif
 	# These are files from mingw32 and required for creating shared libraries like our caches.
 	-$(INSTALL_M) $(build_libdir)/libgcc_s.a $(DESTDIR)$(libdir)/
 	-$(INSTALL_M) $(build_libdir)/libgcc.a $(DESTDIR)$(libdir)/
-	-$(INSTALL_M) $(build_libdir)/libmsvcrt.a $(DESTDIR)$(libdir)/
+	-$(INSTALL_M) $(build_libdir)/libucrtbase.a $(DESTDIR)$(libdir)/
 else
 
 # Copy over .dSYM directories directly for Darwin
diff --git a/base/linking.jl b/base/linking.jl
index 18cf128b34..0c8d47bfed 100644
--- a/base/linking.jl
+++ b/base/linking.jl
@@ -155,7 +155,7 @@ function link_image_cmd(path, out)
     SHLIBDIR = "-L$(shlibdir())"
     LIBS = is_debug() ? ("-ljulia-debug", "-ljulia-internal-debug") : ("-ljulia", "-ljulia-internal")
     @static if Sys.iswindows()
-        LIBS = (LIBS..., "-lopenlibm", "-lssp", "-lgcc_s", "-lgcc", "-lmsvcrt")
+        LIBS = (LIBS..., "-lopenlibm", "-lssp", "-lgcc_s", "-lgcc", "-lucrtbase")
     end
 
     V = VERBOSE[] ? "--verbose" : ""
diff --git a/src/dlload.c b/src/dlload.c
index 9f4e8be299..cd584461a1 100644
--- a/src/dlload.c
+++ b/src/dlload.c
@@ -60,7 +60,7 @@ static int endswith_extension(const char *path) JL_NOTSAFEPOINT
 }
 
 #ifdef _OS_WINDOWS_
-#define CRTDLL_BASENAME "msvcrt"
+#define CRTDLL_BASENAME "ucrtbase"
 
 JL_DLLEXPORT const char *jl_crtdll_basename = CRTDLL_BASENAME;
 const char *jl_crtdll_name = CRTDLL_BASENAME ".dll";
-- 
```

It might or might not be needed by you.

Tim S.

**Comment by Neumann-A** [comment] 2023-05-30 06:59
@stahta01 Thanks for the hints. I am at the point where `linking.jl` is run from I assume `generate_precompile.jl`. However, I get a link error from `lld-link` that the symbol `jl_RTLD_DEFAULT_handle` is not defined. Since `jl_RTLD_DEFAULT_handle` is a global data symbol which is exported and the error does not include the `__imp__` prefix I have to assume that julia is not correctly decorating global data symbols as `__delcspec(dllimport)` (or adding the `__imp__` prefix)

**Comment by Neumann-A** [comment] 2023-05-30 07:01
Also basic cmake support for Windows is here https://github.com/Neumann-A/julia/tree/add_cmake. If somebody wants to make it cross-platform be my guest. I keep fighting the normal windows build until then.

**Comment by mkitti** [comment] 2023-05-30 07:27
I guess you are looking for https://github.com/JuliaLang/julia/blob/ed5bd4c9553b757155b559744c8ce7a6ab513bf7/src/support/dtypes.h#L82

**Comment by Neumann-A** [comment] 2023-05-30 17:00
After resolving the last issue. I am now at `Collect (Basic: ✓ 680, REPL 39/39: ✓ 1865) => Execute ✓ 1933` (Julia mingw CI claims `└ Collect (Basic: ✓ 774, REPL 39/39: ✓ 1943) => Execute ✓ 2009`) so I assume I already have a partly working Julia binary. Have to check how to actually convert the output to `sys.dll`

**Comment by mkitti** [comment] 2023-05-30 17:37
The above is for building the system image. You might be able to run `julia` without that via `--sysimage-native-code=no`.

You probably want to have Julia output code. See the following.

```
$ julia --help-hidden

    julia [switches] -- [programfile] [args...]

Switches (a '*' marks the default value, if applicable):

 --compile={yes*|no|all|min}
                          Enable or disable JIT compiler, or request exhaustive or minimal compilation

 --output-o <name>        Generate an object file (including system image data)
 --output-ji <name>       Generate a system image data file (.ji)
 --strip-metadata         Remove docstrings and source location info from system image
 --strip-ir               Remove IR (intermediate representation) of compiled functions

 --output-unopt-bc <name> Generate unoptimized LLVM bitcode (.bc)
 --output-bc <name>       Generate LLVM bitcode (.bc)
 --output-asm <name>      Generate an assembly file (.s)
 --output-incremental={yes|no*}
                          Generate an incremental output file (rather than complete)
 --trace-compile={stderr,name}
                          Print precompile statements for methods compiled during execution or save to a path
 --image-codegen          Force generate code in imaging mode
```

See https://github.com/JuliaLang/julia/blob/master/sysimage.mk

```
make --f sysimage.mk sysimg-ji JULIA_EXECUTABLE='usr/bin/julia'
make --f sysimage.mk sysimg-release
```

```
$ make -n -f sysimage.mk sysimg-release
printf '    %b %b\n' "\033[32;1m"JULIA"\033[0m" "\033[37;1m"usr/lib/julia/corecompiler.ji"\033[0m";  cd /home/mkitti/src/julia/base && /home/mkitti/src/julia/usr/bin/julia -C "native" --output-ji /home/mkitti/src/julia/usr/lib/julia/corecompiler.ji.tmp --startup-file=no --warn-overwrite=yes -g0 -O0 compiler/compiler.jl
mv /home/mkitti/src/julia/usr/lib/julia/corecompiler.ji.tmp /home/mkitti/src/julia/usr/lib/julia/corecompiler.ji
printf '    %b %b\n' "\033[32;1m"JULIA"\033[0m" "\033[37;1m"usr/lib/julia/sys.ji"\033[0m";  cd /home/mkitti/src/julia/base && if ! JULIA_BINDIR=/home/mkitti/src/julia/usr/bin WINEPATH="/home/mkitti/src/julia/usr/bin;$WINEPATH"  /home/mkitti/src/julia/usr/bin/julia -g1 -O0 -C "native" --output-ji /home/mkitti/src/julia/usr/lib/julia/sys.ji.tmp  --startup-file=no --warn-overwrite=yes --sysimage /home/mkitti/src/julia/usr/lib/julia/corecompiler.ji sysimg.jl ./ ; then echo '*** This error might be fixed by running `make clean`. If the error persists, try `make cleanall`. ***'; false; fi 
mv /home/mkitti/src/julia/usr/lib/julia/sys.ji.tmp /home/mkitti/src/julia/usr/lib/julia/sys.ji
printf '    %b %b\n' "\033[32;1m"JULIA"\033[0m" "\033[37;1m"usr/lib/julia/sys-o.a"\033[0m";  cd /home/mkitti/src/julia/base && if ! JULIA_BINDIR=/home/mkitti/src/julia/usr/bin WINEPATH="/home/mkitti/src/julia/usr/bin;$WINEPATH" JULIA_NUM_THREADS=1  /home/mkitti/src/julia/usr/bin/julia -O3 -C "native" --output-o /home/mkitti/src/julia/usr/lib/julia/sys-o.a.tmp  --startup-file=no --warn-overwrite=yes --sysimage /home/mkitti/src/julia/usr/lib/julia/sys.ji /home/mkitti/src/julia/contrib/generate_precompile.jl 1; then echo '*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***'; false; fi 
mv /home/mkitti/src/julia/usr/lib/julia/sys-o.a.tmp /home/mkitti/src/julia/usr/lib/julia/sys-o.a
printf '    %b %b\n' "\033[34;1m"LINK"\033[0m" "\033[37;1m"usr/lib/julia/sys.so"\033[0m";  g++ -m64  -shared -fPIC -L/home/mkitti/src/julia/usr/lib/julia -L/home/mkitti/src/julia/usr/lib -L/home/mkitti/src/julia/usr/lib -o /home/mkitti/src/julia/usr/lib/julia/sys.so -Wl,--whole-archive /home/mkitti/src/julia/usr/lib/julia/sys-o.a -Wl,--no-whole-archive -ljulia-internal -ljulia $([ Linux = WINNT ] && echo '' -lssp)
true -ignoresys.so /home/mkitti/src/julia/usr/lib/julia/sys.so
true -ignore /home/mkitti/src/julia/usr/lib/julia/sys.so
```

**Comment by Neumann-A** [comment] 2023-05-30 19:56
Running `julia -O0 --sysimage <prefix>\usr\lib\julia\sys.ji --cpu-target=native --startup-file=no -i`

```
julia> versioninfo()
Julia Version 1.10.0
Platform Info:
  OS: Windows (x86_64-pc-windows-msvc)
  CPU: 24 × AMD Ryzen 9 7900X 12-Core Processor
  WORD_SIZE: 64
  LIBM:
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
  Threads: 1 on 24 virtual cores
  
  
julia> sin(3.141)
0.0005926535550994539
julia> sin(3.141/2)
0.9999999560952156

julia> [1,2,3] * [2,3,1]'
3×3 Matrix{Int64}:
 2  3  1
 4  6  2
 6  9  3
```

And I made a copy and paste error. I used `--output-ij` instead of `--output-o`. However linking the sys.dll still fails due to unresovled symbols. 
```
cmd.exe /C "cd /D E:\all\vcpkg\buildtrees\julia-neumann\x64-win-llvm-release-rel\usr\share\julia\base && "C:\Program Files\LLVM\bin\lld-link.exe" /nologo /INCREMENTAL:NO /Brepro /DLL /out:E:/all/vcpkg/buildtrees/julia-neumann/x64-win-llvm-release-rel/usr/lib/julia/sys.dll /DEFAULTLIB:msvcrt.lib /DEFAULTLIB:oldnames.lib -LIBPATH:E:/all/vcpkg/buildtrees/julia-neumann/x64-win-llvm-release-rel/usr/lib/julia -LIBPATH:E:/all/vcpkg/buildtrees/julia-neumann/x64-win-llvm-release-rel/usr/lib /WHOLEARCHIVE:E:/all/vcpkg/buildtrees/julia-neumann/x64-win-llvm-release-rel/usr/lib/julia/sys.obj E:/all/vcpkg/buildtrees/julia-neumann/x64-win-llvm-release-rel/usr/lib/julia.lib E:/all/vcpkg/buildtrees/julia-neumann/x64-win-llvm-release-rel/usr/lib/julia-internal.lib"
lld-link: error: undefined symbol: jl_nothing
>>> referenced by sys.obj(text#0.o):(jl_fvar_base_0)
>>> referenced by sys.obj(text#0.o):(julia_precise_container_type_36676)
>>> referenced by sys.obj(text#0.o):(julia_precise_container_type_36676)
>>> referenced 6997 more times

lld-link: error: undefined symbol: jl_false
>>> referenced by sys.obj(text#0.o):(jl_fvar_base_0)
>>> referenced by sys.obj(text#0.o):(jfptr__issorted_62400)
>>> referenced by sys.obj(text#0.o):(jfptr_bind_76062)
>>> referenced 3387 more times

lld-link: error: undefined symbol: jl_true
>>> referenced by sys.obj(text#0.o):(jl_fvar_base_0)
>>> referenced by sys.obj(text#0.o):(julia_precise_container_type_36676)
>>> referenced by sys.obj(text#0.o):(julia_precise_container_type_36676)
>>> referenced 3079 more times

lld-link: error: undefined symbol: jl_undefref_exception
>>> referenced by sys.obj(text#0.o):(julia_precise_container_type_36676)
>>> referenced by sys.obj(text#0.o):(julia_precise_container_type_36676)
>>> referenced by sys.obj(text#0.o):(julia_precise_container_type_36676)
>>> referenced 11797 more times

lld-link: error: undefined symbol: trunc
>>> referenced by sys.obj(text#0.o):(julia_format_86696)
>>> referenced by sys.obj(text#0.o):(julia_format_86696)
>>> referenced by sys.obj(text#0.o):(julia_YY.7_100603)
>>> referenced 13 more times

lld-link: error: undefined symbol: jl_world_counter
>>> referenced by sys.obj(text#0.o):(jlcapi_read_callback_92799)
>>> referenced by sys.obj(text#0.o):(jlcapi_uv_alloc_buf_77617)
>>> referenced by sys.obj(text#1.o):(jlcapi_header_callback_92502)
>>> referenced 34 more times

lld-link: error: undefined symbol: memcpy
>>> referenced by sys.obj(text#0.o):(julia_assemble_inline_todoNOT._38753)
>>> referenced by sys.obj(text#0.o):(julia_assemble_inline_todoNOT._38753)
>>> referenced by sys.obj(text#0.o):(jfptr_split_cfg_entry_87873)
>>> referenced 445 more times

lld-link: error: undefined symbol: rint
>>> referenced by sys.obj(text#0.o):(julia_YY.7_100603)
>>> referenced by sys.obj(text#3.o):(julia_divrem_58992)
>>> referenced by sys.obj(text#6.o):(julia__round_digits_79084)
>>> referenced 9 more times

lld-link: error: undefined symbol: memset
>>> referenced by sys.obj(text#0.o):(julia_adce_passNOT._39501)
>>> referenced by sys.obj(text#0.o):(julia_type_annotateNOT._37821)
>>> referenced by sys.obj(text#0.o):(julia_access_env_76774)
>>> referenced 209 more times

lld-link: error: undefined symbol: jl_diverror_exception
>>> referenced by sys.obj(text#0.o):(julia_partitionNOT._61727)
>>> referenced by sys.obj(text#0.o):(julia_pkgID_color_95284)
>>> referenced by sys.obj(text#0.o):(julia_show_reduced_backtrace_80560)
>>> referenced 142 more times

lld-link: error: undefined symbol: ceil
>>> referenced by sys.obj(text#0.o):(julia__YY.717_77134)
>>> referenced by sys.obj(text#0.o):(julia__YY.717_77134)
>>> referenced by sys.obj(text#0.o):(julia_YY.setprecisionYY.23_80305)
>>> referenced 9 more times

lld-link: error: undefined symbol: jl_boxed_uint8_cache
>>> referenced by sys.obj(text#0.o):(jfptr_LT.LT._31098)
>>> referenced by sys.obj(text#0.o):(jfptr_SUM._56749)
>>> referenced by sys.obj(text#0.o):(jfptr_add_flag_33585)
>>> referenced 79 more times

lld-link: error: undefined symbol: jl_boxed_int8_cache
>>> referenced by sys.obj(text#0.o):(jfptr_convert_50778)
>>> referenced by sys.obj(text#1.o):(julia_YY.gen_build_codeYY.60_97063)
>>> referenced by sys.obj(text#3.o):(jfptr__sym_to_tpid_53898)
>>> referenced 9 more times

lld-link: error: undefined symbol: jl_emptytuple
>>> referenced by sys.obj(text#0.o):(julia_VersionNumber_40183)
>>> referenced by sys.obj(text#0.o):(julia_ntuple_64099)
>>> referenced by sys.obj(text#0.o):(jfptr_argtail_29162)
>>> referenced 65 more times

lld-link: error: undefined symbol: floor
>>> referenced by sys.obj(text#1.o):(julia_YY.replaceYY.487_70629)
>>> referenced by sys.obj(text#1.o):(julia_YY.replaceYY.487_70574)
>>> referenced by sys.obj(text#2.o):(julia_YY.precisionYY.257_65412)
>>> referenced 11 more times
ninja: build stopped: subcommand failed.
```

**Comment by vtjnash** [comment] 2023-05-30 20:05
Looks like you need to add back calls to DLLImportStorageClass in setComdat and find the missing places for setComdat. We used to have that, years ago, when we used to use link.exe, but it significantly bloated the link times so we dropped it again when we moved back to using GNU `ld` from binutils.

**Comment by Neumann-A** [comment] 2023-05-31 19:24
So I added

![grafik](https://github.com/JuliaLang/julia/assets/30894796/8a45da6c-b556-4398-a28f-bcb9fd2ae6e2)

which seems to be what was there 3 years ago when that file was created.

Getting now:
```
Declaration may not be in a Comdat!
i8*** @jl_RTLD_DEFAULT_handle_pointer
Declaration may not be in a Comdat!
i8*** @jl_RTLD_DEFAULT_handle_pointer
LLVM ERROR: Broken module found, compilation aborted!
```

removed the addition of comdat data for `jl_RTLD_DEFAULT_handle_pointer` which fixed that issue. 
However, the linker errors still remain so it has nothing to do with that?

**Comment by stahta01** [comment] 2023-05-31 19:41
So, are you building with an UCRT toolchain or not?
If yes, did you apply my patch?
If yes, did you copy the libucrtbase.a file to ./usr/lib/ folder?

Do you understand that you will likely need to build the C++ depends like LLVM and GMP?

Tim S.

**Comment by Neumann-A** [comment] 2023-05-31 20:59
> So, are you building with an UCRT toolchain or not?

I am building with clang-cl from a vcvars prompt. To be exact I build inside of vcpkg with https://github.com/Neumann-A/my-vcpkg-triplets/blob/master/x64-win-llvm/x64-win-llvm.toolchain.cmake

> If yes, did you apply my patch?

I adjusted it to apply to my case which means I don't need to manually link. 
Also I am at the last step of converting `sys.obj` into `sys.dll`

> If yes, did you copy the libucrtbase.a file to ./usr/lib/ folder?

I am not using MinGW so no. But the linker knows how to find. Hmm but .a points to a static library so using `/MT` may solve the issues with the non `jl_` prefixed symbols. Let me try that (How do I tell the julia codegen to do that?). However, that would mean that julia uses its own version of the CRT which will be in conflict with the CRT of the ccall'ed dependencies, is there some switch to tell julia to not statically link the CRT?

From MSDN
> If you link your program from the command line without a compiler option that specifies a C runtime library, the linker will use the statically linked CRT libraries: libcmt.lib, libvcruntime.lib, and libucrt.lib.

So i assume the LLVM codegen will do the same as the normal windows compiler in this case. 

Yeah that was it. After using:
```
/DEFAULTLIB:libucrt.lib # Why does the julia codegen not automatically add these linker directives?
/DEFAULTLIB:libvcruntime.lib
/DEFAULTLIB:libcmt.lib
/DEFAULTLIB:oldnames.lib 
```
The only symbols left are `jl_` prefixed symbols.
```
jl_nothing
jl_undefref_exception
jl_true
jl_false
jl_boxed_uint8_cache
jl_boxed_int8_cache
jl_diverror_exception
jl_emptytuple
```

> Do you understand that you will likely need to build the C++ depends like LLVM and GMP?

I have all dependencies build with vcpkg. So no need to rebuild. They are all build with the same toolchain as julia itself is build with.

**Comment by Neumann-A** [comment] 2023-05-31 21:11
Most of those values are here: https://github.com/JuliaLang/julia/blob/304e9a01134d56a7d9a93915590fa9a617d60ff3/src/codegen.cpp#L8871-L8877

the rest is here: (maybe those just need to be exported)
https://github.com/JuliaLang/julia/blob/304e9a01134d56a7d9a93915590fa9a617d60ff3/src/codegen.cpp#L660-L680

**Comment by stahta01** [comment] 2023-05-31 21:23
You do understand that each C++ Compiler has different name mangling; and, unless the C++ compiler you are using understands cygwin GCC C++ name mangling will will get weird link errors.

Tim S.

**Comment by Neumann-A** [comment] 2023-05-31 22:12
> You do understand that each C++ Compiler has different name mangling; and, unless the C++ compiler you are using understands cygwin GCC C++ name mangling will will get weird link errors.

Considering that `link` has been used in the past and that the only issue is related to the import of globals, I doubt this is about weird linker errors. (Also where is gcc used here? codegen happens with llvm and the target is set to `x86_x64-pc-windows-msvc`)

**Comment by mkitti** [comment] 2023-05-31 22:14
> I have all dependencies build with vcpkg. So no need to rebuild. They are all build with the same toolchain as julia itself is build with.

Where is vcpkg pulling sources from though? A vanilla LLVM from upstream is not going to work. Some LInux distributions try to do this, but they end up with very broken and buggy builds.

Can you pull https://github.com/JuliaLang/llvm-project/tree/julia-14.0.6-3 ?

**Comment by Keno** [comment] 2023-05-31 23:38
I don't really have a problem with this effort, as long as somebody volunteer to maintain it, but I do want to make sure you're aware that in order for this to be useable, getting julia to build is gonna be the smallest issue. This will probably needs its whole on platform shard in Yggdrasil and a whole ecosystem rebuild, which we know from the Apple Silicon port is probably about a year's worth of work.

**Comment by Keno** [comment] 2023-05-31 23:42
That said, NAK on the switch to CMake. We went down that road 10 years ago and maintained both for a while and ended up ripping CMake out again.

**Comment by Neumann-A** [comment] 2023-06-01 10:40
> That said, NAK on the switch to CMake. We went down that road 10 years ago and maintained both for a while and ended up ripping CMake out again.

I only saw #11754 and that seem not to have made the cut. Also a lot of water has run down the river since then, especially in the functionality added to CMake.  Also the discussion in #12056 seems partial incorrect today (at least the MKL discussion is dated since OneAPI). 

> Where is vcpkg pulling sources from though? A vanilla LLVM from upstream is not going to work.

github, version 15.0.7. I don't see how https://github.com/llvm/llvm-project/compare/llvmorg-15.0.7...JuliaLang:llvm-project:julia-15.0.7-5 would make a difference (except for maybe slightly better/faster codegen) 

> Similarly, for libuv, can you build https://github.com/JuliaLang/libuv/releases/tag/v1.44.2 

I use libuv master from last week. That is more than good enough for Julia (maybe check the diff?). Also why are you still talking about this since it is clearly working as intended? Otherwise I wouldn't even get to the point of generating the `sys.obj` or running julia by manually setting the sysimage to the generated *.ji files. What is actually the difference between having a dll and a ji file? Is there a good reason to have the dll? For me it seems the ji fulfills the same purpose as the dll?

> getting julia to build is gonna be the smallest issue. 

Let me solve one problem before worrying about the next ;)

**Comment by mkitti** [comment] 2023-06-01 14:13
> I use libuv master from last week. That is more than good enough for Julia (maybe check the diff?). Also why are you still talking about this since it is clearly working as intended? Otherwise I wouldn't even get to the point of generating the sys.obj or running julia by manually setting the sysimage to the generated *.ji files.

Getting Julia to compile is not the same as having it work as intended.

https://github.com/libuv/libuv/compare/master...JuliaLang:libuv:julia-uv2-1.44.2

While those commits do eventually go upstream, the commits exist because of known issues with libuv which is central to much of Julia's aysnc IO and Task based parallelism.

Attempting to use the upstream projects directly has been tried, particularly by Linux distributions, Homebrew, and conda-forge, but this predictably lead to issues. Some of the other dependencies are more forgiving, but those two are known to be particularly in need of patches to work with Julia.

> What is actually the difference between having a dll and a ji file? Is there a good reason to have the dll? For me it seems the ji fulfills the same purpose as the dll?

The ji file is not not native code. It is lowered and type inferred code. The dll is native code.

Without caching the native code, we would need to regenerate native code every time leading to startup latency. Recently, in Julia 1.9.0, the ability to do this on the package level was released.

**Comment by mkitti** [comment] 2023-06-01 14:13
> I use libuv master from last week. That is more than good enough for Julia (maybe check the diff?). Also why are you still talking about this since it is clearly working as intended? Otherwise I wouldn't even get to the point of generating the sys.obj or running julia by manually setting the sysimage to the generated *.ji files.

Getting Julia to compile is not the same as having it work as intended.

https://github.com/libuv/libuv/compare/master...JuliaLang:libuv:julia-uv2-1.44.2

While those commits do eventually go upstream, the commits exist because of known issues with libuv which is central to much of Julia's aysnc IO and Task based parallelism.

Attempting to use the upstream projects directly has been tried, particularly by Linux distributions, Homebrew, and conda-forge, but this predictably lead to issues. Some of the other dependencies are more forgiving, but those two are known to be particularly in need of patches to work with Julia.

> What is actually the difference between having a dll and a ji file? Is there a good reason to have the dll? For me it seems the ji fulfills the same purpose as the dll?

The ji file is not not native code. It is lowered and type inferred code. The dll is native code.

Without caching the native code, we would need to regenerate native code every time leading to startup latency. Recently, in Julia 1.9.0, the ability to do this on the package level was released.

**Comment by Neumann-A** [comment] 2023-06-01 22:51
> The ji file is not not native code. It is lowered and type inferred code. The dll is native code.

Is there a reason Julia isn't directly creating the shared library? I would assume llvm has all the pipeing requried for it. 

> While those commits do eventually go upstream, the commits exist because of known issues with libuv which is central to much of Julia's aysnc IO and Task based parallelism.

I don't know why but somehow github seems to be messing up the diff generation. As far as I checked (part of ?) those patches already landed.

**Comment by oscardssmith** [comment] 2023-06-01 22:56
The reason for the .jl file is that a lot of Julia's compiler is built in Julia, so you need the jl to be able to bootstrap compiling the compiler.

**Comment by Neumann-A** [comment] 2023-06-03 22:43
> Looks like you need to add back calls to DLLImportStorageClass 

@vtjnash: So I tried adding back those calls (gv->setDLLStorageClass(GlobalValue::DLLImportStorageClass)) via a lot of try and error and found these locations.
https://github.com/JuliaLang/julia/blob/0c774c7fb8815cc700e2828066d3e9053f7c3a11/src/cgutils.cpp#L404
fixes all `global_jlvalue_to_llvm` globals
https://github.com/JuliaLang/julia/blob/0c774c7fb8815cc700e2828066d3e9053f7c3a11/src/cgutils.cpp#L3096
fixes  `jlboxed_*` globals

https://github.com/JuliaLang/julia/blob/0c774c7fb8815cc700e2828066d3e9053f7c3a11/src/ccall.cpp#L220
(fixes all handle globals except for `jl_RTLD_DEFAULT_handle`)

https://github.com/JuliaLang/julia/blob/0c774c7fb8815cc700e2828066d3e9053f7c3a11/src/codegen.cpp#L6035
(via `prepare_global_barrier`; current master no longer has that function and instead also calls prepare_global_in; fixes jl_getworld_global)

However, trying to add it for `jl_RTLD_DEFAULT_handle` did not work (and i couldn't find a location to actually make it work).
https://github.com/JuliaLang/julia/blob/0c774c7fb8815cc700e2828066d3e9053f7c3a11/src/ccall.cpp#L50
    GlobalVariable * gv = prepare_global_in(M, jlRTLD_DEFAULT_var);
    gv->setDLLStorageClass(GlobalValue::DLLImportStorageClass);

I assume PR #36260 is one of the PRs which basically lost a lot of information about GlobalVariables. LLVM removes `__imp_` mangling for convience and unless julia codegen tracks what symbols are actually external and imported there is no way to generate correct code. I assume something similar applies to functions which is why I see missing symbols for the static c runtime in `jl_fvar_base_<number>` functions.

**Comment by vtjnash** [comment] 2023-06-04 00:16
Yes, Julia tracks that information, but doesn't mark it. It seems like you have figured out most of them, and just have a few left to find.

**Comment by vtjnash** [comment] 2024-02-10 21:10
I would suggest making a PR for what you have now if you want to collaborate on what is needed next. Closing this issue as this is not a supported platform, though we would take PRs to make it so.

**Closed by vtjnash** 2024-02-10 21:10 UTC
Labels: build, windows
