### ISSUE TITLE
UndefVarError if trying to shadow global variable using let

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaLang/julia#50369] opened 2023-06-30 15:41 UTC
When working with Pluto, I like to wrap more complex cells using `let` and reuse simple variable names.
Within Pluto, everything works fine, but when executing the notebook as a standalone script, Julia complains about some variables not being defined.

### MWE

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.1 (2023-06-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> x = 5
5

julia> y = let
           x = 2x
           x += 1
       end
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] top-level scope
   @ REPL[2]:2
```

### Workaround

By removing the initial line break, Julia gets what I mean.
But I think this is a bug of Julia (and I don't want to use different variable names or edit the whole already-too-long notebook). :upside_down_face: 

```
julia> y = let x = 2x
           x += 1
       end
11

julia> x
5
```

**Comment by MasonProtter** [comment] 2023-06-30 18:46
No I don't think this is considered a bug, this is a core part of how name resolution works in julia. When you write
```julia
let ex1 = ex2
...
end
```
`ex1` is meant to be resolved in the local scope of the `let` block, but the right hand side, `ex2` is resolved in the outer scope.

**Comment by jonas-schulze** [comment] 2023-06-30 23:39
During definition of `x`, an rvalue of the same name obviously refers to the global identifier. By your logic, not even `ex2` would exist.

**Comment by KristofferC** [comment] 2023-07-01 05:12
No, because `x` is not a local variable in that example.

**Comment by MasonProtter** [comment] 2023-07-01 07:04
I think the behaviour being requested would be a somewhat reasonable thing for us to do, and I think it’s fine to keep the issue open as a feature request. 

My point was just that it’s not really a bug. as far as I’m aware this is understood and intended behaviour.

**Closed** 2023-11-08 17:24 UTC
Labels: feature
