### ISSUE TITLE
disallow x!= assignments

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#11365] opened 2015-05-20 01:06 UTC
As pointed out [on the mailing list](https://groups.google.com/d/msg/julia-users/YDGxeTSFhO8/_3w9e8BH0PcJ) `x!=b` is the assignment `x! = b`, but could easily be confused with `x != b`.  Might be good to disallow this kind of assignment in the parser.  See also #7232.

cc: @ScottPJones

**Comment by stevengj** [comment] 2015-05-20 01:08
Wasn't there also a related discussion of `2.^x` vs. `2. ^ x` and `2 .^ x` somewhere?  I can't find it.

**Comment by davidanthoff** [comment] 2015-05-20 01:17
I was bit today by the ``2.^x`` syntax thing. Very much in favor to disallow these kinds of things in the parser and to force people to make a clear choice (i.e. also for the original issue topic).

**Comment by yuyichao** [comment] 2015-05-20 01:22
https://github.com/JuliaLang/julia/issues/10920

**Comment by ScottPJones** [comment] 2015-05-20 01:52
Thanks for making a PR of this... I wasn't sure if it should be, as I said, it isn't really a bug, just a side-effect of decisions elsewhere... such as, it *is* good to use ! to mark functions that modify their arguments... BTW, was it intended that ! should be allowed in the middle of identifiers also?

**Comment by stevengj** [comment] 2015-05-20 02:55
Yes, I think that is intended: like most languages, there are only rules for what characters can start an identifier and what characters can follow, not separately for which characters can end the identifier.  Besides, it's actually not crazy in some areas to have a variable called `foo!!`, e.g. for the double factorial (not to be confused with [U+203C](http://www.fileformat.info/info/unicode/char/203c/index.htm)).  I'm a little sad that we can't use the interrobang in identifiers yet, so that I can't make a variable `WTF‽‽‽`.

**Comment by JeffBezanson** [comment] 2015-05-20 21:27
`x!=y` parses the same as `x != y`. I believe in all these cases we favor the operator. We're consistent about it, imagine that! I think the `!=` operator is drastically more important than `!` identifiers, and it would be extremely fussy to require spaces.

**Comment by ScottPJones** [comment] 2015-05-20 22:00
Please check out the example I posted... Steven made a mistake, but `a!= 0` doesn't do what you'd think, and it's not consistent...

**Comment by ihnorton** [comment] 2015-05-20 22:10
@ScottPJones do you have some local parser modification? I get:
```
julia> a = 1
1
julia> a != 0
true
julia> a!= 0
true
julia> a!=0
true
```

If `a` is undefined then an `UndefVarError` is raised for all of the cases.

**Comment by jeremy-y12** [comment] 2015-05-20 22:16
I also get the behaviour that a!= 0 is true. As long as the exclamation mark is attached to the equal sign, the inequality test occurs. The assignment only happens if you type a! = 0 (or a! =0).

**Comment by ScottPJones** [comment] 2015-05-20 23:58
Now that I'm back home, I can't reproduce this... I'm beginning to think (if it wasn't gremlins), that this was just memory corruption, because shortly before on the same Julia process, I had been making large arrays and tuples... [and I didn't have @yuyichao 's nice fix yet] :crying_cat_face:

**Comment by ihnorton** [comment] 2015-05-21 03:15
(closing in favor of the other, more general issues. comment/reopen if needed)

**Closed by ihnorton** 2015-05-21 03:15 UTC
Labels: decision, parser
