### ISSUE TITLE
add probe-stack support to Julia

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#25523] opened 2018-01-12 01:20 UTC
Looks like support for the "probe-stack" attribute finally landed in LLVM (https://reviews.llvm.org/D34386) thanks to the Rust folks (https://github.com/rust-lang/rust/issues/16012). We should start setting this function attribute in Julia too.

**Comment by DokFaust** [comment] 2018-06-25 15:09
It should not be so hard, as now Julia uses LLVM 6.0.0 it is just needed to add a pass on codegen.
The problem is that looking at [Rust](https://github.com/rust-lang/rust/blob/4dc2d745b9103dc4493b49277337ef4580425d7c/src/librustc_codegen_llvm/attributes.rs) stack probes are incompatible with address sanitizer, so maybe it would be wiser to wait that #27167 gets merged, as maybe we can get similar problems in the future for MSAN or TSAN.

**Comment by vchuravy** [comment] 2018-06-25 17:38
>  so maybe it would be wiser to wait that #27167 gets merged, as maybe we can get similar problems in the future for MSAN or TSAN

Best not to block work on the TSAN support, we only need a way to disable `probe-stack` when sanitizers are used and I can rebase that PR later.

**Comment by DokFaust** [comment] 2018-06-26 18:46
Yeah we can think about that later. Also it seems that the issue is present only with Address Sanitizer, the others are unaffected. I will test it later!

**Comment by eulerkochy** [comment] 2019-02-24 09:30
@vtjnash I'm interested to work on this issue. Can you please give me a headstart about the problems and different reading materials?

**Closed** 2021-03-31 05:13 UTC
Labels: codegen, help wanted
