### ISSUE TITLE
Escaped characters in documentation

### ISSUE THREAD

**Issue by carolfs** [JuliaLang/julia#50996] opened 2023-08-21 13:33 UTC
This is a tiny issue. On this documentation page, the string `&hArr;` is escaped and displayed exactly like that instead of '⇔' as it does on GitHub. I believe just using '⇔' in the Markdown document would work on both sites.

https://docs.julialang.org/en/v1/manual/noteworthy-differences/#Julia-and-hArr;-C/C:-Namespaces

**Comment by 1j01** [comment] 2023-09-04 02:14
This issue is a duplicate of https://github.com/JuliaLang/julia/issues/49991

**Closed** 2023-09-05 21:43 UTC
Labels: doc
