### ISSUE TITLE
Pkg.clone("X") fails silently for non-existent X

### ISSUE THREAD

**Issue by one-more-minute** [JuliaLang/julia#14439] opened 2015-12-18 15:23 UTC
```julia
julia> Pkg.clone("X")
INFO: Cloning X from X
INFO: Computing changes...

julia> 
```
The folder X is also created in the package folder, which messes with later operations.

**Comment by tkelman** [comment] 2015-12-18 15:40
dupe of #14051

**Closed by tkelman** 2015-12-18 15:40 UTC
