### ISSUE TITLE
Prompt to add an uninstalled package on `using` only occurs if Pkg is loaded

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#52091] opened 2023-11-08 22:15 UTC
Current master:
```
julia> using BenchmarkTools
ERROR: ArgumentError: Package BenchmarkTools not found in current path.
- Run `import Pkg; Pkg.add("BenchmarkTools")` to install the BenchmarkTools package.
Stacktrace:
 [1] macro expansion
   @ Base ./loading.jl:1781 [inlined]
 [2] macro expansion
   @ Base ./lock.jl:267 [inlined]
 [3] __require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1762
 [4] #invoke_in_world#3
   @ Base ./essentials.jl:963 [inlined]
 [5] invoke_in_world
   @ Base ./essentials.jl:960 [inlined]
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1755
```
1.10.0-rc1:
```
julia> using BenchmarkTools
 │ Package BenchmarkTools not found, but a package named BenchmarkTools is available from a registry.
 │ Install package?
 │   (@v1.10) pkg> add BenchmarkTools
 └ (y/n/o) [y]:
```

This is an unfortunate regression in user experience. What's worse is that it depends on whether Pkg is loaded, which may not be obvious. For example, if you accidentally hit `]` then backspace out of it, all of a sudden you're prompted to install packages on `using` again since Pkg was loaded when entering its REPL mode.

**Comment by vchuravy** [comment] 2023-11-08 22:20
Duplicate of #52090

**Closed by vchuravy** 2023-11-08 22:20 UTC
Labels: regression
