### ISSUE TITLE
Attempting to start julia from IIS app-pool W3WP.exe throws error

### ISSUE THREAD

**Issue by jonbarkerlondon** [JuliaLang/julia#16127] opened 2016-04-29 19:41 UTC
Hey all, getting the error below when executing julia from a windows service. Any input is welcome.

Thanks,
Jon

Info:
- Windows 2012
- If i start a command line prompt as my local user and run julia.exe, it loads fine.
- If i start a command prompt as user 'svc-resolvernonprod' and run julia.exe it loads fine.
- The IIS app-pool W3WP.EXE is running under the user account 'svc-resolvernonprod'
- When the IIS app-pool application runs julia.exe, the following error is displayed:

fatal: error thrown and no exception handler available.
[inline] at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:583
rec_backtrace_ctx at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:578
jl_throw at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:854
[inline] at .\env.jl:37
getindex at .\env.jl:79
__init__ at .\pkg.jl:57
unknown function (ip: 00000000021DE6C4)
jl_apply_generic at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\gf.c:1917
[inline] at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\julia.h:1555
jl_eh_restore_state at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\module.c:624
jl_init_restored_modules at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\dump.c:1818
_julia_init at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\init.c:698
julia_init at /home/Administrator/buildbot/slave/package_win6_2-x64/build/src\task.c:278
wmain at /home/Administrator/buildbot/slave/package_win6_2-x64/build/ui\repl.c:628
__tmainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.2-1/crt\crtexe.c:334
mainCRTStartup at /usr/src/debug/mingw64-x86_64-runtime-4.0.2-1/crt\crtexe.c:214
BaseThreadInitThunk at C:\Windows\system32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
Base.InitError(mod=:Pkg, error=Base.KeyError(key="HOMEDRIVE"))

**Comment by vtjnash** [comment] 2016-04-29 19:44
this user account appears to be missing a HOMEDRIVE https://support.microsoft.com/en-us/kb/841343

duplicate of #15884

**Closed by vtjnash** 2016-04-29 19:44 UTC

**Comment by jonbarkerlondon** [comment] 2016-04-29 19:58
Thanks!
