### ISSUE TITLE
Need to update to SuiteSparse 4.4.2

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#9720] opened 2015-01-11 08:40 UTC
I just noticed this, and we should probably update:

•SuiteSparse v4.4.2 : with the latest CUDA-accelerated CHOLMOD and SuiteSparseQR.  This version fixes a rarely occuring but serious bug that exists in CHOLMOD 3.0.0 through 3.0.3, and in SuiteSparse 4.3.0 through 4.4.1.  The bug can cause a segfault, so an upgrade is recommended if you are currently using any of those versions.

**Comment by tkelman** [comment] 2015-01-11 09:13
better as a PR? patch bumps sound low-risk, if you're paranoid we can run the buildbots on it to check for build issues

**Comment by ViralBShah** [comment] 2015-01-11 09:30
There was some windows related stuff with suitesparse that I can't remember. Is it now safe to just bump the version in Versions.make?

**Comment by tkelman** [comment] 2015-01-11 09:35
Yeah, I had some stuff in appveyor that was briefly fragile w.r.t. version number, but I made it more robust, then removed it after it was no longer necessary.

The issue is if we ever need to add or change anything new to `deps/SuiteSparse_wrapper.c` in order to pass tests for new or changed functionality, then that file needs to get built on CI until new binaries are ready, which was requiring downloading the SuiteSparse source and modifying some files' timestamps to not build the entire library. I turned that part off when it started causing failures due to intermittent network problems, and it doesn't look like we'll be needing to make any changes to `SuiteSparse_wrapper` at the moment.

**Comment by ViralBShah** [comment] 2015-01-11 09:36
Ok, I just created the PR. I am assuming that @staticfloat will need to update the debs, and we probably want to backport this too to 0.3.

**Comment by tkelman** [comment] 2015-01-11 09:42
yeah if this is a bugfix then we probably will, though release-0.3 is still on 4.2.something so we'll need to backport the other version bumps (squashed) too, at least the ones that required build changes due to reorganization of some of the libraries

**Comment by ViralBShah** [comment] 2015-01-11 09:44
The bug is apparently only in SuiteSparse 4.3.0-4.4.1. In that case we can avoid the backport.

**Comment by staticfloat** [comment] 2015-01-12 21:31
The OSX bottles are still stuck at 4.2.1 because of the update needed in https://github.com/JuliaLang/julia/pull/9746.  Hopefully after that gets merged, I can just bottle 4.4.2 and we'll be good there.

The `.deb`'s are mostly maintained by @sebastien-villemot.  Sébastien, are you interested at all in updating the debian Suite-Sparse package to 4.4.2?  The segfault mentioned in the changelog doesn't impact the 4.2.X line of suite sparse releases, so that's one less reason to update, but if there's something in the 4.4.X line that you like and want to update for, then we can use those in our PPAs.  The main problem is that the way the shared libraries are being built in the debian packaging makefile is much more labor-intensive than our `repackage_system_suitesparse4.make` file, and I'm not at all certain I'd be able to update the patches that no longer apply satisfactorily.

**Comment by sebastien-villemot** [comment] 2015-01-12 22:05
@staticfloat I indeed plan to update the SuiteSparse package in Debian. However I'm not doing it right now because Debian is currently frozen. In the meantime I could upload 4.4.2 to Debian experimental. I'll do this in the near future when I find the time.

**Comment by staticfloat** [comment] 2015-01-12 22:06
Thanks.  If you need any help with anything, just let me know.

**Comment by jiahao** [comment] 2015-01-18 06:54
Closed by #9721

**Closed by jiahao** 2015-01-18 06:54 UTC
Labels: bug, sparse

**Comment by staticfloat** [comment] 2015-02-14 01:40
Note to all: Sébastien has very helpfully packaged up SuiteSparse 4.4.3, which I've uploaded to the julia-deps PPA.  Travis and Ubuntu julia installs should get 4.4.3 by default from now on.
