### ISSUE TITLE
=> is imported for extension

### ISSUE THREAD

**Issue by mbauman** [JuliaLang/julia#39929] opened 2021-03-05 22:17 UTC
This surprised me; happens at both the REPL and in scripts (and no startup file).

```Julia
julia> 1*2
2

julia> a*b = b*a # errors as I expect:
ERROR: error in method definition: function Base.* must be explicitly imported to be extended
Stacktrace:
 [1] top-level scope
   @ none:0
 [2] top-level scope
   @ REPL[2]:1

julia> 1=>2
1 => 2

julia> a=>b = b=>a
Error showing value of type UnionAll:
ERROR:
SYSTEM (REPL): showing an error caused an error
ERROR:
SYSTEM (REPL): caught exception of type StackOverflowError while trying to handle a nested exception; giving up

julia> ┌ Error: Error in the keymap
│   exception =
│    StackOverflowError:
│    Stacktrace:
│     [1] Pair(a::Int64, b::Int64)
│       @ Main ./REPL[4]:1
└ @ REPL.LineEdit ~/Julia/master/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2536
julia>
ERROR: fatal: error thrown and no exception handler available.
StackOverflowError()
Pair at ./REPL[4]:1
Pair at ./REPL[4]:1
# repeated many thousands of times... and crash

$ echo $?
1
```

**Comment by simeonschaub** [comment] 2021-03-05 22:19
duplicate of #25744?

**Comment by KristofferC** [comment] 2021-03-05 22:19
Dup of https://github.com/JuliaLang/julia/issues/37783 (and https://github.com/JuliaLang/julia/issues/25744).

**Closed** 2021-03-05 22:19 UTC
