### ISSUE TITLE
`-` is space sensitive in indexing context

### ISSUE THREAD

**Issue by diegozea** [JuliaLang/julia#16440] opened 2016-05-19 00:06 UTC
The line `reslist[ resindex -1 ]` gives the following error (because of the `-1`):
```
ERROR: MethodError: `typed_hcat` has no method matching typed_hcat(::Array{MIToS.PDB.PDBResidue,1}, ::Int64, ::Int64)
Closest candidates are:
  typed_hcat(::Type{T}, ::Number...)
  typed_hcat(::Type{T}, ::Any...)
```

**Comment by tkelman** [comment] 2016-05-19 01:11
duplicate of https://github.com/JuliaLang/julia/issues/14853 and #7128 and #6491 and https://github.com/JuliaLang/julia/issues/6405

**Closed by tkelman** 2016-05-19 01:11 UTC
