### ISSUE TITLE
Drastic decrease of efficiency for complex matrix multiplication

### ISSUE THREAD

**Issue by photor** [JuliaLang/julia#36646] opened 2020-07-13 21:56 UTC
I found the following weird behavior of a real matrix times a complex matrix. Firstly, we do it by manually decomposing the complex matrix into real and imaginary parts:
```
using BenchmarkTools

dd=rand(60,60)
ψr=rand(60,60*60)
ψi=rand(60,60*60)
@btime dd*ψr+im*dd*ψi;
```
The result seems reasonable:

> 1.248 ms (10 allocations: 8.30 MiB)

But the complex form of the same operation:
```
ψ=rand(60,60*60)+im*rand(60,60*60)
@btime dd*ψ;
```
results in

> 9.523 ms (8 allocations: 3.30 MiB)

What's happening here?

**Comment by photor** [comment] 2020-07-13 21:58
`versioninfo()`

> Julia Version 1.3.1
> Commit 2d5741174c (2019-12-30 21:36 UTC)
> Platform Info:
>   OS: macOS (x86_64-apple-darwin18.6.0)
>   CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-6.0.1 (ORCJIT, haswell)

**Comment by photor** [comment] 2020-07-13 21:59
Actually I have this same problem also on the Windows platform.

**Comment by oscardssmith** [comment] 2020-07-13 22:08
It has to do with blas vs generic fallbacks. We should just have complex matrix * real matrix defined similarly to what you did.

**Comment by photor** [comment] 2020-07-13 22:14
> It has to do with blas vs generic fallbacks. We should just have complex matrix * real matrix defined similarly to what you did.

More strangely, if you swap the dimensions of ψ, then the efficiencies are kind of reversed:
```
ψr=rand(60*60,60)
ψi=rand(60*60,60)
@btime ψr*dd+im*ψi*dd;
```

> 1.803 ms (10 allocations: 11.54 MiB)

versus
```
ψ=rand(60*60,60)+im*rand(60*60,60)
@btime ψ*dd;
```

> 664.374 μs (4 allocations: 3.30 MiB)

**Comment by oscardssmith** [comment] 2020-07-14 02:11
I looked into the source a little, and it looks like in some cases julia does correctly reinterpret the complex matrix as real, do the multiplaction, and convert back.

**Comment by dkarrasch** [comment] 2020-07-14 19:15
This is the fast one:
https://github.com/JuliaLang/julia/blob/09eee44bf600db14c8f7dce7b88ad01b751041a1/stdlib/LinearAlgebra/src/matmul.jl#L175-L181
that does basically two BLAS multiplications. So it's when the left factor is complex when this is fast. I don't know why but I think there must be a reason that there is no similar function for a complex right factor. Maybe it has to do with column major ordering and the specifics of `reinterpret`?

**Comment by oscardssmith** [comment] 2020-07-14 19:19
I think it might just be an oversight.

**Comment by photor** [comment] 2020-07-15 14:34
> This is the fast one:
> 
> https://github.com/JuliaLang/julia/blob/09eee44bf600db14c8f7dce7b88ad01b751041a1/stdlib/LinearAlgebra/src/matmul.jl#L175-L181
> 
> that does basically two BLAS multiplications. So it's when the left factor is complex when this is fast. I don't know why but I think there must be a reason that there is no similar function for a complex right factor. Maybe it has to do with column major ordering and the specifics of `reinterpret`?

Even worse than we expected, real * complex is much slower than complex * complex:
```
dd=rand(60,60)+im*rand(60,60)
ψ=rand(60,60*60)+im*rand(60,60*60)
@btime dd*ψ;
```

> 806.744 μs (2 allocations: 3.30 MiB)

So I have to say it is a serious bug.

**Comment by dkarrasch** [comment] 2020-07-15 14:37
Did you try on Julia v1.4.2? I couldn't reproduce the slow timing from the OP.

**Comment by dkarrasch** [comment] 2020-07-15 16:09
Yes, this seems to be an issue with v1.3.1, there I can reproduce the poor performance. On v1.4.2, passing the complex arrays seems to be always faster than splitting real and imaginary parts.

**Comment by oscardssmith** [comment] 2020-08-07 03:12
Close this since it's just on 1.3.x?

**Closed** 2020-08-07 13:45 UTC
Labels: linear algebra, performance
