### ISSUE TITLE
v1.6 Windows permissions problems with *tmpdir* created dirs 

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#38433] opened 2020-11-13 15:59 UTC
I can reproduce this with more packages but this one should be enough to show the problem,
```
] test FFTW

Discrete cosine transform (DCT) tests |  337    337
Test Summary:  | Pass  Total
UNALIGNED flag |   74     74
Test Summary:           | Pass  Total
Base Julia issue #19892 |    3      3
     Testing FFTW tests passed
┌ Error: mktempdir cleanup
│   exception =
│    SystemError (with C:\TMP\jl_Q9AXIp): rmdir: Permission denied
│    Stacktrace:
│      [1] systemerror(p::Symbol, errno::Int32; extrainfo::String)
```

The problem seems to arise from the lack of **Modify** permission. When I try to manually remove the ``C:\TMP\jl_Q9AXIp`` I get a windows popup asking me to confirm that I have administrator permissions (which I have so it shouldn't ask, but it does). If I manually change the **Modify** permission to *check* then I can delete that directory without further questions.
Quite likely that explains why ``mktempdir cleanup`` can't do its job silently.

![image](https://user-images.githubusercontent.com/537321/99092034-8e899400-25c8-11eb-8254-1493fbc2eb26.png)

**Comment by KristofferC** [comment] 2020-11-13 16:12
Maybe related to https://github.com/JuliaLang/julia/pull/38159

**Comment by bkamins** [comment] 2020-11-13 16:36
Yes - it seems to be related to "Modify" permissions. Yet on my system I have "Modify" set to yes in these folder for "Authenticated Users" and only "Users" it is set to "Read & execute"+"List"+"Read" onyl (without "Modify" and without "Write"). The same set of permissions is for all `.julia` subfolders.

**Comment by musm** [comment] 2020-11-13 16:43
@bkamins what does winver say? And do you have admin permission on the machine? 
![image](https://user-images.githubusercontent.com/4319522/99097300-6e94a900-25a5-11eb-8c94-c03a0c40aec0.png)

**Comment by bkamins** [comment] 2020-11-13 16:50
![image](https://user-images.githubusercontent.com/6187170/99097945-981af800-25d8-11eb-9d1f-883695f50ea1.png)

regarding rights - yes I have them (and that is why I personally do not have a problem - I just run Julia process as an administrator and all works, but many people do not have it)

**Comment by musm** [comment] 2020-11-13 16:52
Strangely enough, on my copy (fresh 1.5 install) and running Julia without Admin privileges I cannot reproduce this error.

**Comment by joa-quim** [comment] 2020-11-13 16:57
![image](https://user-images.githubusercontent.com/537321/99098592-1bd0e680-25d1-11eb-99c7-25f337dbcb11.png)

But I get this also in another computer with an older Windows version. On Julia 1.5.0 it runs fine.

**Comment by joa-quim** [comment] 2020-11-13 16:59
> Probably the same cause as #38411

Maybe but that PR was merged 16 days ago and I still see this problem with the (today's) nightly build.

**Comment by bkamins** [comment] 2020-11-13 17:46
I am not sure it is related, but recently I started to get in DataFrames.jl errors in CI on nightly on Win and OSx of this kind: https://travis-ci.com/github/JuliaData/DataFrames.jl/jobs/439295303 and https://travis-ci.com/github/JuliaData/DataFrames.jl/jobs/439295302 (such things do not happen on Linux; the error message does not tell me what is the reason of failure but one of them might be permissions).

**Comment by fredrikekre** [comment] 2020-11-13 17:49
> I am not sure it is related, but recently I started to get in DataFrames.jl errors in CI on nightly on Win and OSx of this kind: https://travis-ci.com/github/JuliaData/DataFrames.jl/jobs/439295303 and https://travis-ci.com/github/JuliaData/DataFrames.jl/jobs/439295302 (such things do not happen on Linux; the error message does not tell me what is the reason of failure but one of them might be permissions).

That is https://github.com/JuliaLang/julia/issues/38429

**Comment by musm** [comment] 2020-11-13 18:12
I tested a couple of configurations:
1. Locally installed a fresh copy of 1.5.3 in the default installation location, nuked the compile cache folder, attempted `test FFTW` and `using Tables`, no errors in both instances.
2. Fresh VM in Hyper-V with the build information below. Followed the same steps as in 1, and obtained a similar outcome, no errors.
![image](https://user-images.githubusercontent.com/4319522/99106127-bae5e600-25b1-11eb-8ec2-7b783f629aac.png)

I guess the good news is that the error isn't as widespread as initially thought, but the bad news is I can't reproduce the bug.

**Comment by musm** [comment] 2020-11-13 18:40
How are you all installing Julia here? Is it directly form the website and then running the installer normally (without admin privileges)?

**Comment by bkamins** [comment] 2020-11-13 18:44
Yes.

Also I have just checked that if I remove `.julia` folder then I get:
```
julia> using DataFrames
[ Info: Precompiling DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0]
ERROR: LoadError: IOError: unlink: permission denied (EACCES)
```
if I not run `julia` with admin privileges.

**Comment by joa-quim** [comment] 2020-11-13 19:25
Sorry to cast more confusion but in a Win VM on the same machine were it errors I installed Julia both in the standard location (which I hate because it's a hidden directory) and under ``c:/programs/julia-DEV`` and in both cases I had no problems!!

Winver of the VM
![image](https://user-images.githubusercontent.com/537321/99112576-c9e68b80-25e5-11eb-8298-abaaf83256f1.png)

**Comment by musm** [comment] 2020-12-18 22:38
@joa-quim  please reopen a new issue if you encounter this problem again.  I suspect this is a dupe of https://github.com/JuliaLang/julia/issues/38411

**Comment by joa-quim** [comment] 2020-12-18 23:30
I still see the problem
```
julia> mktempdir() do dir
       end
┌ Error: mktempdir cleanup
│   exception =
│    SystemError (with C:\TMP\jl_BrJXnk): rmdir: Permission denied
```
with
```
julia> versioninfo()
Julia Version 1.7.0-DEV.54
Commit 6ddc7f1ecc (2020-12-13 23:16 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, skylake)
```

**Comment by musm** [comment] 2020-12-21 18:58
@joa-quim  do you have a custom `JULIA_DEPOT_PATH ` set? Or any other env variables? I do not get that issue in a plain install of Julia in  VM.

**Comment by joa-quim** [comment] 2020-12-21 19:44
No. I know that's strange but the problem only occurs with v1.6 (and started about 2-3 months ago. Before it was ok). v1.5 in the exact same machine/config has no problems.

**Comment by vtjnash** [comment] 2020-12-21 19:49
Might be 509214d6696f4f061e61e328407630b7d26ebf8b (which added the capability of supporting `mode`): but perhaps `_mkdir` had undocumented functionality affecting this?

**Comment by musm** [comment] 2020-12-21 19:54
That's probably what I think. MSFT's docs for `_mkdir` don't specify how or if they set permissions for `_mkdir`. 

CreateDirectoryW permissions with with the NULL argument  set them to a sensible value:
> If lpSecurityAttributes is NULL, the directory gets a default security descriptor. The ACLs in the default security descriptor for a directory are inherited from its parent directory.

**Comment by musm** [comment] 2020-12-30 05:45
Actually, this is fixed by https://github.com/JuliaLang/julia/pull/39038


I noticed that my `TMP` variable was set to a folder in my user path which is why I couldn't reproduce it initially.
Thus, to reproduce:

```julia
ENV["TMP"] = "C:\\TMP"
julia>  mktempdir() do dir
                     end
```

**Closed** 2020-12-30 07:26 UTC

**Comment by joa-quim** [comment] 2020-12-30 20:47
I'm sorry but too quick in closing
```
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.0-DEV.194 (2020-12-30)
 _/ |\__'_|_|_|\__'_|  |  Commit aeb933c10e (0 days old master)
|__/                   |

julia> mktempdir() do dir end
┌ Error: mktempdir cleanup
│   exception =
│    SystemError (with C:\TMP\jl_T6S6rK): rmdir: Permission denied
│    Stacktrace:
```

But if that may help, I do not have the ``TMP`` in the Windows standard place
```
C:\v
set | grep TMP
TEMP=C:\TMP
TMP=C:\TMP
```

**Comment by musm** [comment] 2020-12-30 20:53
Your nightly is a commit behind the one with the fix. Try downloading again.

**Comment by joa-quim** [comment] 2020-12-30 20:58
OK, I'll try again tomorrow. I just did download the installer 1/4 hour ago.

**Comment by musm** [comment] 2020-12-30 20:59
Sounds good, yes please confirm it works for you.

**Comment by musm** [comment] 2020-12-30 22:07
> I just did download the installer 1/4 hour ago.

Yeah, I think they take day or so to get updated.

**Comment by joa-quim** [comment] 2020-12-31 14:30
Confirmed. Problem solved. Thanks
But on the other hand this new version crashes the VSC language server and broke Revise

**Comment by musm** [comment] 2020-12-31 16:55
That's not surprising, it's a moving target. We will backport the fix for this issue to a stable release.
