### ISSUE TITLE
Loss of accuracy of BigFloat on Win10-64bit plattform

### ISSUE THREAD

**Issue by egarten** [JuliaLang/julia#22758] opened 2017-07-11 18:52 UTC
I found an issue regarding BigFloats using julia0.6.0 on a Win10 system. This error does not appear on linux or macOS systems:
```
# Set precision to 7 million bits, so I expect about 2 million valid digits
setprecision(7000000)
# Get value of pi with high precision
bigpi=BigFloat(pi)
# Calculate difference of sin(pi/2)-1. Should be zero in exact arithmetic
sin(bigpi/BigFloat(2))-1
# Calualate difference of sin(pi/6)-1/2. Should be zero in exact arithmetic
sin(bigpi/BigFloat(6))-1/BigFloat(2)
```

For the first difference I get the value of zero. That means the result of sin(pi/2) is valid up to 2 million digits.

For the seconds difference I get an value of about 4.76993...e-306923. That means sin(pi/6) is only calculated up to about 300,000 digits and not 2 million digits.

Some more details have already been discussed:
https://discourse.julialang.org/t/accuracy-of-bigfloat-calculating-sin-with-high-accuracy/4604

**Comment by simonbyrne** [comment] 2017-07-11 21:45
Anyone want to try it on 32-bit linux? Would be good to know if it's a `Clong` issue.

FWIW, there are some accuracy bounds of the implementation in http://www.mpfr.org/algorithms.pdf

**Comment by stevengj** [comment] 2017-07-12 19:23
Note that the problem seems to be specifically in the `sin` function.   If I do `big(pi)/6` in this precision on MacOS (where `sin` is accurate), the last few digits are `399664339975e-01`.  On Win64, I get exactly the same answer.

**Comment by vtjnash** [comment] 2017-07-12 20:02
For any library which uses libm where we care about numeric accuracy, we should be statically linking a copy of libopenlibm on platforms where the system libm is not accurate. We usually do this on Windows (since the old win32 crt math library was not very accurate) for many libraries. Do we know if MPFR is using libm functions though?

**Comment by simonbyrne** [comment] 2017-07-12 20:17
I wouldn't think so.

**Comment by simonbyrne** [comment] 2017-07-17 17:25
I see the same issue on a 32-bit linux VM.

**Comment by simonbyrne** [comment] 2017-07-17 17:58
Okay, this is an issue with MPFR. The code [here](https://gist.github.com/simonbyrne/0bb647059202d990c60d13d22db68a6d) on 32-bit linux gives:
```
Diff is 4.7699306332221186288894962846258624262005363580770e-306923
```

**Comment by stevengj** [comment] 2017-07-17 18:09
@simonbyrne, thanks for looking into this.  Can you send a bug report to `mpfr@inria.fr` as described [here](http://www.mpfr.org/mpfr-current/mpfr.html#Reporting-Bugs)?

**Comment by simonbyrne** [comment] 2017-07-17 18:09
Will do.

**Comment by simonbyrne** [comment] 2017-07-17 19:08
See https://sympa.inria.fr/sympa/arc/mpfr/2017-07/msg00002.html

**Comment by tkelman** [comment] 2017-07-18 03:10
looks like there's a patch already that we could try applying?

**Comment by stevengj** [comment] 2017-07-18 13:11
Great, looks like they have a fix for MPFR 3.1.   We could apply a patch before then if need be.

**Comment by stevengj** [comment] 2017-09-07 16:58
[MPFR 3.1.5 includes the fix](http://www.mpfr.org/mpfr-3.1.5/#fixed), so once we upgrade then we can delete our patch.

**Comment by simonbyrne** [comment] 2017-12-05 05:57
I just tried this on 0.6.1, which is supposed to have the fix in, but still see the issue.

**Comment by simonbyrne** [comment] 2017-12-05 06:06
Ah, it was fixed in the 3.1.6 release, not 3.1.5 (which was released over a year ago). The link @stevengj pointed to are the bugs _since_ the 3.1.5 release.

**Closed** 2017-12-05 06:06 UTC
Labels: bignums, upstream, windows

**Comment by StefanKarpinski** [comment] 2017-12-05 13:04
Should we have a Julia-side regression test for this? Defense in depth and all that.

**Comment by KristofferC** [comment] 2017-12-05 13:06
Don't we have that? https://github.com/JuliaLang/julia/commit/35011da9a9d2ebcbcfbc07d398615e2fb4260ed1#diff-26b791854ff5dbe1c3ed1392119bcf42R892
