### ISSUE TITLE
Code loading tries to `stat` a potentially unreadable file path

### ISSUE THREAD

**Issue by fredcouderc** [JuliaLang/julia#55966] opened 2024-10-02 13:20 UTC
When installing Julia on a cluster with the Spack package manager, there are a few problems with precompile.
Typically, the root user has performed an installation by issuing the command: `spack install julia@1.9.3%gcc@13.2.0`.
This creates a directory in: `/tmp/root/spack-stage` to compile Julia before installing it.
The installation finishes normally, but when a lambda cluster user calls Julia, there are problems with precompile.
Typically, you find an error like:

```bash
ERROR : LoadError : IOError : stat("/tmp/root/spack-stage/spack-stage-julia-1.10.2-2zigizyfch37c2tz5g5cu75wbnerf4zh/spack-src/usr/share/julia/stdlib/v1.10/Test/src/Test.jl ”) : permission denied (EACCES)
```

(test the SparseArrays package, for example, or even using it after adding it)

Now, if you delete the directory at its head, this seems to solve the problem, meaning that Julia tests for the presence of the installation directory, which normally results in a non-fatal file-not-found error, but in multi-user systems can result in permission denied errors instead.

**Comment by giordano** [comment] 2024-10-02 13:52
To reproduce the issue outside of Spack with the official binaries:
```julia-repl
julia> run(`sudo mkdir -p $(dirname(dirname(dirname(dirname(dirname(abspath(Sys.BUILD_STDLIB_PATH)))))))`);

julia> run(`sudo chmod o-x $(dirname(dirname(dirname(dirname(dirname(abspath(Sys.BUILD_STDLIB_PATH)))))))`);

julia> using SparseArrays
ERROR: IOError: stat("/cache/build/builder-amdci4-4/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/SparseArrays/src/SparseArrays.jl"): permission denied (EACCES)
Stacktrace:
  [1] uv_error
    @ ./libuv.jl:100 [inlined]
  [2] stat(path::String)
    @ Base.Filesystem ./stat.jl:152
  [3] samefile
    @ ./stat.jl:476 [inlined]
  [4] stale_cachefile(modkey::Base.PkgId, build_id::UInt128, modpath::String, cachefile::String; ignore_loaded::Bool)
    @ Base ./loading.jl:3118
  [5] stale_cachefile
    @ ./loading.jl:3007 [inlined]
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base ./loading.jl:1540
  [7] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1938
  [8] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1812
  [9] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [10] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [11] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1803
 [12] macro expansion
    @ ./loading.jl:1790 [inlined]
 [13] macro expansion
    @ ./lock.jl:267 [inlined]
 [14] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1753
 [15] #invoke_in_world#3
    @ ./essentials.jl:926 [inlined]
 [16] invoke_in_world
    @ ./essentials.jl:923 [inlined]
 [17] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1746
```
Looks like the `stale_cachefile` function (or something around that) is doing a useless check?

**Comment by giordano** [comment] 2024-10-02 13:57
Looks like this is fixed in v1.11, but still reproduces in v1.10 (as shown in my previous message), which is LTS.

**Comment by giordano** [comment] 2024-10-02 14:54
> Looks like this is fixed in v1.11

Actually the offending check is still there on `master`, it just happens under a different condition now: https://github.com/JuliaLang/julia/blob/fbb3e1175d52abec0ff4ca83d8c9e126d9f8a06b/base/loading.jl#L3845

**Comment by giordano** [comment] 2024-10-02 15:06
I believe this is ultimately due to the `samefile` implementation, standalone reproducer:
```
julia> mktempdir() do dir1
           file1 = joinpath(dir1, "file")
           touch(file1)
           chmod(dir1, 0o666)
           mktempdir() do dir2
               file2 = joinpath(dir2, "file")
               touch(file2)
               samefile(file1, file2)
           end
       end
ERROR: IOError: stat("/tmp/jl_Z9Orxw/file"): permission denied (EACCES)
Stacktrace:
  [1] uv_error
    @ ./libuv.jl:100 [inlined]
  [2] stat(path::String)
    @ Base.Filesystem ./stat.jl:152
  [3] samefile
    @ ./stat.jl:476 [inlined]
  [4] #16
    @ ./REPL[10]:8 [inlined]
  [5] mktempdir(fn::var"#16#18"{String}, parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:766
  [6] mktempdir (repeats 2 times)
    @ ./file.jl:762 [inlined]
  [7] #15
    @ ./REPL[10]:5 [inlined]
  [8] mktempdir(fn::var"#15#17", parent::String; prefix::String)
    @ Base.Filesystem ./file.jl:766
  [9] mktempdir(fn::Function, parent::String)
    @ Base.Filesystem ./file.jl:762
 [10] top-level scope
    @ REPL[10]:1
```

**Comment by giordano** [comment] 2024-10-02 16:53
Haven't tested it (also because I don't have a reproducer on `master`, since the logic under which this code path is hit is now different) but something like
```diff
diff --git a/base/loading.jl b/base/loading.jl
index 9080a2271fb..cfe4a9395d4 100644
--- a/base/loading.jl
+++ b/base/loading.jl
@@ -3842,10 +3842,13 @@ end
 
         # now check if this file's content hash has changed relative to its source files
         if stalecheck
-            if !samefile(includes[1].filename, modpath) && !samefile(fixup_stdlib_path(includes[1].filename), modpath)
-                @debug "Rejecting cache file $cachefile because it is for file $(includes[1].filename) not file $modpath"
-                record_reason(reasons, "wrong source")
-                return true # cache file was compiled from a different path
+            if !samefile(includes[1].filename, modpath)
+                stdlib_path = fixup_stdlib_path(includes[1].filename)
+                if isreadable(stdlib_path) && !samefile(stdlib_path, modpath)
+                    @debug "Rejecting cache file $cachefile because it is for file $(includes[1].filename) not file $modpath"
+                    record_reason(reasons, "wrong source")
+                    return true # cache file was compiled from a different path
+                end
             end
             for (modkey, req_modkey) in requires
                 # verify that `require(modkey, name(req_modkey))` ==> `req_modkey`
```
should help with avoiding trying to `stat` a file which can't be `stat`-ed.

**Closed** 2024-10-05 07:34 UTC
Labels: bug, filesystem
