### ISSUE TITLE
Solving with sparse cholesky returns two-dimensional array

### ISSUE THREAD

**Issue by clason** [JuliaLang/julia#28985] opened 2018-08-31 14:00 UTC
In v1.0, using the Cholesky decomposition of a sparse array to solve a linear system for the transpose results in a two-dimensional array instead of a vector:

```julia
using LinearAlgebra,SparseArrays
N = 4
A = sparse(I,N,N)
C = cholesky(A)
b = randn(N)
C'\b
```

returns

>4×1 Array{Float64,2}:
>...

By contrast, `C\b` (correctly) returns

>4-element Array{Float64,1}:
>...

(The corresponding test for `Array(I,N,N)` throws a `ERROR: MethodError: no method matching adjoint(::Cholesky{Float64,Array{Float64,2}})`.)

**Comment by StefanKarpinski** [comment] 2018-09-10 16:59
@Sacha0, @andreasnoack?

**Comment by andreasnoack** [comment] 2018-09-10 17:52
This is a bug and should be fixed.

**Comment by ViralBShah** [comment] 2018-12-17 07:34
Yes, we must fix this. The culprit is probably in here:
```
\(adjL::Adjoint{<:Any,<:Factor}, B::Dense) = (L = adjL.parent; solve(CHOLMOD_A, L, B))
\(adjL::Adjoint{<:Any,<:Factor}, B::VecOrMat) = (L = adjL.parent; Matrix(solve(CHOLMOD_A, L, Dense(B))))
```

**Comment by raghav9-97** [comment] 2018-12-17 08:08
I would like to work on this if nobody is currently working on it.

**Comment by ViralBShah** [comment] 2018-12-17 08:14
Go for it.

**Comment by raghav9-97** [comment] 2018-12-17 08:18
I think the problem is explicit conversion to Matrix in ```\(adjL::Adjoint{<:Any,<:Factor}, B::VecOrMat) = (L = adjL.parent; Matrix(solve(CHOLMOD_A, L, Dense(B))))```
Is that correct?

**Comment by ViralBShah** [comment] 2018-12-17 08:20
I believe the matrix and the vector cases need to be separated out.

**Comment by raghav9-97** [comment] 2018-12-17 08:35
```
\(adjL::Adjoint{<:Any,<:Factor}, B::Vector) = (L = adjL.parent; solve(CHOLMOD_A, L, Dense(B)))
\(adjL::Adjoint{<:Any,<:Factor}, B::Matrix) = (L = adjL.parent; Matrix(solve(CHOLMOD_A, L, Dense(B))))
```
Something like this??

**Comment by ViralBShah** [comment] 2018-12-17 08:58
Probably. It needs to be tried out and all tests should pass.

**Comment by andreasnoack** [comment] 2018-12-17 09:01
> Something like this??

Yes that should work. While you are at it, please allow that `B` can be `StridedVector`/`StridedMatrix`. Also, it's slightly nicer to use lower case for vectors (but still upper case for matrices). Finally, please also split the function over multiple lines instead of using `;`.

**Closed** 2018-12-17 14:53 UTC
Labels: bug, linear algebra, sparse
