### ISSUE TITLE
slow lowering of constructors with kwargs

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#27602] opened 2018-06-15 20:20 UTC
Lowering for constructors defined with kwargs is vary bad: it guarantees we can't infer anything about it and also must do a dynamic dispatch. Simple repro:

```julia
julia> struct CS
       CS(; bool=false) = new()
end

julia> code_typed(CS, ())
1-element Array{Any,1}:
 CodeInfo(
2 1 ─ %1 = Core.isdefined(:($(QuoteNode(Core.Box(getfield(Main, Symbol("##CS#12#13"))())))), :(:contents))::Bool
  └──      goto 3 if not %1                                                 │
  2 ─      goto 4                                                           │
  3 ─      $(Expr(:throw_undef_if_not, Symbol("#CS#12"), false))            │
  4 ┄ %5 = Core.getfield(:($(QuoteNode(Core.Box(getfield(Main, Symbol("##CS#12#13"))())))), :(:contents))::Any
  │   %6 = %5(false, %%#self#)::Any                                         │
  └──      return %6                                                        │
) => Any
```

Note that the return type is `Any` and `%6` is required to be a dynamic dispatch

**Comment by JeffBezanson** [comment] 2018-06-15 20:29
Probably same issue as #19668?

**Comment by vtjnash** [comment] 2018-06-15 20:35
Looks very similar, now it's just used more, so it shows up as costly during startup

**Comment by JeffBezanson** [comment] 2018-06-19 20:54
Looking into this now. I'm pretty sure this can be closed as a dup.

**Closed by JeffBezanson** 2018-06-19 20:54 UTC
Labels: lowering, performance

**Comment by JeffBezanson** [comment] 2018-06-19 22:53
It's somewhat related, but the problem in the OP here is much simpler since it doesn't involve any "recursive" (`letrec`-style) bindings. Fixing the recursive case will require some new tricks. The problem is that in general, `g` needs to capture the binding for `g` before it's assigned. But in this case, we know what value will be assigned and need to add code to take advantage of that.

**Comment by vtjnash** [comment] 2018-06-19 22:55
In this case too, it's also question of whether the `g` in the function is an argument or not. That makes a big semantic difference if `g` is reassigned.
