### ISSUE TITLE
Difference in Float32 parsing on Windows and Linux

### ISSUE THREAD

**Issue by jakobnissen** [JuliaLang/julia#55019] opened 2024-07-03 18:05 UTC
This code:
```julia
parse(Float32, "2e300")
```
Throws an error on Linux, but returns `Inf32` on Windows.
This reproduces all the way back to Julia 1.0.5.
Ideally, parsing should behave identically on the two platforms.

**Comment by vtjnash** [comment] 2024-07-03 20:45
We have had some discussion of switching to llvm's float parser in the past, since we already include it, and it is known to handle cases like this correctly and probably fairly fast

**Comment by oscardssmith** [comment] 2024-07-04 04:17
imo the ideal case would be for us to switch to the parsers.jl implementation which JuliaSyntax uses since then it's pure Julia and can inline/const fold etc

**Comment by KristofferC** [comment] 2024-07-04 07:50
> switch to the parsers.jl implementation which JuliaSyntax uses

Does JuliaSyntax use it?

https://github.com/JuliaLang/JuliaSyntax.jl/blob/f425045d56f75c71493aba77e1b751f69f552e48/src/literal_parsing.jl#L134

**Comment by ararslan** [comment] 2024-07-11 23:49
This is a duplicate of #46544. That issue is actually [referenced](https://github.com/JuliaLang/JuliaSyntax.jl/blob/f425045d56f75c71493aba77e1b751f69f552e48/src/literal_parsing.jl#L166) in a comment in the JuliaSyntax float parsing code (which as Kristoffer noted does not use Parsers.jl, it calls Julia's C float parser).

**Closed by ararslan** 2024-07-11 23:49 UTC
Labels: kind:bug
