### ISSUE TITLE
Feel very painful for maintaining packages

### ISSUE THREAD

**Issue by sfchen** [JuliaLang/julia#16681] opened 2016-05-31 08:45 UTC
I am the starter of OpenGene projects (https://github.com/OpenGene), most of my projects are in Julia.

Recently I started to feel very painful to maintain my packages: too many version conflicts, too many deprecations, too many functions/types not found.

My packages are not working with both Julia 0.4 or master, due to lots of depending packages not working, such like Dataframes, Libz...

I think Julia should converge to a stable version ASAP, otherwise lots of package developers will have the same feeling like me.

**Comment by yuyichao** [comment] 2016-05-31 12:33
While I totally feel your pain, I don't think there's much we can do here. We are already very careful about breaking things and will usually print a depwarn instead of breaking code (i.e. changing behavior) whenever we can. We are indeed breaking a lot of stuff on master but that's also because we want to break them to reach stable as early as possible.

While we really appreciate the testing done by packages that works on master, which helps catching bugs early, supporting master is usually not a requirement for packages in the middle of the development cycle. So unless your package needs master feature (which shouldn't be the case if you want to support 0.4) you should feel free to not support master unless someone else needs it and submit a pull request. There should also be a period of a few weeks after 0.5 feature freeze and rc1 release when there should be no breaking anymore and packages can be fixed (usually with helps from the community) within that period.

Closing as I don't think there's any action item here.

**Closed by yuyichao** 2016-05-31 12:33 UTC

**Comment by tkelman** [comment] 2016-05-31 13:16
If something used to work on 0.4 and somehow broke while still on 0.4, please report it to the relevant package - that should really not happen if people are careful, and we'll do what we can to fix it.

**Comment by IainNZ** [comment] 2016-05-31 21:11
@sfchen, the entire JuliaOpt suite of projects is probably one of the larger intergrated package codebases, but I must say we don't have these problems because we actively chose not to. We simply do not place a high priority on supporting 0.5, and most of the people developing the packages and 99% of our users don't want to use anything other than 0.4 anyway. We also try to be careful with our package REQUIRE files, to ensure we have known-good dependencies, even putting upper limits on versions if needed. I'd recommend you adopt a policy for what you will support that you can feasibily maintain, and communicate that to your users - it saves a lot of pain.

**Comment by timholy** [comment] 2016-05-31 21:42
One good reason to rework your code to support julia-0.4 (which has been the stable release for about a year now): julia-0.4 will give you helpful tips about how to fix any breakages that occur from 0.3->0.4. But with julia-0.5, those helpful tips will be deleted, and you'll just get errors. So long term you will probably have an easier path if you upgrade to julia-0.4 now.

**Comment by Keno** [comment] 2016-05-31 22:36
I sympathize here. Using julia on master is a pretty bad experience due to how many packages are broken. Plus PkgEvaluator for testing base julia changes doesn't give much information if the packages are broken. Luckily we're rapidly converging on 0.5.

**Comment by IainNZ** [comment] 2016-05-31 22:46
> Plus PkgEvaluator for testing base julia changes doesn't give much information if the packages are broken

What additional information do you need from it?

**Comment by tkelman** [comment] 2016-05-31 22:50
I think Keno's point is that broken packages on nightly are not useful for detecting regressions or unintentionally breaking changes on master. For example there are some failures in JuMP that as far as I can tell are bugs in base, just haven't had time to reduce them yet. Being aware of and reporting these things early helps with base development, but I think the burden of that does have to lie with those doing the base development, not package authors.

**Comment by sfchen** [comment] 2016-05-31 23:50
Thanks every one, I think part of my pain was caused by

`WARNING: Cannot perform fast-forward merge.` for Pkg.update()

This issue blocks any updating of METADATA and then it makes a lot of package requirement failing.

After a manual `git pull` on METADATA folder it gets a bit better. `git pull` didn't give any warning.

I don't know why it cannot perform fast-forward merge (maybe due to I submitted some commits before). But definitely this WARNING message should be revised to alert user to manually update using native git commands.

**Comment by tkelman** [comment] 2016-05-31 23:56
You likely have local commits that don't exist in upstream metadata. Normal `git pull` creates a merge commit by default, Pkg.update tries to do a pull with rebase. If you have merge commits, the history od your metadata branch will always diverge from upstream, you won't have any common commits with upstream and these merge commits will keep showing up if you try to tag or register packages. If you rebase instead, then your local commits will always be the most recent, and the majority of the metadata history will be exactly as it was upstream. I would look into why you were unable to rebase, and what differs between your local metadata copy and upstream.

**Comment by wildart** [comment] 2016-06-01 00:52
@sfchen `Pkg.update` warning indicates that your METADATA has some changes that are not present in the remote, and after that update tries to rebase your changes. If you don't get any error from update than your METADATA should be updated. BTW, try to update your 0.5-dev version often.

**Comment by ViralBShah** [comment] 2016-06-01 19:43
I guess the only good news is that we are converging on 0.5 soon, and the pace of breaking changes will naturally slow down as we march towards 1.0.

**Comment by pkofod** [comment] 2016-06-02 19:46
It can be a real pain to maintain code. That is why a lot of people require a lot of money to do it. So when you're writing open source code, it's very annoying when you have to keep working hours and hours on maintenance at the expense of adding features.

However, if you're looking at the changes that arrived with v0.3 first, and later v0.4 I think you can't help but realize why it was a good thing to have breaking changes. Rushing to the finish line (v1.0) is only going to make things worse, as many of the features that the devs and community wants are simply, well, breaking. If v1.1 introduces many breaking changes, JuliaLang is potentially going to get a lot of negative PR as a result.

Officially supporting master is a time-consuming thing. Of course it makes sense to run your package against master sometimes. For one thing you get to keep track of all the changes we're seeing all the time. Sometimes you can make adjustments such that it still works on v0.4 and v0.5, and. honestly, most of the time Compat.jl lives up to it's goal.

There is the occasional large breaking change, but it doesn't happen that often, and it certainly shouldn't happen on the release version (v0.4 currently). If a function suddenly disappears (as you mentioned) on the release version, it is very much worthy of a bug report.

Hope the METADATA problem was sorted out :)
