### ISSUE TITLE
Julia release 0.4 build error: cdefs-compat.h: No such file or directory

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/julia#13530] opened 2015-10-10 11:36 UTC
I got the error below when running the Julia `make`.  But going to `deps\openspecfun` and running `make` there seemed to work fine, and I was able to continue the Julia `make` afterward.

```
uname -a
Linux giada.mitre.org 2.6.32-431.29.2.el6.x86_64 #1 SMP Sun Jul 27 15:55:46 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.7 (Santiago)

gcc --version
gcc (GCC) 4.8.2

git --version
git version 2.5.0
(but the default gcc and git on this system are older)
....
make[1]: *** [openspecfun/Makefile] Error 129
make: *** [julia-deps] Error 2
[keithc@giada julia]$ make
In file included from /devel/asias/keithc/julia/usr/include/openlibm.h:4:0,
                 from Faddeeva/Faddeeva.cc:225,
                 from Faddeeva/Faddeeva.c:3:
/devel/asias/keithc/julia/usr/include/openlibm_complex.h:27:0: warning: "_Complex_I" redefined [enabled by default]
 #define _Complex_I 1.0fi
 ^
In file included from Faddeeva/Faddeeva.h:31:0,
                 from Faddeeva/Faddeeva.cc:218,
                 from Faddeeva/Faddeeva.c:3:
/usr/include/complex.h:45:0: note: this is the location of the previous definition
 #define _Complex_I (__extension__ 1.0iF)
 ^
In file included from /devel/asias/keithc/julia/usr/include/openlibm_fenv.h:8:0,
                 from /devel/asias/keithc/julia/usr/include/openlibm.h:5,
                 from Faddeeva/Faddeeva.cc:225,
                 from Faddeeva/Faddeeva.c:3:
/devel/asias/keithc/julia/usr/include/openlibm_fenv_amd64.h:32:26: fatal error: cdefs-compat.h: No such file or directory
 #include "cdefs-compat.h"
                          ^
compilation terminated.
make[2]: *** [Faddeeva/Faddeeva.c.o] Error 1
make[1]: *** [openspecfun/libopenspecfun.so] Error 2
```

**Comment by ihnorton** [comment] 2015-10-10 22:56
Closing as duplicate of #12582. If this comes back, leave a comment and will reopen. (could try `make -C deps/ distclean-openspecfun`)

**Closed by ihnorton** 2015-10-10 22:56 UTC
Labels: build

**Comment by catawbasam** [comment] 2015-10-11 09:55
This turned to be a LD_LIBRARY_PATH issue -- I needed to add paths to my non-default git and gcc versions, and then everything built.  So no need to re-open.
