### ISSUE TITLE
anonymous functions are inconsistent when defined inside if

### ISSUE THREAD

**Issue by jonso99** [JuliaLang/julia#42988] opened 2021-11-07 07:45 UTC
I am running 1.63 on intel mac and 1.7 beta on M1 mac. both have this.  Julia is inconsistent in how it creates anonymous functions with an if statement. If I create one outside of a function it respects the if, but not inside. 

here is output that should be the same
julia> f3()
f2
julia> fff()
f1

and the code
```
function f1()
    println("f1")
end
function f2()
    println("f2")
end
f3=function()
    if 1==1
        ff()=f1()
    end
    if 1==2
        ff()=f2()
    end
    ff()
end
if 1==1
    fff()=f1()
end
if 1==2
    fff()=f2()
end
fff()
f3()
```

**Comment by giordano** [comment] 2021-11-07 09:39
Duplicate of #15602

**Closed** 2021-11-07 09:45 UTC
