### ISSUE TITLE
Return type annotation doesn't work with assignment form

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#23163] opened 2017-08-07 14:53 UTC
```julia
julia> foo(x::T)::Bool where {T} = true
ERROR: UndefVarError: T not defined
```

**Comment by yuyichao** [comment] 2017-08-07 14:55
```julia
julia> (foo(x::T)::Bool) where {T} = true
foo (generic function with 1 method)
```

**Comment by JeffBezanson** [comment] 2017-08-07 14:56
Yes, this is a tough one. `a::b where c` is parsed as `a::(b where c)`, since that would be the only sensible interpretation in every context except this one. There aren't even any context clues until we get to the `=`, at which point it's too late. Not sure what to do here.

**Comment by andreasnoack** [comment] 2017-08-07 14:59
Can't comment on the parsing aspects but we should add an example/comment to https://docs.julialang.org/en/stable/manual/types/#Type-Declarations-1 if it can't be fixed.

**Comment by StefanKarpinski** [comment] 2017-08-07 16:39
What about disallowing type annotations on short-form functions entirely? They're not super useful anyway. Throwing an error would be better here than giving a surprising interpretation.

**Comment by rfourquet** [comment] 2017-08-07 16:46
Dupe of #21847.

**Closed by rfourquet** 2017-08-07 16:46 UTC

**Comment by haampie** [comment] 2017-08-08 10:58
@StefanKarpinski it could make functions with ternary operators a bit more readable.

```julia
f(x::T)::Float64 where {T} = some_condition(x) ? do_foo(x) : do_bar(x)
```

**Comment by StefanKarpinski** [comment] 2017-08-08 16:11
@haampie, please read @JeffBezanson's comments on this. I'm not just being arbitrarily grinchy here because I don't want you to be able to write that. It is **technical infeasible** to parse a return type annotation with a where clause on a short-form method – it would requires infinite backtracking, which our parser doesn't and won't support.
