### ISSUE TITLE
docs call julia function as python functions

### ISSUE THREAD

**Issue by musmo** [JuliaLang/julia#14989] opened 2016-02-08 15:19 UTC
See:
![image](https://cloud.githubusercontent.com/assets/4319522/12889519/4d06f3f6-ce4d-11e5-9f36-b2e05f96cccc.png)

This could be confusing to newcomers, who may misinterpret this as julia calling python these python function.

**Comment by swt30** [comment] 2016-02-08 15:26
Duplicate of https://github.com/JuliaLang/julia/issues/11527

**Closed** 2016-02-08 15:35 UTC
