### ISSUE TITLE
@cfunction segfaults for function that isn't type stable

### ISSUE THREAD

**Issue by danielmatz** [JuliaLang/julia#32251] opened 2019-06-05 21:36 UTC
Using `@cfunction` on a function without a stable return type and then calling the function through the returned function pointer produces a segfault.  We discussed this on [discourse](https://discourse.julialang.org/t/can-a-functionwrapper-be-used-with-a-function-that-isnt-type-stable/24977), where we came up with several simple cases to reproduce the issue.  The simplest one seems to be:

```julia
julia> f(x) = x ? 1 : 2.0
f (generic function with 1 method)

julia> fptr = @cfunction(f, Any, (Bool,))
Ptr{Nothing} @0x00007effcbe85e00

julia> ccall(fptr, Any, (Bool,), true)
Unreachable reached at 0x7effcbe85f2a

signal (4): Illegal instruction
```

**Comment by JeffBezanson** [comment] 2019-06-05 21:41
Looks like a possible duplicate of #26078.

**Comment by tkoolen** [comment] 2019-06-05 22:09
Might also be related to https://github.com/JuliaLang/julia/issues/28669 - at least in that the end result is an `@cfunction`-related segfault.

**Comment by yuyichao** [comment] 2019-06-05 22:31
No #28669 is an inference issue and it doesn't segfault. This is a codegen issue and it seems that the c calling convention generator couldn't handle the small union calling convention.

**Comment by tkoolen** [comment] 2019-06-05 23:46
Ah yes, I misremembered.

**Closed** 2020-03-15 20:54 UTC
