### ISSUE TITLE
isapprox() comparison to zero

### ISSUE THREAD

**Issue by jlumpe** [JuliaLang/julia#32244] opened 2019-06-05 01:04 UTC
Note: this is kind of a duplicate of #23376, which was closed but no one had suggested this particular solution. Would the better etiquette have been to comment there instead of opening a new issue?

The docstring for `isapprox()` gives a clear explanation of why it doesn't really work for one of the arguments be zero. However, I think there would be a lot of utility in including an `isapproxzero()` function that uses the same comparison method but the scale for `rtol` is set using an explicit argument. An example implementation would be as follows:

```julia
function isapproxzero(x, scale; atol::Real=0, rtol::Real=atol>0 ? 0 : sqrt(eps()))
    norm(x) <= atol + rtol * norm(scale)
end
```

I ran into this when trying to check whether x is approximately fixed point of a function by checking the function's derivative is close to zero at that point, relative to the value of f(x). I think it's pretty broadly applicable, though.

**Comment by stevengj** [comment] 2019-06-07 16:59
What's the advantage of that over just writing `norm(x) ≤ atol`, or `norm(x) ≤ rtol*norm(scale)`, or just passing `atol=rtol*norm(scale)`?

`norm(x) ≤ rtol*norm(scale)` seems a lot clearer to me than `isapproxzero(x, scale, rtol=rtol)`.

**Comment by stevengj** [comment] 2019-06-07 17:01
In any case, I would recommend closing this as a duplicate of #23376.  You can always comment on that issue if you feel it merits further discussion — I don't think your proposal is too different from what was proposed there.

**Comment by StefanKarpinski** [comment] 2019-06-10 17:06
Closing as a duplicate of a closed issue is pretty much the same as rejecting something, but fwiw the comparisons with the norm seem clearer to me as well.

**Comment by jlumpe** [comment] 2019-06-11 17:44
I think there are a couple of advantages - although I don't necessarily disagree with your counterexamples. The main advantage is that it works as closely as possible to `isapprox()`, so that `isapprox(x, y; ...)` is very close to `isapproxzero(x - y, x; ...)` (including handling of default arguments). I mostly envision it being useful from within another function that just passes on the `atol` and `rtol` arguments. These are pretty common arguments for a lot of numerical algorithms and it's commonly understood what they mean, so you can pass those on to either or both comparison functions and know they'll be interpreted the same way. Sure it's not a lot to write out explicitly but if you don't know ahead of time whether you'll get a value for `rtol` or `atol` or both it's extra boilerplate to add those cases.

**Closed** 2023-01-17 03:58 UTC
Labels: speculative, maths

**Comment by gaurav-arya** [comment] 2023-02-19 17:52
One disadvantage to manually providing `atol` is that it seems to be most naturally expressed as `rtol*scale`, but to write that the user needs to first compute `rtol` using `Base.rtoldefault(...)` (and know about that function). So for this reason, I wouldn't mind something like a special `rtol_scale` argument to `isapprox` that defaults to `0.`, makes the relative threshold something like `rtol*max(norm(x), norm(y), rtol_scale)`, and is documented to help for the use case of comparing with 0.

**Comment by gaurav-arya** [comment] 2023-02-19 17:58
Although, another solution is to simply write `nearly_zero1 + scale ≈ nearly_zero2 + scale`, which doesn't require knowing how to compute `rtol`. If this solution doesn't have caveats, perhaps it could simply be added to the `isapprox` docstring as a simpler alternative to manually computing `atol`.

**Comment by stevengj** [comment] 2023-02-19 20:38
Adding a scale (rather than passing `atol`) seems a bit obscure to me … and it's more awkward if you are comparing vectors instead of scalars.
