### ISSUE TITLE
Pkg.init() and Pkg.update() fails

### ISSUE THREAD

**Issue by Mirage10** [JuliaLang/julia#13972] opened 2015-11-13 12:50 UTC
Hello julia community!

I am facing big problems with Julia packages: Pkg.init() and Pkg.update() are not working. I have scanned the internet regarding the message, but nothing seems to be the right solution. I have already had a long odyssey ...
This seems to be an frequent trap. So it might be advantageous to be more clear in the installation chapter of julia.

    Pkg.init()     
   displays the following :

    INFO: Initializing package repository /home/user/.julia/v0.5
    INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
    ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:140E0114:SSL routines:SSL_shutdown:uninitialized)
     [inlined code] from libgit2/error.jl:98
     in clone at libgit2/repository.jl:189
     in __clone#364__ at libgit2.jl:310
     in anonymous at pkg/dir.jl:49
     in cd at file.jl:47
     in init at pkg/dir.jl:47
     in init at pkg.jl:22
     in eval at ./boot.jl:264

by the way:

    sudo git pull
    sudo make

works fine! The only thing is, that I cannot install packages in Julia. My computer is behind the proxy. The proxy settings for git seems to be correct

System environment 
Linux Mint 17.02  (based on Ubuntu 14.04)

newest julia from github
    ~/julia $ sudo ./julia
               _
     _       _ _(_)_     |  A fresh approach to technical computing
    (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
     _ _   _| |_  __ _   |  Type "?help" for help.
    | | | | | | |/ _` |  |
   | | |_| | | | (_| |  |  Version 0.5.0-dev+1265 (2015-11-13 08:40 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit f045831 (0 days old master)
|__/                   |  x86_64-linux-gnu

**Comment by tkelman** [comment] 2015-11-13 13:37
duplicate of https://github.com/JuliaLang/julia/issues/13472
see #13952

**Closed by tkelman** 2015-11-13 13:37 UTC
Labels: packages

**Comment by Mirage10** [comment] 2015-11-13 14:09
It still seems not to be clear, what needs to be done. Therefore I would like to reopen this issue.

**Comment by tkelman** [comment] 2015-11-13 14:11
Make the modification shown in https://github.com/JuliaLang/julia/pull/13952/files, then do `make -C deps distclean-libgit2 && make test-pkg`.

**Comment by Mirage10** [comment] 2015-11-13 14:26
@tkelman : Thank you so much! your last post exactly solves my problem. cool!

**Comment by mronian** [comment] 2016-03-18 15:32
@tkelman I am facing the same issue with Pkg. I tried the solution you mentioned above, but the ```make``` fails with a pkg-config not found error if I modify the flag.

**Comment by tkelman** [comment] 2016-03-18 15:59
What platform? Install pkg-config? Though it shouldn't be an error if you don't have pkg-config installed.

**Comment by mronian** [comment] 2016-03-19 04:37
Ubuntu 14.04 LTS. I looked through some of the related issues and tried the approaches. #13472 worked for me in the end. Thanks!

**Comment by mronian** [comment] 2016-03-19 04:43
Ubuntu 14.04 LTS. I tried some of the approaches mentioned in related issues. #13472 worked for me in the end. Thanks!
