### ISSUE TITLE
Autocompletion after selective `using`

### ISSUE THREAD

**Issue by carstenbauer** [JuliaLang/julia#53524] opened 2024-02-29 11:32 UTC
```julia
using Package: something
somet<TAB> # doesn't work :(
```

Especially disappointing when `something == Package`:
```julia
using Package: Package
Packa<TAB> # doesn't work :(
```

Note that this works (of course):
```julia
import Package # or using
Packa<TAB> # works :)
```

**Comment by jakobnissen** [comment] 2024-02-29 11:59
Might be a duplicate of https://github.com/JuliaLang/julia/issues/49109

**Closed** 2024-05-31 06:55 UTC
Labels: stdlib:REPL
