### ISSUE TITLE
DataFrames.jl tests segfault on 1.7.0-rc1 Apple M1

### ISSUE THREAD

**Issue by tpgillam** [JuliaLang/julia#42412] opened 2021-09-28 16:33 UTC
System is an M1 Macbook Air. Julia info:

```
julia> versioninfo()
Julia Version 1.7.0-rc1
Commit 9eade6195e (2021-09-12 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.5.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```

Starting from a clean installation, I did

```
] add DataFrames
] test DataFrames
```

The latter call ran many tests successfully, but then emitted a segfault as here:

```
Test Summary:                    | Pass  Total
stack view=true additional tests |    2      2
        PASSED: reshape.jl

signal (11): Segmentation fault: 11
in expression starting at /Users/gillam/.julia/packages/DataFrames/vuMM8/test/dataframerow.jl:12
ntuple at ./ntuple.jl:0 [inlined]
NamedTuple at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/dataframerow/dataframerow.jl:427
copy at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/dataframerow/dataframerow.jl:442
unknown function (ip: 0x2980b19bb)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
macro expansion at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
macro expansion at /Users/gillam/.julia/packages/DataFrames/vuMM8/test/dataframerow.jl:20 [inlined]
macro expansion at /Users/sabae/src/julia/usr/share/julia/stdlib/v1.7/Test/src/Test.jl:1282 [inlined]
top-level scope at /Users/gillam/.julia/packages/DataFrames/vuMM8/test/dataframerow.jl:13
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
include_string at ./loading.jl:1196
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_include at ./loading.jl:1253
include at ./client.jl:451
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
top-level scope at /Users/gillam/.julia/packages/DataFrames/vuMM8/test/runtests.jl:50
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
include_string at ./loading.jl:1196
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_include at ./loading.jl:1253
include at ./client.jl:451
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
do_call at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_interpret_toplevel_thunk at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
exec_options at ./client.jl:268
_start at ./client.jl:495
jfptr__start_33611 at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
true_main at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_repl_entrypoint at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
Allocations: 516343408 (Pool: 513344936; Big: 2998472); GC: 1050
ERROR: Package DataFrames errored during testing (exit code: 139)
```

(I am surprised I'm seeing the `/Users/sabae` path in this output. It doesn't exist on my system.)

Re-running `] test DataFrames` resulted in another segfault, although this time at a different point in the tests:

```
Test Summary:          | Pass  Total
non standard selectors |    4      4

signal (11): Segmentation fault: 11
in expression starting at /Users/gillam/.julia/packages/DataFrames/vuMM8/test/sort.jl:150
ntuple at ./ntuple.jl:0 [inlined]
DFPerm at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:116
unknown function (ip: 0x2980fa323)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
ordering at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:170
ordering at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:212
#sortperm#754 at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:512
unknown function (ip: 0x2980f80ab)
sortperm##kw at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:503 [inlined]
#sort#753 at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:438 [inlined]
sort at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:438 [inlined]
sort at /Users/gillam/.julia/packages/DataFrames/vuMM8/src/abstractdataframe/sort.jl:438
unknown function (ip: 0x2980f440f)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
do_call at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_interpret_toplevel_thunk at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
include_string at ./loading.jl:1196
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_include at ./loading.jl:1253
include at ./client.jl:451
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
top-level scope at /Users/gillam/.julia/packages/DataFrames/vuMM8/test/runtests.jl:50
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
include_string at ./loading.jl:1196
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
_include at ./loading.jl:1253
include at ./client.jl:451
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
do_call at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval_body at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_interpret_toplevel_thunk at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_flex at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_toplevel_eval_in at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
eval at ./boot.jl:373 [inlined]
exec_options at ./client.jl:268
_start at ./client.jl:495
jfptr__start_33611 at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply_generic at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
true_main at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
jl_repl_entrypoint at /Applications/Julia-1.7.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.7.dylib (unknown line)
Allocations: 585978915 (Pool: 582952489; Big: 3026426); GC: 1114
ERROR: Package DataFrames errored during testing (exit code: 139)
```

**Comment by bkamins** [comment] 2021-09-28 18:17
The first reported offending line is:
```
ntuple(i -> dfr[i], length(dfr))
```
where `dfr` is a type unstable indexable object.

The second reported offending line is:
```
ntuple(i -> df[!, i], ncol(df))
```
where again `df` is a type unstable indexable object.

So it seems that something around `ntuple` when type inference is not possible at compile time fails.

**Comment by giordano** [comment] 2021-09-29 13:40
Duplicate of #41440

**Comment by DilumAluthge** [comment] 2021-09-29 13:42
Duplicate of #41440

**Closed by DilumAluthge** 2021-09-29 13:42 UTC
Labels: apple silicon
