### ISSUE TITLE
`@test_deprecated` has wrong return value when --depwarn=error

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#47308] opened 2022-10-24 12:53 UTC
According to https://docs.julialang.org/en/v1.9-dev/stdlib/Test/#Test.@test_deprecated

```julia
using Test
@deprecate f() 7
@test (@test_deprecated f()) == 7
```

should pass, and it does by default and with `--depwarn=yes`, but with `--depwarn=error` it fails because `@test_deprecated` returns a `Test.Pass` instead of 7.

The example is also out of date (pre-1.0)

**Comment by devmotion** [comment] 2024-12-12 13:40
Seems to be a duplicate of https://github.com/JuliaLang/julia/issues/36167?

**Closed** 2024-12-12 13:58 UTC
Labels: testsystem
