### ISSUE TITLE
Crash on overloading map on parametric struct with two Unions

### ISSUE THREAD

**Issue by evetion** [JuliaLang/julia#29269] opened 2018-09-19 18:49 UTC
The following crashes in 0.7 and 1.0. I cannot reproduce this without parametric types or without at least two Unions in the struct.

```julia
struct Test{T}
    A::Array{Union{Missing, T},1}
    x::Union{Nothing, Int}
end

Base.map(f, t::Test) = Test(map(f, t.A), 1)

t = Test([missing, 1], 1)

Test(map(x->x, t.A), 1)  # works
map(x->x, t)  # crash
```

Versioninfo:
```julia
versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
```

The crash message:
```julia
Unreachable reached at 0x11ad423a4

signal (4): Illegal instruction: 4
in expression starting at /Users/epta/.julia/v0.7/GeoRaster/crash.jl:12
map at /Users/epta/.julia/v0.7/GeoRaster/crash.jl:7
jl_fptr_trampoline at /Users/osx/buildbot/slave/package_osx64/build/src/gf.c:1829
do_call at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:324
eval_stmt_value at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:363 [inlined]
eval_body at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:686
jl_interpret_toplevel_thunk_callback at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:799
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x11492a85f)
unknown function (ip: 0x6)
jl_interpret_toplevel_thunk at /Users/osx/buildbot/slave/package_osx64/build/src/interpreter.c:808
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:831
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx64/build/src/ast.c:841
jl_load at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:865 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx64/build/src/toplevel.c:872
include at ./boot.jl:317 [inlined]
include_relative at ./loading.jl:1038
include at ./sysimg.jl:29
exec_options at ./client.jl:239
_start at ./client.jl:432
true_main at /Applications/Julia-0.7.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-0.7.app/Contents/Resources/julia/bin/julia (unknown line)
Allocations: 581374 (Pool: 581270; Big: 104); GC: 0
[1]    18287 illegal hardware instruction  /Applications/Julia-0.7.app/Contents/Resources/julia/bin/julia crash.jl
```

Code_typed:
```julia
print(@code_typed map(x->x, t))
CodeInfo(
7 1 ─ %1 = (Base.getfield)(t, :A)::Array{Union{Missing, Int64},1}
  │   %2 = %new(Generator{Array{Union{Missing, Int64},1},##5#6}, ##5#6(), %1)::Generator{Array{Union{Missing, Int64},1},##5#6}
  │   %3 = invoke Base._collect(%1::Array{Union{Missing, Int64},1}, %2::Base.Generator{Array{Union{Missing, Int64},1},getfield(Main, Symbol("##5#6"))}, $(QuoteNode(Base.EltypeUnknown()))::Base.EltypeUnknown, $(QuoteNode(Base.HasShape{1}()))::Base.HasShape{1})::Array
  │        (Main.Test)(%3, 1)::Union{}
  │        $(Expr(:unreachable))::Union{}
  └──      $(Expr(:unreachable))::Union{}
) => Union{}%
```

**Comment by JeffBezanson** [comment] 2018-09-20 22:27
Thanks for the detailed report. I believe this is the same type intersection issue as #29208 .

**Comment by JeffBezanson** [comment] 2018-09-26 20:42
Ok, having made some progress on #29208 I believe this is a slightly different issue.

**Comment by JeffBezanson** [comment] 2018-09-27 16:10
Ah, seems to be a duplicate of #25752.

**Comment by evetion** [comment] 2018-09-27 18:34
Good to know! So your WIP fix a19ca46 also applies to #25752?

**Comment by JeffBezanson** [comment] 2018-09-27 21:03
Yes.

**Comment by JeffBezanson** [comment] 2018-11-27 19:53
Closing as dup of #25752.

**Closed by JeffBezanson** 2018-11-27 19:53 UTC
Labels: bug, types and dispatch
