### ISSUE TITLE
"Edit on github" broken for distributed.jl 

### ISSUE THREAD

**Issue by alex-s-gardner** [JuliaLang/julia#51783] opened 2023-10-19 19:30 UTC
The "Edit on Github" link is broken: https://docs.julialang.org/en/v1/stdlib/Distributed/

<img width="1151" alt="Screenshot 2023-10-19 at 12 28 11 PM" src="https://github.com/JuliaLang/julia/assets/32276930/1b3c6b39-ad53-4410-981c-5434573e9bea">

**Comment by Pangoraw** [comment] 2023-10-19 20:01
This seems like a duplicate of https://github.com/JuliaLang/julia/issues/50035.

**Closed** 2023-10-19 20:43 UTC
