### ISSUE TITLE
Many `Exception` subtypes don't accept an error message

### ISSUE THREAD

**Issue by ssfrr** [JuliaLang/julia#14600] opened 2016-01-08 04:32 UTC
Some error types, like `ErrorException` and `ArgumentError` accept a string argument, but others (e.g. the ones defined in [boot.jl](https://github.com/JuliaLang/julia/blob/0845e8f76c222686156335a80c92d5eaf2f0456b/base/boot.jl#L224-L232) do not.

Would a PR be accepted that added optional message fields to these error types? I came across this when throwing an `InexactError` and wanting to describe why the given value didn't fit into my type.

**Comment by KristofferC** [comment] 2016-01-08 04:50
AFAIK the problem is performance when GC frames are created for the strings. Pretty sure there are discussions about it in some issue but can't find it

**Comment by KristofferC** [comment] 2016-01-08 04:54
#12152 and #9693

**Comment by timholy** [comment] 2017-07-11 10:05
Fixed by #20005

**Closed by timholy** 2017-07-11 10:05 UTC
Labels: error handling
