### ISSUE TITLE
Allow compound assignment with all binary operators

### ISSUE THREAD

**Issue by DillonEthier** [JuliaLang/julia#28357] opened 2018-07-30 15:13 UTC
I noticed that compound assignment won't work with certain operators, like |> and ∘.

For example, the following code gives the error "ERROR: syntax: unexpected "="" on line 2:
``` 
a = 2
a |>= exp 
```

But if I say, redefine the * operator as |>, it works perfectly:
```
import Base.*
* = |>
a = 2
a *= exp
```
outputs 7.389, as it should. The same thing happens with the function composition operator. So clearly the language is able to do this, the parser just doesn't handle it properly with all operators. I tried this in both 0.6.4 and 0.7 and got the same results. Is there some deeper reason why this doesn't currently work?

**Comment by stevengj** [comment] 2018-07-30 16:47
It's not really a "deep" reason, but right now the parser code uses an [explicit list of assignment operators](https://github.com/JuliaLang/julia/blob/d8efd75a051b65a7fa77c44fb380f3aa7789746d/src/julia-parser.scm#L10) and a corresponding explicit [list of lowering rules](https://github.com/JuliaLang/julia/blob/d8efd75a051b65a7fa77c44fb380f3aa7789746d/src/julia-syntax.scm#L2206-L2236).   It's impractical to extend this approach to all possible binary operators, so some surgery on the parsing/lowering code would be required.

**Comment by JeffBezanson** [comment] 2018-07-31 19:15
duplicate of #15964

**Closed by JeffBezanson** 2018-07-31 19:15 UTC
Labels: parser, speculative
