### ISSUE TITLE
cmdlineargs test fails with mkl

### ISSUE THREAD

**Issue by calmip** [JuliaLang/julia#30390] opened 2018-12-14 13:28 UTC
Tried to compile julia 1.0.3. Compilation OK, but 4 tests fail when `make -i testall`:

```
Error in testset cmdlineargs:
Test Failed at /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:422
  Expression: success(#= /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:422 =# @cmd("\$exename -e \"exit(0)\""))
Error in testset cmdlineargs:
Test Failed at /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:425
  Expression: success(#= /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:425 =# @cmd("\$exename -e \"exit(!(Base.load_path() == []))\""))
Error in testset cmdlineargs:
Test Failed at /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:425
  Expression: success(#= /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:425 =# @cmd("\$exename -e \"exit(!(Base.load_path() == []))\""))
Error in testset cmdlineargs:
Test Failed at /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:425
  Expression: success(#= /tmpdir/sysinst/julia/julia/test/cmdlineargs.jl:425 =# @cmd("\$exename -e \"exit(!(Base.load_path() == []))\""))
```
Here is the Make.user:
```
prefix = /usr/local/julia/1.0.3
USEIFC = 1
USE_INTEL_MKL = 1
USE_INTEL_MKL_FFT = 1
```
Using mkl rel 19.2 and gcc:
 ```gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
Copyright © 2015 Free Software Foundation, Inc.
Ce logiciel est libre; voir les sources pour les conditions de copie.  Il n'y a PAS
GARANTIE; ni implicite pour le MARCHANDAGE ou pour un BUT PARTICULIER.
```

**Comment by fredrikekre** [comment] 2018-12-15 00:20
Duplicate of #30192 ?

**Comment by ViralBShah** [comment] 2018-12-17 01:44
Closing as duplicate.

**Closed by ViralBShah** 2018-12-17 01:44 UTC
