### ISSUE TITLE
3x performance regression from Julia 1.2 to Julia 1.3 / 1.5

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#34404] opened 2020-01-16 15:39 UTC
This 3x regression from Julia 1.2 to Julia 1.3 / 1.5 on the simplest random walk simulation is not good:

```jl
function walk(T)
    x = 0
    
    for i in 1:T        
        if rand() < 0.5
            x += 1
        else
            x -= 1
        end
    end
    
    return x
end

function run(T, N)
    sumsq = 0.0
    
    for i in 1:N
        w = walk(T)
        sumsq += w^2
    end
    
    return sumsq / N
end
```

Timings after warm-up:
Julia 1.2:
```jl
julia> @time run(10^4, 10^5)
  1.467660 seconds (7 allocations: 208 bytes)
9997.0888 
```

Julia 1.3.1:
```jl
julia> @time run(10^4, 10^5);
  5.518198 seconds (7 allocations: 208 bytes)
```

Julia 1.5-DEV.0:
```jl
julia> @time run(10^4, 10^5);
  4.891881 seconds
```

**Comment by KristofferC** [comment] 2020-01-16 15:40
`rand` being slower (and threadsafe) is known. You can generate a large number of random numbers at ones and use those if it is important.

**Comment by dpsanders** [comment] 2020-01-16 15:47
Thanks, but on my machine that didn't seem to help at all.

**Comment by KristofferC** [comment] 2020-01-16 15:54
I get

```
julia> @time run(10^4, 10^5)
  3.053530 seconds
10060.11512
```

with original code and

```
julia> @time run(10^4, 10^5)
  1.197034 seconds (200.00 k allocations: 7.458 GiB, 2.17% gc time)
10035.5994
```

with my version of `walk`.

**Comment by dpsanders** [comment] 2020-01-16 15:59
With your version of `walk` I get
```jl
julia> @time run(10^4, 10^5)
  5.070322 seconds (200.00 k allocations: 7.458 GiB, 14.69% gc time)
9964.9896
```

**Comment by dpsanders** [comment] 2020-01-16 16:03
A C++ version gives 4.4 seconds, so I don't see how Julia 1.2 is so fast (unless it's just a much faster random number generator).

**Comment by KristofferC** [comment] 2020-01-16 16:22
Did you try pass through your own `RNG` (`rng = MersenneTwister()` and then `rand(rng)`)?

**Comment by dpsanders** [comment] 2020-01-16 16:33
OK that works, thanks! -- it gives 1.48 sec.

This seems like a gotcha -- is it documented?

**Comment by JeffBezanson** [comment] 2020-01-16 16:34
Duplicate of #34216. We hope to eventually be able to hoist the thread-local rng lookup out of the loop.

**Closed** 2020-01-16 16:46 UTC
Labels: performance, regression
