### ISSUE TITLE
Improve error message for macro argument mismatch

### ISSUE THREAD

**Issue by mlubin** [JuliaLang/julia#8701] opened 2014-10-16 14:42 UTC
```julia
julia> macro m(x)
       x
       end

julia> @m(1,2)
ERROR: wrong number of arguments
```

It would be great to include the corresponding macro name in the error message. I traced the message to codegen.cpp, but I'm not familiar enough with the code to easily make this change.

**Comment by ihnorton** [comment] 2015-09-29 15:46
Leaving someone (possibly future-me) some breadcrumbs here:
- 'corresponding macro name in the error message' could be solved by appending the macro name to the ErrorException error message in the [catch block in `fl_invoke_julia_macro`](https://github.com/JuliaLang/julia/blob/e60fd184b9368139f2194c3b5c20bc25cc992e7c/src/ast.c#L81-L84). I'm not really sure how to do that safely though, because the message is not guaranteed to be an ASCIIString.
- also noting that we already emit debug info just fine (look at `gdblookup` after breaking in `jl_throw` above). the problem is that we don't generate the backtrace right away because we have to return through flisp before actually throwing.

**Comment by JeffBezanson** [comment] 2016-01-05 15:52
Fixed by #14563.

**Closed by JeffBezanson** 2016-01-05 15:52 UTC
Labels: error handling
