### ISSUE TITLE
`type does not have a definite number of fields` error in REPL completions

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#26513] opened 2018-03-19 01:25 UTC
For `f` a function, type `typeof(f).<TAB>` and get:

```
julia> typeof(f).┌ Error: Error in the keymap
│   exception =
│    type does not have a definite number of fields
│    Stacktrace:
│     [1] error at ./error.jl:33 [inlined]
│     [2] fieldcount(::Any) at ./reflection.jl:578
│     [3] fieldnames(::DataType) at ./reflection.jl:156
│     [4] complete_symbol(::String, ::getfield(REPL.REPLCompletions, Symbol("##15#17"))) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/REPLCompletions.jl:97
│     [5] completions(::String, ::Int64) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/REPLCompletions.jl:619
│     [6] complete_line(::REPL.REPLCompletionProvider, ::REPL.LineEdit.PromptState) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/REPL.jl:341
│     [7] complete_line(::REPL.LineEdit.PromptState, ::Int64) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:310
│     [8] complete_line(::REPL.LineEdit.MIState) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:301
│     [9] edit_tab(::REPL.LineEdit.MIState, ::Bool, ::Bool) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:1911 (repeats 2 times)
│     [10] (::getfield(REPL.LineEdit, Symbol("##108#160")))(::REPL.LineEdit.MIState, ::REPL.LineEditREPL, ::Vararg{Any,N} where N) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:1952
│     [11] top-level scope
│     [12] eval at ./boot.jl:309 [inlined]
│     [13] eval at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:3 [inlined]
│     [14] (::getfield(REPL.LineEdit, Symbol("##27#28")){getfield(REPL.LineEdit, Symbol("##108#160")),String})(::REPL.LineEdit.MIState, ::REPL.LineEditREPL) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:1301
│     [15] prompt!(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:2317
│     [16] run_interface(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:2218
│     [17] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/REPL.jl:1017
│     [18] run_repl(::REPL.LineEditREPL, ::getfield(Base, Symbol("##687#689"))) at /home/keno/julia-comparison/usr/share/julia/site/v0.7/REPL/src/REPL.jl:188
│     [19] (::getfield(Base, Symbol("##686#688")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:414
│     [20] (::getfield(Base, Symbol("#inner#4")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},getfield(Base, Symbol("##686#688")){Bool,Bool,Bool,Bool},Tuple{Module}})() at ./essentials.jl:641
│     [21] #invokelatest#3 at ./essentials.jl:642 [inlined]
│     [22] invokelatest at ./essentials.jl:641 [inlined]
│     [23] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:398
│     [24] exec_options(::Base.JLOptions) at ./client.jl:338
│     [25] _start() at ./client.jl:455
└ @ REPL.LineEdit LineEdit.jl:2319
```

**Comment by derikk** [comment] 2020-11-13 14:05
I believe this is a duplicate of #32558, which was closed by #32840.

**Closed** 2021-03-28 23:19 UTC
Labels: REPL, bug
