### ISSUE TITLE
TypeError happens when constructing `Fix2` struct with Vararg Tuple

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#40054] opened 2021-03-16 04:46 UTC
> master (70b6afa4328d2c4a0aef4c432c85a30eca83aadb):
```julia
julia> isequal(Tuple{Vararg{Int, N}} where N)
julia> isequal(Tuple{Vararg{Int, N}} where N)
ERROR: TypeError: in new, expected DataType, got Type{Tuple{Vararg{Int64, N}} where N}
Stacktrace:
 [1] Base.Fix2(f::typeof(isequal), x::Type{Tuple{Vararg{Int64}}})
   @ Base ./operators.jl:1059
 [2] isequal(x::Type)
   @ Base ./operators.jl:1074
 [3] top-level scope
   @ none:1
```

> 1.6-rc1
```julia
julia> isequal(Tuple{Vararg{Int, N}} where N)
(::Base.Fix2{typeof(isequal), UnionAll}) (generic function with 1 method)
```

I confirmed this issue disappears after checking out to 3635f0473dea7c7254d611e3eaa939e0f6dd9484, so I guess this is caused by 8fc52931fca94f4247f2b0e8f69447f8417d70ab .

/cc @vtjnash

**Comment by vtjnash** [comment] 2021-03-16 06:26
Duplicate of #35661

**Closed by vtjnash** 2021-03-16 06:26 UTC
