### ISSUE TITLE
Mention `--heap-size-hint` in Command-line Interface page

### ISSUE THREAD

**Issue by prbzrg** [JuliaLang/julia#50588] opened 2023-07-18 15:39 UTC
There isn't any mention of `--heap-size-hint` in [Command-line Interface](https://docs.julialang.org/en/v1/manual/command-line-interface/) page.

**Comment by Jay-sanjay** [comment] 2023-07-20 06:15
sir can you please the issue once I want to contribute to this issue

**Comment by prbzrg** [comment] 2023-07-20 10:44
The issue is Julia accept `--heap-size-hint` as a command-line argument and there is a mention of it in Julia's [manpage](https://github.com/JuliaLang/julia/blob/bd8350b3475b0a7c6feace151ebe2752820efa8a/doc/man/julia.1#L225), but it's missing in the [documentation page](https://github.com/JuliaLang/julia/blob/master/doc/src/manual/command-line-interface.md).

**Comment by Jay-sanjay** [comment] 2023-08-03 17:33
sir I guess the issue is fixed but it is not yet closed

**Comment by gbaraldi** [comment] 2023-08-03 17:42
We'll close it when the Pull Request merges ;)

**Comment by PallHaraldsson** [comment] 2023-10-01 16:43
Hopefully that recently added option will become redundant with the new MemBalancer (which has been merged, is expected to be reverted, fixed, than merged hopefully soon again...).

**Closed** 2024-02-08 11:44 UTC
Labels: doc, GC, good first issue
