### ISSUE TITLE
Latest `at-view` macro changes break previously valid code ("invalid let syntax")

### ISSUE THREAD

**Issue by tkemmer** [JuliaLang/julia#53107] opened 2024-01-29 15:55 UTC
I noticed a possible breakage of the `at-view` macro in the current master (since 0588cd407862715e1f0544703d69cfb5d653681c) under very specific circumstances while tracking down a [precompilation error of BioStructures.jl w/ Gihub CI and Julia `nightly`](https://github.com/hildebrandtlab/BiochemicalAlgorithms.jl/actions/runs/7697322191/job/20974110704) pointing to this particular line of code:

https://github.com/BioJulia/BioStructures.jl/blob/69b48127811f0ec235bd17e25838af7ceffd4087/src/spatial.jl#L205

The associated error is:
```julia
ERROR: LoadError: syntax: invalid let syntax around /home/runner/.julia/packages/BioStructures/UfNVa/src/spatial.jl:205
```
Corresponding `versioninfo()` of the Github runner:
```
Julia Version 1.11.0-DEV.1400
Commit 08d229f4a7c (2024-01-29 11:51 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × AMD EPYC 7763 64-Core Processor
  WORD_SIZE: 64
  LLVM: libLLVM-[16](https://github.com/hildebrandtlab/BiochemicalAlgorithms.jl/actions/runs/7697322191/job/20974110704#step:3:17).0.6 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```
Please find below a MWE to trigger the same error as above. A few conditions seem to be required for the error to trigger, particularly:
 - the matrix needs to be wrapped in a lazy transformation such as `transpose` or `adjoint` (working directly on the matrix, does not trigger the error)
 - the projected vector (column or row) needs to be addressed via `end` in some way (replacing `end` by the corresponding column index in the example below does not trigger the error)
 - the view needs to be broadcast-transformed in-place using something like `.+=` or `.*=` (broadcast assignment `.=` does not trigger the error)

### MWE
Expected behavior (before 0588cd407862715e1f0544703d69cfb5d653681c):
```julia
julia> M = [1 2 3; 4 5 6; 7 8 9]
3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

julia> @view(transpose(M)[:,end])
3-element view(transpose(::Matrix{Int64}), :, 3) with eltype Int64:
 7
 8
 9

julia> @view(transpose(M)[:,end]) .+= [1, 1, 1]
3-element view(transpose(::Matrix{Int64}), :, 3) with eltype Int64:
  8
  9
 10

julia> M
3×3 Matrix{Int64}:
 1  2   3
 4  5   6
 8  9  10
```

Since 0588cd407862715e1f0544703d69cfb5d653681c:
```julia
julia> M = [1 2 3; 4 5 6; 7 8 9]
3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

julia> @view(transpose(M)[:,end])
3-element view(transpose(::Matrix{Int64}), :, 3) with eltype Int64:
 7
 8
 9

julia> @view(transpose(M)[:,end]) .+= [1, 1, 1]
ERROR: syntax: invalid let syntax around REPL[47]:1
Stacktrace:
 [1] top-level scope
   @ REPL[47]:1
```
MWE output produced using Julia 1.11.0-DEV.1394 (dcb196e4ca5) before and after cherry-picking 0588cd407862715e1f0544703d69cfb5d653681c, respectively.

**Comment by BioTurboNick** [comment] 2024-01-29 16:35
On one level, it seems like it should be an error to put a `view` on the LHS (without a second level of indexing). However, the issue also occurs when using `@views` to wrap a block for convenience:

```julia
julia> @views transpose(M)[:,end] .+= M[1:3]
ERROR: syntax: invalid let syntax around REPL[6]:1
```

**Comment by vtjnash** [comment] 2024-01-29 21:00
Duplicate of https://github.com/JuliaLang/julia/issues/44356, https://github.com/JuliaLang/julia/issues/35171, others?

**Closed** 2024-01-30 21:06 UTC
Labels: lowering
