### ISSUE TITLE
Vector .* Sparse and Sparse .* Vector broken

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#9664] opened 2015-01-07 18:10 UTC
Broken on both release-0.3 and 0.4-dev:

```jl
julia> [1 1; 1 1] .* [1, 1]
2x2 Array{Int64,2}:
 1  1
 1  1

julia> sparse([1 1; 1 1]) .* [1, 1]
ERROR: DimensionMismatch("")
 in .* at sparse/sparsematrix.jl:568
 in .* at sparse/sparsematrix.jl:669

julia> [1, 1] .* [1 1; 1 1]
2x2 Array{Int64,2}:
 1  1
 1  1

julia> [1, 1] .* sparse([1 1; 1 1])
ERROR: DimensionMismatch("")
 in .* at sparse/sparsematrix.jl:568
 in .* at sparse/sparsematrix.jl:670
```

I'm pretty sure this worked as of v0.2.

**Comment by tkelman** [comment] 2015-01-07 19:42
more or less a duplicate of #8416

**Closed** 2015-04-16 09:15 UTC
Labels: bug, regression, sparse
