### ISSUE TITLE
Feature Request: `in` sorted array

### ISSUE THREAD

**Issue by remi-garcia** [JuliaLang/julia#37442] opened 2020-09-07 05:59 UTC
Their is a "find" function in sorted arrays: `searchsorted`:
https://github.com/JuliaLang/julia/blob/eb2a8018191adf0f5c7f64d84d7e98132d0cbdcb/base/sort.jl#L212-L229

Is that a possible option to add `insorted` that does the same as `in` but knowing that the collection is sorted?

**Comment by goretkin** [comment] 2020-09-09 01:48
Without giving it much thought, this seems like it might be better (more orthogonally) achieved with a wrapper type to annotate that an `AbstractVector` is sorted.

```julia
struct Sorted{T}
    _::T
end

function Base.in(x, v::Sorted)
    r = searchsorted(a._, x)
    return length(r) > 0
end
```

Then you can even use infix `in`:

`x in Sorted(vector)`

**Comment by remi-garcia** [comment] 2020-09-09 12:23
I think I would prefer an independent function to be consistent with the functions `searchsorted`'s. Otherwise the user side would only have `findfirst` instead of `findfirst` and `searchsortedfirst` with `findfirst(x, v::Sorted) = searchsortedfirst(x, v._)`.

I'm working on it but I have a few issues with `insorted` for `AbstractRange`.

**Comment by remi-garcia** [comment] 2020-09-14 19:02
> > I think I would prefer an independent function to be consistent with the functions `searchsorted`'s
> 
> I understand the desire to be consistent. In my opinion, the situation with `searchsortedfirst` and `findfirst` is already something that could be improved, so I do not take it for granted that it's worth being consistent with it.
> 
> There are three ideas: search (or find), sorted/unsorted, first/last/all. So really it's `find`, with two axes of variation: whether the collection is sorted, and whether you want first, last, or all.

Imho the solution should be found in a better naming and not a new structure, that would had an extra layer that should be avoided. What does `sort!(coll::Vector{Int})`?

However, `searchsortedfirst() != findfirst()` if the element is missing from the collection. The first returns an index while the later returns `nothing`. I would probably be for adding a `findsortedfirst` that returns the same as `findfirst` but efficiently in sorted AbstractArray.

**Comment by vtjnash** [comment] 2020-09-15 16:46
Duplicate of #24883

**Comment by goretkin** [comment] 2020-09-15 17:39
I can see that my comments have duplicated things that I now see have been written before, but I don't see the feature request as a duplicate.

**Comment by remi-garcia** [comment] 2020-09-15 20:20
Sorry if I misunderstood something, to me the feature request was not a duplicate.

**Closed** 2020-09-28 20:00 UTC
