### ISSUE TITLE
Regression in inferred return type for `join` on simple iterator.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#55389] opened 2024-08-06 07:33 UTC
```julia-repl
julia> itr = ("foo" for _ in 1:100)
Base.Generator{UnitRange{Int64}, var"#1#2"}(var"#1#2"(), 1:100)

julia> @code_warntype join(itr)
MethodInstance for join(::Base.Generator{UnitRange{Int64}, var"#1#2"})
  from join(iterator) @ Base strings/io.jl:374
Arguments
  #self#::Core.Const(join)
  iterator::Base.Generator{UnitRange{Int64}, var"#1#2"}
Body::Union{Base.AnnotatedString{String}, String}
```

This used to infer to `String`.

Ref https://github.com/JuliaLang/julia/pull/54919.

**Comment by simeonschaub** [comment] 2024-08-06 10:54
Possible duplicate of #55279?

**Comment by KristofferC** [comment] 2024-08-06 11:02
I don't think so because in #55279, the issue is that `seekstart` itself  is all of a sudden much slower.

```julia
julia> @btime seekstart($io)
# master  
85.537 ns (0 allocations: 0 bytes)

# 1.11
 3.125 ns (0 allocations: 0 bytes)
```

As I wrote in https://github.com/JuliaLang/julia/issues/55279#issuecomment-2255238057, I think there is some "inference poisoning" going on.

**Closed** 2024-08-06 17:03 UTC
Labels: domain:strings
