### ISSUE TITLE
RegexMatch should be RegexMatch{T}?

### ISSUE THREAD

**Issue by stevengj** [JuliaLang/julia#48617] opened 2023-02-09 22:44 UTC
`RegexMatch` is [defined as](https://github.com/JuliaLang/julia/blob/b0ac45f3fbc8501c8b3909e838103c88114b29b6/base/regex.jl#L189-L191)
```jl
struct RegexMatch <: AbstractMatch
    match::SubString{String}
    captures::Vector{Union{Nothing,SubString{String}}}
    offset::Int
    offsets::Vector{Int}
    regex::Regex
end
```
which *requires* the `match` to be a `SubString{String}`

I encountered this in JuliaStrings/StringViews.jl#14 — it means that, even though PCRE regex searching is implemented for a `StringView`, the returned `RegexMatch` must *duplicate* the match string into a `String`.  This sucks and will require me to re-implement my own `RegexMatch` with a 1-line change.

Ideally, this would be defined as:
```jl
struct RegexMatch{T} <: AbstractMatch
    match::SubString{T}
    captures::Vector{Union{Nothing,SubString{T}}}
    offset::Int
    offsets::Vector{Int}
    regex::Regex
end
```
instead, to support a wider range of string types. But I guess that would be a breaking change, so it would have to wait for Julia 2.0?

**Comment by stevengj** [comment] 2023-02-09 23:04
(In general, the [regex support in StringViews](https://github.com/JuliaStrings/StringViews.jl/blob/5ddbe5ab5c874827c48e801eceac2b4ce243c4bb/src/regex.jl) required a distressing amount of copy-and-paste, which indicates a lot of opportunities to generalize the Base implementations.)

**Comment by mikmoore** [comment] 2023-02-10 15:53
Is this actually breaking? It would be a performance regression as preexisting code would have missing typeparams, but in many (most?) cases code would not literally fail.

I suppose dispatch methods using `RegexMatch` in the typeparam of another type might now need `<:RegexMatch`, so it could be breaking there.

**Comment by JeffBezanson** [comment] 2023-02-16 19:58
Triage is sympathetic to this; let's try it out as a minor change. Apparently BioSequences already has such a type, as well.

**Comment by Seelengrab** [comment] 2023-02-16 20:00
Of note - the `RegexMatch{S}` in BioSequences is a bit more special, specializing on the kinds of bio sequences themselves:

https://github.com/BioJulia/BioSequences.jl/blob/26e05f723040bd6726ec1e9be37332fec1c4abab/src/search/re.jl#L630-L641

So probably not too related (unless we want to reimplement regex matching ourselves).

**Comment by jakobnissen** [comment] 2024-11-01 12:19
Alternatively, since our current Regex engine PCRE can only operate on arrays in memory (and not all `AbstractString`),  we could store the match and captures as a concrete type, being views into `Memory{UInt8}`.
That would require:
* A memory view type (see https://github.com/JuliaLang/julia/issues/54581)
* Either a string view type in Base, or perhaps in the future, `String` being backed by `Memory`.

**Comment by KristofferC** [comment] 2024-11-01 12:27
Fixed by https://github.com/JuliaLang/julia/commit/7bf226bf8a3c4a99a01e596a6a4c2de6b21ffd40?

**Closed** 2024-11-01 12:35 UTC
Labels: strings
