### ISSUE TITLE
Code is 200x slower in Julia 0.5 with @fastmath 

### ISSUE THREAD

**Issue by raminammour** [JuliaLang/julia#19298] opened 2016-11-10 22:33 UTC
Hello all,

I have some code that slowed down from Julia 0.4 to Julia 0.5 by a factor of 200. After some inspection, the culprit was `@fastmath`. It is probably related to some other issues, but I thought it may be helpful for people who have similar slowdown and searching for a quick fix :)

Weirdly, `@code_warntype` does not show any obvious type instability on my variables (I am no expert on interpreting the output though). 

I unfortunately cannot share the code; anyway, it is too long to be instructive. If I can isolate a reproducible example, I will share it here. Below are the results:

On Julia 0.5
With `@fastmath`:
``` julia
@time  fwd!(c0in, ddout,zeros(nzin,nxin),fin, "fwd", param,pout);
 55.891811 seconds (429.08 M allocations: 7.088 GB, 3.27% gc time)
```

Without `@fastmath`:
``` julia
@time  fwd!(c0in, ddout,zeros(nzin,nxin),fin, "fwd", param,pout);
 0.138615 seconds (1.59 k allocations: 81.074 MB, 18.30% gc time)
```
On Julia 0.4 with `@fastmath`:
``` julia
@time  fwd!(c0in, ddout,zeros(nzin,nxin),fin, "fwd", param,pout);
0.304500 seconds (1.59 k allocations: 81.058 MB, 29.24% gc time)
```

``` 
Julia Version 0.4.6
Commit 2e358ce (2016-06-19 17:16 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-4640 0 @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)
```

**Comment by yuyichao** [comment] 2016-11-10 22:39
Are you using `@fastmath` on complex numbers. (Or what are you using `@fastmath` on?)

P.S. please quote macro names to avoid bringing random people into the thread.

**Comment by raminammour** [comment] 2016-11-10 23:03
No complex numbers (I am aware of the issue with "@fastmath" and complex number promotion).

And thanks for the tip!

**Comment by yuyichao** [comment] 2016-11-10 23:07
....... you need to use `` ` `` to quote code.....

There's nothing we can do without knowing what your problem actually is. You can maybe give some examples one what you are using `@fastmath` on or try to reduce your code to see what actually becomes slower.

**Comment by raminammour** [comment] 2016-11-14 21:49
Sorry for the late reply, I had no access to the codes over the weekend.

After some investigative work, the culprit is `fastmath` function `mul_fast` (line 149 in Julia 0.5). It fails when the number of inputs is strictly larger than 4. This does not happen in Julia 0.4.

Hope this helps :)

```julia
function test4(n)
    s=1.0
    
    for l=1:n
        s+= 2.3*3.4*1.2*5.0
    end
    return s
end

function testf4(n)
    s=1.0
    
    for l=1:n
        @fastmath s+= 2.3*3.4*1.2*5.0
    end
    return s
end

function test5(n)
    s=1.0
    
    for l=1:n
        s+= 2.3*3.4*1.2*5.0*3.1
    end
    return s
end

function testf5(n)
    s=1.0
    
    for l=1:n
        @fastmath s+= 2.3*3.4*1.2*5.0*3.1
    end
    return s
end
#compile
test4(10)
testf4(10)
test5(10)
testf5(10)

@time test4(10^3)
@time testf4(10^3)
@time test5(10^3)
@time testf5(10^3)

  0.000012 seconds (6 allocations: 192 bytes)
  0.000004 seconds (6 allocations: 192 bytes)
  0.000006 seconds (6 allocations: 192 bytes)
  0.002679 seconds (16.01 k allocations: 281.438 KB)
```

**Comment by oscardssmith** [comment] 2016-11-14 22:40
Confirmed, the good news is that it seems to be pretty linear.
Profliing reveals that this code is the problem:
`mul_fast{T<:FloatTypes}(x::T, y::T, zs::T...) =
    mul_fast(mul_fast(x, y), zs...)`

**Comment by oscardssmith** [comment] 2016-11-14 22:43
It seems to be an in-lining issue where the call is being in-lined (properly) for few muls, but it is calling functions for the more general case

**Comment by raminammour** [comment] 2016-11-14 22:50
It happens with `add_fast` too, for the same reasons surely.

**Comment by raminammour** [comment] 2016-11-15 14:31
Looking at operators.jl, something like this resolves these problems:

```julia
afoldl(op,a) = a
afoldl(op,a,b) = op(a,b)
afoldl(op,a,b,c...) = afoldl(op, op(a,b), c...)
function afoldl(op,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,qs...)
    y = op(op(op(op(op(op(op(op(op(op(op(op(op(op(op(a,b),c),d),e),f),g),h),i),j),k),l),m),n),o),p)
    for x in qs; y = op(y,x); end
    y
end
for op in (mul_fast,add_fast)
@eval ($op)(a, b, c, xs...) = afoldl($op, ($op)(($op)(a,b),c), xs...)
end
```

**Comment by oscardssmith** [comment] 2016-11-20 05:30
Isn't that just pushing the problem to cases where you have a lot of variables?

**Comment by KristofferC** [comment] 2017-01-23 10:33
This is fixed:

```jl
julia> using BenchmarkTools

julia> @btime test4(10^3);
  747.172 ns (0 allocations: 0 bytes)

julia> @btime testf4(10^3);
  74.793 ns (0 allocations: 0 bytes)

julia> @btime test5(10^3);
  747.172 ns (0 allocations: 0 bytes)

julia> @btime testf5(10^3);
  74.786 ns (0 allocations: 0 bytes)
```

**Comment by fredrikekre** [comment] 2017-05-24 19:56
> This is fixed

Could we close this then?

**Closed** 2017-05-24 20:01 UTC
Labels: benchmark, performance, regression
