### ISSUE TITLE
Variables not properly escaped inside logging macros

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/julia#48015] opened 2022-12-28 04:40 UTC
A couple of weird cases I found:

1. `level`:
```julia
julia> using Logging

julia> macro log_level()
           quote
               level = Logging.Info
               Logging.@logmsg level "message"
           end
       end
@log_level (macro with 1 method)

julia> @log_level
ERROR: UndefVarError: `level` not defined
Stacktrace:
 [1] macro expansion
   @ logging.jl:371 [inlined]
 [2] top-level scope
   @ REPL[2]:4
```

If I rename the variable `level`, it works as intended

2. `msg`
```julia
julia> using Logging

julia> macro log_msg()
           quote
               msg = "message"
               Logging.@info msg
           end
       end
@log_msg (macro with 1 method)

julia> @log_msg
┌ Error: Exception while generating log record in module Main at REPL[8]:4
│   exception =
│    UndefVarError: `msg` not defined
│    Stacktrace:
│      [1] backtrace()
│        @ Base ./error.jl:114
│      [2] logging_error(logger::Any, level::Any, _module::Any, group::Any, id::Any, filepath::Any, line::Any, err::Any, real::Bool)
│        @ Base.CoreLogging ./logging.jl:465
│      [3] macro expansion
│        @ logging.jl:352 [inlined]
│      [4] top-level scope
│        @ REPL[8]:4
│      [5] eval
│        @ ./boot.jl:370 [inlined]
│      [6] eval_user_input(ast::Any, backend::REPL.REPLBackend, mod::Module)
│        @ REPL /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/REPL/src/REPL.jl:152
│      [7] repl_backend_loop(backend::REPL.REPLBackend, get_module::Function)
│        @ REPL /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/REPL/src/REPL.jl:248
│      [8] start_repl_backend(backend::REPL.REPLBackend, consumer::Any; get_module::Function)
│        @ REPL /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/REPL/src/REPL.jl:233
│      [9] start_repl_backend
│        @ /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/REPL/src/REPL.jl:230 [inlined]
│     [10] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool, backend::Any)
│        @ REPL /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/REPL/src/REPL.jl:376
│     [11] run_repl(repl::REPL.AbstractREPL, consumer::Any)
│        @ REPL /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/REPL/src/REPL.jl:362
│     [12] (::Base.var"#1016#1018"{Bool, Bool, Bool})(REPL::Module)
│        @ Base ./client.jl:421
│     [13] #invokelatest#2
│        @ ./essentials.jl:816 [inlined]
│     [14] invokelatest
│        @ ./essentials.jl:813 [inlined]
│     [15] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
│        @ Base ./client.jl:405
│     [16] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:322
│     [17] _start()
│        @ Base ./client.jl:522
└ @ Main REPL[8]:4
```

Again, renaming the variable `msg` it works as intended.

**Comment by giordano** [comment] 2022-12-28 12:20
Duplicate of #41451

**Closed by giordano** 2022-12-28 12:20 UTC
Labels: logging
