### ISSUE TITLE
multiplication is not checked by default for overflow

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#5054] opened 2013-12-07 18:09 UTC
```julia
julia> 128738872312*invmod(128738872312,9223372036854775783)
9223369465230597584

julia> ans < 9223372036854775783
true
```

**Comment by vtjnash** [comment] 2015-08-26 16:31
```julia
julia> Base.checked_mul(128738872312, invmod(128738872312,9223372036854775783))
ERROR: OverflowError()
 in checked_mul at int.jl:514
```

**Comment by vtjnash** [comment] 2015-08-26 16:32
duplicate of https://github.com/JuliaLang/julia/issues/855

**Closed by vtjnash** 2015-08-26 16:32 UTC
Labels: bug
