### ISSUE TITLE
"Edit on github" link broken

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#48783] opened 2023-02-25 00:56 UTC
The "Edit on github" link doesn't work from https://docs.julialang.org/en/v1/stdlib/Dates/ . It goes to https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.8/Dates/docs/src/index.md which is nothing.

**Comment by inkydragon** [comment] 2023-02-25 06:01
The correct link is:
`https://github.com/JuliaLang/julia/blob/master/stdlib/Dates/docs/src/index.md`

```diff
-https://github.com/JuliaLang/julia/blob/master/usr/share/julia/stdlib/v1.8/Dates/docs/src/index.md
+https://github.com/JuliaLang/julia/blob/master/stdlib/Dates/docs/src/index.md
```

Build path and version number should not be included in the link.

**Comment by felixcremer** [comment] 2023-02-26 19:40
This seems to be a duplicate of #47879

**Closed** 2023-02-26 23:10 UTC
Labels: docsystem
