### ISSUE TITLE
Better syntax error for missing comma

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#50384] opened 2023-07-01 17:54 UTC
```
julia> Cthulhu.descend(
               Diffractor.∂☆{1}(), Tuple{
                       typeof(ZeroBundle{1}(*)),
                       Diffractor.TangentBundle{1, Float64, Diffractor.ExplicitTangent{Tuple{ZeroTangent}}}
                       Diffractor.TangentBundle{1, Float64, Diffractor.TaylorTangent{Tuple{Float64}}}}
       )
ERROR: ParseError:
# Error @ REPL[65]:5:17
                Diffractor.TangentBundle{1, Float64, Diffractor.ExplicitTangent{Tuple{ZeroTangent}}}
                Diffractor.TangentBundle{1, Float64, Diffractor.TaylorTangent{Tuple{Float64}}}}
#               └─────────────────────────────────────────────────────────────────────────┘ ── Expected `}`
# Error @ REPL[65]:5:93
                Diffractor.TangentBundle{1, Float64, Diffractor.ExplicitTangent{Tuple{ZeroTangent}}}
                Diffractor.TangentBundle{1, Float64, Diffractor.TaylorTangent{Tuple{Float64}}}}
#                                                                                           └ ── Expected `)`
# Error @ REPL[65]:5:93
                Diffractor.TangentBundle{1, Float64, Diffractor.ExplicitTangent{Tuple{ZeroTangent}}}
                Diffractor.TangentBundle{1, Float64, Diffractor.TaylorTangent{Tuple{Float64}}}}
#                                                                                           └─┘ ── extra tokens after end of expression
# Error @ REPL[65]:6:1
                Diffractor.TangentBundle{1, Float64, Diffractor.TaylorTangent{Tuple{Float64}}}}
)
└ ── unexpected `)`
# Error @ REPL[65]:6:1
                Diffractor.TangentBundle{1, Float64, Diffractor.TaylorTangent{Tuple{Float64}}}}
)
╙ ── extra tokens after end of expression
Stacktrace:
 [1] top-level scope
   @ none:1

```
The actual issue is a missing comma after the `Diffractor.TangentBundle{1, Float64, Diffractor.ExplicitTangent{Tuple{ZeroTangent}}}`. It'd be nice if it just told me that.

**Comment by oscardssmith** [comment] 2023-07-01 18:02
I believe this is a duplicate of https://github.com/JuliaLang/JuliaSyntax.jl/issues/313

**Comment by giordano** [comment] 2023-07-01 19:50
There are also other tickets about the fact the new parser reports too many errors, for example #50223

**Closed** 2023-07-05 10:58 UTC
Labels: parser
