### ISSUE TITLE
Test suite failures on aarch64-darwin

### ISSUE THREAD

**Issue by samuela** [JuliaLang/julia#43614] opened 2021-12-31 00:29 UTC
After downloading the official dmg from the website, I was surprised to find that the test suite does not pass on aarch64-darwin (aka M1 aka apple silicon aka macOS on ARM etc). I ran `bin/julia --check-bounds=yes --startup-file=no --depwarn=error share/julia/test/runtests.jl` from the Contents/Resources/julia directory. To summarize I'm seeing the following failures:
* segfault in julia/test/strings/basic.jl:228
* segfault in julia/test/iterators.jl:358
* segfault in julia/test/mpfr.jl:931
* test failures in julia/test/errorshow.jl
```
Test Failed at /Users/samuelainsworth/Downloads/Julia-1.7.app/Contents/Resources/julia/share/julia/test/errorshow.jl:781
  Expression: occursin(r"repeats \d+ times", bt_str)
   Evaluated: occursin(r"repeats \d+ times", "\nStacktrace:\n [1] single_repeater()\n   @ Main.Test14Main_errorshow ~/Downloads/Julia-1.7.app/Contents/Resources/julia/share/julia/test/errorshow.jl:771")
Test Failed at /Users/samuelainsworth/Downloads/Julia-1.7.app/Contents/Resources/julia/share/julia/test/errorshow.jl:789
  Expression: occursin(r"the last 2 lines are repeated \d+ more times", bt_str)
   Evaluated: occursin(r"the last 2 lines are repeated \d+ more times", "\nStacktrace:\n [1] pair_repeater_a()\n   @ Main.Test14Main_errorshow ~/Downloads/Julia-1.7.app/Contents/Resources/julia/share/julia/test/errorshow.jl:772")
```
* test failure in julia/test/stacktraces.jl:51
```
Test Failed at /Users/samuelainsworth/Downloads/Julia-1.7.app/Contents/Resources/julia/share/julia/test/stacktraces.jl:51
  Expression: StackTraces.lookup(C_NULL) == [StackTraces.UNKNOWN] == StackTraces.lookup(C_NULL + 1) == StackTraces.lookup(C_NULL - 1)
   Evaluated: Base.StackTraces.StackFrame[ip:0x0] == Base.StackTraces.StackFrame[ip:0x0] == Base.StackTraces.StackFrame[ip:0x1] == Base.StackTraces.StackFrame[_dyld_private at julia:?]
```
* segfault in julia/stdlib/v1.7/SparseArrays/test/sparse.jl:166
* segfault in julia/stdlib/v1.7/Printf/test/runtests.jl:5
* segfault in julia/stdlib/v1.7/SuiteSparse/test/cholmod.jl:318
* error during test in julia/test/testdefs.jl:21
```
Error During Test at /Users/samuelainsworth/Downloads/Julia-1.7.app/Contents/Resources/julia/share/julia/test/testdefs.jl:21
  Got exception outside of a @test
  LoadError: On worker 21:
  SystemError: shm_open() failed for /jl008570nxTwrg2kyN0MULbsX4Ue: Permission denied
```
* Test runner seems to hang after providing the test summary for InvasiveLinkedList followed by a `KILLING BY QUICK KILL WATCHDOG` warning/message

You can view the full logs here: https://gist.github.com/samuela/b24439841ecd52cc201dd1a60d3b1d6f. The whole test suite ran in about 20 minutes for me on the 10-core M1 Max.

Related: https://github.com/JuliaLang/julia/issues/36617

**Comment by giordano** [comment] 2021-12-31 07:46
There are already plenty of tickets reporting issues for [apple silicon](https://github.com/JuliaLang/julia/labels/apple%20silicon), including #43321 which is a similar ticket reporting a grab bag of problems. Some of them had been already addressed before you opened this issue. For example, `shm_open` is already fixed by #43516, `Base.StackTraces.lookup(C_NULL - 1)` is addressed by #43612

**Closed** 2021-12-31 09:26 UTC

**Comment by samuela** [comment] 2021-12-31 21:23
Understood. How should I go about reporting these failures then? Should I create separate GH issues for each one (skipping those that have already been reported ofc)?

**Comment by giordano** [comment] 2021-12-31 22:00
Is there anything different than #43321? This looks a duplicate of that ticket, no?

**Comment by samuela** [comment] 2021-12-31 22:06
I don't see any of the segfaults reported in https://github.com/JuliaLang/julia/issues/43321, but perhaps I'm missing something?

**Comment by giordano** [comment] 2021-12-31 22:09
Many segfaults on the M1 are related to #41440

**Comment by samuela** [comment] 2021-12-31 22:11
Ah, understood. I'll try rerunning things on latest master. Out of curiosity, is there an ETA for getting aarch64-darwin support to tier 1 or 2?

**Comment by giordano** [comment] 2021-12-31 22:11
No
