### ISSUE TITLE
Function evaluation returns value of future definition

### ISSUE THREAD

**Issue by caprilo** [JuliaLang/julia#33342] opened 2019-09-20 20:58 UTC
The return value of a function is determined by the function as defined in the last appearance in the code, instead of the value of the function as it is defined at the moment of the evaluation. Take, for instance

```
function f()
   g() = 1
   return g()
   g() = 2
end
```
 

When calling `f()` it returns `2`, even if the definition of `g` as the constant function 2 was never reached. I would expect this code to return `1`.

`versioninfo()`

Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)

**Comment by fredrikekre** [comment] 2019-09-20 21:06
Duplicate of #15602

**Closed by fredrikekre** 2019-09-20 21:06 UTC
