### ISSUE TITLE
svds does not accept v0 keyword

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#12890] opened 2015-08-31 18:30 UTC
`svds` lacks the ability to specify the starting vector, whereas the underlying `eigs` function it calls does. It would be nice to have the user be able to specify the starting vector, to be consistent with all the other iterative methods.

**Comment by ViralBShah** [comment] 2015-09-01 11:50
+1 and should be easy to do also.

**Comment by tkelman** [comment] 2015-09-03 18:25
duplicate of #10330

**Closed by tkelman** 2015-09-03 18:25 UTC
Labels: intro issue, linear algebra, sparse

**Comment by jiahao** [comment] 2015-09-03 20:56
Derp.
