### ISSUE TITLE
Possible error message improvement for parametric struct definition

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaLang/julia#35994] opened 2020-05-22 16:44 UTC
Not sure how much room there is to improve this, but the error message for the following user error doesn't provide much information about where the error occurs: 

```
julia> struct Inner{T}
           x::T
       end

julia> struct Outer{T}
           y1::Inner{T}
           y2::Inner{T}
           y3:Inner{T} # This single colon is where the user error occurs
       end
ERROR: UndefVarError: T not defined
Stacktrace:
 [1] top-level scope at REPL[2]:1
```

This occurs for me on:

```
Julia Version 1.4.1
Commit 381693d3df (2020-04-14 17:20 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.3.0)
  CPU: Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by JeffBezanson** [comment] 2020-05-22 22:24
I think we can definitely add a check for this.

**Comment by vtjnash** [comment] 2020-06-03 17:28
Duplicate of https://github.com/JuliaLang/julia/issues/35994

**Closed by vtjnash** 2020-06-03 17:28 UTC
Labels: error handling, lowering

**Comment by KristofferC** [comment] 2020-06-03 18:27
@vtjnash I think you pasted the wrong issue number.
