### ISSUE TITLE
Problems with openblas in IJulia/vscode/Juno in 1.6.4

### ISSUE THREAD

**Issue by ctkelley** [JuliaLang/julia#43242] opened 2021-11-27 09:56 UTC
This line of code
```
n=512; L=rand(n,n); z=rand(n); b=L\z;
```
runs in the REPL and in IJUlia with 1.6.3. I get a ```StackOverflowError:```  in IJulia under 1.6.4. Running Monterey. Others report the same problem in vscode and Juno.

Please see 
https://discourse.julialang.org/t/downgrade-to-1-6-3/72129/2

**Comment by metab0t** [comment] 2021-11-27 11:18
![图片](https://user-images.githubusercontent.com/10501166/143678949-da2f4d8e-d355-42be-9a8c-359643304170.png)

Reproduced on Windows 10 with Julia 1.6.4 and IJulia 1.23.2.
It is strange that it works when `n <= 65` and fails when `n > 65`.

**Comment by KristofferC** [comment] 2021-11-27 11:38
I wonder if it has something to do with https://github.com/JuliaLang/julia/issues/43008

**Comment by daviehh** [comment] 2021-11-27 22:27
With https://github.com/JuliaLang/julia/issues/43008, I can somewhat get around the stackoverflow with setting blas thread to 1 with `BLAS.set_num_threads(1)`, does it work for you?

**Comment by metab0t** [comment] 2021-11-28 14:52
> With #43008, I can somewhat get around the stackoverflow with setting blas thread to 1 with `BLAS.set_num_threads(1)`, does it work for you?

Yes, it works for me and solves the problem.

**Comment by KristofferC** [comment] 2021-11-28 15:03
I guess https://github.com/JuliaLang/julia/pull/42147/commits/b8e63b9bd73bddbc6ef1362867f870cfaa9c9d80 was the change on 1.6.4 that caused this? @ViralBShah, is the https://github.com/JuliaPackaging/Yggdrasil/pull/3732 change to change the number of threads also now getting applied when new version of e.g. OpenBLAS 0.3.10 are created? They all seem to include this common file https://github.com/JuliaPackaging/Yggdrasil/blob/b7f1359fb814e02d67a1e6ea80767b2d1d9188d5/O/OpenBLAS/OpenBLAS%400.3.10/build_tarballs.jl#L3 so it seems so?

**Comment by ctkelley** [comment] 2021-11-28 15:27
It's a workaround, but not a solution. I need all the blas threads I can get, so I'm sticking with 1.6.3.

**Comment by ViralBShah** [comment] 2021-11-28 20:51
AFAICT, you have to explicitly bump the BB_REL version to get the new openblas builds on 1.6, which will pick up whatever is in common.jl. 

I believe other patches were required which will need a new BB_REL version to be built and that will pick up other changes from common.jl.

**Comment by ctkelley** [comment] 2021-12-01 16:16
Still a problem in 1.7.0 on Macbook Pro running M1.

**Comment by ViralBShah** [comment] 2021-12-01 16:26
Unfortunately I have not tried M1 - but this may be an M1 specific problem with openblas.

**Comment by ctkelley** [comment] 2021-12-01 18:33
No joy on intel Macs either. Same problem.

**Comment by ViralBShah** [comment] 2021-12-02 01:59
Not sure what binaries you are using, but this works fine on Intel macs for me using the official binaries.

```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

julia> a = randn(66,66); b = rand(66); norm(b-a*(a\b))
4.2670948674214197e-13

julia> a = randn(1666,1666); b = rand(1666); norm(b-a*(a\b))
1.6409946780787127e-11
```

**Comment by BenjaminBorn** [comment] 2021-12-02 08:25
It works for me in a standard REPL. But in the VS Code REPL, it only works if I manually set the number of BLAS threads to 1 (see below), even setting it to 2 threads results in an error.

```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

julia> a = randn(66,66); b = rand(66); norm(b-a*(a\b))
ERROR: ReadOnlyMemoryError()

julia> BLAS.set_num_threads(1)

julia> a = randn(66,66); b = rand(66); norm(b-a*(a\b))
1.9695810178621183e-13
```

**Comment by ctkelley** [comment] 2021-12-02 10:56
It always worked for me in the REPL, and fails in IJulia in 1.6.4 and 1.7.0 on both M1 macs and Intel Macs.

**Comment by ViralBShah** [comment] 2021-12-02 16:09
I believe this is the same as https://github.com/JuliaLang/julia/issues/43301. Closing this as a duplicate, since that one already discusses the fix.

**Closed by ViralBShah** 2021-12-02 16:09 UTC
Labels: linear algebra
