### ISSUE TITLE
Corruption in logging output

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#53473] opened 2024-02-26 13:44 UTC
I had some problems locally with a standard `@info` call when run under tests output some gibberish but I thought it was something weird with my terminal.

Now I see on the Pkg tests the same type of corruption:

https://github.com/JuliaLang/Pkg.jl/actions/runs/8049275146/job/21982300062?pr=3783#step:5:1048

```
    update: package state changes                                         |   15     2      1             18      5.6s
    update: REPL                                                          |    2                           2      0.1s
    up9t1em:1amcEhRiRnOgR :   2 2 m 3 9 m                                           |    1                           1      0.3s
    pin: input checking         L o a d E r r o r :                                  |    3                           3      3.4s
    pin: package state changes                                            |    7                           7      6.7s
    free: input checking                                                  |    2                           2      0.4s
    free: package state changes                                           |    8                           8      8.2s
    free: REPL                       [ 9 1 m S o m e   t e s t s   d i d   n o t   p a s s :   3 0 6 5   p a s s|e d,[ 342 mf a i l3e d , [93 9emrr[o9r1emd ,   1   b ro[k3e9nm.[[9319mm 
 i n   e x pr[e3s9smio[n3 3smt a r t i n g   at[ 3/9Umse[r3s6/mr u n n e3r / wo[r3k9/mPk[g0.mj l / P k0g..1jsl
/ t e s tr/ersuonltvees t s . j l : 3  
```

There looks to be some attempt of ANSI codes in there like `[ 9 1 m` etc.

I'm not sure what is going on but seeing those ANSI codes it might be something with the styled string stuff? It could also be something else.. @tecosaur

**Comment by KristofferC** [comment] 2024-02-28 13:41
<img width="759" alt="image" src="https://github.com/JuliaLang/julia/assets/1282691/451c6a05-69f8-4598-bfa6-5d25308f2a76">

**Comment by KristofferC** [comment] 2024-02-28 14:23
Not only on CI. Locally:

<img width="609" alt="image" src="https://github.com/JuliaLang/julia/assets/1282691/425fd22b-03cc-4a7d-a646-cbd15a039b77">

**Comment by tecosaur** [comment] 2024-02-28 14:36
Oh that is funky! I wonder how on earth that's happened. I'll try digging into this locally.

**Comment by KristofferC** [comment] 2024-02-28 15:16
Just FYI, I haven't verified that this has anything to do with StyledStrings, just that it doesn't seem totally implausible.

**Comment by tecosaur** [comment] 2024-02-28 15:24
Right. I was thinking to test this locally I would modify the `print` method that applies to `StyledStrings` to record the arguments and be able to see (1) what statements were printed, (2) have a reproducible example if anything did come up.

However, since my previous comment `Pkg` (run with the nightly build) has been stuck precompiling :confused: (yes, for 40+ minutes). Might you know of any other places this strange behaviour occurred?

**Comment by KristofferC** [comment] 2024-02-28 15:44
My latest screenshot was from testing LazilyInitializedFields.jl

**Comment by IanButterworth** [comment] 2024-02-28 16:02
I tested this on https://github.com/JuliaLang/julia/commit/b1c8e120d1c73655578a557b4fbe3d6e142dadcc (from Nov 16, 2023) and saw a lot of overprinting, including prints from after the repl returned to the next prompt
![Screenshot 2024-02-28 at 11 00 36 AM](https://github.com/JuliaLang/julia/assets/1694067/e63840d0-020e-44c6-9190-4aba57727bac)

**Comment by IanButterworth** [comment] 2024-03-02 17:18
Related? https://github.com/timholy/ProgressMeter.jl/issues/303

**Comment by KristofferC** [comment] 2024-03-04 09:54
I bisected this to 5fc5556173684f5f5461...

Looking at https://github.com/JuliaLang/Pkg.jl/compare/ff6d645cd8bd18...cf0019fbbaf3ab1e I guess https://github.com/JuliaLang/Pkg.jl/pull/3445.

Here I am, blaming others when I am the guilty all along...

**Comment by KristofferC** [comment] 2024-03-04 10:18
https://github.com/JuliaLang/Pkg.jl/pull/3823 seems to fix it.

However, this naively feels like some bug in the Julia IO system since I don't see why passing a custom IO like this would corrupt the output. (cc @vtjnash)

**Comment by vtjnash** [comment] 2024-03-04 16:21
Ah, yeah, that makes sense. This is just an UnstableIO quality-of-implementation problem. It could be fixed by changing it to being a `<: AbtractPipe` (or simply an `IOContext{IO}` in v1.11)

**Closed** 2024-03-04 16:22 UTC
