### ISSUE TITLE
latency regression from #44364

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#44568] opened 2022-03-11 18:44 UTC
As observed here https://github.com/JuliaLang/julia/pull/44364#discussion_r817983276 this PR has a latency regression, slowing down the build by a couple seconds and adding about 1 second to TTFP. Hopefully that line of work will lead to parallel or lazier compilation, at which point this can probably be closed, but until then it would be nice to get this time back one way or another.

**Comment by pchintalapudi** [comment] 2022-04-18 17:28
Since #44912 was merged, and that PR fixed the latency regression reported in that comment, I'll go ahead and close this issue.

**Closed by pchintalapudi** 2022-04-18 17:28 UTC
Labels: regression, latency
