### ISSUE TITLE
Hit-and-miss method ambiguity detection?

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#6187] opened 2014-03-17 11:34 UTC
In Images, check out commit ddb4259fb2ac39464ed451c5f627d2cd729090ad (I'm about to fix a bunch of ambiguity warnings, but this is a commit that still has them). The list of ambiguity warnings starts with

```
Warning: New definition 
    -(AbstractImageDirect{T,N},AbstractArray{T,N}) at /home/tim/.julia/v0.3/Images/src/algorithms.jl:17
is ambiguous with: 
    -(AbstractArray{TA,2},UniformScaling{TJ<:Number}) at linalg/uniformscaling.jl:35.
To fix, define 
    -(AbstractImageDirect{TA,2},UniformScaling{TJ<:Number})
before the new definition.
```

Why is `-` judged as ambiguous, when the corresponding `+` (which is also defined in `linalg/uniformscaling`) is not even mentioned?

**Comment by mauro3** [comment] 2016-10-12 19:14
Can this be closed now that an error is thrown or is there a deeper issue?

**Comment by JeffBezanson** [comment] 2016-10-12 20:09
The question is whether we are consistently judging similar + and - methods as ambiguous. To close this we have to check that the + and - methods in question are either both ambiguous or both non-ambiguous.

**Comment by StefanKarpinski** [comment] 2016-10-12 20:32
If this applies to ambiguity errors now, rather than warnings, how about changing the title?

**Comment by Keno** [comment] 2019-04-18 23:52
I cannot reproduce this on latest Julia 0.3 with the specified version of Images (all ambiguity warnings that do appear are symmetric between `+` and `-`). Regardless, I looked at the signatures from back then and note that one of them has an extra `<:Number` restriction that may have easily thrown off ambiguity detection. Given that this predates the type system rewrite, I'm gonna call this non-actionable and close it.

**Closed by Keno** 2019-04-18 23:52 UTC
