### ISSUE TITLE
Julia.exe crashes after copying dist-extras (Windows 7)

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaLang/julia#11285] opened 2015-05-15 14:48 UTC
I had some error related to `libexpat-1` so as mentioned in the https://github.com/JuliaLang/julia/blob/master/README.windows.md file I ran `make win-extras` and copied the files into `usr/bin` (overwriting existing files).

After that Julia crashes at startup, without error message beside the default windows popup.

Copying the dll's one by one, it seems `libstdc++-6.dll` is causing the problem.

>Version 0.4.0-dev+4843 (2015-05-15 10:33 UTC)
 Commit 888b6b4 (0 days old master)
 x86_64-w64-mingw32

**Comment by tkelman** [comment] 2015-05-16 00:37
This is actually a duplicate of #10490.

Very sorry, but README.windows.md is out of date. We need to fix things - if you used the MSYS2 instructions to build from source, this is expected because the compiler link that we give is not compatible with packages from WinRPM. Cross-compiling from Cygwin will work. For MSYS2, we need to find and change the link to a different build of MinGW-w64 that would hopefully be compatible. If you're willing to try new compiler versions it would be appreciated if you can try things out until we find one that works?

We could try the MinGW-w64 versions from OpenSUSE which would be guaranteed to be compatible, but there's not a simple installer for those - gotta use winrpm (or my hacky `winrpm.sh` version, which doesn't yet find dependencies).

The next-most-likely version to work correctly would probably be http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev2.7z/download
I haven't tried with that copy yet, but if you have a faster computer than I do and would be willing to give it a shot, please let us know. Best to try from a fresh separate clone.

**Comment by Mike43110** [comment] 2015-05-16 09:03
That is the version of mingw-w64 that I use.

I install it slightly differently however. I install msys2 and copy mingw-w64 into the msys2 directory instead. All tests pass and it builds successfully.

Another note that may need to be added is a step in installing msys2. You seem to need to run `pacman --needed -Sy bash pacman pacman-mirrors msys2-runtime` first before `pacman -Su`as it updates other things first that can't be updated at the same time. I got a Cygwin.dll error until I followed the msys2 guide.

I can update the readme but somebody else needs to test it for obvious reasons.

**Comment by tkelman** [comment] 2015-05-16 09:08
I'm willing to take your word for it at this point as I haven't been using MSYS2 as my primary build environment for a very long time. I'd very much appreciate a PR to update the MSYS2 parts of README.windows.md, maybe @jonathanBieler would be willing to test it out?

**Comment by Mike43110** [comment] 2015-05-16 09:34
Will do in a few hours if @jonathanBieler is ok with that?

What build environment are you using at the moment?

**Comment by tkelman** [comment] 2015-05-16 09:45
I cross-compile from Cygwin for my Windows builds (except for the experimental msvc stuff which all segfaults immediately right now). We can't use most of the 32-bit libraries in MSYS2 because they picked the exception handling model that performs better but can't interoperate with non-mingw libraries (dwarf, whereas we and cygwin and all linux distros that I know of use sjlj for their 32-bit mingw-w64 cross-compilers). I also don't really like pacman in MSYS2, having a package manager that depends on the posix environment to run but also needs to be able to update the core libraries of the posix environment always felt wrong to me. Personal preference, really.

**Comment by jonathanBieler** [comment] 2015-05-16 14:16
I just tried to building using the `x86_64-4.9.2-release-win32-seh-rt_v4-rev2' version above instead of ' `x64-4.8.1-win32-seh-rev5` but I get this:

>Makefile:49: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2

**Comment by tkelman** [comment] 2015-05-16 17:12
Can you try `make -j1` again and post more output please? Upload to https://gist.github.com and leave a link here if it's really long.

**Comment by jonathanBieler** [comment] 2015-05-16 22:03
I had a typo in my python path, sorry about that.

Now it compiles, but it still crashes when I try to use the win-extras dlls.

**Comment by tkelman** [comment] 2015-05-16 22:05
Darn, sorry again. Thanks for your patience and being willing to experiment. @Mike43110 have you been using any WinRPM packages with your MSYS2 source builds?

**Comment by Mike43110** [comment] 2015-05-16 22:08
Excuse my ignorance. WinRPM packages being? Julia packages that require WinRPM packages or MSYS2 using WinRPM?

**Comment by tkelman** [comment] 2015-05-16 22:12
Julia packages that require WinRPM packages - something like ZMQ.jl or Nettle.jl or Tk.jl or Cbc.jl or Ipopt.jl

**Comment by Mike43110** [comment] 2015-05-16 22:21
I just woke up so I will use that as an excuse. Yes, WinRPM packages work fine with my MSYS2 source builds.
@jonathanBieler have you done a `make clean` or `make clean all`? Last time I had strange issues, `core` would refuse to link I think, I ended up having to re-clone and redownload all dependancies.

OT: One thing that is quite annoying is that if a dep fails to download then it must be manually deleted. Wonders of crappy internet is that instead of looking for corner cases, you ARE the corner case!

**Comment by tkelman** [comment] 2015-05-16 22:24
Hm. And are you running those Julia builds within the MSYS2 mintty shell, or outside by double-clicking the .exe?

`make cleanall` would be a good idea just to be sure (rebuilding after that won't take too long, the big dependencies don't get deleted by that, so it'll only rebuild julia src and libuv and a few other small deps)

**Comment by Mike43110** [comment] 2015-05-17 14:09
I will get around to the PR, just had an idea that I want to test first!
I am wondering if I can get a build environment using the native cmd.exe.
Windows 10 has a vastly improved command line so may as well see what can be done with it and the related tools. Not expecting much but if it works and is relatively easy to setup then it may as well be documented.

**Comment by tkelman** [comment] 2015-05-17 21:22
I'm not sure exactly what you mean by "build environment using the native cmd.exe." Julia's makefiles rely on gnu make in a number of ways, and as far as I'm aware the mingw-make versions of gmake that can be run outside of a posix environment like cygwin/msys are not sufficient to build Julia.

See https://github.com/JuliaLang/julia/pull/9422 for a small start towards a cmake build system. This would be the ideal future direction to make the Windows build of Julia more native, and allow better support for MSVC and Intel's Windows compilers.

**Comment by jonathanBieler** [comment] 2015-05-18 15:28
@Mike43110, I restarted from scratch. I start Julia by clicking the .exe, but it starting it from the MSYS2 shell doesn't work either (it just doesn't show the crash window).

**Comment by tkelman** [comment] 2015-05-19 02:33
That's unfortunate, sorry for all the trouble. Cygwin cross-compile is known to work, I was hoping @Mike43110 would be an existence proof that MSYS2 could still work too. We use yet another MinGW-w64 version on appveyor which should work, but doesn't include gfortran so you need to use pre-existing binaries for openblas, arpack, and openspecfun.

@Mike43110 are you running `make win-extras` and copying the dll's from `dist-extras`? That step is what causes problems with some mingw-w64 versions.

**Comment by Mike43110** [comment] 2015-05-19 07:05
I checked with my 4.9.2 setup and I get the same with `make win-extras` as well. Didn't realise `win-extras` was the issue, sorry about that.

I was trying to use GnuWin32 to build Julia but that didn't work unfortunately.
So MSYS2 works apart from `win-extras` on my side.

**Comment by tkelman** [comment] 2015-05-19 07:17
> I get the same with `make win-extras` as well

Can you clarify, by "get the same" do you mean julia crashes?

I think we'll need to try the opensuse mingw-w64 gcc build then, which you can get using `WinRPM.install("gcc")` within Julia, or by modifying the script at `contrib/windows/winrpm.sh` so that it grabs dependencies and preserves folder hierarchies inside the downloaded archives. I'll put it on my list of things to try to get working, but I'll have possibly flaky internet for a few days (probably not as bad as yours, but I'm spoiled being on a university campus).

**Comment by Mike43110** [comment] 2015-05-19 07:29
I don't even get errors unfortunately. It just crashes when I run it.

Also - you have no idea XD even with our fat pipe at varisty, because of all the restrictions it is still a PITA!

**Comment by tkelman** [comment] 2015-06-13 22:07
I've turned off the behavior in `make win-extras` that would cause this problem, so I'm going to close this. ZMQ and hence IJulia might be broken in fresh installs until I can figure out how to use the opensuse toolchain. My working branch for that is https://github.com/JuliaLang/julia/tree/tk/winbuild - if you try in an msys2 build, run the script `contrib/windows/get_toolchain.sh` and try that version of mingw-w64.

**Closed by tkelman** 2015-06-13 22:07 UTC
Labels: build, windows
