### ISSUE TITLE
Performance regression in skipchars

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#33335] opened 2019-09-20 06:43 UTC
`skipchars` took a 5x preformance hit (for the benchmark we have in BaseBenchmarks) presumably after the introduction of locks on the `write` calls.

Perhaps we can lock outside of the loop and write without a lock and finally unlock it when we are done?

**Comment by StefanKarpinski** [comment] 2019-09-23 17:28
cc @vtjnash

**Comment by vtjnash** [comment] 2021-01-28 04:53
Duplicate of https://github.com/JuliaLang/julia/issues/34195 / addressed in https://github.com/JuliaLang/julia/pull/35426. We might be able to do some more automatic compiler optimization of this in the future, instead of the optimization provided there, though it breaks some forward-progress guarantees required by that code pattern in general, so remains to be investigated.

**Closed by vtjnash** 2021-01-28 04:53 UTC
Labels: performance, regression
