### ISSUE TITLE
Uninformative error message when calling keyword argument function with one of the argument typed wrongly

### ISSUE THREAD

**Issue by bvdmitri** [JuliaLang/julia#56554] opened 2024-11-14 09:05 UTC
When using a function with multiple keyword arguments, like the one below, a type mismatch in `save_to` leads to an error that is difficult to understand and troubleshoot for regular users.

Suppose we have the following code:

```julia
function experiment(; 
    parameter1::Float64 = 1.0, 
    parameter2::Float64 = 2.0,
    parameter3::Bool = true,
    parameter4::Float64 = 4.0,
    parameter5::String = "five", 
    parameter6::String = "six",
    parameter7::String = "seven",
    parameter8::String = "eight",
    save_to::String = nothing
) 
    # do some work 
    if !isnothing(save_to)
        # save the work
    end
end

experiment()
```

This code produces the following error:

```julia
MethodError: no method matching var"#experiment#159"(::Float64, ::Float64, ::Bool, ::Float64, ::String, ::String, ::String, ::String, ::Nothing, ::typeof(experiment))
The function `#experiment#159` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  var"#experiment#159"(::Float64, ::Float64, ::Bool, ::Float64, ::String, ::String, ::String, ::String, !Matched::String, ::typeof(experiment))
   @ Main ~/.julia/dev/GraphPPL.jl/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_X10sZmlsZQ==.jl:1
```

- The function is identified as `#experiment#159`, which is an internal Julia detail and irrelevant for a regular user. This naming convention adds confusion without aiding in debugging.
- The error message highlights `!Matched::String` but does not specify which parameter is causing the issue. Given several String-typed parameters, this requires counting parameters to determine which one is problematic.
- The primary issue is with `save_to::String = nothing`, where the default value `nothing` doesn’t match the declared type `String`. However, the error message gives no indication of this mismatch or a clear way to identify it visually in a function with many parameters.

Some suggestions:

- The error message should specify the keyword argument name causing the type mismatch (e.g., `save_to`), allowing users to locate the issue more directly.
- Replace `#experiment#159` with a more user-friendly indication, like experiment, and omit the internal method name where possible.
- If the default value type conflicts with the declared parameter type, highlight this in the error message.

**Comment by fredrikekre** [comment] 2024-11-14 09:13
Duplicate of #36206

**Closed by fredrikekre** 2024-11-14 09:13 UTC
