### ISSUE TITLE
Scoping issue in `@testset`

### ISSUE THREAD

**Issue by ranjanan** [JuliaLang/julia#17170] opened 2016-06-28 20:08 UTC
The following piece of code: 

``` julia
using Base.Dates
using Base.Test
@testset "blah" begin
a = Date(2013)
@show a, "before"
function testlengths(n)
    a = Dates.Date(2000)
    for i = 1:n
        @test length(range(a,i)) == i
    end
    return a+Dates.Day(n)
end
testlengths(100000)
@show a, "after"
end
```

gives the output:

```
(a,"before") = (2013-01-01,"before")
(a,"after") = (2000-01-01,"after")
```

Notice that `a` has changed and shouldn't.

**Comment by StefanKarpinski** [comment] 2016-06-28 20:14
Nice MCV.

**Comment by yuyichao** [comment] 2016-06-28 20:15
AFAIK, this is the expected behavior in a local scope. So should `@testset` be changed to not introduce a new scope?

**Comment by StefanKarpinski** [comment] 2016-06-28 20:19
Test sets introduce a new scope by design since, like `try/catch` they introduce rollback points. In other words, if a test in a test set fails, the tests will continue after the test set. This allows us to get much more complete testing information even when some tests fail – since the tests can continue after a failure.

**Comment by yuyichao** [comment] 2016-06-28 20:39
In another word this is a `won't fix` or dup of https://github.com/JuliaLang/julia/issues/14948 ?

**Comment by StefanKarpinski** [comment] 2016-06-28 20:44
I'm not sure how this is a dup of #14948 since there are no threads involved, but I do think we need to decide if this is the right behavior for test sets and it does perhaps shed some light on one of the more potentially confusing corners of Julia's scoping rules. @JeffBezanson may be interested.

**Comment by yuyichao** [comment] 2016-06-28 20:48
#14948 is not really about threading but the scope lifting due to a variable with the same name in the outer scope

**Comment by JeffBezanson** [comment] 2016-06-28 22:17
Chalk up another point for requiring `outer` (or similar keyword) to assign a variable in an outer scope, I'd have to say.

**Comment by StefanKarpinski** [comment] 2016-06-28 22:27
That seems like it may well make the scoping rules simpler and clearer.

**Comment by mauro3** [comment] 2016-06-29 14:57
X-refs: #5331, #10559, #14959, #16727, #14959

**Comment by bicycle1885** [comment] 2016-07-13 09:05
I also encountered the problem. This case may be much harder to notice:
```julia
using Base.Test

@testset begin
    @testset "foo" begin
        sum = 1
    end

    @testset "bar" begin
        mktemp() do path, io
            @test sum([1,2,3]) == 6
        end
    end
end
```

**Comment by KristofferC** [comment] 2018-04-05 14:34
Original example now warns and the second one works.

**Closed by KristofferC** 2018-04-05 14:34 UTC
Labels: bug, test
