### ISSUE TITLE
Union causes incorrect type parameter extraction?

### ISSUE THREAD

**Issue by githubtomtom** [JuliaLang/julia#41841] opened 2021-08-09 15:00 UTC
in a fresh Mac v1.6.2 session:
```
julia> function f1(x::Union{AbstractArray{T}, AbstractArray{Union{T, Missing}}},
                    y::Union{AbstractArray{T}, AbstractArray{Union{T, Missing}}};
                    α::T = T(3.0) ) where {T<:Real}
           println(typeof(x), " ", typeof(y))
       end;

julia> f1([1.0, missing], [2.0, missing])
ERROR: MethodError: no method matching Union{Missing, Float64}(::Float64)
Stacktrace:
 [1] f1(x::Vector{Union{Missing, Float64}}, y::Vector{Union{Missing, Float64}})
   @ Main ./REPL[1]:4
 [2] top-level scope
   @ REPL[2]:1

julia> function f2(x::Union{AbstractArray{T}, AbstractArray{<:Union{T, Missing}}},
                   y::Union{AbstractArray{T}, AbstractArray{<:Union{T, Missing}}};
                   α::T = T(3.0) ) where {T<:Real}
           println(typeof(x), " ", typeof(y))
       end;

julia> f2([1.0, missing], [2.0, missing])
Vector{Union{Missing, Float64}} Vector{Union{Missing, Float64}}
```

error seems coming from mistaking `Union{Missing, Float64}` as `T`, which should be `Float64`, in the default keyword argument assignment.

noted that if I supply the keyboard argument such that **the default value assignment is not called**, no error:
```
julia> f1([1.0, missing], [2.0, missing]; α = 2.2)
Vector{Union{Missing, Float64}} Vector{Union{Missing, Float64}}
```
it seems to be **a bug in extracting** the `T` (when `Union` is involved?).

the original discussion is from [here](https://discourse.julialang.org/t/union-causes-incorrect-type-parameter-extraction/65953). Thanks.

**Comment by vtjnash** [comment] 2021-08-09 16:02
This should give an UndefVarError, but that can be hard to determine, so we are currently somewhat conservative and return a result, if it none should be returned.

Closing as related to / duplicate of https://github.com/JuliaLang/julia/issues/41728

**Comment by githubtomtom** [comment] 2021-08-09 18:00
why **should** it give an `UndefVarError` ?

in the error case:
```
julia> f1([1.0, missing], [2.0, missing])
ERROR: MethodError: no method matching Union{Missing, Float64}(::Float64)
```
`T` should be **clearly** dispatched as `Float64`.  Of course, that "clearly" refers to a human mind...

**Comment by vtjnash** [comment] 2021-08-09 18:04
We merely have `Float64 <: T <: Union{Float64, Nothing}` as the constraint on that. There's no reason to expect it must pick any particular value from that set.

**Comment by githubtomtom** [comment] 2021-08-09 18:05
to clarify, the specific error occurs **only when there are more than one `Union` inputs**.  For example, the following is fine:
```
julia> function f3(x::Union{AbstractArray{T}, AbstractArray{Union{T, Missing}}};
                   α::T = T(3.0) ) where {T<:Real}
           println(typeof(x))
       end
f3 (generic function with 1 method)

julia> f3([2.0, missing])
Vector{Union{Missing, Float64}}

julia> f3([2.0, missing]; α = 2.0)
Vector{Union{Missing, Float64}}
```

that said, when more than one `Union`s, a human could "match" both inputs as the **same** `AbstractArray{Union{T, Missing}}`, and then infer that `T` is `Float64`. It's difficult for the compiler to do so...

**Comment by vtjnash** [comment] 2021-08-09 18:52
oh, I see now there is an assertion that `T<:Real` in the original, so it seems that the result got widen and is not imposing that constraint when it extracted the output

**Comment by JeffBezanson** [comment] 2021-08-09 19:20
> It's difficult for the compiler to do a two steps inference?

I see the problem here, but yes, this is difficult!! Us humans have a lovely way of being able to "just see" certain things :smile:

**Comment by githubtomtom** [comment] 2021-08-10 03:45
it's difficult ... requiring some "AI inference" !!!

**Comment by vtjnash** [comment] 2023-10-31 17:42
This is fixed now

**Closed by vtjnash** 2023-10-31 17:42 UTC
Labels: types and dispatch
