### ISSUE TITLE
Can't infer types of elements of named tuples under getindex

### ISSUE THREAD

**Issue by andyferris** [JuliaLang/julia#24441] opened 2017-11-02 03:06 UTC
I had hoped that indexing a named tuple (#22194) with a `Symbol` would be a type-inferrable operation. I'm guessing that a tfunc or whatever, like for `Tuple`, may be needed here.

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-DEV.2400 (2017-11-02 03:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  ajf/empty/5fa163f (fork: 1 commits, 0 days)
|__/                   |  x86_64-linux-gnu

julia> nt = (a=1, b=2.0)
(a = 1, b = 2.0)

julia> f(x) = x[:a]
f (generic function with 1 method)

julia> @code_warntype f(nt)
Variables:
  x::NamedTuple{(:a, :b),Tuple{Int64,Float64}}

Body:
  begin
      return (Base.getfield)(x::NamedTuple{(:a, :b),Tuple{Int64,Float64}}, :a)::Union{Float64, Int64}
  end::Union{Float64, Int64}
```

**Comment by StefanKarpinski** [comment] 2017-11-02 03:11
@vtjnash, I believe you've done some constant prop work that might soon help here?

**Comment by andyferris** [comment] 2017-11-02 03:18
That would be even better :) I changed the OP to wrap in a function to reflect that solution.

**Comment by StefanKarpinski** [comment] 2017-11-02 03:21
That's the only way this could work. Note that the `nt.a` form is type inferred:
```jl
julia> f(x) = x.a
f (generic function with 1 method)

julia> @code_warntype f(nt)
Variables:
  x::NamedTuple{(:a, :b),Tuple{Int64,Float64}}

Body:
  begin
      return (Core.getfield)(x::NamedTuple{(:a, :b),Tuple{Int64,Float64}}, :a)::Int64
  end::Int64
```

**Comment by bramtayl** [comment] 2017-11-02 03:54
You can usually get around constant propagation issues by wrapping things in a type. So `Val{:a}()` or `Field{:a}()` ala https://github.com/JuliaLang/julia/issues/1974#issuecomment-286961466 could avoid this issue. One reason why having a nice syntax for `Field{:a}()` would be nice, like `.a`.

**Comment by andyferris** [comment] 2017-11-02 04:05
Yes, you can definitely work around this in a variety of ways - it's just that intuitively we can use `getindex` on a tuple so why not a named tuple?

**Comment by JeffBezanson** [comment] 2017-11-02 04:25
Duplicate of #24011

**Comment by JeffBezanson** [comment] 2017-11-02 04:25
See PR #24362

**Closed by JeffBezanson** 2017-11-02 04:25 UTC
