### ISSUE TITLE
segfault when hashing data structure with circular references

### ISSUE THREAD

**Issue by danspielman** [JuliaLang/julia#39046] opened 2020-12-30 17:04 UTC
When hashing an array that references itself, I get a segfault.

~~~
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 16

julia> x = [1, "a"]; x[1] = x;

julia> h = hash(x)
zsh: segmentation fault  julia --startup-file=no
~~~

**Comment by oscardssmith** [comment] 2020-12-30 17:24
I'm seeing a `StackOverflowError` for this which is reasonable (linux both 1.5.3 and master). Can someone with a mac reproduce this?

**Comment by danspielman** [comment] 2020-12-30 17:45
BTW, if I just hash(x), but don't try to assign it, I also only get the
StackOverflowError:

*julia> *hash(x)

*ERROR: *StackOverflowError:

Stacktrace:

 [1] *!* at *./operators.jl:896* [inlined]

 [2] *hash(*::Array{Any,1}, ::UInt64*)* at *./abstractarray.jl:2317*

 [3] *hash(*::Pair{Int64,Array{Any,1}}, ::UInt64*)* at *./pair.jl:52*

 [4] *hash(*::Array{Any,1}, ::UInt64*)* at *./abstractarray.jl:2298*

 ... (the last 2 lines are repeated 18698 more times)

 [37401] *hash(*::Array{Any,1}*)* at *./hashing.jl:18*

**Comment by josemanuel22** [comment] 2020-12-30 19:14
It happens to me on mac in version 1.5.2 but it seems to be solved in version 1.7.0

`julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)

julia> x = [1, "a"]; x[1] = x;

julia> h = hash(x)
Segmentation fault: 11`

`julia> versioninfo()
Julia Version 1.7.0-DEV.196
Commit 31eb6c20cb (2020-12-30 18:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.0 (ORCJIT, broadwell)

julia> x = [1, "a"]; x[1] = x;

julia> h = hash(x)
ERROR: StackOverflowError:
Stacktrace:
     [1] !
       @ ./operators.jl:1006 [inlined]
     [2] hash(A::Vector{Any}, h::UInt64)
       @ Base ./abstractarray.jl:2440
     [3] hash(p::Pair{Int64, Vector{Any}}, h::UInt64)
       @ Base ./pair.jl:52
     [4] hash(A::Vector{Any}, h::UInt64)
       @ Base ./abstractarray.jl:2421
--- the last 2 lines are repeated 14538 more times ---
 [29081] hash(x::Vector{Any})
       @ Base ./hashing.jl:18`

**Comment by ViralBShah** [comment] 2021-01-02 17:58
Get the same error on 1.6 (no segfault).

**Comment by ViralBShah** [comment] 2021-01-02 18:02
I have a core i5 whereas @danspielman has i9 @josemanuel22 has an i7. I suppose 1.6-beta should come out soon, and if this works for everyone, then we can close it.

**Comment by ViralBShah** [comment] 2021-01-02 18:15
Ok, seems like enabling multi-threading is the key to reproducing the error:

```
➜  julia git:(release-1.6) ./julia -t 2 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-DEV.1780 (2020-12-19)
 _/ |\__'_|_|_|\__'_|  |  release-1.6/de69b02a48 (fork: 58 commits, 24 days)
|__/                   |

julia> x = [1, "a"]; x[1] = x;

julia> h = hash(x)
[1]    62570 segmentation fault  ./julia -t 2
```

**Comment by ViralBShah** [comment] 2022-02-25 06:03
No segfault even with multi-threading now on master.

**Closed by ViralBShah** 2022-02-25 06:03 UTC
Labels: mac, error handling, multithreading
