### ISSUE TITLE
? behaves strangely as an identifier

### ISSUE THREAD

**Issue by joshkarges** [JuliaLang/julia#6286] opened 2014-03-27 17:28 UTC
I have a composite type which has a single Dict property that I thought would be interesting to access with an overloaded ? operator

```
type J9Type
    propDict::Dict
end
function ?(obj::J9Type,field::Union(Symbol,String))
    return get(obj.propDict,field,Nothing())
end
A = J9Type([:p1=>1,:p2=>2,:p3=>7])
```

I found that I could only use my overloaded `?` operator if I mention it before hand, even with a comment.  Otherwise it says that `?` is not a generic function.

```
#?
?(A,:p1)
```

**Comment by jiahao** [comment] 2015-07-23 22:19
Ref: #1910

**Comment by quinnj** [comment] 2017-06-22 05:25
Closing as dupe of https://github.com/JuliaLang/julia/issues/22025 (even though this came first, the other issue seems to have more recent/productive discussion)

**Closed by quinnj** 2017-06-22 05:25 UTC
Labels: parser
