### ISSUE TITLE
linreg deprecation warning incorrectly points to StatsBase.jl

### ISSUE THREAD

**Issue by tribut** [JuliaLang/julia#28688] opened 2018-08-16 13:06 UTC
When `linreg` is called in julia 0.7, it throws this exception:

> ErrorException("linreg has been moved to the package StatsBase.jl.\nRun `Pkg.add(\"StatsBase\")` to install it, restart Julia,\nand then run `using StatsBase` to load it.")

However, StatsBase.jl does not in fact have this function, see https://github.com/JuliaStats/StatsBase.jl/issues/398

**Comment by StefanKarpinski** [comment] 2018-08-17 16:52
It got moved to `Statistics` for some reason. I've said several times that we should just delete this function but for some reason it's still around. It was added by @JeffBezanson because it has a trivial definition in 2011 or so but for that very reason, we should get rid of it. Other numerical systems don't have this function.

**Comment by Leo-C** [comment] 2018-08-30 06:01
Also using GLM (natural repository for this function?) with following lines, error persist (using Julia 0.7.0):
```
julia> using GLM
julia> methods(GLM.linreg)
WARNING: importing deprecated binding Base.linreg into GLM.
# 1 method for generic function "linreg":
[1] linreg(args...; kwargs...) in Base at deprecated.jl:150
```

**Comment by nalimilan** [comment] 2018-08-31 11:30
`linreg` has actually been removed, without a replacement. The deprecation is just wrong.

**Comment by dpsanders** [comment] 2018-09-04 18:14
So what should be used instead of linreg?

**Comment by mkborregaard** [comment] 2018-09-04 20:09
I think the suggestion is `hcat(ones(size(A, 1)), A) \ b`. Which makes complete sense to anyone with a strong statistical background, though not to most people. I frankly don't see why a `linreg` function wouldn't belong in `Statistics` together with `cor` (which is also essentially a one-liner).

**Comment by Leo-C** [comment] 2018-09-04 21:45
`linreg()` returns coefficient and bias using minimum least square, then at the end I've used `llsq()` function in MultivariateStats module that use same algorithm.
This function calculate multivariate regression, but can be used with single regression:

```
using MultivariateStats

function linreg(x, y)
	X = Array{Float64}(undef, length(x),1)
	Y = Vector{Float64}(undef, length(y))
	X[1:length(x),1] .= x
	Y[1:length(y)] .= y
	sol = llsq(X, Y)
	coeff, bias = sol[1], sol[2]
	return (bias, coeff)
end
```

**Comment by nalimilan** [comment] 2019-06-20 07:44
Let's close this since it's too late to add a deprecation to 0.7?

**Closed** 2019-06-20 07:47 UTC
