### ISSUE TITLE
MPFR test failure on windows

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#41484] opened 2021-07-06 17:12 UTC
e.g. https://build.julialang.org/#/builders/65/builds/743/steps/5/logs/stdio
```
Error in testset mpfr:
Test Failed at C:\buildbot\worker-tabularasa\tester_win64\build\share\julia\test\mpfr.jl:609
  Expression: log2(x) == log2(42)
   Evaluated: 5.3923174227787607 == 5.39231742277876
```

**Comment by DilumAluthge** [comment] 2021-07-06 17:32
Duplicate of https://github.com/JuliaLang/julia/issues/41417

This should have been fixed on master by https://github.com/JuliaLang/julia/pull/41473. Are you still seeing this?

**Closed** 2021-07-06 18:12 UTC
Labels: bignums, ci, windows
