### ISSUE TITLE
unable to build on macOS

### ISSUE THREAD

**Issue by vilterp** [JuliaLang/julia#42369] opened 2021-09-23 22:12 UTC
**repro:**

1. clean checkout at master (2c9e051c460dd9700e6814c8e49cc1f119ed8b41)
2. `make`

**expected:**

successful build

**actual:**

```
...
LibCURL  ──────────  0.361519 seconds
Downloads  ────────  0.605942 seconds
Pkg  ──────────────  3.760104 seconds
LazyArtifacts  ────  0.002615 seconds
Stdlibs total  ──── 30.568599 seconds
Sysimage built. Summary:
Total ───────  51.765127 seconds 
Base: ───────  21.193995 seconds 40.9426%
Stdlibs: ────  30.568599 seconds 59.0525%
    JULIA usr/lib/julia/sys-o.a
/bin/sh: line 1: 62349 Segmentation fault: 11  JULIA_BINDIR=/Users/vilterp/code/j-test/julia/usr/bin WINEPATH="/Users/vilterp/code/j-test/julia/usr/bin;$WINEPATH" /Users/vilterp/code/j-test/julia/usr/bin/julia -O3 -C "native" --output-o /Users/vilterp/code/j-test/julia/usr/lib/julia/sys-o.a.tmp --startup-file=no --warn-overwrite=yes --sysimage /Users/vilterp/code/j-test/julia/usr/lib/julia/sys.ji /Users/vilterp/code/j-test/julia/contrib/generate_precompile.jl 1
*** This error is usually fixed by running `make clean`. If the error persists, try `make cleanall`. ***
make[1]: *** [/Users/vilterp/code/j-test/julia/usr/lib/julia/sys-o.a] Error 1
make: *** [julia-sysimg-release] Error 2
```

**context**

* macOS: 11.5.2. intel x64
* clang:
```
clang -v
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by DilumAluthge** [comment] 2021-09-23 22:21
Duplicate of #42346

**Closed by DilumAluthge** 2021-09-23 22:21 UTC
