### ISSUE TITLE
MethodError: `start` has no method matching start(::Colon)

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/julia#11866] opened 2015-06-25 21:32 UTC
Tests in one of my packages suddenly started failing: https://github.com/juliohm/ImageQuilting.jl

**Comment by JeffBezanson** [comment] 2015-06-25 21:37
Do you have a stack trace? That would be helpful.

This is related to the syntax `A[:]`. We used to convert the index to a range `1:n`; now we pass `Colon()`.

**Comment by mbauman** [comment] 2015-06-25 21:37
What version are you running?  This should have been fixed with #11810, but perhaps we're missing another place?  Cf. https://groups.google.com/forum/#!topic/julia-users/EeyryuB7Hz4

**Comment by juliohm** [comment] 2015-06-25 21:48
Travis is configured to use Julia nightly, I can try reproduce the error locally in my machine if you want.

**Comment by juliohm** [comment] 2015-06-25 22:45
Perhaps is just the badge that is outdated? I tried in my machine and it's passing the tests.

**Comment by mbauman** [comment] 2015-06-25 22:51
Yes, that's likely.  As far as I understand, Julia-nightlies only updates if all tests pass, and there's been some test breakages lately.

**Comment by juliohm** [comment] 2015-06-25 22:53
I'll push some trivial changes to my travis file to see if that is the case.

-Júlio

**Comment by tkelman** [comment] 2015-06-25 23:05
check the `versioninfo()` output sha commits from the travis logs, there have been some delays in nightlies recently

**Comment by juliohm** [comment] 2015-06-26 00:45
Yes Tony, I pushed some trivial changes and now everything is failing, even
on Travis.

-Júlio

**Comment by mbauman** [comment] 2015-06-26 03:20
Right, the issue is that there's not been a new nightly published since Monday (1e081b79ed6d24864cec1216a9b7bbe3c8a329e6).  My fix in #11810 (17697b2f770b70dc1be8fe3d9fbeadbdbea40ec3, 5 commits later) hasn't been published yet to the nightly build.

Travis and PkgEval both use the nightly build to run packages on.  But the nightly build isn't truly "nightly" — it only publishes when the base Julia tests pass on all platforms.  So due to several different issues, it hasn't managed to update since Monday.  Once the nightlies update, your Travis and PkgEval should go back to passing.

Please reopen if that's not the case.

**Closed by mbauman** 2015-06-26 03:20 UTC
