### ISSUE TITLE
opnorm(rand(1,0),2) fails

### ISSUE THREAD

**Issue by andreasvarga** [JuliaLang/julia#41871] opened 2021-08-12 10:39 UTC
On Julia 1.6 `opnorm(rand(1,0),2)`  and also `opnorm(rand(0,1),2)` fail: 
julia> opnorm(rand(1,0),2)
```
ERROR: TypeError: in typeassert, expected Tuple, got a value of type Nothing
Stacktrace:
 [1] generic_normInf
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:465 [inlined]
 [2] normInf
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:556 [inlined]
 [3] generic_norm2(x::Matrix{Float64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:497
 [4] norm2(x::Matrix{Float64})
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\dense.jl:105
 [5] opnorm2
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:705 [inlined]
 [6] opnorm(A::Matrix{Float64}, p::Int64)
   @ LinearAlgebra C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\LinearAlgebra\src\generic.jl:767
 [7] top-level scope
   @ REPL[44]:1

```

while the following work:

```
julia> opnorm(rand(1,0),1)
0.0

julia> opnorm(rand(1,0),Inf)
0.0

julia> opnorm(rand(2,0),2)
0.0

julia> opnorm(rand(0,0),2)
0.0

```

**Comment by Seelengrab** [comment] 2021-08-13 14:34
Seems fixed on 1.7:

```
julia> using LinearAlgebra                     
                                               
julia> opnorm(rand(1,0),2)                     
0.0                                            
                                               
julia> opnorm(rand(0,1),2)                     
0.0                                            
                                               
julia> versioninfo()                           
Julia Version 1.7.0-beta3                      
Commit e76c9dad42 (2021-07-07 08:12 UTC)       
Platform Info:                                 
  OS: Linux (x86_64-linux-gnu)                 
  CPU: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64                                
  LIBM: libopenlibm                            
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)       
Environment:                                   
  JULIA_PKG_SERVER =                           
  JULIA_NUM_THREADS = 4                        
```

**Comment by oscardssmith** [comment] 2021-08-13 15:12
Do we have a test for this? If not, we should still add one.

**Comment by Seelengrab** [comment] 2021-08-14 10:07
I think so, yes - this seems to be a duplicate of #40370

**Closed** 2021-08-14 11:14 UTC
