### ISSUE TITLE
Exclude emojis - to e.g. be gender-neutral

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#51130] opened 2023-08-31 13:14 UTC
I discovered for C23 https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2836.pdf
C Identifier Syntax using Unicode Standard
Annex 31

>Prior art: C++, Rust

>The allowed Unicode code points in identifiers include many that are unassigned or unnecessary, and
others that are actually counter-productive.

>**What will this proposal change?**
>**All emoji become excluded, instead of just some**
>Emoji with code points less than FFFF, such as ✌, and ❤ are currently excluded from identifiers.

[I couldn't copy-paste correctly, thus neither test those emojis in Julia, do we allow all or just some emojis in Julia?]

>bool �� = false; // Female Construction Worker
>// ({Construction Worker}{ZWJ}{Female Sign})
>but this is valid:
>bool �� = true; // (Male) Construction Worker

>Other oddities of disallowed vs allowed: [different clocks example I can neither copy paste.]

>**Zero Width Joiner and Zero Width Non-Joiner become excluded.**

>**The available set of identifiers changes over time**

>**Why now**
>One driving factor for addressing this now is that GCC has fixed their long standing bug 67224 "UTF-8
support for identifier names in GCC". Clang has always supported all the allowed code points in
source code. MSVC in its usual configuration defaults to code page 1252, but can be told to accept
UTF-8 source.

It's possible their reasons don't apply to Julia, i.e. C and C++ are standardized and they want the same identifiers to work across compilers, no more or less. For Julia we can allow a superset of what they allow, but should look into if they have a good (other) reason to exclude something.

For us restricting is a breaking change, or at least technically. I think if we want to do that, then we want to do as soon as possible, at least on master, and then 1.10 before release in case it will become LTS. It would be strange to restrict later, and the LTS allowing more.

We could always expand again in a later (even point) version and (conservatively) on 1.10/LTS.

Since it has very little value, I propose blocking at least all human-looking emojis (then also smileys?). It's a can of worms, do we then want to support skin-tone too. Not that I have anything against that for emojis, just for identifiers that could be easily confusable in the REPL. And if we do disallow skin-tones already then we could be accused of race-bias, for white (yellow actually?), against e.g. black.

If in doubt, just block all emojis with a hammer? Since it can be undone later, and discussing (each) could be time-consuming.

**Comment by vtjnash** [comment] 2023-08-31 14:33
Julia already explicitly permits most emoji, except gender modifiers, which have been disallowed since at least v1.0 (though I don't recall the rationale)
```
julia> 👷= false
false

julia> 👷‍♀️=false
ERROR: ParseError:
# Error @ REPL[5]:1:2
👷‍♀️=false
# └ ── invisible character '\u200d'
Stacktrace:
 [1] top-level scope
   @ none:1
```

**Comment by mbauman** [comment] 2023-08-31 15:43
Being able to tab-complete a given symbol is wholly orthogonal to its use as an identifier.  There are many tab-completable characters that are not allowed identifiers, and even more so vice-versa.  What's allowed as an identifier is largely defined by UTF category:

https://github.com/JuliaLang/julia/blob/479743e4d7d5e6f54204dd0390fa475599fed30e/src/flisp/julia_extensions.c#L145-L148

**Comment by Keno** [comment] 2023-08-31 17:06
I'd rather go the opposite way and include all emojis as valid identifiers. We're not in the business of policing people's expression ;). If some organizations want to disallow certain classes of emoji, they're welcome to do that as a lint check.

**Comment by mbauman** [comment] 2023-08-31 17:29
Removing emoji as identifiers would be quite breaking. The actionable part here would be what we do with zero-width joiners, which is a duplicate of #40071.

**Closed by mbauman** 2023-08-31 17:29 UTC
