### ISSUE TITLE
Whitespace sensitivity  / parsing collision in broadcasting array indices

### ISSUE THREAD

**Issue by BenjaminRemez** [JuliaLang/julia#47808] opened 2022-12-05 23:04 UTC
For a MWE, the following is fine:
```
ones(10)[1:5 .+ 1]
```
is fine, whereas without the space between the `+` and `1',
```
ones(10)[1:5 .+1]
```
which produces a "no method matching" error for hcat.  Similarly,
```
ones(10,10)[1:5 .+1 , 1]
```
also errors out.

As far as I can tell, using variables instead of literals for ```1:5``` and 1 does not fix the errors.

**Comment by mikmoore** [comment] 2022-12-06 16:01
Parsing inside `[]` is whitespace-sensitive, resulting in the `+` being treated as either a binary or unary operator. Here's a simpler example that has nothing to do with broadcasting (and uses `-` since it's easier to interpret as a unary operator):
```julia-repl
julia> [1 2 3 -4]
1×4 Matrix{Int64}:
 1  2  3  -4

julia> [1 2 3 - 4]
1×3 Matrix{Int64}:
 1  2  -1

julia> [1 2 3- 4]
1×3 Matrix{Int64}:
 1  2  -1
```
Prior to a recent version (this year, I think), where one can write this as `[1;; 2;; 3;; -4]` (with any number of spaces between `-` and `4`), spaces were the only way to indicate horizontal concatenation in array literals. Thus, whitespace sensitivity was required. I can't imagine this being changed in the Julia v1.X timetrame.

**Comment by mikmoore** [comment] 2022-12-06 17:44
You're right that my explanations were a little off-base in their intent. However, the parsing of `[]` happens before it's decided whether this is an array literal or a `getindex` call so the issue is exactly the same as what I described.

You can avoid the rules of `[]` parsing by adding parentheses or using a function form:
```julia-repl
julia> ones(10,10)[(1:5 .+1) , 1]
6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

julia> getindex(ones(10,10), 1:5 .+1, 1)
6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
```

**Comment by simeonschaub** [comment] 2022-12-11 10:41
Duplicate of #14853

**Closed by simeonschaub** 2022-12-11 10:41 UTC
Labels: parser
