### ISSUE TITLE
eval(Expr(Expr)) will destroy type information of nested Expr

### ISSUE THREAD

**Issue by schlichtanders** [JuliaLang/julia#21329] opened 2017-04-08 11:38 UTC
Dear julia community, when running ``eval`` on an expressions of an expression the ``typ`` information is unexpactedly lost:
```
> expr1 = :(sin(1))
> expr1.typ = Float32
> print(expr1)
sin(1)::Float32
> expr2 = Expr(:quote, expr1)
> eval(expr2).typ
Any
```

Julia: 0.5.1
Operating System: Windows 10

**Comment by yuyichao** [comment] 2017-04-08 12:08
`Expr(:quote)` does not guarantee identical output after `eval`. `QuoteNode` does better.

```julia
julia> expr1 = :(sin(1))
:(sin(1))

julia> expr1.typ = Float

Float16 Float32  Float64
julia> expr1.typ = Float32
Float32

julia> expr1
:(sin(1)::Float32)

julia> expr2 = QuoteNode(expr1)
:($(QuoteNode(:(sin(1)::Float32))))

julia> eval(expr2)
:(sin(1)::Float32)

julia> eval(expr2).typ
Float32
```

**Comment by schlichtanders** [comment] 2017-04-08 13:04
thank you very much.
This suggests that the behaviour is indeed intended. What is the purpose of the difference between Expr and QuoteNode?

**Comment by yuyichao** [comment] 2017-04-08 13:22
Quoting generate `Expr(:quote)` that allows interpolation.

**Comment by schlichtanders** [comment] 2017-04-08 14:26
I just tested the use of QuoteNode within a macro
```
macro tm()
  expr1 = :(sin(1))
  expr1.typ = Float32
  QuoteNode(expr1)
end
```
however there it seems to delete the ``typ`` value too.
```
julias> @tm
sin(1)
# we would like to have sin(1)::Float32
```

**Comment by JeffBezanson** [comment] 2017-04-08 18:00
The `.typ` field is kind of an implementation detail of the compiler; it doesn't have defined semantics. In fact we will likely remove it in the future, using a fully linear IR where each expression has a numbered SSA register. Then types will only be stored in an array associated with a method body.

**Comment by StefanKarpinski** [comment] 2017-04-09 02:00
In particular, assigning to `.typ` and passing to eval is not intended or expected to work.

**Comment by schlichtanders** [comment] 2017-04-09 06:08
thanks for pointing this out, hence I will just go forward as if .typ does not exist at all

**Comment by vtjnash** [comment] 2017-04-10 16:20
there's still the bug that `QuoteNode` fails to preserve its contents when it passes through the front end

**Comment by JeffBezanson** [comment] 2017-04-10 16:45
Duplicate of #15310?

**Closed** 2017-04-10 16:51 UTC
