### ISSUE TITLE
Add semantics for varargs of different types to ccall.

### ISSUE THREAD

**Issue by ninjaaron** [JuliaLang/julia#32758] opened 2019-08-01 19:15 UTC
I'm working on a  PR, #32748, for a macro wraps `ccall` in more Julia-like syntax. An issue that's being discussed a lot is the accommodation of varargs of different types. I had the impression from @vtjnash that this was supported by `foreigncall`, but in retrospect, it's possible I misunderstood what he was saying.

I'm not in a position to implement this myself without first learning Scheme and LLVM. I should really do those things, but it may not be the most efficient way to get this change in.

**Comment by ninjaaron** [comment] 2019-08-01 19:27
And as for syntax, I have no strong opinions, but I can suggest this as a starting point for the conversation, based on what we currently have:

```julia
ccall(:printf, Cint, (Cstring, (Cstring, Cint)...), "%s = %d\n", "value of x", x)
```

**Comment by vtjnash** [comment] 2019-08-02 04:58
sort of a duplicate of https://github.com/JuliaLang/julia/issues/6661, but I'm not a particular fan of that syntax proposal anymore

**Comment by StefanKarpinski** [comment] 2019-08-02 20:48
The semicolon-based alternative syntax would be this:
```jl
ccall(:printf, Cint, (Cstring; Cstring, Cint), "%s = %d\n", "value of x", x)
```
Note that this could potentially be combined with an ellipsis to indicate that all varargs arguments are of the same type, e.g.:
```jl
ccall(:printf, Cint, (Cstring; Cint...), "%d = %d + %d\n", x + y, x, y)
ccall(:printf, Cint, (Cstring, Cint...), "%d = %d + %d\n", x + y, x, y) # might mean the same thing
```
It's unclear how that would be written in the `@ccall` syntax since arguments and their types are paired—this syntax leverages the fact that the type tuple and the args are separate.

**Comment by vtjnash** [comment] 2019-08-03 00:47
I do kind of like that. Seems like `@ccall` would just work the exact same way in that case, since the parser sees these forms as basically the same just inside different wrappers (:tuple vs :call).

Note that you need a `,` there still to make that a tuple during parsing:
```julia
ccall(:printf, Cint, (Cstring,; Cstring, Cint), "%s = %d\n", "value of x", x)
``

**Comment by ninjaaron** [comment] 2019-08-03 12:40
Looks like it sees a tuple if there is a comma somewhere on either side of the semicolon. Otherwise, it sees a "block".
```julia
julia> Meta.@dump (this; that, theother)
Expr
  head: Symbol tuple
  args: Array{Any}((2,))
    1: Expr
      head: Symbol parameters
      args: Array{Any}((2,))
        1: Symbol that
        2: Symbol theother
    2: Symbol this

julia> Meta.@dump (this; that)
Expr
  head: Symbol block
  args: Array{Any}((3,))
    1: Symbol this
    2: LineNumberNode
      line: Int64 1
      file: Symbol REPL[3]
    3: Symbol that
```

**Comment by StefanKarpinski** [comment] 2019-08-03 21:37
Seems like we could also teach ccall to understand the expressions sequence form, although that’s a bit of a cheat and would probably allow other unintentional syntaxes too.

**Closed** 2019-10-07 10:36 UTC
