### ISSUE TITLE
Docstrings inside a begin block

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#19292] opened 2016-11-10 17:26 UTC
This doesn't work. It's not a huge deal, but a bit inconvenient.

```{julia}
begin
    "A test function"
    test_function(a) = "testing"
end

@doc test_function
```

**Comment by yuyichao** [comment] 2016-11-10 17:45
I believe this was intentional

**Comment by bramtayl** [comment] 2016-11-10 21:40
Why?

**Comment by mbauman** [comment] 2016-11-10 23:02
It's documented here: http://docs.julialang.org/en/release-0.5/manual/documentation/#advanced-usage

This is a duplicate of https://github.com/JuliaLang/julia/issues/15684.

**Closed by mbauman** 2016-11-10 23:02 UTC
Labels: docsystem

**Comment by bramtayl** [comment] 2016-11-10 23:07
Ok sorry for the duplicate
