### ISSUE TITLE
Travis nightly binaries are not up to date

### ISSUE THREAD

**Issue by lobingera** [JuliaLang/julia#23149] opened 2017-08-06 06:59 UTC
I tried to track down a failing package on 0.7dev (i'm building locally) and see the package succeeds at travis 'nightly'.

https://travis-ci.org/JuliaMath/FixedPointNumbers.jl/jobs/261353490

list the version 
Julia Version 0.7.0-DEV.1165
Commit 1a43098 (2017-07-31 03:33 UTC)

Is this expected?

**Comment by nalimilan** [comment] 2017-08-06 08:58
Do you mean the problem is that the nightlies are not up-to-date?

**Comment by lobingera** [comment] 2017-08-06 10:17
yes.

**Comment by tkelman** [comment] 2017-08-06 21:12
fixed now. see https://build.julialang.org/builders/build_ubuntu14.04-x64?numbuilds=100 - when there's a test failure on master, nightlies don't get uploaded, by design. we should make a point of reverting problematic commits immediately.

**Closed by tkelman** 2017-08-06 21:12 UTC
Labels: ci
