### ISSUE TITLE
Large `isbits` structs have long compile time for `show` (~32s) and `T[T(...)]` (20+ min)

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#44834] opened 2022-04-02 08:49 UTC
This was found [on discourse](https://discourse.julialang.org/t/using-large-ntuples-makes-julia-hang/78900) with the goal being C interop:

```julia
julia> struct Foo
           id:: UInt64
           tag::NTuple{32, UInt8}
           start_comment::NTuple{4096, UInt8}
           end_comment::NTuple{4096, UInt8}
       end

julia> string2ntuple(s::String, len) = ntuple(i -> i <= ncodeunits(s) ? codeunit(s, i) : 0x0, len)
string2ntuple (generic function with 1 method)

julia> dataset = [Foo(
        0,
        string2ntuple("test_tag", 32),
        string2ntuple("start_comment", 4096),
        string2ntuple("end_comment", 4096),
    )]
# seems to hang, is stuck in compilation somewhere
# the same happens for `Foo[Foo(...)]`
```

Some variations on the above that are otherwise functionally equivalent DO NOT show this behavior:

<details>
<summary>Fast variations</summary>

```julia
julia> @time dataset = Vector{Foo}(undef, 1);
  0.000011 seconds (1 allocation: 8.188 KiB)

julia> @time dataset[1] = Foo(
               0,
               string2ntuple("test_tag", 32),
               string2ntuple("start_comment", 4096),
               string2ntuple("end_comment", 4096),
           ); # silence output
  0.022675 seconds (4.25 k allocations: 344.307 KiB, 98.39% compilation time)

julia> @time dataset[1] = Foo(
               0,
               string2ntuple("test_tag", 32),
               string2ntuple("start_comment", 4096),
               string2ntuple("end_comment", 4096),
           ); # silence output
  0.000272 seconds (9 allocations: 89.016 KiB)

julia> @time data2 = Foo[];
  0.000010 seconds (1 allocation: 64 bytes)

julia> @time push!(data2, Foo(
               0,
               string2ntuple("test_tag", 32),
               string2ntuple("start_comment", 4096),
               string2ntuple("end_comment", 4096),
           )); # silence output
  0.014009 seconds (9.06 k allocations: 700.702 KiB, 97.74% compilation time)
```

</details>

The last `push!` version is also mostly compilation, but I don't know if that's fast or slow relative to regular structs.

`show` itself is also extremely slow to compile, but does eventually finish:

```julia
julia> @time show(stdout, dataset) # that's the dataset from above
Foo[Foo(0x0000000000000000, [...] # I've ommited all the empty data
)] 32.848714 seconds (588.41 k allocations: 60.553 MiB, 0.04% gc time, 99.28% compilation time)
```

**Comment by Seelengrab** [comment] 2022-04-02 09:07
Ok, I had it running in the background and it finally finished:

```
julia> @time data = Foo[Foo(
               0,
               string2ntuple("test_tag", 32),
               string2ntuple("start_comment", 4096),
               string2ntuple("end_comment", 4096),
           )]; # silence output
1255.934351 seconds (4.65 k allocations: 357.717 KiB, 100.00% compilation time)

julia> @time data = Foo[Foo(
               0,
               string2ntuple("test_tag", 32),
               string2ntuple("start_comment", 4096),
               string2ntuple("end_comment", 4096),
           )]; # silence output, second run is still fast
  0.000295 seconds (10 allocations: 97.203 KiB)
```

That's a lot of compilation :sweat_smile:  

```
julia> versioninfo()
Julia Version 1.9.0-DEV.171
Commit 842c27fad3 (2022-03-11 06:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 4 on 4 virtual cores
```

**Comment by simeonschaub** [comment] 2022-04-02 09:38
This is expected and a well known issue. Duplicate of #35619, #35547, #43343 just to name a few.

**Closed by simeonschaub** 2022-04-02 09:38 UTC

**Comment by Seelengrab** [comment] 2022-04-02 10:15
I agree that the general case is well known, but the different variations (in the collapsible details in the OP) on this and the direct use of `Foo` compile extremely fast compared to the two extremes, which are functionally equivalent in the `T[T(...)]` case (and much closer to the times mentioned in the other issues you posted). I think there's more going on here than the usual "tuple is too large" case, but I don't know enough about the compiler to investigate further, e.g. which method exactly takes so long to compile, what other stuff takes time in this etc. How would I go about finding out more about what's going on? Just interrupting or killing the process unfortunately doesn't give me a stacktrace I could investigate with.

**Comment by Seelengrab** [comment] 2023-09-08 13:31
FWIW, this doesn't reproduce anymore, so seems likely to be fixed.
