### ISSUE TITLE
Bug report: `make install` does not copy `libLLVM-8jl.so` on Linux Environment (Julia-1.5 Dev)

### ISSUE THREAD

**Issue by terasakisatoshi** [JuliaLang/julia#34264] opened 2020-01-05 14:03 UTC
- Since `make install` does not copy `libLLVM-8jl.so` (which wll be generated by running `make` command) on linux environment, I can't run Julia that will be installed by `make install` .
- If I copy `libLLVM-8jl.so` manually to directory `path/to/prefix/lib/julia/` it will be alright on Linux environment.

# How to Reproduce

```Dockerfile
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y \
    build-essential \
    libatomic1 \
    python \
    gfortran \
    perl \
    wget \
    m4 \
    cmake \
    pkg-config \
    git

ARG JL_VERSION="master"
ARG WDIR="/root"
ARG JL_BUILD_DIR=$WDIR/build
WORKDIR $JL_BUILD_DIR

RUN echo "\
CXXFLAGS=-D_GLIBCXX_USE_CXX11_ABI=0\n\
prefix=/usr/local/julia-$JL_VERSION\n\
USE_BINARYBUILDER = 0\n\
" > Make.user \
    && cat Make.user \
    && git clone --depth=1 -b $JL_VERSION https://github.com/JuliaLang/julia.git julia-$JL_VERSION\
    && cp Make.user $JL_BUILD_DIR/julia-$JL_VERSION \
    && cd julia-$JL_VERSION \
    && make -j $(nproc) \
    && make install

RUN rm -r $JL_BUILD_DIR && \
    apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
ENV PATH=/usr/local/julia-$JL_VERSION/bin:$PATH
# runtime test
RUN julia -e "using InteractiveUtils; versioninfo()" # it will fail

CMD ["julia"]
```

- Run the following command will occur an error.

```console
$ docker build -t buildmaster .
...
julia: error while loading shared libraries: libLLVM-8jl.so: cannot open shared object file: No such file or directory
```

**Comment by terasakisatoshi** [comment] 2020-01-05 14:10
- I think `JL_PRIVATE_LIBS-?` does not contain `libLLVM-8jl.so`
  - See: 
    - https://github.com/JuliaLang/julia/blob/master/Makefile#L337-L347
    - https://github.com/JuliaLang/julia/blob/master/Makefile#L182

**Comment by terasakisatoshi** [comment] 2020-02-13 18:57
Still same error happens

```
Step 10/12 : ENV PATH=/usr/local/julia-$JL_VERSION/bin:$PATH
 ---> Using cache
 ---> d4c771751911
Step 11/12 : RUN julia -e "using InteractiveUtils; versioninfo()"
 ---> Running in 28e324d74d1d
julia: error while loading shared libraries: libLLVM-9jl.so: cannot open shared object file: No such file or directory
The command '/bin/sh -c julia -e "using InteractiveUtils; versioninfo()"' returned a non-zero code: 127
```

**Comment by terasakisatoshi** [comment] 2020-03-01 14:17
Ah ... I've found this issue occurs when we set `USE_BINARYBUILDER = 0`.  
that's why everyone other than me succeed to build julia without tear.

**Comment by terasakisatoshi** [comment] 2020-03-22 06:00
Apparently, today's julia `Commit a66db76` solves our problem

```
Julia Version 1.5.0-DEV.unknown
Commit a66db76 (2020-03-21 17:57 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Genuine Intel(R) CPU 0000 @ 2.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell)
Removing intermediate container 33463c1ac24e
 ---> 89ab16a7a72c
```

**Comment by non-Jedi** [comment] 2020-03-23 19:22
This is also an issue on the v1.4.0 release.

**Comment by terasakisatoshi** [comment] 2020-03-25 17:49
I think Julia 1.5(in the future) will solve this problem.

**Comment by nalimilan** [comment] 2020-03-27 08:51
This has been fixed on master by https://github.com/JuliaLang/julia/commit/5e0cab69966eb989f380492dda7590bca3a3ba8d AFAICT. I've filed https://github.com/JuliaLang/julia/pull/35273 to backport it (hopefully it's correct).

**Comment by sanderjson** [comment] 2020-04-16 16:50
I am on Fdora 32 and just updated Julia and now I get the error:
```
julia: error while loading shared libraries: libLLVM-8jl.so: cannot open shared object file: No such file or directory
```

**Comment by nalimilan** [comment] 2020-04-16 17:31
@sanderjson How did you install Julia?

**Comment by sanderjson** [comment] 2020-04-16 18:04
I have it installed with dnf
I tried various remove and/installs
I also tried renaming the libllvm file in the installation

What worked in the end:
Dnf remove Julia
Reboot
Just typed Julia in the terminal
Hit yes when prompted to install the command

**Comment by nalimilan** [comment] 2020-04-16 18:18
What exact version of the package do you have?

**Comment by sanderjson** [comment] 2020-04-17 16:07
@nalimilan now I have julia-1.4.0-2.fc32.x86_64 - had the same issues this morning.

```
dnf remove julia
reboot
dnf install julia
```
![julia-failed](https://user-images.githubusercontent.com/20689537/79589503-bba5b080-8092-11ea-8e71-3c252ca4bd84.png)

```
dnf remove julia
reboot
julia
```
![julia-working](https://user-images.githubusercontent.com/20689537/79589531-c6f8dc00-8092-11ea-9a22-b6899d8598c9.png)

**Comment by nalimilan** [comment] 2020-04-17 20:25
Ah, there was a bad interaction between the fix I had applied in 1.4.0 and the fix that was backported in 1.4.1. Should be fixed in the new version I just built.

**Comment by terasakisatoshi** [comment] 2020-04-17 23:34
> https://github.com/JuliaLang/julia/issues/34264#issuecomment-614769772

This error occurs build source from scratch. 

Below is my prescription to solve the issue:

Here is my https://github.com/Julia-Embedded/jlcross/blob/master/rpi3/Dockerfile-v1.4.0#L34

**Comment by vchuravy** [comment] 2020-04-19 15:59
It is fixed on Julia 1.4.1 and 1.5.0-dev, we didn't cache it early enough for `1.4.0` so yes either you have to manually copy or use `USE_BINARYBUILDER_LLVM=1`.

**Closed by vchuravy** 2020-04-19 15:59 UTC
Labels: build

**Comment by sanderjson** [comment] 2020-04-21 01:52
working as intended

**Comment by Klorophane** [comment] 2020-06-16 22:40
It seems like this problem is back? julia-1.4.2-1.fc32.x86_64 gives the same error (Fedora 32)

**Comment by nalimilan** [comment] 2020-06-17 07:32
See https://bugzilla.redhat.com/show_bug.cgi?id=1846698.
