### ISSUE TITLE
pcre.mk still pointing to ftp.pcre.org which is not anymore online since at least November 4th, and consider that pcre2 version 10.36 is not anymore officially provided from pcre.org

### ISSUE THREAD

**Issue by iviar** [JuliaLang/julia#43895] opened 2022-01-22 22:34 UTC
A build prepared with `make full-source-dist` fails because in a second stage deps/pcre.mk tries to retrieve pcre2 from ftp.pcre.org which is "no longer available", it's said FTP, but in practice I don't see either port 443 receptive for the line of deps/pcre.mk containing https://ftp.pcre.org/pub/pcre/pcre2-$(PCRE_VER).tar.bz2

https://pcre.org   -currently last modified on Thu, 04 Nov 2021 23:13:21 GMT- says:
> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

Furthermore to consider pcre.org do not provides anymore officially version 10.36,
Here is PCRE2 [ChangeLog](https://github.com/PhilipHazel/pcre2/blob/master/ChangeLog)
and an extract if I USE_SYSTEM_PCRE:=1 with system pcre 10.39
building julia-git-1.8.0.DEV.r51086.gdd0c14ba1d0
PCRE2_jll                          (1) |        started at 2022-01-18T20:06:00.377
PCRE2_jll                          (1) |         failed at 2022-01-18T20:06:15.913
Test Failed at aur/julia-git/src/julia/usr/share/julia/stdlib/v1.8/PCRE2_jll/test/runtests.jl
  Expression: vn == v"10.36.0"
   Evaluated: v"10.39.0" == v"10.36.0"
giving the only test failure from a version string assert check

**Comment by giordano** [comment] 2022-01-23 02:03
Duplicate of #43878

**Comment by DilumAluthge** [comment] 2022-01-23 06:09
Closing as duplicate of #43878

**Closed by DilumAluthge** 2022-01-23 06:09 UTC
