### ISSUE TITLE
Performance of broadcast over multiple functions

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaLang/julia#40032] opened 2021-03-15 06:46 UTC
Consider the following equivalent definitions of a function and the benchmarking

```julia
mutable struct Agent
	R::Float64
	V::Float64
end

initi(n) = Agent.(1., zeros(n))
f1(arr) = mean((a->cis(getproperty(a, :R))).(arr))
f2(arr) = mean(cis.(getproperty.(arr,:R)))
agents = initi(10000)
fcompose = @benchmark f1($agents)
fchain = @benchmark f2($agents)
judge(median(fcompose), median(fchain))
```

The output of the judge is this-

```julia
BenchmarkTools.TrialJudgement: 
  time:   -71.13% => improvement (5.00% tolerance)
  memory: -49.99% => improvement (1.00% tolerance)
```

Shouldn't both have equivalent performance? From what I understand, the chained version iterates through the array multiple times, whereas the composed version doesn't. Is this an expected thing? If so, then won't everyone just use for loops or maps instead?

## Version Info
```
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_REVISE_WORKER_ONLY = 1
```

**Comment by DhruvaSambrani** [comment] 2021-03-15 06:54
The Julia docs [here](https://docs.julialang.org/en/v1/manual/performance-tips/#More-dots:-Fuse-vectorized-operations) and [here](https://docs.julialang.org/en/v1/base/arrays/#Base.Broadcast.broadcast) suggest that vectorized calls should be fused to a single loop, but the performance doesn't seem to indicate this

**Comment by martinholters** [comment] 2021-07-20 11:29
The problem seems to be that in `f2`, the `:R` is not const-propagated. With the following:
```julia
getR(a) = getproperty(a, :R)
f1(arr) = mean((a->cis(getR(a))).(arr))
f2(arr) = mean(cis.(getR.(arr)))
```
Performance of `f1` and `f2` is equal and on par with the original `f1`.

**Comment by DhruvaSambrani** [comment] 2021-07-20 14:04
But why is :R not propogated? Like, is that a bug or expected behaviour?

**Comment by mbauman** [comment] 2021-07-20 15:01
Duplicate of #39151

You can work around this for now by manually wrapping `:R` in a tuple (or some other immutable 0-dim or length-1 like: `f3(arr) = mean(cis.(getproperty.(arr,(:R,))))`.  But we really need to fix this properly.

**Closed by mbauman** 2021-07-20 15:01 UTC
