### ISSUE TITLE
Compiler crash with `===()`

### ISSUE THREAD

**Issue by akosuas** [JuliaLang/julia#40904] opened 2021-05-21 18:18 UTC
I can get the following on Julia 1.6.1:
```
julia> foo() = ===(0)
foo (generic function with 1 method)

julia> foo()
Internal error: encountered unexpected error in runtime:
BoundsError(a=Array{Any, (2,)}[
  Main.:(===),
  0], i=(3,))
jl_bounds_error_ints at /buildworker/worker/package_linux64/build/src/rtutils.c:186
```
The syntax may indeed be invalid, but it doesn't produce a friendly error.

**Comment by simeonschaub** [comment] 2021-05-21 18:19
duplicate of #40804

**Comment by akosuas** [comment] 2021-05-21 18:19
Thanks!

**Closed by simeonschaub** 2021-05-21 18:19 UTC
