### ISSUE TITLE
floating point `div` differs in optimized code

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#14089] opened 2015-11-21 20:51 UTC
I ran into this trying to get tests to pass on jb/functions. Also happens on master:

```
julia> div(0.3,0.01)
29.0

julia> f()=div(0.3,0.01)
f (generic function with 1 method)

julia> f()
30.0
```

**Comment by vchuravy** [comment] 2015-11-21 23:40
That looks like constant folding to me:
````julia
julia> @code_llvm f()

define double @julia_f_21524() {
top:
  %0 = call double @llvm.rint.f64(double 3.000000e+01)
  ret double %0
}
````

compared to
````julia
julia> f(x, y) = x ÷ y
f (generic function with 2 methods)

julia> f(0.3, 0.01)
29.0

julia> @code_llvm f(0.3, 0.01)

define double @julia_f_21540(double, double) {
top:
  %2 = frem double %0, %1
  %3 = fsub double %0, %2
  %4 = fdiv double %3, %1
  %5 = call double @llvm.rint.f64(double %4)
  ret double %5
}
````

**Comment by yuyichao** [comment] 2015-11-22 00:17
```jl
julia> rem(0.3, 0.01)
0.009999999999999983

julia> f() = rem(0.3, 0.01)
f (generic function with 1 method)

julia> f()
0.0
```

**Comment by yuyichao** [comment] 2015-11-22 00:23
And seems like a LLVM bug (unless we are optimizing `llvmcall` ourselves....)

```jl
julia> function k()
           Base.llvmcall("""
                         %1 = frem double 3.000000e-01, 1.000000e-02
                         ret double %1
                         """, Float64, Tuple{})
       end
k (generic function with 1 method)

julia> @code_llvm k()

define double @julia_k_22866() #0 {
top:
  ret double 0.000000e+00
}

julia> k()
0.0

julia> function k2(a, b)
           Base.llvmcall("""
                         %3 = frem double %0, %1
                         ret double %3
                         """, Float64, Tuple{Float64,Float64}, a, b)
       end
k2 (generic function with 1 method)

julia> @code_llvm k2(0.3, 0.01)

define double @julia_k2_22867(double, double) #0 {
top:
  %2 = frem double %0, %1
  ret double %2
}

julia> k2(0.3, 0.01)
0.009999999999999983
```

**Comment by Keno** [comment] 2015-11-22 02:26
Also seems to happen on llvm-svn.

**Comment by vchuravy** [comment] 2015-11-22 02:49
Possibly related: https://llvm.org/bugs/show_bug.cgi?id=3316

**Comment by KristofferC** [comment] 2017-01-22 13:19
Still happens.

**Comment by simonbyrne** [comment] 2017-01-31 14:38
I've reopened the upstream issue with an example.

**Comment by simonbyrne** [comment] 2017-01-31 21:03
Okay, I've put together a fix here: https://github.com/simonbyrne/llvm/commit/2718254b0627fbf07034b9f0e5ad245536bd8dfa

@Keno how do I go about actually getting this into LLVM?

**Comment by yuyichao** [comment] 2017-01-31 21:05
http://llvm.org/docs/Phabricator.html#requesting-a-review-via-the-web-interface

**Comment by Keno** [comment] 2017-01-31 21:05
Paste your diff here: https://reviews.llvm.org/differential/diff/create/ (Ideally with `git dif -U99999` to get all the context), then fill out the form. It'll ask you to pick reviewers, but as long you put it up, I can find some people to review it for you.

**Comment by simonbyrne** [comment] 2017-01-31 21:19
Submitted here: https://reviews.llvm.org/D29346

**Comment by Keno** [comment] 2017-01-31 21:26
Found you some reviewers. Lets hope they know what they're doing.

**Comment by simonbyrne** [comment] 2017-04-01 12:13
Now fixed upstream: https://github.com/llvm-mirror/llvm/commit/872b505b043539bb5d8dd6211266b651740f7e69

**Comment by tkelman** [comment] 2017-04-01 12:51
Do we want to carry that patch, rebased for LLVM 3.9 if necessary?

Have our tests just been working around this?

**Comment by simonbyrne** [comment] 2017-04-01 13:50
I think we've just been ignoring it, since it is a pretty weird edge case (calling `rem` with constant floating point arguments)

**Comment by jayvn** [comment] 2017-11-20 06:27
When will the fix to llvm be out then ? 
I ran into 
```julia
julia> div(1,0.2)
4.0
``` 
Which is why I'm here. As a workaround I tried
Int(x), but Int(2.9999998) throws InexactError().

```
julia> versioninfo()
Julia Version 0.6.1
Commit 0d7248e2ff (2017-10-24 22:15 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```
Will the Int(2.999998) bug be fixed as well with the patch ?

**Comment by GunnarFarneback** [comment] 2017-11-20 08:45
0.2 can't be represented exactly as a binary floating point value, so it's reasonable for `div(1, 0.2)` to be either 4.0 or 5.0 depending on whether 0.2 turns out to represented by a value that is slightly smaller or slightly larger than 0.2. That's not what this issue is about though, but whether optimizations cause inconsistent results for the same computation.

2.999998 is not an integer so `Int(2.999998)` throwing `InexactError` is working as intended. What you probably want is `round(a / b)` or `round(Int, a / b)`.

Further discussion about the nature of floating point arithmetics should go on the Discourse forum since it's off-topic for this particular issue.

**Comment by StefanKarpinski** [comment] 2017-11-20 13:53
> 0.2 can't be represented exactly as a binary floating point value, so it's reasonable for div(1, 0.2) to be either 4.0 or 5.0 depending on whether 0.2 turns out to represented by a value that is slightly smaller or slightly larger than 0.2.

This is not random, however: there is only one `Float64` value that `0.2` can correctly represent and it is slightly larger than 1/5. However, five times that number is slightly larger than 1.

**Comment by simonbyrne** [comment] 2017-11-20 16:31
Also, fix is now in master, so can be closed.

**Comment by tkelman** [comment] 2017-11-20 17:39
Master of Julia, or only master of llvm? Is it tested, if fixed here?

**Comment by simonbyrne** [comment] 2017-11-20 18:09
Ah, I forgot I had compiled with LLVM-svn.

**Comment by KristofferC** [comment] 2019-03-23 12:07
Fixed in release now.

**Closed by KristofferC** 2019-03-23 12:07 UTC
Labels: bug, codegen, maths, upstream
