### ISSUE TITLE
Confusing UndefVarError in misplaced Ref{} usage

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#13428] opened 2015-10-03 00:41 UTC
The following code snippet emits a very odd error message (requires the GSL library):

```jl
type gsl_error_handler_t end

custom_gsl_error_handler = convert(Ptr{gsl_error_handler_t}, cfunction(error, Void, ()))

function set_error_handler(new_handler::Ptr{gsl_error_handler_t})
    output_ptr = ccall( (:gsl_set_error_handler, :libgsl),
        Ref{gsl_error_handler_t}, #<--- User error: should be Ptr{...}
        (Ptr{gsl_error_handler_t}, ), new_handler )
end

set_error_handler(custom_gsl_error_handler)
```

Result: 
```
ERROR: UndefVarError: result not defined
 in include_from_node1 at ./loading.jl:316
 in process_options at ./client.jl:275
 in _start at ./client.jl:375
```

`result` is not defined in this code, nor is it ever used at the user level, so this error is rather cryptic.

Observed on release-0.4 and master.

**Comment by staticfloat** [comment] 2015-10-03 00:56
Hrmm... I don't get that error; I get a segfault:
```
using GSL
import GSL: set_error_handler

type gsl_error_handler_t end
custom_gsl_error_handler = convert(Ptr{gsl_error_handler_t}, cfunction(error, Void, ()))
function set_error_handler(new_handler::Ptr{gsl_error_handler_t})
    output_ptr = ccall( (:gsl_set_error_handler, :libgsl),
        Ref{gsl_error_handler_t}, #<--- User error: should be Ptr{...}
        (Ptr{gsl_error_handler_t}, ), new_handler )
end

set_error_handler(custom_gsl_error_handler)
```

Results in:
```
signal (11): Segmentation fault: 11
jl_object_id_ at /Users/sabae/src/julia/src/builtins.c:1172
typekey_compare at /Users/sabae/src/julia/src/jltypes.c:1843
lookup_type at /Users/sabae/src/julia/src/jltypes.c:1906
jl_inst_concrete_tupletype_v at /Users/sabae/src/julia/src/jltypes.c:2175
jl_f_tuple at /Users/sabae/src/julia/src/builtins.c:658
eval_user_input at REPL.jl:66
jlcall_eval_user_input_21357 at  (unknown line)
jl_apply at /Users/sabae/src/julia/src/./julia.h:1324
anonymous at REPL.jl:93
jl_apply at /Users/sabae/src/julia/src/task.c:241
```

**Comment by jiahao** [comment] 2015-10-03 01:01
Try it without `using GSL`.

**Comment by jiahao** [comment] 2015-10-03 01:35
Hm, now I can't reproduce.

Instead, I get

```
signal (11): Segmentation fault: 11
jl_f_tuple at /Users/jiahao/local/src/julia/src/builtins.c:667
eval_user_input at REPL.jl:65
jlcall_eval_user_input_21981 at  (unknown line)
anonymous at REPL.jl:92
jl_apply at /Users/jiahao/local/src/julia/src/task.c:241
[1]    81907 segmentation fault  julia
```

**Comment by staticfloat** [comment] 2015-10-03 01:41
I get the exact same thing even when I don't use `using GSL`.  Now interestingly enough, if I turn this into a script instead of evaluating at the REPL, nothing bad happens.  If I store the output of `set_error_handler()` and try to `display()` it, that's when the segfault occurs, so I think this segfault is happening due to display code.

**Comment by jiahao** [comment] 2015-10-03 01:42
yeah, looks like it.

```jl
julia> include("crap.jl");
ERROR: UndefVarError: result not defined
 in include_from_node1 at ./loading.jl:316

julia> include("crap.jl")

signal (11): Segmentation fault: 11
jl_is_type at /Users/jiahao/local/src/julia/src/jltypes.c:68
jl_inst_concrete_tupletype_v at /Users/jiahao/local/src/julia/src/jltypes.c:2175
jl_f_tuple at /Users/jiahao/local/src/julia/src/builtins.c:668
eval_user_input at REPL.jl:65
jlcall_eval_user_input_21921 at  (unknown line)
anonymous at REPL.jl:92
jl_apply at /Users/jiahao/local/src/julia/src/task.c:241
[1]    83085 segmentation fault  julia
```

**Comment by jiahao** [comment] 2015-10-03 01:43
If I add `print("")` to the end of the script then no error is thrown.

**Comment by staticfloat** [comment] 2015-10-03 01:44
I'm on `v0.4.0-rc3`.

**Comment by yuyichao** [comment] 2015-10-03 02:12
IIUC, the use of `ccall` is a valid syntax but does not match the actual c signature. Therefore you are very likely corrupting some memory which either gives you wierd result or just cause a segfault.

**Comment by yuyichao** [comment] 2015-10-03 02:23
I can verify in `gdb` (and also `code_llvm`/`code_native`) that the function is run (and generated) as specified but it is trying to interpret a random pointer as a julia heap object which causes all kinds of madness.

I'll close this as a duplicate of https://github.com/JuliaLang/julia/issues/12173. I'm trying to get a simple version working recently and thanks for reminding me that the arguments are not the only place that can go wrong.....

**Closed** 2015-10-03 02:24 UTC
