### ISSUE TITLE
Change map(f) behavior

### ISSUE THREAD

**Issue by jariji** [JuliaLang/julia#48372] opened 2023-01-21 08:07 UTC
```jl
julia> f() = 9
f (generic function with 1 method)

julia> map(f)
9
```

`map` is a variadic `zipWith`, so I think it should behave like `zip`. 

I don't see a justification for making it call `f` once. `f` should be called once when the shortest data argument has length 1. But in `zip()` the shortest data argument is assumed to have infinite length. So the [most consistent behavior](https://github.com/JuliaLang/julia/issues/43821#issuecomment-1013816939) is to yield an infinite stream of empty tuples. That is the current behavior of `zip()`.

https://github.com/JuliaLang/julia/pull/47344#issuecomment-1310862363:
> Triage thinks that `zip()` should either be an infinite stream, or it should error.

I would think then `map(f)` should either yield an infinite stream of `f()` or throw an error.

For comparison, in Python, which has variadic `map`, it needs at least 1 data argument and throws an error otherwise.

This problem was pointed out on [Discourse](https://discourse.julialang.org/t/why-no-single-argument-filter-f-function/92719/6).

**Comment by fredrikekre** [comment] 2023-01-21 08:12
Duplicate of #35293

**Closed by fredrikekre** 2023-01-21 08:12 UTC
