### ISSUE TITLE
failed to install and run Julia-1.3 on MacOS Catalina

### ISSUE THREAD

**Issue by JADodson** [JuliaLang/julia#34210] opened 2019-12-28 19:12 UTC
I have been using Julia-1.0 at the Terminal and under Jupyter for some time under the previous MacOS. I recently upgraded to Catalina 10.15.2. I can still use Julia 1.0 under Terminal, but when I try to run the new Julia-1.3, I get the alert:

> “Julia-1.3” can’t be opened because Apple cannot check it for malicious software.

Update: I am able to get around this by approving within "System Preferences / Security & Privacy".

Not sure, but I am guessing this is related to the new required app notarization under Catalina. Anyone want to fight with this? Maybe someone can update the instructions in the meantime.

**Comment by cafaxo** [comment] 2019-12-28 20:37
Is this a duplicate of #33331?

**Comment by ViralBShah** [comment] 2019-12-28 22:21
Yes, dup. @staticfloat has a solution for this, which is not ideal and not automated, but should get the job done.

**Closed by ViralBShah** 2019-12-28 22:21 UTC
