### ISSUE TITLE
Pkg.test segmentation fault

### ISSUE THREAD

**Issue by jhlq** [JuliaLang/julia#11466] opened 2015-05-28 12:27 UTC
Previous command was another Pkg.test which was aborted with ctrl+c after it had finished testing during the mysterious extra stuff it does after.

Why doesn't Pkg.test end after testing?

```
julia> Pkg.test("Equations")
INFO: Testing Equations
INFO: Equations tests passed

signal (11): Segmentation fault
unknown function (ip: -568868518)
jl_array_grow_end at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
resize! at ./array.jl:506
ensureroom at ./iobuffer.jl:182
write at ./iobuffer.jl:239
write_sub at ./iobuffer.jl:252
print at ./ascii.jl:93
jlcall_print_5529 at /usr/bin/../lib/x86_64-linux-gnu/julia/sys.so (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
print_to_string at ./string.jl:24
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
string at ./string.jl:31
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
joinpath at ./path.jl:66
joinpath at path.jl:58
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
available at ./pkg/read.jl:21
test! at pkg/entry.jl:705
jlcall___test!#240___20448 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_test!_20447 at  (unknown line)
test at pkg/entry.jl:712
jlcall___test#241___20445 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_test_20444 at  (unknown line)
jlcall_test_20444 at  (unknown line)
jl_f_apply at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at pkg/dir.jl:28
cd at ./file.jl:20
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
cd at pkg/dir.jl:28
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
jl_f_apply at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_cd_20437 at  (unknown line)
test at pkg.jl:67
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
jl_f_apply at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_test_20434 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: -568960120)
unknown function (ip: -568963952)
unknown function (ip: -568896534)
jl_f_top_eval at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
eval_user_input at REPL.jl:53
jlcall_eval_user_input_20293 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
anonymous at task.jl:95
jl_handle_stack_switch at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
julia_trampoline at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 4199613)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 4199667)
unknown function (ip: 0)
Segmentation fault (core dumped)


julia> versioninfo()
Julia Version 0.3.7
Commit cb9bcae* (2015-03-23 21:36 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM)2 Duo CPU     T9400  @ 2.53GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```

**Comment by tkelman** [comment] 2015-05-29 02:20
> Why doesn't Pkg.test end after testing?

It runs `Pkg.resolve()` when it's done, which happens to be really slow. This is in case of needing to add any test-only dependencies from `test/REQUIRE`, though it could possibly be special-cased to skip the resolve step when there is no `test/REQUIRE` present.

**Comment by rened** [comment] 2015-08-12 07:34
@jhlq does this still crash for you? works for me on current master on linux.

On OSX though (independent of this issue) I run into problems because there exists both a  `equations.jl` and a  `Equations.jl` file, which does not work on case-insensitive file systems. The resulting error is:
```jl
NFO: Installing Equations v0.1.1
error: Your local changes to the following files would be overwritten by checkout:
        src/Equations.jl
Please, commit your changes or stash them before you can switch branches.
Aborting
INFO: Rolling back Docile from v0.5.15 to v0.5.14
INFO: Rolling back Blosc from v0.1.4 to v0.1.3
ERROR: failed process: Process(`git --work-tree=/Users/rene/.julia/v0.4/Equations --git-dir=/Users/rene/.julia/v0.4/Equations/.git checkout -q ad82f8e577f87d564ac3db6d417cf1ac7363de8c`, ProcessExited(1)) [1]
 in pipeline_error at process.jl:517
 in run at process.jl:493
```
I would suggest to rename `equations.jl`.

**Comment by jhlq** [comment] 2016-04-21 18:28
@rened Have not noticed any more crash like this but have not been very active with Julia lately. Thanks for the file name info.

**Comment by tkelman** [comment] 2016-04-21 22:06
closing unless we can get a reproducible report. thanks for reporting.

**Closed by tkelman** 2016-04-21 22:06 UTC
Labels: packages
