### ISSUE TITLE
IOStream issues

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#20863] opened 2017-03-02 23:25 UTC
There seems to be some kind of delay for IOStreams to start behaving properly
```julia
julia> io
IOStream(<file /var/folders/bk/3mjdz7xd3xx5pyg6b45fx50r0000gn/T/julia2ErUYS>)

julia> read(io)
3-element Array{UInt8,1}:
 0x68
 0x65
 0x79

julia> io = open(tmp)
IOStream(<file /var/folders/bk/3mjdz7xd3xx5pyg6b45fx50r0000gn/T/julia2ErUYS>)

julia> nb_available(io)
0

julia> dd = readavailable(io)
0-element Array{UInt8,1}

julia> read(io, 1)
1-element Array{UInt8,1}:
 0x68

julia> nb_available(io)
2

julia> readavailable(io)
2-element Array{UInt8,1}:
 0x65
 0x79
```

I'm on OSX, this is on a couple days old master, as well as 0.5.

**Comment by malmaud** [comment] 2017-03-03 17:15
I think this is working as intended. 

`nb_available` is how many bytes can be returned without blocking and a task switch.

It is 0 at first, since the current task blocks as the bytes are loaded into a memory buffer. but since it loads them in chunks, after the blocking `read`, there are still more bytes available in the buffer that won’t require blocking to read.

**Comment by KristofferC** [comment] 2017-05-26 18:02
Closing as there doesn't seem to be a bug here.

**Closed by KristofferC** 2017-05-26 18:02 UTC
Labels: I/O
