### ISSUE TITLE
Creating many SharedArrays across multiple workers results in shm_open() failure: Too many open files

### ISSUE THREAD

**Issue by JohnHBrock** [JuliaLang/julia#12521] opened 2015-08-08 20:01 UTC
When using multiple workers to create many SharedArrays, I get a "Too many open files" error. Running the code with `julia test_code.jl` instead of `julia -p 4 test_code.jl` seems to get rid of the error.

versioninfo():
```
Julia Version 0.3.11
Commit 483dbf5 (2015-07-27 06:18 UTC)
Platform Info:
  System: Linux (x86_64-amazon-linux)
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

Example code:
```Julia
function doStuff()
  container = SharedArray{Int64,1}[]
  resize!(container, 1024)
  @sync @parallel for i=1:1024
    container[i] = convert(SharedArray,rand(Int64, 10))
  end
end

doStuff()
```

Sample execution:
```
$ julia -p 4 test_code.jl
exception on 2: exception on ERROR: shm_open() failed for /jl618081439062831622710016: Too many open files
 in _jl_spawn at process.jl:217
 in spawn at process.jl:348
 in open at /home/jbrock/julia3/usr/bin/../lib/julia/sys.so
 in readbytes at /home/jbrock/julia3/usr/bin/../lib/julia/sys.so
 in print_shmem_limits at sharedarray.jl:319
 in shm_mmap_array at sharedarray.jl:346
 in anonymous at sharedarray.jl:58
 in anonymous at multi.jl:848
 in run_work_thunk at multi.jl:621
 in run_work_thunk at multi.jl:630
 in anonymous at task.jl:6
2: exception on exception on ERROR: shm_open() failed for /jl618101439062831622867200: Too many open files
 in _jl_spawn at process.jl:217
 in spawn at process.jl:348
 in open at /home/jbrock/julia3/usr/bin/../lib/julia/sys.so
 in readbytes at /home/jbrock/julia3/usr/bin/../lib/julia/sys.so
 in print_shmem_limits at sharedarray.jl:319
 in shm_mmap_array at sharedarray.jl:346
 in anonymous at sharedarray.jl:58
 in anonymous at multi.jl:848
 in run_work_thunk at multi.jl:621
 in run_work_thunk at multi.jl:630
 in anonymous at task.jl:6
22: : ERROR: shm_open() failed for /jl618091439062831796041984: Too many open files
 in _jl_spawn at process.jl:217
 in spawn at process.jl:348
 in open at /home/jbrock/julia3/usr/bin/../lib/julia/sys.so
 in readbytes at /home/jbrock/julia3/usr/bin/../lib/julia/sys.so
 in print_shmem_limits at sharedarray.jl:319
 in shm_mmap_array at sharedarray.jl:346
 in anonymous at sharedarray.jl:58
 in anonymous at multi.jl:848
 in run_work_thunk at multi.jl:621
 in run_work_thunk at multi.jl:630
 in anonymous at task.jl:6

(etc.)
```

**Comment by tkelman** [comment] 2015-08-08 20:07
I can reproduce on 0.3 but on 0.4 it appears to work:
```
julia> doStuff()
4-element Array{Any,1}:
 RemoteRef{Channel{Any}}(2,1,5)
 RemoteRef{Channel{Any}}(3,1,7)
 RemoteRef{Channel{Any}}(4,1,9)
 RemoteRef{Channel{Any}}(5,1,11)
```

I don't think the parallel reorganizations that evidently made this work are candidates for backporting to 0.3 at this point.

**Comment by amitmurthy** [comment] 2015-08-09 07:37
This is not really a Julia issue. You need to look at and probably increase system limits for both open files per process and per user. In case of `julia -p4`, there are open fd's for the shmem segments as well as TCP/IP sockets for worker connections.

**Comment by JohnHBrock** [comment] 2015-08-09 08:15
Increasing the limits doesn't seem to help. And on my machine, the system and user limits for open files are at least an order of magnitude higher than the number of SharedArrays in my example code (1024), so that seems like an unlikely culprit with only 4 workers.

It seems like this is a Julia issue if it's broken in 0.3 and works in 0.4. At the very least, the handling of this error should be better (e.g., I need to issue a `kill -9` after this error to terminate the julia processes).

**Comment by amitmurthy** [comment] 2015-08-09 09:40
Unrelated to the discussion above, to be noted that the `@parallel` does not do what is probably expected in this case. In the case of `julia -p4`, `container` in the calling process will not have the SharedArray handles.

**Comment by JohnHBrock** [comment] 2015-08-09 13:34
Right, you mean because container is an Array and not a SharedArray?

**Comment by timholy** [comment] 2015-08-09 15:19
@JohnHBrock, since this works in julia 0.4 and release is near, I think it's fair to say that this is a "wontfix" as far as 0.3 is concerned.

The error handling might be a separate issue, though.

**Comment by jakebolewski** [comment] 2015-08-11 11:28
@JohnHBrock please open another issue for better error handling on 0.3.

**Closed by jakebolewski** 2015-08-11 11:28 UTC
