### ISSUE TITLE
no method matching isvalid(::SubString{String})

### ISSUE THREAD

**Issue by joa-quim** [JuliaLang/julia#24214] opened 2017-10-19 16:22 UTC
Although the docs say "Char" or "String"

```
Returns true if the given value is valid for that type. Types currently can be either Char or String.
```

SubStrings should be accepted as well, but they aren't.

```
isvalid(lstrip(" blabla"))
ERROR: MethodError: no method matching isvalid(::SubString{String})
Closest candidates are:
  isvalid(::SubString, ::Integer) at strings/types.jl:70
  isvalid(::AbstractString, ::Integer) at strings/basic.jl:228
  isvalid(::Char) at strings/utf8proc.jl:56
```

**Comment by stevengj** [comment] 2017-10-19 17:14
Looks pretty easy to extend the [current code](https://github.com/JuliaLang/julia/blob/a1c9549d0d7503137157f5f85d7d805467af4e9b/base/strings/string.jl#L175-L184) to handle this.  Just change `byte_string_classify(s::String)` to
```jl
byte_string_classify(s::Union{String,SubString{String}}) =
    ccall(:u8_isvalid, Int32, (Ptr{UInt8}, Int), pointer(s), sizeof(s))
```
and then widen the signature of `isvalid(::Type{String}, s::Union{Vector{UInt8},String})` to allow `SubString{String}`.

**Comment by nalimilan** [comment] 2017-10-20 08:56
If you add it, please also add a test.

**Comment by stevengj** [comment] 2017-10-20 21:55
In general, it looks like substrings are pretty broken for invalid strings:
```
julia> s = SubString(String(UInt8[0xfe, 0x80, 0x80, 0x80, 0x80, 0x80]), 1,2)
"\U80000000"

julia> String(s)
6-byte String of invalid UTF-8 data:
 0xfe
 0x80
 0x80
 0x80
 0x80
 0x80
```

**Comment by nalimilan** [comment] 2017-10-21 09:44
@bkamins ^

**Comment by bkamins** [comment] 2017-10-21 11:40
@stevengj Are you testing this on latest? The result you give is present on 0.6.
Now it should be fixed and `ss = SubString(s, 1, 2)` should throw `BoundsError` (if it does not please let me know as this is the expected behavior).

**Comment by nalimilan** [comment] 2017-10-21 11:47
Indeed, it's great that your recent changes fixed this kind of bug:
```julia
julia> s = String(UInt8[0xfe, 0x80, 0x80, 0x80, 0x80, 0x80])
6-byte String of invalid UTF-8 data:
 0xfe
 0x80
 0x80
 0x80
 0x80
 0x80

julia> ss = SubString(s, 1, 2)
ERROR: BoundsError: attempt to access 6-byte String of invalid UTF-8 data:
 0xfe
 0x80
 0x80
 0x80
 0x80
 0x80
  at index [2]
Stacktrace:
 [1] SubString{String}(::String, ::Int64, ::Int64) at ./strings/types.jl:33
 [2] SubString(::String, ::Int64, ::Int64) at ./strings/types.jl:38

```

**Comment by joa-quim** [comment] 2018-04-27 15:48
Bump

**Comment by joa-quim** [comment] 2018-04-27 17:51
But isn't this fixed by #24132? It only needs to be merged, I think.

**Comment by nalimilan** [comment] 2018-04-27 18:24
Ah, you mean https://github.com/JuliaLang/julia/pull/25285? I've rebased it, let's see how it goes. FWIW, better bump the PR than the issue next time.

**Comment by raghav9-97** [comment] 2018-12-09 17:19
Is this issue still open? I would like to work on this issue.

**Comment by raghav9-97** [comment] 2018-12-09 17:51
Thanks for the reference @nalimilan

**Closed** 2018-12-17 22:41 UTC
Labels: Hacktoberfest, good first issue, strings
