### ISSUE TITLE
Signature affects allocations when passing functions

### ISSUE THREAD

**Issue by awllee** [JuliaLang/julia#28720] opened 2018-08-17 10:04 UTC
I'm not sure if this is an issue or whether there is an expected performance problem with forwarding functions with varargs (or something else). As suggested in a [discourse thread](https://discourse.julialang.org/t/varargs-performance/13578) I'm submitting it here as an issue.

The following code run as a script with `-O3`

```using BenchmarkTools
using InteractiveUtils

function foo(f::F, m::Int64, args...) where F<:Function
  for i in 1:m
    z = f(args...)
  end
  return true
end

function g(x::Float64, y::Float64)
  return rand() < 0.5, 1
end

function bar(f::F, m::Int64, x::Float64, y::Float64) where F<:Function
  for i in 1:m
    z = f(x, y)
  end
  return true
end

versioninfo()

@btime foo(g, 1000, 1.0, 2.0)
@btime bar(g, 1000, 1.0, 2.0)
```

gives as output

```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4

  38.486 μs (1000 allocations: 31.25 KiB)
  1.260 μs (0 allocations: 0 bytes
```

This suggests there could be an issue with forwarding arguments with varargs.

Changing many things in isolation eliminates the allocations, e.g. if

1. `g` returns `rand() < 0.5`
2. `g` returns `x < y, 1`

**Comment by pablosanjose** [comment] 2018-08-17 11:32
I also encountered something like this. I found that the following trivial rewriting of foo fixes the problem. I would also be very interested to understand why this happens.
```
function foo(f::F, m::Int64, args::Vararg{Any,N}) where {F<:Function, N}
         for i in 1:m
           z = f(args...)
         end
         return true
       end
```
```
julia> @btime foo($g, 1000, 1.0, 2.0)
  1.028 μs (0 allocations: 0 bytes)
```

**Comment by awllee** [comment] 2018-08-17 11:42
That's interesting. While this eliminates the penalty in this MWE, it actually makes the problem worse on the original code I was working on (not yet public, unfortunately).

**Comment by awllee** [comment] 2018-08-17 17:08
Here is a second MWE, now with no tuple return types. Again the example is brittle in that if one replaces sqrt(sqrt(v)) and sqrt(1.0) with less expensive things then there is no issue.

```
using BenchmarkTools
using Compat.InteractiveUtils

function foo1(f::F, m::Int64, v::Float64, args...) where F<:Function
  for i in 1:m
    f(args...)
  end
  return sqrt(sqrt(v))
end

function foo2(f::F, m::Int64, v::Float64, args::Vararg{Any, N}) where
  {F<:Function, N}
  for i in 1:m
    f(args...)
  end
  return sqrt(sqrt(v))
end

function bar(f::F1, m::Int64, v::Float64, x::Float64, y::F2) where
  {F1<:Function, F2<:Function}
  for i in 1:m
    f(x, y)
  end
  return sqrt(sqrt(v))
end

function g(x::Float64, y::F) where F<:Function
  return y()
end

function y()
  return sqrt(1.0)
end

versioninfo()
println()

@btime foo1(g, 1000, 16.0, 1.0, y)
@btime foo2(g, 1000, 16.0, 1.0, y)
@btime bar(g, 1000, 16.0, 1.0, y)
```

with output

```
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4

  33.159 μs (1001 allocations: 15.64 KiB)
  54.172 μs (2003 allocations: 31.30 KiB)
  4.880 ns (0 allocations: 0 bytes)
```

On 0.6.4 the output is different:

```
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)

  34.903 μs (1001 allocations: 15.64 KiB)
  21.378 μs (1001 allocations: 15.64 KiB)
  4.879 ns (0 allocations: 0 bytes)
```

**Comment by pablosanjose** [comment] 2018-08-17 17:59
Thanks! For what it's worth, I don't think the underlying issue here is related to kwarg forwarding: 
```
function bar2(f::F, m::Int64, v::Float64, x::Float64, y) where {F<:Function}
  for i in 1:m
    f(x, y)
  end
  return sqrt(sqrt(v))
end
```
```
julia> @btime bar2(g, 1000, 16.0, 1.0, y)
  17.694 μs (2001 allocations: 31.27 KiB)
2.0
```

**Comment by awllee** [comment] 2018-08-18 13:43
Yes. Notwithstanding some minor differences in performance, and in particular the unfortunate poorer performance in a few situations with `args::Vararg{Any,N}` vs `args...`, this appears to be more of an issue with non-specialization of functions in `args...`.

I am still not super clear as a user when providing type information is necessary for performance, so I typically default to providing it whenever possible, which is probably suboptimal in terms of code re-use.

Anyway, I don't think this is actually an issue and so I'll close it.

**Comment by pablosanjose** [comment] 2018-08-18 13:49
Ok, it might not be an issue, but it doesn't seem trivial to me.  I don't think adding `y::F2` in `bar2` should change performance. Also, it is very intriguing that the difference doesn't show up in `@code_warntype`. I would prefer that you leave this open until you get a more qualified response from a core developer, just to be sure.

**Comment by awllee** [comment] 2018-08-18 13:51
Okay, re-opened as suggested. But happy for it to be closed if it is considered part of larger issue around specialization and non-specialization.

**Comment by pablosanjose** [comment] 2018-08-18 14:52
Great, thanks Anthony. It might be good to rename the issue to better capture the problem at hand. Let me try to clarify your observation a bit more. This is a distilled version of your second MWE

```
g() = sqrt(1.0)
f(g) = g()
foo(f, g) = for i in 1:1000; f(g); end
foo2(f::Function, g::Function) = for i in 1:1000; f(g); end
bar(f::F1, g::F2) where {F1<:Function, F2<:Function} = for i in 1:1000; f(g); end
```
Under v0.7/1.0 (second run)
```
julia> @time foo(f,g)
  0.000102 seconds (1.00 k allocations: 15.781 KiB)
julia> @time foo2(f,g)
  0.000073 seconds (1.00 k allocations: 15.781 KiB)
julia> @time bar(f,g)
  0.000004 seconds (4 allocations: 160 bytes)
```

Then there is the other issue, from your first MWE, that could perhaps be distilled into the following
```
f(x,y) = (rand() < 0.5, 1)
foo(f, args...) = for i in 1:1000; z = f(args...); end
foo2(f::F, args...) where {F<:Function} = for i in 1:1000; z = f(args...); end
bar(f::F, args::Vararg{Any,N}) where {F<:Function, N} = for i in 1:1000; z = f(args...); end
```
Under v0.7/1.0 (second run)
```
julia> @time foo(f, 1, 2)
  0.000163 seconds (1.00 k allocations: 31.406 KiB)
julia> @time foo2(f, 1, 2)
  0.000143 seconds (1.00 k allocations: 31.406 KiB)
julia> @time bar(f, 1, 2)
  0.000009 seconds (4 allocations: 160 bytes)
```

Are these two separate issues? I'm not sure, perhaps not. It seems that, in both cases, the underlying problem is that making the function signature less specific (as in `foo`) leads to more allocations. AFAIU, this should never happen, as the signature should just serve as a way to narrow down dispatch. The problem happens when passing a sufficiently complex function as a parameter (it goes away when one simplifies `g()` or `f(x,y)`).

So perhaps you could rename this issue to "Signature affects allocations when passing functions", or something along those lines?

**Comment by awllee** [comment] 2018-08-18 15:00
Will do.

My reading of the [compiler efficiency documentation](https://docs.julialang.org/en/v1.0.0/devdocs/functions/#Compiler-efficiency-issues-1) suggests that "excessive specialization of functions" is problematic.

**Comment by pablosanjose** [comment] 2018-08-18 15:08
I believe that stuff you link to is mostly related to compile time. I'm actually amazed multiple dispatch can be made to work as well as it does in Julia. It seems like a fiendishly complex thing.  In your case, however, the issue persists *after* compilation (second run), and in fact arises when there is *too little* specialisation (`foo` and `foo2`). I do believe it is a bug. It might even be a duplicate of a known issue.

**Comment by KristofferC** [comment] 2019-10-15 13:09
Closing as dup of https://github.com/JuliaLang/julia/issues/32761 even though this issue is older, since that one has a bit more discussion.

**Closed by KristofferC** 2019-10-15 13:09 UTC
