### ISSUE TITLE
llvmcall test failure with LLVM 3.6.0 on Win64

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#10394] opened 2015-03-03 21:58 UTC
See https://gist.github.com/tkelman/adddb1018adabbb6711b

Mostly lapack / ccall seems broken. The core failure in `jl_method_table_assoc_exact` is also worrying. Dict and hashing just die with no error.

On win32 things are reasonable if you run the tests one at a time (hits #10377 but otherwise ok), though trying to run all of the tests in the same process results in this:
```
    JULIA test/all
     * linalg1              in 109.44 seconds
     * linalg2              in 120.57 seconds
     * linalg3              in  34.47 seconds
     * linalg4              in  57.44 seconds
     * linalg/lapack        in   7.78 seconds
     * linalg/triangular    in 1033.00 seconds
     * linalg/tridiag       in  23.88 seconds
     * linalg/pinv          in  27.93 seconds
     * linalg/givens        in  19.15 seconds
     * linalg/cholesky      in  59.27 seconds
     * linalg/lu            in   0.94 seconds
     * linalg/arnoldi       in  19.38 seconds
     * core                 in 248.43 seconds
     * keywordargs          in  38.54 seconds
     * numbers              in 992.47 seconds
     * strings              in 401.38 seconds
     * dates                in 1106.73 seconds
     * dict                 in 155.75 seconds
     * hashing
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Makefile:9: recipe for target 'all' failed
make[1]: *** [all] Error 3
Makefile:496: recipe for target 'testall1' failed
make: *** [testall1] Error 2
```

**Comment by tkelman** [comment] 2015-03-06 04:36
Oh boy, julia-debug.exe segfaults immediately in either win32 or win64. gist.github.com/3b9ddfa24b74b53814c9

**Comment by tkelman** [comment] 2015-03-18 16:15
With LLVM assertions enabled, we get
```
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: D:\cygwin64\home\Tony\julia\usr\bin\julia-debug.exe
File: /home/Tony/julia/deps/llvm-3.6.0/lib/CodeGen/AsmPrinter/DwarfCompileUnit.cpp, Line 104

Expression: GV.isGlobalVariable()
```

**Comment by tkelman** [comment] 2015-03-18 19:38
I think most of the issue is something about ccall'ing into Fortran libraries, since openspecfun has trouble too. llvmcall fails an assertion:
```
     * llvmcall
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: D:\cygwin64\home\Tony\julia\usr\bin\julia.exe
File: debuginfo.cpp, Line 340

Expression: SectionAddrCheck == SectionAddr
```

ccall segfaults https://gist.github.com/tkelman/697c8f73f072cfdecc9f
and socket segfaults https://gist.github.com/tkelman/084003af7f8f7c61ee4c
(these were built at 2a4fd4412f59455e19f6b5a44b8af254fb2fe2d9)

**Comment by ihnorton** [comment] 2015-03-28 19:25
While debugging #10368 I noticed the following: if I run the test lines on a local build against LLVM3.6, I get thousands of lines of `On entry to DGEMV  parameter number  1 had an illegal value`. I believe this to be incidental (although it does confirm the reporter's observation that the segfault is directly related to the return value creation which does matrix multiplication). However, some googling suggests that this error may be related to calling convention (and bitness) issues). If so, that could explain some of the failures seen in this issue.

**Comment by tkelman** [comment] 2015-03-29 05:43
I'm fairly confident the Fortran calling convention in ccall is busted with LLVM 3.6 for some reason, since almost anything lapack or openspecfun or arpack related isn't working.

**Comment by ViralBShah** [comment] 2015-03-29 17:42
Cc: @vtjnash

**Comment by vtjnash** [comment] 2015-03-30 03:10
It's possible/likely that llvm3.6 is using a different windows calling convention than previous versions of llvm. usually that has only affected C++11 code, but sometimes it crosses over to the C ABI.

> With LLVM assertions enabled, we get ...

I've been struggling with that one since the new GC merged. I think Keno finally found the fix for it in da3d7d53be01959b4e3d93fadaf94d3d991af01b

**Comment by ihnorton** [comment] 2015-03-30 03:29
I've tested [this](https://gist.github.com/ihnorton/c7c959285a4fcecc2c23) with all the calling conventions but haven't seen any change. It's possible I am setting things up wrong, but the error is in parameter 1 which should be the simplest.

**Comment by vtjnash** [comment] 2015-03-30 03:42
if you're feeling particularly ambitious, it would be informative to single step by instructions through the `dgemv64_` function until it calls `xerbla`, and see what value it loads for the first parameter. it seems odd that this would be failing with llvm3.6, since it doesn't seem like that much should have changed.

**Comment by ihnorton** [comment] 2015-03-30 04:49
Well, looking at the registers in an LLVM33 build, it gets the first argument in RCX (which is correctly `N`). With LLVM36 that pointer is garbage.

**Comment by vtjnash** [comment] 2015-03-30 04:53
what does it point to? it should be a dynamically-allocated stack box, but perhaps it is declared in the wrong scope so llvm is deallocating it early?

**Comment by ihnorton** [comment] 2015-03-30 04:59
Nevermind, my function was still `stdcall`. The pointer is good but the data is `\001`. Most of the registers have the same (useless) pointer:
```
(gdb) info reg
rax            0x6d7cf320       1836905248
rbx            0xd5f250 14021200
rcx            0xd5f250 14021200
rdx            0xd5f250 14021200
rsi            0x1      1
rdi            0xd5f250 14021200
rbp            0xd5f290 0xd5f290
rsp            0xd5f110 0xd5f110
r8             0xd5f250 14021200
r9             0xd5f250 14021200
r10            0x82f2add0       2196942288
r11            0x2      2
r12            0xd5f250 14021200
r13            0x8311ee30       2198990384
r14            0x82f2ae00       2196942336
r15            0x830ee520       2198791456
rip            0x6d7cf33b       0x6d7cf33b <dgemv_+27>
```

**Comment by ihnorton** [comment] 2015-03-30 15:51
I checked the IR generated by clang (svn) for the same call, and it is basically the same, so this doesn't seem like our bug. Tonight I'll try turning off various passes, and also disabling copy propagation (#9199).

**Comment by ihnorton** [comment] 2015-03-30 22:40
Looks like this is just a deprecation issue with `&`. Switching to `Ref{}` fixes the problem in my test case.

(At some point we will need to change all the Fortran wrappers to use the new syntax, but that is orthogonal. We do need the deprecation to work for now).

**Comment by vtjnash** [comment] 2015-03-31 00:17
those go through very different code paths, so it still doesn't point to what part of the llvm bytecode was emitted incorrectly

**Comment by ihnorton** [comment] 2015-04-01 21:42
Here are several reduced examples (...compared to the 1000 lines of IR for the real `dgemv!`).

[This](https://gist.github.com/ihnorton/5965e855221b0e371a37#file-z_llvm33_output-ll) is what we emit with 3.3.

Here are [`&`](https://gist.github.com/ihnorton/5965e855221b0e371a37#file-good)   and [`Ref`](https://gist.github.com/ihnorton/5965e855221b0e371a37#file-bad) examples with 3.6.

[Here](https://gist.github.com/ihnorton/5965e855221b0e371a37#file-runnable-test-ll) is a stand-alone version that is runnable with `lli`. See [line 57](https://gist.github.com/ihnorton/5965e855221b0e371a37#file-runnable-test-ll-L57): if that is commented out then the register is left alone and we get a pointer to char* 'N' in RCX as expected. (or alternatively if I comment out [these lines](https://gist.github.com/ihnorton/5965e855221b0e371a37#file-runnable-test-ll-L39-L48) and add a dummy `%8` variable).

**Comment by vtjnash** [comment] 2015-04-01 21:56
It looks like an llvm bug then? llvm comes with a bugpoint tool for isolating errors in lowering code. Alternatively, differencing the assembly generated by the good and bad versions of the llvm bytecode can help with identifying what went wrong. Since llvm36 added a custom lowing for the win64 alloca instruction (that turns it into a function call), I'm going to guess it might be not preserving this register correctly across that function

**Comment by ihnorton** [comment] 2015-04-01 23:15
Yes, unless you or @Keno have a chance to look, and see anything obviously
wrong with the IR linked from the last paragraph. It seems to me that we
are emitting redundant allocas, so maybe the alloca lowering thinks it can
combine something that shouldn't be. I don't have a llvm-svn build right
now but I'm going to double-check that, and work through the assembly next
while it is compiling (sigh, should have gotten a bigger SSD).

**Comment by vtjnash** [comment] 2015-04-01 23:28
Since you have the llvm bytecode now, you can run llc on any machine to investigate the resulting assembly

**Comment by vtjnash** [comment] 2015-04-01 23:33
The redundant alloca might be an artifact of not having marked the arguments as isSA in the initial codegen assignments  I don't think that should matter here though?

**Comment by ihnorton** [comment] 2015-04-02 04:07
Thanks, I do have `llc`. I just want to check llvm-svn before filing a bug.

Is there that much difference in codegen paths between 3.5 and 3.6? @tkelman do you have an  LLVM3.5 build -- if so, could you check the IR for [this function](https://gist.github.com/ihnorton/5965e855221b0e371a37#file-bad)

**Comment by vtjnash** [comment] 2015-04-02 05:11
the `___chkstk` call in that assembly reallly shouldn't be there at all in that function's assembly. however, at least on llvm-svn it calls `__chkstk_ms`

**Comment by ihnorton** [comment] 2015-04-02 05:16
[Here](https://gist.github.com/ihnorton/b86c5a09937687a2a65c) is the `code_native` too (per irc).

**Comment by tkelman** [comment] 2015-04-02 05:24
I can't get a build using 3.5.1 to finish bootstrapping on current master, unknown function access violation in linalg1?

**Comment by vtjnash** [comment] 2015-04-02 05:30
we should cherry-pick the following commit onto our llvm-3.6.0, otherwise the MCJIT will remain DOA for win64 (https://github.com/JuliaLang/julia/issues/9339):

```
commit c9fbc97e9553b257d35ba4507a478bc8fc9459fb
Author: Reid Kleckner <reid@kleckner.net>
Date:   Thu Jan 29 23:58:04 2015 +0000

    x86: Fix large model calls to __chkstk for dynamic allocas
    
    In the large code model, we now put __chkstk in %r11 before calling it.
    
    Refactor the code so that we only do this once. Simplify things by using
    __chkstk_ms instead of __chkstk on cygming. We already use that symbol
    in the prolog emission, and it simplifies our logic.
    
    Second half of PR18582.
    
    git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@227519 91177308-0d34-0410-b5e6-96231b3b80d8
```

**Comment by tkelman** [comment] 2015-04-02 05:42
We should be able to pull that in as a patch file, unless we're also planning on relying on a more substantially modified branch soon.

**Comment by tkelman** [comment] 2015-04-03 00:47
Not sure what was wrong yesterday, works better with 3.5.1 today.
```
julia> versioninfo()
Julia Version 0.4.0-dev+4142
Commit 8e32963* (2015-04-02 19:17 UTC)
DEBUG build
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.5.1

julia> n = 'N'; i = 1;

julia>  bf(n,i) = ccall((:mydgemv, "libt.dll"),
                     Void,
                     (Ptr{Cchar},Ptr{Int}), &n, &i)
bf (generic function with 1 method)

julia> bf(n,i)
N

julia> @code_llvm bf(n,i)

; Function Attrs: sspreq uwtable
define void @julia_bf_1314(i32, i64) #0 {
top:
  %sext = shl i32 %0, 24, !dbg !11
  %2 = ashr exact i32 %sext, 24, !dbg !11
  %3 = icmp eq i32 %2, %0, !dbg !11
  br i1 %3, label %pass, label %fail, !dbg !11

fail:                                             ; preds = %top
  %4 = load %jl_value_t** @jl_inexact_exception, align 8, !dbg !11, !tbaa %jtbaa
_const
  call void @jl_throw_with_superfluous_argument(%jl_value_t* %4, i32 1), !dbg !1
1
  unreachable, !dbg !11

pass:                                             ; preds = %top
  %5 = trunc i32 %0 to i8, !dbg !11
  %6 = alloca i8, align 1, !dbg !11
  store i8 %5, i8* %6, align 1, !dbg !11
  %7 = alloca i64, align 8, !dbg !11
  store i64 %1, i64* %7, align 8, !dbg !11
  call void inttoptr (i64 1825313888 to void (i8*, i64*)*)(i8* %6, i64* %7), !db
g !11
  ret void, !dbg !11
}
```

**Comment by ihnorton** [comment] 2015-04-03 00:56
Thanks! The issue is fixed on llvm-svn (and the IR is identical to 3.5 and 3.3). The patch Jameson linked doesn't apply cleanly but I'm working on it now.

**Comment by ihnorton** [comment] 2015-04-03 00:58
Actually there was a failure in linalg3 but haven't debugged yet. I haven't run the full suite, but the other linalg tests passed.

**Comment by vtjnash** [comment] 2015-04-03 01:04
i only pointed to part 2 of that patch. part 1 is also required.

**Comment by ihnorton** [comment] 2015-04-03 17:29
There are still some test failures with the patch, but saner number now and no obvious Fortran calling issues.

**Comment by vtjnash** [comment] 2015-04-03 23:26
keep posting which specific tests are failing and we'll try to keep burning the list down

**Comment by tkelman** [comment] 2015-04-04 08:20
At least running the tests one at a time with debug LLVM, it looks like that patch fixed everything except llvmcall. Nice work. https://gist.github.com/tkelman/99f050d31e39cbb68d70

**Comment by vtjnash** [comment] 2015-04-04 16:03
it's perhaps possible that I broke llvmcall when fixing the calling conventions. since it is undocumented and under-tested, it was hard to know.

**Comment by tkelman** [comment] 2015-04-04 23:19
Interestingly if I run the linalg tests all in a single process, I get a failure at arnoldi:
```
     * linalg/arnoldi
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x29a77d95f -- umfzl_scale at  (unknown line)
umfzl_scale at D:\cygwin64\home\Tony\julia\usr\bin\libumfpack.DLL (unknown line)
umfzl_scale_column at D:\cygwin64\home\Tony\julia\usr\bin\libumfpack.DLL (unknown line)
umfzl_kernel at D:\cygwin64\home\Tony\julia\usr\bin\libumfpack.DLL (unknown line)
umfpack_zl_numeric at D:\cygwin64\home\Tony\julia\usr\bin\libumfpack.DLL (unknown line)
umfpack_numeric! at .\sparse\umfpack.jl:180
lufact at .\sparse\umfpack.jl:113
factorize at .\sparse\linalg.jl:685
eigs at .\linalg\arnoldi.jl:88
unknown function (ip: -1592454017)
jl_apply_generic at /home/Tony/julia/src\gf.c:1707
unknown function (ip: -1593505778)
unknown function (ip: -1593505418)
eigs at .\linalg\arnoldi.jl:5
unknown function (ip: -1593638483)
anonymous at .\no file:42
jl_apply at /home/Tony/julia/src\julia.h:1261
jl_toplevel_eval_flex at /home/Tony/julia/src\toplevel.c:546
jl_load_ at /home/Tony/julia/src\toplevel.c:598
runtests at D:\cygwin64\home\Tony\julia\test\testdefs.jl:78
unknown function (ip: 251331815)
jl_apply_generic at /home/Tony/julia/src\gf.c:1709
jl_f_apply at /home/Tony/julia/src\builtins.c:413
anonymous at .\multi.jl:626
run_work_thunk at .\multi.jl:587
remotecall_fetch at .\multi.jl:660
jl_apply_generic at /home/Tony/julia/src\gf.c:1709
jl_f_apply at /home/Tony/julia/src\builtins.c:465
remotecall_fetch at .\multi.jl:675
jl_apply_generic at /home/Tony/julia/src\gf.c:1709
jl_f_apply at /home/Tony/julia/src\builtins.c:465
anonymous at .\task.jl:1386
start_task at /home/Tony/julia/src\task.c:233
Makefile:9: recipe for target 'linalg' failed
make[1]: *** [linalg] Error 1
Makefile:503: recipe for target 'test-linalg' failed
make: *** [test-linalg] Error 2
```
But it works fine if I run each test individually. Happens with either debug+asserts or release+asserts patched LLVM 3.6.0, but not LLVM 3.3.

**Comment by ihnorton** [comment] 2015-04-05 18:07
llvmcall is fine for me, but I get test failures consistently in linalg2, numbers, and markdown: https://gist.github.com/ihnorton/07c32daeb2ad8e2f5dbb

The linalg2 failure is in norm for `Complex{Float64}`:
```
julia> include("linalg2.jl")
Float32
Float64
Base.MPFR.BigFloat
Complex{Float32}
Complex{Float64}
ERROR: LoadError: assertion failed: |norm(x,-1) - 1 / 10| <= 1.3877787807814457e-13
  norm(x,-1) = 0.0
  1 / 10 = 0.1
  difference = 0.1 > 1.3877787807814457e-13
 in error at .\error.jl:20
 in test_approx_eq at .\test.jl:137
 in anonymous at .\no file:229
 in include at <invalid>
 in include_from_node1 at <invalid>
while loading C:\dev\jl36-cyg\test\linalg2.jl, in expression starting on line 221
```

**Comment by tkelman** [comment] 2015-04-05 21:46
That's really odd that we would get such different results when we're both on sandy bridge... are you using Windows 8? I'm on 7.

**Comment by ihnorton** [comment] 2015-04-05 21:52
7 as well. I don't know what gives.

**Comment by tkelman** [comment] 2015-04-05 21:54
Oh, probably relevant, in my `Make.user` I have `override MARCH = x86-64`. If you don't have that, it might be a bug with AVX?

**Comment by tkelman** [comment] 2015-04-06 00:18
On a Haswell Win7 machine without `MARCH` set, I see the same failures as you in linalg2 and numbers, but not in Markdown strangely enough.

**Comment by ihnorton** [comment] 2015-04-11 05:17
Reduced case for the norm (linalg2) failure:
```
elty = Complex{Float64}; x = ones(elty,10); p = -1
function gvp(x, p) # from generic_vecnormp
        av = float(abs(x[1]))
        T = typeof(av)
        pp::promote_type(Float64, T) = p

        # println("pp: ", pp) # Y U NO WORK THING?!?

        sum::promote_type(Float64, T) = av^pp
        s = start(x)
        (v,s) = next(x,s)
        while !done(x, s)
            (v, s) = next(x, s)
            sum += abs(v)^pp
        end
        return convert(T, sum^inv(pp))
end
```

Uncommenting the `println` makes it work... :hankey:

**Comment by ihnorton** [comment] 2015-04-14 05:18
Looks like it's still a calling convention issue; 3.6 is putting args to `pow` in the wrong registers. [assembly comparisons](https://gist.github.com/ihnorton/ec4ec85dd615c1992c0f). I'm waiting for my llvm-svn update to finish building to see if there is any improvement.

**Comment by vtjnash** [comment] 2015-04-15 04:29
wow, it's my second copyprop bug of the day!

https://github.com/JuliaLang/julia/blob/d2ee85d1135fd801f1230530f39f05369f6384df/src/codegen.cpp#L5607-L5609 should be applied to all versions of llvm (tested, but not entirely confirmed, on LLVM3.3 and LLVM3.6 today on win64)

**Comment by ihnorton** [comment] 2015-04-15 04:31
:sob:

**Comment by vtjnash** [comment] 2015-04-15 04:32
cross link https://github.com/JuliaLang/julia/issues/9199

**Comment by ihnorton** [comment] 2015-04-15 05:18
How did you test that? I get `'-disable-copyprop' is not a recognized feature for this target (ignoring feature)`

**Comment by vtjnash** [comment] 2015-04-15 05:31
in various indirect ways. i may have missed some combination of julia and llvm versions?

**Comment by ihnorton** [comment] 2015-04-15 05:47
Sorry, I just saw your comments on the gist ([because github](https://github.com/isaacs/github/issues/21)). Replied there (yes, they were swapped. too many consoles).

**Comment by ihnorton** [comment] 2015-04-15 05:54
I tested with `MAttrs.push_back("-disable-copyprop")` outside of that ifdef block (and I know it was actually applied because of the error message). I didn't do a full rebuild though, just `src/`, not sure if that makes a difference due to the cached image? (rebuilding now)

**Comment by ihnorton** [comment] 2015-04-15 13:24
Looking better now: llvmcall and linalg2 both pass. Now I get a weird failure in the markdown test, not sure if related:

```
$ make markdown
    JULIA test/markdown
     * markdown            exception on 1: ERROR: LoadError: test failed: (Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["#"]),Base.Markdown.Paragraph(Any["empty"])],Dict{Any,Any}(:config=>Base.Markdown.Config([hashheader,fencedcode,blockquote],[blocktex,blockinterp,list,indentcode,github_table,horizontalrule,setextheader,paragraph],Dict('['=>[link],'\\'=>[linebreak,escapes],'*'=>[asterisk_bold,asterisk_italic],'$'=>[tex,interp],'`'=>[inline_code],'!'=>[image],'-'=>[en_dash])))) == Base.Markdown.MD(Any[Base.Markdown.Header{1}(""),Base.Markdown.Paragraph("empty")],Dict{Any,Any}()))
 in expression: @md_str $(Expr(:triple_quoted_string, "\r\n  #\r\n  empty\r\n  ")) == MD(Header{1}(""),Paragraph("empty"))
 in error at .\error.jl:19
 in default_handler at .\test.jl:27
 in do_test at .\test.jl:50
 in runtests at C:\dev\jl36-cyg\test\testdefs.jl:78
 in anonymous at .\multi.jl:626
 in run_work_thunk at .\multi.jl:587
 in remotecall_fetch at .\multi.jl:660
 in remotecall_fetch at .\multi.jl:675
 in anonymous at .\task.jl:1386
while loading markdown.jl, in expression starting on line 14
ERROR: LoadError: LoadError: test failed: (Base.Markdown.MD(Any[Base.Markdown.Paragraph(Any["#"]),Base.Markdown.Paragraph(Any["empty"])],Dict{Any,Any}(:config=>Base.Markdown.Config([hashheader,fencedcode,blockquote],[blocktex,blockinterp,list,indentcode,github_table,horizontalrule,setextheader,paragraph],Dict('['=>[link],'\\'=>[linebreak,escapes],'*'=>[asterisk_bold,asterisk_italic],'$'=>[tex,interp],'`'=>[inline_code],'!'=>[image],'-'=>[en_dash])))) == Base.Markdown.MD(Any[Base.Markdown.Header{1}(""),Base.Markdown.Paragraph("empty")],Dict{Any,Any}()))
 in expression: @md_str $(Expr(:triple_quoted_string, "\r\n  #\r\n  empty\r\n  ")) == MD(Header{1}(""),Paragraph("empty"))
 in error at .\error.jl:19
 in default_handler at .\test.jl:27
 in do_test at .\test.jl:50
 in runtests at C:\dev\jl36-cyg\test\testdefs.jl:78
 in anonymous at .\multi.jl:626
 in run_work_thunk at .\multi.jl:587
 in remotecall_fetch at .\multi.jl:660
 in remotecall_fetch at .\multi.jl:675
 in anonymous at .\task.jl:1386
while loading markdown.jl, in expression starting on line 14
while loading C:\dev\jl36-cyg\test\runtests.jl, in expression starting on line 3

Makefile:9: recipe for target 'markdown' failed
make: *** [markdown] Error 1
```

**Comment by ihnorton** [comment] 2015-04-15 15:31
Ok, false alarm. Seems that the error was caused by having windows line endings in `test/markdown.jl`. I'm not quite sure how that happened, because I never touched the file, `git status` was clean before (I think) and is still clean now after running `dos2unix test/markdown.jl`. But now the test passes.

**Comment by ihnorton** [comment] 2015-04-15 17:04
[Current status](https://gist.github.com/ihnorton/ae0eb6998b3aaf2a7507): sparse and parallel failed, but they both pass when run individually.

**Comment by vtjnash** [comment] 2015-04-15 18:06
parallel failed because sparse had previously failed (and killed the worker). so it looks like just sparse had some alignment or corruption issue.

**Comment by tkelman** [comment] 2015-04-15 18:58
the sparse failure looks quite similar to what I saw above https://github.com/JuliaLang/julia/issues/10394#issuecomment-89682836, something in umfpack

**Comment by tkelman** [comment] 2015-04-16 01:44
Note that I still see the same assertion failure in llvmcall when I have `MARCH = x86-64`

**Comment by tkelman** [comment] 2015-04-16 12:00
Was having trouble getting a breakpoint to work at the assertion failure, so resorted to the trusty printf debugger. With this patch
```diff
diff --git a/src/debuginfo.cpp b/src/debuginfo.cpp
index 3b7465a..c443ef4 100644
--- a/src/debuginfo.cpp
+++ b/src/debuginfo.cpp
@@ -251,8 +251,9 @@ public:
@@ -251,8 +251,9 @@ public:
                 UnwindData = (uint8_t*)Addr;
                 if (SectionAddrCheck)
                     assert(SectionAddrCheck == SectionAddr);
-                else
+                else {
                     SectionAddrCheck = SectionAddr;
+                    printf("Section %s has SectionAddr = %lld\n", sName.data(), SectionAddr); }
             }
             if (sName.equals("__catchjmp")) {
                 sym_iter.getAddress(Addr);
@@ -269,10 +270,12 @@ public:
                 catchjmp = (uint8_t*)Addr;
                 if (SectionAddrCheck)
                     assert(SectionAddrCheck == SectionAddr);
-                else
+                else {
                     SectionAddrCheck = SectionAddr;
+                    printf("Section %s has SectionAddr = %lld\n", sName.data(), SectionAddr); }
             }
         }
+        // should we reset SectionAddrCheck = 0; after this loop?
         assert(catchjmp);
         assert(UnwindData);
         catchjmp[0] = 0x48;
@@ -333,11 +336,15 @@ public:
             Section->getSize(SectionSize);
 #endif
             sym_iter.getName(sName);
+            printf("Section %s has SectionAddr = %lld\n", sName.data(), SectionAddr);
 #ifdef _CPU_X86_
             if (sName[0] == '_') sName = sName.substr(1);
 #endif
-            if (SectionAddrCheck)
-                assert(SectionAddrCheck == SectionAddr);
+            if (SectionAddrCheck) {
+                if (SectionAddrCheck != SectionAddr) {
+                    printf("SectionAddrCheck = %lld\n", SectionAddrCheck);
+                    printf("SectionAddr = %lld\n", SectionAddr); }
+                assert(SectionAddrCheck == SectionAddr); }
             else
                 SectionAddrCheck = SectionAddr;
             create_PRUNTIME_FUNCTION(
```

I get the following output
```
Section .text has SectionAddr = 641925120
Section jlcall_add1234_1203 has SectionAddr = 641925120
Section julia_add1234_1203 has SectionAddr = 641925120
Section julia_add1234_12031 has SectionAddr = 641925504
SectionAddrCheck = 641925120
SectionAddr = 641925504
A s s e r t i o n   f a i l e d !

 P r o g r a m :   D : \ c y g w i n 6 4 \ h o m e \ T o n y \ j u l i a \ u s r
 \ b i n \ j u l i a - d e b u g . e x e
 F i l e :   d e b u g i n f o . c p p ,   L i n e   3 4 7

 E x p r e s s i o n :   S e c t i o n A d d r C h e c k   = =   S e c t i o n A
 d d r
```

**Comment by vtjnash** [comment] 2015-04-16 15:07
it looks like Comdat is enabled, but that shouldn't be true unless `imaging_mode==1`. it was expected that all sections would be named `.text` (which is really what this assert was attempting to verify).

but from this, it appears that there are some bugs in the way llvmcall emits its extra function:
a) it does not generate a guaranteed unique name: it should use a namespace that does not overlap with julia functions (very low probability of issue from this, however)
b) it should delete the function after inlining to ensure it doesn't get JIT compiled

**Closed** 2015-04-16 15:54 UTC
Labels: windows

**Comment by tkelman** [comment] 2015-04-16 16:59
Nice, that does fix the llvmcall assertion failure. The umfpack problem might be worth opening a new issue for. Or repurposing this one.

**Comment by vtjnash** [comment] 2015-04-16 17:32
let's go the new issue route. with 59 comments, this one is getting a bit long to keep track of. and i think it should now be possible to open narrow issues

**Comment by ihnorton** [comment] 2015-04-16 17:38
:clap:

**Comment by vtjnash** [comment] 2015-05-01 01:20
bump. can you open the new issues for remaining bugs and cross link them here for reference? I \*think\* the only remaining one was the linalg/arnoldi when running all linalg tests on one process?

**Comment by tkelman** [comment] 2015-05-01 09:45
Sure. Also the bad_alloc in hashing on win32 still happens last I checked.

**Comment by tkelman** [comment] 2015-05-01 17:35
#11083
#11085
