### ISSUE TITLE
arpack-ng-3.3.0 make installation fails

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaLang/julia#23103] opened 2017-08-02 20:42 UTC
make does not execute bootsrap in arpack-ng-3.3.0 before configure is called ...

**Comment by tkelman** [comment] 2017-08-02 22:29
that's why we download a tarball that has already been bootstrapped. please provide complete reproduction steps and the error you're seeing

**Comment by tkelman** [comment] 2017-08-03 21:58
given https://github.com/JuliaLang/julia/issues/23101#issuecomment-319953072 I'm closing this as a duplicate of https://github.com/opencollab/arpack-ng/issues/40, https://github.com/opencollab/arpack-ng/issues/29, and https://github.com/opencollab/arpack-ng/issues/13

**Closed by tkelman** 2017-08-03 21:58 UTC
Labels: build, external dependencies, linear algebra
