### ISSUE TITLE
OSX build with BUILD_LLVM_CLANG=1 fails

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#20243] opened 2017-01-26 07:30 UTC
I am unable to build `clang` on OSX with `BUILD_LLVM_CLANG` in `Make.user`:

```
cd /Users/kevin/Source/julia-cxx/deps/scratch/llvm-svn/build_Release+Asserts/projects/compiler-rt/lib/builtins && \
    /usr/bin/clang -stdlib=libc++ -mmacosx-version-min=10.8 \
    -m64 -D_DEBUG -D__STDC_CONSTANT_MACROS \
    -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS \
    -I/Users/kevin/Source/julia-cxx/deps/scratch/llvm-svn/build_Release+Asserts/projects/compiler-rt/lib/builtins \
    -I/Users/kevin/Source/julia-cxx/deps/srccache/llvm-svn/projects/compiler-rt/lib/builtins \
    -I/Users/kevin/Source/julia-cxx/deps/scratch/llvm-svn/build_Release+Asserts/include \
    -I/Users/kevin/Source/julia-cxx/deps/srccache/llvm-svn/include  -O3  -arch i386   -UNDEBUG  \
    -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
    -mmacosx-version-min=10.5 -fPIC -O3 -fvisibility=hidden -DVISIBILITY_HIDDEN -Wall -fomit-frame-pointer -arch i386 \
    -o CMakeFiles/clang_rt.builtins_i386_osx.dir/absvsi2.c.o   \
    -c /Users/kevin/Source/julia-cxx/deps/srccache/llvm-svn/projects/compiler-rt/lib/builtins/absvsi2.c
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
```

I've tracked it down to a problem with flags: when compiling compiler-rt, an extra `-mmacosx-version-min=10.5` is inserted late in the argument list, overriding the `-mmacosx-version-min=10.8` on the second line.

Solutions on the web suggest 
* defining the environment variable `MACOSX_DEPLOYMENT_TARGET=10.8`
* for cmake, adding `CMAKE_OSX_DEPLOYMENT_TARGET=10.8`

I've tried each of these, and while the second has an effect (I see two instances of `-mmacosx-version-min=10.8` in compile commands), it also does not seem to propagate to compiler-rt.  (Defining `MACOSX_DEPLOYMENT_TARGET=10.8` doesn't seem to do anything.)

Thoughts on this?  I was hoping to use `Cxx.jl`, although I'm wondering if I can get around this issue with a brew installed version...

Cc: @Keno

**Comment by vchuravy** [comment] 2017-01-26 08:21
duplicate of #18920

**Closed by vchuravy** 2017-01-26 08:21 UTC

**Comment by kmsquire** [comment] 2017-01-26 09:11
Missed that one--thanks!
