### ISSUE TITLE
Splatting 1-element vector of `Base.KeySet` inside `union`

### ISSUE THREAD

**Issue by millerjoey** [JuliaLang/julia#41537] opened 2021-07-10 19:34 UTC
I found what looks like a bug/oversight.

```julia
jjulia> d = Dict(i=>rand() for i in 1:3)
Dict{Int64, Float64} with 3 entries:
  2 => 0.192129
  3 => 0.340718
  1 => 0.154868

julia> v = [d,d]
2-element Vector{Dict{Int64, Float64}}:
 Dict(2 => 0.19212863767897548, 3 => 0.34071840174647483, 1 => 0.15486801172387077)
 Dict(2 => 0.19212863767897548, 3 => 0.34071840174647483, 1 => 0.15486801172387077)

julia> union(keys.(v)...)
Set{Int64} with 3 elements:
  2
  3
  1

julia> union(keys.(v[1:1])...)
ERROR: MethodError: no method matching copy(::Base.KeySet{Int64, Dict{Int64, Float64}})
Closest candidates are:
  copy(::Union{SubArray{T, N, var"#s5", I, L} where {var"#s5"<:(PooledArrays.PooledArray{T, R, N, RA} where {N, RA}), I, L}, PooledArrays.PooledArray{T, R, N, RA} where RA} where {T, N, R}) at /home/joe/.julia/packages/PooledArrays/CV8kA/src/PooledArrays.jl:212
  copy(::SubArray{var"#s832", var"#s831", var"#s830", I, L} where {var"#s832", var"#s831", var"#s830"<:Union{SparseArrays.AbstractSparseMatrixCSC, SparseArrays.SparseVector}, I, L}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/SparseArrays/src/sparsevector.jl:720
  copy(::SubArray) at subarray.jl:70
  ...
Stacktrace:
 [1] union(s::Base.KeySet{Int64, Dict{Int64, Float64}})
   @ Base ./abstractset.jl:49
 [2] top-level scope
   @ REPL[30]:1
```

When I use `union(Set.(keys.(v[1:1))...)` it works as expected.

**Comment by sostock** [comment] 2021-07-12 15:49
I think we should define
```julia
Base.copy(x::Keyset) = Set(x)
```
We could add a custom `Set(x::KeySet{K,<:Dict}) where K` method for better performance, it would just copy most of the internal structure of the `Dict` that the `KeySet` belongs to.

**Comment by JeffBezanson** [comment] 2021-07-12 18:36
Sounds reasonable.

**Comment by sostock** [comment] 2021-08-13 06:42
Duplicate of #30307.

**Closed** 2021-08-13 06:42 UTC
Labels: collections
