### ISSUE TITLE
Illegal intruction triggered under some peculiar conditions after method overwriting including an `error()` call

### ISSUE THREAD

**Issue by carlobaldassi** [JuliaLang/julia#17077] opened 2016-06-23 19:53 UTC
I just stumbled upon an illegal instruction while redefining a function called with splatting, under some peculiar conditions. Here is a minimal test case:

```julia
b = 1
v = (1,)

# type annotation for A (but not the actual type) is necessary to trigger the bug
# the return value is not important
f(A::Any, I1) = 1

# the splatting is necessary to trigger the bug
# two calls are needed
f(b, v...)
f(b, v...)

f(A::Any, I1) = error()

# the for loop is required to trigger the bug
for i = 1;  f(b, v...); end
```

The output is:

```
WARNING: Method definition f(Any, Any) in module Main at /home/carlo/Programs/julia/bug.jl:6 overwritten at /home/carlo/Programs/julia/bug.jl:13.

signal (4): Illegal instruction
while loading /home/carlo/Programs/julia/bug.jl, in expression starting on line 16
macro expansion; at /home/carlo/Programs/julia/bug.jl:16
unknown function (ip: 0x7f6df02bc87f)
jl_call_method_internal at /home/carlo/Programs/julia/src/julia_internal.h:86
jl_parse_eval_all at /home/carlo/Programs/julia/src/ast.c:699
jl_load at /home/carlo/Programs/julia/src/toplevel.c:569
include_from_node1 at ./loading.jl:426
unknown function (ip: 0x7f70070fa13c)
jl_call_method_internal at /home/carlo/Programs/julia/src/julia_internal.h:86
do_call at /home/carlo/Programs/julia/src/interpreter.c:65
eval at /home/carlo/Programs/julia/src/interpreter.c:188
jl_toplevel_eval_flex at /home/carlo/Programs/julia/src/toplevel.c:529
jl_toplevel_eval_in_warn at /home/carlo/Programs/julia/src/builtins.c:571
eval at ./boot.jl:231
unknown function (ip: 0x7f70070e07d0)
jl_call_method_internal at /home/carlo/Programs/julia/src/julia_internal.h:86
eval_user_input at ./REPL.jl:62
unknown function (ip: 0x7f6df02bc5b6)
jl_call_method_internal at /home/carlo/Programs/julia/src/julia_internal.h:86
macro expansion; at ./REPL.jl:92
unknown function (ip: 0x7f6df02b8c8f)
jl_call_method_internal at /home/carlo/Programs/julia/src/julia_internal.h:86
jl_apply at /home/carlo/Programs/julia/src/julia.h:1388
unknown function (ip: 0xffffffffffffffff)
Allocations: 4248296 (Pool: 4247549; Big: 747); GC: 9
Illegal instruction (core dumped)
```

This is on:

```
Julia Version 0.5.0-dev+4882
Commit 3aafa05* (2016-06-21 12:36 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by vtjnash** [comment] 2016-06-23 20:03
duplicate of https://github.com/JuliaLang/julia/issues/17076

**Closed by vtjnash** 2016-06-23 20:03 UTC
Labels: bug
