### ISSUE TITLE
Profile: Can we add back the warning that you've overrun the Profile buffer?

### ISSUE THREAD

**Issue by NHDaly** [JuliaLang/julia#37588] opened 2020-09-15 16:04 UTC
Starting in julia 1.4, the `Warning` **disappeared** from `Profile` when you've overrun the profile buffer:

On 1.3:
```julia
julia> using Profile

julia> Profile.init(n=10, delay=0.000001)  # Definitely going to run out of buffer

julia> @profile for _ in 1:10 peakflops() end

julia> Profile.print()
┌ Warning: The profile data buffer is full; profiling probably terminated
│ before your program finished. To profile for longer runs, call
│ `Profile.init()` with a larger buffer and/or larger delay.
└ @ Profile /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Profile/src/Profile.jl:312
┌ Warning: There were no samples collected. Run your program longer (perhaps by
│ running it multiple times), or adjust the delay between samples with
│ `Profile.init()`.
└ @ Profile /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Profile/src/Profile.jl:667
```

On 1.4:
```julia
julia> using Profile

julia> Profile.init(n=10, delay=0.000001)  # Definitely going to run out of buffer

julia> @profile for _ in 1:10 peakflops() end

julia> Profile.print()
┌ Warning: There were no samples collected. Run your program longer (perhaps by
│ running it multiple times), or adjust the delay between samples with
│ `Profile.init()`.
└ @ Profile /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.4/Profile/src/Profile.jl:851
```

Obviously the above is a silly example, but this has definitely led to some wasted time in practice trying to understand a profile that doesn't make sense, only to eventually realize that the buffer must not have been big enough!

Can we add this Warning back to the package? It is **very useful** and should be cheap to perform.

-------

_Even better,_ can we _also_ add a runtime check to print such a Warning as soon as the buffer fills up, _during profiling_? This way  we can know to kill our profiling process and adjust the buffer, and re-run, shortening the developer loop.

------

I've been meaning to file an issue about this for a long time. I'm sorry it took me so long to do! :) Thanks for all your hard work and these very useful tools! ❤️ !

**Comment by NHDaly** [comment] 2020-09-15 16:05
(Also, i'm not entirely sure, but in practice I've seen `WARNING: profiler attempt to access an invalid memory location` so up from time to time, and in my experience this _seems_ to happen when the buffer is overrun? Someone asked about what this warning means on our slack today, which is what reminded me I've wanted to file this issue for a while.)

**Comment by kimikage** [comment] 2020-09-18 13:26
Is this related to #36006?
I don't remember well anymore, so I recommend make a new PR.

**Comment by vtjnash** [comment] 2020-10-27 16:16
Duplicate of #35870

**Closed by vtjnash** 2020-10-27 16:16 UTC
