### ISSUE TITLE
Faster startup with -p/Distributed

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#47806] opened 2022-12-05 21:35 UTC
First note, #47803 was just merged, but I'm testing with a recent master "Commit 0feaf5cc3a6 (1 day old master)", where it's not yet in.

To show what's possible (much faster, still slow):
```
$ hyperfine 'OPENBLAS_NUM_THREADS=1 ~/julia-1.10-DEV-0feaf5cc3a/bin/julia -p4 -O0 --compile=min --startup-file=no --history-file=no -e ""'
Benchmark 1: OPENBLAS_NUM_THREADS=1 ~/julia-1.10-DEV-0feaf5cc3a/bin/julia -p4 -O0 --compile=min --startup-file=no --history-file=no -e ""
  Time (mean ± σ):      1.694 s ±  0.053 s    [User: 4.526 s, System: 0.581 s]
  Range (min … max):    1.652 s …  1.787 s    10 runs

vs.

$ hyperfine 'OPENBLAS_NUM_THREADS=1 ~/julia-1.10-DEV-0feaf5cc3a/bin/julia -p4 --startup-file=no --history-file=no -e ""'
Benchmark 1: OPENBLAS_NUM_THREADS=1 ~/julia-1.10-DEV-0feaf5cc3a/bin/julia -p4 --startup-file=no --history-file=no -e ""
  Time (mean ± σ):      7.893 s ±  0.487 s    [User: 17.657 s, System: 0.518 s]
  Range (min … max):    6.744 s …  8.229 s    10 runs
 
  Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet PC without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
```

Note, I did have a "quite PC" in both cases, the "Statistical outliers" are Julia's own doing, and also note while the latter is 4x slower, the variance is also much worse, at 9x of the former, i.e. it's not just the min (or mean) that's bad.

For those that use -p (meaning Distributed, yes?), it's very unlikely you want to use --compile=min, that's not the point, that you should, just that something better could be done for startup. My guess is that some code isn't precompiled for the sysimage. Or even if, is the sysimage fully precompiled? Like packages, I don't think it is, but it may already have changed?

As with Plots.jl and many packages (i.e. modules), you can force -O0 and/or --compile=min. I actually thought the latter meant the former is meaningless (since interpreted, and optimization only applies to compilation?), but with only --compile=min the timing gets slightly worse consistently, at least in this case.

I don't know if a similar trick can work with Distributed, it is a module, just happens to be a stdlib. I believe the optimization changing works for all of the module, or none of it, so that might be undesirable. Is there a way to do more fine-grained, for some functions that might only run once (at startup), without some hack like possibly using sub-modules, that might though be a workaround?

**Comment by PallHaraldsson** [comment] 2022-12-05 22:14
```
$ /usr/bin/time -v ~/julia-1.10-DEV-0feaf5cc3a/bin/julia -p1 --startup-file=no --history-file=no -e ""
[..]
	Maximum resident set size (kbytes): 322684

adding workers lowers mem use:

$ /usr/bin/time -v ~/julia-1.10-DEV-0feaf5cc3a/bin/julia -p3 --startup-file=no --history-file=no -e ""
	Maximum resident set size (kbytes): 286228
```

I was thinking does "time" only show mem and stats for the top process, then this is weird, or cumulative, apparently not, but third possibility might be average. Then it's still interesting to know that mem use is lower, I guess for the extra julia processes, why?

**Comment by vtjnash** [comment] 2024-02-11 01:09
Duplicate of https://github.com/JuliaLang/Distributed.jl/issues/71

**Closed by vtjnash** 2024-02-11 01:09 UTC
Labels: parallel
