### ISSUE TITLE
Maybe.jl hits an internal error during precompilation in `v1.9.0-rc3`

### ISSUE THREAD

**Issue by MasonProtter** [JuliaLang/julia#49639] opened 2023-05-04 21:37 UTC
This occurs for me on `v1.9.0-rc3`, but appears to be fixed on the current master:
```julia
julia> versioninfo()
Julia Version 1.9.0-rc3
Commit 1853b90328* (2023-04-26 15:51 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 12 × AMD Ryzen 5 5600X 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 6 on 12 virtual cores
Environment:
  JULIA_NUM_THREADS = 6
 
(@v1.9) pkg> activate --temp
  Activating new project at `/tmp/jl_OXkSVw`

(jl_OXkSVw) pkg> add Maybe
   Resolving package versions...
    Updating `/tmp/jl_OXkSVw/Project.toml`
  [334f122f] + Maybe v0.1.7
    Updating `/tmp/jl_OXkSVw/Manifest.toml`
  [34da2185] + Compat v4.6.1
  [e2ba6199] + ExprTools v0.1.9
  [e189563c] + ExternalDocstrings v0.1.1
  [334f122f] + Maybe v0.1.7
  [bf1d0ff0] + Try v0.1.1
  [9a3f8284] + Random
  [ea8e919c] + SHA v0.7.0
  [9e88b42a] + Serialization
  [cf7118a7] + UUIDs
Precompiling project...
  ✗ Maybe
  0 dependencies successfully precompiled in 1 seconds. 4 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package

julia> using Maybe
[ Info: Precompiling Maybe [334f122f-1118-46cc-837f-bff747ee6f78]

[36872] signal (6.-6): Aborted
in expression starting at /home/mason/.julia/packages/Maybe/guklN/src/Maybe.jl:46
unknown function (ip: 0x7f55036958ec)
gsignal at /usr/lib/libc.so.6 (unknown line)
abort at /usr/lib/libc.so.6 (unknown line)
jl_restore_system_image_from_stream_ at /home/mason/julia/src/staticdata.c:3117
jl_restore_package_image_from_stream at /home/mason/julia/src/staticdata.c:3333
jl_restore_incremental_from_buf at /home/mason/julia/src/staticdata.c:3379
ijl_restore_package_image_from_file at /home/mason/julia/src/staticdata.c:3494
_include_from_serialized at ./loading.jl:1011
_require_search_from_serialized at ./loading.jl:1471
_require at ./loading.jl:1748
_require_prelocked at ./loading.jl:1625
macro expansion at ./loading.jl:1613 [inlined]
macro expansion at ./lock.jl:267 [inlined]
require at ./loading.jl:1576
jfptr_require_51988 at /home/mason/julia/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/mason/julia/src/julia.h:1879 [inlined]
call_require at /home/mason/julia/src/toplevel.c:466 [inlined]
eval_import_path at /home/mason/julia/src/toplevel.c:503
eval_import_from at /home/mason/julia/src/toplevel.c:623
jl_toplevel_eval_flex at /home/mason/julia/src/toplevel.c:721
jl_eval_module_expr at /home/mason/julia/src/toplevel.c:203 [inlined]
jl_toplevel_eval_flex at /home/mason/julia/src/toplevel.c:715
jl_eval_module_expr at /home/mason/julia/src/toplevel.c:203 [inlined]
jl_toplevel_eval_flex at /home/mason/julia/src/toplevel.c:715
jl_toplevel_eval_flex at /home/mason/julia/src/toplevel.c:856
ijl_toplevel_eval_in at /home/mason/julia/src/toplevel.c:971
eval at ./boot.jl:370 [inlined]
include_string at ./loading.jl:1864
_include at ./loading.jl:1924
include at ./Base.jl:457 [inlined]
include_package_for_output at ./loading.jl:2010
jfptr_include_package_for_output_28907 at /home/mason/julia/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/mason/julia/src/julia.h:1879 [inlined]
do_call at /home/mason/julia/src/interpreter.c:126
eval_value at /home/mason/julia/src/interpreter.c:226
eval_stmt_value at /home/mason/julia/src/interpreter.c:177 [inlined]
eval_body at /home/mason/julia/src/interpreter.c:606
jl_interpret_toplevel_thunk at /home/mason/julia/src/interpreter.c:762
jl_toplevel_eval_flex at /home/mason/julia/src/toplevel.c:912
jl_toplevel_eval_flex at /home/mason/julia/src/toplevel.c:856
ijl_toplevel_eval_in at /home/mason/julia/src/toplevel.c:971
eval at ./boot.jl:370 [inlined]
include_string at ./loading.jl:1864
include_string at ./loading.jl:1874 [inlined]
exec_options at ./client.jl:305
_start at ./client.jl:522
jfptr__start_34408 at /home/mason/julia/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/mason/julia/src/julia.h:1879 [inlined]
true_main at /home/mason/julia/src/jlapi.c:573
jl_repl_entrypoint at /home/mason/julia/src/jlapi.c:717
main at /home/mason/julia/cli/loader_exe.c:59
unknown function (ip: 0x7f550363178f)
__libc_start_main at /usr/lib/libc.so.6 (unknown line)
_start at /home/mason/julia/usr/bin/julia (unknown line)
Allocations: 2998 (Pool: 2986; Big: 12); GC: 0
ERROR: Failed to precompile Maybe [334f122f-1118-46cc-837f-bff747ee6f78] to "/home/mason/.julia/compiled/v1.9/Maybe/jl_R1cLuZ".
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:2260
 [3] compilecache
   @ ./loading.jl:2127 [inlined]
 [4] _require(pkg::Base.PkgId, env::String)
   @ Base ./loading.jl:1770
 [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
   @ Base ./loading.jl:1625
 [6] macro expansion
   @ ./loading.jl:1613 [inlined]
 [7] macro expansion
   @ ./lock.jl:267 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1576
```

**Comment by Liozou** [comment] 2023-05-05 16:02
Bisection seems to point at 979fd53e531ac085021a596921d8e4a506c2e798 on the [release-1.9](https://github.com/JuliaLang/julia/commits/release-1.9) branch. But this issue is not 100% reproducible, it sometimes works and sometimes not with the same installation so it may be a race condition or something? The error also occurs with `JULIA_NUM_PRECOMPILE_TASKS=1`, still randomly.

For bisection I ran `import Pkg; Pkg.pkg"gc --all; activate --temp; add Maybe"` with no other environment depending on `Maybe.jl` or its dependencies, to force a new precompilation each time.

**Comment by giordano** [comment] 2023-05-05 16:12
To be clear, is https://github.com/JuliaLang/julia/commit/979fd53e531ac085021a596921d8e4a506c2e798 the first good or bad commit?  I put the "bisect wanted" label for searching the fix on `master` (if this is indeed fixed there) which would likely _not_ be on the release-1.9 branch.

**Comment by Liozou** [comment] 2023-05-05 16:28
It's the first bad commit! I'll look for the first fix now on master.

**Comment by Liozou** [comment] 2023-05-05 17:47
Unfortunately I can't reproduce the bug on 1a94dab756aea66180bb720ae7088fc01749dd63, which is commit https://github.com/JuliaLang/julia/commit/979fd53e531ac085021a596921d8e4a506c2e798 but on branch master. So I don't think the bug was actually fixed on master, but instead it appeared on the release-1.9 branch.

**Comment by vtjnash** [comment] 2023-05-05 19:22
Someone put 2 different gvars objects (specifically, the binding for Core.UInt and then the binding for Core.UInt8) at the same gvar offet in memory (as part of the `Try` package loading):
```
(rr) p/a image->gvars_offsets[105]
$55 = 0xfffffffffffffd20
(rr) p/a image->gvars_offsets[96]
$56 = 0xfffffffffffffd20
```
And then, it has the audacity to try to claim the object in this slot is something it has never been seen before in its life, and so it needs uniquing.

**Comment by vtjnash** [comment] 2023-05-05 19:40
@pchintalapudi Isn't that what #48710 is meant to fix?

**Comment by pchintalapudi** [comment] 2023-05-05 20:19
Oh yeah I'm pretty sure I saw a bunch of Core.SUM8x/Core.MUL8x in the logs, which that PR fixed.

**Comment by KristofferC** [comment] 2023-05-06 08:58
Backported

**Closed by KristofferC** 2023-05-06 08:58 UTC
Labels: bug, codegen
