### ISSUE TITLE
Seg fault when using BigFloat literal in precompiled module

### ISSUE THREAD

**Issue by halleysfifthinc** [JuliaLang/julia#22108] opened 2017-05-28 17:06 UTC
Using/calling a variable defined as a BigFloat literal (ie. `a = big"1.0"`) will cause a seg fault (and consequently crash julia) in a precompiled module, but the two other methods of defining BigFloats that I am aware of, `b = BigFloat(1.0)` and `parse(BigFloat,"1.0")` do not cause the seg fault.

This is the smallest code that will reproduce the issue:

```julia
__precompile__()

module Global_bigfloat_literal

export a,b,c,d

function __init__()
    global const a = big"28.0"
    global const b = 10.0
    global const c = BigFloat(28.0)
    global const d = parse(BigFloat,"2.6666666666666666666666666666666666666666666666666666666666666666666666666666666")
end

end
```

Output of above code:

```julia
julia> b
28.0

julia> c
2.800000000000000000000000000000000000000000000000000000000000000000000000000000e+01

julia> d
2.666666666666666666666666666666666666666666666666666666666666666666666666666678

julia> a

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
__gmpn_mul_basecase at /usr/bin/../lib/x86_64-linux-gnu/libgmp.so (unknown line)
mpfr_get_str at /usr/lib/x86_64-linux-gnu/libmpfr.so.4 (unknown line)
unknown function (ip: 0x7facfaa0f8e3)
__gmpfr_vasprintf at /usr/lib/x86_64-linux-gnu/libmpfr.so.4 (unknown line)
mpfr_snprintf at /usr/lib/x86_64-linux-gnu/libmpfr.so.4 (unknown line)
string at ./mpfr.jl:857
show at ./mpfr.jl:869 [inlined]
show at ./replutil.jl:4 [inlined]
display at ./REPL.jl:132
unknown function (ip: 0x7facec00c476)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
display at ./REPL.jl:135
unknown function (ip: 0x7facec00c186)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
display at ./multimedia.jl:143
unknown function (ip: 0x7facec00bfc2)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
print_response at ./REPL.jl:154
unknown function (ip: 0x7facec008bf8)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
print_response at ./REPL.jl:139
unknown function (ip: 0x7facec008648)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
#22 at ./REPL.jl:652
unknown function (ip: 0x7facebfffd11)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
run_interface at ./LineEdit.jl:1579
unknown function (ip: 0x7faefd93639f)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
run_frontend at ./REPL.jl:903
run_repl at ./REPL.jl:188
unknown function (ip: 0x7facebff7532)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
_start at ./client.jl:363
unknown function (ip: 0x7faefd9512c8)
jl_call_method_internal at ./src/./src/julia_internal.h:211 [inlined]
jl_apply_generic at ./src/./src/gf.c:1950
unknown function (ip: 0x5616362c4a8c)
unknown function (ip: 0x5616362c4356)
__libc_start_main at /build/glibc-cxyGtm/glibc-2.24/csu/../csu/libc-start.c:291
unknown function (ip: 0x5616362c43a9)
Allocations: 1722872 (Pool: 1721994; Big: 878); GC: 0
```

Version info:

Julia Version 0.5.2
Commit f4c6c9d4bb (2017-05-06 16:34 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i3-2370M CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)

I have also tested that this is an issue in Windows (it is).

**Comment by KristofferC** [comment] 2017-05-28 17:14
Thanks for the report. I believe this is a duplicate of https://github.com/JuliaLang/julia/issues/15722.

**Closed by KristofferC** 2017-05-28 17:14 UTC

**Comment by halleysfifthinc** [comment] 2017-05-29 17:24
I may be missing something else, but as I understood from the documents, the `__init__` function is the place to define global constants involving pointers returned by external modules in precompiled modules.

By defining a global BigFloat in the init function, there should be no problems, and when defining the BigFloat using the BigFloat constructor, `x = BigFloat(1.0)`, there is no problem. However, when using the BigFloat literal in the init function, `x = big"1.0"`, it causes a seg fault.

Shouldn't the bigfloat literal definition also work, given that BigFloat constructor works just fine and they both are defined at runtime in the init function?

**Comment by yuyichao** [comment] 2017-05-29 17:32
> they both are defined at runtime in the init function?

This is not the case.

**Comment by KristofferC** [comment] 2017-05-29 17:36
The literal is a string macro which is evaluated at macro expansion time.
