### ISSUE TITLE
`enumerate` allocates for arrays of mutables

### ISSUE THREAD

**Issue by JaredCrean2** [JuliaLang/julia#16190] opened 2016-05-04 01:15 UTC
Using `enumerate` to iterate through array of mutable objects allocates, but using a simple for loop does not:

``` julia
type MyMutable
  a::Int
end

immutable MyImmutable
  a::Int
end

function sumit(arr)
  val = 0
  for i=1:length(arr)
    val += arr[i].a
  end

  return val
end

function sumit2(arr)
  val = 0
  for (i, obj) in enumerate(arr)
    val += obj.a
  end

  return val
end

nel = 5000
arr = Array(MyMutable, nel)
arr2 = Array(MyImmutable, nel)
for i=1:nel
  arr[i] = MyMutable(i)
  arr2[i] = MyImmutable(i)
end

# warmup
@time sumit(arr)
@time sumit(arr2)
@time sumit2(arr)
@time sumit2(arr2)

println("\nfinal times:")
@time sumit(arr)
println("  mutable explicit for loop @time printed above\n")

@time sumit(arr2)
println("  immutable explicit for loop @time printed above\n")

@time sumit2(arr)
println("  mutable enumerate @time printed above\n")

@time sumit2(arr2)
println("  immutable enumerate @time printed above\n")
```

results:

``` julia
final times:
  0.000043 seconds (5 allocations: 176 bytes)
  mutable explicit for loop @time printed above

  0.000009 seconds (5 allocations: 176 bytes)
  immutable explicit for loop @time printed above

  0.000123 seconds (10.01 k allocations: 312.688 KB)
  mutable enumerate @time printed above

  0.000008 seconds (6 allocations: 192 bytes)
  immutable enumerate @time printed above
```

also, using `for obj in arr` rather than `enumerate` does not allocate.

**Comment by StefanKarpinski** [comment] 2016-05-04 14:29
This is due to the fact that currently types that mutable values must be heap-allocated and values that refer to heap-allocated values must themselves be heap allocated. This is essentially the same as https://github.com/JuliaLang/julia/issues/10899 and https://github.com/JuliaLang/julia/issues/14955 (which, afaict are dups of each other), has the same root cause as https://github.com/JuliaLang/julia/issues/1168 and would be addressed by https://github.com/JuliaLang/julia/issues/11714 or https://github.com/JuliaLang/julia/pull/12205.

@carnaval, what's the status of stack-allocating objects that refer to the heap? Wasn't that one of the major goals of the Green Fairy work?

**Comment by yuyichao** [comment] 2016-05-04 14:38
This one doesn't need stack allocation to work. The type inference should be able to elide the allocation. This is one of the left over case in https://github.com/JuliaLang/julia/pull/16021 .

**Comment by StefanKarpinski** [comment] 2016-05-04 14:48
Even better that we can solve this without needing to solve those other issues.

**Comment by KristofferC** [comment] 2017-05-24 16:23
Dup of https://github.com/JuliaLang/julia/issues/10899 and other similar issues

**Comment by KristofferC** [comment] 2017-08-13 17:59
Not a dup according to #23240

**Closed** 2018-05-07 17:02 UTC
Labels: performance
