### ISSUE TITLE
minimum of Set{CartesianIndex} returns previously deleted element 

### ISSUE THREAD

**Issue by thibaultdouzon** [JuliaLang/julia#43380] opened 2021-12-09 12:03 UTC
I'm currently using Julia 1.7.0 and discovered some weird behaviour between `minimum` and `Set{CartesianIndex}`
```julia
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_LOAD_PATH = /home/doudou/Documents/Code/AdventofCode:@:@v#.#:@stdlib
```

The minimal reproducible code is the following:
```julia
s = Set(CartesianIndices((2, 2)))
#Set{CartesianIndex{2}} with 4 elements:
#  CartesianIndex(2, 1)
#  CartesianIndex(1, 1)
#  CartesianIndex(2, 2)
#  CartesianIndex(1, 2)

minimum(s)
#CartesianIndex(1, 1)

delete!(s, CartesianIndex(1, 1))
#Set{CartesianIndex{2}} with 3 elements:
#  CartesianIndex(2, 1)
#  CartesianIndex(2, 2)
#  CartesianIndex(1, 2)

minimum(s)
#CartesianIndex(1, 1)

minimum(s) ∈ s
#false

pop!(s)
#Any element of s randomly

minimum(s) ∈ s
#true
```
This does not happens with other type (tried `Int` and some custom struct) inside the set and it seems a `pop!` puts everything back in order.

**Comment by jakobnissen** [comment] 2021-12-09 13:50
This is a natural consequence of the issue reported in https://github.com/JuliaLang/julia/issues/31208. For some reason I can't fathom, this behaviour is apparently intentional.

**Comment by pLOPeGG** [comment] 2021-12-09 15:12
Thanks for the insight !
So the `pop!` behaviour is just some coincidence and there is no direct relation with the issue.
Maybe this behaviour should be documented in https://docs.julialang.org/en/v1/base/arrays/#Base.IteratorsMD.CartesianIndex as it is unexpected?

**Comment by bvdmitri** [comment] 2021-12-09 17:09
While this can be intentional for `CartesianIndex` itself this behaviour does violate `minimum` function contract, from docs:
```
minimum(itr; [init])

  Returns the smallest element in a collection.
```
But in the example above returned value does not belong to the collection

**Comment by jakobnissen** [comment] 2021-12-09 19:25
It also directly violates the definition of `min`:
```
  min(x, y, ...)

  Return the minimum of the arguments (with respect to isless). See also the minimum function to take
  the minimum element from a collection.
```
However, it doesn't use `isless` for `CartesianIndex`.

**Comment by mbauman** [comment] 2023-01-26 18:55
Duplicate of #31208

**Closed by mbauman** 2023-01-26 18:55 UTC
