### ISSUE TITLE
Reproducible segfault with type intersection

### ISSUE THREAD

**Issue by rgiordan** [JuliaLang/julia#18932] opened 2016-10-14 18:45 UTC
I have come across a reproducible segfault in Julia v0.5.0.  I'm afraid it's not very minimal, but it's easy to reproduce.  To reproduce:
- Install branch `fsm_matrix_segfault` of the package jeff-regier/Celeste.jl (commit 21974)
- Check out branch `segfault` from the repo rgiordan/CelesteDev.jl
- Run the Celeste tests with the command `test/runtests misc` (this will download the data files needed for the test case)
- Run the script `rasterized_psf/psf_free_image.jl` from the CelesteDev.jl directory

Please let me know if I can provide any more information.  The backtrace is below:

```
julia> PSFConvolution.convolve_fsm_images!(fsm_vec[b]);

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
ml_matches_visitor at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:2172
jl_typemap_intersection_node_visitor at /home/rgiordan/Documents/git_repos/julia5/src/typemap.c:496
ml_matches at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:2279 [inlined]
jl_matching_methods at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:2300
methods_including_ambiguous at ./reflection.jl:283
unknown function (ip: 0x7f24d5fbfcc6)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
showerror at ./replutil.jl:277
#showerror#899 at ./replutil.jl:200
unknown function (ip: 0x7f24d5fbc849)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
#5 at ./REPL.jl:119
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
with_output_color at ./util.jl:299
display_error at ./REPL.jl:112
unknown function (ip: 0x7f24d5fbb2fd)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
print_response at ./REPL.jl:147
unknown function (ip: 0x7f24d5fbb14d)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
print_response at ./REPL.jl:139
unknown function (ip: 0x7f24d5fbaf1d)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
#22 at ./REPL.jl:652
unknown function (ip: 0x7f24e5336201)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
#38 at ./REPL.jl:867
#13 at ./LineEdit.jl:736
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
prompt! at ./LineEdit.jl:1605
run_interface at ./LineEdit.jl:1574
unknown function (ip: 0x7f26fea486df)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
run_frontend at ./REPL.jl:903
run_repl at ./REPL.jl:188
unknown function (ip: 0x7f24e532f522)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
_start at ./client.jl:360
unknown function (ip: 0x7f26fea63a78)
jl_call_method_internal at /home/rgiordan/Documents/git_repos/julia5/src/julia_internal.h:189 [inlined]
jl_apply_generic at /home/rgiordan/Documents/git_repos/julia5/src/gf.c:1942
unknown function (ip: 0x40184c)
unknown function (ip: 0x4012e6)
__libc_start_main at /build/glibc-GKVZIf/glibc-2.23/csu/../csu/libc-start.c:291
unknown function (ip: 0x401338)
Allocations: 30470709 (Pool: 30468304; Big: 2405); GC: 45
Segmentation fault (core dumped)
```

**Comment by vtjnash** [comment] 2016-10-14 19:04
duplicate of https://github.com/JuliaLang/julia/issues/18710 (fixed on master)?

**Comment by rgiordan** [comment] 2016-10-14 19:08
I'll build master and try it and report back

**Comment by vtjnash** [comment] 2016-10-14 19:10
You can also just cherry-pick the fix commit (6876dd77f3e5c719221a6dd65224e08ccfd6f97f) to your local release-0.5 branch

**Comment by andreasnoack** [comment] 2016-10-14 19:33
I can reproduce the segfault on yesterday's master.

**Comment by rgiordan** [comment] 2016-10-14 21:36
Ah, the problem goes away when I remove the unused parametric type from  ```convolve_fsm_images!```, i.e.

```
# Segfaults:
function convolve_fsm_images!{NumType <: Number}(fsms::FSMSensitiveFloatMatrices)
...

# Works:
function convolve_fsm_images!(fsms::FSMSensitiveFloatMatrices)
...

```

**Comment by jeff-regier** [comment] 2016-10-15 17:41
@kpamnany -- Does this look like the same seg fault that you're getting from Celeste.jl? We might have a few unnecessarily parameterized functions.

**Comment by rgiordan** [comment] 2016-10-15 18:27
FWIW, I looked through all the ```Celeste.jl``` code on master and could not find an instance where we completely ignore a parameterized type.

**Comment by kpamnany** [comment] 2016-10-16 01:24
No, I haven't seen this one.

**Comment by KristofferC** [comment] 2020-12-29 10:08
Closing this as stale. Please open a new issue with a repro if this is still a problem.

**Closed by KristofferC** 2020-12-29 10:08 UTC
Labels: types and dispatch
