### ISSUE TITLE
Strings, Symbols, and `ismutable`

### ISSUE THREAD

**Issue by mikmoore** [JuliaLang/julia#43229] opened 2021-11-25 16:48 UTC
Documentation explicitly states that objects of type [`String`](https://docs.julialang.org/en/v1/manual/strings/) or [`Symbol`](https://docs.julialang.org/en/v1/base/base/#Core.Symbol) are immutable. For all intents and purposes, this is true. However, 
```julia
# version 1.7.0-rc3
julia> ismutable("string")
true
julia> ismutable(:symbol)
true
```
for what I assume are deeply technical reasons.

It would seem proper to add a very brief footnote to the documentation of these types (are there other types I'm missing here?) that mentions the above results as a technical consequence. Alternatively, this remark might be less distracting/misleading/confusing if added to `ismutable` itself, since that's the only place that seems to break rank.

**Comment by rfourquet** [comment] 2021-11-25 20:29
Maybe a mention of `===` too, which unlike `ismutable(::String)`, is pretending immutability:
```julia
julia> x = "a"; y = "a"; x === y
true

julia> Base.__unsafe_string!(x, "b", 1); x === y
false
```

**Comment by musm** [comment] 2022-02-22 20:06
refs: https://github.com/JuliaLang/julia/pull/25349 https://discourse.julialang.org/t/whats-so-mutable-about-symbol-s/8094

**Comment by MashiatK** [comment] 2023-02-08 17:17
I want to work on this. If the issue is open, please assign it to me.

**Closed** 2023-02-08 17:21 UTC
Labels: doc, good first issue
