### ISSUE TITLE
Providing output format modification

### ISSUE THREAD

**Issue by fbruetting** [JuliaLang/julia#19824] opened 2017-01-02 20:54 UTC
In Matlab there's the `format` command, which provides output format modification for e.g. the displayed precision and other things like engineering format. As an engineer, the latter is of particular interest to me, since only showing exponents which are multiples of 3, makes it a lot easier to work with calculated values. This should affect both display() and show(). Could this be implemented?

**Comment by JeffBezanson** [comment] 2017-01-03 21:46
Possible duplicate of #6493

**Comment by fbruetting** [comment] 2017-01-03 21:56
Thanks, this describes the same problem.

**Closed** 2017-01-03 22:20 UTC
Labels: display and printing
