### ISSUE TITLE
Apparent Bug with BigInts in Composite Types

### ISSUE THREAD

**Issue by ztultrebor** [JuliaLang/julia#45332] opened 2022-05-17 00:59 UTC
```julia
import Base: convert, promote_rule

struct Thing1 <: Number
    a::BigInt
end

convert(::Type{Thing1}, x::Int) = Thing1(x)

promote_rule(::Type{Thing1}, ::Type{<:Number}) = Thing1
```
The following example comparison is `false`:
```julia
Thing1(1) == 1
```
Now if `Thing1.a` were an `Int`, a `Float64`, a `Rational{Int}` or a `ComplexF64` the above comparison is `true`. Is there some explanation for this or is it a bug?

**Comment by oscardssmith** [comment] 2022-05-17 01:15
This would work if you define `==(x::Thing1,y::Thing1)`. To the extent that it is a bug, it's a duplicate of https://github.com/JuliaLang/julia/issues/4648

**Closed by oscardssmith** 2022-05-17 01:15 UTC
