### ISSUE TITLE
Major package load slowdown, perhaps unnecessary calls to jl_recache_method_instance

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#34070] opened 2019-12-10 13:24 UTC
This is a cross-post of https://github.com/JuliaGraphics/Gtk.jl/issues/466. Brief summary: there is a 10x increase in package load time for Gtk (from ~1s to ~10s), for which the main culprit is the sheer number of calls to `jl_recache_method_instance`. Looking at the signatures it's being called on, it's not clear that all of those deserve to be there.

This *might* be a consequence of the new artifact system, but the signatures lead me to be skeptical that it's related.

**Comment by vtjnash** [comment] 2019-12-10 15:31
Duplicate of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/538

**Comment by brenhinkeller** [comment] 2022-11-20 22:48
Looks like this is resolved now that the issue it is marked as a duplicate of is resolved

**Closed by brenhinkeller** 2022-11-20 22:48 UTC
