### ISSUE TITLE
 `A_ldiv_B!` has no method for sparse right hand side

### ISSUE THREAD

**Issue by mszlosser** [JuliaLang/julia#10681] opened 2015-03-30 09:04 UTC
M=100
A=sprand(M,M,.5)
B=lufact(A)
C=B\eye(M)        # C=inv(A)

M=100000
A=sprand(M,M,.5)
B=lufact(A)
C=B\eye(M)        # MemoryError()
C=B\speye(M)    #  no method matching

inv(A) function of B[:L], B[:U], B[:Rs] ?

**Comment by simonbyrne** [comment] 2015-03-30 10:04
Did you want `inv(A)`? You might have noticed that:

```
julia> inv(A)
ERROR: The inverse of a sparse matrix can often be dense and can cause the 
computer to run out of memory. If you are sure you have enough memory, please 
convert your matrix to a dense matrix.
 in inv at sparse/linalg.jl:611
```

**Comment by andreasnoack** [comment] 2015-03-30 10:34
This is a limitation in the library that we are using for solving sparse linear systems. It doesn't support a sparse right hand side. Note that very often the solution of a sparse linear system with a sparse right hand side is dense, so you'd reach a memory limitation anyway. E.g.
```julia
julia> Bidiagonal(ones(5), ones(4), false)\eye(5)
5x5 Array{Float64,2}:
  1.0   0.0   0.0   0.0  0.0
 -1.0   1.0   0.0   0.0  0.0
  1.0  -1.0   1.0   0.0  0.0
 -1.0   1.0  -1.0   1.0  0.0
  1.0  -1.0   1.0  -1.0  1.0
```

**Comment by mszlosser** [comment] 2015-03-30 12:03
Can we quickly calculate inv(A) based on B[:L], B[:U] and B[:Rs] ?

(B=lufact(A) or B=cholfact(A) or an oyher fact)

**Comment by simonbyrne** [comment] 2015-03-30 12:34
The fastest you can probably do is
```
C = A_ldiv_B!(B,eye(M))
```
which will save allocating an extra output array.

But, as noted above, the result will be dense, so you will still require sufficient memory to allocate the array to begin with.

**Comment by mszlosser** [comment] 2015-04-01 10:30
Can we quickly calculate inv(A) if A is a sparse circulant matrix ?

**Comment by simonbyrne** [comment] 2015-04-01 10:46
I don't think we have any special routines for them yet. There is a `Circulant` type in:
https://github.com/jiahao/SpecialMatrices.jl
but there doesn't seem to be any fast method for solving them implemented. I'm sure @jiahao would be open to a pull request if you wanted to implement them yourself though.

**Comment by andreasnoack** [comment] 2015-04-01 13:31
This is not really a Julia issue so it is better to take a discussion like this on the mailing list instead of here, but...

If the matrix is circulant you'll only have to store the first columns of it and it is diagonalized by the Discrete Fourier Matrix so it can be inverted very efficiently. You'd have to store the first columns as a dense vector, but that shouldn't really be a problem. Let `x` be the first columns such that your circulant matrix is
```julia
julia> hcat([circshift(x,i) for i = 0:length(x) - 1]...)
5x5 Array{Float64,2}:
 -0.15775  -1.10256   0.0       0.0       0.0    
  0.0      -0.15775  -1.10256   0.0       0.0    
  0.0       0.0      -0.15775  -1.10256   0.0    
  0.0       0.0       0.0      -0.15775  -1.10256
 -1.10256   0.0       0.0       0.0      -0.15775
```
then you can just Fourier transform the first column, calculate the reciprocal and tranform back, i.e.
```julia
julia> irfft(1 ./ rfft(x), length(x))
5-element Array{Float64,1}:
 -0.000380042
 -0.906922   
  0.129758   
 -0.0185653  
  0.00265623 
```
Compare to
```julia
julia> inv(hcat([circshift(x,i) for i = 0:length(x) - 1]...))
5x5 Array{Float64,2}:
 -0.000380042   0.00265623   -0.0185653     0.129758     -0.906922   
 -0.906922     -0.000380042   0.00265623   -0.0185653     0.129758   
  0.129758     -0.906922     -0.000380042   0.00265623   -0.0185653  
 -0.0185653     0.129758     -0.906922     -0.000380042   0.00265623 
  0.00265623   -0.0185653     0.129758     -0.906922     -0.000380042
```
I wrote [some code](https://github.com/andreasnoack/ToeplitzMatrices.jl) for this for my thesis allowing you to write
```julia
julia> inv(Circulant(x))
5x5 ToeplitzMatrices.Circulant{Float64}:
 -0.000380042   0.00265623   -0.0185653     0.129758     -0.906922   
 -0.906922     -0.000380042   0.00265623   -0.0185653     0.129758   
  0.129758     -0.906922     -0.000380042   0.00265623   -0.0185653  
 -0.0185653     0.129758     -0.906922     -0.000380042   0.00265623 
  0.00265623   -0.0185653     0.129758     -0.906922     -0.000380042
```
but it is not doing much more than just described.

**Comment by mszlosser** [comment] 2015-04-01 14:39
Can we quickly build a sparse circulant matrix from a dense column vector ?

this would solve my problem.

**Comment by timholy** [comment] 2015-04-01 14:43
@mszlosser, once you have the factorization, you can use it and create whatever types and methods you want. A possible example to follow would be the [WoodburyMatrices package](https://github.com/timholy/WoodburyMatrices.jl).

As @andreasnoack said, this is definitely better for julia-users. Since it's not a bug in julia, and (if you implement this) it would be better in a package than in core julia, I'm going to close this.

**Closed by timholy** 2015-04-01 14:43 UTC
Labels: sparse
