### ISSUE TITLE
`fatal error in type inference (type bound)` when testing Qecsim on 1.10

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#50709] opened 2023-07-28 17:14 UTC
PkgEval log: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/152f0e9_vs_6fc1be0/Qecsim.primary.log

Error:

```julia
qec_merge-one: Error During Test at /Users/kristoffercarlsson/PkgEvalAnalysis/dev/Qecsim/test/App.jl:336
  Got exception outside of a @test
  fatal error in type inference (type bound)
  Stacktrace:
    [1] collect(itr::Base.Generator{Tuple{Symbol, Symbol}, Qecsim.App.var"#5#11"})
      @ Base ./array.jl:841
    [2] _totuple
      @ Qecsim.App ./tuple.jl:425 [inlined]
    [3] Tuple
      @ Qecsim.App ./tuple.jl:391 [inlined]
    [4] qec_merge(::Dict{Symbol, Any}, ::Vararg{Dict{Symbol, Any}})
      @ Qecsim.App ~/PkgEvalAnalysis/dev/Qecsim/src/App.jl:376
    [5] macro expansion
      @ ~/PkgEvalAnalysis/dev/Qecsim/test/App.jl:339 [inlined]
...
```

Repros locally on `Pkg.test`. Haven't looked into it more.

**Comment by gbaraldi** [comment] 2023-08-16 15:24
@KristofferC does this still reproduce for you?

**Comment by gbaraldi** [comment] 2023-08-16 16:30
This was fixed by https://github.com/JuliaLang/julia/pull/50432. Is that change backportable @Keno ?

**Comment by Keno** [comment] 2023-08-16 16:31
That's not really a "fixed by" so much as a "disabled by" because we thought these weren't happening anymore. We should track down what the type system bug here is and add appropriate tests.

**Comment by gbaraldi** [comment] 2023-08-16 16:54
The error was introduced in https://github.com/JuliaLang/julia/pull/48421

**Comment by gbaraldi** [comment] 2023-08-16 17:15
Short reproducer
```julia
a = [:error_weight_pvar => 1.09
    :n_logical_commutations => [2, 2]]

b = Dict(a)
c = b
vector_val_keys = (:n_logical_commutations, :custom_totals,)
_null_vec_copy(::Nothing) = nothing
_null_vec_copy(vec::AbstractVector) = deepcopy(vec)


function repro(data...)
    vector_val_keys = (:n_logical_commutations, :custom_totals,)
    for runs_data in data
        vector_vals = Tuple(_null_vec_copy(runs_data[k]) for k in vector_val_keys)
    end
end

repro(b,c)
```

**Comment by vtjnash** [comment] 2023-08-17 14:50
Looks like probably an inference bug handling ccall
```julia
julia> Cthulhu.descend(Base._array_for, (Type{<:AbstractVector{T}} where T, Base.HasLength, Int))
```
If you inspect the return value here, it returns `Array{<:AbstractVector{T},1}` (note the missing `where T`)

**Closed** 2023-08-31 18:57 UTC
Labels: bug, inference
