### ISSUE TITLE
Deprecate at-evalpoly

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#33903] opened 2019-11-21 04:19 UTC
Now that https://github.com/JuliaLang/julia/pull/32753 has landed, for Julia 2.0+ , we should deprecate the `@evalpoly` macro.

**Comment by ararslan** [comment] 2019-12-31 21:25
Duplicate of https://github.com/JuliaLang/julia/issues/33289

**Closed by ararslan** 2019-12-31 21:25 UTC
