### ISSUE TITLE
`@test` fails with expressing involving `+` or `/` and atypical spacing

### ISSUE THREAD

**Issue by orionlee** [JuliaLang/julia#44509] opened 2022-03-07 23:28 UTC
The `@test` macro fails when there are expressions involving `+` or `-` with atypical spacings, e.g., `6 +2` (space before `+`; no space after `+`)

Examples:
```julia
julia> using Test
julia> @test 6 +2 == 8
ERROR: LoadError: invalid test macro call: @test 6 2 == 8
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] test_expr!(m::Any, ex::Any, kws::Any)
   @ Test C:\pkg\julia\share\julia\stdlib\v1.7\Test\src\Test.jl:340
 [3] var"@test"(__source__::LineNumberNode, __module__::Module, ex::Any, kws::Vararg{Any})
   @ Test C:\pkg\julia\share\julia\stdlib\v1.7\Test\src\Test.jl:435
in expression starting at REPL[10]:1

julia> @test 6 -2 == 8
ERROR: LoadError: invalid test macro call: @test 6 -2 == 8
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] test_expr!(m::Any, ex::Any, kws::Any)
   @ Test C:\pkg\julia\share\julia\stdlib\v1.7\Test\src\Test.jl:340
 [3] var"@test"(__source__::LineNumberNode, __module__::Module, ex::Any, kws::Vararg{Any})
   @ Test C:\pkg\julia\share\julia\stdlib\v1.7\Test\src\Test.jl:435
in expression starting at REPL[11]:1
```

Notes:
- there is no similar problem for `*` or `/`
- for `+` or `-`, other variants of spacing still work
  - `6+2` (no space), 
  - `6 + 2` (spaces both before and after `+`), 
  - `6+ 2` (no space before `+`)

---
Version info:
```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

**Comment by vtjnash** [comment] 2022-03-07 23:38
Duplicate of https://github.com/JuliaLang/julia/issues/2861

**Closed by vtjnash** 2022-03-07 23:38 UTC
