### ISSUE TITLE
Array{Int}() gives strange result

### ISSUE THREAD

**Issue by garrison** [JuliaLang/julia#11180] opened 2015-05-07 05:49 UTC
As noticed [here](https://github.com/JuliaLang/julia/pull/11154#issuecomment-99523282), `Array{Int}()` fails on julia 0.3:

    julia> Array{Int}()
    ERROR: type cannot be constructed

but leads to a rather weird result on `master`:

    julia> Array{Int}()
    0-dimensional Array{Int64,0}:
    -1229782938247303442

This behavioral change was introduced in 23a6995a560.

**Comment by JeffBezanson** [comment] 2015-05-07 06:13
Did you read the two issues that that commit closed? What would you suggest?

**Comment by garrison** [comment] 2015-05-07 06:30
I did.  But I'm not quite sure what the `-1229782938247303442` is about.  If making a 0-dimensional array is really what we want to do in this case, then I'd suggest removing whatever is causing that to be displayed.

**Comment by garrison** [comment] 2015-05-07 07:03
Sorry, I just had the epiphany that a zero-dimensional array is a scalar, and this is simply an uninitialized scalar.  I guess this will be "fixed" by #9147 if that is implemented as planned.

**Comment by garrison** [comment] 2015-05-07 07:04
But as a new user, I would find the current behavior rather confusing.

**Comment by jakebolewski** [comment] 2015-05-07 13:56
Closing it as a dupe of #9147.

**Closed by jakebolewski** 2015-05-07 13:56 UTC
