### ISSUE TITLE
Inconsistent variable scope between Julia Console and Jupyter Kernel

### ISSUE THREAD

**Issue by kfkelvinng** [JuliaLang/julia#34307] opened 2020-01-08 04:06 UTC
# Version Info
```
julia> versioninfo()
Julia Version 1.1.1
Platform Info:
  OS: Linux (x86_64-conda_cos6-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
```
# Julia Console
```
julia> global_vote = zeros(1)
1-element Array{Float64,1}:
 0.0
julia> for i in 1:1
           global_vote = global_vote .+ 1
       end
ERROR: UndefVarError: global_vote not defined
Stacktrace:
 [1] top-level scope at ./REPL[2]:2 [inlined]
 [2] top-level scope at ./none:0
```

# Jupyter Kernel
```
global_vote = zeros(1)
for i in 1:1
    global_vote = global_vote .+ 1
end
print(global_vote)
[1.0]
```

# Work Around in Julia Console
```
for i in 1:1
   global global_vote = global_vote .+ 1
end
```

**Comment by JeffBezanson** [comment] 2020-01-08 05:43
Duplicate of #28789. The discrepancy was introduced by IJulia; the developers there deliberately diverged from the default REPL. Of course, some people want the default repl to change to match IJulla; #33864 does that.

**Closed by JeffBezanson** 2020-01-08 05:43 UTC
