### ISSUE TITLE
Julia embedding example cannot be compiled in 1.5.2

### ISSUE THREAD

**Issue by uformia** [JuliaLang/julia#37957] opened 2020-10-09 04:46 UTC
On the 1.5.2 branch (or 1.5.1), the file src/atomics.h is missing a template keyword for jl_atomic_store_release , around line 269, making the file uncompilable (in VS2017). See https://github.com/JuliaLang/julia/blob/539f3ce943f59dec8aff3f2238b083f1b27f41e5/src/atomics.h#L269 .

This is compiling the code at https://docs.julialang.org/en/v1/manual/embedding/#High-Level-Embedding-on-Windows-with-Visual-Studio .

This change is made in commit 2b510b417b83b3c08a069866ecf90e2f3a97fc2d on master, which appears to be working on a different feature, but that commit is not in 1.5.2 .

**Comment by JeffBezanson** [comment] 2020-10-09 15:46
Thanks. Would you be willing to open a PR against release-1.5 adding that line?

**Comment by rpep** [comment] 2020-10-09 16:41
Think this is a duplicate of #36481, but there are broader problems that make this not work too.

**Comment by hheld** [comment] 2021-05-25 07:20
It still can't be compiled with Julia version 1.6.3. It shows a different error though: Now it doesn't know what `jl_atomic_load_relaxed` is.

Is there a solution for this?

**Comment by ViralBShah** [comment] 2022-09-05 23:13
MSVC Should be working with https://github.com/JuliaLang/julia/pull/44976. Please reopen if still an issue.

**Closed by ViralBShah** 2022-09-05 23:13 UTC
