### ISSUE TITLE
xdump triggers 'can't repeat a string -1 times' error in print_matrix_row

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/julia#12899] opened 2015-09-01 04:09 UTC
The code in [this gist](https://gist.github.com/jiahao/d58c0647354fbd0f1e6d) triggers a strange error on OSX.

```jl
Array(Float64,(6,6)) 6x6 Array{Float64,2}:
 ERROR: LoadError: ArgumentError: can't repeat a string -1 times
 in repeat at ./strings/types.jl:176
 in print_matrix_row at show.jl:1017
 in print_matrix at show.jl:1061
 in showarray at show.jl:1229
 in xdump at show.jl:908
 in anonymous at show.jl:913
 in with_output_limit at ./show.jl:1246
 in xdump at show.jl:913
 in truncate! at 12899.jl:176
 in thickrestartbidiag at 12899.jl:52
 in thickrestartbidiag at 12899.jl:44
 in include at ./boot.jl:259
 in include_from_node1 at ./loading.jl:271
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading 12899.jl, in expression starting on line 235
```

I can reliably reproduce this error on OSX (but not Linux). It always happens on Iteration 143 of this algorithm, and removing any of the printing statements in this code makes this error go away.

```jl
julia> versioninfo()
Julia Version 0.4.0-pre+7122
Commit 62d570f (2015-08-31 23:19 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by jakebolewski** [comment] 2015-09-01 05:03
solution, remove `xdump`?

**Comment by mschauer** [comment] 2015-09-01 07:29
dup #10908

**Comment by jiahao** [comment] 2015-09-01 15:22
ohhhhh... maybe we finally have a reproducible case of that.

**Comment by mschauer** [comment] 2015-09-01 20:25
yes!

**Comment by vtjnash** [comment] 2015-09-17 06:01
i've managed to prove that this is definitely a duplicate of #10908, still working on the root cause though (at the failing line, `sx = "-02.375", a = (3, 4)`)

**Closed** 2015-09-17 07:28 UTC
Labels: bug, mac

**Comment by mschauer** [comment] 2015-09-17 10:19
yes!!

**Comment by tkelman** [comment] 2015-09-18 18:11
backported in #13182
