### ISSUE TITLE
`Pkg.clone` succeeds for invalid package

### ISSUE THREAD

**Issue by omus** [JuliaLang/julia#18243] opened 2016-08-25 19:35 UTC
`Pkg.clone` supports cloning a package via a registered package name. If you supply a package name that is not registered the following occurs in Julia v0.4

```julia
julia> Pkg.clone("Foo")
INFO: Cloning Foo from Foo
fatal: repository 'Foo' does not exist
ERROR: unlink: no such file or directory (ENOENT)
 in unlink at fs.jl:102
 in rm at file.jl:59
 in clone at pkg/entry.jl:162
 in clone at pkg/entry.jl:186
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in clone at pkg.jl:34
```

In Julia v0.5.0-rc3 this succeeds with no warning or error:
```julia
julia> Pkg.clone("Foo")
INFO: Cloning Foo from Foo
INFO: Computing changes...
```

**Comment by tkelman** [comment] 2016-08-25 19:47
duplicate of https://github.com/JuliaLang/julia/issues/14051

**Closed by tkelman** 2016-08-25 19:47 UTC
Labels: packages

**Comment by omus** [comment] 2016-08-25 19:57
Thanks!
