### ISSUE TITLE
Environment variable for specifying custom system image (-J, --sysimage)

### ISSUE THREAD

**Issue by tomyun** [JuliaLang/julia#37895] opened 2020-10-05 23:31 UTC
There is no environment variable equivalent to `-J`/`--sysimage` option for specifying a custom image for Julia instance. I think supporting a variable like `JULIA_SYSIMAGE` can be quite useful when deploying Julia for custom environment, i.e. deploying in a Docker container with custom system image baked in.

Currently, one would have to manually add an option every time or create a wrapper script to launch Julia with custom image, especially when replacing default system image is not an option (i.e. [repo2docker](https://github.com/jupyterhub/repo2docker) does not allow root privileges for touching system image when using default Julia buildpak).

**Comment by akosuas** [comment] 2020-11-11 16:56
I'd also like this - I think it is a duplicate of #36843 though

**Comment by PallHaraldsson** [comment] 2021-10-13 21:10
I'm not sure about this. Is it really useful? I'm thinking if someone can get to change my default shell environment, then they could trick me into running arbitrary code, right? Maybe I'm too paranoid and shouldn't worry about that. If that happens, the I guess I have bigger problems, and I should e.g. be able trust my system administrator (hackers could also change my code, but it would be more obvious).

Maybe we already have this problem with LD PRELOAD, so might as well do this.

Isn't there a good workaround with using PackageCompiler.jl and/or "create a wrapper script to launch Julia with custom image"?

**Closed** 2021-10-13 21:14 UTC
