### ISSUE TITLE
Incomplete method documentation of Base.countlines()

### ISSUE THREAD

**Issue by veddox** [JuliaLang/julia#48494] opened 2023-02-02 08:43 UTC
[`Base.countlines()`](https://github.com/JuliaLang/julia/blob/e48a0c99bef949a84979c05dc33fd5578f684c1d/base/io.jl#L1336) can be called with an IO stream or a file name string. However, the [documentation](https://docs.julialang.org/en/v1/base/io-network/#Base.countlines) only talks about the former, potentially obscuring a very helpful feature.

As with [`Base.readlines()`](https://docs.julialang.org/en/v1/base/io-network/#Base.readlines) and similar functions, all methods of `countlines()` should be listed in the documentation.

**Comment by MashiatK** [comment] 2023-02-08 17:16
I want to work on this. If the issue is open, please assign it to me.

**Closed** 2023-02-13 09:27 UTC
Labels: doc, good first issue
