### ISSUE TITLE
Pasting in multiline code terminal regression 

### ISSUE THREAD

**Issue by musm** [JuliaLang/julia#25186] opened 2017-12-19 15:44 UTC
On 0.7 copy pasting the following 
```julia
mutable struct Test
    a
    b
    c::String
end
```

Results in 
![image](https://user-images.githubusercontent.com/4319522/34165137-6ea952c8-e4a9-11e7-9cf9-b585bc55e143.png)

compare to 0.6
![image](https://user-images.githubusercontent.com/4319522/34165158-7e19eb3c-e4a9-11e7-89cd-2ccaae37849f.png)

This is especially/annoying/noticeable for larger blocks

**Comment by StefanKarpinski** [comment] 2017-12-19 15:46
cc @rfourquet, @KristofferC

**Comment by rfourquet** [comment] 2017-12-19 15:55
Oh I can't reproduce... Could this is a differences in the shells?

**Comment by musm** [comment] 2017-12-19 15:57
BTW this is on Windows  just using the regular  cmd ....

**Comment by StefanKarpinski** [comment] 2017-12-19 15:58
Or a difference in terminals. cmd is notoriously the worst "terminal" around...

**Comment by musm** [comment] 2017-12-19 16:00
I tried    conemu (and powershell) and is   reproducible on all of them...

**Comment by StefanKarpinski** [comment] 2017-12-19 16:22
Ok, seems to be Windows specific then. I wonder if it has something to do with `\r\n`.

**Comment by vtjnash** [comment] 2017-12-19 17:54
This is the auto-indent feature. On newer terminal emulators, "paste" is a special atomic action, so we can disable reformatting (among other issues). The Windows terminal doesn't have that feature.

**Comment by StefanKarpinski** [comment] 2017-12-19 18:14
Please don't close issues that are clearly a huge usability issue.

**Comment by StefanKarpinski** [comment] 2017-12-19 18:15
If the auto-indent feature cannot be properly supported on some terminals then we should turn it off on those terminals. The question is how to detect if we're running in such a terminal or not.

**Comment by vtjnash** [comment] 2017-12-19 18:27
Or you can just type `\e[200~` \<paste\> `\e[201~` to make it work on Windows :)

If you'd like to reproduce this on your terminal, either type very, very quickly `\e[?2004l`, or use the following command to have Julia do it for you:
```
@async (sleep(1); Base.Terminals.disable_bracketed_paste(Base.Terminals.TTYTerminal("", STDIN, STDOUT, STDERR)))
```

**Comment by StefanKarpinski** [comment] 2017-12-19 18:36
We're not going to have the official "solution" to be typing some weird shit on Windows.

**Comment by musm** [comment] 2017-12-19 18:38
@vtjnash  I typed your suggestion  and then tried the example in the original  post, however the issue remains.

**Comment by vtjnash** [comment] 2017-12-19 18:45
> We're not going to have the official "solution" to be typing some weird shit on Windows.

There's nothing Windows-specific about it, you can test it out by doing the same on any system :)

**Comment by KristofferC** [comment] 2018-01-24 13:39
Here in VSCode:

![screen shot 2018-01-24 at 14 36 10](https://user-images.githubusercontent.com/1282691/35334903-2d5e7ee2-0114-11e8-8fe5-b4272a4fa43b.png)

I'm guessing this is https://github.com/JuliaLang/julia/pull/22948. @rfourquet

**Comment by StefanKarpinski** [comment] 2018-03-15 14:23
@rfourquet, this bug was introduced by your changes. Do you have any ideas for the way forward here, short of reverting those features?

**Comment by rfourquet** [comment] 2018-03-24 08:04
No I don't see what to do here, except disable the feature on Windows (if the bug is Windows specific and concerns every/most Windows platforms) or introduce a REPL option to disable the feature (I could swear this option already existed!) and document this problem together with the way to change the option. I will make a first PR to introduce the option anyway.

**Comment by Keno** [comment] 2018-03-24 20:57
Seems like xterm.js added support in https://github.com/xtermjs/xterm.js/pull/1097. Since the windows 
VT100 emulation is done by libuv, we might be able to fix it there too?

**Comment by Keno** [comment] 2018-03-24 21:02
Also, since windows now has `ENABLE_VIRTUAL_TERMINAL_PROCESSING`, maybe we can just ask them to add it.

**Comment by KristofferC** [comment] 2018-03-24 21:09
Being able to fix this to work properly universally would be great because the feature is really nice.

**Comment by vtjnash** [comment] 2018-03-25 18:18
It’s not in VT100. Conhost.exe would need to implement this functionality - I’m not aware of its existence currently.

**Comment by Keno** [comment] 2018-03-25 18:44
Well, `ENABLE_VIRTUAL_TERMINAL_PROCESSING` makes conhost behave like a unix terminal emulator (since that's what WSL uses to run unmodified ubuntu binaries in cmd), so it seems possible to request microsoft to implement this. In any case, since xterm.js has this feature now, maybe just a default disable on Windows would be sufficient.

**Comment by vtjnash** [comment] 2018-03-25 20:08
I'm slightly confused how the existence of a javascript implementation of xterm is relevant to the Windows Console kernel driver or its GUI wrapper (conhost). I agree it would be nice if Microsoft implements this, but I doubt they read this issue tracker.

**Comment by Keno** [comment] 2018-03-25 20:11
It's not. There were two concerns raised in this issue
1. It doesn't work in VS Code (which as far as I understand uses an old version of xterm.js, so the way to fix that is to get them to upgrade it).
2. It doesn't work on Windows
Thus, since it's fixed in new version of xterm.js, only problem 2 remains. To get microsoft to fix it, the thing is probably to file it against WSL: https://github.com/Microsoft/WSL

**Comment by Keno** [comment] 2018-03-25 20:17
Or rather https://github.com/microsoft/console is probably the right place

**Comment by musm** [comment] 2018-08-22 03:07
Bump, as of https://github.com/libuv/libuv/commit/58ccfd4c210d3cc1a36dd82474976aac296589f2
can we not just turn this on for Windows?

**Comment by musm** [comment] 2018-09-10 15:50
since this is so annoying, the workaround is to set  `Base.active_repl.options.auto_indent = false`  courtesy `@rfourquet`

**Comment by StefanKarpinski** [comment] 2018-09-10 16:51
Is there any way we can detect terminals where this is likely to be broken and turn auto indent off?

**Closed** 2019-03-08 11:30 UTC
Labels: REPL
