### ISSUE TITLE
`versioninfo()` reports confusing number of threads on master

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#49792] opened 2023-05-12 15:58 UTC
```julia
[sukera@tower julia]$ julia -qt 10,1
julia> versioninfo()
Julia Version 1.10.0-DEV.1287
Commit c6fc12c9ee (2023-05-12 14:02 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 24 × AMD Ryzen 9 7900X 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
  Threads: 15 on 24 virtual cores
```

10 threads for the `:default` threadpool are requested, as well as one for the `:interactive` threadpool, but `versioninfo()` reports 15. As far as I can tell, that's due to

```
--gcthreads=N             Use N threads for GC, set to half of the number of compute threads if unspecified.
```

introduced in #48600. Not sure how to best query that new information yet, but printing something like `Threads: 10 compute, 1 interactive, 5 GC on 24 virtual cores` might be nice.

**Comment by jmkuhn** [comment] 2023-05-12 16:09
Duplicate of https://github.com/JuliaLang/julia/issues/49753

**Closed** 2023-05-12 16:12 UTC
