### ISSUE TITLE
line numbers in critical error handler

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#15220] opened 2016-02-24 15:41 UTC
I no longer see julia line numbers in the backtraces that print on aborts, segfaults, etc. They were very helpful for debugging during bootstrap.

**Comment by JeffBezanson** [comment] 2016-02-24 19:06
Works with LLVM 3.3.

**Comment by yuyichao** [comment] 2016-02-24 19:15
Is this bootstrap only? I can see line numbers in the backtrace printed by the signal handler on current master for all non `jlcall` and non-REPL functions

```jl
julia> ccall(:kill, Cint, (Cint, Cint), getpid(), 11)

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
kill at /usr/bin/../lib/libc.so.6 (unknown line)
[inline] at ./essentials.jl:78
anonymous at ./no file:4294967295
unknown function (ip: 0x7f6f652a1040)
[inline] at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/julia_internal.h:69
jl_call_method_internal at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/toplevel.c:556
[inline] at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/julia.h:1379
jl_eh_restore_state at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/builtins.c:548
eval at ./boot.jl:267
[inline] at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/julia_internal.h:69
jl_call_method_internal at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/gf.c:1879
[inline] at ./REPL.jl:3
eval_user_input at ./REPL.jl:62
unknown function (ip: 0x7f6f652a35b7)
[inline] at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/julia_internal.h:69
jl_call_method_internal at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/gf.c:1903
[inline] at ./REPL.jl:92
#1 at ./task.jl:59
unknown function (ip: 0x7f716d87b550)
[inline] at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/julia_internal.h:69
jl_call_method_internal at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/gf.c:1903
start_task at /home/yuyichao/projects/arch-pkg/pkg/all/julia-git/src/julia/src/task.c:245
unknown function (ip: (nil))
Allocations: 2640969 (Pool: 2638386; Big: 2583); GC: 5
0
```

**Comment by JeffBezanson** [comment] 2016-02-24 19:21
Yes, it's possible this is during bootstrap only.

**Comment by yuyichao** [comment] 2016-02-24 19:27
Hmm, I now remembers that we are not cloning the debug info during codegen now due to a missing API in llvm https://github.com/JuliaLang/julia/blob/bd7adbf247cc9436761ff7e4727378e64362b63b/src/cgutils.cpp#L358 Can you see if [this branch](https://github.com/JuliaLang/julia/tree/yyc/llvm-clone) works?

This also causes missing debug info in sysimg on llvm 3.8, this should be fixed on llvm 3.9 by http://reviews.llvm.org/D17165 (with the line linked above uncommented) and hopefully it can be backported to llvm 3.8/3.8.1? @Keno

**Comment by Keno** [comment] 2016-02-24 19:37
Unfortunately, LLVM 3.8 was/is too late in the release stage. We might get it into 3.8.1 though. We can also just carry the patch.

**Comment by yuyichao** [comment] 2016-08-05 22:31
@JeffBezanson Do you have some way of reproducing this? I tried to send signals to the boot strap process and the backtrace looks fine.

**Comment by yuyichao** [comment] 2016-08-05 22:35
Also tried

```diff
diff --git a/base/inference.jl b/base/inference.jl
index 90ae3d8..1d15b8a 100644
--- a/base/inference.jl
+++ b/base/inference.jl
@@ -3354,6 +3354,9 @@ function alloc_elim_pass!(linfo::LambdaInfo, sv::InferenceState)
             i += 1
         end
     end
+    if isdefined(Main, :Base)
+        unsafe_load(Ptr{UInt8}(0))
+    end
 end
 
 # Return the number of expressions deleted before `i0`
```

With or without the condition and the backtrace looks good (with LLVM 3.8)

**Comment by vtjnash** [comment] 2016-08-05 22:35
fixed upstream

**Closed** 2016-08-05 22:35 UTC
Labels: regression, upstream
