### ISSUE TITLE
Unintuitive variable name scopes

### ISSUE THREAD

**Issue by Jackels** [JuliaLang/julia#23000] opened 2017-07-28 12:12 UTC
```
let
  function wat()
    a::String = "wat"
    println(a)
  end

  a::String = "me"
  wat()
end
```

This will throw an exception telling me 

```
ERROR: LoadError: syntax: type of "a" declared in inner scope
while loading /wat.jl, in expression starting on line 1
```

Which is really not helpful at all. Line 1? Wow, thanks! 'syntax: type of "a" declared in inner scope' that tells me nothing, what is wrong with that. It sounds like there are some words missing e. g. " is not allowed because X".

Now my real issue here is, why is this not legal? Why can I not have a function with a local variables whos name is equal to one from outside the function?

**Comment by JeffBezanson** [comment] 2017-07-28 15:27
> Why can I not have a function with a local variables whos name is equal to one from outside the function?

Because the variable is inherited via lexical scope. Putting `local` on the inner variable will make a new variable.

**Comment by JeffBezanson** [comment] 2017-07-28 15:32
Duplicate of #14959

**Comment by KristofferC** [comment] 2019-10-15 10:28
Closing as dup.

**Closed by KristofferC** 2019-10-15 10:28 UTC
Labels: error handling
