### ISSUE TITLE
Unexpected stuck on M1 Mac

### ISSUE THREAD

**Issue by Fenyutanchan** [JuliaLang/julia#48946] opened 2023-03-08 06:20 UTC
1. The output of `versioninfo()`
```log
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.5.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```
2. How you installed Julia
`brew install --cask julia`
---

MWE:
I have the source code file `main.jl` with
```julia
for ii ∈ 1:10000
    println("Begin $ii:")

    write("file_$ii", "test"^100)
    run(`ls file_$ii`)
    rm("file_$ii"; force=true, recursive=true)

    println("End $ii.\n")
end
```
Then, I run `julia main.jl` directly.
The code will be got stuck randomly.
I interrupt it with `^c`, and it exits with
```log
signal (2): Interrupt: 2
in expression starting at /Users/fenyutanchan/workspace/test-julia-file/main.jl:1
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0x0)
Allocations: 2906 (Pool: 2895; Big: 11); GC: 0
```
Actually, the same code works in the Linux platform with `versioninfo()` as
```log
Julia version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, broadwell)
  Threads: 1 or 8 virtual cores
```
It is so strange. Could anyone help me?

**Comment by vtjnash** [comment] 2023-03-10 22:57
Duplicate of https://github.com/JuliaLang/julia/issues/45118

**Closed by vtjnash** 2023-03-10 22:57 UTC
