### ISSUE TITLE
Displaying vector of matrices

### ISSUE THREAD

**Issue by tbreloff** [JuliaLang/julia#13779] opened 2015-10-26 20:53 UTC
On 0.4.0, I see the following unintuitive display behavior for a "vector of matrices":

```
julia> vec_of_mats = Any[Float64[i*j for i in 1:4, j in 1:4]]
1-element Array{Any,1}:
 [1.0,2.0,3.0,4.0,2.0,4.0,6.0,8.0,3.0,6.0,9.0,12.0,4.0,8.0,12.0,16.0]

julia> typeof(vec_of_mats)
Array{Any,1}

julia> vec_of_mats[1]
4x4 Array{Float64,2}:
 1.0  2.0   3.0   4.0
 2.0  4.0   6.0   8.0
 3.0  6.0   9.0  12.0
 4.0  8.0  12.0  16.0

julia> typeof(vec_of_mats[1])
Array{Float64,2}
```

Bug or feature?

**Comment by jiahao** [comment] 2015-10-26 20:59
I can't reproduce on 0.4.1-pre/darwin15.0.0.

```jl
julia> vec_of_mats = Any[Float64[i*j for i in 1:4, j in 1:4]]
1-element Array{Any,1}:
 4x4 Array{Float64,2}:
 1.0  2.0   3.0   4.0
 2.0  4.0   6.0   8.0
 3.0  6.0   9.0  12.0
 4.0  8.0  12.0  16.0
```

**Comment by tbreloff** [comment] 2015-10-26 21:19
Ok this is weird. If I restart julia then the behavior is the same as yours.

I think it's related to an error while displaying a plot in Immerse.jl.

If I display a "vec of mats" before, then the output is as expected:
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0 (2015-10-08 06:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-redhat-linux

julia> using Plots

julia> vec_of_mats = Any[Float64[i*j for i in 1:4, j in 1:4]]
1-element Array{Any,1}:
 4x4 Array{Float64,2}:
 1.0  2.0   3.0   4.0
 2.0  4.0   6.0   8.0
 3.0  6.0   9.0  12.0
 4.0  8.0  12.0  16.0

julia> plot(1:10, 11:20, (x,y) -> sin(x)+cos(y), nlevels=100)
[Plots.jl] Initializing backend: immerse
WARNING: Method definition draw(Compose.Backend, Compose.Context) in module Compose at /home/tom/.julia/v0.4/Compose/src/container.jl:404 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/compose.jl:33.
WARNING: Method definition display(Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, Base.Multimedia.MIME{:text/html}, Gadfly.Plot) in module Gadfly at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:969 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/display_gadfly.jl:144.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
Error showing value of type Plots.Plot{Plots.ImmersePackage}:
ERROR: TypeError: setfield!: expected Union{Array{T,2},Function,Void}, got Array{Any,1}

julia> vec_of_mats = Any[Float64[i*j for i in 1:4, j in 1:4]]
1-element Array{Any,1}:
 4x4 Array{Float64,2}:
 1.0  2.0   3.0   4.0
 2.0  4.0   6.0   8.0
 3.0  6.0   9.0  12.0
 4.0  8.0  12.0  16.0
```

but if the error occurs before I've displayed any "vec of mats" then the resulting display is different:
```
[tom@tomoffice Plots]$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0 (2015-10-08 06:20 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-redhat-linux

julia> using Plots

julia> plot(1:10, 11:20, (x,y) -> sin(x)+cos(y), nlevels=100)
[Plots.jl] Initializing backend: immerse
WARNING: Method definition draw(Compose.Backend, Compose.Context) in module Compose at /home/tom/.julia/v0.4/Compose/src/container.jl:404 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/compose.jl:33.
WARNING: Method definition display(Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, Base.Multimedia.MIME{:text/html}, Gadfly.Plot) in module Gadfly at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:969 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/display_gadfly.jl:144.
WARNING: Base.Uint8 is deprecated, use UInt8 instead.
  likely near no file:0
Error showing value of type Plots.Plot{Plots.ImmersePackage}:
ERROR: TypeError: setfield!: expected Union{Array{T,2},Function,Void}, got Array{Any,1}

julia> vec_of_mats = Any[Float64[i*j for i in 1:4, j in 1:4]]
1-element Array{Any,1}:
 [1.0,2.0,3.0,4.0,2.0,4.0,6.0,8.0,3.0,6.0,9.0,12.0,4.0,8.0,12.0,16.0]
```

Is there some sort of state/flag that gets set/unset during the display method compilation, such that the staged display method depends on a julia state variable?

**Comment by jiahao** [comment] 2015-10-26 21:27
Could it be that one of the packages you are loading redefines a show or display method?

**Comment by tbreloff** [comment] 2015-10-27 22:11
cc: @timholy 

Yes... Immerse.jl redefines some... here's the warnings that are generated:

```
WARNING: Method definition display(Base.REPL.REPLDisplay{R<:Base.REPL.AbstractREPL}, Base.Multimedia.MIME{:text/html}, Gadfly.Plot) in module Gadfly at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:969 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/display_gadfly.jl:144.
WARNING: Method definition draw(Compose.Backend, Compose.Context) in module Compose at /home/tom/.julia/v0.4/Compose/src/container.jl:404 overwritten in module Immerse at /home/tom/.julia/v0.4/Immerse/src/compose.jl:33.
```

Also this might be related... after loading Immerse, I stop getting backtraces for the errors:

```
julia> plot(rand(10,4),c=[:red :blue])
[Plots.jl] Initializing backend: gadfly
Error showing value of type Plots.Plot{Plots.GadflyPackage}:
ERROR: BoundsError: attempt to access 2-element Array{Tuple{Compose.Measure{S,T},Compose.Measure{S,T}},1}:
 (Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.980000000000001,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0),Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.6333333333333337,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0))
 (Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.980000000000001,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0),Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.6333333333333337,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0))
  at index [1:4]
```

but after quitting/reloading (without Immerse this time):

```
julia> plot(rand(10,4),c=[:red :blue])
[Plots.jl] Initializing backend: gadfly
Error showing value of type Plots.Plot{Plots.GadflyPackage}:
ERROR: BoundsError: attempt to access 2-element Array{Tuple{Compose.Measure{S,T},Compose.Measure{S,T}},1}:
 (Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.980000000000001,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0),Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.6333333333333337,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0))
 (Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.980000000000001,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0),Compose.Measure{Compose.MeasureNil,Compose.MeasureNil}(2.6333333333333337,Compose.MeasureNil(),Compose.MeasureNil(),0.0,0.0))
  at index [1:4]
 in throw_boundserror at abstractarray.jl:156
 in getindex at array.jl:288
 in make_layout at /home/tom/.julia/v0.4/Gadfly/src/guide.jl:225
 in map at ./abstractarray.jl:1279
 in render_discrete_color_key at /home/tom/.julia/v0.4/Gadfly/src/guide.jl:303
 in render at /home/tom/.julia/v0.4/Gadfly/src/guide.jl:516
 in render at /home/tom/.julia/v0.4/Gadfly/src/guide.jl:50
 in render_prepared at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:794
 in render at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:721
 in display at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:973
 [inlined code] from multimedia.jl:151
 in display at /home/tom/.julia/v0.4/Gadfly/src/Gadfly.jl:151
 in display at /home/tom/.julia/v0.4/Plots/src/output.jl:104
 in display at REPL.jl:117
 in display at multimedia.jl:151
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at ./LineEdit.jl:1610
 in run_frontend at ./REPL.jl:863
 in run_repl at ./REPL.jl:167
 in _start at ./client.jl:453
```

**Comment by jiahao** [comment] 2015-10-28 14:37
Closing since this does not appear to be a problem with base Julia.

**Closed by jiahao** 2015-10-28 14:37 UTC

**Comment by tbreloff** [comment] 2015-10-28 14:42
Ok.  I do think it is a problem in base Julia which is only showing up
because of something Immerse is doing... however I'm fine to close it and
I'll try to debug myself when I have time.
