### ISSUE TITLE
Updating sysimg to update stdlibs

### ISSUE THREAD

**Issue by aminya** [JuliaLang/julia#36327] opened 2020-06-17 17:21 UTC
We should make it possible to update some parts of sysimg (e.g. different stdlibs) to let all Julia versions use bug fixes without the need to update Julia.

One solution may be to use separate files for each stdlib, which Pkg can update them.

I have seen this issue a lot in the pull requests and issues. People avoid adding a feature to Julia because they are afraid they cannot update it later in case some change is needed. Some examples: #36326, #36223, Pkg's artifacts system, etc.

**Comment by fredrikekre** [comment] 2020-06-17 17:28
Duplicate of #35991 and similar issues.

**Closed by fredrikekre** 2020-06-17 17:28 UTC
