### ISSUE TITLE
Not able to add any packages suddenly -- "Unknown package JLLWrappers"

### ISSUE THREAD

**Issue by grantregen** [JuliaLang/julia#47935] opened 2022-12-20 02:18 UTC
I've been using V1.6 of Julia for a while now, and have had no issues adding packages at all, but now I'm getting this error when I try to add any package: 
```
ERROR: Unknown package JLLWrappers found in the compatibility requirements of Arpack_jll [68821587]
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:33
  [2] Pkg.Resolve.Graph(versions::Dict{Base.UUID, Set{VersionNumber}}, deps::Dict{Base.UUID, Dict{VersionNumber, Dict{String, Base.UUID}}}, compat::Dict{Base.UUID, Dict{VersionNumber, Dict{String, Pkg.Types.VersionSpec}}}, uuid_to_name::Dict{Base.UUID, String}, reqs::Dict{Base.UUID, Pkg.Types.VersionSpec}, fixed::Dict{Base.UUID, Pkg.Resolve.Fixed}, verbose::Bool, julia_version::VersionNumber)
    @ Pkg.Resolve C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Resolve\graphtype.jl:285
  [3] deps_graph(ctx::Pkg.Types.Context, uuid_to_name::Dict{Base.UUID, String}, reqs::Dict{Base.UUID, Pkg.Types.VersionSpec}, fixed::Dict{Base.UUID, Pkg.Resolve.Fixed})
    @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:534
  [4] resolve_versions!(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:404
  [5] targeted_resolve(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel)
    @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:1210
  [6] tiered_resolve(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:1182
  [7] _resolve
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:1216 [inlined]
  [8] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Vector{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
    @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Operations.jl:1231
  [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:203
 [10] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:79
 [11] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:77
 [12] #add#23
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:75 [inlined]
 [13] add
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:75 [inlined]
 [14] #add#22
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:74 [inlined]
 [15] add(pkg::String)
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:74
 [16] top-level scope
    @ REPL[29]:1
```

Not sure if there's an error in another package I have installed already, and I tried to add and remove JLLWrappers and Arpack_jll but no luck--the exact same error pops up when I try to add them and they are not found when I remove them.

pkg.status looks normal too and just prints out the packages I have installed:  

```
(@v1.6) pkg> status
      Status `C:\Users\grant\.julia\environments\v1.6\Project.toml`
  [07493b3f] Alpine v0.4.1
  [7c4d4715] AmplNLWriter v1.0.0
  [c52e3926] Atom v0.12.32
  [5d742f6a] CSVFiles v1.0.2
  [49dc2e85] Calculus v0.5.1
  [8f4d0f93] Conda v1.6.0
  [f65535da] Convex v0.14.18
  [a93c6f00] DataFrames v1.3.4
  [0c46a032] DifferentialEquations v6.19.0
  [e2685f51] ECOS v0.13.0
  [28b8d3ca] GR v0.59.0
  [2e9cd046] Gurobi v0.10.3
  [87dc4568] HiGHS v0.3.2
  [7073ff75] IJulia v1.23.2
  [95701278] ImplicitEquations v1.0.8
  [b6b21f68] Ipopt v0.9.1
  [c8e1da08] IterTools v1.4.0
  [4076af6c] JuMP v0.22.3
  [2ddba703] Juniper v0.8.0
  [e5e0dc1b] Juno v0.8.4
  [429524aa] Optim v1.6.2
  [14b8a8f1] PkgTemplates v0.7.26
  [58dd65bb] Plotly v0.4.1
  [f0f68f2c] PlotlyJS v0.18.8
  [91a5bcdd] Plots v1.22.3
  [08abe8d2] PrettyTables v1.3.1
  [74f56ac7] ReferenceFrameRotations v3.0.0
  [c946c3f1] SCS v0.8.1
  [276daf66] SpecialFunctions v1.8.1
  [90137ffa] StaticArrays v1.4.4
  [0f1e0344] WebIO v0.8.16
```

Any help would be really appreciated, as I would like to avoid deleting all my current packages to reinstall julia (which would probably solve the problem and will be the last resort). 

Thank You!

**Comment by DilumAluthge** [comment] 2022-12-20 02:22
This was caused by a bug in the General registry. The bug has been fixed now - if you open Julia and do `import Pkg; Pkg.Registry.update()`, you should get the fix.

**Closed by DilumAluthge** 2022-12-20 02:22 UTC
