### ISSUE TITLE
log with negative argument is confusing

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10617] opened 2015-03-24 11:38 UTC
Calling `log` on a negative value does everything but tell you that you called it with a negative argument:

``` jl
julia> log(-1.5)
ERROR: DomainError:
log will only return a complex result if called with a complex argument.
try log (complex(x))
 in log at math.jl:123
```

It gives a nice helpful error message about complex results, but doesn't explain why there was an error in the first place.

**Comment by mschauer** [comment] 2015-03-24 12:10
I fell for this before. Maybe the problem is that "DomainError" is much less descriptive than "Argument not in domain of function."

**Comment by jiahao** [comment] 2015-03-24 14:22
We have exactly the same behavior for `sqrt(-1)`.

**Comment by alanedelman** [comment] 2015-03-24 14:42
Argument not in domain of function -- still doesn't quite explain or help with the solution
The familiar mathematical issue: evaluating a function on a branch cut is only slightly relevant, or
perhaps mostly irrelevant

Users often want the principal log or principal sqrt so  the issue is primarily type stability for performance sake vs some users' expectations

May I suggest something like :  The principal logarithm is well defined for negative numbers, but returns complex for real input interfering with type stability and performance.  You may wish to make the real argument complex.

and apply similarly to any other functions

**Comment by ViralBShah** [comment] 2015-03-24 14:48
All we need is a slightly better error message.

**Comment by johnmyleswhite** [comment] 2015-03-24 14:48
Isn't this technically a RangeError, not a DomainError?

**Comment by JeffBezanson** [comment] 2015-03-24 15:09
Many people prefer to get an error in this case for reasons of predictability, rather than performance. I don't think the message needs to include an attempted justification.

**Comment by jiahao** [comment] 2015-03-24 15:13
@johnmyleswhite both `sqrt` and `log` have a branch cut along the negative real axis, where the functions are not analytic. So it would be correct to consider this a `DomainError` (which is @alanedelman's point).

**Comment by jiahao** [comment] 2015-03-24 15:13
But yes, I find the distinction between `DomainError` and `RangeError` rather nebulous.

**Comment by johnmyleswhite** [comment] 2015-03-24 15:19
I'm clearly out of my depth, but I would think being analytic is only a potential property of the `Complex -> Complex` method of `log` since I don't think of being analytic as a property that even applies to the `Real -> Real` method of `log`.

**Comment by johnmyleswhite** [comment] 2015-03-24 15:20
There does seem to be a lot of overlap between `MethodError`, `DomainError` and `RangeError`.

**Comment by StefanKarpinski** [comment] 2015-03-24 15:27
What is `RangeError`? That's not in `base/` anywhere. I think that `DomainError` and `ArgumentError` could be collapsed into a single type. I'm not sure what the distinction is aside from "domain" being a mathy word.

**Comment by jiahao** [comment] 2015-03-24 15:32
I see. So I think of DomainError and RangeError representing states where a method is defined, e.g from Real->Real but either the input is a valid Real but the function is not defined for that subset of Real inputs, or that the output is not a valid Real but is representable in a larger output set containing Real, respectively. log(-1) to me satisfies both criteria.

The problem is that there is no clean separation of RangeError vs DomainError without any function type context. If we had only a method Number->Complex then log(-1) should raise neither error.

I recall having a similar discussion @aviks in the past.

**Comment by JeffBezanson** [comment] 2015-03-24 15:38
I'm glad we don't have `RangeError`. It would be strange, since the arguments to the function are the only thing the caller can control --- any problem that occurs for some argument values and not others must be due to the arguments, and is therefore a DomainError or ArgumentError from a programming perspective.

I'm skeptical of having lots of different exception types. I agree DomainError and ArgumentError could be merged, however it might not be worth making the change at this point.

**Comment by mschauer** [comment] 2015-03-24 16:09
Some evidence from base that the distinction is artificial and thus causing errors is the following:
``log`` gives a DomainError and claims to give an DomainError. ``logdet`` gives an ``ErrorException`` and claims to give an DomainError (also eigmax), ``Base.LinAlg.chol!(-1.)`` gives a DomainError, otherwise matrix functions seem also to give ArgumentErrors etc.


```
julia> log([-1.]')
ERROR: DomainError:
log will only return a complex result if called with a complex argument.
try log (complex(x))
 in log at operators.jl:364

julia> logdet([-1.]')
ERROR: DomainError: determinant is negative
 in logdet at linalg/lu.jl:157

julia> try logdet([-1.]'); catch e; print(typeof(e));end
ErrorException
julia> try log([-1.]'); catch e; print(typeof(e));end
DomainError
julia> 
```

**Comment by aviks** [comment] 2015-03-24 16:47
I think the biggest reason for a lot of this is the fact that you cannot associate a message with `DomainException`. This makes `DomainException`

**Comment by aviks** [comment] 2015-03-24 16:50
I think the biggest reason for a lot of this is the fact that you cannot associate a message with `DomainException`. This makes `DomainException` useless to communicate errors, without doing the stack search (that sqrt and log do).  I believe this is a major cause of not using DomainException consistently. 

I think if we can associate a message with DomainException, a lot of this can be merged.

**Comment by aviks** [comment] 2015-03-24 16:53
@vtjnash  made `BoundsError` smarter, being able to carry a context around. I looked at it, but the LLVM code was too complex for me. If someone can do the LLVM side of `DomainError` being able to carry a message, I will go through and clean up the Julia side.

**Comment by StefanKarpinski** [comment] 2015-03-24 16:56
Can't we just allow any error type to carry context around? Why only this one or that one?

**Comment by JeffBezanson** [comment] 2015-03-24 17:02
This is a tall order. It was hard enough to handle BoundsErrors with just integers. The problem is that allocating a complex exception object introduces too much code into a tight numerical loop. I worry that we are trying to implement a debugger in the exception system. Sure, without a debugger, it's handy to have all that info in a BoundsError. But does the language really promise that you can access all that stuff programmatically whenever an index is out of bounds? I'm not sure I want to commit to that.

**Comment by StefanKarpinski** [comment] 2015-03-24 17:06
Perhaps the debugger is the answer. But that makes the debugger all the more urgent – and not necessarily with a nice UI – just the ability to show a stack trace with argument values would suffice in this case.

**Comment by JeffBezanson** [comment] 2015-03-24 17:08
Yes I tend to think so. Basically, getting good information from exceptions is debugger-complete.

**Comment by aviks** [comment] 2015-03-24 17:09
Well, when the console shows me an error, shouldn't it atleast make an effort to tell me what I could be doing wrong? Currently, when I get a real domain error (other than log or sqrt, this bug notwithstanding), I HAVE to look at the source of the function THROWING the error to find a solution. 

Are we really saying that it is acceptable that any error thrown by Base will need the programmer to debug base code to understand what he is doing wrong?

**Comment by nalimilan** [comment] 2015-03-24 17:14
I agree, the debugger should only be needed for non-trivial cases. It's so nice that `BoundsError` now reports the index and the array. Hainv to start a debugger for that makes code development much more painful -- let alone students who don't know how to use it.

**Comment by aviks** [comment] 2015-03-24 17:15
To clarify, all I want is the ability to attach a string message to an error, so that the _developer_ of a function can communicate to the _user_ of that function when it receives incorrect input. If that is not possible with the `DomainError` type, then as a developer I would rather use something else, and as a user I would find it annoying when I receive one. 

PS: This thread seems to have gone completely off-topic from the original bug report... apologies for my part in it.

**Comment by StefanKarpinski** [comment] 2015-03-24 17:18
I don't really think it's off topic. This is a general problem and while we can put bandaids on specific instances, we need a more general solution.

**Comment by JeffBezanson** [comment] 2015-03-24 17:18
"Debug base code" is putting it a bit strongly. You would be able to see the values of arguments, which is a fully general version of wrapping relevant data in exception objects.

Don't push UI issues into the compiler. Maybe we can integrate a debugger with the REPL, so you don't have to start a separate debugger. If the debugger is a pain to use and nobody knows how to use it, why bother developing it? Also notice that these issues come down to wanting to see certain information, and asking for a specific run-time data structure is a very expensive way to get that.

**Comment by StefanKarpinski** [comment] 2015-03-24 17:25
There's still the issue of having a call-site-specific error message – as opposed to a call-specific error message. In this case, this would be "argument to log cannot be negative, yada, yada". Since this error message can be a compile-time constant, it shouldn't need any compilation or whatnot – actual values can be found from the stack.

**Comment by JeffBezanson** [comment] 2015-03-24 17:38
It would be great to have an approach to call-site specific error messages without allocation. Maybe making more exception types immutable is sufficient.

There is also an issue of error message consistency. It might be more maintainable to have DomainError store the valid range of the function, so we don't need to concoct a new error message in every case. Maybe this is a crazy idea, but doing big passes to edit error messages is not fun.

**Comment by vtjnash** [comment] 2015-03-25 03:44
writing a compilation pass that captures all arguments to the function (or local variables) and forwards them, varargs-style, to `jl_throw` is certainly feasible with fairly low cost (similar to, but a bit more general to the range of functions I provided for emitting bounds errors)

the user's error may be somewhere else far away, but it sometimes can be extremely useful to know if you had `-0.0`, or `-1`, or `-1e37` for bounding the possible causes of the error.

i'm not convinced that a full debugger is required for this. there's something to be said for being able to just look at the error message and immediately be able to fix the bug in your program. i consider this to be similar to printing a backtrace -- it's something relatively small to store but extremely beneficial to the user. in many cases (remote workers, travis, customers), you don't get to see the full code or debugging info, but still want to be able to handle the error as sanely as possible.

while I'm putting together this wish list for santa, It also would be really nice if `@test` /  `@assert` could tell me the values of each of the arguments that it could see syntactically :)

**Comment by JeffBezanson** [comment] 2015-03-25 04:09
Yes you don't always need a full debugger, but with good enough debug info you can print argument values in stack traces.

**Comment by KristofferC** [comment] 2017-09-09 20:31
```
julia> log(-0.5)
ERROR: DomainError with -0.5:
NaN result for non-NaN input.
Stacktrace:
 [1] nan_dom_err at ./math.jl:323 [inlined]
 [2] log(::Float64) at ./math.jl:442
```

Good enough to close?

**Comment by nalimilan** [comment] 2017-09-09 21:29
I wouldn't say so. Even knowing what the problem is, I find it hard to understand that message. We shouldn't mention a "NaN result", since we don't return `NaN` at all (since we raise an error instead). As the original issue description says, the error should mention the fact that the input should not be negative.

**Comment by timholy** [comment] 2017-09-10 15:59
I agree. When I fixed these to allow the arguments to be used, I deliberately preserved the old descriptions exactly (AFAIK), but it seems likely that they could be improved.

**Comment by KristofferC** [comment] 2017-09-10 16:06
WIP at https://github.com/JuliaLang/julia/pull/23652

**Comment by KristofferC** [comment] 2019-03-23 11:38
Now

```
julia> log(-.2)
ERROR: DomainError with -0.2:
log will only return a complex result if called with a complex argument. Try log(Complex(x)).
Stacktrace:
 [1] throw_complex_domainerror(::Symbol, ::Float64) at ./math.jl:31
 [2] log(::Float64) at ./special/log.jl:285
 [3] top-level scope at none:0
```

That seems good enough to close.

**Closed by KristofferC** 2019-03-23 11:38 UTC
Labels: error handling, maths
