### ISSUE TITLE
Matrix view of vector allocates unnecesarily

### ISSUE THREAD

**Issue by baggepinnen** [JuliaLang/julia#41221] opened 2021-06-14 09:47 UTC
In the following example, julia fails to elide the view of the array if the view thinks the underlying array is a matrix rather than a vector.
```julia
function matrix_view(a)
    @views a[:,1]
    0
end

a = randn(3)
A = randn(3,1)
@btime matrix_view($a)
@btime matrix_view($A)

julia> @btime matrix_view($a)
  48.592 ns (2 allocations: 96 bytes)

julia> @btime matrix_view($A)
  1.541 ns (0 allocations: 0 bytes)
```
The problem might be related to the fact that the view thinks the parent is a matrix based on the appearance of the indexing expression, which can not be guaranteed.
```julia
view(a, :, 1)
3-element view(::Matrix{Float64}, :, 1) with eltype Float64:
```

**Comment by mbauman** [comment] 2021-06-14 14:20
Duplicate of #36313

**Comment by mbauman** [comment] 2021-06-14 14:21
Eh, I guess we can treat this separately — we could work around `reshape(::Array, ...)` specifically for this internal use in SubArray.

**Closed** 2022-05-12 05:46 UTC
