### ISSUE TITLE
JuMP.optimize! doesn't work (MacBook M1)

### ISSUE THREAD

**Issue by alessioena** [JuliaLang/julia#46167] opened 2022-07-25 17:37 UTC
**I'm currently programming on Julia using the Ipopt and the JuMP packages and when I try to execute the following code,**

`JuMP.optimize!(mo_d)`

**I get this error**:
```
UndefVarError: libipopt not defined

Stacktrace:
 [1] createProblem(n::Int64, x_L::Vector{Float64}, x_U::Vector{Float64}, m::Int64, g_L::Vector{Float64}, g_U::Vector{Float64}, nele_jac::Int64, nele_hess::Int64, eval_f::Ipopt.var"#eval_f_cb#44"{Ipopt.Optimizer}, eval_g::Ipopt.var"#eval_g_cb#46"{Ipopt.Optimizer}, eval_grad_f::Ipopt.var"#eval_grad_f_cb#45"{Ipopt.Optimizer}, eval_jac_g::Ipopt.var"#eval_jac_g_cb#47"{Ipopt.Optimizer, Vector{Tuple{Int64, Int64}}}, eval_h::Ipopt.var"#eval_h_cb#48"{Ipopt.Optimizer, Vector{Tuple{Int64, Int64}}})
   @ Ipopt ~/.julia/packages/Ipopt/vtrOr/src/Ipopt.jl:320
 [2] optimize!(model::Ipopt.Optimizer)
   @ Ipopt ~/.julia/packages/Ipopt/vtrOr/src/MOI_wrapper.jl:1616
 [3] optimize!(b::MathOptInterface.Bridges.LazyBridgeOptimizer{Ipopt.Optimizer})
   @ MathOptInterface.Bridges ~/.julia/packages/MathOptInterface/YDdD3/src/Bridges/bridge_optimizer.jl:319
 [4] optimize!(m::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ModelFunctionConstraints{Float64}}}})
   @ MathOptInterface.Utilities ~/.julia/packages/MathOptInterface/YDdD3/src/Utilities/cachingoptimizer.jl:252
 [5] optimize!(model::Model, optimizer_factory::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ JuMP ~/.julia/packages/JuMP/klrjG/src/optimizer_interface.jl:185
 [6] optimize! (repeats 2 times)
   @ ~/.julia/packages/JuMP/klrjG/src/optimizer_interface.jl:157 [inlined]
 [7] top-level scope
   @ In[32]:1
 [8] eval
   @ ./boot.jl:373 [inlined]
 [9] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1196
```

**I saw the following [solution](https://discourse.julialang.org/t/errors-using-jump-with-ipopt-or-highs-undefvarerror-libipopt-not-defined-and-undefvarerror-libhighs-not-defined/78539) and I tried to upload the packages, but I got this result:**

`Pkg.update("JuMP")
Pkg.update("Ipopt")`
```
  Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
```
**These are the versions I currently have installed**:
```
  Status `~/.julia/environments/v1.7/Project.toml`
  [7073ff75] IJulia v1.23.3
  [b6b21f68] Ipopt v0.7.0
  [4076af6c] JuMP v0.21.10
  [d330b81b] PyPlot v2.10.0
```
**(and they remained the same after the upload)**

**Comment by gbaraldi** [comment] 2022-07-25 19:12
The issue is that your packages are outdated, specifically JuMP. There might be something in your environment that is stopping the update. An easy way to fix this is to remove the packages from the environment and then readd them.

**Comment by giordano** [comment] 2022-07-25 20:12
I'm going to close this ticket as this is a problem with JuMP, and specifically the fact you have an old version.  If you need help with managing package environments, please direct your questions to, for example, https://discourse.julialang.org/

**Closed by giordano** 2022-07-25 20:12 UTC
