### ISSUE TITLE
Request: Vector and Matrix constructors.

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#10075] opened 2015-02-04 13:26 UTC
For previous discussion, see: https://groups.google.com/forum/#!topic/julia-users/FBmU-mxQ0k4

My request is to have functionality to be able to initialize a vector of size `N` and type `T` using the `Vector(T, N)` command. This would be equivalent to the current `Array(T, N)`. The reason for this is that it if I have a function taking a `Vector` argument it feels nice to create the vector I send in to the function using a `Vector` constructor. Same for matrices.

I tried to implement it myself like this (and in some other ways) but it is not working:

```julia
Base.call{T}(::Vector{T}, size::Int) = Array(T, size)
```

**Comment by nalimilan** [comment] 2015-02-04 13:41
I think what you need is this:
```julia
Base.call(::Type{Vector}, T::Type, m::Integer) = Array(T, convert(Int, m))
```

This is consistent with the definition used for `Array` (cf. `@edit Array(Int, 1)`). It ensures that e.g. `Vector(Int, BigInt(1))` works.

Note `::Type{Vector}`, which means that the argument is the `Vector` *type*, not a `Vector` object.

Could you prepare a PR for this (together with the equivalent code for `Matrix`, and some tests)? Thanks!

**Comment by stevengj** [comment] 2015-02-04 13:43
You could also have `Base.call{T}(::Type{Vector{T}}, m::Integer) = Array(T, Int(m))` to support e.g. `Vector{Int}(5)`.

**Comment by StefanKarpinski** [comment] 2015-02-04 13:50
While we're at it, I think it would be nice if things like `Array{Int}(3,4)` worked. Arguably that's a better, more consistent way to construct arrays than the current `Array(Int,3,4)`.

**Comment by nalimilan** [comment] 2015-02-04 13:51
@stevengj You're right about `convert` of course.

Regarding `Array{Int}(5)`, I've often wanted to do that too, but having too many ways of doing the same thing is not great. We should decide which one is the recommended way, and deprecate the other.

**Comment by ivarne** [comment] 2015-02-04 13:59
`Array{Int}(3,4)` or `Array{Int, 2}(3,4)`

**Comment by StefanKarpinski** [comment] 2015-02-04 14:20
I would say that both could be allowed, but `Array{Int,2}(3,4)` is redundant and the fact that it's a matrix is implied by the dimensions. As for too many ways, I'd favor deprecating `Array(Int,3,4)`.

**Comment by milktrader** [comment] 2015-02-04 14:52
Yeah, +1 for deprecating `Array(Int,3,4)`

This suggests the type is just another parameter, but putting it into curly braces reinforces the notion that types are super-parameters.

**Comment by bicycle1885** [comment] 2015-02-05 07:00
It looks nice and is what I expected to work when I started to play with Julia :+1:.
If you are reluctant to do the job, can I take on it?

**Comment by KristofferC** [comment] 2015-02-05 08:07
How about things like `floor(Integer, x)`? Should they be written `floor{Integer}(x)` as well?

**Comment by bicycle1885** [comment] 2015-02-05 11:00
That would be a separated question. `Array{T,N}` is a constructor but `floor`s are not.
If we take the idea, too many functions that take a type as its first argument will be affected (`rand(Bool)` => `rand{Bool}()`, `convert(Int, 1.0)` => `convert{Int}(1.0)` etc...).

**Comment by JeffBezanson** [comment] 2015-02-05 18:49
duplicate of #3214

**Closed** 2015-02-12 21:06 UTC
Labels: decision

**Comment by JeffBezanson** [comment] 2015-02-12 21:08
I added these. We can decide whether to do formal deprecations --- prepare yourself for lots of warnings!!

I didn't add `Vector(T, n)`, pending the deprecation decision.

**Comment by jakebolewski** [comment] 2015-02-12 21:13
Is it correct that `Array{Int}(1,2)` constructs a new array and `Array{Int}((1,2))` calls `convert(::Type{Array{Int}}, (1,2))`?

**Comment by jakebolewski** [comment] 2015-02-12 21:16
I see the old behavior is still retained.  So `Array{Int}([1,2])` is a conversion and `Array{Int}((1,2))` is a constructor?

**Comment by JeffBezanson** [comment] 2015-02-12 21:33
Yes.

**Comment by jakebolewski** [comment] 2015-02-12 21:55
If this is going to be the new default behavior, could be deprecate the `NTuple` constructor?

**Comment by JeffBezanson** [comment] 2015-02-12 22:15
I would be fine with that, but the trouble is that an NTuple carries type information about the number of dimensions, while varargs do not. So we will need to hack around that with an internal definition that still accepts a tuple. There is also something to be said for minimizing splatting, and writing `Array{T}(size(x))`.

**Comment by stevengj** [comment] 2015-02-13 03:19
See Jeff's commit: 23a6995a560ae88c14bf8e299faec7a4688df3f9
