### ISSUE TITLE
Documentation bug: Delimited Files

### ISSUE THREAD

**Issue by mushunrek** [JuliaLang/julia#51642] opened 2023-10-09 08:05 UTC
I just noticed that the documentation of the standard library [DelimitedFiles](https://docs.julialang.org/en/v1/stdlib/DelimitedFiles/) points to non-existing files in this repository.

**Comment by KristofferC** [comment] 2023-10-09 09:07
Duplicate of https://github.com/JuliaLang/julia/issues/50035

**Closed by KristofferC** 2023-10-09 09:07 UTC
