### ISSUE TITLE
Conditional Definition of Functions Incorrect Answer and Error

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/julia#16965] opened 2016-06-16 14:41 UTC
[This is from julia-users](https://groups.google.com/forum/#!topic/julia-users/IHKQVFVWSMY). The example is:

```julia
function g(a)
  if a
    f() = 2
  else
    f() = 3
  end
  return f
end
f = g(true)
f() # Returns 3
```

What's also interesting is that g(false) in another REPL session gives an error: "f not defined". So in this setup you either get the second function (if you ask for the first one), or you get nothing! This is on Commit 59d1539 (4 days old master).

**Comment by JeffBezanson** [comment] 2016-06-16 14:57
Duplicate of #15602

**Closed** 2016-06-18 21:55 UTC
