### ISSUE TITLE
sequential partial macro expansion leads to different code from code with all the macros expanded at once

### ISSUE THREAD

**Issue by aviatesk** [JuliaLang/julia#39762] opened 2021-02-20 14:02 UTC
I assumed `macroexpand` is supposed to produce the same code whether or not if it expands all the macros at once or sequentially expands macros with `recursive = false` option.

Here is a MRE where `macroexpand(m, ex; recursive = true)` produces valid code while sequential application of `macroexpand(m, ex; recursive = false)` leads to different code (and invalid code as a consequence).

```julia
using Test

ex = :(@test_warn "foo" println(stderr::IO, "foo"))

fully_expanded = macroexpand(@__MODULE__, ex)
Core.eval(@__MODULE__, fully_expanded) # runs w/o any problem

partially_expanded = macroexpand(@__MODULE__, ex; recursive = false)                  # expand `@test_warn`
partially_expanded2 = macroexpand(@__MODULE__, partially_expanded; recursive = false) # expand `@test`
Core.eval(@__MODULE__, partially_expanded2) # leads to syntax error
Core.eval(@__MODULE__, partially_expanded)  # this also leads to syntax error
```

**Comment by vtjnash** [comment] 2021-02-20 17:38
No, they are not currently supposed to produce the same result.

Duplicate of https://github.com/JuliaLang/julia/issues/20241 (and follow on bugs like https://github.com/JuliaLang/julia/issues/32026 and https://github.com/JuliaLang/julia/issues/32603)

**Closed by vtjnash** 2021-02-20 17:38 UTC
Labels: lowering, macros

**Comment by aviatesk** [comment] 2021-02-20 17:45
Thanks. I couldn't find the reference myself.
