### ISSUE TITLE
performance bug with 6-index arrays in 0.5.0 and 0.5.1

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#20943] opened 2017-03-08 02:48 UTC
I've reported this problem before on discourse but apparently I didn't file an issue, and the fix was not included in 0.5.1.  There is a performance bug in 0.5.0, and also now in 0.5.1, with arrays that have 6 or more subscripts.  The bug is fixed in 0.4.7 and was also fixed in 0.6.0 last time I checked.  Here is a sample.  
```julia

julia> @time test_manyway.test2way(100000)
  0.001451 seconds (6 allocations: 288 bytes)
49987.500777183195

julia> @time test_manyway.test4way(100000)
  0.005792 seconds (7 allocations: 432 bytes)
50226.90084188317

julia> @time test_manyway.test6way(100000)
 10.533045 seconds (64.00 M allocations: 1.526 GB, 1.35% gc time)
49979.21341756834
```

```
module test_manyway

function test2way(n)
    a2 = zeros(2,2)
    x = 0.0
    for tr = 1 : n
        for j1 = 1 : 2
            for j2 = 1 : 2
                a2[j1,j2] = rand()
            end
        end
        x += a2[1,1]
    end
    x
end

function test4way(n)
    a4 = zeros(2,2,2,2)
    x = 0.0
    for tr = 1 : n
        for j1 = 1 : 2
            for j2 = 1 : 2
                for j3 = 1 : 2
                    for j4 = 1 : 2
                        a4[j1,j2,j3,j4] = rand()
                    end
                end
            end
        end
        x += a4[1,1,1,1]
    end
    x
end

function test6way(n)
    a6 = zeros(2,2,2,2,2,2)
    x = 0.0
    for tr = 1 : n
        for j1 = 1 : 2
            for j2 = 1 : 2
                for j3 = 1 : 2
                    for j4 = 1 : 2
                        for j5 = 1 : 2
                            for j6 = 1 : 2
                                a6[j1,j2,j3,j4,j5,j6] = rand()
                            end
                        end
                    end
                end
            end
        end
        x += a6[1,1,1,1,1,1]
    end
    x
end


function test7way(n)
    a7 = zeros(2,2,2,2,2,2,2)
    x = 0.0
    for tr = 1 : n
        for j1 = 1 : 2
            for j2 = 1 : 2
                for j3 = 1 : 2
                    for j4 = 1 : 2
                        for j5 = 1 : 2
                            for j6 = 1 : 2
                                for j7 = 1 : 2
                                    a7[j1,j2,j3,j4,j5,j6,j7] = rand()
                                end
                            end
                        end
                    end
                end
            end
        end
        x += a7[1,1,1,1,1,1,1]
    end
    x
end



function test8way(n)
    a8 = zeros(2,2,2,2,2,2,2,2)
    x = 0.0
    for tr = 1 : n
        for j1 = 1 : 2
            for j2 = 1 : 2
                for j3 = 1 : 2
                    for j4 = 1 : 2
                        for j5 = 1 : 2
                            for j6 = 1 : 2
                                for j7 = 1 : 2
                                    for j8 = 1 : 2
                                        a8[j1,j2,j3,j4,j5,j6,j7,j8] = rand()
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        x += a8[1,1,1,1,1,1,1,1]
    end
    x
end

function test8wayb(n)
    x = 0.0
    x2 = 0.0
    for tr = 1 : n
        for j1 = 1 : 2
            for j2 = 1 : 2
                for j3 = 1 : 2
                    for j4 = 1 : 2
                        for j5 = 1 : 2
                            for j6 = 1 : 2
                                for j7 = 1 : 2
                                    for j8 = 1 : 2
                                        x2 = rand()
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
        x += x2
    end
    x
end
end
```

**Comment by tkelman** [comment] 2017-03-08 19:49
Someone will need to bisect or otherwise identify what the fix was.

**Comment by timholy** [comment] 2017-03-08 20:03
Prob #19097 and #19197. I should have marked them for backport, sorry.

**Comment by mbauman** [comment] 2017-03-08 20:32
Let's pick a number of dimensions and add the functions above as test cases to BaseBenchmarks.jl.  This has proven to be finicky and it'd be nice to get nano soldier to track them for us.  Definitely at least 6. Maybe 10 or 12?

I marked #19197 with a backport tag just in case there's another 0.5 release.

**Comment by KristofferC** [comment] 2017-03-08 20:37
They are already there. At least up to 7.

**Comment by tkelman** [comment] 2017-03-08 22:03
and yes you did open an issue - duplicate of https://github.com/JuliaLang/julia/issues/20449

**Closed by tkelman** 2017-03-08 22:03 UTC
Labels: arrays, performance
