### ISSUE TITLE
Deprecation warning for Array(T) never stop printing

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#20220] opened 2017-01-24 20:20 UTC
For example: `Pkg.test("SHA")`:

Gif: https://media.giphy.com/media/l3q2uhPC2EsBExBvi/source.gif

**Comment by tkelman** [comment] 2017-01-24 20:55
This has been causing pkgeval to freeze for the last several weeks.

**Comment by KristofferC** [comment] 2017-02-06 11:58
Can we hack around this somehow?

**Comment by vtjnash** [comment] 2017-02-06 16:05
Probably. The problem is that the name of the function is actually `Type`, while we've applied the deprecation to the name `Array`.

**Comment by mlubin** [comment] 2017-02-07 21:51
Yes please. This is making packages with deprecation warnings untestable on Travis because of log size limits.

**Comment by tkelman** [comment] 2017-02-09 11:46
> hack around this

give #20538 a try

**Comment by tkelman** [comment] 2017-02-11 18:24
This is still happening with the `Array` deprecation, see for example `Pkg.test("Dopri")`

**Comment by JeffBezanson** [comment] 2017-04-12 20:52
Is this fixed now?

**Comment by KristofferC** [comment] 2017-04-12 21:07
Don't think so.

**Comment by tkelman** [comment] 2017-04-12 21:11
Nope. Edited above, pin to Dopri 0.3.0 for a test case.

**Closed** 2017-04-13 02:39 UTC
Labels: deprecation, display and printing, priority

**Comment by KristofferC** [comment] 2017-04-20 08:17
I'm still having problems with deprecation being printed more than once:

![image](https://cloud.githubusercontent.com/assets/1282691/25220591/85836300-25b2-11e7-8c34-065a72c014c8.png)

**Comment by JeffBezanson** [comment] 2017-04-20 15:02
My guess is that's because IJulia labels each input with a different "file name", so the calls appear to come from different source locations. We print a warning for each distinct location to help you find all of them.

**Comment by KristofferC** [comment] 2017-04-20 15:23
How is that handled in the repl? I thought the repl filename is changed as `REPL[1], REPL[2], ...` for each evaluated line?
