### ISSUE TITLE
Further startup time improvements

### ISSUE THREAD

**Issue by Keno** [JuliaLang/julia#17285] opened 2016-07-05 19:13 UTC
Doing some profiling of startup time, the main items are:
- BLAS/LibGit2 initialization (each 10%)
- Creating `Function *` objects for symbols in the system image (~15%)
- Codegen for functions called by cholmod's **init** (~7-8%)
- FLISP initialization (~5%)
- Dynamic linker (~2-3%)
- Most of the rest is in dump.c, restoring the system image.

Low hanging fruits are perhaps, creating `Function *` objects lazily, and deferring libgit2 initialization until it's needed. Might also be worth looking into cholmod's **init** to try to get it to compile everything up front.

**Comment by StefanKarpinski** [comment] 2016-07-05 23:38
Loading and parsing `~/.julia_history` may also be contributing when present. Doing that lazily could be a big win and shouldn't be too hard.

**Comment by Keno** [comment] 2016-07-05 23:46
Yes, it can be significant if your history file is large.

**Comment by JeffreySarnoff** [comment] 2016-07-12 09:07
Why is it not possible to pre-create `Function *` objects  for symbols in the system image within the system image?  Would it make sense to defer BLAS initialization until it is needed?  
I think many history files are large; and as the user base expands that proportion will grow.

**Comment by svnpenn** [comment] 2018-07-19 16:35
https://github.com/JuliaLang/julia/issues/28092

**Comment by KristofferC** [comment] 2018-07-25 11:20
Update of what takes time to startup (ran at #28118)

<img width="639" alt="screen shot 2018-07-25 at 13 19 16" src="https://user-images.githubusercontent.com/1282691/43198009-5a963f98-900d-11e8-9df2-d6036f9a5280.png">

So, ~55% is restoring the sysimg, 18% is blas, 5% is initialization of frontend, 4% is a call to `srand`.

Why does BLAS start two thread servers?

**Comment by cup** [comment] 2018-08-08 03:33
I did some more tests with updated Julia - certainly improved from 0.7.0-beta,
but still seems about 20% slower than even Ruby on my system:

~~~
$ julia -v
julia version 0.7.0-rc3

$ time julia -e 'println("hello world")'
hello world

real    0m0.250s
~~~


~~~
$ julia -v
julia version 1.0.0-rc1

$ time julia -e 'println("hello world")'
hello world

real    0m0.228s
~~~

**Comment by StefanKarpinski** [comment] 2018-08-14 00:37
True, but also about 100x faster than Ruby 😁

**Comment by cup** [comment] 2018-08-14 00:40
@StefanKarpinski thats the exact opposite of what i just said - can you explain

**Comment by StefanKarpinski** [comment] 2018-08-14 17:40
What I'm saying is that in exchange for Julia's 20% slower startup time, you get a language that's 100x faster than Ruby. The fact that Julia is _only_ 20% slower to startup is fairly impressive given that compiling your C++ code would take considerably longer, for example. Startup and compilation time is and will continue to be a high priority for us and will be improved going forward, but posting comparisons between Julia's startup time and the startup time of various slow, interpreted languages doesn't really contribute anything useful. We already know how long it takes to start Julia up and there's nothing we can learn from those languages since they are so technologically dissimilar. If you happen to know of a fast, JIT compiled language with really snappy startup time, then that would be helpful.

**Comment by cup** [comment] 2018-08-14 17:43
@StefanKarpinski first one that comes to mind is PowerShell - but that might not be a good match - i will link in case it is helpful - thanks

http://github.com/PowerShell/PowerShell

**Comment by StefanKarpinski** [comment] 2018-08-14 18:16
PowerShell command execution time is more comparable to timing evaluation in Julia's REPL, which is quite fast for everyone's favorite super useful example:
```jl
julia> @time println("Hello, world")
Hello, world
  0.002232 seconds (27 allocations: 1.750 KiB)

julia> @time println("Hello, world")
Hello, world
  0.000022 seconds (8 allocations: 240 bytes)
```

**Comment by ysmood** [comment] 2018-08-15 01:10
@StefanKarpinski how about luajit?

![image](https://user-images.githubusercontent.com/1415488/44126376-e3ad8960-a072-11e8-9187-d46133cfd5b3.png)

just joking 😂

**Comment by cup** [comment] 2018-08-15 01:14
@ysmood LOL owned :)

**Comment by StefanKarpinski** [comment] 2018-08-17 16:32
LuaJIT is a super impressive piece of work. There's still not much to learn since Lua is notoriously minimal and LuaJIT doesn't do any of the things that are taking time above: loading and initializing a BLAS library, a high-performance RNG, multithreading infrastructure, etc.

**Comment by PallHaraldsson** [comment] 2018-12-23 12:06
"4% is a call to srand."

How about getting rid of that for Julia 1.1; MersenneTwister?

Does having to do "using Random" do that already?

**Comment by ViralBShah** [comment] 2018-12-23 17:17
Which codes are you referring to?

**Comment by ViralBShah** [comment] 2018-12-26 17:04
I thought those RNG don't pass the RNG testsuite.

**Comment by cup** [comment] 2019-01-01 21:54
I noticed something interesting. If you take Julia, it is slower than Ruby in
regards to a `time` test:

~~~
manjaro-lxqt% julia -v       
julia version 1.0.3

manjaro-lxqt% time julia -e 0
julia -e 0  0.08s user 0.05s system 95% cpu 0.136 total
~~~

~~~
manjaro-lxqt% ruby -v          
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

manjaro-lxqt% time ruby -e 0
ruby -e 0  0.05s user 0.02s system 90% cpu 0.075 total
~~~

However it seems to win with `strace` test:

~~~
manjaro-lxqt% strace -c julia -e 0 2>&1 | awk '/sec|tot/'
% time     seconds  usecs/call     calls    errors syscall
100.00    0.000107                   768       101 total
~~~

~~~
manjaro-lxqt% strace -c ruby -e 0 2>&1 | awk '/sec|tot/'
% time     seconds  usecs/call     calls    errors syscall
100.00    0.001197                  1407       320 total
~~~

**Comment by cup** [comment] 2019-11-19 03:28
I did some more testing, and it seems Julia is still at least 5 times slower
than even Ruby:

~~~
$ bin/julia -v
julia version 1.2.0

$ cat app.jl
using Formatting
s1 = FormatExpr("{1:05.2f}")
printfmtln(s1, 1.2)

$ time bin/julia app.jl
01.20

real    0m0.828s
~~~

~~~
$ cat app.rb
s1 = '%05.2f' % 1.2
puts s1

$ time ruby app.rb
01.20

real    0m0.140s
~~~

~~~
$ cat app.py
s1 = format(1.2, '05.2f')
print(s1)

$ time python3 app.py
01.20

real    0m0.094s
~~~

~~~
$ cat app.php
<?php
$s1 = sprintf('%05.2f', 1.2);
var_dump($s1);

$ time php app.php
string(5) "01.20"

real    0m0.078s
~~~

**Comment by KristofferC** [comment] 2019-11-19 06:07
Use 1.3. 1.2 has a known startup time regression.

**Comment by ViralBShah** [comment] 2019-11-19 14:03
Also, startup times of interpreters are not comparable with jit compiled languages.

**Comment by cup** [comment] 2019-11-19 14:25
@KristofferC thanks - I will try new version and also Printf later and update

@ViralBShah um ok? Do you have some comparable languages that I can test against then?

**Comment by KristofferC** [comment] 2019-11-19 14:46
>  I will try new version and also Printf later and update

This specific example is pretty arbitrary though. If we only talk about latency you can do

```
❯ time julia --compile=min app.jl
01.20
julia --compile=min app.jl  0.08s user 0.06s system 133% cpu 0.104 total
```

Comparing random small pieces of code between different languages is not really productive.

**Comment by cup** [comment] 2019-11-19 14:53
@KristofferC but *it is a comparison*. I think youre in a better position to criticise my methods, after youve presented your own comparison.

**Comment by KristofferC** [comment] 2019-11-19 14:58
My point is that simple comparisons don't provide any information that help make Julia improve. Profiling like https://github.com/JuliaLang/julia/issues/17285#issuecomment-407721005, identifying hot spots where things can be optimized etc, on the other hand, might be useful.

Saying Julia does x in 0.5s while OtherLanguage does it in 0.3s is just pointless in an issue like this. You could post the result on a blog or something.

**Comment by cup** [comment] 2019-11-19 15:13
@KristofferC youre right in that it doesnt help fix the problem.

But it does help confirm the existence of the problem, and the degree.

Something to help fix the problem would be more valuable, which I think you are
alluding to. But suggesting that comparison testing has no value is just wrong.
Comparison is literally the only way one could know a problem exists in the
first place.

Without comparison, youd have to have some objective measure of what is fast and
slow in regard to interpreter startup, and I am not aware of any such standard.

**Comment by cup** [comment] 2020-02-08 17:01
To add a counter, Dart is a popular language:

https://github.com/flutter/flutter

and it is pretty slow:

~~~
$ cat a.dart
main () {
   print('sunday');
}

$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "windows_ia32"

$ time dart a.dart
sunday

real    0m0.390s
~~~

Julia is faster:

~~~
$ cat a.jl
println("sunday")

$ julia -v
julia version 1.5.0-DEV

$ time julia --compile=min a.jl
sunday

real    0m0.140s
~~~

**Comment by ViralBShah** [comment] 2020-02-08 18:09
For cholmod, we could avoid compiling it into the system image. I in imagine compiling SuitesSparse is hardly noticeable. 

I imagine libgit2 can also be removed from the system image in 1.4 once Pkg does not need it.

**Comment by ViralBShah** [comment] 2020-02-08 18:11
Not building blas into the system image will open the door to easier use of alternate blas libraries. However this one will affect a lot of people, if it is not in the system image.

**Comment by KristofferC** [comment] 2020-02-08 18:12
> I imagine libgit2 can also be removed from the system image in 1.4 once Pkg does not need it.


Pkg needs LibGit2 in 1.4.

**Comment by ViralBShah** [comment] 2020-02-08 18:16
Is it 1.5 then or am I misunderstanding?

**Comment by KristofferC** [comment] 2020-02-08 18:41
Yes, we still support using git fo registries and to add unregistered packages via git URLs.

**Comment by JeffreySarnoff** [comment] 2020-02-08 21:37
> Not building blas into the system image will open the door to easier use of alternate blas libraries. However this one will affect a lot of people, if it is not in the system image. And these packages probably have significant compile time.

Why not build it into the system image and also allow an alternate blas library to be used?

**Comment by nu8** [comment] 2020-10-20 20:19
https://github.com/JuliaLang/julia/issues/36016

**Comment by ViralBShah** [comment] 2021-05-19 21:48
Should we close this now?

**Closed** 2021-05-19 21:52 UTC
Labels: latency
