### ISSUE TITLE
Warnings from ld on mac

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#41399] opened 2021-06-28 15:01 UTC
On current master (on macOS), I get these warnings when building Julia. I suppose they are safe to ignore.

```
    LINK usr/lib/julia/sys.dylib
ld: warning: could not create compact unwind for _julia_Dict_17462: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _julia_Dict_17470: stack subq instruction is too different from dwarf stack size
➜  julia git:(master) ./julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-DEV.86 (2021-06-28)
 _/ |\__'_|_|_|\__'_|  |  Commit 74fab49ffb (0 days old master)
|__/                   |

```

**Comment by dkarrasch** [comment] 2021-06-28 19:05
Duplicate of #41191.

**Comment by DilumAluthge** [comment] 2021-06-28 22:11
Duplicate of #41191

**Closed by DilumAluthge** 2021-06-28 22:11 UTC
Labels: build, mac

**Comment by dkarrasch** [comment] 2021-06-29 05:42
@DilumAluthge How do you do this "marked as a duplicate"? I thought I typed the same but somehow GH didn't recognize this as a "keyword" for crossreferencing.

**Comment by DilumAluthge** [comment] 2021-06-29 05:48
I clicked "Close with comment" - I think that's necessary to trigger the keyword.
