### ISSUE TITLE
Lettings macros get the entire scope from where it is called through implicit parameter

### ISSUE THREAD

**Issue by JKRT** [JuliaLang/julia#32453] opened 2019-06-29 21:14 UTC
Consider these two files:

```
module fooScope
include("./minEx.jl")
import .myMod
function bar()
end
using Test
@testset begin #This works fine without @testset
function foo()
  0
end
 println(myMod.@client)
end
end

```

It imports 

```
#Some other file
module myMod
function getClientField(__module__::Module)
  println(names(__module__))
  getfield(__module__, :foo)
end
macro client()
  a = getClientField(__module__)
end
end

```
When enclosing the first macro in a @testset a new scope is introduced! However, that scope is not caught by the __module__ which is logical, since __module__ captures the module and not the scope. This led to an interesting bug for me in which my tests failed but not my actual code.  Being a Julia beginner my self I struggled with this far too long before releasing it tonight. Would the addition of a __scope__ implicit parameter for macros, in general, be something feasible?  

All the best 

John

**Comment by yuyichao** [comment] 2019-06-29 21:35
What do you mean by scope? Are you talking about variable scope? If yes, then it's impossible since that concept does not exist when the macro is called yet.

It seems that you assume every scope is a module and you can access variables in that scope via fields. Such things does not exist in julia by design. Your macro is also doing evaluation at the macro expansion time rather than runtime which is wrong if you want to access local variables in the calling scope. Please read the macro hygene section in the document and ask any further questions on discourse.julilalang.org

**Comment by JKRT** [comment] 2019-06-29 22:22
> 
> 
> What do you mean by scope? Are you talking about variable scope? If yes, then it's impossible since that concept does not exist when the macro is called yet.
> 
> It seems that you assume every scope is a module (or something module-like) and you can access variables in that scope via fields. Such things does not exist in julia by design. Your macro is also doing evaluation at the macro expansion time rather than runtime which is wrong if you want to access local variables in the calling scope. Please read the macro hygene section in the document and ask any further questions on http://discourse.julialang.org

Thank you for your time! 

The scope in which the function is declared, in this case inside @testset.  Without using @testset it would work fine, even when I nest modules. I guess that @testset creates a variable scope I did not expect that. My bad. The intention regarding the code I am currently writing is doing everything during expansion time.  Thus, I am not interested in capturing variables declared in some scope from where I call my macro, so that is a non issue for me. I do not quite see what my question has to do with macro hygene?

It worked fine, in production but the results using @testset confused me somewhat. As stated I do not wish to access variables rather declarations such as the function foo.

However, looking at the IR it seems that this scope is accessible at some point 

`julia> function bar()
       function barbar()
       4
       end
       barbar()
       end
bar (generic function with 1 method)

julia> code_lowered(bar)
1-element Array{Core.CodeInfo,1}:
 CodeInfo(
1 ─      barbar = %new(Main.:(#barbar#10))
│   %2 = (barbar)()
└──      return %2
)`

And if I write 

`julia> function bar()
       function barbar()
       end
       end
bar (generic function with 1 method)

julia> a = bar()
(::getfield(Main, Symbol("#barbar#4"))) (generic function with 1 method)
`
So it does seems that atleast nested functions have the declaration as some kind of field. Altough I cannot access it

**Comment by yuyichao** [comment] 2019-06-30 03:15
> Without using `@testset` it would work fine, even when I nest modules.

"Work fine" does not mean you are writing the right code.

> The intention regarding the code I am currently writing is doing everything during expansion time.

There's absolutely no way you can get accessed to `foo` during macro expansion time. It's not even created when your macro is called.

> Thus, I am not interested in capturing variables declared in some scope from where I call my macro, so that is a non-issue for me.

`@testset` **is** the scope from where you are calling your macro. `foo` is defined in that scope so yes you are absolutely interested in a variable defined in the calling scope of the macro.

> So it does seems that at least nested functions have the declaration as some kind of field.

No that's completely unrelated.

From your comment you seems to have some deep misunderstanding of a lot of things, common for beginners, and this is not the right place for it. What you are asking is fundamentally impossible to do, no matter how you interpreted some of your observations otherwise. Again, please close this issue and move the discussion to discourse.

**Closed** 2019-06-30 04:16 UTC
