### ISSUE TITLE
Function composition to take arguments

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [JuliaLang/julia#19001] opened 2016-10-18 13:14 UTC
The status quo, as I understand, is that the following is valid code:

    "The quick red fox jumped over the lazy dog." |> length |> sqrt |> log

However, the following is not:

    "The quick red fox jumped over the lazy dog." |> length |> hypot(9)

The way around this is using a stabby lambda, as in

    "The quick red fox jumped over the lazy dog." |> length |> x -> hypot(x, 9)

This is on the whole workable, but a tad clumsy. I wonder if this could possibly be reframed to work a little more like [magrittr](https://cran.r-project.org/web/packages/magrittr/vignettes/magrittr.html), where the operator automatically feeds the result of the previous operation into the next one as its first argument. I appreciate there is a degree of sacrificing the theoretical purity of the operator here (as of course this would mean the correspondence between `f |> g` and `f ○ g`, but perhaps it would be a more convenient tool. Potentially, as a separate operator.

What do you think?

**Comment by chrisvoncsefalvay** [comment] 2016-10-18 13:14
(duh, wrong word)

**Comment by yuyichao** [comment] 2016-10-18 13:31
Duplicate of many other issues.

**Comment by simonbyrne** [comment] 2016-10-18 14:25
Yes, duplicate of #5571.

**Closed by simonbyrne** 2016-10-18 14:25 UTC
