### ISSUE TITLE
Return basic statistical functionality to Base

### ISSUE THREAD

**Issue by ararslan** [JuliaLang/julia#27374] opened 2018-06-01 19:11 UTC
It seems incredibly unfortunate to me, and indeed almost actively user-hostile, to remove basic functionality such as `std` from Base. @sbromberger summarized it well in Slack: "if the function is generally understood by a layperson, it should not be removed." You don't have to be a statistics expert to understand what a standard deviation is. The collection of basic statistics functionality in Base in previous versions of Julia was fairly lean and I think struck the perfect balance of "here are the basics, now load a package if you want to get more advanced." Indeed, in the `release-0.6` branch, `base/statistics.jl` is a couple hundred lines of code, including whitespace and extensive documentation. Who was it hurting to have in Base?

**Comment by sbromberger** [comment] 2018-06-01 19:17
I note that `mean` and `median` are still in Base. What are the current criteria for moving things out?

> The collection of basic statistics functionality in Base in previous versions of Julia was fairly lean and I think struck the perfect balance of "here are the basics, now load a package if you want to get more advanced."

This, 100%. I will fight the "npm-ification" of Julia as long as I'm a participating member of the community. Having things ready to go out of the box was a huge selling point for me.

Moving large chunks of "basic" functionality out of Base to other packages also makes the library ecosystem that much more fragile – while `Pkg.add("StatsBase")` isn't so much of a problem for an end user, it introduces a dependence fragility on any libraries that need a function like `std` now, which then propagate to other libraries / end users.

**Comment by pablosanjose** [comment] 2018-06-01 19:57
FWIW I agree. 

Is there an official decision of where the line is drawn between Base, stdlib and third-party packages?
 
I think this is a crucial definition that can totally affect the character and feel of a language, from Julia-the-language to Julia-the-platform. With the current strategy, the development of Julia-the-language is fast and nimble, but at the cost of a fragile/fragmented Julia-the-platform, as nicely pointed out above.

**Comment by fredrikekre** [comment] 2018-06-01 20:07
> if the function is generally understood by a layperson, it should not be removed.

How about matrix multiplication? Or solving a linear system? These are things a layeperson understand even better than `std`! Should we move `LinearAlgebra` back too?

> Moving large chunks of "basic" functionality out of Base to other packages (especially third-party packages; I'm willing to consider stdlib packages like Random and Iterators special cases, though I haven't really made up my mind as to whether this is a good thing yet) also makes the library ecosystem that much more fragile – while Pkg.add("StatsBase") isn't so much of a problem for an end user, it introduces a dependence fragility on any libraries that need a function like std now, which then propagates to other libraries / end users.

I thought the plan was that `StatsBase` will be a stdlib (perhaps named `Statistics`?). It just felt unnecessary to move `StatsBase` into this repo, only to move it out soon again.

**Comment by sbromberger** [comment] 2018-06-01 20:11
> How about matrix multiplication? 

Matrix multiplication is in stdlib, which is "close enough to Base" right now, I guess. I'm still not really sold on "small base, large stdlib" but as long as the functionality is being distributed via a standard Julia install, I guess it's better than going third-party.

> I thought the plan was that StatsBase will be a stdlib (perhaps named Statistics?). 

That would perhaps change things somewhat, but currently, it's not that way, and in order to use `std` in 0.7, we now have to rely on a third-party package. That doesn't seem right.



Or solving a linear system?

**Comment by StefanKarpinski** [comment] 2018-06-01 20:14
Yes, the plan is to move `StatsBase` to `stdlib/Statistics`. I had proposed moving these functions into a new `stdlib/Statistics` module which would ship with Julia, of course, and then move the appropriate parts of `StatsBase` later but people preferred doing it this way.

**Comment by sbromberger** [comment] 2018-06-01 20:15
@StefanKarpinski until that's done, can we please keep `std` (and any others) in Base?

**Comment by StefanKarpinski** [comment] 2018-06-01 20:16
No, because we can't move things out of Base later but we can move things into `stdlib` later.

**Comment by sbromberger** [comment] 2018-06-01 20:17
so until then the burden falls on the library developers to change where they source their functions from? That seems ... wrong, somehow.

**Comment by ararslan** [comment] 2018-06-01 20:20
Why do these need to be removed from Base at all?

**Comment by StefanKarpinski** [comment] 2018-06-01 21:03
We already had this discussion and came to a pretty clear consensus at the time, I'm not inclined to rehash the whole thing.

**Comment by ararslan** [comment] 2018-06-01 21:11
Seems like there's fairly broad support now for undoing it.

**Comment by ararslan** [comment] 2018-06-01 21:15
PR open to revert the change. #27375

**Comment by ararslan** [comment] 2018-06-14 18:45
Here's what I would suggest:

* Return standard deviation to Base as `stddev`
* Return variance to Base as `variance`
* Leave the rest where they currently are in StatsBase

**Comment by StefanKarpinski** [comment] 2018-06-14 18:46
Yes, I'm 100% on board with that. Can you make a PR?

**Comment by ararslan** [comment] 2018-06-14 18:48
Yep, can do.

**Comment by JeffBezanson** [comment] 2018-06-14 20:47
So before, the story was "trust me, `std` is a super special case that absolutely must be in Base". Now I see we're just casually extending that to `var` as well. W H A T E V E R

**Comment by ararslan** [comment] 2018-06-14 20:55
...they're basically the same thing though, so it would be weird to split them

**Comment by andreasnoack** [comment] 2018-06-14 21:06
I agree with @ararslan here. It's either both or none.

**Comment by Nosferican** [comment] 2018-06-15 13:27
From a developer/maintainer it is just a mess to have code all over the place due to lay-man definitions (which really is more field-based than anything). The original `base/statistics` had the relevant code all together and doing these splits will make it hard to look up code (a huge component in transparency for reproducibility, security, etc.). I would be very happy with taking these out of base and just a robust `stdlib/Statistics`. Personally, I can't wait for most `stdlib` to move out, but other compromises could include (loading certain `stdlib` by default or very easy setting to accomplish this (e.g., R provides several ways to do this) or have easily customizable distributions (choose the packages or ecosystems you want and get a custom download/image)... Not sure if it has to be managed by Julialang, but could be third-party as long as there is a way to easily to accomplish this.

**Comment by ViralBShah** [comment] 2018-06-25 20:39
Are we still going to try to do something here, with the beta tagged? This issue is still on the milestone, so perhaps it is ok to try make this change. I am personally ok with `stddev` and `variance`.

**Comment by ararslan** [comment] 2018-06-25 20:51
Since they're already removed from Base, it would be non-breaking to put them back, regardless of the name, which means it can happen any time. That said, if we're going to do this, I think we should try to do it for 0.7. I haven't moved forward with this change as there doesn't appear to be broad agreement over the names `stddev` and `variance`.

**Comment by Datseris** [comment] 2018-06-26 20:01
Wow I am thoroughly astonished by reading this post!!! I had no idea that such a basic thing would be removed!

```julia
julia> MathConstants.eulergamma
γ = 0.5772156649015...

julia> std(rand(1000))
ERROR: std has been moved to the package StatsBase.jl.
Run `Pkg.add("StatsBase")` to install it, restart Julia,
and then run `using StatsBase` to load it.
```
So, this means that "euler gamma" is much more common and used more often than the standard deviation? I wouldn't think so.

**Comment by Nosferican** [comment] 2018-06-26 20:13
`γ` is not in `Base`. It is in a package just like `std`. You would be doing,
```
using MathConstants: γ
γ
```
or
```
using StatsBase: std
std(rand(1e3))
```

**Comment by Datseris** [comment] 2018-06-26 20:16
Yes that point was clarified to me. But I also should clarify that using `γ` in a scientific development context is equivalent to having a dependency on `julia 0.7`, is it not? Since they come together, what difference does it make for the end user? Anyway, I am sorry this is off-topic I don't want to polute the issue with irrelevant stuff. I was just shocked that such a basic thing was considered less important than the euler constant.

**Comment by ViralBShah** [comment] 2018-06-27 02:40
@sbromberger I think it would be good to mention or at least refer to your personal reasons for not wanting external repositories, in order to provide the full background to folks reading this.

Also, for other discussion in this thread, it doesn't help bringing up examples of other stuff and comparing if feature x is more widely used than `std`. If something is better maintained elsewhere, or is not reasonably commonly used functionality, please make an independent case for it and we can figure out the right place for it.

@ararslan I do agree we should do it for 0.7 and `stddev` and `variance` are consistent with our general naming conventions. It's not a good idea to take up 3 letter names.

**Comment by sbromberger** [comment] 2018-06-27 04:18
> I think it would be good to mention or at least refer to your personal reasons for not wanting external repositories, in order to provide the full background to folks reading this.

Sorry, @ViralBShah. I'm all talked about about the larger issue – most of the core team is probably sick of hearing from me by now – and we've worked around this one by removing our use of `std`. I'd rather not rehash the specific situation I'm in, but I hope you'll indulge me anyway.

Two things I'd like to put out there for consideration:

1) The argument that "it's common enough and small enough that everyone's going to have it installed anyway" is dangerous for two reasons: first, it makes the edge cases that don't / can't follow this convention that much more difficult to satisfy AND more prevalent, and second, it increases the overall fragility of the ecosystem: when everyone's depending on a common set of third-party utilities, then you've got what is essentially a "core install" made up of things that can change at the whim of devs who might not share the same commitment to stability or multi-use (see below) as the language core team. (This is not to disparage other devs; it's just the way it is.) My opinion is that if a function is "common enough" that everyone should have it installed anyway, then it should at a minimum be in stdlib.

2) It would be great if we could give some thought to separating data structures from functions that commonly operate on those data structures. As an example, [there are lots of things one can do with sparse matrices other than perform linear algebra on them](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl/blob/ee3bf53d9f026b06d0f56b203e7f4611c1d37d76/src/simpleweightedgraph.jl#L8-L10). Moving the data structures into a package that is domain specific (like linear algebra) ignores these use cases at the expense of added complexity for those applications that don't treat the structures the way that others do. Continuing the example, in a language like Julia, it's easy and natural for people to place an emphasis on linear algebra. There are those of us who see the language as more than just a fast way to perform LA operations, and the talk of moving sparse matrices to a package primarily focused on linear algebra really makes it feel like we're second-class citizens in this language. At least when sparse matrices are in Base, I can feel some assurance that someone will understand the non-traditional use cases.

Finally (I promise), it seems as if the bulk of the development work is not on the data structures themselves; rather, it's on optimizing functions that operate on them. That is, `SparseMatrixCSC` [has not been significantly changed in 3 years](https://github.com/JuliaLang/julia/blame/d0e0e2341987b5b7955632c02a99af12a16c7f1e/stdlib/SparseArrays/src/sparsematrix.jl#L8-L34). The argument that we need to move things out to third party packages to improve our ability to make quick changes falls flat here when we're talking about the data structure.

Thanks for the opportunity to weigh in, and I apologize both for not directly answering your question, and for the length of my (non-)response.

**Comment by JeffBezanson** [comment] 2018-06-27 04:42
I'd like to second Viral's point that it doesn't help to point to other things in Base like eulergamma. It's quite likely a bunch of other stuff should be removed too! When the `stdlib` directory was first created, initially around 2 functions moved out of Base. One might have argued "What? Are you saying these are the two least important functions in Base that must be removed, while everything else gets to stay?" No, of course not --- pretty soon stdlib had ~30 packages.

I'll also point out that my original proposal was to move the functions to a stdlib package. In light of @sbromberger 's situation we should reconsider that --- we didn't think stdlib vs. external StatsBase was such a big difference, but apparently in some environments it is.

I like the point about separating data structures and functions; julia's design makes that especially easy and natural (though apparently some people call it type piracy :) ).

**Comment by Datseris** [comment] 2018-06-27 17:01
> I'd like to second Viral's point that it doesn't help to point to other things in Base like eulergamma. 

You are right, I see the flaw in my example. Of course  I didn't state it as the "absolute argument against the change", but only to get a point across.

**Comment by Sacha0** [comment] 2018-06-27 17:40
> That is, `SparseMatrixCSC` has not significantly changed in at least 3 years. The argument that we need to move things out to third party packages to improve our ability to make quick changes falls flat here when we're talking about the data structure.

To note, several parties have long had in mind an overhaul of the sparse data structures. That those data structures have not changed in the last three years reflects lack of developer bandwidth rather than lack of utility in being able to rapidly iterate when developer bandwidth exists :). Best!

**Comment by ViralBShah** [comment] 2018-06-28 16:01
There is quite a bit of sparse matrix experimentation outside of Base that people have done, and having something in Base has also deterred others from trying alternate ideas (because it would be so difficult to get anyone to consider using them).

**Comment by JeffBezanson** [comment] 2018-06-29 04:45
Resolved by #27834

**Closed by JeffBezanson** 2018-06-29 04:45 UTC
Labels: maths, triage

**Comment by alanedelman** [comment] 2020-07-28 16:15
not a tutorial goes by that `mean` , `median` and `std` is missed
the argument is not only that's known by a lay person (a fifth grader?)
it's something that shows up for teachers analyzing their class grade data
(which is way more common than general statistics analysis),

Can we please, please, please get these three functions in base?

**Comment by alanedelman** [comment] 2021-07-21 14:11
What would it take to get these three back into base?

**Comment by andreasnoack** [comment] 2021-07-21 14:53
The conclusion here was to put these in the standard library `Statistics`. I think it's unlikely that they'll return to `Base`.

**Comment by Nosferican** [comment] 2021-07-21 17:33
I think the answer is more along the willpower and making a compelling case enough to convince the core team to revert the decision. That would probably be the biggest force needed relative to the technical aspect. I am sided with the latest determination of moving those to the stdlib. To revisit the decision, I would say it would require a documented stable pattern of issues for it (e.g., soft-scope decision).

**Comment by quinnj** [comment] 2021-07-21 17:41
I don't think I've seen a compelling argument to move these functions from `Statistics` stdlib back to Base. For users, it's literally typing `using Statistics` and then using the functions. This is standard in every language I'm aware of out there (adding imports for non-core functionality you're using).

On the other hand, I think it'd be a better use of developer time/effort to work on allowing stdlibs to upgrade separately from the rest of Base release process. Then we can work on consolidating functionality from StatsBase.jl and other "core" statistics packages to the `Statistics` stdlib and provide even more useful stats functionality in a very easy/stable/"blessed" way to users.

**Comment by catawbasam** [comment] 2021-07-21 19:14
Hi Jacob,
Thank you for all your contributions to Julia.

re "This is standard in every language I'm aware of out there (adding
imports for non-core functionality you're using)." : this begs the question
of what should be considered core functionality.  For a numerically
oriented language like Julia, there is a sound argument that mean(),
median(), and std() should be considered core.  The designers of R and
matlab did treat their analogous functions in that way.

Also, while I'm not usually a big fan of argument from authority, I do
think a request by Alan Edelman should be given particular weight.  As a
co-founder of the language, he is in a special position to understand what
ought to be considered core in Julia.
regards,
Keith

**Comment by alanedelman** [comment] 2021-07-22 09:53
My argument is based primarily on around 35 years of teaching students.  While functions could
be based on usage patterns, technical categorization, or frequency, psychology plays the biggest
role.  Around the world, mean and median are learned at a very very young age.  Later students take
tests, and scores take on an excessive importance to them, and they will hear about std.  Are these
technically statistics, sure?  But lets take +,-,etc out of base and let's require 
`using BasisArithmetic`

My argument is that students learn these three sometimes before they even learn the word "statistics"
(well mean and median anyway) and I've seen student after student just get angry over these three functions.

(I'm also not a big fan of argument from authority -- but perhaps argument from extensive consumer experience
is more compelling, in this case the consumers are the students I teach.)

**Comment by oscardssmith** [comment] 2021-07-22 13:17
We could always re-triage this...

**Comment by LilithHafner** [comment] 2023-03-02 03:13
I'm neutral on this, but I think the current status is "not planned" rather than "completed"
