### ISSUE TITLE
forward declaration of types

### ISSUE THREAD

**Issue by kuldeepdhaka** [JuliaLang/julia#12116] opened 2015-07-11 15:16 UTC
```julia
type Dev
        child::Ptr{Mod}
end
 
type Mod
        parent::Ptr{Dev}
end
```
results: "ERROR: Mod not defined"

in c, i can do
`typedef struct Mod Mod;`
and use `Mod *my_mod` as opque type (until define `Mod`)

**Comment by johnmyleswhite** [comment] 2015-07-11 15:18
I would imagine this is only possible for C because it's always statically compiled, so the compiler is essentially doing whole program analysis when allowing this sort of thing.

**Comment by ivarne** [comment] 2015-07-11 17:59
Duplicate of https://github.com/JuliaLang/julia/issues/269?

**Closed by ivarne** 2015-07-11 17:59 UTC

**Comment by kmsquire** [comment] 2015-07-11 19:56
Workaround:

```julia
abstract AbstractMod
type Dev{T <: AbstractMod}
        child::Ptr{T}
end

type Mod <: AbstractMod
        parent::Ptr{Dev}
end
```

**Comment by kuldeepdhaka** [comment] 2015-07-12 16:15
@kmsquire thanks for the tip.
