### ISSUE TITLE
crash in vecelement test

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#23796] opened 2017-09-20 18:31 UTC
I've seen this many times, e.g.

https://travis-ci.org/JuliaLang/julia/jobs/277518263
https://circleci.com/gh/JuliaLang/julia/3693

Seems to be intermittent, and I have no idea whether it's actually related to VecElements, but is a definite pattern.

**Comment by yuyichao** [comment] 2017-09-20 18:42
I think this just https://github.com/JuliaLang/julia/issues/21918

**Comment by JeffBezanson** [comment] 2017-09-20 18:44
Was the fix for that issue incomplete?

**Comment by yuyichao** [comment] 2017-09-20 18:45
Either that or it regressed in special case. I'm not able to reproduce it but I've seen alignment of 32 specified in llvm IR. The fix is mostly a workaround to begin with.

**Comment by yuyichao** [comment] 2017-09-20 18:46
> a workaround

-> There are a few linked PR for the more correct fix.

**Comment by vchuravy** [comment] 2017-09-20 23:59
If there are still alignments of 32 present than my fix was incomplete. I can rebase #21959 but I will probably need help to make sure that it doesn't lead to a performance regression since it is quite hot code.

**Comment by vchuravy** [comment] 2017-09-27 18:45
Should be fixed by #23883

**Closed by vchuravy** 2017-09-27 18:45 UTC
Labels: bug, priority, test
