### ISSUE TITLE
local variables in a let block aren't optimized?

### ISSUE THREAD

**Issue by colinfang** [JuliaLang/julia#16507] opened 2016-05-22 01:31 UTC
```julia
x = [
    1 2 3 4 5 6;
    2 3 4 5 6 7;
]
const y = x

let
    local a = x
    @time for i in 1:10^4 reshape(a, 12) end
end
0.002322 seconds (20.00 k allocations: 781.250 KB)

let
    local a = y
    @time for i in 1:10^4 reshape(a, 12) end
end
0.000344 seconds (10.00 k allocations: 625.000 KB)
```

It seems the type of `a` isn't inferred.

**Comment by JeffBezanson** [comment] 2016-05-22 01:41
Duplicate of #524 and #8870. This is entirely because of `x`, and not related to locals or let blocks.

**Closed** 2016-05-22 02:39 UTC
