### ISSUE TITLE
failure to build on Windows (Cygwin)

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaLang/julia#18372] opened 2016-09-06 10:59 UTC
Using freshly cloned master.  My previous successful build was at 8481fec.
```
HAW7L0605$ make VERBOSE=1
make[1]: Entering directory '/home/s2sajs/julia-master/deps'
mkdir -p /home/s2sajs/julia-master/usr
/usr/bin/tar xzf /home/s2sajs/julia-master/usr-staging/dsfmt-2.2.3.tgz -C /home/s2sajs/julia-master/usr
/usr/bin/tar: ./bin: Cannot open: File exists
/usr/bin/tar: Exiting with failure status due to previous errors
/home/s2sajs/julia-master/deps/dsfmt.mk:43: recipe for target '/home/s2sajs/julia-master/usr/manifest/dsfmt' failed
make[1]: *** [/home/s2sajs/julia-master/usr/manifest/dsfmt] Error 2
make[1]: Leaving directory '/home/s2sajs/julia-master/deps'
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

**Comment by tkelman** [comment] 2016-09-06 11:13
caused by https://github.com/JuliaLang/julia/pull/17859 which was merged without sufficient testing

**Closed** 2016-09-06 20:36 UTC
Labels: bug, build, windows

**Comment by josefsachsconning** [comment] 2016-09-07 08:15
At 442af7b I still have the same problem, but at a slightly different place.
```
HAW7L0605$ make VERBOSE=1
make[1]: Entering directory '/home/s2sajs/julia-master/deps'
mkdir -p /home/s2sajs/julia-master/usr
/usr/bin/tar xzf /home/s2sajs/julia-master/usr-staging/mbedtls-2.3.0.tgz -C /home/s2sajs/julia-master/usr
/usr/bin/tar: ./bin: Cannot open: File exists
/usr/bin/tar: Exiting with failure status due to previous errors
/home/s2sajs/julia-master/deps/mbedtls.mk:65: recipe for target '/home/s2sajs/julia-master/usr/manifest/mbedtls' failed
make[1]: *** [/home/s2sajs/julia-master/usr/manifest/mbedtls] Error 2
make[1]: Leaving directory '/home/s2sajs/julia-master/deps'
Makefile:81: recipe for target 'julia-deps' failed
make: *** [julia-deps] Error 2
```

**Comment by tkelman** [comment] 2016-09-07 11:24
may need to `rm -rf usr-staging usr` ?

**Comment by josefsachsconning** [comment] 2016-09-07 11:28
That was again with a freshly cloned master, but I'm running `make` after `rm -rf usr-staging usr` now.

**Comment by tkelman** [comment] 2016-09-07 11:31
hm. I'd think that should have been fixed by https://github.com/JuliaLang/julia/pull/18388 but I could be wrong.

**Comment by josefsachsconning** [comment] 2016-09-07 11:51
That build succeeded.  Trying once again with a fresh clone.

**Comment by josefsachsconning** [comment] 2016-09-07 15:36
This time, building from a fresh clone of master succeeded.  I don't know what happened last time.  I'm satisfied.
