### ISSUE TITLE
Importing from stdlib modules using the deprecated name gives an error

### ISSUE THREAD

**Issue by c42f** [JuliaLang/julia#24832] opened 2017-11-29 05:01 UTC
I'd expect to be able to import with a depwarn, but get an error instead:

```julia
julia> import Base.Test: record
WARNING: Base.Test is deprecated, run `using Test` instead.
  likely near no file:0
ERROR: invalid import path: "Test" does not name a module
```

**Comment by ararslan** [comment] 2017-11-29 05:05
Related to (possibly duplicate of) #24488

**Comment by vchuravy** [comment] 2017-11-29 13:30
definitly a dup and I might have a fix for this.

**Closed by vchuravy** 2017-11-29 13:30 UTC

**Comment by KristofferC** [comment] 2017-11-29 13:42
Fixing this would be incredibly helpful in reducing breakage.

**Comment by vchuravy** [comment] 2018-01-25 02:58
This is now properly fixed even for exported functions and submodules after #25692
