### ISSUE TITLE
Performance of mapslices

### ISSUE THREAD

**Issue by alhirzel** [JuliaLang/julia#35009] opened 2020-03-04 23:39 UTC
Is this confusing performance a bug? Version 1.3.1

```julia
img = rand(512,512,16)
@time mapslices(sum, img, dims=[3])
@time sum([img[:,:,i] for i=1:size(img)[3]])
```

```
  0.423263 seconds (2.89 M allocations: 74.065 MiB, 2.89% gc time)
  0.054033 seconds (53.06 k allocations: 64.729 MiB)
```

**Comment by johnnychen94** [comment] 2020-03-05 00:59
`mapslice` seems slower, but in this specific case, `sum(img; dims=3)` is the best choice to me.

**Comment by haampie** [comment] 2020-03-05 21:05
`mapslices` is unfortunately very type unstable. There's open issues about this already.

If you need a fast mapslices try JuliennedArrays.jl:

```
using JuliennedArrays

map(sum, JuliennedArrays.Slices(img, 3))
```

**Comment by mbauman** [comment] 2020-03-05 21:21
Duplicate of #26868

**Closed by mbauman** 2020-03-05 21:21 UTC
