### ISSUE TITLE
`all`/`any` return the wrong result when reducing over infinite iterators

### ISSUE THREAD

**Issue by Seelengrab** [JuliaLang/julia#47664] opened 2022-11-22 12:11 UTC
This is a bit of an odd one:

```julia
julia> f() = any(isone, Iterators.repeated(0))
```

should clearly return `false` or loop infinitely, yet:

```julia
julia> @code_typed f()
CodeInfo(
1 ─     return true
) => Bool
```

The inverse happens with `all`:

```julia
julia> f() = all(iszero, Iterators.repeated(0))
f (generic function with 1 method)

julia> @code_lowered f()
CodeInfo(
1 ─ %1 = Main.iszero
│   %2 = Base.Iterators.repeated
│   %3 = (%2)(0)
│   %4 = Main.all(%1, %3)
└──      return %4
)

julia> @code_typed f()
CodeInfo(
1 ─     return false
) => Bool
```

which should (if anything) return `true`.

Seems like an issue in inference:

```julia
julia> @code_warntype f()
MethodInstance for f()
  from f() @ Main REPL[1]:1
Arguments
  #self#::Core.Const(f)
Body::Bool
1 ─ %1 = Main.iszero::Core.Const(iszero)
│   %2 = Base.getproperty(Main.Iterators, :repeated)::Core.Const(Base.Iterators.repeated)
│   %3 = (%2)(0)::Core.Const(Base.Iterators.Repeated{Int64}(0))
│   %4 = Main.all(%1, %3)::Core.Const(false)
└──      return %4
```

**Comment by KristofferC** [comment] 2022-11-22 12:21
Ref https://github.com/JuliaLang/julia/issues/40009

**Comment by JeffBezanson** [comment] 2022-11-22 19:59
Yes, this is a duplicate of #40009. I do really think we should change it, and Keno seems to agree.

**Closed by JeffBezanson** 2022-11-22 19:59 UTC
Labels: design, iteration
