### ISSUE TITLE
realpath gives wrong path for network drives on windows with 1.2

### ISSUE THREAD

**Issue by sebastianpech** [JuliaLang/julia#33127] opened 2019-08-31 09:57 UTC
See also discussion over at JuliaLang/Pkg.jl#1328 and JuliaDynamics/DrWatson.jl#82

For network drives `realpath` returns a wrong path.
```
julia> realpath("Z://")
"UNC\\Mac\\Home\\"

julia> realpath("C://")
"C:\\"
```

Tested on:
```
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
It's this call:
```
 349 len = ccall(:GetFinalPathNameByHandleW, stdcall, UInt32, (Int, Ptr{UInt16}, UInt32, UInt32),
 350                              h, buf, (oldlen=len)-1, 0x0)
```
with `buf` being
```
1|julia> transcode(String,buf)
"\\\\?\\UNC\\Mac\\Home\\\ .... garbage due to length not being corrected"
```

**Comment by fredrikekre** [comment] 2019-08-31 12:55
Maybe caused by https://github.com/JuliaLang/julia/pull/30611 ? cc @stevengj

**Comment by musm** [comment] 2019-08-31 18:05
fixed by https://github.com/JuliaLang/julia/pull/33116

**Comment by stevengj** [comment] 2019-08-31 21:25
#30611 uses the [same `GetFinalPathNameByHandleW` as `uv_fs_realpath`](https://github.com/libuv/libuv/blob/813264add0c3b5fba782e4bb849bffad4701ecf6/src/win/fs.c#L2488-L2493), but libuv does [some post-processing of UNC paths](https://github.com/libuv/libuv/blob/813264add0c3b5fba782e4bb849bffad4701ecf6/src/win/fs.c#L2495-L2511) that we didn't do.

Changing to `uv_fs_realpath` seems like the best choice in any case.

**Closed** 2019-09-04 16:45 UTC
Labels: bug, filesystem, windows
