### ISSUE TITLE
`unique` not working for vector of tuple types

### ISSUE THREAD

**Issue by manuelbb-upb** [JuliaLang/julia#48777] opened 2023-02-24 12:08 UTC
According to the [docs](https://docs.julialang.org/en/v1/base/collections/#Base.unique), `unique` should filter based on `isequal`.
This does not work for iterable objects of tuple types:
```julia
T1 = Tuple{T} where T<:Real
T2 = Tuple{Real}

isequal(T1, T2) == true
allequal([T1, T2]) == true
unique([T1,T2]) == [T1, T2] # would expect singleton [T1] or [T2] here
allunique([T1, T2]) == true # also seems contradictory
```

**versioninfo**
```
Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 4 on 8 virtual cores
Environment:
  JULIA_NUM_THREADS = 4
  LD_PRELOAD = /usr/lib/x86_64-linux-gnu/libstdc++.so.6
```
Downloaded the latest binary for testing.

**Comment by sostock** [comment] 2023-02-24 12:53
The problem is that `T1` and `T2` have different hashes, which should not be the case if `isequal(T1, T2)`:
```julia
julia> isequal(T1, T2)
true

julia> hash(T1)
0x290a54c217b84587

julia> hash(T2)
0x0953949a008acc84
```
(these hashes are from Julia 1.8.5)

**Comment by Seelengrab** [comment] 2023-02-24 12:55
This is not a bug in `unique`, but in `hash` or `isequal` of a type (seemingly):

```
julia> isequal(T1, T2)
true

julia> hash(T1) == hash(T2)
false
```

These two should always agree, but don't here.

**Comment by manuelbb-upb** [comment] 2023-02-24 12:56
makes sense. Should I change the title of the issue?

**Comment by manuelbb-upb** [comment] 2023-02-24 13:06
From what I see, `hash(T1)` falls back to `Base.hash_uint(-objectid(T1))`.
The docs for `objectid` say that `x===y` implies `objectid(x)==objectid(y)`.
Thus, if the above hashing behavior is consistent for all types of types, having `isequal` fall back to `===` for types should resolve the issue...

**Comment by manuelbb-upb** [comment] 2023-02-24 14:01
There already is [`@test i != j || (a === b)`](https://github.com/JuliaLang/julia/blob/b5482c82d486aaa68939871eb1d1bc71bb421096/test/hashing.jl#L241) as a test for #5849. This should not test successfully if expressions for Tuple Types are added to `vals_expr`.
For types, `isequal` falls back to `==` which has a special method [here](https://github.com/JuliaLang/julia/blob/b5482c82d486aaa68939871eb1d1bc71bb421096/base/operators.jl#L243).

@JeffBezanson does it seem sensible to overload `isequal` to redirect to `===` for types?

**Comment by fredcallaway** [comment] 2024-03-14 16:14
I just ran into a similar issue for a custom struct. I think it's a documentation bug. The docs of `unique` should clarify that equality is determined by hash so that end users know they need to override both `hash` and `isequal`. I realize that the docs for `isequal` state that `isequal` should imply `hash` equality but should we expect the user to know/remember this?

**Comment by gbaraldi** [comment] 2024-03-15 14:27
So this specific example here is fixed, but one may be able to construct something that fails this. However #53109 seems to show the issue a bit more clearly (the fact that `hash` may disagree with `==` for types) so i'm closing this one for that one

**Closed by gbaraldi** 2024-03-15 14:27 UTC
