### ISSUE TITLE
Strange behaviour of Bool variables in Julia 1.0 and 0.7

### ISSUE THREAD

**Issue by tanhevg** [JuliaLang/julia#29805] opened 2018-10-25 19:30 UTC
I am observing a weird behaviour in Julia 1.0. I have a boolean variable, which is set to `true`. The problem is, its negation is also `true` ... :-\

The code is as follows:

```julia    
my_var = my_func(....)
println("my_var ", my_var, 
    ' ', !my_var,
    ' ', bitstring(my_var),
    ' ', typeof(my_var))
```

This prints

    my_var true true 00000000 Bool

This code is located inside a package that I am developing. `my_func` has two methods, both of which return a `Bool`. This problem manifests itself only when one of the methods is used, the other one works fine. Both methods of `my_func` go like this:

```julia    
function my_func(arg::SomeType) # or arg::SomeOtherType
    .... # various branches of this code may return true or false
    return true # this statement is reached on the path that triggers the bug
end
```

This works the same in 0.7 and 1.0. The problem is reproduced every time I run that bit of code. There is no such problem in 0.6. 

```
julia> versioninfo()
Julia Version 0.7.0
Commit a4cb80f3ed (2018-08-08 06:46 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)
Environment:
  JULIA = /project/soft/linux64/src/julia-0.7.0
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 12
```

**Comment by KristofferC** [comment] 2018-10-25 19:35
It would be very helpful to be able to reproduce this. Is there anyway to provide enough code that it can be run?

**Comment by tanhevg** [comment] 2018-10-25 19:44
https://github.com/tanhevg/GpABC.jl
branch ev/julia_1_0
The offending code is in src/abc/smc.jl, lines 392-400
To run it, launch the script in examples/smc-abc-script.jl

**Comment by tanhevg** [comment] 2018-10-26 13:07
I have worked around the issue in my code. The version where the bug is reproduced is tagged `tags/julia_lang_issue_29805`

**Comment by ViralBShah** [comment] 2022-09-05 23:49
Is it possible to have an MWE here to reproduce? I am closing since this is quite old, but please reopen if still an issue.

**Closed by ViralBShah** 2022-09-05 23:49 UTC
Labels: bug
