### ISSUE TITLE
broadcasted ops are 2x slower on Symmetric

### ISSUE THREAD

**Issue by oxinabox** [JuliaLang/julia#39903] opened 2021-03-03 17:35 UTC
Broadcasting a unitary operation like `exp` against a `Symmetric` matrix should be almost 2x faster since it only needs to process 1/2 the elements.
But instead is is  almost 2x slower.
(So like 4x slower than expected)

```julia
julia> using LinearAlgebra

julia> using BenchmarkTools

julia> const data = Matrix(Symmetric(randn(2_000, 2_000)));

julia> @benchmark exp.($data)
BenchmarkTools.Trial:
  memory estimate:  30.52 MiB
  allocs estimate:  2
  --------------
  minimum time:     23.570 ms (0.00% GC)
  median time:      24.860 ms (0.00% GC)
  mean time:        27.109 ms (9.95% GC)
  maximum time:     98.043 ms (70.41% GC)
  --------------
  samples:          185
  evals/sample:     1

julia> @benchmark exp.($(Symmetric(data)))
BenchmarkTools.Trial:
  memory estimate:  30.52 MiB
  allocs estimate:  2
  --------------
  minimum time:     37.712 ms (0.00% GC)
  median time:      38.774 ms (0.00% GC)
  mean time:        41.895 ms (7.72% GC)
  maximum time:     115.427 ms (59.57% GC)
  --------------
  samples:          120
  evals/sample:     1
```

**Comment by mbauman** [comment] 2021-03-05 18:49
half-ways duplicate of #32624

**Comment by mbauman** [comment] 2021-03-05 19:00
Without looking, I'd guess the branch in `getindex` to always push indices into one side or the other is foiling simd.  Not sure if there's a solution that wouldn't also be a solution to #32624.

**Closed by mbauman** 2021-03-05 19:00 UTC
Labels: broadcast, linear algebra, performance
