### ISSUE TITLE
RemoteException not re-thrown by pmap()

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/julia#12908] opened 2015-09-01 22:18 UTC
```julia
@everywhere function do_work(i)
    r = [1,2,3][i]
    println(r)
    return r
end

for r in pmap(do_work, [3,2,1,0])
    println("pmap got result")
    println(typeof(r))
end
```

The `pmap()` call above returns a RemoteException object in the result array instead of re-throwing it.

The output is:

```
./julia -p4 test.jl
	From worker 3:	2
	From worker 4:	1
	From worker 2:	3
pmap got result
Int64
pmap got result
Int64
pmap got result
Int64
pmap got result
RemoteException
```

Changing `pmap()` to `map()` results in BoundsError as expected.

**Comment by simonster** [comment] 2015-09-01 23:03
Related to/dup of #7808. Also IMO `err_stop=true` and rethrowing the error should be the default behavior for `pmap`.

**Comment by samoconnor** [comment] 2015-09-01 23:50
As far as I can tell `err_stop=true` is just a performance optimisation to save time when an error occurs.

However, re-throwing the exception (after re-tries) seems like a must unless the documentation clearly says that `pmap()` returns exceptions in the output collection.

**Comment by simonster** [comment] 2015-09-02 00:03
The problem is that there's no way to get the incomplete output of `pmap` if it throws an exception. If you set `err_stop=err_rety=false`, you clearly want the output even if it's incomplete. (With the defaults `err_stop=false, err_retry=true` it's a little less clear what you want.) The behavior should certainly be documented, but I imagine there are cases where it's desirable to return the exceptions instead of throwing them.

**Comment by samoconnor** [comment] 2015-09-03 04:13
To me it seems very clear: a function should either return a "complete" result or throw an exception.
A function that returns exception objects in-line with an output collection seems odd to me.

If "incomplete output of pmap" is useful in some particular application, that application could just do:

```julia
pmap([1,2,3]) do i
    try
        [1,2][i]
    catch e
        return e
    end
end
```

**Comment by simonster** [comment] 2015-09-03 04:31
But then failures never get retried with `err_retry=true`, because you don't throw an error.

**Comment by malmaud** [comment] 2015-10-14 08:01
This is definitely an issue, but closing in favor of the earlier https://github.com/JuliaLang/julia/issues/7808.

**Closed by malmaud** 2015-10-14 08:01 UTC
Labels: error handling, parallel
