### ISSUE TITLE
Wrong @sprintf output with # flag

### ISSUE THREAD

**Issue by mwlidar** [JuliaLang/julia#43129] opened 2021-11-18 14:03 UTC
```
julia> @sprintf("%#.3g", 100.0 - eps(100.0))
"1000"

julia> @sprintf("%#.3g", 100.0)
"100."
```

This is with Julia 1.6.3

**Comment by inkydragon** [comment] 2022-08-11 02:43
Test code 
```jl
versioninfo()
using Printf
Printf.format(Printf.Format("%#.3g"), 100.0 - eps(100.0))
```

- ✔️ 1.6.0 (2021-03-24) f9720dc2eb
- ✔️ 1.6.1 (2021-04-23) 6aaedecc44
- ? ecc3f1dc955dfb3c3ecd9d68570f7a3d3ef6bee4
- ? [make Printf's general format C11 compliant](https://github.com/JuliaLang/julia/commit/4ab8c79d447218bc24380afe82ee141c4ead4fa4) 
    From the files involved, my guess is that this commit introduced the regression
- ❌ 1.6.2 (2021-07-14) 1b93d53fc4
- ❌ 1.7.3 (2022-05-06) 742b9abb4d

**Comment by KristofferC** [comment] 2022-08-11 04:45
Why was this added to the 1.8 milestone?

**Comment by vtjnash** [comment] 2022-08-11 04:51
Showing the wrong answer seems quite a bad regression

**Comment by KristofferC** [comment] 2022-08-11 13:30
Yes, but not vs 1.7. If all supported Julia versions are released with this bug, we surely can release 1.8 with it as well.

**Comment by gitboy16** [comment] 2022-08-25 09:25
Maybe worth adding the backport 1.8 flag on this one?

**Comment by gitboy16** [comment] 2023-03-23 06:37
Completely agree with @vtjnash , this is a bad regression. I think it should have fixed long time ago. Could it be that it has been forgotten because it is not on any milestone?

**Comment by KristofferC** [comment] 2023-03-23 07:17
> I think it should have fixed long time ago

It's just waiting for an unsung hero to roll up their sleeves and get to work. Maybe you could be that hero?

**Comment by gitboy16** [comment] 2023-03-23 08:25
I really wish I had enough knowledge to do it.
In any case don't you think it should be add on a milestone (1.6 , 1.8 or 1.9) not to be forgotten?

**Comment by KristofferC** [comment] 2023-09-01 07:38
Been an issue since 1.6 so removing from milestone.

**Comment by gitboy16** [comment] 2023-09-01 08:17
It seems it was an issue since 1.6.2. It was working in 1.6.0 and 1.6.1 hence the regression/bug flags I suppose. It should have been fixed long time ago I think.

**Closed** 2023-09-12 16:23 UTC
Labels: bug, regression, display and printing, forget me not, backport 1.6, backport 1.8
