### ISSUE TITLE
`methods(Core.OpaqueClosure)` errors

### ISSUE THREAD

**Issue by simeonschaub** [JuliaLang/julia#52043] opened 2023-11-06 10:24 UTC
```julia
julia> methods(Core.OpaqueClosure)
# 2 methods for type constructor:Error showing value of type Base.MethodList:
ERROR: "OpaqueClosure" is not defined in module Base.Experimental
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] which
    @ ./reflection.jl:1924 [inlined]
  [3] show_method_table(io::IOContext{Base.TTY}, ms::Base.MethodList, max::Int64, header::Bool)
    @ Base ./methodshow.jl:304
  [4] show_method_table
    @ Base ./methodshow.jl:290 [inlined]
  [5] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, ms::Base.MethodList)
    @ Base ./methodshow.jl:350
  [6] (::REPL.var"#57#58"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:288
  [7] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:584
  [8] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:274
  [9] display
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:293 [inlined]
 [10] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:340
 [11] #invokelatest#2
    @ ./essentials.jl:929 [inlined]
 [12] invokelatest
    @ ./essentials.jl:926 [inlined]
 [13] print_response(errio::IO, response::Any, show_value::Bool, have_color::Bool, specialdisplay::Union{Nothing, AbstractDisplay})
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:330
 [14] (::REPL.var"#59#60"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:299
 [15] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:584
 [16] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:297
 [17] (::REPL.var"#do_respond#82"{Bool, Bool, REPL.var"#95#107"{…}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:926
 [18] #invokelatest#2
    @ Base ./essentials.jl:929 [inlined]
 [19] invokelatest
    @ Base ./essentials.jl:926 [inlined]
 [20] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/LineEdit.jl:2722
 [21] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:1352
 [22] (::REPL.var"#64#70"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ~/packages/julias/julia-latest/share/julia/stdlib/v1.11/REPL/src/REPL.jl:401
Some type information was truncated. Use `show(err)` to see complete types.
```

**Comment by ararslan** [comment] 2023-11-06 22:00
Duplicate of #49403

**Comment by persinammon** [comment] 2023-11-20 08:04
Hi! I'm a new contributor btw.

I tried seeing if the indirect reference through linking through `include` was a problem, and no, didn't change the error. No idea if that's useful or not, lol

**Closed** 2023-12-22 20:21 UTC
