### ISSUE TITLE
Regression in methodshow/print_to_string

### ISSUE THREAD

**Issue by dhoegh** [JuliaLang/julia#11700] opened 2015-06-13 14:09 UTC
I have observed a regression of a factor of 2-3 between master and 0.3.8 in the following test case:

```
function test1(n)
    for i=1:n
        string(methods(max))
    end
end
test1(1)
@time test1(10000)
```

0.3.8 runs in `2.467998002 s` while master takes `7.016 s`.

**Comment by IainNZ** [comment] 2015-06-13 14:31
Isn't this function only used interactively? And isn't the difference less than a human can perceive?

**Comment by dhoegh** [comment] 2015-06-13 14:35
Yes, but I do not think the root cause is inside the methodshow but in the string conversion. I have not been able to track the exact difference down.

**Comment by dhoegh** [comment] 2015-06-13 14:52
The regression occurred between 8fc5b4e and c6d0759 where no change have been made in `methodshow.jl`, but #10380 where merged in this interval.

**Comment by KristofferC** [comment] 2015-06-13 14:59
Maybe you can test the commit before and see if it is fast again then? Or alternative just do a full fledged bisection.

**Comment by dhoegh** [comment] 2015-06-13 17:40
I can confirm that the time goes from `2.3s` to `3.7s` at 9da1662b1a37f3365d2871480e1f522058b6b64c.

**Comment by dhoegh** [comment] 2015-06-13 18:47
I have tried to track this further. The following goes from 14.7s to 20.6s post #10380 
```
function test(n)
           a=rand(300)
           for i=1:n
               Base.print_to_string(a...)
       end
end
test(100)
@time test(100000)
```

**Comment by JeffBezanson** [comment] 2015-06-14 21:36
My best guess is that this is caused by the call to jl_f_tuple used to allocate varargs tuples (https://github.com/JuliaLang/julia/blob/99391b3827b9b3139bec34b9a49b3fbcb8690154/src/codegen.cpp#L4613). It now has extra overhead for constructing the type of the tuple, and then the tuple itself. This can be fixed by constructing the type at compile time, since we usually know it.

Another possibility is that the optimization to elide varargs tuples has regressed in some cases.

**Comment by JeffBezanson** [comment] 2015-09-07 22:01
Now an additional ~5x slower, with all the time in `is_exported_from_stdlib`.

**Comment by ScottPJones** [comment] 2015-09-07 23:13
Ouch, a performance regression that large IMO may need to be treated as blocking

**Comment by mbauman** [comment] 2015-09-07 23:31
I'm on a phone so I can't measure it, but I have a hunch Jeff already fixed it: https://github.com/JuliaLang/julia/commit/c2d35bb30f86979cb7f1a410e14b3c82d871500f (thanks Jeff!)

**Comment by KristofferC** [comment] 2018-04-05 14:10
0.3.12 runs https://github.com/JuliaLang/julia/issues/11700#issuecomment-111739547 at 10 seconds, master at 11.5 seconds. Seems close enough to close.

**Closed by KristofferC** 2018-04-05 14:10 UTC
Labels: performance, regression
