### ISSUE TITLE
resize of reshaped array

### ISSUE THREAD

**Issue by chethega** [JuliaLang/julia#29283] opened 2018-09-20 12:03 UTC
```
julia> a=zeros(1,1); b = reshape(a,1); push!(b,1); b[1]=-1; a,b
([0.0], [-1.0, 1.0])
```
Expected behavior:
```
julia> push!(b,1)
ERROR: cannot resize array with shared data
```
Not really sure whether this is a bug or intended, but it is surprising and weird (I would have expected reshape to lock further resizing on either both the source and the target, or on neither).

**Comment by mbauman** [comment] 2019-09-03 16:06
Duplicate of #33143.  I know this one predates the other, but that one has the beginning of a conversation, so may as well keep things there.

**Closed by mbauman** 2019-09-03 16:06 UTC
