### ISSUE TITLE
Unreachable reached, Julia 1.2.0-rc2.0

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/julia#32607] opened 2019-07-17 05:00 UTC
```julia
julia> CartesianIndex(BigInt(1), 1)
Unreachable reached at 0x117746b26

signal (4): Illegal instruction: 4
in expression starting at REPL[4]:1
Type at ./multidimensional.jl:68
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:323
eval_stmt_value at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:362 [inlined]
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:758
jl_interpret_toplevel_thunk_callback at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:884
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x11907c70f)
unknown function (ip: 0x0)
jl_interpret_toplevel_thunk at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:893
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:815
jl_toplevel_eval_flex at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:764
jl_toplevel_eval at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:824 [inlined]
jl_toplevel_eval_in at /Users/julia/buildbot/worker/package_macos64/build/src/toplevel.c:844
eval at ./boot.jl:330
eval_user_input at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:86
run_backend at /Users/jacobquinn/.julia/packages/Revise/agmgx/src/Revise.jl:949
#75 at ./task.jl:268
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1606 [inlined]
start_task at /Users/julia/buildbot/worker/package_macos64/build/src/task.c:596
Allocations: 8132905 (Pool: 8131258; Big: 1647); GC: 18
[1]    10138 illegal hardware instruction  julia
➜  dev
```

**Comment by bkamins** [comment] 2019-07-17 11:35
On 1.3.0-DEV.542 it works OK (at least for me):
```
julia>  CartesianIndex(BigInt(1), 1)
CartesianIndex(1, 1)
```

**Comment by fredrikekre** [comment] 2019-07-17 11:57
I can reproduce this on Linux so I don't think it is related to the OS.

**Comment by vchuravy** [comment] 2019-07-17 13:02
Can't reproduce on ` Version 1.3.0-DEV.468 (2019-06-30)` Linux, so might be fixed on master?

**Comment by goggle** [comment] 2019-07-18 16:56
I can confirm this.

On `v1.2.0-rc2`:
```julia
julia> CartesianIndex(BigInt(1), 1)
Unreachable reached at 0x7fe48d9c584f

signal (4): Illegal instruction
in expression starting at REPL[1]:1
Type at ./multidimensional.jl:68
do_call at /home/alex/Projects/github/goggle/julia/src/interpreter.c:323
eval_value at /home/alex/Projects/github/goggle/julia/src/interpreter.c:411
eval_stmt_value at /home/alex/Projects/github/goggle/julia/src/interpreter.c:362 [inlined]
eval_body at /home/alex/Projects/github/goggle/julia/src/interpreter.c:754
jl_interpret_toplevel_thunk_callback at /home/alex/Projects/github/goggle/julia/src/interpreter.c:884
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fe4a77a558f)
unknown function (ip: (nil))
jl_interpret_toplevel_thunk at /home/alex/Projects/github/goggle/julia/src/interpreter.c:893
jl_toplevel_eval_flex at /home/alex/Projects/github/goggle/julia/src/toplevel.c:815
jl_toplevel_eval_flex at /home/alex/Projects/github/goggle/julia/src/toplevel.c:764
jl_toplevel_eval_in at /home/alex/Projects/github/goggle/julia/src/toplevel.c:844
eval at ./boot.jl:330
eval_user_input at /home/alex/Projects/github/goggle/julia/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:86
macro expansion at /home/alex/Projects/github/goggle/julia/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:118 [inlined]
#26 at ./task.jl:268
jl_apply at /home/alex/Projects/github/goggle/julia/src/julia.h:1606 [inlined]
start_task at /home/alex/Projects/github/goggle/julia/src/task.c:596
unknown function (ip: 0xffffffffffffffff)
Allocations: 1883706 (Pool: 1883236; Big: 470); GC: 3
```

On the current master (`1.3.0-DEV.557`):
```julia
julia> CartesianIndex(BigInt(1), 1)
CartesianIndex(1, 1)
```

Both version are build from source on a 64-bit Linux machine.

**Comment by Keno** [comment] 2019-07-20 18:15
Bisect says this got fixed with #31698.

**Comment by JeffBezanson** [comment] 2019-07-30 17:54
Bisecting in the other direction, the first bad commit was 8c445663547791e59f33f9e8d49b276332107614.

**Comment by JeffBezanson** [comment] 2019-07-31 16:32
cc @vtjnash

**Comment by vtjnash** [comment] 2019-08-02 17:04
Reduced to:
```julia
julia> typeintersect(Type{<:Tuple{Any,Vararg{Any}}}, Type{Tuple{Vararg{Any,A}}} where A)
Union{}
```
(which should have solutions for `A > 1`)

**Comment by JeffBezanson** [comment] 2019-08-02 18:31
So this was not caused by the commit pointed to by bisect, just exposed by it due to an improvement in inference.

**Closed** 2019-08-04 22:20 UTC
