### ISSUE TITLE
Optional and keyword argument interaction with `inbounds`/`propagate_inbounds`

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#56493] opened 2024-11-07 16:51 UTC
Normally, when I have a function that uses `@boundscheck` a simple `@inbounds f()` is enough.

```
function f()
     @boundscheck println("I am alive!")
     return nothing
end

f_inbounds() = @inbounds f()
f_normal() = f()
```

```
julia> f_inbounds()

julia> f_normal()
I am alive!
```

Yet when a function has default or keyword arguments this does not suffice.

```
function f_kw(;arg=3) 
    @boundscheck @show arg
    return nothing
end

f_kw_inbounds() = @inbounds f_kw()
f_kw_normal() = f_kw()
```

```
julia> f_kw_inbounds()
arg = 3

julia> f_kw_normal()
arg = 3
```

Instead `Base.@propagate_inbounds` is necessary.

```
Base.@propagate_inbounds function g_kw(;arg=3)
           @boundscheck @show arg
           return nothing
       end

g_kw_inbounds() = @inbounds g_kw()
g_kw_normal() = g_kw()
```

```
julia> g_kw_inbounds()

julia> g_kw_normal()
arg = 3
```

While this is nominally okay, it is a bit unfortunate since `propagate_inbounds` has the additional consequence of propagating the `@inbounds` annotation yet another level deeper. 

So it will propagate `@inbounds` one-level deeper than a user might originally intend. 

```
julia> explosion() = (@boundscheck return; error("explode"))
explosion (generic function with 1 method)

julia> Base.@propagate_inbounds function g_kw(;arg=3)
                         @boundscheck @show arg
                         explosion()
                     end
g_kw (generic function with 1 method)

julia> g_kw_normal()
arg = 3

julia> g_kw_inbounds()
ERROR: explode
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] explosion
   @ ./REPL[28]:1 [inlined]
 [3] #g_kw#6
   @ ./REPL[29]:3 [inlined]
 [4] g_kw
   @ ./REPL[29]:1 [inlined]
 [5] g_kw_inbounds()
   @ Main ./REPL[23]:1
 [6] top-level scope
   @ REPL[31]:1
```

As far as I know we don't have a "@noinbounds" that would block that propagation,
except for introducing a function barrier.

I quickly tried:

```
julia> @eval Base.@propagate_inbounds function g_kw(;arg=3)
                         @boundscheck @show arg
                         $(Expr(:inbounds, false))
                         explosion()
                         $(Expr(:inbounds, :pop))
                     end
g_kw (generic function with 1 method)

julia> g_kw_inbounds()
ERROR: explode
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] explosion
   @ ./REPL[28]:1 [inlined]
 [3] #g_kw#7
   @ ./REPL[32]:4 [inlined]
 [4] g_kw
   @ ./REPL[32]:1 [inlined]
 [5] g_kw_inbounds()
   @ Main ./REPL[23]:1
 [6] top-level scope
   @ REPL[33]:1
```

But sadly that doesn't work.

HT @efaulhaber for bringing this up offline.

**Comment by mbauman** [comment] 2024-11-07 16:55
Duplicate of #30411

**Closed by mbauman** 2024-11-07 16:55 UTC
