### ISSUE TITLE
--track-allocation seems to be broken on Windows

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/julia#10102] opened 2015-02-06 15:21 UTC
Not sure what's going on here – this runs but no `.mem` file appears. The same issue may affect measuring coverage (the logging logic is shared). It might be good to add some testing for this and run those tests under CI on Travis and AppVeyor.

**Comment by jakebolewski** [comment] 2015-02-06 15:22
Dupe of #9654

**Closed** 2015-02-06 15:44 UTC
Labels: windows

**Comment by tkelman** [comment] 2015-02-06 22:18
I think I fixed the coverage part, but track-allocation is doing something different somewhere.

**Comment by tkelman** [comment] 2015-02-16 06:27
@StefanKarpinski can you recall what version of Julia was running here?

**Comment by StefanKarpinski** [comment] 2015-03-25 11:15
http://stackoverflow.com/questions/29253222/julia-windows-7-track-memory-allocation

**Comment by tkelman** [comment] 2015-03-25 11:21
Apparently this is fixed on master but we're not sure what the fix was... #9654
