### ISSUE TITLE
workers die in pmap if function throws an exception that contains a pointer

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#13122] opened 2015-09-14 16:08 UTC
```
>julia -p 2
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+32 (2015-09-10 21:27 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 8f08a1f* (3 days old master)
|__/                   |  x86_64-linux-gnu

julia> A_mul_B!(plan_fft([1.0]))
ERROR: MethodError: `A_mul_B!` has no method matching A_mul_B!(::Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,false,1})

julia> pmap(x->A_mul_B!(plan_fft([1.0])), 1:1)
fatal error on 2: ERROR: cannot serialize a pointer
 in serialize at serialize.jl:105
 in serialize at serialize.jl:414
 in serialize at serialize.jl:119
 in serialize at serialize.jl:414 (repeats 4 times)
 in send_msg_ at multi.jl:222
 in send_msg_now at multi.jl:173
 in deliver_result at multi.jl:808
 [inlined code] from multi.jl:893
 in anonymous at task.jl:63
Worker 2 terminated.
ERROR (unhandled task failure): EOFError: read end of file
fatal error on 3: ERROR: cannot serialize a pointer
 in serialize at serialize.jl:105
 in serialize at serialize.jl:414
 in serialize at serialize.jl:119
 in serialize at serialize.jl:414 (repeats 4 times)
 in send_msg_ at multi.jl:222
 in send_msg_now at multi.jl:173
 in deliver_result at multi.jl:808
 [inlined code] from multi.jl:893
 in anonymous at task.jl:63
Worker 3 terminated.
1-element Array{Any,1}ERROR (unhandled task failure): EOFError: read end of file
:
 ProcessExitedException()
```

The issue here appears to be that `plan_fft` returns a `Base.DFT.FFTW.cFFTWPlan{Complex{Float64},-1,false,1}`, which contains a pointer, and so the MethodError cannot be serialized. The workers definitely shouldn't terminate, and it would be nice if the error were returned in some form, even if the argument can't be fully preserved.

**Comment by JeffBezanson** [comment] 2015-09-14 19:10
Possible immediate bandaid: serialize 0 (null pointer).

Possible long term bandaid: store types, not values, in `MethodError`.

**Comment by yuyichao** [comment] 2015-09-14 19:19
Storing types in `MethodError` isn't very hard and is actually already done for the one thrown in `invoke`. The downside would be that we will not be able to print some of the error messages that depends on the size of the arrays (or we'd have to do that when we construct the exception.)

**Comment by JeffBezanson** [comment] 2015-09-14 20:38
This is due to a relatively recent change to the distributed computing code, so it's really a regression in some sense and a fix should be backported.

**Comment by amitmurthy** [comment] 2015-09-15 12:56
The connection always used to be closed, with the worker removed upon a serialization error.

The long term fix would be to drop the message on both sides, throw an error on the sender side and reconnect. The issue is the other side may still be writing data, or there may already be data present in the TCP buffers that is assumed to have been reliably sent.

For short messages, we serialize to a memory buffer, before writing to the socket. This case should be fixable, where we can trap and gracefully handle the error (no need for closing and reconnecting the socket). The problem is mainly for longer messages (> 64K I think).

At the very least, it can be more resilient in some situations.

**Comment by JeffBezanson** [comment] 2015-09-17 15:32
I'm starting to think, in the interest of robustness, we should just serialize the bits of the pointer. At least it will round-trip correctly. Plus you might be working with a shared memory segment, where it could potentially make sense to send a pointer.

**Comment by StefanKarpinski** [comment] 2015-09-17 16:17
For clusters, would it make sense to leverage huge VM space by having disjoint heaps address spaces? That way it would be easy to know whether a pointer is valid on a given node or not.

**Comment by ScottPJones** [comment] 2015-09-17 16:26
Are you requiring that any shared memory segments are mapped to the same address?
We always had to use offsets from the base of the shared memory segment, as it is frequently not possible to get the same virtual address in each process.

**Comment by amitmurthy** [comment] 2015-09-18 05:13
Serializing 0 is a good compromise - since code everywhere should check for a null pointer when deferencing it. Maybe with a `warn_once`.

Serializing actual bit values can result in unexplained segfaults.

**Comment by ScottPJones** [comment] 2015-09-18 05:25
Could support for dealing with (multiple) shared memory segment(s) be added to Julia later (in a package)?  Is anybody interested in that (besides me) for parallel computing in Julia?
I think it might need a hook in the serialization / deserialization code in src to handle it though.
For now, serialize 0.

**Comment by hayd** [comment] 2015-10-06 19:54
I don't think this was cherry-pick. presumably we should wait til 0.4.0's out before back-porting?

**Comment by simonster** [comment] 2015-10-06 20:12
@JeffBezanson's PR (#13190) is still open and unmerged, so the fix isn't even on master yet. Would be good to do something, though. I just ran into this again yesterday.

**Comment by andreasnoack** [comment] 2015-10-26 15:13
The example above is still crashing the workers but the error is different. A simpler example is
```jl
julia> remotecall_fetch(() -> sqrt(C_NULL), workers()[1])
Worker 4 terminated.ERROR: ProcessExitedException()
 in yieldto at ./task.jl:67
 in wait at ./task.jl:367
 in wait at ./task.jl:282
 in wait at ./channels.jl:97
 in take! at ./channels.jl:84
 in take! at ./multi.jl:809
 in remotecall_fetch at multi.jl:735
 [inlined code] from multi.jl:373
 in remotecall_fetch at multi.jl:740
 in eval at ./boot.jl:264
```

**Comment by JeffBezanson** [comment] 2015-10-26 15:20
Wow, `write` for `Ptr` is defined only for IOBuffer. WTH.

**Comment by JeffBezanson** [comment] 2015-10-26 15:25
@Keno can you comment on what the definition

```
write(t::UnixTerminal, p::Ptr{UInt8}) = write(t.out_stream, p)
```

is for? Is this expecting to write a C-string, or the bits of the pointer itself?

**Comment by JeffBezanson** [comment] 2015-10-26 15:47
Also, should

```
read{T,N}(t::UnixTerminal, x::Array{T,N}) = read(t.in_stream, x)
```

be a method of `read!` instead?

**Closed** 2015-10-26 16:25 UTC
Labels: backport pending 0.4, bug, parallel

**Comment by tkelman** [comment] 2015-10-31 07:10
This is another case where if you come to rely on this in a package, please ensure your users are on a new enough Julia to support it by putting `julia 0.4.1` in your `REQUIRE` file.
