### ISSUE TITLE
Not following the ARPACK guidelines for then generalized problem

### ISSUE THREAD

**Issue by andreasnoack** [JuliaLang/julia#17866] opened 2016-08-06 19:23 UTC
The following problem was provided on [julia users](https://groups.google.com/forum/#!topic/julia-users/_XG5251nbek)

``` jl
julia> n = 10
10

julia> A = zeros(n,n);

julia> A[1,1] = 100;

julia> A[10,10] = -100;

julia> C = eye(n);

julia> eigs(A,C)
ERROR: Base.LinAlg.ARPACKException("unspecified ARPACK error: -9999")
 in aupd_wrapper(::Type{T}, ::Base.LinAlg.#matvecA!#69{Array{Float64,2}}, ::Base.LinAlg.##66#73{Array{
Float64,2}}, ::Base.LinAlg.##67#74, ::Int64, ::Bool, ::Bool, ::String, ::Int64, ::Int64, ::String, ::F
loat64, ::Int64, ::Int64, ::Array{Float64,1}) at ./linalg/arpack.jl:53
 in #_eigs#62(::Int64, ::Int64, ::Symbol, ::Float64, ::Int64, ::Void, ::Array{Float64,1}, ::Bool, ::Ba
se.LinAlg.#_eigs, ::Array{Float64,2}, ::Array{Float64,2}) at ./linalg/arnoldi.jl:271
 in _eigs(::Array{Float64,2}, ::Array{Float64,2}) at ./linalg/arnoldi.jl:158
 in #eigs#56(::Array{Any,1}, ::Function, ::Array{Float64,2}, ::Array{Float64,2}) at ./linalg/arnoldi.j
l:80
 in eigs(::Array{Float64,2}, ::Array{Float64,2}) at ./linalg/arnoldi.jl:80
```

Right now, we are using `mode 2` when solving symmetric generalized problems but according to the source we shouldn't. In `dsaupd.f` line 291

``` fortran
c  3. If M can be factored into a Cholesky factorization M = LL`
c     then Mode = 2 should not be selected.  Instead one should use
c     Mode = 1 with  OP = inv(L)*A*inv(L`).  Appropriate triangular
c     linear systems should be solved with L and L` rather
c     than computing inverses.  After convergence, an approximate
c     eigenvector z of the original problem is recovered by solving
c     L`z = x  where x is a Ritz vector of OP.
```

**Comment by ViralBShah** [comment] 2016-08-07 16:16
Seems like the fix for this would also need to be backported to 0.5.

**Comment by rleegates** [comment] 2017-11-29 10:14
I'm encountering the same problem. If I may ask, what is the status on this issue?

**Comment by andreasnoack** [comment] 2017-11-29 11:03
I don't think anybody is currently working on this but eventually, it will get fixed. ARPACK is just a bit of a time sink and right now other tasks have higher priority. However, feel free to work on it if you need this fixed more urgently.

**Comment by ViralBShah** [comment] 2017-11-30 03:00
Is the fix to essentially do what the snippet above says - `Mode = 1 with  OP = inv(L)*A*inv(L')`?

**Comment by timholy** [comment] 2017-11-30 03:07
Cross-linking https://github.com/JuliaGraphs/LightGraphs.jl/pull/736#issuecomment-326725987.
https://github.com/JuliaGraphs/LightGraphs.jl/pull/736#issuecomment-344524228 is a different problem but may be worth mentioning.

**Comment by ViralBShah** [comment] 2017-11-30 07:34
I might be able to take a look at this next week, unless someone beats me to it.

**Comment by ViralBShah** [comment] 2017-12-01 01:51
Closing in favour of #24668. Please reopen if the issue is different.

**Closed by ViralBShah** 2017-12-01 01:51 UTC
Labels: linear algebra
