### ISSUE TITLE
Array access is buggy

### ISSUE THREAD

**Issue by FelixBenning** [JuliaLang/julia#49962] opened 2023-05-26 14:51 UTC
Some Error messages google hopefully picks up on:
- ERROR: UndefVarError: begin not defined
- ERROR: MethodError: no method matching typed_hcat

```julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0 (2022-08-17)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> b = Base.OneTo(3)
Base.OneTo(3)

julia> x = 1
1

julia> b[begin + x -1]
ERROR: UndefVarError: begin not defined
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1

julia> b[firstindex(b) + x -1]
ERROR: MethodError: no method matching typed_hcat(::Base.OneTo{Int64}, ::Int64, ::Int64)
Closest candidates are:
  typed_hcat(::Type{T}, ::Number...) where T at abstractarray.jl:1561
  typed_hcat(::Type{T}, ::Union{Number, LinearAlgebra.Adjoint{T, <:AbstractVector} where T}...) where T at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:229
  typed_hcat(::Type{T}, ::Union{Number, LinearAlgebra.Transpose{T, <:AbstractVector} where T}...) where T at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/adjtrans.jl:230
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1
julia> b[begin +1 ]
ERROR: UndefVarError: begin not defined
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1

julia> b[begin+1 ]
2
julia> b[begin+x]
2

julia> b[begin +x]
ERROR: UndefVarError: begin not defined
Stacktrace:
 [1] top-level scope
   @ REPL[11]:1

```

Note that the JuliaFormatter will introduce spaces!

**Comment by jakobnissen** [comment] 2023-05-26 15:58
Is this a duplicate of the recent https://github.com/JuliaLang/julia/issues/49676 ?

**Comment by oscardssmith** [comment] 2023-05-26 16:36
yeah.

**Closed by oscardssmith** 2023-05-26 16:36 UTC
Labels: parser, invalid
