### ISSUE TITLE
Performance not scaling with multithreading

### ISSUE THREAD

**Issue by abhijithch** [JuliaLang/julia#15874] opened 2016-04-14 14:16 UTC
While running an example from recommender system package for movielens data, the performance of multithreaded parallel version does not seem to scale well. 

<img width="528" alt="screen shot 2016-04-16 at 5 30 01 pm" src="https://cloud.githubusercontent.com/assets/2932535/14580833/f10bfc04-03f8-11e6-84f7-da20a35588a8.png">

To run the example download the dataset from [here](http://files.grouplens.org/datasets/movielens/ml-20m.zip), unzip the files to any folder. Clone this [repository](https://github.com/abhijithch/RecSys.jl/) and run the movielens [example](url) in julia built with multithreading,  
- have a thread enabled julia build
- include the julia [file](https://github.com/abhijithch/RecSys.jl/tree/master/examples/movielens)
- set OPENBLAS_NUM_THREADS to 1
- set JULIA_NUM_THREADS to desired number of threads
- call the `test_thread(dataset_path)` method in the example script

**Comment by andreasnoack** [comment] 2016-04-14 14:24
I think this is a duplicate of https://github.com/JuliaLang/julia/issues/15871 and https://github.com/JuliaLang/julia/issues/15276. Could you try running the threading benchmarks with commit dc6b0de80550c58a2fbb7200632e3ecafaf4dca7

**Comment by abhijithch** [comment] 2016-04-14 14:43
Thanks @andreasnoack, also this is segfaulting for `nthreads()` > 30.

**Comment by ranjanan** [comment] 2016-04-14 15:20
Just adding versioninfo() for reference:
```
Julia Version 0.5.0-dev+1918
Commit 80b14f3 (2015-12-24 13:04 UTC)
Platform Info:
  System: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) CPU E7-4890 v2 @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by ViralBShah** [comment] 2016-04-14 15:26
I think this is not a dup. @abhijithch Didn't you use an older version of julia? Could you point out which commit you used, and is it possible to bisect and find where things broke?

**Comment by ViralBShah** [comment] 2016-04-14 15:27
Oops - ignore. I see @ranjanan did post the commit.

**Comment by ViralBShah** [comment] 2016-04-14 18:26
Cc @tanmaykm

**Comment by amitmurthy** [comment] 2016-04-15 02:13
How many cores?

**Comment by ranjanan** [comment] 2016-04-15 02:19
30 cores with 2 hardware threads per core.

**Comment by kpamnany** [comment] 2016-04-15 20:43
There appear to be 3 different things here.

1. Performance regression. This doesn't seem connected with threads; with 1 thread alone, ``test_thread()`` completes in 60.011244 seconds on commit https://github.com/JuliaLang/julia/commit/dc6b0de80550c58a2fbb7200632e3ecafaf4dca7 and in 75.866557 seconds on master. I think @andreasnoack is right about this part.

2. Segfault. Occurs with 32 threads on commit https://github.com/JuliaLang/julia/commit/dc6b0de80550c58a2fbb7200632e3ecafaf4dca7, and with 16 threads on master. This is https://github.com/JuliaLang/julia/issues/15875.

3. Poor scalability. On commit https://github.com/JuliaLang/julia/commit/dc6b0de80550c58a2fbb7200632e3ecafaf4dca7, performance with 1, 2, 4, 8, and 16 threads is 60.011244, 53.702526, 49.711778, 47.373577, and 47.155389 seconds respectively. On inspection, ``update_user()`` and ``update_item()`` take ~1.5 and ~1.1 seconds on 138493 users and 26744 items. This _should_ show better benefit from threads. Barrier time is negligible which means the loops are regular and load is balanced. How big and unique is the data touched by each thread? Perhaps the cache is being thrashed?

**Comment by yuyichao** [comment] 2016-04-15 22:13
I suspect the performance/scalability issues are probably all/mainly https://github.com/JuliaLang/julia/issues/15276. This includes https://github.com/JuliaLang/julia/issues/15740 https://github.com/JuliaLang/julia/issues/15871 and https://github.com/JuliaLang/julia/issues/15874

**Comment by kpamnany** [comment] 2016-04-15 23:09
Performance with threads still scales on master so I think the scalability issue here is unrelated to the performance regression.
![laplace3d_scaling](https://cloud.githubusercontent.com/assets/3784427/14577084/363285d0-0324-11e6-8b15-300dc0cc3aee.png)

**Comment by ViralBShah** [comment] 2016-04-16 10:28
Given that different users will have different behaviours with items, there shouldn't be much of cache thrashing. You can randomply permute the rows and columns of the R matrix and check if it changes performance. At each iteration, a submatrix is selected from R to work on.

**Comment by abhijithch** [comment] 2016-04-16 14:31
On the commit `dc6b0de` segfault occured for 30 threads itself. The performance with 1, 2, 5, 10, 20 and 29 threads is 68, 61, 58, 53, 58 and 79 seconds respectively.

**Comment by kpamnany** [comment] 2016-04-18 23:49
@ViralBShah: what I meant was, is it possible that each thread is bringing too much data into the cache and evicting other threads' data?

**Comment by pingzou** [comment] 2016-04-27 09:00
I want to try multi-threading, but when I type nthreads() in the REPL, the 
result is 1. Would you please tell me how to set JULIA_NUM_THREADS?

**Comment by nalimilan** [comment] 2016-04-27 10:46
@pingzou Just start Julia with e.g. `JULIA_NUM_THREADS=2 julia`. (But note this only works with a recent git master.)

**Comment by ViralBShah** [comment] 2016-07-09 03:57
@abhijithch Can you try this again and see where we are?

**Comment by KristofferC** [comment] 2018-10-18 03:29
Closing due to inactivity.

**Closed by KristofferC** 2018-10-18 03:29 UTC
Labels: multithreading, performance
