### ISSUE TITLE
Pkg.clone via https hangs

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/julia#17423] opened 2016-07-14 20:22 UTC
I'm trying to clone a (small) private package repo from github using https via ``Pkg.clone``. I get asked for a username, then password (see also #17422), and then everything hangs. I've waited at least 15 minutes by now, and nothing is happening. I reproduced on two different Windows systems.

When I kill the julia process and restart, and then do ``Pkg.status()``, the repo appears in the list, with a status of ``broken-repo (unregistered)`` (in red). When I go into the package folder and do a ``git status``, I get
````
C:\Users\anthoff\.julia\v0.5\Judyp [master]> git status
On branch master

Initial commit

nothing to commit (create/copy files and use "git add" to track)
C:\Users\anthoff\.julia\v0.5\Judyp [master]>
````
And of course I can clone the repo without a problem from command line git via https, so there is no issue with the repo itself.

This should go on the 0.5.0 milestone.

````
julia> versioninfo()
Julia Version 0.5.0-dev+5435
Commit 894fbe7* (2016-07-14 16:00 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
````

**Comment by tkelman** [comment] 2016-07-14 22:15
I can reproduce this too (on Windows, not on Linux). @wildart what's the best way to find out where in the call chain libgit2 gets to for cloning a private https package?

**Comment by tkelman** [comment] 2016-07-15 00:14
I added some print statements, it looks like it's waiting for an extra keypress after asking for the password? Maybe I should try with gallium.
```
Username for 'https://github.com':tkelman
Password for 'https://tkelman@github.com':THISWASMYPWD
<hit enter here a second time after waiting a while>
successfully read userpass

successfully ran git_cred_userpass_plaintext_new
Username for 'https://github.com':Password for 'https://THISWASMYPWD@github.com':
successfully read userpass

successfully ran git_cred_userpass_plaintext_new
Username for 'https://github.com':tkelman
Password for 'https://tkelman@github.com':THISWASMYPWD
<had to hit enter a second time again>
successfully read userpass

successfully ran git_cred_userpass_plaintext_new
Username for 'https://github.com':Password for 'https://THISWASMYPWD@github.com':
successfully read userpass

successfully ran git_cred_userpass_plaintext_new
Username for 'https://github.com':
Password for 'https://@github.com':

successfully read userpass
ERROR: GitError(Code:EAUTH, Class:None, No errors)
 in macro expansion at .\libgit2\error.jl:98 [inlined]
 in clone(::String, ::SubString{String}, ::Base.LibGit2.CloneOptions) at .\libgit2\repository.jl:189
 in #clone#105(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractPayload}, ::Function, ::String, ::SubString{String}) at .\libgit2\libgit2.jl:308
 in clone(::String, ::SubString{String}) at .\pkg\entry.jl:195
 in clone(::String) at .\pkg\entry.jl:221
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{String}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{String}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at .\pkg\dir.jl:31
 in clone(::String) at .\pkg\pkg.jl:151
 in eval(::Module, ::Any) at .\boot.jl:234
 in macro expansion at .\REPL.jl:92 [inlined]
 in (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at .\event.jl:46
```

**Comment by wildart** [comment] 2016-07-15 13:41
I bet it's somehow linked to https://github.com/JuliaLang/julia/issues/17422

**Comment by tkelman** [comment] 2016-07-15 18:30
I agree that seems likely. 2 birds with one stone, hopefully.

**Comment by davidanthoff** [comment] 2016-07-15 21:22
This is not Windows specific, I just tried on Ubuntu and I get exactly the same behavior (everything hangs and julia uses 100% of CPU time).
````
julia> versioninfo()
Julia Version 0.5.0-dev+5448
Commit 54a6490 (2016-07-15 08:36 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
````

**Comment by tkelman** [comment] 2016-07-15 22:12
it worked fine for me on ubuntu

**Comment by davidanthoff** [comment] 2016-07-15 22:32
Just tried again, this definitely doesn't work on my Ubuntu. It is a clean ubuntu install, and then a new source build of julia from master.

**Comment by wildart** [comment] 2016-07-16 01:23
@davidanthoff do you type in or copy-paste your password?

**Comment by davidanthoff** [comment] 2016-07-16 01:51
I type them in.

**Comment by tkelman** [comment] 2016-07-16 01:53
14.04, 16.04, or ?

**Comment by davidanthoff** [comment] 2016-07-16 02:50
16.06, running in a Hyper-V VM. Ubuntu freshly installed yesterday (I think).

**Comment by tkelman** [comment] 2016-07-20 01:00
Hm, now I'm getting a freeze during Pkg.update after entering my password for a private https package on Ubuntu 14.04.

**Comment by davidanthoff** [comment] 2016-07-20 16:14
> Hm, now I'm getting a freeze during Pkg.update after entering my password for a private https package on Ubuntu 14.04.

So remove the windows label?

**Comment by wildart** [comment] 2016-07-20 16:57
I think I was able to reproduce hanging. So, clone a private repo, enter user name then wait for some time before entering password, after password entered - hang is occurred. Please, let me know if anybody can reproduce hanging following above.

**Comment by wildart** [comment] 2016-07-20 17:05
This may be relevant https://github.com/libgit2/libgit2/pull/2979, as the backtrace points on the hanging SSL read operation.

**Comment by wildart** [comment] 2016-07-20 19:46
BTW, when running with native TLS streams (#17471), I do not have this problem.

**Comment by Keno** [comment] 2016-07-21 00:27
@wildart I can reproduce following your instructions. There was a separate issue on windows which should be fixed as soon as the password entry PR is merged. I suspect what's happening here is that github is hanging up the connection if we wait too long and somebody isn't detecting that.

**Comment by wildart** [comment] 2016-07-21 14:25
`libgit2` has infinite timeout on socket IO operations. So when connection is drop on server side, read hang indefinitely.  I wonder if its related to `keep-alive` parameter in HTTP handshake.

**Comment by Keno** [comment] 2016-07-21 18:31
This is https://github.com/libgit2/libgit2/commit/4734c52ab2e5d8b77f2659282eefdbd7ebee4628. Will make a PR to put in the patch.

**Comment by wildart** [comment] 2016-07-21 19:00
@Keno Yes, that is the one. I've seen it after 0.24.1 release, but totally disregarded it. Thanks for finding it.

**Closed** 2016-07-22 07:07 UTC
Labels: libgit2, packages
