### ISSUE TITLE
Broadcasting breakage for non-1 indices

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#20569] opened 2017-02-11 13:49 UTC
```jl
julia> using OffsetArrays

julia> a = OffsetArray(1:3, -1:1)
OffsetArrays.OffsetArray{Int64,1,UnitRange{Int64}} with indices -1:1:
 1
 2
 3

julia> Float64.(a)
ERROR: MethodError: Cannot `convert` an object of type Tuple{UnitRange{Int64}} to an object of type Array{Float64,N} where N
This may have arisen from a call to the constructor Array{Float64,N} where N(...),
since type constructors fall back to convert methods.
Stacktrace:
 [1] Array{Float64,N} where N(::Tuple{UnitRange{Int64}}) at ./sysimg.jl:24
 [2] similar(::Type{T} where T, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:508
 [3] broadcast_t(::Type{T} where T, ::Type{T} where T, ::Tuple{UnitRange{Int64}}, ::CartesianRange{CartesianIndex{1}}, ::OffsetArrays.OffsetArray{Int64,1,UnitRange{Int64}}) at ./broadcast.jl:265
 [4] broadcast_c(::Type{T} where T, ::Type{Array}, ::OffsetArrays.OffsetArray{Int64,1,UnitRange{Int64}}) at ./broadcast.jl:293
 [5] broadcast(::Type{T} where T, ::OffsetArrays.OffsetArray{Int64,1,UnitRange{Int64}}) at ./broadcast.jl:406
 [6] eval(::Module, ::Any) at ./boot.jl:235
```
Works in Julia 0.5.

AFAICT broken in #18642, d16d99432dd7d012d38df2d78765103c3df90244. CC @pabloferz.

**Comment by pabloferz** [comment] 2017-02-11 18:11
Hi Tim, the problem is with `similar` more than with `broadcast`.

On master `similar(Array{Float64}, (-1,1))` gives the error above, but on 0.5 it calls `similar(f::Union{DataType,Function}, shape::Tuple{UnitRange,Vararg{UnitRange,N<:Any}})` form `OffsetArrays` which returns an `OffsetArray`.

I'm not sure if this has to be fixed in master or in `OffsetArrays`, though.

**Comment by timholy** [comment] 2017-02-11 18:28
That's interesting. For reference, the Base method is
```julia
similar(f, shape::Tuple) = f(to_shape(shape))
```
and the one in OffsetArrays is
```julia
Base.similar{T}(f::Union{Function,DataType}, shape::Tuple{UnitRange,Vararg{UnitRange}}) = OffsetArray(f(map(length, shape)), map(indexoffset, shape))
```
To me it seems the one in OffsetArrays is unambiguously more specific. So why isn't it called?

I'm going to classify this as a type system bug.

**Comment by timholy** [comment] 2017-02-11 18:31
I can confirm that splitting the Union fixes the problem:
```julia
Base.similar{T}(::Type{T}, shape::Tuple{UnitRange,Vararg{UnitRange}}) = _similar(T, shape)
Base.similar(f::Function, shape::Tuple{UnitRange,Vararg{UnitRange}}) = _similar(f, shape)
_similar(f, shape) = OffsetArray(f(map(length, shape)), map(indexoffset, shape))
```

**Comment by pabloferz** [comment] 2017-02-11 20:52
The problem is that `Array{Float64}` is now a `UnionAll` (`Array{Float64,N} where N`) which is not a subtype of `DataType`. This could be fixed in `OffsetArrays` by changing the signature to `::Union{Function,Type}`.

**Comment by pabloferz** [comment] 2017-02-11 20:56
See https://github.com/alsam/OffsetArrays.jl/pull/20

**Closed by pabloferz** 2017-02-11 20:56 UTC
Labels: regression, types and dispatch
