### ISSUE TITLE
Define copy for immutable values

### ISSUE THREAD

**Issue by bkamins** [JuliaLang/julia#45143] opened 2022-05-01 20:56 UTC
Following the discussion in https://discourse.julialang.org/t/coordinating-community-efforts-to-enrich-function-docs/80338/8 I propose to add the following catch-all method for `copy` (tentative):
```
function copy(x::T) where T
    ismutable(x) || return x
    throw(ArgumentError("copy for values of type $T is not supported."))
end
```
However, maybe there are reasons why there is no such definition present?

**Comment by KristofferC** [comment] 2022-05-02 06:24
See the discussion in https://github.com/JuliaLang/julia/issues/31995#issuecomment-491327803.

**Comment by bkamins** [comment] 2022-05-02 08:18
So in short:
1. `copy` should be defined for mutable types only.
2. the fact that currently `copy` works for some immutable types is a left-over and is present only to reduce breakage? (unfortunately there are many such cases in practice)

If this is the case then probably this can be closed, but maybe a docstring of `copy` should be improved to reduce users' confusion?

**Comment by bkamins** [comment] 2022-05-02 22:59
Maybe we can add one more point:

3. `copy` can be also defined for lazy structures (like views, transpose, adjoint) in which case it materializes them.

I assume this is also an intended use of `copy`?

**Comment by KristofferC** [comment] 2022-05-03 11:39
Yes, I think that has became the de facto way of doing that (although it feels slightly weird).

**Comment by StefanKarpinski** [comment] 2022-05-03 13:36
For what it's worth I've always felt that defining copy methods for immutable objects that just return their argument is fine but Jeff seems to feel strongly that this is not good.

**Comment by bkamins** [comment] 2022-05-03 19:07
> Is this intended to be a general pattern throughout the Julia ecosystem or just for those array types mentioned?

I guess this is the point of this issue - I would like to settle the rules and write them down in the docsting of `copy` so that newcomers are clear what to expect (`copy` is a function that you learn very early when using Julia so it is important to have a precise contract for it IMHO; this issue was prompted by the documentation improvement initiative of @johnmyleswhite).

My feeling is like @KristofferC - it has become a de-facto way of doing this. Though maybe `materialize` would be a better function to achieve such effect. But for now I would prefer to focus on deciding the contract for `copy` in this issue.

**Comment by Tokazama** [comment] 2022-05-03 23:19
`materialize` sounds like a better name for that to me since we use that for broadcasting too.

**Comment by Tokazama** [comment] 2022-05-04 14:33
Iterators don't follow this pattern. For example, `copy(Iterators.reverse([1, 2, 3]))` errors.

**Comment by jakobnissen** [comment] 2024-04-03 09:00
I would also like to point out that the proposed fallback implementation is wrong - for example, `Set`s are immutable according to `ismutable`, but has mutable semantics because they contain a field that _can_ be mutated. For the proposed implementation to work, there would need to be a way to query if an object is semantically mutable which is not something we have.

**Comment by nsajko** [comment] 2024-04-03 10:48
If the fallback were to use `isbits(x)` instead of `ismutable(x)` I think it would work as intended:

```julia
function copy(x::T) where {T}
    isbits(x) || throw(ArgumentError("copy for values of type $T is not supported."))
    x
end
```

**Comment by nsajko** [comment] 2024-04-03 10:50
Although possibly `ArgumentError` is not the best exception type to use, xref #50196.

**Comment by JeffBezanson** [comment] 2024-04-05 20:03
Closing as wontfix.

**Closed by JeffBezanson** 2024-04-05 20:03 UTC
Labels: design

**Comment by nsajko** [comment] 2024-04-06 06:42
@JeffBezanson, in "You should not call `copy` on immutable objects" (#53938), what does "immutable object" mean? There's a bunch of `struct` types that are not mutable, but have `copy` defined. Including many array types, including many in the `LinearAlgebra`  stdlib:

```julia-repl
julia> using LinearAlgebra

julia> d = Diagonal([1 0; 0 1])
2×2 Diagonal{Int64, Vector{Int64}}:
 1  ⋅
 ⋅  1

julia> ismutable(d)
false

julia> copy(d)
2×2 Diagonal{Int64, Vector{Int64}}:
 1  ⋅
 ⋅  1
```

Some array types in the ecosystem can even be `isbits`, like with StaticArrays.

**Comment by nsajko** [comment] 2024-04-06 06:47
Some others?

```julia-repl
julia> ismutable(Set([1]))
false

julia> ismutable(@view [1][1:1])
false

julia> ismutable(LinearIndices([1]))
false
```
