### ISSUE TITLE
Julia links OpenSSL which has a GPL-incompatible license

### ISSUE THREAD

**Issue by drbo** [JuliaLang/julia#13476] opened 2015-10-07 06:24 UTC
Julia currently links to OpenSSL (via libgit2).  However, OpenSSL has a GPL-incompatible license.  Since a build of Julia that links to FFTW is under the GPL this is a serious problem.

The only solution that I can think of is to use a different crypto lib (such as Mozilla Network Security Services).

**Comment by tkelman** [comment] 2015-10-07 07:03
Duplicate of #10763. Git itself is GPLv2, and distributes binaries that bundle openssl, so we're no worse than that. As far as I know, libgit2 is not capable of using any tls libraries other than openssl or libressl right now, which have the same licenses. The best bet for resolving this would be to look into adding support upstream with libgit2 for using mbedtls, which is available dual-licensed as either Apache 2.0 (for GPL-free Julia) or GPL 2.0 (for GPL-compatible Julia).

**Closed by tkelman** 2015-10-07 07:03 UTC

**Comment by wildart** [comment] 2015-10-07 08:14
One exception, only *nix distributions are affected. On Windows and OSX, libgit2 does not link to libssl.
