### ISSUE TITLE
Views and Array{Bool} on 0.6

### ISSUE THREAD

**Issue by wtkranz** [JuliaLang/julia#22003] opened 2017-05-21 12:04 UTC
Doing a seemingly innocent 
```julia
versioninfo()
c, d = Array{Bool}(10), Array{Bool}(10)
view(c, d)
```

unexpectedly fails with the rather unhelpful message

```
Julia Version 0.6.0-rc1.0
Commit 6bdb395 (2017-05-07 00:00 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Prescott)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

BoundsError: attempt to access 10-element Array{Bool,1} at index [11]

Stacktrace:
 [1] next at ./multidimensional.jl:352 [inlined]
 [2] next at ./generator.jl:44 [inlined]
 [3] collect_to!(::Array{Int64,1}, ::Base.Generator{Base.LogicalIndex{Int64,Array{Bool,1}},Base.##272#273}, ::Int64, ::Tuple{Base.OneTo{Int64},Int64,Int64}) at ./array.jl:462
 [4] collect(::Base.Generator{Base.LogicalIndex{Int64,Array{Bool,1}},Base.##272#273}) at ./array.jl:430
 [5] unsafe_view(::Array{Bool,1}, ::Base.LogicalIndex{Int64,Array{Bool,1}}, ::Vararg{Base.LogicalIndex{Int64,Array{Bool,1}},N} where N) at ./subarray.jl:119
 [6] view(::Array{Bool,1}, ::Array{Bool,1}, ::Vararg{Array{Bool,1},N} where N) at ./subarray.jl:114
```

I would have expected it to do logical indexing. 

On exploring this I realized that things like `trues(10)` and `1:10 .< 5` return `BitArray`s. This seems a little backwards to me. Shouldn't *logical* expressions return *boolean* arrays (which may or may not be *implemented* as BitArrays, but this should not concern me as a user)?  I could find arguments why one may **not** want to allow BitArrays as logical indices (but then this may be overly pedantic and inconvenient in practice) but the why `Array{Bool}` should explicitly be unsupported baffles me

**Comment by carlobaldassi** [comment] 2017-05-21 12:43
I don't think this has directly to do with the choice of `Array{Bool}` vs `BitArray`, but rather with the bug described in #20065. If you initialize the array `d` it works as expected, e.g.
```julia
c, d = Array{Bool}(10), Array{Bool}(bitrand(10))
view(c, d)
```

**Comment by carlobaldassi** [comment] 2017-05-21 12:51
As another demonstration of the bug, the following hack also works:
```julia
c, d = Array{Bool}(10), Array{Bool}(10)
for j = 1:length(d)
    d[j] = d[j]
end
view(c, d)
```

**Comment by timholy** [comment] 2017-05-21 13:38
That is really wild. Here's an even simpler example:
```julia
julia> d = Array{Bool}(10)
10-element Array{Bool,1}:
 false
  true
  true
 false
  true
  true
 false
 false
 false
  true

julia> for item in d
           @show item
       end
item = true
item = true
item = true
item = true
item = true
item = true
item = false
item = false
item = true
item = true
```

**Comment by wtkranz** [comment] 2017-05-21 14:20
Wow, two things learned

1. I can use Array{Bool} to do logical indexing although it may at any time be converted to a BitArray (e.g., by `.!`)
2. I cannot use uninitialized arrays for checking out Julia features even when I do not care about values

I am still not sure I like BitArrays playing such a fundamental role

**Comment by nalimilan** [comment] 2017-05-21 14:38
@wtkranz To be clear, this is a terrible bug, not the expected behavior. Normally, you should be able to index uninitialized arrays, and they should return a (random) value.

**Comment by mbauman** [comment] 2017-05-22 14:42
Note that there's a new section in the 0.6 documentation that describes logical indexing in more detail: https://docs.julialang.org/en/latest/manual/arrays.html#Logical-indexing-1

The key part here is that *all* arrays with an element type of Bool participate in logical indexing. BitArray's name is a little confusing: it is an array of Bool, it just uses bits as the storage.

**Comment by mbauman** [comment] 2017-05-22 14:44
I'll close this as a dup of #20065 since that bug seems to be at the root here.

**Closed by mbauman** 2017-05-22 14:44 UTC
Labels: arrays
