### ISSUE TITLE
'make test' fails for julia-1.11.0-rc2

### ISSUE THREAD

**Issue by sergstesh** [JuliaLang/julia#55467] opened 2024-08-11 23:01 UTC
I've downloaded https://github.com/JuliaLang/julia/releases/download/v1.11.0-rc2/julia-1.11.0-rc2-full.tar.gz tarball and unpacked it the usual way, then after doing 'cd julia-1.11.0-rc2' I ran the following command line:

`nice -n 19 make test 1>make_test.log 2>&1`
.
Output of 'versioninfo()':

```
julia> versioninfo()
Julia Version 1.11.0-rc2
Commit 34c3a63147 (2024-07-29 06:24 UTC)
Build Info:

    Note: This is an unofficial build, please report bugs to the project
    responsible for this build and not to the Julia project unless you can
    reproduce the issue using official builds available at https://julialang.org/downloads

Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) N100
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, goldmont)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)

julia> 
```

.

'make_test.log' file is attached.
[make_test.log](https://github.com/user-attachments/files/16576370/make_test.log)

**Comment by giordano** [comment] 2024-08-13 00:18
I can't open the log file now, but is there anything new compared to  #54280,  #54777, #54234, #54771, or  #54966?

**Comment by giordano** [comment] 2024-08-13 19:59
Duplicate of #54966

**Closed by giordano** 2024-08-13 19:59 UTC
