### ISSUE TITLE
Add error message for `DomainError`

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/julia#13226] opened 2015-09-19 14:18 UTC
Currently `ArgumentError` can be passed a string to use as an error message, but `DomainError` cannot. It would be nice for the user to have a useful error message also for `DomainError`s.

I would make a PR but I can't find where to do this.

**Comment by jiahao** [comment] 2015-09-19 15:29
Duplicate of #12152 #9693

The main blocking issue is the speed of generated code.

**Closed by jiahao** 2015-09-19 15:29 UTC
Labels: error handling

**Comment by dpsanders** [comment] 2015-09-19 15:30
Ah OK, sorry.
