### ISSUE TITLE
Julia 1.8 beta3 can't be opened on macOS Apple Silicon: "The application Terminal can't be opened. -1703"

### ISSUE THREAD

**Issue by truedichotomy** [JuliaLang/julia#44826] opened 2022-04-01 14:12 UTC
When double click on the icon to open Julia 1.8 beta3 for the first time, I encounter the "The application "Terminal" can't be opened. -1703" error on my Apple Silicon M1 mac.

**Comment by ngam** [comment] 2022-04-01 17:07
Duplicate of #44690

**Closed** 2022-04-01 17:18 UTC
