### ISSUE TITLE
Should `convert(::Type{Array}, itr::Base.Generator) = collect(itr)`?

### ISSUE THREAD

**Issue by schmrlng** [JuliaLang/julia#24442] opened 2017-11-02 03:27 UTC
I can't think of a reason why this method shouldn't be added, but I may be missing something.

**Comment by JeffBezanson** [comment] 2017-11-02 04:29
Duplicate of #16029. Many of us think `collect(itr)` should be replaced by `Array(itr)`, but making it a method of `convert` probably isn't necessary or advisable.

**Closed by JeffBezanson** 2017-11-02 04:29 UTC
