### ISSUE TITLE
Dispatch issue with parametric methods where subtype constraint is a Type

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#12721] opened 2015-08-21 01:29 UTC
Consider (on 0.4):

``` julia
julia> f{T<:Type{Int}}(::T) = true;

julia> f(Float64)
true
```

I think this should be a MethodError. It seems like `f` is applicable for any DataType, not just `Type{Int}`.

On 0.3, `f(Float64)` is in fact a MethodError, but so is `f(Int)`, which I would expect to work, so while the behavior has changed it doesn't seem like this is a regression.

**Comment by JeffBezanson** [comment] 2015-08-21 16:32
I think this has the same root cause as #11327.

**Comment by JeffBezanson** [comment] 2017-01-16 17:57
This is now fixed. (Maybe by #18457 but might have been fixed before that.)

**Closed by JeffBezanson** 2017-01-16 17:57 UTC
Labels: types and dispatch

**Comment by tkelman** [comment] 2017-01-16 17:59
should add a test if there isn't one

**Comment by mauro3** [comment] 2017-01-17 20:01
This is fixed on 0.4.7 already.
