### ISSUE TITLE
Towards true duck-typing

### ISSUE THREAD

**Issue by bramtayl** [JuliaLang/julia#35940] opened 2020-05-19 18:10 UTC
Ok. So the fundamental motivating problem here is broadcasted objects, which have `size` and `getindex` methods, but not `eltype` and `setindex!` methods. That is, they implement 1/2 of the [AbstractArray interface](https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array-1). A lot of methods defined for AbstractArrays, however, do not require `eltype` nor `setindex!`. For evidence of this, see #34196. So it would be nice if these methods could be automatically defined for broadcasted objects. 

The fundamental problem is that labeling something as AbstractArray is, at least by the interface definition, simply asserting that it has four special methods (`getindex`, `setindex!`, `eltype`, and `size`). However, this information is contained only in the documentation, and not encoded into the language itself. So solving this problem requires having some way of addressing this information gap.

Therefore, I propose the following:
1) All abstract types be required to define exactly what fundamental methods are required of them 
2) A way to harness this information during dispatch

I'm not sure of the best way to implement a solution, but I can suggest that solutions should avoid boolean hell. For an extended discussion of the topic of boolean hell, see #35095

Quack quack

**Comment by JeffBezanson** [comment] 2020-05-19 19:23
Duplicate of #6975. The feature described here is interfaces, not duck typing. You get duck typing just by removing type constraints from arguments.

**Closed by JeffBezanson** 2020-05-19 19:23 UTC

**Comment by bramtayl** [comment] 2020-05-19 22:51
Yes, that issue is exactly what I was trying to describe!
