### ISSUE TITLE
Align `SharedArray` constructor with other Array constructors

### ISSUE THREAD

**Issue by nilshg** [JuliaLang/julia#29046] opened 2018-09-05 09:39 UTC
Following the discussion in [this issue](https://github.com/JuliaLang/julia/issues/24595) an Array is constructed as 

`Array{T}(undef, shape...)`

A `SharedArray` however is still constructed using 

`SharedArray{T}(shape...)`

Having asked about this [on the Discourse forum](https://discourse.julialang.org/t/undef-for-array-and-sharedarray-initialisation/14366), @rdeits suggested aligning the `SharedArray` API to that of general arrays, which seems like a good idea to me.

**Comment by fredrikekre** [comment] 2018-09-05 09:43
Duplicate of #27388

**Closed by fredrikekre** 2018-09-05 09:43 UTC
