### ISSUE TITLE
Unicode Conversion Error

### ISSUE THREAD

**Issue by SloanLindsey** [JuliaLang/julia#13484] opened 2015-10-07 17:05 UTC
When trying to read the following line from an ANSI windows text file I get the following error
```
³00001³29.58E+00³24438.E-03³-1598.E-04³ 9003.E-05³0011.60³ Si ³83353.E-03³ <== Start of New Cascade  ³

Error showing value of type Array{ByteString,1}:
ERROR: UnicodeError: invalid character index
 in next at unicode/utf8.jl:65
 in print_escaped at strings/io.jl:114
 in print_quoted at strings/io.jl:131
 in showcompact_lim at show.jl:120
 in sprint at iostream.jl:206
 in alignment at show.jl:959
 in alignment at show.jl:991
 in print_matrix at show.jl:1091
 in print_matrix at show.jl:1058
 in anonymous at replutil.jl:23
 in with_output_limit at show.jl:1255
 in writemime at replutil.jl:23
 in display at REPL.jl:114
 in display at REPL.jl:117
 in display at multimedia.jl:151
 in print_response at REPL.jl:134
 in print_response at REPL.jl:121
 in anonymous at REPL.jl:624
 in run_interface at LineEdit.jl:1610
 in run_frontend at REPL.jl:863
 in run_repl at REPL.jl:167
 in _start at client.jl:453
```
On version 3 this does not create a problem.
```
julia> readlines(io)
112496-element Array{Union(ASCIIString,UTF8String),1}:
```
It looks like there is some fancy typing going on in 3 that wasn't ported to 4 (I've tried both rc1 and rc4). 
I've delved into the documents and haven't really seen how to push the type declaration before calling readlines() or readline. 
So far the only solution that I've seen is to call the windows version of iconv to shift the data into a UTF8 format. This is less than optimal because it forces me to include a gnu-tool in the package or at the minimum add a further dependency.

Is this a legitimate bug or is this a design feature for which there exist a Julia-space work around?
Thanks,
Sloan Lindsey

**Comment by jiahao** [comment] 2015-10-07 17:09
Your issue report does not provide enough details to reproduce the error. Please post the result of `versioninfo()` and the relevant snippets of code and input (if possible).

**Comment by jiahao** [comment] 2015-10-07 17:13
Note also that ANSI (I assume you mean Windows-1252) is _not_ Unicode compatible and is not supported by base Julia. You're probably encountering a non-ASCII character that is confusing Julia, which expects only Unicode code points.

**Comment by SloanLindsey** [comment] 2015-10-07 17:18
You are correct, ANSI is not Unicode compatible. However there was a "feature" in the version 3 that allowed it to function.
Let me see if I can figure out how to upload an example file snippet.

**Comment by ScottPJones** [comment] 2015-10-07 17:21
Version 3 just allowed garbage into the strings, it was a bug, not a "feature".

**Comment by SloanLindsey** [comment] 2015-10-07 17:27
julia> versioninfo()
Julia Version 0.4.0-rc4
Commit e9c9c92* (2015-10-04 03:14 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Well git won't let me load the file because of the bad character. 

I am aware of this issue and that this is aberrant behavior; however in my case, the data is only available in this stupid format because it comes from an old closed source monte-carlo simulator. Is there a work around where I can get julia to load the line as something else and then skip the offending character? As of now julia just throws an error. Try:catching the error results in skipping the line, not the offending first character.

**Comment by jiahao** [comment] 2015-10-07 17:45
> Please post the result of versioninfo() and the relevant snippets of code and input (if possible).

You still haven't explained how you are reading the file.

One way to circumvent the issue (if the non-ASCII characters are unimportant) is to read the file in as a raw sequence of bytes using `readbytes`, manually drop or replace the offending characters, and then calling the appropriate `ASCIIString()` or `UTF8String()` constructor on the array of bytes to produce a Julia string which you can work with. You can also call `parse(Float64, _)` on the raw array of bytes to produce a number directly.

This is not a bug in Julia, so I'm closing the issue.

**Closed by jiahao** 2015-10-07 17:45 UTC

**Comment by ScottPJones** [comment] 2015-10-07 17:49
If you know it is really in the ANSI Latin 1 character set (and not Windows CP1252, which frequently is mislabled as ANSI Latin 1), then you can do the `readbytes`, then copy the bytes into a UInt16 vector (unfortunately, with an extra \0 word!) and then use the `UTF16String` constructor on it.  Since ANSI Latin1 is a subset of Unicode, that will work, giving you a correct `UTF16String`, which you can then use directly in Julia, or convert to a `UTF8String` easily.

**Comment by SloanLindsey** [comment] 2015-10-07 18:35
jiahao,
I agree with closing the issue. Though for historic reasons (in case someone else ever gets bit by this windows junk) I'll follow up with answers to your questions.

I'm reading the file using:
```jl
path = "COLLISION.TXT"
io = open(path,"r")
lines = readlines(io)
```

this results in the error

What ended up working for me with the assistance provided here:

```jl
path = "COLLISION.TXT"
io = open(path,"r")
bytes = readbytes(io)
close(io)
string =  UTF8String(UTF16String(ASCIIString(bytes)))
lines = split(string, "\r\n")
```
The triple conversion appears to be needed. 
Thanks for the pointers
Sloan

**Comment by jiahao** [comment] 2015-10-07 18:50
Thanks for documenting your solution!
