### ISSUE TITLE
Interactive slow cursor

### ISSUE THREAD

**Issue by cup** [JuliaLang/julia#32198] opened 2019-05-31 00:34 UTC
Using Windows, if you launch the REPL and type

~~~
abcde
~~~

then use left arrow, the cursor is quite slow, perhap one second per keystroke.
I am not sure if the cursor just blinks slower than normal or what the issue is.
I thought it might be because Julia REPL is in color, but modern Ruby REPL is in
color too so thats not it.

If my cursor is under `e` and I move left, the cursor should show under `d`
FAST. Like 1/10 of a second or similar. Otherwise its painful to do anything
beyond the most basic of task in the REPL and I will end up doing scripts for
even 2 line tasks, or perhaps string programs. Then this kills the whole point
of having a REPL.

**Comment by musm** [comment] 2019-05-31 16:56
can you post a gif or similar of the repl?

**Comment by cup** [comment] 2019-06-01 22:54
@musm Julia:

https://s.put.re/Yo9YmJMe.mp4

Python:

https://s.put.re/z5tvmMWG.mp4

**Comment by mbauman** [comment] 2019-06-05 19:10
What terminal are you using?  See #7267.

**Comment by cup** [comment] 2019-06-05 19:57
@mbauman the default terminal

https://wikipedia.org/wiki/Cmd.exe

**Comment by musm** [comment] 2019-06-05 19:58
Strange, I definitely don't see this. 

Which windows version  (winver)

**Comment by cup** [comment] 2019-06-05 20:21
Windows 7

**Comment by iamed2** [comment] 2019-06-05 20:22
For me there's less of a delay but it is just barely slower than Python. I do see flickering of the current line in the Julia prompt that I don't see in the Python prompt. This only shows up when using the default Windows terminal; if I use ConEmu with cmd.exe as the shell, it doesn't happen. This is Windows 10 1809.

**Comment by musm** [comment] 2019-06-05 20:25
I see the exact same behavior as @iamed2

**Comment by mbaz** [comment] 2019-06-06 00:34
@cup Make sure you don't load any packages that rely on Gtk.jl; see https://github.com/JuliaGraphics/Gtk.jl/issues/325

BTW, I also see a very slow REPL on cmd.exe in Windows 10, even without Gtk.jl loaded.

**Comment by cup** [comment] 2019-06-06 03:06
@mbaz uh, how would i even unload it?

im using a pristine Julia install, so unless its loaded by default, that aint it.

**Comment by mbaz** [comment] 2019-06-06 14:49
@cup Yeah, if you're not loading it, then it's not the cause of the slowdown you see.

I brought this up because many packages (which one may load from Julia's startup file) depend on Gtk.jl. `using` any of those packages brings Gtk.jl in.

In my case, I was trying to use ProfileView to profile some code. The results showed my code spending most of its time in Gtk functions, which was weird -- until I saw that ProfileView brings Gtk in and messes up the event loop.

**Comment by cup** [comment] 2019-07-05 22:42
I just retested this with pristine virtual machine of Windows 7, Windows 8.1 and Windows 10 and the behavior persists.

Note as previously stated other REPLs (Python) work fine.

I didnt test with other terminals like ConEmu or similar because, frankly, I shouldnt have to. Julia should work correctly with the default terminal. No other interpreted language Ive ever dealt with has had this problem, and Ive used REPL of:

- Python
- PHP
- Ruby
- Perl
- R
- Lua
- Tcl

please look into this as its the only issue keeping me from using Julia.

**Comment by cup** [comment] 2019-08-18 20:13
FYI I have also tested these and the problem persists:

- v1.2.0-rc3
- v1.3.0-rc1

although thats likely expected, as doesnt seem any work has been done to
resolve.

**Comment by KristofferC** [comment] 2019-08-18 21:00
I cannot repro on a freshly installed Windows 10 with julia 1.2-rc3.

**Comment by cup** [comment] 2019-08-18 21:14
@KristofferC can you clarify your terminal?

**Comment by KristofferC** [comment] 2019-08-18 21:51
cmd.exe

**Comment by cup** [comment] 2019-08-18 22:54
@KristofferC are you able to test any other Windows versions? I can set up a Windows 10 virtual machine, but I would like to avoid that if possible

**Comment by KristofferC** [comment] 2019-08-18 23:10
> are you able to test any other Windows versions?

Unfortunately, no.

**Comment by cup** [comment] 2019-08-18 23:33
@KristofferC hm, well as long as Windows 7 and 8 are officially supported:

https://julialang.org/downloads

this is a valid issue. So I think the easiest thing for me to do is just keep
waiting. Thanks.

**Comment by StefanKarpinski** [comment] 2019-08-18 23:47
We would, of course like to provide a good experience on as many platforms as possible, but since this seems to be due to a CMD.exe bug (that we're expected to figure out a workaround for even though it's not our bug), that only happens on old Windows versions when using the known-to-be-crappy terminal, and there are alternative terminals that are much better in every way, this is a pretty low priority. If you or someone else who has one of these old systems doesn't investigate this, it seems unlikely that it will be fixed.

**Comment by cup** [comment] 2019-08-18 23:52
@StefanKarpinski that is a strange comment, considering these and others work
just fine in the situation youve described:

- Python
- PHP
- Ruby
- Perl
- Lua

**Comment by cup** [comment] 2019-08-18 23:54
@StefanKarpinski that is a strange comment, considering these and others work
just fine in the situation youve described:

- Python
- PHP
- Ruby
- Perl
- Lua

it seems like when you are saying this:

> We would, of course like to provide a good experience on as many platforms as
> possible

what you really mean is:

> We would, of course like to provide a good experience on as many platforms as
> possible, as long as that goal doesnt require any effort

**Comment by StefanKarpinski** [comment] 2019-08-19 00:02
I think you really need to reexamine your attitude about open source software. You are not entitled to anyone else fixing bugs for you. Since you seem to have a lot of enthusiastic for getting this particular issue fixed, I would suggest directing that energy towards investigating whether any of the above languages have had a similar bug in the past, and if so, how they fixed it.

**Comment by cup** [comment] 2019-08-19 00:11
> I think you really need to reexamine your attitude about open source software.

as do you

> You are not entitled to anyone else fixing bugs for you.

correct

> You either fix a bug yourself, pay for someone else to fix it, or wait until
> someone else decides to fix it.

also correct, I am choosing to wait

> Since you seem to have a lot of enthusiasm for getting this particular
> issue fixed, I would suggest directing that energy towards investigating
> whether any of the above languages have had a similar bug in the past, and if
> so, how they fixed it.

i think better use of my time would be to continue to wait. as I am actively
using some of the other programming languages listed, it wont be a huge problem
if this goes several years without being fixed. obviously i would like to see
this fixed in a timely manner, but as youve said thats unlikely to happen with
the current leadership. thanks

**Comment by cup** [comment] 2019-08-19 00:14
> I think you really need to reexamine your attitude about open source software.

as do you. windows 7 is proudly listed here:

https://julialang.org/downloads

but leadership seems to be unwilling to unable to take steps to ensure that
experience is actually usuable on that platform. it would be better to just be
honest and change it to Windows 10, or at least be clear that Windows 7 (and 8?)
users are going to have a degraded experience.

> You are not entitled to anyone else fixing bugs for you.

correct

> You either fix a bug yourself, pay for someone else to fix it, or wait until
> someone else decides to fix it.

also correct, I am choosing to wait

> Since you seem to have a lot of enthusiasm for getting this particular
> issue fixed, I would suggest directing that energy towards investigating
> whether any of the above languages have had a similar bug in the past, and if
> so, how they fixed it.

i think better use of my time would be to continue to wait. as I am actively
using some of the other programming languages listed, it wont be a huge problem
if this goes several years without being fixed. obviously i would like to see
this fixed in a timely manner, but as youve said thats unlikely to happen with
the current leadership. thanks

**Comment by StefanKarpinski** [comment] 2019-08-19 00:25
I'm just trying to set expectations. Microsoft won't even support Windows 7 [in five months](https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information).

**Comment by StefanKarpinski** [comment] 2019-08-19 00:31
Also, Julia is perfectly usable on Windows 7: you can any of the various higher quality terminals that don’t have this problem, or use Juno which has a built in terminal, also without this problem. Is there some reason you are unable to use a real terminal?

**Comment by cup** [comment] 2019-08-19 01:58
@StefanKarpinski it seems you have a habit of framing an issue as a problem with
a user or environment, rather than a Julia issue. Is there some reason why you
refuse to admit a problem with Julia when its addressed? Windows 7 is currently
supposed to be supported:

https://julialang.org/downloads

this linked page doesnt say that windows 7 performance will be degraded, or that
windows 7 users should use some other terminal else face degraded experience.
Also Windows 7 still has a higher marketshare than Mac and Linux combined:

https://netmarketshare.com/operating-system-market-share.aspx?id=platformsDesktopVersions

if you want to hand wave over valid issues, thats your business. but it seems
no one else has even tested the issue with anything other than windows 10, so
its not really valid to say "works for me" or similar. Finally I will repeat
that no other major interpreted language has this problem, including with the
environment in question.

**Comment by ihnorton** [comment] 2019-08-22 02:33
x-ref previous issue analysis here and for NodeJS (which also uses libuv and also exhibits this issue on Windows 7):

- https://github.com/JuliaLang/julia/issues/26422
- https://github.com/nodejs/node/issues/20348 (especially [this comment](https://github.com/nodejs/node/issues/20348#issuecomment-387414086)

**Comment by vtjnash** [comment] 2019-08-22 17:53
Since we (and nodejs) have shown this is a bug with Windows 7 conhost.exe, and they've already reported this to be fixed in newer releases (https://github.com/microsoft/terminal/issues/269), I'm going to close this and suggest you file any new bug reports against the responsible entity (same link as previous: https://github.com/microsoft/terminal/issues/new?template=Bug_Report.md)

**Closed by vtjnash** 2019-08-22 17:53 UTC
Labels: windows

**Comment by cup** [comment] 2019-08-22 18:04
https://github.com/JuliaLang/julia/issues/33030

**Comment by cup** [comment] 2019-09-02 05:00
It seems I did not do enough testing. Previously I had only tested the Cygwin
versions. Retesting with native Windows versions yields this:

1. Python
   - Slow
2. PHP
   - Fast
3. Ruby
   - Slow
4. Perl
   - Slow
5. Lua
   - Slow

Julia is still slower than these listed, but not by much. I am not sure why the
Windows version would be slower than Cygwin version, or how PHP was able to keep
speed up.
