### ISSUE TITLE
`vect` / promote change between `1.8` and `1.9` - `nightly`

### ISSUE THREAD

**Issue by t-bltg** [JuliaLang/julia#47261] opened 2022-10-20 21:40 UTC
Not sure if this is a bug or not (used to work in `1.8` and before), but this currently breaks `Plots` ci on nightly.

**1.8**
```julia
julia> using StaticArrays, OffsetArrays
julia> sv = SVector{10}(rand(10));
julia> ov = OffsetVector(rand(10), -2);
julia> [sv, ov]
2-element Vector{AbstractVector{Float64}}:
[...]
```

**1.9 / nightly**
```julia
julia> using StaticArrays, OffsetArrays
julia> sv = SVector{10}(rand(10));
julia> ov = OffsetVector(rand(10), -2);
julia> [sv, ov]
ERROR: DimensionMismatch: axes must agree, got (Base.OneTo(10),) and (OffsetArrays.IdOffsetRange(values=-1:8, indices=-1:8),)
Stacktrace:
  [1] _checkaxs(axd::Tuple{Base.OneTo{Int64}}, axs::Tuple{OffsetArrays.IdOffsetRange{Int64, Base.OneTo{Int64}}})
    @ Base ./abstractarray.jl:1168
  [2] copyto_axcheck!(dest::Vector{Float64}, src::OffsetVector{Float64, Vector{Float64}})
    @ Base ./abstractarray.jl:1171
  [3] Array
    @ ./array.jl:621 [inlined]
  [4] convert
    @ ./array.jl:613 [inlined]
  [5] setindex!
    @ ./array.jl:969 [inlined]
  [6] #109
    @ ./array.jl:408 [inlined]
  [7] afoldl
    @ ./operators.jl:536 [inlined]
  [8] getindex(::Type{Vector{Float64}}, ::SVector{10, Float64}, ::OffsetVector{Float64, Vector{Float64}})
    @ Base ./array.jl:407
  [9] vect(::SVector{10, Float64}, ::Vararg{Any})
    @ Base ./array.jl:145
 [10] top-level scope
    @ REPL[7]:1
```

**Comment by giordano** [comment] 2022-10-20 23:20
Can you please provide a more descriptive title?  That one probably applies to a good fraction of issues opened in the last couple of months.

**Comment by jishnub** [comment] 2022-10-21 08:06
Duplicate of https://github.com/JuliaLang/julia/issues/44939

**Closed by jishnub** 2022-10-21 08:06 UTC
