### ISSUE TITLE
Document the interaction of Julia and BLAS threads

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#44201] opened 2022-02-16 08:46 UTC
Following the discussion in https://github.com/JuliaLang/julia/pull/44168#discussion_r805863793 (and https://github.com/JuliaLinearAlgebra/MKL.jl/issues/106) I suggest to copy https://carstenbauer.github.io/ThreadPinning.jl/dev/explanations/blas/ into somewhere in the Julia manual if @carstenbauer is OK with it.

**Comment by ViralBShah** [comment] 2022-02-18 19:10
Yes, good idea.

**Comment by carstenbauer** [comment] 2022-02-18 20:28
Yes feel free to copy whatever you deem worth copying! (We should definitely drop my ranty comments :smile:)

Note, though, that I wrote this down rather quickly, so perhaps it needs some polishing for the Julia docs.

**Comment by carstenbauer** [comment] 2022-02-18 20:35
One more thing. I think I remember that someone mentioned that there might be a difference between setting `OPENBLAS_NUM_THREADS=1` before starting Julia and calling `BLAS.set_num_threads(1)`. I didn't really investigate this (I guess that the difference, if there is one, is only technical.)

**Comment by ViralBShah** [comment] 2022-02-18 21:58
I believe you are strictly better off setting it before starting. IIRC, it used to be unreliable if you did it after starting, or it would allocate all the memory anyways if you did it  after starting. I can't remember which versions had this problem - but my mental model is - always do it before starting.

**Comment by MashiatK** [comment] 2023-02-08 17:17
I want to work on this. If the issue is open, please assign it to me.

**Comment by ViralBShah** [comment] 2023-02-08 17:30
@MashiatK, please open a PR. Consider it assigned.

**Comment by gdalle** [comment] 2023-06-10 12:24
@MashiatK do you still wanna work on this? If not, I'll be happy to do the copy-paste, ran into this question myself today

**Comment by inkydragon** [comment] 2023-06-10 13:06
> do you still wanna work on this? If not

Just do it and open a pr.
No need to assign to someone.

**Closed** 2023-06-27 20:41 UTC
Labels: doc, multithreading, good first issue
