### ISSUE TITLE
erroneous reinterpret only fails with --code-coverage=user

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/julia#34865] opened 2020-02-25 07:57 UTC
```
$ julia                      -e 'reinterpret(Nothing, nothing)'                               
                                               
$ julia --code-coverage=user -e 'reinterpret(Nothing, nothing)'                                                         
ERROR: bitcast: target type not a leaf primitive type
Stacktrace:
 [1] reinterpret(::Type{Nothing}, ::Nothing) at ./essentials.jl:413
 [2] top-level scope at none:1
```

Started behaving differently with 1.1, on 1.0 both fail. Arguably this use of `reinterpret` should be allowed, but the change in behavior based on code coverage had me stumped for a while.

**Comment by vtjnash** [comment] 2020-02-25 16:09
`reinterpret(T, nothing)` should fail consistently for all `T`, but we're in need of merging https://github.com/JuliaLang/julia/pull/34539

**Comment by vtjnash** [comment] 2020-02-25 16:10
Duplicate of #34482

**Closed by vtjnash** 2020-02-25 16:10 UTC
Labels: bug, optimizer

**Comment by maleadt** [comment] 2020-02-25 16:12
> `reinterpret(T, nothing)` should fail consistently for all `T`, but we're in need of merging #34539

What's the recommended way to create an instance of a singleton type then? This for implementing the GPU version of `pointerset`; calling `T()` seems fragile (user might have defined a constructor, and I just want an instance to make codegen happy and generate a `ret void`).

**Comment by vtjnash** [comment] 2020-02-25 16:49
`unsafe_load` could generate one (or its wrappers, such as `Array{T,0}(undef)[]`), though in general the system doesn't like to materialize undefined values from just their types

**Comment by maleadt** [comment] 2020-02-25 17:02
I was trying to mimick `Base.pointerref` which does handle that case:

```
julia> foo(ptr) = Base.pointerref(ptr,1,1)
foo (generic function with 1 method)

julia> code_llvm(foo, Tuple{Ptr{Nothing}})

;  @ REPL[4]:1 within `foo'
define void @julia_foo_17046(i64) {
top:
  ret void
}
```
