### ISSUE TITLE
Implement `getpasswd`, fix up github two-factor authentication

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/julia#8228] opened 2014-09-04 06:45 UTC
~~#5252~~ #6668 added support for github two-factor authentication.  However, the implementation is a bit ugly: in the worst case, the user has to enter her password 4 times(!). 

The nicest way to handle this would probably be to implement a `getpasswd` (or `getpass`) function, which reads in a password without echoing, and then passes that onto curl via `curl -K -` (which reads a config file from stdin).

**Comment by tkelman** [comment] 2015-10-22 06:52
I think this should be reopened at PkgDev.jl. @wildart @jakebolewski how much of this is already functioning?

**Comment by stevengj** [comment] 2015-10-22 11:43
A `getpasswd` function might be more generally useful than just PkgDev.

**Comment by wildart** [comment] 2015-10-22 13:06
I use `getpass` in [libgit2/utils.jl](https://github.com/JuliaLang/julia/blob/53c2a2c9d5e9e7ccff3f30e83011d6959e79bf9f/base/libgit2/utils.jl#L15).

**Comment by stevengj** [comment] 2015-10-22 16:59
The man page for `getpass` says "This function is obsolete.  Do not use it."  It also doesn't exist on Windows as far as I can tell.  Python uses [their own implementation](https://github.com/python/cpython/blob/master/Lib/getpass.py), apparently.

**Comment by tkelman** [comment] 2015-10-23 05:07
Does newer libuv maybe have something for this?

**Comment by wildart** [comment] 2015-10-23 13:25
I think it is easier to write pure julia implementation.

**Comment by tkelman** [comment] 2015-10-23 13:29
> It also doesn't exist on Windows as far as I can tell.

It does not. @wildart please be more careful to not assume that a posix libc is present. Especially in interactive code that does not get tested on CI.

**Comment by davidanthoff** [comment] 2016-04-25 23:48
Can this please get a 0.5 label? Until this is fixed, there is a major regression for windows users, i.e. that they can't work with private package repos at all.

**Comment by Keno** [comment] 2016-04-26 00:25
Somebody with access to a windows machine please test the following:
```
diff --git a/base/libgit2/utils.jl b/base/libgit2/utils.jl
index b0c841b..66a9ab7 100644
--- a/base/libgit2/utils.jl
+++ b/base/libgit2/utils.jl
@@ -11,13 +11,20 @@ end
 
 isset(val::Integer, flag::Integer) = (val & flag == flag)
 
+using Base.Terminals: TTYTerminal, raw!
 function prompt(msg::AbstractString; default::AbstractString="", password::Bool=false)
-    msg = !isempty(default) ? msg*" [$default]:" : msg*":"
-    uinput = if password
-        bytestring(ccall(:getpass, Cstring, (Cstring,), msg))
+    msg = !isempty(default) ? msg*" [$default]: " : msg*": "
+    print(msg)
+    if password
+        t = TTYTerminal("xterm", STDIN, STDOUT, STDERR)
+        raw!(t, true)
+        try
+            uinput = rstrip(readuntil(STDIN,'\r'),'\r')
+        finally
+            raw!(t, false)
+        end
     else
-        print(msg)
-        chomp(readline(STDIN))
+        uinput = chomp(readline(STDIN))
     end
     isempty(uinput) ? default : uinput
 end
```
Tests for this are nontrivial, since it depends on the exact state of the tty which we can't really emulate.

**Comment by tkelman** [comment] 2016-04-26 00:32
Don't we want this not to echo what gets typed?

**Comment by Keno** [comment] 2016-04-26 00:33
Yes, that's what happens in raw mode.

**Comment by Keno** [comment] 2016-04-26 00:33
At least on unix.

**Comment by tkelman** [comment] 2016-04-26 00:34
Raw mode isn't really working on Windows then. And one or both of the `\r` above would have to be a `\n` to work in mintty.

**Comment by stevengj** [comment] 2016-04-26 17:40
Can we just use [_getch](https://msdn.microsoft.com/en-us/library/078sfkak.aspx) on Windows?

The more I look into this, the more I think we should just use `getpass` on Unix systems.   It's been marked as "obsolete" for over a decade, but since there is no simple alternative function it is still widely used.  If it ever disappears we can re-implement it, but why bother now?

**Comment by stevengj** [comment] 2016-04-26 17:59
The following works for me on Mac, GNU/Linux, and Windows, though it would probably be good to handle the backspace key and other niceties on Windows:
```jl
@windows_only function getpass(prompt::AbstractString)
    print(prompt)
    p = UInt8[]
    sizehint!(p, 128)
    while true
        c = ccall(:_getch, Cint, ())
        c < 16 && break
    end
    s = bytestring(p)
    fill!(p, 0)
    return s
end
@unix_only getpass(prompt::AbstractString) = pointer_to_string(ccall(:getpass, Cstring, (Cstring,), prompt), true)
```

**Comment by tkelman** [comment] 2016-04-27 01:02
That sounds like it'll be good enough for now. Certainly better than trying to ccall something that doesn't exist.

**Comment by stevengj** [comment] 2016-04-27 03:44
Here's a somewhat improved version, that handles backspace but ignores other control characters as well as arrow and function keys:
```jl
@windows_only function getpass(prompt::AbstractString)
    print(prompt)
    p = Array(UInt8, 128)
    plen = 0
    while true
        c = ccall(:_getch, UInt8, ())
        if c == 0xff || c == UInt8('\n') || c == UInt8('\r')
            break # EOF or return
        elseif c == 0x00 || c == 0xe0
            ccall(:_getch, UInt8, ()) # ignore function/arrow keys
        elseif c > 0x7f
            fill!(p, 0x00) # don't leave partial passwd in memory
            error("non-ASCII character $c")
        elseif c == UInt8('\b') && plen > 0
            plen -= 1 # delete last character on backspace
        elseif c >= 0x20
            p[plen += 1] = c
        end
    end
    s = bytestring(pointer(p), plen)
    fill!(p, 0) # don't leave password in memory
    return s
end
```
There is also a `_getwch` function that returns a `wint_t`, but it appears to be useless: I tried it out, an not only does it seem to ignore Unicode characters, but it mimics `_getch` in using `0xe0` to indicate an arrow key (making the latter indistinguishable from [U+00e0](http://www.fileformat.info/info/unicode/char/00e0/index.htm)).   In consequence, I think we can only support ASCII passwords on Windows.

**Comment by vtjnash** [comment] 2016-04-27 04:26
> Raw mode isn't really working on Windows then

i find that hard to believe since we depend on it for the REPL to print correctly

**Comment by tkelman** [comment] 2016-04-27 05:12
Ah, apologies, it looks like Keno's code does work when built into the sysimg but not when called from the repl. My bad.

**Comment by wildart** [comment] 2016-05-01 17:00
I wonder if `xterm` is installed on every platform or distro by default.

**Comment by nalimilan** [comment] 2016-05-01 20:18
> I wonder if xterm is installed on every platform or distro by default.

Just tried it, it's not even installed on my Fedora 23 box (on which I installed all kinds of packages over the years). So no.

**Comment by stevengj** [comment] 2016-05-06 03:04
Note that one of the things that we have to be very careful of is accidentally leaving extra copies of the password in memory.  e.g. @Keno's version calls `readuntil` (which calls [`jl_readuntil`](https://github.com/JuliaLang/julia/blob/63e0c605b05ea05f00b829fd3de793da31e36f57/src/sys.c#L269-L298)), and it looks like `jl_readuntil` can easily make extra copies.

`getpass` implementations presumably go to more care in this regard.  I tried to be careful in my Windows implementation above, too, although we should probably wrap it in a `try`/`finally` block to ensure that `fill!` is called... we certainly need to manually manage any buffers here.

Also, `getpass` has the nice feature of displaying a snazzy "key" icon in the prompt, at least on MacOS:
![image](https://cloud.githubusercontent.com/assets/2913679/15063064/e4b4c3fc-1314-11e6-9241-031889988ee5.png)
:smirk:

**Closed** 2016-05-23 20:49 UTC
Labels: needs-tests, packages, up for grabs
