### ISSUE TITLE
Assertion failure in type system

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#22592] opened 2017-06-28 04:04 UTC
On simonster/JLD2.jl@dfca1f0dc387b51d5f410a34dc20d2fee1ce1dae (current JLD2 master) with 0.6 debug build:

```
  | | |_| | | | (_| |  |  Version 0.6.1-pre.0 (2017-06-19 13:06 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit dcf39a1 (8 days old release-0.6)
|__/                   |  x86_64-apple-darwin16.5.0

julia> using JLD2
Assertion failed: (!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)), function check_ambiguous_visitor, file /usr/local/julia-release-0.6/src/gf.c, line 1129.

signal (6): Abort trap: 6
while loading /Users/simon/.julia/v0.6/JLD2/src/data.jl, in expression starting on line 914
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 3993141 (Pool: 3991608; Big: 1533); GC: 7
fish: 'julia-debug' terminated by signal SIGABRT (Abort)
```

The assertion failure occurs when loading [this line](https://github.com/simonster/JLD2.jl/blob/dfca1f0dc387b51d5f410a34dc20d2fee1ce1dae/src/data.jl#L914). Appears to operate properly with a non-debug build.

**Comment by simonster** [comment] 2017-07-09 03:58
Minimal reproducer:

```julia
f(::UnionAll) = nothing
f(::DataType) = nothing
f{T<:DataType}(::Type{T}) = nothing
```

**Comment by JeffBezanson** [comment] 2017-09-19 19:20
Seems to be fixed on master? @simonster could you confirm whether JLD2 works?

**Comment by timholy** [comment] 2017-12-16 09:29
On a debug build of current master, here's a case that triggers the same assertion:

```julia
module CVS

import Base: +

abstract type Colorant{T,N} end
abstract type Color{T, N} <: Colorant{T,N} end
abstract type AbstractRGB{T} <: Color{T,3} end

AbstractGray{T} = Color{T,1}

MathTypes{T,C} = Union{AbstractRGB{T},AbstractGray{T}}

(+)(a::AbstractGray{S}, b::AbstractGray{T}) where {S,T} = 1
(+)(c::AbstractGray) = c
(+)(a::MathTypes, b::MathTypes) = (+)(promote(a, b)...)

end
```

It's a stripped-down version of ColorVectorSpace.

**Comment by timholy** [comment] 2017-12-16 09:59
It seems to be a problem of type specificity between the unary variant and the `MathTypes` variant:
```
julia: /home/tim/src/julia-1.0/src/gf.c:1152: check_ambiguous_visitor: Assertion `!jl_subtype((jl_value_t*)sig, (jl_value_t*)type)' failed.

Thread 1 "julia" received signal SIGABRT, Aborted.
0x00007ffff6b1e428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) f 4
#4  0x00007ffff7519df2 in check_ambiguous_visitor (oldentry=0x7fffea3562c0, closure0=0x7fffffffb890) at /home/tim/src/julia-1.0/src/gf.c:1152
1152            assert(!jl_subtype((jl_value_t*)sig, (jl_value_t*)type));
(gdb) call jl_type_morespecific(type, sig)
$1 = 0
(gdb) call jl_type_morespecific(sig, type)
$2 = 1
(gdb) call jl_(closure->newentry)
TypeMapEntry(sig=Tuple{typeof(CVS.plus), Union{CVS.AbstractRGB{T}, CVS.Color{T, 1}} where T, Union{CVS.AbstractRGB{T}, CVS.Color{T, 1}} where T}, simplesig=nothing, guardsigs=svec(), min_world=24860, max_world=-1, func=CVS.plus(...), isleafsig=false, issimplesig=false, va=false, next=↩︎
  TypeMapEntry(sig=Tuple{typeof(CVS.plus), CVS.Color{T, 1} where T}, simplesig=nothing, guardsigs=svec(), min_world=24859, max_world=-1, func=CVS.plus(...), isleafsig=false, issimplesig=false, va=false, next=↩︎
  TypeMapEntry(sig=Tuple{typeof(CVS.plus), CVS.Color{T, 1} where T, CVS.Color{T, 1} where T}, simplesig=nothing, guardsigs=svec(), min_world=24858, max_world=-1, func=CVS.plus(...), isleafsig=false, issimplesig=false, va=false, next=↩︎
  nothing)))
(gdb) call jl_(closure->newentry->next->sig)
Tuple{typeof(CVS.plus), CVS.Color{T, 1} where T}
(gdb) call jl_(type)
Tuple{typeof(CVS.plus), Union{CVS.AbstractRGB{T}, CVS.Color{T, 1}} where T, Union{CVS.AbstractRGB{T}, CVS.Color{T, 1}} where T}
(gdb) call jl_type_morespecific(type, closure->newentry->next->sig)
$3 = 1
```
So it seems that the method table is being sorted like this (in order of "most specific to least specific"):
```julia
plus(a::MathTypes, b::MathTypes) = plus(promote(a, b)...)
plus(c::AbstractGray) = c
plus(a::AbstractGray, b::AbstractGray) = 1
```
As evidence that this is correct, all I have to do is change the order of their definition to
```julia
plus(a::AbstractGray, b::AbstractGray) = 1
plus(a::MathTypes, b::MathTypes) = plus(promote(a, b)...)
plus(c::AbstractGray) = c
```
and then I don't trigger the assertion anymore.

**Comment by JeffBezanson** [comment] 2018-09-11 22:45
I believe this was fixed a while ago; @simonster please reopen if you're still able to reproduce this. The ColorVectorSpace issue is separate, #29136.

**Closed by JeffBezanson** 2018-09-11 22:45 UTC
Labels: bug, types and dispatch
