### ISSUE TITLE
incorrect dispatch with invoke on methods with default arguments

### ISSUE THREAD

**Issue by skariel** [JuliaLang/julia#9938] opened 2015-01-27 12:56 UTC
see image below, this works correctly if no keyword arguments are used. This is causing the current test failures of #9575 

![screenshot from 2015-01-27 14 53 57](https://cloud.githubusercontent.com/assets/2347816/5918734/a7a2bab2-a634-11e4-8247-0b310dca56fb.png)

**Comment by simonster** [comment] 2015-01-27 17:23
This makes some sort of sense based on the implementation of default arguments. `f(i::Number, o::Int64=1) = println("Number")` is eventually lowered to:

```julia
f(i::Number, o::Int64) = println("Number")
f(i::Number) = f(i, 1)
```

which is why `f` above has 4 methods, not 2. So `invoke` calls `f(::Number)`, but then f(::Number)` dispatches to `f(::Int64, ::Int64)` instead of `f(::Number, ::Int64)`. I think there has been some discussion of this in another issue but I can't find it. We could potentially lower to:

```julia
f(i::Number, o::Int64) = println("Number")
f(i::Number) = invoke(f, (Number, Int64), i)
```

although we'd need #9642 for this to perform well, and it would be a breaking change, since a different method would be called for:

```julia
f(i::Int64, o::Int64) = println("Int64")
f(i::Number, o::Int64=1) = println("Number")
f(1)
```

For #9575 it seems like the tests that use `invoke` could be changed to pass the default arguments so that the appropriate method gets dispatched.

**Comment by vtjnash** [comment] 2015-01-27 18:54
i believe @simonster's solution is correct. might need to search back through the issues to make sure there wasn't specific concerns with it. i think the previous concern was that it would change the behavior of:
```julia
f(x::Int, y::String=2) = 1
f(x::Int, y) = 2
```
which is valid under the current rules (where `f(1)` would return 1)

**Comment by skariel** [comment] 2015-01-27 18:59
@simonster good point, I changed the test it works now.

**Comment by JeffBezanson** [comment] 2015-01-27 19:48
More or less a duplicate of #7357. In that issue the solution of lowering default arguments to use `invoke` is mentioned.

**Comment by JeffBezanson** [comment] 2015-04-21 18:13
Closing as dup.

**Closed by JeffBezanson** 2015-04-21 18:13 UTC
Labels: breaking, decision
