### ISSUE TITLE
Cannot add SymTridiagonal matrices based on sparse vectors

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/julia#46355] opened 2022-08-15 16:52 UTC
This fails:
```Julia
julia> using LinearAlgebra
julia> using SparseArrays
julia> A = SymTridiagonal(sparsevec(Int[1]), sparsevec(Int[]))
julia> A + A
ERROR: MethodError: no method matching SymTridiagonal(::SparseVector{Int64, Int64}, ::Vector{Int64})
```

I assume the problem is that `SymTridiagonal` matrices accidentally convert the internal representation of the off-diagonal elements to a dense vector.

I am using
```
julia> versioninfo()
Julia Version 1.9.0-DEV.1130
Commit c80316e125* (2022-08-15 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin21.6.0)
  CPU: 16 × Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, skylake)
  Threads: 8 on 16 virtual cores
```

**Comment by jishnub** [comment] 2022-08-16 10:36
This works on `v1.7.3`, but not on higher versions
```julia
julia> A + A
1×1 SymTridiagonal{Int64, SparseVector{Int64, Int64}}:
 2

julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_EDITOR = subl
```

**Comment by inkydragon** [comment] 2022-08-16 13:14
- ✔️ 1.7.2 (2022-02-06)
- ✔️ 1.8.0-DEV.682 (2021-10-08) f2080d57c8
- ❌ 1.8.0-DEV.683 (2021-10-08) 146de38b40
    https://github.com/JuliaLang/julia/pull/42472  cc: @mcognetta
- ❌ 1.8.0-beta1 (2022-02-23)
- ❌ 1.8.0-rc4 (2022-08-08)

**Comment by mcognetta** [comment] 2022-08-16 14:00
The issue is that adding `@view`s of SparseArrays makes it dense.

https://github.com/JuliaLang/julia/blob/ec98087cbf19bac26f6be05df9282746b0cffe78/stdlib/LinearAlgebra/src/tridiag.jl#L207

https://github.com/JuliaLang/julia/blob/ec98087cbf19bac26f6be05df9282746b0cffe78/stdlib/LinearAlgebra/src/LinearAlgebra.jl#L449-L453

```julia
julia> z = @view sparse([1, 2, 3])[1:3]
3-element view(::SparseVector{Int64, Int64}, 1:3) with eltype Int64:
 1
 2
 3

julia> z + z
3-element Vector{Int64}:
 2
 4
 6
```

I will see what can be done quickly.

**Comment by mcognetta** [comment] 2022-08-16 14:27
Ok I have a fix but I am not quite sure how to commit to SparseArrays now that it is its own package.

**Comment by jishnub** [comment] 2022-08-16 14:42
Just open a PR on the `SparseArray` repo?

**Comment by mcognetta** [comment] 2022-08-16 14:59
I meant that a copy of SparseArrays still shows up in the Julia stdlib directory when opening it in VSCode, etc. but changes to it didn't get tracked by git.

Anyway: https://github.com/JuliaSparse/SparseArrays.jl/pull/225

**Comment by inkydragon** [comment] 2022-08-16 15:27
@mcognetta After the pr is merged, just ask someone to [BumpStdlibs](https://github.com/JuliaLang/BumpStdlibs.jl). like #46266

**Comment by SobhanMP** [comment] 2022-08-16 21:23
Is there any reason the diagonals of SymTridiagonal cannot have different types?

**Comment by mcognetta** [comment] 2022-08-17 05:03
I think that it is possible, but that is a much bigger change than necessary to fix this (all structured matrix types would have to be updated, and `Tridiagonal` could have 3 different types. I haven't heard of much need for this, but that's not necessarily an end-all reason for not doing it).

**Closed** 2023-09-09 16:35 UTC
Labels: regression, linear algebra
