### ISSUE TITLE
Rename `getindex` and `setindex!` to operator form

### ISSUE THREAD

**Issue by timholy** [JuliaLang/julia#42525] opened 2021-10-06 21:00 UTC
A discussion on slack suggested that `getindex` is confusing and should perhaps be called `getatindex` (which is not quite as readable). But if we could write this in operator form
```julia
julia> Base.:(==)
== (generic function with 165 methods)

julia> Base.:([])
ERROR: syntax: invalid syntax "Base.[]" around REPL[2]:1
Stacktrace:
 [1] top-level scope
   @ REPL[2]:1
```
(it's good that it throws an error now, that means it's available) then we could add a custom array type and define
```julia
Base.:([])(A::MySpecialArray, i::Int) = ...
```

It would seem this doesn't even have to wait for Julia 2.0; that could be when we delete the older names.

**Comment by mkitti** [comment] 2021-10-06 22:10
> But like... Why?

The name `getindex` is counterintuitive. Coming from other language conventions, one might expect this to return an `index` rather than the value at the `index` given as an argument. In other circumstances, such as `getindex(::RefValue)`, there is no `index` argument at all.

In the near term, it may improve the legibility of code if this was more clearly connected with the square bracket syntax using an alias.

Could we turn `[]` into an operator as in C++ without being enormously disruptive?

**Comment by haampie** [comment] 2021-10-07 15:48
`.:([])` looks more like ascii art than a reference to a function to me :grimacing:. even C++'s weird `operator[]` is more humanly decodable than this

**Comment by mkitti** [comment] 2021-10-08 00:12
I dug and found the inception of the name `getindex`. It came as the counterpart to `setindex!`.
https://github.com/JuliaLang/julia/issues/907#issuecomment-14653861

Consider that we also have `getproperty`, and `getfield`, which take the property name and field name as the second argument. Being more verbose, these could be `getbypropertyname` or `getbyfieldname` just as `getindex` could be `getbyindex`. A method named `getvalue` could apply to an element that is a member of an indexed array, a property, or a field, thus `getvalue` seems ambiguous. In this sense, there seems to be a consistent habit of dropping prepositions and being brief for the method names `getindex`, `getproperty`, and `getfield`.

`getkey` seems out of place out of the `getX` names because its meaning is actually read literally. It's not `getbykey`, which is just `get`.

**Comment by haampie** [comment] 2021-10-08 00:23
What alias would you propose for setindex! then for symmetry?

**Comment by BioTurboNick** [comment] 2021-10-09 01:27
> I dug and found the inception of the name `getindex`. It came as the counterpart to `setindex!`. [#907 (comment)](https://github.com/JuliaLang/julia/issues/907#issuecomment-14653861)
> 
> Consider that we also have `getproperty`, and `getfield`, which take the property name and field name as the second argument. Being more verbose, these could be `getbypropertyname` or `getbyfieldname` just as `getindex` could be `getbyindex`. A method named `getvalue` could apply to an element that is a member of an indexed array, a property, or a field, thus `getvalue` seems ambiguous. In this sense, there seems to be a consistent habit of dropping prepositions and being brief for the method names `getindex`, `getproperty`, and `getfield`.
> 
> `getkey` seems out of place out of the `getX` names because its meaning is actually read literally. It's not `getbykey`, which is just `get`.

You could argue that the value returned by `getproperty` and `getfield` is the property/field.

That is, `property name:property` as `field name:field` and `key name:key`... and as you note, `index:element`.

Seen that way, `getelement` fits in nicely.

**Comment by mkitti** [comment] 2021-10-09 03:03
> while `getelement` is not bad, the mere fact it will be breaking change (at some point) is a huge cost. Besides, the function names (IMO) just need to be reasonable, people don't have to "get it perfectly" the first time they see it. In fact, `getindex` emphasizes the fact that it's indexable (not keyed by name like `property` or `field`), which is a nice association.

I am not advocating for deprecation of `getindex`. I, however, do think an alias could be helpful and provide clarity, especially in circumstances where the element being retrieved is **not** indexable. I also do not follow the "not keyed" point since we use `getindex` to define methods to retrieve values from a dictionary using a key.

**Comment by mkitti** [comment] 2021-10-09 08:01
Could we add some kind of facility to deal with brackets in general? `bracket"[]"` for this issue or `bracket"⟨⟩" as in #35288?

**Comment by bramtayl** [comment] 2021-10-10 12:50
How about `atindex` for `getindex` and `toindex!` for `setindex!`?

**Comment by mkitti** [comment] 2021-10-10 16:22
Let's just close this bike shed.
* The issue is more complicated than defining a new operator.
* A `getvalue`/`setvalue!` PR or `getelement`/`setelement!` PR can stand on its own and does not really address the original issue as stated by Tim.
* Since brackets are not operators, we should decide how to address brackets before revisiting this.

**Closed** 2021-10-10 21:44 UTC
