### ISSUE TITLE
Compat update hangs

### ISSUE THREAD

**Issue by nimadehghani** [JuliaLang/julia#15841] opened 2016-04-12 14:34 UTC
Hi,
When I run Pkg.update(), it starts the update but when it reaches Compat, it does not move forward anymore. Then I interrupt and it "rolls bacl ColorType" (see below; In Compat's link, it mentions only v 0.07.12. While the attempted update is trying to fetch 0.07.13. ). This happened under v 4.3. I upgraded the julia core to 4.5 and still face the same issue. Any idea how to fix this or bypass this Compat issue?
Thank

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Upgrading ColorTypes: v0.2.1 => v0.2.2
INFO: Upgrading ColorVectorSpace: v0.1.1 => v0.1.2
INFO: Upgrading Compat: v0.7.12 => v0.7.13
^CINFO: Rolling back ColorVectorSpace from v0.1.2 to v0.1.1
INFO: Rolling back ColorTypes from v0.2.2 to v0.2.1

**Comment by jiahao** [comment] 2016-05-16 23:38
Duplicate of #14616

**Closed by jiahao** 2016-05-16 23:38 UTC
