### ISSUE TITLE
Stackoverflow in ovious_subtype due to splatting

### ISSUE THREAD

**Issue by bienpierre** [JuliaLang/julia#39826] opened 2021-02-25 17:49 UTC
Hello,

I was expected an  "error" syntax message with the following command, otherwise it filled the memory until system crashed or "interrupt execution" is proceed via htop or CTrL+C:
![Capture d'écran du 2021-02-25 15 16 19](https://user-images.githubusercontent.com/50803547/109172483-1d3ead00-7783-11eb-8a7e-90906cf5ade3.png)

Regards

**Comment by simeonschaub** [comment] 2021-02-25 18:00
I don't see why this should error, since it's a valid thing to do, but we strongly discourage splatting large arrays, exactly because it causes excessive compile times.

**Comment by bienpierre** [comment] 2021-02-25 18:31
Ok I see...  
I also tried this one. Is it also due to excessive compile time?
![Capture d'écran du 2021-02-25 19 26 05](https://user-images.githubusercontent.com/50803547/109199287-8cc29580-779f-11eb-835d-8cf290fb0aee.png)
regards

**Comment by simeonschaub** [comment] 2021-02-25 18:39
Hmm, that does look like a more serious issue. I don't think this is related

**Comment by simeonschaub** [comment] 2021-02-25 18:52
I can reproduce on nightly and 1.5. I would not have expected a length of 2050 to produce a Stackoverflow in this example, but not 100% sure there is something to be done here.

**Comment by Keno** [comment] 2021-02-25 19:49
Yeah, the system doesn't currently like tuples this long. Fixing that is #31681, so closing as a dup.

**Closed by Keno** 2021-02-25 19:49 UTC
