### ISSUE TITLE
serachsortedfirst, searchsortedlast, searchsorted unexpected behavior

### ISSUE THREAD

**Issue by KlausC** [JuliaLang/julia#35381] opened 2020-04-06 16:06 UTC
I would like to do a binary search without having to materialize the array:
I would prefer not to build the array, because my function is not i->i^2 but expensive to calculate.

```
searchsortedfirst([i^2 for i in 1:10], 25) # is working
searchsortedfirst((i^2 for i in 1:10), 25) # no method
searchsortedfirst(1:10, 25, by=i->i^2) # does not what I had expected
```
It looks like an implementation error, that the `by=transform` is applied to the value to compare with.
There are at least 2 arguments against the current implementation:

1. It forces the user to pre-calculate an abstract vector with the transformed values
2. the transform of the comparison value is performed as many times as comparisons are made in the algorithm
3. the documentation does not suggest, that the comparison value is treated this way

**Comment by KlausC** [comment] 2020-04-06 16:39
This seems to be a duplicate of #9429, which has not been resolved.
There was a proposal by @JeffBezanson to introduce a new keyword argument to avoid a breaking change. (Actually I don't understand why we kept a not-useful feature in the code-base for so long time).

I propose now to change the documentation and add the new keyword `transformation`.

**Comment by mbauman** [comment] 2020-05-04 20:29
Duplicate of #9429

**Closed by mbauman** 2020-05-04 20:29 UTC
