### ISSUE TITLE
`minimum()` (`foldl(min, ary)`) seems to be much slower than it can be

### ISSUE THREAD

**Issue by Moelf** [JuliaLang/julia#56353] opened 2024-10-27 16:31 UTC
```julia
julia> function normal_findmin(dij)
           vmin = Inf
           for x in dij
               vmin = ifelse(x < vmin, x, vmin)
           end
           return vmin
       end
julia> a = rand(120)

julia> @be minimum($a)
Benchmark: 2911 samples with 71 evaluations
 min    376.620 ns
 median 412.183 ns
 mean   439.258 ns
 max    1.319 μs

julia> @be normal_findmin($a)
Benchmark: 2923 samples with 761 evaluations
 min    37.783 ns
 median 38.403 ns
 mean   40.277 ns
 max    130.361 ns
```

(Handling `isempty()` and `init` isn't enough to account for the difference)

**Comment by giordano** [comment] 2024-10-27 16:34
Duplicate of #38558

**Comment by Moelf** [comment] 2024-10-27 16:37
I think this is not a 100% duplicate. Yes, solving #38558 will solve this, but we don't need to solve #38558 to solve this -- we can imagine specialize `minimum/maximum/maxia` to at least make them faster?

**Comment by jakobnissen** [comment] 2024-10-28 08:59
Your `normal_findmin` does not take NaN into account, and therefore compiles to more efficient machine code.

**Closed** 2024-10-28 09:01 UTC
Labels: performance, fold

**Comment by Moelf** [comment] 2024-10-28 09:22
Actually on x8664 it's the opposite, https://discourse.julialang.org/t/ifelse-x-y-x-y-much-faster-than-min/121826

**Comment by Moelf** [comment] 2024-10-28 09:25
I will note that right now on aarch64 using min is actually faster, not slower, so maybe still something to be done for x86
