### ISSUE TITLE
Segfault on Power9 HPC when built from source

### ISSUE THREAD

**Issue by adamryczkowski** [JuliaLang/julia#28984] opened 2018-08-31 13:47 UTC
To reproduce:

1. Clone the current (`804d12ebe3801f7faf8cea234ffe6ec2452443c8`) Julia repo.
2. Build with `make`
3. Run `./julia`
4. Type `import Pkg` and then `Pkg.update()`.

```
/julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.unknown (2018-08-31)
 _/ |\__'_|_|_|\__'_|  |  Commit 804d12e (0 days old master)
|__/                   |

julia> import Pkg

julia> Pkg.update()
   Cloning default registries into /home/openpower.student18/.julia/registries
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"

signal (11): Segmentation fault
in expression starting at no file:0
set_ssl_cert_locations at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/error.jl:0
initialize at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/LibGit2.jl:990
ensure_initialized at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/LibGit2.jl:967 [inlined]
Type at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/config.jl:50
Type at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/config.jl:50 [inlined]
Type at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/types.jl:1340 [inlined]
#CredentialPayload#32 at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/types.jl:1350 [inlined]
Type at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/types.jl:1350 [inlined]
#clone#131 at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/LibGit2/src/LibGit2.jl:559
unknown function (ip: 0x7fff60538347)
jl_fptr_trampoline at /home/openpower.student18/tmp/julia/src/gf.c:1841
jl_apply_generic at /home/openpower.student18/tmp/julia/src/gf.c:2196
jl_apply at /home/openpower.student18/tmp/julia/src/julia.h:1558 [inlined]
jl_invoke at /home/openpower.student18/tmp/julia/src/gf.c:56
#clone at ./none:0 [inlined]
#clone#2 at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/GitTools.jl:94
jl_fptr_args at /home/openpower.student18/tmp/julia/src/gf.c:1851
jl_fptr_trampoline at /home/openpower.student18/tmp/julia/src/gf.c:1841
jl_apply_generic at /home/openpower.student18/tmp/julia/src/gf.c:2196
jl_apply at /home/openpower.student18/tmp/julia/src/julia.h:1558 [inlined]
jl_invoke at /home/openpower.student18/tmp/julia/src/gf.c:56
#50 at ./none:0
shred! at ./secretbuffer.jl:184
#registries#49 at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:923
jfptr_#registries#49_9962 at /home/openpower.student18/tmp/julia/usr/lib/julia/sys.so (unknown line)
jl_invoke at /home/openpower.student18/tmp/julia/src/gf.c:42
registries at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/Types.jl:907 [inlined]
macro expansion at ./logging.jl:307 [inlined]
update_registry at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:96
#up#31 at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:166
unknown function (ip: 0x7fff605319f3)
jl_fptr_trampoline at /home/openpower.student18/tmp/julia/src/gf.c:1841
jl_apply_generic at /home/openpower.student18/tmp/julia/src/gf.c:2196
jl_apply at /home/openpower.student18/tmp/julia/src/julia.h:1558 [inlined]
jl_invoke at /home/openpower.student18/tmp/julia/src/gf.c:56
up at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:158 [inlined]
#up#30 at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:154 [inlined]
up at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:154 [inlined]
#up#27 at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:151 [inlined]
up at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/Pkg/src/API.jl:151
jl_fptr_args at /home/openpower.student18/tmp/julia/src/gf.c:1851
jl_fptr_trampoline at /home/openpower.student18/tmp/julia/src/gf.c:1841
jl_apply_generic at /home/openpower.student18/tmp/julia/src/gf.c:2196
do_call at /home/openpower.student18/tmp/julia/src/interpreter.c:324
eval_value at /home/openpower.student18/tmp/julia/src/interpreter.c:430
eval_stmt_value at /home/openpower.student18/tmp/julia/src/interpreter.c:363 [inlined]
eval_body at /home/openpower.student18/tmp/julia/src/interpreter.c:684
jl_interpret_toplevel_thunk_callback at /home/openpower.student18/tmp/julia/src/interpreter.c:803
unknown function (ip: 0xfffffffffffffffe)
unknown function (ip: 0x7fff887a635f)
unknown function (ip: (nil))
jl_interpret_toplevel_thunk at /home/openpower.student18/tmp/julia/src/interpreter.c:812
jl_toplevel_eval at /home/openpower.student18/tmp/julia/src/toplevel.c:792
jl_toplevel_eval_in at /home/openpower.student18/tmp/julia/src/builtins.c:622
eval at ./boot.jl:319
jl_fptr_args at /home/openpower.student18/tmp/julia/src/gf.c:1851
jl_apply_generic at /home/openpower.student18/tmp/julia/src/gf.c:2196
eval_user_input at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:85
macro expansion at /home/openpower.student18/tmp/julia/usr/share/julia/stdlib/v1.1/REPL/src/REPL.jl:117 [inlined]
#28 at ./task.jl:259
jl_fptr_args at /home/openpower.student18/tmp/julia/src/gf.c:1851
jl_apply_generic at /home/openpower.student18/tmp/julia/src/gf.c:2196
jl_apply at /home/openpower.student18/tmp/julia/src/julia.h:1558 [inlined]
start_task at /home/openpower.student18/tmp/julia/src/task.c:271
jl_set_base_ctx at /home/openpower.student18/tmp/julia/src/task.c:291
Allocations: 858046 (Pool: 857638; Big: 408); GC: 0
Segmentation fault
```

I will have access to this architecture (PPC64 little-endian) only until monday.

**Comment by ViralBShah** [comment] 2018-08-31 15:15
While it used to work in an earlier release, this is currently an unsupported architecture.

**Comment by KristofferC** [comment] 2018-08-31 15:33
Crashes in Libgit2 initialization.

**Comment by vchuravy** [comment] 2018-08-31 16:11
Likely duplicate of #27007

**Closed** 2018-08-31 16:12 UTC
Labels: power
