### ISSUE TITLE
MethodError when add '@threads' to 'for' loop

### ISSUE THREAD

**Issue by aqzas** [JuliaLang/julia#30364] opened 2018-12-12 14:12 UTC
Hi guys, I meet a problem when I trying to paralleling my code using multi-thread

``` Julia
for (lgt,val) in gp
     absorb!(lgt, val, the_ERR)
end
```

to 

```Julia
Threads.@threads for (lgt,val) in gp
        absorb!(lgt, val, the_ERR)
    end
```

gp is a Dict{Int, Array{Myread,1}}()
Myread is my custom struct
function of absorb is complicate to explain, but generally it will filter out some item in the Array according to the lgt variable

Everything goes well without @threads, but after add @threadand a MethodError will occur and output data in val, like this

![wx20181212-221316](https://user-images.githubusercontent.com/10047675/49875109-27528a80-fe5b-11e8-9b69-66169387c3d4.png)

**Comment by KristofferC** [comment] 2018-12-12 16:37
This doesn't look like a question, it looks like a reported crash in the optimizer or something.

**Comment by yuyichao** [comment] 2018-12-12 16:45
No that's impossible. (By which I mean the thing to detect is the method error.......... You can generate code to try to predict the error (check method applicability for example) but for the **macro** to detect it is impossible.)

**Comment by jpsamaroo** [comment] 2018-12-12 18:02
@aqzas would you be able to craft a Minimum Working Example so that we can debug this on our local systems? It would also be great if you could post that error you got as text (instead of an image) so that we can see the whole thing.

**Comment by yuyichao** [comment] 2018-12-12 18:39
You should get that error if you run any thread loop on dict.

**Comment by aqzas** [comment] 2018-12-13 01:22
@yuyichao Thank for you reply, I vaguely feel that's the problem before

@jpsamaroo 
Though the problem is solved as @yuyichao said, here is the example you can reproduce it.
```Julia
gp = Dict(
1=>[1,2,3,4,5,6,7],
2=>[1,2,3,4,5,6,7],
3=>[1,2,4,5,3,5,6,36]
)

function absorb!(key, val)
    filter!(x->x>key, val)
    return
end

Threads.@threads for (key, val) in gp
    absorb!(key, val)
end

@show gp
```

**Comment by BCRARL** [comment] 2019-03-11 13:25
Currently the documentation of @threads doesn't mention these limitations.  A literal reading of the documentation suggests that any iterator is possible and in particular that an iterator over a finite collection will work. I had the same issue using `eachrow` in 1.1.0

**Comment by StefanKarpinski** [comment] 2019-03-11 18:53
Best to quote `@threads` so that you don't ping the GitHub user who has that handle.

**Comment by JeffBezanson** [comment] 2019-06-01 21:46
The error reporting should be better here now but we should add this limitation to the documentation for `@threads`.

**Comment by JeffBezanson** [comment] 2019-06-03 19:25
Also duplicate of #18263.

**Comment by KristofferC** [comment] 2019-10-15 14:18
Closing as dup.

**Closed by KristofferC** 2019-10-15 14:18 UTC
Labels: doc, multithreading
