### ISSUE TITLE
Rename default branch from master to main

### ISSUE THREAD

**Issue by LilithHafner** [JuliaLang/julia#51819] opened 2023-10-22 15:03 UTC
We should rename our default branch from master to main in line with social norms and standard git tooling.
NumPy and CPython (May 2021) already switched and haven't spontaneously combusted.
Github tooling support is great now.

**Comment by jishnub** [comment] 2023-10-22 15:54
Duplicate of https://github.com/JuliaLang/julia/issues/40316?

**Comment by jakobnissen** [comment] 2023-10-23 05:17
Closing as duplicate. This was to be discussed among the JuliaLang members, and since the branch name hasn't changed, we can assume a decision has been made.
Pinging @ViralBShah just in case.

**Closed by jakobnissen** 2023-10-23 05:17 UTC

**Comment by oxinabox** [comment] 2023-10-23 08:38
A case could be made that the situation has changed in the 2 years since then, in terms of e.g. github releasing tooling that means this doesn't break open PRs etc.
And that the general shift has been significantly towards main.
So it seems it is likely worth revisiting that decision,  and confirming if we still believe that it is better to be on `master` than `main`.

However, discussion can not happen on that issue, given it is locked.

**Comment by KristofferC** [comment] 2023-10-23 08:43
> in terms of e.g. github releasing tooling that means this doesn't break open PRs etc.

I think that was the case even at that date.


> However, discussion can not happen on that issue, given it is locked.

Good point, since nothing has changed here I'll lock this on the same merit as https://github.com/JuliaLang/julia/issues/40316

**Comment by ViralBShah** [comment] 2023-10-24 13:08
While there is no specific plan to work on this (given the tremendous effort it takes to keep CI running), I wanted to repeat what @KristofferC said in https://github.com/JuliaLang/julia/issues/40316#issuecomment-1775574786 - a fix would be welcome if someone wanted to work on this to address it in a general way, and help contribute to our CI tooling.
