### ISSUE TITLE
begin not defined under @less

### ISSUE THREAD

**Issue by jtrakk** [JuliaLang/julia#42880] opened 2021-10-31 21:14 UTC
This doesn't seem right:

```jl
julia> [1][begin:end]
1-element Vector{Int64}:
 1

julia> @less [1][begin:end]
ERROR: UndefVarError: begin not defined
Stacktrace:
 [1] top-level scope
   @ REPL[16]:1
```

Julia 1.6.1

**Comment by fredrikekre** [comment] 2021-11-01 16:37
Duplicate of https://github.com/JuliaLang/julia/issues/37379

**Closed by fredrikekre** 2021-11-01 16:37 UTC
