### ISSUE TITLE
Apple M1 Julia 1.8-rc1 init crash

### ISSUE THREAD

**Issue by gnuille** [JuliaLang/julia#45709] opened 2022-06-16 14:55 UTC
## Context
I am using an Apple M1. `versioninfo()` output:
```
Julia Version 1.8.0-rc1
Commit 6368fdc6565 (2022-05-27 18:33 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```
## Issue
When linking the julia library and calling `jl_init_threading` or `jl_init`, for example in python:
```python
import ctypes
lib = ctypes.CDLL("/Applications/Julia-1.8.app/Contents/Resources/julia/lib/libjulia.1.8.dylib")
lib.jl_init()
```
The internal symbol `jl_n_threads` seems to not be accessible  from the `Threads.nthreads()` method.
```
fatal: error thrown and no exception handler available.
ErrorException("could not load symbol "jl_n_threads":
dlsym(RTLD_DEFAULT, jl_n_threads): symbol not found")
ijl_errorf at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_dlsym at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_load_and_lookup at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
nthreads at ./threadingconstructs.jl:23 [inlined]
__preinit_threads__ at ./task.jl:706
jfptr___preinit_threads___50438 at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
ijl_apply_generic at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
_finish_julia_init at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
julia_init at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ijl_init at /Applications/Julia-1.8.app/Contents/Resources/julia/lib/julia/libjulia-internal.1.8.dylib (unknown line)
ffi_call_SYSV at /usr/lib/libffi.dylib (unknown line)
```
It happens in the `_finish_julia_init` method which suggests that the `jl_init` has previosuly invoked the `jl_init_threading` which modifies the `jl_n_threads` symbol and did not crash.

Any hints? The issue seems related to: https://github.com/JuliaLang/julia/pull/38938/files 
This is needed for the [juliacall](https://github.com/cjdoris/PythonCall.jl) python module to work.

Thanks!

**Comment by giordano** [comment] 2022-06-16 17:07
For the record, this is a cross post from https://github.com/cjdoris/PythonCall.jl/issues/185, which was a duplicate of https://github.com/cjdoris/PythonCall.jl/issues/175

> Any hints? The issue seems related to: [#38938 (files)](https://github.com/JuliaLang/julia/pull/38938/files)

What makes you think so?

**Comment by vtjnash** [comment] 2022-06-16 17:21
This might mean it is getting opened with RTLD_LOCAL, while libjulia expects to be opened as RTLD_GLOBAL?

**Comment by giordano** [comment] 2022-06-16 17:30
Works for me with `ctypes.RTLD_GLOBAL`:
```py
In [1]: import ctypes
   ...: lib = ctypes.CDLL("/Users/mose/repo/julia/usr/lib/libjulia.1.9.dylib", mode= ctypes.RTLD_GLOBAL)
   ...: lib.jl_init()
Out[1]: 7700480
```

Indeed, the default mode is local, not global:
```py
In [2]:  ctypes.DEFAULT_MODE
Out[2]: 4

In [3]:  ctypes.RTLD_GLOBAL
Out[3]: 8

In [4]:  ctypes.RTLD_LOCAL
Out[4]: 4
```

**Comment by gnuille** [comment] 2022-06-17 08:53
I have performed some tests and indeed is now working, thanks! From my understanding this issue should be closed?

**Closed** 2022-06-17 09:09 UTC
Labels: bug, apple silicon
