### ISSUE TITLE
Build error in git Julia 1.9.0-1.9.3

### ISSUE THREAD

**Issue by domr2695** [JuliaLang/julia#51821] opened 2023-10-22 18:26 UTC
In Git Julia releases 1.9.0-1.9.3, "./deps/checksums/openblas" states :
openblas-b89fb708caa5a5a32de8f4306c4ff132e0228e9a.tar.gz/sha512/00e7bde49525c2c28bf07b47290e00b53bff446be63f09e90c51724c6350e5ddc90f5a071ae6de057b3fbb107060e70bf16683fcefcf48ae37ba1d0758be553b

But "sha512sum " on this archive gives :

7f52721efcc7c5fd146526463c8856c33d3f2f36cbded55ac5320e1c5211da0c549d25385ff74579907efe00b340c187688440fbb3a56b9ada471ada34ddef72

And if you put it in "./deps/checksums/openblas" in place of the incorrect checksum, then the Julia build goes fine.

**Comment by giordano** [comment] 2023-10-22 23:41
Duplicate of #51408

**Closed by giordano** 2023-10-22 23:41 UTC
Labels: build
