### ISSUE TITLE
infix function definition should be disallowed

### ISSUE THREAD

**Issue by adienes** [JuliaLang/julia#49972] opened 2023-05-27 15:39 UTC
I cannot imagine any cases where the benefit is so great that it is worth all the potential confusion this can cause.

Just imagine someone typos `==` to `=` somewhere and sets the wrong flag
```
julia> x = (a - b = c)
- (generic function with 1 method)
```

**Comment by fredrikekre** [comment] 2023-05-27 15:42
Duplicate of #15483

**Closed by fredrikekre** 2023-05-27 15:42 UTC

**Comment by adienes** [comment] 2023-05-27 15:46
I don't think it's a duplicate --- that issue is tagged `docs` and `needs docs`, this issue about removal, which would be an actual (breaking) functionality change. Can at least one of the two be tagged for 2.0 so that there is sure to be discussion about whether the notation should exist at all?
