### ISSUE TITLE
Construction of inhomogenous arrays seems to be inconsistent

### ISSUE THREAD

**Issue by vchuravy** [JuliaLang/julia#18395] opened 2016-09-07 18:40 UTC
This came up in Alans class today.
Depending on the position of values in an `Any` array the values get silently converted to different types (or not). 

``` julia
A =  Any["a" 5; 2//3 1.0]
typeof(A[2,1]) # => Float64
B = Any["a" 5 2//3 1.0]
typeof(B[3]) # => Rational{Int}
C = Any["A" 1//2; 0.5 1]
typeof(C[1,2]) # => Rational{Int}
```

This is the same for untyped array construction. e.g. `["A" 1//2; 0.5 1]`

cc @dpsanders

**Comment by JeffBezanson** [comment] 2016-09-07 18:53
`typed_hvcat` is calling `hcat` internally; it should call `typed_hcat` instead.

**Comment by EdwardMcCants** [comment] 2017-04-11 01:33
I was going to take a look at this as a potential first contribution, but I am unable to reproduce the problem in 0.5.2-pre+1

```
A = Any["a" 5; 2//3 1.0]
2×2 Array{Any,2}:
   "a"  5  
 2//3   1.0

typeof(A[2,1])
Rational{Int64}

versioninfo()
Julia Version 0.5.2-pre+1
Commit a6c55c5e50 (2017-03-06 03:59 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.4.0)
  CPU: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, penryn)
``` 
Did this bug already get fixed by other changes?

**Comment by yuyichao** [comment] 2017-04-11 01:54
Fixed by https://github.com/JuliaLang/julia/pull/18398. The pull request wasn't using a proper reference syntax.

**Closed by yuyichao** 2017-04-11 01:54 UTC
Labels: bug
