### ISSUE TITLE
Search Documentation: everywhere `Python function` ???

### ISSUE THREAD

**Issue by peter1000** [JuliaLang/julia#11539] opened 2015-06-02 17:58 UTC
http://julia.readthedocs.org/en/latest/search/?q=ext&check_keywords=yes&area=default#

![screenshot from 2015-06-02 14-56-30](https://cloud.githubusercontent.com/assets/6168860/7942931/bfdb1780-0937-11e5-950c-28b9b08f9c3c.png)

**Comment by yuyichao** [comment] 2015-06-02 17:59
Duplicate of #11527

**Closed by yuyichao** 2015-06-02 17:59 UTC
