### ISSUE TITLE
Pkg.update() runs out of memory

### ISSUE THREAD

**Issue by afarah1** [JuliaLang/julia#26467] opened 2018-03-15 00:22 UTC
I have 1GB of RAM, 950MB of it are free. `Pkg.update()` consumes all of it, and then requires some more, and julia is rightfully killed by the OOM killer. This is a real problem on low end boxes, though it would, ofc, be mitigated by using a swapfile. Nevertheless, a relevant (I think) feature request: Reduce memory usage (don't do everything in one go?) or don't fail on exhaustion for `Pkg.update`. 

Steps to reproduce:

1. Install julia 0.3.2 from debian
2. Limit the amount of available memory to roughly 950MB and turn on the OOM killer
3. Run Pkg.add("JuMP"); Pkg.add("GLPKMathProgInterface"); Pkg.add("DataFrames")
4. Run Pkg.update()

I could not test it with the latest version because of [this issue](https://github.com/JuliaOpt/GLPK.jl/issues/50), but I guess it's easy enough to test it with a number of other packages instead of GLPK (I don't know any though, as I don't use julia).

**Comment by ararslan** [comment] 2018-03-15 04:16
Hi @afarah1, thanks for the report. Please note that we don't support system package manager installation, as stated in the README. Relevant excerpt reproduced here:

> Although some system package managers provide Julia, such installations are neither maintained nor endorsed by the Julia project. They may be outdated and/or unmaintained. We recommend you use the official Julia binaries instead.

In particular, Julia v0.3.2 is long past end of life. If you use the official binaries, you'll find that the current version is 0.6.2. Anything prior to 0.6.0 is now unmaintained.

I'm going to close this since nothing will be done regarding issues with Julia 0.3. If you run into this with a recent version, please feel free to file a new issue. Thanks!

**Closed by ararslan** 2018-03-15 04:16 UTC
