### ISSUE TITLE
Another case in type stability in captured variable closure

### ISSUE THREAD

**Issue by Roger-luo** [JuliaLang/julia#34894] opened 2020-02-26 21:20 UTC
I guess this is related to #15276, I found this while debugging a Zygote performance issue of its pullback in a quite complicated case, the following is a simplified version.
It seems the compiler fails to infer the types of the following code and the cause `Cassette` to cause more type inference failure somehow in [AutoPreallocation.jl](https://github.com/oxinabox/AutoPreallocation.jl)...

```julia
using LinearAlgebra
using FillArrays

struct MPS{L}
    tensors::NTuple{L, NTuple{2, Matrix{Float64}}}

    function MPS(bond::Int, l::Int)
        tensors = ntuple(l) do k
            (rand(bond, bond), rand(bond, bond))
        end
        new{l}(tensors)
    end
end

function contract_pullback(op::MPS{L}, configs) where L
    @boundscheck length(configs) == L || error("length of the configuration does not match mps length")
    output = @inbounds op.tensors[1][configs[1]]
    stack = Vector{Matrix{Float64}}(undef, L)
    stack[1] = output
    @inbounds for i in 2:L
        output = *(output, op.tensors[i][configs[i]])
        stack[i] = output
    end
    y = tr(output)

    function back(Δ)
        Δ = Diagonal(Fill(Δ, size(output, 1)))
        for i in L:-1:2
            A, B = stack[i-1], op.tensors[i][configs[i]]
            Δ, grad_tensor = *(Δ, transpose(B)), *(transpose(A), Δ)
            # accum_param(__context__, op.tensors[i][configs[i]], grad_tensor)
        end
        # accum_param(__context__, op.tensors[1][configs[1]], Δ)
        return nothing, nothing
    end
    return y, back
end
```

using `@code_warntype`:

```julia
m = MPS(2, 10)
S = rand(1:2, 10)
_, back = contract_pullback(m, S)

@code_warntype back(1.0)
```

I get

```julia
Variables
  #self#::var"#back#17"{10,MPS{10},Array{Int64,1},Array{Array{
Float64,2},1}}
  Δ@_2::Float64
  @_3::Union{Nothing, Tuple{Int64,Int64}}
  i::Int64
  A::Array{Float64,2}
  B::Array{Float64,2}
  grad_tensor::Any
  output::Union{}
  Δ@_9::Any

Body::Tuple{Nothing,Nothing}
1 ─       (Δ@_9 = Δ@_2)
│         Core.NewvarNode(:(@_3))
│   %3  = Δ@_9::Float64::Float64
│   %4  = Core.getfield(#self#, :output)::Core.Box
│   %5  = Core.isdefined(%4, :contents)::Bool
└──       goto #3 if not %5
2 ─       goto #4
3 ─       Core.NewvarNode(:(output))
└──       output
4 ┄ %10 = Core.getfield(%4, :contents)::Any
│   %11 = Main.size(%10, 1)::Any
│   %12 = Main.Fill(%3, %11)::Fill{Float64,_A,_B} where _B where _A
│         (Δ@_9 = Main.Diagonal(%12))
│   %14 = ($(Expr(:static_parameter, 1)):-1:2)::Core.Compiler.Const(10:-1:2, false)
│         (@_3 = Base.iterate(%14))
│   %16 = (@_3::Core.Compiler.Const((10, 10), false) === nothing)::Core.Compiler.Const(false, false)
│   %17 = Base.not_int(%16)::Core.Compiler.Const(true, false)
└──       goto #7 if not %17
5 ┄ %19 = @_3::Tuple{Int64,Int64}::Tuple{Int64,Int64}
│         (i = Core.getfield(%19, 1))
│   %21 = Core.getfield(%19, 2)::Int64
│   %22 = Core.getfield(#self#, :stack)::Array{Array{Float64,2},1}
│   %23 = (i - 1)::Int64
│   %24 = Base.getindex(%22, %23)::Array{Float64,2}
│   %25 = Core.getfield(#self#, :op)::MPS{10}
│   %26 = Base.getproperty(%25, :tensors)::NTuple{10,Tuple{Array{Float64,2},Array{Float64,2}}}
│   %27 = Base.getindex(%26, i)::Tuple{Array{Float64,2},Array{Float64,2}}
│   %28 = Core.getfield(#self#, :configs)::Array{Int64,1}
│   %29 = Base.getindex(%28, i)::Int64
│   %30 = Base.getindex(%27, %29)::Array{Float64,2}
│         (A = %24)
│         (B = %30)
│   %33 = Δ@_9::Any
│   %34 = Main.transpose(B)::Transpose{Float64,Array{Float64,2}}
│   %35 = (%33 * %34)::Any
│   %36 = Main.transpose(A)::Transpose{Float64,Array{Float64,2}}
│   %37 = (%36 * Δ@_9)::Any
│         (Δ@_9 = %35)
│         (grad_tensor = %37)
│         (@_3 = Base.iterate(%14, %21))
│   %41 = (@_3 === nothing)::Bool
│   %42 = Base.not_int(%41)::Bool
└──       goto #7 if not %42
6 ─       goto #5
7 ┄ %45 = Core.tuple(Main.nothing, Main.nothing)::Core.Compiler.Const((nothing, nothing), false)
└──       return %45
```

It seems I could workaround this type inference issue by splitting these intermediate variables as following

```julia
function contract_pullback_stable(op::MPS{L}, configs) where L
    @boundscheck length(configs) == L || error("length of the configuration does not match mps length")
    output = @inbounds op.tensors[1][configs[1]]
    stack = Vector{Matrix{Float64}}(undef, L)
    stack[1] = output
    @inbounds for i in 2:L
        output = *(output, op.tensors[i][configs[i]])
        stack[i] = output
    end
    y = tr(output)

    function back(Δ)
        # use this which can be correctly inferred
        T1 = op.tensors[1][configs[1]]
        Δ = Diagonal(Fill(Δ, size(T1, 1)))

        A, B = stack[L-1], op.tensors[L][configs[L]]
        Δ, grad_tensor = *(Δ, transpose(B)), *(transpose(A), Δ)

        for i in L-1:-1:2
            A, B = stack[i-1], op.tensors[i][configs[i]]
            Δ, grad_tensor = *(Δ, transpose(B)), *(transpose(A), Δ)
        end
        return nothing, nothing
    end

    return y, back
end
```

It seems the type of `output` is just failed to be inferred as `Matrix{Float64}`, and the typeof `Δ` fails to infer after it is assigned by a new `Matrix{Float64}` inside the loop.  I tried this on both official release of `1.3.1` and `1.5.0-DEV`, see the following for `versioninfo`:

```julia
julia> versioninfo()
Julia Version 1.5.0-DEV.337
Commit 9af0715ab6 (2020-02-24 19:32 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PROJECT = @.
```

For 1.3

```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PROJECT = @.
```

**Comment by vtjnash** [comment] 2024-02-17 00:47
Duplicate of https://github.com/JuliaLang/julia/issues/15276

**Closed by vtjnash** 2024-02-17 00:47 UTC
